Repository enso-org/enso, pull requests merged in 2018-10, with the labels that each got.

#291 Standard library parts of LQuery support for Arrow's Timestamp datatype.
  stdlib/Std/src/Base.luna
  stdlib/Std/src/Time.luna
Labels: C - Compiler, C - Libraries, D - Core Contributor, P - High, T - Enhancement, T - Non-Breaking Change

#293 New parser fixes
  core/src/Luna/IR/Term/Ast/Invalid.hs
  lib/parser-utils/src/Text/Parser/State/Indent.hs
  syntax/text/parser2/src/Luna/Syntax/Text/Parser/Ast/Class.hs
  syntax/text/parser2/src/Luna/Syntax/Text/Parser/Hardcoded.hs
  syntax/text/parser2/src/Luna/Syntax/Text/Parser/Lexer/Grammar.hs
  syntax/text/parser2/src/Luna/Syntax/Text/Parser/Parser/Class.hs
  syntax/text/parser2/test/spec/Luna/Test/Source/Text/ParserSpec.hs
Labels: C - Compiler, C - Syntax, D - Core Contributor, Overdue, P - Critical, T - Breaking Change, T - Enhancement

#299 Run tests after build
  .circleci/config.yml
  shell/src/Luna/Shell/Command.hs
Labels: C - External, D - Core Contributor, P - High, T - Enhancement, T - Non-Breaking Change

#311 Hack previous parser behaviour for AccSection
  syntax/text/parser3/src/Luna/Pass/Parsing/Parser.hs
  syntax/text/parser3/test/spec/Luna/Test/Source/Text/ParserSpec.hs
Labels: C - Compiler, C - Syntax, D - Core Contributor, P - High, T - Breaking Change, T - Bug

#324 Fix Package Renaming + Add Rename Command
  package/src/Luna/Package.hs
  package/src/Luna/Package/Utilities.hs
  package/test/spec/Luna/PackageSpec.hs
  shell/src/Luna/Shell/Command.hs
  shell/src/Luna/Shell/Option.hs
Labels: C - Tooling, D - Core Contributor, T - Bug, T - Non-Breaking Change

#327 Repo cleanup
  debug/package.yaml
  passes/package.yaml
  stack-local.yaml
  stack.yaml
  syntax/text/builder/package.yaml
  syntax/text/builder/src/Luna/Pass/Parsing/Parser.hs
  syntax/text/builder/test/spec/Luna/Test/Source/Text/ParserSpec.hs
  syntax/text/builder/test/spec/Main.hs
  syntax/text/builder/test/spec/Spec.hs
  syntax/text/parser/package.yaml
  syntax/text/parser/src-libs/Data/Attoparsec/List.hs
  syntax/text/parser/src-libs/Text/Parser/Combinators.hs
  syntax/text/parser/src/Luna/Syntax/Text/Parser/Ast.hs
  syntax/text/parser/src/Luna/Syntax/Text/Parser/Ast/Class.hs
  syntax/text/parser/src/Luna/Syntax/Text/Parser/Ast/CodeSpan.hs
  syntax/text/parser/src/Luna/Syntax/Text/Parser/Ast/Simple.hs
  syntax/text/parser/src/Luna/Syntax/Text/Parser/Ast/Spanned.hs
  syntax/text/parser/src/Luna/Syntax/Text/Parser/Hardcoded.hs
  syntax/text/parser/src/Luna/Syntax/Text/Parser/Lexer.hs
  syntax/text/parser/src/Luna/Syntax/Text/Parser/Lexer/Grammar.hs
  syntax/text/parser/src/Luna/Syntax/Text/Parser/Lexer/Names.hs
  syntax/text/parser/src/Luna/Syntax/Text/Parser/Parser.hs
  syntax/text/parser/src/Luna/Syntax/Text/Parser/Parser/Class.hs
  syntax/text/parser/src/Luna/Syntax/Text/Parser/Parser/ExprBuilder.hs
  syntax/text/parser/src/Luna/Syntax/Text/Parser/State/Invalid.hs
  syntax/text/parser/src/Luna/Syntax/Text/Parser/State/LastOffset.hs
  syntax/text/parser/src/Luna/Syntax/Text/Parser/State/Marker.hs
  syntax/text/parser/src/Luna/Syntax/Text/Parser/State/Reserved.hs
  syntax/text/parser/src/Luna/Syntax/Text/Parser/State/Result.hs
  syntax/text/parser/src/Luna/Syntax/Text/Parser/State/TokenStream.hs
  syntax/text/parser/src/Luna/Syntax/Text/Parser/State/Version.hs
  syntax/text/parser/test/bench/Main.hs
  syntax/text/parser/test/spec/Luna/Test/Source/Text/ParserSpec.hs
  syntax/text/parser/test/spec/Main.hs
  syntax/text/parser/test/spec/Spec.hs
  syntax/text/parser3/package.yaml
  syntax/text/prettyprint/package.yaml
Labels: C - External, T - Enhancement, T - Non-Breaking Change

#332 Update Base.luna
  stdlib/Std/src/Base.luna
Labels: C - Libraries
