Repository enso-org/enso, pull requests merged in 2018-09, with the labels that each got.

#277 Fix compilation issue on windows
  package/src/Luna/Package.hs
Labels: C - Compiler, C - Libraries, C - Tooling, D - Core Contributor, P - Critical, T - Bug, T - Enhancement

#273 Lquery Integration
  stdlib/Std/src/Base.luna
Labels: C - Compiler, C - Tooling, D - Core Contributor, P - High, T - Enhancement, T - Non-Breaking Change

#295 fix Std.Base.Binary.take & .drop
  stdlib/src/Luna/Prim/Base.hs
Labels: C - Libraries, P - High, T - Bug

#298 Include all comments in a docstring instead of only the first line
  syntax/text/parser2/src/Luna/Syntax/Text/Parser/Ast/Spanned.hs
  syntax/text/parser2/src/Luna/Syntax/Text/Parser/Parser/Class.hs
Labels: C - Compiler, C - Documentation, D - Core Contributor, P - High, T - Enhancement, T - Non-Breaking Change
