Repository enso-org/enso, pull requests merged in 2018-02, with the labels that each got.

#112 Make visualizations work with arbitrary-sized graphs
  core/package.yaml
  core/src-libs/Luna/Test/IR/Runner.hs
  core/src/OCI/IR/Repr/Vis.hs
Labels: C - Tooling, D - Core Contributor, P - High, S - In Progress, T - Non-Breaking Change

#133 Allow pattern matching on literals
  passes/src/Luna/Pass/Evaluation/Interpreter.hs
  stdlib/Std/src/Test.luna
  stdlib/StdTest/src/Lang/PatternMatch.luna
  stdlib/StdTest/src/Main.luna
Labels: C - Compiler, C - Semantics, P - Critical, S - In Progress, T - Breaking Change, T - Enhancement

#121 Add missing stdlib functions
  stdlib/Std/src/Base.luna
  stdlib/src/Luna/Prim/Base.hs
Labels: C - Libraries, D - Core Contributor, P - High, S - In Progress, T - Enhancement, T - Non-Breaking Change

#134 Readme Fixes
  CONTRIBUTING.md
  README.md
Labels: C - Documentation, P - Lowest, S - In Progress, T - Enhancement

#132 Correctly propagate compile errors
  passes/src/Luna/Pass/Evaluation/Interpreter.hs
  passes/src/Luna/Pass/Inference/ErrorPropagation.hs
Labels: C - Compiler, P - Medium, S - In Progress, T - Enhancement, T - Non-Breaking Change

#124 Use async for threads
  core/package.yaml
  core/src/Luna/Builtin/Prim.hs
  passes/src/Luna/Pass/Inference/ErrorPropagation.hs
  stdlib/package.yaml
  stdlib/src/Luna/Prim/Base.hs
  stdlib/src/Luna/Std/Finalizers.hs
Labels: C - Compiler, P - Medium, S - In Progress, T - Non-Breaking Change

#127 Add PATCH support to HTTP client
  stdlib/Std/src/HTTP.luna
Labels: C - Libraries, D - Beginner, P - Medium, S - Help Wanted, S - In Progress, T - Enhancement, T - Non-Breaking Change

#128 Add OPTIONS support to HTTP client
  stdlib/Std/src/HTTP.luna
Labels: C - Libraries, P - Medium, S - In Progress, T - Enhancement, T - Non-Breaking Change

#129 Add HEAD support to HTTP client
  stdlib/Std/src/HTTP.luna
Labels: C - Libraries, P - Medium, S - In Progress, T - Enhancement, T - Non-Breaking Change

#130 Add TRACE support to HTTP client
  stdlib/Std/src/HTTP.luna
Labels: C - Libraries, P - Medium, S - In Progress, T - Enhancement, T - Non-Breaking Change

#131 Add CONNECT support to HTTP client
  stdlib/Std/src/HTTP.luna
Labels: C - Libraries, P - Medium, S - In Progress, T - Enhancement, T - Non-Breaking Change

#136 Fixes deprecation warnings
  core/src-libs/Luna/Test/Utils.hs
  core/src/Luna/IR/Analysis.hs
  core/src/Luna/IR/ToRefactor.hs
  core/src/OCI/IR/Combinators.hs
  core/src/OCI/Pass/Definition.hs
  stdlib/src/Luna/Prim/Time.hs
  stdlib/src/Luna/Std/Builder.hs
Labels: C - Compiler, D - Beginner, P - Lowest, T - Enhancement, T - Non-Breaking Change
