Repository enso-org/enso, pull requests merged in 2018-04, with the labels that each got.

#197 Small Project Structure Refactor
  debug/depvis/overview.sh
  debug/depvis/package.yaml
  debug/depvis/src/Main.hs
  debug/depvis/stack.yaml
Labels: C - Documentation, C - Tooling, P - Lowest, T - Enhancement

#195 Report errors for malformed pattern matches
  core/src-libs/Data/Event.hs
  core/src-libs/Data/Graph/Class.hs
  passes/src/Luna/Pass/Inference/StructuralTyping.hs
  passes/src/Luna/Pass/Resolution/ConstructorResolution.hs
  passes/src/Luna/Pass/Resolution/Data/ImportError.hs
  passes/src/Luna/Pass/Resolution/DeconstructorResolution.hs
Labels: C - Compiler, C - Type System, D - Core Contributor, P - Medium, T - Fixed

#198 Rename Luna build script in preparation for Luna Build.
  build_luna
Labels: C - Tooling, P - Critical, T - Enhancement

#193 Improvements to lunac
  shell/package.yaml
  shell/src/Luna/Shell.hs
Labels: C - Compiler, C - Tooling, T - Enhancement
