Repository enso-org/enso, pull requests merged in 2018-03, with the labels that each got.

#158 Updated Stack Configuration to Centralise Dependency Management
  CONTRIBUTING.md
  README.md
  build
  build_config/luna-snapshot-local.yaml
  build_config/luna-snapshot.yaml
  build_config/stack-local.yaml
  build_config/stack_build.py
  build_config/utils.py
  circle.yml
  core/stack-develop.yaml
  core/stack.yaml
  passes/package.yaml
  passes/stack-develop.yaml
  passes/stack.yaml
  project/package.yaml
  project/stack-develop.yaml
  project/stack.yaml
  shell/package.yaml
  shell/stack-develop.yaml
  shell/stack.yaml
  stack.yaml
  stdlib/package.yaml
  syntax/text/lexer/package.yaml
  syntax/text/lexer/stack-develop.yaml
  syntax/text/lexer/stack.yaml
  syntax/text/parser/package.yaml
  syntax/text/parser/stack-develop.yaml
  syntax/text/parser/stack.yaml
Labels: C - Tooling, P - Low, T - Enhancement, T - Non-Breaking Change

#160 Resolve local dependencies from local_libs directory
  project/package.yaml
  project/src/Luna/Project.hs
  shell/src/Luna/Shell.hs
Labels: C - Compiler, D - Core Contributor, P - High, S - In Progress, T - Non-Breaking Change

#176 Update Text API in WebSockets client
  stdlib/Std/src/WebSockets.luna
Labels: C - Libraries, D - Beginner, P - High, T - Bug, T - Non-Breaking Change

#157 Fix the definition of HTTP HEAD method.
  stdlib/Std/src/HTTP.luna
Labels: C - Libraries, D - Beginner, P - Low, T - Bug, T - Non-Breaking Change

#156 Add toBinary method on JSON
  stdlib/Std/src/Base.luna
Labels: C - Libraries, D - Beginner, P - Low, T - Enhancement, T - Non-Breaking Change

#177 Use Scientific instead of Real inside JSONs
  stdlib/Std/src/Base.luna
  stdlib/src/Luna/Prim/Base.hs
Labels: C - Libraries, T - Breaking Change, T - Enhancement

#178 Fix local bin path
  stack.yaml
Labels: C - Tooling, D - Beginner, T - Bug, T - Fixed

#161 Add a way to access HTTP response headers
  stdlib/Std/src/HTTP.luna
  stdlib/src/Luna/Prim/HTTP.hs
Labels: C - Libraries, T - Breaking Change

#180 Implement FFI Syntax for Luna
  core/src/Luna/IR.hs
  core/src/Luna/IR/Expr.hs
  core/src/Luna/IR/Format2.hs
  core/src/Luna/IR/Term.hs
  core/src/Luna/IR/Term/Uni.hs
  core/src/Luna/IR/Term/Unit.hs
  syntax/text/lexer/src/Luna/Syntax/Text/Lexer/Symbol.hs
  syntax/text/parser/src-libs/Text/Parser/Combinators.hs
  syntax/text/parser/src/Luna/Syntax/Text/Parser/Parsing.hs
  syntax/text/parser/src/Luna/Syntax/Text/Pretty/Pretty.hs
  syntax/text/parser/test/spec/Luna/Test/Source/Text/ParserSpec.hs
Labels: C - Compiler, C - Syntax, D - Core Contributor, T - Enhancement, T - Non-Breaking Change

#181 Initial C FFI implementation
  core/src/Luna/Builtin/Prim.hs
  project/src/Luna/Compilation.hs
  stdlib/Std/src/Base.luna
  stdlib/Std/src/Foreign.luna
  stdlib/Std/src/Foreign/C/Value.luna
  stdlib/package.yaml
  stdlib/src/Luna/Prim/Base.hs
  stdlib/src/Luna/Prim/CTypes.hs
  stdlib/src/Luna/Prim/DynamicLinker.hs
  stdlib/src/Luna/Prim/Foreign.hs
  stdlib/src/Luna/Std.hs
Labels: C - Compiler, C - Libraries, D - Core Contributor, P - High, T - Enhancement, T - Non-Breaking Change

#186 Comment Overhaul
  syntax/text/lexer/src/Luna/Syntax/Text/Lexer/Grammar.hs
  syntax/text/parser/src/Luna/Syntax/Text/Pretty/Pretty.hs
  syntax/text/parser/test/spec/Luna/Test/Source/Text/ParserSpec.hs
Labels: C - Compiler, C - Syntax, P - High, T - Breaking Change, T - Enhancement

#187 Convert Stdlib to New Comment Syntax
  stdlib/Std/src/Base.luna
  stdlib/Std/src/HTTP.luna
  stdlib/Std/src/OAuth.luna
  stdlib/Std/src/System.luna
  stdlib/Std/src/Time.luna
  stdlib/Std/src/WebSockets.luna
Labels: C - Libraries, C - Syntax, P - Critical, T - Bug, T - Non-Breaking Change

#189 Managed pointers
  stdlib/Std/src/Foreign/C/Value.luna
  stdlib/src/Luna/Prim/Foreign.hs
  stdlib/src/Luna/Std.hs
Labels: C - Libraries, D - Core Contributor, P - Medium, T - Enhancement, T - Non-Breaking Change

#188 Add helper class for dealing with C arrays
  stdlib/Std/src/Foreign/C/Value.luna
Labels: C - Libraries, P - Medium, T - Enhancement, T - Fixed, T - Non-Breaking Change

#190 Add int accessors for JSON objects
  stdlib/Std/src/Base.luna
Labels: C - Libraries, P - Medium, T - Enhancement, T - Fixed, T - Non-Breaking Change

#192 Proper resolution of projects in local_libs
  project/src/Luna/Compilation.hs
  project/src/Luna/Project.hs
  shell/src/Luna/Shell.hs
Labels: C - Compiler, C - Libraries, C - Tooling, D - Core Contributor, T - Enhancement
