Repository enso-org/enso, pull requests merged in 2019-03, with the labels that each got.

#378 Remove Benchmarking Library
  config/snapshot.yaml
  lib/benchmark/package.yaml
  lib/benchmark/src/Luna/Benchmark.hs
  lib/benchmark/src/Luna/Benchmark/Config.hs
  lib/benchmark/src/Luna/Benchmark/Internal.hs
  lib/benchmark/src/Luna/Benchmark/Location.hs
  lib/benchmark/src/Luna/Benchmark/Output.hs
  lib/benchmark/src/Luna/Benchmark/SrcLoc.hs
  lib/benchmark/src/Luna/Benchmark/State.hs
  lib/benchmark/src/Luna/Benchmark/Statistics.hs
  lib/benchmark/src/Luna/Benchmark/Statistics/Comparison.hs
  lib/benchmark/src/Luna/Benchmark/Statistics/Comparison/Orphans.hs
  lib/benchmark/src/Luna/Benchmark/Statistics/Internal.hs
  lib/benchmark/test/spec/Luna/Benchmark/StatisticsSpec.hs
  lib/benchmark/test/spec/Main.hs
  lib/benchmark/test/spec/Spec.hs
  shell/package.yaml
  stack.yaml
Labels: C - External, C - Libraries, D - Core Contributor, P - High, T - Enhancement, T - Non-Breaking Change

#379 Improve docs for Std library [WIP]
  stdlib/Std/src/Base.luna
  stdlib/Std/src/Geo.luna
  stdlib/Std/src/HTTP.luna
  stdlib/Std/src/OAuth.luna
  stdlib/Std/src/System.luna
  stdlib/Std/src/Time.luna
  stdlib/Std/src/WebSockets.luna
Labels: C - External, D - Core Contributor, P - High, T - Enhancement, T - Non-Breaking Change

#381 Document the luna-datafile Library
  lib/datafile/src/Luna/Datafile.hs
  lib/datafile/src/Luna/Datafile/Licenses.hs
  lib/datafile/src/Luna/Datafile/Stdlib.hs
Labels: C - Libraries, D - Core Contributor, P - Lowest, T - Enhancement, T - Non-Breaking Change

#380 Package Build Script
  .ci/azure-pipelines.yml
  build_luna
  build_package.hs
  config/build/stack_build.py
  config/build/utils.py
  lib/prologue/package.yaml
  package/src/Luna/Package.hs
  shell/src/Luna/Shell/Interpret.hs
  stack.yaml
  syntax/text/builder/src/Luna/Pass/Parsing/Parser.hs
Labels: C - External, D - Core Contributor, P - High, T - Enhancement, T - Non-Breaking Change

#383 Add CI status icons to the Luna readme
  README.md
Labels: C - External, D - Core Contributor, P - Lowest, T - Enhancement, T - Non-Breaking Change
