Repository enso-org/enso, pull requests merged in 2019-04, with the labels that each got.

#384 Runtime Design Skeleton
  .ci/azure-pipelines.yml
  doc/design/runtime/runtime.md
  doc/design/syntax/unified-syntax.md
  doc/design/type-system/modules.md
Labels: C - Compiler, C - Documentation, D - Core Contributor, P - High, T - Enhancement, T - Non-Breaking Change

#386 Type-System Principles
  doc/design/runtime/runtime.md
  doc/design/syntax/syntax.md
  doc/design/type-system/type-discipline.md
Labels: C - Compiler, C - Documentation, D - Core Contributor, P - High, T - Enhancement, T - Non-Breaking Change

#392 Update README.md and CONTRIBUTING.md
  .ci/azure-pipelines.yml
  CONTRIBUTING.md
  README.md
Labels: C - Documentation, D - Core Contributor, P - High, T - Enhancement, T - Non-Breaking Change

#395 Prevent CI running twice on Pull Requests
  .ci/azure-pipelines.yml
Labels: C - External, D - Core Contributor, P - Low, T - Enhancement, T - Non-Breaking Change

#391 Docs for Std.Base
  stdlib/Std/src/Base.luna
Labels: C - Documentation, D - Core Contributor, P - Low, T - Enhancement

#394 Library env vars
  package/src/Luna/Package/Environment.hs
  shell/src/Luna/Shell/Interpret.hs
  stdlib/Std/src/Base.luna
  stdlib/src/Luna/Prim/Package.hs
  stdlib/src/Luna/Std.hs
  syntax/text/parser/src/Luna/Syntax/Text/Parser/Hardcoded.hs
Labels: C - Compiler, C - Libraries, D - Core Contributor, P - High, T - Enhancement, T - Non-Breaking Change

#401 code snippets
  stdlib/Std/snippets.yaml
Labels: C - Documentation, D - Core Contributor, P - Medium, T - Enhancement, T - Non-Breaking Change

#400 Add definition order to functions
  passes/src/Luna/Pass/Evaluation/EvaluateUnits.hs
  passes/src/Luna/Pass/Flow/ProcessUnits.hs
  passes/src/Luna/Pass/Preprocess/PreprocessUnit.hs
  passes/src/Luna/Pass/Sourcing/ClassProcessor.hs
  passes/src/Luna/Pass/Sourcing/Data/Def.hs
  passes/src/Luna/Pass/Sourcing/UnitMapper.hs
  passes/src/Luna/Pass/Typing/TypeUnits.hs
Labels: C - Compiler, C - Syntax, C - Tooling, D - Core Contributor, P - High, T - Enhancement, T - Non-Breaking Change

#402 Snippets files
  stdlib/Std/samples/exampleFile.txt
  stdlib/Std/snippets.yaml
  stdlib/Std/src/Base.luna
Labels: Category: Documentation, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement
