Repository enso-org/enso, pull requests merged in 2019-06, with the labels that each got.

#410 Update snippets.yaml
  stdlib/Std/snippets.yaml
Labels: Category: Documentation, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Bug

#412 Make use of Path/Path.IO as much as possible
  config/snapshot.yaml
  lib/datafile/package.yaml
  lib/datafile/src/Luna/Datafile.hs
  lib/datafile/test/spec/Luna/DatafileSpec.hs
  package/package.yaml
  package/src/Luna/Package.hs
  package/src/Luna/Package/Configuration/Global.hs
  package/src/Luna/Package/Configuration/License/Data.hs
  package/src/Luna/Package/Environment.hs
  package/src/Luna/Package/Orphans.hs
  package/src/Luna/Package/Structure/Generate.hs
  package/src/Luna/Package/Structure/Generate/Internal.hs
  package/src/Luna/Package/Structure/Name.hs
  package/src/Luna/Package/Structure/Utilities.hs
  package/src/Luna/Package/Utilities.hs
  package/test/spec/Luna/Package/Structure/GenerateSpec.hs
  package/test/spec/Luna/PackageSpec.hs
  passes/package.yaml
  passes/src/Luna/Pass/Sourcing/UnitLoader.hs
  path/package.yaml
  path/src/Luna/Path/Path.hs
  shell/package.yaml
  shell/src/Luna/Shell/CWD.hs
  shell/src/Luna/Shell/Command.hs
  shell/src/Luna/Shell/GenerateDocumentation.hs
  shell/src/Luna/Shell/Interpret.hs
  stack.yaml
  stdlib/package.yaml
  stdlib/src/Luna/Prim/DynamicLinker.hs
Labels: Category: Libraries, Category: Tooling, Change: Breaking, Difficulty: Intermediate, Priority: Medium, Type: Enhancement

#413 Check and fix whitespaces and line lengths
  lib/datafile/test/spec/Luna/DatafileSpec.hs
  package/src/Luna/Package.hs
  package/src/Luna/Package/Configuration/Global.hs
  package/src/Luna/Package/Configuration/License/Data.hs
  package/src/Luna/Package/Environment.hs
  package/src/Luna/Package/Structure/Generate.hs
  package/src/Luna/Package/Structure/Generate/Internal.hs
  package/src/Luna/Package/Structure/Name.hs
  package/src/Luna/Package/Structure/Utilities.hs
  package/test/spec/Luna/Package/Structure/GenerateSpec.hs
  package/test/spec/Luna/PackageSpec.hs
  passes/src/Luna/Pass/Sourcing/UnitLoader.hs
  path/src/Luna/Path/Path.hs
  shell/src/Luna/Shell/Command.hs
  shell/src/Luna/Shell/GenerateDocumentation.hs
  shell/src/Luna/Shell/Interpret.hs
  stdlib/src/Luna/Prim/DynamicLinker.hs
Labels: Category: Documentation, Change: Non-Breaking, Difficulty: Beginner, Priority: Low, Type: Enhancement

#414 change ./samples directory to ./data/samples
  stdlib/Std/data/samples/exampleFile.txt
  stdlib/Std/snippets.yaml
  stdlib/Std/src/Base.luna
Labels: Category: Documentation, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#415 Update snippets.yaml
  stdlib/Std/snippets.yaml
Labels: Category: Documentation, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Bug
