Repository enso-org/enso, pull requests merged in 2020-08, with the labels that each got.

#1047 Integrate the Scala AST Generation with SBT
  .github/workflows/codeql-analysis.yml
  .github/workflows/scala.yml
  .gitignore
  build.sbt
  docs/CONTRIBUTING.md
  docs/parser/ast.md
  lib/rust/ast/Cargo.toml
  lib/rust/ast/src/ast.rs
  lib/rust/ast/src/generation.rs
  project/EnvironmentCheck.scala
  project/GenerateAST.scala
Labels: Category: Codegen, Change: Non-Breaking, Difficulty: Intermediate, Priority: Highest, Type: Enhancement

#1051 Emit Value Updates Only When There is a Change
  engine/language-server/src/test/scala/org/enso/languageserver/runtime/ContextEventsListenerSpec.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java
  engine/runtime/src/main/java/org/enso/interpreter/instrument/RuntimeCache.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/type/Types.java
  engine/runtime/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime/src/main/scala/org/enso/compiler/context/Changeset.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/CacheInvalidation.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeCacheTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/infrastructure/languageserver/ProjectRenameActionSpec.scala
Labels: Category: Backend, Category: Interpreter, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium

#1040 Generated Flexer Code Structure
  .github/workflows/scala.yml
  .gitignore
  docs/parser/flexer.md
  docs/style-guide/markdown.md
  lib/rust/enso-logger/src/lib.rs
  lib/rust/enso-prelude/src/data.rs
  lib/rust/enso-prelude/src/data/non_empty_vec.rs
  lib/rust/enso-prelude/src/lib.rs
  lib/rust/enso-prelude/src/macros.rs
  lib/rust/enso-prelude/src/option.rs
  lib/rust/enso-prelude/src/vec.rs
  lib/rust/flexer/Cargo.toml
  lib/rust/flexer/src/automata/alphabet.rs
  lib/rust/flexer/src/automata/dfa.rs
  lib/rust/flexer/src/automata/nfa.rs
  lib/rust/flexer/src/automata/pattern.rs
  lib/rust/flexer/src/automata/state.rs
  lib/rust/flexer/src/group.rs
  lib/rust/flexer/src/group/rule.rs
  lib/rust/flexer/src/lib.rs
  lib/rust/flexer/tests/flexer_generated_api_test.rs
  lib/rust/flexer/tests/flexer_lexer_definition_test.rs
  lib/rust/lazy-reader/Cargo.toml
  lib/rust/lazy-reader/src/decoder.rs
  lib/rust/lazy-reader/src/lib.rs
  lib/rust/lexer/definition/src/lexer.rs
  lib/rust/lexer/generation/build.rs
  lib/scala/flexer/src/main/scala/org/enso/flexer/Parser.scala
  lib/scala/flexer/src/main/scala/org/enso/flexer/Reader.scala
  lib/scala/syntax/definition/src/main/scala/org/enso/syntax/text/spec/ParserDefSmall.scala
  lib/scala/syntax/definition/src/main/scala/org/enso/syntax/text/spec/__Parser__.scala
Labels: Category: Syntax, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement

#1053 Update CODEOWNERS
  .github/CODEOWNERS
Labels: Category: Build, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1055 Update Runtime Notifications API
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextEventsListener.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistry.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ExpressionValueUpdate.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/MethodPointer.scala
  engine/language-server/src/test/scala/org/enso/languageserver/runtime/ContextEventsListenerSpec.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledStackJob.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  lib/scala/searcher/src/bench/java/org/enso/searcher/sql/SuggestionsRepoBenchmark.java
  lib/scala/searcher/src/bench/scala/org/enso/searcher/sql/SuggestionRandom.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/SuggestionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlSuggestionsRepo.scala
  lib/scala/searcher/src/test/scala/org/enso/searcher/sql/SuggestionsRepoTest.scala
Labels: Category: Backend, Change: Breaking, Difficulty: Core Contributor, Priority: High, Type: Bug

#1060 Send Method Call Updates After Popping the Frame
  engine/runtime/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java
  engine/runtime/src/main/java/org/enso/interpreter/instrument/MethodCallsCache.java
  engine/runtime/src/main/java/org/enso/interpreter/instrument/RuntimeCache.java
  engine/runtime/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/EditFileCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/PopContextCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/PushContextCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/RecomputeContextCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/Executable.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ExecuteJob.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/UpsertVisualisationJob.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Bug

#1062 Qualified names & uppercase name resolution
  docs/CONTRIBUTING.md
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/AtomBenchmarks.java
  engine/runtime/src/bench/scala/org/enso/interpreter/bench/fixtures/semantic/AtomFixtures.scala
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/atom/QualifiedAccessorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/AtomConstructor.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java
  engine/runtime/src/main/scala/org/enso/compiler/Passes.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstToIr.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstView.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/FreshNameSupply.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/main/scala/org/enso/compiler/data/BindingsMap.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/BindingAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/ComplexType.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/LambdaShorthandToLambda.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/IgnoredBindings.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/MethodDefinitions.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/Patterns.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/SuspendedArguments.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/UppercaseNames.scala
  engine/runtime/src/main/scala/org/enso/compiler/phase/StubIrBuilder.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/CompilerTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/codegen/AstToIrTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/BindingAnalysisTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/DataflowAnalysisTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/GatherDiagnosticsTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/OperatorToFunctionTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/optimise/ApplicationSaturationTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/optimise/LambdaConsolidateTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/UppercaseNamesTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/ConstructorsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/PatternMatchTest.scala
  project/WithDebugCommand.scala
  test/Test/src/Main.enso
  test/Test/src/Names/Definitions.enso
  test/Test/src/Names_Spec.enso
Labels: Category: Compiler, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1057 Fix for release workflow.
  .github/settings.yml
  .github/workflows/release.yml
  .github/workflows/scala.yml
  build.sbt
  distribution/bin/enso.bat
  distribution/bin/project-manager.bat
  docs/distribution/release-policy.md
  project/EnvironmentCheck.scala
  project/GenerateAST.scala
Labels: Category: Tooling, Change: Non-Breaking, Difficulty: Beginner, Priority: Highest, Type: Bug

#1070 New Import Syntax
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstToIr.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/test/resources/TestNonImportedOverloads/src/Main.enso
  engine/runtime/src/test/resources/TestSimpleImports/src/Main.enso
  engine/runtime/src/test/resources/Test_Hiding_Error/src/Main.enso
  engine/runtime/src/test/resources/Test_Hiding_Success/src/Main.enso
  engine/runtime/src/test/scala/org/enso/compiler/test/codegen/AstToIrTest.scala
  lib/scala/syntax/definition/src/main/scala/org/enso/syntax/text/ast/meta/Builtin.scala
  test/Test/src/Import_Loop/A.enso
  test/Test/src/Names_Spec.enso
Labels: Category: Syntax, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1068 Handle TailCallException in Runtime Instrument
  engine/runtime/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java
  engine/runtime/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
Labels: Category: Backend, Category: Interpreter, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Bug

#1074 Remove Duplicate Suggestion Entry Id in Doc
  docs/language-server/protocol-language-server.md
Labels: Category: Documentation, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Bug

#1058 Allow Defining Lexers in the Flexer
  .gitignore
  Cargo.toml
  docs/parser/flexer.md
  lib/rust/enso-logger/Cargo.toml
  lib/rust/enso-logger/src/enabled.rs
  lib/rust/enso-prelude/src/vec.rs
  lib/rust/flexer-testing/definition/Cargo.toml
  lib/rust/flexer-testing/definition/src/lib.rs
  lib/rust/flexer-testing/generation/Cargo.toml
  lib/rust/flexer-testing/generation/build.rs
  lib/rust/flexer-testing/generation/src/generated.rs
  lib/rust/flexer-testing/generation/src/lib.rs
  lib/rust/flexer-testing/generation/tests/test_generated_lexer.rs
  lib/rust/flexer/Cargo.toml
  lib/rust/flexer/src/automata/alphabet.rs
  lib/rust/flexer/src/automata/dfa.rs
  lib/rust/flexer/src/automata/nfa.rs
  lib/rust/flexer/src/automata/pattern.rs
  lib/rust/flexer/src/automata/pattern/macros.rs
  lib/rust/flexer/src/automata/state.rs
  lib/rust/flexer/src/automata/symbol.rs
  lib/rust/flexer/src/data/matrix.rs
  lib/rust/flexer/src/generate.rs
  lib/rust/flexer/src/group.rs
  lib/rust/flexer/src/group/rule.rs
  lib/rust/flexer/src/lib.rs
  lib/rust/flexer/tests/flexer_generated_api_test.rs
  lib/rust/flexer/tests/flexer_lexer_definition_test.rs
  lib/rust/flexer/tests/test_invalid_definitions.rs
  lib/rust/lazy-reader/Cargo.toml
  lib/rust/lazy-reader/src/lib.rs
  lib/rust/lexer/definition/Cargo.toml
  lib/rust/lexer/definition/src/lexer.rs
  lib/rust/lexer/definition/src/lib.rs
  lib/rust/lexer/generation/Cargo.toml
  lib/rust/lexer/generation/build.rs
  lib/rust/lexer/generation/src/lexer.rs
  lib/rust/lexer/generation/src/lib.rs
  lib/rust/lexer/tests/Cargo.toml
  lib/rust/lexer/tests/src/main.rs
  lib/scala/flexer/src/main/scala/org/enso/flexer/Spec.scala
  lib/scala/syntax/definition/src/main/scala/org/enso/syntax/text/spec/ParserDefSmall.scala
  lib/scala/syntax/definition/src/main/scala/org/enso/syntax/text/spec/__Parser__.scala
Labels: Category: Syntax, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1081 Fix a bug in error pattern matching
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/CaseNode.java
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/ErrorsTest.scala
Labels: Category: Interpreter, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Bug

#1065 Stub Out the Parser Interface
  Cargo.toml
  build.sbt
  docs/distribution/distribution.md
  docs/infrastructure/rust.md
  docs/parser/jvm-object-generation.md
  lib/rust/parser/Cargo.toml
  lib/rust/parser/src/jni.rs
  lib/rust/parser/src/lib.rs
  lib/scala/parser/src/main/scala/org/enso/parser/Parser.scala
  lib/scala/parser/src/test/scala/org/enso/parser/ParserTest.scala
  project/Cargo.scala
  project/EnvironmentCheck.scala
  project/GenerateAST.scala
Labels: Category: Syntax, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1083 Return Error When the Method Pointer Not Found
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Context.java
  engine/runtime/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime/src/main/java/org/enso/interpreter/service/error/ConstructorNotFoundException.java
  engine/runtime/src/main/java/org/enso/interpreter/service/error/MethodNotFoundException.java
  engine/runtime/src/main/java/org/enso/interpreter/service/error/ModuleNotFoundException.java
  engine/runtime/src/main/java/org/enso/interpreter/service/error/ServiceException.java
  engine/runtime/src/main/java/org/enso/interpreter/service/error/SourceNotFoundException.java
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/RenameProjectCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
Labels: Category: Interpreter, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Bug

#1086 Imports, Exports, and Modules documentation
  docs/semantics/modules.md
  docs/syntax/imports.md
Labels: Category: Documentation, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1084 Fix Method Pointer Update Notifications
  engine/runtime/src/main/java/org/enso/interpreter/instrument/MethodCallsCache.java
  engine/runtime/src/main/java/org/enso/interpreter/instrument/RuntimeCache.java
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
Labels: Category: Interpreter, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Bug

#1088 Information about visualization directory in package structure
  docs/distribution/packaging.md
  docs/infrastructure/rust.md
Labels: Category: Documentation, Change: Non-Breaking, Difficulty: Beginner, Priority: Medium, Type: Discussion, Type: Enhancement

#1087 Add DISABLE_PARALLEL_EXECUTION runtime option
  engine/polyglot-api/src/main/java/org/enso/polyglot/RuntimeOptions.java
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/CommandExecutionEngine.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/JobExecutionEngine.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ExecuteJob.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
Labels: Category: Interpreter, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Low, Type: Enhancement

#1089 Launcher Uninstallation
  build.sbt
  engine/launcher/src/main/scala/org/enso/launcher/FileSystem.scala
  engine/launcher/src/main/scala/org/enso/launcher/GlobalConfigurationManager.scala
  engine/launcher/src/main/scala/org/enso/launcher/cli/InternalOpts.scala
  engine/launcher/src/main/scala/org/enso/launcher/cli/Main.scala
  engine/launcher/src/main/scala/org/enso/launcher/installation/DistributionUninstaller.scala
  engine/launcher/src/test/scala/org/enso/launcher/NativeTest.scala
  engine/launcher/src/test/scala/org/enso/launcher/installation/InstallerSpec.scala
  engine/launcher/src/test/scala/org/enso/launcher/installation/UninstallerSpec.scala
  lib/scala/cli/src/main/scala/org/enso/cli/Command.scala
  lib/scala/cli/src/main/scala/org/enso/cli/Opts.scala
  lib/scala/cli/src/main/scala/org/enso/cli/internal/SubcommandOpt.scala
  lib/scala/cli/src/test/scala/org/enso/cli/OptsSpec.scala
  project/EnvironmentCheck.scala
Labels: Category: Tooling, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1093 Resolve `here` References when Building Suggestions
  engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/CompilerTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/context/SuggestionBuilderTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Bug

#1095 Module re-exports
  docs/semantics/modules.md
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/Passes.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstToIr.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/main/scala/org/enso/compiler/data/BindingsMap.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/DocumentationComments.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/ModuleThisToHere.scala
  engine/runtime/src/main/scala/org/enso/compiler/phase/ExportsResolution.scala
  engine/runtime/src/main/scala/org/enso/compiler/phase/ImportResolver.scala
  engine/runtime/src/main/scala/org/enso/compiler/phase/StubIrBuilder.scala
  engine/runtime/src/test/resources/Cycle_Test/package.yaml
  engine/runtime/src/test/resources/Cycle_Test/src/Main.enso
  engine/runtime/src/test/resources/Cycle_Test/src/Sub/A.enso
  engine/runtime/src/test/resources/Cycle_Test/src/Sub/B.enso
  engine/runtime/src/test/resources/Cycle_Test/src/Sub/C.enso
  engine/runtime/src/test/resources/Cycle_Test/src/Sub/Imp.enso
  engine/runtime/src/test/scala/org/enso/compiler/test/CompilerTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/PassesTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/codegen/AstToIrTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/GatherDiagnosticsTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/ModuleThisToHereTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/UppercaseNamesTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/ImportsTest.scala
  lib/scala/syntax/definition/src/main/scala/org/enso/syntax/text/AST.scala
  lib/scala/syntax/definition/src/main/scala/org/enso/syntax/text/ast/meta/Builtin.scala
  test/Test/src/Deep_Export/Internal.enso
  test/Test/src/Deep_Export/Internal_1.enso
  test/Test/src/Deep_Export/Internal_2.enso
  test/Test/src/Deep_Export/Internal_3.enso
  test/Test/src/Deep_Export/Internal_4.enso
  test/Test/src/Deep_Export/Internal_5.enso
  test/Test/src/Deep_Export_Spec.enso
  test/Test/src/Main.enso
Labels: Category: Interpreter, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1107 Add Trace Logging to Language Server Boot
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1106 Add Base.Process library
  build.sbt
  distribution/std-lib/Base/src/Process.enso
  distribution/std-lib/Base/src/Process/Exit_Code.enso
  distribution/std-lib/Base/src/System/Platform.enso
  distribution/std-lib/Base/src/Test.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/atom/QualifiedAccessorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/io/PrintErrNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/io/ReadlnNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/system/CreateProcessNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/system/OsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/TextEqualsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Context.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/System.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/AtomConstructor.java
  engine/runtime/src/test/scala/org/enso/interpreter/test/InterpreterTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/SystemProcessTest.scala
  lib/scala/testkit/src/main/scala/org/enso/testkit/OsSpec.scala
  test/Test/src/Main.enso
  test/Test/src/Process_Spec.enso
Labels: Category: Libraries, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement

#1108 Fix SBT Exit During Boot With Code 1
  .github/workflows/release.yml
  .github/workflows/scala.yml
Labels: Category: Build, Difficulty: Core Contributor, Priority: Low, Type: Enhancement

#1109 Partial Implementation of the Enso Lexer
  Cargo.toml
  docs/distribution/packaging.md
  docs/parser/flexer.md
  docs/parser/lexer.md
  docs/parser/operator-resolution.md
  docs/semantics/modules.md
  docs/syntax/naming.md
  engine/runtime/src/test/resources/Cycle_Test/package.yaml
  lib/rust/ast/src/ast.rs
  lib/rust/enso-logger/src/enabled.rs
  lib/rust/enso-optics/Cargo.toml
  lib/rust/enso-prelude/src/data/non_empty_vec.rs
  lib/rust/enso-prelude/src/lib.rs
  lib/rust/flexer-testing/definition/src/lib.rs
  lib/rust/flexer-testing/generation/tests/flexer_generated_lexer.rs
  lib/rust/flexer/src/automata/nfa.rs
  lib/rust/flexer/src/automata/pattern.rs
  lib/rust/flexer/src/automata/symbol.rs
  lib/rust/flexer/src/generate.rs
  lib/rust/flexer/src/group.rs
  lib/rust/flexer/src/lib.rs
  lib/rust/flexer/tests/flexer_invalid_definitions.rs
  lib/rust/lazy-reader/src/decoder.rs
  lib/rust/lazy-reader/src/lib.rs
  lib/rust/lexer/definition/Cargo.toml
  lib/rust/lexer/definition/src/lexer.rs
  lib/rust/lexer/definition/src/lib.rs
  lib/rust/lexer/definition/src/token.rs
  lib/rust/lexer/generation/Cargo.toml
  lib/rust/lexer/generation/build.rs
  lib/rust/lexer/generation/src/generated.rs
  lib/rust/lexer/generation/src/lib.rs
  lib/rust/lexer/generation/tests/enso_lexer.rs
  lib/scala/syntax/definition/src/main/scala/org/enso/syntax/text/spec/ParserDef.scala
Labels: Category: Syntax, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1094 Bump GraalVM Version to 20.2.0
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/workflows/codeql-analysis.yml
  .github/workflows/release.yml
  .github/workflows/rust.yml
  .github/workflows/scala.yml
  build.sbt
  docs/CONTRIBUTING.md
  docs/distribution/packaging.md
  docs/distribution/release-policy.md
  docs/getting-enso.md
  docs/infrastructure/README.md
  docs/infrastructure/native-image.md
  docs/infrastructure/rust.md
  docs/infrastructure/upgrading-graalvm.md
  engine/launcher/src/main/java/org/enso/launcher/workarounds/ReplacementStatics.java
  engine/launcher/src/main/scala/org/enso/launcher/Launcher.scala
  engine/launcher/src/main/scala/org/enso/launcher/workarounds/Unsafe.scala
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/dispatch/LoopingCallOptimiserNode.java
  lib/scala/version-output/src/main/scala/org/enso/version/VersionDescription.scala
  project/NativeImage.scala
Labels: Category: Build, Change: Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1101 Make launched processes inherit streams
  engine/launcher/src/main/scala/org/enso/launcher/components/runner/Command.scala
Labels: Category: Tooling, Change: Non-Breaking, Difficulty: Intermediate, Priority: High, Type: Bug

#1112 Configuration Management in the Launcher
  build.sbt
  docs/distribution/packaging.md
  engine/launcher/src/main/scala/org/enso/launcher/GlobalConfigurationManager.scala
  engine/launcher/src/main/scala/org/enso/launcher/Launcher.scala
  engine/launcher/src/main/scala/org/enso/launcher/cli/Main.scala
  engine/launcher/src/main/scala/org/enso/launcher/components/Manifest.scala
  engine/launcher/src/main/scala/org/enso/launcher/components/runner/Runner.scala
  engine/launcher/src/main/scala/org/enso/launcher/config/DefaultVersion.scala
  engine/launcher/src/main/scala/org/enso/launcher/config/GlobalConfig.scala
  engine/launcher/src/main/scala/org/enso/launcher/config/GlobalConfigurationManager.scala
  engine/launcher/src/main/scala/org/enso/launcher/config/InvalidConfigError.scala
  engine/launcher/src/main/scala/org/enso/launcher/installation/DistributionInstaller.scala
  engine/launcher/src/main/scala/org/enso/launcher/installation/DistributionUninstaller.scala
  engine/launcher/src/main/scala/org/enso/launcher/project/Project.scala
  engine/launcher/src/main/scala/org/enso/launcher/project/ProjectManager.scala
  engine/launcher/src/test/scala/org/enso/launcher/DefaultVersionSpec.scala
  engine/launcher/src/test/scala/org/enso/launcher/components/runner/RunnerSpec.scala
  engine/launcher/src/test/scala/org/enso/launcher/config/GlobalConfigurationManagerSpec.scala
  engine/launcher/src/test/scala/org/enso/launcher/project/ProjectManagerSpec.scala
  lib/scala/pkg/src/main/scala/org/enso/pkg/Config.scala
  lib/scala/pkg/src/main/scala/org/enso/pkg/Package.scala
  lib/scala/pkg/src/main/scala/org/enso/pkg/SemVerJson.scala
  lib/scala/pkg/src/test/scala/org/enso/pkg/ConfigSpec.scala
Labels: Category: Tooling, Change: Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement
