Repository enso-org/enso, pull requests merged in 2020-12, with the labels that each got.

#1311 Add Bitwise Operations on Integer
  distribution/std-lib/Base/src/Data/Number/Extensions.enso
  distribution/std-lib/Base/src/Data/Ordering.enso
  distribution/std-lib/Base/src/Data/Ordering/Sort_Order.enso
  distribution/std-lib/Base/src/Data/Vector.enso
  distribution/std-lib/Base/src/Data/Vector/Sort.enso
  distribution/std-lib/Base/src/Main.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/ApplicationNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/ArrayBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/BooleanBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/BooleanConstructorBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/BranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/BranchSelectedException.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/CaseNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/CatchAllBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/ConstructorBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/DecimalBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/IntegerBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/NumberBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/PolyglotBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/TextBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/BitAndNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/BitNotNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/BitOrNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/BitShiftNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/BitShiftRightNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/BitXorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/BitAndNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/BitNotNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/BitOrNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/BitShiftNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/BitShiftRightNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/BitXorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/utils/BigIntegerOps.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/state/RunStateNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Error.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Number.java
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstToIr.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/optimise/ApplicationSaturation.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/NestedPatternMatchTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/optimise/ApplicationSaturationTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/CodeLocationsTest.scala
  test/Tests/src/Data/Numbers_Spec.enso
  test/Tests/src/Data/Vector_Spec.enso
  test/Tests/src/Main.enso
Labels: Category: Stdlib, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1321 Fix some CI timeouts
  .github/workflows/legal-review.yml
  .github/workflows/release.yml
  .github/workflows/scala.yml
Labels: Category: Build, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1319 Fix Runtime Jobs Scheduling
  engine/runtime/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime/src/main/java/org/enso/interpreter/service/error/FailedToApplyEditsException.java
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/CachePreferenceAnalysis.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/AttachVisualisationCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/EditFileCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/ModifyVisualisationCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/PopContextCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/PushContextCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/RecomputeContextCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/CommandExecutionEngine.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/ExecutionState.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/JobExecutionEngine.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/PendingEdits.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/PendingFileEdits.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/RuntimeContext.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledStackJob.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  lib/scala/text-buffer/src/main/scala/org/enso/text/editing/JavaEditorAdapter.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Bug

#1328 Misc Visualization Fixes
  distribution/std-lib/Base/src/Data/Time/Date.enso
  distribution/std-lib/Base/src/Data/Time/Duration.enso
  distribution/std-lib/Base/src/Data/Time/Locale.enso
  distribution/std-lib/Base/src/Data/Time/Time.enso
  distribution/std-lib/Base/src/Data/Time/Time_Of_Day.enso
  distribution/std-lib/Base/src/Data/Time/Zone.enso
  distribution/std-lib/Base/src/Network/Http/Response.enso
  distribution/std-lib/Base/src/Network/Uri.enso
  distribution/std-lib/Base/src/System/File.enso
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextEventsListener.scala
  engine/language-server/src/test/scala/org/enso/languageserver/runtime/ContextEventsListenerSpec.scala
  engine/runtime/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/VectorLiterals.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/EditFileCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/Locking.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/ReentrantLocking.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  test/Tests/src/Data/Time/Date_Spec.enso
  test/Tests/src/Data/Time/Duration_Spec.enso
  test/Tests/src/Data/Time/Locale_Spec.enso
  test/Tests/src/Data/Time/Time_Of_Day_Spec.enso
  test/Tests/src/Data/Time/Time_Spec.enso
  test/Tests/src/Data/Time/Zone_Spec.enso
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Bug

#1332 Add JSON-RPC Timeout Error
  .github/CODEOWNERS
  docs/language-server/protocol-common.md
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/capability/AcquireCapabilityHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/capability/ReleaseCapabilityHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/executioncontext/CreateHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/executioncontext/DestroyHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/executioncontext/PopHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/executioncontext/PushHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/executioncontext/RecomputeHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/CopyFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/CreateFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/DeleteFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/ExistsFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/InfoFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/ListFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/MoveFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/ReadTextualFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/TreeFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/WriteTextualFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/refactoring/RenameProjectHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/search/CompletionHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/search/GetSuggestionsDatabaseHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/search/GetSuggestionsDatabaseVersionHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/search/ImportHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/search/InvalidateSuggestionsDatabaseHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/session/InitProtocolConnectionHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/text/ApplyEditHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/text/CloseFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/text/OpenFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/text/SaveFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/visualisation/AttachVisualisationHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/visualisation/DetachVisualisationHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/visualisation/ModifyVisualisationHandler.scala
  lib/scala/json-rpc-server/src/main/scala/org/enso/jsonrpc/Protocol.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement

#1338 Cleanup the Runtime Listener
  engine/runtime/src/main/java/org/enso/interpreter/service/ExecutionService.java
Labels: Category: RTS, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Bug

#1344 Don't Suppress Errors When Creating Data Directory
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/data/Config.scala
  engine/language-server/src/test/scala/org/enso/languageserver/runtime/ContextEventsListenerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/SuggestionsHandlerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/binary/BaseBinaryServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/FileManagerTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Low, Type: Enhancement

#1343 Fix EditFileCmd locking
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/EditFileCmd.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Bug

#1346 Finish Logging Service Integration
  build.sbt
  distribution/launcher-manifest.yaml
  docs/distribution/distribution.md
  docs/infrastructure/logging.md
  engine/language-server/src/test/resources/logging.properties
  engine/launcher/src/main/scala/org/enso/launcher/cli/GlobalCLIOptions.scala
  engine/launcher/src/main/scala/org/enso/launcher/cli/LauncherApplication.scala
  engine/launcher/src/main/scala/org/enso/launcher/cli/LauncherLogging.scala
  engine/launcher/src/main/scala/org/enso/launcher/components/LauncherRunner.scala
  engine/launcher/src/main/scala/org/enso/launcher/installation/DistributionInstaller.scala
  engine/launcher/src/main/scala/org/enso/launcher/installation/DistributionUninstaller.scala
  engine/launcher/src/test/resources/logging.properties
  engine/launcher/src/test/resources/org/enso/launcher/components/fake-releases/launcher/enso-0.0.1/enso-launcher-0.0.1-linux-amd64.tar.gz/enso/THIRD-PARTY/test-license.txt
  engine/launcher/src/test/resources/org/enso/launcher/components/fake-releases/launcher/enso-0.0.1/enso-launcher-0.0.1-macos-amd64.tar.gz/enso/THIRD-PARTY/test-license.txt
  engine/launcher/src/test/resources/org/enso/launcher/components/fake-releases/launcher/enso-0.0.1/enso-launcher-0.0.1-windows-amd64.zip/enso/THIRD-PARTY/test-license.txt
  engine/launcher/src/test/resources/org/enso/launcher/components/fake-releases/launcher/enso-0.0.1/launcher-manifest.yaml
  engine/launcher/src/test/scala/org/enso/launcher/upgrade/UpgradeSpec.scala
  lib/scala/logging-service/src/main/scala/org/enso/loggingservice/ColorMode.scala
  lib/scala/logging-service/src/main/scala/org/enso/loggingservice/LogLevel.scala
  lib/scala/logging-service/src/main/scala/org/enso/loggingservice/LoggingServiceManager.scala
  lib/scala/logging-service/src/main/scala/org/enso/loggingservice/LoggingServiceSetupHelper.scala
  lib/scala/logging-service/src/main/scala/org/enso/loggingservice/TestLogger.scala
  lib/scala/logging-service/src/main/scala/org/enso/loggingservice/internal/LoggingSettings.scala
  lib/scala/logging-service/src/main/scala/org/enso/loggingservice/internal/TestMessageQueue.scala
  lib/scala/logging-service/src/main/scala/org/enso/loggingservice/internal/service/ServiceWithActorSystem.scala
  lib/scala/logging-service/src/main/scala/org/enso/loggingservice/internal/service/ThreadProcessingService.scala
  lib/scala/logging-service/src/main/scala/org/enso/loggingservice/printers/FileOutputPrinter.scala
  lib/scala/project-manager/src/main/resources/META-INF/native-image/org/enso/projectmanager/native-image.properties
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/Logging.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/MainModule.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/ProjectManager.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/ExecutorWithUnlimitedPool.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerController.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerDescriptor.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerRegistry.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/protocol/ClientController.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/protocol/ManagerClientControllerFactory.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/LoggingServiceEndpointRequestHandler.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/RequestHandler.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/LoggingServiceDescriptor.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectCreationService.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/versionmanagement/DistributionConfiguration.scala
  lib/scala/project-manager/src/test/resources/logging.properties
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/BaseServerSpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/ProjectManagementOps.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/TestLoggingService.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/LoggingServiceEndpointSpec.scala
  lib/scala/runtime-version-manager-test/src/main/scala/org/enso/runtimeversionmanager/test/DropLogs.scala
  lib/scala/runtime-version-manager-test/src/main/scala/org/enso/runtimeversionmanager/test/RuntimeVersionManagerTest.scala
  lib/scala/runtime-version-manager-test/src/test/resources/logging.properties
  lib/scala/runtime-version-manager-test/src/test/scala/org/enso/runtimeversionmanager/config/GlobalConfigurationManagerSpec.scala
  lib/scala/runtime-version-manager-test/src/test/scala/org/enso/runtimeversionmanager/distributuion/DistributionManagerSpec.scala
  lib/scala/runtime-version-manager-test/src/test/scala/org/enso/runtimeversionmanager/locking/ConcurrencyTest.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/RuntimeVersionManager.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/distribution/DistributionManager.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/runner/Runner.scala
Labels: Category: Tooling, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1349 Vector.sort
  distribution/std-lib/Base/src/Data/Number/Extensions.enso
  distribution/std-lib/Base/src/Data/Ordering.enso
  distribution/std-lib/Base/src/Data/Vector.enso
  distribution/std-lib/Base/src/Data/Vector/Sort.enso
  distribution/std-lib/Base/src/Main.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/MethodResolverNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/mutable/ComparatorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/mutable/CopyNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/mutable/SortNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/CompareToNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/decimal/CompareToNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/CompareToNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/utils/BigIntegerOps.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Error.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Mutable.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Number.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Ordering.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Array.java
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/SuspendedArguments.scala
  std-bits/src/main/java/org/enso/base/Time_Utils.java
  test/Benchmarks/src/Vector.enso
  test/Tests/src/Data/Noise_Spec.enso
  test/Tests/src/Data/Vector_Spec.enso
Labels: Category: Stdlib, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement

#1300 Enso Docs: Fix inline scripts.
  lib/scala/syntax/definition/src/main/scala/org/enso/syntax/text/ast/Doc.scala
  lib/scala/syntax/definition/src/main/scala/org/enso/syntax/text/spec/DocParserDef.scala
Labels: Category: Syntax, Change: Non-Breaking, Difficulty: Intermediate, Priority: High, Size: Small, Type: Enhancement

#1356 Table: maps, zips & more builtins
  distribution/std-lib/Table/src/Data/Column.enso
  table/src/main/java/org/enso/table/data/column/operation/map/MapOpStorage.java
  table/src/main/java/org/enso/table/data/column/operation/map/MapOperation.java
  table/src/main/java/org/enso/table/data/column/operation/map/UnaryMapOperation.java
  table/src/main/java/org/enso/table/data/column/operation/map/numeric/DoubleBooleanOp.java
  table/src/main/java/org/enso/table/data/column/operation/map/numeric/DoubleNumericOp.java
  table/src/main/java/org/enso/table/data/column/operation/map/numeric/LongBooleanOp.java
  table/src/main/java/org/enso/table/data/column/operation/map/numeric/LongNumericOp.java
  table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java
  table/src/main/java/org/enso/table/data/column/storage/DoubleStorage.java
  table/src/main/java/org/enso/table/data/column/storage/LongStorage.java
  table/src/main/java/org/enso/table/data/column/storage/ObjectStorage.java
  table/src/main/java/org/enso/table/data/column/storage/Storage.java
  table/src/main/java/org/enso/table/data/column/storage/StringStorage.java
  table/src/main/java/org/enso/table/error/UnexpectedTypeException.java
  test/Table_Tests/src/Table_Spec.enso
Labels: Category: Stdlib, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1367 Safepoint without invalidation
  engine/runtime/src/main/java/org/enso/interpreter/node/ClosureRootNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/ExecuteCallNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/dispatch/LoopingCallOptimiserNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/ThreadManager.java
Labels: Category: Interpreter, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1363 Macro Preparation
  Cargo.toml
  docs/parser/lexer.md
  docs/parser/macro-resolution.md
  lib/rust/lexer/definition/src/token.rs
  lib/rust/lexer/generation/benches/lexer_bench_sources.rs
  lib/rust/lexer/generation/src/lexer.rs
  lib/rust/lexer/generation/src/lib.rs
  lib/rust/lexer/generation/tests/test_utils.rs
  lib/rust/parser-jni/Cargo.toml
  lib/rust/parser-jni/src/jni.rs
  lib/rust/parser-jni/src/lib.rs
  lib/rust/parser/Cargo.toml
  lib/rust/parser/src/lib.rs
  lib/rust/parser/src/macros.rs
  lib/rust/parser/src/macros/definition.rs
  lib/rust/parser/src/macros/literal.rs
  lib/rust/parser/src/macros/registry.rs
  lib/rust/parser/src/operator.rs
  lib/rust/parser/src/operator/associativity.rs
  lib/rust/parser/src/operator/precedence.rs
  lib/rust/parser/src/parser.rs
Labels: Category: Syntax, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1368 Update Json to_text
  distribution/std-lib/Base/src/Data/Json.enso
  distribution/std-lib/Base/src/Data/Json/Internal.enso
  distribution/std-lib/Base/src/Data/Map.enso
Labels: Category: Stdlib, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1370 Implement LocalReleaseProvider
  docs/distribution/README.md
  docs/distribution/local-repository.md
  engine/launcher/src/main/scala/org/enso/launcher/distribution/DefaultManagers.scala
  lib/scala/cli/src/main/scala/org/enso/cli/task/TaskProgress.scala
  lib/scala/logging-service/src/main/scala/org/enso/loggingservice/TestLogger.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/Cli.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/ProjectManager.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/versionmanagement/DefaultDistributionConfiguration.scala
  lib/scala/runtime-version-manager-test/src/main/scala/org/enso/runtimeversionmanager/test/FakeReleases.scala
  lib/scala/runtime-version-manager-test/src/main/scala/org/enso/runtimeversionmanager/test/RuntimeVersionManagerTest.scala
  lib/scala/runtime-version-manager-test/src/test/scala/org/enso/runtimeversionmanager/components/LocalReleaseProviderSpec.scala
  lib/scala/runtime-version-manager-test/src/test/scala/org/enso/runtimeversionmanager/locking/ThreadSafeFileLockManagerTest.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/FileSystem.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/RuntimeVersionManager.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/distribution/DistributionManager.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/releases/engine/EngineRepository.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/releases/graalvm/GraalCEReleaseProvider.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/releases/local/LocalReleaseProvider.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/releases/testing/FakeReleaseProvider.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/releases/testing/TestArchivePackager.scala
Labels: Category: Distribution, Category: Tooling, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1372 Implement fill_missing
  distribution/std-lib/Table/src/Data/Column.enso
  distribution/std-lib/Table/src/Data/Storage.enso
  table/src/main/java/org/enso/table/data/column/builder/object/BoolBuilder.java
  table/src/main/java/org/enso/table/data/column/builder/object/NumericBuilder.java
  table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java
  table/src/main/java/org/enso/table/data/column/storage/DoubleStorage.java
  table/src/main/java/org/enso/table/data/column/storage/LongStorage.java
  table/src/main/java/org/enso/table/data/column/storage/ObjectStorage.java
  table/src/main/java/org/enso/table/data/column/storage/Storage.java
  table/src/main/java/org/enso/table/data/column/storage/StringStorage.java
  test/Table_Tests/src/Table_Spec.enso
Labels: Category: Libraries, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1345 Runtime Containerisation
  .github/workflows/release.yml
  engine/runner/src/main/scala/org/enso/runner/LanguageServerApp.scala
  engine/runner/src/main/scala/org/enso/runner/Main.scala
  lib/scala/json-rpc-server-test/src/main/scala/org/enso/jsonrpc/test/JsonRpcServerTestKit.scala
  lib/scala/project-manager/src/test/resources/application.conf
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/ProjectManagementOps.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala
  tools/ci/docker/Dockerfile
Labels: Category: Distribution, Difficulty: Intermediate, Priority: Medium, Size: Small, Type: Enhancement

#1373 Release hot fix
  .github/workflows/release.yml
Labels: Category: Distribution, Change: Non-Breaking, Difficulty: Intermediate, Priority: Medium, Size: Small, Type: Bug

#1378 Use Cached Value when Computing Visualizations
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/AttachVisualisationCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/UpsertVisualisationJob.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1377 Fix Logging Service Preventing Normal Shutdown
  lib/scala/logging-service/src/main/scala/org/enso/loggingservice/LoggingServiceAlreadyInitializedException.scala
  lib/scala/logging-service/src/main/scala/org/enso/loggingservice/LoggingServiceManager.scala
  lib/scala/logging-service/src/main/scala/org/enso/loggingservice/LoggingServiceSetupHelper.scala
  lib/scala/logging-service/src/main/scala/org/enso/loggingservice/internal/service/ServiceWithActorSystem.scala
  lib/scala/logging-service/src/main/scala/org/enso/loggingservice/internal/service/ThreadProcessingService.scala
Labels: Category: Tooling, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Bug
