Repository enso-org/enso, pull requests merged in 2020-09, with the labels that each got.

#1114 No Implicit Builtins
  distribution/std-lib/Base/src/List.enso
  distribution/std-lib/Base/src/Main.enso
  distribution/std-lib/Base/src/Process.enso
  distribution/std-lib/Base/src/System/Platform.enso
  distribution/std-lib/Base/src/Test.enso
  engine/runner/src/main/scala/org/enso/runner/Main.scala
  engine/runtime/src/bench/scala/org/enso/interpreter/bench/fixtures/semantic/AtomFixtures.scala
  engine/runtime/src/bench/scala/org/enso/interpreter/bench/fixtures/semantic/RecursionFixtures.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Context.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/TopLevelScope.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/phase/ImportResolver.scala
  engine/runtime/src/test/resources/TestNonImportedOverloads/src/Main.enso
  engine/runtime/src/test/resources/TestNonImportedOverloads/src/Util.enso
  engine/runtime/src/test/resources/TestNonImportedOwnMethods/src/Main.enso
  engine/runtime/src/test/resources/TestNonImportedOwnMethods/src/Util.enso
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/ReplTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/CaseTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/CodeLocationsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/CompileDiagnosticsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/ComplexTypeDefinitionSugarTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/ConstructorsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/CurryingTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/ErrorsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/EvalTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/ExpressionIdTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/FunctionSugarTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/GlobalScopeTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/GroupingTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/InteropTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/LambdaChainingTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/LambdaShorthandArgsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/LambdaTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/MethodsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/NamedArgumentsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/OverloadsResolutionErrorTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/PatternMatchTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/PolyglotTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/SequenceLiteralsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/StateTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/SuspendedArgumentsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/SystemProcessTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/TextTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/ThreadInterruptionTest.scala
  engine/runtime/src/test/scala/org/enso/std/test/BooleanTest.scala
  engine/runtime/src/test/scala/org/enso/std/test/JsonSerializationTest.scala
  engine/runtime/src/test/scala/org/enso/std/test/NumberTest.scala
  lib/scala/pkg/src/main/resources/Main.enso
  test/Test/src/Deep_Export/Internal_5.enso
  tools/ci/Test.enso
Labels: Category: Interpreter, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1116 Use Runner to Create Projects in Launcher
  docs/distribution/launcher-cli.md
  engine/launcher/src/main/scala/org/enso/launcher/Launcher.scala
  engine/launcher/src/main/scala/org/enso/launcher/cli/Main.scala
  engine/launcher/src/main/scala/org/enso/launcher/components/runner/Runner.scala
  engine/launcher/src/main/scala/org/enso/launcher/project/ProjectManager.scala
  engine/launcher/src/test/scala/org/enso/launcher/components/ComponentsManagerTest.scala
  engine/launcher/src/test/scala/org/enso/launcher/components/runner/RunnerSpec.scala
  engine/launcher/src/test/scala/org/enso/launcher/project/ProjectManagerSpec.scala
  engine/runner/src/main/scala/org/enso/runner/Main.scala
  lib/scala/pkg/src/main/scala/org/enso/pkg/Package.scala
Labels: Category: Tooling, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1120 Store Project Manager Metadata in Project Directory
  build.sbt
  lib/scala/json-rpc-server-test/src/main/scala/org/enso/jsonrpc/test/JsonRpcServerTestKit.scala
  lib/scala/project-manager/src/main/resources/application.conf
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/Globals.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/MainModule.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/ProjectManager.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/ZioPlatform.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/configuration.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/control/core/Applicative.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/control/core/ApplicativeFunctionOps.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/control/core/ApplicativeOps.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/control/core/CovariantFlatMap.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/control/core/Traverse.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/control/core/ZioApplicative.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/control/core/ZioCovariantFlatMap.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/control/core/syntax.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/file/BlockingFileSystem.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/file/FileSystem.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/file/FileSystemFailure.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/file/JsonFileStorage.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/repository/MetadataFileStorage.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/repository/ProjectFileRepository.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/repository/ProjectRepository.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/model/ProjectMetadata.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/MoveProjectDirCmd.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectService.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/BaseServerSpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/test/ObservableGenerator.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1122 Misc CI Improvements
  .github/settings.yml
  .github/workflows/docs.yml
  .github/workflows/publish-docs.yml
  .github/workflows/release.yml
  .github/workflows/scala.yml
Labels: Category: Build, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1129 Fix Imports Resolution
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/scala/org/enso/compiler/phase/ImportResolver.scala
Labels: Category: Compiler, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Bug

#1128 Setup Runtime logging
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/util/LogHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/util/Logging.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/ProjectManager.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/util/Logging.scala
Labels: Category: Backend, Category: RTS, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement

#1134 Unbounded Integers
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/MethodResolverNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/AddNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/DivideNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/EqualsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/ModNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/MultiplyNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/NegateNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/SubtractNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/AddNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/DivideNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/EqualsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/ModNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/MultiplyNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/NegateNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/SubtractNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/int64/AddNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/int64/DivideNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/int64/EqualsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/int64/ModNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/int64/MultiplyNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/int64/NegateNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/int64/SubtractNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/utils/BigIntegerOps.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/utils/ToEnsoNumberNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/literal/BigIntegerLiteralNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Number.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/number/EnsoBigInteger.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/type/Types.java
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/ReplTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/MethodsTest.scala
  test/Benchmarks/src/Main.enso
  test/Test/src/Main.enso
  test/Test/src/Numbers/Spec.enso
Labels: Category: Interpreter, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1142 [Documentation] Fix Typo in docs/README
  docs/README.md
Labels: Category: Documentation, Change: Non-Breaking, Difficulty: Beginner, Priority: Highest, Type: Bug

#1139 Fallback for Launcher Upgrades
  .github/workflows/release-update-broken.yml
  .github/workflows/release.yml
  docs/distribution/README.md
  docs/distribution/fallback-launcher-release-infrastructure.md
  docs/distribution/launcher-cli.md
  docs/distribution/release-policy.md
  engine/launcher/src/main/scala/org/enso/launcher/FileSystem.scala
  engine/launcher/src/main/scala/org/enso/launcher/archive/Archive.scala
  engine/launcher/src/main/scala/org/enso/launcher/config/GlobalConfigurationManager.scala
  engine/launcher/src/main/scala/org/enso/launcher/http/HTTPDownload.scala
  engine/launcher/src/main/scala/org/enso/launcher/releases/EnsoRepository.scala
  engine/launcher/src/main/scala/org/enso/launcher/releases/fallback/FallbackReleaseProvider.scala
  engine/launcher/src/main/scala/org/enso/launcher/releases/fallback/SimpleReleaseProviderWithFallback.scala
  engine/launcher/src/main/scala/org/enso/launcher/releases/fallback/staticwebsite/FallbackAsset.scala
  engine/launcher/src/main/scala/org/enso/launcher/releases/fallback/staticwebsite/FallbackManifest.scala
  engine/launcher/src/main/scala/org/enso/launcher/releases/fallback/staticwebsite/FallbackRelease.scala
  engine/launcher/src/main/scala/org/enso/launcher/releases/fallback/staticwebsite/FileStorage.scala
  engine/launcher/src/main/scala/org/enso/launcher/releases/fallback/staticwebsite/FileStorageFallbackReleaseProvider.scala
  engine/launcher/src/main/scala/org/enso/launcher/releases/fallback/staticwebsite/ReleaseList.scala
  engine/launcher/src/main/scala/org/enso/launcher/releases/fallback/staticwebsite/StaticWebsite.scala
  engine/launcher/src/main/scala/org/enso/launcher/releases/fallback/staticwebsite/StaticWebsiteFallbackReleaseProvider.scala
  engine/launcher/src/main/scala/org/enso/launcher/upgrade/LauncherUpgrader.scala
  engine/launcher/src/test/resources/org/enso/launcher/releases/fallback/available/fallback-manifest.yaml
  engine/launcher/src/test/resources/org/enso/launcher/releases/fallback/available/launcher/enso-0.0.0/broken
  engine/launcher/src/test/resources/org/enso/launcher/releases/fallback/available/launcher/enso-0.0.0/data.txt
  engine/launcher/src/test/resources/org/enso/launcher/releases/fallback/available/launcher/enso-0.0.1/data.txt
  engine/launcher/src/test/resources/org/enso/launcher/releases/fallback/available/release-list.json
  engine/launcher/src/test/resources/org/enso/launcher/releases/fallback/unavailable/fallback-manifest.yaml
  engine/launcher/src/test/scala/org/enso/launcher/releases/fallback/FileStorageFallbackReleaseProviderSpec.scala
  engine/launcher/src/test/scala/org/enso/launcher/releases/fallback/SimpleReleaseProviderWithFallbackSpec.scala
  engine/launcher/src/test/scala/org/enso/launcher/releases/fallback/TestFileStorage.scala
  tools/ci/releases/add-release.js
  tools/ci/releases/is-broken.js
  tools/ci/releases/mark-broken.js
Labels: Category: Build, Category: Distribution, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1145 Fix Project Manager Projects Loading
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/repository/ProjectFileRepository.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Bug

#1148 Rename the Int64 Package
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/AbsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/AddNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/DivNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/DivideNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/EqualsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/GreaterNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/GreaterOrEqualNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/LessNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/LessOrEqualNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/ModNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/MultiplyNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/NegateNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/PowNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/SubtractNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/ToDecimalNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Number.java
Labels: Category: Libraries, Change: Non-Breaking, Difficulty: Beginner, Priority: Highest, Type: Enhancement

#1147 Add Locks to the Launcher
  build.sbt
  engine/launcher/src/main/scala/org/enso/launcher/Launcher.scala
  engine/launcher/src/main/scala/org/enso/launcher/cli/InternalOpts.scala
  engine/launcher/src/main/scala/org/enso/launcher/cli/LauncherApplication.scala
  engine/launcher/src/main/scala/org/enso/launcher/cli/Main.scala
  engine/launcher/src/main/scala/org/enso/launcher/cli/PluginManager.scala
  engine/launcher/src/main/scala/org/enso/launcher/components/ComponentsManager.scala
  engine/launcher/src/main/scala/org/enso/launcher/components/Engine.scala
  engine/launcher/src/main/scala/org/enso/launcher/components/Runtime.scala
  engine/launcher/src/main/scala/org/enso/launcher/components/runner/Runner.scala
  engine/launcher/src/main/scala/org/enso/launcher/installation/DistributionInstaller.scala
  engine/launcher/src/main/scala/org/enso/launcher/installation/DistributionManager.scala
  engine/launcher/src/main/scala/org/enso/launcher/installation/DistributionUninstaller.scala
  engine/launcher/src/main/scala/org/enso/launcher/locking/DefaultFileLockManager.scala
  engine/launcher/src/main/scala/org/enso/launcher/locking/DefaultResourceManager.scala
  engine/launcher/src/main/scala/org/enso/launcher/locking/FileLockManager.scala
  engine/launcher/src/main/scala/org/enso/launcher/locking/Lock.scala
  engine/launcher/src/main/scala/org/enso/launcher/locking/LockManager.scala
  engine/launcher/src/main/scala/org/enso/launcher/locking/LockType.scala
  engine/launcher/src/main/scala/org/enso/launcher/locking/Resource.scala
  engine/launcher/src/main/scala/org/enso/launcher/locking/ResourceManager.scala
  engine/launcher/src/main/scala/org/enso/launcher/releases/EnsoRepository.scala
  engine/launcher/src/main/scala/org/enso/launcher/releases/testing/FakeReleaseProvider.scala
  engine/launcher/src/main/scala/org/enso/launcher/upgrade/AnotherUpgradeInProgressError.scala
  engine/launcher/src/main/scala/org/enso/launcher/upgrade/LauncherUpgrader.scala
  engine/launcher/src/test/scala/org/enso/launcher/FakeEnvironment.scala
  engine/launcher/src/test/scala/org/enso/launcher/NativeTest.scala
  engine/launcher/src/test/scala/org/enso/launcher/WithTemporaryDirectory.scala
  engine/launcher/src/test/scala/org/enso/launcher/components/ComponentsManagerTest.scala
  engine/launcher/src/test/scala/org/enso/launcher/components/runner/RunnerSpec.scala
  engine/launcher/src/test/scala/org/enso/launcher/config/GlobalConfigurationManagerSpec.scala
  engine/launcher/src/test/scala/org/enso/launcher/installation/DistributionManagerSpec.scala
  engine/launcher/src/test/scala/org/enso/launcher/installation/InstallerSpec.scala
  engine/launcher/src/test/scala/org/enso/launcher/installation/UninstallerSpec.scala
  engine/launcher/src/test/scala/org/enso/launcher/locking/ConcurrencyTest.scala
  engine/launcher/src/test/scala/org/enso/launcher/locking/TestLocalLockManager.scala
  engine/launcher/src/test/scala/org/enso/launcher/locking/TestLocalResourceManager.scala
  engine/launcher/src/test/scala/org/enso/launcher/locking/TestSynchronizer.scala
  engine/launcher/src/test/scala/org/enso/launcher/project/ProjectManagerSpec.scala
  engine/launcher/src/test/scala/org/enso/launcher/upgrade/UpgradeSpec.scala
  lib/scala/cli/src/main/scala/org/enso/cli/arguments/Application.scala
  lib/scala/cli/src/main/scala/org/enso/cli/arguments/PluginManager.scala
  lib/scala/cli/src/main/scala/org/enso/cli/arguments/TopLevelBehavior.scala
  lib/scala/cli/src/main/scala/org/enso/cli/internal/Parser.scala
  lib/scala/cli/src/main/scala/org/enso/cli/internal/ParserContinuation.scala
  lib/scala/cli/src/main/scala/org/enso/cli/internal/opts/TopLevelCommandsOpt.scala
  lib/scala/cli/src/test/scala/org/enso/cli/ApplicationSpec.scala
Labels: Category: Tooling, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1155 Populate the Suggestions Database with Imported Modules
  build.sbt
  engine/language-server/src/main/resources/application.conf
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/util/Logging.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/SuggestionsHandlerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/Suggestion.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime/src/main/java/org/enso/interpreter/OptionsHelper.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Context.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime/src/main/java/org/enso/interpreter/service/error/FailedToApplyEditsException.java
  engine/runtime/src/main/java/org/enso/interpreter/service/error/ModuleNotFoundForFileException.java
  engine/runtime/src/main/java/org/enso/interpreter/service/error/SourceNotFoundException.java
  engine/runtime/src/main/scala/org/enso/compiler/context/ChangesetBuilder.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/Handler.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/EditFileCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/InvalidateModulesIndexCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledStackJob.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/context/ChangesetBuilderTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/StdlibRuntimeServerTest.scala
  lib/scala/searcher/src/main/resources/reference.conf
  lib/scala/searcher/src/main/scala/org/enso/searcher/FileVersionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/SuggestionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlSuggestionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlVersionsRepo.scala
  lib/scala/searcher/src/test/resources/application.conf
  lib/scala/searcher/src/test/scala/org/enso/searcher/sql/FileVersionsRepoTest.scala
  lib/scala/searcher/src/test/scala/org/enso/searcher/sql/SuggestionsRepoTest.scala
  lib/scala/testkit/src/main/scala/org/enso/testkit/OsSpec.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1159 Disable TCP Offloading on macOS
  .github/workflows/release.yml
  .github/workflows/scala.yml
Labels: Category: Build, Change: Non-Breaking, Difficulty: Beginner, Priority: Highest, Type: Enhancement
