Repository enso-org/enso, pull requests merged in 2020-11, with the labels that each got.

#1240 Update Project Manager Protocol
  docs/language-server/protocol-architecture.md
  docs/language-server/protocol-common.md
  docs/language-server/protocol-project-manager.md
  lib/scala/json-rpc-server/src/main/scala/org/enso/jsonrpc/JsonProtocol.scala
  lib/scala/json-rpc-server/src/main/scala/org/enso/jsonrpc/MessageHandler.scala
  lib/scala/json-rpc-server/src/main/scala/org/enso/jsonrpc/Protocol.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/data/EngineVersion.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/data/MissingComponentAction.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/data/ProgressUnit.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/protocol/ClientController.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/protocol/JsonRpc.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/protocol/ProjectManagementApi.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/NotImplementedHandler.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/ProjectCreateHandler.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/ProjectOpenHandler.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectService.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectServiceApi.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/ProjectManagementOps.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala
Labels: Category: Documentation, Category: Libraries, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1264 Macros Design
  docs/parser/macro-resolution.md
Labels: Category: Documentation, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1268 Simple CSV parser
  .github/workflows/scala.yml
  build.sbt
  distribution/std-lib/Base/src/Data/Json.enso
  distribution/std-lib/Base/src/Data/Map.enso
  distribution/std-lib/Base/src/Data/Text/Extensions.enso
  distribution/std-lib/Base/src/System/File.enso
  distribution/std-lib/Table/THIRD-PARTY/NOTICE
  distribution/std-lib/Table/THIRD-PARTY/com.univocity.univocity-parsers-2.9.0/NOTICES
  distribution/std-lib/Table/THIRD-PARTY/licenses/APACHE2.0
  distribution/std-lib/Table/package.yaml
  distribution/std-lib/Table/src/Io/Csv.enso
  distribution/std-lib/Table/src/Main.enso
  distribution/std-lib/Table/src/Table.enso
  table/src/main/java/org/enso/table/data/column/DoubleStorage.java
  table/src/main/java/org/enso/table/data/column/LongStorage.java
  table/src/main/java/org/enso/table/data/column/Storage.java
  table/src/main/java/org/enso/table/data/column/StringStorage.java
  table/src/main/java/org/enso/table/data/column/builder/PrimInferredStorageBuilder.java
  table/src/main/java/org/enso/table/data/column/builder/StorageBuilder.java
  table/src/main/java/org/enso/table/data/column/builder/StringStorageBuilder.java
  table/src/main/java/org/enso/table/data/table/Column.java
  table/src/main/java/org/enso/table/data/table/Table.java
  table/src/main/java/org/enso/table/format/csv/Parser.java
  test/Table_Tests/data/simple_empty.csv
  test/Table_Tests/data/varied_column.csv
  test/Table_Tests/package.yaml
  test/Table_Tests/src/Main.enso
  test/Table_Tests/src/Table_Spec.enso
  tools/legal-review/std-lib-Table/com.univocity.univocity-parsers-2.9.0/copyright-keep
  tools/legal-review/std-lib-Table/report-state
  tools/legal-review/std-lib-Table/reviewed-licenses/Apache_2
Labels: Category: Stdlib, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1250 Update the Running Enso Section in Contribution Docs
  docs/CONTRIBUTING.md
Labels: Category: Documentation, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement

#1269 Rename Unit to Nothing
  distribution/std-lib/Base/src/Data/Json.enso
  distribution/std-lib/Base/src/Data/Json/Internal.enso
  distribution/std-lib/Base/src/Data/List.enso
  distribution/std-lib/Base/src/Data/Map.enso
  distribution/std-lib/Base/src/Data/Text/Extensions.enso
  distribution/std-lib/Base/src/Data/Vector.enso
  distribution/std-lib/Base/src/Main.enso
  distribution/std-lib/Base/src/Network/Http.enso
  distribution/std-lib/Base/src/Network/Proxy.enso
  distribution/std-lib/Base/src/System/File.enso
  distribution/std-lib/Test/src/Test.enso
  engine/runtime/src/bench/scala/org/enso/interpreter/bench/fixtures/semantic/RecursionFixtures.scala
  engine/runtime/src/main/java/org/enso/interpreter/instrument/ReplDebuggerInstrument.java
  engine/runtime/src/main/java/org/enso/interpreter/node/ExpressionNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/java/AddToClassPathNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/resource/FinalizeNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Context.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  engine/runtime/src/test/resources/TestNonImportedOverloads/src/Main.enso
  engine/runtime/src/test/resources/TestNonImportedOverloads/src/Util.enso
  engine/runtime/src/test/resources/TestNonImportedOwnMethods/src/Main.enso
  engine/runtime/src/test/resources/TestNonImportedOwnMethods/src/Util.enso
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/CodeLocationsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/ConstructorsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/CurryingTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/ErrorsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/ExpressionIdTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/FunctionSugarTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/GlobalScopeTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/LambdaTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/MethodsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/NamedArgumentsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/OverloadsResolutionErrorTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/RuntimeManagementTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/StateTest.scala
  test/Table_Tests/src/Table_Spec.enso
  test/Tests/src/Data/Json_Spec.enso
  test/Tests/src/Data/Vector_Spec.enso
  test/Tests/src/Network/Http_Spec.enso
  test/Tests/src/Semantic/Meta_Spec.enso
Labels: Category: Interpreter, Category: Stdlib, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1267 Make Locking Thread-Safe
  build.sbt
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/SuggestionsHandlerTest.scala
  engine/launcher/src/main/scala/org/enso/launcher/DefaultComponentManager.scala
  engine/launcher/src/main/scala/org/enso/launcher/cli/LauncherApplication.scala
  engine/launcher/src/main/scala/org/enso/launcher/cli/Main.scala
  engine/launcher/src/main/scala/org/enso/launcher/distribution/DefaultManagers.scala
  engine/launcher/src/main/scala/org/enso/launcher/installation/DistributionInstaller.scala
  engine/launcher/src/main/scala/org/enso/launcher/installation/DistributionUninstaller.scala
  engine/launcher/src/main/scala/org/enso/launcher/releases/EnsoRepository.scala
  engine/launcher/src/main/scala/org/enso/launcher/upgrade/LauncherUpgrader.scala
  engine/launcher/src/test/scala/org/enso/launcher/NativeTest.scala
  engine/launcher/src/test/scala/org/enso/launcher/upgrade/UpgradeSpec.scala
  lib/scala/locking-test-helper/src/main/scala/org/enso/runtimeversionmanager/test/Main.scala
  lib/scala/runtime-version-manager-test/src/main/scala/org/enso/runtimeversionmanager/test/NativeTestHelper.scala
  lib/scala/runtime-version-manager-test/src/main/scala/org/enso/runtimeversionmanager/test/TestSynchronizer.scala
  lib/scala/runtime-version-manager-test/src/test/scala/org/enso/runtimeversionmanager/components/RuntimeVersionManagerSpec.scala
  lib/scala/runtime-version-manager-test/src/test/scala/org/enso/runtimeversionmanager/locking/ConcurrencyTest.scala
  lib/scala/runtime-version-manager-test/src/test/scala/org/enso/runtimeversionmanager/locking/ThreadSafeFileLockManagerTest.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/locking/FileLockManager.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/locking/ThreadSafeFileLockManager.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/releases/testing/FakeReleaseProvider.scala
  lib/scala/testkit/src/main/scala/org/enso/testkit/OsSpec.scala
Labels: Category: Tooling, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1271 Fix Storing the Runtime Types
  build.sbt
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/data/ContentBasedVersioning.scala
  engine/language-server/src/main/scala/org/enso/languageserver/data/Sha3_224VersionCalculator.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/text/OpenFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SearchProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/Buffer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/BufferRegistry.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/CollaborativeBuffer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/FileEdit.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/TextApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/TextProtocol.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/Suggestions.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/SuggestionsHandlerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/SuggestionsHandlerEventsTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/Suggestion.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/data/These.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/data/Tree.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/polyglot-api/src/test/scala/org/enso/polyglot/data/TreeTest.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionDiff.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/CommandExecutionEngine.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/JobExecutionEngine.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/RuntimeContext.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/context/ChangesetBuilderTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/context/SuggestionBuilderTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/StdlibRuntimeServerTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/SuggestionUpdatesTest.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/SuggestionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/data/QueryResult.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlSuggestionsRepo.scala
  lib/scala/searcher/src/test/scala/org/enso/searcher/sql/SuggestionsRepoTest.scala
  lib/scala/text-buffer/src/main/scala/org/enso/text/ContentBasedVersioning.scala
  lib/scala/text-buffer/src/main/scala/org/enso/text/ContentVersion.scala
  lib/scala/text-buffer/src/main/scala/org/enso/text/Sha3_224VersionCalculator.scala
  lib/scala/text-buffer/src/test/scala/org/enso/text/Sha3224VersionCalculatorSpec.scala
  tools/legal-review/engine/report-state
Labels: Category: Backend, Change: Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1284 Requested Standard Library Improvements
  distribution/std-lib/Base/src/Data/Json.enso
  distribution/std-lib/Base/src/Data/List.enso
  distribution/std-lib/Base/src/Data/Number/Extensions.enso
  distribution/std-lib/Base/src/Data/Pair.enso
  distribution/std-lib/Base/src/Data/Range.enso
  distribution/std-lib/Base/src/Data/Text/Extensions.enso
  distribution/std-lib/Base/src/Data/Vector.enso
  distribution/std-lib/Base/src/Main.enso
  distribution/std-lib/Base/src/Math.enso
  distribution/std-lib/Table/src/Table.enso
  distribution/std-lib/Test/src/Test.enso
  test/Benchmarks/src/Collections.enso
  test/Benchmarks/src/Text.enso
  test/Tests/src/Data/List_Spec.enso
  test/Tests/src/Data/Numbers_Spec.enso
  test/Tests/src/Data/Range_Spec.enso
  test/Tests/src/Data/Text_Spec.enso
  test/Tests/src/Data/Vector_Spec.enso
  test/Tests/src/Main.enso
Labels: Category: Stdlib, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1288 Enso Docs: Proper indentation in HTML render of code block and `copy` button.
  lib/scala/syntax/definition/src/main/scala/org/enso/syntax/text/ast/Doc.scala
Labels: Category: Syntax, Change: Non-Breaking, Difficulty: Intermediate, Priority: High, Size: Small, Type: Enhancement

#1290 More Standard Library Improvements
  distribution/std-lib/Base/src/Data/Any/Extensions.enso
  distribution/std-lib/Base/src/Data/Json.enso
  distribution/std-lib/Base/src/Data/Json/Internal.enso
  distribution/std-lib/Base/src/Data/List.enso
  distribution/std-lib/Base/src/Data/Map.enso
  distribution/std-lib/Base/src/Data/Range.enso
  distribution/std-lib/Base/src/Data/Text/Extensions.enso
  distribution/std-lib/Base/src/Data/Time/Duration.enso
  distribution/std-lib/Base/src/Data/Time/Locale.enso
  distribution/std-lib/Base/src/Data/Time/Time.enso
  distribution/std-lib/Base/src/Data/Time/Time_Of_Day.enso
  distribution/std-lib/Base/src/Data/Vector.enso
  distribution/std-lib/Base/src/Main.enso
  distribution/std-lib/Base/src/Meta.enso
  distribution/std-lib/Base/src/Network/Http.enso
  distribution/std-lib/Base/src/Network/Http/Form.enso
  distribution/std-lib/Base/src/Network/Http/Request.enso
  distribution/std-lib/Base/src/Network/Http/Response.enso
  distribution/std-lib/Base/src/System/File.enso
  distribution/std-lib/Base/src/System/Process.enso
  distribution/std-lib/Table/src/Table.enso
  engine/polyglot-api/src/main/scala/org/enso/polyglot/data/Tree.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstToIr.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstView.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/main/scala/org/enso/compiler/data/BindingsMap.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/LambdaShorthandToLambda.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/OperatorToFunction.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/SuspendedArguments.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/TypeFunctions.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/UppercaseNames.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/codegen/AstToIrTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/SuspendedArgumentsTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/TypeSignaturesTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/StdlibRuntimeServerTest.scala
  std-bits/src/main/java/org/enso/base/Text_Utils.java
  std-bits/src/main/java/org/enso/base/Time_Utils.java
  test/Tests/src/Data/Json_Spec.enso
  test/Tests/src/Data/List_Spec.enso
  test/Tests/src/Data/Map_Spec.enso
  test/Tests/src/Data/Time/Locale_Spec.enso
  test/Tests/src/Data/Vector_Spec.enso
  test/Tests/src/Main.enso
  test/Tests/src/System/File_Spec.enso
Labels: Category: Stdlib, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1295 Add `Number.noise` and a Required Abstractions
  distribution/std-lib/Base/src/Data/Interval.enso
  distribution/std-lib/Base/src/Data/Interval/Bound.enso
  distribution/std-lib/Base/src/Data/Noise.enso
  distribution/std-lib/Base/src/Data/Noise/Generator.enso
  distribution/std-lib/Base/src/Data/Number/Extensions.enso
  distribution/std-lib/Base/src/Error/Extensions.enso
  distribution/std-lib/Base/src/Main.enso
  distribution/std-lib/Test/src/Test.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/CeilNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/FloorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/decimal/CeilNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/decimal/FloorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/CeilNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/FloorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/utils/BigIntegerOps.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/utils/ToEnsoNumberNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Number.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/number/EnsoBigInteger.java
  lib/scala/syntax/definition/src/main/scala/org/enso/syntax/text/ast/meta/Builtin.scala
  test/Tests/src/Data/Interval_Spec.enso
  test/Tests/src/Data/Noise/Generator_Spec.enso
  test/Tests/src/Data/Noise_Spec.enso
  test/Tests/src/Data/Numbers_Spec.enso
  test/Tests/src/Main.enso
  test/Tests/src/Semantic/Meta_Spec.enso
Labels: Category: Stdlib, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1297 Tables: column mapping & masking
  distribution/std-lib/Base/src/Data/Number/Extensions.enso
  distribution/std-lib/Base/src/Data/Text/Extensions.enso
  distribution/std-lib/Base/src/Main.enso
  distribution/std-lib/Base/src/System/File.enso
  distribution/std-lib/Table/src/Data/Column.enso
  distribution/std-lib/Table/src/Data/Table.enso
  distribution/std-lib/Table/src/Io/Csv.enso
  distribution/std-lib/Table/src/Main.enso
  distribution/std-lib/Table/src/Table.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/syntax/HostValueToEnsoNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/io/GetUserHomeNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/Atom.java
  std-bits/src/main/java/org/enso/base/Text_Utils.java
  table/src/main/java/org/enso/table/data/column/DoubleStorage.java
  table/src/main/java/org/enso/table/data/column/LongStorage.java
  table/src/main/java/org/enso/table/data/column/Storage.java
  table/src/main/java/org/enso/table/data/column/StringStorage.java
  table/src/main/java/org/enso/table/data/column/builder/object/BoolBuilder.java
  table/src/main/java/org/enso/table/data/column/builder/object/Builder.java
  table/src/main/java/org/enso/table/data/column/builder/object/InferredBuilder.java
  table/src/main/java/org/enso/table/data/column/builder/object/NumericBuilder.java
  table/src/main/java/org/enso/table/data/column/builder/object/ObjectBuilder.java
  table/src/main/java/org/enso/table/data/column/builder/object/StringBuilder.java
  table/src/main/java/org/enso/table/data/column/builder/object/TypedBuilder.java
  table/src/main/java/org/enso/table/data/column/builder/string/PrimInferredStorageBuilder.java
  table/src/main/java/org/enso/table/data/column/builder/string/StorageBuilder.java
  table/src/main/java/org/enso/table/data/column/builder/string/StringStorageBuilder.java
  table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java
  table/src/main/java/org/enso/table/data/column/storage/DoubleStorage.java
  table/src/main/java/org/enso/table/data/column/storage/LongStorage.java
  table/src/main/java/org/enso/table/data/column/storage/ObjectStorage.java
  table/src/main/java/org/enso/table/data/column/storage/Storage.java
  table/src/main/java/org/enso/table/data/column/storage/StringStorage.java
  table/src/main/java/org/enso/table/data/table/Column.java
  table/src/main/java/org/enso/table/data/table/Table.java
  table/src/main/java/org/enso/table/error/UnexpectedColumnTypeException.java
  table/src/main/java/org/enso/table/format/csv/Parser.java
  test/Table_Tests/src/Table_Spec.enso
  test/Tests/src/Data/Text_Spec.enso
Labels: Category: Stdlib, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1298 Implement better splitting on text
  distribution/std-lib/Base/src/Data/Text/Extensions.enso
  distribution/std-lib/Base/src/Data/Text/Split_Kind.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/ArrayBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/BooleanBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/BranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/CatchAllBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/ConstructorBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/DecimalBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/IntegerBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/NumberBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/PolyglotBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/TextBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Polyglot.java
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  std-bits/src/main/java/org/enso/base/Text_Utils.java
  test/Tests/src/Data/Text_Spec.enso
  test/Tests/src/Main.enso
  test/Tests/src/Semantic/Case_Spec.enso
Labels: Category: Interpreter, Category: Stdlib, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1302 Allow Splitting on Word Boundaries
  distribution/std-lib/Base/src/Data/Text/Extensions.enso
  distribution/std-lib/Base/src/Data/Text/Split_Kind.enso
  distribution/std-lib/Base/src/Meta.enso
  distribution/std-lib/Test/src/Test.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/BooleanBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/BooleanConstructorBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/IntegerBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/NumberBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/bool/EqualsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/EqualsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/decimal/EqualsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/EqualsNode.java
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  std-bits/src/main/java/org/enso/base/Text_Utils.java
  test/Tests/src/Data/Text_Spec.enso
  test/Tests/src/Semantic/Case_Spec.enso
  test/Tests/src/Semantic/Meta_Spec.enso
Labels: Category: Stdlib, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1306 Introduce Ordering
  distribution/std-lib/Base/src/Data/Any/Extensions.enso
  distribution/std-lib/Base/src/Data/Number/Extensions.enso
  distribution/std-lib/Base/src/Data/Ordering.enso
  distribution/std-lib/Base/src/Data/Text/Extensions.enso
  distribution/std-lib/Base/src/Main.enso
  test/Tests/src/Data/Ordering_Spec.enso
  test/Tests/src/Main.enso
Labels: Category: Stdlib, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1310 Add search/import command
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonRpc.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/search/ImportHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SearchApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SearchFailureMapper.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SearchProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/handler/ImportModuleHandler.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/CommandFactory.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/ImportSuggestionCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledStackJob.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1317 Table: Indexes & Joins
  distribution/std-lib/Base/src/Data/Json.enso
  distribution/std-lib/Base/src/Data/Vector.enso
  distribution/std-lib/Table/src/Data/Column.enso
  distribution/std-lib/Table/src/Data/Table.enso
  distribution/std-lib/Table/src/Main.enso
  table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java
  table/src/main/java/org/enso/table/data/column/storage/DoubleStorage.java
  table/src/main/java/org/enso/table/data/column/storage/LongStorage.java
  table/src/main/java/org/enso/table/data/column/storage/ObjectStorage.java
  table/src/main/java/org/enso/table/data/column/storage/Storage.java
  table/src/main/java/org/enso/table/data/column/storage/StringStorage.java
  table/src/main/java/org/enso/table/data/index/DefaultIndex.java
  table/src/main/java/org/enso/table/data/index/HashIndex.java
  table/src/main/java/org/enso/table/data/index/Index.java
  table/src/main/java/org/enso/table/data/table/Column.java
  table/src/main/java/org/enso/table/data/table/Table.java
  table/src/main/java/org/enso/table/error/NoSuchColumnException.java
  table/src/main/java/org/enso/table/format/csv/Parser.java
  test/Table_Tests/src/Table_Spec.enso
Labels: Category: Stdlib, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement
