Repository enso-org/enso, pull requests merged in 2020-06, with the labels that each got.

#931 Update References to Luna to be Enso
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/docs.yml
  README.md
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
  docs/distribution/README.md
  docs/getting-enso.md
  docs/infrastructure/java-11.md
  docs/rfcs/README.md
  docs/runtime/runtime-features.md
  docs/style-guide/haskell.md
  engine/language-server/src/main/scala/org/enso/languageserver/capability/CapabilityApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/io/InputOutputApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/monitoring/MonitoringApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/ErrorApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ExecutionApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/VisualisationApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/session/SessionApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/TextApi.scala
  lib/project-manager/src/main/resources/application.conf
  lib/project-manager/src/main/scala/org/enso/projectmanager/protocol/ProjectManagementApi.scala
  lib/project-manager/src/test/resources/application.conf
  lib/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala
  parser/flexer/Cargo.toml
  tools/performance/comparative-benchmark/benchmarks/haskell/package.yaml
Labels: Category: Documentation, Change: Non-Breaking, Difficulty: Beginner, Priority: Highest, Type: Enhancement

#934 Bugfix for `text/applyEdit` Reports Trailing Empty Line to be an Invalid Position
  lib/text-buffer/src/main/scala/org/enso/text/buffer/Rope.scala
  lib/text-buffer/src/test/scala/org/enso/text/editing/EditorOpsSpec.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Bug

#936 Initial Parser Docs Setup
  docs/parser/README.md
  docs/parser/architecture.md
  docs/parser/ast.md
  docs/parser/construct-resolution.md
  docs/parser/flexer.md
  docs/parser/jvm-object-generation.md
  docs/parser/lexer.md
  docs/parser/macro-resolution.md
  docs/parser/parser-driver.md
  docs/parser/parser.md
  docs/parser/reader.md
  docs/parser/tech-analysis.md
  parser/flexer/src/automata.rs
  parser/flexer/src/automata/alphabet.rs
  parser/flexer/src/automata/dfa.rs
  parser/flexer/src/automata/nfa.rs
  parser/flexer/src/automata/pattern.rs
  parser/flexer/src/automata/state.rs
  parser/flexer/src/data.rs
  parser/flexer/src/data/matrix.rs
  parser/flexer/src/group.rs
  parser/flexer/src/group/rule.rs
  parser/flexer/src/lib.rs
  parser/flexer/src/parser.rs
Labels: Category: Documentation, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#937 Fix unbalanced parentheses parse error
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstToIr.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstView.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/codegen/AstToIrTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/codegen/MatchersTest.scala
  lib/syntax/definition/src/main/scala/org/enso/syntax/text/AST.scala
Labels: Category: Compiler, Category: Syntax, Change: Non-Breaking, Difficulty: Core Contributor, Difficulty: Intermediate, Priority: High, Type: Bug, Type: Enhancement

#947 Update the Parser Documentation
  docs/parser/README.md
  docs/parser/architecture.md
  docs/parser/ast.md
  docs/parser/construct-resolution.md
  docs/parser/flexer.md
  docs/parser/jvm-object-generation.md
  docs/parser/lexer.md
  docs/parser/macro-resolution.md
  docs/parser/operator-resolution.md
  docs/parser/parser-driver.md
  docs/parser/parser.md
  docs/parser/reader.md
Labels: Category: Documentation, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#930 Implement Suggestions Updates API
  build.sbt
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/capability/CapabilityRouter.scala
  engine/language-server/src/main/scala/org/enso/languageserver/data/Capability.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonRpc.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/SearchApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/SearchProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/SuggestionsDatabaseEventsListener.scala
  engine/language-server/src/main/schema/binary_protocol.fbs
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/SuggestionsDatabaseEventsListenerTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#950 Interpreter Performance Improvements
  engine/runtime/src/main/java/org/enso/interpreter/node/EnsoRootNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/thunk/ThunkExecutorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  engine/runtime/src/test/scala/org/enso/interpreter/test/InterpreterTest.scala
  lib/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/MethodProcessor.java
  lib/text-buffer/src/main/scala/org/enso/text/buffer/CharView.scala
  project/WithDebugCommand.scala
Labels: Category: Interpreter, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#946 Fix documentation metadata getting lost
  build.sbt
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstToIr.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstView.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/ir/DiagnosticStorage.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/ir/MetadataStorage.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/IRPass.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/CachePreferenceAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DataflowAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/GatherDiagnostics.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/TailCall.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/ComplexType.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/FunctionBinding.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/LambdaShorthandToLambda.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/NestedPatternMatch.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/OperatorToFunction.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/lint/ShadowedPatternFields.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/lint/UnusedBindings.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/optimise/ApplicationSaturation.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/optimise/UnreachableMatchBranches.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/DocumentationComments.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/IgnoredBindings.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/TypeSignatures.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/core/ir/MetadataStorageTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/GatherDiagnosticsTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/DocumentationCommentsTest.scala
  lib/json-rpc-server/src/test/scala/org/enso/jsonrpc/MessageHandlerSpec.scala
Labels: Category: Compiler, Category: Syntax, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Bug, Type: Enhancement

#951 Benchmarking Utilities
  distribution/std-lib/Base/src/Bench_Utils.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/runtime/NoInlineNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
Labels: Category: Libraries, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#948 Update SBT and Scalac
  .github/CODEOWNERS
  .github/settings.yml
  .github/workflows/rust.yml
  .github/workflows/scala.yml
  build.sbt
  docs/CONTRIBUTING.md
  docs/SECURITY.md
  engine/language-server/src/main/scala/org/enso/languageserver/effect/Exec.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/CollaborativeBuffer.scala
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/Core.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/PassManager.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/GenerateMethodBodies.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/OperatorToFunction.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/lint/UnusedBindings.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/optimise/LambdaConsolidate.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/OverloadsResolution.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/SuspendedArguments.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/DebuggerMessageHandler.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/Handler.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/JobExecutionEngine.scala
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/scope/LocalScope.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/CompilerTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/PassesTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/context/FreshNameSupplyTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/core/CorePrimTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/core/CoreTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/core/SmartConstructorsTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/AliasAnalysisTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/DemandAnalysisTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/ComplexTypeTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/FunctionBindingTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/GenerateMethodBodiesTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/SectionsToBinOpTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/optimise/ApplicationSaturationTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/optimise/LambdaConsolidateTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/DocumentationCommentsTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/OverloadsResolutionTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/TypeFunctionsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/InterpreterTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/ReplTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  lib/parser-service/src/main/scala/org/enso/parserservice/Server.scala
  lib/project-manager/src/main/scala/org/enso/projectmanager/control/effect/ZioEnvExec.scala
  lib/project-manager/src/test/scala/org/enso/projectmanager/infrastructure/languageserver/StepParent.scala
  lib/searcher/src/main/scala/org/enso/searcher/sql/Tables.scala
  lib/syntax/definition/src/main/scala/org/enso/syntax/text/AST.scala
  lib/syntax/definition/src/main/scala/org/enso/syntax/text/ast/meta/Pattern.scala
  lib/syntax/definition/src/main/scala/org/enso/syntax/text/spec/ParserDef.scala
  lib/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/CommentRemover.scala
  parser/flexer/Cargo.toml
  project/build.properties
  project/plugins.sbt
Labels: Category: Build, Change: Non-Breaking, Difficulty: Beginner, Priority: Highest, Type: Enhancement

#952 Implement Interop Library for Unresolved Symbols
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/UnresolvedSymbol.java
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/InteropTest.scala
Labels: Category: Interpreter, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement
