Repository enso-org/enso, pull requests merged in 2020-10, with the labels that each got.

#1176 Change SBT Links to Direct GitHub Releases Links
  .github/workflows/codeql-analysis.yml
  .github/workflows/release.yml
  .github/workflows/scala.yml
Labels: Category: Build, Change: Non-Breaking, Difficulty: Beginner, Priority: Highest, Type: Enhancement

#1179 Polyglot Import Renaming
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstToIr.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/BindingAnalysis.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/BindingAnalysisTest.scala
  lib/scala/syntax/definition/src/main/scala/org/enso/syntax/text/AST.scala
  lib/scala/syntax/definition/src/main/scala/org/enso/syntax/text/ast/meta/Builtin.scala
  test/Test/src/Java_Interop/Spec.enso
Labels: Category: Syntax, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1173 Fix Logical Leaks in MethodResolverNode
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/MethodResolverNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/state/GetStateNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/state/PutStateNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Error.java
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/ImportsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/MethodsTest.scala
  test/Test/src/Deep_Export/Internal.enso
  test/Test/src/Deep_Export/Internal_1.enso
  test/Test/src/Deep_Export/Internal_2.enso
  test/Test/src/Deep_Export/Internal_3.enso
  test/Test/src/Deep_Export/Internal_4.enso
  test/Test/src/Import_Loop/A.enso
  test/Test/src/Main.enso
  test/Test/src/Semantic/Deep_Export/Internal.enso
  test/Test/src/Semantic/Deep_Export/Internal_1.enso
  test/Test/src/Semantic/Deep_Export/Internal_2.enso
  test/Test/src/Semantic/Deep_Export/Internal_3.enso
  test/Test/src/Semantic/Deep_Export/Internal_4.enso
  test/Test/src/Semantic/Deep_Export/Internal_5.enso
  test/Test/src/Semantic/Deep_Export/Spec.enso
  test/Test/src/Semantic/Error_Spec.enso
  test/Test/src/Semantic/Import_Loop/A.enso
  test/Test/src/Semantic/Import_Loop/B.enso
  test/Test/src/Semantic/Import_Loop/Spec.enso
  test/Test/src/Semantic/Java_Interop_Spec.enso
  test/Test/src/Semantic/Names_Spec.enso
Labels: Category: Interpreter, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1182 Bump the Node LTS Patch Version
  .github/workflows/docs.yml
  .github/workflows/release.yml
  .github/workflows/rust.yml
  .github/workflows/scala.yml
  docs/CONTRIBUTING.md
  engine/launcher/src/test/scala/org/enso/launcher/NativeTest.scala
  engine/launcher/src/test/scala/org/enso/launcher/locking/TestSynchronizer.scala
  engine/launcher/src/test/scala/org/enso/launcher/upgrade/UpgradeSpec.scala
Labels: Category: Build, Change: Non-Breaking, Difficulty: Beginner, Priority: Highest, Type: Enhancement

#1189 Defining methods for operators
  distribution/std-lib/Base/src/Boolean.enso
  distribution/std-lib/Base/src/Main.enso
  distribution/std-lib/Base/src/Maybe.enso
  distribution/std-lib/Base/src/System/Platform.enso
  distribution/std-lib/Base/src/Test.enso
  distribution/std-lib/Base/src/Text/Extensions.enso
  distribution/std-lib/Base/src/Vector.enso
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstToIr.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstView.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/codegen/AstToIrTest.scala
  lib/scala/syntax/definition/src/main/scala/org/enso/syntax/text/spec/ParserDef.scala
  lib/scala/syntax/specialization/shared/src/test/scala/org/enso/syntax/text/ParserTest.scala
  test/Test/src/Text/Spec.enso
  test/Test/src/Vector/Spec.enso
Labels: Category: Syntax, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1161 Fix the Suggestions Database Updates Handling
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/SuggestionsHandlerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/SuggestionsHandlerEventsTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/Suggestion.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/StdlibRuntimeServerTest.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/FileVersionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlSuggestionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlVersionsRepo.scala
  lib/scala/searcher/src/test/scala/org/enso/searcher/sql/FileVersionsRepoTest.scala
  lib/scala/searcher/src/test/scala/org/enso/searcher/sql/SuggestionsRepoTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Bug

#1194 Managed Resources Engine
  docs/semantics/managed-resources.md
  engine/runtime/src/main/java/org/enso/interpreter/Language.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/managedResource/FinalizeNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/managedResource/RegisterNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/managedResource/TakeNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/managedResource/WithNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Context.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/ResourceManager.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/ManagedResource.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/ManagedResource.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/type/Types.java
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/RuntimeManagementTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/ThreadInterruptionTest.scala
Labels: Category: RTS, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1196 Run Stdlib tests on CI
  .github/settings.yml
  .github/workflows/scala.yml
  test/Test/src/Process_Spec.enso
Labels: Category: Build, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1199 Fix Documentation Comments
  engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/TypeFunctions.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/TypeSignatures.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/context/SuggestionBuilderTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/DocumentationCommentsTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/TypeSignaturesTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Bug

#1200 Catch Polyglot Exceptions
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/CatchPanicNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Error.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/Atom.java
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/ErrorsTest.scala
Labels: Category: RTS, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1202 Remove stylesheet from documentation parser and code block fix.
  lib/scala/syntax/definition/src/main/scala/org/enso/syntax/text/ast/Doc.scala
  lib/scala/syntax/definition/src/main/scala/org/enso/syntax/text/spec/DocParserDef.scala
  lib/scala/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/DocParser.scala
  lib/scala/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/DocParserStyle/style.sass
  lib/scala/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/Parser.scala
Labels: Category: Libraries, Category: Syntax, Change: Non-Breaking, Difficulty: Intermediate, Priority: High

#1171 Implement Enso Time Library
  distribution/std-lib/Base/src/Time/Date.enso
  distribution/std-lib/Base/src/Time/Duration.enso
  distribution/std-lib/Base/src/Time/Time.enso
  distribution/std-lib/Base/src/Time/Time_Of_Day.enso
  distribution/std-lib/Base/src/Time/Zone.enso
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/BindingAnalysis.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/BindingAnalysisTest.scala
  std-bits/src/main/java/org/enso/base/Time_Utils.java
  test/Test/src/Main.enso
  test/Test/src/Time/Date_Spec.enso
  test/Test/src/Time/Duration_Spec.enso
  test/Test/src/Time/Spec.enso
  test/Test/src/Time/Time_Of_Day_Spec.enso
  test/Test/src/Time/Time_Spec.enso
  test/Test/src/Time/Zone_Spec.enso
Labels: Category: Libraries, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement

#1205 Fix bugs in TCO and test library
  distribution/std-lib/Base/src/Test.enso
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/TailCall.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/TailCallTest.scala
Labels: Category: Compiler, Category: Stdlib, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Bug

#1204 Files API
  distribution/std-lib/Base/src/Error/Extensions.enso
  distribution/std-lib/Base/src/Main.enso
  distribution/std-lib/Base/src/Meta/Enso_Project.enso
  distribution/std-lib/Base/src/Polyglot/Java.enso
  distribution/std-lib/Base/src/System/File.enso
  distribution/std-lib/Base/src/System/File/Option.enso
  distribution/std-lib/Base/src/Test.enso
  distribution/std-lib/Base/src/Text/Extensions.enso
  distribution/std-lib/Base/src/Vector.enso
  docs/distribution/packaging.md
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/MethodResolverNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/atom/QualifiedAccessorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/bool/EqualsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/bool/IfThenNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/io/GetCwdNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/io/GetFileNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/CreateUnresolvedSymbolNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/GetUnresolvedSymbolNameNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/GetUnresolvedSymbolScopeNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/resource/BracketNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/resource/FinalizeNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/resource/RegisterNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/resource/TakeNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/resource/WithNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/constant/EnsoProjectNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Context.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Bool.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Error.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/ManagedResource.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Meta.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Resource.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/UnresolvedSymbol.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoFile.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/type/Types.java
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/data/BindingsMap.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/BindingAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/phase/ExportsResolution.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/BindingAnalysisTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/ImportsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/MethodsTest.scala
  std-bits/src/main/java/org/enso/base/Text_Utils.java
  test/Test/data/sample.txt
  test/Test/src/Main.enso
  test/Test/src/System/File_Spec.enso
  test/Test/src/Vector/Spec.enso
Labels: Category: Stdlib, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1208 Fix Source Locations in Enso Files
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
Labels: Category: Compiler, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Bug

#1209 Allow Underscores in Project Names
  lib/scala/pkg/src/main/scala/org/enso/pkg/Package.scala
  lib/scala/pkg/src/test/scala/org/enso/pkg/NameSanitizationSpec.scala
Labels: Category: Tooling, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1198 Automate License Information Gathering
  .github/workflows/release.yml
  .github/workflows/scala.yml
  .prettierignore
  build.sbt
  docs/CONTRIBUTING.md
  docs/distribution/README.md
  docs/distribution/licences.md
  docs/distribution/licenses.md
  project/Distribution.scala
  project/GatherLicenses.scala
  project/StdBits.scala
  project/src/main/scala/licenses/Attachment.scala
  project/src/main/scala/licenses/DependencyInformation.scala
  project/src/main/scala/licenses/DependencySummary.scala
  project/src/main/scala/licenses/DistributionDescription.scala
  project/src/main/scala/licenses/backend/AttachmentGatherer.scala
  project/src/main/scala/licenses/backend/CombinedBackend.scala
  project/src/main/scala/licenses/backend/GatherCopyrights.scala
  project/src/main/scala/licenses/backend/GatherNotices.scala
  project/src/main/scala/licenses/backend/GithubHeuristic.scala
  project/src/main/scala/licenses/frontend/DependencyFilter.scala
  project/src/main/scala/licenses/frontend/SbtLicenses.scala
  project/src/main/scala/licenses/report/HTMLWriter.scala
  project/src/main/scala/licenses/report/PackageNotices.scala
  project/src/main/scala/licenses/report/Report.scala
  project/src/main/scala/licenses/report/Review.scala
  project/src/main/scala/licenses/report/WithWarnings.scala
  std-bits/pom.xml
  tools/legal-review-helper/index.js
  tools/legal-review-helper/package.json
  tools/legal-review-helper/static/inject.js
  tools/legal-review/launcher/com.typesafe.akka.akka-protobuf-v3_2.13-2.6.6/files-add/COPYING.protobuf
  tools/legal-review/launcher/commons-io.commons-io-2.7/custom-license
  tools/legal-review/license-texts/APACHE2.0
Labels: Category: Build, Category: Distribution, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1216 Implement Generic Programming Facilities
  distribution/std-lib/Base/src/Error/Extensions.enso
  distribution/std-lib/Base/src/Main.enso
  distribution/std-lib/Base/src/Meta/Meta.enso
  distribution/std-lib/Base/src/Number/Extensions.enso
  distribution/std-lib/Base/src/Vector.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/MethodResolverNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/GetAtomConstructorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/GetAtomFieldsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/GetConstructorFieldNamesNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/GetConstructorNameNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/GetPolyglotLanguageNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/IsAtomConstructorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/IsAtomNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/IsErrorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/IsPolyglotNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/IsSameObjectNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/IsUnresolvedSymbolNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/NewAtomInstanceNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Meta.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/AtomConstructor.java
  engine/runtime/src/main/scala/org/enso/compiler/pass/lint/ShadowedPatternFields.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/optimise/LambdaConsolidate.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/optimise/LambdaConsolidateTest.scala
  test/Benchmarks/src/Collections.enso
  test/Test/src/Main.enso
  test/Test/src/Semantic/Meta_Spec.enso
Labels: Category: Stdlib, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1212 Localize Interpreter Errors
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonRpc.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextEventsListener.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistry.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistryProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ExecutionApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/language-server/src/test/scala/org/enso/languageserver/runtime/ContextEventsListenerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/SuggestionsHandlerEventsTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime/src/main/java/org/enso/interpreter/service/error/ConstructorNotFoundException.java
  engine/runtime/src/main/java/org/enso/interpreter/service/error/MethodNotFoundException.java
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstToIr.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/EditFileCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/PushContextCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledStackJob.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ExecuteJob.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/StdlibRuntimeServerTest.scala
Labels: Category: Backend, Change: Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1222 Map Implementation
  distribution/bin/enso
  distribution/std-lib/Base/src/Data/Map.enso
  distribution/std-lib/Base/src/Data/Map/Internal.enso
  distribution/std-lib/Base/src/Main.enso
  distribution/std-lib/Base/src/Test.enso
  distribution/std-lib/Base/src/Text/Extensions.enso
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/RecursionBenchmarks.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/IndirectInvokeCallableNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeCallableNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/argument/ArgumentSorterNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/thunk/ForceNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/thunk/ThunkExecutorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/BooleanBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/BranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/CaseNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/CatchAllBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/ConstructorBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/InstantiateAtomNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/bool/IfThenElseNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/bool/IfThenNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/CatchPanicNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/function/ApplicationOperator.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/generic/EvalNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/generic/ExecuteNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/resource/BracketNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/runtime/NoInlineNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/state/RunStateNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/thread/WithInterruptHandlerNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Polyglot.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/Function.java
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/CodeLocationsTest.scala
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/Suspend.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/model/MethodDefinition.java
  std-bits/src/main/java/org/enso/base/Text_Utils.java
  test/Benchmarks/src/Collections.enso
  test/Benchmarks/src/Main.enso
  test/Test/src/Data/Map_Spec.enso
  test/Test/src/Main.enso
  tools/performance/comparative-benchmark/benchmarks/haskell/package.yaml
  tools/performance/comparative-benchmark/benchmarks/haskell/src/Fixtures.hs
  tools/performance/comparative-benchmark/benchmarks/haskell/test/bench/Main.hs
Labels: Category: Interpreter, Change: Non-Breaking, Difficulty: Core Contributor, Type: Enhancement

#1218 Use Environment Files in Actions
  .github/workflows/codeql-analysis.yml
  .github/workflows/legal-review.yml
  .github/workflows/release-update-broken.yml
  .github/workflows/release.yml
  .github/workflows/rust.yml
  .github/workflows/scala.yml
Labels: Category: Build, Change: Non-Breaking, Difficulty: Beginner, Priority: Highest, Type: Enhancement

#1241 JSON implementation
  build.sbt
  distribution/std-lib/Base/src/Data/Json.enso
  distribution/std-lib/Base/src/Data/Json/Internal.enso
  distribution/std-lib/Base/src/Main.enso
  distribution/std-lib/Base/src/Number/Extensions.enso
  distribution/std-lib/Base/src/Test.enso
  distribution/std-lib/Base/src/Text/Extensions.enso
  distribution/std-lib/Base/src/Vector.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/MethodResolverNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/mutable/EmptyNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/mutable/GetAtNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/mutable/GetRefNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/mutable/LengthNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/mutable/New1Node.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/mutable/New2Node.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/mutable/New3Node.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/mutable/New4Node.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/mutable/NewNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/mutable/NewRefNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/mutable/PutRefNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/mutable/SetAtNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/mutable/ToArrayNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/JsonSerializeNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Mutable.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Ref.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/type/Types.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/builtin/LanguageEntitySerializer.scala
  engine/runtime/src/test/scala/org/enso/std/test/JsonSerializationTest.scala
  std-bits/src/main/java/org/enso/base/Text_Utils.java
  std-bits/src/main/java/org/enso/base/json/Parser.java
  std-bits/src/main/java/org/enso/base/json/Printer.java
  test/Benchmarks/src/Json.enso
  test/Test/data/books.json
  test/Test/src/Data/Json_Spec.enso
  test/Test/src/Main.enso
Labels: Category: Stdlib, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1220 HTTP Library
  .github/workflows/scala.yml
  distribution/std-lib/Base/src/Main.enso
  distribution/std-lib/Base/src/Net/Http.enso
  distribution/std-lib/Base/src/Net/Http/Form.enso
  distribution/std-lib/Base/src/Net/Http/Header.enso
  distribution/std-lib/Base/src/Net/Http/Method.enso
  distribution/std-lib/Base/src/Net/Http/Request.enso
  distribution/std-lib/Base/src/Net/Http/Request/Body.enso
  distribution/std-lib/Base/src/Net/Http/Response.enso
  distribution/std-lib/Base/src/Net/Http/Response/Body.enso
  distribution/std-lib/Base/src/Net/Http/Status_Code.enso
  distribution/std-lib/Base/src/Net/Http/Version.enso
  distribution/std-lib/Base/src/Net/Proxy.enso
  distribution/std-lib/Base/src/Net/Uri.enso
  distribution/std-lib/Base/src/Text/Extensions.enso
  distribution/std-lib/Base/src/Time/Date.enso
  distribution/std-lib/Base/src/Time/Duration.enso
  distribution/std-lib/Base/src/Time/Time.enso
  distribution/std-lib/Base/src/Time/Time_Of_Day.enso
  distribution/std-lib/Base/src/Vector.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/syntax/ConstructorDispatchNode.java
  std-bits/src/main/java/org/enso/base/Http_Utils.java
  std-bits/src/main/java/org/enso/base/Text_Utils.java
  std-bits/src/main/java/org/enso/base/net/http/BasicAuthorization.java
  std-bits/src/main/java/org/enso/base/net/http/MultipartBodyBuilder.java
  std-bits/src/main/java/org/enso/base/net/http/UrlencodedBodyBuilder.java
  test/Test/src/Main.enso
  test/Test/src/Net/Http/Header_Spec.enso
  test/Test/src/Net/Http/Request_Spec.enso
  test/Test/src/Net/Http_Spec.enso
  test/Test/src/Net/Uri_Spec.enso
  test/Test/src/Time/Duration_Spec.enso
  test/Test/src/Vector/Spec.enso
Labels: Category: Stdlib, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement

#1246 Make Legal Review Required For PRs
  .github/settings.yml
  lib/rust/flexer/Cargo.toml
Labels: Category: Build, Category: Distribution, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement
