Repository enso-org/enso, pull requests merged in 2020-07, with the labels that each got.

#928 Java 11 Migration
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/workflows/scala.yml
  .jvmopts
  build.sbt
  docs/CONTRIBUTING.md
  docs/debugger/protocol.md
  docs/getting-enso.md
  docs/infrastructure/README.md
  docs/infrastructure/java-11.md
  docs/infrastructure/sbt.md
  engine/language-server/src/bench/scala/org/enso/languageserver/text/RopeBench.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/FileManagerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/TextOperationsTest.scala
  engine/runner/src/main/scala/org/enso/runner/Main.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/DocumentationCommentsTest.scala
  lib/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/MethodProcessor.java
  lib/searcher/src/test/scala/org/enso/searcher/sql/SuggestionsRepoTest.scala
  lib/text-buffer/src/test/scala/org/enso/text/editing/RopeTextEditorSpec.scala
  project/CopyTruffleJAR.scala
  project/EnvironmentCheck.scala
  project/FixInstrumentsGeneration.scala
  project/GenerateFlatbuffers.scala
  project/RecompileParser.scala
Labels: Category: Build, Change: Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#957 Describe the Release Process
  .github/settings.yml
  .github/workflows/rust.yml
  .github/workflows/scala.yml
  docs/SECURITY.md
  docs/distribution/README.md
  docs/distribution/release-policy.md
Labels: Category: Build, Category: Documentation, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#956 Enable CodeQL Analysis for Java
  .github/settings.yml
  .github/workflows/codeql-analysis.yml
Labels: Category: Build, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#958 Fix testOnly after Java 11 migration
  build.sbt
  docs/infrastructure/java-11.md
  lib/project-manager/src/test/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerSupervisorSpec.scala
Labels: Category: Build, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#935 Version option for Project Manager
  build.sbt
  lib/project-manager/src/main/scala/org/enso/projectmanager/boot/ProjectManager.scala
Labels: Category: Tooling, Change: Non-Breaking, Difficulty: Intermediate, Priority: Medium, Size: Small, Status: Help Wanted, Type: Enhancement

#960 Fix missing warning for unused arguments
  docs/CONTRIBUTING.md
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/ComplexType.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/LambdaShorthandToLambda.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/NestedPatternMatch.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/OperatorToFunction.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/SectionsToBinOp.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/lint/ShadowedPatternFields.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/lint/UnusedBindings.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/optimise/ApplicationSaturation.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/optimise/LambdaConsolidate.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/optimise/UnreachableMatchBranches.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/IgnoredBindings.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/TypeFunctions.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/GatherDiagnosticsTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/lint/UnusedBindingsTest.scala
  lib/searcher/src/test/scala/org/enso/searcher/sql/SuggestionsRepoTest.scala
Labels: Category: Compiler, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Bug

#961 Update scalafmt to 2.6.1
  .github/workflows/codeql-analysis.yml
  .rustfmt.toml
  .scalafmt.conf
Labels: Category: Build, Change: Non-Breaking, Difficulty: Beginner, Priority: Highest, Type: Enhancement

#962 Bugfix for project path collisions
  lib/project-manager/src/main/scala/org/enso/projectmanager/control/core/CovariantFlatMap.scala
  lib/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/file/BlockingFileSystem.scala
  lib/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/file/FileSystem.scala
  lib/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/repository/ProjectFileRepository.scala
  lib/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Bug

#968 Update the Links in the Docs
  .github/CODEOWNERS
  README.md
  docs/getting-enso.md
Labels: Category: Documentation, Change: Non-Breaking, Difficulty: Beginner, Priority: Highest, Type: Enhancement

#969 Bump scalafmt to 2.6.2
  .scalafmt.conf
Labels: Category: Build, Change: Non-Breaking, Difficulty: Beginner, Priority: Highest, Type: Enhancement

#953 Implement Search Requests API
  .github/workflows/scala.yml
  build.sbt
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/resources/logback.xml
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionControllerFactory.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonRpc.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/search/CompletionHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/search/GetSuggestionsDatabaseHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/search/GetSuggestionsDatabaseVersionHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/SearchApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/SearchProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/SuggestionsDatabaseEventsListener.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/SuggestionsHandler.scala
  engine/language-server/src/test/resources/application.conf
  engine/language-server/src/test/scala/org/enso/languageserver/runtime/Suggestions.scala
  engine/language-server/src/test/scala/org/enso/languageserver/runtime/SuggestionsDatabaseEventsListenerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/runtime/SuggestionsHandlerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/FileNotificationsTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/SearchJsonMessages.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/SuggestionsDatabaseEventsListenerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/SuggestionsHandlerTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/DocumentationCommentsTest.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala
  lib/scala/searcher/src/bench/java/org/enso/searcher/sql/SuggestionsRepoBenchmark.java
  lib/scala/searcher/src/bench/scala/org/enso/searcher/sql/SuggestionRandom.scala
  lib/scala/searcher/src/main/resources/application.conf
  lib/scala/searcher/src/main/resources/reference.conf
  lib/scala/searcher/src/main/scala/org/enso/searcher/Database.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/Suggestion.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/SuggestionEntry.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/SuggestionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlDatabase.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlSuggestionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/Tables.scala
  lib/scala/searcher/src/test/resources/application.conf
  lib/scala/searcher/src/test/resources/logback-test.xml
  lib/scala/searcher/src/test/scala/org/enso/searcher/sql/SuggestionsRepoTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#972 Refactor the Flexer
  lib/rust/flexer/src/automata.rs
  lib/rust/flexer/src/automata/alphabet.rs
  lib/rust/flexer/src/automata/dfa.rs
  lib/rust/flexer/src/automata/nfa.rs
  lib/rust/flexer/src/automata/pattern.rs
  lib/rust/flexer/src/automata/state.rs
  lib/rust/flexer/src/automata/symbol.rs
  lib/rust/flexer/src/data.rs
  lib/rust/flexer/src/data/matrix.rs
  lib/rust/flexer/src/group.rs
  lib/rust/flexer/src/group/rule.rs
  lib/rust/flexer/src/lib.rs
  lib/rust/flexer/src/parser.rs
  lib/scala/flexer/src/main/scala/org/enso/flexer/spec/Macro.scala
Labels: Category: Syntax, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#963 Launcher Design
  .github/ISSUE_TEMPLATE/bug-report.md
  distribution/launcher/README.md
  docs/distribution/README.md
  docs/distribution/launcher-cli.md
  docs/distribution/launcher.md
  docs/distribution/release-policy.md
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala
Labels: Category: Distribution, Change: Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#979 Move project dirs on project close
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/MainModule.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/ProjectManager.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/event/ProjectEvent.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerController.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerGateway.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerGatewayImpl.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerKiller.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/ShutdownHookActivationWatcher.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/ShutdownHookActivator.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/ShutdownHookRunner.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/shutdown/ShutdownHookProcessor.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectService.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/BaseServerSpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerGatewaySpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/test/Net.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement

#970 Launcher Native Image Build
  .github/workflows/scala.yml
  build.sbt
  distribution/launcher/NOTICE
  distribution/launcher/components-licences/LICENSE-APACHE
  distribution/launcher/components-licences/LICENSE-MIT
  distribution/manifest.template.yml
  docs/CONTRIBUTING.md
  docs/distribution/README.md
  docs/distribution/launcher-cli.md
  docs/distribution/licences.md
  docs/distribution/release-policy.md
  docs/infrastructure/sbt.md
  engine/language-server/src/test/scala/org/enso/languageserver/runtime/SuggestionsDatabaseEventsListenerTest.scala
  engine/launcher/src/main/scala/org/enso/launcher/Launcher.scala
  engine/launcher/src/main/scala/org/enso/launcher/Main.scala
  engine/launcher/src/test/scala/org/enso/launcher/LauncherSpec.scala
  engine/runner/src/main/scala/org/enso/runner/Main.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/ProjectManager.scala
  lib/scala/version-output/src/main/scala/org/enso/version/VersionDescription.scala
  project/BuildInfo.scala
  project/EnvironmentCheck.scala
  project/NativeImage.scala
  project/plugins.sbt
Labels: Category: Build, Category: Tooling, Change: Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#983 Flexer Tests
  lib/rust/flexer/src/automata/alphabet.rs
  lib/rust/flexer/src/automata/dfa.rs
  lib/rust/flexer/src/automata/nfa.rs
  lib/rust/flexer/src/group.rs
Labels: Category: Syntax, Change: Non-Breaking, Difficulty: Beginner, Priority: High, Type: Enhancement

#988 Increase timeouts on Windows CI
  .github/workflows/scala.yml
  build.sbt
  engine/language-server/src/test/resources/application.conf
  engine/language-server/src/test/scala/org/enso/languageserver/filemanager/WatcherAdapterSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/requesthandler/monitoring/PingHandlerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/runtime/SuggestionsDatabaseEventsListenerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/runtime/SuggestionsHandlerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/binary/BinaryFileManipulationTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/binary/BinarySessionManagementTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/binary/VisualisationProtocolTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/FileManagerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/FileNotificationsTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/SuggestionsDatabaseEventsListenerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/TextOperationsTest.scala
  lib/scala/project-manager/src/test/resources/application.conf
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/BaseServerSpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerGatewaySpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerSupervisorSpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/infrastructure/languageserver/ProjectRenameActionSpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala
  lib/scala/searcher/src/test/scala/org/enso/searcher/sql/SuggestionsRepoTest.scala
  lib/scala/testkit/src/main/scala/org/enso/testkit/FlakySpec.scala
  lib/scala/testkit/src/main/scala/org/enso/testkit/RetrySpec.scala
Labels: Category: Build, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Low, Type: Enhancement

#990 Automate the Rust Code Generation
  .gitignore
  Cargo.toml
  docs/parser/flexer.md
  lib/rust/flexer/Cargo.toml
  lib/rust/flexer/build.rs
  lib/rust/flexer/src/lib.rs
  lib/rust/lexer/definition/Cargo.toml
  lib/rust/lexer/definition/src/lexer.rs
  lib/rust/lexer/definition/src/lib.rs
  lib/rust/lexer/generation/Cargo.toml
  lib/rust/lexer/generation/build.rs
  lib/rust/lexer/generation/src/lexer.rs
  lib/rust/lexer/generation/src/lib.rs
  lib/rust/lexer/tests/Cargo.toml
  lib/rust/lexer/tests/src/main.rs
  tools/run
Labels: Category: Syntax, Change: Non-Breaking, Difficulty: Intermediate, Priority: Highest, Type: Enhancement

#998 Test Framework for Enso
  distribution/std-lib/Base/src/Bench_Utils.enso
  distribution/std-lib/Base/src/List.enso
  distribution/std-lib/Base/src/Test.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/atom/GetFieldNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/function/ApplicationOperator.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/runtime/GCNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/system/ExitNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/unsafe/SetAtomFieldNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/Atom.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/AtomConstructor.java
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DemandAnalysis.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/DemandAnalysisTest.scala
  lib/scala/syntax/definition/src/main/scala/org/enso/syntax/text/ast/opr/Assoc.scala
  lib/scala/syntax/definition/src/main/scala/org/enso/syntax/text/ast/opr/Prec.scala
  test/Benchmarks/src/Main.enso
  test/Test/package.yaml
  test/Test/src/List_Spec.enso
  test/Test/src/Main.enso
  test/Test/src/Number_Spec.enso
Labels: Category: Libraries, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1002 Expose connection with Documentation parser and generator in ScalaJS artifact
  lib/scala/syntax/specialization/js/src/main/scala/org/enso/syntax/text/Main.scala
  lib/scala/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/DocParser.scala
  lib/scala/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/Parser.scala
Labels: Category: Libraries, Category: Syntax, Change: Non-Breaking, Difficulty: Intermediate, Priority: Medium, Size: Small, Type: Enhancement

#1017 Create Documentation Parser and generator websocket wrapper
  lib/scala/parser-service/src/main/scala/org/enso/ParserService.scala
  lib/scala/parser-service/src/main/scala/org/enso/parserservice/Protocol.scala
  lib/scala/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/DocParserStyle/style.sass
Labels: Category: Syntax, Change: Non-Breaking, Difficulty: Intermediate, Priority: High, Type: Enhancement

#1015 Enable FlakySpec only on Windows
  .github/workflows/scala.yml
  engine/language-server/src/main/scala/org/enso/languageserver/boot/LanguageServerComponent.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  lib/scala/json-rpc-server-test/src/main/scala/org/enso/jsonrpc/test/JsonRpcServerTestKit.scala
  lib/scala/project-manager/src/test/resources/application.conf
  lib/scala/project-manager/src/test/resources/logback-test.xml
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/BaseServerSpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/ProjectManagementOps.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlDatabase.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlSuggestionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlVersionsRepo.scala
  lib/scala/testkit/src/main/scala/org/enso/testkit/FlakySpec.scala
Labels: Category: Build, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Low, Type: Enhancement

#1018 Fix capability/acquire documentation
  docs/language-server/protocol-language-server.md
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Bug

#993 Update Documentation and Build Settings
  .github/workflows/scala.yml
  build.sbt
  distribution/bin/enso
  distribution/bin/enso.bat
  distribution/manifest.template.yaml
  docs/CONTRIBUTING.md
  docs/distribution/distribution.md
  docs/distribution/launcher-cli.md
  docs/distribution/launcher.md
  docs/distribution/packaging.md
  docs/distribution/release-policy.md
  engine/runner/jupyter-kernel/enso/kernel.json
Labels: Category: Distribution, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1023 Add possibility to generate Doc HTML from pure text without connection to Enso AST
  lib/scala/parser-service/src/main/scala/org/enso/ParserService.scala
  lib/scala/parser-service/src/main/scala/org/enso/parserservice/Protocol.scala
  lib/scala/syntax/specialization/js/src/main/scala/org/enso/syntax/text/Main.scala
  lib/scala/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/DocParser.scala
  lib/scala/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/Parser.scala
Labels: Category: External, Category: Libraries, Change: Non-Breaking, Difficulty: Intermediate, Priority: High, Size: Small, Type: Enhancement

#1014 Input Reader for the Flexer
  Cargo.toml
  docs/parser/reader.md
  lib/rust/lazy-reader/Cargo.toml
  lib/rust/lazy-reader/src/decoder.rs
  lib/rust/lazy-reader/src/lib.rs
Labels: Category: Syntax, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#989 Release Process Automation on the CI
  .github/workflows/release.yml
  distribution/launcher/.enso.portable
Labels: Category: Build, Category: Distribution, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1021 Fix the search/getSuggestionsDatabase API
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/SearchApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/SearchProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/SuggestionsHandler.scala
  engine/language-server/src/test/scala/org/enso/languageserver/runtime/SuggestionsHandlerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/SuggestionsHandlerEventsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Bug

#1024 Method naming fixes
  distribution/std-lib/Base/src/Test.enso
  engine/runner/src/main/scala/org/enso/runner/Main.scala
  engine/runtime/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java
  engine/runtime/src/main/java/org/enso/interpreter/node/ClosureRootNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/MethodRootNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/ProgramRootNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/debug/EvalNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/AtomConstructor.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/TopLevelScope.java
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  lib/scala/pkg/src/main/scala/org/enso/pkg/QualifiedName.scala
  test/Test/src/Main.enso
Labels: Category: Interpreter, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1019 Stub AST for flexer.
  Cargo.toml
  lib/rust/ast/Cargo.toml
  lib/rust/ast/src/lib.rs
  lib/rust/lazy-reader/src/lib.rs
Labels: Category: Syntax, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1025 Wait for Suggestions Database Initialization
  engine/language-server/src/main/scala/org/enso/languageserver/boot/LanguageServerComponent.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/event/InitializedEvent.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonRpc.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/search/CompletionHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/search/GetSuggestionsDatabaseHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/search/GetSuggestionsDatabaseVersionHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/ModuleNameBuilder.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SearchApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SearchFailureMapper.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SearchProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/language-server/src/test/resources/application.conf
  engine/language-server/src/test/scala/org/enso/languageserver/search/Suggestions.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/SuggestionsHandlerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/SuggestionsHandlerEventsTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/SuggestionsHandlerTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  lib/scala/project-manager/src/main/resources/logback.xml
  lib/scala/project-manager/src/test/resources/application.conf
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlSuggestionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlVersionsRepo.scala
  lib/scala/searcher/src/test/resources/application.conf
  lib/scala/searcher/src/test/scala/org/enso/searcher/sql/FileVersionsRepoTest.scala
  lib/scala/searcher/src/test/scala/org/enso/searcher/sql/SuggestionsRepoTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Bug

#997 [Feat, Tool] Add CLI Parser for the Launcher
  .github/workflows/release.yml
  .github/workflows/scala.yml
  build.sbt
  distribution/launcher/NOTICE
  docs/CONTRIBUTING.md
  docs/distribution/distribution.md
  docs/distribution/launcher-cli.md
  docs/distribution/launcher.md
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/InputOutputRedirectionTest.scala
  engine/launcher/src/main/scala/org/enso/launcher/Main.scala
  engine/launcher/src/main/scala/org/enso/launcher/PluginManager.scala
  engine/launcher/src/test/scala/org/enso/launcher/LauncherSpec.scala
  engine/launcher/src/test/scala/org/enso/launcher/NativeLauncherSpec.scala
  engine/launcher/src/test/scala/org/enso/launcher/NativeTest.scala
  engine/launcher/src/test/scala/org/enso/launcher/PluginManagerSpec.scala
  engine/launcher/src/test/scala/org/enso/launcher/WithTemporaryDirectory.scala
  lib/scala/cli/src/main/scala/org/enso/cli/Application.scala
  lib/scala/cli/src/main/scala/org/enso/cli/Argument.scala
  lib/scala/cli/src/main/scala/org/enso/cli/CLIOutput.scala
  lib/scala/cli/src/main/scala/org/enso/cli/Command.scala
  lib/scala/cli/src/main/scala/org/enso/cli/Opts.scala
  lib/scala/cli/src/main/scala/org/enso/cli/Spelling.scala
  lib/scala/cli/src/main/scala/org/enso/cli/internal/AdditionalArguments.scala
  lib/scala/cli/src/main/scala/org/enso/cli/internal/BaseOpts.scala
  lib/scala/cli/src/main/scala/org/enso/cli/internal/CLIOutputInternal.scala
  lib/scala/cli/src/main/scala/org/enso/cli/internal/Flag.scala
  lib/scala/cli/src/main/scala/org/enso/cli/internal/NeedlemanWunsch.scala
  lib/scala/cli/src/main/scala/org/enso/cli/internal/OptionalParameter.scala
  lib/scala/cli/src/main/scala/org/enso/cli/internal/OptionalPositionalArgument.scala
  lib/scala/cli/src/main/scala/org/enso/cli/internal/OptsMap.scala
  lib/scala/cli/src/main/scala/org/enso/cli/internal/OptsProduct.scala
  lib/scala/cli/src/main/scala/org/enso/cli/internal/OptsPure.scala
  lib/scala/cli/src/main/scala/org/enso/cli/internal/Parameter.scala
  lib/scala/cli/src/main/scala/org/enso/cli/internal/Parser.scala
  lib/scala/cli/src/main/scala/org/enso/cli/internal/PositionalArgument.scala
  lib/scala/cli/src/main/scala/org/enso/cli/internal/PrefixedParameters.scala
  lib/scala/cli/src/main/scala/org/enso/cli/internal/SubcommandOpt.scala
  lib/scala/cli/src/main/scala/org/enso/cli/internal/TrailingArguments.scala
  lib/scala/cli/src/main/scala/org/enso/cli/internal/package.scala
  lib/scala/cli/src/test/scala/org/enso/cli/ApplicationSpec.scala
  lib/scala/cli/src/test/scala/org/enso/cli/CLIOutputSpec.scala
  lib/scala/cli/src/test/scala/org/enso/cli/OptsSpec.scala
  lib/scala/cli/src/test/scala/org/enso/cli/SpellingSpec.scala
  lib/scala/version-output/src/main/scala/org/enso/version/VersionDescription.scala
  project/NativeImage.scala
Labels: Category: Tooling, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1030 [Tool] Move engine build after launcher
  .github/workflows/release.yml
  build.sbt
Labels: Category: Build, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1036 [Build,Doc] Make builds work outside a repository
  docs/getting-enso.md
  project/BuildInfo.scala
Labels: Category: Build, Category: Documentation, Change: Non-Breaking, Difficulty: Intermediate, Priority: High, Type: Enhancement

#1034 Add Installation Mechanism in the Launcher
  .gitignore
  docs/distribution/distribution.md
  engine/launcher/src/main/scala/org/enso/launcher/Environment.scala
  engine/launcher/src/main/scala/org/enso/launcher/FileSystem.scala
  engine/launcher/src/main/scala/org/enso/launcher/GlobalConfigurationManager.scala
  engine/launcher/src/main/scala/org/enso/launcher/InternalOpts.scala
  engine/launcher/src/main/scala/org/enso/launcher/Launcher.scala
  engine/launcher/src/main/scala/org/enso/launcher/Logger.scala
  engine/launcher/src/main/scala/org/enso/launcher/Main.scala
  engine/launcher/src/main/scala/org/enso/launcher/PluginManager.scala
  engine/launcher/src/main/scala/org/enso/launcher/installation/DistributionInstaller.scala
  engine/launcher/src/main/scala/org/enso/launcher/installation/DistributionManager.scala
  engine/launcher/src/main/scala/org/enso/launcher/internal/Environment.scala
  engine/launcher/src/main/scala/org/enso/launcher/internal/OS.scala
  engine/launcher/src/main/scala/org/enso/launcher/internal/PluginManager.scala
  engine/launcher/src/main/scala/org/enso/launcher/internal/installation/DistributionManager.scala
  engine/launcher/src/test/scala/org/enso/launcher/NativeTest.scala
  engine/launcher/src/test/scala/org/enso/launcher/WithTemporaryDirectory.scala
  engine/launcher/src/test/scala/org/enso/launcher/installation/DistributionManagerSpec.scala
  engine/launcher/src/test/scala/org/enso/launcher/installation/InstallerSpec.scala
  lib/scala/cli/src/main/scala/org/enso/cli/Application.scala
  lib/scala/cli/src/main/scala/org/enso/cli/CLIOutput.scala
  lib/scala/cli/src/main/scala/org/enso/cli/Opts.scala
  lib/scala/cli/src/main/scala/org/enso/cli/internal/Flag.scala
  lib/scala/cli/src/main/scala/org/enso/cli/internal/HiddenOpts.scala
  lib/scala/cli/src/main/scala/org/enso/cli/internal/Parser.scala
Labels: Category: Tooling, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1033 Update ExpressionValueUpdate Notification API
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextEventsListener.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistry.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ExpressionValueUpdate.scala
  engine/language-server/src/test/scala/org/enso/languageserver/runtime/ContextEventsListenerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/ContextRegistryTest.scala
  lib/scala/searcher/src/bench/java/org/enso/searcher/sql/SuggestionsRepoBenchmark.java
  lib/scala/searcher/src/bench/scala/org/enso/searcher/sql/SuggestionRandom.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/SuggestionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlSuggestionsRepo.scala
  lib/scala/searcher/src/test/scala/org/enso/searcher/sql/SuggestionsRepoTest.scala
Labels: Category: Backend, Change: Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1041 Handle Rename Command Properly
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonRpc.scala
  engine/language-server/src/main/scala/org/enso/languageserver/refactoring/ProjectNameChangedEvent.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/refactoring/RenameProjectHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/search/InvalidateSuggestionsDatabaseHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SearchApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SearchProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/handler/InvalidateModulesIndexHandler.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/SuggestionsHandlerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/SuggestionsHandlerEventsTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/SuggestionsHandlerTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/TopLevelScope.java
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/CommandFactory.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/InvalidateModulesIndexCmd.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/FileVersionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/SuggestionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlSuggestionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlVersionsRepo.scala
  lib/scala/searcher/src/test/scala/org/enso/searcher/sql/SuggestionsRepoTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Bug

#1043 Revert expressionId Removal from Value Update
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextEventsListener.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ExpressionValueUpdate.scala
  engine/language-server/src/test/scala/org/enso/languageserver/runtime/ContextEventsListenerSpec.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/infrastructure/languageserver/ProgrammableWebSocketServer.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/infrastructure/languageserver/ProjectRenameActionSpec.scala
Labels: Category: Backend, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Bug

#1044 Generate Scala Classes from the Stub AST
  docs/distribution/distribution.md
  docs/distribution/launcher-cli.md
  docs/distribution/launcher.md
  docs/parser/ast.md
  lib/rust/ast/Cargo.toml
  lib/rust/ast/src/ast.rs
  lib/rust/ast/src/generation.rs
  lib/rust/ast/src/lib.rs
  lib/rust/ast/src/main.rs
Labels: Category: Codegen, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement
