Repository enso-org/enso, pull requests merged in 2021-05, with the labels that each got.

#1714 More Examples Enhancements
  .gitignore
  distribution/std-lib/Standard/src/Base/Error/Common.enso
  distribution/std-lib/Standard/src/Base/Error/Extensions.enso
  distribution/std-lib/Standard/src/Base/Math.enso
  distribution/std-lib/Standard/src/Base/Meta/Enso_Project.enso
  distribution/std-lib/Standard/src/Base/Network/Http.enso
  distribution/std-lib/Standard/src/Base/Network/Http/Form.enso
  distribution/std-lib/Standard/src/Base/Network/Http/Header.enso
  distribution/std-lib/Standard/src/Base/Network/Http/Request.enso
  distribution/std-lib/Standard/src/Base/Network/Http/Response.enso
  distribution/std-lib/Standard/src/Base/Network/Http/Response/Body.enso
  distribution/std-lib/Standard/src/Base/Network/Proxy.enso
  distribution/std-lib/Standard/src/Base/Network/Uri.enso
  distribution/std-lib/Standard/src/Base/System/Environment.enso
  distribution/std-lib/Standard/src/Base/System/File.enso
  distribution/std-lib/Standard/src/Base/System/Platform.enso
  distribution/std-lib/Standard/src/Base/System/Process.enso
  distribution/std-lib/Standard/src/Base/System/Process/Exit_Code.enso
  distribution/std-lib/Standard/src/Examples.enso
  engine/runtime/src/main/resources/Builtins.enso
  test/Tests/src/Network/Http_Spec.enso
  test/Tests/src/System/Process_Spec.enso
Labels: Category: Stdlib, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1718 Extract Symlinks from Archives
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/archive/Archive.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/ComponentsException.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/RuntimeVersionManager.scala
Labels: Category: Distribution, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Bug

#1722 HTTP Library Updates
  distribution/std-lib/Standard/src/Base/Network/Http.enso
  distribution/std-lib/Standard/src/Base/Network/Http/Request.enso
  distribution/std-lib/Standard/src/Base/Network/Uri.enso
  test/Tests/src/Network/Http_Spec.enso
Labels: Category: Libraries, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Bug

#1725 Enhance the `Standard.Image` Examples
  .gitignore
  distribution/std-lib/Standard/src/Database/Connection/Connection.enso
  distribution/std-lib/Standard/src/Database/Connection/Database.enso
  distribution/std-lib/Standard/src/Database/Data/Column.enso
  distribution/std-lib/Standard/src/Database/Data/Dialect.enso
  distribution/std-lib/Standard/src/Database/Data/Internal/Base_Generator.enso
  distribution/std-lib/Standard/src/Database/Data/Internal/Helpers.enso
  distribution/std-lib/Standard/src/Database/Data/Internal/IR.enso
  distribution/std-lib/Standard/src/Database/Data/Internal/Vector_Builder.enso
  distribution/std-lib/Standard/src/Database/Data/Sql.enso
  distribution/std-lib/Standard/src/Database/Data/Table.enso
  distribution/std-lib/Standard/src/Examples.enso
  distribution/std-lib/Standard/src/Geo.enso
  distribution/std-lib/Standard/src/Image/Codecs.enso
  distribution/std-lib/Standard/src/Image/Codecs/Internal.enso
  distribution/std-lib/Standard/src/Image/Data/Histogram.enso
  distribution/std-lib/Standard/src/Image/Data/Image.enso
  distribution/std-lib/Standard/src/Image/Data/Image/Internal.enso
  distribution/std-lib/Standard/src/Image/Data/Matrix.enso
  distribution/std-lib/Standard/src/Image/Data/Matrix/Internal.enso
  project/DistributionPackage.scala
Labels: Category: Stdlib, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1728 Update the changelog for the new nightlies
  RELEASES.md
Labels: Category: Documentation, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1727 Remove Reflective Access when Loading OpenCV
  .github/workflows/scala.yml
  RELEASES.md
  std-bits/src/main/java/org/enso/image/Codecs.java
  std-bits/src/main/java/org/enso/image/data/Image.java
  std-bits/src/main/java/org/enso/image/data/Matrix.java
  test/Image_Tests/src/Codecs_Spec.enso
Labels: Category: Build, Category: Libraries, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement

#1731 Finish Updating the Standard Library Examples
  RELEASES.md
  distribution/std-lib/Standard/data/food_shop_inventory.csv
  distribution/std-lib/Standard/data/food_shop_popularity.csv
  distribution/std-lib/Standard/data/food_shop_transactions.csv
  distribution/std-lib/Standard/src/Examples.enso
  distribution/std-lib/Standard/src/Table.enso
  distribution/std-lib/Standard/src/Table/Data/Column.enso
  distribution/std-lib/Standard/src/Table/Data/Order_Rule.enso
  distribution/std-lib/Standard/src/Table/Data/Table.enso
  distribution/std-lib/Standard/src/Table/Io/Csv.enso
  distribution/std-lib/Standard/src/Test.enso
  distribution/std-lib/Standard/src/Test/Bench.enso
  distribution/std-lib/Standard/src/Visualization/Geo_Map.enso
  distribution/std-lib/Standard/src/Visualization/Helpers.enso
  distribution/std-lib/Standard/src/Visualization/Histogram.enso
  distribution/std-lib/Standard/src/Visualization/Scatter_Plot.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/GetQualifiedTypeNameNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/GetSimpleTypeNameNode.java
  test/Tests/src/Examples_Spec.enso
  test/Tests/src/Main.enso
Labels: Category: Stdlib, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1738 Update to Graal 21.1.0
  .github/workflows/codeql-analysis.yml
  .github/workflows/legal-review.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/rust.yml
  .github/workflows/scala.yml
  .gitignore
  Cargo.lock
  RELEASES.md
  build.sbt
  docs/CONTRIBUTING.md
  engine/runtime/src/main/java/org/enso/interpreter/Language.java
  engine/runtime/src/main/java/org/enso/interpreter/epb/EpbLanguage.java
  engine/runtime/src/main/java/org/enso/interpreter/epb/node/ContextRewrapNode.java
  engine/runtime/src/main/java/org/enso/interpreter/epb/node/ForeignEvalNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Context.java
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ExecuteJob.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualisationsTest.scala
  lib/rust/ast/Cargo.toml
  lib/rust/lexer/definition/Cargo.toml
  lib/rust/lexer/definition/src/lexer.rs
  lib/rust/lexer/generation/Cargo.toml
  lib/rust/parser-jni/Cargo.toml
  lib/rust/parser-jni/src/jni.rs
  lib/rust/parser/Cargo.toml
  lib/rust/parser/src/lib.rs
  lib/rust/parser/src/macros.rs
  project/EnvironmentCheck.scala
  project/GenerateFlatbuffers.scala
  project/NativeImage.scala
  project/build.properties
  test/Tests/src/Network/Http_Spec.enso
  test/Tests/src/Semantic/Python_Interop_Spec.enso
  tools/run
Labels: Category: Build, Category: Distribution, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1742 Add Error to Json Conversion
  distribution/std-lib/Standard/src/Base/Error/Extensions.enso
  test/Tests/src/Semantic/Error_Spec.enso
Labels: Category: Stdlib, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Size: Small, Type: Bug

#1743 Fix Legal Review Warnings
  tools/legal-review/engine/com.fasterxml.jackson.dataformat.jackson-dataformat-cbor-2.11.1/files-ignore
  tools/legal-review/engine/eu.timepit.refined_2.13-0.9.14/files-ignore
  tools/legal-review/engine/io.circe.circe-core_2.13-0.14.0-M1/files-ignore
  tools/legal-review/engine/io.circe.circe-generic-extras_2.13-0.13.0/files-ignore
  tools/legal-review/engine/io.circe.circe-generic_2.13-0.14.0-M1/files-ignore
  tools/legal-review/engine/io.circe.circe-jawn_2.13-0.14.0-M1/files-ignore
  tools/legal-review/engine/io.circe.circe-literal_2.13-0.14.0-M1/files-ignore
  tools/legal-review/engine/io.circe.circe-numbers_2.13-0.14.0-M1/files-ignore
  tools/legal-review/engine/io.circe.circe-parser_2.13-0.14.0-M1/files-ignore
  tools/legal-review/engine/io.circe.circe-yaml_2.13-0.13.1/files-ignore
  tools/legal-review/engine/nl.gn0s1s.bump_2.13-0.1.3/files-ignore
  tools/legal-review/engine/org.typelevel.alleycats-core_2.13-2.1.1/files-ignore
  tools/legal-review/engine/org.typelevel.alleycats-core_2.13-2.1.1/files-keep
  tools/legal-review/engine/org.typelevel.cats-core_2.13-2.2.0-M3/files-keep
  tools/legal-review/engine/org.typelevel.cats-free_2.13-2.1.1/files-ignore
  tools/legal-review/engine/org.typelevel.cats-free_2.13-2.1.1/files-keep
  tools/legal-review/engine/org.typelevel.cats-kernel_2.13-2.2.0-M3/files-ignore
  tools/legal-review/engine/org.typelevel.cats-kernel_2.13-2.2.0-M3/files-keep
  tools/legal-review/engine/org.typelevel.cats-macros_2.13-2.1.1/files-ignore
  tools/legal-review/engine/org.typelevel.cats-macros_2.13-2.1.1/files-keep
  tools/legal-review/engine/report-state
  tools/legal-review/launcher/io.circe.circe-core_2.13-0.14.0-M1/files-ignore
  tools/legal-review/launcher/io.circe.circe-generic_2.13-0.14.0-M1/files-ignore
  tools/legal-review/launcher/io.circe.circe-jawn_2.13-0.14.0-M1/files-ignore
  tools/legal-review/launcher/io.circe.circe-numbers_2.13-0.14.0-M1/files-ignore
  tools/legal-review/launcher/io.circe.circe-parser_2.13-0.14.0-M1/files-ignore
  tools/legal-review/launcher/io.circe.circe-yaml_2.13-0.13.1/files-ignore
  tools/legal-review/launcher/nl.gn0s1s.bump_2.13-0.1.3/files-ignore
  tools/legal-review/launcher/org.typelevel.cats-core_2.13-2.2.0-M3/files-keep
  tools/legal-review/launcher/org.typelevel.cats-kernel_2.13-2.2.0-M3/files-ignore
  tools/legal-review/launcher/org.typelevel.cats-kernel_2.13-2.2.0-M3/files-keep
  tools/legal-review/launcher/report-state
  tools/legal-review/project-manager/com.fasterxml.jackson.dataformat.jackson-dataformat-cbor-2.11.1/files-ignore
  tools/legal-review/project-manager/com.github.pureconfig.pureconfig-core_2.13-0.13.0/files-ignore
  tools/legal-review/project-manager/com.github.pureconfig.pureconfig-generic-base_2.13-0.13.0/files-ignore
  tools/legal-review/project-manager/com.github.pureconfig.pureconfig-generic_2.13-0.13.0/files-ignore
  tools/legal-review/project-manager/com.github.pureconfig.pureconfig-macros_2.13-0.13.0/files-ignore
  tools/legal-review/project-manager/com.github.pureconfig.pureconfig_2.13-0.13.0/files-ignore
  tools/legal-review/project-manager/io.circe.circe-core_2.13-0.14.0-M1/files-ignore
  tools/legal-review/project-manager/io.circe.circe-generic_2.13-0.14.0-M1/files-ignore
  tools/legal-review/project-manager/io.circe.circe-jawn_2.13-0.14.0-M1/files-ignore
  tools/legal-review/project-manager/io.circe.circe-literal_2.13-0.14.0-M1/files-ignore
  tools/legal-review/project-manager/io.circe.circe-numbers_2.13-0.14.0-M1/files-ignore
  tools/legal-review/project-manager/io.circe.circe-parser_2.13-0.14.0-M1/files-ignore
  tools/legal-review/project-manager/io.circe.circe-yaml_2.13-0.13.1/files-ignore
  tools/legal-review/project-manager/nl.gn0s1s.bump_2.13-0.1.3/files-ignore
  tools/legal-review/project-manager/org.typelevel.cats-core_2.13-2.2.0-M3/files-keep
  tools/legal-review/project-manager/org.typelevel.cats-kernel_2.13-2.2.0-M3/files-ignore
  tools/legal-review/project-manager/org.typelevel.cats-kernel_2.13-2.2.0-M3/files-keep
  tools/legal-review/project-manager/report-state
  tools/legal-review/std-lib-Image/report-state
Labels: Category: Build, Change: Non-Breaking, Difficulty: Intermediate, Priority: High, Type: Enhancement

#1729 Rewrite Docs Generator from Python to Scala/Java
  .github/workflows/scala.yml
  .gitignore
  RELEASES.md
  build.sbt
  lib/scala/docs-generator/README.md
  lib/scala/docs-generator/src/main/scala/org/enso/docs/generator/Constants.scala
  lib/scala/docs-generator/src/main/scala/org/enso/docs/generator/DocsGenerator.scala
  lib/scala/docs-generator/src/main/scala/org/enso/docs/generator/Main.scala
  lib/scala/docs-generator/src/main/scala/org/enso/docs/generator/TreeOfCommonPrefixes.scala
  lib/scala/docs-generator/src/main/scala/org/enso/docs/generator/template.js
  lib/scala/docs-generator/src/main/scala/org/enso/docs/generator/treeStyle.css
  lib/scala/parser-service/src/main/scala/org/enso/ParserService.scala
  lib/scala/syntax/specialization/js/src/main/scala/org/enso/syntax/text/Main.scala
  lib/scala/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/DocParser.scala
  lib/scala/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/Parser.scala
  lib/scala/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/docparser/DocParserHTMLGenerator.scala
  lib/scala/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/docparser/DocParserRunner.scala
Labels: Category: Documentation, Category: Syntax, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Size: Medium, Type: Enhancement

#1719 Log Akka Messages
  build.sbt
  engine/language-server/src/main/scala/org/enso/languageserver/boot/LanguageServerConfig.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistry.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistryProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/RuntimeKiller.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/StackItem.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/VisualisationConfiguration.scala
  engine/launcher/src/main/scala/org/enso/launcher/Launcher.scala
  engine/launcher/src/main/scala/org/enso/launcher/cli/LauncherApplication.scala
  engine/launcher/src/main/scala/org/enso/launcher/components/LauncherRunner.scala
  engine/launcher/src/test/scala/org/enso/launcher/components/LauncherRunnerSpec.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/Suggestion.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  lib/scala/logging-service/src/main/scala/org/enso/logger/akka/ActorLoggingReceive.scala
  lib/scala/logging-service/src/main/scala/org/enso/logger/akka/ActorMessageLogging.scala
  lib/scala/logging-service/src/main/scala/org/enso/loggingservice/LoggerFactory.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/MainModule.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/ProjectManager.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/ExecutorWithUnlimitedPool.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/HeartbeatSession.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerBootLoader.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerController.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/config/GlobalConfigurationManager.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/runner/Runner.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1747 Remove the EPB GIL for GraalPython
  .gitignore
  engine/runtime/src/main/java/org/enso/interpreter/epb/node/CoercePrimitiveNode.java
  engine/runtime/src/main/java/org/enso/interpreter/epb/node/ContextRewrapExceptionNode.java
  engine/runtime/src/main/java/org/enso/interpreter/epb/node/ContextRewrapNode.java
  engine/runtime/src/main/java/org/enso/interpreter/epb/node/ForeignEvalNode.java
  engine/runtime/src/main/java/org/enso/interpreter/epb/node/PyForeignNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/ArrayBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/BooleanBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/BooleanConstructorBranchNode.java
  test/Tests/src/Semantic/Js_Interop_Spec.enso
  test/Tests/src/Semantic/Python_Interop_Spec.enso
  test/Tests/src/Semantic/R_Interop_Spec.enso
Labels: Category: Interpreter, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1749 Add Oneshot Visualization
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonRpc.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/visualisation/ExecuteExpressionHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextEventsListener.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistry.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistryProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/VisualisationApi.scala
  engine/language-server/src/test/scala/org/enso/languageserver/runtime/ContextEventsListenerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/ContextRegistryTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/ExecutionContextJsonMessages.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1757 Update the Protocol to Support Streaming Files
  distribution/std-lib/Standard/src/Visualization.enso
  distribution/std-lib/Standard/src/Visualization/File_Upload.enso
  docs/language-server/README.md
  docs/language-server/protocol-language-server.md
  docs/language-server/streaming-file-transfer.md
  test/Visualization_Tests/src/Main.enso
  test/Visualization_Tests/src/Visualization_Spec.enso
Labels: Category: Backend, Category: Documentation, Category: Stdlib, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1759 Provide Access to the Project Name
  RELEASES.md
  build.sbt
  docs/language-server/protocol-language-server.md
  docs/language-server/protocol-project-manager.md
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/data/Config.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionControllerFactory.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonRpc.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/workspace/ProjectInfoHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/workspace/WorkspaceApi.scala
  engine/language-server/src/test/resources/package.yaml
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/WorkspaceOperationsTest.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/data/RunningLanguageServerInfo.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/protocol/ProjectManagementApi.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/ProjectOpenHandler.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectService.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/ProjectManagementOps.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala
  tools/legal-review/engine/report-state
Labels: Category: Backend, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1763 Update the FlatBuffers Schemas with the New Design
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/binary/factory/ErrorFactory.scala
  engine/language-server/src/main/schema/binary_protocol.fbs
Labels: Category: Backend, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement
