Repository enso-org/enso, pull requests merged in 2021-11, with the labels that each got.

#3129 Bump rustc to nightly-2021-10-21
  .github/workflows/gui.yml
  gui/build/workflow.js
  gui/run
  gui/rust-toolchain
  gui/src/rust/ensogl/example/src/lib.rs
  gui/src/rust/ensogl/example/src/list_view.rs
  gui/src/rust/ensogl/lib/components/src/drop_down_menu.rs
  gui/src/rust/ensogl/lib/components/src/label.rs
  gui/src/rust/ensogl/lib/core/src/display/shape/primitive/shader/builder.rs
  gui/src/rust/ensogl/lib/core/src/display/shape/primitive/shader/canvas.rs
  gui/src/rust/ensogl/lib/core/src/lib.rs
  gui/src/rust/ensogl/lib/text/src/buffer/view.rs
  gui/src/rust/ensogl/lib/text/src/buffer/view/movement.rs
  gui/src/rust/ide/lib/ast/impl/src/lib.rs
  gui/src/rust/ide/lib/ast/impl/src/prefix.rs
  gui/src/rust/ide/lib/enso-protocol/src/lib.rs
  gui/src/rust/ide/src/controller/project.rs
  gui/src/rust/ide/src/double_representation/refactorings/collapse.rs
  gui/src/rust/ide/src/ide.rs
  gui/src/rust/ide/src/ide/integration/visualization.rs
  gui/src/rust/ide/view/graph-editor/src/builtin/visualization/native/bubble_chart.rs
  gui/src/rust/ide/view/graph-editor/src/component/edge.rs
  gui/src/rust/ide/view/graph-editor/src/component/visualization/container.rs
  gui/src/rust/ide/view/graph-editor/src/lib.rs
  gui/src/rust/ide/view/src/lib.rs
  gui/src/rust/lib/frp/src/data/watch.rs
  gui/src/rust/lib/frp/src/debug.rs
  gui/src/rust/lib/frp/src/io/keyboard.rs
  gui/src/rust/lib/frp/src/nodes.rs
Labels: Type: Enhancement, Difficulty: Intermediate

#3138 Disable ProjectManagementApiSpec
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala
Labels: Type: Bug, Change: Non-Breaking, Priority: Medium, Category: Backend

#3158 Set Locale in Tests
  test/Tests/src/Data/Locale_Spec.enso
  test/Tests/src/Main.enso
Labels: Type: Bug, Difficulty: Core Contributor, Change: Non-Breaking, Priority: Medium, Category: Build

#1981 Preinstalling With Dependencies
  .github/workflows/scala.yml
  .gitignore
  RELEASES.md
  build.sbt
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/libraries/CompilerBasedDependencyExtractor.scala
  engine/language-server/src/main/scala/org/enso/languageserver/libraries/LibraryApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/libraries/LibraryInstallerConfig.scala
  engine/language-server/src/main/scala/org/enso/languageserver/libraries/handler/LibraryPreinstallHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/libraries/handler/LibraryPublishHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/LibrariesTest.scala
  engine/launcher/src/main/scala/org/enso/launcher/Constants.scala
  engine/launcher/src/main/scala/org/enso/launcher/Launcher.scala
  engine/launcher/src/main/scala/org/enso/launcher/cli/LauncherApplication.scala
  engine/launcher/src/main/scala/org/enso/launcher/components/LauncherRunner.scala
  engine/polyglot-api/src/main/java/org/enso/polyglot/MethodNames.java
  engine/polyglot-api/src/main/scala/org/enso/polyglot/Module.scala
  engine/polyglot-api/src/test/scala/org/enso/polyglot/ModuleManagementTest.scala
  engine/runner/src/main/scala/org/enso/runner/DependencyPreinstaller.scala
  engine/runner/src/main/scala/org/enso/runner/Main.scala
  engine/runner/src/main/scala/org/enso/runner/ProjectUploader.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/PackageRepository.scala
  lib/scala/library-manager-test/src/main/scala/org/enso/librarymanager/published/repository/DummyRepository.scala
  lib/scala/library-manager-test/src/test/scala/org/enso/libraryupload/LibraryUploadTest.scala
  lib/scala/library-manager/src/main/scala/org/enso/librarymanager/DefaultLibraryProvider.scala
  lib/scala/library-manager/src/main/scala/org/enso/librarymanager/ResolvingLibraryProvider.scala
  lib/scala/library-manager/src/main/scala/org/enso/librarymanager/dependencies/Dependency.scala
  lib/scala/library-manager/src/main/scala/org/enso/librarymanager/dependencies/DependencyResolver.scala
  lib/scala/library-manager/src/main/scala/org/enso/librarymanager/published/CachedLibraryProvider.scala
  lib/scala/library-manager/src/main/scala/org/enso/librarymanager/published/DefaultPublishedLibraryProvider.scala
  lib/scala/library-manager/src/main/scala/org/enso/librarymanager/published/PublishedLibraryCache.scala
  lib/scala/library-manager/src/main/scala/org/enso/librarymanager/published/cache/DownloadingLibraryCache.scala
  lib/scala/library-manager/src/main/scala/org/enso/libraryupload/DependencyExtractor.scala
  lib/scala/library-manager/src/main/scala/org/enso/libraryupload/LibraryUploader.scala
  lib/scala/logging-service/src/main/scala/org/enso/loggingservice/internal/service/ThreadProcessingService.scala
  project/LibraryManifestGenerator.scala
Labels: Type: Enhancement, Difficulty: Core Contributor, Category: Tooling, Change: Non-Breaking, Priority: High, Category: Libraries, Category: Backend
