Repository enso-org/enso, pull requests merged in 2021-01, with the labels that each got.

#1381 Implement Some Vectorized Text Operations And Dropping Missing
  distribution/std-lib/Base/src/Data/Text/Extensions.enso
  distribution/std-lib/Base/src/Data/Vector.enso
  distribution/std-lib/Table/src/Data/Column.enso
  distribution/std-lib/Table/src/Data/Table.enso
  std-bits/src/main/java/org/enso/base/Text_Utils.java
  table/src/main/java/org/enso/table/data/column/operation/map/text/StringBooleanOp.java
  table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java
  table/src/main/java/org/enso/table/data/column/storage/DoubleStorage.java
  table/src/main/java/org/enso/table/data/column/storage/LongStorage.java
  table/src/main/java/org/enso/table/data/column/storage/ObjectStorage.java
  table/src/main/java/org/enso/table/data/column/storage/Storage.java
  table/src/main/java/org/enso/table/data/column/storage/StringStorage.java
  table/src/main/java/org/enso/table/data/table/Column.java
  table/src/main/java/org/enso/table/data/table/Table.java
  test/Table_Tests/src/Table_Spec.enso
  test/Tests/src/Data/Vector_Spec.enso
Labels: Category: Libraries, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1387 Switch from Staging to Main Repository
  RELEASES.md
  build.sbt
  docs/distribution/packaging.md
  docs/distribution/release-policy.md
  docs/getting-enso.md
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/releases/engine/EngineRepository.scala
Labels: Category: Distribution, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1389 Update the `main` Branch After Making the First Release
  .github/settings.yml
  build.sbt
  distribution/launcher-manifest.yaml
  distribution/manifest.template.yaml
  docs/distribution/release-policy.md
  docs/getting-enso.md
Labels: Category: Build, Category: Documentation, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1380 Fix doc parser's tags and unrecognized characters.
  distribution/std-lib/Base/src/Data/Text/Extensions.enso
  lib/scala/syntax/definition/src/main/scala/org/enso/syntax/text/spec/DocParserDef.scala
Labels: Category: Documentation, Category: Syntax, Change: Non-Breaking, Difficulty: Intermediate, Priority: High, Size: Small, Type: Enhancement

#1375 Return Correct Name for the Module in AtomConstructor
  engine/runtime/src/main/java/org/enso/interpreter/node/MethodRootNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/AtomConstructor.java
  lib/rust/parser/Cargo.toml
Labels: Category: Backend, Category: RTS, Difficulty: Core Contributor, Priority: High, Type: Bug

#1376 Use Qualified Names in Runtime Updates
  engine/runtime/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/TopLevelScope.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/type/Constants.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/type/Types.java
  engine/runtime/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/RenameProjectCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/context/SuggestionBuilderTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/SuggestionUpdatesTest.scala
  lib/scala/pkg/src/main/scala/org/enso/pkg/QualifiedName.scala
Labels: Category: Backend, Category: Interpreter, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1392 Table: grouping
  distribution/std-lib/Base/src/Data/Vector.enso
  distribution/std-lib/Table/src/Data/Column.enso
  distribution/std-lib/Table/src/Data/Table.enso
  distribution/std-lib/Table/src/Main.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/mutable/CopyNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Error.java
  table/src/main/java/org/enso/table/data/column/operation/aggregate/Aggregator.java
  table/src/main/java/org/enso/table/data/column/operation/aggregate/CountAggregator.java
  table/src/main/java/org/enso/table/data/column/operation/aggregate/FunctionAggregator.java
  table/src/main/java/org/enso/table/data/column/operation/aggregate/numeric/LongToLongAggregator.java
  table/src/main/java/org/enso/table/data/column/operation/aggregate/numeric/NumericAggregator.java
  table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java
  table/src/main/java/org/enso/table/data/column/storage/DoubleStorage.java
  table/src/main/java/org/enso/table/data/column/storage/LongStorage.java
  table/src/main/java/org/enso/table/data/column/storage/NumericStorage.java
  table/src/main/java/org/enso/table/data/column/storage/ObjectStorage.java
  table/src/main/java/org/enso/table/data/column/storage/Storage.java
  table/src/main/java/org/enso/table/data/column/storage/StringStorage.java
  table/src/main/java/org/enso/table/data/index/DefaultIndex.java
  table/src/main/java/org/enso/table/data/index/HashIndex.java
  table/src/main/java/org/enso/table/data/index/Index.java
  table/src/main/java/org/enso/table/data/table/Column.java
  table/src/main/java/org/enso/table/data/table/Table.java
  table/src/main/java/org/enso/table/data/table/aggregate/AggregateColumn.java
  table/src/main/java/org/enso/table/data/table/aggregate/AggregateTable.java
  test/Table_Tests/src/Table_Spec.enso
Labels: Category: Stdlib, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1394 Fix Reflection Configuration for Project Manager
  build.sbt
  docs/infrastructure/native-image.md
  lib/scala/project-manager/src/main/resources/META-INF/native-image/org/enso/projectmanager/reflect-config.json
  project/VerifyReflectionSetup.scala
Labels: Category: Build, Category: Tooling, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Bug

#1397 Builtins Documentation
  build.sbt
  distribution/std-lib/Base/src/Meta/Enso_Project.enso
  docs/distribution/README.md
  docs/distribution/standard-libraries.md
  docs/syntax/comments.md
  engine/runtime/src/main/java/org/enso/interpreter/Language.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/RecoverPanicNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/mutable/CopyNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/mutable/NewRefNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/runtime/GCNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/OptimizeNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/constant/EnsoProjectNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Context.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  engine/runtime/src/main/resources/Builtins.enso
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/Passes.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstToIr.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/InlineContext.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/ModuleContext.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/CachePreferenceAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DataflowAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/TailCall.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/ComplexType.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/FunctionBinding.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/lint/UnusedBindings.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/DocumentationComments.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/ExpressionAnnotations.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/ModuleAnnotations.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/SuspendedArguments.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/TypeSignatures.scala
  engine/runtime/src/main/scala/org/enso/compiler/phase/BuiltinsIrBuilder.scala
  engine/runtime/src/main/scala/org/enso/compiler/phase/StubIrBuilder.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/PassesTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/codegen/AstToIrTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/ComplexTypeTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/ExpressionAnnotationsTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/ModuleAnnotationsTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/TypeSignaturesTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/InterpreterTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/ReplTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/ImportsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/OverloadsResolutionErrorTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/StrictCompileDiagnosticsTest.scala
  lib/scala/cli/src/main/scala/org/enso/cli/arguments/Application.scala
  lib/scala/syntax/definition/src/main/scala/org/enso/syntax/text/ast/meta/Builtin.scala
  test/Tests/src/Semantic/Case_Spec.enso
Labels: Category: Documentation, Category: Stdlib, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1399 Better Component Bundling for Project Manager
  .github/workflows/release.yml
  .github/workflows/scala.yml
  build.sbt
  distribution/enso.bundle.template
  docs/distribution/README.md
  docs/distribution/bundles.md
  docs/distribution/fallback-launcher-release-infrastructure.md
  docs/distribution/local-repository.md
  docs/distribution/standard-libraries.md
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/Cli.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/ProjectManager.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/versionmanagement/RuntimeVersionManagerErrorRecoverySyntax.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/versionmanagement/DefaultDistributionConfiguration.scala
  lib/scala/runtime-version-manager-test/src/main/scala/org/enso/runtimeversionmanager/test/TestRuntimeVersionManagementUserInterface.scala
  lib/scala/runtime-version-manager-test/src/test/scala/org/enso/runtimeversionmanager/components/LocalReleaseProviderSpec.scala
  lib/scala/runtime-version-manager-test/src/test/scala/org/enso/runtimeversionmanager/components/RuntimeVersionManagerSpec.scala
  lib/scala/runtime-version-manager-test/src/test/scala/org/enso/runtimeversionmanager/distributuion/DistributionManagerSpec.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/ComponentsException.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/Engine.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/GraalRuntime.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/RuntimeVersionManager.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/distribution/DistributionManager.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/distribution/PortableDistributionManager.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/releases/engine/EngineRepository.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/releases/graalvm/GraalCEReleaseProvider.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/releases/local/LocalReleaseProvider.scala
  project/DistributionPackage.scala
  tools/ci/prepare-distribution-env.sh
Labels: Category: Build, Category: Distribution, Category: Tooling, Change: Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1395 Fix for SQLite DB busy error on Azure
  engine/language-server/src/main/scala/org/enso/languageserver/boot/DeploymentType.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/SuggestionsHandlerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  lib/scala/searcher/src/main/resources/reference.conf
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlDatabase.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sqlite/LockingMode.scala
  tools/ci/docker/Dockerfile
Labels: Category: Distribution, Change: Breaking, Difficulty: Core Contributor, Priority: Medium, Size: Small, Type: Bug

#1407 Add Time Profiling Information to the Protocol
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextEventsListener.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ExpressionValueUpdate.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ProfilingInfo.scala
  engine/language-server/src/test/scala/org/enso/languageserver/runtime/ContextEventsListenerSpec.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime/src/main/java/org/enso/interpreter/Language.java
  engine/runtime/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java
  engine/runtime/src/main/java/org/enso/interpreter/instrument/profiling/ExecutionTime.java
  engine/runtime/src/main/java/org/enso/interpreter/instrument/profiling/ProfilingInfo.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Context.java
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/Timer.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/ValueEquality.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1413 Add Null Check when Executing Host Values
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/syntax/HostValueToEnsoNode.java
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
Labels: Category: RTS, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Bug

#1419 Update Main.enso
  lib/scala/pkg/src/main/resources/Main.enso
Labels: Category: Distribution, Change: Non-Breaking, Size: Small, Type: Enhancement

#1421 Fix Dataflow Analysis of Undefined Variables
  engine/runtime/src/main/scala/org/enso/compiler/Passes.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/UndefinedVariables.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/DataflowAnalysisTest.scala
Labels: Category: Compiler, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Bug

#1405 Resolve Expression Ids for Errors
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonRpc.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextEventsListener.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistry.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistryProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ExecutionApi.scala
  engine/language-server/src/test/scala/org/enso/languageserver/runtime/ContextEventsListenerSpec.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/ErrorResolver.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/LocationResolver.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ExecutionItem.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/ExpressionErrorsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1422 Add API for Dataflow Errors
  .gitignore
  Cargo.lock
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextEventsListener.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistryProtocol.scala
  engine/language-server/src/test/scala/org/enso/languageserver/runtime/ContextEventsListenerSpec.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/ErrorResolver.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/ExpressionErrorsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1420 Docker refinement
  .github/workflows/release.yml
  engine/runner/src/main/scala/org/enso/runner/LanguageServerApp.scala
  tools/ci/docker/Dockerfile
  tools/ci/docker/docker-entrypoint.sh
Labels: Category: Distribution, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Size: Small, Type: Enhancement

#1426 README changes ahead of IDE tester packages
  README.md
Labels: Category: Documentation, Category: External, Difficulty: Core Contributor, Priority: Highest, Size: Small, Type: Enhancement

#1433 Dataflow Errors
  README.md
  distribution/std-lib/Test/src/Test.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/IndirectInvokeCallableNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/IndirectInvokeMethodNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeCallableNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/CaseNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/atom/InstantiateNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/io/PrintErrNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/io/PrintlnNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/IsAtomConstructorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/IsAtomNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/IsErrorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/IsPolyglotNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/IsSameObjectNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/IsUnresolvedSymbolNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/BitShiftNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/DivNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/ModNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/BitShiftNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/DivNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/ModNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/state/GetStateNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/state/PutStateNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Error.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicSentinel.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/type/Types.java
  engine/runtime/src/main/resources/Builtins.enso
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/DataflowErrorsTest.scala
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/AcceptsError.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/MethodProcessor.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/model/MethodDefinition.java
  test/Tests/src/Data/Noise/Generator_Spec.enso
  test/Tests/src/Data/Numbers_Spec.enso
Labels: Category: Interpreter, Category: RTS, Category: Semantics, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement
