Repository enso-org/enso, pull requests merged in 2021-09, with the labels that each got.

#1982 Add `Column.set_index`
  RELEASES.md
  distribution/lib/Standard/Table/0.2.28-SNAPSHOT/src/Data/Column.enso
  distribution/lib/Standard/Table/0.2.28-SNAPSHOT/src/Data/Table.enso
  std-bits/table/src/main/java/org/enso/table/data/index/Index.java
  std-bits/table/src/main/java/org/enso/table/data/table/Column.java
  std-bits/table/src/main/java/org/enso/table/data/table/Table.java
  test/Table_Tests/src/Column_Spec.enso
  test/Table_Tests/src/Table_Spec.enso
Labels: Type: Enhancement, Difficulty: Core Contributor, Change: Non-Breaking, Priority: Highest, Category: Libraries, echoes/effort: XS, echoes/intent: users/libraries

#1990 Statistical functions
  RELEASES.md
  distribution/lib/Standard/Table/0.2.29-SNAPSHOT/src/Data/Column.enso
  test/Table_Tests/src/Column_Spec.enso
Labels: Type: Enhancement, Difficulty: Core Contributor, Priority: Highest, Category: Stdlib, echoes/intent: technology

#1991 Write IR to the Cache
  .gitignore
  RELEASES.md
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/polyglot-api/src/main/java/org/enso/polyglot/RuntimeOptions.java
  engine/runner/src/main/scala/org/enso/runner/ContextFactory.scala
  engine/runner/src/main/scala/org/enso/runner/Main.scala
  engine/runtime/src/main/java/org/enso/interpreter/Language.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Context.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/ThreadManager.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/ModuleCache.scala
  engine/runtime/src/main/scala/org/enso/compiler/SerializationManager.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/ir/DiagnosticStorage.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/ir/MetadataStorage.scala
  engine/runtime/src/main/scala/org/enso/compiler/data/BindingsMap.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/IRPass.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/CachePreferenceAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DataflowAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/GatherDiagnostics.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/TailCall.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/optimise/ApplicationSaturation.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/DocumentationComments.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/IgnoredBindings.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/ModuleAnnotations.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/TypeSignatures.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/core/ir/MetadataStorageTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/InterpreterTest.scala
  test/Tests/src/Data/Text_Spec.enso
Labels: Type: Enhancement, Difficulty: Core Contributor, Category: Compiler, Change: Non-Breaking, Priority: Highest, echoes/effort: L, echoes/intent: technology/runtime

#1989 Simple Fix for Native Image Rebuild
  project/NativeImage.scala
Labels: Type: Enhancement, Difficulty: Beginner, Change: Non-Breaking, Priority: High, Category: Build, echoes/effort: XS, echoes/intent: technology

#1993 Add log.masking runtime option
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/polyglot-api/src/main/java/org/enso/polyglot/RuntimeOptions.java
  engine/runner/src/main/scala/org/enso/runner/ContextFactory.scala
  engine/runner/src/main/scala/org/enso/runner/Main.scala
  engine/runtime/src/main/java/org/enso/interpreter/Language.java
  lib/scala/logging-utils/src/main/java/org/enso/logger/masking/MaskingFactory.java
Labels: Type: Bug, Difficulty: Core Contributor, Change: Non-Breaking, Priority: High, Category: Backend

#1997 Remove Accidentally Committed Import_Test
  Import_Test/package.yaml
  Import_Test/src/Foo.enso
  Import_Test/src/Main.enso
Labels: Type: Enhancement, Difficulty: Core Contributor, Change: Non-Breaking, Priority: Highest, Category: Build, echoes/effort: XS, echoes/intent: risks, echoes/intent: technology

#1998 Implement a `--compile` Command for the Engine Runner
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/scala.yml
  RELEASES.md
  engine/polyglot-api/src/main/java/org/enso/polyglot/MethodNames.java
  engine/polyglot-api/src/main/java/org/enso/polyglot/RuntimeOptions.java
  engine/polyglot-api/src/main/scala/org/enso/polyglot/TopScope.scala
  engine/runner/src/main/scala/org/enso/runner/ContextFactory.scala
  engine/runner/src/main/scala/org/enso/runner/Main.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Context.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/TopLevelScope.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/type/Types.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/ModuleCache.scala
  engine/runtime/src/main/scala/org/enso/compiler/PackageRepository.scala
  engine/runtime/src/main/scala/org/enso/compiler/SerializationManager.scala
  lib/scala/pkg/src/main/scala/org/enso/pkg/Package.scala
  test/Tests/src/Main.enso
Labels: Type: Enhancement, Difficulty: Core Contributor, Category: Compiler, Category: Tooling, Change: Non-Breaking, Priority: Highest, echoes/effort: XL, echoes/intent: technology

#2000 Auto Parallelism
  RELEASES.md
  engine/polyglot-api/src/main/java/org/enso/polyglot/RuntimeOptions.java
  engine/runner/src/main/scala/org/enso/runner/ContextFactory.scala
  engine/runner/src/main/scala/org/enso/runner/Main.scala
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/special/JoinThreadNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/special/NewRefNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/special/ReadRefNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/special/RunThreadNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/special/WriteRefNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Context.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Special.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Ref.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/Passes.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/main/scala/org/enso/compiler/data/BindingsMap.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/AutomaticParallelism.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DemandAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/optimise/LambdaConsolidate.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/IgnoredBindings.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/MethodCalls.scala
  engine/runtime/src/main/scala/org/enso/compiler/phase/BuiltinsIrBuilder.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/AutomaticParallelismTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/UppercaseNamesTest.scala
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/MethodProcessor.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/model/MethodDefinition.java
Labels: echoes/intent: technology/runtime

#2002 Enable Caches by Default for the Nightly Runner
  engine/runner/src/main/scala/org/enso/runner/Main.scala
Labels: Type: Enhancement, Difficulty: Beginner, Category: Tooling, Change: Non-Breaking, Priority: Highest, echoes/effort: XS, echoes/intent: technology

#2003 Linear Regression (Least Squares)
  RELEASES.md
  distribution/lib/Standard/Table/0.2.31-SNAPSHOT/src/Data/Table.enso
  distribution/lib/Standard/Table/0.2.31-SNAPSHOT/src/Main.enso
  distribution/lib/Standard/Table/0.2.31-SNAPSHOT/src/Model.enso
  test/Table_Tests/src/Main.enso
  test/Table_Tests/src/Model_Spec.enso
Labels: Type: Enhancement, Difficulty: Core Contributor, Change: Non-Breaking, Priority: Highest, Category: Stdlib, echoes/effort: S, echoes/intent: users/libraries
