Repository enso-org/enso, pull requests merged in 2021-06, with the labels that each got.

#1758 Add HTML Documentation API
  docs/language-server/protocol-language-server.md
  docs/runtime/searcher.md
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/WorkspaceOperationsTest.scala
Labels: Category: Documentation, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1778 FlatBuffers Schema Fix
  engine/language-server/src/main/schema/binary_protocol.fbs
Labels: Category: Backend, Change: Breaking, Difficulty: Beginner, Priority: Highest, Size: Small, Type: Bug

#1786 Default visualization definitions
  RELEASES.md
  distribution/std-lib/Standard/src/Base/Meta/Enso_Project.enso
  distribution/std-lib/Standard/src/Table/Data/Table.enso
  distribution/std-lib/Standard/src/Visualization.enso
  distribution/std-lib/Standard/src/Visualization/Id.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/constant/EnsoProjectNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  test/Table_Tests/src/Table_Spec.enso
  test/Tests/src/Semantic/Meta_Spec.enso
  test/Visualization_Tests/src/Id_Spec.enso
  test/Visualization_Tests/src/Main.enso
Labels: Category: Stdlib, Change: Non-Breaking, Difficulty: Beginner, Priority: Highest, Type: Enhancement

#1787 Add Support for the `file/checksum` Endpoint
  RELEASES.md
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManager.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystem.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemFailure.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemFailureMapper.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonRpc.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/ChecksumFileHandler.scala
  engine/language-server/src/main/schema/binary_protocol.fbs
  engine/language-server/src/test/scala/org/enso/languageserver/filemanager/FileSystemSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/FileManagerTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1795 Implement Byte-Based File Operations
  RELEASES.md
  docs/language-server/protocol-language-server.md
  docs/language-server/streaming-file-transfer.md
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManager.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystem.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemFailure.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemFailureMapper.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/binary/BinaryConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/binary/factory/ChecksumBytesReplyFactory.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/binary/factory/EnsoDigestFactory.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/binary/factory/ErrorFactory.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/binary/factory/FileContentsReplyFactory.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/binary/factory/ReadBytesReplyFactory.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/binary/factory/WriteBytesReplyFactory.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/ChecksumBytesHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/ChecksumFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/ReadBinaryFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/ReadBytesHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/WriteBinaryFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/WriteBytesHandler.scala
  engine/language-server/src/test/scala/org/enso/languageserver/filemanager/FileSystemSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/binary/BinaryFileManipulationTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/binary/factory/ChecksumBytesCommandFactory.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/binary/factory/FileSegmentFactory.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/binary/factory/ReadBytesCommandFactory.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/binary/factory/WriteBytesCommandFactory.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/FileManagerTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1800 Refactor the LS to Support Multiple Content Roots
  .github/workflows/nightly.yml
  .github/workflows/scala.yml
  RELEASES.md
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/ResourcesInitialization.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/resource/DirectoriesInitialization.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/resource/RepoInitialization.scala
  engine/language-server/src/main/scala/org/enso/languageserver/data/Config.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/ContentRoot.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManager.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/PathWatcher.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/session/SessionApi.scala
  engine/language-server/src/test/scala/org/enso/languageserver/boot/resource/RepoInitializationSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/runtime/ContextEventsListenerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/SuggestionsHandlerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/binary/BaseBinaryServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/binary/BinaryFileManipulationTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/FileManagerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/FileNotificationsTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/ReceivesTreeUpdatesHandlerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/SessionManagementTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/WorkspaceOperationsTest.scala
Labels: Category: Backend, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1803 Document How to Run IDE with Dev Language Server
  docs/CONTRIBUTING.md
Labels: Category: Documentation, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement

#1807 Fix the Spec to Conform to the Implementation
  docs/language-server/protocol-language-server.md
Labels: Category: Documentation, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1814 Update GraalVM in Docker
  tools/ci/docker/Dockerfile
Labels: Category: Tooling, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1804 Libraries Repository
  RELEASES.md
  build.sbt
  docs/libraries/README.md
  docs/libraries/repositories.md
  lib/scala/editions/src/main/scala/org/enso/editions/EditionName.scala
  lib/scala/editions/src/main/scala/org/enso/editions/EditionResolutionError.scala
  lib/scala/editions/src/main/scala/org/enso/editions/EditionSerialization.scala
  lib/scala/editions/src/main/scala/org/enso/editions/LibraryName.scala
  lib/scala/editions/src/main/scala/org/enso/editions/repository/Manifest.scala
  lib/scala/editions/src/main/scala/org/enso/yaml/ParseError.scala
  lib/scala/editions/src/main/scala/org/enso/yaml/YamlHelper.scala
  lib/scala/editions/src/test/scala/org/enso/editions/LibraryNameSpec.scala
  lib/scala/editions/src/test/scala/org/enso/editions/repository/ManifestParserSpec.scala
  lib/scala/library-manager/src/main/scala/org/enso/librarymanager/published/repository/LibraryManifest.scala
  lib/scala/library-manager/src/test/scala/org/enso/librarymanager/published/repository/LibraryManifestParserSpec.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/http/HTTPDownload.scala
  lib/scala/runtime-version-manager/src/test/scala/org/enso/runtimeversionmanager/http/HTTPDownloadSpec.scala
  tools/simple-library-server/README.md
  tools/simple-library-server/main.js
  tools/simple-library-server/package.json
Labels: Category: Libraries, Category: Tooling, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1791 Documentation in the Suggestions Database
  RELEASES.md
  build.sbt
  distribution/engine/THIRD-PARTY/com.google.auto.service.auto-service-1.0-rc7/NOTICES
  distribution/engine/THIRD-PARTY/com.google.errorprone.error_prone_annotations-2.3.4/NOTICES
  distribution/engine/THIRD-PARTY/com.typesafe.akka.akka-http-spray-json_2.13-10.2.0-RC1/NOTICES
  distribution/engine/THIRD-PARTY/dev.zio.zio_2.13-1.0.1/NOTICES
  distribution/engine/THIRD-PARTY/io.spray.spray-json_2.13-1.3.5/NOTICES
  distribution/project-manager/THIRD-PARTY/com.typesafe.akka.akka-http-spray-json_2.13-10.2.0-RC1/NOTICES
  distribution/project-manager/THIRD-PARTY/dev.zio.zio_2.13-1.0.1/NOTICES
  distribution/project-manager/THIRD-PARTY/io.spray.spray-json_2.13-1.3.5/NOTICES
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/search/SearchProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/Suggestions.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/SuggestionsHandlerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/SuggestionsHandlerEventsTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/Suggestion.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionDiff.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/context/SuggestionBuilderTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeSuggestionUpdatesTest.scala
  lib/scala/searcher/src/bench/scala/org/enso/searcher/sql/SuggestionRandom.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/SuggestionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlSuggestionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/Tables.scala
  lib/scala/searcher/src/test/scala/org/enso/searcher/sql/SuggestionsRepoTest.scala
  tools/legal-review/engine/report-state
  tools/legal-review/project-manager/report-state
Labels: Category: Backend, Change: Breaking, Difficulty: Core Contributor, Priority: High, Size: Medium

#1815 Add Syntactic Support for Conversion Definitions
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstToIr.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstView.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/AutomaticParallelism.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/CachePreferenceAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DataflowAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DemandAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/TailCall.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/FunctionBinding.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/GenerateMethodBodies.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/LambdaShorthandToLambda.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/SectionsToBinOp.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/lint/UnusedBindings.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/optimise/LambdaConsolidate.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/DocumentationComments.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/IgnoredBindings.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/SuspendedArguments.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/CompilerTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/codegen/AstToIrTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/GatherDiagnosticsTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/FunctionBindingTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/GenerateMethodBodiesTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/optimise/LambdaConsolidateTest.scala
  lib/scala/syntax/definition/src/main/scala/org/enso/syntax/text/ast/meta/Builtin.scala
  test/Tests/src/Semantic/Js_Interop_Spec.enso
Labels: Category: Compiler, Category: Syntax, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1818 Prepare for the 0.2.11 release
  RELEASES.md
  build.sbt
Labels: Category: Distribution, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Release

#1820 Include namespace in the project manager messages
  RELEASES.md
  docs/language-server/protocol-project-manager.md
  lib/scala/pkg/src/main/scala/org/enso/pkg/Config.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/data/ProjectMetadata.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/data/RunningLanguageServerInfo.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/repository/ProjectFileRepository.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/model/Project.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/protocol/ProjectManagementApi.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/ProjectOpenHandler.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectService.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/ProjectManagementOps.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala
Labels: Category: Tooling, Change: Non-Breaking, Priority: Highest, Type: Enhancement

#1819 Document the Process for Avoiding Release Breakage
  .github/CODEOWNERS
  docs/distribution/release-policy.md
Labels: Category: Documentation, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1822 Refactor import resolver to allow for dynamic loading of modules.
  RELEASES.md
  engine/polyglot-api/src/test/scala/org/enso/polyglot/ModuleManagementTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Context.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/PackageRepository.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/main/scala/org/enso/compiler/phase/ImportResolver.scala
  engine/runtime/src/test/resources/Test_Bad_Imports/package.yaml
  engine/runtime/src/test/resources/Test_Bad_Imports/src/Main.enso
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/ImportsTest.scala
Labels: Category: Compiler, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1824 Fix the PM Not Checking To Preinstall the Graal Runtime if the Engine Was Already Installed
  RELEASES.md
  engine/launcher/src/main/scala/org/enso/launcher/Launcher.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/ExecutorWithUnlimitedPool.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectCreationService.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectService.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/BaseServerSpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/MissingComponentBehavior.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectCreateDefaultToLatestSpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectCreateHandleMissingRuntimeSpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectCreateMissingComponentsSpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectCreateSpecBase.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectOpenHandleMissingRuntimeSpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectOpenMissingComponentsSpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectOpenSpecBase.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/RuntimeVersionManager.scala
Labels: Category: Backend, Category: Distribution, Change: Non-Breaking, Difficulty: Intermediate, Priority: Highest, Type: Bug

#1821 Support for Multiple Content Roots
  RELEASES.md
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/data/Config.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/ContentRootManager.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/ContentRootManagerActor.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/ContentRootManagerProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/ContentRootManagerWrapper.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManager.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/Path.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/PathWatcher.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/ReceivesTreeUpdatesHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionControllerFactory.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonRpc.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/session/InitProtocolConnectionHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextEventsListener.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistry.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/RuntimeConnector.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/RuntimeFailureMapper.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/handler/AttachVisualisationHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/handler/CreateContextHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/handler/DestroyContextHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/handler/DetachVisualisationHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/handler/ModifyVisualisationHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/handler/PopContextHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/handler/PushContextHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/handler/RecomputeContextHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/handler/ImportModuleHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/handler/InvalidateModulesIndexHandler.scala
  engine/language-server/src/test/scala/org/enso/languageserver/boot/resource/RepoInitializationSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/filemanager/ContentRootManagerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/runtime/ContextEventsListenerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/SuggestionsHandlerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/binary/BaseBinaryServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/FileManagerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/SessionManagementTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  lib/scala/editions/src/main/scala/org/enso/editions/LibraryVersion.scala
  lib/scala/library-manager/src/main/scala/org/enso/librarymanager/LibraryLoader.scala
  lib/scala/library-manager/src/main/scala/org/enso/librarymanager/LibraryResolver.scala
  lib/scala/library-manager/src/main/scala/org/enso/librarymanager/published/DefaultPublishedLibraryProvider.scala
  lib/scala/library-manager/src/main/scala/org/enso/librarymanager/published/PublishedLibraryProvider.scala
  lib/scala/library-manager/src/test/scala/org/enso/librarymanager/LibraryResolverSpec.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement
