Repository enso-org/enso, pull requests merged in 2021-07, with the labels that each got.

#1827 Add File System Path to the Content Roots
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/ContentRoot.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/ContentRootManagerActor.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala
  engine/language-server/src/test/scala/org/enso/languageserver/boot/resource/RepoInitializationSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/filemanager/ContentRootManagerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/filemanager/ContentRootSerializationSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/runtime/ContextEventsListenerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/SuggestionsHandlerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/binary/BaseBinaryServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/FileManagerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/SessionManagementTest.scala
  lib/scala/editions/src/main/scala/org/enso/editions/LibraryName.scala
  lib/scala/editions/src/test/scala/org/enso/editions/LibraryNameSpec.scala
  lib/scala/library-manager/src/main/scala/org/enso/librarymanager/local/DefaultLocalLibraryProvider.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1744 Documentation files on disk.
  RELEASES.md
  build.sbt
  distribution/engine/THIRD-PARTY/com.google.auto.service.auto-service-1.0-rc7/NOTICES
  distribution/engine/THIRD-PARTY/com.google.errorprone.error_prone_annotations-2.3.4/NOTICES
  distribution/engine/THIRD-PARTY/com.typesafe.akka.akka-http-spray-json_2.13-10.2.0-RC1/NOTICES
  distribution/engine/THIRD-PARTY/dev.zio.zio_2.13-1.0.1/NOTICES
  distribution/engine/THIRD-PARTY/io.spray.spray-json_2.13-1.3.5/NOTICES
  distribution/project-manager/THIRD-PARTY/com.typesafe.akka.akka-http-spray-json_2.13-10.2.0-RC1/NOTICES
  distribution/project-manager/THIRD-PARTY/dev.zio.zio_2.13-1.0.1/NOTICES
  distribution/project-manager/THIRD-PARTY/io.spray.spray-json_2.13-1.3.5/NOTICES
  engine/polyglot-api/src/main/java/org/enso/polyglot/MethodNames.java
  engine/polyglot-api/src/main/scala/org/enso/polyglot/Module.scala
  engine/runner/src/main/scala/org/enso/runner/Main.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/Passes.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/ModuleContext.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/GenerateDocumentation.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/CompilerTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/PassesTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/GenerateDocumentationTest.scala
  lib/scala/docs-generator/src/bench/scala/org/enso/docs/generator/DocsGeneratorBench.scala
  lib/scala/docs-generator/src/main/scala/org/enso/docs/generator/DocParserWrapper.scala
  lib/scala/docs-generator/src/main/scala/org/enso/docs/generator/DocsGenerator.scala
  lib/scala/docs-generator/src/main/scala/org/enso/docs/generator/Main.scala
  tools/legal-review/engine/report-state
  tools/legal-review/project-manager/report-state
Labels: Category: Libraries, Change: Breaking, Difficulty: Core Contributor, Priority: High, Size: Large, Type: Enhancement

#1834 Compiler Support for Conversion Methods
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstView.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/CachePreferenceAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DataflowAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/TailCall.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/DocumentationComments.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/MethodDefinitions.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/ModuleThisToHere.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/OverloadsResolution.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/SuspendedArguments.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/AliasAnalysisTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/BindingAnalysisTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/DataflowAnalysisTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/TailCallTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/FunctionBindingTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/MethodDefinitionsTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/ModuleThisToHereTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/OverloadsResolutionTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/SuspendedArgumentsTest.scala
Labels: Category: Compiler, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1844 Prepare for the 0.2.13 Release
  RELEASES.md
  build.sbt
Labels: Category: Distribution, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Release

#1817 Updates and Fixes for the Cloud
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/language-server/src/test/scala/org/enso/languageserver/boot/resource/RepoInitializationSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/runtime/ContextEventsListenerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/SuggestionsHandlerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/FileManagerTest.scala
  lib/scala/searcher/src/bench/java/org/enso/searcher/sql/SuggestionsRepoBenchmark.java
  lib/scala/searcher/src/main/resources/reference.conf
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlDatabase.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlSuggestionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlVersionsRepo.scala
  lib/scala/searcher/src/test/scala/org/enso/searcher/sql/FileVersionsRepoTest.scala
  lib/scala/searcher/src/test/scala/org/enso/searcher/sql/SuggestionsRepoTest.scala
Labels: Category: Backend, Change: Non-Breaking, Priority: High, Type: Bug

#1845 Fix Nightly Workflows and Update Release Policy
  .github/workflows/nightly.yml
  build.sbt
  docs/distribution/nightly.md
  docs/distribution/release-policy.md
  tools/ci/nightly/bump-version.js
  tools/ci/nightly/preflight-check.js
Labels: Category: Build, Category: Distribution, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1848 Update Dockerfile for Integrating Editions with Cloud
  docs/libraries/editions.md
  tools/ci/docker/Dockerfile
Labels: Category: Backend, Category: Tooling, Change: Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1847 Add Idleness Http Endpoint
  RELEASES.md
  docs/language-server/README.md
  docs/language-server/language-server-http-endpoints.md
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/monitoring/IdlenessEndpoint.scala
  engine/language-server/src/main/scala/org/enso/languageserver/monitoring/IdlenessMonitor.scala
  engine/language-server/src/main/scala/org/enso/languageserver/monitoring/MonitoringProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionControllerFactory.scala
  engine/language-server/src/test/scala/org/enso/languageserver/TestClock.scala
  engine/language-server/src/test/scala/org/enso/languageserver/monitoring/IdlenessEndpointSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
Labels: Category: Backend, Change: Non-Breaking, Priority: High, Type: Enhancement

#1854 Bump Minimal PM/Launcher Versions for New Engine
  build.sbt
  distribution/manifest.template.yaml
  engine/runner/src/main/scala/org/enso/runner/Main.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/ProjectCreateHandler.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectCreationService.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/ProjectManagementOps.scala
  project/Editions.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1857 Fix Imports When Attaching Visualization
  RELEASES.md
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Context.java
  engine/runtime/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime/src/main/scala/org/enso/compiler/PackageRepository.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/UpsertVisualisationJob.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualisationsTest.scala
  lib/scala/editions/src/main/scala/org/enso/editions/LibraryName.scala
Labels: Category: Backend, Category: Libraries, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1858 [release: nightly] Fix `project/list` Failing If One of the Projects Could Not Resolve Its Edition
  RELEASES.md
  docs/language-server/protocol-project-manager.md
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/data/ProjectMetadata.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectService.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/BaseServerSpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1866 Fix Compilation Order
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Bug

#1868 Design Support for IR Serialisation
  docs/runtime/README.md
  docs/runtime/ir-caching.md
Labels: Category: Documentation, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1874 Prepare for the 0.2.14 release
  RELEASES.md
  build.sbt
Labels: Category: Distribution, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Release

#1869 Add Runtime Tests
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeErrorsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeStdlibTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/TestMessages.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement

#1881 Prune Versions when Verifying Modules Index
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/BufferRegistry.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/CollaborativeBuffer.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/SuggestionsHandlerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/FileNotificationsTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/SuggestionsHandlerEventsTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/OpenFileCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeErrorsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeInstrumentTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeStdlibTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeSuggestionUpdatesTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualisationsTest.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/FileVersionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/VersionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlSuggestionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlVersionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/Tables.scala
  lib/scala/searcher/src/test/scala/org/enso/searcher/sql/VersionsRepoTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Bug

#1883 Prepare for the 0.2.15 release
  RELEASES.md
  build.sbt
Labels: Category: Distribution, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Release

#1793 Add Reexport Field to Suggestions
  build.sbt
  distribution/engine/THIRD-PARTY/NOTICE
  distribution/engine/THIRD-PARTY/com.google.errorprone.error_prone_annotations-2.3.4/NOTICES
  distribution/engine/THIRD-PARTY/org.xerial.sqlite-jdbc-3.36.0.1/LICENSE
  distribution/engine/THIRD-PARTY/org.xerial.sqlite-jdbc-3.36.0.1/LICENSE.zentus
  distribution/engine/THIRD-PARTY/org.xerial.sqlite-jdbc-3.36.0.1/NOTICES
  distribution/engine/THIRD-PARTY/org.yaml.snakeyaml-1.26/NOTICES
  distribution/launcher/THIRD-PARTY/org.yaml.snakeyaml-1.26/NOTICES
  distribution/project-manager/THIRD-PARTY/org.yaml.snakeyaml-1.26/NOTICES
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/search/SearchProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/Suggestions.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/SuggestionsHandlerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/SuggestionsHandlerEventsTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/ExportedSymbol.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/ModuleExports.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/Suggestion.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java
  engine/runtime/src/main/scala/org/enso/compiler/context/ExportsBuilder.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/ModuleExportsDiff.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionDiff.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/context/SuggestionBuilderTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeStdlibTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeSuggestionUpdatesTest.scala
  lib/scala/searcher/src/bench/scala/org/enso/searcher/sql/SuggestionRandom.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/SuggestionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/data/QueryResult.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlSuggestionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlVersionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/Tables.scala
  lib/scala/searcher/src/test/scala/org/enso/searcher/sql/SuggestionsRepoTest.scala
  tools/legal-review/engine/org.xerial.sqlite-jdbc-3.36.0.1/copyright-add
  tools/legal-review/engine/org.xerial.sqlite-jdbc-3.36.0.1/copyright-ignore
  tools/legal-review/engine/org.xerial.sqlite-jdbc-3.36.0.1/copyright-keep
  tools/legal-review/engine/org.xerial.sqlite-jdbc-3.36.0.1/copyright-keep-context
  tools/legal-review/engine/org.xerial.sqlite-jdbc-3.36.0.1/custom-license
  tools/legal-review/engine/org.xerial.sqlite-jdbc-3.36.0.1/files-keep
  tools/legal-review/engine/report-state
  tools/legal-review/launcher/report-state
  tools/legal-review/project-manager/report-state
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1893 Update Codeowners And Release Policy
  .github/CODEOWNERS
  docs/distribution/release-policy.md
Labels: Category: Distribution, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1894 CSV Writing
  RELEASES.md
  distribution/lib/Standard/Base/0.1.0/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.1.0/src/Data/Text/Line_Ending_Style.enso
  distribution/lib/Standard/Base/0.1.0/src/Main.enso
  distribution/lib/Standard/Table/0.1.0/src/Data/Table.enso
  std-bits/table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/DoubleStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/LongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/ObjectStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/Storage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/StringStorage.java
  std-bits/table/src/main/java/org/enso/table/format/csv/Writer.java
  test/Table_Tests/src/Csv_Spec.enso
Labels: Category: Libraries, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1896 Add support for the ALIAS tag in docs
  RELEASES.md
  docs/syntax/comments.md
  lib/scala/syntax/definition/src/main/scala/org/enso/syntax/text/ast/Doc.scala
  lib/scala/syntax/specialization/shared/src/test/scala/org/enso/syntax/text/DocParserTests.scala
Labels: Category: Syntax, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1897 Prepare for the 0.2.16 release
  RELEASES.md
  build.sbt
Labels: Category: Distribution, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Release

#1898 Library Publishing MVP
  .github/workflows/scala.yml
  RELEASES.md
  build.sbt
  docs/language-server/protocol-language-server.md
  docs/libraries/repositories.md
  docs/libraries/sharing.md
  engine/language-server/src/main/scala/org/enso/languageserver/libraries/LibraryApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/libraries/LocalLibraryManager.scala
  engine/language-server/src/main/scala/org/enso/languageserver/libraries/LocalLibraryManagerProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/libraries/handler/LibraryPublishHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/LibrariesTest.scala
  engine/launcher/src/main/scala/org/enso/launcher/Constants.scala
  engine/launcher/src/main/scala/org/enso/launcher/Launcher.scala
  engine/launcher/src/main/scala/org/enso/launcher/cli/CLIProgressReporter.scala
  engine/launcher/src/main/scala/org/enso/launcher/cli/CLIRuntimeVersionManagementUserInterface.scala
  engine/launcher/src/main/scala/org/enso/launcher/cli/LauncherApplication.scala
  engine/launcher/src/main/scala/org/enso/launcher/components/LauncherRunner.scala
  engine/launcher/src/test/scala/org/enso/launcher/components/UploadVersionCheck.scala
  engine/runner/src/main/scala/org/enso/runner/Main.scala
  engine/runner/src/main/scala/org/enso/runner/ProjectUploader.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/NotificationHandler.scala
  lib/scala/cli/src/main/scala/org/enso/cli/task/TaskProgress.scala
  lib/scala/downloader/src/main/scala/org/enso/downloader/archive/TarGzWriter.scala
  lib/scala/downloader/src/main/scala/org/enso/downloader/http/HTTPDownload.scala
  lib/scala/downloader/src/main/scala/org/enso/downloader/http/HTTPRequestBuilder.scala
  lib/scala/editions/src/main/scala/org/enso/yaml/YamlHelper.scala
  lib/scala/library-manager-test/src/main/scala/org/enso/librarymanager/published/repository/DownloaderTest.scala
  lib/scala/library-manager-test/src/main/scala/org/enso/librarymanager/published/repository/DummyRepository.scala
  lib/scala/library-manager-test/src/main/scala/org/enso/librarymanager/published/repository/EmptyRepository.scala
  lib/scala/library-manager-test/src/main/scala/org/enso/librarymanager/published/repository/ExampleRepository.scala
  lib/scala/library-manager-test/src/test/scala/org/enso/librarymanager/published/repository/LibraryDownloadTest.scala
  lib/scala/library-manager-test/src/test/scala/org/enso/libraryupload/LibraryUploadTest.scala
  lib/scala/library-manager/src/main/scala/org/enso/librarymanager/published/repository/LibraryManifest.scala
  lib/scala/library-manager/src/main/scala/org/enso/libraryupload/LibraryUploader.scala
  lib/scala/library-manager/src/main/scala/org/enso/libraryupload/auth/Token.scala
  lib/scala/library-manager/src/test/scala/org/enso/librarymanager/published/repository/ArchiveWriter.scala
  tools/simple-library-server/main.js
  tools/simple-library-server/package.json
Labels: Category: Backend, Category: Libraries, Category: Tooling, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1900 Add Support for Documenting Modules
  RELEASES.md
  docs/syntax/comments.md
  engine/language-server/src/test/scala/org/enso/languageserver/search/Suggestions.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/DocumentationComments.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/context/SuggestionBuilderTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/FunctionBindingTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/DocumentationCommentsTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/GenerateDocumentationTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/TypeSignaturesTest.scala
Labels: Category: Compiler, Category: Syntax, Change: Breaking, Difficulty: Core Contributor, Type: Enhancement

#1902 Add Support for Project Templates
  RELEASES.md
  docs/language-server/protocol-project-manager.md
  engine/launcher/src/main/scala/org/enso/launcher/Launcher.scala
  engine/launcher/src/main/scala/org/enso/launcher/cli/LauncherApplication.scala
  engine/launcher/src/test/scala/org/enso/launcher/components/LauncherRunnerSpec.scala
  engine/runner/src/main/scala/org/enso/runner/Main.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/util/TruffleFileSystem.java
  lib/scala/pkg/src/main/resources/default/src/Main.enso
  lib/scala/pkg/src/main/resources/example/hello.txt
  lib/scala/pkg/src/main/resources/example/src/Main.enso
  lib/scala/pkg/src/main/scala/org/enso/filesystem/FileSystem.scala
  lib/scala/pkg/src/main/scala/org/enso/pkg/Package.scala
  lib/scala/pkg/src/main/scala/org/enso/pkg/Template.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/protocol/ProjectManagementApi.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/ProjectCreateHandler.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectCreationService.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectCreationServiceApi.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectService.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectServiceApi.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/ProjectManagementOps.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectOpenSpecBase.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/runner/Runner.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1905 Prepare for the 0.2.17 release
  RELEASES.md
  build.sbt
Labels: Category: Distribution, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Release

#1906 Write XLSX files
  RELEASES.md
  distribution/lib/Standard/Table/0.1.0/src/Data/Table.enso
  distribution/lib/Standard/Table/0.1.0/src/Io/Spreadsheet_Write_Mode.enso
  distribution/lib/Standard/Table/0.1.0/src/Main.enso
  std-bits/table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/DoubleStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/LongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/ObjectStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/Storage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/StringStorage.java
  std-bits/table/src/main/java/org/enso/table/format/csv/Writer.java
  std-bits/table/src/main/java/org/enso/table/format/util/FileSplitter.java
  std-bits/table/src/main/java/org/enso/table/format/xlsx/Writer.java
  test/Table_Tests/src/Spreadsheet_Spec.enso
Labels: Category: Stdlib, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1907 Add Aliases to the Standard Library
  distribution/lib/Standard/Base/0.1.0/src/Data/Any/Extensions.enso
  distribution/lib/Standard/Base/0.1.0/src/Data/Json.enso
  distribution/lib/Standard/Base/0.1.0/src/Data/Number/Extensions.enso
  distribution/lib/Standard/Base/0.1.0/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.1.0/src/Data/Time.enso
  distribution/lib/Standard/Base/0.1.0/src/Data/Time/Date.enso
  distribution/lib/Standard/Base/0.1.0/src/Data/Time/Zone.enso
  distribution/lib/Standard/Base/0.1.0/src/Math.enso
  distribution/lib/Standard/Base/0.1.0/src/Network/Http.enso
  distribution/lib/Standard/Base/0.1.0/src/Network/Http/Header.enso
  distribution/lib/Standard/Base/0.1.0/src/Network/Uri.enso
  distribution/lib/Standard/Base/0.1.0/src/System/Environment.enso
  distribution/lib/Standard/Base/0.1.0/src/System/File.enso
  distribution/lib/Standard/Base/0.1.0/src/System/Process.enso
  distribution/lib/Standard/Searcher/package.yaml
  distribution/lib/Standard/Searcher/src/Main.enso
  distribution/lib/Standard/Table/0.1.0/src/Data/Column.enso
  distribution/lib/Standard/Table/0.1.0/src/Data/Table.enso
  distribution/lib/Standard/Table/0.1.0/src/Io/Csv.enso
  distribution/lib/Standard/Table/0.1.0/src/Io/Spreadsheet.enso
  distribution/lib/Standard/Table/0.1.0/src/Main.enso
  engine/runtime/src/main/resources/Builtins.enso
Labels: Category: Stdlib, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1908 Return Project Name when Creating a Project
  docs/language-server/protocol-project-manager.md
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/protocol/ProjectManagementApi.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/ProjectCreateHandler.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectService.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectServiceApi.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/ProjectManagementOps.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectOpenSpecBase.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1910 Searcher Category Docs
  RELEASES.md
  distribution/lib/Standard/Base/0.1.0/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Searcher/0.1.0/package.yaml
  distribution/lib/Standard/Searcher/0.1.0/src/Data_Science.enso
  distribution/lib/Standard/Searcher/0.1.0/src/Data_Science/Aggregate.enso
  distribution/lib/Standard/Searcher/0.1.0/src/Data_Science/Compare.enso
  distribution/lib/Standard/Searcher/0.1.0/src/Data_Science/Date_And_Time.enso
  distribution/lib/Standard/Searcher/0.1.0/src/Data_Science/Input_And_Output.enso
  distribution/lib/Standard/Searcher/0.1.0/src/Data_Science/Join.enso
  distribution/lib/Standard/Searcher/0.1.0/src/Data_Science/Numbers.enso
  distribution/lib/Standard/Searcher/0.1.0/src/Data_Science/Preparation.enso
  distribution/lib/Standard/Searcher/0.1.0/src/Data_Science/Text.enso
  distribution/lib/Standard/Searcher/0.1.0/src/Data_Science/Transform.enso
  distribution/lib/Standard/Searcher/0.1.0/src/Main.enso
  distribution/lib/Standard/Searcher/0.1.0/src/Network.enso
  distribution/lib/Standard/Searcher/0.1.0/src/Network/Http.enso
  distribution/lib/Standard/Searcher/0.1.0/src/System.enso
  distribution/lib/Standard/Searcher/0.1.0/src/System/Environment.enso
  distribution/lib/Standard/Searcher/0.1.0/src/System/Filesystem.enso
  distribution/lib/Standard/Searcher/0.1.0/src/System/Process.enso
  distribution/lib/Standard/Table/0.1.0/src/Data/Table.enso
Labels: Category: Stdlib, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement, echoes/effort: M, echoes/intent: users/documentation

#1912 Support Types Unions in Suggestions Database
  engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/context/SuggestionBuilderTest.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/Tables.scala
Labels: Category: Backend, Change: Non-Breaking, Priority: High, Type: Bug
