Repository enso-org/enso, pull requests merged in 2021-03, with the labels that each got.

#1528 Make panic messages short
  engine/polyglot-api/src/test/scala/org/enso/polyglot/ModuleManagementTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicException.java
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/ReplTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/CaseTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/ConstructorsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/ImportsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/MethodsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/PatternMatchTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/SystemProcessTest.scala
Labels: Category: Semantics, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1532 Fix Invalidation of Dynamic Dependencies
  engine/runtime/src/main/scala/org/enso/compiler/context/ChangesetBuilder.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DataflowAnalysis.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
Labels: Category: Backend, Category: Interpreter, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Bug

#1533 Prepare for the 0.2.6 release
  .github/settings.yml
  RELEASES.md
  build.sbt
Labels: Category: Build, Category: Documentation, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1535 Initialize Language Server on Client Connection
  .github/settings.yml
  .github/workflows/legal-review.yml
  .github/workflows/release-update-broken.yml
  .github/workflows/release.yml
  .github/workflows/scala.yml
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/boot/LanguageServerComponent.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/ResourcesInitialization.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/resource/DirectoriesInitialization.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/resource/InitializationComponent.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/resource/RepoInitialization.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/resource/SequentialResourcesInitialization.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/resource/TruffleContextInitialization.scala
  engine/language-server/src/main/scala/org/enso/languageserver/data/Config.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionControllerFactory.scala
  engine/language-server/src/main/scala/org/enso/languageserver/session/SessionApi.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/FileVersionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/SuggestionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlSuggestionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlVersionsRepo.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Size: Medium, Type: Enhancement

#1541 Python interop
  .github/workflows/scala.yml
  distribution/std-lib/Test/src/Test.enso
  engine/runner/src/main/scala/org/enso/runner/ContextFactory.scala
  engine/runtime/src/main/java/org/enso/interpreter/epb/EpbParser.java
  engine/runtime/src/main/java/org/enso/interpreter/epb/node/ForeignEvalNode.java
  engine/runtime/src/main/java/org/enso/interpreter/epb/node/JsForeignNode.java
  engine/runtime/src/main/java/org/enso/interpreter/epb/node/PyForeignNode.java
  engine/runtime/src/main/java/org/enso/interpreter/epb/runtime/PolyglotProxy.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/RecoverPanicNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/generic/IsLanguageInstalledNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Polyglot.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/DataflowError.java
  test/Tests/src/Main.enso
  test/Tests/src/Network/Http_Spec.enso
  test/Tests/src/Semantic/Js_Interop_Spec.enso
  test/Tests/src/Semantic/Python_Interop_Spec.enso
Labels: Category: Interpreter, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1559 R Interop
  .github/workflows/scala.yml
  distribution/std-lib/Test/src/Test.enso
  engine/runtime/src/main/java/org/enso/interpreter/epb/EpbParser.java
  engine/runtime/src/main/java/org/enso/interpreter/epb/node/ContextRewrapNode.java
  engine/runtime/src/main/java/org/enso/interpreter/epb/node/ForeignEvalNode.java
  engine/runtime/src/main/java/org/enso/interpreter/epb/node/RForeignNode.java
  engine/runtime/src/main/java/org/enso/interpreter/epb/runtime/PolyglotProxy.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/GetStackTraceTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/displaytext/PolyglotErrorToDisplayTextNode.java
  test/Tests/src/Main.enso
  test/Tests/src/Semantic/Js_Interop_Spec.enso
  test/Tests/src/Semantic/Python_Interop_Spec.enso
  test/Tests/src/Semantic/R_Interop_Spec.enso
Labels: Category: Interpreter, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1546 Connection and Materialization in the Database Library
  build.sbt
  distribution/std-lib/Base/src/Error/Common.enso
  distribution/std-lib/Base/src/Main.enso
  distribution/std-lib/Base/src/System/File.enso
  distribution/std-lib/Database/THIRD-PARTY/NOTICE
  distribution/std-lib/Database/THIRD-PARTY/org.xerial.sqlite-jdbc-3.34.0/LICENSE
  distribution/std-lib/Database/THIRD-PARTY/org.xerial.sqlite-jdbc-3.34.0/LICENSE.zentus
  distribution/std-lib/Database/THIRD-PARTY/org.xerial.sqlite-jdbc-3.34.0/NOTICES
  distribution/std-lib/Database/src/Connection/Connection.enso
  distribution/std-lib/Database/src/Connection/Database.enso
  distribution/std-lib/Database/src/Data/Column.enso
  distribution/std-lib/Database/src/Data/Dialect.enso
  distribution/std-lib/Database/src/Data/Internal/Base_Generator.enso
  distribution/std-lib/Database/src/Data/Internal/Helpers.enso
  distribution/std-lib/Database/src/Data/Internal/IR.enso
  distribution/std-lib/Database/src/Data/Sql.enso
  distribution/std-lib/Database/src/Data/Table.enso
  distribution/std-lib/Database/src/Main.enso
  distribution/std-lib/Table/src/Data/Column.enso
  distribution/std-lib/Table/src/Data/Table.enso
  distribution/std-lib/Table/src/Internal/Java_Exports.enso
  distribution/std-lib/Test/src/Test.enso
  engine/runtime/src/main/java/org/enso/interpreter/epb/runtime/PolyglotProxy.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/GetStackTraceTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoFile.java
  table/src/main/java/org/enso/table/data/column/builder/object/BoolBuilder.java
  table/src/main/java/org/enso/table/data/column/builder/object/Builder.java
  table/src/main/java/org/enso/table/data/column/builder/object/InferredBuilder.java
  table/src/main/java/org/enso/table/data/column/builder/object/NumericBuilder.java
  table/src/main/java/org/enso/table/data/column/builder/object/ObjectBuilder.java
  table/src/main/java/org/enso/table/data/column/builder/object/StringBuilder.java
  table/src/main/java/org/enso/table/data/column/operation/aggregate/FunctionAggregator.java
  table/src/main/java/org/enso/table/data/column/storage/DoubleStorage.java
  table/src/main/java/org/enso/table/data/column/storage/LongStorage.java
  table/src/main/java/org/enso/table/data/column/storage/Storage.java
  table/src/main/java/org/enso/table/data/table/Column.java
  table/src/main/java/org/enso/table/data/table/Table.java
  test/Database_Tests/src/Codegen_Spec.enso
  test/Database_Tests/src/Database_Spec.enso
  test/Database_Tests/src/Helpers/Fake_Test_Connection.enso
  test/Database_Tests/src/Main.enso
  test/Table_Tests/src/Table_Spec.enso
  tools/legal-review/std-lib-Database/org.xerial.sqlite-jdbc-3.34.0/copyright-add
  tools/legal-review/std-lib-Database/org.xerial.sqlite-jdbc-3.34.0/copyright-ignore
  tools/legal-review/std-lib-Database/org.xerial.sqlite-jdbc-3.34.0/copyright-keep
  tools/legal-review/std-lib-Database/org.xerial.sqlite-jdbc-3.34.0/copyright-keep-context
  tools/legal-review/std-lib-Database/org.xerial.sqlite-jdbc-3.34.0/custom-license
  tools/legal-review/std-lib-Database/org.xerial.sqlite-jdbc-3.34.0/files-keep
  tools/legal-review/std-lib-Database/report-state
Labels: Category: Libraries, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1563 Fix Logger Disconnect
  lib/scala/logging-service/src/main/scala/org/enso/loggingservice/internal/service/ServiceWithActorSystem.scala
  lib/scala/logging-service/src/main/scala/org/enso/loggingservice/printers/FileOutputPrinter.scala
Labels: Category: Tooling, Change: Non-Breaking, Difficulty: Beginner, Priority: High, Type: Enhancement

#1570 Update Project Name Validation
  lib/scala/pkg/src/main/scala/org/enso/pkg/Package.scala
  lib/scala/pkg/src/main/scala/org/enso/pkg/validation/InvalidNameError.scala
  lib/scala/pkg/src/main/scala/org/enso/pkg/validation/NameValidation.scala
  lib/scala/pkg/src/test/scala/org/enso/pkg/NameSanitizationSpec.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/repository/ProjectFileRepository.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/MonadicProjectValidator.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectService.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ValidationFailure.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectCreateDefaultToLatestSpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectCreateMissingComponentsSpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectOpenMissingComponentsSpec.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Bug

#1574 Don't use thread interrupts to cancel executions
  engine/runtime/src/main/java/org/enso/interpreter/runtime/ThreadManager.java
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/JobExecutionEngine.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ExecuteJob.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/RuntimeManagementTest.scala
  table/src/main/java/org/enso/table/data/index/HashIndex.java
Labels: Category: Interpreter, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Bug

#1578 Prepare for the 0.2.7 Release
  RELEASES.md
  build.sbt
Labels: Category: Distribution, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1565 PostgreSQL Support in Database Library
  .github/workflows/scala.yml
  build.sbt
  distribution/std-lib/Standard/THIRD-PARTY/NOTICE
  distribution/std-lib/Standard/THIRD-PARTY/org.checkerframework.checker-qual-3.5.0/LICENSE.txt
  distribution/std-lib/Standard/THIRD-PARTY/org.postgresql.postgresql-42.2.19/LICENSE
  distribution/std-lib/Standard/THIRD-PARTY/org.postgresql.postgresql-42.2.19/NOTICES
  distribution/std-lib/Standard/src/Base/Meta.enso
  distribution/std-lib/Standard/src/Base/System/Environment.enso
  distribution/std-lib/Standard/src/Database/Connection/Connection.enso
  distribution/std-lib/Standard/src/Database/Connection/Database.enso
  distribution/std-lib/Standard/src/Database/Data/Column.enso
  distribution/std-lib/Standard/src/Database/Data/Sql.enso
  distribution/std-lib/Standard/src/Database/Data/Table.enso
  distribution/std-lib/Standard/src/Test.enso
  docs/CONTRIBUTING.md
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/GetSourceLocationNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Meta.java
  engine/runtime/src/main/resources/Builtins.enso
  std-bits/src/main/java/org/enso/database/JDBCProxy.java
  test/Database_Tests/README.md
  test/Database_Tests/src/Common_Spec.enso
  test/Database_Tests/src/Main.enso
  test/Database_Tests/src/Postgresql_Spec.enso
  test/Database_Tests/src/Sqlite_Spec.enso
  test/Tests/src/Semantic/Meta_Spec.enso
  tools/legal-review/Standard/org.checkerframework.checker-qual-3.5.0/custom-license
  tools/legal-review/Standard/org.checkerframework.checker-qual-3.5.0/files-keep
  tools/legal-review/Standard/org.postgresql.postgresql-42.2.19/copyright-ignore
  tools/legal-review/Standard/org.postgresql.postgresql-42.2.19/copyright-keep
  tools/legal-review/Standard/org.postgresql.postgresql-42.2.19/copyright-keep-context
  tools/legal-review/Standard/org.postgresql.postgresql-42.2.19/custom-license
  tools/legal-review/Standard/org.postgresql.postgresql-42.2.19/files-keep
  tools/legal-review/Standard/report-state
Labels: Category: Libraries, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High

#1575 Index Builtins Suggestions
  engine/polyglot-api/src/main/java/org/enso/polyglot/RuntimeOptions.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Context.java
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeErrorsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeInstrumentTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeStdlibTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeSuggestionUpdatesTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Size: Small, Type: Bug

#1582 Database Visualization Support
  distribution/std-lib/Standard/src/Base/Data/Json.enso
  distribution/std-lib/Standard/src/Base/Meta.enso
  distribution/std-lib/Standard/src/Database/Connection/Connection.enso
  distribution/std-lib/Standard/src/Database/Data/Column.enso
  distribution/std-lib/Standard/src/Database/Data/Sql.enso
  distribution/std-lib/Standard/src/Database/Data/Table.enso
  distribution/std-lib/Standard/src/Table/Data/Column.enso
  distribution/std-lib/Standard/src/Table/Data/Table.enso
  distribution/std-lib/Standard/src/Test.enso
  distribution/std-lib/Standard/src/Visualization/Helpers.enso
  distribution/std-lib/Standard/src/Visualization/Sql/Visualization.enso
  distribution/std-lib/Standard/src/Visualization/Table/Visualization.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/GetQualifiedTypeNameNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/GetSimpleTypeNameNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Meta.java
  engine/runtime/src/main/resources/Builtins.enso
  std-bits/src/main/java/org/enso/table/data/column/storage/BoolStorage.java
  std-bits/src/main/java/org/enso/table/data/column/storage/DoubleStorage.java
  std-bits/src/main/java/org/enso/table/data/column/storage/LongStorage.java
  std-bits/src/main/java/org/enso/table/data/column/storage/NumericStorage.java
  std-bits/src/main/java/org/enso/table/data/column/storage/ObjectStorage.java
  std-bits/src/main/java/org/enso/table/data/column/storage/Storage.java
  std-bits/src/main/java/org/enso/table/data/column/storage/StringStorage.java
  std-bits/src/main/java/org/enso/table/data/index/DefaultIndex.java
  std-bits/src/main/java/org/enso/table/data/index/HashIndex.java
  std-bits/src/main/java/org/enso/table/data/index/Index.java
  std-bits/src/main/java/org/enso/table/data/table/Column.java
  std-bits/src/main/java/org/enso/table/data/table/Table.java
  std-bits/src/main/java/org/enso/table/data/table/aggregate/AggregateColumn.java
  std-bits/src/main/java/org/enso/table/data/table/aggregate/AggregateTable.java
  test/Database_Tests/src/Codegen_Spec.enso
  test/Database_Tests/src/Postgresql_Spec.enso
  test/Database_Tests/src/Sqlite_Spec.enso
  test/Table_Tests/src/Table_Spec.enso
  test/Tests/src/Semantic/Meta_Spec.enso
Labels: Category: Libraries, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1591 Make the process library more IDE-friendly
  distribution/std-lib/Standard/src/Base/System/Process.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/system/CreateProcessNode.java
  test/Tests/src/System/Process_Spec.enso
Labels: Category: Stdlib, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1595 Fix Table Visualization When No Index Is Present
  distribution/std-lib/Standard/src/Visualization/Table/Visualization.enso
Labels: Category: Libraries, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Bug

#1596 Prepare for the 0.2.8 Release
  RELEASES.md
  build.sbt
Labels: Category: Distribution, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1450 Image Processing Library Prototype
  build.sbt
  distribution/std-lib/Standard/THIRD-PARTY/NOTICE
  distribution/std-lib/Standard/THIRD-PARTY/licenses/BSD-3-Clause
  distribution/std-lib/Standard/THIRD-PARTY/org.openpnp.opencv-4.5.1-0/NOTICES
  distribution/std-lib/Standard/src/Base/Data/Vector.enso
  distribution/std-lib/Standard/src/Image.enso
  distribution/std-lib/Standard/src/Image/Codecs.enso
  distribution/std-lib/Standard/src/Image/Codecs/Internal.enso
  distribution/std-lib/Standard/src/Image/Data/Histogram.enso
  distribution/std-lib/Standard/src/Image/Data/Image.enso
  distribution/std-lib/Standard/src/Image/Data/Image/Internal.enso
  distribution/std-lib/Standard/src/Image/Data/Matrix.enso
  distribution/std-lib/Standard/src/Image/Data/Matrix/Internal.enso
  docs/CONTRIBUTING.md
  std-bits/src/main/java/org/enso/image/Codecs.java
  std-bits/src/main/java/org/enso/image/data/Histogram.java
  std-bits/src/main/java/org/enso/image/data/Image.java
  std-bits/src/main/java/org/enso/image/data/Matrix.java
  std-bits/src/main/java/org/enso/image/opencv/OpenCV.java
  test/Image_Tests/.gitignore
  test/Image_Tests/package.yaml
  test/Image_Tests/src/Codecs_Spec.enso
  test/Image_Tests/src/Data/Image_Spec.enso
  test/Image_Tests/src/Data/Matrix_Spec.enso
  test/Image_Tests/src/Main.enso
  test/Tests/src/Data/Vector_Spec.enso
  test/Tests/src/Network/Http_Spec.enso
  tools/legal-review/Standard/org.openpnp.opencv-4.5.1-0/copyright-ignore
  tools/legal-review/Standard/org.openpnp.opencv-4.5.1-0/copyright-keep
  tools/legal-review/Standard/report-state
  tools/legal-review/Standard/reviewed-licenses/BSD_License
  tools/legal-review/std-lib-Image/report-state
Labels: Category: Libraries, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Low, Type: Enhancement

#1612 Fix Image Visualization
  std-bits/src/main/java/org/enso/image/data/Image.java
Labels: Category: Stdlib, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Bug

#1611 Do not Cache Panics
  engine/runtime/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeErrorsTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Bug

#1613 Provide Suggestions for Compatible Types
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/Suggestions.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/SuggestionsHandlerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/data/TypeGraph.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/polyglot-api/src/test/scala/org/enso/polyglot/data/TypeGraphTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/type/Types.java
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/CommandFactory.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/GetTypeGraphCommand.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  lib/scala/searcher/src/bench/java/org/enso/searcher/sql/SuggestionsRepoBenchmark.java
  lib/scala/searcher/src/main/scala/org/enso/searcher/SuggestionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlSuggestionsRepo.scala
  lib/scala/searcher/src/test/scala/org/enso/searcher/sql/SuggestionsRepoTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1608 Histogram and Scatterplot visualizations support for Table
  .github/workflows/scala.yml
  distribution/std-lib/Standard/src/Visualization/Helpers.enso
  distribution/std-lib/Standard/src/Visualization/Histogram.enso
  distribution/std-lib/Standard/src/Visualization/Scatter_Plot.enso
  test/Visualization_Tests/package.yaml
  test/Visualization_Tests/src/Helpers_Spec.enso
  test/Visualization_Tests/src/Histogram_Spec.enso
  test/Visualization_Tests/src/Main.enso
  test/Visualization_Tests/src/Scatter_Plot_Spec.enso
Labels: Category: Stdlib, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1614 Fix a Bug in the Database Join Implementation
  distribution/std-lib/Standard/src/Database/Data/Internal/IR.enso
  distribution/std-lib/Standard/src/Database/Data/Table.enso
  distribution/std-lib/Standard/src/Visualization/Table/Visualization.enso
  test/Database_Tests/src/Codegen_Spec.enso
  test/Database_Tests/src/Common_Spec.enso
  test/Visualization_Tests/src/Main.enso
  test/Visualization_Tests/src/Sql_Spec.enso
  test/Visualization_Tests/src/Table_Spec.enso
Labels: Category: Libraries, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Bug, Type: Enhancement

#1618 Fix the Example for File.read
  distribution/std-lib/Standard/src/Base/System/File.enso
Labels: Category: Stdlib, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1619 Prepare for the 0.2.9 release
  RELEASES.md
  build.sbt
Labels: Category: Distribution, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1629 Rank Suggestions by Self-Type Specificity
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/SuggestionsHandlerSpec.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/data/TypeGraph.scala
  engine/polyglot-api/src/test/scala/org/enso/polyglot/data/TypeGraphTest.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/SuggestionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlSuggestionsRepo.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1628 Implement Additional Methods for Table and Column
  distribution/std-lib/Standard/src/Table/Data/Column.enso
  distribution/std-lib/Standard/src/Table/Data/Table.enso
  std-bits/src/main/java/org/enso/table/operations/OrderBuilder.java
  test/Table_Tests/src/Column_Spec.enso
  test/Table_Tests/src/Main.enso
  test/Table_Tests/src/Table_Spec.enso
Labels: Category: Stdlib, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1633 Misc Runtime Fixes
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/AttachVisualisationCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/DetachVisualisationCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/ModifyVisualisationCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/LocationFilter.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/DetachVisualisationJob.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeInstrumentTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Bug

#1632 Convert GeoJSON to Table
  distribution/std-lib/Standard/src/Base/Network/Http.enso
  distribution/std-lib/Standard/src/Base/Network/Http/Form.enso
  distribution/std-lib/Standard/src/Base/Network/Http/Request.enso
  distribution/std-lib/Standard/src/Base/Network/Internal.enso
  distribution/std-lib/Standard/src/Base/Network/Uri.enso
  distribution/std-lib/Standard/src/Base/Network/Uri/Internal.enso
  distribution/std-lib/Standard/src/Geo/Geo_Json.enso
  distribution/std-lib/Standard/src/Table.enso
  test/Geo_Tests/src/Main.enso
  test/Table_Tests/src/Table_Spec.enso
  test/Tests/src/Network/Http/Request_Spec.enso
  test/Tests/src/Network/Http_Spec.enso
  test/Tests/src/Network/Uri_Spec.enso
Labels: Category: Stdlib, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1638 Inlining Helper for Benchmarks
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/runtime/NoInlineWithArgNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  engine/runtime/src/main/resources/Builtins.enso
  test/Tests/src/Main.enso
  test/Tests/src/Semantic/Runtime_Spec.enso
Labels: Category: Performance, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement
