Repository enso-org/enso, pull requests merged in 2021-04, with the labels that each got.

#1634 Case Insensitive Dataframe Support in Visualizations
  distribution/std-lib/Standard/src/Visualization/Geo_Map.enso
  distribution/std-lib/Standard/src/Visualization/Helpers.enso
  distribution/std-lib/Standard/src/Visualization/Histogram.enso
  distribution/std-lib/Standard/src/Visualization/Scatter_Plot.enso
  test/Visualization_Tests/src/Geo_Map_Spec.enso
  test/Visualization_Tests/src/Helpers.enso
  test/Visualization_Tests/src/Helpers_Spec.enso
  test/Visualization_Tests/src/Histogram_Spec.enso
  test/Visualization_Tests/src/Main.enso
  test/Visualization_Tests/src/Scatter_Plot_Spec.enso
Labels: Category: Libraries, Change: Non-Breaking, Difficulty: Intermediate, Priority: Highest, Type: Enhancement

#1647 Sync Suggestions Database when Renaming the Project
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonRpc.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextEventsListener.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistryProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ExecutionApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ExpressionValueUpdate.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SearchProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/language-server/src/test/scala/org/enso/languageserver/runtime/ContextEventsListenerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/SuggestionsHandlerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/SuggestionsHandlerEventsTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/SuggestionsHandlerTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/CommandFactory.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/VerifyModulesIndexCmd.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/SuggestionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlSuggestionsRepo.scala
  lib/scala/searcher/src/test/scala/org/enso/searcher/sql/SuggestionsRepoTest.scala
Labels: Category: Backend, Change: Breaking, Difficulty: Core Contributor, Priority: High, Type: Bug

#1650 Fix Some Implementations of Vector Constructors
  distribution/std-lib/Standard/src/Base/Data/Text/Extensions.enso
  distribution/std-lib/Standard/src/Base/Data/Vector.enso
  distribution/std-lib/Standard/src/Base/System/File.enso
  engine/runtime/src/main/java/org/enso/interpreter/epb/node/ContextRewrapNode.java
  test/Tests/src/Data/Vector_Spec.enso
  test/Tests/src/Semantic/Js_Interop_Spec.enso
Labels: Category: Stdlib, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1644 Add Python and R to the GraalVM Bundle
  .github/workflows/release.yml
  build.sbt
  project/DistributionPackage.scala
  tools/ci/prepare-distribution-env.sh
Labels: Category: Distribution, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1651 Install Required GraalVM Components
  engine/launcher/src/main/scala/org/enso/launcher/distribution/DefaultManagers.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/versionmanagement/DefaultDistributionConfiguration.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/TestDistributionConfiguration.scala
  lib/scala/runtime-version-manager-test/src/main/scala/org/enso/runtimeversionmanager/test/NoopComponentUpdater.scala
  lib/scala/runtime-version-manager-test/src/main/scala/org/enso/runtimeversionmanager/test/NoopComponentUpdaterFactory.scala
  lib/scala/runtime-version-manager-test/src/main/scala/org/enso/runtimeversionmanager/test/RuntimeVersionManagerTest.scala
  lib/scala/runtime-version-manager-test/src/test/scala/org/enso/runtimeversionmanager/locking/ConcurrencyTest.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/GraalVMComponent.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/GraalVMComponentConfiguration.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/GraalVMComponentUpdater.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/RuntimeComponentConfiguration.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/RuntimeComponentUpdater.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/RuntimeComponentUpdaterFactory.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/RuntimeVersionManager.scala
  lib/scala/runtime-version-manager/src/test/scala/org/enso/runtimeversionmanager/components/GraalVMComponentConfigurationSpec.scala
  lib/scala/runtime-version-manager/src/test/scala/org/enso/runtimeversionmanager/components/GraalVMComponentParserSpec.scala
  lib/scala/runtime-version-manager/src/test/scala/org/enso/runtimeversionmanager/components/GraalVMComponentUpdaterSpec.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1656 Prepare for the 0.2.10 release
  RELEASES.md
  build.sbt
Labels: Category: Distribution, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Release

#1660 Install GraalVM Components in Temp Directory
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/RuntimeVersionManager.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Low, Type: Enhancement

#1666 Fix some naming for Maybe
  distribution/std-lib/Standard/src/Base/Data/Maybe.enso
  test/Tests/src/Data/Maybe_Spec.enso
Labels: Category: Stdlib, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Bug

#1665 Resolve Clashing Project Ids
  engine/language-server/src/test/resources/application.conf
  engine/runtime/src/main/java/org/enso/interpreter/runtime/util/TruffleFileSystem.java
  lib/scala/pkg/src/main/scala/org/enso/filesystem/FileSystem.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/repository/ProjectFileRepository.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/model/Project.scala
  lib/scala/project-manager/src/test/resources/application.conf
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1659 Add an Atom Suggestion for a Module
  engine/language-server/src/test/scala/org/enso/languageserver/search/SuggestionsHandlerSpec.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/context/SuggestionBuilderTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeSuggestionUpdatesTest.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/Tables.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement

#1663 Debug GraalVM Installation
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/GraalVMComponentUpdater.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/RuntimeVersionManager.scala
Labels: Category: Backend, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1667 Update README.md
  README.md
Labels: Category: Documentation, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1672 Remove Unused JAR Launcher Prefix to Fix Issue with Signing
  build.sbt
  docs/CONTRIBUTING.md
Labels: Category: Backend, Category: Distribution, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest

#1681 Ensodev user
  tools/ci/docker/Dockerfile
Labels: Category: Tooling, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Size: Small, Type: Enhancement

#1671 Report Visualization Errors
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/binary/BinaryConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/binary/factory/ErrorFactory.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonRpc.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextEventsListener.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistry.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistryProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ExecutionApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/RuntimeFailureMapper.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/handler/AttachVisualisationHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/handler/CreateContextHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/handler/DestroyContextHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/handler/DetachVisualisationHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/handler/ModifyVisualisationHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/handler/PopContextHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/handler/PushContextHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/handler/RecomputeContextHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/handler/ImportModuleHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/handler/InvalidateModulesIndexHandler.scala
  engine/language-server/src/test/scala/org/enso/languageserver/runtime/ContextEventsListenerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/ContextRegistryTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/ExecutionContextJsonMessages.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/VisualisationOperationsTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime/src/main/java/org/enso/interpreter/service/error/VisualisationException.java
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/DetachVisualisationJob.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ExecuteJob.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/UpsertVisualisationJob.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  lib/scala/json-rpc-server/src/main/scala/org/enso/jsonrpc/JsonProtocol.scala
  lib/scala/json-rpc-server/src/main/scala/org/enso/jsonrpc/MessageHandler.scala
  lib/scala/json-rpc-server/src/main/scala/org/enso/jsonrpc/Protocol.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectCreateDefaultToLatestSpec.scala
Labels: Category: Backend, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1646 Adjust Doc Generator to comply with new Tailwind-css-based stylesheet
  lib/scala/syntax/definition/src/main/scala/org/enso/syntax/text/ast/Doc.scala
  lib/scala/syntax/definition/src/main/scala/org/enso/syntax/text/spec/DocParserDef.scala
  lib/scala/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/DocParser.scala
  lib/scala/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/Parser.scala
Labels: Category: Syntax, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1691 Synchronize Runtime Updates Sending
  engine/runtime/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java
  engine/runtime/src/main/java/org/enso/interpreter/instrument/RuntimeCache.java
  engine/runtime/src/main/java/org/enso/interpreter/instrument/UpdatesSynchronizationState.java
  engine/runtime/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/CacheInvalidation.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/ExecutionContextState.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/EditFileCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/PopContextCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/PushContextCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/RecomputeContextCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/RenameProjectCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/Executable.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ExecuteJob.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/UpsertVisualisationJob.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualisationsTest.scala
Labels: Category: Backend, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1702 Add `.sum` to Vector
  distribution/std-lib/Standard/src/Base/Data/Range.enso
  distribution/std-lib/Standard/src/Base/Data/Vector.enso
  distribution/std-lib/Standard/src/Visualization/Scatter_Plot.enso
  test/Tests/src/Data/Range_Spec.enso
  test/Tests/src/Data/Vector_Spec.enso
  test/Visualization_Tests/src/Histogram_Spec.enso
  test/Visualization_Tests/src/Scatter_Plot_Spec.enso
Labels: Category: Stdlib, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#1703 Add Suggestions Database Schema Version
  engine/language-server/src/main/scala/org/enso/languageserver/boot/ResourcesInitialization.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/resource/RepoInitialization.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/BufferRegistry.scala
  engine/language-server/src/test/scala/org/enso/languageserver/boot/resource/RepoInitializationSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/runtime/ContextEventsListenerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  lib/scala/searcher/src/main/resources/reference.conf
  lib/scala/searcher/src/main/scala/org/enso/searcher/Database.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/InvalidSchemaVersion.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlDatabase.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlSuggestionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlVersionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/Tables.scala
  lib/scala/searcher/src/test/scala/org/enso/searcher/sql/SuggestionsRepoTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#1704 Add Initialization Info-level Logging
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/RuntimeConnector.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/RuntimeKiller.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/launcher/src/main/scala/org/enso/launcher/Launcher.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectService.scala
  lib/scala/runtime-version-manager-test/src/main/scala/org/enso/runtimeversionmanager/test/NoopComponentUpdaterFactory.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/ComponentsException.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/GraalRuntime.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/GraalVMComponentUpdater.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/RuntimeComponentUpdaterFactory.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/RuntimeVersionManager.scala
  lib/scala/runtime-version-manager/src/test/scala/org/enso/runtimeversionmanager/components/GraalVMComponentUpdaterSpec.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Bug

#1708 Prepare for the 0.2.11 release
  RELEASES.md
  build.sbt
Labels: Category: Distribution, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Release

#1712 Support Higher-Kinded Types in Suggestions
  engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/context/SuggestionBuilderTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement
