Repository enso-org/enso, pull requests merged in 2022-12, with the labels that each got.

#3917 Disabling musl as it isn't capable to load dynamic library
  build.sbt
  engine/runtime/src/main/java/org/enso/compiler/EnsoCompiler.java
Labels: CI: Ready to merge, CI: No changelog needed

#3934 Integer.parse and Decimal.parse improvements
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/NumberParseError.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/ParseIntegerNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Error.java
  test/Tests/src/Data/Numbers_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#3940 Split Common_Table_Spec into smaller modules, tidy up Table tests
  test/Table_Tests/data/datetime_sample_normalized_hours.csv
  test/Table_Tests/data/time_of_day_sample_normalized_hours.csv
  test/Table_Tests/src/Common_Table_Operations/Aggregate_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Core_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Expression_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Filter_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Main.enso
  test/Table_Tests/src/Common_Table_Operations/Missing_Values_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Order_By_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Select_Columns_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Take_Drop_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Util.enso
  test/Table_Tests/src/Common_Table_Spec.enso
  test/Table_Tests/src/Database/Common_Spec.enso
  test/Table_Tests/src/Database/Main.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Database/Redshift_Spec.enso
  test/Table_Tests/src/Database/SQLite_Spec.enso
  test/Table_Tests/src/Formatting/Data_Formatter_Spec.enso
  test/Table_Tests/src/Formatting/Main.enso
  test/Table_Tests/src/Formatting/Parse_Values_Spec.enso
  test/Table_Tests/src/IO/Csv_Spec.enso
  test/Table_Tests/src/IO/Delimited_Read_Spec.enso
  test/Table_Tests/src/IO/Delimited_Write_Spec.enso
  test/Table_Tests/src/IO/Excel_Spec.enso
  test/Table_Tests/src/IO/Json_Spec.enso
  test/Table_Tests/src/IO/Main.enso
  test/Table_Tests/src/In_Memory/Aggregate_Column_Spec.enso
  test/Table_Tests/src/In_Memory/Column_Spec.enso
  test/Table_Tests/src/In_Memory/Main.enso
  test/Table_Tests/src/In_Memory/Table_Date_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Date_Time_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Time_Of_Day_Spec.enso
  test/Table_Tests/src/In_Memory/Unique_Naming_Strategy_Spec.enso
  test/Table_Tests/src/In_Memory_Tests.enso
  test/Table_Tests/src/Main.enso
Labels: CI: Ready to merge, CI: No changelog needed

#3936 implement compare_to for Ordering
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Ordering.enso
  test/Tests/src/Data/Ordering_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#3909 Release process
  .github/workflows/nightly.yml
  .github/workflows/promote.yml
  .github/workflows/release-publish-edition.yml
  .github/workflows/release.yml
  Cargo.lock
  build/base/src/extensions/from_string.rs
  build/base/src/extensions/future.rs
  build/base/src/extensions/path.rs
  build/base/src/extensions/result.rs
  build/build/Cargo.toml
  build/build/paths.yaml
  build/build/release-body.md
  build/build/src/context.rs
  build/build/src/engine/bundle.rs
  build/build/src/engine/context.rs
  build/build/src/lib.rs
  build/build/src/project.rs
  build/build/src/release.rs
  build/build/src/repo.rs
  build/build/src/repo/cloud.rs
  build/build/src/version.rs
  build/build/src/version/nightly.rs
  build/build/src/version/promote.rs
  build/ci_utils/Cargo.toml
  build/ci_utils/src/actions/workflow.rs
  build/ci_utils/src/actions/workflow/definition.rs
  build/ci_utils/src/env.rs
  build/ci_utils/src/extensions/version.rs
  build/ci_utils/src/fs/wrappers/tokio.rs
  build/ci_utils/src/github/release.rs
  build/ci_utils/src/github/repo.rs
  build/ci_utils/src/lib.rs
  build/ci_utils/src/log.rs
  build/ci_utils/src/programs/git.rs
  build/ci_utils/src/programs/git/clean.rs
  build/ci_utils/src/programs/git/pretty_format.rs
  build/ci_utils/src/programs/git/ref.rs
  build/cli/src/arg.rs
  build/cli/src/arg/release.rs
  build/cli/src/bin/enso-remove-draft-releases.rs
  build/cli/src/ci_gen.rs
  build/cli/src/ci_gen/job.rs
  build/cli/src/lib.rs
  build/macros/src/program_args.rs
  build/macros/tests/with_attr.rs
  docs/distribution/nightly.md
  docs/distribution/release-policy.md
  engine/runtime/src/test/java/org/enso/interpreter/test/DebuggingEnsoTest.java
  run.ps1
Labels: CI: No changelog needed

#3923 Make a VCS save on ctrl+s shortcut
  CHANGELOG.md
  app/gui/controller/engine-protocol/src/language_server.rs
  app/gui/controller/engine-protocol/src/language_server/response.rs
  app/gui/controller/engine-protocol/src/language_server/types.rs
  app/gui/src/controller/project.rs
  app/gui/src/controller/text.rs
  app/gui/src/model/project/synchronized.rs
  app/gui/src/presenter/code.rs
  app/gui/src/presenter/project.rs
  app/gui/view/src/project.rs
Labels: CI: Ready to merge

#3944 Recognize NamedApp in @Tail_Call
  engine/runtime/src/main/java/org/enso/compiler/TreeToIr.java
  engine/runtime/src/test/java/org/enso/compiler/EnsoCompilerTest.java
Labels: CI: Ready to merge, CI: No changelog needed

#3935 Update component browser design
  Cargo.lock
  app/gui/view/component-browser/component-list-panel/Cargo.toml
  app/gui/view/component-browser/component-list-panel/breadcrumbs/Cargo.toml
  app/gui/view/component-browser/component-list-panel/breadcrumbs/src/entry.rs
  app/gui/view/component-browser/component-list-panel/breadcrumbs/src/lib.rs
  app/gui/view/component-browser/component-list-panel/grid/Cargo.toml
  app/gui/view/component-browser/component-list-panel/grid/src/entry.rs
  app/gui/view/component-browser/component-list-panel/grid/src/entry/icon.rs
  app/gui/view/component-browser/component-list-panel/grid/src/entry/icon/entry.rs
  app/gui/view/component-browser/component-list-panel/grid/src/entry/style.rs
  app/gui/view/component-browser/component-list-panel/grid/src/lib.rs
  app/gui/view/component-browser/component-list-panel/icons/Cargo.toml
  app/gui/view/component-browser/component-list-panel/icons/src/common_part.rs
  app/gui/view/component-browser/component-list-panel/icons/src/define_macro.rs
  app/gui/view/component-browser/component-list-panel/icons/src/lib.rs
  app/gui/view/component-browser/component-list-panel/src/lib.rs
  app/gui/view/component-browser/component-list-panel/src/navigator.rs
  app/gui/view/component-browser/component-list-panel/src/navigator/entry.rs
  app/gui/view/debug_scene/component-list-panel-view/src/lib.rs
  app/gui/view/debug_scene/icons/Cargo.toml
  app/gui/view/debug_scene/icons/src/lib.rs
  build-config.yaml
  lib/rust/ensogl/app/theme/derive/src/from_theme.rs
  lib/rust/ensogl/app/theme/derive/src/lib.rs
  lib/rust/ensogl/app/theme/hardcoded/src/lib.rs
  lib/rust/ensogl/component/grid-view/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#3913 Skip and Freeze macros in IDE
  app/gui/controller/double-representation/src/node.rs
  app/gui/language/ast/impl/src/macros.rs
  app/gui/language/ast/impl/src/macros/skip_and_freeze.rs
  app/gui/src/controller/graph.rs
  app/gui/src/controller/searcher.rs
  app/gui/src/model/undo_redo.rs
  app/gui/src/presenter/graph.rs
  app/gui/src/presenter/graph/state.rs
  app/gui/view/graph-editor/src/component/node.rs
  app/gui/view/graph-editor/src/component/node/action_bar.rs
  app/gui/view/graph-editor/src/lib.rs
  build-config.yaml
Labels: CI: Ready to merge, CI: No changelog needed

#3947 Ensure project name starts with uppercase
  app/gui/controller/double-representation/src/name/project.rs
  app/gui/src/controller/ide.rs
  app/gui/src/controller/ide/desktop.rs
  app/gui/src/presenter.rs
Labels: CI: Ready to merge, CI: No changelog needed

#3955 Fix issue where constructor was becoming a value. Fixes to_json.
  distribution/lib/Standard/Base/0.0.0-dev/src/Any.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json/Internal.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Meta.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Problems.enso
  test/Tests/src/Semantic/Meta_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#3957 Fix order by Text
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  test/Table_Tests/src/Common_Table_Operations/Order_By_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#3941 Allow arbitrary expression evaluation in chromeinspector
  CHANGELOG.md
  docs/debugger/README.md
  engine/runtime/src/main/java/org/enso/compiler/EnsoCompiler.java
  engine/runtime/src/main/java/org/enso/compiler/TreeToIr.java
  engine/runtime/src/main/java/org/enso/interpreter/EnsoLanguage.java
  engine/runtime/src/main/java/org/enso/interpreter/instrument/HostObjectDebugWrapper.java
  engine/runtime/src/main/java/org/enso/interpreter/node/ExpressionNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/DebugLocalScope.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/data/CompilerConfig.scala
  engine/runtime/src/test/java/org/enso/interpreter/test/DebuggingEnsoTest.java
Labels: CI: Ready to merge

#3952 Add executionContext/interrupt API command
  CHANGELOG.md
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonRpc.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/executioncontext/InterruptHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistry.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistryProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ExecutionApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/handler/InterruptContextHandler.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeAsyncCommandsTest.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/CommandFactory.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/InterruptContextCmd.scala
Labels: CI: Ready to merge

#3959 Use the MultiValueIndex for the JoinStrategy.
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  std-bits/table/src/main/java/org/enso/table/data/index/MultiValueIndex.java
  std-bits/table/src/main/java/org/enso/table/data/table/Table.java
  std-bits/table/src/main/java/org/enso/table/data/table/join/IndexJoin.java
Labels: CI: Ready to merge, CI: No changelog needed

#3945 Fix disappearing text labels when entering edit mode
  lib/rust/ensogl/component/text/src/font/glyph.rs
  lib/rust/ensogl/core/src/display/scene/layer.rs
  lib/rust/ensogl/core/src/display/shape/primitive/system.rs
  lib/rust/ensogl/core/src/gui/component.rs
Labels: CI: Ready to merge, CI: No changelog needed

#3960 Empty block body shall result in a syntax error
  engine/runtime/src/main/java/org/enso/compiler/TreeToIr.java
  engine/runtime/src/test/java/org/enso/compiler/ErrorCompilerTest.java
Labels: CI: Ready to merge, CI: No changelog needed

#3951 Show default mouse cursor over documentation panel
  app/gui/view/src/documentation.rs
  lib/rust/ensogl/core/src/application.rs
Labels: CI: Ready to merge, CI: No changelog needed

#3961 Tweaks to make benchmarking easier
  build.sbt
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/StringBenchmarks.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/TypePatternBenchmarks.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/VectorBenchmarks.java
  project/WithDebugCommand.scala
Labels: CI: Ready to merge, CI: No changelog needed

#3953 Small tweak to convert Date and Time objects to strings in Table viz.
  app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js
Labels: CI: Ready to merge, CI: No changelog needed

#3970 ExpressionNodes are only wrapped in the presence of Chrome inspector
  engine/runtime/src/main/java/org/enso/interpreter/node/ExpressionNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/function/BlockNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
Labels: CI: Ready to merge, CI: No changelog needed

#3969 Speeding up Array_Proxy.from_proxy_object twice
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array_Proxy.enso
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/SrcUtil.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/VectorBenchmarks.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/ArrayProxy.java
Labels: CI: Ready to merge, CI: No changelog needed

#3885 Numeric slider component enhancement
  CHANGELOG.md
  Cargo.lock
  build-config.yaml
  lib/rust/ensogl/component/slider/Cargo.toml
  lib/rust/ensogl/component/slider/src/lib.rs
  lib/rust/ensogl/component/slider/src/model.rs
  lib/rust/ensogl/example/slider/Cargo.toml
  lib/rust/ensogl/example/slider/src/lib.rs
Labels: CI: Ready to merge

#3966 Fix adding constructor record to suggestions database
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlSuggestionsRepo.scala
Labels: CI: No changelog needed

#3972 Move Create New Project button to top.
  app/gui/view/welcome-screen/src/side_menu.rs
  lib/scala/pkg/src/main/resources/default/src/Main.enso
Labels: CI: Ready to merge, CI: No changelog needed

#3967 Add a shortcut for interrupting the program
  CHANGELOG.md
  app/gui/controller/engine-protocol/src/language_server.rs
  app/gui/docs/product/shortcuts.md
  app/gui/src/controller/graph/executed.rs
  app/gui/src/model/execution_context.rs
  app/gui/src/model/execution_context/plain.rs
  app/gui/src/model/execution_context/synchronized.rs
  app/gui/src/presenter/project.rs
  app/gui/view/src/project.rs
Labels: CI: Ready to merge

#3974 Windows doesn't like resolving last commit with `refs/heads/master`
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/vcs/StatusVcsHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/vcsmanager/Git.scala
  engine/language-server/src/main/scala/org/enso/languageserver/vcsmanager/VcsApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/vcsmanager/VcsManager.scala
  engine/language-server/src/main/scala/org/enso/languageserver/vcsmanager/VcsManagerApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/vcsmanager/VcsProtocol.scala
  engine/language-server/src/test/scala/org/enso/languageserver/vcsmanager/GitSpec.scala
Labels: CI: Ready to merge, CI: No changelog needed

#3786 Add with_clue support to test framework
  distribution/lib/Standard/Test/0.0.0-dev/src/Test.enso
  test/Meta_Test_Suite_Tests/README.md
  test/Meta_Test_Suite_Tests/data/fail_report/Main.enso
  test/Meta_Test_Suite_Tests/data/fail_report/stdout.txt
  test/Meta_Test_Suite_Tests/data/fail_report/test_description.txt
  test/Meta_Test_Suite_Tests/data/with_clue_1/Main.enso
  test/Meta_Test_Suite_Tests/data/with_clue_1/stdout.txt
  test/Meta_Test_Suite_Tests/data/with_clue_1/test_description.txt
  test/Meta_Test_Suite_Tests/data/with_clue_2/Main.enso
  test/Meta_Test_Suite_Tests/data/with_clue_2/stdout.txt
  test/Meta_Test_Suite_Tests/data/with_clue_2/test_description.txt
  test/Meta_Test_Suite_Tests/package.yaml
  test/Meta_Test_Suite_Tests/src/Main.enso
Labels: CI: Ready to merge, CI: No changelog needed

#3971 Bump wasm-bindgen
  Cargo.lock
  Cargo.toml
  app/gui/Cargo.toml
  app/gui/analytics/Cargo.toml
  app/gui/controller/double-representation/Cargo.toml
  app/gui/controller/engine-protocol/Cargo.toml
  app/gui/language/parser/Cargo.toml
  app/gui/language/span-tree/Cargo.toml
  app/gui/language/span-tree/example/Cargo.toml
  app/gui/view/Cargo.toml
  app/gui/view/debug_scene/cloud-dashboard/Cargo.toml
  app/gui/view/debug_scene/component-list-panel-view/Cargo.toml
  app/gui/view/debug_scene/icons/Cargo.toml
  app/gui/view/debug_scene/interface/Cargo.toml
  app/gui/view/debug_scene/text-grid-visualization/Cargo.toml
  app/gui/view/debug_scene/visualization/Cargo.toml
  app/gui/view/graph-editor/Cargo.toml
  app/gui/view/graph-editor/src/component/visualization/foreign/java_script/binding.rs
  app/gui/view/graph-editor/src/component/visualization/foreign/java_script/instance.rs
  app/gui/view/welcome-screen/Cargo.toml
  app/ide-desktop/lib/content/src/index.ts
  app/ide-desktop/lib/content/src/wasm_imports.js
  build/build/src/project/wasm.rs
  build/build/src/project/wasm/js_patcher.rs
  integration-test/Cargo.toml
  lib/rust/debug-api/Cargo.toml
  lib/rust/ensogl/component/drop-manager/Cargo.toml
  lib/rust/ensogl/component/gui/Cargo.toml
  lib/rust/ensogl/component/text/Cargo.toml
  lib/rust/ensogl/component/text/src/font/msdf/Cargo.toml
  lib/rust/ensogl/core/Cargo.toml
  lib/rust/ensogl/example/animation/Cargo.toml
  lib/rust/ensogl/example/complex-shape-system/Cargo.toml
  lib/rust/ensogl/example/custom-shape-system/Cargo.toml
  lib/rust/ensogl/example/dom-symbols/Cargo.toml
  lib/rust/ensogl/example/drop-manager/Cargo.toml
  lib/rust/ensogl/example/easing-animator/Cargo.toml
  lib/rust/ensogl/example/focus-management/Cargo.toml
  lib/rust/ensogl/example/grid-view/Cargo.toml
  lib/rust/ensogl/example/list-view/Cargo.toml
  lib/rust/ensogl/example/mouse-events/Cargo.toml
  lib/rust/ensogl/example/profiling-run-graph/Cargo.toml
  lib/rust/ensogl/example/render-profile-flamegraph/Cargo.toml
  lib/rust/ensogl/example/scroll-area/Cargo.toml
  lib/rust/ensogl/example/slider/Cargo.toml
  lib/rust/ensogl/example/sprite-system-benchmark/Cargo.toml
  lib/rust/ensogl/example/sprite-system/Cargo.toml
  lib/rust/ensogl/example/text-area/Cargo.toml
  lib/rust/frp/Cargo.toml
  lib/rust/logger/Cargo.toml
  lib/rust/prelude/Cargo.toml
  lib/rust/profiler/Cargo.toml
  lib/rust/shapely/Cargo.toml
  lib/rust/shortcuts/Cargo.toml
  lib/rust/shortcuts/example/Cargo.toml
  lib/rust/web/Cargo.toml
Labels: CI: Ready to merge, CI: No changelog needed

#3977 AvoidIdInstrumentationTagTest to control which nodes are instrumentable
  engine/runtime-with-instruments/src/test/java/org/enso/interpreter/test/instrument/AvoidIdInstrumentationTagTest.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/FunctionCallInstrumentationNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/function/StatementNode.java
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
Labels: CI: Ready to merge, CI: No changelog needed

#3983 Bump wasm-pack
  actions/setup-build/action.yml
  app/gui/docs/CONTRIBUTING.md
  docs/CONTRIBUTING.md
Labels: CI: No changelog needed

#3964 JSON Improvements, small Table stuff, Statistic in Enso not Java and few other minor bits.
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Filter_Condition.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json/Internal.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Ordering.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Pair.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Statistics.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Duration.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Error/Common.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/HTTP_Method.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/Existing_File_Behavior.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/package.yaml
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Filter_Condition_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  engine/runtime/src/test/java/org/enso/compiler/ParseStdLibTest.java
  std-bits/base/src/main/java/org/enso/base/statistics/CountMinMax.java
  std-bits/base/src/main/java/org/enso/base/statistics/Moments.java
  test/Benchmarks/src/Vector/Operations.enso
  test/Table_Tests/src/Common_Table_Operations/Filter_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Order_By_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
  test/Tests/src/Data/Json_Spec.enso
  test/Tests/src/Data/List_Spec.enso
  test/Tests/src/Data/Numbers_Spec.enso
  test/Tests/src/Data/Ordering_Spec.enso
  test/Tests/src/Data/Pair_Spec.enso
  test/Tests/src/Data/Range_Spec.enso
  test/Tests/src/Data/Statistics_Spec.enso
  test/Tests/src/Data/Time/Duration_Spec.enso
  test/Tests/src/Data/Vector_Spec.enso
  test/Tests/src/Main.enso
Labels: CI: Ready to merge

#3978 Efficient joining for Equals and Equals_Ignore_Case using a hashmap
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Join_Condition.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Aggregate_Column_Helper.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Join_Helpers.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Test_Reporter.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/CatchTypeBranchNode.java
  std-bits/base/src/main/java/org/enso/base/polyglot/NumericConverter.java
  std-bits/table/src/main/java/org/enso/table/aggregations/Aggregator.java
  std-bits/table/src/main/java/org/enso/table/aggregations/CountDistinct.java
  std-bits/table/src/main/java/org/enso/table/aggregations/Mean.java
  std-bits/table/src/main/java/org/enso/table/aggregations/Mode.java
  std-bits/table/src/main/java/org/enso/table/aggregations/Percentile.java
  std-bits/table/src/main/java/org/enso/table/aggregations/StandardDeviation.java
  std-bits/table/src/main/java/org/enso/table/aggregations/Sum.java
  std-bits/table/src/main/java/org/enso/table/data/index/MultiValueIndex.java
  std-bits/table/src/main/java/org/enso/table/data/index/MultiValueKeyBase.java
  std-bits/table/src/main/java/org/enso/table/data/index/UnorderedMultiValueKey.java
  std-bits/table/src/main/java/org/enso/table/data/table/Table.java
  std-bits/table/src/main/java/org/enso/table/data/table/join/IndexJoin.java
  std-bits/table/src/main/java/org/enso/table/data/table/join/scan/MatcherFactory.java
  std-bits/table/src/main/java/org/enso/table/data/table/join/scan/ScanJoin.java
  std-bits/table/src/main/java/org/enso/table/data/table/problems/FloatingPointGrouping.java
  std-bits/table/src/main/java/org/enso/table/operations/Distinct.java
  std-bits/table/src/main/java/org/enso/table/util/ConstantList.java
  test/Table_Tests/src/Common_Table_Operations/Aggregate_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Util.enso
  test/Table_Tests/src/In_Memory/Common_Spec.enso
  test/Table_Tests/src/In_Memory/Main.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
  test/Tests/src/Data/Vector_Spec.enso
  test/Tests/src/Semantic/Case_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#3984 Fix directing JSON data to JS visualizations.
  app/gui/view/graph-editor/src/component/visualization/foreign/java_script/instance.rs
Labels: CI: No changelog needed

#3990 Fail runner when update manifest fails
  engine/runner/src/main/scala/org/enso/runner/Main.scala
Labels: CI: Ready to merge, CI: No changelog needed

#3982 Recover from invalid metadata
  lib/rust/parser/jni/src/lib.rs
  lib/rust/parser/src/metadata.rs
Labels: CI: Ready to merge, CI: No changelog needed

#3975 Build script updates
  .github/workflows/benchmark.yml
  Cargo.lock
  Cargo.toml
  build/base/src/extensions.rs
  build/base/src/extensions/os_str.rs
  build/base/src/extensions/path.rs
  build/base/src/lib.rs
  build/build/examples/s3.rs
  build/build/paths.yaml
  build/build/src/engine.rs
  build/build/src/engine/context.rs
  build/build/src/enso.rs
  build/build/src/ide/web.rs
  build/build/src/paths.rs
  build/build/src/postgres.rs
  build/build/src/project.rs
  build/build/src/version.rs
  build/ci_utils/Cargo.toml
  build/ci_utils/src/actions/artifacts.rs
  build/ci_utils/src/actions/artifacts/upload.rs
  build/ci_utils/src/actions/env.rs
  build/ci_utils/src/actions/env_file.rs
  build/ci_utils/src/actions/workflow.rs
  build/ci_utils/src/actions/workflow/definition.rs
  build/ci_utils/src/cache/goodie.rs
  build/ci_utils/src/cache/goodie/binaryen.rs
  build/ci_utils/src/cache/goodie/graalvm.rs
  build/ci_utils/src/cache/goodie/sbt.rs
  build/ci_utils/src/env.rs
  build/ci_utils/src/env/accessor.rs
  build/ci_utils/src/env/known.rs
  build/ci_utils/src/goodies/musl.rs
  build/ci_utils/src/lib.rs
  build/ci_utils/src/program/command.rs
  build/ci_utils/src/program/shell.rs
  build/ci_utils/src/programs/cargo.rs
  build/ci_utils/src/programs/cmd.rs
  build/ci_utils/src/programs/docker.rs
  build/ci_utils/src/programs/graal.rs
  build/ci_utils/src/programs/pwsh.rs
  build/ci_utils/src/programs/sh.rs
  build/ci_utils/src/serde.rs
  build/cli/src/ci_gen.rs
Labels: CI: No changelog needed

#3979 Curried and lambda function invocation should be both fast
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array_Proxy.enso
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/CurriedFunctionBenchmarks.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/StringBenchmarks.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/TypePatternBenchmarks.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/VectorBenchmarks.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/argument/ArgumentSorterNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/argument/IndirectArgumentSorterNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/Function.java
  engine/runtime/src/test/java/org/enso/interpreter/test/BigNumberTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/DebuggingEnsoTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/ForeignMethodInvokeTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/TypeMembersTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/VectorTest.java
Labels: CI: Ready to merge, CI: No changelog needed

#3989 Allow for dry-running benchmark test
  distribution/lib/Standard/Test/0.0.0-dev/src/Bench.enso
  test/Benchmarks/src/Statistics/Count_Min_Max.enso
Labels: CI: Ready to merge, CI: No changelog needed

#3993 Switch WASM tests to Firefox
  build/build/src/project/wasm.rs
  build/build/src/project/wasm/test.rs
Labels: CI: No changelog needed

#3991 Update Component Browser only when user stops typing.
  app/gui/src/presenter/searcher.rs
  app/gui/view/src/project.rs
Labels: CI: Ready to merge, CI: No changelog needed

#3950 Visual indication of outdated VCS snapshot
  CHANGELOG.md
  app/gui/controller/engine-protocol/src/common/error.rs
  app/gui/controller/engine-protocol/src/language_server.rs
  app/gui/controller/engine-protocol/src/language_server/response.rs
  app/gui/src/controller/project.rs
  app/gui/src/model/project.rs
  app/gui/src/model/project/synchronized.rs
  app/gui/src/presenter/project.rs
  app/gui/view/graph-editor/src/component/breadcrumbs.rs
  app/gui/view/graph-editor/src/component/breadcrumbs/project_name.rs
  lib/rust/ensogl/app/theme/hardcoded/src/lib.rs
Labels: CI: Ready to merge

#3988 Always send method pointer updates
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/instrument/IdExecutionService.java
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
Labels: CI: Ready to merge, CI: No changelog needed

#3992 Implement hierarchy index in suggestion database
  app/gui/src/model/suggestion_database.rs
Labels: CI: Ready to merge, CI: No changelog needed

#3980 Demo scene & DocSections in suggestion database
  app/gui/src/controller/searcher.rs
  app/gui/src/documentation_debug_scene.rs
  app/gui/src/lib.rs
  app/gui/src/model/suggestion_database.rs
  app/gui/src/model/suggestion_database/entry.rs
  app/gui/src/model/suggestion_database/mock.rs
  build-config.yaml
Labels: CI: Ready to merge, CI: No changelog needed

#3995 Fixing set_size regression.
  app/gui/view/component-browser/component-list-panel/src/lib.rs
  app/gui/view/debug_scene/icons/src/lib.rs
  app/gui/view/graph-editor/src/builtin/visualization/native/error.rs
  app/gui/view/graph-editor/src/builtin/visualization/native/raw_text.rs
  app/gui/view/graph-editor/src/builtin/visualization/native/text_grid.rs
  app/gui/view/graph-editor/src/component/node.rs
  app/gui/view/graph-editor/src/component/node/output/port.rs
  app/gui/view/graph-editor/src/component/profiling.rs
  app/gui/view/graph-editor/src/component/visualization/container.rs
  app/gui/view/graph-editor/src/component/visualization/container/action_bar.rs
  app/gui/view/graph-editor/src/component/visualization/foreign/java_script/instance.rs
  app/gui/view/graph-editor/src/component/visualization/instance.rs
  app/gui/view/src/documentation.rs
  app/gui/view/welcome-screen/src/lib.rs
  build/build/src/project/wasm/test.rs
  lib/rust/ensogl/component/grid-view/src/lib.rs
  lib/rust/ensogl/component/gui/src/component.rs
  lib/rust/ensogl/component/sequence-diagram/src/lib.rs
  lib/rust/ensogl/component/slider/src/lib.rs
  lib/rust/ensogl/component/slider/src/model.rs
  lib/rust/ensogl/core/src/display/symbol/dom.rs
  lib/rust/ensogl/example/dom-symbols/src/lib.rs
  lib/rust/types/src/dim_macros.rs
Labels: CI: No changelog needed

#3997 Adds Date, Time_Of_Day and Date_Time support to Excel IO
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Map.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/JDBC_Connection.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Bench.enso
  std-bits/table/src/main/java/org/enso/table/data/index/MultiValueIndex.java
  std-bits/table/src/main/java/org/enso/table/excel/ExcelRow.java
  test/Table_Tests/data/TestSheet.xlsx
  test/Table_Tests/data/TestSheetOld.xls
  test/Table_Tests/src/IO/Excel_Spec.enso
Labels: CI: Ready to merge

#3942 Implement SKIP/FREEZE in parser/TreeToIr
  engine/runtime/src/main/java/org/enso/compiler/TreeToIr.java
  engine/runtime/src/test/java/org/enso/compiler/EnsoCompilerTest.java
  lib/rust/parser/debug/tests/parse.rs
  lib/rust/parser/src/macros/built_in.rs
Labels: CI: Ready to merge, CI: No changelog needed

#4000 Workaround the JS serialisation issue for errors.
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Preprocessor.enso
Labels: CI: Ready to merge, CI: No changelog needed

#3996 Allow overriding electron-builder target.
  app/ide-desktop/lib/client/electron-builder-config.ts
  build/build/src/ide/web.rs
  build/build/src/project/ide.rs
  build/ci_utils/src/program/command.rs
  build/cli/src/arg/ide.rs
  build/cli/src/lib.rs
Labels: CI: No changelog needed

#4001 Dry-run Enso benchmarks when checking engine in CI.
  build/build/src/engine.rs
  build/build/src/engine/context.rs
  build/build/src/enso.rs
  build/cli/src/arg/ide.rs
  build/cli/src/lib.rs
Labels: CI: No changelog needed

#3994 Browser selection for wasm tests
  Cargo.lock
  app/gui/src/documentation_debug_scene.rs
  build/build/src/project/wasm.rs
  build/build/src/project/wasm/test.rs
  build/cli/Cargo.toml
  build/cli/src/arg/wasm.rs
  build/cli/src/lib.rs
Labels: CI: No changelog needed

#3998 Clean restart on keypress
  app/gui/controller/engine-protocol/src/language_server.rs
  app/gui/controller/engine-protocol/src/language_server/types.rs
  app/gui/src/model/execution_context/synchronized.rs
Labels: CI: Ready to merge, CI: No changelog needed

#4002 Fix collapsed node is not updating visualizations
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/TestMessages.scala
Labels: CI: Ready to merge, CI: No changelog needed

#3831 Add benchmarks comparing ArrayProxy with elements generated ad-hoc with a regular Vector
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array_Proxy.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Error/Illegal_Argument.enso
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/ArrayProxyBenchmarks.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/VectorBenchmarks.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/ArrayProxy.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/builtins/SafeWrapException.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/builtins/TypeWithKind.java
  test/Benchmarks/src/Vector/Array_Proxy_Bench.enso
  test/Benchmarks/src/Vector/Main.enso
  test/Tests/src/Data/Array_Proxy_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#3985 Grid-view based dropdown component
  CHANGELOG.md
  Cargo.lock
  app/gui/view/component-browser/component-list-panel/breadcrumbs/src/lib.rs
  app/gui/view/component-browser/component-list-panel/grid/src/lib.rs
  app/gui/view/graph-editor/src/component/node/input/area.rs
  app/gui/view/graph-editor/src/component/node/input/port.rs
  build-config.yaml
  lib/rust/ensogl/component/Cargo.toml
  lib/rust/ensogl/component/drop-down/Cargo.toml
  lib/rust/ensogl/component/drop-down/src/entry.rs
  lib/rust/ensogl/component/drop-down/src/lib.rs
  lib/rust/ensogl/component/drop-down/src/model.rs
  lib/rust/ensogl/component/grid-view/src/entry.rs
  lib/rust/ensogl/component/grid-view/src/entry/visible.rs
  lib/rust/ensogl/component/grid-view/src/lib.rs
  lib/rust/ensogl/component/grid-view/src/scrollable.rs
  lib/rust/ensogl/component/grid-view/src/selectable/highlight/layer.rs
  lib/rust/ensogl/component/gui/src/component.rs
  lib/rust/ensogl/component/scroll-area/src/lib.rs
  lib/rust/ensogl/component/scrollbar/src/lib.rs
  lib/rust/ensogl/component/src/lib.rs
  lib/rust/ensogl/core/Cargo.toml
  lib/rust/ensogl/core/src/display/garbage.rs
  lib/rust/ensogl/core/src/display/render/passes/symbols.rs
  lib/rust/ensogl/core/src/display/scene.rs
  lib/rust/ensogl/core/src/display/scene/layer.rs
  lib/rust/ensogl/core/src/display/shape/primitive/system.rs
  lib/rust/ensogl/example/Cargo.toml
  lib/rust/ensogl/example/complex-shape-system/src/lib.rs
  lib/rust/ensogl/example/drop-down/Cargo.toml
  lib/rust/ensogl/example/drop-down/src/lib.rs
  lib/rust/ensogl/example/scroll-area/src/lib.rs
  lib/rust/ensogl/example/src/lib.rs
  lib/rust/frp/src/nodes.rs
  lib/rust/frp/src/stream.rs
  lib/rust/types/build.rs
Labels: CI: Ready to merge, CI: Clean build required

#4004 Add globs to logger configuration
  docs/infrastructure/logging.md
  lib/scala/logging-service/src/main/scala/org/enso/loggingservice/internal/LoggingSettings.scala
Labels: CI: Ready to merge, CI: No changelog needed

#3999 Integrate Tailwind framework
  .prettierignore
  Cargo.lock
  app/gui/view/Cargo.toml
  app/gui/view/documentation/Cargo.toml
  app/gui/view/documentation/assets/.gitignore
  app/gui/view/documentation/assets/input.css
  app/gui/view/documentation/assets/spinner.html
  app/gui/view/documentation/build.rs
  app/gui/view/documentation/package.json
  app/gui/view/documentation/src/lib.rs
  app/gui/view/documentation/tailwind.config.js
  app/gui/view/src/lib.rs
  build-config.yaml
Labels: CI: Ready to merge, CI: No changelog needed

#3956 Convert Any.== to a builtin
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Any.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Boolean.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Locale.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Duration.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Period.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Of_Day.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Zone.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Error.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/URI.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Helpers.enso
  docs/distribution/launcher.md
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/EqualsBenchmarks.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/bool/EqualsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsAnyNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/EqualsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/decimal/EqualsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/EqualsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoDate.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoDuration.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoFile.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoTimeOfDay.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Vector.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/number/EnsoBigInteger.java
  engine/runtime/src/main/scala/org/enso/compiler/data/BindingsMap.scala
  test/Tests/src/Data/Array_Spec.enso
  test/Tests/src/Data/Bool_Spec.enso
  test/Tests/src/Data/Time/Date_Time_Spec.enso
  test/Tests/src/Data/Time/Time_Zone_Spec.enso
  test/Tests/src/Main.enso
  test/Tests/src/Network/URI_Spec.enso
  test/Tests/src/Semantic/Equals_Spec.enso
  test/Tests/src/System/File_Spec.enso
Labels: CI: Ready to merge

#4008 IGV can jump to JMH sources & more
  CHANGELOG.md
  docs/CONTRIBUTING.md
  docs/debugger/README.md
  docs/debugger/chrome-debugger.png
  docs/debugger/java-debugger.png
  docs/runtime-guide.md
  project/FrgaalJavaCompiler.scala
  tools/enso4igv/README.md
  tools/enso4igv/pom.xml
  tools/enso4igv/src/main/java/org/enso/tools/enso4igv/EnsoDataObject.java
  tools/enso4igv/src/main/java/org/enso/tools/enso4igv/EnsoLogicalView.java
  tools/enso4igv/src/main/java/org/enso/tools/enso4igv/EnsoSbtClassPathProvider.java
  tools/enso4igv/src/main/java/org/enso/tools/enso4igv/EnsoSbtProject.java
  tools/enso4igv/src/main/java/org/enso/tools/enso4igv/GraalVMSourceForBinaryQuery.java
  tools/enso4igv/src/main/java/org/enso/tools/enso4igv/NextToSourceForBinaryQueryImpl.java
  tools/enso4igv/src/main/resources/org/enso/tools/enso4igv/enso.png
  tools/enso4igv/src/main/resources/org/enso/tools/enso4igv/enso.svg
Labels: CI: Ready to merge

#4011 Nested type declaration shall yield a syntax error
  engine/runtime/src/main/java/org/enso/compiler/TreeToIr.java
  engine/runtime/src/test/java/org/enso/compiler/EnsoCompilerTest.java
Labels: CI: Ready to merge, CI: No changelog needed

#4005 Simplify compilation of nested patterns
  CHANGELOG.md
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/NestedPatternCompilationBenchmarks.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/BooleanBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/BranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/BranchResult.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/BranchSelectedException.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/CaseNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/CatchAllBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/CatchTypeBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/ConstructorBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/NumericLiteralBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/ObjectEqualityBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/PolyglotBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/PolyglotSymbolTypeBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/StringLiteralBranchNode.java
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DataflowAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DemandAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/TailCall.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/NestedPatternMatch.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/lint/ShadowedPatternFields.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/lint/UnusedBindings.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/optimise/UnreachableMatchBranches.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/DocumentationComments.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/IgnoredBindings.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/NestedPatternMatchTest.scala
Labels: CI: Ready to merge
