Repository enso-org/enso, pull requests merged in 2022-01, with the labels that each got.

#3217 Remove references to dependent types
  docs/enso-philosophy.md
  docs/polyglot/polyglot-bindings.md
  docs/types/README.md
  docs/types/dependent-typing.md
  docs/types/goals.md
  docs/types/hierarchy.md
  docs/types/references.md
Labels: Type: Enhancement, Difficulty: Core Contributor, Change: Non-Breaking, Priority: Medium, Category: Documentation

#3223 Fix a few typos in code
  build.sbt
  engine/runtime/src/main/resources/Builtins.enso
Labels: Change: Non-Breaking

#3235 Add support for the component groups syntax
  engine/runner/src/main/scala/org/enso/runner/Main.scala
  lib/scala/editions/src/main/scala/org/enso/editions/LibraryName.scala
  lib/scala/pkg/src/main/scala/org/enso/pkg/ComponentGroup.scala
  lib/scala/pkg/src/main/scala/org/enso/pkg/Config.scala
  lib/scala/pkg/src/main/scala/org/enso/pkg/ConfigCodecs.scala
  lib/scala/pkg/src/main/scala/org/enso/pkg/Package.scala
  lib/scala/pkg/src/test/scala/org/enso/pkg/ConfigSpec.scala
Labels: Type: Enhancement, Difficulty: Core Contributor, Change: Non-Breaking, Priority: High, Category: Backend
