Repository enso-org/enso, pull requests merged in 2022-08, with the labels that each got.

#3622 Grid view selection and hover
  CHANGELOG.md
  Cargo.lock
  build-config.yaml
  lib/rust/ensogl/component/grid-view/src/entry.rs
  lib/rust/ensogl/component/grid-view/src/lib.rs
  lib/rust/ensogl/component/grid-view/src/scrollable.rs
  lib/rust/ensogl/component/grid-view/src/selectable.rs
  lib/rust/ensogl/component/grid-view/src/selectable/highlight.rs
  lib/rust/ensogl/component/grid-view/src/selectable/highlight/layer.rs
  lib/rust/ensogl/component/grid-view/src/selectable/highlight/shape.rs
  lib/rust/ensogl/component/grid-view/src/simple.rs
  lib/rust/ensogl/component/scroll-area/src/lib.rs
  lib/rust/ensogl/core/src/data/color/space/def.rs
  lib/rust/ensogl/core/src/display/shape/primitive/def/var.rs
  lib/rust/ensogl/core/src/display/shape/primitive/glsl/math.glsl
  lib/rust/ensogl/example/grid-view/Cargo.toml
  lib/rust/ensogl/example/grid-view/src/lib.rs
  lib/rust/types/src/algebra.rs
Labels: CI: Ready to merge

#3627 Parser: implement import
  lib/rust/metamodel/src/java/from_meta.rs
  lib/rust/parser/generate-java/src/serialization.rs
  lib/rust/parser/src/macros/built_in.rs
  lib/rust/parser/src/syntax/tree.rs
  lib/rust/parser/tests/parse.rs
Labels: CI: Ready to merge

#3617 Create `Index_Sub_Range` type and update `Text.take` and `Text.drop`
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Index_Sub_Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Span.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Text_Sub_Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Error/Common.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Random.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/constant/ConstructorNode.java
  std-bits/base/src/main/java/org/enso/base/Random_Utils.java
  test/Table_Tests/src/Column_Spec.enso
  test/Tests/src/Data/Text/Codepoint_Ranges_Spec.enso
  test/Tests/src/Data/Text_Spec.enso
  test/Tests/src/Data/Time/Date_Spec.enso
  test/Tests/src/Data/Vector_Spec.enso
  test/Tests/src/Main.enso
  test/Tests/src/Random_Spec.enso
Labels: CI: Ready to merge

#3630 Update CODEOWNERS
  .github/CODEOWNERS
Labels: CI: Ready to merge

#3625 Layouting algorithm for the Favorites section
  app/gui/src/presenter/searcher/provider.rs
  app/gui/view/component-browser/searcher-list-panel/src/column_grid.rs
  app/gui/view/component-browser/searcher-list-panel/src/layouting.rs
  app/gui/view/component-browser/searcher-list-panel/src/lib.rs
  app/gui/view/debug_scene/component-list-panel-view/src/lib.rs
  lib/rust/parser/src/syntax/tree.rs
Labels: CI: Ready to merge

#3604 Fix: Selection does not follow mouse when scrolling and can show half-way between entries
  app/gui/src/presenter/searcher.rs
  app/gui/src/presenter/searcher/provider.rs
  app/gui/view/component-browser/component-group/src/lib.rs
  app/gui/view/component-browser/component-group/src/set.rs
  app/gui/view/component-browser/component-group/src/wide.rs
  app/gui/view/component-browser/searcher-list-panel/src/lib.rs
  app/gui/view/debug_scene/component-group/src/lib.rs
Labels: CI: Ready to merge

#3623 Add text/openBuffer command
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManager.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonRpc.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/text/OpenBufferHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/BufferRegistry.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/CollaborativeBuffer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/TextApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/TextProtocol.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/TextOperationsTest.scala
Labels: CI: Ready to merge

#3633 Allow for importing methods
  CHANGELOG.md
  engine/runtime/src/test/scala/org/enso/compiler/test/codegen/AstToIrTest.scala
  lib/scala/syntax/definition/src/main/scala/org/enso/syntax/text/AST.scala
  lib/scala/syntax/definition/src/main/scala/org/enso/syntax/text/ast/meta/Builtin.scala
  test/Tests/src/Semantic/Names_Spec.enso
Labels: CI: Ready to merge

#3624 Fix REPL runner
  engine/runner/src/main/scala/org/enso/runner/Main.scala
Labels: CI: Ready to merge

#3626 Parser: Unary minus
  lib/rust/parser/src/lexer.rs
  lib/rust/parser/src/syntax/operator.rs
  lib/rust/parser/src/syntax/token.rs
  lib/rust/parser/tests/parse.rs
  lib/rust/prelude/src/vec.rs
Labels: CI: Ready to merge

#3605 Parser: hide internal APIs in generated Java
  Cargo.lock
  lib/rust/metamodel/src/java/bincode.rs
  lib/rust/metamodel/src/java/syntax.rs
  lib/rust/parser/generate-java/java/org/enso/syntax2/Either.java
  lib/rust/parser/generate-java/java/org/enso/syntax2/FormatException.java
  lib/rust/parser/generate-java/java/org/enso/syntax2/Message.java
  lib/rust/parser/generate-java/src/bin/java-tests.rs
  lib/rust/parser/generate-java/src/lib.rs
Labels: CI: Ready to merge

#3636 Left align component browser to the edited node
  app/gui/view/src/component_browser.rs
  lib/rust/ensogl/core/src/display/camera/camera2d.rs
Labels: CI: Ready to merge

#3618 Enable caching in visualization functions
  CHANGELOG.md
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistry.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/MethodPointer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/VisualisationConfiguration.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/ExecutionContextJsonMessages.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/VisualisationOperationsTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/FunctionCallInstrumentationNode.java
  engine/runtime/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/CacheInvalidation.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/ExecutionContextManager.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/ExecutionContextState.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/Visualisation.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/VisualisationHolder.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/AttachVisualisationCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/EditFileCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/ModifyVisualisationCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/RenameProjectCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/SetExpressionValueCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/UpsertVisualisationJob.scala
Labels: CI: Ready to merge

#3639 Fix benchmarks
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/AtomBenchmarks.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/CallableBenchmarks.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/NamedDefaultedArgumentBenchmarks.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/RecursionBenchmarks.java
  engine/runtime/src/bench/scala/org/enso/interpreter/bench/fixtures/semantic/AtomFixtures.scala
  engine/runtime/src/bench/scala/org/enso/interpreter/bench/fixtures/semantic/CallableFixtures.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/InterpreterTest.scala
Labels: CI: Ready to merge

#3629 Add `Vector.take` and `Vector.drop` functions
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Text_Sub_Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Runtime.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Warning.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Dialect/Postgres.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Dialect/SQLite.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Internal/Aggregate_Helper.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Aggregate_Column_Helper.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Delimited_Reader.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
  std-bits/base/src/main/java/org/enso/base/Random_Utils.java
  test/Benchmarks/src/Vector.enso
  test/Table_Tests/src/Aggregate_Column_Spec.enso
  test/Table_Tests/src/Aggregate_Spec.enso
  test/Table_Tests/src/Database/Redshift_Spec.enso
  test/Table_Tests/src/Table_Spec.enso
  test/Tests/src/Data/Range_Spec.enso
  test/Tests/src/Data/Text/Default_Regex_Engine_Spec.enso
  test/Tests/src/Data/Text/Text_Sub_Range_Spec.enso
  test/Tests/src/Data/Text_Spec.enso
  test/Tests/src/Data/Vector/Slicing_Helpers_Spec.enso
  test/Tests/src/Data/Vector_Spec.enso
  test/Tests/src/Main.enso
  test/Tests/src/Random_Spec.enso
  test/Tests/src/Runtime/Stack_Traces_Spec.enso
  test/Tests/src/Semantic/Warnings_Spec.enso
  test/Tests/src/System/File_Spec.enso
Labels: CI: Ready to merge

#3640 Verify benchmarks compile and execute in the gate
  .github/workflows/benchmark.yml
  Cargo.lock
  build.sbt
  engine/runtime/src/bench/java/org/enso/interpreter/bench/BenchmarksRunner.java
Labels: Category: Build, CI: Ready to merge

#3637 Support Autosave for open buffers
  CHANGELOG.md
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/TimingsConfig.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonRpc.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/Buffer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/BufferRegistry.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/CollaborativeBuffer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/TextApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/TextProtocol.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/TextOperationsTest.scala
Labels: CI: Ready to merge

#3613 Implement reversion of nodes after editing via searcher.
  app/gui/src/controller/graph.rs
  app/gui/src/controller/searcher.rs
  app/gui/src/presenter/searcher.rs
Labels: CI: Ready to merge

#3641 Support pattern matching on constants
  CHANGELOG.md
  build.sbt
  distribution/engine/THIRD-PARTY/NOTICE
  distribution/engine/THIRD-PARTY/com.ibm.icu.icu4j-71.1/LICENSE
  distribution/engine/THIRD-PARTY/com.ibm.icu.icu4j-71.1/NOTICES
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/NumericLiteralBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/StringLiteralBranchNode.java
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstToIr.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstView.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DataflowAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/TailCall.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/NestedPatternMatch.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/lint/ShadowedPatternFields.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/lint/UnusedBindings.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/optimise/UnreachableMatchBranches.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/IgnoredBindings.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/codegen/AstToIrTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/NestedPatternMatchTest.scala
  test/Tests/src/Semantic/Case_Spec.enso
  tools/legal-review/engine/com.ibm.icu.icu4j-71.1/copyright-ignore
  tools/legal-review/engine/com.ibm.icu.icu4j-71.1/copyright-keep
  tools/legal-review/engine/com.ibm.icu.icu4j-71.1/custom-license
  tools/legal-review/engine/com.ibm.icu.icu4j-71.1/files-keep
  tools/legal-review/engine/report-state
  tools/legal-review/engine/reviewed-licenses/Unicode_ICU_License
Labels: CI: Ready to merge

#3646 Fix zooming regression in demo scene & fix switching of the navigator in the component browser
  app/gui/view/component-browser/searcher-list-panel/src/lib.rs
  app/gui/view/debug_scene/interface/src/lib.rs
  app/gui/view/src/component_browser.rs
Labels: CI: Ready to merge

#3642 Update apply-edit benchmark to use lazy visualization
  tools/language-server/wstest/benchmarks/apply-edit/README.md
  tools/language-server/wstest/benchmarks/apply-edit/ignore_responses.txt
  tools/language-server/wstest/benchmarks/apply-edit/init.txt
  tools/language-server/wstest/benchmarks/set-expression-value/README.md
Labels: CI: Ready to merge

#3649 Increase library upload timeout in tests
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/LibrariesTest.scala
Labels: CI: Ready to merge

#3376 Add type system documentation
  docs/types/types.md
Labels: CI: Ready to merge

#3650 Use Java's LocalDate for parsing date in tests
  test/Tests/src/Data/Time/Date_Spec.enso
Labels: CI: Ready to merge

#3621 Virtual Entries in Component Browser
  Cargo.lock
  app/gui/Cargo.toml
  app/gui/controller/double-representation/Cargo.toml
  app/gui/controller/double-representation/src/project.rs
  app/gui/src/controller/searcher.rs
  app/gui/src/controller/searcher/action.rs
  app/gui/src/controller/searcher/action/hardcoded.rs
  app/gui/src/controller/searcher/component.rs
  app/gui/src/controller/searcher/component/builder.rs
  app/gui/src/controller/searcher/component/group.rs
  app/gui/src/controller/searcher/component/hardcoded.rs
  app/gui/src/lib.rs
  app/gui/src/model/execution_context.rs
  app/gui/src/model/execution_context/plain.rs
  app/gui/src/model/execution_context/synchronized.rs
  app/gui/src/presenter/searcher.rs
  app/gui/src/presenter/searcher/provider.rs
  app/gui/src/test.rs
  app/gui/view/component-browser/component-group/src/icon/define_macro.rs
  build-config.yaml
Labels: CI: Ready to merge

#3652 Filtering of Virtual Entries in Component Browser by input & return types.
  app/gui/src/controller/searcher.rs
  app/gui/src/controller/searcher/action.rs
  app/gui/src/controller/searcher/action/hardcoded.rs
  app/gui/src/controller/searcher/component/hardcoded.rs
  app/gui/src/presenter/searcher/provider.rs
Labels: CI: Ready to merge

#3644 Add key functions to Table to make it act as [Column]
  CHANGELOG.md
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Main.enso
  test/Table_Tests/src/Aggregate_Spec.enso
  test/Table_Tests/src/Common_Table_Spec.enso
  test/Table_Tests/src/Database/Codegen_Spec.enso
  test/Table_Tests/src/Database/Common_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Excel_Spec.enso
  test/Table_Tests/src/Table_Date_Spec.enso
  test/Table_Tests/src/Table_Spec.enso
Labels: CI: Ready to merge

#3645 Create new node when opening searcher and no node is selected.
  CHANGELOG.md
  app/gui/src/controller/searcher.rs
  app/gui/src/model/undo_redo.rs
  app/gui/src/presenter/graph.rs
  app/gui/src/presenter/graph/state.rs
  app/gui/src/presenter/project.rs
  app/gui/src/presenter/searcher.rs
  app/gui/src/test.rs
  app/gui/src/tests.rs
  app/gui/view/src/project.rs
Labels: Category: Backend, CI: Ready to merge

#3655 Lazy scatterplot for Vector & Table
  CHANGELOG.md
  app/gui/view/graph-editor/src/builtin/visualization/java_script/scatterPlot.js
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Scatter_Plot.enso
  test/Visualization_Tests/src/Scatter_Plot_Spec.enso
Labels: CI: Ready to merge

#3651 Grid View with variable column widths
  Cargo.lock
  build-config.yaml
  build/enso-formatter/src/main.rs
  lib/rust/ensogl/component/grid-view/Cargo.toml
  lib/rust/ensogl/component/grid-view/src/column_widths.rs
  lib/rust/ensogl/component/grid-view/src/entry.rs
  lib/rust/ensogl/component/grid-view/src/lib.rs
  lib/rust/ensogl/component/grid-view/src/selectable.rs
  lib/rust/ensogl/component/grid-view/src/selectable/highlight.rs
  lib/rust/ensogl/component/grid-view/src/simple.rs
  lib/rust/ensogl/component/grid-view/src/visible_area.rs
  lib/rust/ensogl/example/grid-view/src/lib.rs
Labels: CI: Ready to merge

#3628 Use Vector.from_polyglot_array to make Vectors backed by polyglot arrays
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Statistics.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Encoding.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Engine/Default.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/Http/Response.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Polyglot.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Polyglot/Proxy_Polyglot_Array.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Random.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/Platform.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Data/Histogram.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Data/Image.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Data/Matrix.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Data_Formatter.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/IO/Excel.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Aggregate_Column_Helper.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Delimited_Reader.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Parse_Values_Helper.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Unique_Name_Strategy.enso
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/node/CoercePrimitiveNode.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/node/JsForeignNode.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/node/RForeignNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/generic/ReadArrayElementNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/foreign/CoerceNothing.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/foreign/ForeignMethodCallNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  test/Tests/src/Data/Array_Spec.enso
  test/Tests/src/Data/Text/Utils_Spec.enso
  test/Tests/src/Data/Vector_Spec.enso
  test/Tests/src/Semantic/Js_Interop_Spec.enso
  test/Tests/src/Semantic/Python_Interop_Spec.enso
  test/Tests/src/Semantic/R_Interop_Spec.enso
  test/Visualization_Tests/src/Table_Spec.enso
Labels: CI: Ready to merge

#3656 Grid View Headers
  build-config.yaml
  build/src/main.rs
  lib/rust/ensogl/component/grid-view/src/entry.rs
  lib/rust/ensogl/component/grid-view/src/entry/visible.rs
  lib/rust/ensogl/component/grid-view/src/header.rs
  lib/rust/ensogl/component/grid-view/src/lib.rs
  lib/rust/ensogl/component/grid-view/src/scrollable.rs
  lib/rust/ensogl/component/grid-view/src/selectable.rs
  lib/rust/ensogl/component/grid-view/src/selectable/highlight.rs
  lib/rust/ensogl/component/grid-view/src/selectable/highlight/connected_entry.rs
  lib/rust/ensogl/component/grid-view/src/selectable/highlight/layer.rs
  lib/rust/ensogl/component/grid-view/src/selectable/highlight/shape.rs
  lib/rust/ensogl/component/grid-view/src/simple.rs
  lib/rust/ensogl/component/grid-view/src/visible_area.rs
  lib/rust/ensogl/core/src/display/shape/primitive/def/var.rs
  lib/rust/ensogl/example/grid-view/src/lib.rs
Labels: CI: Ready to merge

#3662 Component Panel List Layout structure.
  Cargo.lock
  app/gui/view/component-browser/searcher-list-panel/Cargo.toml
  app/gui/view/component-browser/searcher-list-panel/src/column_grid.rs
  app/gui/view/component-browser/searcher-list-panel/src/layout.rs
  app/gui/view/component-browser/searcher-list-panel/src/layouting.rs
  app/gui/view/component-browser/searcher-list-panel/src/lib.rs
Labels: CI: Ready to merge

#3659 Add api for updating searcher with selected component
  app/gui/src/controller/searcher.rs
  app/gui/src/presenter/searcher.rs
  app/gui/view/component-browser/searcher-list-panel/src/lib.rs
Labels: CI: Ready to merge

#3634 Remove `Array.set_at`
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Data/Matrix/Internal.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Geo_Map.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Helpers.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Scatter_Plot.enso
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Array.java
  std-bits/base/src/main/java/org/enso/base/Array_Utils.java
  test/Tests/src/Data/Array_Spec.enso
  test/Tests/src/Data/Vector_Spec.enso
  test/Visualization_Tests/src/Geo_Map_Spec.enso
Labels: CI: Ready to merge

#3669 Adding DateTime part functions
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Day_Of_Week.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Duration.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Of_Day.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Zone.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Error/Common.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/Http.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Examples/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Searcher/0.0.0-dev/src/Data_Science/Date_And_Time.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column_Type_Selection.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Data_Formatter.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Main.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/resolver/HostMethodCallNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoDate.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoDateTime.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoTimeOfDay.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoTimeZone.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/type/Types.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/builtins/TypeWithKind.java
  std-bits/base/src/main/java/org/enso/base/Time_Utils.java
  test/Table_Tests/src/Data_Formatter_Spec.enso
  test/Table_Tests/src/Delimited_Write_Spec.enso
  test/Table_Tests/src/Parse_Values_Spec.enso
  test/Table_Tests/src/Table_Time_Of_Day_Spec.enso
  test/Table_Tests/src/Table_Time_Spec.enso
  test/Tests/src/Data/Time/Date_Part_Spec.enso
  test/Tests/src/Data/Time/Date_Spec.enso
  test/Tests/src/Data/Time/Date_Time_Spec.enso
  test/Tests/src/Data/Time/Day_Of_Week_Spec.enso
  test/Tests/src/Data/Time/Duration_Spec.enso
  test/Tests/src/Data/Time/Spec.enso
  test/Tests/src/Data/Time/Time_Of_Day_Spec.enso
  test/Tests/src/Data/Time/Time_Zone_Spec.enso
Labels: CI: Ready to merge

#3666 Add Jaroslav as codeowner of interpreter dsl
  .github/CODEOWNERS
Labels: CI: Ready to merge

#3647 Add `Table.take` and `Table.drop` functions to In-Memory table
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Index_Sub_Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Text_Sub_Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
  std-bits/table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/DoubleStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/LongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/ObjectStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/Storage.java
  std-bits/table/src/main/java/org/enso/table/data/index/DefaultIndex.java
  std-bits/table/src/main/java/org/enso/table/data/index/HashIndex.java
  std-bits/table/src/main/java/org/enso/table/data/index/Index.java
  std-bits/table/src/main/java/org/enso/table/data/mask/SliceRange.java
  std-bits/table/src/main/java/org/enso/table/data/table/Column.java
  std-bits/table/src/main/java/org/enso/table/data/table/Table.java
  test/Table_Tests/src/Column_Spec.enso
  test/Table_Tests/src/Common_Table_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Database/Redshift_Spec.enso
  test/Table_Tests/src/Database/SQLite_Spec.enso
  test/Table_Tests/src/Table_Spec.enso
  test/Table_Tests/src/Util.enso
  test/Tests/src/Data/Text_Spec.enso
  test/Tests/src/Data/Vector/Slicing_Helpers_Spec.enso
  test/Tests/src/Data/Vector_Spec.enso
Labels: CI: Ready to merge

#3668 DataFormatter should infer datetime from values without seconds
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Data_Formatter.enso
  test/Table_Tests/data/datetime_sample.csv
  test/Table_Tests/data/time_of_day_sample.csv
  test/Table_Tests/src/Data_Formatter_Spec.enso
Labels: CI: Ready to merge

#3665 Split long lines to 1024 long chunks
  CHANGELOG.md
  app/gui/controller/engine-protocol/Cargo.toml
  app/gui/view/graph-editor/src/builtin/visualization/native/raw_text.rs
Labels: CI: Ready to merge

#3676 Remove a leftover debug print
  engine/runner/src/main/scala/org/enso/runner/Main.scala
Labels: CI: Ready to merge

#3673 Add storage support for Date, Time and DateTime to InMemory table
  CHANGELOG.md
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Data_Formatter.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Storage.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Main.enso
  std-bits/table/src/main/java/org/enso/table/data/column/builder/object/BoolBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/object/Builder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/object/DateBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/object/DateTimeBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/object/InferredBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/object/NumericBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/object/ObjectBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/object/StringBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/object/TimeOfDayBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/object/TypedBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/object/TypedBuilderImpl.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/string/StringStorageBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/DoubleBooleanOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/DoubleNumericOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/LongBooleanOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/LongNumericOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/text/StringBooleanOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/DateStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/DateTimeStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/DoubleStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/LongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/NumericStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/ObjectStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/SpecializedStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/Storage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/StringStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/TimeOfDayStorage.java
  std-bits/table/src/main/java/org/enso/table/data/index/DefaultIndex.java
  std-bits/table/src/main/java/org/enso/table/data/index/Index.java
  std-bits/table/src/main/java/org/enso/table/data/index/MultiValueIndex.java
  std-bits/table/src/main/java/org/enso/table/data/index/MultiValueKey.java
  std-bits/table/src/main/java/org/enso/table/data/table/Column.java
  std-bits/table/src/main/java/org/enso/table/data/table/Table.java
  std-bits/table/src/main/java/org/enso/table/data/table/problems/Problem.java
  std-bits/table/src/main/java/org/enso/table/parsing/BaseTimeParser.java
  std-bits/table/src/main/java/org/enso/table/parsing/DateParser.java
  std-bits/table/src/main/java/org/enso/table/parsing/DateTimeParser.java
  std-bits/table/src/main/java/org/enso/table/parsing/IdentityParser.java
  std-bits/table/src/main/java/org/enso/table/parsing/TimeOfDayParser.java
  std-bits/table/src/main/java/org/enso/table/parsing/TimeParser.java
  test/Table_Tests/src/Aggregate_Spec.enso
  test/Table_Tests/src/Column_Spec.enso
  test/Table_Tests/src/Data_Formatter_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Database/Redshift_Spec.enso
  test/Table_Tests/src/Database/SQLite_Spec.enso
  test/Table_Tests/src/Table_Date_Spec.enso
  test/Table_Tests/src/Table_Spec.enso
  test/Table_Tests/src/Table_Time_Of_Day_Spec.enso
  test/Table_Tests/src/Table_Time_Spec.enso
Labels: CI: Ready to merge
