Repository enso-org/enso, pull requests merged in 2022-03, with the labels that each got.

#3307 Remove mod-level "allow missing docs" in graph-editor; add entity-level FIXMEs.
  app/gui/view/graph-editor/src/builtin.rs
  app/gui/view/graph-editor/src/builtin/visualization.rs
  app/gui/view/graph-editor/src/component/node.rs
  app/gui/view/graph-editor/src/component/node/expression.rs
  app/gui/view/graph-editor/src/component/node/input.rs
  app/gui/view/graph-editor/src/component/node/input/area.rs
  app/gui/view/graph-editor/src/component/node/input/port.rs
  app/gui/view/graph-editor/src/component/node/output.rs
  app/gui/view/graph-editor/src/component/node/output/area.rs
  app/gui/view/graph-editor/src/component/node/output/port.rs
  app/gui/view/graph-editor/src/data.rs
  app/gui/view/graph-editor/src/lib.rs
Labels: CI: Ready to merge

#3310 Updating `Text.repeat` and adding `Text.*`
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  test/Tests/src/Data/Text_Spec.enso
Labels: CI: Ready to merge

#3308 Update the Language Server API
  distribution/lib/Standard/Searcher/0.0.0-dev/package.yaml
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/libraries/ComponentGroupsResolver.scala
  engine/language-server/src/main/scala/org/enso/languageserver/libraries/LibraryApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/libraries/LibraryComponentGroup.scala
  engine/language-server/src/main/scala/org/enso/languageserver/libraries/LocalLibraryManager.scala
  engine/language-server/src/main/scala/org/enso/languageserver/libraries/LocalLibraryManagerFailureMapper.scala
  engine/language-server/src/main/scala/org/enso/languageserver/libraries/LocalLibraryManagerProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/libraries/handler/EditionsListAvailableHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/libraries/handler/EditionsListDefinedComponentsHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/libraries/handler/EditionsListDefinedLibrariesHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/libraries/handler/LibraryGetMetadataHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/libraries/handler/LibraryGetPackageHandler.scala
  engine/language-server/src/test/scala/org/enso/languageserver/libraries/ComponentGroupsResolverSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/LibrariesTest.scala
  lib/scala/edition-updater/src/main/scala/org/enso/editions/updater/UpdatingEditionProvider.scala
  lib/scala/editions/src/main/scala/org/enso/editions/provider/EditionLoadingError.scala
  lib/scala/editions/src/main/scala/org/enso/editions/provider/FileSystemEditionProvider.scala
  lib/scala/editions/src/test/scala/org/enso/editions/EditionResolverSpec.scala
  lib/scala/pkg/src/main/scala/org/enso/pkg/ComponentGroup.scala
  lib/scala/pkg/src/main/scala/org/enso/pkg/ConfigCodecs.scala
  lib/scala/pkg/src/test/scala/org/enso/pkg/ConfigSpec.scala
Labels: Type: Bug, Difficulty: Core Contributor, Change: Non-Breaking, Priority: High, Category: Backend

#3303 Fix teardown for engine's testcases
  engine/language-server/src/test/scala/org/enso/languageserver/filemanager/ContentRootManagerSpec.scala
  engine/polyglot-api/src/test/scala/org/enso/polyglot/ModuleManagementTest.scala
Labels: CI: Ready to merge

#3236 Within Vector, use Array.Copy wherever possible
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/mutable/CopyNode.java
  test/Benchmarks/src/Vector.enso
  test/Tests/src/Data/Vector_Spec.enso
  test/Tests/src/System/File_Spec.enso
Labels: CI: Ready to merge

#3297 Flame Graph for Profiling Data
  Cargo.lock
  app/ide-desktop/lib/content/src/index.ts
  build/run.js
  lib/rust/ensogl/component/Cargo.toml
  lib/rust/ensogl/component/flame-graph/Cargo.toml
  lib/rust/ensogl/component/flame-graph/src/block.rs
  lib/rust/ensogl/component/flame-graph/src/lib.rs
  lib/rust/ensogl/component/gui/src/component.rs
  lib/rust/ensogl/component/text/src/component/area.rs
  lib/rust/ensogl/example/Cargo.toml
  lib/rust/ensogl/example/profiling-run-graph/Cargo.toml
  lib/rust/ensogl/example/profiling-run-graph/src/lib.rs
  lib/rust/ensogl/example/src/lib.rs
  lib/rust/profiler/Cargo.toml
  lib/rust/profiler/data/src/lib.rs
  lib/rust/profiler/flame-graph/Cargo.toml
  lib/rust/profiler/flame-graph/src/lib.rs
  lib/rust/profiler/src/internal.rs
Labels: CI: Ready to merge

#3315 Fix Error Payload Serialization
  docs/language-server/protocol-language-server.md
  docs/language-server/protocol-project-manager.md
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/VisualisationOperationsTest.scala
  lib/scala/json-rpc-server/src/main/scala/org/enso/jsonrpc/JsonProtocol.scala
  lib/scala/json-rpc-server/src/main/scala/org/enso/jsonrpc/MessageHandler.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectCreateDefaultToLatestSpec.scala
Labels: Type: Bug, Difficulty: Core Contributor, Change: Non-Breaking, Priority: High, Category: Backend, CI: Ready to merge

#3311 New Text.insert function
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  test/Tests/src/Data/Text_Spec.enso
Labels: CI: Ready to merge

#3314 Use `.isEmpty()` instead of `.length() == 0`
  std-bits/base/src/main/java/org/enso/base/Text_Utils.java
  std-bits/table/src/main/java/org/enso/table/format/csv/Parser.java
Labels: CI: Ready to merge

#3313 Fix the style of comments introduced in PR #3307.
  app/gui/view/graph-editor/src/builtin.rs
  app/gui/view/graph-editor/src/builtin/visualization.rs
  app/gui/view/graph-editor/src/component/node.rs
  app/gui/view/graph-editor/src/component/node/expression.rs
  app/gui/view/graph-editor/src/component/node/input.rs
  app/gui/view/graph-editor/src/component/node/input/area.rs
  app/gui/view/graph-editor/src/component/node/input/port.rs
  app/gui/view/graph-editor/src/component/node/output.rs
  app/gui/view/graph-editor/src/component/node/output/area.rs
  app/gui/view/graph-editor/src/component/node/output/port.rs
  app/gui/view/graph-editor/src/data.rs
  app/gui/view/graph-editor/src/lib.rs
Labels: CI: Ready to merge

#3317 Added `compare_to` to True/False
  CHANGELOG.md
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/bool/CompareToNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Bool.java
  test/Tests/src/Data/Bool_Spec.enso
Labels: CI: Ready to merge

#3318 Restructuring the Faker type and creating tests for Group_By
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Map.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Aggregate_Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Group_By.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Faker.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/mutable/CopyNode.java
  test/Benchmarks/src/Natural_Order_Sort.enso
  test/Benchmarks/src/Number_Parse.enso
  test/Benchmarks/src/Table/Group_By.enso
  test/Benchmarks/src/Text/Compare.enso
  test/Benchmarks/src/Text/Contains.enso
  test/Table_Tests/data/data.csv
  test/Table_Tests/src/Aggregate_Column_Spec.enso
  test/Table_Tests/src/Group_By_Spec.enso
  test/Tests/src/Data/Map_Spec.enso
Labels: CI: Ready to merge

#3328 Revert "Adding new node with (+) button"
  .github/CODEOWNERS
  CHANGELOG.md
  Cargo.lock
  app/gui/src/presenter/graph.rs
  app/gui/src/presenter/project.rs
  app/gui/src/presenter/searcher.rs
  app/gui/view/debug_scene/interface/src/lib.rs
  app/gui/view/graph-editor/src/component.rs
  app/gui/view/graph-editor/src/free_place_finder.rs
  app/gui/view/graph-editor/src/lib.rs
  app/gui/view/src/project.rs
  app/gui/view/src/searcher.rs
  app/gui/view/src/searcher/new.rs
  app/gui/view/src/status_bar.rs
  app/gui/view/src/window_control_buttons.rs
  app/gui/view/src/window_control_buttons/close.rs
  app/gui/view/src/window_control_buttons/common.rs
  app/gui/view/src/window_control_buttons/fullscreen.rs
  build/run.js
  integration-test/Cargo.toml
  integration-test/tests/graph_editor.rs
  lib/rust/ensogl/app/theme/hardcoded/src/lib.rs
  lib/rust/ensogl/component/Cargo.toml
  lib/rust/ensogl/component/button/Cargo.toml
  lib/rust/ensogl/component/src/lib.rs
  lib/rust/ensogl/core/src/display/scene.rs
Labels: CI: Ready to merge

#3316 Update Electron
  CHANGELOG.md
  app/ide-desktop/lib/client/package.js
  app/ide-desktop/lib/client/src/index.js
Labels: CI: Ready to merge

#3324 Data analysts should be able to use `Text.location_of` to find indexes within string using various matchers
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Matching_Mode.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Engine/Default.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Mode.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Span.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Text_Sub_Range.enso
  engine/launcher/src/main/resources/application.conf
  std-bits/base/src/main/java/org/enso/base/Text_Utils.java
  std-bits/base/src/main/java/org/enso/base/text/CaseFoldedString.java
  std-bits/base/src/main/java/org/enso/base/text/GraphemeSpan.java
  std-bits/base/src/main/java/org/enso/base/text/IntArrayBuilder.java
  std-bits/base/src/main/java/org/enso/base/text/StringSlice.java
  std-bits/base/src/main/java/org/enso/base/text/Utf16Span.java
  test/Tests/src/Data/Text/Default_Regex_Engine_Spec.enso
  test/Tests/src/Data/Text/Regex_Spec.enso
  test/Tests/src/Data/Text/Span_Spec.enso
  test/Tests/src/Data/Text/Utils_Spec.enso
  test/Tests/src/Data/Text_Spec.enso
  test/Tests/src/Examples_Spec.enso
  test/Tests/src/Main.enso
Labels: CI: Ready to merge

#3337 Refactor library warnings to use the new system
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Matching.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Error/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Error/Problem_Behavior.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Error/Warnings.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Runtime/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Warning.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Problems.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/GetStackTraceNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/warning/AttachWarningNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/warning/CreateWarningNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/warning/SetWarningsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Context.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/DataflowError.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Warning.java
  engine/runtime/src/main/resources/Builtins.enso
  test/Table_Tests/src/Common_Table_Spec.enso
  test/Table_Tests/src/Table_Spec.enso
  test/Tests/src/Data/Text/Matching_Spec.enso
  test/Tests/src/Semantic/Error_Spec.enso
  test/Tests/src/Semantic/Warnings_Spec.enso
Labels: CI: Ready to merge

#3339 Refactor table.group_by to table.aggregate
  CHANGELOG.md
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Aggregate_Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Group_By_Key.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  test/Benchmarks/src/Table/Aggregate.enso
  test/Benchmarks/src/Table/Group_By.enso
  test/Table_Tests/src/Aggregate_Spec.enso
  test/Table_Tests/src/Main.enso
Labels: CI: Ready to merge

#3340 Minor fixes for Text
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Span.enso
  test/Tests/src/Data/Text/Span_Spec.enso
  test/Tests/src/Data/Text/Utils_Spec.enso
  test/Tests/src/Data/Text_Spec.enso
Labels: CI: Ready to merge

#3342 Replace deprecated EpbContext calls and caching of Ordering
  engine/runtime/src/main/java/org/enso/interpreter/epb/EpbContext.java
  engine/runtime/src/main/java/org/enso/interpreter/epb/node/ForeignEvalNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/mutable/ComparatorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/CompareToNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/decimal/CompareToNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/CompareToNode.java
Labels: CI: Ready to merge

#3327 Node searcher zoom & edited node growth/shrink animation
  CHANGELOG.md
  app/gui/view/graph-editor/src/component/node.rs
  app/gui/view/graph-editor/src/component/node/growth_animation.rs
  app/gui/view/graph-editor/src/component/node/input/area.rs
  app/gui/view/graph-editor/src/component/node/output/area.rs
  app/gui/view/graph-editor/src/component/node/profiling.rs
  app/gui/view/graph-editor/src/lib.rs
  app/gui/view/src/documentation.rs
  app/gui/view/src/project.rs
  app/gui/view/src/searcher.rs
  lib/rust/ensogl/core/src/animation/easing.rs
  lib/rust/ensogl/core/src/animation/frp/animation.rs
  lib/rust/ensogl/core/src/animation/physics/inertia.rs
  lib/rust/ensogl/core/src/display/camera/camera2d.rs
  lib/rust/ensogl/core/src/display/navigation/navigator.rs
  lib/rust/ensogl/core/src/display/scene.rs
  lib/rust/ensogl/example/complex-shape-system/src/lib.rs
Labels: CI: Ready to merge

#3336 Fix performance issue with too many labels existing in the performance visualisation.
  lib/rust/ensogl/component/flame-graph/src/block.rs
Labels: CI: Ready to merge

#3348 Bump Rust toolchain to `nightly-2022-02-24`.
  app/gui/view/graph-editor/src/lib.rs
  lib/rust/ensogl/core/src/display/navigation/navigator/events.rs
  lib/rust/ensogl/core/src/lib.rs
  run
  rust-toolchain.toml
Labels: CI: Ready to merge

#3345 Fix enso-formatter unit test
  build/enso-formatter/src/main.rs
Labels: CI: Ready to merge

#3344 The library developer should be able to handle specific types of Panics while passing through others
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Number/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Matching.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Engine/Default.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Of_Day.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Error/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/Http.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/Http/Request.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/Uri.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Examples/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Codecs.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Data/Image.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Data/Matrix.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Io/Csv.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Helpers.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/CatchPanicNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/CaughtPanicConvertToDataflowErrorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/GetAttachedStackTraceNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/GetStackTraceNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/RecoverPanicNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/ThrowPanicNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/runtime/GetStackTraceNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/DataflowError.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/DataflowError.java
  engine/runtime/src/main/resources/Builtins.enso
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeErrorsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualisationsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/CompileDiagnosticsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/PanicsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/StateTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/TextTest.scala
  test/Database_Tests/src/Common_Spec.enso
  test/Tests/src/Data/Locale_Spec.enso
  test/Tests/src/Semantic/Conversion_Spec.enso
  test/Tests/src/Semantic/Error_Spec.enso
  test/Tests/src/Semantic/Js_Interop_Spec.enso
  test/Tests/src/Semantic/Python_Interop_Spec.enso
  test/Tests/src/Semantic/R_Interop_Spec.enso
  test/Tests/src/Semantic/Warnings_Spec.enso
  test/Tests/src/System/File_Spec.enso
Labels: CI: Ready to merge

#3347 Split documentation comment into sections
  build.sbt
  lib/scala/docs-generator/src/main/scala/org/enso/docs/generator/DocParserWrapper.scala
  lib/scala/docs-generator/src/main/scala/org/enso/docs/sections/ParsedSectionsBuilder.scala
  lib/scala/docs-generator/src/main/scala/org/enso/docs/sections/Section.scala
  lib/scala/docs-generator/src/main/scala/org/enso/docs/sections/package.scala
  lib/scala/docs-generator/src/test/scala/org/enso/docs/sections/ParsedSectionsBuilderTest.scala
  lib/scala/syntax/definition/src/main/scala/org/enso/syntax/text/ast/Doc.scala
  lib/scala/syntax/definition/src/main/scala/org/enso/syntax/text/spec/DocParserDef.scala
  lib/scala/syntax/specialization/shared/src/test/scala/org/enso/syntax/text/DocParserTests.scala
Labels: Type: Enhancement, Difficulty: Core Contributor, Change: Non-Breaking, Priority: High, Category: Backend

#3330 Initialize AtomConstructor's fields via local vars
  CHANGELOG.md
  engine/runtime/src/main/java/org/enso/interpreter/node/EnsoRootNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/atom/InstantiateNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/InstantiateAtomNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/AtomConstructor.java
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  test/Tests/src/Semantic/Default_Args_Spec.enso
Labels: CI: Ready to merge

#3346 Opening Component Browser by clicking on the output port
  CHANGELOG.md
  app/gui/view/graph-editor/src/component/node/output/area.rs
  app/gui/view/graph-editor/src/lib.rs
  integration-test/tests/graph_editor.rs
Labels: CI: Ready to merge

#3349 Refactor Aggregate Column
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Aggregate_Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Aggregate_Column_Aggregator.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Aggregate_Column_Helper.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  std-bits/table/src/main/java/org/enso/table/data/table/aggregate/AggregateColumn.java
  test/Table_Tests/src/Aggregate_Column_Spec.enso
  test/Table_Tests/src/Aggregate_Spec.enso
Labels: CI: Ready to merge

#3356 Make `Resource.bracket` not run the action if initializer failed with a dataflow error
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/CatchErrorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/resource/BracketNode.java
  test/Tests/src/Main.enso
  test/Tests/src/Resource/Bracket_Spec.enso
Labels: CI: Ready to merge

#3357 Quick-fix for Error.to_text CCE
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/ErrorToTextNode.java
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualisationsTest.scala
  test/Tests/src/Semantic/Error_Spec.enso
Labels: CI: Ready to merge

#3360 Implement Documentation Sections API
  CHANGELOG.md
  build.sbt
  distribution/lib/Standard/Base/0.0.0-dev/src/Error/Extensions.enso
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/search/DocSectionsBuilder.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SearchProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/DocSectionsBuilderTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/Suggestions.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/SuggestionsHandlerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/SuggestionsHandlerEventsTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/DocSection.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/Suggestion.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionDiff.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/context/SuggestionBuilderTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeSuggestionUpdatesTest.scala
  lib/scala/docs-generator/src/main/scala/org/enso/docs/generator/DocsGenerator.scala
  lib/scala/docs-generator/src/main/scala/org/enso/docs/sections/HtmlRepr.scala
  lib/scala/docs-generator/src/main/scala/org/enso/docs/sections/ParsedSectionsBuilder.scala
  lib/scala/docs-generator/src/main/scala/org/enso/docs/sections/Section.scala
  lib/scala/docs-generator/src/main/scala/org/enso/docs/sections/package.scala
  lib/scala/docs-generator/src/test/scala/org/enso/docs/sections/HtmlReprTest.scala
  lib/scala/docs-generator/src/test/scala/org/enso/docs/sections/ParsedSectionsBuilderTest.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/SuggestionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlSuggestionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/Tables.scala
  lib/scala/searcher/src/test/scala/org/enso/searcher/sql/SuggestionsRepoTest.scala
Labels: CI: Ready to merge

#3353 Aggregates in the Database library - MVP
  .github/workflows/scala.yml
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Dialect/Postgres.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Dialect/Redshift.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Dialect/Sqlite.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Internal/Aggregate_Helper.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Sql.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Aggregate_Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Aggregate_Column_Helper.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
  docs/CONTRIBUTING.md
  engine/runtime/src/main/resources/Builtins.enso
  test/Database_Tests/package.yaml
  test/Database_Tests/src/Main.enso
  test/Database_Tests/src/Postgresql_Spec.enso
  test/Table_Tests/src/Aggregate_Spec.enso
  test/Table_Tests/src/Common_Table_Spec.enso
  test/Table_Tests/src/Database/Codegen_Spec.enso
  test/Table_Tests/src/Database/Common_Spec.enso
  test/Table_Tests/src/Database/Helpers/Fake_Test_Connection.enso
  test/Table_Tests/src/Database/Main.enso
  test/Table_Tests/src/Database/Postgresql_Spec.enso
  test/Table_Tests/src/Database/README.md
  test/Table_Tests/src/Database/Redshift_Spec.enso
  test/Table_Tests/src/Database/Sqlite_Spec.enso
  test/Table_Tests/src/Database_Spec.enso
  test/Table_Tests/src/In_Memory_Tests.enso
  test/Table_Tests/src/Main.enso
  test/Table_Tests/src/Table_Spec.enso
Labels: CI: Ready to merge

#3352 GraphEditor Unit Tests
  app/gui/view/graph-editor/src/component/node.rs
  app/gui/view/graph-editor/src/component/node/input/area.rs
  app/gui/view/graph-editor/src/component/node/output/area.rs
  app/gui/view/graph-editor/src/lib.rs
  app/gui/view/src/project.rs
  integration-test/src/lib.rs
  integration-test/tests/graph_editor.rs
  lib/rust/ensogl/component/text/src/component/area.rs
  lib/rust/ensogl/component/text/src/component/selection.rs
  lib/rust/ensogl/core/src/application.rs
  lib/rust/ensogl/core/src/display/scene.rs
  lib/rust/profiler/data/src/lib.rs
Labels: CI: Ready to merge

#3370 Fix docparser
  build.sbt
  distribution/engine/THIRD-PARTY/NOTICE
  distribution/lib/Standard/Base/0.0.0-dev/THIRD-PARTY/NOTICE
  distribution/lib/Standard/Database/0.0.0-dev/THIRD-PARTY/NOTICE
  distribution/lib/Standard/Google_Api/0.0.0-dev/THIRD-PARTY/NOTICE
  distribution/lib/Standard/Image/0.0.0-dev/THIRD-PARTY/NOTICE
  distribution/lib/Standard/Table/0.0.0-dev/THIRD-PARTY/NOTICE
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/ContentRootManagerActor.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/Suggestion.scala
  engine/runtime/src/main/scala/org/enso/compiler/ModuleCache.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeComponentsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeStdlibTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/TestEdition.scala
  lib/scala/syntax/definition/src/main/scala/org/enso/syntax/text/spec/DocParserDef.scala
  lib/scala/syntax/specialization/shared/src/test/scala/org/enso/syntax/text/DocParserTests.scala
  tools/legal-review/Base/report-state
  tools/legal-review/Database/report-state
  tools/legal-review/Google_Api/report-state
  tools/legal-review/Image/report-state
  tools/legal-review/Table/report-state
  tools/legal-review/engine/report-state
Labels: CI: Ready to merge

#3371 Implement Error-Handling for Database aggregations, unify some error helpers across backends
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Matching.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Error/Common.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Warning.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Internal/Aggregate_Helper.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Sql.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Aggregate_Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Aggregate_Column_Aggregator.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Aggregate_Column_Helper.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Problem_Builder.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Vector_Builder.enso
  test/Table_Tests/src/Aggregate_Column_Spec.enso
  test/Table_Tests/src/Aggregate_Spec.enso
  test/Table_Tests/src/Database/Common_Spec.enso
  test/Table_Tests/src/Database/Helpers/Name_Generator.enso
  test/Table_Tests/src/Database/Postgresql_Spec.enso
  test/Table_Tests/src/Database/Redshift_Spec.enso
  test/Table_Tests/src/Database/Sqlite_Spec.enso
  test/Tests/src/Data/Text/Matching_Spec.enso
  test/Visualization_Tests/src/Table_Spec.enso
Labels: CI: Ready to merge

#3301 Placement of newly opened Component Browser dictated by the mouse pointer.
  CHANGELOG.md
  Cargo.toml
  app/gui/view/graph-editor/src/component/node.rs
  app/gui/view/graph-editor/src/lib.rs
  app/gui/view/graph-editor/src/new_node_position.rs
  app/gui/view/graph-editor/src/new_node_position/free_place_finder.rs
  app/gui/view/graph-editor/src/selection/bounding_box.rs
  build/run.js
  integration-test/tests/graph_editor.rs
  lib/rust/ensogl/app/theme/hardcoded/src/lib.rs
Labels: CI: Ready to merge
