Repository enso-org/enso, pull requests merged in 2022-02, with the labels that each got.

#3244 Implement the component resolving algorithm
  engine/runner/src/main/scala/org/enso/runner/Main.scala
  engine/runtime/src/main/java/org/enso/interpreter/OptionsHelper.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Context.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/PackageRepository.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeComponentsTest.scala
  lib/scala/library-manager/src/main/scala/org/enso/librarymanager/ProjectLoadingFailure.scala
  lib/scala/pkg/src/main/scala/org/enso/pkg/ComponentGroup.scala
  lib/scala/pkg/src/test/scala/org/enso/pkg/ConfigSpec.scala
Labels: Type: Enhancement, Difficulty: Core Contributor, Change: Non-Breaking, Priority: High, Category: Backend

#3263 Fix CHANGELOG formatting
  CHANGELOG.md
Labels: Type: Bug, Difficulty: Core Contributor, Change: Non-Breaking, Priority: High, Category: Documentation, Type: Release

#3258 Upgrade Truffle and Graal to Version 21.3.0 (#180303532)
  .github/workflows/codeql-analysis.yml
  .github/workflows/legal-review.yml
  .github/workflows/nightly.yml
  .github/workflows/release-publish-edition.yml
  .github/workflows/release.yml
  .github/workflows/scala.yml
  CHANGELOG.md
  RELEASES.md
  build.sbt
  docs/infrastructure/native-image.md
  engine/runtime/src/main/java/org/enso/interpreter/node/ClosureRootNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/dispatch/LoopingCallOptimiserNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/io/GetUserHomeNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/EqualsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/utils/BigIntegerOps.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Context.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/ThreadManager.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/type/Types.java
  project/NativeImage.scala
  test/Tests/src/Network/Http_Spec.enso
  tools/ci/docker/Dockerfile
Labels: Category: Compiler

#3267 Fix macOS icns generation.
  app/ide-desktop/lib/icons/src/index.js
Labels: Type: Enhancement, Difficulty: Beginner, Change: Non-Breaking, Priority: Highest, Category: Build, Size: Small

#3259 Implement Vector.flatten
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  test/Tests/src/Data/Vector_Spec.enso
Labels: Type: Enhancement, Difficulty: Beginner, Change: Non-Breaking, Category: Stdlib

#3279 Make Engine macOS check not required on PRs
  .github/settings.yml
Labels: Category: Build

#3280 Add Code Owners for missing Rust related config files.
  .github/CODEOWNERS
Labels: Category: Build

#3282 Ensure that `Text.compare_to` compares strings according to grapheme clusters
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Faker.enso
  std-bits/base/src/main/java/org/enso/base/Text_Utils.java
  test/Benchmarks/src/Text/Build.enso
  test/Benchmarks/src/Text/Compare.enso
  test/Tests/src/Data/Text_Spec.enso
Labels: Category: Stdlib, CI: Ready to merge

#3260 Allow collection of EnsoGL stats when Monitor panel is not visible
  app/ide-desktop/package-lock.json
  lib/rust/ensogl/core/src/debug/monitor.rs
  lib/rust/ensogl/core/src/debug/stats.rs
  lib/rust/ensogl/core/src/display/world.rs
  lib/rust/ensogl/core/src/display/world/stats.rs
  lib/rust/web/src/lib.rs
Labels: CI: Ready to merge

#3296 doc: Range datatype
  docs/language-server/protocol-language-server.md
  lib/scala/text-buffer/src/main/scala/org/enso/text/editing/model.scala
Labels: Type: Enhancement, Difficulty: Core Contributor, Change: Non-Breaking, Priority: Low, Category: Documentation

#3295 Restrict Graph Editor Zoom
  CHANGELOG.md
  app/gui/view/graph-editor/src/lib.rs
  lib/rust/ensogl/core/src/display/camera/camera2d.rs
  lib/rust/ensogl/core/src/display/navigation/navigator.rs
  lib/rust/ensogl/core/src/display/navigation/navigator/events.rs
Labels: CI: Ready to merge

#3285 Data analysts should be able to use `Text.contains` to check for substring using various matcher techniques.
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Matching.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Engine/Default.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/Http/Request.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Matching.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Sort_Method.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Faker.enso
  std-bits/base/src/main/java/org/enso/base/Text_Utils.java
  test/Benchmarks/src/Text/Contains.enso
  test/Table_Tests/src/Common_Table_Spec.enso
  test/Table_Tests/src/Matching_Spec.enso
  test/Tests/src/Data/Text_Spec.enso
Labels: CI: Ready to merge

#3287 Text.take and Text.drop
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Text_Sub_Range.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column_Mapping.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Error.enso
  std-bits/base/src/main/java/org/enso/base/Text_Utils.java
  test/Tests/src/Data/Range_Spec.enso
  test/Tests/src/Data/Text_Spec.enso
  test/Tests/src/Semantic/Meta_Spec.enso
Labels: CI: Ready to merge

#3292 Data analysts should be able to use `Text.starts_with` and `Text.ends_with`
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  std-bits/base/src/main/java/org/enso/base/Text_Utils.java
  test/Tests/src/Data/Text_Spec.enso
Labels: CI: Ready to merge

#3278 Creating a new node with the (+) button
  .github/CODEOWNERS
  CHANGELOG.md
  Cargo.lock
  app/gui/src/presenter/graph.rs
  app/gui/src/presenter/project.rs
  app/gui/src/presenter/searcher.rs
  app/gui/view/debug_scene/interface/src/lib.rs
  app/gui/view/graph-editor/src/component.rs
  app/gui/view/graph-editor/src/component/add_node_button.rs
  app/gui/view/graph-editor/src/free_place_finder.rs
  app/gui/view/graph-editor/src/lib.rs
  app/gui/view/src/project.rs
  app/gui/view/src/searcher.rs
  app/gui/view/src/searcher/new.rs
  app/gui/view/src/status_bar.rs
  app/gui/view/src/window_control_buttons.rs
  app/gui/view/src/window_control_buttons/close.rs
  app/gui/view/src/window_control_buttons/fullscreen.rs
  build/run.js
  integration-test/Cargo.toml
  integration-test/tests/graph_editor.rs
  lib/rust/ensogl/app/theme/hardcoded/src/lib.rs
  lib/rust/ensogl/component/Cargo.toml
  lib/rust/ensogl/component/button/Cargo.toml
  lib/rust/ensogl/component/button/src/lib.rs
  lib/rust/ensogl/component/src/lib.rs
  lib/rust/ensogl/core/src/display/scene.rs
Labels: CI: Ready to merge

#3300 Fix debug screen regression
  app/ide-desktop/lib/content/src/index.ts
Labels: CI: Ready to merge

#3299 Update Column_Selector and Column_Mapping to use Matcher over Matching_Strategy
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Matching.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column_Mapping.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column_Selector.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Matching.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Main.enso
  test/Table_Tests/src/Common_Table_Spec.enso
  test/Table_Tests/src/Main.enso
  test/Table_Tests/src/Matching_Spec.enso
  test/Tests/src/Data/Text/Matching_Spec.enso
  test/Tests/src/Main.enso
Labels: CI: Ready to merge

#3302 Data analysts should be able to use `Text.to_case` to change the case of Text values
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Case.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Scatter_Plot.enso
  test/Tests/src/Data/Text_Spec.enso
Labels: Change: Breaking, Category: Stdlib, CI: Ready to merge
