Repository enso-org/enso, pull requests merged in 2022-10, with the labels that each got.

#3752 Unique job for visualizations
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/JobExecutionEngine.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/Job.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/UpsertVisualisationJob.scala
Labels: CI: Ready to merge

#3720 Breadcrumbs integration
  app/gui/controller/double-representation/src/module.rs
  app/gui/controller/double-representation/src/project.rs
  app/gui/src/controller/project.rs
  app/gui/src/controller/searcher.rs
  app/gui/src/controller/searcher/breadcrumbs.rs
  app/gui/src/controller/searcher/component.rs
  app/gui/src/controller/searcher/component/builder.rs
  app/gui/src/ide.rs
  app/gui/src/model/project.rs
  app/gui/src/model/suggestion_database/entry.rs
  app/gui/src/presenter/searcher.rs
  app/gui/tests/language_server.rs
  app/gui/view/component-browser/breadcrumbs/src/entry.rs
  app/gui/view/component-browser/breadcrumbs/src/lib.rs
  app/gui/view/component-browser/searcher-list-panel/src/lib.rs
  build-config.yaml
  lib/rust/ensogl/component/grid-view/src/column_widths.rs
  lib/rust/prelude/src/string.rs
Labels: CI: Ready to merge

#3753 Adding a shorthand for the Table API until widgets available
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  test/Table_Tests/src/Common_Table_Spec.enso
  test/Table_Tests/src/Table_Spec.enso
Labels: CI: Ready to merge

#3754 Fix Warnings visualization
  distribution/lib/Standard/Base/0.0.0-dev/src/Runtime.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Warning.enso
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/type/Types.java
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  test/Tests/src/Runtime/Stack_Traces_Spec.enso
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Runtime.enso
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Warning.enso
Labels: CI: Ready to merge

#3716 Parser: Full constructor syntax for type definitions; Field syntax; Complex operator sections; Template functions; Text improvements; Operator methods; eliminate Unsupported; better ArgumentDefinitions
  .github/CODEOWNERS
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Main.enso
  engine/runtime/src/main/java/org/enso/compiler/EnsoCompiler.java
  engine/runtime/src/main/java/org/enso/compiler/TreeToIr.java
  engine/runtime/src/test/java/org/enso/compiler/EnsoCompilerTest.java
  lib/rust/metamodel/lexpr/src/lib.rs
  lib/rust/metamodel/src/java/from_meta.rs
  lib/rust/metamodel/src/meta/graphviz.rs
  lib/rust/metamodel/src/meta/mod.rs
  lib/rust/metamodel/src/meta/serialization.rs
  lib/rust/metamodel/src/rust/mod.rs
  lib/rust/metamodel/src/rust/to_meta.rs
  lib/rust/parser/generate-java/java/org/enso/syntax2/Message.java
  lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java
  lib/rust/parser/generate-java/java/org/enso/syntax2/UnsupportedSyntaxException.java
  lib/rust/parser/generate-java/src/main.rs
  lib/rust/parser/generate-java/src/serialization.rs
  lib/rust/parser/src/lexer.rs
  lib/rust/parser/src/lib.rs
  lib/rust/parser/src/macros/built_in.rs
  lib/rust/parser/src/macros/resolver.rs
  lib/rust/parser/src/main.rs
  lib/rust/parser/src/serialization.rs
  lib/rust/parser/src/syntax/item.rs
  lib/rust/parser/src/syntax/operator.rs
  lib/rust/parser/src/syntax/token.rs
  lib/rust/parser/src/syntax/tree.rs
  lib/rust/parser/src/syntax/tree/block.rs
  lib/rust/parser/tests/parse.rs
  lib/rust/reflect/src/lib.rs
  project/FrgaalJavaCompiler.scala
Labels: CI: Ready to merge

#3750 Update Table API with new `filter` design
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Error/Problem_Behavior.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Searcher/0.0.0-dev/src/Data_Science.enso
  distribution/lib/Standard/Searcher/0.0.0-dev/src/Data_Science/Transform.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Filter_Condition.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Value_Type.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Problems.enso
  test/Table_Tests/src/Common_Table_Spec.enso
  test/Table_Tests/src/Database/Codegen_Spec.enso
  test/Table_Tests/src/Database/Common_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Table_Spec.enso
  test/Visualization_Tests/src/SQL_Spec.enso
Labels: CI: Ready to merge

#3757 Fix type pattern matching benchmark
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/TypePatternBenchmarks.java
Labels: CI: Ready to merge

#3763 Associate the argument root nodes with their function name
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
Labels: CI: Ready to merge

#3761 Try fixing JUnit reports for CI
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Duration.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Main.enso
Labels: CI: Ready to merge, CI: No changelog needed

#3762 Print average when benchmarking
  distribution/lib/Standard/Test/0.0.0-dev/src/Bench.enso
  test/Benchmarks/src/Vector/Vector.enso
Labels: CI: Ready to merge

#3769 Always attempt to build rust parser libs in CI
  build.sbt
Labels: CI: Ready to merge

#3771 Supporting more complicated case_of and other patterns
  engine/runtime/src/main/java/org/enso/compiler/TreeToIr.java
  engine/runtime/src/test/java/org/enso/compiler/EnsoCompilerTest.java
Labels: CI: Ready to merge

#3765 Always report errors for all modules
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
Labels: CI: Ready to merge

#3767 Fix repl
  engine/runner/src/main/scala/org/enso/runner/Main.scala
Labels: CI: Ready to merge

#3756 Enable Junit reports for Scalatest
  .github/workflows/scala-new.yml
  build.sbt
Labels: CI: Ready to merge

#3770 Add filtering by Filter_Condition to `Vector`, `Range` and `List`
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Filter_Condition.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/List.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Filter_Condition_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Main.enso
  test/Table_Tests/src/Common_Table_Spec.enso
  test/Table_Tests/src/Table_Spec.enso
  test/Tests/src/Data/List_Spec.enso
  test/Tests/src/Data/Range_Spec.enso
  test/Tests/src/Data/Vector_Spec.enso
Labels: CI: Ready to merge

#3773 Old translateArgumentDefinitions is not necessary for Tree.ArgumentDefinition
  engine/runtime/src/main/java/org/enso/compiler/TreeToIr.java
Labels: CI: Ready to merge, CI: No changelog needed

#3768 Suppress some obvious warnings
  std-bits/image/src/main/java/org/enso/image/Codecs.java
  std-bits/image/src/main/java/org/enso/image/data/Image.java
  std-bits/image/src/main/java/org/enso/image/data/Matrix.java
  std-bits/image/src/main/java/org/enso/image/opencv/OpenCV.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/StorageListView.java
Labels: CI: Ready to merge

#3777 Supporting more of the Enso language syntax in the newly built IR
  engine/runtime/src/main/java/org/enso/compiler/TreeToIr.java
  engine/runtime/src/test/java/org/enso/compiler/EnsoCompilerTest.java
Labels: CI: Ready to merge

#3780 Implement annotations
  lib/rust/parser/src/lexer.rs
  lib/rust/parser/src/macros/built_in.rs
  lib/rust/parser/src/syntax/operator.rs
  lib/rust/parser/src/syntax/token.rs
  lib/rust/parser/src/syntax/tree.rs
  lib/rust/parser/src/syntax/tree/block.rs
  lib/rust/parser/tests/parse.rs
Labels: CI: Ready to merge

#3779 Fix text sync with Engine
  app/gui/src/model/module/synchronized.rs
Labels: CI: Ready to merge, CI: No changelog needed

#3781 Fix for perf degradation in method calls on polyglot arrays
  CHANGELOG.md
  distribution/lib/Standard/Test/0.0.0-dev/src/Bench.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/IndirectInvokeMethodNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/resolver/HostMethodCallNode.java
Labels: CI: Ready to merge

#3764 Static, but instance, but static
  CHANGELOG.md
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/MethodDefinitions.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/OverloadsResolution.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/MethodsTest.scala
Labels: CI: Ready to merge

#3784 Convert annotations provided by the new parser to IR
  engine/runtime/src/main/java/org/enso/compiler/TreeToIr.java
  engine/runtime/src/test/java/org/enso/compiler/EnsoCompilerTest.java
Labels: CI: Ready to merge

#3775 Add `Is_Empty`, `Not_Empty`, `Like` and `Not_Like` to `Filter_Condition`
  CHANGELOG.md
  build.sbt
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Filter_Condition.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Filter_Condition_Helpers.enso
  project/StdBits.scala
  std-bits/base/src/main/java/org/enso/base/Regex_Utils.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/text/LikeOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/Storage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/StringStorage.java
  test/Table_Tests/src/Common_Table_Spec.enso
  test/Table_Tests/src/Database/Codegen_Spec.enso
  test/Table_Tests/src/Table_Spec.enso
  test/Tests/src/Data/List_Spec.enso
  test/Tests/src/Data/Range_Spec.enso
  test/Tests/src/Data/Vector_Spec.enso
Labels: CI: Ready to merge

#3788 Sign MacOS package on CI only
  app/ide-desktop/lib/client/electron-builder-config.ts
Labels: CI: No changelog needed

#3789 Supporting self attribute, type methods and operations
  engine/runtime/src/main/java/org/enso/compiler/TreeToIr.java
  engine/runtime/src/test/java/org/enso/compiler/EnsoCompilerTest.java
Labels: CI: Ready to merge, CI: No changelog needed

#3785 Qualified defs
  Cargo.lock
  Cargo.toml
  engine/runtime/src/main/java/org/enso/compiler/TreeToIr.java
  engine/runtime/src/test/java/org/enso/compiler/EnsoCompilerTest.java
  lib/rust/parser/debug/Cargo.toml
  lib/rust/parser/debug/src/lib.rs
  lib/rust/parser/debug/src/main.rs
  lib/rust/parser/debug/tests/metadata/mod.rs
  lib/rust/parser/debug/tests/parse.rs
  lib/rust/parser/src/lexer.rs
  lib/rust/parser/src/lib.rs
  lib/rust/parser/src/macros/built_in.rs
  lib/rust/parser/src/main.rs
  lib/rust/parser/src/syntax/token.rs
  lib/rust/parser/src/syntax/tree.rs
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#3792 Macro contexts
  engine/runtime/src/main/java/org/enso/compiler/TreeToIr.java
  lib/rust/parser/debug/tests/parse.rs
  lib/rust/parser/src/lexer.rs
  lib/rust/parser/src/lib.rs
  lib/rust/parser/src/macros/built_in.rs
  lib/rust/parser/src/macros/resolver.rs
  lib/rust/parser/src/syntax/operator.rs
  lib/rust/parser/src/syntax/token.rs
  lib/rust/parser/src/syntax/tree.rs
Labels: CI: Ready to merge, CI: No changelog needed

#3787 Don't crash interpreter on missing method
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/resolver/HostMethodCallNode.java
  test/Tests/src/Semantic/Java_Interop_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#3796 More coding patterns converted to IR
  engine/runtime/src/main/java/org/enso/compiler/TreeToIr.java
  engine/runtime/src/test/java/org/enso/compiler/EnsoCompilerTest.java
Labels: CI: Ready to merge, CI: No changelog needed

#3759 Duration type is a builtin type
  CHANGELOG.md
  build.sbt
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Duration.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Of_Day.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/Http.enso
  distribution/lib/Standard/Examples/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Main.enso
  docs/infrastructure/native-image.md
  engine/runner-native/src/main/resources/META-INF/native-image/org/enso/runner/reflect-config.json
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/node/ReadOnlyArray.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/runtime/PolyglotProxy.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/FunctionCallInstrumentationNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/resolver/HostMethodCallNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/UnresolvedConversion.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/UnresolvedSymbol.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/ArraySlice.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoDateTime.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoDuration.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoFile.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoTimeOfDay.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/ManagedResource.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Ref.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Type.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/text/Text.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/Warning.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/WithWarnings.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/number/EnsoBigInteger.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/TopLevelScope.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/type/Types.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/builtins/TypeWithKind.java
  project/StdBits.scala
  std-bits/base/src/main/java/org/enso/base/Time_Utils.java
  test/Tests/src/Data/Time/Date_Spec.enso
  test/Tests/src/Data/Time/Date_Time_Spec.enso
  test/Tests/src/Data/Time/Duration_Spec.enso
  test/Tests/src/Data/Time/Time_Of_Day_Spec.enso
  test/Tests/src/Network/Http_Spec.enso
  test/Tests/src/Semantic/Java_Interop_Spec.enso
Labels: Category: Stdlib, CI: Ready to merge, CI: Clean build required

#3795 Lex doc comments and attach text to AST
  engine/runtime/src/test/java/org/enso/compiler/EnsoCompilerTest.java
  lib/rust/parser/debug/src/bin/lexer.rs
  lib/rust/parser/debug/tests/parse.rs
  lib/rust/parser/src/lexer.rs
  lib/rust/parser/src/macros/built_in.rs
  lib/rust/parser/src/main.rs
  lib/rust/parser/src/syntax/operator.rs
  lib/rust/parser/src/syntax/token.rs
  lib/rust/parser/src/syntax/tree.rs
  lib/rust/parser/src/syntax/tree/block.rs
Labels: CI: Ready to merge, CI: No changelog needed

#3800 Ensure all new parser files are checked for changes
  build.sbt
Labels: CI: Ready to merge, CI: No changelog needed

#3778 Show section name in breadcrumbs
  app/gui/src/presenter/searcher.rs
  app/gui/view/component-browser/component-list-panel/breadcrumbs/src/entry.rs
  app/gui/view/component-browser/component-list-panel/breadcrumbs/src/lib.rs
  app/gui/view/component-browser/component-list-panel/grid/src/content.rs
  app/gui/view/component-browser/component-list-panel/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#3802 Parse case-by-type, add an old-lambda syntax rule
  engine/runtime/src/test/java/org/enso/compiler/EnsoCompilerTest.java
  lib/rust/parser/debug/src/bin/lexer.rs
  lib/rust/parser/debug/tests/parse.rs
  lib/rust/parser/src/lexer.rs
  lib/rust/parser/src/macros/built_in.rs
  lib/rust/parser/src/macros/resolver.rs
  lib/rust/parser/src/syntax/operator.rs
  lib/rust/parser/src/syntax/token.rs
  lib/rust/parser/src/syntax/tree.rs
  lib/rust/parser/src/syntax/tree/block.rs
Labels: CI: Ready to merge, CI: No changelog needed

#3803 Improve Unsupported_Argument_Types message.
  distribution/lib/Standard/Base/0.0.0-dev/src/Error/Common.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/resolver/HostMethodCallNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/UnsupportedArgumentTypes.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/displaytext/UnsupportedArgumentTypesToDisplayTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/mutable/ArrayLengthNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Error.java
  test/Tests/src/Semantic/Error_Spec.enso
Labels: Change: Non-Breaking, CI: Ready to merge, CI: No changelog needed

#3805 Update `drop_missing_rows` to `filter_blank_rows` API.
  CHANGELOG.md
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Searcher/0.0.0-dev/src/Data_Science/Preparation.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  std-bits/table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/DoubleStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/Storage.java
  test/Table_Tests/src/Common_Table_Spec.enso
  test/Table_Tests/src/Database/Codegen_Spec.enso
  test/Table_Tests/src/Database/Common_Spec.enso
  test/Table_Tests/src/Database/SQLite_Spec.enso
  test/Table_Tests/src/Table_Spec.enso
Labels: CI: Ready to merge

#3808 fix span bug in doc comments
  engine/runtime/src/test/java/org/enso/compiler/EnsoCompilerTest.java
  lib/rust/parser/debug/tests/parse.rs
  lib/rust/parser/src/lexer.rs
  lib/rust/parser/src/lib.rs
  lib/rust/parser/src/macros/built_in.rs
  lib/rust/parser/src/source/code.rs
  lib/rust/parser/src/syntax/tree.rs
Labels: CI: Ready to merge, CI: No changelog needed

#3806 Process documentation in type definitions
  engine/runtime/src/main/java/org/enso/compiler/TreeToIr.java
  engine/runtime/src/test/java/org/enso/compiler/EnsoCompilerTest.java
  lib/rust/parser/generate-java/src/serialization.rs
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#3807 Fix potential dobule-borrow panic.
  lib/rust/frp/src/network.rs
Labels: CI: Ready to merge, CI: Keep up to date, CI: No changelog needed

#3783 A caption when hovering the marketplace button on the left bar of Component Browser
  Cargo.lock
  app/gui/view/component-browser/component-list-panel/Cargo.toml
  app/gui/view/component-browser/component-list-panel/src/navigator.rs
  lib/rust/ensogl/component/label/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#3812 Add support for `Blank_Columns` to Table and Database
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Any.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Span.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Day_Of_Week_From.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Error/Common.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Aggregate_Helper.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Searcher/0.0.0-dev/src/Data_Science/Preparation.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column_Selector.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Aggregate_Column_Helper.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  std-bits/base/src/main/java/org/enso/base/polyglot/Polyglot_Utils.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/Storage.java
  test/Table_Tests/src/Common_Table_Spec.enso
  test/Table_Tests/src/Database/Common_Spec.enso
  test/Table_Tests/src/Database/Helpers/Fake_Test_Connection.enso
  test/Table_Tests/src/Table_Spec.enso
Labels: CI: Ready to merge

#3811 Move logic calculating the index in Vector.at to a builtin method to make the performance of Vector to be on par with Array
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Error/Common.enso
  docs/runtime-guide.md
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/IndexOutOfBoundsError.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/immutable/AtVectorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/mutable/ArrayAtNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Error.java
  test/Tests/src/Data/Array_Spec.enso
Labels: CI: Ready to merge

#3814 Test to make sure number of files accepted by the new parser only grows
  engine/runtime/src/test/java/org/enso/compiler/ParseStdLibTest.java
Labels: CI: Ready to merge, CI: No changelog needed

#3825 Order of types in method signatures and more robust comment handling
  engine/runtime/src/main/java/org/enso/compiler/TreeToIr.java
  engine/runtime/src/test/java/org/enso/compiler/EnsoCompilerTest.java
  engine/runtime/src/test/java/org/enso/compiler/ParseStdLibTest.java
Labels: CI: Ready to merge, CI: No changelog needed

#3820 Update CODEOWNERS to avoid project files being owned by just one person
  .github/CODEOWNERS
Labels: CI: Ready to merge, CI: No changelog needed

#3826 Few more properly parsed files
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Ordering/Natural_Order.enso
  engine/runtime/src/main/java/org/enso/compiler/TreeToIr.java
  engine/runtime/src/test/java/org/enso/compiler/EnsoCompilerTest.java
  engine/runtime/src/test/java/org/enso/compiler/ParseStdLibTest.java
Labels: CI: Ready to merge, CI: No changelog needed

#3822 Add support for using Columns within `Is_In`
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Filter_Condition.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Helpers.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/SpecializedIsInOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/bool/BooleanIsInOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/datetime/DateTimeIsInOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/DoubleIsInOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/LongIsInOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/text/StringIsInOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/DateStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/DateTimeStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/DoubleStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/LongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/SpecializedStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/Storage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/StringStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/TimeOfDayStorage.java
  test/Table_Tests/src/Common_Table_Spec.enso
  test/Table_Tests/src/Database/Codegen_Spec.enso
  test/Table_Tests/src/Table_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#3815 Remove obsolete Rust parser experiment, superseded by the much more mature new Rust parser integration
  build.sbt
  lib/scala/parser/src/main/scala/org/enso/parser/Parser.scala
  lib/scala/parser/src/test/scala/org/enso/parser/ParserTest.scala
  project/GenerateAST.scala
Labels: CI: Ready to merge, CI: No changelog needed

#3817 Accept Array-like objects seamlessly in builtins
  CHANGELOG.md
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/immutable/FromArrayBuiltinVectorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/generic/ExecuteNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/generic/InstantiateNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/generic/InvokeNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/NewAtomInstanceNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/mutable/CoerceArrayNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/system/System.java
  test/Tests/src/Data/Polyglot_Spec.enso
  test/Tests/src/Main.enso
  test/Tests/src/Semantic/Meta_Location_Spec.enso
  test/Tests/src/Semantic/Meta_Spec.enso
  test/Tests/src/System/System_Spec.enso
Labels: CI: Ready to merge

#3799 Editing via esc does not correctly update node view
  app/gui/src/presenter/graph.rs
  app/gui/src/presenter/graph/state.rs
  app/gui/view/debug_scene/interface/src/lib.rs
  app/gui/view/graph-editor/src/component/node.rs
  app/gui/view/graph-editor/src/component/node/expression.rs
  app/gui/view/graph-editor/src/component/node/input/area.rs
  app/gui/view/graph-editor/src/lib.rs
  lib/rust/text/src/text.rs
Labels: CI: Ready to merge, CI: No changelog needed

#3821 Initialize Builtins at Native Image build time
  CHANGELOG.md
  engine/runner-native/src/main/resources/META-INF/native-image/org/enso/runner/reflect-config.json
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
Labels: CI: Ready to merge

#3829 Add isStatic method field
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/search/SearchProtocol.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/Suggestions.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/SuggestionsHandlerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/SuggestionsHandlerEventsTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/Suggestion.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeSuggestionUpdatesTest.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/context/SuggestionBuilderTest.scala
  lib/scala/searcher/src/bench/scala/org/enso/searcher/sql/SuggestionRandom.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlSuggestionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/Tables.scala
  lib/scala/searcher/src/test/scala/org/enso/searcher/sql/SuggestionsRepoTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#3827 Create a Table `Row` Type and expose as a Vector on In-Memory Table with `.rows` property
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array_Proxy.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Row.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Rows_View.enso
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/VectorBenchmarks.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/InvalidArrayIndexError.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Array.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/ArrayProxy.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/type/Types.java
  test/Table_Tests/src/Common_Table_Spec.enso
  test/Tests/src/Data/Array_Proxy_Spec.enso
  test/Tests/src/Main.enso
Labels: CI: Ready to merge

#3804 Define Enso epoch start as 15th October 1582.
  .gitignore
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Error/Common.enso
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoDateTime.java
  test/Tests/src/Data/Time/Date_Spec.enso
  test/Tests/src/Data/Time/Date_Time_Spec.enso
Labels: Change: Non-Breaking, CI: Ready to merge

#3833 Document no changelog label
  app/gui/docs/CONTRIBUTING.md
Labels: CI: No changelog needed

#3816 Recognize unqualified import syntax in double representation library.
  app/gui/controller/double-representation/src/import.rs
  app/gui/controller/double-representation/src/lib.rs
  app/gui/controller/double-representation/src/module.rs
  app/gui/language/ast/impl/src/lib.rs
  app/gui/language/ast/impl/src/macros.rs
  app/gui/language/parser/tests/parsing.rs
  app/gui/src/controller/module.rs
  app/gui/src/controller/searcher.rs
  app/gui/src/model/module.rs
  app/gui/src/model/module/plain.rs
  app/gui/src/model/module/synchronized.rs
Labels: CI: Ready to merge, CI: Keep up to date, CI: No changelog needed

#3818 Add `Period` type
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Duration.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Period.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Of_Day.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Meta.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/Http.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/TypeOfNode.java
  engine/runtime/src/test/java/org/enso/compiler/ParseStdLibTest.java
  std-bits/base/src/main/java/org/enso/base/Time_Utils.java
  test/Benchmarks/src/Equality.enso
  test/Benchmarks/src/Time/Work_Days.enso
  test/Tests/src/Data/Time/Date_Spec.enso
  test/Tests/src/Data/Time/Date_Time_Spec.enso
  test/Tests/src/Data/Time/Duration_Spec.enso
  test/Tests/src/Data/Time/Period_Spec.enso
  test/Tests/src/Data/Time/Spec.enso
  test/Tests/src/Data/Time/Time_Of_Day_Spec.enso
  test/Tests/src/Network/Http_Spec.enso
Labels: CI: Ready to merge

#3837 Add a Visualization to the Table.Row type
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Row.enso
  test/Table_Tests/src/Common_Table_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed
