Repository enso-org/enso, pull requests merged in 2023-01, with the labels that each got.

#4015 Basic IGV Scala Support
  tools/enso4igv/pom.xml
  tools/enso4igv/src/main/java/org/enso/tools/enso4igv/EnsoSbtClassPathProvider.java
  tools/enso4igv/src/main/java/org/enso/tools/enso4igv/scala/ScalaDataObject.java
  tools/enso4igv/src/main/java/org/enso/tools/enso4igv/scala/ToggleScalaBreakpointActionProvider.java
  tools/enso4igv/src/main/java/org/enso/tools/enso4igv/scala/package-info.java
  tools/enso4igv/src/main/resources/org/enso/tools/enso4igv/layer.xml
  tools/enso4igv/src/main/resources/org/enso/tools/enso4igv/scala/Scala.tmLanguage
  tools/enso4igv/src/main/resources/org/enso/tools/enso4igv/scala/ScalaTemplate.scala
  tools/enso4igv/src/main/resources/org/enso/tools/enso4igv/scala/scala-spiral.svg
Labels: CI: Ready to merge, CI: No changelog needed

#4012 Improve performance of Text.compare_to
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text.enso
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/text/Text.java
  std-bits/base/src/main/java/org/enso/base/Text_Utils.java
Labels: CI: Ready to merge, CI: No changelog needed

#4016 Add Polyglot Support in Runtime Tests
  build.sbt
  engine/polyglot-api/src/main/java/org/enso/polyglot/RuntimeOptions.java
  engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/BuiltinTypesTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeAsyncCommandsTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeErrorsTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeInstrumentTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime-with-polyglot/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/EnsoLanguage.java
  engine/runtime/src/main/java/org/enso/interpreter/instrument/IdExecutionService.java
  engine/runtime/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/Timer.scala
Labels: CI: Ready to merge, CI: No changelog needed

#4018 AST support for new annotation syntax
  engine/runtime/src/main/java/org/enso/compiler/TreeToIr.java
  lib/rust/parser/debug/tests/parse.rs
  lib/rust/parser/src/syntax/tree.rs
  lib/rust/parser/src/syntax/tree/block.rs
Labels: CI: No changelog needed, CI: Clean build required

#4020 Sync file system and language server after restore
  CHANGELOG.md
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/vcs/RestoreVcsHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/Buffer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/BufferRegistry.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/CollaborativeBuffer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/TextProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/vcsmanager/EmptyUserConfigReader.scala
  engine/language-server/src/main/scala/org/enso/languageserver/vcsmanager/Git.scala
  engine/language-server/src/main/scala/org/enso/languageserver/vcsmanager/VcsApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/vcsmanager/VcsManager.scala
  engine/language-server/src/main/scala/org/enso/languageserver/vcsmanager/VcsManagerApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/vcsmanager/VcsProtocol.scala
  engine/language-server/src/test/scala/org/enso/languageserver/vcsmanager/GitSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/VcsManagerTest.scala
Labels: CI: Ready to merge

#4014 Basic VSCode support for Enso language and development
  .github/workflows/enso4igv.yml
  CHANGELOG.md
  tools/enso4igv/.gitignore
  tools/enso4igv/.vscodeignore
  tools/enso4igv/README.md
  tools/enso4igv/package.json
  tools/enso4igv/pom.xml
  tools/enso4igv/src/main/vscode/extension.ts
  tools/enso4igv/tsconfig.json
  tools/enso4igv/webpack.config.js
Labels: CI: Ready to merge

#4030 Report failed name resolutions in type signatures
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Engine.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Pattern.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Duration.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Error.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Runtime.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/SQLite_Options.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Helpers.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Data/Image.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Storage.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Reader.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Writer.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Suite_Config.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Scatter_Plot.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/GatherDiagnostics.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/TypeNames.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/TypeSignatures.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/TypeNamesTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/TypeSignaturesTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/semantic/TypeSignaturesTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/IOContextTest.scala
  test/Tests/src/Semantic/Equals_Spec.enso
  test/Tests/src/Semantic/Runtime_Spec.enso
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Runtime.enso
Labels: CI: Ready to merge

#4023 Removing Unsafe.set_atom_field
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/List.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Meta.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Runtime/Unsafe.enso
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/ListBenchmarks.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/VectorBenchmarks.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/AtomWithAHoleNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/unsafe/SetAtomFieldNode.java
  engine/runtime/src/test/java/org/enso/interpreter/test/DebuggingEnsoTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/ListTest.java
  project/FrgaalJavaCompiler.scala
  test/Tests/src/Data/List_Spec.enso
  test/Tests/src/Semantic/Meta_Spec.enso
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Runtime/Unsafe.enso
Labels: CI: Ready to merge, CI: Clean build required

#4022 Make ArrayOverBuffer behave like an Array/Array.sort no longer mutates the Array
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/mutable/SortNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/ArrayOverBuffer.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/DisplayArrayUtils.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Vector.java
  test/Tests/src/Data/Array_Spec.enso
  test/Tests/src/Semantic/Js_Interop_Spec.enso
  test/Tests/src/Semantic/Python_Interop_Spec.enso
  test/Tests/src/Semantic/R_Interop_Spec.enso
Labels: CI: Ready to merge

#4032 Don't include type in tagValues
  engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/context/SuggestionBuilderTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#4029 Documentation for functions and locals
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/search/SearchProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/Suggestions.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/SuggestionsHandlerEventsTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/Suggestion.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeStdlibTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeSuggestionUpdatesTest.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionDiff.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/context/SuggestionBuilderTest.scala
  lib/scala/searcher/src/bench/scala/org/enso/searcher/sql/SuggestionRandom.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlSuggestionsRepo.scala
  lib/scala/searcher/src/test/scala/org/enso/searcher/sql/SuggestionsRepoTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#4033 Prune unused ids from metadata on loading file
  app/gui/language/parser/src/api.rs
  app/gui/language/parser/src/wsclient.rs
  app/gui/language/parser/tests/parsing.rs
  app/gui/src/model/module.rs
Labels: CI: Ready to merge, CI: No changelog needed

#4027 Implement Distinct for the Database backends
  CHANGELOG.md
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Common/Database_Distinct_Helper.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Common/Database_Join_Helper.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/IR/Context.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/IR/Query.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Java_Problems.enso
  std-bits/table/src/main/java/org/enso/table/aggregations/Aggregator.java
  std-bits/table/src/main/java/org/enso/table/data/index/MultiValueIndex.java
  std-bits/table/src/main/java/org/enso/table/data/table/Table.java
  std-bits/table/src/main/java/org/enso/table/data/table/join/IndexJoin.java
  std-bits/table/src/main/java/org/enso/table/data/table/join/JoinResult.java
  std-bits/table/src/main/java/org/enso/table/data/table/join/scan/Matcher.java
  std-bits/table/src/main/java/org/enso/table/data/table/join/scan/MatcherFactory.java
  std-bits/table/src/main/java/org/enso/table/operations/Distinct.java
  std-bits/table/src/main/java/org/enso/table/problems/AggregatedProblems.java
  test/Table_Tests/src/Common_Table_Operations/Distinct_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Integration_Tests.enso
  test/Table_Tests/src/Common_Table_Operations/Main.enso
  test/Table_Tests/src/Database/Codegen_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Database/SQLite_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
Labels: CI: Ready to merge

#4034 Catch Panic and Error from Atom.to_text and yield detailed error message
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/List.enso
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/ReplTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/Atom.java
  engine/runtime/src/test/java/org/enso/interpreter/test/ListTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/PolyglotErrorTest.java
Labels: CI: Ready to merge, CI: No changelog needed

#4040 Fix for "When editing text if you Ctrl-Enter quickly it deletes some of the input"
  app/gui/view/src/project.rs
Labels: CI: Ready to merge, CI: No changelog needed

#4042 Workaround vcs/restore issues on Windows
  engine/language-server/src/main/scala/org/enso/languageserver/vcsmanager/Git.scala
Labels: CI: Ready to merge, CI: No changelog needed

#4026 Align Vector API with design, add some extra functions from AoC
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/package.yaml
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Index_Sub_Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/List.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Map.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Pair.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Error/Common.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Function.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Panic.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Random.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File_Format.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Pgpass.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Google_Api/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Searcher/0.0.0-dev/src/Data_Science/Aggregate.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Aggregate_Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Delimited/Delimited_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Delimited/Delimited_Reader.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Helpers.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Histogram.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Scatter_Plot.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
  engine/runtime/src/test/java/org/enso/compiler/ParseStdLibTest.java
  test/Benchmarks/src/Vector/Operations.enso
  test/Benchmarks/src/Vector/Sort.enso
  test/Table_Tests/src/Common_Table_Operations/Select_Columns_Spec.enso
  test/Table_Tests/src/Database/Common_Spec.enso
  test/Table_Tests/src/Formatting/Parse_Values_Spec.enso
  test/Table_Tests/src/In_Memory/Column_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
  test/Tests/src/Data/List_Spec.enso
  test/Tests/src/Data/Map_Spec.enso
  test/Tests/src/Data/Pair_Spec.enso
  test/Tests/src/Data/Range_Spec.enso
  test/Tests/src/Data/Text_Spec.enso
  test/Tests/src/Data/Time/Date_Spec.enso
  test/Tests/src/Data/Vector_Spec.enso
  test/Tests/src/Random_Spec.enso
  test/Tests/src/Semantic/Warnings_Spec.enso
Labels: CI: Ready to merge

#4024 Implement documentation IR
  Cargo.lock
  app/gui/Cargo.toml
  app/gui/controller/double-representation/src/module.rs
  app/gui/controller/double-representation/src/name.rs
  app/gui/src/controller/graph/executed.rs
  app/gui/src/controller/ide.rs
  app/gui/src/controller/ide/desktop.rs
  app/gui/src/controller/searcher.rs
  app/gui/src/controller/searcher/action.rs
  app/gui/src/controller/searcher/component.rs
  app/gui/src/executor.rs
  app/gui/src/ide/initializer.rs
  app/gui/src/integration_test.rs
  app/gui/src/lib.rs
  app/gui/src/model.rs
  app/gui/src/model/execution_context.rs
  app/gui/src/model/module.rs
  app/gui/src/model/module/plain.rs
  app/gui/src/model/project/synchronized.rs
  app/gui/src/model/registry.rs
  app/gui/src/presenter/searcher/provider.rs
  app/gui/src/sync.rs
  app/gui/suggestion-database/Cargo.toml
  app/gui/suggestion-database/src/documentation_ir.rs
  app/gui/suggestion-database/src/entry.rs
  app/gui/suggestion-database/src/example.rs
  app/gui/suggestion-database/src/lib.rs
  app/gui/suggestion-database/src/mock.rs
  app/gui/tests/language_server.rs
  app/gui/tests/project_manager.rs
  app/gui/view/debug_scene/Cargo.toml
  app/gui/view/debug_scene/documentation/Cargo.toml
  app/gui/view/debug_scene/documentation/src/lib.rs
  app/gui/view/debug_scene/src/lib.rs
  build-config.yaml
  integration-test/Cargo.toml
  integration-test/tests/engine.rs
  lib/rust/executor/Cargo.toml
  lib/rust/executor/src/global.rs
  lib/rust/executor/src/lib.rs
  lib/rust/executor/src/test_utils.rs
  lib/rust/executor/src/web.rs
  lib/rust/executor/src/web/test.rs
  lib/rust/notification/Cargo.toml
  lib/rust/notification/src/lib.rs
  lib/rust/shapely/macros/src/derive_for_each_variant.rs
Labels: CI: Ready to merge, CI: No changelog needed

#4036 Parser: Support annotations in type defs
  engine/runtime/src/main/java/org/enso/compiler/TreeToIr.java
  lib/rust/parser/debug/tests/parse.rs
  lib/rust/parser/src/lib.rs
  lib/rust/parser/src/macros/built_in.rs
  lib/rust/parser/src/syntax/tree.rs
  lib/rust/parser/src/syntax/tree/block.rs
Labels: CI: Ready to merge, CI: No changelog needed

#4043 Simple Warnings visualization.
  app/gui/src/controller/upload.rs
  app/gui/view/graph-editor/src/builtin/visualization/java_script.rs
  app/gui/view/graph-editor/src/builtin/visualization/java_script/warnings.js
  app/gui/view/graph-editor/src/component/visualization/registry.rs
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Warnings.enso
Labels: CI: Ready to merge, CI: No changelog needed

#4045 visualizationResultToBytes converts anything that looks like a string
  build.sbt
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Geo_Map.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Histogram.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Preprocessor.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/SQL/Visualization.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Scatter_Plot.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
  engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/instrument/VerifyJavaScriptIsAvailableTest.java
  engine/runtime-with-polyglot/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/instrument/job/VisualizationResult.java
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime/src/test/java/org/enso/interpreter/test/instrument/ConvertAsStringObjectTest.java
  engine/runtime/src/test/scala/org/enso/interpreter/test/Metadata.scala
Labels: CI: Ready to merge, CI: No changelog needed

#4051 Avoid IllegalStateException in favor of syntax error in the IR
  engine/runtime/src/main/java/org/enso/compiler/TreeToIr.java
  engine/runtime/src/test/java/org/enso/compiler/EnsoCompilerTest.java
Labels: CI: Ready to merge, CI: No changelog needed

#4048 Attach visualizations to sub-expressions
  CHANGELOG.md
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistryProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ExecutionApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/RuntimeFailureMapper.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime-with-polyglot/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DataflowAnalysis.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/UpsertVisualisationJob.scala
Labels: CI: Ready to merge, CI: Clean build required

#4037 Make sure import/export resolution does not bring duplicates
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
Labels: CI: Ready to merge, CI: No changelog needed

#4019 Package MSVC CRT redistributables in with the backend native images.
  Cargo.lock
  build/build/paths.yaml
  build/build/src/engine.rs
  build/build/src/engine/artifact.rs
  build/build/src/engine/bundle.rs
  build/build/src/engine/context.rs
  build/build/src/engine/package.rs
  build/build/src/enso.rs
  build/build/src/lib.rs
  build/build/src/paths.rs
  build/build/src/programs.rs
  build/build/src/project/backend.rs
  build/build/src/project/runtime.rs
  build/build/src/project_manager.rs
  build/build/src/release.rs
  build/ci_utils/Cargo.toml
  build/ci_utils/src/actions/artifacts.rs
  build/ci_utils/src/actions/env.rs
  build/ci_utils/src/actions/workflow/definition.rs
  build/ci_utils/src/archive.rs
  build/ci_utils/src/cache/goodie/graalvm.rs
  build/ci_utils/src/github/release.rs
  build/ci_utils/src/lib.rs
  build/ci_utils/src/packaging.rs
  build/ci_utils/src/paths.rs
  build/ci_utils/src/programs/cargo.rs
  build/ci_utils/src/programs/npx.rs
  build/ci_utils/src/programs/tar.rs
  build/ci_utils/src/programs/vs.rs
  build/ci_utils/src/programs/vs/redist.rs
  build/ci_utils/src/programs/vswhere.rs
Labels: CI: No changelog needed, CI: Clean build required

#4055 Fix serialization of NPE in logger
  lib/scala/logging-service/src/main/scala/org/enso/loggingservice/internal/protocol/SerializedException.scala
  lib/scala/logging-service/src/test/scala/org/enso/loggingservice/internal/DefaultLogMessageRendererSpec.scala
  lib/scala/logging-service/src/test/scala/org/enso/loggingservice/internal/SerializedExceptionSpec.scala
  lib/scala/logging-service/src/test/scala/org/enso/loggingservice/internal/WSLogMessageSpec.scala
Labels: CI: Ready to merge, CI: No changelog needed

#4052 Add `Table.union` to the In-Memory Table.
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Map.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Match_Columns.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Report_Unmatched.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Storage.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Value_Type.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Main.enso
  std-bits/table/src/main/java/org/enso/table/data/column/builder/object/BoolBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/object/Builder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/object/InferredBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/object/NumericBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/object/ObjectBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/object/StorageTypeMismatch.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/object/TypedBuilderImpl.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/DoubleStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/LongStorage.java
  std-bits/table/src/main/java/org/enso/table/util/BitSets.java
  test/Table_Tests/src/Common_Table_Operations/Join_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Main.enso
  test/Table_Tests/src/Common_Table_Operations/Union_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Util.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
Labels: CI: Ready to merge

#4054 Remove all UnhandledEntity panics
  engine/runtime/src/main/java/org/enso/compiler/TreeToIr.java
Labels: CI: Ready to merge, CI: No changelog needed

#3954 move hardcoded mixpanel token to the config
  app/gui/config/src/lib.rs
  app/ide-desktop/lib/content/src/index.ts
Labels: CI: Ready to merge, CI: No changelog needed

#4035 Additional shortcut for Redo
  app/gui/docs/product/shortcuts.md
  app/gui/view/src/project.rs
Labels: CI: Ready to merge, CI: No changelog needed

#4057 Division in Columns within InDB is integer based if both columns are integers
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/DoubleNumericOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/LongNumericOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/DoubleStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/LongStorage.java
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Database/Codegen_Spec.enso
  test/Table_Tests/src/Database/Common_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#4058 Some little bits from Book Club week 1
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File_Format.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table_Conversions.enso
  test/Benchmarks/src/Table/Aggregate.enso
  test/Table_Tests/src/Common_Table_Operations/Aggregate_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Core_Spec.enso
  test/Table_Tests/src/In_Memory/Aggregate_Column_Spec.enso
  test/Tests/src/System/File_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#4025 Fix CB making many frames for Undo-Redo
  app/gui/controller/double-representation/src/definition.rs
  app/gui/language/ast/impl/src/lib.rs
  app/gui/src/controller/searcher.rs
  app/gui/src/model/module.rs
  app/gui/src/model/module/plain.rs
  app/gui/src/model/module/synchronized.rs
  app/gui/src/model/undo_redo.rs
  app/gui/src/presenter/searcher.rs
  app/gui/src/test.rs
  app/gui/src/tests.rs
  lib/rust/prelude/src/result.rs
Labels: CI: Ready to merge, CI: No changelog needed

#4038 Generate HTML for section headers and synopsis
  Cargo.lock
  app/gui/view/debug_scene/documentation/src/lib.rs
  app/gui/view/documentation/Cargo.toml
  app/gui/view/documentation/assets/icon-examples.svg
  app/gui/view/documentation/assets/icon-methods.svg
  app/gui/view/documentation/assets/icon-type.svg
  app/gui/view/documentation/assets/input.css
  app/gui/view/documentation/build.rs
  app/gui/view/documentation/src/html.rs
  app/gui/view/documentation/src/lib.rs
  app/gui/view/documentation/tailwind.config.js
Labels: CI: Ready to merge, CI: No changelog needed

#4059 Fix clearing modules' sources during fileClose
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/TextOperationsTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/ModuleSources.java
  engine/runtime/src/test/java/org/enso/interpreter/runtime/ModuleSourcesTest.java
  engine/runtime/src/test/java/org/enso/interpreter/runtime/ModuleTest.java
Labels: CI: Ready to merge, CI: No changelog needed

#4064 Allow attaching visualizations to non-existent expressions
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistryProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ExecutionApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/RuntimeFailureMapper.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime-with-polyglot/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/UpsertVisualisationJob.scala
Labels: CI: Ready to merge, CI: No changelog needed

#4065 Avoid IndexOutOfBounds when edits go out of range
  lib/scala/text-buffer/src/main/scala/org/enso/text/editing/RopeTextEditor.scala
  lib/scala/text-buffer/src/test/scala/org/enso/text/editing/RopeTextEditorSpec.scala
Labels: CI: Ready to merge, CI: No changelog needed

#4060 Rename option to --wasm-log-level; small refactoring
  build/build/src/project/wasm.rs
  build/cli/src/arg/wasm.rs
  build/cli/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#4021 Reject `@` as binary operator
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime/src/main/java/org/enso/compiler/TreeToIr.java
  engine/runtime/src/test/java/org/enso/compiler/EnsoCompilerTest.java
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/CompileDiagnosticsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/DataflowErrorsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/StrictCompileDiagnosticsTest.scala
  lib/rust/parser/debug/tests/parse.rs
  lib/rust/parser/src/lexer.rs
  lib/rust/parser/src/syntax/operator.rs
  lib/rust/parser/src/syntax/tree.rs
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#4061 handle compiler job cancelation in shader cache
  lib/rust/ensogl/core/src/system/gpu/shader.rs
  lib/rust/ensogl/core/src/system/gpu/shader/compiler.rs
Labels: CI: Ready to merge, CI: No changelog needed

#4069 Fix TextEdit range
  engine/language-server/src/main/scala/org/enso/languageserver/text/CollaborativeBuffer.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/VcsManagerTest.scala
  lib/scala/text-buffer/src/main/scala/org/enso/text/editing/model.scala
Labels: CI: Ready to merge, CI: No changelog needed

#4044 Separate component browser sections for every namespace libraries are imported from
  CHANGELOG.md
  app/gui/src/controller/searcher.rs
  app/gui/src/controller/searcher/component.rs
  app/gui/src/controller/searcher/component/builder.rs
  app/gui/src/presenter/graph/state.rs
  app/gui/src/presenter/searcher.rs
  app/gui/src/presenter/searcher/provider.rs
  app/gui/view/component-browser/component-list-panel/grid/src/content.rs
  app/gui/view/component-browser/component-list-panel/grid/src/layout.rs
  app/gui/view/component-browser/component-list-panel/grid/src/lib.rs
  app/gui/view/component-browser/component-list-panel/src/lib.rs
  app/gui/view/component-browser/component-list-panel/src/navigator.rs
  app/gui/view/debug_scene/component-list-panel-view/src/lib.rs
Labels: CI: Ready to merge

#4063 Add Table.cross_join and Table.zip to In-Memory Table
  CHANGELOG.md
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Problems.enso
  std-bits/base/src/main/java/org/enso/base/arrays/IntArrayBuilder.java
  std-bits/base/src/main/java/org/enso/base/text/CaseFoldedString.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/object/NumericBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/DateStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/DateTimeStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/DoubleStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/LongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/ObjectStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/Storage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/StringStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/TimeOfDayStorage.java
  std-bits/table/src/main/java/org/enso/table/data/mask/OrderMask.java
  std-bits/table/src/main/java/org/enso/table/data/table/Column.java
  std-bits/table/src/main/java/org/enso/table/data/table/Table.java
  std-bits/table/src/main/java/org/enso/table/data/table/join/CrossJoin.java
  std-bits/table/src/main/java/org/enso/table/data/table/join/IndexJoin.java
  std-bits/table/src/main/java/org/enso/table/data/table/join/JoinResult.java
  std-bits/table/src/main/java/org/enso/table/data/table/join/scan/ScanJoin.java
  std-bits/table/src/main/java/org/enso/table/util/BitSets.java
  test/Table_Tests/src/Common_Table_Operations/Aggregate_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Cross_Join_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Join_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Union_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Zip_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Main.enso
  test/Table_Tests/src/Common_Table_Operations/Select_Columns_Spec.enso
  test/Table_Tests/src/Formatting/Data_Formatter_Spec.enso
  test/Table_Tests/src/Formatting/Parse_Values_Spec.enso
  test/Table_Tests/src/IO/Delimited_Write_Spec.enso
  test/Tests/src/Data/Time/Date_Spec.enso
  test/Tests/src/System/Reporting_Stream_Decoder_Spec.enso
  test/Tests/src/System/Reporting_Stream_Encoder_Spec.enso
Labels: CI: Ready to merge

#3862 Unboxed atoms
  CHANGELOG.md
  build.sbt
  engine/runtime/src/bench/scala/org/enso/interpreter/bench/fixtures/semantic/AtomFixtures.scala
  engine/runtime/src/bench/scala/org/enso/interpreter/bench/fixtures/semantic/NamedDefaultedArgumentFixtures.scala
  engine/runtime/src/main/java/org/enso/interpreter/instrument/HostObjectDebugWrapper.java
  engine/runtime/src/main/java/org/enso/interpreter/node/ExpressionNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/ConstructorBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/atom/GetFieldNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/atom/GetFieldWithMatchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/atom/InstantiateNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/CaughtPanicConvertToDataflowErrorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/ThrowPanicNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/displaytext/ArithmeticErrorToDisplayTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/displaytext/ArityErrorToDisplayTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/displaytext/CompileErrorToDisplayTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/displaytext/InexhaustivePatternMatchToDisplayTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/displaytext/InvalidArrayIndexToDisplayTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/displaytext/InvalidConversionTargetToDisplayTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/displaytext/ModuleDoesNotExistToDisplayTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/displaytext/NoSuchConversionToDisplayTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/displaytext/NoSuchMethodToDisplayTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/displaytext/NotInvokableToDisplayTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/displaytext/SyntaxErrorToDisplayTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/displaytext/TypeErrorToDisplayTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/displaytext/UninitializedStateErrorToDisplayTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/displaytext/UnsupportedArgumentTypesToDisplayTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/AtomWithAHoleNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsAnyNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/GetAtomFieldsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/HashCodeAnyNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyPrettyNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/Atom.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/AtomConstructor.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/BoxingAtom.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/StructsLibrary.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/unboxing/Layout.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/unboxing/UnboxingAtom.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/DebugLocalScope.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/type/TypesFromProxy.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/atom/LayoutSpec.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/atom/LayoutSpecProcessor.java
Labels: CI: Ready to merge

#4049 Add Meta.get_annotation
  CHANGELOG.md
  build.sbt
  distribution/lib/Standard/Base/0.0.0-dev/src/Meta.enso
  engine/runtime/src/main/java/org/enso/compiler/EnsoCompiler.java
  engine/runtime/src/main/java/org/enso/compiler/TreeToIr.java
  engine/runtime/src/main/java/org/enso/interpreter/node/BaseNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/AtomWithAHoleNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/GetAnnotationNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/Annotation.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/argument/CallArgumentInfo.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/AtomConstructor.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/Function.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/FunctionSchema.java
  engine/runtime/src/main/scala/org/enso/compiler/Passes.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstToIr.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/FreshNameSupply.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/ir/MetadataStorage.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/PassManager.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/CachePreferenceAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DataflowAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/TailCall.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/ComplexType.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/FunctionBinding.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/DocumentationComments.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/ExpressionAnnotations.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/GenericAnnotations.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/GlobalNames.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/ModuleAnnotations.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/OverloadsResolution.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/SuspendedArguments.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/TypeSignatures.scala
  engine/runtime/src/test/java/org/enso/compiler/AnnotationsCompilerTest.java
  engine/runtime/src/test/java/org/enso/compiler/CompilerTest.java
  engine/runtime/src/test/java/org/enso/compiler/EnsoCompilerTest.java
  engine/runtime/src/test/java/org/enso/compiler/ErrorCompilerTest.java
  engine/runtime/src/test/scala/org/enso/compiler/test/CompilerTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/codegen/AstToIrTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/ModuleAnnotationsTest.scala
  test/Tests/src/Semantic/Meta_Spec.enso
Labels: CI: Ready to merge

#3910 Implement Lazy Text Visualisation.
  CHANGELOG.md
  app/gui/view/debug_scene/text-grid-visualization/src/lib.rs
  app/gui/view/graph-editor/src/builtin/visualization/native.rs
  app/gui/view/graph-editor/src/builtin/visualization/native/raw_text.rs
  app/gui/view/graph-editor/src/builtin/visualization/native/text_grid.rs
  app/gui/view/graph-editor/src/builtin/visualization/native/text_visualization.rs
  app/gui/view/graph-editor/src/builtin/visualization/native/text_visualization/grid_cache.rs
  app/gui/view/graph-editor/src/builtin/visualization/native/text_visualization/grid_view_entry.rs
  app/gui/view/graph-editor/src/builtin/visualization/native/text_visualization/text_provider.rs
  app/gui/view/graph-editor/src/component/visualization/instance.rs
  app/gui/view/graph-editor/src/component/visualization/registry.rs
  build-config.yaml
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Helpers.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Preprocessor.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Text.enso
  lib/rust/ensogl/app/theme/hardcoded/src/lib.rs
  test/Visualization_Tests/src/Lazy_Text_Spec.enso
  test/Visualization_Tests/src/Main.enso
Labels: CI: Ready to merge, CI: No changelog needed

#4079 Eliminate various compiler warnings
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/unboxing/Layout.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/atom/LayoutSpecProcessor.java
Labels: CI: Ready to merge, CI: No changelog needed

#4066 New documentation panel
  Cargo.lock
  app/gui/controller/engine-protocol/src/language_server/types.rs
  app/gui/src/controller/searcher.rs
  app/gui/src/presenter/searcher.rs
  app/gui/suggestion-database/src/documentation_ir.rs
  app/gui/suggestion-database/src/entry.rs
  app/gui/suggestion-database/src/lib.rs
  app/gui/suggestion-database/src/mock.rs
  app/gui/view/component-browser/component-list-panel/src/lib.rs
  app/gui/view/debug_scene/documentation/src/lib.rs
  app/gui/view/documentation/Cargo.toml
  app/gui/view/documentation/src/html.rs
  app/gui/view/documentation/src/lib.rs
  app/gui/view/documentation/tailwind.config.js
  app/gui/view/src/component_browser.rs
  app/gui/view/src/searcher.rs
  lib/rust/logging/macros/src/lib.rs
  lib/rust/prelude/src/collections.rs
  lib/rust/profiler/macros/src/lib.rs
  lib/rust/profiler/macros/src/low_level.rs
  lib/rust/profiler/macros/src/profile_attribute.rs
  lib/rust/profiler/macros/src/wrap_async.rs
  lib/rust/profiler/src/log.rs
  lib/rust/web/src/binding/mock.rs
Labels: CI: Ready to merge, CI: No changelog needed

#4073 Table with no columns is not valid, No_Output_Columns is always an error
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Warning.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Delimited/Delimited_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Delimited/Delimited_Reader.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Reader.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Aggregate_Column_Helper.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Join_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Problem_Builder.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  std-bits/base/src/main/java/org/enso/base/Array_Builder.java
  std-bits/table/src/main/java/org/enso/table/data/table/Table.java
  std-bits/table/src/main/java/org/enso/table/error/EmptyFileException.java
  std-bits/table/src/main/java/org/enso/table/error/EmptySheetException.java
  std-bits/table/src/main/java/org/enso/table/read/DelimitedReader.java
  std-bits/table/src/main/java/org/enso/table/read/ExcelReader.java
  test/Table_Tests/src/Common_Table_Operations/Aggregate_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Distinct_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Missing_Values_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Select_Columns_Spec.enso
  test/Table_Tests/src/Database/Codegen_Spec.enso
  test/Table_Tests/src/IO/Delimited_Read_Spec.enso
  test/Table_Tests/src/IO/Delimited_Write_Spec.enso
  test/Table_Tests/src/IO/Excel_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
  test/Visualization_Tests/src/Geo_Map_Spec.enso
  test/Visualization_Tests/src/Histogram_Spec.enso
  test/Visualization_Tests/src/Scatter_Plot_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#4080 Default visualization preprocessor handles errors
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Preprocessor.enso
  engine/runtime-with-polyglot/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#4078 Update starts_with, ends_with and contains to new API design
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Ordering/Comparator.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Ordering/Natural_Order.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Case_Sensitivity.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex_Matcher.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Text_Ordering.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/SQL_Type.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Common/Database_Distinct_Helper.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  test/Benchmarks/src/Text/Contains.enso
  test/Tests/src/Data/Text_Spec.enso
Labels: CI: Ready to merge

#4082 Initial Widget Dynamic Metadata
  distribution/lib/Standard/Base/0.0.0-dev/src/Metadata.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Connection.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Widgets.enso
  test/Visualization_Tests/src/Main.enso
  test/Visualization_Tests/src/Widgets/Database_Widgets_Spec.enso
  test/Visualization_Tests/src/Widgets/Table_Widgets_Spec.enso
  test/Visualization_Tests/src/Widgets_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#4070 Fix lexing bug encountered when doc-comments contain space-only lines
  lib/rust/parser/debug/tests/parse.rs
  lib/rust/parser/src/lexer.rs
Labels: CI: Ready to merge, CI: No changelog needed

#4083 Reload module's sources when LS reloads buffer
  engine/language-server/src/main/scala/org/enso/languageserver/text/CollaborativeBuffer.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/FileNotificationsTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime-with-instruments/src/test/java/org/enso/interpreter/test/instrument/IncrementalUpdatesTest.java
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/BuiltinTypesTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeAsyncCommandsTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeComponentsTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeErrorsTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeInstrumentTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeStdlibTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeSuggestionUpdatesTest.scala
  engine/runtime-with-polyglot/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/CommandFactory.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/SetModuleSourcesCmd.scala
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#4074 Enable asserts in the tests
  build.sbt
  engine/runtime-with-instruments/src/test/java/org/enso/interpreter/test/instrument/AvoidIdInstrumentationTagTest.java
  engine/runtime/src/main/java/org/enso/interpreter/node/EnsoRootNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/ExpressionNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/function/BlockNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/function/StatementNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/BranchResult.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/Builtin.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/Atom.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/AtomConstructor.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Type.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicException.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/TopLevelScope.java
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/JobExecutionEngine.scala
  engine/runtime/src/test/java/org/enso/interpreter/test/BigNumberTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/DebuggingEnsoTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/EqualsTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/HashCodeTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/MetaObjectTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/TestBase.java
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/SystemProcessTest.scala
  test/Tests/src/Semantic/Meta_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#4075 Documentation display delay and hovered item preview caption
  Cargo.lock
  app/gui/src/presenter/searcher.rs
  app/gui/view/debug_scene/documentation/src/lib.rs
  app/gui/view/documentation/Cargo.toml
  app/gui/view/documentation/src/html.rs
  app/gui/view/documentation/src/lib.rs
  app/gui/view/documentation/tailwind.config.js
  app/gui/view/src/component_browser.rs
  lib/rust/ensogl/app/theme/hardcoded/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#4091 Provide better diagnostics when handlers crash
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/vcs/InitVcsHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/vcs/ListVcsHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/vcs/RestoreVcsHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/vcs/SaveVcsHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/vcs/StatusVcsHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/CollaborativeBuffer.scala
Labels: CI: Ready to merge, CI: No changelog needed

#4093 Warnings API
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Warnings.enso
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextEventsListener.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistryProtocol.scala
  engine/language-server/src/test/scala/org/enso/languageserver/runtime/ContextEventsListenerSpec.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime-with-instruments/src/test/java/org/enso/interpreter/test/instrument/IncrementalUpdatesTest.java
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime-with-polyglot/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/WithWarnings.java
  engine/runtime/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/TestMessages.scala
Labels: CI: Ready to merge, CI: No changelog needed

#4084 Allow removing all nodes from the scene
  app/gui/controller/double-representation/src/graph.rs
Labels: CI: Ready to merge, CI: No changelog needed

#4095 vcs/restore triggers execution
  engine/language-server/src/main/scala/org/enso/languageserver/text/CollaborativeBuffer.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeAsyncCommandsTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#4090 Propagate subjectToInstrumentation flag via ExpressionProcessor
  engine/runtime-with-instruments/src/test/java/org/enso/interpreter/test/instrument/AvoidIdInstrumentationTagTest.java
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
Labels: CI: Ready to merge, CI: No changelog needed

#4006 Send all pending expressions
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/RecomputeContextCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
Labels: CI: Ready to merge, CI: No changelog needed

#4086 First steps of the Problem Handling refactor to the new design
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Map.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column_Name_Mapping.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Problem_Builder.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Extensions.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Problems.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Scatter_Plot.enso
  test/Table_Tests/src/Common_Table_Operations/Order_By_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Select_Columns_Spec.enso
  test/Table_Tests/src/Database/Codegen_Spec.enso
  test/Table_Tests/src/Database/Common_Spec.enso
  test/Tests/src/Data/Map_Spec.enso
  test/Visualization_Tests/src/Scatter_Plot_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#4077 Create static wrappers for builtin types
  CHANGELOG.md
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/Any.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/MethodDefinitions.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/MethodsTest.scala
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/MethodProcessor.java
  test/Tests/src/Semantic/Error_Spec.enso
  test/Tests/src/Semantic/Java_Interop_Spec.enso
  test/Tests/src/Semantic/Warnings_Spec.enso
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Nothing.enso
Labels: CI: Ready to merge

#4100 Fix vcs-restore edit notification
  engine/language-server/src/main/scala/org/enso/languageserver/text/CollaborativeBuffer.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/FileNotificationsTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime-with-instruments/src/test/java/org/enso/interpreter/test/instrument/IncrementalUpdatesTest.java
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/BuiltinTypesTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeAsyncCommandsTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeComponentsTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeErrorsTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeInstrumentTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeStdlibTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeSuggestionUpdatesTest.scala
  engine/runtime-with-polyglot/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/CommandFactory.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/OpenFileCmd.scala
Labels: CI: Ready to merge, CI: No changelog needed

#4103 Fix missing /home/ensodev directory
  tools/ci/docker/Dockerfile
Labels: CI: Ready to merge, CI: No changelog needed

#4094 Avoid relying on order of updates for hierarchy index
  app/gui/suggestion-database/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#4104 Review `Table.order_by`
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Aggregate_Helper.enso
  distribution/lib/Standard/Searcher/0.0.0-dev/src/Data_Science.enso
  distribution/lib/Standard/Searcher/0.0.0-dev/src/Data_Science/Transform.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Aggregate_Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Sort_Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Sort_Column_Selector.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Aggregate_Column_Helper.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Main.enso
  test/Benchmarks/src/Table/Sorting.enso
  test/Table_Tests/src/Common_Table_Operations/Aggregate_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Distinct_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Expression_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Integration_Tests.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Cross_Join_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Zip_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Order_By_Spec.enso
  test/Table_Tests/src/Database/Codegen_Spec.enso
  test/Table_Tests/src/Database/Common_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#4097 New set function, parse a column
  CHANGELOG.md
  app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Filter_Condition.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Metadata.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Postgres_Options.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Helpers.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Set_Mode.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Delimited/Delimited_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Filter_Condition_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Main.enso
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/text/Text.java
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Core_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Expression_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Filter_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Join_Spec.enso
  test/Table_Tests/src/Database/Codegen_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Formatting/Parse_Values_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
  test/Tests/src/Data/List_Spec.enso
  test/Tests/src/Data/Text_Spec.enso
  test/Tests/src/Data/Vector_Spec.enso
  test/Visualization_Tests/src/Widgets/Database_Widgets_Spec.enso
  test/Visualization_Tests/src/Widgets/Table_Widgets_Spec.enso
Labels: CI: Ready to merge

#4105 Don't attempt to access JGit config in VCS ops
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/data/Config.scala
  engine/language-server/src/main/scala/org/enso/languageserver/vcsmanager/EmptyUserConfigReader.scala
  engine/language-server/src/main/scala/org/enso/languageserver/vcsmanager/VcsManager.scala
  engine/language-server/src/test/scala/org/enso/languageserver/boot/resource/RepoInitializationSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/effect/Effects.scala
  engine/language-server/src/test/scala/org/enso/languageserver/filemanager/ContentRootManagerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/runtime/ContextEventsListenerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/SuggestionsHandlerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/vcsmanager/GitSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/binary/BaseBinaryServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/FileManagerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/VcsManagerTest.scala
Labels: CI: Ready to merge, CI: No changelog needed
