Repository enso-org/enso, pull requests merged in 2023-12, with the labels that each got.

#8437 Replacing usage of Source by (Location => String)
  build.sbt
  engine/runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime-parser/src/main/java/org/enso/compiler/core/IR.java
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Diagnostic.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Empty.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Warning.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/Error.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Conversion.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/ImportExport.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Pattern.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Redefined.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Resolution.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Syntax.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Unexpected.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/warnings/Shadowed.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/warnings/Unreachable.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/warnings/Unused.scala
  engine/runtime-parser/src/test/java/org/enso/compiler/core/EnsoParserTest.java
  engine/runtime-parser/src/test/java/org/enso/compiler/core/ParserDependenciesTest.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
Labels: CI: No changelog needed

#8415 Multi line chained operator syntax
  engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java
  engine/runtime-parser/src/test/java/org/enso/compiler/core/EnsoParserTest.java
  engine/runtime/src/test/java/org/enso/compiler/ExecCompilerTest.java
Labels: CI: No changelog needed

#8435 Fix node not being draggable
  app/gui2/src/components/CodeEditor.vue
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/util/codemirror.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, --regression, -gui2

#8389 Fallback to default visualization based on type, when no viz has been explicitly set
  app/gui2/scripts/generateBuiltinVisualizationMetadata.js
  app/gui2/shared/languageServer.ts
  app/gui2/shared/yjsModel.ts
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/GraphVisualization.vue
  app/gui2/src/components/SvgIcon.vue
  app/gui2/src/components/VisualizationContainer.vue
  app/gui2/src/components/VisualizationSelector.vue
  app/gui2/src/components/visualizations/HeatmapVisualization.vue
  app/gui2/src/components/visualizations/HistogramVisualization.vue
  app/gui2/src/components/visualizations/ImageBase64Visualization.vue
  app/gui2/src/components/visualizations/JSONVisualization.vue
  app/gui2/src/components/visualizations/LoadingErrorVisualization.vue
  app/gui2/src/components/visualizations/LoadingVisualization.vue
  app/gui2/src/components/visualizations/SQLVisualization.vue
  app/gui2/src/components/visualizations/TableVisualization.vue
  app/gui2/src/components/visualizations/WarningsVisualization.vue
  app/gui2/src/providers/visualizationConfig.ts
  app/gui2/src/stores/graph/index.ts
  app/gui2/src/stores/project/index.ts
  app/gui2/src/stores/visualization/compilerMessaging.ts
  app/gui2/src/stores/visualization/index.ts
  app/gui2/src/stores/visualization/metadata.ts
  app/gui2/src/stores/visualization/runtimeTypes.ts
  app/gui2/src/util/urlString.ts
  app/gui2/src/util/visualizationBuiltins.ts
  app/gui2/stories/setup.ts
  app/gui2/ydoc-server/edits.ts
  app/gui2/ydoc-server/fileFormat.ts
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, -gui2

#8438 Properly report errors on duplicated constructor names
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Redefined.scala
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
  engine/runtime/src/test/java/org/enso/compiler/ExecCompilerTest.java
  engine/runtime/src/test/java/org/enso/compiler/ExecStrictCompilerTest.java
Labels: CI: No changelog needed

#8407 Build distribution for amd64 and aarch64 MacOS
  build.sbt
  lib/scala/cli/src/main/scala/org/enso/cli/OS.scala
  project/DistributionPackage.scala
  project/Platform.scala
Labels: CI: No changelog needed, CI: Clean build required

#8455 Dynamic dropdowns
  app/gui2/src/components/GraphEditor/widgets/WidgetApplication.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetFunction.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetPort.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetTopLevelArgument.vue
Labels: -gui2

#8458 Fix package
  app/gui2/src/util/vec2.ts
  build/ci_utils/src/cache/goodie/graalpy.rs
  build/ci_utils/src/programs/graalpy.rs
Labels: p-highest, CI: Ready to merge, CI: No changelog needed, CI: Clean build required, --bug, --regression, -gui2

#8459 Zoom to all/zoom to selected
  app/gui2/src/bindings.ts
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/VisualizationSelector.vue
  app/gui2/src/components/visualizations/HistogramVisualization.vue
  app/gui2/src/components/visualizations/ScatterplotVisualization.vue
  app/gui2/src/util/navigator.ts
  app/gui2/src/util/rect.ts
  app/gui2/stories/UserDefinedVisualization.story.vue
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required, x-new-feature, -gui2

#8263 New AST types
  app/gui2/src/components/CodeEditor.vue
  app/gui2/src/components/ComponentBrowser/input.ts
  app/gui2/src/components/GraphEditor/NodeWidget.vue
  app/gui2/src/components/GraphEditor/NodeWidgetTree.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetApplication.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetBlank.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetCheckbox.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetFunction.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetHierarchy.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetNumber.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetPort.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetToken.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetVector.vue
  app/gui2/src/components/widgets/ListWidget.vue
  app/gui2/src/providers/__tests__/widgetRegistry.test.ts
  app/gui2/src/providers/portInfo.ts
  app/gui2/src/providers/widgetRegistry.ts
  app/gui2/src/providers/widgetTree.ts
  app/gui2/src/stores/graph/__tests__/graphDatabase.test.ts
  app/gui2/src/stores/graph/graphDatabase.ts
  app/gui2/src/stores/graph/imports.ts
  app/gui2/src/stores/graph/index.ts
  app/gui2/src/util/ast/__tests__/abstract.test.ts
  app/gui2/src/util/ast/__tests__/callTree.test.ts
  app/gui2/src/util/ast/abstract.ts
  app/gui2/src/util/ast/aliasAnalysis.ts
  app/gui2/src/util/ast/index.ts
  app/gui2/src/util/ast/opr.ts
  app/gui2/src/util/callTree.ts
  app/gui2/src/util/codemirror.ts
  app/gui2/src/util/qualifiedName.ts
  app/gui2/stories/GraphNode.story.vue
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required, -gui2

#8448 Consistent simple and qualified type name
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Aggregate_Column_Helper.enso
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeErrorsTest.scala
  engine/runtime-with-polyglot/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/IndirectInvokeConversionNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeConversionNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/resolver/HostMethodCallNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/CaseNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/atom/InstantiateNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/date/ToEnsoDateNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/CatchPanicNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/ErrorToTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/ThrowPanicNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/generic/ExecuteNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/generic/GetMemberNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/generic/InstantiateNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/generic/InvokeNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/io/PrintErrNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/io/PrintlnNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/io/ReadlnNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EnsoProjectNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsComplexNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/GetSimpleTypeNameNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/HashCodeNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/InstrumentorEvalNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/IsSameObjectNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/HashCallbackNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/LessThanNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/runtime/GetStackTraceNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToDisplayTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/util/ExpectStringNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/util/TypeToDisplayTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/ResourceManager.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/AtomConstructor.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoDuration.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoFile.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/hash/EnsoHashMap.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/hash/HashMapGetNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/hash/HashMapRemoveNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/hash/HashMapToTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/ArrayLikeCopyToArrayNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/ArraySlice.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/Vector.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicException.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/Warning.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/WithWarnings.java
  engine/runtime/src/test/java/org/enso/interpreter/test/MetaObjectTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/ValuesGenerator.java
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/ConstructorsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/MethodsTest.scala
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/builtins/SafeWrapException.java
  test/Table_Tests/src/Common_Table_Operations/Core_Spec.enso
  test/Tests/src/Data/Array_Proxy_Spec.enso
  test/Tests/src/Data/Vector_Spec.enso
  test/Tests/src/Semantic/Meta_Location_Spec.enso
  test/Visualization_Tests/src/Default_Visualizations_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#8444 Use MIME type parameter for drag instead of a unique MIME type
  app/gui2/src/components/widgets/ListWidget.vue
Labels: CI: Ready to merge, CI: No changelog needed, x-chore, -gui2

#8414 Add button to toggle whether passwords are visible
  app/ide-desktop/eslint.config.js
  app/ide-desktop/lib/assets/eye.svg
  app/ide-desktop/lib/assets/eye_crossed.svg
  app/ide-desktop/lib/dashboard/esbuild-config.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/input.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/login.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/registration.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/resetPassword.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/svgIcon.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/autocomplete.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/changePasswordModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/contextMenuSeparator.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/driveBar.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/manageLabelsModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/managePermissionsModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/menuEntry.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/newDataConnectorModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/newLabelModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/permissionTypeSelector.tsx
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#8451 Component Browser Preview Panel
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/components/ComponentBrowser/input.ts
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/GraphVisualization.vue
  app/gui2/src/components/VisualizationContainer.vue
  app/gui2/src/providers/visualizationConfig.ts
  app/gui2/src/stores/graph/index.ts
  app/gui2/src/stores/project/index.ts
  app/gui2/src/stores/project/visualizationDataRegistry.ts
  app/gui2/src/stores/visualization/index.ts
  app/gui2/src/util/result.ts
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required, x-new-feature, -gui2

#8400 Reading widget configuration from the engine
  app/gui2/src/components/GraphEditor/NodeWidget.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetApplication.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetFunction.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetPort.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetTopLevelArgument.vue
  app/gui2/src/providers/__tests__/widgetRegistry.test.ts
  app/gui2/src/providers/widgetRegistry.ts
  app/gui2/src/providers/widgetRegistry/configuration.ts
  app/gui2/src/stores/suggestionDatabase/__tests__/lsUpdate.test.ts
  app/gui2/src/stores/suggestionDatabase/entry.ts
  app/gui2/src/stores/suggestionDatabase/lsUpdate.ts
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, -gui2

#8454 Inline execution should support FQNs
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Main.enso
  engine/runtime-compiler/src/main/scala/org/enso/compiler/context/InlineContext.scala
  engine/runtime-with-polyglot/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/debug/EvalNode.java
  lib/scala/pkg/src/main/scala/org/enso/pkg/Package.scala
Labels: CI: No changelog needed

#8466 Ignore resources in linter
  .prettierignore
Labels: CI: No changelog needed

#8446 Mark some tests as flaky on Windows
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/ReceivesTreeUpdatesHandlerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/VcsManagerTest.scala
  lib/scala/library-manager-test/src/test/scala/org/enso/librarymanager/published/repository/LibraryDownloadTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#8471 Add missing resources for aarch64
  lib/scala/runtime-version-manager-test/src/main/resources/org/enso/runtimeversionmanager/test/fake-releases/enso/enso-0.0.0-pre/enso-engine-0.0.0-pre-macos-aarch64.tar.gz/enso-0.0.0-pre/component/runner.jar
  lib/scala/runtime-version-manager-test/src/main/resources/org/enso/runtimeversionmanager/test/fake-releases/enso/enso-0.0.0-pre/enso-engine-0.0.0-pre-macos-aarch64.tar.gz/enso-0.0.0-pre/component/runtime.jar
  lib/scala/runtime-version-manager-test/src/main/resources/org/enso/runtimeversionmanager/test/fake-releases/enso/enso-0.0.0/enso-engine-0.0.0-macos-aarch64.tar.gz/enso-0.0.0/component/runner.jar
  lib/scala/runtime-version-manager-test/src/main/resources/org/enso/runtimeversionmanager/test/fake-releases/enso/enso-0.0.0/enso-engine-0.0.0-macos-aarch64.tar.gz/enso-0.0.0/component/runtime.jar
  lib/scala/runtime-version-manager-test/src/main/resources/org/enso/runtimeversionmanager/test/fake-releases/enso/enso-0.0.1-pre/enso-engine-0.0.1-pre-macos-aarch64.tar.gz/enso-0.0.1-pre/component/runner.jar
  lib/scala/runtime-version-manager-test/src/main/resources/org/enso/runtimeversionmanager/test/fake-releases/enso/enso-0.0.1-pre/enso-engine-0.0.1-pre-macos-aarch64.tar.gz/enso-0.0.1-pre/component/runtime.jar
  lib/scala/runtime-version-manager-test/src/main/resources/org/enso/runtimeversionmanager/test/fake-releases/enso/enso-0.0.1/enso-engine-0.0.1-macos-aarch64.tar.gz/enso-0.0.1/component/runner/runner.jar
  lib/scala/runtime-version-manager-test/src/main/resources/org/enso/runtimeversionmanager/test/fake-releases/enso/enso-0.0.1/enso-engine-0.0.1-macos-aarch64.tar.gz/enso-0.0.1/component/runtime.jar
  lib/scala/runtime-version-manager-test/src/main/resources/org/enso/runtimeversionmanager/test/fake-releases/enso/enso-0.1.0/enso-engine-0.1.0-macos-aarch64.tar.gz/enso-0.1.0/component/runner/runner.jar
  lib/scala/runtime-version-manager-test/src/main/resources/org/enso/runtimeversionmanager/test/fake-releases/enso/enso-0.1.0/enso-engine-0.1.0-macos-aarch64.tar.gz/enso-0.1.0/component/runtime.jar
  lib/scala/runtime-version-manager-test/src/main/resources/org/enso/runtimeversionmanager/test/fake-releases/enso/enso-0.9999.0-broken/enso-engine-0.9999.0-broken-macos-aarch64.tar.gz/enso-0.9999.0-broken/component/runner.jar
  lib/scala/runtime-version-manager-test/src/main/resources/org/enso/runtimeversionmanager/test/fake-releases/enso/enso-0.9999.0-broken/enso-engine-0.9999.0-broken-macos-aarch64.tar.gz/enso-0.9999.0-broken/component/runtime.jar
  lib/scala/runtime-version-manager-test/src/main/resources/org/enso/runtimeversionmanager/test/fake-releases/graalvm/vm-1.0.0/graalvm-ce-java11-darwin-aarch64-1.0.0.tar.gz/graalvm-ce-java11-1.0.0/Contents/Home/bin/java
  lib/scala/runtime-version-manager-test/src/main/resources/org/enso/runtimeversionmanager/test/fake-releases/graalvm/vm-2.0.0/graalvm-ce-java11-darwin-aarch64-2.0.0.tar.gz/graalvm-ce-java11-2.0.0/Contents/Home/bin/java
  lib/scala/runtime-version-manager-test/src/main/resources/org/enso/runtimeversionmanager/test/fake-releases/graalvm/vm-23.0.0/graalvm-ce-java17.0.7-darwin-aarch64-23.0.0.tar.gz/graalvm-ce-java17.0.7-23.0.0/Contents/Home/bin/java
Labels: CI: No changelog needed

#8477 Selection widget improvements
  app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue
Labels: CI: No changelog needed, g-widgets, -gui2

#8488 Fix node output type
  app/gui2/src/components/GraphEditor/GraphNode.vue
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui2

#8464 Sync presenter state not only on abort, but also on commit
  app/gui/src/presenter/searcher/component_browser.rs
Labels: CI: No changelog needed

#8490 Read file directly from location
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/upload.ts
  app/gui2/src/stores/project/index.ts
  app/gui2/src/util/ast/text.ts
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, -gui2

#8486 Increase timeout for running launcher command
  engine/launcher/src/test/scala/org/enso/launcher/NativeLauncherSpec.scala
  engine/launcher/src/test/scala/org/enso/launcher/NativeTest.scala
  engine/launcher/src/test/scala/org/enso/launcher/PluginManagerSpec.scala
  engine/launcher/src/test/scala/org/enso/launcher/installation/UninstallerSpec.scala
  lib/scala/runtime-version-manager-test/src/main/scala/org/enso/runtimeversionmanager/test/NativeTestHelper.scala
Labels: CI: No changelog needed

#8475 Turning Sieve benchmarks into Enso benchmarks
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/SieveBenchmarks.java
  lib/scala/bench-processor/src/main/java/org/enso/benchmarks/processor/BenchProcessor.java
  test/Benchmarks/data/sieve.js
  test/Benchmarks/src/Main.enso
  test/Benchmarks/src/Sieve/Main.enso
  test/Benchmarks/src/Sieve/Sieve_Ascribed.enso
  test/Benchmarks/src/Sieve/Sieve_Java_Script.enso
  test/Benchmarks/src/Sieve/Sieve_Original.enso
  test/Benchmarks/src/Sieve/Sieve_Without_Types.enso
Labels: CI: No changelog needed, CI: Clean build required

#8499 Use Enso font
  app/gui2/.gitignore
  app/gui2/.prettierignore
  app/gui2/e2e/MockApp.vue
  app/gui2/package.json
  app/gui2/scripts/downloadFonts.js
  app/gui2/src/App.vue
  app/gui2/src/assets/base.css
  app/gui2/src/assets/font-dejavu.css
  app/gui2/src/assets/font-enso.css
  app/gui2/src/assets/font-mplus1.css
  app/gui2/src/assets/main.css
  app/gui2/src/components/CodeEditor.vue
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/components/DocumentationPanel.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/visualizations/HeatmapVisualization.vue
  app/gui2/src/components/visualizations/JSONVisualization.vue
  app/gui2/src/components/visualizations/SQLVisualization.vue
  app/gui2/stories/setup.ts
  app/gui2/stories/story.css
  package-lock.json
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, -gui2

#8492 Entering and leaving nodes
  app/gui2/src/bindings.ts
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/GraphNodes.vue
  app/gui2/src/components/NavBar.vue
  app/gui2/src/composables/doubleClick.ts
  app/gui2/src/stores/graph/index.ts
  app/gui2/src/stores/project/index.ts
Labels: CI: Ready to merge, CI: No changelog needed, g-graph-editor, -gui2

#8506 Add new magnet axes
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/__tests__/dragging.test.ts
  app/gui2/src/components/GraphEditor/dragging.ts
  app/gui2/src/stores/graph/graphDatabase.ts
  app/gui2/src/stores/graph/index.ts
  app/gui2/src/util/navigator.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui2

#8461 Fix missing edges
  app/gui2/src/components/GraphEditor/widgets/WidgetHierarchy.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetPort.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetVector.vue
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui2

#8510 Compare long and double and BigInteger properly
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/NumericLiteralBranchNode.java
  test/Tests/src/Semantic/Case_Spec.enso
Labels: CI: No changelog needed

#8445 Hide GUI2 when not in Editor tab
  app/ide-desktop/lib/content/src/index.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/editor.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/pageSwitcher.tsx
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard, -gui2

#8462 E2E Tests in CI
  app/gui2/e2e/componentBrowser.spec.ts
  app/gui2/e2e/locate.ts
  app/gui2/package.json
  app/gui2/playwright.config.ts
  app/gui2/src/components/GraphEditor/GraphVisualization.vue
  app/gui2/src/stores/project/index.ts
  app/gui2/src/stores/project/visualizationDataRegistry.ts
  build/build/src/project/gui2.rs
  build/cli/src/arg/gui2.rs
  build/cli/src/lib.rs
Labels: CI: No changelog needed, -ci, x-new-feature, -gui2

#8470 Parse inline function signatures
  app/gui/language/parser/src/translation.rs
  app/gui2/src/util/ast/__tests__/aliasAnalysis.test.ts
  app/gui2/src/util/ast/abstract.ts
  app/gui2/src/util/ast/aliasAnalysis.ts
  engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java
  engine/runtime/src/test/java/org/enso/compiler/ExecCompilerTest.java
  lib/rust/parser/debug/tests/parse.rs
  lib/rust/parser/src/lib.rs
  lib/rust/parser/src/syntax/tree.rs
Labels: CI: Ready to merge, CI: No changelog needed, -parser, -gui2

#8515 Fix typo in `Match.enso`
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Match.enso
  test/Tests/src/Data/Text/Regex_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, --bug

#8449 Dashboard improvements
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/cognito.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/registration.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/auth.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/backend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/column.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetRow.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetsTable.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/chat.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/chatPlaceholder.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/connectorNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/directoryNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/fileNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/globalContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/labels.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/manageLabelsModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/newLabelModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectIcon.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/samples.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/events/assetEvent.ts
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#8507 Some CB fixes
  app/gui2/src/components/CodeEditor.vue
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/components/ComponentBrowser/input.ts
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphEdges.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/stores/graph/index.ts
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required, --bug, --regression, -gui2

#8307 Better Error Trapping in map
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Statistics.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Error.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Wrapped_Error.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Array_Like_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Runtime/Ref.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Warning.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Take_Drop_Helpers.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/IR/Context.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Data_Formatter.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Type/Value_Type_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Extensions/Table_Ref.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Aggregate_Column_Helper.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Delimited_Reader.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Java_Problems.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Join_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Lookup_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Bench.enso
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Ref.java
  test/Benchmarks/src/Main.enso
  test/Benchmarks/src/Vector/Map_Error_Benchmark.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
  test/Tests/src/Data/Vector_Spec.enso
  test/Tests/src/Runtime/Ref_Spec.enso
  test/Tests/src/Semantic/Error_Spec.enso
Labels: CI: Clean build required

#8535 Small GUI improvements
  app/gui2/src/assets/main.css
  app/gui2/src/bindings.ts
  app/gui2/src/components/CodeEditor.vue
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/SelectionBrush.vue
  app/gui2/src/components/VisualizationContainer.vue
  app/gui2/src/components/widgets/SliderWidget.vue
  lib/scala/pkg/src/main/resources/default/src/Main.enso
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui2

#8508 Fixes for Enso Font in GUI2
  app/gui2/.gitignore
  app/gui2/index.html
  app/gui2/scripts/downloadFonts.js
  app/gui2/src/assets/font-dejavu.css
  app/gui2/src/assets/font-enso.css
  app/gui2/src/assets/font-mplus1.css
  app/gui2/src/components/CodeEditor.vue
  app/gui2/src/components/DocumentationPanel.vue
  app/gui2/stories/story.css
  build/build/paths.yaml
  build/build/src/ide/web.rs
  build/build/src/ide/web/dejavu_font.rs
  build/build/src/ide/web/enso_font.rs
  build/build/src/ide/web/fonts.rs
  build/build/src/ide/web/google_font.rs
  build/build/src/project/gui2.rs
  build/ci_utils/src/archive.rs
  build/ci_utils/src/archive/extract_files.rs
  build/ci_utils/src/archive/tar.rs
  build/ci_utils/src/archive/zip.rs
  build/ci_utils/src/lib.rs
  lib/rust/enso-font/src/lib.rs
  lib/rust/ensogl/component/text/src/font/embedded/build.rs
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui2

#8536 Minor improvement to Startup.enso error
  test/Benchmarks/src/Startup/Startup.enso
Labels: CI: Ready to merge, CI: No changelog needed

#8541 Fix console error when dragging assets
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetsTable.tsx
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#8528 Improve details attached to `No_Output_Columns` reported from various operations
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Match_Columns.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Aggregate_Column_Helper.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Problem_Builder.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  test/Table_Tests/src/Common_Table_Operations/Aggregate_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Union_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Missing_Values_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Select_Columns_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#8272 Try reporting diagnostics in non-strict mode
  engine/runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/MockLogHandler.java
  engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/NonStrictConversionMethodTests.java
  engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/NonStrictModeTests.java
  engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/instrument/VerifyJavaScriptIsAvailableTest.java
Labels: CI: Ready to merge, CI: No changelog needed

#8403 Reworking Excel support to allow for reading of big files
  .prettierignore
  CHANGELOG.md
  build.sbt
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Any.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Enso_Cloud/Enso_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/XML/XML_Format.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/File_Error.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Illegal_State.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Response_Body.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Nothing.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/Advanced/Temporary_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/Existing_File_Behavior.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File_Format.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/Input_Stream.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Delimited/Delimited_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Workbook.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Delimited_Writer.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Excel_Reader.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Excel_Writer.enso
  std-bits/base/src/main/java/org/enso/base/DryRunFileManager.java
  std-bits/table/src/main/java/org/enso/table/error/InvalidLocationException.java
  std-bits/table/src/main/java/org/enso/table/excel/ExcelConnectionPool.java
  std-bits/table/src/main/java/org/enso/table/excel/ExcelFileFormat.java
  std-bits/table/src/main/java/org/enso/table/excel/ReadOnlyExcelConnection.java
  std-bits/table/src/main/java/org/enso/table/read/ExcelReader.java
  std-bits/table/src/main/java/org/enso/table/write/ExcelWriter.java
  std-bits/table/src/main/java/org/enso/table/write/ExistingFileBehavior.java
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/IO/Excel_Spec.enso
  test/Table_Tests/src/IO/Fetch_Spec.enso
  test/Table_Tests/src/IO/Formats_Spec.enso
  test/Table_Tests/src/IO/Main.enso
  test/Tests/polyglot-sources/enso-test-java-helpers/src/main/java/org/enso/table_test_helpers/RandomHelpers.java
  test/Tests/src/Main.enso
  test/Tests/src/System/File_Spec.enso
  test/Tests/src/System/Temporary_File_Spec.enso
  tools/simple-httpbin/src/main/java/org/enso/shttp/SimpleHTTPBin.java
  tools/simple-httpbin/src/main/java/org/enso/shttp/TestHandler.java
  tools/simple-httpbin/www-files/table.csv
  tools/simple-httpbin/www-files/table.json
  tools/simple-httpbin/www-files/table.xls
  tools/simple-httpbin/www-files/table.xlsx
Labels: CI: Ready to merge

#8440 Set output evaluation context for a single node
  app/gui2/e2e/MockApp.vue
  app/gui2/e2e/main.ts
  app/gui2/e2e/setup.ts
  app/gui2/mock/engine.ts
  app/gui2/mock/index.ts
  app/gui2/mock/projectManager.ts
  app/gui2/mock/providers.ts
  app/gui2/mock/vue.ts
  app/gui2/src/assets/icons.svg
  app/gui2/src/components/CircularMenu.vue
  app/gui2/src/components/GraphEditor/GraphEdge.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/GraphNodes.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetVector.vue
  app/gui2/src/components/ToggleIcon.vue
  app/gui2/src/composables/events.ts
  app/gui2/src/stores/graph/graphDatabase.ts
  app/gui2/src/stores/graph/index.ts
  app/gui2/src/stores/project/index.ts
  app/gui2/src/util/ast/__tests__/abstract.test.ts
  app/gui2/src/util/ast/__tests__/match.test.ts
  app/gui2/src/util/ast/__tests__/prefixes.test.ts
  app/gui2/src/util/ast/__tests__/text.ts
  app/gui2/src/util/ast/abstract.ts
  app/gui2/src/util/ast/match.ts
  app/gui2/src/util/ast/node.ts
  app/gui2/src/util/ast/prefixes.ts
  app/gui2/src/util/data/iterable.ts
  app/gui2/src/util/net.ts
  app/gui2/src/util/record.ts
  app/gui2/src/util/theme.json
  app/gui2/src/util/theme.ts
  app/gui2/tsconfig.app.json
  app/gui2/tsconfig.node.json
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, -gui2

#7882 Run Enso tests with assertions enabled
  build.sbt
  build/build/src/enso.rs
  engine/polyglot-api/src/main/java/org/enso/polyglot/ForeignLanguage.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/desugar/GenerateMethodBodies.scala
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/CoercePrimitiveNode.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbContext.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbLanguage.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbParser.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/ExceptionForeignNode.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/ForeignEvalNode.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/ForeignFunctionCallNode.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/ForeignParsingException.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/GenericForeignNode.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/JsForeignNode.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/PyForeignNode.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/node/ContextRewrapExceptionNode.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/node/ContextRewrapNode.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/node/ForeignEvalNode.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/node/JsForeignNode.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/node/RForeignNode.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/node/ReadOnlyArray.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/runtime/GuardedTruffleContext.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/runtime/PolyglotExceptionProxy.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/runtime/PolyglotProxy.java
  engine/runtime-language-epb/src/test/java/org/enso/interpreter/epb/EpbLanguageDependenciesTest.java
  engine/runtime-language-epb/src/test/java/org/enso/interpreter/epb/ForeignEvalNodeTest.java
  engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/ForeignMethodInvokeTest.java
  engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/instrument/VerifyLanguageAvailabilityTest.java
  engine/runtime/src/main/java/org/enso/interpreter/EnsoLanguage.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/FunctionCallInstrumentationNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/Instrumentor.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/InstrumentorEvalNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/PowNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/Array.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/ArrayBuilder.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/ArrayLikeAtNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/ArrayLikeHelpers.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/DebugLocalScope.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
  lib/scala/bench-processor/src/main/java/org/enso/benchmarks/processor/BenchProcessor.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/Builder.java
  test/Benchmarks/src/Sieve/Sieve_Ascribed.enso
  test/Benchmarks/src/Sieve/Sieve_Java_Script.enso
  test/Benchmarks/src/Sieve/Sieve_Original.enso
  test/Benchmarks/src/Sieve/Sieve_Without_Types.enso
  test/Tests/src/Semantic/Python_Interop_Spec.enso
Labels: CI: No changelog needed, CI: Clean build required

#8550 Fix serialization of alias analysis graph
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/PassPersistance.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
Labels: CI: Ready to merge, CI: No changelog needed

#8557 Minor fixes and tweak for Cloud APIs.
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Type/Value_Type.enso
  std-bits/base/src/main/java/org/enso/base/enso_cloud/EnsoSecretReader.java
Labels: CI: Ready to merge, CI: No changelog needed

#8562 A few minor fixes from release testing today.
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/cognito.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/login.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/changePasswordModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/drive.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/userMenu.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/shortcuts.ts
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#8497 Improving tests and edge cases for URI and HTTP
  build.sbt
  distribution/lib/Standard/Base/0.0.0-dev/THIRD-PARTY/NOTICE
  distribution/lib/Standard/Base/0.0.0-dev/THIRD-PARTY/commons-codec.commons-codec-1.9/LICENSE.txt
  distribution/lib/Standard/Base/0.0.0-dev/THIRD-PARTY/commons-codec.commons-codec-1.9/NOTICE.txt
  distribution/lib/Standard/Base/0.0.0-dev/THIRD-PARTY/commons-logging.commons-logging-1.2/NOTICE.txt
  distribution/lib/Standard/Base/0.0.0-dev/THIRD-PARTY/licenses/APACHE2.0
  distribution/lib/Standard/Base/0.0.0-dev/THIRD-PARTY/org.apache.httpcomponents.httpclient-4.4.1/NOTICE
  distribution/lib/Standard/Base/0.0.0-dev/THIRD-PARTY/org.apache.httpcomponents.httpcore-4.4.1/LICENSE
  distribution/lib/Standard/Base/0.0.0-dev/THIRD-PARTY/org.apache.httpcomponents.httpcore-4.4.1/NOTICE
  distribution/lib/Standard/Base/0.0.0-dev/THIRD-PARTY/org.apache.httpcomponents.httpcore-4.4.1/NOTICES
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/HTTP_Error.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/HTTP_Method.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/HTTP_Status_Code.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Response.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/URI.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/URI_With_Query.enso
  std-bits/base/src/main/java/org/enso/base/enso_cloud/EnsoHttpResponse.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/EnsoSecretHelper.java
  std-bits/base/src/main/java/org/enso/base/net/URIHelpers.java
  test/Table_Tests/src/IO/Fetch_Spec.enso
  test/Tests/src/Data/Json_Spec.enso
  test/Tests/src/Network/Http_Spec.enso
  test/Tests/src/Network/URI_Spec.enso
  tools/legal-review/Base/commons-codec.commons-codec-1.9/copyright-ignore
  tools/legal-review/Base/commons-codec.commons-codec-1.9/custom-license
  tools/legal-review/Base/commons-codec.commons-codec-1.9/files-keep
  tools/legal-review/Base/commons-logging.commons-logging-1.2/copyright-ignore
  tools/legal-review/Base/commons-logging.commons-logging-1.2/files-ignore
  tools/legal-review/Base/commons-logging.commons-logging-1.2/files-keep
  tools/legal-review/Base/org.apache.httpcomponents.httpclient-4.4.1/copyright-ignore
  tools/legal-review/Base/org.apache.httpcomponents.httpclient-4.4.1/files-ignore
  tools/legal-review/Base/org.apache.httpcomponents.httpclient-4.4.1/files-keep
  tools/legal-review/Base/org.apache.httpcomponents.httpcore-4.4.1/copyright-add
  tools/legal-review/Base/org.apache.httpcomponents.httpcore-4.4.1/copyright-ignore
  tools/legal-review/Base/org.apache.httpcomponents.httpcore-4.4.1/custom-license
  tools/legal-review/Base/org.apache.httpcomponents.httpcore-4.4.1/files-keep
  tools/legal-review/Base/report-state
  tools/legal-review/Base/reviewed-licenses/Apache_License__Version_2.0
  tools/simple-httpbin/src/main/java/org/enso/shttp/BasicAuthTestHandler.java
  tools/simple-httpbin/src/main/java/org/enso/shttp/CrashingTestHandler.java
  tools/simple-httpbin/src/main/java/org/enso/shttp/HeaderTestHandler.java
  tools/simple-httpbin/src/main/java/org/enso/shttp/SimpleHTTPBin.java
  tools/simple-httpbin/src/main/java/org/enso/shttp/SimpleHttpHandler.java
  tools/simple-httpbin/src/main/java/org/enso/shttp/TestHandler.java
  tools/simple-httpbin/src/main/java/org/enso/shttp/TokenAuthTestHandler.java
Labels: CI: Ready to merge, CI: No changelog needed

#8561 Fixes `Date_Diff` widget
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Calculations/Column_Operation.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#8539 Add a few new `Filter_Condition`s
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Filter_Condition.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Case_Sensitivity.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Range.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Dialect.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Extensions/Table_Ref.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Filter_Condition_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  test/Table_Tests/src/Common_Table_Operations/Date_Time_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Derived_Columns_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Filter_Spec.enso
  test/Tests/src/Data/Range_Spec.enso
  test/Tests/src/Data/Vector_Spec.enso
Labels: CI: Ready to merge, CI: Clean build required

#8563 Fix Table viz error
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
Labels: CI: Ready to merge, CI: No changelog needed

#8560 Syntax error results in silent error
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/desugar/GenerateMethodBodies.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Warning.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Redefined.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/GenerateMethodBodiesTest.scala
  lib/java/persistance/src/main/java/org/enso/persist/Persistance.java
Labels: CI: Ready to merge, CI: No changelog needed

#8519 Graph editor breadcrumbs integration
  .prettierignore
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/NavBar.vue
  app/gui2/src/components/NavBreadcrumb.vue
  app/gui2/src/components/NavBreadcrumbs.vue
  app/gui2/src/components/TopBar.vue
  app/gui2/src/composables/stackNavigator.ts
Labels: CI: Ready to merge, CI: No changelog needed, g-graph-editor, -gui2

#8574 Stop parsing METADATA section for IdMap
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
Labels: CI: Ready to merge, CI: No changelog needed

#8588 Runtime test build depends on fat jar classes
  build.sbt
Labels: CI: Ready to merge, CI: No changelog needed

#8575 Ignore spurious warnings
  build.sbt
Labels: CI: Ready to merge, CI: No changelog needed

#8589 Carry position for project management operations
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/ProjectManagementOps.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectShutdownSpec.scala
Labels: CI: Ready to merge, CI: No changelog needed

#8583 Avoid no WithWarnings warnings
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/WithWarnings.java
  engine/runtime/src/test/java/org/enso/interpreter/test/WarningsTest.java
Labels: CI: No changelog needed

#8577 Add thread dump info to investigate MacOS timeouts
  lib/scala/testkit/src/main/scala/org/enso/testkit/process/WrappedProcess.scala
Labels: CI: Ready to merge, CI: No changelog needed

#8511 Add tests for Enso Cloud auth + simple API mock for `Enso_User`
  .prettierignore
  build.sbt
  build/build/src/httpbin.rs
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Enso_Cloud/Enso_User.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Enso_Cloud/Utils.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Header.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Test_Environment.enso
  std-bits/base/src/main/java/org/enso/base/Environment_Utils.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/AuthenticationProvider.java
  test/Table_Tests/src/IO/Fetch_Spec.enso
  test/Tests/README.md
  test/Tests/src/Main.enso
  test/Tests/src/Network/Enso_Cloud/Enso_Cloud_Spec.enso
  test/Tests/src/Network/Http_Spec.enso
  test/Tests/src/Network/URI_Spec.enso
  tools/http-test-helper/README.md
  tools/http-test-helper/src/main/java/org/enso/shttp/BasicAuthTestHandler.java
  tools/http-test-helper/src/main/java/org/enso/shttp/CrashingTestHandler.java
  tools/http-test-helper/src/main/java/org/enso/shttp/HTTPTestHelperServer.java
  tools/http-test-helper/src/main/java/org/enso/shttp/HandlerWithTokenAuth.java
  tools/http-test-helper/src/main/java/org/enso/shttp/HeaderTestHandler.java
  tools/http-test-helper/src/main/java/org/enso/shttp/HttpMethod.java
  tools/http-test-helper/src/main/java/org/enso/shttp/SimpleHttpHandler.java
  tools/http-test-helper/src/main/java/org/enso/shttp/TestHandler.java
  tools/http-test-helper/src/main/java/org/enso/shttp/TokenAuthTestHandler.java
  tools/http-test-helper/src/main/java/org/enso/shttp/cloud_mock/CloudHandler.java
  tools/http-test-helper/src/main/java/org/enso/shttp/cloud_mock/CloudRoot.java
  tools/http-test-helper/src/main/java/org/enso/shttp/cloud_mock/UsersHandler.java
  tools/http-test-helper/www-files/table.csv
  tools/http-test-helper/www-files/table.json
  tools/http-test-helper/www-files/table.xls
  tools/http-test-helper/www-files/table.xlsx
  tools/simple-httpbin/README.md
Labels: CI: Ready to merge, CI: No changelog needed

#8576 Ast edits
  app/gui2/mock/index.ts
  app/gui2/shared/yjsModel.ts
  app/gui2/src/components/CodeEditor.vue
  app/gui2/src/stores/graph/graphDatabase.ts
  app/gui2/src/stores/graph/index.ts
  app/gui2/src/util/ast/__tests__/abstract.test.ts
  app/gui2/src/util/ast/__tests__/fixtures/stargazers.enso
  app/gui2/src/util/ast/__tests__/match.test.ts
  app/gui2/src/util/ast/__tests__/prefixes.test.ts
  app/gui2/src/util/ast/abstract.ts
  app/gui2/src/util/ast/match.ts
  app/gui2/stories/ComponentBrowser.story.vue
  app/gui2/stories/GraphNode.story.vue
  app/gui2/stories/MockProjectStoreWrapper.vue
  app/gui2/stories/SelectionBrushWrapper.vue
  app/gui2/stories/UserDefinedVisualization.story.vue
  app/gui2/ydoc-server/__tests__/edits.test.ts
  app/gui2/ydoc-server/edits.ts
  app/gui2/ydoc-server/languageServerSession.ts
Labels: CI: Ready to merge, CI: No changelog needed

#8584 Fix dashboard background on Safari
  app/ide-desktop/lib/content/src/index.ts
  app/ide-desktop/lib/dashboard/src/index.ts
  app/ide-desktop/lib/dashboard/src/tailwind.css
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#8596 More robust against debris in the repository
  tools/enso4igv/src/main/java/org/enso/tools/enso4igv/EnsoDataObject.java
  tools/enso4igv/src/main/java/org/enso/tools/enso4igv/EnsoSbtClassPathProvider.java
Labels: CI: No changelog needed

#8599 Fix E2E tests
  app/gui2/e2e/componentBrowser.spec.ts
  app/gui2/src/stores/graph/index.ts
  app/gui2/stories/MockProjectStoreWrapper.vue
Labels: CI: Ready to merge, CI: No changelog needed, --bug, --regression, -gui2

#8607 Update OWNERS
  .github/CODEOWNERS
Labels: CI: No changelog needed, -gui2

#8592 Small linting fixes.
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/XML/XML_Format.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Error.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Wrapped_Error.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Array_Like_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/HTTP_Error.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Workbook.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Problem_Builder.enso
Labels: CI: Ready to merge, CI: No changelog needed

#8566 Better context info in `Type_Error` raised from return type checks
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/PassPersistance.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/DataflowAnalysis.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/desugar/ComplexType.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/SuspendedArguments.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/TypeFunctions.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/TypeNames.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/TypeSignatures.scala
  engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Type.scala
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/argument/ReadArgumentCheckNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/TypeError.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Error.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
  engine/runtime/src/test/java/org/enso/interpreter/test/SignaturePolyglotTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/TextTest.scala
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#8606 Add text_length to column for in-memory and database
  .gitignore
  CHANGELOG.md
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Type_Mapping.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  std-bits/table/src/main/java/org/enso/table/data/column/storage/Storage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/StringStorage.java
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
Labels: CI: Ready to merge

#8605 Add a quick support for pasting data from Excel.
  app/gui2/src/components/GraphEditor.vue
Labels: CI: Ready to merge, CI: No changelog needed

#8593 All unit tests use the same testing logging provider
  build.sbt
  engine/language-server/src/test/resources/application-test.conf
  engine/launcher/src/test/resources/application-test.conf
  engine/runtime/src/test/java/org/enso/interpreter/test/TestLogProviderOnClasspath.java
  engine/runtime/src/test/resources/application-test.conf
  lib/scala/filewatcher/src/test/resources/application-test.conf
  lib/scala/library-manager-test/src/test/resources/application-test.conf
  lib/scala/logger/README.md
  lib/scala/logger/src/main/java/org/enso/package-info.java
  lib/scala/logger/src/main/scala/org/enso/Logger.scala
  lib/scala/logging-service-logback/src/test/java/org/enso/logger/TestLogProvider.java
  lib/scala/project-manager/src/test/java/org/enso/projectmanager/TestLogProviderOnClasspath.java
  lib/scala/project-manager/src/test/resources/application-test.conf
  lib/scala/runtime-version-manager-test/src/test/resources/application-test.conf
Labels: CI: Ready to merge, CI: No changelog needed

#8542 Fix GUI2 entrypoint
  app/gui2/.prettierignore
  app/gui2/e2e/MockApp.vue
  app/gui2/env.d.ts
  app/gui2/index.html
  app/gui2/mock/index.ts
  app/gui2/package.json
  app/gui2/src/App.vue
  app/gui2/src/assets/base.css
  app/gui2/src/assets/main.css
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/HelpScreen.vue
  app/gui2/src/components/HelpScreen/types.ts
  app/gui2/src/config.json
  app/gui2/src/createApp.ts
  app/gui2/src/main.ts
  app/gui2/src/providers/guiConfig.ts
  app/gui2/src/stores/project/index.ts
  app/gui2/src/util/config.ts
  app/gui2/src/util/detect.ts
  app/gui2/src/util/fetchTimeout.ts
  app/gui2/src/util/ffi.ts
  app/gui2/src/util/urlParams.ts
  app/gui2/tsconfig.scripts.json
  app/gui2/vite.config.ts
  package-lock.json
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required, g-dashboard, -gui2

#8573 Display initialization message
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/createApp.ts
  package-lock.json
  package.json
Labels: CI: Ready to merge, CI: Keep up to date, CI: No changelog needed, g-graph-editor, -gui2

#8591 Merge `URI_With_Query` into `URI`, extend API of `URI`
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Enso_Cloud/Utils.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/HTTP_Error.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Header.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Request.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/URI.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/URI_With_Query.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/JDBC_Connection.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Test.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Test_Suite.enso
  std-bits/base/src/main/java/org/enso/base/enso_cloud/EnsoKeyValuePair.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/EnsoSecretAccessDenied.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/EnsoSecretHelper.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/HideableValue.java
  std-bits/base/src/main/java/org/enso/base/net/URIHelpers.java
  std-bits/base/src/main/java/org/enso/base/net/URISchematic.java
  std-bits/base/src/main/java/org/enso/base/net/URITransformer.java
  std-bits/base/src/main/java/org/enso/base/net/URIWithSecrets.java
  std-bits/base/src/main/java/org/enso/base/net/UserInfoWithSecrets.java
  std-bits/database/src/main/java/org/enso/database/JDBCProxy.java
  test/Tests/src/Network/Enso_Cloud/Enso_Cloud_Spec.enso
  test/Tests/src/Network/Http_Spec.enso
  test/Tests/src/Network/URI_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#8600 Handle `Nothing` values in `Filter_Condition.to_predicate`
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Filter_Condition.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Range.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
  test/Tests/src/Data/List_Spec.enso
  test/Tests/src/Data/Range_Spec.enso
  test/Tests/src/Data/Vector_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#8545 [GUI2] Widget update handlers
  app/gui2/playwright.config.ts
  app/gui2/shared/languageServer.ts
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphEdge.vue
  app/gui2/src/components/GraphEditor/GraphEdges.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/NodeWidget.vue
  app/gui2/src/components/GraphEditor/NodeWidgetTree.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetApplication.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetArgumentName.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetBlank.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetCheckbox.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetFunction.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetHierarchy.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetNumber.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetPort.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetToken.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetVector.vue
  app/gui2/src/components/widgets/DropdownWidget.vue
  app/gui2/src/components/widgets/ListWidget.vue
  app/gui2/src/composables/selection.ts
  app/gui2/src/providers/portInfo.ts
  app/gui2/src/providers/widgetRegistry.ts
  app/gui2/src/providers/widgetTree.ts
  app/gui2/src/providers/widgetUsageInfo.ts
  app/gui2/src/stores/graph/graphDatabase.ts
  app/gui2/src/stores/graph/index.ts
  app/gui2/src/stores/suggestionDatabase/index.ts
  app/gui2/src/stores/visualization/compilerMessaging.ts
  app/gui2/src/util/ast/abstract.ts
  app/gui2/src/util/ast/node.ts
  app/gui2/src/util/callTree.ts
  app/gui2/src/util/reactivity.ts
  app/gui2/src/util/visualizationBuiltins.ts
  app/gui2/stories/GraphNode.story.vue
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required, -gui2

#8620 Fix build of engine benchmarks
  build.sbt
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/ListBenchmarks.java
  engine/runtime/src/bench/resources/application-bench.conf
  project/JPMSPlugin.scala
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#8634 Update cache invalidation commands
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
Labels: CI: Ready to merge, CI: No changelog needed

#8638 Format Java sources in benchmark configuration
  build.sbt
  engine/runtime/src/bench/java/org/enso/interpreter/bench/BenchmarkItem.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/BenchmarksRunner.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/Report.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/ReportItem.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/ArrayProxyBenchmarks.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/CallableBenchmarks.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/EqualsBenchmarks.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/IfVsCaseBenchmarks.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/ListBenchmarks.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/NestedPatternCompilationBenchmarks.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/RecursionBenchmarks.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/SrcUtil.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/StringBenchmarks.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/TypePatternBenchmarks.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/VectorBenchmarks.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/WarningBenchmarks.java
Labels: CI: Ready to merge, CI: No changelog needed

#8637 Change null to Nothing
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#8635 Store Graph as a reference
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/PassPersistance.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/data/BindingsMap.scala
  engine/runtime-parser/src/main/java/org/enso/compiler/core/ir/IrPersistance.java
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/module/scope/Import.scala
  engine/runtime-parser/src/test/java/org/enso/compiler/core/IrPersistanceTest.java
  engine/runtime/src/main/java/org/enso/interpreter/caches/ModuleCache.java
  engine/runtime/src/test/java/org/enso/compiler/CompilerTest.java
  lib/java/persistance-dsl/src/main/java/org/enso/persist/impl/PersistableProcessor.java
  lib/java/persistance/src/main/java/org/enso/persist/PerGenerator.java
  lib/java/persistance/src/main/java/org/enso/persist/PerInputImpl.java
  lib/java/persistance/src/main/java/org/enso/persist/PerMap.java
  lib/java/persistance/src/main/java/org/enso/persist/Persistable.java
  lib/java/persistance/src/main/java/org/enso/persist/Persistance.java
Labels: CI: No changelog needed

#8636 Increase warmup for `EqualsBenchmarks`.
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/EqualsBenchmarks.java
Labels: CI: Ready to merge, CI: No changelog needed
