Repository enso-org/enso, pull requests merged in 2023-10, with the labels that each got.

#7939 [gui2] Removing nodes
  app/gui2/shared/yjsModel.ts
  app/gui2/src/components/TopBar.vue
  app/gui2/src/stores/graph.ts
Labels: CI: No changelog needed

#7893 [gui2] Shortcut manager + shortcuts for selecting nodes
  app/gui2/env.d.ts
  app/gui2/package.json
  app/gui2/public/visualizations/GeoMapVisualization.vue
  app/gui2/public/visualizations/ScatterplotVisualization.vue
  app/gui2/public/visualizations/dependencyTypesPatches.ts
  app/gui2/public/visualizations/events.ts
  app/gui2/public/visualizations/template.vue
  app/gui2/shared/yjsModel.ts
  app/gui2/src/assets/base.css
  app/gui2/src/bindings/nodeSelection.ts
  app/gui2/src/components/CircularMenu.vue
  app/gui2/src/components/CodeEditor.vue
  app/gui2/src/components/ExecutionModeSelector.vue
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphNode.vue
  app/gui2/src/components/NavBar.vue
  app/gui2/src/components/NavBreadcrumbs.vue
  app/gui2/src/components/NodeSpan.vue
  app/gui2/src/components/SelectionBrush.vue
  app/gui2/src/components/ToggleIcon.vue
  app/gui2/src/components/VisualizationContainer.vue
  app/gui2/src/components/VisualizationSelector.vue
  app/gui2/src/components/visualizations/HeatmapVisualization.vue
  app/gui2/src/components/visualizations/HistogramVisualization.vue
  app/gui2/src/components/visualizations/JSONVisualization.vue
  app/gui2/src/components/visualizations/TableVisualization.vue
  app/gui2/src/components/visualizations/WarningsVisualization.vue
  app/gui2/src/components/visualizations/dependencyTypesPatches.ts
  app/gui2/src/providers/useVisualizationConfig.ts
  app/gui2/src/stores/visualization.ts
  app/gui2/src/util/events.ts
  app/gui2/src/util/navigator.ts
  app/gui2/src/util/shortcuts.ts
  app/gui2/src/util/vec2.ts
  app/gui2/tsconfig.app.json
  app/gui2/vite.config.ts
  app/ide-desktop/lib/content/esbuild-config.ts
  app/ide-desktop/lib/dashboard/esbuild-config.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/config.ts
  app/ide-desktop/lib/types/globals.d.ts
  package-lock.json
Labels: CI: Ready to merge, CI: No changelog needed

#7918 Enable log-to-file configuration
  docs/infrastructure/logging.md
  engine/language-server/src/main/resources/application.conf
  engine/launcher/src/main/resources/application.conf
  lib/scala/logging-config/src/main/java/org/enso/logger/config/BaseConfig.java
  lib/scala/logging-config/src/main/java/org/enso/logger/config/ConsoleAppender.java
  lib/scala/logging-config/src/main/java/org/enso/logger/config/LogToFile.java
  lib/scala/logging-config/src/main/java/org/enso/logger/config/LoggingServer.java
  lib/scala/logging-config/src/main/java/org/enso/logger/config/LoggingServiceConfig.java
  lib/scala/logging-config/src/main/java/org/enso/logger/config/SentryAppender.java
  lib/scala/logging-service-logback/src/main/java/org/enso/logger/LogbackSetup.java
  lib/scala/logging-service/src/main/java/org/enso/logging/LoggingServiceManager.java
  lib/scala/project-manager/src/main/resources/application.conf
  tools/simple-library-server/package-lock.json
Labels: CI: No changelog needed

#7943 Avoid classloading deadlock by delaying computations of other passes
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/AmbiguousImportsAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/AutomaticParallelism.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/BindingAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/CachePreferenceAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DataflowAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DemandAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/GatherDiagnostics.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/ImportSymbolAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/TailCall.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/ComplexType.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/FunctionBinding.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/GenerateMethodBodies.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/Imports.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/LambdaShorthandToLambda.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/NestedPatternMatch.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/OperatorToFunction.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/SectionsToBinOp.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/lint/ModuleNameConflicts.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/lint/NoSelfInStatic.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/lint/ShadowedPatternFields.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/lint/UnusedBindings.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/optimise/ApplicationSaturation.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/optimise/LambdaConsolidate.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/optimise/UnreachableMatchBranches.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/DocumentationComments.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/ExpressionAnnotations.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/FullyAppliedFunctionUses.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/FullyQualifiedNames.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/GenericAnnotations.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/GlobalNames.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/IgnoredBindings.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/MethodCalls.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/MethodDefinitions.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/ModuleAnnotations.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/OverloadsResolution.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/Patterns.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/SuspendedArguments.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/TypeFunctions.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/TypeNames.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/TypeSignatures.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/PassesTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/core/ir/MetadataStorageTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/PassConfigurationTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#7859 Using conversions in a few places
  CHANGELOG.md
  distribution/lib/Standard/AWS/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Filter_Condition.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time_Formatter.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Day_Of_Week.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Day_Of_Week_From.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Of_Day.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Zone.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Time/Format/As_Java_Formatter_Interpreter.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Time/Format/Parser.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/HTTP_Method.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Header.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Request.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Request_Body.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Widget_Helpers.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Extensions/Table_Conversions.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Extensions/Upload_Database_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Extensions/Upload_In_Memory_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Aggregate_Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Data_Formatter.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table_Conversions.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Add_Row_Number.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Aggregate_Column_Helper.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Column_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Split_Tokenize.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
  test/Tests/src/Data/Json_Spec.enso
  test/Tests/src/Data/Time/Time_Zone_Spec.enso
  test/Tests/src/Network/Http_Spec.enso
Labels: CI: Ready to merge

#7885 Meta.Type.find a type by FQN
  distribution/lib/Standard/Base/0.0.0-dev/src/Meta.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/ProgramRootNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/FindTypeByFqnNode.java
  test/Tests/src/Semantic/Meta_Spec.enso
Labels: CI: No changelog needed

#7934 Avoid exponential growth of column names
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Connection/Entity_Naming_Properties.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Entity_Naming_Properties.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Entity_Naming_Properties.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Column_Naming_Helper.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Naming_Properties.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Missing_Values_Spec.enso
  test/Table_Tests/src/Database/Common/Names_Length_Limits_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#7961 Lint fix
  app/gui2/shared/languageServerTypes/suggestions.ts
  app/ide-desktop/lib/client/src/bin/server.ts
Labels: CI: Clean build required

#7832 New GUI/IDE build script support
  .github/workflows/gui.yml
  .github/workflows/release.yml
  .gitignore
  .prettierignore
  .vscode/settings.json
  app/gui2/package.json
  app/gui2/shared/yjsModel.ts
  app/gui2/src/main.ts
  app/gui2/src/stores/graph.ts
  app/gui2/ydoc-server/languageServerSession.ts
  app/ide-desktop/lib/client/electron-builder-config.ts
  app/ide-desktop/lib/client/src/bin/server.ts
  app/ide-desktop/lib/common/src/index.ts
  app/ide-desktop/lib/dashboard/src/authentication/package.json
  app/ide-desktop/lib/types/modules.d.ts
  build-config.yaml
  build/build/paths.yaml
  build/build/src/ci_gen.rs
  build/build/src/ci_gen/job.rs
  build/build/src/ide/web.rs
  build/build/src/lib.rs
  build/build/src/project.rs
  build/build/src/project/backend.rs
  build/build/src/project/gui.rs
  build/build/src/project/gui2.rs
  build/build/src/project/ide.rs
  build/build/src/project/ide2.rs
  build/build/src/project/runtime.rs
  build/build/src/project/wasm.rs
  build/build/src/source.rs
  build/build/src/web.rs
  build/ci-gen/src/main.rs
  build/ci_utils/src/program/command.rs
  build/cli/src/arg.rs
  build/cli/src/arg/gui2.rs
  build/cli/src/arg/ide.rs
  build/cli/src/arg/ide2.rs
  build/cli/src/lib.rs
  lib/rust/ensogl/pack/src/lib.rs
  package-lock.json
Labels: CI: No changelog needed, CI: Clean build required, -ci, -build-script

#7946 Fix `NumberParser` to avoid `thousandSeparator==decimalPoint` and prefer US decimal format
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Data_Formatter.enso
  std-bits/table/src/main/java/org/enso/table/parsing/NumberParser.java
  test/Table_Tests/src/Formatting/Data_Formatter_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#7956 Native image should not be tied a particular hardware
  project/NativeImage.scala
Labels: CI: No changelog needed, CI: Clean build required

#7965 Hotfix code editor focus
  app/gui2/src/components/CodeEditor.vue
Labels: CI: Ready to merge, CI: No changelog needed

#7969 Fix lint error when running `compile-server`
  app/gui2/shared/languageServerTypes/suggestions.ts
  app/gui2/tsconfig.server.json
  app/ide-desktop/lib/client/src/bin/server.ts
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#7952 Avoid unnecessary conversions in favor of direct match
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/argument/ReadArgumentCheckNode.java
  test/Tests/src/Semantic/Conversion_Spec.enso
Labels: CI: Ready to merge, CI: Keep up to date, CI: No changelog needed

#7840 Implement private modules
  CHANGELOG.md
  docs/semantics/README.md
  docs/semantics/encapsulation.md
  engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Module.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/ImportExport.scala
  engine/runtime-parser/src/test/java/org/enso/compiler/core/EnsoParserTest.java
  engine/runtime/src/main/java/org/enso/compiler/pass/analyse/PrivateModuleAnalysis.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/java/org/enso/interpreter/util/ScalaConversions.java
  engine/runtime/src/main/scala/org/enso/compiler/Passes.scala
  engine/runtime/src/test/resources/Test_Private_Modules_1/package.yaml
  engine/runtime/src/test/resources/Test_Private_Modules_1/src/Main.enso
  engine/runtime/src/test/resources/Test_Private_Modules_1/src/Priv_Mod.enso
  engine/runtime/src/test/resources/Test_Private_Modules_1/src/Pub_Mod.enso
  engine/runtime/src/test/resources/Test_Private_Modules_2/package.yaml
  engine/runtime/src/test/resources/Test_Private_Modules_2/src/Main.enso
  engine/runtime/src/test/resources/Test_Private_Modules_3/package.yaml
  engine/runtime/src/test/resources/Test_Private_Modules_3/src/Main.enso
  engine/runtime/src/test/resources/Test_Private_Modules_4/package.yaml
  engine/runtime/src/test/resources/Test_Private_Modules_4/src/Main.enso
  engine/runtime/src/test/resources/Test_Private_Modules_4/src/Sub/Priv_SubMod.enso
  engine/runtime/src/test/resources/Test_Private_Modules_4/src/Sub/Pub_SubMod.enso
  engine/runtime/src/test/resources/Test_Private_Modules_5/package.yaml
  engine/runtime/src/test/resources/Test_Private_Modules_5/src/Main.enso
  engine/runtime/src/test/resources/Test_Private_Modules_5/src/Sub.enso
  engine/runtime/src/test/resources/Test_Private_Modules_5/src/Sub/Priv.enso
  engine/runtime/src/test/scala/org/enso/compiler/test/CompilerTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/PassesTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/GatherDiagnosticsTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/semantic/ImportExportTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/ImportsTest.scala
  lib/rust/parser/debug/src/lib.rs
  lib/rust/parser/debug/tests/parse.rs
  lib/rust/parser/src/macros/built_in.rs
  lib/rust/parser/src/syntax/token.rs
  lib/rust/parser/src/syntax/tree.rs
Labels: CI: Ready to merge

#7968 [GUI2] Fix and add tests for delta format translation.
  app/gui2/eslint.config.js
  app/gui2/package.json
  app/gui2/src/components/CodeEditor.vue
  app/gui2/tsconfig.app.json
  app/gui2/tsconfig.app.vitest.json
  app/gui2/tsconfig.json
  app/gui2/tsconfig.node.json
  app/gui2/tsconfig.server.json
  app/gui2/tsconfig.server.vitest.json
  app/gui2/tsconfig.vitest.json
  app/gui2/ydoc-server/__tests__/edits.test.ts
  app/gui2/ydoc-server/edits.ts
  app/gui2/ydoc-server/languageServerSession.ts
  app/ide-desktop/lib/content/package.json
  app/ide-desktop/lib/dashboard/package.json
  app/ide-desktop/lib/types/tsconfig.json
  app/ide-desktop/package.json
  package-lock.json
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#7902 Add automatic generation of missing group colors
  app/gui2/package.json
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/util/colors.ts
  package-lock.json
Labels: CI: Ready to merge, CI: No changelog needed

#7951 Using ENSO_JAVA env variable to turn on the Espresso support
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/polyglot-api/src/main/java/org/enso/polyglot/RuntimeOptions.java
  engine/runner/src/main/scala/org/enso/runner/ContextFactory.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
Labels: CI: Ready to merge, CI: No changelog needed

#7929 Enable Enso asserts on CI
  build/build/src/enso.rs
  build/build/src/paths.rs
  test/Tests/src/Main.enso
  test/Tests/src/Runtime/Asserts_Spec.enso
Labels: CI: No changelog needed, CI: Clean build required

#7970 Removal of unused onExceptionalCallback
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/IdExecutionService.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionCallbacks.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java
Labels: CI: No changelog needed

#7844 Make the code editor editable again
  app/gui/view/src/code_editor.rs
  app/gui/view/src/project.rs
  lib/rust/ensogl/component/text/src/component/text.rs
Labels: CI: Ready to merge, CI: No changelog needed

#7974 Remove extra dot in error messages
  app/gui/controller/engine-protocol/src/binary/connection.rs
  app/gui/controller/engine-protocol/src/language_server/connection.rs
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#7980 Restore execution environment before the execution complete notification
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ExecuteJob.scala
  engine/runtime/src/main/java/org/enso/interpreter/EnsoLanguage.java
Labels: CI: Ready to merge, CI: No changelog needed

#7779 Create and edit nodes in temporary ast nodes with execution context disabled
  app/gui/controller/double-representation/src/graph.rs
  app/gui/src/controller/graph.rs
  app/gui/src/controller/searcher.rs
  app/gui/src/model/undo_redo.rs
  app/gui/src/presenter/graph.rs
  app/gui/src/presenter/graph/state.rs
  app/gui/src/presenter/searcher.rs
  app/gui/src/presenter/searcher/component_browser.rs
  app/gui/src/test.rs
  app/gui/view/graph-editor/src/component/node.rs
  app/gui/view/graph-editor/src/component/node/input/area.rs
  app/gui/view/graph-editor/src/component/node/input/widget.rs
Labels: CI: Ready to merge, CI: No changelog needed

#7953 Remove context locks from visualization commands
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/polyglot-api/src/main/java/org/enso/polyglot/RuntimeOptions.java
  engine/runner/src/main/scala/org/enso/runner/ContextFactory.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/AttachVisualizationCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/ContextCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/DetachVisualizationCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/ModifyVisualizationCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ExecuteJob.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Module.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/scala/org/enso/compiler/data/BindingsMap.scala
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#7948 Fix bundled GraalVM path
  build.sbt
  build/build/src/engine.rs
  build/build/src/engine/bundle.rs
  build/build/src/engine/context.rs
  build/build/src/lib.rs
  build/cli/src/lib.rs
  project/DistributionPackage.scala
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#7998 Cache filtered children in XML
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/XML.enso
Labels: CI: Ready to merge, CI: No changelog needed

#7873 [gui2] Language Server binary protocol, and loading of visualization data
  app/gui2/.gitignore
  app/gui2/.vscode/settings.json
  app/gui2/env.d.ts
  app/gui2/eslint.config.js
  app/gui2/node.env.d.ts
  app/gui2/package.json
  app/gui2/public/visualizations/ScatterplotVisualization.vue
  app/gui2/public/visualizations/template.vue
  app/gui2/shared/binaryProtocol.ts
  app/gui2/shared/dataServer.ts
  app/gui2/shared/events.ts
  app/gui2/shared/languageServer.ts
  app/gui2/shared/languageServerTypes.ts
  app/gui2/shared/websocket.ts
  app/gui2/shared/yjsModel.ts
  app/gui2/src/assets/icons.svg
  app/gui2/src/bindings/index.ts
  app/gui2/src/components/CircularMenu.vue
  app/gui2/src/components/CodeEditor.vue
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphNode.vue
  app/gui2/src/components/ProjectTitle.vue
  app/gui2/src/components/VisualizationContainer.vue
  app/gui2/src/components/VisualizationSelector.vue
  app/gui2/src/components/visualizations/HeatmapVisualization.vue
  app/gui2/src/components/visualizations/HistogramVisualization.vue
  app/gui2/src/components/visualizations/ImageBase64Visualization.vue
  app/gui2/src/components/visualizations/JSONVisualization.vue
  app/gui2/src/components/visualizations/LoadingVisualization.vue
  app/gui2/src/components/visualizations/SQLVisualization.vue
  app/gui2/src/components/visualizations/TableVisualization.vue
  app/gui2/src/components/visualizations/WarningsVisualization.vue
  app/gui2/src/createApp.ts
  app/gui2/src/main.ts
  app/gui2/src/providers/visualizationConfig.ts
  app/gui2/src/stores/graph.ts
  app/gui2/src/stores/project.ts
  app/gui2/src/stores/suggestionDatabase/index.ts
  app/gui2/src/stores/visualization.ts
  app/gui2/src/util/codemirror.ts
  app/gui2/src/util/crdt.ts
  app/gui2/src/util/events.ts
  app/gui2/src/util/navigator.ts
  app/gui2/src/util/net.ts
  app/gui2/src/util/result.ts
  app/gui2/src/util/shortcuts.ts
  app/gui2/tsconfig.node.json
  app/gui2/vite.config.ts
  app/gui2/ydoc-server/__tests__/edits.test.ts
  app/gui2/ydoc-server/edits.ts
  app/gui2/ydoc-server/fileFormat.ts
  app/gui2/ydoc-server/languageServerSession.ts
  app/gui2/ydoc-server/ydoc.ts
  package-lock.json
Labels: CI: Ready to merge, CI: No changelog needed

#7982 Add functionality to handle Expression Updates to GUI2
  app/gui2/shared/dataServer.ts
  app/gui2/shared/languageServer.ts
  app/gui2/shared/languageServerTypes.ts
  app/gui2/shared/yjsModel.ts
  app/gui2/src/bindings/index.ts
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphNode.vue
  app/gui2/src/components/NodeSpan.vue
  app/gui2/src/stores/graph.ts
  app/gui2/src/stores/project.ts
  app/gui2/src/util/computedValueRegistry.ts
  app/gui2/src/util/visualizationDataRegistry.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#7986 Read groups from LS
  app/gui2/shared/languageServer.ts
  app/gui2/shared/languageServerTypes.ts
  app/gui2/src/stores/suggestionDatabase/index.ts
  app/gui2/src/util/colors.ts
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required, -gui2

#7975 Make engine version optional
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/backend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/editor.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/localBackend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/projectManager.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/remoteBackend.ts
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#7960 Exporting non-existing symbols fails with compiler error
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/ImportExport.scala
  engine/runtime/src/main/java/org/enso/compiler/pass/analyse/ExportSymbolAnalysis.java
  engine/runtime/src/main/java/org/enso/compiler/pass/analyse/PrivateModuleAnalysis.java
  engine/runtime/src/main/scala/org/enso/compiler/Passes.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/PassesTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/semantic/ImportExportTest.scala
Labels: CI: Ready to merge, CI: Clean build required

#8003 Fix Language Server documentation
  docs/language-server/protocol-language-server.md
Labels: CI: Ready to merge, CI: No changelog needed

#8012 Fix opening projects with arbitrary name
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/editor.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/localBackend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/projectManager.ts
Labels: CI: Ready to merge, CI: No changelog needed

#7833 Instrumenter to observe behavior of nodes with UUID
  .gitattributes
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Meta.enso
  engine/polyglot-api/src/main/java/org/enso/polyglot/debugger/IdExecutionService.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/IdExecutionService.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/RuntimeCache.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionCallbacks.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java
  engine/runtime-instrument-runtime-server/src/main/java/org/enso/interpreter/instrument/RuntimeServerInstrument.java
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Module.scala
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/FunctionCallInstrumentationNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/dispatch/InvokeFunctionNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/Instrumentor.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/InstrumentorBuiltin.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/Function.java
  engine/runtime/src/main/scala/org/enso/compiler/data/BindingsMap.scala
  lib/scala/cli/src/test/scala/org/enso/cli/ApplicationSpec.scala
  lib/scala/cli/src/test/scala/org/enso/cli/CLIOutputSpec.scala
  test/Tests/src/Main.enso
  test/Tests/src/Semantic/Instrumentor_Spec.enso
Labels: CI: Ready to merge, CI: Clean build required

#7979 Implement `Table.lookup_and_replace` for in-memory
  CHANGELOG.md
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Extensions/Upload_Database_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Extensions/Upload_In_Memory_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Lookup_Helpers.enso
  std-bits/table/src/main/java/org/enso/table/data/index/MultiValueIndex.java
  std-bits/table/src/main/java/org/enso/table/data/index/MultiValueKeyBase.java
  std-bits/table/src/main/java/org/enso/table/data/index/UnorderedMultiValueKey.java
  std-bits/table/src/main/java/org/enso/table/data/table/join/LookupColumnDescription.java
  std-bits/table/src/main/java/org/enso/table/data/table/join/LookupJoin.java
  std-bits/table/src/main/java/org/enso/table/error/NonUniqueLookupKey.java
  std-bits/table/src/main/java/org/enso/table/error/NullValuesInKeyColumns.java
  std-bits/table/src/main/java/org/enso/table/error/UnmatchedRow.java
  test/Table_Tests/src/Common_Table_Operations/Join/Lookup_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Main.enso
  test/Table_Tests/src/Database/Upload_Spec.enso
Labels: CI: Ready to merge

#8007 Fix a DROP table bug, add SQL debug logging
  distribution/lib/Standard/AWS/0.0.0-dev/src/Database/Redshift/Internal/Redshift_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/JDBC_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload_Table.enso
  test/Table_Tests/src/Database/Upload_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#8013 Eliminate line feeds from `XML.outer_xml` on Windows
  std-bits/base/src/main/java/org/enso/base/XML_Utils.java
  test/Tests/src/Data/XML/XML_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#8018 Check asset name uniqueness
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetsTable.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/directoryNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/editableSpan.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectNameColumn.tsx
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#8014 Define and enforce locking order during runtime
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/SynchronousCommand.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/ReentrantLocking.scala
Labels: CI: No changelog needed, -compiler, -language-server

#8010 Add tests for Table.from_objects and Table.expand_column.
  test/Table_Tests/src/Common_Table_Operations/Conversion_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Conversion_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#8016 Runtime checks of signatures with polyglot java classes
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/argument/ReadArgumentCheckNode.java
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  engine/runtime/src/test/java/org/enso/interpreter/test/SignaturePolyglotTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java
  test/Tests/src/Semantic/Conversion_Spec.enso
Labels: CI: No changelog needed

#7988 Node icons and colors
  app/gui2/src/assets/icons.svg
  app/gui2/src/bindings.ts
  app/gui2/src/components/ExecutionModeSelector.vue
  app/gui2/src/components/GraphNode.vue
  app/gui2/src/stores/graph.ts
  app/gui2/src/util/colors.ts
  app/gui2/src/util/getIconName.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#8004 Filter visualization types based on node type
  app/gui2/src/components/GraphNode.vue
  app/gui2/src/components/VisualizationSelector.vue
  app/gui2/src/providers/visualizationConfig.ts
  app/gui2/src/stores/visualization.ts
  app/gui2/src/util/mutable.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#8023 Remove incorrect dependencies in the root `package.json`
  package-lock.json
  package.json
Labels: CI: Ready to merge, CI: No changelog needed

#8028 [GUI2] use DataView directly in generated parser code
  app/gui2/parser-codegen/codegen.ts
  app/gui2/parser-codegen/serialization.ts
  app/gui2/parser-codegen/util.ts
  app/gui2/src/util/ast.ts
  app/gui2/src/util/parserSupport.ts
Labels: CI: Ready to merge, CI: No changelog needed

#8020 Restructure `Table.from_objects` to use conversions
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Extensions/Table_Conversions.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Conversions/Convertible_To_Columns.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Conversions/Convertible_To_Rows.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table_Conversions.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Expand_Objects_Helpers.enso
  std-bits/table/src/main/java/org/enso/table/data/column/builder/Builder.java
  test/Table_Tests/src/Common_Table_Operations/Conversion_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Conversion_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#8026 Fix warnings in SBT build
  project/BuildInfo.scala
  project/LibraryManifestGenerator.scala
  project/plugins.sbt
Labels: CI: Ready to merge, CI: No changelog needed

#8027 Remove dependency on jdk.compiler from builtin method processor
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/builtins/ExecuteMethodImplGenerator.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/builtins/MethodGenerator.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/builtins/SafeWrapException.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/builtins/SpecializedMethodsGenerator.java
Labels: CI: No changelog needed, CI: Clean build required

#8022 Interpreting CB input using AST.
  app/gui2/parser-codegen/codegen.ts
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/components/ComponentBrowser/input.ts
  app/gui2/src/util/ast.ts
  app/gui2/src/util/ast/__snapshots__/index.ts.snap
  app/gui2/src/util/ast/index.ts
  app/gui2/src/util/ast/opr.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#8034 Minor improvements from last couple of Book Clubs
  distribution/lib/Standard/Base/0.0.0-dev/src/Any.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Map.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Workbook.enso
  test/Tests/src/Data/Map_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#8031 Fixed node icons and colors, derived from suggestions DB groups
  app/gui2/src/components/GraphNode.vue
  app/gui2/src/stores/suggestionDatabase/index.ts
  app/gui2/src/stores/visualization.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#8044 Avoid Null receiver values are not supported by libraries
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionCallbacks.java
Labels: CI: No changelog needed

#8005 Expand capabilities of `Table.set` and better dropdown support,
  CHANGELOG.md
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Calculations/Column_Operation.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column_Ref.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Extensions/Table_Conversions.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Extensions/Table_Ref.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Constant_Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Test.enso
  test/Table_Tests/src/Common_Table_Operations/Core_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Date_Time_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Derived_Columns_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Filter_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Main.enso
  test/Table_Tests/src/IO/Delimited_Read_Spec.enso
  test/Table_Tests/src/IO/Json_Spec.enso
  test/Table_Tests/src/In_Memory/Parse_To_Table_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Conversion_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Date_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Date_Time_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Time_Of_Day_Spec.enso
Labels: CI: Ready to merge

#8053 Use US locale for Date/Time parsing by default.
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time_Formatter.enso
  test/Table_Tests/src/IO/Delimited_Write_Spec.enso
  test/Table_Tests/src/In_Memory/Column_Format_Spec.enso
  test/Tests/src/Data/Text/Parse_Spec.enso
  test/Tests/src/Data/Time/Date_Spec.enso
  test/Tests/src/Data/Time/Date_Time_Formatter_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#8042 Add Table.expand_to_rows to allow flattening vector and array values in table
  CHANGELOG.md
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Conversions/Convertible_To_Rows.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Extensions/Table_Conversions.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Expand_Objects_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Fan_Out.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Split_Tokenize.enso
  std-bits/table/src/main/java/org/enso/table/data/column/builder/InferredBuilder.java
  test/Table_Tests/src/Common_Table_Operations/Conversion_Spec.enso
  test/Table_Tests/src/In_Memory/Builders_Spec.enso
  test/Table_Tests/src/In_Memory/Fan_Out_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Conversion_Spec.enso
Labels: CI: Ready to merge, CI: Clean build required

#8051 Icon and documentation for Enso VSCode extension
  .vscode/extensions.json
  tools/enso4igv/.gitignore
  tools/enso4igv/IGV.md
  tools/enso4igv/README.md
  tools/enso4igv/package.json
  tools/enso4igv/pom.xml
  tools/enso4igv/vscode.md
Labels: CI: Ready to merge, CI: No changelog needed

#8056 Suppress futile visualization warnings
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
Labels: CI: Ready to merge, CI: No changelog needed

#7809 Reduce extra output in compilation and tests
  build.sbt
  distribution/engine/THIRD-PARTY/NOTICE
  distribution/engine/THIRD-PARTY/org.slf4j.slf4j-api-1.7.36/NOTICES
  distribution/engine/THIRD-PARTY/org.slf4j.slf4j-api-2.0.9/NOTICES
  distribution/launcher/THIRD-PARTY/NOTICE
  distribution/launcher/THIRD-PARTY/org.slf4j.slf4j-api-1.7.36/NOTICES
  distribution/launcher/THIRD-PARTY/org.slf4j.slf4j-api-2.0.9/NOTICES
  distribution/project-manager/THIRD-PARTY/NOTICE
  distribution/project-manager/THIRD-PARTY/org.slf4j.slf4j-api-1.7.36/NOTICES
  distribution/project-manager/THIRD-PARTY/org.slf4j.slf4j-api-2.0.9/NOTICES
  engine/language-server/src/test/scala/org/enso/languageserver/search/SuggestionsHandlerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/LibrariesTest.scala
  engine/runtime-with-instruments/src/test/resources/application.conf
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeErrorsTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime-with-polyglot/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
  engine/runtime/src/test/java/org/enso/compiler/SerdeCompilerTest.java
  lib/scala/edition-updater/src/test/scala/org/enso/editions/updater/UpdatingEditionProviderTest.scala
  lib/scala/library-manager-test/src/main/scala/org/enso/librarymanager/published/repository/DummyRepository.scala
  lib/scala/library-manager-test/src/main/scala/org/enso/librarymanager/published/repository/EmptyRepository.scala
  lib/scala/library-manager-test/src/main/scala/org/enso/librarymanager/published/repository/ExampleRepository.scala
  lib/scala/library-manager-test/src/test/scala/org/enso/librarymanager/published/repository/LibraryDownloadTest.scala
  lib/scala/library-manager-test/src/test/scala/org/enso/libraryupload/LibraryUploadTest.scala
  lib/scala/logging-config/src/main/java/org/enso/logger/config/LoggingServiceConfig.java
  lib/scala/logging-service-logback/src/main/java/org/enso/logger/LogbackSetup.java
  lib/scala/logging-service-logback/src/test/java/org/enso/logger/TestLogProvider.java
  lib/scala/logging-truffle-connector/src/main/java/org/enso/truffleloggerwrapper/TruffleLoggerWrapperProvider.java
  lib/scala/logging-truffle-connector/src/main/java/org/slf4j/impl/StaticLoggerBinder.java
  lib/scala/logging-truffle-connector/src/main/java/org/slf4j/impl/StaticMDCBinder.java
  lib/scala/logging-truffle-connector/src/main/java/org/slf4j/impl/StaticMarkerBinder.java
  lib/scala/logging-utils/src/test/scala/org/enso/logger/TestLogger.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerSupervisorSpec.scala
  tools/legal-review/engine/com.lihaoyi.sourcecode_2.13-0.3.0/files-keep
  tools/legal-review/engine/org.slf4j.slf4j-api-1.7.36/copyright-keep
  tools/legal-review/engine/org.slf4j.slf4j-api-2.0.9/copyright-keep
  tools/legal-review/engine/org.slf4j.slf4j-api-2.0.9/files-ignore
  tools/legal-review/engine/org.slf4j.slf4j-api-2.0.9/files-keep
  tools/legal-review/engine/report-state
  tools/legal-review/launcher/org.slf4j.slf4j-api-1.7.36/copyright-keep-context
  tools/legal-review/launcher/org.slf4j.slf4j-api-2.0.9/copyright-keep
  tools/legal-review/launcher/org.slf4j.slf4j-api-2.0.9/files-ignore
  tools/legal-review/launcher/org.slf4j.slf4j-api-2.0.9/files-keep
  tools/legal-review/launcher/report-state
  tools/legal-review/project-manager/org.slf4j.slf4j-api-1.7.36/copyright-keep-context
  tools/legal-review/project-manager/org.slf4j.slf4j-api-2.0.9/copyright-keep
  tools/legal-review/project-manager/org.slf4j.slf4j-api-2.0.9/files-ignore
  tools/legal-review/project-manager/org.slf4j.slf4j-api-2.0.9/files-keep
  tools/legal-review/project-manager/report-state
Labels: CI: No changelog needed

#7987 Drag and drop
  app/ide-desktop/lib/assets/paste.svg
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/backend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetRow.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetsTable.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/autocomplete.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/categorySwitcher.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/confirmDeleteModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/connectorNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/contextMenu.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/directoryNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dragModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/drive.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/driveBar.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/fileNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/globalContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/managePermissionsModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/newDataConnectorModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/permissionTypeSelector.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectIcon.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/samples.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/table.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/events/assetEvent.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/events/assetListEvent.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/localBackend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/remoteBackend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/remoteBackendPaths.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/shortcuts.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/visibility.ts
  app/ide-desktop/lib/dashboard/test-e2e/driveView.spec.ts-snapshots/drive-view-3-linux.png
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#8059 CI improvements / IDE2 releasing
  .github/workflows/gui.yml
  .github/workflows/release.yml
  build/build/src/ci_gen.rs
  build/build/src/engine.rs
  build/build/src/engine/bundle.rs
  build/build/src/engine/context.rs
  build/build/src/release.rs
  build/ci_utils/src/actions/workflow/definition.rs
  build/ci_utils/src/github/release.rs
  build/ci_utils/src/programs/docker.rs
  build/cli/src/arg.rs
  build/cli/src/arg/ide.rs
  build/cli/src/arg/ide2.rs
  build/cli/src/lib.rs
  lib/rust/metamodel/src/java/from_meta.rs
  lib/rust/metamodel/src/java/mod.rs
  lib/rust/parser/debug/src/bin/binary_ast.rs
  lib/rust/parser/debug/src/bin/json_ast.rs
  lib/rust/parser/schema/src/main.rs
  lib/rust/parser/src/format.rs
  lib/rust/parser/src/lib.rs
Labels: CI: No changelog needed, CI: Clean build required

#8052 ReactiveDb and ReactiveIndex
  app/gui2/src/components/GraphNode.vue
  app/gui2/src/stores/suggestionDatabase/__tests__/lsUpdate.test.ts
  app/gui2/src/stores/suggestionDatabase/entry.ts
  app/gui2/src/stores/suggestionDatabase/index.ts
  app/gui2/src/util/database/__tests__/reactiveDb.test.ts
  app/gui2/src/util/database/reactiveDb.ts
  app/gui2/src/util/reactivity.ts
Labels: CI: Ready to merge, CI: No changelog needed

#8061 Avoid null values in constant node
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/constant/ConstantObjectNode.java
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  engine/runtime/src/test/java/org/enso/compiler/ExecCompilerTest.java
Labels: CI: Ready to merge, CI: No changelog needed

#8074 Avoid relative imports whenever possible
  app/gui2/parser-codegen/serialization.ts
  app/gui2/shared/events.ts
  app/gui2/src/components/CodeEditor.vue
  app/gui2/src/components/ComponentBrowser/__tests__/component.test.ts
  app/gui2/src/components/ComponentBrowser/__tests__/filtering.test.ts
  app/gui2/src/components/ComponentBrowser/component.ts
  app/gui2/src/components/ComponentBrowser/input.ts
  app/gui2/src/components/ExecutionModeSelector.vue
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphNode.vue
  app/gui2/src/components/SelectionBrush.vue
  app/gui2/src/components/VisualizationContainer.vue
  app/gui2/src/components/visualizations/HistogramVisualization.vue
  app/gui2/src/components/visualizations/SQLVisualization.vue
  app/gui2/src/components/visualizations/events.ts
  app/gui2/src/createApp.ts
  app/gui2/src/stores/graph.ts
  app/gui2/src/stores/suggestionDatabase/__tests__/lsUpdate.test.ts
  app/gui2/src/stores/suggestionDatabase/entry.ts
  app/gui2/src/stores/suggestionDatabase/index.ts
  app/gui2/src/stores/suggestionDatabase/lsUpdate.ts
  app/gui2/src/util/ast/index.ts
  app/gui2/src/util/ast/opr.ts
  app/gui2/src/util/compare.ts
  app/gui2/src/util/computedValueRegistry.ts
  app/gui2/src/util/database/__tests__/reactiveDb.test.ts
  app/gui2/src/util/docParser.ts
  app/gui2/src/util/events.ts
  app/gui2/src/util/ffi.ts
  app/gui2/src/util/measurement.ts
  app/gui2/src/util/navigator.ts
  app/gui2/src/util/net.ts
  app/gui2/src/util/parserSupport.ts
  app/gui2/src/util/qualifiedName.ts
  app/gui2/src/util/shortcuts.ts
  app/gui2/src/util/visualizationDataRegistry.ts
  app/gui2/src/views/ProjectView.vue
  app/gui2/vite.config.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#8060 Bump third-party CI actions
  .github/workflows/changelog.yml
  .github/workflows/engine-benchmark.yml
  .github/workflows/gui.yml
  .github/workflows/promote.yml
  .github/workflows/release.yml
  .github/workflows/scala-new.yml
  .github/workflows/shader-tools.yml
  .github/workflows/std-libs-benchmark.yml
  build/ci_utils/src/actions/workflow/definition.rs
Labels: CI: No changelog needed, CI: Clean build required

#8076 Improve performance of `add_row_number`
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Add_Row_Number.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Bench.enso
  std-bits/base/src/main/java/org/enso/base/ObjectComparator.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/LongRangeStorage.java
  std-bits/table/src/main/java/org/enso/table/data/index/MultiValueIndex.java
  std-bits/table/src/main/java/org/enso/table/data/index/MultiValueKeyBase.java
  std-bits/table/src/main/java/org/enso/table/operations/AddRowNumber.java
  std-bits/table/src/main/java/org/enso/table/operations/Distinct.java
  test/Benchmarks/src/Main.enso
  test/Benchmarks/src/Table/Add_Row_Number.enso
  test/Table_Tests/src/Common_Table_Operations/Add_Row_Number_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#8008 Labels
  app/ide-desktop/lib/assets/plus.svg
  app/ide-desktop/lib/assets/plus2.svg
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/backend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/column.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetRow.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetsTable.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/colorPicker.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/connectorNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/directoryNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/drive.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/fileNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/label.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/labels.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/manageLabelsModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/managePermissionsModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/newLabelModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectIcon.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/events/assetEvent.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/identity.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/localBackend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/remoteBackend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/remoteBackendPaths.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/hooks.tsx
  app/ide-desktop/lib/dashboard/tailwind.config.ts
  app/ide-desktop/lib/dashboard/test-e2e/actions.ts
  app/ide-desktop/lib/dashboard/test-e2e/api.ts
  app/ide-desktop/lib/dashboard/test-e2e/changePasswordModal.spec.ts-snapshots/change-password-modal-1-darwin.png
  app/ide-desktop/lib/dashboard/test-e2e/changePasswordModal.spec.ts-snapshots/change-password-modal-1-linux.png
  app/ide-desktop/lib/dashboard/test-e2e/driveView.spec.ts-snapshots/drive-view-1-darwin.png
  app/ide-desktop/lib/dashboard/test-e2e/driveView.spec.ts-snapshots/drive-view-1-linux.png
  app/ide-desktop/lib/dashboard/test-e2e/driveView.spec.ts-snapshots/drive-view-3-darwin.png
  app/ide-desktop/lib/dashboard/test-e2e/labelsPanel.spec.ts
  app/ide-desktop/lib/dashboard/test-e2e/labelsPanel.spec.ts-snapshots/labels-1-darwin.png
  app/ide-desktop/lib/dashboard/test-e2e/labelsPanel.spec.ts-snapshots/labels-1-linux.png
  app/ide-desktop/lib/dashboard/test-e2e/labelsPanel.spec.ts-snapshots/labels-2-darwin.png
  app/ide-desktop/lib/dashboard/test-e2e/labelsPanel.spec.ts-snapshots/labels-2-linux.png
  app/ide-desktop/lib/dashboard/test-e2e/labelsPanel.spec.ts-snapshots/labels-3-darwin.png
  app/ide-desktop/lib/dashboard/test-e2e/labelsPanel.spec.ts-snapshots/labels-3-linux.png
  app/ide-desktop/lib/dashboard/test-e2e/labelsPanel.spec.ts-snapshots/labels-4-darwin.png
  app/ide-desktop/lib/dashboard/test-e2e/labelsPanel.spec.ts-snapshots/labels-4-linux.png
  app/ide-desktop/lib/dashboard/test-e2e/labelsPanel.spec.ts-snapshots/labels-5-darwin.png
  app/ide-desktop/lib/dashboard/test-e2e/labelsPanel.spec.ts-snapshots/labels-5-linux.png
  app/ide-desktop/lib/dashboard/test-e2e/labelsPanel.spec.ts-snapshots/labels-6-darwin.png
  app/ide-desktop/lib/dashboard/test-e2e/labelsPanel.spec.ts-snapshots/labels-6-linux.png
  app/ide-desktop/lib/dashboard/test-e2e/labelsPanel.spec.ts-snapshots/labels-7-darwin.png
  app/ide-desktop/lib/dashboard/test-e2e/labelsPanel.spec.ts-snapshots/labels-7-linux.png
  app/ide-desktop/lib/dashboard/test-e2e/loginLogout.spec.ts-snapshots/login-and-logout-1-darwin.png
  app/ide-desktop/lib/dashboard/test-e2e/loginLogout.spec.ts-snapshots/login-and-logout-1-linux.png
  app/ide-desktop/lib/dashboard/test-e2e/signUpFlow.spec.ts-snapshots/sign-up-flow-3-darwin.png
  app/ide-desktop/lib/dashboard/test-e2e/signUpFlow.spec.ts-snapshots/sign-up-flow-3-linux.png
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#8078 Fix issue with circular import
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetRow.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetsTable.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/categorySwitcher.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/drag.ts
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#8080 Eliminate VCS TimeoutExceptions on startup
  .gitattributes
  build.sbt
  distribution/engine/THIRD-PARTY/NOTICE
  distribution/engine/THIRD-PARTY/com.googlecode.javaewah.JavaEWAH-1.2.3/NOTICES
  distribution/engine/THIRD-PARTY/commons-codec.commons-codec-1.16.0/NOTICES
  distribution/engine/THIRD-PARTY/org.eclipse.jgit.org.eclipse.jgit-6.7.0.202309050840-r/NOTICES
  engine/language-server/src/main/scala/org/enso/languageserver/vcsmanager/Git.scala
  engine/language-server/src/test/scala/org/enso/languageserver/vcsmanager/GitSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/VcsManagerTest.scala
  tools/legal-review/engine/com.googlecode.javaewah.JavaEWAH-1.2.3/copyright-keep
  tools/legal-review/engine/commons-codec.commons-codec-1.16.0/copyright-add
  tools/legal-review/engine/org.eclipse.jgit.org.eclipse.jgit-6.3.0.202209071007-r/copyright-ignore
  tools/legal-review/engine/org.eclipse.jgit.org.eclipse.jgit-6.3.0.202209071007-r/copyright-keep-context
  tools/legal-review/engine/org.eclipse.jgit.org.eclipse.jgit-6.7.0.202309050840-r/copyright-keep
  tools/legal-review/engine/org.eclipse.jgit.org.eclipse.jgit-6.7.0.202309050840-r/copyright-keep-context
  tools/legal-review/engine/report-state
  tools/legal-review/engine/reviewed-licenses/Apache_License_v2.0
Labels: CI: Ready to merge, CI: No changelog needed

#8087 Disable remote logging
  app/ide-desktop/lib/content/src/index.ts
Labels: CI: Ready to merge, CI: No changelog needed

#8095 Snap CB position to pixel boundary
  app/gui2/package.json
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/util/navigator.ts
  package-lock.json
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#8091 Add benchmarks related to `add_row_number` performance investigation
  build.sbt
  distribution/lib/Standard/Test/0.0.0-dev/src/Bench.enso
  std-bits/table/src/main/java/org/enso/table/data/index/OrderedMultiValueKey.java
  test/Benchmarks/polyglot-sources/benchmark-java-helpers/src/main/java/org/enso/benchmark_helpers/JavaHashMapWrapper.java
  test/Benchmarks/src/Main.enso
  test/Benchmarks/src/Map/Hash_Map.enso
  test/Benchmarks/src/Table/Internal/Multi_Value_Key.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#8101 Review places where we can use `Column_Ref`
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Replace_Params.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Missing_Values_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#8093 Ambiguous imports warnings/errors are serializable
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Diagnostic.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Empty.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Warning.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/Error.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Conversion.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/ImportExport.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Pattern.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Redefined.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Resolution.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Syntax.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Unexpected.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/warnings/Shadowed.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/warnings/Unreachable.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/warnings/Unused.scala
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/AmbiguousImportsAnalysis.scala
  engine/runtime/src/test/java/org/enso/compiler/ErrorCompilerTest.java
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/GatherDiagnosticsTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/semantic/ImportExportTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#8083 Restructuring XML into Table form
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Conversions/Convertible_To_Columns.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Extensions/Prefix_Name.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Expand_Objects_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Main.enso
  test/Table_Tests/data/xml/library.xml
  test/Table_Tests/src/In_Memory/Table_Conversion_Spec.enso
Labels: CI: Ready to merge, CI: Clean build required

#8096 Tree traversal API
  app/gui2/eslint.config.js
  app/gui2/parser-codegen/codegen.ts
  app/gui2/parser-codegen/serialization.ts
  app/gui2/src/components/ComponentBrowser/input.ts
  app/gui2/src/util/ast/index.ts
  app/gui2/src/util/parserSupport.ts
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required, -gui2

#8099 Fix
  app/gui2/src/stores/suggestionDatabase/__tests__/lsUpdate.test.ts
  app/gui2/src/stores/suggestionDatabase/lsUpdate.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#8039 Ensure all spans have document offsets
  app/gui2/src/util/ast/__snapshots__/index.ts.snap
  app/gui2/src/util/ast/index.ts
  app/gui2/src/util/ast/opr.ts
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/XML.enso
  engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/JsInteropTest.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/NestedPatternCompilationBenchmarks.java
  lib/rust/parser/debug/src/lib.rs
  lib/rust/parser/debug/src/main.rs
  lib/rust/parser/debug/tests/metadata/mod.rs
  lib/rust/parser/debug/tests/parse.rs
  lib/rust/parser/src/lexer.rs
  lib/rust/parser/src/lib.rs
  lib/rust/parser/src/macros/built_in.rs
  lib/rust/parser/src/macros/resolver.rs
  lib/rust/parser/src/source/code.rs
  lib/rust/parser/src/source/span.rs
  lib/rust/parser/src/syntax/operator.rs
  lib/rust/parser/src/syntax/token.rs
  lib/rust/parser/src/syntax/tree.rs
  lib/rust/parser/src/syntax/tree/block.rs
Labels: CI: Ready to merge, CI: No changelog needed, -parser

#8107 More debug info for failed edits
  engine/runtime-instrument-common/src/test/scala/org/enso/compiler/test/context/ChangesetBuilderTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/service/error/FailedToApplyEditsException.java
Labels: CI: Ready to merge, CI: No changelog needed

#8098 Highlight matches in CB
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/components/ComponentBrowser/__tests__/component.test.ts
  app/gui2/src/components/ComponentBrowser/__tests__/filtering.test.ts
  app/gui2/src/components/ComponentBrowser/component.ts
  app/gui2/src/components/ComponentBrowser/filtering.ts
  app/gui2/src/util/database/__tests__/reactiveDb.test.ts
  app/gui2/src/util/qualifiedName.ts
  app/gui2/src/util/range.ts
  app/gui2/vitest.config.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#8106 Remove flaky screenshot for labels VRT
  app/ide-desktop/lib/dashboard/test-e2e/labelsPanel.spec.ts
  app/ide-desktop/lib/dashboard/test-e2e/labelsPanel.spec.ts-snapshots/labels-6-darwin.png
  app/ide-desktop/lib/dashboard/test-e2e/labelsPanel.spec.ts-snapshots/labels-6-linux.png
  app/ide-desktop/lib/dashboard/test-e2e/labelsPanel.spec.ts-snapshots/labels-7-darwin.png
  app/ide-desktop/lib/dashboard/test-e2e/labelsPanel.spec.ts-snapshots/labels-7-linux.png
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#8115 Report human-readable names for shadowed parameters
  engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Name.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/warnings/Shadowed.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/FreshNameSupply.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/AutomaticParallelism.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/BindingAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/ComplexType.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/NestedPatternMatch.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/lint/UnusedBindings.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/optimise/LambdaConsolidate.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/FullyQualifiedNames.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/IgnoredBindings.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/MethodDefinitions.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/SuspendedArguments.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/lint/ShadowedPatternFieldsTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/lint/UnusedBindingsTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/optimise/LambdaConsolidateTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#8036 Applying suggestions in the Component Browser
  app/gui2/src/bindings.ts
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/components/ComponentBrowser/__tests__/input.test.ts
  app/gui2/src/components/ComponentBrowser/input.ts
  app/gui2/src/util/ast/index.ts
  app/gui2/src/util/qualifiedName.ts
  app/gui2/src/util/shortcuts.ts
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required, -gui2

#8105 Support `Previous_Value` in `fill_nothing` and `fill_missing`
  CHANGELOG.md
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Constants.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Main.enso
  std-bits/table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/MixedStorageFacade.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/SpecializedStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/Storage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/AbstractLongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/DoubleStorage.java
  test/Table_Tests/src/Common_Table_Operations/Missing_Values_Spec.enso
  test/Tests/polyglot-sources/enso-test-java-helpers/src/main/java/org/enso/table_test_helpers/ExplodingStorage.java
Labels: CI: Ready to merge, CI: Clean build required

#8121 Move `Rect` to `util/`
  app/gui2/src/components/GraphEdge.vue
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphNode.vue
  app/gui2/src/components/NodeSpan.vue
  app/gui2/src/util/navigator.ts
  app/gui2/src/util/rect.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#8116 Initialize suggestions database only once
  engine/language-server/src/main/java/org/enso/languageserver/boot/resource/AsyncResourcesInitialization.java
  engine/language-server/src/main/java/org/enso/languageserver/boot/resource/BlockingInitialization.java
  engine/language-server/src/main/java/org/enso/languageserver/boot/resource/DirectoriesInitialization.java
  engine/language-server/src/main/java/org/enso/languageserver/boot/resource/InitializationComponent.java
  engine/language-server/src/main/java/org/enso/languageserver/boot/resource/InitializationComponentInitialized.java
  engine/language-server/src/main/java/org/enso/languageserver/boot/resource/JsonRpcInitialization.java
  engine/language-server/src/main/java/org/enso/languageserver/boot/resource/RepoInitialization.java
  engine/language-server/src/main/java/org/enso/languageserver/boot/resource/SequentialResourcesInitialization.java
  engine/language-server/src/main/java/org/enso/languageserver/boot/resource/TruffleContextInitialization.java
  engine/language-server/src/main/java/org/enso/languageserver/boot/resource/ZioRuntimeInitialization.java
  engine/language-server/src/main/scala/org/enso/languageserver/boot/ResourcesInitialization.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/resource/AsyncResourcesInitialization.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/resource/DirectoriesInitialization.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/resource/InitializationComponent.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/resource/JsonRpcInitializationComponent.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/resource/RepoInitialization.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/resource/SequentialResourcesInitialization.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/resource/TruffleContextInitialization.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/resource/ZioRuntimeInitialization.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/language-server/src/test/scala/org/enso/languageserver/boot/resource/RepoInitializationSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/command/InvalidateModulesIndexCommand.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/job/BackgroundJob.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/job/SerializeModuleJob.java
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/ModifyVisualizationCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/JobControlPlane.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/JobExecutionEngine.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/DeserializeLibrarySuggestionsJob.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/DetachVisualizationJob.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ExecuteJob.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/Job.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/UpsertVisualizationJob.scala
  engine/runtime-with-instruments/src/test/java/org/enso/interpreter/test/instrument/IncrementalUpdatesTest.java
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeAsyncCommandsTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeErrorsTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeExecutionEnvironmentTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeRefactoringTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeSuggestionUpdatesTest.scala
  engine/runtime-with-polyglot/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java
  engine/runtime/src/main/scala/org/enso/compiler/SerializationManager.scala
  lib/scala/testkit/src/main/scala/org/enso/testkit/ToScalaFutureConversions.scala
Labels: CI: Ready to merge, CI: No changelog needed

#8114 Test and improve handling of `Date_Time with_timezone=False` in Postgres
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Column_Fetcher.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/JDBC_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Type_Mapping.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Statement_Setter.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Type/Storage.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Type/Value_Type.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoTimeZone.java
  lib/scala/common-polyglot-core-utils/src/main/java/org/enso/polyglot/common_utils/Core_Date_Utils.java
  std-bits/database/src/main/java/org/enso/database/JDBCUtils.java
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Database/Types/Postgres_Type_Mapping_Spec.enso
  test/Table_Tests/src/Helpers/Value_Type_Spec.enso
  test/Table_Tests/src/In_Memory/Column_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#8109 Local scope filtering
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/components/ComponentBrowser/__tests__/filtering.test.ts
  app/gui2/src/components/ComponentBrowser/filtering.ts
  app/gui2/src/providers/guiConfig.ts
  app/gui2/src/stores/project.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#8129 Fix incremental compilation of SPI in Java helper libraries
  build.sbt
  project/SPIHelpers.scala
Labels: CI: Ready to merge, CI: No changelog needed

#8108 Remove Playwright tests from Lint CI action
  app/ide-desktop/lib/dashboard/package.json
Labels: CI: Ready to merge, CI: No changelog needed

#8092 Simplify code to run in the browser
  engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/builtins/MethodGenerator.java
Labels: CI: Ready to merge, CI: No changelog needed

#8143 Properly convert defaulted arguments before on_call back
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/Instrumentor.java
  test/Tests/src/Semantic/Instrumentor_Spec.enso
Labels: CI: No changelog needed

#8130 Compare performance of Panic / Java Exception / Dataflow error
  docs/infrastructure/benchmarks.md
  test/Benchmarks/polyglot-sources/benchmark-java-helpers/src/main/java/org/enso/benchmark_helpers/PanicsHelpers.java
  test/Benchmarks/src/Config.enso
  test/Benchmarks/src/Main.enso
  test/Benchmarks/src/Runtime/Panics_And_Errors.enso
  test/Benchmarks/src/Table/Add_Row_Number.enso
  test/Benchmarks/src/Table/Column_From_Vector.enso
  test/Exploratory_Benchmarks/src/Main.enso
  test/Exploratory_Benchmarks/src/Table/Enso_Callback.enso
  test/Exploratory_Benchmarks/src/Table/Helpers.enso
  test/Tests/src/Semantic/Error_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#8133 Error on invalid capability acquire/release request
  engine/language-server/src/main/scala/org/enso/languageserver/capability/CapabilityRouter.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/CapabilitiesTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#8123 Use Enso AST in graph editor
  app/gui2/parser-codegen/codegen.ts
  app/gui2/parser-codegen/serialization.ts
  app/gui2/public/visualizations/ScatterplotVisualization.vue
  app/gui2/shared/yjsModel.ts
  app/gui2/src/App.vue
  app/gui2/src/assets/base.css
  app/gui2/src/bindings.ts
  app/gui2/src/components/CodeEditor.vue
  app/gui2/src/components/ComponentBrowser/input.ts
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphEdge.vue
  app/gui2/src/components/GraphEditor/GraphEdges.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/GraphNodes.vue
  app/gui2/src/components/GraphEditor/NodeToken.vue
  app/gui2/src/components/GraphEditor/NodeTree.vue
  app/gui2/src/components/NavBar.vue
  app/gui2/src/components/NodeSpan.vue
  app/gui2/src/components/ProjectTitle.vue
  app/gui2/src/components/TopBar.vue
  app/gui2/src/components/VisualizationContainer.vue
  app/gui2/src/components/visualizations/HeatmapVisualization.vue
  app/gui2/src/components/visualizations/HistogramVisualization.vue
  app/gui2/src/components/visualizations/TableVisualization.vue
  app/gui2/src/providers/graphNavigator.ts
  app/gui2/src/providers/graphSelection.ts
  app/gui2/src/providers/guiConfig.ts
  app/gui2/src/providers/index.ts
  app/gui2/src/providers/visualizationConfig.ts
  app/gui2/src/stores/graph.ts
  app/gui2/src/stores/project.ts
  app/gui2/src/util/assert.ts
  app/gui2/src/util/ast/__tests__/__snapshots__/ast.test.ts.snap
  app/gui2/src/util/ast/__tests__/ast.test.ts
  app/gui2/src/util/ast/extended.ts
  app/gui2/src/util/ast/index.ts
  app/gui2/src/util/codemirror.ts
  app/gui2/src/util/navigator.ts
  app/gui2/src/util/net.ts
  app/gui2/src/util/parserSupport.ts
  app/gui2/src/util/result.ts
  app/gui2/src/util/selection.ts
  app/gui2/src/util/vec2.ts
  app/gui2/src/util/visualizationDataRegistry.ts
Labels: CI: Ready to merge, CI: No changelog needed

#8142 Navigating in documentation panel
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/components/DocumentationPanel.vue
  app/gui2/src/components/documentation/DocsList.vue
  app/gui2/src/components/documentation/DocsTags.vue
Labels: -gui2

#8144 Introducing CompilerContext.Module
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/job/SerializeModuleJob.java
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/RenameProjectCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/AnalyzeModuleInScopeJob.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/AnalyzeModuleJob.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime/src/main/java/org/enso/compiler/context/CompilerContext.java
  engine/runtime/src/main/java/org/enso/interpreter/EnsoLanguage.java
  engine/runtime/src/main/java/org/enso/interpreter/node/ProgramRootNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/TopLevelScope.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/CompilerResult.scala
  engine/runtime/src/main/scala/org/enso/compiler/PackageRepository.scala
  engine/runtime/src/main/scala/org/enso/compiler/SerializationManager.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/InlineContext.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/ModuleContext.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala
  engine/runtime/src/main/scala/org/enso/compiler/data/BindingsMap.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/FullyQualifiedNames.scala
  engine/runtime/src/main/scala/org/enso/compiler/phase/BuiltinsIrBuilder.scala
  engine/runtime/src/main/scala/org/enso/compiler/phase/ExportsResolution.scala
  engine/runtime/src/main/scala/org/enso/compiler/phase/ImportResolver.scala
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/DefaultPackageRepository.scala
  engine/runtime/src/test/java/org/enso/compiler/SerdeCompilerTest.java
  engine/runtime/src/test/java/org/enso/compiler/SerializerTest.java
  engine/runtime/src/test/scala/org/enso/compiler/refactoring/IRUtilsTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/CompilerTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/context/SuggestionBuilderTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/GlobalNamesTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/semantic/ImportExportTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/semantic/TypeSignaturesTest.scala
Labels: CI: No changelog needed

#8037 Hook up Play Button and Execution Mode selector to Language Server.
  app/gui2/shared/languageServer.ts
  app/gui2/src/components/ExecutionModeSelector.vue
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/stores/project.ts
Labels: CI: Ready to merge, CI: No changelog needed

#8154 Eliminate potential race-condition in PathWatcher
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/PathWatcher.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/ReceivesTreeUpdatesHandler.scala
Labels: CI: Ready to merge, CI: No changelog needed

#8166 Fix bench-processor test
  build.sbt
  lib/scala/bench-processor/src/main/java/org/enso/benchmarks/BenchConfig.java
  lib/scala/bench-processor/src/main/java/org/enso/benchmarks/BenchGroup.java
  lib/scala/bench-processor/src/main/java/org/enso/benchmarks/BenchSpec.java
  lib/scala/bench-processor/src/main/java/org/enso/benchmarks/BenchSuite.java
  lib/scala/bench-processor/src/main/java/org/enso/benchmarks/ModuleBenchSuite.java
  lib/scala/bench-processor/src/main/java/org/enso/benchmarks/PhaseConfig.java
  lib/scala/bench-processor/src/main/java/org/enso/benchmarks/processor/GenerateBenchSources.java
  lib/scala/bench-processor/src/main/java/org/enso/benchmarks/processor/SpecCollector.java
  lib/scala/bench-processor/src/main/java/org/enso/benchmarks/runner/BenchRunner.java
  lib/scala/bench-processor/src/main/java/org/enso/benchmarks/runner/Report.java
  lib/scala/bench-processor/src/main/java/org/enso/benchmarks/runner/ReportItem.java
  lib/scala/bench-processor/src/test/java/org/enso/benchmarks/TestSpecCollector.java
  lib/scala/bench-processor/src/test/resources/Test_Collector/src/Main.enso
Labels: CI: No changelog needed

#8168 Add special handling for Dataflow_Error passed to Runtime.assert
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/runtime/AssertNode.java
  test/Tests/src/Runtime/Asserts_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#8160 Resolve imports and exports via cached BindingsMap
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Module.scala
  engine/runtime/src/main/java/org/enso/compiler/Cache.java
  engine/runtime/src/main/java/org/enso/compiler/context/CompilerContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/SerializationManager.scala
  engine/runtime/src/main/scala/org/enso/compiler/data/BindingsMap.scala
  engine/runtime/src/main/scala/org/enso/compiler/phase/ImportResolver.scala
  engine/runtime/src/test/java/org/enso/compiler/SerdeCompilerTest.java
Labels: CI: No changelog needed, CI: Clean build required

#8118 Documentation Panel
  app/gui2/README.md
  app/gui2/package.json
  app/gui2/src/assets/base.css
  app/gui2/src/assets/icon-examples.svg
  app/gui2/src/assets/icon-important.svg
  app/gui2/src/assets/icon-info.svg
  app/gui2/src/assets/icon-methods.svg
  app/gui2/src/assets/icons.svg
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/components/DocumentationPanel.vue
  app/gui2/src/components/DocumentationPanel/DocsExamples.vue
  app/gui2/src/components/DocumentationPanel/DocsHeader.vue
  app/gui2/src/components/DocumentationPanel/DocsList.vue
  app/gui2/src/components/DocumentationPanel/DocsSynopsis.vue
  app/gui2/src/components/DocumentationPanel/DocsTags.vue
  app/gui2/src/components/DocumentationPanel/ir.ts
  app/gui2/src/components/GraphEditor/GraphEdge.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/NodeTree.vue
  package-lock.json
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#8112 New node placement
  app/gui2/src/components/ComponentBrowser/__tests__/placement.test.ts
  app/gui2/src/components/ComponentBrowser/component.ts
  app/gui2/src/components/ComponentBrowser/filtering.ts
  app/gui2/src/components/ComponentBrowser/placement.ts
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphEdge.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/stores/graph.ts
  app/gui2/src/util/__tests__/array.test.ts
  app/gui2/src/util/__tests__/range.test.ts
  app/gui2/src/util/array.ts
  app/gui2/src/util/events.ts
  app/gui2/src/util/iterable.ts
  app/gui2/src/util/navigator.ts
  app/gui2/src/util/range.ts
  app/gui2/src/util/rect.ts
  app/gui2/src/util/vec2.ts
Labels: CI: Ready to merge, CI: No changelog needed

#8172 Eliminate references to Truffle nodes & co. in the compiler
  engine/runtime/src/main/java/org/enso/compiler/context/CompilerContext.java
  engine/runtime/src/main/java/org/enso/interpreter/Constants.java
  engine/runtime/src/main/java/org/enso/interpreter/EnsoLanguage.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/debug/EvalNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/InlineContext.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/ModuleContext.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala
  engine/runtime/src/main/scala/org/enso/compiler/data/BindingsMap.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DataflowAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/FunctionBinding.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/GlobalNames.scala
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/RuntimeStubsGenerator.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/GenerateMethodBodiesTest.scala
Labels: CI: No changelog needed

#8176 Navigating documentation panel with breadcrumbs
  app/gui2/src/components/DocumentationPanel.vue
  app/gui2/src/components/DocumentationPanel/DocsBreadcrumb.vue
  app/gui2/src/components/DocumentationPanel/DocsBreadcrumbs.vue
  app/gui2/src/components/DocumentationPanel/DocsList.vue
  app/gui2/src/components/DocumentationPanel/history.ts
  app/gui2/src/components/DocumentationPanel/ir.ts
  app/gui2/src/util/qualifiedName.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#8177 Fix node color
  app/gui2/src/components/GraphEditor/GraphNode.vue
Labels: CI: Ready to merge, CI: No changelog needed, --regression, -gui2

#8157 Synchronize execution mode
  app/gui2/shared/yjsModel.ts
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/stores/project.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#8178 Caches belong to runtime, not IR compiler
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/job/SerializeModuleJob.java
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/DeserializeLibrarySuggestionsJob.scala
  engine/runtime/src/main/java/org/enso/compiler/context/CompilerContext.java
  engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java
  engine/runtime/src/main/java/org/enso/interpreter/caches/ImportExportCache.java
  engine/runtime/src/main/java/org/enso/interpreter/caches/ModuleCache.java
  engine/runtime/src/main/java/org/enso/interpreter/caches/SuggestionsCache.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/PackageRepository.scala
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/DefaultPackageRepository.scala
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/SerializationManager.scala
  engine/runtime/src/test/java/org/enso/compiler/SerdeCompilerTest.java
  engine/runtime/src/test/java/org/enso/compiler/SerializationManagerTest.java
  engine/runtime/src/test/java/org/enso/compiler/SerializerTest.java
Labels: CI: No changelog needed

#8181 Removal of useless ApplicationSaturation phase
  engine/runtime/src/main/scala/org/enso/compiler/Passes.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/ComplexType.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/LambdaShorthandToLambda.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/optimise/ApplicationSaturation.scala
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/PassManagerTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/DataflowAnalysisTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/TailCallTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/lint/UnusedBindingsTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/optimise/ApplicationSaturationTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/PatternsTest.scala
Labels: CI: No changelog needed

#8169 Use TruffleLogger bound to the engine to prevent illegal usage
  engine/interpreter-dsl-test/src/test/java/org/enso/interpreter/dsl/test/ThrowableCatchTest.java
  engine/runtime-with-instruments/src/test/java/org/enso/interpreter/test/instrument/AvoidIdInstrumentationTagTest.java
  engine/runtime-with-instruments/src/test/java/org/enso/interpreter/test/instrument/WarningInstrumentationTest.java
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/BuiltinTypesTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeAsyncCommandsTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeComponentsTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeExecutionEnvironmentTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeInstrumentTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeProjectContextTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeRefactoringTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeStdlibTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeSuggestionUpdatesTest.scala
  engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/InsightForEnsoTest.java
  engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/instrument/VerifyJavaScriptIsAvailableTest.java
  engine/runtime-with-polyglot/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/ArrayProxyBenchmarks.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/CurriedFunctionBenchmarks.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/EqualsBenchmarks.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/IfVsCaseBenchmarks.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/ListBenchmarks.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/NestedPatternCompilationBenchmarks.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/SieveBenchmarks.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/StringBenchmarks.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/TypePatternBenchmarks.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/VectorBenchmarks.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java
  engine/runtime/src/test/java/org/enso/compiler/ExecCompilerTest.java
  engine/runtime/src/test/java/org/enso/compiler/SerdeCompilerTest.java
  engine/runtime/src/test/java/org/enso/compiler/SerializerTest.java
  engine/runtime/src/test/java/org/enso/interpreter/runtime/ModuleSourcesTest.java
  engine/runtime/src/test/java/org/enso/interpreter/runtime/ModuleTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/DebuggingEnsoTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/SharedEngineTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/TestBase.java
  engine/runtime/src/test/scala/org/enso/compiler/test/ModifiedTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/semantic/ImportExportTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/InterpreterTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/PackageTest.scala
  lib/scala/bench-processor/src/main/java/org/enso/benchmarks/processor/BenchProcessor.java
Labels: CI: Ready to merge, CI: No changelog needed

#8190 Allow reassigning of BindingsMap
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime/src/main/java/org/enso/compiler/PackageRepositoryUtils.java
  engine/runtime/src/main/java/org/enso/compiler/context/CompilerContext.java
  engine/runtime/src/main/java/org/enso/compiler/pass/analyse/ExportSymbolAnalysis.java
  engine/runtime/src/main/java/org/enso/compiler/pass/analyse/PrivateModuleAnalysis.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
Labels: CI: Ready to merge, CI: No changelog needed

#8191 Preserve error code in the error message from RPC
  app/gui2/shared/languageServer.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#8146 Implement `Table.lookup_and_replace` in Database
  distribution/lib/Standard/AWS/0.0.0-dev/src/Database/Redshift/Internal/Redshift_Error_Mapper.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Common/Lookup_Query_Helper.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Error_Mapper.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Helpers.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/IR/SQL_Expression.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Error_Mapper.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Error_Mapper.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Type_Mapping.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Lookup_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  std-bits/table/src/main/java/org/enso/table/data/table/join/LookupJoin.java
  test/Table_Tests/src/Common_Table_Operations/Core_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Cross_Join_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Join_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Lookup_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Union_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Zip_Spec.enso
  test/Table_Tests/src/Database/Common/Common_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed
