Repository enso-org/enso, pull requests merged in 2023-03, with the labels that each got.

#5700 Optimize import/export resolution
  CHANGELOG.md
  build.sbt
  docs/runtime/ir-caching.md
  engine/language-server/src/main/scala/org/enso/languageserver/libraries/CompilerBasedDependencyExtractor.scala
  engine/language-server/src/main/scala/org/enso/languageserver/libraries/handler/LibraryPreinstallHandler.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/LibrariesTest.scala
  engine/runtime/src/main/java/org/enso/compiler/Cache.java
  engine/runtime/src/main/java/org/enso/compiler/ImportExportCache.java
  engine/runtime/src/main/java/org/enso/compiler/ModuleCache.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/ModuleCache.scala
  engine/runtime/src/main/scala/org/enso/compiler/PackageRepository.scala
  engine/runtime/src/main/scala/org/enso/compiler/SerializationManager.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/data/BindingsMap.scala
  engine/runtime/src/main/scala/org/enso/compiler/data/CompilerConfig.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/MethodCalls.scala
  engine/runtime/src/main/scala/org/enso/compiler/phase/ExportsResolution.scala
  engine/runtime/src/main/scala/org/enso/compiler/phase/ImportResolver.scala
  engine/runtime/src/test/java/org/enso/compiler/SerializerTest.java
  engine/runtime/src/test/scala/org/enso/compiler/test/CacheInvalidationTest.scala
  lib/scala/library-manager-test/src/test/scala/org/enso/librarymanager/published/repository/LibraryDownloadTest.scala
  lib/scala/library-manager-test/src/test/scala/org/enso/libraryupload/LibraryUploadTest.scala
  lib/scala/library-manager/src/main/scala/org/enso/librarymanager/dependencies/DependencyResolver.scala
  lib/scala/library-manager/src/main/scala/org/enso/librarymanager/published/repository/LibraryManifest.scala
  lib/scala/pkg/src/main/scala/org/enso/pkg/Package.scala
  project/DistributionPackage.scala
  project/Platform.scala
Labels: CI: Ready to merge

#5779 Use cached icons in Component Browser
  CHANGELOG.md
  app/gui/suggestion-database/src/lib.rs
  app/gui/view/component-browser/component-list-panel/grid/src/entry.rs
  app/gui/view/component-browser/component-list-panel/grid/src/entry/icon.rs
  app/gui/view/component-browser/component-list-panel/icons/src/define_macro.rs
  app/gui/view/component-browser/component-list-panel/icons/src/lib.rs
  app/gui/view/component-browser/component-list-panel/src/lib.rs
  app/gui/view/component-browser/component-list-panel/src/navigator/entry.rs
  app/gui/view/examples/Cargo.toml
  app/gui/view/examples/icons/src/lib.rs
  build/build/src/ide/web.rs
  build/build/src/project/gui.rs
  lib/rust/ensogl/core/src/display/render/composer.rs
  lib/rust/ensogl/core/src/display/render/pass.rs
  lib/rust/ensogl/core/src/display/render/passes/cache_shapes.rs
  lib/rust/ensogl/core/src/display/scene.rs
  lib/rust/ensogl/core/src/display/shape/compound.rs
  lib/rust/ensogl/core/src/display/shape/compound/from_cache.rs
  lib/rust/ensogl/core/src/display/shape/primitive/glsl/shape.glsl
  lib/rust/ensogl/core/src/display/shape/primitive/system/cached.rs
  lib/rust/ensogl/core/src/display/world.rs
  lib/rust/ensogl/examples/cached-shape/src/lib.rs
Labels: CI: Ready to merge

#5634 Reworked `ide watch` and `ide start` commands
  Cargo.lock
  Cargo.toml
  app/gui/language/ast/macros/Cargo.toml
  app/ide-desktop/esbuild-watch.ts
  app/ide-desktop/lib/client/bundle.ts
  app/ide-desktop/lib/client/dist.ts
  app/ide-desktop/lib/client/electron-builder-config.ts
  app/ide-desktop/lib/client/esbuild-config.ts
  app/ide-desktop/lib/client/package.json
  app/ide-desktop/lib/client/paths.ts
  app/ide-desktop/lib/client/src/bin/server.ts
  app/ide-desktop/lib/client/src/paths.ts
  app/ide-desktop/lib/client/start.ts
  app/ide-desktop/lib/client/watch.ts
  app/ide-desktop/lib/content/esbuild-config.ts
  app/ide-desktop/lib/content/start.ts
  app/ide-desktop/lib/content/watch.ts
  build/build/Cargo.toml
  build/build/build.rs
  build/build/src/ide/web.rs
  build/build/src/project.rs
  build/build/src/project/backend.rs
  build/build/src/project/gui.rs
  build/build/src/project/ide.rs
  build/ci_utils/Cargo.toml
  build/ci_utils/src/lib.rs
  build/cli/src/arg/gui.rs
  build/cli/src/arg/ide.rs
  build/cli/src/lib.rs
  build/macros/lib/Cargo.toml
  build/macros/lib/src/lib.rs
  build/macros/lib/src/paths.rs
  build/macros/lib/src/program_args.rs
  build/macros/proc-macro/Cargo.toml
  build/macros/proc-macro/src/lib.rs
  build/macros/proc-macro/tests/paths.rs
  build/macros/proc-macro/tests/plain.rs
  build/macros/proc-macro/tests/with_arg.rs
  build/macros/proc-macro/tests/with_attr.rs
  lib/rust/ensogl/app/theme/derive/Cargo.toml
  lib/rust/logging/macros/Cargo.toml
  lib/rust/macro-utils/Cargo.toml
  lib/rust/parser/src/syntax/tree/visitor/Cargo.toml
  lib/rust/profiler/macros/Cargo.toml
  lib/rust/reflect/macros/Cargo.toml
  lib/rust/shapely/macros/Cargo.toml
Labels: CI: No changelog needed, CI: Clean build required, -build-script

#5790 Improving Expression Support for In Database
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/SQL_Type.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Helpers.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/JDBC_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Expression.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Format.enso
  std-bits/database/src/main/java/org/enso/database/JDBCUtils.java
  test/Table_Tests/src/Common_Table_Operations/Expression_Spec.enso
  test/Table_Tests/src/Database/Codegen_Spec.enso
  test/Table_Tests/src/IO/Excel_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#5800 Updates dashboard styles
  .prettierrc.yaml
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/auth.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/service.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectActionButton.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/templates.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/service.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/useProjectManagerAdapter.ts
Labels: CI: No changelog needed

#5783 Switch to Truffle PE mode before calling into Enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Runtime.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/generic/GetExecutableNameNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/runtime/GetStackTraceNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Array.java
  engine/runtime/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/ErrorResolver.scala
  test/Tests/src/Semantic/Error_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#5799 Review File/Data read and read_text warnings
  .prettierignore
  distribution/lib/Standard/Base/0.0.0-dev/src/Error/File_Error.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/Existing_File_Behavior.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Delimited/Delimited_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Delimited/Delimited_Reader.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Delimited/Delimited_Writer.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Reader.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Workbook.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Java_Problems.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Extensions.enso
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoFile.java
  std-bits/table/src/main/java/org/enso/table/parsing/problems/InvalidRow.java
  std-bits/table/src/main/java/org/enso/table/parsing/problems/MismatchedQuote.java
  std-bits/table/src/main/java/org/enso/table/parsing/problems/ProblemAggregatorImpl.java
  std-bits/table/src/main/java/org/enso/table/read/DelimitedReader.java
  std-bits/table/src/main/java/org/enso/table/read/QuoteHelper.java
  test/Table_Tests/data/varying_rows2.csv
  test/Table_Tests/data/varying_rows3.csv
  test/Table_Tests/src/IO/Delimited_Read_Spec.enso
  test/Table_Tests/src/IO/Excel_Spec.enso
  test/Tests/data/sample-json.weird-extension
  test/Tests/data/sample-malformed.json
  test/Tests/data/sample.json
  test/Tests/polyglot-sources/enso-test-java-helpers/src/main/java/org/enso/base_test_helpers/FileSystemHelper.java
  test/Tests/src/System/File_Read_Spec.enso
  test/Tests/src/System/File_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#5725 Remove glyph FRP
  .github/CODEOWNERS
  Cargo.lock
  lib/rust/ensogl/component/text/src/buffer/formatting.rs
  lib/rust/ensogl/component/text/src/component/text.rs
  lib/rust/ensogl/component/text/src/font.rs
  lib/rust/ensogl/component/text/src/font/glyph.rs
  lib/rust/ensogl/component/text/src/font/msdf/Cargo.toml
  lib/rust/ensogl/component/text/src/font/msdf/src/lib.rs
  lib/rust/ensogl/component/text/src/font/msdf/src/texture.rs
  lib/rust/ensogl/core/src/display/object/instance.rs
  lib/rust/ensogl/examples/text-area/src/lib.rs
  lib/rust/frp/src/network.rs
  lib/rust/profiler/data/src/aggregate.rs
  lib/rust/profiler/data/src/bin/intervals.rs
  lib/rust/profiler/macros/src/low_level.rs
Labels: CI: Ready to merge, CI: No changelog needed

#5816 Review Text/Table.write problem behavior
  build.sbt
  distribution/lib/Standard/Base/0.0.0-dev/src/Error/Common.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Error/File_Error.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/Existing_File_Behavior.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/Write_Extensions.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/NoSuchField.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Error.java
  engine/runtime/src/test/java/org/enso/interpreter/test/TypeMembersTest.java
  test/Table_Tests/data/transient/.gitignore
  test/Table_Tests/src/IO/Delimited_Write_Spec.enso
  test/Table_Tests/src/IO/Excel_Spec.enso
  test/Table_Tests/src/IO/Formats_Spec.enso
  test/Table_Tests/src/IO/Main.enso
  test/Table_Tests/src/Util.enso
  test/Tests/src/System/File_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#5778 Comparators support partial ordering
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Any.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Ordering.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Ordering/Comparator.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Statistics.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Period.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Error/Common.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Error/Incomparable_Values.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/IncomparableValues.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/mutable/SortNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/LessThanNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Error.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/hash/EnsoHashMapBuilder.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/hash/HashMapRemoveNode.java
  engine/runtime/src/test/java/org/enso/compiler/ParseStdLibTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/EqualsTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/HashCodeTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/ValuesGenerator.java
  std-bits/base/src/main/java/org/enso/base/CompareException.java
  std-bits/base/src/main/java/org/enso/base/ObjectComparator.java
  std-bits/table/src/main/java/org/enso/table/aggregations/MinOrMax.java
  test/Table_Tests/src/Common_Table_Operations/Aggregate_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Order_By_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
  test/Tests/src/Data/Map_Spec.enso
  test/Tests/src/Data/Ordering/Comparator_Spec.enso
  test/Tests/src/Data/Ordering_Spec.enso
  test/Tests/src/Data/Statistics_Spec.enso
  test/Tests/src/Data/Time/Date_Spec.enso
  test/Tests/src/Data/Time/Date_Time_Spec.enso
  test/Tests/src/Data/Time/Period_Spec.enso
  test/Tests/src/Data/Time/Time_Of_Day_Spec.enso
  test/Tests/src/Data/Vector_Spec.enso
Labels: CI: Ready to merge

#5802 Retry IDE controller initialization.
  CHANGELOG.md
  app/gui/src/ide/initializer.rs
Labels: CI: Ready to merge

#5832 Coerce values obtained from polyglot calls
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/generic/GetMemberNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/generic/InstantiateNode.java
  test/Tests/polyglot-sources/enso-test-java-helpers/src/main/java/org/enso/base_test_helpers/IntHolder.java
  test/Tests/src/Data/Polyglot_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#5823 Fixes from the Demo on 2nd March
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Of_Day.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Data_Formatter.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Geo_Map.enso
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoDateTime.java
  std-bits/base/src/main/java/org/enso/base/Time_Utils.java
  std-bits/table/src/main/java/org/enso/table/expressions/ExpressionVisitorImpl.java
  std-bits/table/src/main/java/org/enso/table/formatting/DateFormatter.java
  std-bits/table/src/main/java/org/enso/table/formatting/DateTimeFormatter.java
  std-bits/table/src/main/java/org/enso/table/formatting/TimeFormatter.java
  std-bits/table/src/main/java/org/enso/table/parsing/BaseTimeParser.java
  std-bits/table/src/main/java/org/enso/table/parsing/DateTimeParser.java
  test/Table_Tests/src/Common_Table_Operations/Cross_Tab_Spec.enso
  test/Table_Tests/src/Formatting/Data_Formatter_Spec.enso
  test/Table_Tests/src/Formatting/Parse_Values_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#5808 Implement fix for duplicate entries in visualisation list.
  Cargo.lock
  app/gui/view/graph-editor/Cargo.toml
  app/gui/view/graph-editor/src/component/visualization/definition.rs
  app/gui/view/graph-editor/src/component/visualization/registry.rs
Labels: CI: Ready to merge, CI: No changelog needed

#5847 Fixing web content input config bug
  app/ide-desktop/lib/content/src/index.ts
Labels: CI: No changelog needed

#5698 Pre compute suggestion db during build time
  build.sbt
  engine/language-server/src/main/scala/org/enso/languageserver/boot/resource/RepoInitialization.scala
  engine/language-server/src/main/scala/org/enso/languageserver/event/InitializedEvent.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/BufferRegistry.scala
  engine/language-server/src/test/scala/org/enso/languageserver/boot/resource/RepoInitializationSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/Suggestions.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/SuggestionsHandlerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/polyglot-api/src/test/scala/org/enso/polyglot/data/TreeTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeComponentsTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeErrorsTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeInstrumentTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeStdlibTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeSuggestionUpdatesTest.scala
  engine/runtime/src/main/java/org/enso/compiler/Cache.java
  engine/runtime/src/main/java/org/enso/compiler/ImportExportCache.java
  engine/runtime/src/main/java/org/enso/compiler/ModuleCache.java
  engine/runtime/src/main/java/org/enso/compiler/SuggestionsCache.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/SerializationManager.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionDiff.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/Handler.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/NotificationHandler.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/CommandFactory.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/DeserializeLibrarySuggestionsCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/VerifyModulesIndexCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/AnalyzeModuleInScopeJob.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/DeserializeLibrarySuggestionsJob.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime/src/test/java/org/enso/compiler/SerializerTest.java
  engine/runtime/src/test/java/org/enso/compiler/test/context/JacksonTest.java
  lib/scala/docs-generator/src/main/scala/org/enso/docs/sections/DocSectionsBuilder.scala
  lib/scala/docs-generator/src/test/scala/org/enso/docs/sections/DocSectionsBuilderTest.scala
  lib/scala/pkg/src/main/scala/org/enso/pkg/Package.scala
  lib/scala/pkg/src/main/scala/org/enso/pkg/QualifiedName.scala
  project/DistributionPackage.scala
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
Labels: CI: Ready to merge, CI: No changelog needed

#5793 Cognito auth 1/2 - extracted electron logic
  app/ide-desktop/lib/client/electron-builder-config.ts
  app/ide-desktop/lib/client/package.json
  app/ide-desktop/lib/client/shared.ts
  app/ide-desktop/lib/client/src/authentication.ts
  app/ide-desktop/lib/client/src/index.ts
  app/ide-desktop/lib/client/src/ipc.ts
  app/ide-desktop/lib/client/src/preload.ts
  app/ide-desktop/package-lock.json
  build-config.yaml
Labels: CI: Ready to merge, CI: No changelog needed

#5774 Named arguments support in IDE
  CHANGELOG.md
  app/gui/controller/double-representation/src/definition.rs
  app/gui/language/ast/impl/src/crumbs.rs
  app/gui/language/ast/impl/src/lib.rs
  app/gui/language/ast/impl/src/opr.rs
  app/gui/language/ast/impl/src/prefix.rs
  app/gui/language/span-tree/example/src/lib.rs
  app/gui/language/span-tree/src/action.rs
  app/gui/language/span-tree/src/builder.rs
  app/gui/language/span-tree/src/generate.rs
  app/gui/language/span-tree/src/iter.rs
  app/gui/language/span-tree/src/lib.rs
  app/gui/language/span-tree/src/node.rs
  app/gui/language/span-tree/src/node/kind.rs
  app/gui/src/controller/graph.rs
  app/gui/src/controller/graph/executed.rs
  app/gui/src/presenter/graph.rs
  app/gui/src/tests.rs
  app/gui/view/graph-editor/src/component/node/input/area.rs
  app/gui/view/graph-editor/src/component/node/input/widget.rs
  app/gui/view/graph-editor/src/lib.rs
  lib/rust/ensogl/component/drop-down/src/entry.rs
  lib/rust/ensogl/component/drop-down/src/lib.rs
Labels: CI: Ready to merge

#5846 Bump Benchmarks Timeout
  .github/workflows/benchmark.yml
  .github/workflows/changelog.yml
  .github/workflows/gui.yml
  .github/workflows/promote.yml
  .github/workflows/release.yml
  .github/workflows/scala-new.yml
  .github/workflows/shader-tools.yml
  build/build/src/ci_gen.rs
  build/ci_utils/src/actions/workflow/definition.rs
Labels: CI: No changelog needed

#5820 Allow fractional pixel ratio in CacheShapesPass
  lib/rust/ensogl/core/src/display/render/composer.rs
  lib/rust/ensogl/core/src/display/render/pass.rs
  lib/rust/ensogl/core/src/display/render/passes/cache_shapes.rs
  lib/rust/ensogl/core/src/display/scene.rs
Labels: CI: Ready to merge, CI: No changelog needed

#5811 Precompute MSDFs
  Cargo.lock
  app/gui/Cargo.toml
  app/gui/enso-profiler-enso-data/src/lib.rs
  app/gui/src/lib.rs
  app/ide-desktop/lib/content/src/index.ts
  build/build/paths.yaml
  build/build/src/project/wasm.rs
  build/build/src/release.rs
  lib/rust/bitmap/Cargo.toml
  lib/rust/bitmap/src/lib.rs
  lib/rust/ensogl/app/theme/hardcoded/Cargo.toml
  lib/rust/ensogl/app/theme/hardcoded/src/lib.rs
  lib/rust/ensogl/component/Cargo.toml
  lib/rust/ensogl/component/dynamic-assets/Cargo.toml
  lib/rust/ensogl/component/dynamic-assets/src/fonts.rs
  lib/rust/ensogl/component/dynamic-assets/src/lib.rs
  lib/rust/ensogl/component/dynamic-assets/src/shaders.rs
  lib/rust/ensogl/component/text/Cargo.toml
  lib/rust/ensogl/component/text/src/font.rs
  lib/rust/ensogl/component/text/src/font/embedded/src/lib.rs
  lib/rust/ensogl/component/text/src/font/family/src/lib.rs
  lib/rust/ensogl/component/text/src/font/msdf/Cargo.toml
  lib/rust/ensogl/component/text/src/font/msdf/src/texture.rs
  lib/rust/ensogl/component/text/src/lib.rs
  lib/rust/ensogl/core/src/display/world.rs
  lib/rust/ensogl/core/src/system/js/app.rs
  lib/rust/ensogl/examples/text-area/src/lib.rs
  lib/rust/ensogl/pack/Cargo.toml
  lib/rust/ensogl/pack/js/package.json
  lib/rust/ensogl/pack/js/src/asset-extractor/args.ts
  lib/rust/ensogl/pack/js/src/asset-extractor/asset-extractor.ts
  lib/rust/ensogl/pack/js/src/asset-extractor/fs.ts
  lib/rust/ensogl/pack/js/src/runner/config.json
  lib/rust/ensogl/pack/js/src/runner/index.ts
  lib/rust/ensogl/pack/js/src/shader-extractor/shader-extractor.ts
  lib/rust/ensogl/pack/src/assets.rs
  lib/rust/ensogl/pack/src/lib.rs
Labels: CI: Ready to merge, CI: Keep up to date, CI: No changelog needed, -gui

#5850 Review generated Column names
  CHANGELOG.md
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Redshift/Redshift_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Naming_Helpers.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/GetQualifiedTypeNameNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/text/Text.java
  std-bits/table/src/main/java/org/enso/table/data/index/MultiValueIndex.java
  std-bits/table/src/main/java/org/enso/table/data/table/Column.java
  std-bits/table/src/main/java/org/enso/table/util/NameDeduplicator.java
  test/Table_Tests/data/.gitignore
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Core_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Cross_Tab_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Expression_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Integration_Tests.enso
  test/Table_Tests/src/Common_Table_Operations/Select_Columns_Spec.enso
  test/Table_Tests/src/Database/Codegen_Spec.enso
  test/Table_Tests/src/IO/Delimited_Write_Spec.enso
  test/Table_Tests/src/In_Memory/Column_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
  test/Tests/src/Data/Text_Spec.enso
  test/Visualization_Tests/src/Table_Spec.enso
Labels: CI: Ready to merge

#5785 Regex.Compile using Truffle Regex, update find, match and match_all
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Prim_Text_Helper.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Match_2.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Pattern_2.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex_2.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Span.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/RegexCompileNode.java
  engine/runtime/src/test/java/org/enso/compiler/ParseStdLibTest.java
  test/Tests/src/Data/Text_Spec.enso
Labels: CI: Ready to merge, CI: Clean build required

#5870 Use SimpleFormatter.formatMessage to replace {0} with actual parameters
  build.sbt
  engine/runtime/src/main/java/org/enso/compiler/ImportExportCache.java
  engine/runtime/src/main/java/org/enso/compiler/ModuleCache.java
  engine/runtime/src/main/java/org/enso/compiler/SuggestionsCache.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/SerializationManager.scala
  lib/scala/logging-service/src/main/scala/org/enso/loggingservice/JavaLoggingLogHandler.scala
  lib/scala/logging-service/src/test/java/org/enso/loggingservice/JavaLoggingLogHandlerTest.java
  project/Cargo.scala
  project/CustomLogManager.scala
  project/DistributionPackage.scala
  project/FrgaalJavaCompiler.scala
  project/GenerateFlatbuffers.scala
  project/LauncherShimsForTest.scala
  project/NativeImage.scala
  project/StdBits.scala
  project/plugins.sbt
  project/src/main/scala/licenses/report/ReportState.scala
Labels: CI: Ready to merge, CI: No changelog needed

#5880 Check SBT build format on CI
  .github/workflows/formatting.yml
Labels: CI: Ready to merge, CI: No changelog needed

#5845 Merge ordered and unordered comparators
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Any.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Boolean.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Ordering.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Duration.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Period.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Of_Day.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Value_Type.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/DefaultComparator.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/DefaultUnorderedComparator.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/HasCustomComparatorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/LessThanNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  engine/runtime/src/test/java/org/enso/interpreter/test/EqualsTest.java
  test/Benchmarks/src/Table/Sorting.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Join_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
  test/Tests/src/Data/Map_Spec.enso
  test/Tests/src/Data/Numbers_Spec.enso
  test/Tests/src/Data/Ordering/Comparator_Spec.enso
  test/Tests/src/Data/Ordering_Spec.enso
  test/Tests/src/Data/Statistics_Spec.enso
  test/Tests/src/Data/Text_Spec.enso
  test/Tests/src/Data/Time/Date_Spec.enso
  test/Tests/src/Data/Time/Date_Time_Spec.enso
  test/Tests/src/Data/Time/Duration_Spec.enso
  test/Tests/src/Data/Vector_Spec.enso
  test/Tests/src/Semantic/Equals_Spec.enso
Labels: CI: Ready to merge

#5859 triangle indicator for dropdowns
  app/gui/view/graph-editor/src/component/node/input/area.rs
  app/gui/view/graph-editor/src/component/node/input/widget.rs
  lib/rust/ensogl/core/src/display/shape/primitive/def/class.rs
  lib/rust/ensogl/core/src/display/shape/primitive/def/modifier.rs
  lib/rust/ensogl/core/src/display/shape/primitive/def/primitive.rs
  lib/rust/ensogl/core/src/display/shape/primitive/shader/canvas.rs
Labels: CI: Ready to merge, CI: No changelog needed

#5871 Log exceptions with stack traces
  engine/language-server/src/main/resources/application.conf
  engine/language-server/src/main/scala/org/enso/languageserver/boot/LanguageServerComponent.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/TimingsConfig.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/resource/RepoInitialization.scala
  engine/language-server/src/main/scala/org/enso/languageserver/data/Config.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/ContentRoot.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/ContentRootManagerActor.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/ContentRootManagerWrapper.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystem.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/PathWatcher.scala
  engine/language-server/src/main/scala/org/enso/languageserver/io/InputRedirectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/libraries/FakeDownload.scala
  engine/language-server/src/main/scala/org/enso/languageserver/libraries/LocalLibraryManager.scala
  engine/language-server/src/main/scala/org/enso/languageserver/libraries/handler/EditionsGetProjectSettingsHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/binary/BinaryConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/RuntimeConnector.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/RuntimeFailureMapper.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/util/UnhandledLogging.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/UpsertVisualisationJob.scala
  lib/scala/project-manager/src/main/resources/application.conf
Labels: CI: Ready to merge, CI: No changelog needed

#5855 Add a `common-polyglot-core-utils `project
  build.sbt
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoDateTime.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/text/Text.java
  lib/scala/common-polyglot-core-utils/src/main/java/org/enso/polyglot/common_utils/Core_Date_Utils.java
  lib/scala/common-polyglot-core-utils/src/main/java/org/enso/polyglot/common_utils/Core_Text_Utils.java
  lib/scala/common-polyglot-core-utils/src/main/java/org/enso/polyglot/common_utils/package-info.java
  project/StdBits.scala
  std-bits/base/src/main/java/org/enso/base/Text_Utils.java
  std-bits/base/src/main/java/org/enso/base/Time_Utils.java
  std-bits/table/src/main/java/org/enso/table/aggregations/ShortestOrLongest.java
  std-bits/table/src/main/java/org/enso/table/data/table/Column.java
Labels: CI: Ready to merge, CI: No changelog needed

#5863 Fix `cross_tab` column naming edge cases, add `fill_empty`
  CHANGELOG.md
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Searcher/0.0.0-dev/src/Data_Science/Preparation.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Row.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Filter_Condition_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Join_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Scatter_Plot.enso
  std-bits/table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/DoubleStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/LongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/ObjectStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/Storage.java
  std-bits/table/src/main/java/org/enso/table/data/index/MultiValueIndex.java
  std-bits/table/src/main/java/org/enso/table/data/table/Column.java
  std-bits/table/src/main/java/org/enso/table/expressions/ExpressionVisitorImpl.java
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Cross_Tab_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Join_Spec.enso
  test/Table_Tests/src/Database/Codegen_Spec.enso
  test/Table_Tests/src/Database/Common_Spec.enso
  test/Table_Tests/src/In_Memory/Column_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
Labels: CI: Ready to merge

#5869 Meta.get_constructor_fields works for Type
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/GetConstructorFieldNamesNode.java
  test/Tests/src/Semantic/Meta_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#5913 Do not cancel detach visualization jobs
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/DetachVisualisationJob.scala
Labels: CI: Ready to merge, CI: No changelog needed

#5843 Change order of objects to avoid scrollbar over visualisation chooser
  app/gui/view/graph-editor/src/builtin/visualization/native/text_visualization.rs
  app/gui/view/graph-editor/src/component/visualization/container.rs
  app/gui/view/graph-editor/src/component/visualization/container/action_bar.rs
  app/gui/view/graph-editor/src/component/visualization/container/visualization_chooser.rs
  lib/rust/ensogl/component/list-view/src/entry/list.rs
Labels: CI: Ready to merge, CI: No changelog needed

#5937 fix npx typecript errors
  lib/rust/ensogl/pack/js/src/asset-extractor/asset-extractor.ts
  lib/rust/ensogl/pack/js/src/asset-extractor/fs.ts
  lib/rust/ensogl/pack/js/src/runner/config.ts
  lib/rust/ensogl/pack/js/src/runner/index.ts
  lib/rust/ensogl/pack/js/src/runtime-libs/runtime-libs.ts
  lib/rust/ensogl/pack/js/src/wasm-pack-bundle/index.ts
Labels: CI: Ready to merge, CI: No changelog needed

#5939 Fix a font specification. Fixes #5912.
  lib/rust/ensogl/app/theme/hardcoded/src/lib.rs
Labels: CI: No changelog needed

#5717 Enable typescript-eslint
  app/ide-desktop/eslint.config.js
  app/ide-desktop/lib/client/.eslintrc.cjs
  app/ide-desktop/lib/client/bundle.ts
  app/ide-desktop/lib/client/dist.ts
  app/ide-desktop/lib/client/electron-builder-config.ts
  app/ide-desktop/lib/client/esbuild-config.ts
  app/ide-desktop/lib/client/paths.ts
  app/ide-desktop/lib/client/src/authentication.ts
  app/ide-desktop/lib/client/src/bin/project-manager.ts
  app/ide-desktop/lib/client/src/bin/server.ts
  app/ide-desktop/lib/client/src/config.ts
  app/ide-desktop/lib/client/src/config/parser.ts
  app/ide-desktop/lib/client/src/debug.ts
  app/ide-desktop/lib/client/src/index.ts
  app/ide-desktop/lib/client/src/ipc.ts
  app/ide-desktop/lib/client/src/paths.ts
  app/ide-desktop/lib/client/src/preload.ts
  app/ide-desktop/lib/client/src/security.ts
  app/ide-desktop/lib/client/start.ts
  app/ide-desktop/lib/client/tasks/computeHashes.cjs
  app/ide-desktop/lib/client/tasks/signArchivesMacOs.ts
  app/ide-desktop/lib/client/tsconfig.json
  app/ide-desktop/lib/client/watch.ts
  app/ide-desktop/lib/content-config/src/index.ts
  app/ide-desktop/lib/content-config/tsconfig.json
  app/ide-desktop/lib/content/.eslintrc.cjs
  app/ide-desktop/lib/content/bundle.ts
  app/ide-desktop/lib/content/esbuild-config.ts
  app/ide-desktop/lib/content/package.json
  app/ide-desktop/lib/content/src/index.ts
  app/ide-desktop/lib/content/src/project_manager.ts
  app/ide-desktop/lib/content/src/run.js
  app/ide-desktop/lib/content/src/wasm_imports.js
  app/ide-desktop/lib/content/start.ts
  app/ide-desktop/lib/content/tsconfig.json
  app/ide-desktop/lib/content/watch.ts
  app/ide-desktop/lib/copy-plugin/src/index.mjs
  app/ide-desktop/lib/icons/src/index.js
  app/ide-desktop/lib/server/src/index.mjs
  app/ide-desktop/lib/server/src/live-reload.js
  app/ide-desktop/lib/types/enso-copy-plugin.d.ts
  app/ide-desktop/lib/types/enso-gui-server.d.ts
  app/ide-desktop/lib/types/globals.d.ts
  app/ide-desktop/lib/types/modules.d.ts
  app/ide-desktop/package-lock.json
  app/ide-desktop/tsconfig.json
  app/ide-desktop/utils.ts
Labels: CI: Ready to merge, CI: No changelog needed

#5915 Use AG Grid instead of the old table.js rendering
  app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js
Labels: CI: Ready to merge, CI: No changelog needed

#5798 Cognito auth 2/7 - add authorization app
  CHANGELOG.md
  app/ide-desktop/eslint.config.js
  app/ide-desktop/lib/client/electron-builder-config.ts
  app/ide-desktop/lib/client/package.json
  app/ide-desktop/lib/client/shared.ts
  app/ide-desktop/lib/client/src/authentication.ts
  app/ide-desktop/lib/common/package.json
  app/ide-desktop/lib/common/src/index.ts
  app/ide-desktop/lib/content/package.json
  app/ide-desktop/lib/content/src/index.html
  app/ide-desktop/lib/content/src/index.ts
  app/ide-desktop/lib/dashboard/package.json
  app/ide-desktop/lib/dashboard/public/index.html
  app/ide-desktop/lib/dashboard/src/authentication/package.json
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/cognito.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/config.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/auth.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/session.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/service.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/components/app.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/config.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/service.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/error.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/hooks.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/http.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/index.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/navigation.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/platform.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/providers/logger.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/styles/index.css
  app/ide-desktop/lib/dashboard/src/authentication/src/utils.ts
  app/ide-desktop/lib/dashboard/src/authentication/tailwind.config.ts
  app/ide-desktop/lib/dashboard/src/authentication/tsconfig.json
  app/ide-desktop/lib/dashboard/src/index.tsx
  app/ide-desktop/lib/dashboard/tsconfig.json
  app/ide-desktop/lib/icons/package.json
  app/ide-desktop/package-lock.json
  app/ide-desktop/package.json
  app/ide-desktop/tsconfig.json
  build/build/src/ide/web.rs
  lib/rust/ensogl/pack/js/package.json
  lib/rust/ensogl/pack/js/src/runner/host.ts
Labels: CI: Ready to merge

#5908 Generate import/export bindings in local cache
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/TopLevelScope.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/SerializationManager.scala
  project/DistributionPackage.scala
Labels: CI: Ready to merge, CI: No changelog needed

#5954 Do not ignore package-lock.json files
  .gitignore
  app/gui/view/documentation/package-lock.json
  app/ide-desktop/package-lock.json
  build/prettier/package-lock.json
  lib/rust/ensogl/pack/js/package-lock.json
  package-lock.json
Labels: CI: Ready to merge, CI: No changelog needed

#5945 Dedicated Module.containsUUID method with a cache
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
Labels: CI: Ready to merge, CI: No changelog needed, --low-performance

#5953 Fix Location, a type signature issue, clean up warnings.
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Location.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Helpers.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table.enso
  test/Tests/src/Data/Ordering/Comparator_Spec.enso
  test/Tests/src/Data/Statistics_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#5958 Enable clipboard access.
  app/ide-desktop/lib/client/src/index.ts
Labels: CI: Ready to merge, CI: No changelog needed

#5883 Truffle regex: finish group accessors
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Match_2.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Pattern_2.enso
  test/Tests/src/Data/Text/Regex_2_Spec.enso
  test/Tests/src/Data/Text_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#5900 Don't log installed engines and runtimes in prod
  CHANGELOG.md
  engine/language-server/src/main/scala/org/enso/languageserver/boot/LanguageServerConfig.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/StartupConfig.scala
  engine/language-server/src/main/scala/org/enso/languageserver/data/Config.scala
  engine/language-server/src/test/scala/org/enso/languageserver/boot/resource/RepoInitializationSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/filemanager/ContentRootManagerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/runtime/ContextEventsListenerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/SuggestionsHandlerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/binary/BaseBinaryServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/FileManagerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/VcsManagerTest.scala
  engine/launcher/src/main/scala/org/enso/launcher/Launcher.scala
  engine/runner/src/main/scala/org/enso/runner/Main.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/configuration.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/ExecutorWithUnlimitedPool.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerController.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerDescriptor.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerGatewayImpl.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerProtocol.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerRegistry.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectCreationService.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectService.scala
  lib/scala/runtime-version-manager-test/src/main/scala/org/enso/runtimeversionmanager/test/NoopComponentUpdater.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/GraalVMComponentConfiguration.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/GraalVMComponentUpdater.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/RuntimeComponentUpdater.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/RuntimeVersionManager.scala
  lib/scala/runtime-version-manager/src/test/scala/org/enso/runtimeversionmanager/components/GraalVMComponentConfigurationSpec.scala
  lib/scala/runtime-version-manager/src/test/scala/org/enso/runtimeversionmanager/components/GraalVMComponentUpdaterSpec.scala
Labels: CI: Ready to merge

#4115 Better sorting after filtering items in the Component Browser
  CHANGELOG.md
  Cargo.lock
  app/gui/Cargo.toml
  app/gui/src/controller/searcher.rs
  app/gui/src/controller/searcher/action.rs
  app/gui/src/controller/searcher/component.rs
  app/gui/src/controller/searcher/component/builder.rs
  app/gui/src/controller/searcher/component/group.rs
  app/gui/src/presenter/searcher/provider.rs
  app/gui/view/component-browser/component-list-panel/grid/src/content.rs
  app/gui/view/component-browser/component-list-panel/grid/src/layout.rs
  app/gui/view/component-browser/component-list-panel/grid/src/layouting.rs
  app/gui/view/examples/component-list-panel-view/src/lib.rs
  lib/rust/fuzzly/src/score.rs
Labels: CI: Ready to merge

#5972 Fix #5969
  app/ide-desktop/eslint.config.js
  app/ide-desktop/lib/client/src/index.ts
  app/ide-desktop/lib/client/watch.ts
  app/ide-desktop/utils.ts
Labels: CI: No changelog needed

#5978 Fix qualified names in tag values
  engine/runtime/src/main/scala/org/enso/compiler/data/BindingsMap.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/context/SuggestionBuilderTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#5982 Set authentication default value to false
  app/ide-desktop/lib/content-config/src/config.json
Labels: CI: Ready to merge, CI: No changelog needed

#5974 Fix #5963
  app/ide-desktop/lib/dashboard/src/authentication/tailwind.config.ts
Labels: CI: Ready to merge, CI: No changelog needed

#5979 Fix up some type signatures...
  distribution/lib/Standard/Base/0.0.0-dev/src/Any.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Regression.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Prim_Text_Helper.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex_Matcher.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Text_Matcher.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Duration.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Polyglot.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Runtime.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Runtime/Managed_Resource.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Postgres_Options.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Redshift_Options.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/SQLite_Options.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Geo/0.0.0-dev/src/Geo_Json.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Data/Image.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Delimited/Delimited_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Range.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Writer.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Aggregate_Column_Helper.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Java_Exports.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Problem_Builder.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Bench.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Extensions.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Helpers.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Histogram.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Scatter_Plot.enso
Labels: CI: Ready to merge, CI: No changelog needed

#5970 Delay initialization of SQL database
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/ResourcesInitialization.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/resource/RepoInitialization.scala
  engine/language-server/src/test/scala/org/enso/languageserver/boot/resource/RepoInitializationSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/SuggestionsHandlerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  lib/scala/searcher/src/bench/java/org/enso/searcher/sql/SuggestionsRepoBenchmark.java
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlDatabase.scala
  lib/scala/searcher/src/test/scala/org/enso/searcher/sql/SuggestionsRepoTest.scala
  lib/scala/searcher/src/test/scala/org/enso/searcher/sql/VersionsRepoTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#5864 Cognito auth 3/7 - add registration
  app/ide-desktop/eslint.config.js
  app/ide-desktop/lib/client/src/authentication.ts
  app/ide-desktop/lib/common/src/index.ts
  app/ide-desktop/lib/content/esbuild-config.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/cognito.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/confirmRegistration.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/login.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/registration.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/config.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/auth.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/session.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/service.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/components/app.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/components/svg.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/config.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/service.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/hooks.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/http.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/index.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/navigation.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/utils.ts
  app/ide-desktop/lib/dashboard/src/authentication/tailwind.config.ts
  app/ide-desktop/lib/dashboard/src/authentication/tsconfig.json
  app/ide-desktop/lib/dashboard/tsconfig.json
  app/ide-desktop/lib/types/globals.d.ts
  app/ide-desktop/package-lock.json
  lib/rust/ensogl/pack/js/src/runner/host.ts
Labels: CI: Ready to merge, CI: No changelog needed

#5918 Don't persist UUIDs in IR caches
  engine/runtime/src/main/java/org/enso/compiler/Cache.java
  engine/runtime/src/main/java/org/enso/compiler/ImportExportCache.java
  engine/runtime/src/main/java/org/enso/compiler/ModuleCache.java
  engine/runtime/src/main/java/org/enso/compiler/SuggestionsCache.java
Labels: CI: Ready to merge, CI: No changelog needed, -compiler, --low-performance

#5830 Fix precedence of `-1.x`
  app/gui/language/parser/src/lib.rs
  app/gui/language/parser/src/translation.rs
  engine/runtime/src/main/java/org/enso/compiler/TreeToIr.java
  engine/runtime/src/test/java/org/enso/compiler/EnsoCompilerTest.java
  lib/rust/parser/debug/tests/parse.rs
  lib/rust/parser/src/lexer.rs
  lib/rust/parser/src/syntax/operator.rs
  lib/rust/parser/src/syntax/token.rs
  lib/rust/parser/src/syntax/tree.rs
Labels: CI: Ready to merge, CI: Keep up to date, CI: No changelog needed, CI: Clean build required

#5906 Fix wrong placement of nodes created from dropped files.
  Cargo.lock
  app/gui/view/graph-editor/src/lib.rs
  lib/rust/ensogl/component/drop-manager/Cargo.toml
  lib/rust/ensogl/component/drop-manager/src/lib.rs
  lib/rust/ensogl/examples/drop-manager/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#5988 Fix warnings from ag-grid.
  app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js
Labels: CI: No changelog needed

#5957 Delay writing IR caches
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeComponentsTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeStdlibTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeSuggestionUpdatesTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/instrument/command/SerializeModuleCommand.java
  engine/runtime/src/main/java/org/enso/interpreter/instrument/job/BackgroundJob.java
  engine/runtime/src/main/java/org/enso/interpreter/instrument/job/SerializeModuleJob.java
  engine/runtime/src/main/java/org/enso/interpreter/instrument/job/VisualizationResult.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/SerializationManager.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/NotificationHandler.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/CommandFactory.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/JobExecutionEngine.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/JobProcessor.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/AnalyzeModuleInScopeJob.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/AnalyzeModuleJob.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/DeserializeLibrarySuggestionsJob.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/Job.scala
  engine/runtime/src/test/java/org/enso/compiler/SerializerTest.java
  lib/scala/pkg/src/main/scala/org/enso/pkg/QualifiedName.scala
Labels: CI: Ready to merge, CI: No changelog needed

#5990 Delay initialization of ZIO executors
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/ResourcesInitialization.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/resource/ZioRuntimeInitialization.scala
  engine/language-server/src/main/scala/org/enso/languageserver/effect/Exec.scala
  engine/language-server/src/main/scala/org/enso/languageserver/effect/Runtime.scala
  engine/language-server/src/test/scala/org/enso/languageserver/effect/Effects.scala
  engine/language-server/src/test/scala/org/enso/languageserver/effect/TestRuntime.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/binary/BaseBinaryServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#5865 Cognito auth 4/7 - add login
  app/ide-desktop/eslint.config.js
  app/ide-desktop/lib/client/src/config.ts
  app/ide-desktop/lib/content/src/index.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/cognito.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/common.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/confirmRegistration.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/login.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/registration.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/listen.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/auth.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/session.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/service.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/components/app.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/components/svg.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/service.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/index.tsx
Labels: CI: Ready to merge, CI: No changelog needed

#5944 Finish enabling ts-eslint
  app/ide-desktop/esbuild-watch.ts
  app/ide-desktop/eslint.config.js
  app/ide-desktop/lib/client/electron-builder-config.ts
  app/ide-desktop/lib/client/shared.ts
  app/ide-desktop/lib/client/src/authentication.ts
  app/ide-desktop/lib/client/src/bin/project-manager.ts
  app/ide-desktop/lib/client/src/bin/server.ts
  app/ide-desktop/lib/client/src/config/parser.ts
  app/ide-desktop/lib/client/src/debug.ts
  app/ide-desktop/lib/client/src/index.ts
  app/ide-desktop/lib/client/src/preload.ts
  app/ide-desktop/lib/client/tasks/computeHashes.cjs
  app/ide-desktop/lib/common/src/index.ts
  app/ide-desktop/lib/content/esbuild-config.ts
  app/ide-desktop/lib/content/src/index.ts
  app/ide-desktop/lib/content/src/project_manager.ts
  app/ide-desktop/lib/content/start.ts
  app/ide-desktop/lib/content/watch.ts
  app/ide-desktop/lib/copy-plugin/src/index.mjs
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/cognito.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/config.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/listen.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/auth.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/service.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/components/svg.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/index.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/providers/logger.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/utils.ts
  app/ide-desktop/lib/icons/src/index.js
  app/ide-desktop/lib/server/src/index.mjs
  app/ide-desktop/lib/types/enso-gui-server.d.ts
  app/ide-desktop/lib/types/modules.d.ts
  app/ide-desktop/tsconfig.json
  app/ide-desktop/utils.ts
Labels: CI: Ready to merge, CI: No changelog needed

#5866 Cognito auth 5/7 - set username
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/setUsername.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/auth.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/components/app.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/service.tsx
Labels: CI: Ready to merge, CI: No changelog needed

#6006 Apply enso-formatter
  app/gui/suggestion-database/src/mock.rs
  app/gui/view/component-browser/src/lib.rs
  build/ci_utils/src/programs/docker.rs
  lib/rust/bitmap/src/lib.rs
  lib/rust/ensogl/component/dynamic-assets/src/fonts.rs
  lib/rust/ensogl/component/dynamic-assets/src/lib.rs
  lib/rust/ensogl/component/dynamic-assets/src/shaders.rs
  lib/rust/ensogl/pack/src/assets.rs
  lib/rust/ensogl/pack/src/lib.rs
  lib/rust/parser/doc-parser/src/lib.rs
  lib/rust/parser/doc-parser/src/main.rs
Labels: CI: Ready to merge, CI: No changelog needed

#6020 Fix passing custom options to Electron app in ./run ide watch
  app/ide-desktop/lib/client/watch.ts
Labels: CI: No changelog needed

#5868 Cognito auth 7/7 - add forgot password + reset password
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/cognito.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/common.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/forgotPassword.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/login.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/registration.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/resetPassword.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/setUsername.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/auth.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/service.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/components/app.tsx
Labels: CI: No changelog needed

#5867 Cognito auth 6/7 - add signout
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/cognito.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/common.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/forgotPassword.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/login.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/registration.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/resetPassword.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/setUsername.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/config.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/listen.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/auth.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/session.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/service.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/components/app.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/components/svg.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
Labels: CI: No changelog needed

#6019 Rendering improvement/debugging support
  app/gui/config/build.rs
  app/gui/src/ide/initializer.rs
  app/ide-desktop/lib/client/src/config.ts
  app/ide-desktop/lib/client/src/index.ts
  app/ide-desktop/lib/content-config/src/config.json
  app/ide-desktop/lib/content/esbuild-config.ts
  build/build/paths.yaml
  docs/profiler/profiling.md
  lib/rust/ensogl/core/src/display/render/passes/pixel_read.rs
  lib/rust/ensogl/core/src/display/world.rs
  lib/rust/ensogl/pack/js/src/runner/config.json
Labels: CI: Ready to merge, CI: No changelog needed

#6029 Early initialize ZIO
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
Labels: CI: No changelog needed

#5976 Fix #5975
  app/ide-desktop/eslint.config.js
  app/ide-desktop/lib/content/esbuild-config.ts
  app/ide-desktop/lib/content/package.json
  app/ide-desktop/lib/content/src/index.html
  app/ide-desktop/lib/content/src/tailwind.css
  app/ide-desktop/lib/content/tailwind.config.ts
  app/ide-desktop/lib/content/tsconfig.json
  app/ide-desktop/lib/dashboard/src/authentication/package.json
  app/ide-desktop/lib/dashboard/src/authentication/src/index.tsx
  app/ide-desktop/package-lock.json
Labels: CI: No changelog needed

#5994 Deal with warnings attached to value when making widgets.
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Dialect.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Widgets.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeCallableNode.java
  test/Visualization_Tests/src/Widgets/Database_Widgets_Spec.enso
  test/Visualization_Tests/src/Widgets/Table_Widgets_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#5960 Implement recognition of qualified names in CB input
  app/gui/controller/double-representation/src/import.rs
  app/gui/src/controller/graph.rs
  app/gui/src/controller/searcher.rs
  app/gui/src/controller/searcher/action.rs
  app/gui/src/controller/searcher/component.rs
  app/gui/src/controller/searcher/input.rs
  app/gui/suggestion-database/src/entry.rs
  app/gui/view/examples/icons/src/lib.rs
  app/gui/view/graph-editor/src/component/node/action_bar.rs
Labels: CI: Ready to merge, CI: No changelog needed

#5770 Cursor aware Component Browser
  app/gui/controller/double-representation/src/import.rs
  app/gui/language/ast/impl/src/crumbs.rs
  app/gui/language/ast/impl/src/opr.rs
  app/gui/language/ast/impl/src/repr.rs
  app/gui/src/controller/graph.rs
  app/gui/src/controller/graph/executed.rs
  app/gui/src/controller/searcher.rs
  app/gui/src/controller/searcher/action.rs
  app/gui/src/controller/searcher/component.rs
  app/gui/src/controller/searcher/component/builder.rs
  app/gui/src/controller/searcher/component/hardcoded.rs
  app/gui/src/controller/searcher/input.rs
  app/gui/src/model/module.rs
  app/gui/src/model/module/plain.rs
  app/gui/src/model/project/synchronized.rs
  app/gui/src/model/undo_redo.rs
  app/gui/src/presenter/searcher.rs
  app/gui/src/presenter/searcher/provider.rs
  app/gui/src/test.rs
  app/gui/src/tests.rs
  app/gui/suggestion-database/src/entry.rs
  app/gui/view/examples/icons/src/lib.rs
  app/gui/view/graph-editor/src/component/node.rs
  app/gui/view/graph-editor/src/component/node/action_bar.rs
  app/gui/view/graph-editor/src/component/node/input/area.rs
  app/gui/view/graph-editor/src/lib.rs
  app/gui/view/src/project.rs
  lib/rust/ensogl/component/text/src/buffer.rs
  lib/rust/ensogl/component/text/src/component/text.rs
Labels: CI: Ready to merge, CI: No changelog needed

#6032 Tidy up the public module level statics
  .github/CODEOWNERS
  app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Ordering/Comparator.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Pattern_2.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Meta.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Polyglot.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Polyglot/Java.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Runtime.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Warning.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/SQL.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Common/Database_Join_Helper.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/JDBC_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Image_File_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table_Conversions.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Delimited/Delimited_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Workbook.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Aggregate_Column_Helper.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Delimited_Reader.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Delimited_Writer.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Excel_Reader.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Excel_Writer.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/File_Upload.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Helpers.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Text.enso
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/PolyglotTest.scala
  test/Tests/src/Semantic/Case_Spec.enso
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date.enso
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Polyglot.enso
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Polyglot/Java.enso
Labels: CI: Ready to merge, CI: No changelog needed

#6033 Implementation of EnsoGL predefined Rectangle shape.
  Cargo.lock
  lib/rust/ensogl/core/src/display/shape/primitive/def/class.rs
  lib/rust/ensogl/core/src/display/shape/primitive/def/modifier.rs
  lib/rust/ensogl/core/src/display/shape/primitive/glsl/shape.glsl
  lib/rust/ensogl/core/src/display/shape/primitive/shader/canvas.rs
  lib/rust/ensogl/examples/Cargo.toml
  lib/rust/ensogl/examples/built-in-shapes/Cargo.toml
  lib/rust/ensogl/examples/built-in-shapes/src/lib.rs
  lib/rust/ensogl/examples/src/lib.rs
Labels: CI: No changelog needed

#6054 Fix code generation for suggestion preview
  app/gui/src/controller/searcher.rs
Labels: CI: Ready to merge, CI: No changelog needed

#6057 Use .node-version for pinning Node.js version
  .node-version
  app/gui/docs/CONTRIBUTING.md
  build-config.yaml
  build/build/src/config.rs
  build/cli/src/main.rs
  docs/CONTRIBUTING.md
Labels: CI: Ready to merge, CI: No changelog needed

#6060 Use new Enso Hash Codes and Comparable
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Ordering.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Ordering/Comparator.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Statistics.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Day_Of_Week.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Header.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/SQL_Type.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Data/Image.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Data/Matrix.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Aggregate_Column_Helper.enso
  std-bits/base/src/main/java/org/enso/base/ObjectComparator.java
  std-bits/base/src/main/java/org/enso/base/polyglot/EnsoObjectWrapper.java
  std-bits/base/src/main/java/org/enso/base/statistics/Rank.java
  std-bits/table/src/main/java/org/enso/table/aggregations/First.java
  std-bits/table/src/main/java/org/enso/table/aggregations/Last.java
  std-bits/table/src/main/java/org/enso/table/aggregations/MinOrMax.java
  std-bits/table/src/main/java/org/enso/table/data/index/OrderedMultiValueKey.java
  std-bits/table/src/main/java/org/enso/table/data/index/UnorderedMultiValueKey.java
  std-bits/table/src/main/java/org/enso/table/data/table/Column.java
  std-bits/table/src/main/java/org/enso/table/data/table/Table.java
  std-bits/table/src/main/java/org/enso/table/data/table/join/IndexJoin.java
  std-bits/table/src/main/java/org/enso/table/data/table/join/scan/MatcherFactory.java
  std-bits/table/src/main/java/org/enso/table/data/table/join/scan/ScanJoin.java
  std-bits/table/src/main/java/org/enso/table/operations/OrderBuilder.java
  test/Table_Tests/src/Common_Table_Operations/Order_By_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
  test/Tests/src/Data/Ordering/Comparator_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#6066 Layout fixes
  lib/rust/ensogl/core/src/display/object/instance.rs
  lib/rust/ensogl/core/src/display/object/layout.rs
  lib/rust/ensogl/examples/auto-layout/src/lib.rs
  lib/rust/ensogl/examples/slider/src/lib.rs
  lib/rust/prelude/src/leak.rs
Labels: CI: No changelog needed

#6075 Use new common parse method throwing less exceptions.
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoDateTime.java
  lib/scala/common-polyglot-core-utils/src/main/java/org/enso/polyglot/common_utils/Core_Date_Utils.java
  std-bits/base/src/main/java/org/enso/base/Time_Utils.java
  std-bits/table/src/main/java/org/enso/table/expressions/ExpressionVisitorImpl.java
  std-bits/table/src/main/java/org/enso/table/parsing/DateTimeParser.java
Labels: CI: Ready to merge, CI: No changelog needed

#6035 Add tooltips to the action bar
  CHANGELOG.md
  app/gui/view/graph-editor/src/component/node/action_bar.rs
  app/gui/view/graph-editor/src/component/profiling.rs
  lib/rust/ensogl/component/toggle-button/src/lib.rs
Labels: CI: Ready to merge

#6067 Ensure new and wrapper nodes inherit UUID
  CHANGELOG.md
  engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java
  engine/runtime-with-instruments/src/test/java/org/enso/interpreter/test/NodeCountingTestInstrument.java
  engine/runtime-with-instruments/src/test/java/org/enso/interpreter/test/instrument/IncrementalUpdatesTest.java
  engine/runtime-with-instruments/src/test/java/org/enso/interpreter/test/instrument/WarningInstrumentationTest.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/FunctionCallInstrumentationNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeCallableNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeConversionNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/dispatch/InvokeFunctionNode.java
Labels: CI: Ready to merge

#6090 Treat Boolean.False as false primitive
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/atom/QualifiedAccessorNode.java
  engine/runtime/src/test/scala/org/enso/std/test/BooleanTest.scala
  project/DistributionPackage.scala
Labels: CI: Ready to merge, CI: No changelog needed

#5959 Implement Regular Expression replace and update `Text.replace` to the new API
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Match_2.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Pattern_2.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Replacer.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex_2.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Naming_Helpers.enso
  std-bits/base/src/main/java/org/enso/base/Replacer_Cache.java
  test/Table_Tests/src/In_Memory/Table_Spec.enso
  test/Tests/src/Data/Text/Regex_2_Spec.enso
  test/Tests/src/Data/Text_Spec.enso
Labels: CI: Ready to merge

#6062 Serde testing infrastructure for the Enso compiler
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/SerializationManager.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/test/java/org/enso/compiler/CompilerTest.java
  engine/runtime/src/test/java/org/enso/compiler/EnsoCompilerTest.java
  engine/runtime/src/test/java/org/enso/compiler/SerdeCompilerTest.java
  engine/runtime/src/test/resources/Fib_Test/package.yaml
  engine/runtime/src/test/resources/Fib_Test/src/Arith.enso
  engine/runtime/src/test/resources/Fib_Test/src/Main.enso
Labels: CI: Ready to merge, CI: No changelog needed

#6101 Restore mistakenly removed unit test for named arguments
  app/gui/src/controller/graph.rs
Labels: CI: Ready to merge, CI: No changelog needed

#6108 More elaborate error message for invalid text edit
  engine/language-server/src/main/scala/org/enso/languageserver/text/CollaborativeBuffer.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/TextOperationsTest.scala
  lib/scala/text-buffer/src/main/scala/org/enso/text/editing/TextEditValidationFailure.scala
  lib/scala/text-buffer/src/main/scala/org/enso/text/editing/TextEditValidator.scala
  lib/scala/text-buffer/src/test/scala/org/enso/text/editing/EditorOpsSpec.scala
  lib/scala/text-buffer/src/test/scala/org/enso/text/editing/TextEditValidatorSpec.scala
Labels: CI: Ready to merge, CI: No changelog needed

#5852 Add engine benchmark analysis tool
  tools/performance/engine-benchmarks/Engine_Benchs/package.yaml
  tools/performance/engine-benchmarks/Engine_Benchs/src/Main.enso
  tools/performance/engine-benchmarks/README.md
  tools/performance/engine-benchmarks/bench_download.py
  tools/performance/engine-benchmarks/template_jinja.html
Labels: CI: Ready to merge, CI: No changelog needed

#6107 Turn missing body in a binding into a syntax error
  engine/runtime/src/main/java/org/enso/compiler/TreeToIr.java
  engine/runtime/src/test/java/org/enso/compiler/ExecCompilerTest.java
Labels: CI: Ready to merge, CI: No changelog needed

#6003 Cognito auth 8/7 - fix prettier config; run prettier
  .prettierrc.yaml
  app/ide-desktop/esbuild-watch.ts
  app/ide-desktop/eslint.config.js
  app/ide-desktop/lib/client/bundle.ts
  app/ide-desktop/lib/client/dist.ts
  app/ide-desktop/lib/client/electron-builder-config.ts
  app/ide-desktop/lib/client/esbuild-config.ts
  app/ide-desktop/lib/client/package.json
  app/ide-desktop/lib/client/paths.ts
  app/ide-desktop/lib/client/start.ts
  app/ide-desktop/lib/client/watch.ts
  app/ide-desktop/lib/content/bundle.ts
  app/ide-desktop/lib/content/esbuild-config.ts
  app/ide-desktop/lib/content/package.json
  app/ide-desktop/lib/content/src/tailwind.css
  app/ide-desktop/lib/content/start.ts
  app/ide-desktop/lib/content/tailwind.config.ts
  app/ide-desktop/lib/content/tsconfig.json
  app/ide-desktop/lib/content/watch.ts
  app/ide-desktop/lib/copy-plugin/src/index.mjs
  app/ide-desktop/lib/dashboard/bundle.ts
  app/ide-desktop/lib/dashboard/esbuild-config.ts
  app/ide-desktop/lib/dashboard/package.json
  app/ide-desktop/lib/dashboard/src/authentication/package.json
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/common.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/confirmRegistration.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/forgotPassword.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/login.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/registration.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/resetPassword.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/setUsername.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/listen.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/auth.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/session.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/service.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/components/app.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/components/svg.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/service.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/hooks.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/http.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/index.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/providers/logger.tsx
  app/ide-desktop/lib/dashboard/src/authentication/tsconfig.json
  app/ide-desktop/lib/dashboard/src/index.html
  app/ide-desktop/lib/dashboard/src/index.tsx
  app/ide-desktop/lib/dashboard/src/serviceWorker.ts
  app/ide-desktop/lib/dashboard/src/tailwind.css
  app/ide-desktop/lib/dashboard/tailwind.config.ts
  app/ide-desktop/lib/dashboard/watch.ts
  app/ide-desktop/lib/server/package.json
  app/ide-desktop/lib/server/src/index.mjs
  app/ide-desktop/lib/server/src/live-reload.js
  app/ide-desktop/lib/types/enso-gui-server.d.ts
  app/ide-desktop/lib/types/globals.d.ts
  app/ide-desktop/lib/types/modules.d.ts
  app/ide-desktop/package-lock.json
  app/ide-desktop/package.json
  app/ide-desktop/tsconfig.json
Labels: CI: Ready to merge, CI: No changelog needed

#5983 Decouple node edit mode from ports
  app/gui/language/span-tree/src/generate.rs
  app/gui/language/span-tree/src/node/kind.rs
  app/gui/src/presenter/graph.rs
  app/gui/view/graph-editor/src/component/node.rs
  app/gui/view/graph-editor/src/component/node/expression.rs
  app/gui/view/graph-editor/src/component/node/input/area.rs
  app/gui/view/graph-editor/src/lib.rs
  app/gui/view/src/project.rs
  integration-test/tests/graph_editor.rs
  lib/rust/ensogl/component/text/src/component/text.rs
  lib/rust/ensogl/core/src/application/command.rs
  lib/rust/frp/src/nodes.rs
Labels: CI: Ready to merge, CI: No changelog needed

#6127 Revert "Cognito auth 8/7 - fix prettier config; run prettier (#6003)"
  .prettierrc.yaml
  app/ide-desktop/esbuild-watch.ts
  app/ide-desktop/eslint.config.js
  app/ide-desktop/lib/client/bundle.ts
  app/ide-desktop/lib/client/dist.ts
  app/ide-desktop/lib/client/electron-builder-config.ts
  app/ide-desktop/lib/client/esbuild-config.ts
  app/ide-desktop/lib/client/package.json
  app/ide-desktop/lib/client/paths.ts
  app/ide-desktop/lib/client/start.ts
  app/ide-desktop/lib/client/watch.ts
  app/ide-desktop/lib/content/bundle.ts
  app/ide-desktop/lib/content/esbuild-config.ts
  app/ide-desktop/lib/content/package.json
  app/ide-desktop/lib/content/src/tailwind.css
  app/ide-desktop/lib/content/start.ts
  app/ide-desktop/lib/content/tailwind.config.ts
  app/ide-desktop/lib/content/tsconfig.json
  app/ide-desktop/lib/content/watch.ts
  app/ide-desktop/lib/copy-plugin/src/index.mjs
  app/ide-desktop/lib/dashboard/bundle.ts
  app/ide-desktop/lib/dashboard/esbuild-config.ts
  app/ide-desktop/lib/dashboard/package.json
  app/ide-desktop/lib/dashboard/public/index.html
  app/ide-desktop/lib/dashboard/src/authentication/package.json
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/common.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/confirmRegistration.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/forgotPassword.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/login.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/registration.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/resetPassword.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/setUsername.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/listen.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/auth.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/session.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/service.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/components/app.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/components/svg.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/service.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/hooks.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/http.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/index.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/providers/logger.tsx
  app/ide-desktop/lib/dashboard/src/authentication/tsconfig.json
  app/ide-desktop/lib/dashboard/src/index.tsx
  app/ide-desktop/lib/dashboard/src/serviceWorker.ts
  app/ide-desktop/lib/dashboard/src/tailwind.css
  app/ide-desktop/lib/dashboard/tailwind.config.ts
  app/ide-desktop/lib/dashboard/watch.ts
  app/ide-desktop/lib/server/package.json
  app/ide-desktop/lib/server/src/index.mjs
  app/ide-desktop/lib/server/src/live-reload.js
  app/ide-desktop/lib/types/enso-gui-server.d.ts
  app/ide-desktop/lib/types/globals.d.ts
  app/ide-desktop/lib/types/modules.d.ts
  app/ide-desktop/package-lock.json
  app/ide-desktop/package.json
  app/ide-desktop/tsconfig.json
Labels: CI: No changelog needed

#6128 Always print stacktrace to provide some guidance of what is going on
  engine/runner/src/main/scala/org/enso/runner/Main.scala
Labels: CI: Ready to merge, CI: No changelog needed

#6097 Make tooltips more visually pleasing
  CHANGELOG.md
  lib/rust/ensogl/app/theme/hardcoded/src/lib.rs
  lib/rust/ensogl/component/label/src/lib.rs
  lib/rust/ensogl/component/tooltip/src/lib.rs
Labels: CI: Ready to merge

#6123 Report errors when generating indexes
  build.sbt
  engine/runner/src/main/scala/org/enso/runner/Main.scala
  engine/runtime/src/main/java/org/enso/compiler/Cache.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/TopLevelScope.java
  project/DistributionPackage.scala
Labels: CI: Ready to merge, CI: No changelog needed

#6116 Implement Regular Expression split and update Text.split to the new API
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Index_Sub_Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Pattern_2.enso
  test/Tests/src/Data/Text/Regex_2_Spec.enso
  test/Tests/src/Data/Text_Spec.enso
Labels: CI: Ready to merge

#6087 add alignment setting per shape system
  lib/rust/ensogl/core/src/display/object/instance.rs
  lib/rust/ensogl/core/src/display/shape/compound/rectangle.rs
  lib/rust/ensogl/core/src/display/shape/primitive/system.rs
  lib/rust/ensogl/core/src/display/symbol/gpu/geometry/compound/screen.rs
  lib/rust/ensogl/core/src/display/symbol/gpu/geometry/compound/sprite.rs
  lib/rust/ensogl/core/src/lib.rs
  lib/rust/ensogl/examples/auto-layout/src/lib.rs
  lib/rust/ensogl/examples/dom-symbols/src/lib.rs
  lib/rust/ensogl/examples/sprite-system-benchmark/src/lib.rs
  lib/rust/ensogl/examples/sprite-system/src/lib.rs
  lib/rust/types/src/topology.rs
Labels: CI: Ready to merge, CI: No changelog needed

#6148 When renaming the project clean old modules instead of updating
  engine/language-server/src/main/scala/org/enso/languageserver/refactoring/ProjectNameChangedEvent.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/refactoring/RenameProjectHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/SuggestionsHandlerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeSuggestionUpdatesTest.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/RecomputeContextCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/RenameProjectCmd.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/SuggestionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlSuggestionsRepo.scala
  lib/scala/searcher/src/test/scala/org/enso/searcher/sql/SuggestionsRepoTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#6157 Compute column widths based on content of column.
  app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js
Labels: CI: Ready to merge, CI: No changelog needed

#6132 Fix prettier config; run prettier
  .prettierrc.yaml
  app/ide-desktop/lib/content/src/index.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/common.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/confirmRegistration.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/forgotPassword.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/login.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/registration.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/resetPassword.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/setUsername.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/listen.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/auth.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/session.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/service.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/components/app.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/components/svg.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/service.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/hooks.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/http.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/index.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/providers/logger.tsx
  app/ide-desktop/lib/dashboard/src/index.tsx
Labels: CI: No changelog needed

#6034 Convert dashboard to use esbuild
  app/ide-desktop/esbuild-watch.ts
  app/ide-desktop/eslint.config.js
  app/ide-desktop/lib/client/bundle.ts
  app/ide-desktop/lib/client/dist.ts
  app/ide-desktop/lib/client/electron-builder-config.ts
  app/ide-desktop/lib/client/esbuild-config.ts
  app/ide-desktop/lib/client/package.json
  app/ide-desktop/lib/client/paths.ts
  app/ide-desktop/lib/client/start.ts
  app/ide-desktop/lib/client/watch.ts
  app/ide-desktop/lib/content/bundle.ts
  app/ide-desktop/lib/content/esbuild-config.ts
  app/ide-desktop/lib/content/package.json
  app/ide-desktop/lib/content/src/index.ts
  app/ide-desktop/lib/content/src/tailwind.css
  app/ide-desktop/lib/content/start.ts
  app/ide-desktop/lib/content/tailwind.config.ts
  app/ide-desktop/lib/content/tsconfig.json
  app/ide-desktop/lib/content/watch.ts
  app/ide-desktop/lib/copy-plugin/src/index.mjs
  app/ide-desktop/lib/dashboard/bundle.ts
  app/ide-desktop/lib/dashboard/esbuild-config.ts
  app/ide-desktop/lib/dashboard/package.json
  app/ide-desktop/lib/dashboard/src/authentication/package.json
  app/ide-desktop/lib/dashboard/src/authentication/src/index.tsx
  app/ide-desktop/lib/dashboard/src/authentication/tsconfig.json
  app/ide-desktop/lib/dashboard/src/index.html
  app/ide-desktop/lib/dashboard/src/index.tsx
  app/ide-desktop/lib/dashboard/src/serviceWorker.ts
  app/ide-desktop/lib/dashboard/src/tailwind.css
  app/ide-desktop/lib/dashboard/tailwind.config.ts
  app/ide-desktop/lib/dashboard/watch.ts
  app/ide-desktop/lib/server/package.json
  app/ide-desktop/lib/server/src/index.mjs
  app/ide-desktop/lib/server/src/live-reload.js
  app/ide-desktop/lib/types/enso-gui-server.d.ts
  app/ide-desktop/lib/types/globals.d.ts
  app/ide-desktop/lib/types/modules.d.ts
  app/ide-desktop/package-lock.json
  app/ide-desktop/package.json
  app/ide-desktop/tsconfig.json
Labels: CI: No changelog needed

#6153 Date/time support for Postgres. Year/month/day operations on Columns.
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Of_Day.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Column_Fetcher.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Statement_Setter.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Type/Value_Type.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Java_Exports.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Extensions.enso
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoTimeOfDay.java
  std-bits/database/src/main/java/org/enso/database/JDBCUtils.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/UnaryIntegerOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/DateStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/DateTimeStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/Storage.java
  test/Table_Tests/src/Common_Table_Operations/Aggregate_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Date_Time_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Expression_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Main.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Database/SQLite_Spec.enso
Labels: CI: Ready to merge, CI: Clean build required
