Repository enso-org/enso, pull requests merged in 2023-09, with the labels that each got.

#7697 Standardization of Vector.sort array access
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/ArrayLikeAtNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/ArrayLikeLengthNode.java
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#7634 Change layout of local library search path in order to be able to move `Round_Spec.enso` back to `Tests`
  CHANGELOG.md
  docs/libraries/editions.md
  docs/libraries/sharing.md
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/libraries/EditionReferenceResolver.scala
  engine/language-server/src/main/scala/org/enso/languageserver/libraries/LocalLibraryManager.scala
  engine/language-server/src/main/scala/org/enso/languageserver/libraries/handler/LibraryPreinstallHandler.scala
  engine/language-server/src/test/scala/org/enso/languageserver/libraries/LocalLibraryManagerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/LibrariesTest.scala
  engine/runner/src/main/scala/org/enso/runner/DependencyPreinstaller.scala
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/DefaultPackageRepository.scala
  lib/scala/distribution-manager/src/main/scala/org/enso/distribution/DistributionManager.scala
  lib/scala/library-manager/src/main/scala/org/enso/librarymanager/DefaultLibraryProvider.scala
  lib/scala/library-manager/src/main/scala/org/enso/librarymanager/LibraryLocations.scala
  lib/scala/library-manager/src/main/scala/org/enso/librarymanager/LibraryResolver.scala
  lib/scala/library-manager/src/main/scala/org/enso/librarymanager/local/DefaultLocalLibraryProvider.scala
  lib/scala/library-manager/src/main/scala/org/enso/librarymanager/local/LocalLibraryProvider.scala
  lib/scala/library-manager/src/test/resources/org/enso/librarymanager/local/secondary-test-library-path/library_in_both_dirs/package.yaml
  lib/scala/library-manager/src/test/resources/org/enso/librarymanager/local/secondary-test-library-path/new_folder1/package.yaml
  lib/scala/library-manager/src/test/resources/org/enso/librarymanager/local/test-library-path/Simple_Library_1/package.yaml
  lib/scala/library-manager/src/test/resources/org/enso/librarymanager/local/test-library-path/Simple_Library_2/package.yaml
  lib/scala/library-manager/src/test/resources/org/enso/librarymanager/local/test-library-path/ambiguous1/package.yaml
  lib/scala/library-manager/src/test/resources/org/enso/librarymanager/local/test-library-path/ambiguous2/package.yaml
  lib/scala/library-manager/src/test/resources/org/enso/librarymanager/local/test-library-path/library_in_both_dirs/package.yaml
  lib/scala/library-manager/src/test/scala/org/enso/librarymanager/LibraryResolverSpec.scala
  lib/scala/library-manager/src/test/scala/org/enso/librarymanager/local/LocalLibraryProviderSpec.scala
  lib/scala/pkg/src/main/scala/org/enso/pkg/Config.scala
  lib/scala/testkit/src/main/scala/org/enso/testkit/WithTemporaryDirectory.scala
  test/Examples_Tests/package.yaml
  test/Table_Tests/package.yaml
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Tests/src/Data/Numbers_Spec.enso
  test/Tests/src/Data/Round_Spec.enso
Labels: CI: Ready to merge

#7696 Add Vue gui project
  .github/CODEOWNERS
  app/gui2/.eslintrc.cjs
  app/gui2/.gitignore
  app/gui2/.prettierrc.json
  app/gui2/.vscode/extensions.json
  app/gui2/README.md
  app/gui2/e2e/tsconfig.json
  app/gui2/e2e/vue.spec.ts
  app/gui2/env.d.ts
  app/gui2/index.html
  app/gui2/package-lock.json
  app/gui2/package.json
  app/gui2/playwright.config.ts
  app/gui2/postcss.config.js
  app/gui2/public/favicon.ico
  app/gui2/shared/yjs-model.ts
  app/gui2/src/App.vue
  app/gui2/src/assets/base.css
  app/gui2/src/assets/main.css
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/components/GraphEdge.vue
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphNode.vue
  app/gui2/src/components/HelloWorld.vue
  app/gui2/src/components/NodeSpan.vue
  app/gui2/src/components/__tests__/HelloWorld.spec.ts
  app/gui2/src/main.ts
  app/gui2/src/stores/counter.ts
  app/gui2/src/stores/graph.ts
  app/gui2/src/stores/project.ts
  app/gui2/src/stores/rect.ts
  app/gui2/src/template.vue
  app/gui2/src/util/animation.ts
  app/gui2/src/util/assert.ts
  app/gui2/src/util/crdt.ts
  app/gui2/src/util/events.ts
  app/gui2/src/util/navigator.ts
  app/gui2/src/util/opt.ts
  app/gui2/src/util/reactivity.ts
  app/gui2/src/util/vec2.ts
  app/gui2/src/views/AboutView.vue
  app/gui2/src/views/HomeView.vue
  app/gui2/src/views/ProjectView.vue
  app/gui2/tsconfig.app.json
  app/gui2/tsconfig.json
  app/gui2/tsconfig.node.json
  app/gui2/tsconfig.vitest.json
  app/gui2/vite.config.ts
  app/gui2/vitest.config.ts
Labels: CI: Ready to merge, CI: Keep up to date, CI: No changelog needed, CI: Clean build required

#7690 Fix double clicking projects to open them
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectNameColumn.tsx
Labels: CI: Ready to merge, CI: No changelog needed

#7670 Fix atom types in dropdowns.
  CHANGELOG.md
  Cargo.lock
  app/gui/docs/product/shortcuts.md
  app/gui/src/controller/searcher.rs
  app/gui/src/presenter/project.rs
  app/gui/src/presenter/searcher/component_browser.rs
  app/gui/suggestion-database/Cargo.toml
  app/gui/suggestion-database/src/entry.rs
  app/gui/suggestion-database/src/lib.rs
  app/gui/view/src/project.rs
  lib/rust/font/src/lib.rs
  lib/rust/parser/doc-parser/Cargo.toml
  lib/rust/parser/doc-parser/src/doc_sections.rs
  lib/rust/parser/doc-parser/src/lib.rs
  lib/rust/text/Cargo.toml
  lib/rust/text/src/index.rs
  lib/rust/text/src/unit.rs
  lib/rust/types/src/unit.rs
Labels: CI: Ready to merge

#7727 Delay check of suspended arguments until they are about to be computed
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/argument/ReadArgumentCheckNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/unboxing/SuspendedFieldGetterNode.java
  engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java
Labels: CI: No changelog needed

#7744 Fix console output for native image
  docs/infrastructure/logging.md
  engine/launcher/src/main/resources/META-INF/native-image/org/enso/launcher/serialization-config.json
  lib/scala/project-manager/src/main/resources/META-INF/native-image/org/enso/projectmanager/serialization-config.json
Labels: CI: No changelog needed

#7724 Fix re-exports of type constructors
  engine/runtime/src/main/java/org/enso/compiler/context/ExportsMap.java
  engine/runtime/src/main/scala/org/enso/compiler/SerializationManager.scala
  engine/runtime/src/test/java/org/enso/compiler/SerializationManagerTest.java
  engine/runtime/src/test/scala/org/enso/compiler/test/CompilerTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/InterpreterTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#7721 Fix sbt task that creates GraalVM package
  project/DistributionPackage.scala
Labels: CI: No changelog needed

#7707 Bump electron version
  app/ide-desktop/lib/client/package.json
  app/ide-desktop/package-lock.json
Labels: CI: Ready to merge, CI: No changelog needed

#7599 Collect stdlib benchmarks results
  .gitignore
  tools/performance/engine-benchmarks/README.md
  tools/performance/engine-benchmarks/bench_download.py
  tools/performance/engine-benchmarks/template_jinja.html
  tools/performance/engine-benchmarks/templates/styles.css
  tools/performance/engine-benchmarks/templates/template_jinja.html
Labels: CI: Ready to merge, CI: No changelog needed

#7709 Implement `Table.delete_rows`.
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Runtime.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Extensions/Upload_Database_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Extensions/Upload_In_Memory_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/IR/Query.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload_Table.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Test_Reporter.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/generic/GetExecutableNameNode.java
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Database/Redshift_Spec.enso
  test/Table_Tests/src/Database/SQLite_Spec.enso
  test/Table_Tests/src/Database/Upload_Spec.enso
Labels: CI: Ready to merge

#7762 Display overriden non-default values
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/Function.java
  test/Tests/src/Semantic/Error_Spec.enso
Labels: CI: No changelog needed

#7592 Async execution controls
  app/ide-desktop/lib/assets/play2.svg
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/backend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetsTable.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/modal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/permissionSelector.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectIcon.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/events/assetEvent.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/remoteBackend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/shortcuts.tsx
  app/ide-desktop/lib/dashboard/tailwind.config.ts
Labels: CI: Ready to merge, CI: No changelog needed

#7764 Use only a single node color (blue)
  app/gui/view/graph-editor/src/component/node.rs
Labels: CI: Ready to merge, CI: No changelog needed

#7747 Fix unnecessary `/versions` calls
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/remoteBackend.ts
Labels: CI: Ready to merge, CI: No changelog needed

#7710 Rename trash to delete; fix search bar autofocus
  app/ide-desktop/lib/dashboard/src/authentication/src/components/app.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetsTable.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/localStorage.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/shortcuts.tsx
Labels: CI: Ready to merge, CI: No changelog needed

#7726 Vue project title, execution mode selector, and breadcrumbs
  app/gui2/.prettierignore
  app/gui2/package-lock.json
  app/gui2/package.json
  app/gui2/src/assets/base.css
  app/gui2/src/assets/icons.svg
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/components/ExecutionModeSelector.vue
  app/gui2/src/components/GraphEdge.vue
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphNode.vue
  app/gui2/src/components/NavBar.vue
  app/gui2/src/components/NavBreadcrumb.vue
  app/gui2/src/components/NavBreadcrumbs.vue
  app/gui2/src/components/ProjectTitle.vue
  app/gui2/src/components/SvgIcon.vue
  app/gui2/src/components/TopBar.vue
  app/gui2/src/util/events.ts
Labels: CI: Ready to merge, CI: No changelog needed

#7751 Fix `on` argument for Vector.sort
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java
  test/Tests/src/Data/Vector_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#7763 Fixes issue writing to a dry run Excel File
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Excel_Writer.enso
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoFile.java
  test/Table_Tests/src/IO/Excel_Spec.enso
  test/Tests/src/System/File_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#7718 First iteration of Component Browser Panel in Vue
  app/gui2/src/assets/icons.svg
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/components/ExecutionModeSelector.vue
  app/gui2/src/components/NavBar.vue
  app/gui2/src/components/NavBreadcrumbs.vue
  app/gui2/src/components/SvgIcon.vue
  app/gui2/src/components/ToggleIcon.vue
  app/gui2/src/components/TopBar.vue
  app/gui2/src/main.ts
  app/gui2/src/stores/components.ts
  app/gui2/src/util/animation.ts
  app/gui2/src/util/navigator.ts
Labels: CI: Ready to merge, CI: No changelog needed

#7772 Fix query parameters in `bench_download.py` tool
  tools/performance/engine-benchmarks/bench_download.py
Labels: CI: Ready to merge, CI: No changelog needed

#7774 Fix implicit conversion of foreign JS object to Text
  engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/JsInteropTest.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/Atom.java
Labels: CI: No changelog needed

#7781 Benchmark shall loop correctly
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/ListBenchmarks.java
Labels: CI: No changelog needed

#7769 Support runtime checks of intersection types
  CHANGELOG.md
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/type/Set.scala
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/argument/ReadArgumentCheckNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/argument/ReadArgumentNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/resolver/MethodResolverNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/GetAnnotationNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/IsValueOfTypeNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/UnresolvedConversion.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/UnresolvedSymbol.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/argument/ArgumentDefinition.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/AtomConstructor.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/unboxing/Layout.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoMultiValue.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Type.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicException.java
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DataflowAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/TypeFunctions.scala
  engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/SugaredTypeFunctionsTest.scala
  test/Tests/src/Semantic/Conversion_Spec.enso
Labels: CI: Clean build required

#7778 Workaround crashes during regular execution
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsAtomNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/GetTypeMethodsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/HashCodeNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/HashCallbackNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/PatchedModuleValues.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/Atom.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Type.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  engine/runtime/src/test/java/org/enso/compiler/SerdeCompilerTest.java
Labels: CI: Ready to merge, CI: No changelog needed

#7782 Do not lose focus when clicking fullscreen visualization
  app/gui/view/graph-editor/src/component/visualization/container.rs
Labels: CI: Ready to merge, CI: No changelog needed

#7794 Fix flaky project rename test
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/refactoring/RenameProjectHandler.scala
Labels: CI: Ready to merge, CI: No changelog needed

#7756 Log visualization expressions generated by IDE
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/ModifyVisualizationCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/UpsertVisualizationJob.scala
Labels: CI: Ready to merge, CI: No changelog needed

#7728 Vue widgets
  app/gui2/src/App.vue
  app/gui2/src/assets/base.css
  app/gui2/src/assets/icons.svg
  app/gui2/src/assets/icons/sort_descending.svg
  app/gui2/src/components/GraphNode.vue
  app/gui2/src/components/NavBreadcrumb.vue
  app/gui2/src/components/widgets/CheckboxWidget.vue
  app/gui2/src/components/widgets/DropdownWidget.vue
  app/gui2/src/components/widgets/PlaceholderWidget.vue
  app/gui2/src/components/widgets/SliderWidget.vue
  app/gui2/src/util/events.ts
Labels: CI: Ready to merge, CI: No changelog needed

#7803 Fix log output for suggestions' tests
  engine/language-server/src/test/scala/org/enso/languageserver/search/SuggestionsHandlerSpec.scala
Labels: CI: Ready to merge, CI: No changelog needed

#7798 Fix visualization closing when cmd shortcut is pressed
  app/gui/view/graph-editor/src/component/node.rs
  app/gui/view/graph-editor/src/component/visualization/container.rs
Labels: CI: Ready to merge, CI: No changelog needed

#7808 Moving numpy check into test/Examples_Tests
  test/Examples_Tests/src/Main.enso
  test/Examples_Tests/src/Python_Examples_Spec.enso
  test/Tests/src/System/Process_Spec.enso
Labels: CI: No changelog needed

#7662 Context restoration
  CHANGELOG.md
  app/gui/docs/product/shortcuts.md
  app/gui/src/presenter/project.rs
  lib/rust/ensogl/component/text/src/font.rs
  lib/rust/ensogl/component/text/src/font/glyph.rs
  lib/rust/ensogl/core/Cargo.toml
  lib/rust/ensogl/core/src/display/render/composer.rs
  lib/rust/ensogl/core/src/display/render/pass.rs
  lib/rust/ensogl/core/src/display/render/passes/cache_shapes.rs
  lib/rust/ensogl/core/src/display/render/passes/pixel_read.rs
  lib/rust/ensogl/core/src/display/render/passes/screen.rs
  lib/rust/ensogl/core/src/display/render/passes/symbols.rs
  lib/rust/ensogl/core/src/display/render/pipeline.rs
  lib/rust/ensogl/core/src/display/scene.rs
  lib/rust/ensogl/core/src/display/symbol/gpu.rs
  lib/rust/ensogl/core/src/display/symbol/gpu/geometry/compound/screen.rs
  lib/rust/ensogl/core/src/display/symbol/gpu/geometry/compound/sprite.rs
  lib/rust/ensogl/core/src/display/symbol/gpu/geometry/primitive/mesh.rs
  lib/rust/ensogl/core/src/display/symbol/gpu/registry.rs
  lib/rust/ensogl/core/src/display/symbol/gpu/shader.rs
  lib/rust/ensogl/core/src/display/world.rs
  lib/rust/ensogl/core/src/gui/component.rs
  lib/rust/ensogl/core/src/system/gpu.rs
  lib/rust/ensogl/core/src/system/gpu/context.rs
  lib/rust/ensogl/core/src/system/gpu/context/extension.rs
  lib/rust/ensogl/core/src/system/gpu/context/profiler.rs
  lib/rust/ensogl/core/src/system/gpu/data/buffer.rs
  lib/rust/ensogl/core/src/system/gpu/data/texture.rs
  lib/rust/ensogl/core/src/system/gpu/data/texture/class.rs
  lib/rust/ensogl/core/src/system/gpu/data/texture/storage.rs
  lib/rust/ensogl/core/src/system/gpu/data/texture/storage/gpu_only.rs
  lib/rust/ensogl/core/src/system/gpu/data/texture/storage/owned.rs
  lib/rust/ensogl/core/src/system/gpu/data/texture/storage/remote_image.rs
  lib/rust/ensogl/core/src/system/gpu/data/texture/types/internal_format.rs
  lib/rust/ensogl/core/src/system/gpu/data/texture/types/relations.rs
  lib/rust/ensogl/core/src/system/gpu/data/uniform.rs
  lib/rust/ensogl/core/src/system/gpu/shader/compiler.rs
  lib/rust/ensogl/examples/custom-shape-system/src/lib.rs
Labels: CI: Ready to merge

#7812 Send suggestions database on request
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistry.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/SuggestionsHandlerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/SuggestionsHandlerEventsTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#7659 expressionUpdates do not contain Method Pointer of operators
  engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/SectionsToBinOp.scala
  engine/runtime/src/test/java/org/enso/compiler/CompilerTest.java
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/SectionsToBinOpTest.scala
  test/Tests/src/Data/Text/Regex_Spec.enso
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso
Labels: CI: Ready to merge, CI: No changelog needed

#7811 Cleanup code in IdExecutionInstrument
  build.sbt
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/IdExecutionService.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionCallbacks.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java
Labels: CI: Ready to merge, CI: No changelog needed

#7817 Throw UnsupportedMessageException when loosing BigInteger precision
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/AddNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/number/EnsoBigInteger.java
  test/Tests/src/Data/Numbers_Spec.enso
Labels: CI: No changelog needed

#7800 Fix Esc not closing CB
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/shortcuts.tsx
Labels: CI: Ready to merge, CI: No changelog needed

#7810 Stable order for filtered components
  app/gui/src/controller/searcher/component.rs
  app/gui/src/controller/searcher/component/builder.rs
Labels: CI: Ready to merge, CI: No changelog needed

#7793 Do not suppress panic exception in runtime type check
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeErrorsTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/argument/ReadArgumentCheckNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EnsoProjectNode.java
  engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java
Labels: CI: No changelog needed

#7771 Download single edition by name
  lib/scala/distribution-manager/src/main/scala/org/enso/distribution/DistributionManager.scala
  lib/scala/distribution-manager/src/main/scala/org/enso/distribution/config/GlobalConfig.scala
  lib/scala/edition-updater/src/main/scala/org/enso/editions/updater/EditionUpdater.scala
  lib/scala/edition-updater/src/main/scala/org/enso/editions/updater/UpdatingEditionProvider.scala
Labels: CI: Ready to merge, CI: No changelog needed

#7700 New Data.post for sending a payload to a Web API
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Form.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Header.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Request.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Request_Body.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Response_Body.enso
  distribution/lib/Standard/Examples/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Searcher/0.0.0-dev/src/Network.enso
  distribution/lib/Standard/Searcher/0.0.0-dev/src/Network/Http.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Execution_Context_Helpers.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Extensions.enso
  docs/CONTRIBUTING.md
  test/Table_Tests/src/Database/Common/Names_Length_Limits_Spec.enso
  test/Table_Tests/src/Database/Upload_Spec.enso
  test/Tests/data/sample.png
  test/Tests/src/Network/Http/Request_Spec.enso
  test/Tests/src/Network/Http_Spec.enso
  test/Tests/src/System/File_Spec.enso
  tools/simple-httpbin/src/main/java/org/enso/shttp/DummyHandler.java
  tools/simple-httpbin/src/main/java/org/enso/shttp/HttpMethod.java
  tools/simple-httpbin/src/main/java/org/enso/shttp/SimpleHTTPBin.java
Labels: CI: Ready to merge, CI: Clean build required

#6966 Espresso support with most recent Enso@GraalVM
  .vscode/settings.json
  CHANGELOG.md
  build.sbt
  docs/infrastructure/native-image.md
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/runner/src/main/scala/org/enso/runner/ContextFactory.scala
  engine/runtime/src/main/java/org/enso/interpreter/node/ExpressionNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/function/StatementNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/resolver/HostMethodCallNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/java/AddToClassPathNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/java/LookupClassNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/literal/PatchableLiteralNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/DebugLocalScope.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/DefaultPackageRepository.scala
  project/NativeImage.scala
  test/Tests/src/Data/Time/Time_Zone_Spec.enso
Labels: CI: Keep up to date, -compiler, -libs

#7711 Eager macro resolution.
  lib/rust/parser/debug/tests/parse.rs
  lib/rust/parser/debug/tools/parse_all_enso_files.sh
  lib/rust/parser/src/lib.rs
  lib/rust/parser/src/macros.rs
  lib/rust/parser/src/macros/built_in.rs
  lib/rust/parser/src/macros/resolver.rs
  lib/rust/parser/src/main.rs
  lib/rust/parser/src/syntax/item.rs
  lib/rust/parser/src/syntax/operator.rs
  lib/rust/parser/src/syntax/tree.rs
Labels: CI: Ready to merge, CI: No changelog needed

#7831 Static parameter in search/completion request affects only methods
  docs/language-server/protocol-language-server.md
  engine/language-server/src/test/scala/org/enso/languageserver/search/SuggestionsHandlerSpec.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlSuggestionsRepo.scala
  lib/scala/searcher/src/test/scala/org/enso/searcher/sql/SuggestionsRepoTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#7780 Avoid StackOverflow when comparing unknown foreign objects
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsComplexNode.java
  test/Examples_Tests/src/Python_Examples_Spec.enso
  test/Tests/polyglot-sources/enso-test-java-helpers/src/main/java/org/enso/base_test_helpers/IntHolderEquals.java
  test/Tests/src/Data/Vector_Spec.enso
  test/Tests/src/Semantic/Equals_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#7804 Fitering entries in Vue IDE + suggestion database mock
  app/gui2/package-lock.json
  app/gui2/package.json
  app/gui2/src/App.vue
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/components/ComponentBrowser/__tests__/component.test.ts
  app/gui2/src/components/ComponentBrowser/__tests__/filtering.test.ts
  app/gui2/src/components/ComponentBrowser/component.ts
  app/gui2/src/components/ComponentBrowser/filtering.ts
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/SvgIcon.vue
  app/gui2/src/components/__tests__/HelloWorld.spec.ts
  app/gui2/src/stores/components.ts
  app/gui2/src/stores/suggestionDatabase/entry.ts
  app/gui2/src/stores/suggestionDatabase/index.ts
  app/gui2/src/util/array.ts
  app/gui2/src/util/assert.ts
  app/gui2/src/util/compare.ts
  app/gui2/src/util/events.ts
  app/gui2/src/util/qualifiedName.ts
  app/gui2/tsconfig.app.json
  app/gui2/tsconfig.vitest.json
  app/gui2/vite.config.ts
  app/gui2/vitest.config.ts
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#7848 Accept type argument in instance method signatures
  engine/runtime/src/main/scala/org/enso/compiler/data/BindingsMap.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/BindingAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/FullyQualifiedNames.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/TypeNames.scala
  engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/BindingAnalysisTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/MethodDefinitionsTest.scala
Labels: CI: No changelog needed

#7776 S3 Read Access, Input Stream based reading
  CHANGELOG.md
  build/build/src/paths.rs
  distribution/lib/Standard/AWS/0.0.0-dev/src/Database/Redshift/Redshift_Details.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/Internal/Auth.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Locale.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Map.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/HTTP_Error.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Response.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Response_Body.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/Existing_File_Behavior.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File_Format.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/Input_Stream.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/Output_Stream.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Postgres_Details.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/SQLite_Details.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Column_Fetcher.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Helpers.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Pgpass.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload_Table.enso
  distribution/lib/Standard/Examples/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Google_Api/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Type/Enso_Types.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Type/Storage.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Type/Value_Type_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Delimited/Delimited_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Workbook.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Aggregate_Column_Helper.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Delimited_Reader.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Delimited_Writer.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Excel_Reader.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Scatter_Plot.enso
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoFile.java
  std-bits/aws/src/main/java/org/enso/aws/file_system/S3FileSystemSPI.java
  std-bits/base/src/main/java/org/enso/base/file_system/FileSystemSPI.java
  test/AWS_Tests/package.yaml
  test/AWS_Tests/src/Main.enso
  test/AWS_Tests/src/S3_Spec.enso
  test/Examples_Tests/src/Examples_Spec.enso
Labels: CI: Ready to merge

#7849 Avoid duplicated conversion & search target type scope
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Request_Body.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/argument/ReadArgumentCheckNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java
  test/Tests/src/Network/Http_Spec.enso
  test/Tests/src/Semantic/Conversion_Spec.enso
Labels: CI: No changelog needed

#7725 Fix issue 3140 case insensitive collisions
  project/src/main/scala/licenses/report/Review.scala
  tools/legal-review/engine/reviewed-licenses/Apache_License_v2.0
  tools/legal-review/project-manager/reviewed-licenses/Apache_License_v2.0
Labels: CI: No changelog needed

#7845 Fix static methods in dropdowns
  .prettierignore
  app/gui/src/controller/graph/executed.rs
  app/gui/src/controller/graph/widget.rs
  app/gui/src/controller/graph/widget/configuration.rs
  app/gui/src/test.rs
  app/gui/suggestion-database/src/entry.rs
  lib/rust/ensogl/core/src/display/render/passes/cache_shapes.rs
  lib/rust/ensogl/core/src/display/render/passes/screen.rs
  lib/rust/ensogl/core/src/display/scene.rs
  lib/rust/ensogl/core/src/display/symbol/gpu.rs
  lib/rust/ensogl/core/src/display/world.rs
  lib/rust/ensogl/core/src/system/gpu/data/texture.rs
Labels: CI: Ready to merge, CI: No changelog needed

#7862 Fix API representation of conversion suggestion
  engine/language-server/src/main/scala/org/enso/languageserver/search/SearchProtocol.scala
Labels: CI: Ready to merge, CI: No changelog needed

#7860 Upgrading to Frgaal compiler 20.0.1
  engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java
  project/FrgaalJavaCompiler.scala
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/arithmetic/NumericBinaryOpImplementation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/comparisons/NumericComparison.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/helpers/DoubleArrayAdapter.java
Labels: CI: No changelog needed

#7855 Adjusting to GraalVM for JDK21+
  build.sbt
  build/build/src/engine/context.rs
  project/CopyTruffleJAR.scala
  project/GraalVersionCheck.scala
Labels: CI: Ready to merge, CI: No changelog needed

#7846 Small wins in Engine CI job execution
  build/build/src/engine.rs
  build/build/src/engine/context.rs
  build/cli/src/lib.rs
Labels: CI: No changelog needed

#7806 Add CodeEditor component to GUI2
  app/gui2/package.json
  app/gui2/src/components/CodeEditor.vue
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/main.ts
  app/gui2/src/stores/graph.ts
  app/gui2/src/stores/project.ts
  package-lock.json
Labels: CI: Ready to merge, CI: No changelog needed

#7802 Minor changes to the top bar styles
  app/gui2/src/assets/base.css
  app/gui2/src/assets/main.css
  app/gui2/src/components/ExecutionModeSelector.vue
  app/gui2/src/components/GraphNode.vue
  app/gui2/src/components/NavBreadcrumb.vue
  app/gui2/src/components/ProjectTitle.vue
Labels: CI: Ready to merge, CI: No changelog needed

#7896 Fix password validation; add autocomplete attributes
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/forgotPassword.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/input.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/login.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/registration.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/resetPassword.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/setUsername.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/changePasswordModal.tsx
Labels: CI: Ready to merge, CI: No changelog needed

#7897 Log nothing when class is found
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/scala/org/enso/compiler/SerializationManager.scala
Labels: CI: No changelog needed

#7682 Trash and Recent categories
  app/ide-desktop/.vscode/react.code-snippets
  app/ide-desktop/eslint.config.js
  app/ide-desktop/lib/assets/untrash.svg
  app/ide-desktop/lib/content/esbuild-config.ts
  app/ide-desktop/lib/dashboard/esbuild-config.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/auth.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/config.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/backend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/column.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetRow.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetsTable.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/categorySwitcher.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/directoryNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/drive.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/driveBar.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/fileNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/globalContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectIcon.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/secretNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/events/assetEvent.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/localBackend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/localStorage.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/remoteBackend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/shortcuts.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/http.tsx
  app/ide-desktop/lib/types/globals.d.ts
Labels: CI: Ready to merge, CI: No changelog needed

#7905 Transform Range.iterate test to a benchmark
  test/Benchmarks/src/Main.enso
  test/Benchmarks/src/Range.enso
  test/Tests/src/Data/Range_Spec.enso
Labels: CI: No changelog needed

#7847 Improve HTTP tests
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Header.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Request.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Request_Body.enso
  test/Tests/src/Network/Http_Spec.enso
  tools/legal-review/engine/reviewed-licenses/Apache_License_V2.0
  tools/legal-review/project-manager/reviewed-licenses/Apache_License_V2.0
  tools/simple-httpbin/src/main/java/org/enso/shttp/SimpleHTTPBin.java
  tools/simple-httpbin/src/main/java/org/enso/shttp/TestHandler.java
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#7894 Create execution context on GUI2 start
  app/gui2/package.json
  app/gui2/shared/event.ts
  app/gui2/shared/languageServer.ts
  app/gui2/shared/languageServerTypes.ts
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/providers/guiConfig.ts
  app/gui2/src/stores/project.ts
  app/gui2/vite.config.ts
  app/gui2/ydoc-server/languageServerSession.ts
  app/gui2/ydoc-server/ydoc.ts
  package-lock.json
Labels: CI: Ready to merge, CI: No changelog needed

#7908 Implement `auto_value_type` operation
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Boolean.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Type/Enso_Types.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Type/Storage.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Type/Value_Type.enso
  std-bits/table/src/main/java/org/enso/table/data/column/builder/BigIntegerBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/LongBuilderChecked.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/LongBuilderUnchecked.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/ToTextStorageConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/text/StringStringOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/MixedStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/MixedStorageFacade.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/Storage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/StringStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/AbstractLongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/BigIntegerStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/ComputedNullableLongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/DoubleStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/type/StorageType.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/type/TextType.java
  test/Table_Tests/src/Common_Table_Operations/Conversion_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Map_Spec.enso
  test/Table_Tests/src/Helpers/Value_Type_Spec.enso
  test/Table_Tests/src/In_Memory/Column_Spec.enso
Labels: CI: Ready to merge

#7875 Follow up improvements to `Date_Time_Formatter`
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Internal/Replacer.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time_Formatter.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Errors.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Time/Format/Analyzer.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Time/Format/As_Java_Formatter_Interpreter.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Time/Format/Parser.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Time/Format/Tokenizer.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Warning.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Data_Formatter.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Bench.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Test_Reporter.enso
  std-bits/base/src/main/java/org/enso/base/Cache.java
  std-bits/base/src/main/java/org/enso/base/text/Replacer_Cache.java
  std-bits/base/src/main/java/org/enso/base/time/EnsoDateTimeFormatter.java
  std-bits/base/src/main/java/org/enso/base/time/FormatterCache.java
  std-bits/base/src/main/java/org/enso/base/time/FormatterCacheKey.java
  std-bits/table/src/main/java/org/enso/table/parsing/BaseTimeParser.java
  test/Benchmarks/src/Main.enso
  test/Benchmarks/src/Time/Format.enso
  test/Table_Tests/src/Formatting/Data_Formatter_Spec.enso
  test/Table_Tests/src/Formatting/Parse_Values_Spec.enso
  test/Table_Tests/src/In_Memory/Column_Format_Spec.enso
  test/Tests/src/Data/Text/Regex_Spec.enso
  test/Tests/src/Data/Time/Date_Time_Formatter_Spec.enso
  test/Tests/src/Data/Time/Time_Of_Day_Spec.enso
  test/Tests/src/Network/Http_Spec.enso
  test/Tests/src/Semantic/Conversion_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#7909 Make sure Integer can be treated as Float
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso
  test/Tests/src/Data/Numbers_Spec.enso
Labels: CI: No changelog needed, -compiler, -libs

#7868 Open projects using the packaged language server
  app/gui/controller/engine-protocol/src/project_manager.rs
  app/gui/src/ide/initializer.rs
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/session/SessionApi.scala
  lib/scala/distribution-manager/src/main/scala/org/enso/distribution/config/GlobalConfigurationManager.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/data/ProjectMetadata.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/HeartbeatSession.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/ProjectCreateHandler.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectService.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/BaseServerSpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerGatewaySpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/EngineManagementApiSpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/MissingComponentBehavior.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectOpenHandleMissingRuntimeSpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectOpenMissingComponentsSpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectShutdownSpec.scala
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#7914 Fixes for AG Grid License handling
  app/gui/view/graph-editor/src/builtin/visualization/java_script.rs
Labels: CI: Ready to merge, CI: No changelog needed

#7877 (even more) Dashboard fixes
  app/ide-desktop/lib/client/watch.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/forgotPassword.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/input.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/login.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/registration.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/resetPassword.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/setUsername.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/auth.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/components/app.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/assetTreeNode.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetInfoBar.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetsTable.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/changePasswordModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/contextMenus.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/directoryNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/drive.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/driveBar.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/fileNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/managePermissionsModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/modal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/pageSwitcher.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/permissionSelector.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/secretNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/table.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/topBar.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/userBar.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/userMenu.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/localBackend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/remoteBackend.ts
  app/ide-desktop/lib/dashboard/src/tailwind.css
  app/ide-desktop/lib/dashboard/tailwind.config.ts
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#7920 AWS access data for stdlib tests
  .github/workflows/changelog.yml
  .github/workflows/engine-benchmark.yml
  .github/workflows/gui.yml
  .github/workflows/promote.yml
  .github/workflows/release.yml
  .github/workflows/scala-new.yml
  .github/workflows/std-libs-benchmark.yml
  build/build/src/aws.rs
  build/build/src/aws/env.rs
  build/build/src/ci_gen.rs
  build/build/src/ci_gen/job.rs
  build/ci_utils/src/actions/workflow/definition.rs
Labels: CI: No changelog needed
