Repository enso-org/enso, pull requests merged in 2023-07, with the labels that each got.

#7121 Delay URM reset until the async initialization is done.
  app/gui/src/presenter/graph.rs
  app/gui/src/presenter/project.rs
Labels: CI: No changelog needed

#7158 Preview keeps showing when cursor is over it, preventing flickering
  app/gui/view/graph-editor/src/component/node.rs
  app/gui/view/graph-editor/src/component/visualization/container.rs
Labels: CI: Ready to merge, CI: No changelog needed

#7159 Provide human-readable error log during installation
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/GraalVMComponentUpdater.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/RuntimeVersionManager.scala
Labels: CI: Ready to merge, CI: No changelog needed

#7179 Reload project's config on rename
  engine/language-server/src/main/scala/org/enso/languageserver/libraries/EditionReferenceResolver.scala
  engine/language-server/src/main/scala/org/enso/languageserver/libraries/LocalLibraryManager.scala
  engine/language-server/src/main/scala/org/enso/languageserver/libraries/ProjectSettingsManager.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/workspace/ProjectInfoHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/LibrariesTest.scala
  engine/runner/src/main/scala/org/enso/runner/DependencyPreinstaller.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/RenameProjectCmd.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeComponentsTest.scala
  engine/runtime/src/main/java/org/enso/compiler/ImportExportCache.java
  engine/runtime/src/main/java/org/enso/compiler/ModuleCache.java
  engine/runtime/src/main/java/org/enso/compiler/SuggestionsCache.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EnsoProjectNode.java
  engine/runtime/src/main/scala/org/enso/compiler/PackageRepository.scala
  lib/scala/library-manager/src/main/scala/org/enso/librarymanager/LibraryResolver.scala
  lib/scala/library-manager/src/main/scala/org/enso/libraryupload/LibraryUploader.scala
  lib/scala/pkg/src/main/scala/org/enso/pkg/Config.scala
  lib/scala/pkg/src/main/scala/org/enso/pkg/Package.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/repository/ProjectFileRepository.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/runner/Project.scala
Labels: CI: Ready to merge, CI: No changelog needed

#7174 Implement `add_row_number` for Database backends, fix primary key inference for SQLite
  CHANGELOG.md
  distribution/lib/Standard/AWS/0.0.0-dev/src/Database/Redshift/Internal/Redshift_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Type_Mapping.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Add_Row_Number.enso
  test/Table_Tests/src/Common_Table_Operations/Add_Row_Number_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Main.enso
  test/Table_Tests/src/Database/Common/Common_Spec.enso
  test/Table_Tests/src/Database/Common/Default_Ordering_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Database/Redshift_Spec.enso
  test/Table_Tests/src/Database/SQLite_Spec.enso
  test/Table_Tests/src/Database/Upload_Spec.enso
  test/Table_Tests/src/In_Memory/Common_Spec.enso
Labels: CI: Ready to merge

#7147 Remove `Array.new` and `Array.copy` and move Vector functions to builtins.
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Filter_Condition.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Regression.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Statistics.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Span.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Meta.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Random.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/Write_Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/Process/Process_Builder.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Warning.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Data/Image.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Data/Matrix.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Data_Formatter.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Expression.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Add_Row_Number.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Aggregate_Column_Helper.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Delimited_Reader.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Delimited_Writer.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Vector_Builder.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Extensions.enso
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/BuiltinTypesTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/immutable/FlattenVectorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/immutable/InsertBuiltinVectorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/immutable/RemoveAtVectorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/mutable/CoerceArrayNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/mutable/CopyNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Array.java
  engine/runtime/src/test/java/org/enso/interpreter/test/ArrayTest.java
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/MethodsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/PolyglotTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/SystemProcessTest.scala
  test/Table_Tests/src/Database/Upload_Spec.enso
  test/Table_Tests/src/In_Memory/Aggregate_Column_Spec.enso
  test/Tests/src/Data/Array_Spec.enso
  test/Tests/src/Data/Text/Utils_Spec.enso
  test/Tests/src/Semantic/Equals_Spec.enso
  test/Tests/src/Semantic/Names_Spec.enso
  test/Tests/src/System/System_Spec.enso
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso
Labels: CI: Ready to merge, CI: No changelog needed

#7173 Add timeout retries for project-related operations
  lib/scala/pkg/src/main/scala/org/enso/pkg/Package.scala
  lib/scala/project-manager/src/main/resources/application.conf
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/configuration.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/protocol/ClientController.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/ProjectCreateHandler.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/ProjectListHandler.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/ProjectOpenHandler.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/RequestHandler.scala
Labels: CI: Ready to merge, CI: No changelog needed

#7145 Support signing up to an existing organization
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/cognito.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/confirmRegistration.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/registration.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/auth.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/service.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/backend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/remoteBackend.ts
Labels: CI: No changelog needed

#7204 Fix a bug that somehow went under CI
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Add_Row_Number.enso
  std-bits/base/src/main/java/org/enso/base/arrays/MutableLongArrayWrapper.java
  test/Table_Tests/src/Database/Upload_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#7205 A dataflow error with warnings reports the former
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeErrorsTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/WithWarnings.java
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
Labels: CI: No changelog needed

#7207 Update context on timeout retry
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/RequestHandler.scala
Labels: CI: Ready to merge, CI: No changelog needed

#7172 Combine Regex and Pattern
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Filter_Condition.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Case_Sensitivity.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Internal/Match_Iterator.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Internal/Replacer.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Match.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Pattern.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Split_Tokenize.enso
  test/Tests/src/Data/Text/Regex_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#7185 Remove connections for a node that is being deleted.
  app/gui/src/controller/graph.rs
  app/gui/src/controller/graph/executed.rs
  app/gui/src/presenter/graph.rs
Labels: CI: Ready to merge, CI: Keep up to date, CI: No changelog needed

#7166 Do not rename column on fill_nothing and add version to the Table allowing filling multiple (include fill_empty as well).
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Database/Codegen_Spec.enso
  test/Table_Tests/src/In_Memory/Column_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
  test/Tests/src/Data/Text_Spec.enso
Labels: CI: Ready to merge

#7188 add support for bidirectional rectangle border and inset
  app/gui/view/graph-editor/src/component/edge/render.rs
  app/gui/view/graph-editor/src/component/node.rs
  app/gui/view/graph-editor/src/component/node/action_bar.rs
  lib/rust/ensogl/component/list-editor/src/placeholder.rs
  lib/rust/ensogl/core/src/display/shape/compound/rectangle.rs
  lib/rust/ensogl/core/src/display/shape/primitive/def/class.rs
  lib/rust/ensogl/core/src/display/shape/primitive/def/modifier.rs
  lib/rust/ensogl/core/src/display/shape/primitive/def/primitive.rs
  lib/rust/ensogl/core/src/display/shape/primitive/def/var.rs
  lib/rust/ensogl/core/src/display/shape/primitive/glsl/fragment_runner.glsl
  lib/rust/ensogl/core/src/display/shape/primitive/glsl/shape.glsl
  lib/rust/ensogl/core/src/display/shape/primitive/shader/canvas.rs
  lib/rust/ensogl/examples/built-in-shapes/src/lib.rs
  lib/rust/ensogl/examples/instance-ordering/src/lib.rs
Labels: CI: Ready to merge, CI: Keep up to date, CI: No changelog needed

#7023 Enable React and `strict-boolean-expressions` lints
  app/ide-desktop/eslint.config.js
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/cognito.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/confirmRegistration.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/fontAwesomeIcon.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/forgotPassword.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/input.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/login.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/registration.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/resetPassword.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/setUsername.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/auth.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/session.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/components/app.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/components/svg.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/changePasswordModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/confirmDeleteModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/contextMenu.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/contextMenuEntry.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/createForm.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/fileCreateForm.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/ide.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/input.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/label.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/modal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/permissionDisplay.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectActionButton.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/renameModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/rows.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/secretCreateForm.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/templates.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/topBar.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/userMenu.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/localBackend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/remoteBackend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/hooks.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/http.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/index.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/providers/backend.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/providers/logger.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/providers/modal.tsx
  app/ide-desktop/lib/types/modules.d.ts
  app/ide-desktop/package-lock.json
  app/ide-desktop/package.json
Labels: CI: No changelog needed

#7177 Fix mouse hover events.
  app/gui/view/graph-editor/src/component/node.rs
  app/gui/view/graph-editor/src/component/node/input/widget/list_editor.rs
  app/gui/view/graph-editor/src/component/node/output/port.rs
  lib/rust/ensogl/core/src/display/object/instance.rs
  lib/rust/ensogl/core/src/display/scene.rs
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#7217 Reload externally changed file on a keypress
  app/gui/src/controller/graph/executed.rs
  app/gui/src/model/module.rs
  app/gui/src/model/module/plain.rs
  app/gui/src/model/module/synchronized.rs
  app/gui/src/presenter/project.rs
  app/gui/view/src/project.rs
Labels: CI: Ready to merge, CI: No changelog needed

#7223 Add Table.replace; Change Text.replace to take a Text|Pattern, and remove the use_regex param.
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Case_Sensitivity.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Naming_Helpers.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Tests/src/Data/Text_Spec.enso
Labels: CI: Ready to merge

#7232 Initialize Language Server's JSON RPC protocol asynchronously
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonRpc.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonRpcProtocolFactory.scala
  lib/scala/json-rpc-server-test/src/main/scala/org/enso/jsonrpc/test/JsonRpcServerTestKit.scala
  lib/scala/json-rpc-server/src/main/scala/org/enso/jsonrpc/JsonRpcServer.scala
  lib/scala/json-rpc-server/src/main/scala/org/enso/jsonrpc/MessageHandler.scala
  lib/scala/json-rpc-server/src/main/scala/org/enso/jsonrpc/MessageHandlerSupervisor.scala
  lib/scala/json-rpc-server/src/main/scala/org/enso/jsonrpc/Protocol.scala
  lib/scala/json-rpc-server/src/main/scala/org/enso/jsonrpc/ProtocolFactory.scala
  lib/scala/json-rpc-server/src/test/scala/org/enso/jsonrpc/MessageHandlerSpec.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/protocol/JsonRpc.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/protocol/JsonRpcProtocolFactory.scala
Labels: CI: Ready to merge, CI: No changelog needed

#7146 New Prototype AI Searcher
  CHANGELOG.md
  app/gui/src/controller/graph.rs
  app/gui/src/controller/searcher.rs
  app/gui/src/controller/searcher/breadcrumbs.rs
  app/gui/src/presenter.rs
  app/gui/src/presenter/graph.rs
  app/gui/src/presenter/project.rs
  app/gui/src/presenter/searcher.rs
  app/gui/src/presenter/searcher/ai.rs
  app/gui/src/presenter/searcher/component_browser.rs
  app/gui/src/presenter/searcher/component_browser/provider.rs
  app/gui/view/graph-editor/src/lib.rs
  app/gui/view/graph-editor/src/shortcuts.rs
  app/gui/view/src/project.rs
  app/gui/view/src/root.rs
  build-config.yaml
Labels: CI: Ready to merge, -gui

#7193 Cache dataflow errors
  CHANGELOG.md
  engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeErrorsTest.scala
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Illegal_Argument.enso
Labels: CI: Ready to merge

#7164 Resizing visualizations
  CHANGELOG.md
  Cargo.lock
  app/gui/view/component-browser/src/lib.rs
  app/gui/view/documentation/src/lib.rs
  app/gui/view/graph-editor/Cargo.toml
  app/gui/view/graph-editor/src/component/node.rs
  app/gui/view/graph-editor/src/component/node/error.rs
  app/gui/view/graph-editor/src/component/visualization/container.rs
  lib/rust/ensogl/app/theme/hardcoded/src/lib.rs
  lib/rust/ensogl/core/src/display/scene.rs
  lib/rust/ensogl/core/src/display/shape/compound/rectangle.rs
Labels: CI: Ready to merge

#7243 Fixes from the live demo.
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Aggregate_Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Aggregate_Column_Helper.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  std-bits/table/src/main/java/org/enso/table/data/index/MultiValueIndex.java
  std-bits/table/src/main/java/org/enso/table/error/TooManyColumnsException.java
  test/Table_Tests/src/Common_Table_Operations/Aggregate_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Cross_Tab_Spec.enso
  test/Table_Tests/src/Database/Codegen_Spec.enso
  test/Table_Tests/src/Database/Common/Common_Spec.enso
  test/Table_Tests/src/In_Memory/Aggregate_Column_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#7209 Fix Undo/Redo for visualization toggling
  app/gui/view/graph-editor/src/lib.rs
Labels: CI: No changelog needed, g-graph-editor, -gui, --regression

#7230 Skip local engine version check
  app/gui/config/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#7239 Add fileModifiedOnDisk notification
  app/gui/controller/engine-protocol/src/language_server/types.rs
  app/gui/src/model/project/synchronized.rs
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManager.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonRpc.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/WriteBinaryFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/WriteTextualFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/Buffer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/CollaborativeBuffer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/FileWithMetadata.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/TextApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/TextProtocol.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/TextOperationsTest.scala
  lib/scala/text-buffer/src/main/scala/org/enso/text/ContentVersion.scala
Labels: CI: Ready to merge, CI: No changelog needed

#7246 Round on a column was always adding a warning
  distribution/lib/Standard/Base/0.0.0-dev/src/Any.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  std-bits/table/src/main/java/org/enso/table/data/column/storage/Storage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/AbstractLongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/DoubleStorage.java
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Main.enso
  test/Table_Tests/src/In_Memory/Column_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#7211 Fix improperly scoped styles in visualizations
  app/gui/view/graph-editor/src/builtin/visualization/java_script/histogram.js
  app/gui/view/graph-editor/src/builtin/visualization/java_script/scatterPlot.js
Labels: CI: No changelog needed

#7225 Show spinner on templates when creating project
  app/ide-desktop/lib/dashboard/src/authentication/src/components/svg.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectActionButton.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/rows.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/spinner.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/templates.tsx
  app/ide-desktop/lib/dashboard/tailwind.config.ts
Labels: CI: No changelog needed

#7100 "Share with" button
  app/ide-desktop/eslint.config.js
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/cognito.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/backend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/autocomplete.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/managePermissionsModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/permissionDisplay.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/permissionSelector.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectActionButton.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/remoteBackend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/error.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/set.ts
  app/ide-desktop/lib/dashboard/src/tailwind.css
  app/ide-desktop/lib/dashboard/tailwind.config.ts
Labels: CI: No changelog needed

#6582 add remoteLog function for gathering gui logs
  app/gui/analytics/src/remote_log.rs
  app/ide-desktop/lib/content-config/src/config.json
  app/ide-desktop/lib/content/src/index.ts
  app/ide-desktop/lib/content/src/remoteLog.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/auth.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/service.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/config.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/ide.tsx
  app/ide-desktop/lib/types/types.d.ts
  lib/rust/ensogl/pack/js/src/runner/config.json
  lib/rust/ensogl/pack/js/src/runner/index.ts
Labels: CI: No changelog needed

#7271 Convert vector elements when needed
  test/Tests/src/Semantic/Conversion_Spec.enso
  test/Tests/src/Semantic/Conversion_Use.enso
Labels: CI: Ready to merge, CI: No changelog needed, -compiler, -libs

#7233 Single column in component browser
  app/gui/view/component-browser/component-list-panel/grid/src/entry.rs
  app/gui/view/component-browser/component-list-panel/grid/src/layout.rs
  app/gui/view/component-browser/component-list-panel/grid/src/layouting.rs
  app/gui/view/component-browser/component-list-panel/grid/src/lib.rs
  app/gui/view/component-browser/component-list-panel/src/navigator.rs
  lib/rust/ensogl/app/theme/hardcoded/src/lib.rs
  lib/rust/ensogl/component/grid-view/src/scrollable.rs
Labels: CI: Ready to merge, CI: No changelog needed

#7269 Fix node name visibility
  app/gui/view/graph-editor/src/component/node.rs
  app/gui/view/graph-editor/src/component/node/output/area.rs
  app/gui/view/graph-editor/src/component/node/output/port.rs
Labels: CI: Ready to merge, CI: Keep up to date, CI: No changelog needed

#7221 Adding new Date/Time operations (`-`, `date_add`, `date_diff`, `date_part`)
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Period.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Period.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Aggregate_Helper.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/IR/Operation_Metadata.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/IR/SQL_Expression.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Type/Value_Type.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Type/Value_Type_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Date_Time_Helpers.enso
  std-bits/base/src/main/java/org/enso/base/Time_Utils.java
  std-bits/base/src/main/java/org/enso/base/time/CustomTemporalUnits.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/GenericBinaryObjectMapOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/datetime/DatePartExtractors.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/DoubleLongMapOpWithSpecialNumericHandling.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/GenericUnaryIntegerOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/UnaryDoubleToLongOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/UnaryIntegerOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/UnaryLongToLongOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/datetime/DateStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/datetime/DateTimeStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/datetime/TimeOfDayStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/AbstractLongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/DoubleStorage.java
  std-bits/table/src/main/java/org/enso/table/error/UnexpectedTypeException.java
  test/Table_Tests/src/Common_Table_Operations/Date_Time_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Main.enso
  test/Table_Tests/src/Common_Table_Operations/Util.enso
  test/Table_Tests/src/Database/Upload_Spec.enso
  test/Table_Tests/src/In_Memory/Common_Spec.enso
  test/Tests/src/Data/Text/Regex_Spec.enso
  test/Tests/src/Data/Time/Date_Time_Spec.enso
  test/Tests/src/Data/Time/Time_Of_Day_Spec.enso
Labels: CI: Ready to merge

#7257 Engine benchmarks download tool is able to plot multiple branches
  tools/performance/engine-benchmarks/bench_download.py
  tools/performance/engine-benchmarks/template_jinja.html
Labels: -tooling, CI: Ready to merge, CI: No changelog needed

#7292 Debug TextOperations test
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/TextOperationsTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#7291 Add endpoint for downloading a project
  CHANGELOG.md
  build.sbt
  docs/language-server/project-manager-http-endpoints.md
  lib/scala/pkg/src/main/java/org/enso/pkg/archive/CloseArchiveEntryException.java
  lib/scala/pkg/src/main/java/org/enso/pkg/archive/EnsoProjectArchive.java
  lib/scala/pkg/src/main/java/org/enso/pkg/archive/EnsoProjectArchiveException.java
  lib/scala/pkg/src/main/java/org/enso/pkg/archive/TarArchiveBuildingFileVisitor.java
  lib/scala/pkg/src/main/java/org/enso/pkg/archive/WriteArchiveEntryException.java
  lib/scala/pkg/src/test/resources/Enso_Project_Archive_Test/data/sample.txt
  lib/scala/pkg/src/test/resources/Enso_Project_Archive_Test/package.yaml
  lib/scala/pkg/src/test/resources/Enso_Project_Archive_Test/src/Main.enso
  lib/scala/pkg/src/test/scala/org/enso/pkg/archive/EnsoProjectArchiveSpec.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/MainModule.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/http/ProjectsEndpoint.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerController.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/repository/ProjectFileRepository.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/repository/ProjectRepository.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/model/Project.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectService.scala
Labels: CI: Ready to merge

#7267 Fix error visualization positioning
  app/gui/view/graph-editor/src/component/node.rs
Labels: CI: Ready to merge, CI: No changelog needed

#7277 Avoiding dependency on EnsoContext from Module and ModuleScope
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Type.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/TopLevelScope.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/PackageRepository.scala
  engine/runtime/src/test/java/org/enso/interpreter/test/MetaObjectTest.java
  engine/runtime/src/test/scala/org/enso/compiler/test/CompilerTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#7235 Builtin methods can support array-like arguments
  build.sbt
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoFile.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/BuiltinsProcessor.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/MethodProcessor.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/builtins/ExecuteMethodImplGenerator.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/builtins/MethodGenerator.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/builtins/MethodNodeClassGenerator.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/builtins/NoSpecializationClassGenerator.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/builtins/SpecializationClassGenerator.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/builtins/SpecializedMethodsGenerator.java
Labels: CI: No changelog needed

#7299 Avoid Compiler compile time dependency on EnsoContext
  engine/polyglot-api/src/main/java/org/enso/polyglot/CompilationStage.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/job/SerializeModuleJob.java
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime/src/main/java/org/enso/compiler/ModuleCache.java
  engine/runtime/src/main/java/org/enso/compiler/context/CompilerContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/PackageRepository.scala
  engine/runtime/src/main/scala/org/enso/compiler/SerializationManager.scala
  engine/runtime/src/main/scala/org/enso/compiler/data/BindingsMap.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/FullyQualifiedNames.scala
  engine/runtime/src/main/scala/org/enso/compiler/phase/BuiltinsIrBuilder.scala
  engine/runtime/src/main/scala/org/enso/compiler/phase/ImportResolver.scala
  engine/runtime/src/test/java/org/enso/compiler/SerializerTest.java
  engine/runtime/src/test/java/org/enso/interpreter/runtime/ModuleTestUtils.java
  engine/runtime/src/test/scala/org/enso/compiler/test/CompilerTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/GlobalNamesTest.scala
Labels: CI: No changelog needed

#7298 Type checks inconsistent when dealing with a -> b function types
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  test/Tests/src/Main.enso
  test/Tests/src/Runtime/Ascribed_Parameters_Spec.enso
Labels: CI: No changelog needed

#7302 ResourceManagerTest to verify resources are cleaned on ctx.close()
  engine/runtime/src/main/java/org/enso/interpreter/runtime/ResourceManager.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/ManagedResource.java
  engine/runtime/src/test/java/org/enso/interpreter/runtime/ResourceManagerTest.java
Labels: CI: Ready to merge, CI: No changelog needed

#7254 Delay LS shutdown when last client disconnects
  lib/scala/project-manager/src/main/resources/application.conf
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/configuration.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerController.scala
  lib/scala/project-manager/src/test/resources/application.conf
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectShutdownSpec.scala
Labels: CI: No changelog needed

#7285 Bump electron to 25.3.
  app/ide-desktop/lib/client/package.json
  app/ide-desktop/package-lock.json
Labels: CI: Ready to merge, CI: No changelog needed

#7249 Redesign IDE top bar
  Cargo.lock
  app/gui/src/ide/initializer.rs
  app/gui/src/presenter.rs
  app/gui/src/presenter/graph.rs
  app/gui/src/presenter/graph/call_stack.rs
  app/gui/src/presenter/project.rs
  app/gui/view/Cargo.toml
  app/gui/view/examples/Cargo.toml
  app/gui/view/examples/interface/src/lib.rs
  app/gui/view/examples/project-view-top-bar/Cargo.toml
  app/gui/view/examples/project-view-top-bar/src/lib.rs
  app/gui/view/examples/src/lib.rs
  app/gui/view/execution-environment-selector/src/lib.rs
  app/gui/view/graph-editor/src/component.rs
  app/gui/view/graph-editor/src/component/breadcrumbs/breadcrumb.rs
  app/gui/view/graph-editor/src/component/breadcrumbs/project_name.rs
  app/gui/view/graph-editor/src/execution_environment.rs
  app/gui/view/graph-editor/src/lib.rs
  app/gui/view/graph-editor/src/shortcuts.rs
  app/gui/view/project-view-top-bar/Cargo.toml
  app/gui/view/project-view-top-bar/src/breadcrumbs.rs
  app/gui/view/project-view-top-bar/src/breadcrumbs/breadcrumb.rs
  app/gui/view/project-view-top-bar/src/go_to_dashboard_button.rs
  app/gui/view/project-view-top-bar/src/lib.rs
  app/gui/view/project-view-top-bar/src/project_name.rs
  app/gui/view/project-view-top-bar/src/window_control_buttons.rs
  app/gui/view/project-view-top-bar/src/window_control_buttons/close.rs
  app/gui/view/project-view-top-bar/src/window_control_buttons/fullscreen.rs
  app/gui/view/src/lib.rs
  app/gui/view/src/project.rs
  app/gui/view/src/project/project_view_top_bar.rs
  lib/rust/ensogl/app/theme/hardcoded/src/lib.rs
  lib/rust/ensogl/component/drop-down-menu/src/lib.rs
  lib/rust/ensogl/core/src/data/color/space/def.rs
  lib/rust/ensogl/core/src/display/scene.rs
Labels: CI: Ready to merge, CI: No changelog needed

#7151 Help chat
  CHANGELOG.md
  app/ide-desktop/eslint.config.js
  app/ide-desktop/lib/assets/close_large.svg
  app/ide-desktop/lib/assets/triangle_down.svg
  app/ide-desktop/lib/content/src/index.html
  app/ide-desktop/lib/dashboard/package.json
  app/ide-desktop/lib/dashboard/src/authentication/src/animations.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/config.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/chat.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/topBar.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/twemoji.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/dateTime.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/hooks.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/newtype.ts
  app/ide-desktop/lib/dashboard/src/tailwind.css
  app/ide-desktop/lib/dashboard/tailwind.config.ts
  app/ide-desktop/lib/dashboard/watch.ts
  app/ide-desktop/package-lock.json
Labels: CI: Clean build required

#7296 New icons, part 1
  app/gui/view/component-browser/component-list-panel/grid/src/entry/icon.rs
  app/gui/view/component-browser/component-list-panel/icons/src/common_part.rs
  app/gui/view/examples/icons/src/lib.rs
  app/gui/view/graph-editor/src/component/node/action_bar/icon.rs
  app/gui/view/graph-editor/src/component/node/output/port.rs
  app/gui/view/graph-editor/src/component/visualization/container/action_bar.rs
  build-config.yaml
  lib/rust/ensogl/app/theme/hardcoded/src/lib.rs
  lib/rust/ensogl/core/src/display/shape/primitive/def/primitive.rs
Labels: CI: Ready to merge, CI: No changelog needed

#7321 Fix issue with rename_columns and revert order of parameter change on select_columns.
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  test/Table_Tests/src/Common_Table_Operations/Select_Columns_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#7297 Add Fallback to Prim_Text_Helper.compile_regex; accept Regex in Text.parse_to_table
  CHANGELOG.md
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table_Conversions.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Parse_To_Table.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/RegexCompileNode.java
  test/Table_Tests/src/In_Memory/Parse_To_Table_Spec.enso
  test/Tests/src/Data/Text/Regex_Spec.enso
Labels: CI: Ready to merge

#7324 Bench builder API
  distribution/lib/Standard/Test/0.0.0-dev/src/Bench.enso
  test/Benchmarks/src/Vector/Operations.enso
Labels: CI: Ready to merge, CI: No changelog needed

#7325 Add zone to Date_Times
  test/Table_Tests/src/Common_Table_Operations/Date_Time_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#7338 Update junit-interface
  build.sbt
Labels: CI: Ready to merge, CI: No changelog needed

#7322 Allow external edits of project files
  build.sbt
  engine/language-server/src/main/scala/org/enso/languageserver/boot/ResourcesInitialization.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/resource/ZioRuntimeInitialization.scala
  engine/language-server/src/main/scala/org/enso/languageserver/event/InitializedEvent.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileEvent.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/PathWatcher.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/ReceivesTreeUpdatesHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/Buffer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/BufferRegistry.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/CollaborativeBuffer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/FileWithMetadata.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/ReceivesTreeUpdatesHandlerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/TextOperationsTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/VcsManagerTest.scala
  lib/scala/filewatcher/src/main/java/org/enso/filewatcher/package-info.java
  lib/scala/filewatcher/src/main/scala/org/enso/filewatcher/WatcherAdapter.scala
  lib/scala/filewatcher/src/test/scala/org/enso/filewatcher/WatcherAdapterSpec.scala
Labels: CI: Ready to merge, CI: No changelog needed

#7319 Set background throttling to false by default
  app/ide-desktop/lib/client/src/config.ts
Labels: CI: No changelog needed

#7358 Bump setup-conda action
  .github/workflows/benchmark.yml
  .github/workflows/changelog.yml
  .github/workflows/gui.yml
  .github/workflows/promote.yml
  .github/workflows/release.yml
  .github/workflows/scala-new.yml
  build/ci_utils/src/actions/workflow/definition.rs
Labels: CI: No changelog needed

#7355 Flaky pending saves vcs test
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/VcsManagerTest.scala
Labels: CI: No changelog needed

#7327 New Components Order
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  app/gui/Cargo.toml
  app/gui/controller/double-representation/src/name.rs
  app/gui/src/controller/searcher.rs
  app/gui/src/controller/searcher/action.rs
  app/gui/src/controller/searcher/action/hardcoded.rs
  app/gui/src/controller/searcher/breadcrumbs.rs
  app/gui/src/controller/searcher/component.rs
  app/gui/src/controller/searcher/component/builder.rs
  app/gui/src/controller/searcher/component/group.rs
  app/gui/src/controller/searcher/component/hardcoded.rs
  app/gui/src/controller/searcher/input.rs
  app/gui/src/presenter/project.rs
  app/gui/src/presenter/searcher.rs
  app/gui/src/presenter/searcher/ai.rs
  app/gui/src/presenter/searcher/component_browser.rs
  app/gui/src/presenter/searcher/component_browser/provider.rs
  app/gui/view/component-browser/component-list-panel/grid/src/content.rs
  app/gui/view/component-browser/component-list-panel/grid/src/entry.rs
  app/gui/view/component-browser/component-list-panel/grid/src/entry/style.rs
  app/gui/view/component-browser/component-list-panel/grid/src/layout.rs
  app/gui/view/component-browser/component-list-panel/grid/src/layouting.rs
  app/gui/view/component-browser/component-list-panel/grid/src/lib.rs
  app/gui/view/component-browser/component-list-panel/src/lib.rs
  app/gui/view/component-browser/component-list-panel/src/navigator.rs
  app/gui/view/component-browser/component-list-panel/src/navigator/entry.rs
  app/gui/view/examples/component-list-panel-view/src/lib.rs
  app/gui/view/src/project.rs
Labels: CI: Ready to merge

#7334 Update codeowners
  .github/CODEOWNERS
Labels: CI: No changelog needed, CI: Clean build required

#7340 Yield UnclosedTextLiteral syntax errors
  engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java
  engine/runtime/src/test/java/org/enso/compiler/ErrorCompilerTest.java
Labels: CI: Ready to merge, CI: Keep up to date, CI: No changelog needed, CI: Clean build required

#7282 Add option to skip logging in
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/confirmRegistration.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/enterOfflineMode.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/login.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/auth.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/components/app.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
Labels: CI: No changelog needed, CI: Clean build required

#7270 Add benchmarks comparing performance of Table operations 'vectorized' in Java vs performed in Enso
  build.sbt
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Bench.enso
  std-bits/table/src/main/java/org/enso/table/data/table/Column.java
  test/Exploratory_Benchmarks/README.md
  test/Exploratory_Benchmarks/package.yaml
  test/Exploratory_Benchmarks/polyglot-sources/exploratory-benchmark-java-helpers/src/main/java/org/enso/exploratory_benchmark_helpers/MapHelpers.java
  test/Exploratory_Benchmarks/polyglot-sources/exploratory-benchmark-java-helpers/src/main/java/org/enso/exploratory_benchmark_helpers/SimpleStorageAggregateHelpers.java
  test/Exploratory_Benchmarks/src/Main.enso
  test/Exploratory_Benchmarks/src/Table/Column_Aggregate.enso
  test/Exploratory_Benchmarks/src/Table/Column_Bi_Map.enso
  test/Exploratory_Benchmarks/src/Table/Column_Map.enso
  test/Exploratory_Benchmarks/src/Table/Column_Map_2.enso
  test/Exploratory_Benchmarks/src/Table/Common_Setup.enso
  test/Exploratory_Benchmarks/src/Table/Enso_Callback.enso
  test/Exploratory_Benchmarks/src/Table/Helpers.enso
  test/Exploratory_Benchmarks/src/Table/Main.enso
  tools/performance/benchmark-analysis/README.md
  tools/performance/benchmark-analysis/data/benchmarks-vectorized-3-2023-07-17.txt
  tools/performance/benchmark-analysis/package.yaml
  tools/performance/benchmark-analysis/src/Main.enso
Labels: CI: Ready to merge, CI: No changelog needed

#7367 Various small tickets...
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Match.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/BitShiftNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/BitShiftNode.java
  test/Tests/src/Data/Text_Spec.enso
  test/Tests/src/Data/Time/Date_Time_Spec.enso
  test/Tests/src/Semantic/Meta_Spec.enso
  test/Tests/src/System/File_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#7364 Fix GraalVM distribution download on MacOS
  .github/workflows/formatting.yml
  build.sbt
  build/build/src/paths.rs
  build/ci_utils/src/cache/goodie/graalvm.rs
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/releases/graalvm/GraalCEReleaseProvider.scala
  project/DistributionPackage.scala
  project/GraalVersionCheck.scala
  project/plugins.sbt
Labels: p-highest, CI: Ready to merge, CI: No changelog needed

#7369 Decrease watcher verbosity
  engine/language-server/src/main/resources/application.conf
Labels: CI: Ready to merge, CI: No changelog needed

#7370 Runtime instrumentation is being used before finishing instrumentation
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/Handler.scala
Labels: CI: Ready to merge, CI: No changelog needed

#7348 Ascribed types & atom_with_hole
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/SieveBenchmarks.java
  engine/runtime/src/bench/resources/org/enso/interpreter/bench/benchmarks/semantic/sieveAscribed.enso
  engine/runtime/src/bench/resources/org/enso/interpreter/bench/benchmarks/semantic/sieveWithoutTypes.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/argument/ReadArgumentCheckNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/Builtin.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/AtomWithAHoleNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/argument/ArgumentDefinition.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/AtomConstructor.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/unboxing/Layout.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/unboxing/UnboxingAtom.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Type.java
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/MethodProcessor.java
  test/Tests/src/Semantic/Meta_Spec.enso
Labels: CI: No changelog needed, CI: Clean build required

#7344 Simplifying builtins type system support
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/GetQualifiedTypeNameNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/util/TypeToDisplayTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/type/Types.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/type/TypesFromProxy.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/MethodProcessor.java
Labels: CI: No changelog needed

#7337 Groups in DocTags
  CHANGELOG.md
  app/gui/controller/double-representation/src/name.rs
  app/gui/controller/double-representation/src/name/project.rs
  app/gui/controller/engine-protocol/src/language_server/types.rs
  app/gui/src/controller/searcher.rs
  app/gui/src/controller/searcher/component.rs
  app/gui/src/controller/searcher/component/builder.rs
  app/gui/src/controller/searcher/component/hardcoded.rs
  app/gui/src/model/execution_context.rs
  app/gui/src/model/execution_context/synchronized.rs
  app/gui/suggestion-database/src/entry.rs
  distribution/lib/Standard/Base/0.0.0-dev/package.yaml
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Table/0.0.0-dev/package.yaml
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  lib/rust/parser/doc-parser/src/lib.rs
  lib/rust/prelude/src/string.rs
Labels: CI: Ready to merge

#7339 New notification system
  Cargo.lock
  Cargo.toml
  app/gui/controller/engine-protocol/Cargo.toml
  app/gui/view/Cargo.toml
  app/gui/view/src/lib.rs
  app/gui/view/src/notification.rs
  app/gui/view/src/notification/js.rs
  app/ide-desktop/lib/content/package.json
  app/ide-desktop/lib/content/src/index.ts
  app/ide-desktop/lib/dashboard/esbuild-config.ts
  app/ide-desktop/lib/dashboard/package.json
  app/ide-desktop/lib/dashboard/src/authentication/package.json
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/confirmRegistration.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/registration.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/resetPassword.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/auth.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/components/app.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/changePasswordModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/chat.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/confirmDeleteModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/directoriesTable.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/directoryView.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/driveBar.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/filesTable.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/managePermissionsModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectsTable.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/secretsTable.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/error.ts
  app/ide-desktop/lib/dashboard/src/tailwind.css
  app/ide-desktop/package-lock.json
  build/build/Cargo.toml
  build/ci_utils/Cargo.toml
  build/cli/Cargo.toml
Labels: CI: No changelog needed, -gui

#7275 Implement replace on the Database Column
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Case_Sensitivity.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Replace_Params.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Type_Mapping.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Main.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Database/SQLite_Spec.enso
Labels: CI: Ready to merge

#7368 Fixing operations on Mixed types
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Filter_Condition.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Polyglot_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Type/Storage.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Test.enso
  std-bits/base/src/main/java/org/enso/base/polyglot/Polyglot_Utils.java
  std-bits/base/src/main/java/org/enso/base/polyglot/WrappedDataflowError.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/BoolBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/Builder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/InferredBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/MixedBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/ObjectBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/TypedBuilderImpl.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/ToTextStorageConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/BinaryMapOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/GenericBinaryObjectMapOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/MapOpStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/MapOperationStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/SpecializedIsInOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/UnaryMapOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/UnaryMapOperationWithProblemBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/bool/BooleanIsInOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/datetime/DatePartExtractors.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/DoubleBooleanOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/DoubleComparison.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/DoubleLongMapOpWithSpecialNumericHandling.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/DoubleNumericOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/LongBooleanOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/LongComparison.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/LongNumericOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/UnaryDoubleToLongOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/UnaryIntegerOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/UnaryLongToLongOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/text/LikeOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/text/StringBooleanOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/text/StringStringOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/MixedStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/MixedStorageFacade.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/ObjectStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/SpecializedStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/Storage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/StringStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/datetime/DateStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/datetime/DateTimeStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/datetime/TimeOfDayStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/AbstractLongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/DoubleStorage.java
  std-bits/table/src/main/java/org/enso/table/data/table/Column.java
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Main.enso
  test/Table_Tests/src/Common_Table_Operations/Map_Spec.enso
  test/Table_Tests/src/In_Memory/Column_Spec.enso
  test/Table_Tests/src/In_Memory/Common_Spec.enso
  test/Tests/polyglot-sources/enso-test-java-helpers/src/main/java/org/enso/table_test_helpers/ExplodingStorage.java
Labels: CI: Ready to merge, CI: No changelog needed

#7395 Moving PackageRepository.Default into its own EnsoPackageRepository
  engine/runtime/src/main/java/org/enso/compiler/ImportExportCache.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/scala/org/enso/compiler/PackageRepository.scala
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/EnsoPackageRepository.scala
Labels: CI: Keep up to date, CI: No changelog needed

#7390 Speed up statistics
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Statistics.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Replace_Params.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Row.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Split_Tokenize.enso
  std-bits/base/src/main/java/org/enso/base/statistics/CountMinMax.java
  std-bits/base/src/main/java/org/enso/base/statistics/Kurtosis.java
  std-bits/base/src/main/java/org/enso/base/statistics/Mean.java
  std-bits/base/src/main/java/org/enso/base/statistics/MomentStatistic.java
  std-bits/base/src/main/java/org/enso/base/statistics/Moments.java
  std-bits/base/src/main/java/org/enso/base/statistics/Skew.java
  std-bits/base/src/main/java/org/enso/base/statistics/StandardDeviation.java
  std-bits/base/src/main/java/org/enso/base/statistics/Sum.java
  std-bits/base/src/main/java/org/enso/base/statistics/Variance.java
  test/Benchmarks/src/Vector/Operations.enso
  test/Tests/src/Data/Statistics_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#7360 Convert Number.round to Java
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Illegal_Argument.enso
  lib/scala/common-polyglot-core-utils/src/main/java/org/enso/polyglot/common_utils/Core_Math_Utils.java
  test/Benchmarks/src/Main.enso
  test/Benchmarks/src/Numeric.enso
Labels: CI: Ready to merge, CI: No changelog needed

#7407 CI fixes
  .github/workflows/gui.yml
  .github/workflows/release.yml
  .github/workflows/scala-new.yml
  build/build/src/ci_gen.rs
  build/build/src/ci_gen/job.rs
  build/build/src/env.rs
  build/build/src/release.rs
  build/ci_utils/src/actions/workflow/definition.rs
Labels: CI: No changelog needed

#7386 Background translucency
  app/ide-desktop/eslint.config.js
  app/ide-desktop/lib/assets/background.png
  app/ide-desktop/lib/assets/geo.png
  app/ide-desktop/lib/assets/spreadsheets.png
  app/ide-desktop/lib/assets/visualize.png
  app/ide-desktop/lib/client/src/detect.ts
  app/ide-desktop/lib/client/src/index.ts
  app/ide-desktop/lib/content/esbuild-config.ts
  app/ide-desktop/lib/dashboard/esbuild-config.ts
  app/ide-desktop/lib/dashboard/package.json
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/forgotPassword.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/login.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/registration.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/resetPassword.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/setUsername.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/templates.tsx
  app/ide-desktop/lib/dashboard/src/tailwind.css
  app/ide-desktop/lib/types/modules.d.ts
  app/ide-desktop/package-lock.json
Labels: CI: No changelog needed, CI: Clean build required

#7362 Updated breadcrumb UI to new design
  CHANGELOG.md
  Cargo.lock
  app/gui/view/component-browser/component-list-panel/breadcrumbs/Cargo.toml
  app/gui/view/component-browser/component-list-panel/breadcrumbs/src/entry.rs
  app/gui/view/component-browser/component-list-panel/breadcrumbs/src/lib.rs
  app/gui/view/examples/component-list-panel-view/src/lib.rs
  lib/rust/ensogl/app/theme/hardcoded/src/lib.rs
Labels: CI: Ready to merge

#7399 Parser: Fix handling of syntax errors such as `x =- 2`
  .github/CODEOWNERS
  lib/rust/parser/debug/tests/parse.rs
  lib/rust/parser/src/lexer.rs
  lib/rust/parser/src/syntax/operator.rs
Labels: CI: No changelog needed

#7416 StopServer timing out on project stopping
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerGatewayImpl.scala
Labels: CI: Ready to merge, CI: No changelog needed

#7385 Check for PanicSentinel in SequenceLiteralNode
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/SequenceLiteralNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicException.java
  engine/runtime/src/test/java/org/enso/interpreter/node/callable/SequenceLiteralNodeTest.java
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#7396 Verify Python date can be used where Enso date
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoTimeZone.java
  test/Tests/src/Data/Time/Date_Part_Spec.enso
  test/Tests/src/Data/Time/Date_Spec.enso
  test/Tests/src/Data/Time/Date_Time_Spec.enso
  test/Tests/src/Data/Time/Time_Of_Day_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#7381 New fuzzy matching
  Cargo.lock
  app/gui/src/controller/graph/widget.rs
  app/gui/src/controller/searcher.rs
  app/gui/src/controller/searcher/breadcrumbs.rs
  app/gui/src/controller/searcher/component.rs
  app/gui/src/controller/searcher/component/builder.rs
  app/gui/src/controller/searcher/search.rs
  app/gui/src/presenter/searcher/component_browser/provider.rs
  app/gui/suggestion-database/src/entry.rs
  app/gui/suggestion-database/src/lib.rs
  app/gui/suggestion-database/src/mock.rs
  lib/rust/fuzzly/Cargo.toml
  lib/rust/fuzzly/src/bitstring.rs
  lib/rust/fuzzly/src/lib.rs
  lib/rust/fuzzly/src/metric.rs
  lib/rust/fuzzly/src/score.rs
  lib/rust/fuzzly/src/subsequence_graph.rs
Labels: CI: Ready to merge, CI: No changelog needed

#7414 Fix dashboard regressions
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetsTable.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/directoryNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/driveBar.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/driveView.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/fileNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectIcon.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/secretNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/templates.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/events/assetEvent.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/events/assetListEvent.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/localBackend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/hooks.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/uniqueString.ts
Labels: CI: No changelog needed

#7421 Disable file watcher in VcsManagerTest suite
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileEvent.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/PathWatcher.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/ReceivesTreeUpdatesHandler.scala
  engine/language-server/src/test/scala/org/enso/filewatcher/NoopWatcher.scala
  engine/language-server/src/test/scala/org/enso/filewatcher/NoopWatcherFactory.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/ReceivesTreeUpdatesHandlerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/TextOperationsTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/VcsManagerTest.scala
  lib/scala/filewatcher/src/main/scala/org/enso/filewatcher/Watcher.scala
  lib/scala/filewatcher/src/main/scala/org/enso/filewatcher/WatcherAdapter.scala
  lib/scala/filewatcher/src/main/scala/org/enso/filewatcher/WatcherAdapterFactory.scala
  lib/scala/filewatcher/src/main/scala/org/enso/filewatcher/WatcherFactory.scala
  lib/scala/filewatcher/src/test/scala/org/enso/filewatcher/WatcherAdapterSpec.scala
Labels: CI: Ready to merge, CI: No changelog needed

#7422 Fix panic when closing project while some GUI elements are still in executor.
  app/gui/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#7419 Refactor icons and breadcrumbs into separate crate.
  Cargo.lock
  app/gui/Cargo.toml
  app/gui/src/controller/searcher/component/hardcoded.rs
  app/gui/src/presenter/searcher/component_browser/provider.rs
  app/gui/suggestion-database/Cargo.toml
  app/gui/view/component-browser/Cargo.toml
  app/gui/view/component-browser/component-list-panel/Cargo.toml
  app/gui/view/component-browser/component-list-panel/grid/Cargo.toml
  app/gui/view/component-browser/component-list-panel/grid/src/entry.rs
  app/gui/view/component-browser/component-list-panel/grid/src/entry/icon.rs
  app/gui/view/component-browser/component-list-panel/grid/src/lib.rs
  app/gui/view/component-browser/component-list-panel/icons/Cargo.toml
  app/gui/view/component-browser/component-list-panel/src/lib.rs
  app/gui/view/examples/component-list-panel-view/Cargo.toml
  app/gui/view/examples/component-list-panel-view/src/lib.rs
  app/gui/view/examples/icons/Cargo.toml
  app/gui/view/examples/icons/src/lib.rs
  app/gui/view/graph-editor/Cargo.toml
  app/gui/view/graph-editor/src/component/breadcrumbs/breadcrumb.rs
  app/gui/view/graph-editor/src/component/node/action_bar.rs
  app/gui/view/graph-editor/src/component/node/input/widget/method.rs
  lib/rust/ensogl/component/breadcrumbs/Cargo.toml
  lib/rust/ensogl/component/breadcrumbs/src/entry.rs
  lib/rust/ensogl/component/breadcrumbs/src/lib.rs
  lib/rust/ensogl/component/icons/Cargo.toml
  lib/rust/ensogl/component/icons/src/common_part.rs
  lib/rust/ensogl/component/icons/src/component_icons.rs
  lib/rust/ensogl/component/icons/src/define_macro.rs
  lib/rust/ensogl/component/icons/src/icon.rs
  lib/rust/ensogl/component/icons/src/lib.rs
  lib/rust/ensogl/component/text/src/component/text.rs
  lib/rust/ensogl/core/src/control/io.rs
  lib/rust/ensogl/core/src/control/io/keyboard.rs
  lib/rust/ensogl/core/src/control/io/keyboard/dom.rs
  lib/rust/ensogl/core/src/control/io/mouse.rs
  lib/rust/ensogl/derive/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#7439 Fix opening projects after switching backend
  app/ide-desktop/lib/content/src/index.ts
  lib/rust/ensogl/pack/js/src/runner/config.ts
Labels: CI: No changelog needed

#7444 Refactor project normalized name
  app/gui/controller/engine-protocol/src/project_manager.rs
  app/gui/src/model/project/synchronized.rs
  docs/language-server/protocol-project-manager.md
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/data/RunningLanguageServerInfo.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/protocol/ProjectManagementApi.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/ProjectOpenHandler.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/ProjectManagementOps.scala
Labels: CI: Ready to merge, CI: No changelog needed

#7393 Fix `startup.project`
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/driveView.tsx
Labels: CI: No changelog needed, CI: Clean build required
