Repository enso-org/enso, pull requests merged in 2023-05, with the labels that each got.

#6458 Fix disappearing cached shapes
  lib/rust/ensogl/core/src/display/render/composer.rs
  lib/rust/ensogl/core/src/display/render/pass.rs
  lib/rust/ensogl/core/src/display/render/passes/cache_shapes.rs
  lib/rust/ensogl/core/src/system/gpu/data/texture/class.rs
Labels: CI: No changelog needed

#6496 Make execution mode `live` default for CLI
  engine/runner/src/main/scala/org/enso/runner/Main.scala
  test/Tests/src/Semantic/Runtime_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#6482 Limit Dead Letter logging
  engine/language-server/src/main/resources/application.conf
  lib/scala/project-manager/src/main/resources/application.conf
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#6493 DataflowAnalysis preserves dependencies order
  engine/runtime-with-polyglot/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DataflowAnalysis.scala
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#6477 Multiflavor layers
  lib/rust/ensogl/core/src/display/scene/layer.rs
  lib/rust/ensogl/core/src/display/shape/primitive/system.rs
Labels: CI: Ready to merge, CI: No changelog needed

#6483 Fix layer ordering between dropdown and breadcrumbs backgrounds.
  app/gui/view/execution-environment-selector/src/lib.rs
  app/gui/view/graph-editor/src/component/breadcrumbs.rs
  lib/rust/ensogl/core/src/display/scene.rs
Labels: CI: Ready to merge, CI: No changelog needed

#6352 Reimplement `enso_project` as a proper builtin
  CHANGELOG.md
  app/gui/src/controller/searcher.rs
  build.sbt
  distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Meta/Enso_Project.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Id.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EnsoProjectNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/constant/EnsoProjectNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  engine/runtime/src/main/scala/org/enso/compiler/SerializationManager.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/data/BindingsMap.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/BindingAnalysis.scala
  engine/runtime/src/test/java/org/enso/compiler/ExecCompilerTest.java
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/BindingAnalysisTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/EnsoProjectTest.scala
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/MethodProcessor.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/model/MethodDefinition.java
  test/Tests/src/Semantic/Meta_Location_Spec.enso
  test/Visualization_Tests/src/Id_Spec.enso
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Meta.enso
Labels: CI: Ready to merge

#6422 Fix doubled named arguments bug
  app/gui/language/span-tree/src/action.rs
  app/gui/language/span-tree/src/node.rs
  app/gui/src/controller/graph.rs
Labels: CI: Ready to merge, CI: No changelog needed

#6448 Cloud/desktop mode switcher
  app/gui/config.yaml
  app/ide-desktop/eslint.config.js
  app/ide-desktop/lib/content/esbuild-config.ts
  app/ide-desktop/lib/content/src/index.html
  app/ide-desktop/lib/content/src/index.ts
  app/ide-desktop/lib/content/src/newtype.ts
  app/ide-desktop/lib/content/src/project_manager.ts
  app/ide-desktop/lib/dashboard/bundle.ts
  app/ide-desktop/lib/dashboard/esbuild-config.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/registration.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/resetPassword.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/setUsername.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/auth.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/components/app.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/components/svg.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/backend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/changePasswordModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/directoryCreateForm.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/fileCreateForm.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/ide.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectActionButton.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectCreateForm.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/secretCreateForm.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/templates.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/topBar.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/uploadFileModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/userMenu.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/localBackend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/projectManager.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/remoteBackend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/index.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/providers/backend.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/uploadMultipleFiles.ts
  app/ide-desktop/lib/dashboard/src/index.tsx
  app/ide-desktop/lib/dashboard/src/serviceWorker.ts
  app/ide-desktop/lib/types/modules.d.ts
  app/ide-desktop/lib/types/types.d.ts
  lib/rust/ensogl/pack/js/src/runner/index.ts
Labels: CI: Ready to merge, CI: No changelog needed

#6513 Fix application config
  engine/language-server/src/main/resources/application.conf
  lib/scala/project-manager/src/main/resources/application.conf
Labels: CI: Ready to merge, CI: No changelog needed

#6478 IDE's logging to a file
  app/ide-desktop/eslint.config.js
  app/ide-desktop/lib/client/src/index.ts
  app/ide-desktop/lib/client/src/log.ts
  app/ide-desktop/lib/client/src/paths.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#6514 Force pending saves if client closes abruptly
  engine/language-server/src/main/scala/org/enso/languageserver/text/CollaborativeBuffer.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/TextOperationsTest.scala
  lib/scala/json-rpc-server-test/src/main/scala/org/enso/jsonrpc/test/JsonRpcServerTestKit.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerController.scala
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#6314 Run typecheck and eslint on `./run lint`
  app/ide-desktop/lib/client/src/file-associations.ts
  build/cli/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#6535 Delete unused websocket dependency
  Cargo.lock
  app/gui/Cargo.toml
Labels: CI: Ready to merge, CI: No changelog needed

#6525 Infer correct synthetic name for nested modules
  engine/runtime/src/main/scala/org/enso/compiler/PackageRepository.scala
  engine/runtime/src/test/resources/Test_Deeply_Nested_Modules/package.yaml
  engine/runtime/src/test/resources/Test_Deeply_Nested_Modules/src/A.enso
  engine/runtime/src/test/resources/Test_Deeply_Nested_Modules/src/A/A_Mod.enso
  engine/runtime/src/test/resources/Test_Deeply_Nested_Modules/src/A/B.enso
  engine/runtime/src/test/resources/Test_Deeply_Nested_Modules/src/A/B/B_Mod.enso
  engine/runtime/src/test/resources/Test_Deeply_Nested_Modules/src/A/B/C/C_Mod.enso
  engine/runtime/src/test/resources/Test_Deeply_Nested_Modules/src/A/B/C/D/D_Mod.enso
  engine/runtime/src/test/resources/Test_Deeply_Nested_Modules/src/Main.enso
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/ImportsTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#6421 Fix cut-off in text visualisations
  CHANGELOG.md
  app/gui/view/examples/text-grid-visualization/src/lib.rs
  app/gui/view/graph-editor/src/builtin/visualization/native/text_visualization.rs
  app/gui/view/graph-editor/src/builtin/visualization/native/text_visualization/grid_view_entry.rs
Labels: CI: Ready to merge

#6551 Build nightly 3 hours earlier
  .github/workflows/nightly.yml
  build/build/src/ci_gen.rs
Labels: CI: No changelog needed

#6567 Fix TypeScript lint errors
  app/ide-desktop/lib/content-config/src/index.ts
  app/ide-desktop/lib/types/modules.d.ts
Labels: CI: No changelog needed

#6487 Disregard visualisation for selection of nodes.
  CHANGELOG.md
  app/gui/view/graph-editor/src/component/node.rs
  app/gui/view/graph-editor/src/selection.rs
Labels: CI: Ready to merge

#6569 Fix early resize
  lib/rust/ensogl/core/src/display/render/composer.rs
  lib/rust/ensogl/core/src/display/render/pass.rs
Labels: CI: No changelog needed

#6537 Fix default dynamic-asssets directory
  app/ide-desktop/lib/content/src/index.ts
  lib/rust/ensogl/pack/js/src/runner/config.json
Labels: CI: Ready to merge, CI: Keep up to date, CI: No changelog needed

#6564 Only `Join_Kind.Inner` removes the common-named columns
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Common/Database_Join_Helper.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  test/Table_Tests/src/Common_Table_Operations/Integration_Tests.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Join_Spec.enso
  test/Table_Tests/src/Database/Upload_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#6530 Fix #5075: stop panning on full-screen visualisation
  CHANGELOG.md
  app/gui/view/graph-editor/src/lib.rs
Labels: CI: Ready to merge, CI: Keep up to date

#6548 Let ChangesetBuilder.invalidated search even container elements
  engine/runtime/src/main/scala/org/enso/compiler/context/ChangesetBuilder.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/context/ChangesetBuilderTest.scala
Labels: CI: No changelog needed, --bug

#6502 Fix dashboard issues
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/ide.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectActionButton.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/templates.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/topBar.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/localBackend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/index.tsx
Labels: CI: No changelog needed

#6574 Identify SyntaxError exception and avoid printing a stack trace
  engine/runner/src/main/scala/org/enso/runner/Main.scala
  engine/runtime/src/main/java/org/enso/compiler/exception/CompilationAbortedException.java
  engine/runtime/src/main/scala/org/enso/compiler/exception/CompilationAbortedException.scala
  engine/runtime/src/test/java/org/enso/interpreter/test/EqualsTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/PolyglotErrorTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/TestBase.java
  engine/runtime/src/test/java/org/enso/interpreter/test/ValuesGenerator.java
Labels: CI: No changelog needed

#6507 Fix opening links in desktop IDE
  app/ide-desktop/lib/client/src/security.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/topBar.tsx
Labels: CI: No changelog needed

#6585 Catch 5813 and avoid crash
  app/gui/view/documentation/src/html.rs
  app/gui/view/documentation/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#6534 Benchmark Engine job runs only engine, not Enso benchmarks
  .github/workflows/benchmark.yml
  build/build/src/ci_gen.rs
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/main/scala/org/enso/compiler/data/BindingsMap.scala
Labels: CI: No changelog needed, -ci

#6539 "at_least_one" flag for tokenize_to_rows
  CHANGELOG.md
  app/ide-desktop/lib/dashboard/src/index.html
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Split_Tokenize.enso
  test/Table_Tests/src/In_Memory/Split_Tokenize_Spec.enso
Labels: CI: Ready to merge, CI: Clean build required

#6533 Small changes from Book Club issues
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Map.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Period.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Period.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File_Format.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Delimited/Delimited_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Join_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Problem_Builder.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Split_Tokenize.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Unique_Name_Strategy.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  std-bits/base/src/main/java/org/enso/base/time/Date_Period_Utils.java
  std-bits/table/src/main/java/org/enso/table/read/DelimitedReader.java
  std-bits/table/src/main/java/org/enso/table/util/NameDeduplicator.java
  test/Table_Tests/src/Common_Table_Operations/Aggregate_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Core_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Cross_Tab_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Integration_Tests.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Cross_Join_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Join_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Zip_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Select_Columns_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Transpose_Spec.enso
  test/Table_Tests/src/Database/Codegen_Spec.enso
  test/Table_Tests/src/Database/Upload_Spec.enso
  test/Table_Tests/src/Helpers/Unique_Naming_Strategy_Spec.enso
  test/Table_Tests/src/IO/Csv_Spec.enso
  test/Table_Tests/src/IO/Delimited_Read_Spec.enso
  test/Table_Tests/src/IO/Delimited_Write_Spec.enso
  test/Table_Tests/src/IO/Excel_Spec.enso
  test/Table_Tests/src/In_Memory/Column_Spec.enso
  test/Table_Tests/src/In_Memory/Join_Performance_Spec.enso
  test/Table_Tests/src/In_Memory/Split_Tokenize_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
  test/Table_Tests/src/Util.enso
  test/Tests/src/Data/Time/Date_Spec.enso
  test/Visualization_Tests/src/Lazy_Table_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#6366 Show error pop-up when failing to rename a project
  CHANGELOG.md
  Cargo.lock
  app/gui/controller/engine-protocol/src/common/error.rs
  app/gui/src/model/project/synchronized.rs
  app/gui/src/presenter/project.rs
  app/gui/view/examples/interface/src/lib.rs
  app/gui/view/graph-editor/Cargo.toml
  app/gui/view/graph-editor/src/component/breadcrumbs.rs
  app/gui/view/graph-editor/src/component/breadcrumbs/project_name.rs
  app/gui/view/src/debug_mode_popup.rs
  app/gui/view/src/lib.rs
  app/gui/view/src/popup.rs
  app/gui/view/src/project.rs
  build-config.yaml
  integration-test/tests/graph_editor.rs
Labels: CI: Ready to merge, CI: Keep up to date

#6570 Fix the Engine version check in GUI
  Cargo.lock
  Cargo.toml
  app/gui/Cargo.toml
  app/gui/config.yaml
  app/gui/config/Cargo.toml
  app/gui/config/src/lib.rs
  app/gui/src/controller/project.rs
  app/gui/src/model/project/synchronized.rs
  build/build/Cargo.toml
  build/ci_utils/Cargo.toml
  lib/rust/ensogl/core/Cargo.toml
Labels: CI: Ready to merge, CI: No changelog needed

#6602 Revert typescript CI Lint changes
  app/ide-desktop/lib/client/src/file-associations.ts
  app/ide-desktop/lib/content-config/src/index.ts
  app/ide-desktop/lib/types/modules.d.ts
  build/cli/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#6575 Fix visualisation type selector artifacts rendered after node preview visualisation was closed.
  app/gui/view/graph-editor/src/component/visualization/container.rs
Labels: CI: Ready to merge, CI: No changelog needed

#6538 Add format to the in-memory Column
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Of_Day.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column_Format.enso
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoDateTime.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoTimeOfDay.java
  std-bits/base/src/main/java/org/enso/base/Time_Utils.java
  test/Table_Tests/src/In_Memory/Column_Format_Spec.enso
  test/Table_Tests/src/In_Memory/Main.enso
  test/Tests/src/Data/Time/Date_Spec.enso
  test/Tests/src/Data/Time/Date_Time_Spec.enso
  test/Tests/src/Data/Time/Time_Of_Day_Spec.enso
Labels: CI: Ready to merge, CI: Clean build required

#6594 Fix node editing race condition
  app/gui/view/src/project.rs
Labels: CI: Ready to merge, CI: No changelog needed

#6607 tokenize_to_columns or parse_to_columns results in a single column we shouldn't add the 1
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Split_Tokenize.enso
  test/Table_Tests/src/In_Memory/Split_Tokenize_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#6606 Add tests for Date.until, Date.next and Date.previous.
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date.enso
  test/Tests/src/Data/Time/Date_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#6620 Fix #6377: Change ctrl-r shortcut
  CHANGELOG.md
  app/gui/docs/product/shortcuts.md
  app/gui/view/src/project.rs
Labels: CI: Ready to merge

#6566 Fix asset delete; implement project delete and project rename
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/changePasswordModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/confirmDeleteModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/renameModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/uploadFileModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/localBackend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/remoteBackend.ts
  app/ide-desktop/lib/dashboard/src/index.html
Labels: CI: No changelog needed

#6577 Limit the number of reported warnings
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Warning.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Warnings.enso
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextEventsListener.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistryProtocol.scala
  engine/polyglot-api/src/main/java/org/enso/polyglot/RuntimeOptions.java
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runner/src/main/scala/org/enso/runner/ContextFactory.scala
  engine/runner/src/main/scala/org/enso/runner/Main.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime-with-polyglot/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/WarningBenchmarks.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/IndirectInvokeCallableNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/IndirectInvokeConversionNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/IndirectInvokeMethodNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeCallableNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeConversionNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/CaseNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/atom/InstantiateNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/foreign/CoerceNothing.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Array.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/ArraySlice.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Vector.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/Warning.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/WarningsLibrary.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/WithWarnings.java
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime/src/test/java/org/enso/interpreter/test/WarningsTest.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/MethodProcessor.java
  test/Tests/src/Data/Vector_Spec.enso
  test/Tests/src/Semantic/Warnings_Spec.enso
Labels: CI: Ready to merge

#6629 Automatic type based dropdown does not include singleton in a union type
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/Any.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/Builtin.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/Error.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/Nothing.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/Panic.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/function/Function.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/Decimal.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/Integer.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/Number.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/Text.java
  engine/runtime/src/main/scala/org/enso/compiler/SerializationManager.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/AnalyzeModuleInScopeJob.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/AnalyzeModuleJob.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/context/SuggestionBuilderTest.scala
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/BuiltinsProcessor.java
Labels: CI: Ready to merge, CI: No changelog needed

#6644 Fix shortcuts table formatting
  app/gui/docs/product/shortcuts.md
Labels: CI: Ready to merge, CI: No changelog needed

#6647 Revert "Add COOP+COEP+CORP headers (#6597)"
  app/ide-desktop/lib/client/src/bin/server.ts
  app/ide-desktop/lib/common/src/index.ts
  app/ide-desktop/lib/content/esbuild-config.ts
  app/ide-desktop/lib/content/src/index.ts
  app/ide-desktop/lib/content/src/serviceWorker.ts
  app/ide-desktop/lib/content/watch.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/components/svg.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/topBar.tsx
  app/ide-desktop/lib/dashboard/src/serviceWorker.ts
Labels: CI: Ready to merge, CI: No changelog needed

#6643 Whitelist AWS Cognito domains
  app/ide-desktop/lib/client/src/security.ts
Labels: CI: Ready to merge, CI: No changelog needed

#6617 Fix #6287: wrong nested breadcrumb ordering
  CHANGELOG.md
  app/gui/src/controller/graph/executed.rs
  app/gui/src/controller/project.rs
  app/gui/src/presenter/graph.rs
  app/gui/src/presenter/graph/call_stack.rs
  app/gui/src/presenter/graph/visualization.rs
  app/gui/view/graph-editor/src/component/breadcrumbs.rs
  app/gui/view/graph-editor/src/component/breadcrumbs/breadcrumb.rs
Labels: CI: Ready to merge

#6605 Fix redirect paths and enable authentication and new dashboard by default
  app/ide-desktop/lib/content-config/src/config.json
  app/ide-desktop/lib/content/esbuild-config.ts
  app/ide-desktop/lib/content/src/index.ts
  app/ide-desktop/lib/content/src/serviceWorker.ts
  app/ide-desktop/lib/content/watch.ts
  app/ide-desktop/lib/dashboard/esbuild-config.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/config.ts
  app/ide-desktop/lib/dashboard/watch.ts
  app/ide-desktop/lib/types/globals.d.ts
Labels: CI: Ready to merge, CI: No changelog needed

#6642 All Vector operations shall be applicable on java.util.ArrayList
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/immutable/SliceArrayVectorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Array.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Vector.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicException.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/model/MethodDefinition.java
  test/Tests/src/Data/Vector_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#6621 Add `Date_Range`
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/List.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Map.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Pair.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Range/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Period.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Period.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Period.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  std-bits/base/src/main/java/org/enso/base/Time_Utils.java
  test/Tests/src/Data/Range_Spec.enso
  test/Tests/src/Data/Time/Date_Range_Spec.enso
  test/Tests/src/Data/Time/Spec.enso
Labels: CI: Ready to merge

#6614 Fix blank input port
  app/gui/view/graph-editor/src/component/node/input/widget.rs
Labels: CI: Ready to merge, CI: No changelog needed

#6512 Implement loading spinner for visualisations.
  CHANGELOG.md
  Cargo.lock
  app/gui/view/documentation/src/lib.rs
  app/gui/view/graph-editor/src/component/visualization/container.rs
  lib/rust/ensogl/component/Cargo.toml
  lib/rust/ensogl/component/spinner/Cargo.toml
  lib/rust/ensogl/component/spinner/src/lib.rs
  lib/rust/ensogl/component/src/lib.rs
Labels: CI: Ready to merge

#6646 Add COOP+COEP+CORP headers
  app/gui/view/examples/text-grid-visualization/src/lib.rs
  app/gui/view/graph-editor/src/builtin/visualization/java_script/heatmap.js
  app/gui/view/graph-editor/src/builtin/visualization/java_script/helpers/loading.js
  app/gui/view/graph-editor/src/builtin/visualization/java_script/histogram.js
  app/gui/view/graph-editor/src/builtin/visualization/java_script/scatterPlot.js
  app/ide-desktop/lib/client/src/bin/server.ts
  app/ide-desktop/lib/common/src/index.ts
  app/ide-desktop/lib/content/esbuild-config.ts
  app/ide-desktop/lib/content/src/serviceWorker.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/components/svg.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/topBar.tsx
  app/ide-desktop/lib/dashboard/src/serviceWorker.ts
Labels: CI: No changelog needed

#6670 Removing flush
  lib/rust/ensogl/core/src/display/render/passes/pixel_read.rs
Labels: CI: No changelog needed

#6653 Improvements to the Table visualization.
  app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Metadata.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
Labels: CI: Ready to merge, CI: No changelog needed

#6655 SuggestionBuilder needs to send ascribedType of constructor parameters
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/File_Error.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Type/Value_Type.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Excel_Reader.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Test.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/SQL/Visualization.enso
  engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/TypeNames.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/TypeSignatures.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/context/SuggestionBuilderTest.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala
  test/Benchmarks/src/Vector/Utils.enso
  test/Tests/src/Semantic/Default_Args_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#6584 Verify ascribed types of parameters really exist
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Match.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  engine/runtime/src/main/java/org/enso/compiler/TreeToIr.java
  engine/runtime/src/main/scala/org/enso/compiler/data/BindingsMap.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/GlobalNames.scala
  engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java
Labels: CI: Ready to merge, CI: No changelog needed

#6680 Force `newDashboard` default on the CI-built packages.
  app/gui/view/documentation/src/lib.rs
  build/base/src/fs.rs
  build/build/paths.yaml
  build/build/src/project/gui.rs
  lib/rust/ensogl/component/spinner/src/lib.rs
Labels: CI: No changelog needed

#6671 Fix `--startup.project` to bypass opening dashboard
  app/ide-desktop/lib/content/src/index.ts
Labels: CI: No changelog needed

#6665 Ensure slow shutdown of LS always kicks off hooks
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerController.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerKiller.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerRegistry.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/ShutdownHookActivator.scala
Labels: CI: Ready to merge, CI: No changelog needed

#6696 Fix logic for enabling dashboard
  app/ide-desktop/lib/content/src/index.ts
Labels: CI: No changelog needed

#6321 Show spinner when opening/creating a project
  app/gui/src/controller/ide.rs
  app/gui/src/controller/ide/desktop.rs
  app/gui/src/controller/searcher.rs
  app/gui/src/controller/searcher/action.rs
  app/gui/src/ide.rs
  app/gui/src/ide/initializer.rs
  app/gui/src/integration_test.rs
  app/gui/src/presenter.rs
  app/gui/src/presenter/project.rs
  app/gui/src/presenter/searcher/provider.rs
  app/gui/src/tests.rs
  app/gui/view/src/project.rs
  app/gui/view/src/project_list.rs
  app/gui/view/src/root.rs
  build-config.yaml
  integration-test/tests/engine.rs
  lib/rust/ensogl/pack/js/src/runner/index.ts
Labels: CI: Ready to merge, CI: No changelog needed

#6683 Fix opening cloud projects on desktop IDE
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/ide.tsx
Labels: CI: No changelog needed

#6703 Add verbose logs mention to CONTRIBUTING.md
  docs/CONTRIBUTING.md
Labels: CI: Ready to merge, CI: No changelog needed

#6638 Fix FRP events that deactivate visualizations.
  app/gui/view/graph-editor/src/component/visualization/container.rs
  app/gui/view/graph-editor/src/component/visualization/container/visualization_chooser.rs
Labels: CI: Ready to merge, CI: No changelog needed

#6663 Change full-screen visualisation shortcut to shift-space
  CHANGELOG.md
  app/gui/view/graph-editor/src/lib.rs
  app/gui/view/graph-editor/src/shortcuts.rs
Labels: CI: Ready to merge

#6540 Fix list editor panics during insertion
  Cargo.lock
  Cargo.toml
  app/gui/language/span-tree/src/generate.rs
  app/gui/language/span-tree/src/lib.rs
  app/gui/language/span-tree/src/node.rs
  app/gui/src/controller/graph/widget/configuration.rs
  app/gui/src/controller/graph/widget/response.rs
  app/gui/view/graph-editor/Cargo.toml
  app/gui/view/graph-editor/src/component/edge.rs
  app/gui/view/graph-editor/src/component/node.rs
  app/gui/view/graph-editor/src/component/node/input/area.rs
  app/gui/view/graph-editor/src/component/node/input/port.rs
  app/gui/view/graph-editor/src/component/node/input/widget.rs
  app/gui/view/graph-editor/src/component/node/input/widget/list_editor.rs
  app/gui/view/graph-editor/src/component/node/input/widget/single_choice.rs
  app/gui/view/graph-editor/src/component/node/output/port.rs
  app/gui/view/graph-editor/src/component/node/vcs.rs
  app/gui/view/graph-editor/src/lib.rs
  app/ide-desktop/lib/content-config/src/config.json
  build-config.yaml
  lib/rust/ensogl/component/list-editor/src/lib.rs
  lib/rust/ensogl/core/Cargo.toml
  lib/rust/ensogl/core/src/display/object/event.rs
  lib/rust/ensogl/core/src/display/object/instance.rs
  lib/rust/ensogl/core/src/display/scene.rs
  lib/rust/ensogl/core/src/display/shape/compound/rectangle.rs
  lib/rust/ensogl/core/src/display/shape/primitive/system.rs
  lib/rust/ensogl/core/src/gui/cursor.rs
  lib/rust/ensogl/examples/cached-shape/src/lib.rs
  lib/rust/frp/src/nodes.rs
  lib/rust/prelude/src/string.rs
Labels: CI: Ready to merge, CI: Keep up to date, CI: No changelog needed, CI: Clean build required

#6714 Show spinner while loading assets
  app/ide-desktop/lib/dashboard/src/authentication/src/components/svg.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/rows.tsx
Labels: CI: No changelog needed

#6740 Meta.meta Integer . methods
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/GetTypeMethodsNode.java
  test/Tests/src/Semantic/Meta_Spec.enso
Labels: CI: No changelog needed, CI: Clean build required

#6687 Display "modified at" column on the cloud dashboard
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/backend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/rows.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/dateTime.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/localBackend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/projectManager.ts
Labels: CI: No changelog needed

#6755 Only send suggestions updates when type changes
  CHANGELOG.md
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/language-server/src/test/scala/org/enso/languageserver/runtime/ContextEventsListenerSpec.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeErrorsTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeExecutionEnvironmentTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime-with-polyglot/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/RecomputeContextCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/TestMessages.scala
Labels: CI: Ready to merge

#6661 Display Initializing project... message when initializing project
  app/gui/view/graph-editor/src/component/breadcrumbs/project_name.rs
Labels: CI: Ready to merge, CI: No changelog needed

#6711 Implement `cast` for Table and Column
  CHANGELOG.md
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Type/Value_Type.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Cast_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Parse_Values_Helper.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Problems.enso
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoDate.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoTimeOfDay.java
  lib/scala/common-polyglot-core-utils/src/main/java/org/enso/polyglot/common_utils/Core_Date_Utils.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/object/Builder.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/CastProblemBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/DateStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/DateTimeStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/DoubleStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/LongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/MixedStorageFacade.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/ObjectStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/SpecializedStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/Storage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/StringStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/TimeOfDayStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/type/IntegerType.java
  test/Table_Tests/data/.gitignore
  test/Table_Tests/src/Common_Table_Operations/Cast_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Conversion_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Main.enso
  test/Tests/polyglot-sources/enso-test-java-helpers/src/main/java/org/enso/table_test_helpers/ExplodingStorage.java
Labels: CI: Ready to merge

#6689 Fix file uploading node expression.
  app/gui/src/controller/upload.rs
Labels: CI: Ready to merge, CI: No changelog needed

#6778 Set suggestion reexports when serializing the library
  engine/language-server/src/test/scala/org/enso/languageserver/search/SuggestionsHandlerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/SuggestionsHandlerEventsTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/ExportedSymbol.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/Suggestion.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeSuggestionUpdatesTest.scala
  engine/runtime/src/main/java/org/enso/compiler/context/ExportsMap.java
  engine/runtime/src/main/scala/org/enso/compiler/SerializationManager.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/ExportsBuilder.scala
  engine/runtime/src/main/scala/org/enso/compiler/data/BindingsMap.scala
Labels: CI: Ready to merge, CI: No changelog needed

#6743 Decimal/Integer .round and .int #6654
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/decimal/TruncateNode.java
  test/Tests/src/Data/Numbers_Spec.enso
  test/Tests/src/Semantic/Meta_Spec.enso
Labels: CI: Ready to merge

#6731 Implement simple variants of `parse` for the Database backend
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Type_Mapping.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Problems.enso
  test/Table_Tests/src/Common_Table_Operations/Conversion_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Date_Time_Spec.enso
  test/Table_Tests/src/Database/Types/SQLite_Type_Mapping_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#6768 Widgets, Vector as Column, Viz Fixes and Rename Columns
  app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Filter_Condition.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Index_Sub_Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Map.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Encoding.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Text_Sub_Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Problem_Behavior.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File_Format.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Widget_Helpers.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Database.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column_Vector_Extensions.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Row.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table_Conversions.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Column_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Problem_Builder.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Extensions.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
  test/Table_Tests/src/Common_Table_Operations/Date_Time_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Expression_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Filter_Spec.enso
  test/Table_Tests/src/Database/Types/Postgres_Type_Mapping_Spec.enso
  test/Table_Tests/src/Database/Types/SQLite_Type_Mapping_Spec.enso
  test/Table_Tests/src/In_Memory/Column_Format_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#6726 Add a compiler pass to analyze non-existing imported symbols
  engine/runtime/src/main/scala/org/enso/compiler/Passes.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/main/scala/org/enso/compiler/data/BindingsMap.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/ImportSymbolAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/FullyQualifiedNames.scala
  engine/runtime/src/main/scala/org/enso/compiler/phase/ImportResolver.scala
  engine/runtime/src/test/java/org/enso/compiler/ErrorCompilerTest.java
  engine/runtime/src/test/scala/org/enso/compiler/test/PassesTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/semantic/ImportExportTest.scala
  test/Table_Tests/src/Database/Codegen_Spec.enso
  test/Tests/src/Semantic/Deep_Export/Internal_3.enso
  test/Tests/src/Semantic/Deep_Export/Spec.enso
  test/Tests/src/Semantic/Names_Spec.enso
  tools/performance/engine-benchmarks/bench_download.py
Labels: CI: No changelog needed

#6780 Add project creation time to project metadata
  CHANGELOG.md
  docs/language-server/protocol-project-manager.md
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/data/ProjectMetadata.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectService.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala
Labels: CI: Ready to merge

#6801 feat: set constructor args tag values
  engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/context/SuggestionBuilderTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#6803 Missing conversion of hash key in EqualsNode
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsComplexNode.java
  engine/runtime/src/test/java/org/enso/interpreter/test/HashCodeTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/ValuesGenerator.java
Labels: CI: No changelog needed

#6752 Reloading file in LS after desynchronization.
  CHANGELOG.md
  app/gui/docs/product/shortcuts.md
  app/gui/src/model/module.rs
  app/gui/src/model/module/plain.rs
  app/gui/src/model/module/synchronized.rs
  app/gui/src/model/project/synchronized.rs
  app/gui/src/presenter/graph.rs
  app/gui/src/test.rs
  app/gui/view/graph-editor/src/lib.rs
  app/gui/view/graph-editor/src/shortcuts.rs
  app/gui/view/src/project.rs
Labels: CI: Ready to merge

#6779 Disable cloud backend for unverified users; use local backend as default backend; minor bugfixes
  app/ide-desktop/lib/content/src/index.ts
  app/ide-desktop/lib/content/src/serviceWorker.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/auth.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/components/app.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/backend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/changePasswordModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/renameModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/userMenu.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/localBackend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/projectManager.ts
  app/ide-desktop/lib/dashboard/src/index.tsx
  app/ide-desktop/lib/dashboard/src/serviceWorker.ts
Labels: CI: No changelog needed

#6794 Use state sent with `GET /directories` instead of querying state separately
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/backend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectActionButton.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/localBackend.ts
Labels: CI: No changelog needed

#6813 Filter suggestion constructors when searching by self type
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlSuggestionsRepo.scala
  lib/scala/searcher/src/test/scala/org/enso/searcher/sql/SuggestionsRepoTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#6808 Import/export syntax error have more specific messages
  engine/runtime/src/main/java/org/enso/compiler/TreeToIr.java
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/test/java/org/enso/compiler/ErrorCompilerTest.java
Labels: CI: No changelog needed

#6750 Update GraalVM to 22.3.1 JDK17
  CHANGELOG.md
  app/ide-desktop/lib/client/tasks/signArchivesMacOs.ts
  build.sbt
  build/ci_utils/src/cache/goodie/graalvm.rs
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/GraalVMComponentConfiguration.scala
  lib/scala/runtime-version-manager/src/test/scala/org/enso/runtimeversionmanager/components/GraalVMComponentConfigurationSpec.scala
  test/Table_Tests/src/In_Memory/Column_Format_Spec.enso
  test/Tests/src/Network/Http_Spec.enso
  tools/ci/docker/Dockerfile
  tools/enso4igv/src/test/java/org/enso/tools/enso4igv/EnsoSbtProjectTest.java
Labels: CI: Clean build required

#6830 do not activate nested dropdowns together
  app/gui/view/graph-editor/src/component/node/input/widget/single_choice.rs
Labels: CI: Ready to merge, CI: No changelog needed

#6820 Various test improvements to increase coverage and speed things up
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Interval.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Pattern.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/MetaIsAPolyglotTest.java
  engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/MetaObjectPolyglotTest.java
  engine/runtime/src/test/java/org/enso/compiler/EnsoCompilerTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/EqualsTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/HashCodeTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/MetaIsATest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/MetaObjectTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/ValuesGenerator.java
  engine/runtime/src/test/java/org/enso/interpreter/test/VectorSortTest.java
Labels: CI: Keep up to date, CI: No changelog needed, CI: Clean build required

#6824 Fix "set username" screen
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/auth.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/components/app.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectActionButton.tsx
Labels: CI: No changelog needed

#6668 Fix some dashboard issues
  app/ide-desktop/lib/client/start.ts
  app/ide-desktop/lib/client/watch.ts
  app/ide-desktop/lib/content-config/src/config.json
  app/ide-desktop/lib/content/bundle.ts
  app/ide-desktop/lib/content/esbuild-config.ts
  app/ide-desktop/lib/content/globals.d.ts
  app/ide-desktop/lib/content/src/index.ts
  app/ide-desktop/lib/content/start.ts
  app/ide-desktop/lib/content/watch.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/cognito.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/registration.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/resetPassword.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/auth.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/session.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/service.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/components/app.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/backend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/changePasswordModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/directoryCreateForm.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/fileCreateForm.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/ide.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectActionButton.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectCreateForm.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/secretCreateForm.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/topBar.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/uploadFileModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/localBackend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/projectManager.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/remoteBackend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/validation.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/detect.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/index.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/platform.ts
  app/ide-desktop/lib/dashboard/src/index.tsx
  app/ide-desktop/lib/types/globals.d.ts
  lib/rust/ensogl/pack/js/src/runner/config.ts
  lib/rust/ensogl/pack/js/src/runner/index.ts
Labels: CI: Ready to merge, CI: No changelog needed

#6837 Handle `show-dashboard` event
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
Labels: CI: Ready to merge, CI: No changelog needed

#6844 Stop graph editing when in full-screen visualization mode
  CHANGELOG.md
  app/gui/view/graph-editor/src/shortcuts.rs
Labels: CI: Ready to merge

#6777 Allow casting a Mixed column into a concrete type
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Cast_Helpers.enso
  std-bits/table/src/main/java/org/enso/table/data/column/builder/object/DoubleBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/object/LongBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/object/NumericBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/string/StorageBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/string/StringStorageBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/CastProblemBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/CastProblemBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/StorageConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/ToBooleanStorageConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/ToDateStorageConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/ToDateTimeStorageConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/ToFloatStorageConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/ToIntegerStorageConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/ToMixedStorageConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/ToTextStorageConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/ToTimeOfDayStorageConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/DateStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/DateTimeStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/DoubleStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/LongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/MixedStorageFacade.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/ObjectStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/SpecializedStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/Storage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/StringStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/TimeOfDayStorage.java
  std-bits/table/src/main/java/org/enso/table/read/DelimitedReader.java
  test/Table_Tests/src/Common_Table_Operations/Conversion_Spec.enso
  test/Tests/polyglot-sources/enso-test-java-helpers/src/main/java/org/enso/table_test_helpers/ExplodingStorage.java
Labels: CI: Ready to merge, CI: No changelog needed

#6758 Only initialise visualisation chooser if it is used.
  app/gui/view/graph-editor/src/component/visualization/container.rs
  app/gui/view/graph-editor/src/component/visualization/container/action_bar.rs
Labels: CI: Ready to merge, CI: No changelog needed

#6840 Infrastructure for testing inter project imports and exports
  engine/runtime/src/test/resources/Logical_Import_Violated_Test/package.yaml
  engine/runtime/src/test/resources/Logical_Import_Violated_Test/src/Main.enso
  engine/runtime/src/test/scala/org/enso/compiler/test/semantic/ImportExportTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/InterpreterException.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/PackageTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/ImportsTest.scala
  test/micro-distribution/editions/0.0.0-dev.yaml
  test/micro-distribution/lib/Test/Logical_Export/0.0.0-dev/manifest.yaml
  test/micro-distribution/lib/Test/Logical_Export/0.0.0-dev/package.yaml
  test/micro-distribution/lib/Test/Logical_Export/0.0.0-dev/src/Api/Element.enso
  test/micro-distribution/lib/Test/Logical_Export/0.0.0-dev/src/Impl/Internal.enso
  test/micro-distribution/lib/Test/Logical_Export/0.0.0-dev/src/Main.enso
Labels: CI: No changelog needed

#6842 Detect and override hooks of the same kind
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/ShutdownHookActivator.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/shutdown/ShutdownHook.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/MoveProjectDirCmd.scala
Labels: CI: Ready to merge, CI: No changelog needed

#6849 Append warnings extracted before tail call execution
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeCallableNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeConversionNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java
  test/Tests/src/Semantic/Warnings_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#6786 Coalesce graph editor view invalidations
  app/gui/src/presenter/graph.rs
  app/gui/view/graph-editor/src/lib.rs
  lib/rust/ensogl/core/src/animation/loops.rs
Labels: CI: Ready to merge, CI: No changelog needed

#6833 Fix dashboard modal bugs
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/changePasswordModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/contextMenu.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/input.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/modal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/renameModal.tsx
Labels: CI: No changelog needed

#6873 Empty editions are not parsed as NaN
  lib/scala/editions/src/main/scala/org/enso/editions/EditionName.scala
  lib/scala/pkg/src/test/scala/org/enso/pkg/ConfigSpec.scala
Labels: CI: Ready to merge, CI: No changelog needed

#6810 Run IDE with Project Manager endpoint instead of Language Server endpoints, when on local backend
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/ide.tsx
Labels: CI: Ready to merge, CI: No changelog needed

#6878 Implement nested widget overrides
  app/gui/language/ast/impl/src/opr.rs
  app/gui/language/span-tree/example/src/lib.rs
  app/gui/language/span-tree/src/action.rs
  app/gui/language/span-tree/src/builder.rs
  app/gui/language/span-tree/src/generate.rs
  app/gui/language/span-tree/src/generate/context.rs
  app/gui/language/span-tree/src/iter.rs
  app/gui/language/span-tree/src/lib.rs
  app/gui/language/span-tree/src/node.rs
  app/gui/src/controller/graph/executed.rs
  app/gui/src/controller/graph/widget.rs
  app/gui/src/controller/graph/widget/configuration.rs
  app/gui/src/controller/graph/widget/response.rs
  app/gui/src/model/undo_redo.rs
  app/gui/src/presenter/graph.rs
  app/gui/src/presenter/graph/state.rs
  app/gui/suggestion-database/src/entry.rs
  app/gui/suggestion-database/src/lib.rs
  app/gui/view/graph-editor/src/component/node/action_bar.rs
  app/gui/view/graph-editor/src/component/node/input/widget.rs
  app/gui/view/graph-editor/src/component/node/input/widget/single_choice.rs
  app/gui/view/graph-editor/src/component/node/output/area.rs
  app/gui/view/graph-editor/src/lib.rs
  lib/rust/ensogl/core/src/data/color/animation.rs
  lib/rust/ensogl/core/src/display/scene.rs
  lib/rust/ensogl/core/src/display/shape/primitive/system.rs
Labels: CI: Ready to merge, CI: Keep up to date, CI: No changelog needed, CI: Clean build required

#6818 Import polyglot java inner classes
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/java/LookupClassNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  engine/runtime/src/test/java/org/enso/example/TestClass.java
  engine/runtime/src/test/java/org/enso/interpreter/test/JavaInteropTest.java
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/JavaInteropTest.scala
  project/NativeImage.scala
Labels: CI: No changelog needed

#6888 Disable node entering while editing
  app/gui/view/graph-editor/src/shortcuts.rs
Labels: CI: Ready to merge, CI: No changelog needed

#6902 Search for IR.Function deeper in the IR tree to find instance methods
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/TypeNames.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/TypeSignatures.scala
  engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java
Labels: CI: No changelog needed

#6654 Add drop down for Locale like Encoding
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Locale.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Of_Day.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  test/Tests/src/Data/Locale_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#6898 Fix month number in new dashboard
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/dateTime.ts
Labels: CI: No changelog needed

#6904 IGV Enso support recognizes lib/scala/pkg as project
  build.sbt
  lib/scala/pkg/src/main/java/org/enso/pkg/package-info.java
Labels: CI: Ready to merge, CI: No changelog needed
