Repository enso-org/enso, pull requests merged in 2023-04, with the labels that each got.

#6155 remove content_origin property from layout
  app/gui/view/component-browser/component-list-panel/breadcrumbs/src/entry.rs
  app/gui/view/component-browser/component-list-panel/breadcrumbs/src/lib.rs
  app/gui/view/component-browser/component-list-panel/grid/src/entry.rs
  app/gui/view/component-browser/component-list-panel/grid/src/entry/icon.rs
  app/gui/view/component-browser/component-list-panel/src/lib.rs
  app/gui/view/examples/documentation/src/lib.rs
  app/gui/view/examples/icons/src/lib.rs
  app/gui/view/graph-editor/src/builtin/visualization/native/bubble_chart.rs
  app/gui/view/graph-editor/src/component/add_node_button.rs
  app/gui/view/graph-editor/src/component/breadcrumbs.rs
  app/gui/view/graph-editor/src/component/breadcrumbs/breadcrumb.rs
  app/gui/view/graph-editor/src/component/breadcrumbs/project_name.rs
  app/gui/view/graph-editor/src/component/edge.rs
  app/gui/view/graph-editor/src/component/node.rs
  app/gui/view/graph-editor/src/component/node/action_bar.rs
  app/gui/view/graph-editor/src/component/node/action_bar/icon.rs
  app/gui/view/graph-editor/src/component/node/input/port.rs
  app/gui/view/graph-editor/src/component/node/input/widget.rs
  app/gui/view/graph-editor/src/component/node/output/port.rs
  app/gui/view/graph-editor/src/component/node/vcs.rs
  app/gui/view/graph-editor/src/component/profiling.rs
  app/gui/view/graph-editor/src/component/visualization/container.rs
  app/gui/view/graph-editor/src/component/visualization/container/action_bar.rs
  app/gui/view/graph-editor/src/component/visualization/container/fullscreen.rs
  app/gui/view/src/project_list.rs
  app/gui/view/src/status_bar.rs
  app/gui/view/src/window_control_buttons/fullscreen.rs
  lib/rust/ensogl/component/drop-down-menu/src/lib.rs
  lib/rust/ensogl/component/drop-down/src/model.rs
  lib/rust/ensogl/component/flame-graph/src/block.rs
  lib/rust/ensogl/component/flame-graph/src/mark.rs
  lib/rust/ensogl/component/grid-view/src/entry.rs
  lib/rust/ensogl/component/grid-view/src/selectable/highlight/shape.rs
  lib/rust/ensogl/component/label/src/lib.rs
  lib/rust/ensogl/component/list-view/src/lib.rs
  lib/rust/ensogl/component/scroll-area/src/lib.rs
  lib/rust/ensogl/component/selector/src/shape.rs
  lib/rust/ensogl/component/sequence-diagram/src/shape.rs
  lib/rust/ensogl/component/slider/src/model.rs
  lib/rust/ensogl/component/text/src/component/line.rs
  lib/rust/ensogl/component/text/src/component/selection.rs
  lib/rust/ensogl/core/src/display/object/instance.rs
  lib/rust/ensogl/core/src/display/object/transformation.rs
  lib/rust/ensogl/core/src/display/shape/compound/from_cache.rs
  lib/rust/ensogl/core/src/display/shape/compound/rectangle.rs
  lib/rust/ensogl/core/src/display/shape/primitive/system.rs
  lib/rust/ensogl/core/src/display/shape/primitive/system/cached.rs
  lib/rust/ensogl/core/src/display/symbol/gpu/geometry/compound/sprite.rs
  lib/rust/ensogl/core/src/gui/cursor.rs
  lib/rust/ensogl/examples/auto-layout/src/lib.rs
  lib/rust/ensogl/examples/cached-shape/src/lib.rs
  lib/rust/ensogl/examples/custom-shape-system/src/lib.rs
  lib/rust/ensogl/examples/focus-management/src/lib.rs
  lib/rust/ensogl/examples/mouse-events/src/lib.rs
  lib/rust/ensogl/examples/scroll-area/src/lib.rs
  lib/rust/ensogl/examples/text-area/src/lib.rs
  lib/rust/types/src/dim.rs
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#6164 bump shader tools version and use distribution install by default
  build/build/src/project/wasm.rs
  build/ci_utils/src/cache/goodie.rs
  build/ci_utils/src/goodies/shader_tools.rs
  build/cli/src/arg/wasm.rs
  build/cli/src/lib.rs
  lib/rust/ensogl/core/src/display/shape/primitive/system.rs
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#6143 Adjusting tests to new parser
  engine/runtime/src/main/java/org/enso/compiler/TreeToIr.java
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/OperatorToFunction.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/ExpressionAnnotations.scala
  engine/runtime/src/test/java/org/enso/compiler/AnnotationsCompilerTest.java
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/AliasAnalysisTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/DataflowAnalysisTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/ComplexTypeTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/FunctionBindingTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/LambdaShorthandToLambdaTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/ExpressionAnnotationsTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/IgnoredBindingsTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/SugaredTypeFunctionsTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/SuspendedArgumentsTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/TypeSignaturesTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/Metadata.scala
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#6142 A Stub for Vector Editor Widget.
  app/gui/view/graph-editor/src/component/node/input/area.rs
  app/gui/view/graph-editor/src/component/node/input/widget.rs
  app/gui/view/graph-editor/src/component/node/input/widget/vector_editor.rs
  app/ide-desktop/lib/content-config/src/config.json
Labels: CI: Ready to merge, CI: No changelog needed

#6121 Execution context switch expressions
  app/gui/controller/double-representation/src/context_switch.rs
  app/gui/controller/double-representation/src/lib.rs
  app/gui/controller/double-representation/src/name.rs
  app/gui/controller/double-representation/src/node.rs
  app/gui/controller/double-representation/src/refactorings/collapse.rs
  app/gui/language/ast/impl/src/lib.rs
  app/gui/language/ast/impl/src/macros/skip_and_freeze.rs
  app/gui/language/ast/impl/src/opr.rs
  app/gui/language/ast/impl/src/repr.rs
  app/gui/src/controller/graph.rs
  app/gui/src/controller/searcher/input.rs
  app/gui/src/presenter/graph.rs
  app/gui/src/presenter/graph/state.rs
Labels: CI: Ready to merge, CI: No changelog needed

#6170 do not override default shape alignment in macro
  app/gui/view/src/window_control_buttons.rs
  app/gui/view/src/window_control_buttons/close.rs
  lib/rust/ensogl/core/src/display/shape/primitive/system.rs
Labels: CI: No changelog needed

#6004 Add JSON-RPC endpoints
  app/ide-desktop/lib/content/src/newtype.ts
  app/ide-desktop/lib/content/src/project_manager.ts
Labels: CI: Ready to merge, CI: No changelog needed

#6160 Small issues from working with Ned
  app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js
  distribution/lib/Standard/Base/0.0.0-dev/src/System/Process.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/Process/Process_Builder.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Unique_Name_Strategy.enso
  std-bits/table/src/main/java/org/enso/table/util/NameDeduplicator.java
  test/Image_Tests/src/Image_Read_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Cross_Join_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Join_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Zip_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Helpers/Unique_Naming_Strategy_Spec.enso
  test/Tests/src/System/File_Spec.enso
  test/Tests/src/System/Process_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#6150 #5123 Text.tokenize
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Case_Sensitivity.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Pattern_2.enso
  test/Tests/src/Data/Text/Regex_2_Spec.enso
  test/Tests/src/Data/Text_Spec.enso
Labels: CI: Ready to merge

#6190 Add prettier commit to git-blame-ignore
  .git-blame-ignore-revs
Labels: CI: No changelog needed

#6140 Instance ordering
  Cargo.lock
  app/gui/src/ide/initializer.rs
  build-config.yaml
  lib/rust/ensogl/core/src/data/seq/observable.rs
  lib/rust/ensogl/core/src/display/object.rs
  lib/rust/ensogl/core/src/display/object/instance.rs
  lib/rust/ensogl/core/src/display/scene/layer.rs
  lib/rust/ensogl/core/src/display/shape/compound/rectangle.rs
  lib/rust/ensogl/core/src/display/shape/primitive/system.rs
  lib/rust/ensogl/core/src/display/symbol/gpu.rs
  lib/rust/ensogl/core/src/display/symbol/gpu/geometry/compound/sprite.rs
  lib/rust/ensogl/core/src/gui/component.rs
  lib/rust/ensogl/core/src/system/gpu/data/attribute.rs
  lib/rust/ensogl/core/src/system/gpu/data/buffer.rs
  lib/rust/ensogl/examples/Cargo.toml
  lib/rust/ensogl/examples/instance-ordering/Cargo.toml
  lib/rust/ensogl/examples/instance-ordering/src/lib.rs
  lib/rust/ensogl/examples/src/lib.rs
  lib/rust/ensogl/pack/js/src/runner/config.json
Labels: CI: Keep up to date, CI: No changelog needed

#6156 Update `Text.split` to take a `Vector Text` parameter
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  std-bits/base/src/main/java/org/enso/base/Regex_Utils.java
  std-bits/base/src/main/java/org/enso/base/Text_Utils.java
  test/Tests/src/Data/Text_Spec.enso
Labels: CI: Ready to merge

#6199 Disable buffer compaction
  lib/rust/ensogl/core/src/system/gpu/data/attribute.rs
Labels: CI: Ready to merge, CI: No changelog needed

#6195 Remove old (Java) Regex library and replace with new (Truffle) library.
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Filter_Condition.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Matching.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Engine.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Engine/Default.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Match.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Match_2.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Pattern.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Pattern_2.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Regex_Mode.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Regex_Option.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Replacer.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex_2.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex_Matcher.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Text_Matcher.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Examples/0.0.0-dev/src/Main.enso
  std-bits/base/src/main/java/org/enso/base/Regex_Utils.java
  test/Meta_Test_Suite_Tests/src/Main.enso
  test/Tests/src/Data/Range_Spec.enso
  test/Tests/src/Data/Text/Default_Regex_Engine_Spec.enso
  test/Tests/src/Data/Text/Matching_Spec.enso
  test/Tests/src/Data/Text/Regex_2_Spec.enso
  test/Tests/src/Data/Text/Regex_Spec.enso
  test/Tests/src/Data/Text_Spec.enso
  test/Tests/src/Data/Vector_Spec.enso
  test/Tests/src/Main.enso
Labels: CI: Ready to merge, CI: No changelog needed

#6203 Fix calculating checksums
  app/ide-desktop/lib/client/tasks/computeHashes.cjs
  build/ci_utils/src/github/release.rs
  build/ci_utils/src/io/web.rs
Labels: CI: No changelog needed, --regression, -build-script

#6174 Text.to_display_text is (shortened) identity
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToDisplayTextNode.java
  lib/scala/common-polyglot-core-utils/src/main/java/org/enso/polyglot/common_utils/Core_Text_Utils.java
  std-bits/base/src/main/java/org/enso/base/Text_Utils.java
  test/Tests/src/Data/Text/Utils_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#6151 Suspended atom fields are evaluated only once
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Runtime/Lazy.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQL_Type_Reference.enso
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/ListBenchmarks.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/AtomConstructor.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/unboxing/Layout.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/unboxing/SuspendedFieldGetterNode.java
  engine/runtime/src/test/java/org/enso/interpreter/test/LazyAtomFieldTest.java
  test/Tests/src/Runtime/Lazy_Spec.enso
Labels: CI: Ready to merge, -compiler

#6172 Formatter fix to not fail when encountering an invalid symlink.
  Cargo.lock
  Cargo.toml
  build/base/src/fs/wrappers.rs
  build/build/src/project/backend.rs
  build/ci_utils/Cargo.toml
  build/ci_utils/src/fs/wrappers/tokio.rs
  build/enso-formatter/src/lib.rs
Labels: CI: No changelog needed, -build-script

#6189 Batch insert suggestions
  build.sbt
  distribution/engine/THIRD-PARTY/NOTICE
  distribution/engine/THIRD-PARTY/com.typesafe.slick.slick_2.13-3.4.1/LICENSE.txt
  distribution/engine/THIRD-PARTY/licenses/MIT-0
  distribution/engine/THIRD-PARTY/org.reactivestreams.reactive-streams-1.0.4/NOTICES
  distribution/engine/THIRD-PARTY/org.scala-lang.modules.scala-collection-compat_2.13-2.8.1/NOTICES
  distribution/engine/THIRD-PARTY/org.xerial.sqlite-jdbc-3.36.0.3/NOTICES
  distribution/engine/THIRD-PARTY/org.xerial.sqlite-jdbc-3.41.2.1/LICENSE
  distribution/engine/THIRD-PARTY/org.xerial.sqlite-jdbc-3.41.2.1/LICENSE.zentus
  distribution/engine/THIRD-PARTY/org.xerial.sqlite-jdbc-3.41.2.1/NOTICES
  distribution/lib/Standard/Database/0.0.0-dev/THIRD-PARTY/NOTICE
  distribution/lib/Standard/Database/0.0.0-dev/THIRD-PARTY/org.xerial.sqlite-jdbc-3.36.0.3/NOTICES
  distribution/lib/Standard/Database/0.0.0-dev/THIRD-PARTY/org.xerial.sqlite-jdbc-3.41.2.1/LICENSE
  distribution/lib/Standard/Database/0.0.0-dev/THIRD-PARTY/org.xerial.sqlite-jdbc-3.41.2.1/LICENSE.zentus
  distribution/lib/Standard/Database/0.0.0-dev/THIRD-PARTY/org.xerial.sqlite-jdbc-3.41.2.1/NOTICES
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/resources/application.conf
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/SuggestionsHandlerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/SuggestionsHandlerEventsTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/Suggestion.scala
  engine/runtime/src/main/scala/org/enso/compiler/SerializationManager.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/AnalyzeModuleInScopeJob.scala
  lib/scala/searcher/src/bench/java/org/enso/searcher/sql/SuggestionsRepoBenchmark.java
  lib/scala/searcher/src/bench/scala/org/enso/searcher/sql/SuggestionRandom.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/SuggestionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlSuggestionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/Tables.scala
  lib/scala/searcher/src/test/resources/logback-test.xml
  lib/scala/searcher/src/test/scala/org/enso/searcher/sql/SuggestionsRepoTest.scala
  lib/scala/searcher/src/test/scala/org/enso/searcher/sql/equality/SuggestionEntryEqualityIgnoringArguments.scala
  lib/scala/searcher/src/test/scala/org/enso/searcher/sql/equality/SuggestionEqualityIgnoringArguments.scala
  lib/scala/searcher/src/test/scala/org/enso/searcher/sql/equality/SuggestionOptionEqualityIgnoringArguments.scala
  lib/scala/searcher/src/test/scala/org/enso/searcher/sql/equality/SuggestionsEquality.scala
  test/Visualization_Tests/src/Widgets/Database_Widgets_Spec.enso
  tools/legal-review/Database/org.xerial.sqlite-jdbc-3.36.0.3/copyright-add
  tools/legal-review/Database/org.xerial.sqlite-jdbc-3.36.0.3/copyright-ignore
  tools/legal-review/Database/org.xerial.sqlite-jdbc-3.36.0.3/copyright-keep
  tools/legal-review/Database/org.xerial.sqlite-jdbc-3.36.0.3/copyright-keep-context
  tools/legal-review/Database/org.xerial.sqlite-jdbc-3.41.2.1/copyright-ignore
  tools/legal-review/Database/org.xerial.sqlite-jdbc-3.41.2.1/copyright-keep
  tools/legal-review/Database/org.xerial.sqlite-jdbc-3.41.2.1/custom-license
  tools/legal-review/Database/org.xerial.sqlite-jdbc-3.41.2.1/files-keep
  tools/legal-review/Database/report-state
  tools/legal-review/engine/com.typesafe.slick.slick_2.13-3.4.1/custom-license
  tools/legal-review/engine/com.typesafe.slick.slick_2.13-3.4.1/files-add/LICENSE.txt
  tools/legal-review/engine/org.reactivestreams.reactive-streams-1.0.4/copyright-keep-context
  tools/legal-review/engine/org.scala-lang.modules.scala-collection-compat_2.13-2.8.1/copyright-add
  tools/legal-review/engine/org.scala-lang.modules.scala-collection-compat_2.13-2.8.1/copyright-keep-context
  tools/legal-review/engine/org.xerial.sqlite-jdbc-3.36.0.3/copyright-add
  tools/legal-review/engine/org.xerial.sqlite-jdbc-3.36.0.3/copyright-keep-context
  tools/legal-review/engine/org.xerial.sqlite-jdbc-3.41.2.1/copyright-ignore
  tools/legal-review/engine/org.xerial.sqlite-jdbc-3.41.2.1/copyright-keep
  tools/legal-review/engine/org.xerial.sqlite-jdbc-3.41.2.1/custom-license
  tools/legal-review/engine/org.xerial.sqlite-jdbc-3.41.2.1/files-keep
  tools/legal-review/engine/report-state
  tools/legal-review/engine/reviewed-licenses/MIT-0
  tools/legal-review/license-texts/MIT-0
Labels: CI: Ready to merge, CI: No changelog needed

#6204 Implement `Table.union` for Database backend
  CHANGELOG.md
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/SQL_Type.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Common/Database_Join_Helper.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/IR/From_Spec.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/IR/SQL_Expression.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/JDBC_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Type_Mapping.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Redshift/Redshift_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQL_Type_Mapping.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQL_Type_Reference.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Type_Mapping.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Type/Value_Type.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Type/Value_Type_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  test/Table_Tests/src/Common_Table_Operations/Cast_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Union_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Main.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Database/Types/Postgres_Type_Mapping_Spec.enso
  test/Table_Tests/src/Helpers/Value_Type_Spec.enso
  test/Visualization_Tests/src/Table_Spec.enso
Labels: CI: Ready to merge

#6002 Add cloud endpoints for frontend
  app/ide-desktop/eslint.config.js
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/config.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/auth.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/service.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/config.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/service.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/service.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/http.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/newtype.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/utils.ts
Labels: CI: Ready to merge, CI: No changelog needed

#6213 Adjust `{Table|Column}.parse` to use `Value_Type`
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Data_Formatter.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Type/Value_Type_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Parse_Values_Helper.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Problems.enso
  std-bits/table/src/main/java/org/enso/table/parsing/TypeInferringParser.java
  test/Table_Tests/src/Formatting/Data_Formatter_Spec.enso
  test/Table_Tests/src/Formatting/Parse_Values_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#6215 Full-joins in SQLite
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Common/Database_Join_Helper.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Redshift/Redshift_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Join_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Main.enso
  test/Table_Tests/src/Database/SQLite_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#6187 Fix #6011. Don't use debug-assertion; fix sanity check that wasn't being run.
  lib/rust/bitmap/src/lib.rs
  lib/rust/ensogl/component/text/src/font/msdf/src/texture.rs
Labels: CI: Ready to merge, CI: Keep up to date, CI: No changelog needed

#6005 Add dashboard skeleton
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/index.tsx
Labels: CI: Ready to merge, CI: No changelog needed

#6235 Fix links in Markdown
  README.md
  docs/style-guide/rust.md
Labels: CI: No changelog needed

#6218 Consolidate Vector and Array methods
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Meta.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/GetConstructorNameNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Array.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/ArraySlice.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Vector.java
  engine/runtime/src/test/java/org/enso/compiler/EnsoCompilerTest.java
  engine/runtime/src/test/java/org/enso/compiler/VectorArraySignatureTest.java
  test/Tests/src/Data/Array_Spec.enso
  test/Tests/src/Data/Pair_Spec.enso
  test/Tests/src/Data/Vector_Spec.enso
  test/Tests/src/Semantic/Error_Spec.enso
Labels: CI: Ready to merge

#6239 Fix `./run gui watch` on Windows
  app/ide-desktop/lib/content/esbuild-config.ts
Labels: CI: Ready to merge, CI: No changelog needed

#6242 Remove SQL versions repo
  docs/runtime/searcher.md
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/ResourcesInitialization.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/resource/RepoInitialization.scala
  engine/language-server/src/main/scala/org/enso/languageserver/event/InitializedEvent.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/BufferRegistry.scala
  engine/language-server/src/test/scala/org/enso/languageserver/boot/resource/RepoInitializationSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/SuggestionsHandlerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/SuggestionsHandlerEventsTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeStdlibTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeSuggestionUpdatesTest.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/RenameProjectCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/CommandExecutionEngine.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/JobExecutionEngine.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/RuntimeContext.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/AnalyzeModuleInScopeJob.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/AnalyzeModuleJob.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/VersionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlVersionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/Tables.scala
  lib/scala/searcher/src/test/scala/org/enso/searcher/sql/VersionsRepoTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#6246 Provide Forbidden_Operation.to_display_text
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeExecutionEnvironmentTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/displaytext/ForbiddenOperationToDisplayTextNode.java
Labels: CI: Ready to merge, CI: No changelog needed

#6209 Fix: when default visualization is displayed, its entry is not present in the chooser list.
  app/gui/view/graph-editor/src/component/visualization/container.rs
  app/gui/view/graph-editor/src/component/visualization/container/action_bar.rs
  app/gui/view/graph-editor/src/component/visualization/container/visualization_chooser.rs
Labels: CI: Ready to merge, CI: No changelog needed

#6176 Add Warning methods onto Any to make working with them easier.
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Any.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Warning.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/dispatch/InvokeFunctionNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/UnresolvedSymbol.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/Warning.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/WithWarnings.java
  test/Tests/src/Semantic/Warnings_Spec.enso
Labels: CI: Ready to merge

#6220 Simplify authentication JS module
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/common.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/fontAwesomeIcon.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/forgotPassword.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/input.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/login.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/registration.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/resetPassword.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/setUsername.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/svgIcon.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/components/svg.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/hooks.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/utils.ts
Labels: CI: Ready to merge, CI: No changelog needed

#6265 Update codewoners with cloud dashboard & authentication
  .github/CODEOWNERS
Labels: CI: Ready to merge, CI: No changelog needed

#6015 Add dashboard table view
  app/ide-desktop/eslint.config.js
  app/ide-desktop/lib/content-config/src/config.json
  app/ide-desktop/lib/content/src/index.html
  app/ide-desktop/lib/content/src/index.ts
  app/ide-desktop/lib/dashboard/bundle.ts
  app/ide-desktop/lib/dashboard/src/authentication/package.json
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/cognito.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/components/app.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/components/svg.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/label.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/permissionDisplay.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectActionButton.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/rows.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/index.tsx
  app/ide-desktop/lib/dashboard/src/index.tsx
  app/ide-desktop/lib/dashboard/src/tailwind.css
  app/ide-desktop/lib/dashboard/tailwind.config.ts
  app/ide-desktop/lib/types/globals.d.ts
  app/ide-desktop/package.json
  app/ide-desktop/tsconfig.json
Labels: CI: Ready to merge, CI: No changelog needed

#6251 Save cognito access token to ~/.enso/credentials
  app/ide-desktop/lib/client/src/authentication.ts
  app/ide-desktop/lib/client/src/ipc.ts
  app/ide-desktop/lib/client/src/preload.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/cognito.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/config.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/auth.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/service.tsx
  app/ide-desktop/lib/types/globals.d.ts
Labels: CI: Ready to merge, CI: No changelog needed

#6219 Update top-bar styles and implement changePassword feature.
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/cognito.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/auth.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/components/app.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/components/svg.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/changePasswordModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/modal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/topBar.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/userMenu.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/providers/modal.tsx
  app/ide-desktop/lib/dashboard/tailwind.config.ts
Labels: CI: Ready to merge, CI: No changelog needed

#6268 Language Server preserves the suggestion updates order
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
Labels: CI: Ready to merge, CI: No changelog needed

#6255 Speed cascade of if statements up
  distribution/lib/Standard/Base/0.0.0-dev/src/Meta.enso
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/IfVsCaseBenchmarks.java
  engine/runtime/src/main/java/org/enso/interpreter/node/InlineableRootNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/ExecuteCallNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/BuiltinRootNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/bool/IfThenElseNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/debug/DebugEvalNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/ThrowErrorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/ThrowPanicNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/runtime/GetStackTraceNode.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/MethodProcessor.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/model/MethodDefinition.java
  test/Tests/src/Semantic/Warnings_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#6202 Test, fix, re-enable buffer compaction.
  Cargo.lock
  lib/rust/ensogl/core/Cargo.toml
  lib/rust/ensogl/core/src/lib.rs
  lib/rust/ensogl/core/src/system/gpu/data/attribute.rs
  lib/rust/ensogl/core/src/system/gpu/data/buffer.rs
  lib/rust/ensogl/examples/instance-ordering/src/lib.rs
Labels: CI: No changelog needed

#6233 Add split and tokenize to the Table.
  CHANGELOG.md
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Split_Tokenize.enso
  test/Table_Tests/src/In_Memory/Main.enso
  test/Table_Tests/src/In_Memory/Split_Tokenize_Spec.enso
  test/Table_Tests/src/Util.enso
Labels: CI: Ready to merge

#6275 Deprecate Error's `to_display_text` builtin methods
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/ReplTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeErrorsTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/ModuleNotInPackageError.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/displaytext/ArithmeticErrorToDisplayTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/displaytext/ArityErrorToDisplayTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/displaytext/CompileErrorToDisplayTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/displaytext/ForbiddenOperationToDisplayTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/displaytext/InexhaustivePatternMatchToDisplayTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/displaytext/InvalidArrayIndexToDisplayTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/displaytext/ModuleDoesNotExistToDisplayTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/displaytext/ModuleNotInPackageErrorToDisplayTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/displaytext/NoSuchConversionToDisplayTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/displaytext/NoSuchMethodToDisplayTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/displaytext/NotInvokableToDisplayTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/displaytext/SyntaxErrorToDisplayTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/displaytext/TypeErrorToDisplayTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/displaytext/UninitializedStateErrorToDisplayTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/displaytext/UnsupportedArgumentTypesToDisplayTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/TypeOfNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Error.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/Atom.java
  engine/runtime/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime/src/test/java/org/enso/compiler/ErrorCompilerTest.java
  engine/runtime/src/test/java/org/enso/compiler/ExecCompilerTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/TypeMembersTest.java
  engine/runtime/src/test/resources/TestNonImportedOverloads/src/Main.enso
  engine/runtime/src/test/resources/Test_Extension_Methods_Failure/src/Main.enso
  engine/runtime/src/test/resources/Test_Fully_Qualified_Name_Conflict/src/Main.enso
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/CaseTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/CompileDiagnosticsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/DataflowErrorsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/TextTest.scala
  test/Tests/src/Semantic/Conversion_Spec.enso
  test/Tests/src/Semantic/Meta_Spec.enso
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Any.enso
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Error.enso
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Meta.enso
Labels: CI: Ready to merge, CI: No changelog needed

#6226 Add TypeScript style guide
  docs/style-guide/README.md
  docs/style-guide/typescript.md
Labels: CI: Ready to merge, CI: No changelog needed

#5804 Start and open workspace
  app/ide-desktop/lib/content/src/index.html
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/ide.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectActionButton.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/topBar.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/service.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/index.tsx
  app/ide-desktop/lib/dashboard/src/authentication/tsconfig.json
  app/ide-desktop/lib/dashboard/tailwind.config.ts
Labels: CI: Ready to merge, CI: No changelog needed

#5998 sort handles incomparable values
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Any.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Index_Sub_Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Ordering.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Problem_Behavior.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Problems.enso
  engine/polyglot-api/src/main/java/org/enso/polyglot/HostEnsoUtils.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/TypeOfNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/mutable/SortNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/GreaterNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/GreaterOrEqualNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/LessNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/LessOrEqualNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/decimal/GreaterNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/decimal/GreaterOrEqualNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/decimal/LessNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/decimal/LessOrEqualNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/GreaterNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/GreaterOrEqualNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/LessNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/LessOrEqualNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/LessThanNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortArrayNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToTextNode.java
  engine/runtime/src/test/java/org/enso/interpreter/test/DebuggingEnsoTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/TestBase.java
  engine/runtime/src/test/java/org/enso/interpreter/test/ValuesGenerator.java
  engine/runtime/src/test/java/org/enso/interpreter/test/VectorSortTest.java
  test/Table_Tests/src/In_Memory/Table_Spec.enso
  test/Tests/src/Data/Array_Spec.enso
  test/Tests/src/Data/Numbers_Spec.enso
  test/Tests/src/Data/Ordering_Spec.enso
  test/Tests/src/Data/Vector_Spec.enso
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Any.enso
  tools/performance/engine-benchmarks/bench_download.py
Labels: CI: Ready to merge

#6280 Splitting Gigantic EqualsNode into few Smaller Ones
  distribution/lib/Standard/Base/0.0.0-dev/src/Any.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Ordering.enso
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/CurriedFunctionBenchmarks.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/EqualsBenchmarks.java
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/VectorBenchmarks.java
  engine/runtime/src/bench/scala/org/enso/interpreter/bench/fixtures/semantic/AtomFixtures.scala
  engine/runtime/src/bench/scala/org/enso/interpreter/bench/fixtures/semantic/CallableFixtures.scala
  engine/runtime/src/bench/scala/org/enso/interpreter/bench/fixtures/semantic/NamedDefaultedArgumentFixtures.scala
  engine/runtime/src/bench/scala/org/enso/interpreter/bench/fixtures/semantic/RecursionFixtures.scala
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsAtomNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsComplexNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/HashCodeNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/CustomComparatorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/HasCustomComparatorNode.java
  engine/runtime/src/test/java/org/enso/interpreter/test/EqualsTest.java
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Any.enso
Labels: CI: No changelog needed

#6295 fix paths to dashboard modules
  .github/CODEOWNERS
Labels: CI: No changelog needed

#6284 Type of UnresolvedSymbol is Function
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/IsValueOfTypeNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/TypeOfNode.java
  test/Tests/src/Semantic/Case_Spec.enso
  test/Tests/src/Semantic/Meta_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#6262 Allow opening dev-tools using keyboard shortcut in Electron
  app/ide-desktop/lib/client/src/index.ts
Labels: CI: Ready to merge, CI: No changelog needed

#6316 Tests: Use debug-info level 1 instead of 2.
  Cargo.toml
Labels: CI: No changelog needed

#6304 Avoid NullPointerException in --dumpGraphs & test & docs
  build.sbt
  engine/interpreter-dsl-test/src/test/java/org/enso/interpreter/dsl/test/InliningBuiltinsInNode.java
  engine/interpreter-dsl-test/src/test/java/org/enso/interpreter/dsl/test/InliningBuiltinsOutNode.java
  engine/interpreter-dsl-test/src/test/java/org/enso/interpreter/dsl/test/InliningBuiltinsTest.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/BuiltinRootNode.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/BuiltinMethod.java
Labels: CI: No changelog needed, --bug, --low-performance

#6130 A drop-down that allows changing the execution mode.
  CHANGELOG.md
  Cargo.lock
  app/gui/src/presenter/project.rs
  app/gui/view/Cargo.toml
  app/gui/view/examples/Cargo.toml
  app/gui/view/examples/execution-mode-dropdown/Cargo.toml
  app/gui/view/examples/execution-mode-dropdown/src/lib.rs
  app/gui/view/examples/interface/Cargo.toml
  app/gui/view/examples/interface/src/lib.rs
  app/gui/view/examples/src/lib.rs
  app/gui/view/execution-mode-selector/Cargo.toml
  app/gui/view/execution-mode-selector/src/lib.rs
  app/gui/view/graph-editor/Cargo.toml
  app/gui/view/graph-editor/src/component/breadcrumbs.rs
  app/gui/view/graph-editor/src/component/visualization/container/visualization_chooser.rs
  app/gui/view/graph-editor/src/lib.rs
  app/gui/view/src/lib.rs
  app/gui/view/src/root.rs
  lib/rust/ensogl/app/theme/hardcoded/src/lib.rs
  lib/rust/ensogl/component/drop-down-menu/src/lib.rs
  lib/rust/ensogl/component/list-view/src/lib.rs
  lib/rust/ensogl/core/src/data/color/space/def.rs
  lib/rust/ensogl/core/src/display/scene.rs
  lib/rust/ensogl/core/src/display/shape/compound/rectangle.rs
Labels: d-intermediate, p-high, CI: Ready to merge, CI: Keep up to date, CI: Clean build required, -gui

#6266 Use red color for context switch button
  app/gui/view/graph-editor/src/component/node/action_bar.rs
  lib/rust/ensogl/app/theme/hardcoded/src/lib.rs
Labels: CI: No changelog needed

#6336 Async Language Server resources initialization
  engine/language-server/src/main/scala/org/enso/languageserver/boot/ResourcesInitialization.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/resource/AsyncResourcesInitialization.scala
Labels: CI: Ready to merge, CI: No changelog needed

#6245 Vector Editor first visual implementation
  Cargo.lock
  Cargo.toml
  app/gui/view/graph-editor/Cargo.toml
  app/gui/view/graph-editor/src/component/node.rs
  app/gui/view/graph-editor/src/component/node/input/widget/vector_editor.rs
  app/gui/view/graph-editor/src/lib.rs
  integration-test/Cargo.toml
  lib/rust/callback/src/lib.rs
  lib/rust/ensogl/component/Cargo.toml
  lib/rust/ensogl/component/list-editor/Cargo.toml
  lib/rust/ensogl/component/list-editor/src/item.rs
  lib/rust/ensogl/component/list-editor/src/lib.rs
  lib/rust/ensogl/component/list-editor/src/placeholder.rs
  lib/rust/ensogl/component/src/lib.rs
  lib/rust/ensogl/core/src/animation/easing.rs
  lib/rust/ensogl/core/src/animation/frp/animation.rs
  lib/rust/ensogl/core/src/animation/loops.rs
  lib/rust/ensogl/core/src/animation/physics/inertia.rs
  lib/rust/ensogl/core/src/application/frp.rs
  lib/rust/ensogl/core/src/control/io/mouse/event.rs
  lib/rust/ensogl/core/src/display/camera/camera2d.rs
  lib/rust/ensogl/core/src/display/object.rs
  lib/rust/ensogl/core/src/display/object/event.rs
  lib/rust/ensogl/core/src/display/object/instance.rs
  lib/rust/ensogl/core/src/display/shape/primitive/def/var.rs
  lib/rust/ensogl/core/src/display/shape/primitive/glsl/color.glsl
  lib/rust/ensogl/core/src/display/symbol/dom.rs
  lib/rust/ensogl/core/src/display/symbol/gpu/geometry/compound/sprite.rs
  lib/rust/ensogl/core/src/gui/cursor.rs
  lib/rust/ensogl/core/src/system/gpu/data/attribute.rs
  lib/rust/ensogl/examples/easing-animator/src/lib.rs
  lib/rust/ensogl/examples/profiling-run-graph/src/lib.rs
  lib/rust/executor/src/web.rs
  lib/rust/frp/src/microtasks.rs
  lib/rust/frp/src/nodes.rs
  lib/rust/prelude/src/data/vec_indexed_by.rs
  lib/rust/prelude/src/lib.rs
  lib/rust/shapely/src/lib.rs
  lib/rust/web/src/binding/mock.rs
Labels: CI: No changelog needed

#6348 Avoid double WithWarnings wrapping
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/IndirectInvokeCallableNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeCallableNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/CaseNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/foreign/CoerceNothing.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Array.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/ArraySlice.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Vector.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/Warning.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/WithWarnings.java
  engine/runtime/src/test/java/org/enso/interpreter/test/WarningsTest.java
Labels: CI: No changelog needed

#6313 Fix uncaught sign up error; minor code style changes
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/cognito.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/resetPassword.tsx
Labels: CI: No changelog needed

#6343 Simplify test for #6248
  engine/runtime/src/test/java/org/enso/interpreter/test/TypeMembersTest.java
Labels: CI: No changelog needed

#6345 Don't propagate warnings on suspended arguments
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/model/MethodDefinition.java
  test/Tests/src/Semantic/Warnings_Spec.enso
Labels: CI: No changelog needed

#6302 Make play button clickable and hide it when irrelevant, take #2
  app/gui/src/presenter/project.rs
  app/gui/view/examples/execution-mode-dropdown/src/lib.rs
  app/gui/view/examples/interface/src/lib.rs
  app/gui/view/execution-mode-selector/src/lib.rs
  app/gui/view/execution-mode-selector/src/play_button.rs
  lib/rust/ensogl/app/theme/hardcoded/src/lib.rs
Labels: CI: No changelog needed

#6357 Change order of arguments when controlling context
  distribution/lib/Standard/Base/0.0.0-dev/src/Runtime.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/runtime/RuntimeWithDisabledContextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/runtime/RuntimeWithEnabledContextNode.java
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/DesignExecutionEnvironmentTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/LiveExecutionEnvironmentTest.scala
  test/Tests/src/Semantic/Runtime_Spec.enso
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Runtime.enso
Labels: CI: Ready to merge, CI: No changelog needed

#6354 Keep scheduled execution job on text edit
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/EditFileCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/JobControlPlane.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/JobExecutionEngine.scala
Labels: CI: Ready to merge, CI: No changelog needed

#6247 Layer/Rectangle improvements
  .git-blame-ignore-revs
  .github/CODEOWNERS
  app/gui/view/execution-mode-selector/src/lib.rs
  app/gui/view/graph-editor/src/component/breadcrumbs.rs
  app/gui/view/src/status_bar.rs
  app/gui/view/src/window_control_buttons.rs
  lib/rust/ensogl/app/theme/hardcoded/src/lib.rs
  lib/rust/ensogl/component/drop-down-menu/src/lib.rs
  lib/rust/ensogl/component/drop-down/src/model.rs
  lib/rust/ensogl/core/src/display/scene.rs
  lib/rust/ensogl/core/src/display/scene/layer.rs
  lib/rust/ensogl/core/src/display/shape/compound/rectangle.rs
  lib/rust/ensogl/core/src/display/shape/primitive/shader/builder.rs
  lib/rust/ensogl/core/src/display/shape/primitive/system.rs
  lib/rust/ensogl/examples/mouse-events/src/lib.rs
Labels: CI: No changelog needed

#6355 Increase the stack size
  project/NativeImage.scala
Labels: CI: Ready to merge, CI: No changelog needed

#6359 Reduce borrow scope
  lib/rust/ensogl/core/src/display/scene/layer.rs
Labels: CI: Ready to merge, CI: No changelog needed

#6334 UnresolvedSymbol is now accepted by Vector.sort
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java
  test/Benchmarks/src/Vector/Sort.enso
  test/Tests/src/Data/Vector_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#6335 Removing need for asynchronous thread to execute ResourceManager finalizers
  CHANGELOG.md
  engine/interpreter-dsl-test/src/test/java/org/enso/interpreter/dsl/test/InliningBuiltinsOutNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/ResourceManager.java
  engine/runtime/src/test/scala/org/enso/interpreter/test/InterpreterTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/RuntimeManagementTest.scala
Labels: CI: Ready to merge

#6358 Fix render issues, re-enable buffer compaction
  lib/rust/ensogl/core/src/display/symbol/gpu.rs
  lib/rust/ensogl/core/src/system/gpu/data/attribute.rs
Labels: CI: No changelog needed

#6364 Prevent default for all events, fixing multiple IDE bugs
  lib/rust/ensogl/core/src/control/io/mouse/event.rs
  lib/rust/ensogl/core/src/display/navigation/navigator/events.rs
  lib/rust/frp/src/io/keyboard.rs
Labels: CI: No changelog needed

#6253 Add `replace`, `trim` to Column. Better number parsing.
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/SQL.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Table/0.0.0-dev/package.yaml
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Data_Formatter.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table_Conversions.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Java_Problems.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Parse_Values_Helper.enso
  std-bits/table/src/main/java/org/enso/table/parsing/DecimalParser.java
  std-bits/table/src/main/java/org/enso/table/parsing/IntegerParser.java
  std-bits/table/src/main/java/org/enso/table/parsing/NumberParser.java
  std-bits/table/src/main/java/org/enso/table/parsing/problems/LeadingZeros.java
  std-bits/table/src/main/java/org/enso/table/parsing/problems/NoOpProblemAggregator.java
  std-bits/table/src/main/java/org/enso/table/parsing/problems/ProblemAggregator.java
  std-bits/table/src/main/java/org/enso/table/parsing/problems/ProblemAggregatorImpl.java
  std-bits/table/src/main/java/org/enso/table/parsing/problems/SimplifiedProblemAggregator.java
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Formatting/Data_Formatter_Spec.enso
  test/Table_Tests/src/Formatting/Parse_Values_Spec.enso
  test/Table_Tests/src/IO/Formats_Spec.enso
  test/Table_Tests/src/IO/Json_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
Labels: CI: Ready to merge

#6369 Project folder not renamed after project name change
  lib/scala/json-rpc-server-test/src/main/scala/org/enso/jsonrpc/test/JsonRpcServerTestKit.scala
  lib/scala/json-rpc-server/src/main/scala/org/enso/jsonrpc/JsonRpcServer.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/ProjectManager.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/ShutdownHookActivator.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/ShutdownHookRunner.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala
Labels: CI: Ready to merge, CI: No changelog needed

#6331 Rollback cloud options groups
  app/ide-desktop/lib/content-config/src/config.json
  app/ide-desktop/lib/content/src/index.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/index.tsx
Labels: CI: No changelog needed

#6298 Adding typechecks to Column Operations
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Runtime/Debug.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Type_Mapping.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Redshift/Redshift_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Type_Mapping.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Statement_Setter.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Type/Storage.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Type/Value_Type.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Type/Value_Type_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Filter_Condition_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Join_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Naming_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Split_Tokenize.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Extensions.enso
  std-bits/base/src/main/java/org/enso/base/polyglot/NumericConverter.java
  std-bits/database/src/main/java/org/enso/database/JDBCUtils.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/object/BoolBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/DoubleBooleanOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/text/StringStringOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/DoubleStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/LongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/Storage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/StringStorage.java
  test/Table_Tests/src/Common_Table_Operations/Cast_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Date_Time_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Expression_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Filter_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Integration_Tests.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Join_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Union_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Missing_Values_Spec.enso
  test/Table_Tests/src/Database/Codegen_Spec.enso
  test/Table_Tests/src/Database/Common_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Database/Types/Postgres_Type_Mapping_Spec.enso
  test/Table_Tests/src/Database/Types/SQLite_Type_Mapping_Spec.enso
  test/Table_Tests/src/Formatting/Parse_Values_Spec.enso
  test/Table_Tests/src/Helpers/Value_Type_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#6294 Add Table.parse_text_to_table to convert Text to a Table.
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Pattern.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table_Conversions.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Parse_To_Table.enso
  test/Table_Tests/src/In_Memory/Main.enso
  test/Table_Tests/src/In_Memory/Parse_To_Table_Spec.enso
  test/Tests/src/Data/Text/Regex_Spec.enso
Labels: CI: Ready to merge, CI: Clean build required

#6363 Vector Editor with List Editor and adding elements.
  app/gui/view/graph-editor/src/component/node/input/widget/vector_editor.rs
  lib/rust/ensogl/component/list-editor/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#6381 Infer SQLite types locally
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Type_Mapping.enso
  test/Table_Tests/src/Common_Table_Operations/Cast_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Database/Types/SQLite_Type_Mapping_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#6267 Fix all eslint errors
  app/ide-desktop/eslint.config.js
  app/ide-desktop/lib/client/electron-builder-config.ts
  app/ide-desktop/lib/client/src/authentication.ts
  app/ide-desktop/lib/client/src/bin/project-manager.ts
  app/ide-desktop/lib/client/src/file-associations.ts
  app/ide-desktop/lib/client/src/index.ts
  app/ide-desktop/lib/client/src/project-management.ts
  app/ide-desktop/lib/client/tasks/signArchivesMacOs.ts
  app/ide-desktop/lib/dashboard/bundle.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/auth.tsx
  app/ide-desktop/lib/dashboard/src/index.tsx
  app/ide-desktop/lib/icons/src/index.js
Labels: CI: Ready to merge, CI: No changelog needed

#6392 Better cleanup of project management test suite
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala
Labels: CI: Ready to merge, CI: No changelog needed

#6370 Exclude comparison operators from modifier logic
  app/gui/language/ast/impl/src/opr.rs
  app/gui/language/parser/src/translation.rs
  app/gui/language/span-tree/src/main.rs
  lib/rust/parser/src/lexer.rs
  lib/rust/parser/src/syntax/token.rs
Labels: CI: No changelog needed

#6243 URL handling
  app/ide-desktop/eslint.config.js
  app/ide-desktop/lib/client/src/authentication.ts
  app/ide-desktop/lib/client/src/file-associations.ts
  app/ide-desktop/lib/client/src/index.ts
  app/ide-desktop/lib/client/src/url-associations.ts
  app/ide-desktop/lib/common/src/index.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/service.tsx
Labels: CI: No changelog needed

#6383 5127 Add Table.parse_to_columns to parse a single column to a set of columns.
  CHANGELOG.md
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Split_Tokenize.enso
  test/Table_Tests/src/In_Memory/Split_Tokenize_Spec.enso
Labels: CI: Ready to merge

#6071 Feat: update templates styles and feature
  app/ide-desktop/lib/dashboard/src/authentication/src/components/svg.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/templates.tsx
  app/ide-desktop/lib/dashboard/src/tailwind.css
Labels: CI: Ready to merge, CI: No changelog needed

#6384 Improve inlining of `<|` on (GraalVM EE)
  distribution/lib/Standard/Base/0.0.0-dev/src/Any.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Function.enso
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/IfVsCaseBenchmarks.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/BuiltinRootNode.java
Labels: CI: No changelog needed, --low-performance

#6223 Ensure that IO.println does not fail if `to_text` returned a non-Text value.
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/io/PrintlnNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/WithWarnings.java
  engine/runtime/src/test/java/org/enso/interpreter/test/PrintTest.java
Labels: CI: Ready to merge, CI: Keep up to date, CI: No changelog needed

#6365 Drop method exported from WASM + removing leaks.
  app/gui/src/lib.rs
  app/gui/src/presenter.rs
  app/gui/view/graph-editor/src/component/breadcrumbs.rs
  app/gui/view/graph-editor/src/component/node/growth_animation.rs
  app/gui/view/graph-editor/src/lib.rs
  app/gui/view/graph-editor/src/new_node_position.rs
  lib/rust/ensogl/core/src/display/scene.rs
  lib/rust/executor/src/web.rs
  lib/rust/prelude/src/debug.rs
Labels: CI: Ready to merge, CI: No changelog needed

#6390 Implementation of elements adding to List Editor and a lot of internal API
  lib/rust/ensogl/component/list-editor/src/lib.rs
  lib/rust/ensogl/component/slider/src/lib.rs
  lib/rust/ensogl/component/slider/src/model.rs
  lib/rust/ensogl/core/src/gui/cursor.rs
  lib/rust/ensogl/examples/slider/src/lib.rs
  lib/rust/frp/src/nodes.rs
  lib/rust/prelude/src/option.rs
  lib/rust/types/src/dim.rs
Labels: CI: No changelog needed

#6341 Ability to change the execution environment between design and live.
  CHANGELOG.md
  Cargo.lock
  app/gui/controller/engine-protocol/src/language_server.rs
  app/gui/controller/engine-protocol/src/language_server/types.rs
  app/gui/docs/product/shortcuts.md
  app/gui/src/controller/graph/executed.rs
  app/gui/src/model/execution_context.rs
  app/gui/src/model/execution_context/plain.rs
  app/gui/src/model/execution_context/synchronized.rs
  app/gui/src/presenter/graph.rs
  app/gui/src/presenter/project.rs
  app/gui/view/Cargo.toml
  app/gui/view/examples/Cargo.toml
  app/gui/view/examples/execution-environment-dropdown/Cargo.toml
  app/gui/view/examples/execution-environment-dropdown/src/lib.rs
  app/gui/view/examples/interface/Cargo.toml
  app/gui/view/examples/interface/src/lib.rs
  app/gui/view/examples/src/lib.rs
  app/gui/view/execution-environment-selector/Cargo.toml
  app/gui/view/execution-environment-selector/src/lib.rs
  app/gui/view/execution-environment-selector/src/play_button.rs
  app/gui/view/graph-editor/Cargo.toml
  app/gui/view/graph-editor/src/component/node.rs
  app/gui/view/graph-editor/src/component/node/action_bar.rs
  app/gui/view/graph-editor/src/execution_environment.rs
  app/gui/view/graph-editor/src/lib.rs
  app/gui/view/graph-editor/src/shortcuts.rs
  app/gui/view/src/lib.rs
  lib/rust/ensogl/app/theme/hardcoded/src/lib.rs
  lib/rust/ensogl/component/drop-down-menu/src/lib.rs
Labels: CI: Ready to merge

#6279 Dashboard directory interactivity
  app/ide-desktop/eslint.config.js
  app/ide-desktop/lib/client/src/authentication.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/forgotPassword.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/login.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/session.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/components/svg.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/confirmDeleteModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/contextMenu.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/contextMenuEntry.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/createForm.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/directoryCreateForm.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/fileCreateForm.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/ide.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/label.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/permissionDisplay.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectCreateForm.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/renameModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/rows.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/secretCreateForm.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/templates.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/topBar.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/uploadFileModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/service.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/error.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/fileInfo.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/hooks.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/uploadMultipleFiles.ts
  app/ide-desktop/lib/dashboard/src/tailwind.css
  app/ide-desktop/lib/dashboard/tailwind.config.ts
  app/ide-desktop/package-lock.json
  app/ide-desktop/package.json
Labels: CI: No changelog needed

#6396 Rollback event handling changes for the mouse
  lib/rust/ensogl/core/src/control/io/mouse/event.rs
  lib/rust/ensogl/core/src/display/navigation/navigator/events.rs
Labels: CI: Ready to merge, CI: No changelog needed

#6405 Replace Table should_equal with should_equal_verbose
  test/Table_Tests/src/In_Memory/Parse_To_Table_Spec.enso
  test/Table_Tests/src/In_Memory/Split_Tokenize_Spec.enso
  test/Table_Tests/src/Util.enso
Labels: CI: Ready to merge, CI: No changelog needed

#6308 Cloud/desktop mode switcher
  app/ide-desktop/eslint.config.js
  app/ide-desktop/lib/content/esbuild-config.ts
  app/ide-desktop/lib/content/src/index.html
  app/ide-desktop/lib/content/src/index.ts
  app/ide-desktop/lib/content/src/newtype.ts
  app/ide-desktop/lib/content/src/project_manager.ts
  app/ide-desktop/lib/content/src/run.js
  app/ide-desktop/lib/content/src/style.css
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/auth.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/components/app.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/components/svg.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/cloudService.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/directoryCreateForm.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/fileCreateForm.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/ide.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectActionButton.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectCreateForm.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/secretCreateForm.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/templates.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/topBar.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/uploadFileModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/userMenu.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/localService.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/projectManager.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/index.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/providers/backend.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/uploadMultipleFiles.ts
  app/ide-desktop/lib/dashboard/src/serviceWorker.ts
  app/ide-desktop/lib/types/globals.d.ts
Labels: CI: No changelog needed

#6404 Add parse extensions to Text type. #6330
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Of_Day.enso
  test/Tests/src/Data/Text/Parse_Spec.enso
  test/Tests/src/Main.enso
Labels: CI: Ready to merge, CI: Clean build required

#6436 Skip redundant compilations
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/EditFileCmd.scala
Labels: CI: Ready to merge, CI: No changelog needed

#6382 Table Visualization and display text changes.
  .github/CODEOWNERS
  app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Filter_Condition.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Index_Sub_Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Interval.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Locale.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Maybe.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Noise.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Pair.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Regression.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Case_Sensitivity.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Encoding.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Span.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Text_Ordering.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Text_Sub_Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Duration.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Period.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Of_Day.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Zone.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Meta/Enso_Project.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/HTTP_Status_Code.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Header.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/URI.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Random.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/File_Permissions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/Process/Exit_Code.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/Process/Process_Builder.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Warning.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Type/Value_Type.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime-with-polyglot/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToDisplayTextNode.java
  engine/runtime/src/test/java/org/enso/interpreter/test/TypeMembersTest.java
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/ImportsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/MethodsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/TextTest.scala
  test/Table_Tests/src/Formatting/Parse_Values_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
  test/Tests/src/Data/Map_Spec.enso
  test/Tests/src/Data/Noise/Generator_Spec.enso
  test/Tests/src/Data/Text/Utils_Spec.enso
  test/Tests/src/Data/Time/Date_Time_Spec.enso
  test/Tests/src/Data/Time/Duration_Spec.enso
  test/Tests/src/Data/Time/Period_Spec.enso
  test/Visualization_Tests/src/Table_Spec.enso
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Meta.enso
Labels: CI: Ready to merge, CI: No changelog needed

#6433 Passing events to sub-widgets in List Editor and refactoring of the slider component.
  Cargo.lock
  lib/rust/ensogl/component/list-editor/src/lib.rs
  lib/rust/ensogl/component/slider/src/lib.rs
  lib/rust/ensogl/component/slider/src/model.rs
  lib/rust/ensogl/core/src/display/object/event.rs
  lib/rust/ensogl/core/src/display/object/instance.rs
  lib/rust/ensogl/core/src/display/scene.rs
  lib/rust/ensogl/examples/Cargo.toml
  lib/rust/ensogl/examples/list-editor/Cargo.toml
  lib/rust/ensogl/examples/list-editor/src/lib.rs
  lib/rust/ensogl/examples/slider/src/lib.rs
  lib/rust/ensogl/examples/src/lib.rs
  lib/rust/ensogl/examples/vector-editor/src/lib.rs
  lib/rust/frp/src/nodes.rs
Labels: CI: No changelog needed

#6449 Switch execution environment before the complete notification
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ExecuteJob.scala
Labels: CI: Ready to merge, CI: No changelog needed

#6450 Fix for the massive number of warnings when renaming with invalid names.
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  std-bits/table/src/main/java/org/enso/table/excel/ExcelHeaders.java
  std-bits/table/src/main/java/org/enso/table/read/DelimitedReader.java
  std-bits/table/src/main/java/org/enso/table/util/NameDeduplicator.java
  std-bits/table/src/main/java/org/enso/table/write/ExcelWriter.java
  test/Table_Tests/src/In_Memory/Table_Spec.enso
Labels: CI: No changelog needed

#6427 Implement workflow-level Play button business-logic
  app/gui/src/controller/graph/executed.rs
  app/gui/src/model/execution_context.rs
  app/gui/src/model/execution_context/plain.rs
  app/gui/src/model/execution_context/synchronized.rs
  app/gui/src/model/project.rs
  app/gui/src/model/project/synchronized.rs
  app/gui/src/presenter/project.rs
  app/gui/view/execution-environment-selector/src/lib.rs
  app/gui/view/graph-editor/src/execution_environment.rs
  app/gui/view/graph-editor/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#6434 Execution environment integration fixes.
  Cargo.lock
  app/gui/controller/engine-protocol/src/language_server/types.rs
  app/gui/docs/product/shortcuts.md
  app/gui/src/controller/graph/executed.rs
  app/gui/src/model/execution_context.rs
  app/gui/src/model/execution_context/plain.rs
  app/gui/src/model/execution_context/synchronized.rs
  app/gui/src/presenter/graph.rs
  app/gui/src/presenter/project.rs
  app/gui/view/execution-environment-selector/Cargo.toml
  app/gui/view/execution-environment-selector/src/lib.rs
  app/gui/view/graph-editor/src/execution_environment.rs
  app/gui/view/graph-editor/src/lib.rs
  app/gui/view/graph-editor/src/shortcuts.rs
  lib/rust/ensogl/component/drop-down-menu/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#6432 Unselect all nodes when the project name is edited
  app/gui/view/graph-editor/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#6429 Create database table from memory
  CHANGELOG.md
  build.sbt
  distribution/lib/Standard/Base/0.0.0-dev/src/Panic.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Random.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Extensions/Upload_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/IR/Query.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/JDBC_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Redshift/Redshift_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Type_Mapping.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Main.enso
  test/Table_Tests/src/Common_Table_Operations/Cross_Tab_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Date_Time_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Expression_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Cross_Join_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Join_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Zip_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Transpose_Spec.enso
  test/Table_Tests/src/Database/Common_Spec.enso
  test/Table_Tests/src/Database/Helpers/Name_Generator.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Database/Redshift_Spec.enso
  test/Table_Tests/src/Database/SQLite_Spec.enso
  test/Table_Tests/src/Database/Types/Postgres_Type_Mapping_Spec.enso
  test/Table_Tests/src/Database/Types/SQLite_Type_Mapping_Spec.enso
  test/Table_Tests/src/Database/Upload_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
  test/Tests/polyglot-sources/enso-test-java-helpers/src/main/java/org/enso/table_test_helpers/ExplodingStorage.java
  test/Tests/polyglot-sources/enso-test-java-helpers/src/main/java/org/enso/table_test_helpers/ExplodingStoragePayload.java
  test/Tests/src/Semantic/Error_Spec.enso
  test/Visualization_Tests/src/Table_Spec.enso
Labels: CI: Ready to merge

#6407 Fixes for URL and file handling
  app/ide-desktop/lib/client/src/bin/project-manager.ts
  app/ide-desktop/lib/client/src/file-associations.ts
  app/ide-desktop/lib/client/src/index.ts
  app/ide-desktop/lib/client/src/project-management.ts
  app/ide-desktop/lib/client/src/url-associations.ts
  app/ide-desktop/tsconfig.json
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#6372 Report only unique warnings
  CHANGELOG.md
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/semantic/WarningBenchmarks.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/IndirectInvokeConversionNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/IndirectInvokeMethodNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeCallableNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeConversionNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Array.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/ArrayRope.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/Warning.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/WarningsLibrary.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/WithWarnings.java
  engine/runtime/src/test/java/org/enso/interpreter/test/ArrayTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/BigNumberTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/ForeignMethodInvokeTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/LazyAtomFieldTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/ListTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/MetaObjectTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/PolyglotErrorTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/PrintTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/TestBase.java
  engine/runtime/src/test/java/org/enso/interpreter/test/TypeMembersTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/VectorTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/WarningsTest.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/MethodProcessor.java
  test/Table_Tests/src/Database/SQLite_Spec.enso
  test/Tests/src/Semantic/Warnings_Spec.enso
Labels: CI: Ready to merge

#6441 Invoke instance methods for Any overrides
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/List.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Extensions.enso
  engine/runtime-with-polyglot/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/resolver/MethodResolverNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Type.java
  engine/runtime/src/test/java/org/enso/interpreter/test/PrintTest.java
  test/Tests/src/Semantic/Any_Spec.enso
  test/Tests/src/Semantic/Definitions/Any_Types.enso
  test/Tests/src/Semantic/Definitions/Names.enso
  test/Tests/src/Semantic/Meta_Spec.enso
  test/Tests/src/Semantic/Names_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#6462 Welcome Pavel to engine team
  .github/CODEOWNERS
Labels: CI: No changelog needed

#6466 Unbreak CI after outdated merge
  test/Table_Tests/src/Database/SQLite_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#6463 Don't attempt to resolve hostname for git init
  engine/language-server/src/main/scala/org/enso/languageserver/vcsmanager/EmptyUserConfigReader.scala
  engine/language-server/src/main/scala/org/enso/languageserver/vcsmanager/Git.scala
  engine/language-server/src/test/scala/org/enso/languageserver/vcsmanager/GitSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/VcsManagerTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#6430 Hide profile button behind a feature flag
  app/gui/view/graph-editor/src/lib.rs
  app/ide-desktop/lib/content-config/src/config.json
Labels: CI: Ready to merge, CI: No changelog needed

#6443 Change defaults for `Connection.tables` and ensure that `Connection.query` recognizes all available tables
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Extensions/Upload_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Redshift/Redshift_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  test/Table_Tests/src/Database/Common_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Database/SQLite_Spec.enso
  test/Table_Tests/src/Database/Upload_Spec.enso
  test/Visualization_Tests/src/Widgets/Database_Widgets_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#6459 Add Execution Context control to Text.write
  CHANGELOG.md
  app/gui/controller/engine-protocol/src/language_server.rs
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Encoding.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Runtime.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/Write_Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File_Format.enso
  distribution/lib/Standard/Examples/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table_Conversions.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Test_Reporter.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/runtime/ContextIsEnabledNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoFile.java
  std-bits/base/src/main/java/org/enso/base/DryRunFileManager.java
  std-bits/base/src/main/java/org/enso/base/file_format/JSONFormatSPI.java
  test/Table_Tests/src/Database/SQLite_Spec.enso
  test/Table_Tests/src/IO/Csv_Spec.enso
  test/Table_Tests/src/IO/Delimited_Read_Spec.enso
  test/Table_Tests/src/IO/Delimited_Write_Spec.enso
  test/Table_Tests/src/IO/Excel_Spec.enso
  test/Table_Tests/src/IO/Formats_Spec.enso
  test/Tests/src/System/File_Read_Spec.enso
  test/Tests/src/System/File_Spec.enso
  test/Tests/src/System/Reporting_Stream_Decoder_Spec.enso
  test/Tests/src/System/Reporting_Stream_Encoder_Spec.enso
  test/Visualization_Tests/src/Table_Spec.enso
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Runtime.enso
Labels: CI: Ready to merge
