Repository enso-org/enso, pull requests merged in 2023-02, with the labels that each got.

#4107 Prevent errors in log when closing a context
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/ResourceManager.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/ThreadExecutors.java
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/CommandExecutionEngine.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/JobExecutionEngine.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/TruffleThreadFactory.scala
Labels: CI: Ready to merge, CI: No changelog needed

#4089 Cached_shape macro rendered to special texture.
  Cargo.lock
  lib/rust/ensogl/core/src/data/bounding_box.rs
  lib/rust/ensogl/core/src/display/object/instance.rs
  lib/rust/ensogl/core/src/display/render/pass.rs
  lib/rust/ensogl/core/src/display/render/passes.rs
  lib/rust/ensogl/core/src/display/render/passes/cache_shapes.rs
  lib/rust/ensogl/core/src/display/scene.rs
  lib/rust/ensogl/core/src/display/shape/primitive/system.rs
  lib/rust/ensogl/core/src/display/symbol/gpu/registry.rs
  lib/rust/ensogl/core/src/display/world.rs
  lib/rust/ensogl/core/src/gui/component.rs
  lib/rust/ensogl/core/src/lib.rs
  lib/rust/ensogl/example/Cargo.toml
  lib/rust/ensogl/example/cached-shape/Cargo.toml
  lib/rust/ensogl/example/cached-shape/src/lib.rs
  lib/rust/ensogl/example/src/lib.rs
  lib/rust/shapely/macros/src/before_main.rs
Labels: CI: Ready to merge, CI: No changelog needed

#4112 Fix bug with Delimited_Format web reader.
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Delimited/Delimited_Format.enso
Labels: CI: Ready to merge, CI: No changelog needed

#4108 Fix documentation locking while moving around with arrow keys
  app/gui/src/presenter/searcher.rs
  app/gui/view/documentation/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#4101 Mark nodes with yellow stripes if their evaluation produced warnings
  app/gui/controller/engine-protocol/src/language_server/tests.rs
  app/gui/controller/engine-protocol/src/language_server/types.rs
  app/gui/src/model/execution_context.rs
  app/gui/src/presenter/graph/state.rs
  app/gui/view/debug_scene/interface/src/lib.rs
  app/gui/view/graph-editor/src/builtin/visualization/native/error.rs
  app/gui/view/graph-editor/src/component/node.rs
  app/gui/view/graph-editor/src/component/node/error.rs
  lib/rust/ensogl/app/theme/hardcoded/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#4096 Fix for the cargo-installed build script usage.
  build/build/src/repo.rs
  build/ci_utils/src/programs/cargo.rs
  lib/rust/ensogl/pack/src/lib.rs
Labels: CI: No changelog needed

#4114 Cloud fixes
  build/build/paths.yaml
  build/build/src/aws/ecr/runtime.rs
  build/build/src/aws/s3.rs
  build/build/src/release.rs
  tools/ci/docker/Dockerfile
Labels: CI: No changelog needed

#4116 JGit should run its bookkeeping in the background
  engine/language-server/src/main/scala/org/enso/languageserver/vcsmanager/Git.scala
  engine/language-server/src/test/scala/org/enso/languageserver/vcsmanager/GitSpec.scala
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#4109 Hide skip and freeze buttons behind feature flag
  app/gui/config/src/lib.rs
  app/gui/view/graph-editor/src/component/node/action_bar.rs
  app/ide-desktop/lib/client/src/index.js
  app/ide-desktop/lib/content/src/index.ts
Labels: CI: Ready to merge, CI: No changelog needed

#4072 Dynamic dropdown support
  CHANGELOG.md
  app/gui/controller/double-representation/src/node.rs
  app/gui/controller/engine-protocol/src/language_server/types.rs
  app/gui/language/ast/impl/src/id_map.rs
  app/gui/language/ast/impl/src/known.rs
  app/gui/language/ast/impl/src/opr.rs
  app/gui/language/span-tree/example/src/lib.rs
  app/gui/language/span-tree/src/action.rs
  app/gui/language/span-tree/src/generate.rs
  app/gui/language/span-tree/src/generate/context.rs
  app/gui/language/span-tree/src/iter.rs
  app/gui/language/span-tree/src/lib.rs
  app/gui/language/span-tree/src/node.rs
  app/gui/language/span-tree/src/node/kind.rs
  app/gui/src/controller.rs
  app/gui/src/controller/graph.rs
  app/gui/src/controller/graph/executed.rs
  app/gui/src/controller/graph/widget.rs
  app/gui/src/controller/visualization.rs
  app/gui/src/controller/visualization/manager.rs
  app/gui/src/model/execution_context.rs
  app/gui/src/model/execution_context/synchronized.rs
  app/gui/src/presenter/graph.rs
  app/gui/src/presenter/graph/state.rs
  app/gui/src/presenter/graph/visualization.rs
  app/gui/src/presenter/searcher.rs
  app/gui/src/tests.rs
  app/gui/suggestion-database/src/entry.rs
  app/gui/suggestion-database/src/lib.rs
  app/gui/tests/language_server.rs
  app/gui/view/debug_scene/interface/src/lib.rs
  app/gui/view/graph-editor/src/component/breadcrumbs/breadcrumb.rs
  app/gui/view/graph-editor/src/component/node.rs
  app/gui/view/graph-editor/src/component/node/input/area.rs
  app/gui/view/graph-editor/src/component/node/input/port.rs
  app/gui/view/graph-editor/src/component/node/input/widget.rs
  app/gui/view/graph-editor/src/lib.rs
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/VcsManagerTest.scala
  lib/rust/ensogl/component/text/src/font/glyph.rs
  lib/rust/ensogl/core/src/display/object/instance.rs
  lib/rust/ensogl/core/src/system/gpu/data/attribute.rs
  lib/rust/frp/src/network.rs
  lib/rust/frp/src/nodes.rs
  lib/rust/prelude/src/debug.rs
Labels: CI: Ready to merge, CI: Clean build required

#4110 Write the log in XML format suitable for VisualVM 'UI Actions'
  CHANGELOG.md
  docs/profiler/engine-startup.md
  docs/profiler/profiling.md
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ApiEventsMonitor.scala
Labels: CI: Ready to merge

#4118 Review `Missing_Input_Column` and `Column_Index_Out_Of_Range` warnings
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Aggregate_Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column_Selector.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Expression.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Aggregate_Column_Helper.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Problem_Builder.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  test/Table_Tests/src/Common_Table_Operations/Aggregate_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Core_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Cross_Tab_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Distinct_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Filter_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Join_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Union_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Main.enso
  test/Table_Tests/src/Common_Table_Operations/Order_By_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Select_Columns_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Transpose_Spec.enso
  test/Table_Tests/src/Database/Codegen_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#5564 Adjusting annotations to use Widget types properly.
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Filter_Condition.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Error/Problem_Behavior.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Metadata.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Connection.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Widgets.enso
  engine/runtime/src/test/java/org/enso/compiler/ParseStdLibTest.java
Labels: CI: Ready to merge, CI: No changelog needed

#5580 New issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/epic.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/task.md
Labels: CI: No changelog needed

#4119 Fix issue with reverting text edits on cmd-click
  app/gui/view/graph-editor/src/component/node/input/area.rs
  app/gui/view/graph-editor/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#5577 Stabilize flaky test that re-uses test setup
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/data/Config.scala
  engine/language-server/src/main/scala/org/enso/languageserver/vcsmanager/Git.scala
  engine/language-server/src/test/scala/org/enso/languageserver/vcsmanager/GitSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/VcsManagerTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#4120 Ensure Table Visualisation is the Default Visualization for Tables
  CHANGELOG.md
  app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js
  app/gui/view/graph-editor/src/component/visualization/container.rs
  app/gui/view/graph-editor/src/component/visualization/registry.rs
  test/Visualization_Tests/src/Default_Visualizations_Spec.enso
  test/Visualization_Tests/src/Main.enso
Labels: CI: Ready to merge

#5578 Lookup method pointers in IDE
  app/gui/controller/engine-protocol/src/language_server/types.rs
  app/gui/src/controller/graph/executed.rs
  app/gui/src/model/execution_context.rs
  app/gui/src/presenter/graph.rs
  app/gui/src/presenter/graph/call_stack.rs
  app/gui/suggestion-database/src/lib.rs
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextEventsListener.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistry.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistryProtocol.scala
  engine/language-server/src/test/scala/org/enso/languageserver/runtime/ContextEventsListenerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#5588 Check `cargo` return value to ensure issues are reported back to SBT
  build.sbt
  project/Cargo.scala
  project/LauncherShimsForTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#5579 Rework Invalid Aggregations
  distribution/lib/Standard/Base/0.0.0-dev/src/Error/Problem_Behavior.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Java_Problems.enso
  std-bits/table/src/main/java/org/enso/table/data/index/MultiValueIndex.java
  std-bits/table/src/main/java/org/enso/table/data/table/Table.java
  test/Table_Tests/src/Common_Table_Operations/Aggregate_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Cross_Tab_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#5592 Some fixed form the Anagrams experiment.
  app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json/Extensions.enso
  engine/runtime/src/test/java/org/enso/compiler/ParseStdLibTest.java
  std-bits/table/src/main/java/org/enso/table/aggregations/Concatenate.java
  std-bits/table/src/main/java/org/enso/table/data/table/Column.java
  test/Table_Tests/src/Common_Table_Operations/Aggregate_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#4111 Report type of expressions returning polyglot values
  CHANGELOG.md
  engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/BuiltinTypesTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeErrorsTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeInstrumentTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime-with-polyglot/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/instrument/IdExecutionService.java
  engine/runtime/src/main/java/org/enso/interpreter/instrument/RuntimeCache.java
  engine/runtime/src/main/java/org/enso/interpreter/instrument/UpdatesSynchronizationState.java
  engine/runtime/src/main/java/org/enso/interpreter/node/ExpressionNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/TypeOfNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/type/Constants.java
  engine/runtime/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime/src/test/java/org/enso/interpreter/test/MetaObjectTest.java
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/TestMessages.scala
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/TypeProcessor.java
Labels: CI: Ready to merge, CI: Clean build required

#5591 Recover from serialization failures
  CHANGELOG.md
  engine/runtime/src/main/scala/org/enso/compiler/SerializationManager.scala
Labels: CI: Ready to merge

#5596 fix visualization debug scene
  app/gui/view/debug_scene/visualization/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#5593 Send method pointers of constructors
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime-with-polyglot/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/instrument/IdExecutionService.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/atom/QualifiedAccessorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/AtomConstructor.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/BoxingAtom.java
Labels: CI: Ready to merge, CI: No changelog needed

#5597 Remove duplicate entry in default visualisations.
  app/gui/view/graph-editor/src/component/visualization/registry.rs
Labels: CI: Ready to merge, CI: No changelog needed

#5599 Fix unhandled macro match failure case (#5056)
  lib/rust/parser/debug/tests/parse.rs
  lib/rust/parser/src/lib.rs
  lib/rust/parser/src/macros/resolver.rs
Labels: CI: Ready to merge, CI: No changelog needed

#5600 Fix serialization of FQNs
  engine/runtime/src/main/scala/org/enso/compiler/ModuleCache.scala
  engine/runtime/src/main/scala/org/enso/compiler/SerializationManager.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/FullyQualifiedNames.scala
  engine/runtime/src/test/java/org/enso/compiler/SerializerTest.java
  engine/runtime/src/test/resources/Test_Serializer_FQN/package.yaml
  engine/runtime/src/test/resources/Test_Serializer_FQN/src/Main.enso
  engine/runtime/src/test/scala/org/enso/compiler/test/CacheInvalidationTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#5630 Fix separate compilation for ConstantsGen
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/TypeProcessor.java
Labels: CI: Ready to merge, CI: No changelog needed

#4117 Set edition when starting language server
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
Labels: CI: Ready to merge, CI: No changelog needed

#5617 Fix links to dev documentation
  app/gui/controller/engine-protocol/src/project_manager.rs
  app/gui/language/ast/impl/src/macros.rs
  app/gui/language/ast/impl/src/opr.rs
  app/gui/view/graph-editor/src/component/visualization/instance.rs
  app/gui/view/graph-editor/src/component/visualization/metadata.rs
Labels: CI: Ready to merge, CI: No changelog needed

#4085 Exclude components with a "PRIVATE" tag from the component browser
  CHANGELOG.md
  app/gui/language/ast/impl/src/lib.rs
  app/gui/src/controller/searcher/component.rs
  app/gui/src/controller/searcher/component/builder.rs
Labels: CI: Ready to merge

#5601 extend list of allowed project templates
  build/build/src/engine.rs
  lib/scala/pkg/src/main/scala/org/enso/pkg/Package.scala
  lib/scala/pkg/src/main/scala/org/enso/pkg/Template.scala
Labels: CI: Ready to merge, CI: No changelog needed

#5598 Improve Text.toDisplayString (#5045)
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/text/Text.java
  test/Benchmarks/src/Text/Pretty.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#5654 Make font size in the documentation panel smaller
  app/gui/view/documentation/src/html.rs
  app/gui/view/documentation/tailwind.config.js
Labels: CI: Ready to merge, CI: No changelog needed

#4087 Implement Backend API for Lazy Table Visualization.
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Helpers.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table.enso
  test/Visualization_Tests/src/Lazy_Table_Spec.enso
  test/Visualization_Tests/src/Main.enso
Labels: CI: Ready to merge, CI: No changelog needed

#5602 Update GraalVM to 22.3.1
  .github/workflows/formatting.yml
  CHANGELOG.md
  build.sbt
  build/ci_utils/src/cache/goodie/graalvm.rs
  docs/infrastructure/upgrading-graalvm.md
  engine/runtime/src/main/java/org/enso/interpreter/instrument/HostObjectDebugWrapper.java
  engine/runtime/src/main/java/org/enso/interpreter/node/ExpressionNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/function/StatementNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/DebugLocalScope.java
  engine/runtime/src/test/java/org/enso/interpreter/test/DebuggingEnsoTest.java
  test/Tests/src/Network/Http_Spec.enso
  tools/ci/docker/Dockerfile
  tools/enso4igv/README.md
Labels: CI: Ready to merge, -compiler

#5646 Remove `Column` type from Aggregate_Column, simplify Column_Selector, some new `File_Format`s
  CHANGELOG.md
  build.sbt
  distribution/lib/Standard/Base/0.0.0-dev/src/Metadata.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/SQLite_Format.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Image_File_Format.enso
  distribution/lib/Standard/Searcher/0.0.0-dev/src/Data_Science/Preparation.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Aggregate_Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column_Selector.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Row.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Reader.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Section.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Workbook.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Aggregate_Column_Helper.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
  std-bits/database/src/main/java/org/enso/database/SQLiteFormatSPI.java
  std-bits/image/src/main/java/org/enso/image/ImageFormatSPI.java
  std-bits/table/src/main/java/org/enso/table/read/ExcelReader.java
  test/Benchmarks/src/Table/Aggregate.enso
  test/Image_Tests/src/Image_Read_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Aggregate_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Core_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Cross_Tab_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Distinct_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Expression_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Join_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Select_Columns_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Transpose_Spec.enso
  test/Table_Tests/src/Database/Codegen_Spec.enso
  test/Table_Tests/src/Database/Common_Spec.enso
  test/Table_Tests/src/Database/SQLite_Spec.enso
  test/Table_Tests/src/IO/Csv_Spec.enso
  test/Table_Tests/src/IO/Excel_Spec.enso
  test/Table_Tests/src/In_Memory/Aggregate_Column_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
Labels: CI: Ready to merge

#4050 Roll back last VCS snapshot
  CHANGELOG.md
  app/gui/controller/engine-protocol/src/language_server.rs
  app/gui/controller/engine-protocol/src/language_server/response.rs
  app/gui/controller/engine-protocol/src/language_server/types.rs
  app/gui/src/controller/graph.rs
  app/gui/src/controller/project.rs
  app/gui/src/controller/text.rs
  app/gui/src/model/module.rs
  app/gui/src/model/module/plain.rs
  app/gui/src/model/module/synchronized.rs
  app/gui/src/model/project/synchronized.rs
  app/gui/src/model/registry.rs
  app/gui/src/presenter/project.rs
  app/gui/view/src/project.rs
  lib/scala/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/Parser.scala
Labels: CI: Ready to merge

#5609 sbt runEngineDistribution ...args... to build and execute the engine
  CHANGELOG.md
  build.sbt
  docs/CONTRIBUTING.md
  project/DistributionPackage.scala
  tools/enso4igv/README.md
  tools/language-server/wstest/benchmarks/apply-edit/README.md
Labels: -tooling, CI: Ready to merge, CI: Clean build required, -compiler, -libs

#5645 Improve searching of component browser entries
  CHANGELOG.md
  app/gui/src/controller/searcher/component.rs
Labels: CI: Ready to merge

#5652 Ensure entries containing newlines are quoted when writing Delimited Files
  distribution/lib/Standard/Base/0.0.0-dev/src/Any.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Error.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/Existing_File_Behavior.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/Write_Extensions.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Delimited/Delimited_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Delimited/Delimited_Writer.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Java_Problems.enso
  std-bits/table/src/main/java/org/enso/table/data/table/problems/ArithmeticError.java
  std-bits/table/src/main/java/org/enso/table/data/table/problems/ColumnAggregatedProblems.java
  std-bits/table/src/main/java/org/enso/table/data/table/problems/UnquotedCharactersInOutput.java
  std-bits/table/src/main/java/org/enso/table/read/DelimitedReader.java
  std-bits/table/src/main/java/org/enso/table/write/DelimitedWriter.java
  test/Table_Tests/src/Common_Table_Operations/Aggregate_Spec.enso
  test/Table_Tests/src/IO/Csv_Spec.enso
  test/Table_Tests/src/IO/Delimited_Read_Spec.enso
  test/Table_Tests/src/IO/Delimited_Write_Spec.enso
  test/Table_Tests/src/IO/Excel_Spec.enso
  test/Table_Tests/src/IO/Json_Spec.enso
  test/Table_Tests/src/In_Memory/Join_Performance_Spec.enso
  test/Tests/src/Semantic/Error_Spec.enso
  test/Tests/src/Semantic/Warnings_Spec.enso
  test/Tests/src/System/File_Spec.enso
  test/Tests/src/System/Reporting_Stream_Encoder_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#5665 Fix Match Scoring Algorithm
  app/gui/src/controller/searcher/component.rs
  lib/rust/fuzzly/src/metric.rs
  lib/rust/fuzzly/src/score.rs
Labels: CI: Ready to merge, CI: No changelog needed

#5624 Fix visualizations sometimes not opening with space bar.
  app/gui/view/graph-editor/src/lib.rs
  lib/rust/web/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#5676 Bump supported engine version
  app/gui/config.yaml
  app/gui/config/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#5677 Ensure that warnings are preserved on Nothing values passing back to Enso through polyglot boundary
  build.sbt
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/syntax/HostValueToEnsoNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/foreign/CoerceNothing.java
  std-bits/base/src/main/java/org/enso/base/Encoding_Utils.java
  test/Tests/polyglot-sources/enso-test-java-helpers/src/main/java/org/enso/base_test_helpers/CallbackHelper.java
  test/Tests/src/Semantic/Warnings_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#5680 Schedule initialization of JS context in a separate thread
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/polyglot-api/src/main/java/org/enso/polyglot/RuntimeOptions.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbContext.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbLanguage.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/node/ForeignEvalNode.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/runtime/GuardedTruffleContext.java
  engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/instrument/MockLogHandler.java
  engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/instrument/VerifyJavaScriptIsAvailableTest.java
  engine/runtime/src/main/java/org/enso/interpreter/EnsoLanguage.java
  engine/runtime/src/main/java/org/enso/interpreter/instrument/IdExecutionService.java
Labels: CI: Ready to merge, CI: No changelog needed, -compiler

#5679 Update Text.locate, Text.locate_all, Text.index_of and Text.last_index_of #5119
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Matching_Mode.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Engine/Default.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Pattern.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Regex_Mode.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  test/Tests/src/Data/Text/Default_Regex_Engine_Spec.enso
  test/Tests/src/Data/Text_Spec.enso
Labels: CI: Ready to merge

#5688 Optimize opening dropdown
  Cargo.lock
  app/gui/language/parser-scala/src/jsclient.rs
  app/gui/language/parser-scala/src/lib.rs
  app/gui/language/parser-scala/src/wsclient.rs
  app/gui/suggestion-database/Cargo.toml
  app/gui/suggestion-database/src/lib.rs
  app/gui/view/graph-editor/src/component/node/input/widget.rs
  app/gui/view/graph-editor/src/lib.rs
  lib/rust/ensogl/component/drop-down/src/entry.rs
  lib/rust/ensogl/component/drop-down/src/lib.rs
  lib/rust/ensogl/component/drop-down/src/model.rs
  lib/rust/ensogl/component/grid-view/src/lib.rs
  lib/rust/ensogl/component/text/src/component/text.rs
  lib/rust/ensogl/component/text/src/font.rs
  lib/rust/ensogl/component/text/src/font/glyph.rs
  lib/rust/ensogl/component/text/src/font/glyph_render_info.rs
  lib/rust/ensogl/core/src/animation/frp/animation.rs
  lib/rust/ensogl/core/src/control/io/mouse.rs
  lib/rust/ensogl/core/src/display/object/instance.rs
  lib/rust/ensogl/example/render-profile-flamegraph/Cargo.toml
  lib/rust/ensogl/example/render-profile-flamegraph/src/lib.rs
  lib/rust/executor/src/global.rs
  lib/rust/frp/src/macros.rs
Labels: CI: No changelog needed, -gui

#5656 Support widgets and placeholders in more complex expressions
  CHANGELOG.md
  app/gui/language/ast/impl/src/opr.rs
  app/gui/language/span-tree/example/src/lib.rs
  app/gui/language/span-tree/src/action.rs
  app/gui/language/span-tree/src/generate.rs
  app/gui/language/span-tree/src/generate/context.rs
  app/gui/language/span-tree/src/iter.rs
  app/gui/language/span-tree/src/node.rs
  app/gui/language/span-tree/src/node/kind.rs
  app/gui/src/controller/graph.rs
  app/gui/src/controller/graph/executed.rs
  app/gui/src/controller/graph/widget.rs
  app/gui/suggestion-database/src/entry.rs
  app/gui/suggestion-database/src/lib.rs
  app/gui/view/debug_scene/interface/src/lib.rs
  app/gui/view/graph-editor/src/component/node/input/area.rs
  app/gui/view/graph-editor/src/component/node/input/widget.rs
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Filter_Condition.enso
Labels: CI: Ready to merge, CI: Clean build required

#5684 Two findExceptionMessage methods to extract exception messages consistently
  build.sbt
  engine/polyglot-api/src/main/java/org/enso/polyglot/HostEnsoUtils.java
  engine/runner/src/main/scala/org/enso/runner/Main.scala
  engine/runtime-with-instruments/src/test/java/org/enso/interpreter/test/FindExceptionMessageTest.java
  engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/PolyglotFindExceptionMessageTest.java
  engine/runtime/src/main/java/org/enso/interpreter/instrument/job/VisualizationResult.java
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  project/FrgaalJavaCompiler.scala
Labels: CI: Ready to merge, CI: No changelog needed

#5607 Open Project Dialog
  Cargo.lock
  app/gui/src/controller/ide.rs
  app/gui/src/controller/ide/desktop.rs
  app/gui/src/presenter.rs
  app/gui/src/presenter/project.rs
  app/gui/view/Cargo.toml
  app/gui/view/src/lib.rs
  app/gui/view/src/open_dialog.rs
  app/gui/view/src/open_dialog/project_list.rs
  app/gui/view/src/project.rs
  app/gui/view/src/project_list.rs
  lib/rust/ensogl/app/theme/hardcoded/src/lib.rs
  lib/rust/ensogl/component/grid-view/src/entry.rs
  lib/rust/ensogl/core/src/system/js/app.rs
  lib/rust/ensogl/pack/js/src/runner/index.ts
  lib/rust/ensogl/pack/js/src/runner/wasm/loader.ts
Labels: CI: Ready to merge, CI: No changelog needed

#5699 File.parent can return Nothing
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoFile.java
  test/Tests/src/System/File_Spec.enso
Labels: CI: Ready to merge

#5582 Add a shortcut to toggle the visibility of private components in the component browser
  CHANGELOG.md
  app/gui/docs/product/shortcuts.md
  app/gui/src/controller/ide.rs
  app/gui/src/controller/ide/desktop.rs
  app/gui/src/controller/ide/plain.rs
  app/gui/src/controller/searcher.rs
  app/gui/src/controller/searcher/component/builder.rs
  app/gui/src/presenter/project.rs
  app/gui/src/presenter/searcher.rs
  app/gui/view/component-browser/component-list-panel/src/navigator.rs
  app/gui/view/src/project.rs
Labels: CI: Ready to merge

#5702 Adding JSON serialization for Map. Adding Table viz support for map.
  app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Map.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
Labels: CI: Ready to merge, CI: No changelog needed

#5687 Performance improvements for Comparators
  distribution/lib/Standard/Base/0.0.0-dev/src/Any.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Ordering.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Runtime/State.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/HashCodeNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Array.java
  engine/runtime/src/test/java/org/enso/interpreter/test/EqualsTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/HashCodeTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/ValuesGenerator.java
Labels: p-highest, CI: Ready to merge, CI: No changelog needed, --low-performance

#5715 Exception message may not be specified
  lib/scala/logging-service/src/main/scala/org/enso/loggingservice/internal/DefaultLogMessageRenderer.scala
  lib/scala/logging-service/src/main/scala/org/enso/loggingservice/internal/protocol/WSLogMessage.scala
  lib/scala/logging-service/src/test/scala/org/enso/loggingservice/internal/DefaultLogMessageRendererSpec.scala
Labels: CI: Ready to merge, CI: No changelog needed

#5736 Avoid nulls in Array.items
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/runtime/GetStackTraceNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/Atom.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Array.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Vector.java
  engine/runtime/src/test/java/org/enso/interpreter/test/ArrayTest.java
Labels: CI: Ready to merge, CI: No changelog needed

#5721 Wip/gmt/match find only text
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Case_Sensitivity.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Suite_Config.enso
  test/Tests/src/Data/Text_Spec.enso
Labels: CI: Ready to merge

#5685 Cached Shape Parameter
  Cargo.lock
  app/gui/view/graph-editor/src/component/breadcrumbs.rs
  app/gui/view/src/window_control_buttons.rs
  lib/rust/ensogl/component/grid-view/src/simple.rs
  lib/rust/ensogl/core/Cargo.toml
  lib/rust/ensogl/core/src/data/bounding_box.rs
  lib/rust/ensogl/core/src/display/render/passes/cache_shapes.rs
  lib/rust/ensogl/core/src/display/shape/primitive/glsl/codes.rs
  lib/rust/ensogl/core/src/display/shape/primitive/glsl/fragment_runner.glsl
  lib/rust/ensogl/core/src/display/shape/primitive/glsl/shape.glsl
  lib/rust/ensogl/core/src/display/shape/primitive/shader/builder.rs
  lib/rust/ensogl/core/src/display/shape/primitive/shader/canvas.rs
  lib/rust/ensogl/core/src/display/shape/primitive/system.rs
  lib/rust/ensogl/core/src/display/shape/primitive/system/cached.rs
  lib/rust/ensogl/core/src/display/shape/primitive/system/cached/arrange_on_texture.rs
  lib/rust/ensogl/core/src/display/symbol/gpu/registry.rs
  lib/rust/ensogl/core/src/display/symbol/gpu/shader.rs
  lib/rust/ensogl/core/src/display/world.rs
  lib/rust/ensogl/core/src/gui/cursor.rs
  lib/rust/ensogl/core/src/system/gpu/shader/glsl.rs
  lib/rust/ensogl/examples/cached-shape/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#5701 Review Text encoding/decoding problem handling
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  test/Tests/src/Data/Text/Encoding_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#5678 Match component browser entries by alias
  CHANGELOG.md
  app/gui/language/ast/impl/src/lib.rs
  app/gui/src/controller/searcher/action.rs
  app/gui/src/controller/searcher/component.rs
  app/gui/src/controller/searcher/component/group.rs
  app/gui/src/presenter/searcher/provider.rs
Labels: CI: Ready to merge

#5719 Update `rename_columns` to new API design, add `first_row`, `second_row` and `last_row` functions to the table.
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Case_Sensitivity.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Pattern.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/JDBC_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Result_Set.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Connection.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column_Name_Mapping.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Main.enso
  std-bits/database/src/main/java/org/enso/database/JDBCProxy.java
  test/Table_Tests/src/Common_Table_Operations/Core_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Integration_Tests.enso
  test/Table_Tests/src/Common_Table_Operations/Select_Columns_Spec.enso
  test/Table_Tests/src/IO/Delimited_Write_Spec.enso
  test/Table_Tests/src/IO/Excel_Spec.enso
Labels: CI: Ready to merge

#5692 Improve Table.parse_values API
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column_Type_Selection.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Data_Formatter.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Value_Type.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Extensions.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Problems.enso
  std-bits/table/src/main/java/org/enso/table/parsing/TypeInferringParser.java
  test/Table_Tests/src/Formatting/Parse_Values_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#5693 Improve error handling of Connection.query
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Redshift/Redshift_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  test/Table_Tests/src/Database/Common_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Database/SQLite_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#5760 Stability improvements in visualizations.
  app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Warning.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/IndirectInvokeCallableNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/Warning.java
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/ErrorResolver.scala
Labels: CI: Ready to merge, CI: No changelog needed

#5682 Update system requirements of CONTRIBUTING documents
  docs/CONTRIBUTING.md
Labels: CI: Ready to merge, CI: No changelog needed

#5752 Filling cached shapes with a different color.
  app/gui/view/component-browser/component-list-panel/grid/src/entry/icon.rs
  lib/rust/ensogl/core/src/display/shape/primitive/def/class.rs
  lib/rust/ensogl/core/src/display/shape/primitive/def/modifier.rs
  lib/rust/ensogl/core/src/display/shape/primitive/glsl/shape.glsl
  lib/rust/ensogl/core/src/display/shape/primitive/shader/canvas.rs
  lib/rust/ensogl/examples/cached-shape/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#5764 Fixing incorrect Electron behavior.
  app/ide-desktop/lib/client/src/config.ts
  app/ide-desktop/lib/client/src/debug.ts
  app/ide-desktop/lib/client/src/index.ts
  app/ide-desktop/lib/content/src/index.html
  app/ide-desktop/lib/content/src/style.css
Labels: CI: No changelog needed

#5769 Adjust generateCheckedArgumentRead to return correct expected type
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/BuiltinType.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/BuiltinsProcessor.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/MethodProcessor.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/TypeProcessor.java
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#5757 Fix missing visualization preview in CB
  CHANGELOG.md
  app/gui/view/graph-editor/src/component/visualization/container.rs
Labels: CI: Ready to merge

#5747 Offer no suggestion for single constructor
  engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/context/SuggestionBuilderTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#5776 Convert dangling comma into unexpected expression
  engine/runtime/src/main/java/org/enso/compiler/TreeToIr.java
  engine/runtime/src/test/java/org/enso/compiler/EnsoCompilerTest.java
Labels: CI: Ready to merge, CI: No changelog needed

#5738 Fixing the node.js dependencies, so the VSCode plugin can be built again
  .github/workflows/enso4igv.yml
  tools/enso4igv/package.json
Labels: CI: Ready to merge, CI: No changelog needed
