Repository enso-org/enso, pull requests merged in 2023-08, with the labels that each got.

#7392 New top bar
  app/ide-desktop/lib/assets/bars.svg
  app/ide-desktop/lib/assets/chat.svg
  app/ide-desktop/lib/assets/cloud.svg
  app/ide-desktop/lib/assets/drive.svg
  app/ide-desktop/lib/assets/find.svg
  app/ide-desktop/lib/assets/home.svg
  app/ide-desktop/lib/assets/magnifying_glass.svg
  app/ide-desktop/lib/assets/network.svg
  app/ide-desktop/lib/assets/not_cloud.svg
  app/ide-desktop/lib/assets/settings.svg
  app/ide-desktop/lib/assets/speech_bubble.svg
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetInfoBar.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/backendSwitcher.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/button.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/chat.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/driveBar.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/driveView.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/editor.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/ide.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/pageSwitcher.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/topBar.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/userBar.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/userMenu.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/tab.ts
  app/ide-desktop/lib/dashboard/src/tailwind.css
  app/ide-desktop/lib/dashboard/tailwind.config.ts
Labels: CI: No changelog needed

#7442 Fix `.png` and `.svg` loading errors
  app/ide-desktop/lib/content/esbuild-config.ts
Labels: CI: No changelog needed

#7450 Add missing cognito oauth scope
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/config.ts
Labels: CI: Ready to merge, CI: No changelog needed

#7441 Fix Component Browser Preview
  app/gui/src/presenter/searcher.rs
  app/gui/view/graph-editor/src/component/node.rs
  app/gui/view/graph-editor/src/component/visualization/container.rs
  app/gui/view/graph-editor/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#7451 Auth flow improvements
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/input.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/login.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/registration.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/resetPassword.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/changePasswordModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/driveView.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/input.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/userMenu.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/validation.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/string.ts
Labels: CI: No changelog needed

#7404 impr(cloud-v2#494): Remove OpenSSL as a dependency
  Cargo.lock
  Cargo.toml
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/service.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/config.ts
  build/deprecated/build-utils/Cargo.toml
Labels: CI: No changelog needed

#7483 Add common-polyglot-core-utils to projects' aggregates
  build.sbt
  lib/scala/common-polyglot-core-utils/src/main/java/org/enso/polyglot/common_utils/package-info.java
Labels: CI: Ready to merge, CI: No changelog needed

#7429 Fix broken text vis layout on slow loading
  app/gui/view/graph-editor/src/builtin/visualization/native/text_visualization/grid_view_entry.rs
Labels: CI: Ready to merge, CI: No changelog needed

#7484 Fix CB scoring for new label format.
  app/gui/src/controller/searcher/component.rs
  app/gui/src/controller/searcher/search.rs
Labels: CI: Ready to merge, CI: No changelog needed

#7420 Adopting GraalVM's support for BigInteger
  CHANGELOG.md
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/IndirectInvokeMethodNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/resolver/HostMethodCallNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/syntax/HostValueToEnsoNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/AbsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/AddNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/BitAndNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/BitOrNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/BitShiftNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/BitXorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/DivNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/ModNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/MultiplyNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/NegateNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/PowNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/bigInteger/SubtractNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/AbsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/AddNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/BitAndNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/BitOrNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/BitShiftNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/BitXorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/MultiplyNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/NegateNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/PowNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/SubtractNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/utils/ToEnsoNumberNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/Warning.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/number/EnsoBigInteger.java
  engine/runtime/src/test/java/org/enso/example/TestClass.java
  engine/runtime/src/test/java/org/enso/interpreter/node/callable/PolyglotCallTypeTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/BigNumberTest.java
  test/Tests/src/Data/Numbers_Spec.enso
Labels: CI: Ready to merge, CI: Keep up to date

#7425 Expose Unicode normalization methods on Texts
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Normalization.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  std-bits/base/src/main/java/org/enso/base/Text_Utils.java
  test/Tests/src/Data/Text_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#7495 Fix column naming edge cases - invalid and duplicated columns, case-insensitive name aliasing for case-insensitive backends
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Common/Encoding_Limited_Naming_Properties.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Entity_Naming_Properties.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Entity_Naming_Properties.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Aggregate_Column_Helper.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Column_Naming_Helper.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Excel_Reader.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Java_Problems.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Naming_Properties.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Problem_Builder.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Unique_Name_Strategy.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Problems.enso
  std-bits/base/src/main/java/org/enso/base/text/CaseInsensitiveUnicodeNormalizedTextEquivalence.java
  std-bits/base/src/main/java/org/enso/base/text/UnicodeNormalizedTextEquivalence.java
  std-bits/table/src/main/java/org/enso/table/util/NameDeduplicator.java
  std-bits/table/src/main/java/org/enso/table/util/NamingProperties.java
  test/Table_Tests/src/Common_Table_Operations/Column_Name_Edge_Cases_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Core_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Cross_Tab_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Main.enso
  test/Table_Tests/src/Common_Table_Operations/Select_Columns_Spec.enso
  test/Table_Tests/src/Database/Common/Common_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Database/SQLite_Spec.enso
  test/Table_Tests/src/Database/Upload_Spec.enso
  test/Table_Tests/src/IO/Delimited_Read_Spec.enso
  test/Table_Tests/src/IO/Excel_Spec.enso
  test/Table_Tests/src/In_Memory/Column_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#7475 Two fixes: hidden CB entry and scrolling in text vis.
  app/gui/view/component-browser/component-list-panel/grid/src/lib.rs
  app/gui/view/graph-editor/src/builtin/visualization/native/text_grid.rs
  app/gui/view/graph-editor/src/component/visualization/container.rs
  lib/rust/ensogl/core/src/display/scene.rs
Labels: CI: Ready to merge, CI: No changelog needed

#7458 Introducing new notifications to the GUI
  app/gui/src/controller/ide.rs
  app/gui/src/ide.rs
  app/gui/src/ide/initializer.rs
  app/gui/src/presenter.rs
  app/gui/src/presenter/project.rs
  app/gui/view/examples/interface/src/lib.rs
  app/gui/view/src/debug_mode_popup.rs
  app/gui/view/src/lib.rs
  app/gui/view/src/notification.rs
  app/gui/view/src/notification/api.rs
  app/gui/view/src/notification/js.rs
  app/gui/view/src/notification/logged.rs
  app/gui/view/src/project.rs
  app/gui/view/src/root.rs
  app/gui/view/src/status_bar.rs
  app/ide-desktop/lib/dashboard/src/authentication/src/components/app.tsx
  app/ide-desktop/lib/dashboard/src/tailwind.css
  integration-test/tests/graph_editor.rs
  lib/rust/ensogl/app/theme/hardcoded/src/lib.rs
Labels: CI: No changelog needed

#7417 Avoid indexing the table twice for Cross Tab
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  std-bits/table/src/main/java/org/enso/table/data/index/CrossTabIndex.java
  std-bits/table/src/main/java/org/enso/table/data/index/MultiValueIndex.java
  std-bits/table/src/main/java/org/enso/table/data/index/ObjectNumberer.java
  std-bits/table/src/main/java/org/enso/table/data/index/UnorderedMultiValueKey.java
  std-bits/table/src/main/java/org/enso/table/data/table/Table.java
  test/Benchmarks/src/Table/Cross_Tab.enso
  test/Benchmarks/src/Table/Main.enso
  test/Table_Tests/src/Common_Table_Operations/Cross_Tab_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#7430 Fix dispatching events to assets table
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/enterOfflineMode.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/backend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetsTable.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/button.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/directoryNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/driveView.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/editor.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectIcon.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/table.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/tableRow.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/localBackend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/projectManager.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/remoteBackend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/hooks.tsx
Labels: CI: No changelog needed

#7482 Avoid NPEs during regular execution
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
Labels: CI: Ready to merge, CI: No changelog needed

#7101 Invoke all Enso benchmarks via JMH
  build.sbt
  docs/CONTRIBUTING.md
  docs/debugger/README.md
  docs/debugger/chrome-devtools.md
  docs/debugger/mixed-debugging.md
  docs/debugger/runtime-debugging.md
  docs/infrastructure/README.md
  docs/infrastructure/benchmarks.md
  lib/scala/bench-processor/src/main/java/org/enso/benchmarks/BenchConfig.java
  lib/scala/bench-processor/src/main/java/org/enso/benchmarks/BenchGroup.java
  lib/scala/bench-processor/src/main/java/org/enso/benchmarks/BenchSpec.java
  lib/scala/bench-processor/src/main/java/org/enso/benchmarks/BenchSuite.java
  lib/scala/bench-processor/src/main/java/org/enso/benchmarks/ModuleBenchSuite.java
  lib/scala/bench-processor/src/main/java/org/enso/benchmarks/Utils.java
  lib/scala/bench-processor/src/main/java/org/enso/benchmarks/processor/BenchProcessor.java
  lib/scala/bench-processor/src/main/java/org/enso/benchmarks/processor/GenerateBenchSources.java
  lib/scala/bench-processor/src/main/java/org/enso/benchmarks/processor/SpecCollector.java
  lib/scala/bench-processor/src/main/java/org/enso/benchmarks/runner/BenchRunner.java
  lib/scala/bench-processor/src/main/java/org/enso/benchmarks/runner/BenchmarkItem.java
  lib/scala/bench-processor/src/main/java/org/enso/benchmarks/runner/BenchmarkResultProcessor.java
  lib/scala/bench-processor/src/main/java/org/enso/benchmarks/runner/Report.java
  lib/scala/bench-processor/src/main/java/org/enso/benchmarks/runner/ReportItem.java
  lib/scala/bench-processor/src/test/java/org/enso/benchmarks/TestSpecCollector.java
  lib/scala/bench-processor/src/test/resources/Test_Collector/package.yaml
  lib/scala/bench-processor/src/test/resources/Test_Collector/src/Main.enso
  lib/scala/distribution-manager/src/main/scala/org/enso/distribution/LanguageHome.scala
  project/FrgaalJavaCompiler.scala
  std-bits/benchmarks/src/bench/java/org/enso/benchmarks/libs/LibBenchRunner.java
  test/Benchmarks/src/Main.enso
  test/Benchmarks/src/Vector/Distinct.enso
  test/Benchmarks/src/Vector/Operations.enso
  test/Benchmarks/src/Vector/Utils.enso
Labels: CI: Ready to merge, CI: No changelog needed

#7487 Convert no such method Panic to UnknownIdentifierException
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InteropMethodCallNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeCallableNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Error.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/Atom.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicException.java
  engine/runtime/src/test/java/org/enso/example/ToString.java
  engine/runtime/src/test/java/org/enso/interpreter/test/JavaInteropTest.java
Labels: CI: No changelog needed

#7493 Exclusive context policy ensures EnsoContext.get returns compilation constant
  engine/runtime/src/main/java/org/enso/interpreter/EnsoLanguage.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/AtomConstructor.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/Function.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Array.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/ArrayProxy.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoDate.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoDateTime.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoDuration.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoFile.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoTimeOfDay.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoTimeZone.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/ManagedResource.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Ref.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Vector.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/hash/EnsoHashMap.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/text/Text.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/DataflowError.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicException.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/Warning.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/library/dispatch/DefaultBooleanExports.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/library/dispatch/DefaultDoubleExports.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/library/dispatch/DefaultLongExports.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/number/EnsoBigInteger.java
  engine/runtime/src/test/java/org/enso/interpreter/test/SharedEngineTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/TestBase.java
Labels: CI: Ready to merge, CI: No changelog needed

#7497 Hide private entries in Component Browser
  app/gui/src/controller/searcher.rs
  app/gui/src/controller/searcher/component/builder.rs
  app/gui/suggestion-database/src/mock.rs
Labels: CI: Ready to merge, CI: No changelog needed

#7406 New sharing menu
  app/ide-desktop/debugGlobals.ts
  app/ide-desktop/eslint.config.js
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/listen.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/auth.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/service.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/backend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/column.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetInfoBar.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetsTable.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/autocomplete.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/backendSwitcher.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/chat.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/confirmDeleteModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/directoryNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/driveBar.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/fileNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/input.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/managePermissionsModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/modal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/permissionDisplay.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/permissionSelector.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/permissionTypeSelector.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectIcon.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/secretNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/table.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/tableRow.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/topBar.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/userBar.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/userPermissions.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/dateTime.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/events/assetEvent.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/permissions.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/permissions.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/projectManager.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/remoteBackend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/error.ts
  app/ide-desktop/lib/dashboard/src/tailwind.css
  app/ide-desktop/lib/dashboard/tailwind.config.ts
  app/ide-desktop/lib/types/globals.d.ts
Labels: CI: Ready to merge, CI: No changelog needed

#7515 Renaming Variable or Function Support
  CHANGELOG.md
  build.sbt
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonRpc.scala
  engine/language-server/src/main/scala/org/enso/languageserver/refactoring/RefactoringApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/refactoring/RenameFailureMapper.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/refactoring/RenameSymbolHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/text/ApplyEditHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ExecutionApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/RuntimeFailureMapper.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/BufferRegistry.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/CollaborativeBuffer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/TextProtocol.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/RefactoringTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/TextOperationsTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/Command.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/CommandFactory.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/RenameSymbolCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/CommandExecutionEngine.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/JobExecutionEngine.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/PendingEdits.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/PendingFileEdits.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/RuntimeContext.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/RefactoringRenameJob.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/UpsertVisualizationJob.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeRefactoringTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime/src/main/scala/org/enso/compiler/refactoring/IRUtils.scala
  engine/runtime/src/test/scala/org/enso/compiler/refactoring/IRUtilsTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/context/SuggestionBuilderTest.scala
  lib/scala/refactoring-utils/src/main/java/org/enso/refactoring/validation/MethodNameValidation.java
  lib/scala/refactoring-utils/src/main/scala/org/enso/refactoring/RenameUtils.scala
  lib/scala/refactoring-utils/src/test/scala/org/enso/refactoring/RenameUtilsTest.java
  lib/scala/refactoring-utils/src/test/scala/org/enso/refactoring/validation/MethodNameValidationTest.java
Labels: CI: Ready to merge

#7467 `localStorage` manager
  app/ide-desktop/lib/content/src/index.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/auth.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/components/app.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/backend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetsTable.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/editor.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/templates.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/topBar.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/load.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/localBackend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/localStorage.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/remoteBackend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/providers/backend.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/providers/localStorage.tsx
  app/ide-desktop/lib/dashboard/src/index.tsx
  app/ide-desktop/lib/types/types.d.ts
Labels: CI: Ready to merge, CI: No changelog needed

#7533 Display user-provided project name in the top bar
  app/gui/src/config.rs
  app/gui/src/controller/ide/plain.rs
  app/gui/src/ide/initializer.rs
  app/gui/src/model/project/synchronized.rs
  app/ide-desktop/lib/content-config/src/config.json
Labels: CI: Ready to merge, CI: No changelog needed

#7564 Fix IDE bug on cloud backend
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/auth.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/components/app.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/editor.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/shortcuts.tsx
Labels: CI: Ready to merge, CI: No changelog needed

#7558 Fixes for importing project bundles
  app/ide-desktop/lib/client/src/bin/server.ts
  app/ide-desktop/lib/client/src/file-associations.ts
  app/ide-desktop/lib/client/src/paths.ts
  app/ide-desktop/lib/client/src/preload.ts
  app/ide-desktop/lib/client/src/project-management.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/driveView.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectNameColumn.tsx
  app/ide-desktop/lib/types/globals.d.ts
Labels: CI: Ready to merge, CI: No changelog needed

#7527 Change shortcut for opening Component Browser to `enter`
  CHANGELOG.md
  app/gui/docs/product/shortcuts.md
  app/gui/view/project-view-top-bar/src/lib.rs
  app/gui/view/src/project.rs
  lib/scala/pkg/src/main/resources/default/src/Main.enso
Labels: CI: Ready to merge

#7534 Simplify CB names
  app/gui/src/controller/searcher/component.rs
  app/gui/src/controller/searcher/component/builder.rs
  app/gui/src/model/module.rs
  lib/rust/prelude/src/string.rs
  lib/rust/text/src/text.rs
Labels: CI: Ready to merge, CI: No changelog needed

#7570 Load a maximum of one IDE entrypoint
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/editor.tsx
Labels: CI: Ready to merge, CI: No changelog needed

#7532 Fix broken text vis layout
  app/gui/view/graph-editor/src/builtin/visualization/native/text_visualization.rs
  app/gui/view/graph-editor/src/builtin/visualization/native/text_visualization/grid_view_entry.rs
Labels: CI: Ready to merge, CI: No changelog needed

#7460 Implement Number.round as a builtin
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/decimal/RoundNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/smallInteger/RoundNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/utils/RoundHelpers.java
  lib/scala/common-polyglot-core-utils/src/main/java/org/enso/polyglot/common_utils/Core_Math_Utils.java
  test/Benchmarks/src/Main.enso
  test/Benchmarks/src/Numeric.enso
  test/Tests/src/Data/Numbers_Spec.enso
  test/Tests/src/Semantic/Meta_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#7569 Add a method for getting component groups without execution context
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonRpc.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/runtime/GetComponentGroupsHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/RuntimeApi.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/RuntimeTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#7556 Improve generation of long operation in presence of column name length limit
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Column_Naming_Helper.enso
  test/Table_Tests/src/Database/Common/Names_Length_Limits_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#7508 Sync breadcrumbs and documentation panel.
  Cargo.lock
  app/gui/Cargo.toml
  app/gui/src/controller/searcher.rs
  app/gui/src/controller/searcher/breadcrumbs.rs
  app/gui/src/presenter/searcher/component_browser.rs
  app/gui/suggestion-database/src/documentation_ir.rs
  app/gui/suggestion-database/src/entry.rs
  app/gui/view/component-browser/Cargo.toml
  app/gui/view/component-browser/src/lib.rs
  app/gui/view/documentation/Cargo.toml
  app/gui/view/documentation/src/lib.rs
  app/gui/view/examples/component-list-panel-view/src/lib.rs
  lib/rust/ensogl/app/theme/hardcoded/src/lib.rs
  lib/rust/ensogl/component/breadcrumbs/Cargo.toml
  lib/rust/ensogl/component/breadcrumbs/src/entry.rs
  lib/rust/ensogl/component/breadcrumbs/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#7372 Documentation panel redesign
  Cargo.lock
  app/gui/suggestion-database/src/documentation_ir.rs
  app/gui/suggestion-database/src/mock.rs
  app/gui/view/documentation/assets/icon-methods.svg
  app/gui/view/documentation/assets/icon-type.svg
  app/gui/view/documentation/assets/styles.css
  app/gui/view/documentation/src/html.rs
  app/gui/view/documentation/src/lib.rs
  app/gui/view/examples/documentation/src/lib.rs
  lib/rust/ensogl/app/theme/hardcoded/src/lib.rs
  lib/rust/ensogl/component/breadcrumbs/src/lib.rs
  lib/rust/parser/doc-parser/Cargo.toml
  lib/rust/parser/doc-parser/src/doc_sections.rs
  lib/rust/parser/doc-parser/src/lib.rs
  lib/rust/parser/doc-parser/src/main.rs
Labels: CI: Ready to merge, CI: No changelog needed

#7593 Fix for empty column on replace and out of memory catching for join and tab
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Column_Naming_Helper.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Excel_Reader.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Java_Problems.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Unique_Name_Strategy.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Problems.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#7499 Fix validation regexes
  app/ide-desktop/lib/dashboard/package.json
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/resetPassword.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/changePasswordModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/validation.ts
  app/ide-desktop/lib/dashboard/test.ts
  app/ide-desktop/package-lock.json
  app/ide-desktop/package.json
Labels: CI: Ready to merge, CI: No changelog needed

#7519 Ability to invoke all std benchmarks via jmh
  build.sbt
  distribution/lib/Standard/Test/0.0.0-dev/src/Bench.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Main.enso
  lib/scala/bench-processor/src/main/java/org/enso/benchmarks/BenchConfig.java
  lib/scala/bench-processor/src/main/java/org/enso/benchmarks/PhaseConfig.java
  lib/scala/bench-processor/src/main/java/org/enso/benchmarks/processor/BenchProcessor.java
  test/Benchmarks/src/Collections.enso
  test/Benchmarks/src/Column_Numeric.enso
  test/Benchmarks/src/Equality.enso
  test/Benchmarks/src/Json_Bench.enso
  test/Benchmarks/src/Main.enso
  test/Benchmarks/src/Natural_Order_Sort.enso
  test/Benchmarks/src/Number_Parse.enso
  test/Benchmarks/src/Numeric.enso
  test/Benchmarks/src/Statistics/Count_Min_Max.enso
  test/Benchmarks/src/Statistics/Main.enso
  test/Benchmarks/src/Sum.enso
  test/Benchmarks/src/Table/Aggregate.enso
  test/Benchmarks/src/Table/Cross_Tab.enso
  test/Benchmarks/src/Table/Main.enso
  test/Benchmarks/src/Table/Sorting.enso
  test/Benchmarks/src/Text/Build.enso
  test/Benchmarks/src/Text/Compare.enso
  test/Benchmarks/src/Text/Contains.enso
  test/Benchmarks/src/Text/Main.enso
  test/Benchmarks/src/Text/Pretty.enso
  test/Benchmarks/src/Text/Reverse.enso
  test/Benchmarks/src/Time/Main.enso
  test/Benchmarks/src/Time/Work_Days.enso
  test/Benchmarks/src/Vector/Array_Proxy_Bench.enso
  test/Benchmarks/src/Vector/Distinct.enso
  test/Benchmarks/src/Vector/Main.enso
  test/Benchmarks/src/Vector/Operations.enso
  test/Benchmarks/src/Vector/Sort.enso
Labels: CI: No changelog needed

#7594 Fix the panic on resize to tiny window dimensions
  app/gui/view/graph-editor/src/component/visualization/container.rs
Labels: CI: No changelog needed

#7541 Pending nodes
  app/gui/src/controller/graph.rs
  app/gui/src/model/execution_context.rs
  app/gui/src/presenter/graph.rs
  app/gui/src/presenter/graph/state.rs
  app/gui/view/examples/interface/src/lib.rs
  app/gui/view/graph-editor/src/component.rs
  app/gui/view/graph-editor/src/component/edge/layout.rs
  app/gui/view/graph-editor/src/component/edge/render.rs
  app/gui/view/graph-editor/src/component/node.rs
  app/gui/view/graph-editor/src/component/node/input/area.rs
  app/gui/view/graph-editor/src/component/node/input/widget.rs
  app/gui/view/graph-editor/src/component/node/input/widget/label.rs
  app/gui/view/graph-editor/src/component/node/input/widget/method.rs
  app/gui/view/graph-editor/src/component/node/profiling.rs
  app/gui/view/graph-editor/src/component/profiling.rs
  app/gui/view/graph-editor/src/lib.rs
  app/gui/view/graph-editor/src/profiling.rs
  lib/rust/ensogl/app/theme/hardcoded/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#7516 Use Enso Font
  .idea/runConfigurations/clippy-enso-font-family-wasm-linux.xml
  .idea/runConfigurations/clippy-enso-font-family-wasm-macos.xml
  .idea/runConfigurations/clippy-enso-font-family-wasm-windows.xml
  .idea/runConfigurations/clippy-enso-font-family-wasm.xml
  .idea/runConfigurations/doc-test-enso-font-family-native.xml
  .idea/runConfigurations/test-enso-font-family-native.xml
  Cargo.lock
  app/gui/view/documentation/assets/styles.css
  app/gui/view/documentation/src/html.rs
  app/gui/view/graph-editor/src/builtin/visualization/native/error.rs
  app/gui/view/graph-editor/src/component/node/input/widget/label.rs
  app/ide-desktop/lib/content/esbuild-config.ts
  app/ide-desktop/lib/content/src/docsStyle.css
  app/ide-desktop/lib/content/src/docsStyle.less
  app/ide-desktop/lib/content/src/index.html
  app/ide-desktop/lib/content/src/serviceWorkerConstants.js
  build/build/Cargo.toml
  build/build/src/ide/web.rs
  build/build/src/ide/web/fonts.rs
  build/ci_utils/Cargo.toml
  build/ci_utils/src/archive.rs
  build/ci_utils/src/archive/tar.rs
  lib/rust/enso-font/Cargo.toml
  lib/rust/enso-font/src/lib.rs
  lib/rust/ensogl/app/theme/hardcoded/src/lib.rs
  lib/rust/ensogl/component/dynamic-assets/src/fonts.rs
  lib/rust/ensogl/component/text/Cargo.toml
  lib/rust/ensogl/component/text/src/buffer.rs
  lib/rust/ensogl/component/text/src/component/line.rs
  lib/rust/ensogl/component/text/src/component/text.rs
  lib/rust/ensogl/component/text/src/font.rs
  lib/rust/ensogl/component/text/src/font/embedded/Cargo.toml
  lib/rust/ensogl/component/text/src/font/embedded/build.rs
  lib/rust/ensogl/component/text/src/font/embedded/src/lib.rs
  lib/rust/ensogl/component/text/src/font/msdf/Cargo.toml
  lib/rust/ensogl/component/text/src/font/msdf/src/lib.rs
  lib/rust/ensogl/examples/text-area/src/lib.rs
  lib/rust/font/Cargo.toml
  lib/rust/font/src/lib.rs
  lib/rust/parser/doc-parser/src/doc_sections.rs
  lib/rust/parser/doc-parser/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#7537 Fix z-index of top bar
  app/ide-desktop/lib/content/src/index.html
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetsTable.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/autocomplete.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/changePasswordModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/chat.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/managePermissionsModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/pageSwitcher.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/topBar.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/userMenu.tsx
  app/ide-desktop/lib/dashboard/src/tailwind.css
  app/ide-desktop/lib/dashboard/tailwind.config.ts
Labels: CI: Ready to merge, CI: No changelog needed

#7539 Text blocks in Enso grammar for TextMate based editor
  tools/enso4igv/pom.xml
  tools/enso4igv/src/main/resources/org/enso/tools/enso4igv/enso.tmLanguage.json
Labels: CI: Ready to merge, CI: No changelog needed

#7602 Disable shortcuts in modals
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/confirmDeleteModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/managePermissionsModal.tsx
Labels: CI: Ready to merge, CI: No changelog needed

#7578 Change context menu styling for non-macOS platforms
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/contextMenu.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/keyboardShortcut.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/shortcuts.tsx
  app/ide-desktop/lib/dashboard/tailwind.config.ts
Labels: CI: Ready to merge, CI: No changelog needed

#7586 Category switcher
  app/ide-desktop/lib/assets/home2.svg
  app/ide-desktop/lib/assets/recent.svg
  app/ide-desktop/lib/assets/root.svg
  app/ide-desktop/lib/assets/temp.svg
  app/ide-desktop/lib/assets/trash2.svg
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/column.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetsTable.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/button.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/categorySwitcher.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/driveView.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/pageSwitcher.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/table.tsx
  app/ide-desktop/lib/dashboard/tailwind.config.ts
Labels: CI: Ready to merge, CI: No changelog needed

#7595 Editing the node is not changing the placeholders and widgets
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/MethodCallsCache.java
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeErrorsTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#7540 Sort assets
  app/ide-desktop/lib/assets/sort_ascending.svg
  app/ide-desktop/lib/assets/sort_descending.svg
  app/ide-desktop/lib/client/src/file-associations.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/array.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/assetTreeNode.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/backend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/column.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetRow.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetsTable.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/directoryNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/driveView.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/fileNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/secretNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/table.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/tableRow.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/events/assetEvent.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/events/assetListEvent.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/sorting.ts
Labels: CI: Ready to merge, CI: No changelog needed

#7611 Eliminate compile time dependency on runtime-language-epb
  build.sbt
  engine/polyglot-api/src/main/java/org/enso/polyglot/ForeignLanguage.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbLanguage.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbParser.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/node/ForeignEvalNode.java
  engine/runtime-with-polyglot/src/test/java/org/enso/interpreter/test/ForeignMethodInvokeTest.java
  engine/runtime/src/main/java/org/enso/interpreter/EnsoLanguage.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/generic/ReadArrayElementNode.java
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IrToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/GenerateMethodBodies.scala
  engine/runtime/src/test/java/org/enso/interpreter/test/TestBase.java
Labels: CI: No changelog needed

#7581 New user menu
  app/ide-desktop/lib/assets/change_password.svg
  app/ide-desktop/lib/assets/sign_in.svg
  app/ide-desktop/lib/assets/sign_out.svg
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetsTable.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/changePasswordModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/globalContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/menuEntry.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/userMenu.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/shortcuts.tsx
  app/ide-desktop/lib/dashboard/tailwind.config.ts
Labels: CI: Ready to merge, CI: No changelog needed

#7278 Limit deferred assets future execution
  lib/rust/ensogl/pack/src/assets.rs
Labels: CI: No changelog needed

#7613 Notification about the project rename action
  CHANGELOG.md
  app/gui/controller/engine-protocol/src/language_server/types.rs
  app/gui/src/model/project.rs
  app/gui/src/model/project/synchronized.rs
  app/gui/src/presenter/project.rs
  app/gui/view/graph-editor/src/component/node/input/widget.rs
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonRpc.scala
  engine/language-server/src/main/scala/org/enso/languageserver/refactoring/RefactoringApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/refactoring/RefactoringProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/refactoring/RenameProjectHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/VisualizationConfiguration.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/LibrariesTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/RefactoringTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/RenameProjectCmd.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeSuggestionUpdatesTest.scala
  engine/runtime/src/main/java/org/enso/compiler/ImportExportCache.java
  engine/runtime/src/main/java/org/enso/compiler/ModuleCache.java
  engine/runtime/src/main/java/org/enso/compiler/SuggestionsCache.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/Imports.scala
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/DefaultPackageRepository.scala
  lib/scala/library-manager-test/src/test/scala/org/enso/librarymanager/published/repository/LibraryDownloadTest.scala
  lib/scala/library-manager-test/src/test/scala/org/enso/libraryupload/LibraryUploadTest.scala
  lib/scala/pkg/src/main/scala/org/enso/pkg/Package.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/repository/ProjectFileRepository.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/runner/Project.scala
Labels: CI: Ready to merge

#7625 Update the Enso grammar in the VS Code extension
  tools/enso4igv/src/main/resources/org/enso/tools/enso4igv/enso.tmLanguage.json
Labels: CI: Ready to merge, CI: No changelog needed

#7596 Rework `ide-desktop` CI
  app/ide-desktop/package.json
  build/cli/src/lib.rs
Labels: CI: No changelog needed

#7631 Remove tokio-tar.
  Cargo.lock
  build/ci_utils/Cargo.toml
  build/ci_utils/src/archive/tar.rs
  build/ci_utils/src/fs/wrappers/tokio.rs
  lib/rust/ensogl/component/text/src/font.rs
Labels: CI: No changelog needed

#7597 Add std-libs benchmarks GH workflow
  .github/workflows/engine-benchmark.yml
  .github/workflows/std-libs-benchmark.yml
  build.sbt
  build/build/paths.yaml
  build/build/src/ci_gen.rs
  build/build/src/engine.rs
  build/build/src/engine/context.rs
  lib/scala/bench-processor/src/main/java/org/enso/benchmarks/processor/BenchProcessor.java
  test/Benchmarks/src/Collections.enso
  test/Benchmarks/src/Column_Numeric.enso
  test/Benchmarks/src/Natural_Order_Sort.enso
  test/Benchmarks/src/Number_Parse.enso
  test/Benchmarks/src/Table/Sorting.enso
  test/Benchmarks/src/Text/Compare.enso
  test/Benchmarks/src/Text/Contains.enso
  test/Benchmarks/src/Time/Work_Days.enso
  test/Benchmarks/src/Vector/Array_Proxy_Bench.enso
  test/Benchmarks/src/Vector/Operations.enso
  test/Benchmarks/src/Vector/Sort.enso
Labels: CI: No changelog needed, -ci

#7632 Display only static methods when creating new node without self-argument
  app/gui/src/controller/searcher.rs
Labels: CI: Ready to merge, CI: No changelog needed

#7646 Log project manager version on startup
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/ProjectManager.scala
  lib/scala/version-output/src/main/scala/org/enso/version/VersionDescription.scala
Labels: CI: Ready to merge, CI: No changelog needed

#7620 Increase visualization offset to improve ease of creating a connection.
  app/gui/view/graph-editor/src/component/node.rs
Labels: CI: Ready to merge, CI: No changelog needed

#7629 More descriptive function information
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/ReplTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/Atom.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/AtomConstructor.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/Function.java
  engine/runtime/src/test/java/org/enso/interpreter/test/SignatureTest.java
  test/Tests/src/Semantic/Error_Spec.enso
Labels: CI: Ready to merge, CI: Keep up to date, CI: No changelog needed

#7638 Handle writing to a relative file
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/Existing_File_Behavior.enso
  test/Tests/src/System/File_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#7644 Add double-arrow cursor for visualization resizing
  app/gui/view/graph-editor/src/component/visualization/container.rs
  lib/rust/ensogl/core/src/gui/cursor.rs
Labels: CI: Ready to merge, CI: No changelog needed

#7619 Replace old breadcrumb implementation in the top bar with new breadcrumb component.
  Cargo.lock
  app/gui/src/controller/searcher.rs
  app/gui/src/presenter/graph/call_stack.rs
  app/gui/view/documentation/src/lib.rs
  app/gui/view/examples/interface/src/lib.rs
  app/gui/view/examples/project-view-top-bar/src/lib.rs
  app/gui/view/project-view-top-bar/src/breadcrumbs.rs
  app/gui/view/project-view-top-bar/src/breadcrumbs/breadcrumb.rs
  app/gui/view/project-view-top-bar/src/lib.rs
  app/gui/view/src/project.rs
  lib/rust/ensogl/app/theme/hardcoded/src/lib.rs
  lib/rust/ensogl/component/Cargo.toml
  lib/rust/ensogl/component/breadcrumbs/src/entry.rs
  lib/rust/ensogl/component/breadcrumbs/src/lib.rs
  lib/rust/ensogl/component/src/lib.rs
  lib/rust/ensogl/core/src/application.rs
Labels: CI: Ready to merge, CI: No changelog needed

#7651 Turn abnormal CompilerError into regular Panic
  engine/runtime/src/main/java/org/enso/interpreter/node/MethodRootNode.java
  engine/runtime/src/test/java/org/enso/compiler/ExecCompilerTest.java
Labels: CI: No changelog needed

#7606 Properly hide "delete all" when no items are selected
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetRow.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetsTable.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/events/assetListEvent.ts
Labels: CI: Ready to merge, CI: No changelog needed

#7628 Fix "manage permissions" modal losing focus
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/managePermissionsModal.tsx
Labels: CI: Ready to merge, CI: No changelog needed

#6774 Allow configuring Project Manager server host and port
  app/ide-desktop/lib/client/electron-builder-config.ts
  app/ide-desktop/lib/client/src/bin/project-manager.ts
  app/ide-desktop/lib/client/src/config.ts
  app/ide-desktop/lib/client/src/index.ts
  app/ide-desktop/lib/content/src/index.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/auth.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/components/app.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/editor.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/localBackend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/projectManager.ts
  app/ide-desktop/lib/dashboard/src/index.tsx
  app/ide-desktop/lib/types/globals.d.ts
  lib/scala/project-manager/src/main/resources/application.conf
Labels: CI: Ready to merge, CI: No changelog needed

#7617 Special support for Python Date/Time/Zone interop
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Zone.enso
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/node/ForeignEvalNode.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/node/ForeignFunctionCallNode.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/node/JsForeignNode.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/node/PyForeignNode.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/node/RForeignNode.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/runtime/ForeignParsingException.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoTimeZone.java
  test/Tests/src/Data/Time/Date_Time_Spec.enso
Labels: CI: No changelog needed

#7640 Fix dev version check
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/protocol/ProjectManagementApi.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/ProjectServiceFailureMapper.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectServiceFailure.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/versionmanagement/RuntimeVersionManagerErrorRecoverySyntax.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectCreateDefaultToLatestSpec.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/CurrentVersion.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/ComponentsException.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/RuntimeVersionManager.scala
Labels: CI: Ready to merge, CI: No changelog needed

#7584 Fix restoring cloud projects that have been closed (e.g. from inactivity)
  app/ide-desktop/lib/client/watch.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/backend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetsTable.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/driveView.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/editor.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectIcon.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/events/assetEvent.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/remoteBackend.ts
Labels: CI: Ready to merge, CI: No changelog needed

#7657 Avoid _ after .
  engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/test/java/org/enso/compiler/ErrorCompilerTest.java
  engine/runtime/src/test/java/org/enso/compiler/ExecCompilerTest.java
Labels: CI: No changelog needed

#7666 Removing references to Builtins from Compiler
  engine/runtime/src/main/java/org/enso/compiler/context/CompilerContext.java
  engine/runtime/src/main/java/org/enso/interpreter/EnsoLanguage.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/InlineContext.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/ModuleContext.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/AmbiguousImportsAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/BindingAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DemandAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/Imports.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/LambdaShorthandToLambda.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/OperatorToFunction.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/SectionsToBinOp.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/lint/ModuleNameConflicts.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/lint/UnusedBindings.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/optimise/ApplicationSaturation.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/optimise/LambdaConsolidate.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/FullyQualifiedNames.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/GlobalNames.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/IgnoredBindings.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/Patterns.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/CompilerTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/BindingAnalysisTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/GlobalNamesTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/MethodDefinitionsTest.scala
Labels: CI: No changelog needed

#7658 Add `Provisioned` project state
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/backend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectIcon.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/remoteBackend.ts
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#7661 Fix unsetting saved project on close
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectIcon.tsx
Labels: CI: Ready to merge, CI: No changelog needed

#7660 Disable opening projects that are already opened by other users
  app/ide-desktop/eslint.config.js
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/backend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetRow.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetsTable.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/managePermissionsModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectIcon.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/userPermissions.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/localBackend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/remoteBackend.ts
  app/ide-desktop/lib/dashboard/watch.ts
Labels: CI: Ready to merge, CI: No changelog needed

#7668 Add more debugging info to a failed apply edit
  lib/scala/text-buffer/src/main/scala/org/enso/text/editing/TextEditValidator.scala
  lib/scala/text-buffer/src/test/scala/org/enso/text/editing/EditorOpsSpec.scala
  lib/scala/text-buffer/src/test/scala/org/enso/text/editing/TextEditValidatorSpec.scala
Labels: CI: Ready to merge, CI: No changelog needed

#7675 Fix "localStorage has already been declared"
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectIcon.tsx
Labels: CI: Ready to merge, CI: No changelog needed

#7500 Improve assets table display
  app/ide-desktop/debugGlobals.ts
  app/ide-desktop/lib/assets/arrow_up.svg
  app/ide-desktop/lib/assets/close.svg
  app/ide-desktop/lib/common/src/detect.ts
  app/ide-desktop/lib/content/esbuild-config.ts
  app/ide-desktop/lib/content/src/index.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/cognito.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/input.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/login.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/providers/auth.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/components/app.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/array.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/backend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/column.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetRow.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetsTable.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/backendSwitcher.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/button.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/categorySwitcher.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/contextMenus.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/dashboard.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/directoryNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/driveBar.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/driveView.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/editor.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/fileNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/managePermissionsModal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/menuEntry.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/modal.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/permissionSelector.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectIcon.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/secretNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/table.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/tableRow.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/templates.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/topBar.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/userBar.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/userMenu.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/events/assetEvent.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/events/assetListEvent.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/indent.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/remoteBackend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/shortcuts.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/style.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/index.tsx
  app/ide-desktop/lib/dashboard/src/tailwind.css
  app/ide-desktop/lib/dashboard/tailwind.config.ts
Labels: CI: Ready to merge, CI: No changelog needed

#7684 Fix "opened by" being missing for new projects
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/backend.ts
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetsTable.tsx
Labels: CI: Ready to merge, CI: No changelog needed

#7686 Fix context menu option visibility
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectIcon.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectNameColumn.tsx
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#7678 Support for Python libraries like numpy
  CHANGELOG.md
  docs/polyglot/README.md
  docs/polyglot/polyglot-bindings.md
  docs/polyglot/python.md
  engine/runner/src/main/scala/org/enso/runner/ContextFactory.scala
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/node/ForeignEvalNode.java
  test/Tests/src/System/Process_Spec.enso
Labels: -compiler

#7673 Change folder icon to arrow on hover
  app/ide-desktop/lib/assets/arrow_right_small.svg
  app/ide-desktop/lib/dashboard/src/authentication/src/authentication/components/svgMask.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/assetRow.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/directoryNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/userBar.tsx
  app/ide-desktop/lib/dashboard/src/authentication/src/hooks.tsx
Labels: CI: Ready to merge, CI: No changelog needed

#7637 Add `value_type` to `Column.from_vector` and `expected_value_type` to `Column.map` and `Column.zip`
  CHANGELOG.md
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Type/Enso_Types.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Type/Value_Type.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Type/Value_Type_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  std-bits/table/src/main/java/org/enso/table/data/column/builder/BoolBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/DateBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/DateTimeBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/DoubleBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/LongBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/LongBuilderChecked.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/LongBuilderUnchecked.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/StorageTypeMismatchException.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/StringBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/TimeOfDayBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/TypedBuilderImpl.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/StringStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/type/IntegerType.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/type/TextType.java
  std-bits/table/src/main/java/org/enso/table/data/table/Column.java
  std-bits/table/src/main/java/org/enso/table/error/ValueTypeMismatchException.java
  test/Benchmarks/src/Main.enso
  test/Benchmarks/src/Table/Arithmetic.enso
  test/Benchmarks/src/Table/Column_From_Vector.enso
  test/Exploratory_Benchmarks/src/Table/Enso_Callback.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Map_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Missing_Values_Spec.enso
  test/Table_Tests/src/Formatting/Data_Formatter_Spec.enso
  test/Table_Tests/src/Helpers/Value_Type_Spec.enso
  test/Table_Tests/src/In_Memory/Column_Spec.enso
Labels: CI: Ready to merge, CI: Clean build required

#7699 When opening the project for a second time suggestion database is not sent
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistry.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/command/InvalidateModulesIndexCommand.java
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/CommandFactory.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/InvalidateModulesIndexCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/JobControlPlane.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/JobExecutionEngine.scala
  engine/runtime-with-instruments/src/test/scala/org/enso/interpreter/test/instrument/RuntimeSuggestionUpdatesTest.scala
  engine/runtime/src/main/scala/org/enso/compiler/SerializationManager.scala
  lib/scala/json-rpc-server/src/main/scala/org/enso/jsonrpc/MessageHandler.scala
Labels: CI: Ready to merge, CI: No changelog needed

#7615 Add simple parts of Table.take and Table.drop functions to Database table
  CHANGELOG.md
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Take_Drop_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Column_Naming_Helper.enso
  test/Table_Tests/src/Common_Table_Operations/Add_Row_Number_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Main.enso
  test/Table_Tests/src/Common_Table_Operations/Take_Drop_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Temp_Column_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Database/Redshift_Spec.enso
  test/Table_Tests/src/Database/SQLite_Spec.enso
  test/Table_Tests/src/Util.enso
Labels: CI: Ready to merge, CI: Clean build required

#7649 fix dst test failure
  test/Tests/src/Data/Time/Date_Time_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required
