Repository enso-org/enso, pull requests merged in 2024-09, with the labels that each got.

#10944 Add today, now and time to expressions
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Extensions/Column_Vector_Extensions.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Main.enso
  std-bits/table/src/main/java/org/enso/table/expressions/ExpressionVisitorImpl.java
Labels: CI: No changelog needed, CI: Clean build required

#10926 Improve the Signup experience
  app/dashboard/src/components/AriaComponents/Alert/Alert.tsx
  app/dashboard/src/components/Link.tsx
  app/dashboard/src/components/Result.tsx
  app/dashboard/src/components/Stepper/Stepper.tsx
  app/dashboard/src/components/Stepper/useStepperState.ts
  app/dashboard/src/hooks/mountHooks.ts
  app/dashboard/src/pages/authentication/AuthenticationPage.tsx
  app/dashboard/src/pages/authentication/ConfirmRegistration.tsx
  app/dashboard/src/pages/authentication/Login.tsx
  app/dashboard/src/pages/authentication/Registration.tsx
  app/dashboard/src/providers/AuthProvider.tsx
  app/ide-desktop/common/src/text/english.json
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#10940 text format selection bug
  app/gui2/src/components/visualizations/TableVisualization.vue
  app/gui2/src/components/widgets/AgGridTableView.vue
Labels: CI: No changelog needed

#10937 Fix component list scrolling
  app/gui2/src/components/ComponentBrowser/ComponentList.vue
Labels: p-highest, CI: Ready to merge, CI: No changelog needed, --bug, -gui

#10950 Ignore port updates on removed nodes
  app/gui2/src/stores/graph/index.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui

#10953 Disable record button temporarily
  app/gui2/e2e/componentBrowser.spec.ts
  app/gui2/src/components/CircularMenu.vue
  app/gui2/src/components/ToggleIcon.vue
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui

#10907 Remove optimistic query hooks
  app/dashboard/e2e/organizationSettings.spec.ts
  app/dashboard/src/components/dashboard/AssetRow.tsx
  app/dashboard/src/components/dashboard/column/LabelsColumn.tsx
  app/dashboard/src/hooks/backendHooks.ts
  app/dashboard/src/layouts/AssetProperties.tsx
  app/dashboard/src/layouts/AssetSearchBar.tsx
  app/dashboard/src/layouts/AssetsTable.tsx
  app/dashboard/src/layouts/CategorySwitcher.tsx
  app/dashboard/src/layouts/Labels.tsx
  app/dashboard/src/layouts/Settings.tsx
  app/dashboard/src/layouts/Settings/ActivityLogSettingsSection.tsx
  app/dashboard/src/layouts/Settings/MembersTable.tsx
  app/dashboard/src/layouts/Settings/OrganizationProfilePictureInput.tsx
  app/dashboard/src/layouts/Settings/ProfilePictureInput.tsx
  app/dashboard/src/layouts/Settings/UserGroupRow.tsx
  app/dashboard/src/layouts/Settings/UserGroupUserRow.tsx
  app/dashboard/src/layouts/Settings/UserGroupsSettingsSection.tsx
  app/dashboard/src/modals/ManageLabelsModal.tsx
  app/dashboard/src/modals/NewLabelModal.tsx
  app/ide-desktop/common/src/utilities/data/array.ts
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#10963 Couple of small fixes for vizzes.
  app/gui2/src/components/visualizations/GeoMapVisualization.vue
  app/gui2/src/components/visualizations/TableVisualization.vue
Labels: CI: Ready to merge, CI: No changelog needed

#10964 Run Enso Cloud tests on the CI
  .github/workflows/extra-nightly-tests.yml
  .vscode/settings.json
  build/build/src/ci_gen.rs
  build/build/src/ci_gen/job.rs
  build/build/src/cloud_tests/env.rs
  build/build/src/cloud_tests/mod.rs
  build/build/src/enso.rs
  build/build/src/lib.rs
  test/Base_Tests/src/System/File_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10960 Re-enable IR caching in Language Server
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala
Labels: CI: No changelog needed

#10967 Reduce akka logs in PM and LS
  build.sbt
  distribution/engine/THIRD-PARTY/NOTICE
  distribution/engine/THIRD-PARTY/com.typesafe.akka.akka-slf4j_2.13-2.6.20/NOTICES
  distribution/project-manager/THIRD-PARTY/NOTICE
  distribution/project-manager/THIRD-PARTY/com.typesafe.akka.akka-slf4j_2.13-2.6.20/NOTICES
  engine/language-server/src/main/resources/application.conf
  lib/scala/project-manager/src/main/resources/application.conf
  tools/legal-review/engine/com.typesafe.akka.akka-slf4j_2.13-2.6.20/copyright-keep
  tools/legal-review/engine/report-state
  tools/legal-review/project-manager/com.typesafe.akka.akka-slf4j_2.13-2.6.20/copyright-keep
  tools/legal-review/project-manager/report-state
Labels: CI: No changelog needed

#10977 Workaround missing `aws` CLI on self-hosted runners by running the Cloud tests on GH runners
  .github/workflows/extra-nightly-tests.yml
  build/build/src/ci_gen.rs
  build/build/src/ci_gen/job.rs
Labels: CI: Ready to merge, CI: No changelog needed

#10775 Adjust Refresh Interval in Assets table
  app/dashboard/e2e/api.ts
  app/dashboard/e2e/copy.spec.ts
  app/dashboard/e2e/driveView.spec.ts
  app/dashboard/src/App.tsx
  app/dashboard/src/components/AriaComponents/Dialog/DialogTrigger.tsx
  app/dashboard/src/components/AriaComponents/Dialog/types.ts
  app/dashboard/src/components/AriaComponents/Form/Form.tsx
  app/dashboard/src/components/AriaComponents/Form/components/Field.tsx
  app/dashboard/src/components/AriaComponents/Form/components/index.ts
  app/dashboard/src/components/AriaComponents/Form/components/types.ts
  app/dashboard/src/components/AriaComponents/Form/components/useField.ts
  app/dashboard/src/components/AriaComponents/Form/components/useForm.ts
  app/dashboard/src/components/AriaComponents/Form/types.ts
  app/dashboard/src/components/AriaComponents/Inputs/variants.ts
  app/dashboard/src/components/AriaComponents/Switch/Switch.tsx
  app/dashboard/src/components/AriaComponents/Switch/index.ts
  app/dashboard/src/components/AriaComponents/Tooltip/Tooltip.tsx
  app/dashboard/src/components/AriaComponents/index.ts
  app/dashboard/src/components/Devtools/EnsoDevtools.tsx
  app/dashboard/src/components/Devtools/EnsoDevtoolsProvider.tsx
  app/dashboard/src/components/Devtools/index.ts
  app/dashboard/src/components/dashboard/AssetRow.tsx
  app/dashboard/src/components/dashboard/DatalinkNameColumn.tsx
  app/dashboard/src/components/dashboard/DirectoryNameColumn.tsx
  app/dashboard/src/components/dashboard/FileNameColumn.tsx
  app/dashboard/src/components/dashboard/PermissionSelector.tsx
  app/dashboard/src/components/dashboard/ProjectNameColumn.tsx
  app/dashboard/src/components/dashboard/SecretNameColumn.tsx
  app/dashboard/src/components/dashboard/column/SharedWithColumn.tsx
  app/dashboard/src/events/assetListEvent.ts
  app/dashboard/src/hooks/intersectionHooks.ts
  app/dashboard/src/hooks/projectHooks.ts
  app/dashboard/src/hooks/syncRefHooks.ts
  app/dashboard/src/layouts/AssetsTable.tsx
  app/dashboard/src/layouts/AssetsTableContextMenu.tsx
  app/dashboard/src/layouts/DriveBar.tsx
  app/dashboard/src/layouts/StartModal.tsx
  app/dashboard/src/layouts/VersionChecker.tsx
  app/dashboard/src/modals/DuplicateAssetsModal.tsx
  app/dashboard/src/pages/dashboard/Dashboard.tsx
  app/dashboard/src/providers/EnsoDevtoolsProvider.tsx
  app/dashboard/src/providers/FeatureFlagsProvider.tsx
  app/dashboard/src/utilities/AssetTreeNode.ts
  app/ide-desktop/common/src/text/english.json
  app/ide-desktop/common/tsconfig.json
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#10906 Provide names of local variables via FramePointerAnalysis
  docs/runtime/compiler-ir.md
  engine/runtime-compiler/src/main/java/org/enso/compiler/context/ContextUtils.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/context/FramePointer.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/FrameAnalysisMeta.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/FramePointer.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/FrameVariableNames.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/PassPersistance.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/context/LocalScope.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/FramePointerAnalysis.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/graph/Graph.scala
  engine/runtime-instrument-common/src/test/scala/org/enso/compiler/test/context/ChangesetBuilderTest.scala
  engine/runtime-instrument-repl-debugger/src/main/java/org/enso/interpreter/instrument/ReplDebuggerInstrument.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/ExecCompilerTest.java
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/analyse/DataflowAnalysisTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/analyse/DemandAnalysisTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/analyse/FramePointerAnalysisTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/analyse/TailCallTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/lint/UnusedBindingsTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/optimise/LambdaConsolidateTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/resolve/SuspendedArgumentsTest.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Function.scala
  engine/runtime/src/main/java/org/enso/interpreter/EnsoLanguage.java
  engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java
  engine/runtime/src/main/java/org/enso/interpreter/node/EnsoRootNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/debug/EvalNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/scope/ReadLocalVariableNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/UnresolvedConstructor.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/AtomConstructor.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/GetFieldNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/QualifiedAccessorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/DebugLocalScope.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/TopLevelScope.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
Labels: CI: No changelog needed, CI: Clean build required

#10979 Prevent node name collisions when drag-and-dropping multiple files
  CHANGELOG.md
  app/dashboard/src/components/Devtools/EnsoDevtools.tsx
  app/dashboard/src/pages/dashboard/Dashboard.tsx
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/composables/nodeCreation.ts
Labels: CI: Ready to merge

#10975 Get ready for `python` and `js` being optional when running `test/Base_Tests`
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/RegexCompileNode.java
  test/Base_Tests/src/Data/Array_Polyglot_Spec.enso
  test/Base_Tests/src/Data/Dictionary_Spec.enso
  test/Base_Tests/src/Data/Numbers_Spec.enso
  test/Base_Tests/src/Data/Pair_Spec.enso
  test/Base_Tests/src/Data/Polyglot_Spec.enso
  test/Base_Tests/src/Data/Time/Date_Part_Spec.enso
  test/Base_Tests/src/Data/Time/Date_Spec.enso
  test/Base_Tests/src/Data/Time/Date_Time_Spec.enso
  test/Base_Tests/src/Data/Time/Duration_Spec.enso
  test/Base_Tests/src/Data/Vector_Spec.enso
  test/Base_Tests/src/Runtime/Asserts_Spec.enso
  test/Base_Tests/src/Semantic/Conversion_Spec.enso
  test/Base_Tests/src/Semantic/Equals_Spec.enso
  test/Base_Tests/src/Semantic/Error_Spec.enso
  test/Base_Tests/src/Semantic/Js_Interop_Spec.enso
  test/Base_Tests/src/Semantic/Meta_Location_Spec.enso
  test/Base_Tests/src/Semantic/Private_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10965 Fix small-plus alignment when visualization is open
  app/gui2/src/components/GraphEditor/GraphNode.vue
Labels: CI: No changelog needed

#10980 Default Project, Templates and Docs
  app/gui2/src/components/DocumentationPanel/DocsExamples.vue
  distribution/lib/Standard/AWS/0.0.0-dev/src/AWS_Credential.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Decimal.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Ordering.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Text_Cleanse.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Zone.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Data_Link.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/IO.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Postgres.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Postgres_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/SQLite_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Common/Row_Number_Helpers.enso
  distribution/lib/Standard/Examples/0.0.0-dev/data/welcome.csv
  distribution/lib/Standard/Examples/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/SQLServer_Connection.enso
  distribution/lib/Standard/Searcher/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Snowflake_Connection.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Workbook.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Simple_Expression.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  distribution/lib/Standard/Tableau/0.0.0-dev/src/Hyper_Table.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Faker.enso
  lib/scala/pkg/src/main/resources/default/src/Main.enso
  test/Benchmarks/src/Natural_Order_Sort.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10844 Setup Screen Improvements
  app/dashboard/e2e/actions.ts
  app/dashboard/e2e/actions/BaseActions.ts
  app/dashboard/e2e/actions/RegisterPageActions.ts
  app/dashboard/e2e/api.ts
  app/dashboard/src/App.tsx
  app/dashboard/src/components/AnimatedBackground.tsx
  app/dashboard/src/components/AriaComponents/Alert/Alert.tsx
  app/dashboard/src/components/AriaComponents/Button/Button.tsx
  app/dashboard/src/components/AriaComponents/Checkbox/Checkbox.tsx
  app/dashboard/src/components/AriaComponents/Checkbox/CheckboxContext.tsx
  app/dashboard/src/components/AriaComponents/Checkbox/CheckboxGroup.tsx
  app/dashboard/src/components/AriaComponents/Checkbox/index.ts
  app/dashboard/src/components/AriaComponents/Dialog/Dialog.tsx
  app/dashboard/src/components/AriaComponents/Dialog/Popover.tsx
  app/dashboard/src/components/AriaComponents/Form/Form.tsx
  app/dashboard/src/components/AriaComponents/Form/components/Field.tsx
  app/dashboard/src/components/AriaComponents/Form/components/index.ts
  app/dashboard/src/components/AriaComponents/Form/components/types.ts
  app/dashboard/src/components/AriaComponents/Form/components/useForm.ts
  app/dashboard/src/components/AriaComponents/Form/components/useFormContext.tsx
  app/dashboard/src/components/AriaComponents/Inputs/Input/Input.tsx
  app/dashboard/src/components/AriaComponents/Inputs/ResizableInput/ResizableContentEditableInput.tsx
  app/dashboard/src/components/AriaComponents/Inputs/Selector/Selector.tsx
  app/dashboard/src/components/AriaComponents/Inputs/Selector/SelectorOption.tsx
  app/dashboard/src/components/AriaComponents/Radio/Radio.tsx
  app/dashboard/src/components/AriaComponents/Radio/RadioGroup.tsx
  app/dashboard/src/components/AriaComponents/index.ts
  app/dashboard/src/components/AriaComponents/types.ts
  app/dashboard/src/components/Devtools/EnsoDevtools.tsx
  app/dashboard/src/components/ErrorBoundary.tsx
  app/dashboard/src/components/Paywall/PaywallAlert.tsx
  app/dashboard/src/components/Stepper/Stepper.tsx
  app/dashboard/src/components/Stepper/useStepperState.ts
  app/dashboard/src/layouts/Settings/MembersSettingsSection.tsx
  app/dashboard/src/layouts/UserBar.tsx
  app/dashboard/src/modals/AgreementsModal.tsx
  app/dashboard/src/modals/InviteUsersModal/InviteUsersForm.tsx
  app/dashboard/src/modals/InviteUsersModal/InviteUsersModal.tsx
  app/dashboard/src/modals/InviteUsersModal/index.ts
  app/dashboard/src/modals/SetOrganizationNameModal.tsx
  app/dashboard/src/modals/SetupOrganizationAfterSubscribe.tsx
  app/dashboard/src/modules/payments/components/AddPaymentMethodForm.tsx
  app/dashboard/src/modules/payments/components/PlanSelector/PlanSelector.tsx
  app/dashboard/src/modules/payments/components/PlanSelector/components/PlanSelectorDialog.tsx
  app/dashboard/src/modules/payments/components/PlanSelector/components/SubscribeButton.tsx
  app/dashboard/src/pages/authentication/Registration.tsx
  app/dashboard/src/pages/authentication/Setup/Setup.tsx
  app/dashboard/src/pages/subscribe/Subscribe/Subscribe.tsx
  app/dashboard/src/services/RemoteBackend.ts
  app/dashboard/src/tailwind.css
  app/dashboard/src/utilities/mergeRefs.ts
  app/dashboard/src/utilities/tailwindVariants.ts
  app/ide-desktop/common/src/services/Backend.ts
  app/ide-desktop/common/src/text/english.json
  app/ide-desktop/common/src/text/index.ts
  pnpm-lock.yaml
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#10954 Clear caches from the runtime hook
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/execution/ExecutionHooks.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/execution/RuntimeExecutionHooks.java
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/EditFileCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/ExecutionState.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ExecuteJob.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/UpsertVisualizationJob.scala
  engine/runtime-instrument-common/src/test/scala/org/enso/interpreter/instrument/command/SlowEditFileCmd.scala
  engine/runtime-instrument-common/src/test/scala/org/enso/interpreter/instrument/job/SlowEnsureCompiledJob.scala
Labels: CI: Ready to merge, CI: No changelog needed

#10986 Add select icon
  app/gui2/src/assets/icons.svg
Labels: CI: Ready to merge, CI: No changelog needed

#10900 Move component browser help
  CHANGELOG.md
  app/gui2/e2e/componentBrowser.spec.ts
  app/gui2/e2e/locate.ts
  app/gui2/e2e/undoRedo.spec.ts
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/components/ComponentDocumentation.vue
  app/gui2/src/components/DockPanel.vue
  app/gui2/src/components/DocumentationEditor.vue
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/composables/navigator.ts
  app/gui2/src/stores/settings.ts
  app/gui2/src/util/autoBlur.ts
  app/gui2/src/util/reactivity.ts
  app/gui2/src/views/ProjectView.vue
  app/gui2/stories/ComponentBrowser.story.vue
Labels: CI: Ready to merge, x-new-feature, -gui

#10959 Wip/mk/scatter plot visual improvements
  app/gui2/src/components/visualizations/ScatterplotVisualization.vue
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Scatter_Plot.enso
  test/Visualization_Tests/src/Scatter_Plot_Spec.enso
Labels: CI: No changelog needed

#10997 Update welcome.csv
  distribution/lib/Standard/Examples/0.0.0-dev/data/welcome.csv
Labels: CI: Ready to merge, CI: No changelog needed

#10957 only show filter/sort node button if node is a table
  app/gui2/src/components/TableVizToolbar.vue
  app/gui2/src/components/visualizations/TableVisualization.vue
Labels: CI: Ready to merge, CI: No changelog needed

#10929 Fix permissions for Asset Panel for Team-owned assets
  app/dashboard/src/components/AriaComponents/Inputs/Dropdown/Dropdown.tsx
  app/dashboard/src/components/JSONSchemaInput.tsx
  app/dashboard/src/components/dashboard/DatalinkInput.tsx
  app/dashboard/src/layouts/AssetProperties.tsx
  app/dashboard/src/layouts/Settings/ActivityLogSettingsSection.tsx
  app/dashboard/src/modals/UpsertDatalinkModal.tsx
  app/ide-desktop/common/src/text/english.json
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#10991 Remove module that was causing failures for enterprise edition of GraalVM
  build.sbt
Labels: CI: Ready to merge, CI: No changelog needed

#10992 Mark cloud as beta
  app/dashboard/src/components/AriaComponents/Text/Text.tsx
  app/dashboard/src/components/Badge/Badge.tsx
  app/dashboard/src/components/Badge/index.ts
  app/dashboard/src/layouts/CategorySwitcher.tsx
  app/dashboard/src/pages/dashboard/Dashboard.tsx
  app/dashboard/src/tailwind.css
  app/dashboard/tailwind.config.js
  app/ide-desktop/common/src/text/english.json
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#10924 Settings improvements
  app/.vscode/launch.json
  app/dashboard/e2e/organizationSettings.spec.ts
  app/dashboard/src/components/AriaComponents/Alert/Alert.tsx
  app/dashboard/src/components/AriaComponents/Button/CloseButton.tsx
  app/dashboard/src/components/AriaComponents/Tooltip/Tooltip.tsx
  app/dashboard/src/components/Devtools/EnsoDevtools.tsx
  app/dashboard/src/components/styled/SidebarTabButton.tsx
  app/dashboard/src/layouts/Settings/MembersSettingsSection.tsx
  app/dashboard/src/layouts/Settings/MembersTable.tsx
  app/dashboard/src/layouts/Settings/SettingsSection.tsx
  app/dashboard/src/layouts/Settings/UserGroupsSettingsSection.tsx
  app/dashboard/src/layouts/Settings/UserRow.tsx
  app/dashboard/src/layouts/Settings/settingsData.tsx
  app/dashboard/src/layouts/SettingsSidebar.tsx
  app/dashboard/src/utilities/LocalStorage.ts
  app/dashboard/tailwind.config.js
  app/ide-desktop/common/src/services/Backend.ts
  app/ide-desktop/common/src/text/english.json
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#10946 Dashboard improvements 08/26/2024
  app/dashboard/src/components/dashboard/column/columnUtils.ts
  app/dashboard/src/layouts/AssetPanel.tsx
  app/dashboard/src/layouts/AssetsTable.tsx
  app/dashboard/src/layouts/CategorySwitcher.tsx
  app/dashboard/src/pages/authentication/Setup/Setup.tsx
  app/dashboard/src/utilities/LocalStorage.ts
  app/ide-desktop/common/src/text/english.json
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#10990 Do not crash on empty main function body.
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/composables/navigator.ts
  app/gui2/src/providers/index.ts
  app/gui2/src/stores/graph/graphDatabase.ts
  app/gui2/src/stores/graph/index.ts
  app/gui2/src/util/database/reactiveDb.ts
  app/gui2/src/util/reactivity.ts
  app/ydoc-shared/src/ast/parse.ts
  app/ydoc-shared/src/ast/tree.ts
Labels: CI: Ready to merge, CI: No changelog needed

#11006 Add Not Paragraph icon
  app/gui2/src/assets/icons.svg
Labels: CI: Ready to merge, CI: No changelog needed

#10911 Upgrade SQLite to 3.46
  CHANGELOG.md
  build.sbt
  distribution/lib/Standard/Database/0.0.0-dev/THIRD-PARTY/NOTICE
  distribution/lib/Standard/Database/0.0.0-dev/THIRD-PARTY/licenses/MIT
  distribution/lib/Standard/Database/0.0.0-dev/THIRD-PARTY/org.slf4j.slf4j-api-1.7.36/NOTICES
  distribution/lib/Standard/Database/0.0.0-dev/THIRD-PARTY/org.xerial.sqlite-jdbc-3.46.1.0/LICENSE
  distribution/lib/Standard/Database/0.0.0-dev/THIRD-PARTY/org.xerial.sqlite-jdbc-3.46.1.0/LICENSE.zentus
  distribution/lib/Standard/Database/0.0.0-dev/THIRD-PARTY/org.xerial.sqlite-jdbc-3.46.1.0/NOTICES
  docs/distribution/licenses.md
  test/Base_Tests/src/Data/Round_Spec.enso
  test/Table_Tests/src/Database/Common/IR_Spec.enso
  tools/legal-review/Database/org.slf4j.slf4j-api-1.7.36/copyright-add
  tools/legal-review/Database/org.slf4j.slf4j-api-1.7.36/copyright-keep-context
  tools/legal-review/Database/org.xerial.sqlite-jdbc-3.46.1.0/copyright-ignore
  tools/legal-review/Database/org.xerial.sqlite-jdbc-3.46.1.0/copyright-keep
  tools/legal-review/Database/org.xerial.sqlite-jdbc-3.46.1.0/custom-license
  tools/legal-review/Database/org.xerial.sqlite-jdbc-3.46.1.0/files-keep
  tools/legal-review/Database/report-state
  tools/legal-review/Database/reviewed-licenses/MIT_License
Labels: CI: Ready to merge, CI: Clean build required

#10958 Local Dashboard fixes
  app/dashboard/package.json
  app/dashboard/src/App.tsx
  app/dashboard/src/components/AriaComponents/Dialog/Dialog.tsx
  app/dashboard/src/components/dashboard/AssetRow.tsx
  app/dashboard/src/components/dashboard/DatalinkNameColumn.tsx
  app/dashboard/src/components/dashboard/DirectoryNameColumn.tsx
  app/dashboard/src/components/dashboard/FileNameColumn.tsx
  app/dashboard/src/components/dashboard/ProjectNameColumn.tsx
  app/dashboard/src/components/dashboard/SecretNameColumn.tsx
  app/dashboard/src/globals.d.ts
  app/dashboard/src/layouts/AssetContextMenu.tsx
  app/dashboard/src/layouts/AssetsTable.tsx
  app/dashboard/src/layouts/Settings/settingsData.tsx
  app/dashboard/src/pages/dashboard/Dashboard.tsx
  app/dashboard/src/providers/ProjectsProvider.tsx
  app/dashboard/src/services/ProjectManager.ts
  app/dashboard/src/utilities/fileInfo.ts
  app/dashboard/src/utilities/nullable.ts
  app/dashboard/src/utilities/reactQuery.ts
  app/gui2/package.json
  app/gui2/src/entrypoint.ts
  app/ide-desktop/client/package.json
  app/ide-desktop/client/src/fileAssociations.ts
  app/ide-desktop/client/src/globals.d.ts
  app/ide-desktop/client/src/index.ts
  app/ide-desktop/client/src/preload.ts
  app/ide-desktop/client/src/server.ts
  app/ide-desktop/client/watch.ts
  app/ide-desktop/common/package.json
  app/ide-desktop/common/src/queryClient.ts
  app/ide-desktop/common/src/text/english.json
  app/ide-desktop/common/src/vueQuery.ts
  pnpm-lock.yaml
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#10913 Move some Drive state to zustand
  app/dashboard/src/components/SelectionBrush.tsx
  app/dashboard/src/components/dashboard/AssetRow.tsx
  app/dashboard/src/components/dashboard/DatalinkNameColumn.tsx
  app/dashboard/src/hooks/eventCallbackHooks.ts
  app/dashboard/src/hooks/syncRefHooks.ts
  app/dashboard/src/layouts/AssetPanel.tsx
  app/dashboard/src/layouts/AssetSearchBar.tsx
  app/dashboard/src/layouts/AssetsTable.tsx
  app/dashboard/src/layouts/Drive.tsx
  app/dashboard/src/layouts/DriveBar.tsx
  app/dashboard/src/providers/DriveProvider.tsx
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#10984 Add retries when fetching tableau artifacts in sbt
  .github/CODEOWNERS
  build.sbt
  project/plugins.sbt
Labels: CI: No changelog needed

#11007 Fix edge cut off in plan select at first
  app/dashboard/src/components/AriaComponents/Text/Text.tsx
  app/dashboard/src/modules/payments/components/PlanSelector/PlanSelector.tsx
  app/dashboard/src/modules/payments/components/PlanSelector/components/SubscribeButton.tsx
  app/ide-desktop/common/src/text/english.json
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#10994 Expand Templates
  app/dashboard/src/assets/ReadAndFilter.png
  app/dashboard/src/assets/aggregate.png
  app/dashboard/src/assets/blankProject.png
  app/dashboard/src/assets/book.png
  app/dashboard/src/assets/cleansing.png
  app/dashboard/src/assets/covid.png
  app/dashboard/src/assets/enso_logo_large.svg
  app/dashboard/src/assets/joining.png
  app/dashboard/src/assets/kmeans.png
  app/dashboard/src/assets/monthSales.png
  app/dashboard/src/assets/nasdaq.png
  app/dashboard/src/assets/weather.png
  app/dashboard/src/components/AriaComponents/Dialog/Dialog.tsx
  app/dashboard/src/components/AriaComponents/Text/Text.tsx
  app/dashboard/src/layouts/Samples.tsx
  app/dashboard/src/layouts/StartModal.tsx
  app/dashboard/src/layouts/WhatsNew.tsx
  app/dashboard/src/tailwind.css
  app/dashboard/tailwind.config.js
  app/ide-desktop/common/src/text/english.json
  build/build/src/engine.rs
  lib/scala/pkg/src/main/scala/org/enso/pkg/Package.scala
  lib/scala/pkg/src/main/scala/org/enso/pkg/Template.scala
Labels: CI: Ready to merge, CI: No changelog needed

#10914 Fold output of each benchmark
  build/ci_utils/src/program/command.rs
  lib/java/benchmarks-common/src/main/java/org/enso/interpreter/bench/BenchmarksRunner.java
  lib/scala/bench-processor/src/main/java/org/enso/benchmarks/processor/BenchProcessor.java
Labels: CI: No changelog needed

#11010 Add file to be signed.
  app/ide-desktop/client/tasks/signArchivesMacOs.ts
Labels: CI: Ready to merge, CI: No changelog needed

#10996 Avoid AliasAnalysis for Hello_World.enso
  engine/runtime-compiler/src/main/scala/org/enso/compiler/data/BindingsMap.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/phase/ImportResolver.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/phase/exports/ExportsResolution.scala
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/caches/HelloWorldCacheTest.java
  lib/java/test-utils/src/main/java/org/enso/test/utils/ContextUtils.java
Labels: CI: No changelog needed, CI: Clean build required

#11014 Fix initialization after reconnecting
  CHANGELOG.md
  app/gui2/src/util/net.ts
  app/gui2/src/util/net/dataServer.ts
  app/ydoc-shared/src/util/net/ReconnectingWSTransport.ts
Labels: CI: Ready to merge, --bug, -gui

#10971 Use `NUMBER(38, 12)` as default range for Snowflake `DECIMAL`s
  distribution/lib/Standard/AWS/0.0.0-dev/src/Database/Redshift/Internal/Redshift_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Dialect_Flags.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload/Operations/Internal_Core.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/Internal/SQLServer_Dialect.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Dialect.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Type_Mapping.enso
  test/Snowflake_Tests/src/Snowflake_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11017 Add Row Number starts at 0 and other tweaks.
  app/dashboard/src/layouts/Samples.tsx
  app/dashboard/src/layouts/StartModal.tsx
  app/ide-desktop/common/src/text/english.json
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Index_Sub_Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Statistics/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Random.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Widgets.enso
  test/Base_Tests/data/datalinks/example-http-format-notreal.datalink
  test/Base_Tests/src/Network/Http/Http_Data_Link_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Add_Row_Number_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Integration_Tests.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11013 Fix skipping creating a user if we don't change the default name
  app/dashboard/src/components/AriaComponents/Dialog/Dialog.tsx
  app/dashboard/src/components/AriaComponents/Dialog/variants.ts
  app/dashboard/src/modules/payments/components/PlanSelector/PlanSelector.tsx
  app/dashboard/src/pages/authentication/Setup/Setup.tsx
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#11001 Use enso paths in cloud browser
  CHANGELOG.md
  app/gui2/src/components/widgets/FileBrowserWidget.vue
Labels: CI: Ready to merge

#11015 Disable check for equals when two objects collide
  lib/java/persistance/src/main/java/org/enso/persist/PerInputImpl.java
Labels: CI: No changelog needed, CI: Clean build required

#11032 Re-compile module if IdMap is present
  engine/runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala
Labels: CI: No changelog needed

#11016 Update Vue
  app/gui2/package.json
  app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui2/src/components/WithFullscreenMode.vue
  app/gui2/src/util/reactivity.ts
  app/gui2/stories/histoire/HstWrapper.vue
  app/ide-desktop/common/package.json
  pnpm-lock.yaml
Labels: CI: No changelog needed

#11025 Log details when `to_display_text` invocation fails
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/AtomConstructorTest.java
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/ReplTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicException.java
Labels: CI: Ready to merge, CI: No changelog needed

#11036 Remove pool of FileManager actors
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManager.scala
Labels: CI: Ready to merge, CI: No changelog needed

#11030 Fix file associations on Windows + opening project bug
  CHANGELOG.md
  app/dashboard/src/pages/dashboard/Dashboard.tsx
  app/ide-desktop/client/electron-builder-config.ts
  app/ide-desktop/client/src/fileAssociations.ts
  app/ide-desktop/client/src/index.ts
Labels: CI: Ready to merge, --bug, --regression, g-electron

#11031 Add regression e2e test for empty graph
  app/gui2/e2e/emptyGraph.spec.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#11046 Better workaround for missing root folder.
  app/dashboard/src/services/LocalBackend.ts
Labels: CI: Ready to merge, CI: No changelog needed

#11041 Scatterplot fixes
  app/gui2/src/components/visualizations/ScatterplotVisualization.vue
Labels: CI: Ready to merge, CI: No changelog needed

#11037 Add a banker's rounding primitive for Snowflake
  distribution/lib/Standard/AWS/0.0.0-dev/src/Database/Redshift/Internal/Redshift_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Dialect_Flags.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/Internal/SQLServer_Dialect.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Dialect.enso
  test/Base_Tests/src/Data/Round_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
Labels: CI: No changelog needed

#11045 Add update mode to Table.Running
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Add_Row_Number.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Add_Running.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  test/Table_Tests/src/In_Memory/Table_Running_Spec.enso
Labels: CI: No changelog needed

#11029 Open a welcome dialog after user signed up
  app/dashboard/src/components/AriaComponents/Dialog/DialogTrigger.tsx
  app/dashboard/src/hooks/searchParamsStateHooks.ts
  app/dashboard/src/layouts/DriveBar.tsx
  app/dashboard/src/pages/authentication/Setup/Setup.tsx
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#11049 Fix Banker's rounding type check test failure
  test/Snowflake_Tests/src/Snowflake_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10810 Make all Common_Spec tests pass for SQLSerever
  distribution/lib/Standard/AWS/0.0.0-dev/src/Database/Redshift/Internal/Redshift_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload/Operations/Create.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload/Operations/Select_Into.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/Internal/SQLServer_Dialect.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/Internal/SQLServer_Type_Mapping.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/SQLServer_Connection.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Dialect.enso
  test/Microsoft_Tests/src/SQLServer_Spec.enso
  test/Table_Tests/src/Database/Common/Common_Spec.enso
  test/Table_Tests/src/Database/Common/Names_Length_Limits_Spec.enso
Labels: CI: No changelog needed

#11057 Fix Vector Drag
  app/gui2/src/providers/appClass.ts
Labels: p-highest, CI: Ready to merge, CI: No changelog needed, --bug, --regression, -gui

#11061 Updated feature list
  app/dashboard/src/layouts/Samples.tsx
  app/ide-desktop/common/src/text/english.json
Labels: CI: Ready to merge, CI: No changelog needed

#11060 Fix cached method pointers in expression updates
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeErrorsTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeTypesTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#11044 Handle 403 for listGroups and getOrganization
  app/dashboard/src/services/RemoteBackend.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#11058 Remove edit name on mod+click
  app/dashboard/e2e/actions/DrivePageActions.ts
  app/dashboard/e2e/editAssetName.spec.ts
  app/dashboard/src/components/MenuEntry.tsx
  app/dashboard/src/components/dashboard/DatalinkNameColumn.tsx
  app/dashboard/src/components/dashboard/DirectoryNameColumn.tsx
  app/dashboard/src/components/dashboard/FileNameColumn.tsx
  app/dashboard/src/components/dashboard/ProjectNameColumn.tsx
  app/dashboard/src/components/dashboard/SecretNameColumn.tsx
  app/dashboard/src/configurations/inputBindings.ts
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#11067 Cloud backend issues
  app/dashboard/src/components/AriaComponents/Dialog/DialogTrigger.tsx
  app/dashboard/src/components/AriaComponents/Inputs/DatePicker/DatePicker.tsx
  app/dashboard/src/components/AriaComponents/Inputs/Dropdown/Dropdown.tsx
  app/dashboard/src/components/ContextMenus.tsx
  app/dashboard/src/components/JSONSchemaInput.tsx
  app/dashboard/src/components/dashboard/AssetRow.tsx
  app/dashboard/src/components/dashboard/TheModal.tsx
  app/dashboard/src/layouts/AssetPanel.tsx
  app/dashboard/src/layouts/AssetProperties.tsx
  app/dashboard/src/layouts/AssetsTableContextMenu.tsx
  app/dashboard/src/modals/UpsertDatalinkModal.tsx
  app/dashboard/src/modals/UpsertSecretModal.tsx
  app/dashboard/src/providers/ModalProvider.tsx
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#11038 Workaround for Electron sanbox issues on Ubuntu
  app/ide-desktop/client/src/fileAssociations.ts
Labels: CI: No changelog needed

#11078 Fix invalid version of wasm-pack
  build/ci_utils/src/actions/workflow/definition.rs
Labels: CI: No changelog needed

#11079 Regenerate workflows after bumping wasm-pack
  .github/workflows/changelog.yml
  .github/workflows/engine-benchmark.yml
  .github/workflows/engine-nightly.yml
  .github/workflows/extra-nightly-tests.yml
  .github/workflows/gui-tests.yml
  .github/workflows/gui.yml
  .github/workflows/promote.yml
  .github/workflows/release.yml
  .github/workflows/scala-new.yml
  .github/workflows/std-libs-benchmark.yml
Labels: CI: Ready to merge, CI: No changelog needed

#11065 Poor man's hack to deal with stuck index generation
  project/DistributionPackage.scala
Labels: CI: No changelog needed

#11059 Dashboard fixes
  app/dashboard/e2e/actions.ts
  app/dashboard/e2e/actions/contextMenuActions.ts
  app/dashboard/e2e/api.ts
  app/dashboard/e2e/delete.spec.ts
  app/dashboard/e2e/driveView.spec.ts
  app/dashboard/e2e/labelsPanel.spec.ts
  app/dashboard/src/components/dashboard/column/SharedWithColumn.tsx
  app/dashboard/src/components/dashboard/column/columnUtils.ts
  app/dashboard/src/components/dashboard/columnHeading/SharedWithColumnHeading.tsx
  app/dashboard/src/layouts/AssetContextMenu.tsx
  app/dashboard/src/layouts/AssetsTable.tsx
  app/dashboard/src/layouts/AssetsTableContextMenu.tsx
  app/dashboard/src/layouts/GlobalContextMenu.tsx
  app/dashboard/src/layouts/UserBar.tsx
  app/dashboard/src/modals/CaptureKeyboardShortcutModal.tsx
  app/dashboard/src/modals/ConfirmDeleteModal.tsx
  app/dashboard/src/modals/NewUserGroupModal.tsx
  app/dashboard/src/modals/UpsertSecretModal.tsx
  app/dashboard/src/services/RemoteBackend.ts
  app/ide-desktop/common/src/text/english.json
  app/ide-desktop/common/src/text/index.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#11080 Follow-up for Remote backend fixes PR
  app/dashboard/src/components/JSONSchemaInput.tsx
  app/dashboard/src/layouts/AssetsTableContextMenu.tsx
  app/dashboard/src/providers/ModalProvider.tsx
  app/dashboard/src/utilities/permissions.ts
  app/eslint.config.mjs
Labels: CI: Ready to merge, CI: No changelog needed

#11091 Fix Numeric Input cooperation with Drop Down
  app/gui2/src/components/GraphEditor/widgets/WidgetNumber.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetText.vue
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui

#11089 Disable Invite button for solo/free.
  app/dashboard/src/layouts/UserBar.tsx
Labels: CI: Ready to merge, CI: No changelog needed

#11087 Fix importing conflicting files
  app/dashboard/src/layouts/AssetsTable.tsx
  app/dashboard/src/modals/DuplicateAssetsModal.tsx
Labels: CI: Ready to merge, CI: No changelog needed

#11096 Fix table dissapear after switching tabs
  app/dashboard/src/layouts/AssetsTable.tsx
Labels: CI: Ready to merge, CI: No changelog needed

#11099 Fix node removing bug, caused by spurious watchEffect effect.
  app/gui2/e2e/emptyGraph.spec.ts
  app/gui2/e2e/removingNodes.spec.ts
  app/gui2/e2e/selectingNodes.spec.ts
  app/gui2/src/util/__tests__/reactivity.test.ts
  app/gui2/src/util/reactivity.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui

#11107 Avoid dependency on org.graalvm.collections
  engine/runtime-language-arrow/src/main/java/org/enso/interpreter/arrow/runtime/ArrowCastToFixedSizeArrayFactory.java
Labels: CI: Ready to merge, CI: No changelog needed

#11103 Renaming project: fix invalid state when the name does not change
  CHANGELOG.md
  app/gui2/src/components/NavBreadcrumbs.vue
Labels: CI: Ready to merge, --bug, -gui

#11108 Allow numbers starting with dot in WidgetNumber
  CHANGELOG.md
  app/gui2/src/components/widgets/NumericInputWidget.vue
Labels: CI: Ready to merge, x-new-feature, -gui

#11110 Small tweaks from using Process.run
  distribution/lib/Standard/AWS/0.0.0-dev/src/AWS_Credential.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/Process.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Dialect_Flags.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Widgets.enso
Labels: CI: No changelog needed

#11008 Better error message for unresolved symbol
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/GlobalNames.scala
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/SymbolResolutionTest.java
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/resolve/GlobalNamesTest.scala
  test/AWS_Tests/src/Redshift_Spec.enso
Labels: CI: No changelog needed, CI: Clean build required

#11064 Stack Overflow Error not shown in GUI
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ExecuteJob.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeErrorsTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#11115 Benchmark static site generator does not include so many records
  tools/performance/engine-benchmarks/website_regen.py
Labels: CI: Ready to merge, CI: No changelog needed

#11075 Move execution environment from State to EnsoContext
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/runtime/ContextIsEnabledNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/runtime/RuntimeCurrentExecutionEnvironmentNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/runtime/RuntimeWithDisabledContextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/runtime/RuntimeWithEnabledContextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/DataflowError.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/state/State.java
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#11098 Try harder to deal with stuck index generation
  project/DistributionPackage.scala
Labels: CI: No changelog needed

#11113 More info when we fail to log AssertError
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicException.java
Labels: CI: No changelog needed

#11112 Wip/sergeigarin/fix-focus
  app/dashboard/src/components/AriaComponents/Dialog/Dialog.tsx
  app/dashboard/src/modals/InviteUsersModal/InviteUsersModal.tsx
Labels: CI: No changelog needed, --bug, g-dashboard

#11097 Fix JsonSchema input sizing
  app/dashboard/src/components/Autocomplete.tsx
  app/dashboard/src/components/JSONSchemaInput.tsx
  app/dashboard/src/layouts/AssetProperties.tsx
  app/dashboard/src/modals/ConfirmDeleteModal.tsx
  app/dashboard/src/modals/UpsertDatalinkModal.tsx
Labels: CI: No changelog needed

#11123 Update CHANGELOG after 2024.4.1
  CHANGELOG.md
Labels: CI: Ready to merge

#11124 Fix changelog
  CHANGELOG.md
Labels: CI: Ready to merge

#11055 Better error message for NULLs in primary key columns
  distribution/lib/Standard/AWS/0.0.0-dev/src/Database/Redshift/Internal/Redshift_Dialect.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/Database/Redshift/Internal/Redshift_Error_Mapper.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Dialect_Flags.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Error_Mapper.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Error_Mapper.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Error_Mapper.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload/Helpers/Error_Helpers.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/Internal/SQLServer_Dialect.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/Internal/SQLServer_Error_Mapper.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Dialect.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Error_Mapper.enso
  test/Table_Tests/src/Database/Upload_Spec.enso
Labels: CI: No changelog needed, CI: Clean build required

#11122 Don't convert type to the same type
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/BinarySelfDispatchTest.java
  engine/runtime/src/main/java/org/enso/interpreter/node/BinaryOperatorNode.java
Labels: CI: No changelog needed

#11125 More info when NPE is encountered
  std-bits/base/src/main/java/org/enso/base/polyglot/EnsoMeta.java
Labels: CI: No changelog needed

#11128 Removing serialization metadata
  engine/runner/src/main/resources/META-INF/native-image/org/enso/runner/reflect-config.json
  engine/runner/src/main/resources/META-INF/native-image/org/enso/runner/serialization-config.json
Labels: CI: No changelog needed

#11136 Improve backend error handling
  lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java
  std-bits/base/src/main/java/org/enso/base/polyglot/EnsoMeta.java
Labels: CI: Ready to merge, CI: No changelog needed

#11085 scatterplot- time series support
  app/gui2/src/components/visualizations/ScatterplotVisualization.vue
  distribution/lib/Standard/Table/0.0.0-dev/src/Value_Type.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Scatter_Plot.enso
  test/Visualization_Tests/src/Scatter_Plot_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11056 Add support for touch-based graph navigation and selection
  CHANGELOG.md
  app/dashboard/src/components/aria.tsx
  app/gui2/package.json
  app/gui2/playwright.config.ts
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/GraphNodes.vue
  app/gui2/src/components/GraphEditor/dragging.ts
  app/gui2/src/components/GraphMouse.vue
  app/gui2/src/components/ResizeHandles.vue
  app/gui2/src/components/ScrollBar.vue
  app/gui2/src/components/SelectionBrush.vue
  app/gui2/src/components/TopBar.vue
  app/gui2/src/composables/__tests__/events.test.ts
  app/gui2/src/composables/__tests__/selection.test.ts
  app/gui2/src/composables/events.ts
  app/gui2/src/composables/navigator.ts
  app/gui2/src/composables/selection.ts
  app/gui2/src/entrypoint.ts
  app/gui2/src/util/ast/__tests__/aliasAnalysis.test.ts
  app/gui2/src/util/data/vec2.ts
  app/gui2/src/util/shortcuts.ts
  app/gui2/stories/SelectionBrushWrapper.vue
  app/gui2/vite.config.ts
  app/gui2/vitest.config.ts
  app/ydoc-server-nodejs/src/main.ts
  pnpm-lock.yaml
Labels: CI: Ready to merge

#11094 Disable signing artifacts for PRs and develop
  .github/workflows/gui.yml
  app/ide-desktop/client/electron-builder-config.ts
  build/build/src/ci_gen/job.rs
  build/build/src/ide/web.rs
  build/build/src/project/ide.rs
  build/build/src/source.rs
  build/cli/src/arg.rs
  build/cli/src/arg/ide.rs
  build/cli/src/lib.rs
Labels: CI: No changelog needed

#11092 More info when critical failure occurs
  build.sbt
  build/build/src/engine/context.rs
  build/build/src/rust/parser.rs
  build/cli/src/lib.rs
  lib/rust/parser/generate-java/java/module-info.java
  lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java
Labels: CI: No changelog needed

#11138 Fix width of settings sections when only a single column is visible
  app/dashboard/src/layouts/Settings/SettingsTab.tsx
Labels: p-high, CI: Ready to merge, CI: No changelog needed, --bug, --regression, g-dashboard

#11144 Component comment fixes
  app/gui2/src/components/GraphEditor/GraphNode.vue
Labels: CI: Ready to merge, CI: No changelog needed

#11152 Change new project text
  app/dashboard/e2e/actions/DrivePageActions.ts
  app/dashboard/src/layouts/Samples.tsx
  app/ide-desktop/common/src/text/english.json
Labels: CI: Ready to merge, CI: No changelog needed

#11077 New visualization UI API
  app/gui2/e2e/locate.ts
  app/gui2/src/App.vue
  app/gui2/src/components/DropdownMenu.vue
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphEdges.vue
  app/gui2/src/components/GraphEditor/GraphVisualization.vue
  app/gui2/src/components/GraphEditor/GraphVisualization/VisualizationToolbar.vue
  app/gui2/src/components/GraphEditor/GraphVisualization/visualizationData.ts
  app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetTableEditor.vue
  app/gui2/src/components/MarkdownEditor/BlockTypeMenu.vue
  app/gui2/src/components/SelectionDropdown.vue
  app/gui2/src/components/SvgButton.vue
  app/gui2/src/components/TableVizToolbar.vue
  app/gui2/src/components/ToggleIcon.vue
  app/gui2/src/components/VisualizationContainer.vue
  app/gui2/src/components/VisualizationPanel.vue
  app/gui2/src/components/VisualizationSelector.vue
  app/gui2/src/components/WithFullscreenMode.vue
  app/gui2/src/components/shared/AgGridTableView.vue
  app/gui2/src/components/shared/LoadingSpinner.vue
  app/gui2/src/components/visualizations/GeoMapVisualization.vue
  app/gui2/src/components/visualizations/HeatmapVisualization.vue
  app/gui2/src/components/visualizations/HistogramVisualization.vue
  app/gui2/src/components/visualizations/ImageBase64Visualization.vue
  app/gui2/src/components/visualizations/JSONVisualization.vue
  app/gui2/src/components/visualizations/LoadingErrorVisualization.vue
  app/gui2/src/components/visualizations/LoadingVisualization.vue
  app/gui2/src/components/visualizations/SQLVisualization.vue
  app/gui2/src/components/visualizations/ScatterplotVisualization.vue
  app/gui2/src/components/visualizations/TableVisualization.vue
  app/gui2/src/components/visualizations/VisualizationHost.vue
  app/gui2/src/components/visualizations/WarningsVisualization.vue
  app/gui2/src/components/visualizations/tableVizToolbar.ts
  app/gui2/src/components/visualizations/toolbar.ts
  app/gui2/src/components/widgets/FileBrowserWidget.vue
  app/gui2/src/providers/interactionHandler.ts
  app/gui2/src/providers/visualizationConfig.ts
  app/gui2/src/providers/widgetRegistry/__tests__/editHandler.test.ts
  app/gui2/src/providers/widgetRegistry/editHandler.ts
  app/gui2/src/util/autoBlur.ts
  app/gui2/src/util/visualizationBuiltins.ts
  app/gui2/stories/UserDefinedVisualization.story.vue
  app/gui2/stories/setup.ts
  app/gui2/stories/story.css
  app/gui2/templates/visualization.vue
  app/gui2/vite.config.ts
Labels: CI: Ready to merge, CI: No changelog needed

#11149 Initialize Enso Terminal in a background thread
  engine/runner/src/main/java/org/enso/runner/Main.java
Labels: CI: No changelog needed

#11155 Eliminate Blanks inside of Type.Ascription
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/desugar/LambdaShorthandToLambda.scala
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/ExecCompilerTest.java
Labels: CI: No changelog needed

#11142 scatterplot- on point click
  app/gui2/src/components/visualizations/ScatterplotVisualization.vue
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Scatter_Plot.enso
  test/Visualization_Tests/src/Scatter_Plot_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11130 Fix focusing after clicking "Rename" in context menu
  app/dashboard/src/components/AriaComponents/Inputs/Input/Input.tsx
  app/dashboard/src/components/EditableSpan.tsx
  app/dashboard/src/components/dashboard/TheModal.tsx
  app/dashboard/src/hooks/autoFocusHooks.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#11160 Fix application start when YDOC_SERVER_URL is undefined
  app/gui2/env.d.ts
  app/gui2/src/entrypoint.ts
Labels: CI: Ready to merge, CI: No changelog needed

#11157 Toolbar fixes
  app/gui2/src/components/shared/AgGridTableView.vue
  app/gui2/src/components/visualizations/TableVisualization.vue
  app/gui2/src/components/visualizations/tableVizToolbar.ts
  app/gui2/src/components/visualizations/toolbar.ts
Labels: CI: Ready to merge, CI: No changelog needed

#11009 Propagate comparator warnings via Any.==
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/EqualsTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/HashCodeTest.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsAndInfo.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsAtomNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsBuiltinNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsComplexNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsSimpleNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/hash/EnsoHashMapBuilder.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/hash/HashMapRemoveNode.java
  test/Base_Internal_Tests/src/Comparator_Spec.enso
  test/Base_Tests/src/Data/Decimal_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11126 Fix rest of user/team permissions checks and "new label" dialog
  app/dashboard/e2e/actions.ts
  app/dashboard/e2e/labelsPanel.spec.ts
  app/dashboard/src/components/AriaComponents/Form/Form.tsx
  app/dashboard/src/components/AriaComponents/Switch/Switch.tsx
  app/dashboard/src/components/ColorPicker.tsx
  app/dashboard/src/components/dashboard/AssetRow.tsx
  app/dashboard/src/components/dashboard/DatalinkNameColumn.tsx
  app/dashboard/src/components/dashboard/DirectoryNameColumn.tsx
  app/dashboard/src/components/dashboard/FileNameColumn.tsx
  app/dashboard/src/components/dashboard/ProjectIcon.tsx
  app/dashboard/src/components/dashboard/ProjectNameColumn.tsx
  app/dashboard/src/components/dashboard/SecretNameColumn.tsx
  app/dashboard/src/components/dashboard/column/NameColumn.tsx
  app/dashboard/src/hooks/projectHooks.ts
  app/dashboard/src/layouts/AssetContextMenu.tsx
  app/dashboard/src/layouts/AssetPanel.tsx
  app/dashboard/src/layouts/AssetsTable.tsx
  app/dashboard/src/layouts/Labels.tsx
  app/dashboard/src/modals/ManageLabelsModal.tsx
  app/dashboard/src/modals/NewLabelModal.tsx
  app/dashboard/src/modals/UpsertSecretModal.tsx
  app/dashboard/src/pages/dashboard/Dashboard.tsx
  app/ide-desktop/common/src/services/Backend.ts
  app/ide-desktop/common/src/text/english.json
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#11164 Do not show loading spinner for created projects
  app/dashboard/src/components/dashboard/ProjectIcon.tsx
Labels: CI: Ready to merge, CI: No changelog needed, --bug, --regression, g-dashboard

#11169 Sign artifacts for nightlies/releases
  .github/workflows/release.yml
  build/build/src/ci_gen.rs
Labels: CI: No changelog needed

#11167 Special treatment of PanicSentinel in CatchPanicNode
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/node/expression/builtin/error/CatchPanicNodeTest.java
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeErrorsTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/CatchPanicNode.java
Labels: CI: Ready to merge, CI: Keep up to date, CI: No changelog needed, CI: Clean build required

#11182 Drop per artifact signing
  .github/workflows/gui.yml
  .github/workflows/release.yml
  build/build/src/ci_gen.rs
  build/build/src/ci_gen/job.rs
  build/build/src/ide/web.rs
  build/build/src/source.rs
  build/cli/src/arg.rs
  build/cli/src/lib.rs
Labels: CI: No changelog needed, CI: Clean build required

#11172 IR caches can be disabled for --compile
  engine/runner/src/main/java/org/enso/runner/Main.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#11188 Fix MacOS Engine CI JVM tests by fixing directory-watcher module config
  lib/java/directory-watcher-wrapper/src/main/java/module-info.java
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#11156 Refactor unsupported db error messages
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Aggregate_Helper.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Column_Fetcher.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Helpers.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Type_Mapping.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Replace_Params.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Type_Mapping.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload/Operations/Internal_Core.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Take_Drop_Helpers.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/Internal/SQLServer_Dialect.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/Internal/SQLServer_Type_Mapping.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Dialect.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Type_Mapping.enso
  test/Table_Tests/src/Common_Table_Operations/Aggregate_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Conversion_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Date_Time_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Database/SQLite_Spec.enso
  test/Table_Tests/src/Database/Types/SQLite_Type_Mapping_Spec.enso
  test/Table_Tests/src/Database/Upload_Spec.enso
Labels: CI: No changelog needed

#11161 Autosized Component Browser Input
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/components/ComponentBrowser/ComponentEditor.vue
  app/gui2/src/components/ComponentBrowser/input.ts
  app/gui2/src/components/widgets/AutoSizedInput.vue
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#11194 Use color Google and GitHub icons in Login screen
  app/dashboard/src/pages/authentication/Login.tsx
  app/ide-desktop/common/src/text/english.json
Labels: CI: Ready to merge, CI: No changelog needed, --bug, --regression, g-dashboard

#11200 Don't coerce arg passed to electron
  app/ide-desktop/client/electron-builder-config.ts
Labels: CI: No changelog needed

#11170 Cleanup list of Enso's project aggregates
  build.sbt
  engine/common/src/main/java/org/enso/common/Asserts.java
  engine/common/src/main/java/org/enso/common/ContextFactory.java
  engine/common/src/main/java/org/enso/common/DebugServerInfo.java
  engine/common/src/main/java/org/enso/common/RuntimeOptions.java
Labels: CI: No changelog needed, CI: Clean build required

#11186 Integration Tests
  app/ide-desktop/client/package.json
  app/ide-desktop/client/playwright.config.ts
  app/ide-desktop/client/src/fileAssociations.ts
  app/ide-desktop/client/src/globals.d.ts
  app/ide-desktop/client/src/index.ts
  app/ide-desktop/client/src/projectManagement.ts
  app/ide-desktop/client/tests/createNewProject.spec.ts
  app/ide-desktop/client/tests/electronTest.ts
  app/ide-desktop/client/tests/setup.ts
  pnpm-lock.yaml
Labels: CI: Ready to merge, CI: No changelog needed, g-electron, -gui

#11147 Stateless parser API
  engine/runner/src/main/java/org/enso/runner/EnsoLibraryFeature.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/phase/BuiltinsIrBuilder.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/ChangesetBuilder.scala
  engine/runtime-instrument-common/src/test/scala/org/enso/compiler/test/CompilerTestSetup.scala
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/CompilerTests.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/VectorArraySignatureTest.java
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/CompilerTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/resolve/GlobalNamesTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
  engine/runtime-parser/src/main/java/org/enso/compiler/core/EnsoParser.java
  engine/runtime-parser/src/test/java/org/enso/compiler/core/EnsoParserMultiThreadedTest.java
  engine/runtime-parser/src/test/java/org/enso/compiler/core/EnsoParserTest.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  lib/java/ydoc-server/src/main/java/org/enso/ydoc/Ydoc.java
  lib/java/ydoc-server/src/main/java/org/enso/ydoc/polyfill/ParserPolyfill.java
  lib/java/ydoc-server/src/test/java/org/enso/ydoc/polyfill/ParserPolyfillTest.java
  lib/rust/parser/generate-java/java/module-info.java
  lib/rust/parser/generate-java/java/org/enso/syntax2/FinalizationManager.java
  lib/rust/parser/generate-java/java/org/enso/syntax2/Message.java
  lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java
  lib/rust/parser/generate-java/src/bin/java-tests.rs
  lib/rust/parser/jni/src/lib.rs
  tools/enso4igv/src/main/java/org/enso/tools/enso4igv/enso/EnsoErrorProvider.java
  tools/enso4igv/src/main/java/org/enso/tools/enso4igv/enso/EnsoStructure.java
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#11177 Update SQLServer version
  build/build/src/enso.rs
  build/build/src/sqlserver.rs
Labels: CI: No changelog needed, CI: Clean build required

#11190 Add `Table` and `Warnings` to standard exports of Visualization/Main.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Main.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11199 Widget support for Data.fetch and Data.post.
  distribution/lib/Standard/AWS/0.0.0-dev/src/Internal/S3_File_Write_Strategy.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Dictionary.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Pair.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Of_Day.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_Secret.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Enso_File_Write_Strategy.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Utils.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Header.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Request.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Request_Body.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Widget_Helpers.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Data_Link_Setup.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Image.enso
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeExecutionEnvironmentTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/hash/HashMapInsertNode.java
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11202 Eliminate Akka's shutdown hook
  engine/language-server/src/main/resources/application.conf
Labels: CI: No changelog needed

#11206 Fix signing yet again.
  app/ide-desktop/client/tasks/signArchivesMacOs.ts
Labels: CI: Ready to merge, CI: No changelog needed

#11208 Add graph editor and add to graph editor icons
  app/gui2/src/assets/icons.svg
Labels: CI: No changelog needed

#11178 Use `IR.STRUCTURE_COMPARATOR` to compare two IR objects
  engine/runtime-parser/src/main/java/org/enso/compiler/core/IR.java
  engine/runtime-parser/src/test/java/org/enso/compiler/core/IrPersistanceTest.java
  lib/java/persistance/src/main/java/org/enso/persist/PerInputImpl.java
Labels: CI: No changelog needed, CI: Clean build required

#11209 Replace imports of `tailwind-variants` with imports of `#/utilities/tailwindVariants`
  app/dashboard/src/components/AriaComponents/Inputs/Input/Input.tsx
  app/dashboard/src/components/AriaComponents/Inputs/MultiSelector/MultiSelector.tsx
  app/dashboard/src/components/AriaComponents/Inputs/Selector/Selector.tsx
  app/dashboard/src/components/AriaComponents/Switch/Switch.tsx
  app/dashboard/src/components/Result.tsx
  app/dashboard/src/components/Stepper/Step.tsx
  app/dashboard/src/components/Stepper/Stepper.tsx
  app/dashboard/src/modules/payments/components/PlanSelector/components/Card.tsx
Labels: CI: Ready to merge, CI: No changelog needed, x-chore, g-dashboard

#11168 Increase z-index for dialogs/popovers
  app/dashboard/src/components/AriaComponents/Dialog/Dialog.tsx
  app/dashboard/src/components/AriaComponents/Dialog/Popover.tsx
Labels: CI: No changelog needed, --bug, g-dashboard

#11212 Fix booting enso on MacOS
  build.sbt
  lib/java/directory-watcher-wrapper/src/main/java/module-info.java
  lib/java/jna-wrapper/src/main/java/module-info.java
Labels: p-highest, CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#11165 Input nodes
  CHANGELOG.md
  app/gui2/e2e/actions.ts
  app/gui2/e2e/collapsingAndEntering.spec.ts
  app/gui2/e2e/locate.ts
  app/gui2/src/components/ComponentBrowser/__tests__/placement.test.ts
  app/gui2/src/components/ComponentBrowser/placement.ts
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphEdge.vue
  app/gui2/src/components/GraphEditor/GraphEdges.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/__tests__/collapsing.test.ts
  app/gui2/src/components/GraphEditor/collapsing.ts
  app/gui2/src/components/GraphEditor/widgets/WidgetPort.vue
  app/gui2/src/composables/nodeColors.ts
  app/gui2/src/stores/graph/__tests__/graphDatabase.test.ts
  app/gui2/src/stores/graph/graphDatabase.ts
  app/gui2/src/stores/graph/index.ts
  app/gui2/src/util/ast/node.ts
  app/gui2/src/util/data/vec2.ts
  app/gui2/src/util/getIconName.ts
  app/gui2/stories/GraphNode.story.vue
  app/ydoc-shared/src/ast/parse.ts
  app/ydoc-shared/src/ast/tree.ts
Labels: CI: Ready to merge, -gui
