Repository enso-org/enso, pull requests merged in 2024-02, with the labels that each got.

#8915 Always runEngineDistribution with -ea
  project/DistributionPackage.scala
Labels: CI: No changelog needed

#8922 Add dashboard tests to GUI2 CI; fix dashboard tests
  app/ide-desktop/lib/dashboard/package.json
  app/ide-desktop/lib/dashboard/src/utilities/__tests__/ShortcutManager.test.ts
  build/build/src/project/gui2.rs
  build/cli/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed, -ci, g-dashboard

#8864 CI: Native aarch64 macOS builds, refactoring
  .github/workflows/changelog.yml
  .github/workflows/engine-benchmark.yml
  .github/workflows/gui.yml
  .github/workflows/promote.yml
  .github/workflows/release.yml
  .github/workflows/scala-new.yml
  .github/workflows/shader-tools.yml
  .github/workflows/std-libs-benchmark.yml
  .prettierignore
  app/ide-desktop/lib/client/electron-builder-config.ts
  build/build/release-body.md
  build/build/src/ci_gen.rs
  build/build/src/ci_gen/job.rs
  build/build/src/ci_gen/step.rs
  build/build/src/project/ide.rs
  build/ci_utils/src/actions/workflow/definition.rs
Labels: CI: No changelog needed

#8909 CB preview debounce
  app/gui2/e2e/componentBrowser.spec.ts
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/util/reactivity.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#8850 Split HashJoin to SimpleHashJoin and CompoundHashJoin
  std-bits/table/src/main/java/org/enso/table/data/table/join/JoinStrategy.java
  std-bits/table/src/main/java/org/enso/table/data/table/join/MatchAllStrategy.java
  std-bits/table/src/main/java/org/enso/table/data/table/join/NoOpStrategy.java
  std-bits/table/src/main/java/org/enso/table/data/table/join/PluggableJoinStrategy.java
  std-bits/table/src/main/java/org/enso/table/data/table/join/between/SortJoin.java
  std-bits/table/src/main/java/org/enso/table/data/table/join/hashing/CompoundHashJoin.java
  std-bits/table/src/main/java/org/enso/table/data/table/join/hashing/HashJoin.java
  std-bits/table/src/main/java/org/enso/table/data/table/join/hashing/HashJoinConfig.java
  std-bits/table/src/main/java/org/enso/table/data/table/join/hashing/SimpleHashJoin.java
Labels: CI: Ready to merge, CI: Keep up to date, CI: No changelog needed

#8893 Syntactic synchronization, automatic parentheses, metadata in Ast
  .prettierignore
  app/gui2/e2e/edgeRendering.spec.ts
  app/gui2/eslint.config.js
  app/gui2/mock/index.ts
  app/gui2/package.json
  app/gui2/parser-codegen/codegen.ts
  app/gui2/shared/ast/ffi.ts
  app/gui2/shared/ast/generated/.gitkeep
  app/gui2/shared/ast/index.ts
  app/gui2/shared/ast/mutableModule.ts
  app/gui2/shared/ast/parse.ts
  app/gui2/shared/ast/parserSupport.ts
  app/gui2/shared/ast/token.ts
  app/gui2/shared/ast/tree.ts
  app/gui2/shared/util/assert.ts
  app/gui2/shared/util/data/opt.ts
  app/gui2/shared/util/data/result.ts
  app/gui2/shared/util/detect.ts
  app/gui2/shared/yjsModel.ts
  app/gui2/src/App.vue
  app/gui2/src/components/ComponentBrowser/__tests__/filtering.test.ts
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphEdge.vue
  app/gui2/src/components/GraphEditor/GraphEdges.vue
  app/gui2/src/components/GraphEditor/NodeWidgetTree.vue
  app/gui2/src/components/GraphEditor/collapsing.ts
  app/gui2/src/main.ts
  app/gui2/src/stores/graph/__tests__/graphDatabase.test.ts
  app/gui2/src/stores/graph/graphDatabase.ts
  app/gui2/src/stores/graph/imports.ts
  app/gui2/src/stores/graph/index.ts
  app/gui2/src/stores/suggestionDatabase/__tests__/lsUpdate.test.ts
  app/gui2/src/stores/suggestionDatabase/documentation.ts
  app/gui2/src/util/assert.ts
  app/gui2/src/util/ast/__tests__/abstract.test.ts
  app/gui2/src/util/ast/__tests__/abstractFileIo.test.ts
  app/gui2/src/util/ast/__tests__/ast.test.ts
  app/gui2/src/util/ast/__tests__/callTree.test.ts
  app/gui2/src/util/ast/__tests__/match.test.ts
  app/gui2/src/util/ast/__tests__/prefixes.test.ts
  app/gui2/src/util/ast/__tests__/reactive.test.ts
  app/gui2/src/util/ast/abstract.ts
  app/gui2/src/util/ast/aliasAnalysis.ts
  app/gui2/src/util/ast/extended.ts
  app/gui2/src/util/ast/index.ts
  app/gui2/src/util/ast/opr.ts
  app/gui2/src/util/config.ts
  app/gui2/src/util/data/opt.ts
  app/gui2/src/util/data/result.ts
  app/gui2/src/util/docParser.ts
  app/gui2/src/util/ffi.ts
  app/gui2/src/util/qualifiedName.ts
  app/gui2/stories/MockProjectStoreWrapper.vue
  app/gui2/vite.config.ts
  app/gui2/ydoc-server/edits.ts
  app/gui2/ydoc-server/index.ts
  app/gui2/ydoc-server/languageServerSession.ts
  app/ide-desktop/lib/client/src/bin/server.ts
  package-lock.json
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#8847 Remove fansi dependency from runtime-compiler
  build.sbt
  engine/runtime-compiler/src/main/java/org/enso/compiler/context/CompilerContext.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/java/org/enso/interpreter/EnsoLanguage.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/debug/EvalNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/util/DiagnosticFormatter.scala
  engine/runtime/src/test/java/org/enso/interpreter/test/DebuggingEnsoTest.java
  engine/runtime/src/test/java/org/enso/interpreter/test/DiagnosticFormatterTest.java
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#8933 A quick fix for incorrectly working dropdowns.
  app/gui2/e2e/widgets.spec.ts
  app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#8764 Fix Truffle invariants for Nothing with a warning
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Type.java
  engine/runtime/src/test/java/org/enso/interpreter/test/MetaObjectTest.java
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#8952 Fix loading wasm for ydocs server
  app/ide-desktop/lib/client/src/bin/server.ts
Labels: CI: No changelog needed, CI: Clean build required, --bug, -gui, --regression, -gui2

#8946 Another set of small fixes
  app/gui2/e2e/componentBrowser.spec.ts
  app/gui2/e2e/customExpect.ts
  app/gui2/mock/providers.ts
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/dragging.ts
  app/gui2/src/components/widgets/EnsoTextInputWidget.vue
  app/gui2/src/components/widgets/NumericInputWidget.vue
  app/gui2/src/composables/selection.ts
  app/gui2/src/stores/graph/index.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#8936 Further optimizations to test resources
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/ReceivesTreeUpdatesHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionControllerFactory.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/binary/BaseBinaryServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/LibrariesTest.scala
  lib/scala/json-rpc-server-test/src/main/scala/org/enso/jsonrpc/test/JsonRpcServerTestKit.scala
  lib/scala/json-rpc-server/src/main/scala/org/enso/jsonrpc/ClientControllerFactory.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/protocol/ManagerClientControllerFactory.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/BaseServerSpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectShutdownSpec.scala
Labels: CI: Ready to merge, CI: No changelog needed

#8912 How to get a Java library from Maven central
  docs/distribution/packaging.md
  docs/polyglot/java.md
Labels: CI: Ready to merge, CI: Keep up to date, CI: No changelog needed, CI: Clean build required

#8940 Better `runEngineDistribution --run test/Base_Tests "filter"`
  build.sbt
  project/JPMSUtils.scala
  test/Base_Tests/src/Main.enso
  test/Table_Tests/src/Main.enso
Labels: CI: Keep up to date, CI: No changelog needed, CI: Clean build required

#8902 Fix dangling node connection
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/NodeWidgetTree.vue
  app/gui2/src/providers/widgetTree.ts
  app/gui2/src/stores/graph/index.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#8918 Fix teardown in SQLite File spec
  test/Table_Tests/src/Database/SQLite_Spec.enso
Labels: p-high, CI: No changelog needed

#8967 Disable flaky test
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/LibrariesTest.scala
  lib/scala/json-rpc-server-test/src/main/scala/org/enso/jsonrpc/test/JsonRpcServerTestKit.scala
Labels: CI: Ready to merge, CI: No changelog needed

#8947 Reduce test flakiness
  app/gui2/e2e/actions.ts
  app/gui2/e2e/typesOnNodeHover.spec.ts
  app/gui2/package.json
  app/gui2/playwright.config.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui2

#8860 Update icon definitions to new figma export format
  app/gui2/scripts/generateIconMetadata.js
  app/gui2/src/assets/icons.svg
Labels: CI: Ready to merge, CI: No changelog needed

#8970 CI: Retry Artifact Upload Finalization
  build/ci_utils/src/actions/artifacts/raw.rs
  build/ci_utils/src/actions/artifacts/run_session.rs
  build/ci_utils/src/actions/workflow.rs
  build/ci_utils/src/io.rs
Labels: CI: Ready to merge, CI: No changelog needed, -ci, -build-script

#8961 Keep only module-info.class in the root of runtime-fat-jar
  build.sbt
Labels: CI: No changelog needed

#8972 Fix vector widget in non-argument literal
  app/gui2/e2e/collapsingAndEntering.spec.ts
  app/gui2/e2e/widgets.spec.ts
  app/gui2/mock/engine.ts
  app/gui2/playwright.config.ts
  app/gui2/src/components/GraphEditor/widgets/WidgetVector.vue
Labels: CI: Ready to merge, CI: No changelog needed, --bug, --regression, -gui2

#8978 Interpret documented nodes properly
  app/gui2/e2e/graphRenderNodes.spec.ts
  app/gui2/mock/engine.ts
  app/gui2/src/components/GraphEditor/collapsing.ts
  app/gui2/src/stores/graph/graphDatabase.ts
  app/gui2/src/util/ast/node.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui2

#8956 Refactoring before text edits
  app/gui2/shared/ast/parse.ts
  app/gui2/shared/ast/tree.ts
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphEdges.vue
  app/gui2/src/components/GraphEditor/NodeWidgetTree.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetCheckbox.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetFunction.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetNumber.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetText.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetVector.vue
  app/gui2/src/composables/stackNavigator.ts
  app/gui2/src/providers/widgetRegistry.ts
  app/gui2/src/stores/graph/imports.ts
  app/gui2/src/stores/graph/index.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#8917 New scenarios for E2E tests - Interactions with Edges
  app/gui2/e2e/actions.ts
  app/gui2/e2e/edgeInteractions.spec.ts
  app/gui2/e2e/edgeRendering.spec.ts
  app/gui2/e2e/locate.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#8957 Introduce SourceDocument for text edit support
  app/gui2/shared/ast/mutableModule.ts
  app/gui2/shared/ast/sourceDocument.ts
  app/gui2/shared/ast/tree.ts
  app/gui2/src/components/CodeEditor.vue
  app/gui2/src/components/GraphEditor/NodeWidget.vue
  app/gui2/src/providers/widgetTree.ts
  app/gui2/src/stores/graph/index.ts
  app/gui2/src/util/ast/__tests__/reactive.test.ts
  app/gui2/src/util/ast/abstract.ts
  app/gui2/stories/MockProjectStoreWrapper.vue
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#8935 Implement Table.replace for the in-memory backend
  CHANGELOG.md
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Lookup_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Replace_Spec.enso
Labels: CI: Ready to merge

#8951 Fix saved project validation
  app/ide-desktop/lib/dashboard/src/pages/dashboard/Dashboard.tsx
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#8968 Refactor stdlib tests to the builder API
  distribution/lib/Standard/Test_New/0.0.0-dev/src/Suite.enso
  distribution/lib/Standard/Test_New/0.0.0-dev/src/Test.enso
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoFile.java
  test/AWS_Tests/src/Main.enso
  test/AWS_Tests/src/S3_Spec.enso
  test/Base_Tests/src/System/File_Spec.enso
  test/Examples_Tests/src/Examples_Spec.enso
  test/Examples_Tests/src/Main.enso
  test/Examples_Tests/src/Python_Examples_Spec.enso
  test/Geo_Tests/src/Geo_Spec.enso
  test/Geo_Tests/src/Main.enso
  test/Google_Api_Test/src/Main.enso
  test/Image_Tests/src/Data/Image_Spec.enso
  test/Image_Tests/src/Data/Matrix_Spec.enso
  test/Image_Tests/src/Image_Read_Write_Spec.enso
  test/Image_Tests/src/Main.enso
  test/Meta_Test_Suite_Tests/README.md
  test/Meta_Test_Suite_Tests/data/asserts_outside_of_tests/Main.enso
  test/Meta_Test_Suite_Tests/data/fail_report/Main.enso
  test/Meta_Test_Suite_Tests/data/fail_report/stdout.txt
  test/Meta_Test_Suite_Tests/data/with_clue_1/Main.enso
  test/Meta_Test_Suite_Tests/data/with_clue_1/stdout.txt
  test/Meta_Test_Suite_Tests/data/with_clue_2/Main.enso
  test/Meta_Test_Suite_Tests/data/with_clue_2/stdout.txt
  test/Meta_Test_Suite_Tests/src/Main.enso
  test/Visualization_Tests/src/Default_Visualizations_Spec.enso
  test/Visualization_Tests/src/Geo_Map_Spec.enso
  test/Visualization_Tests/src/Helpers.enso
  test/Visualization_Tests/src/Helpers_Spec.enso
  test/Visualization_Tests/src/Histogram_Spec.enso
  test/Visualization_Tests/src/Id_Spec.enso
  test/Visualization_Tests/src/Lazy_Table_Spec.enso
  test/Visualization_Tests/src/Lazy_Text_Spec.enso
  test/Visualization_Tests/src/Main.enso
  test/Visualization_Tests/src/SQL_Spec.enso
  test/Visualization_Tests/src/Scatter_Plot_Spec.enso
  test/Visualization_Tests/src/Table_Spec.enso
  test/Visualization_Tests/src/Visualization_Spec.enso
  test/Visualization_Tests/src/Widgets/Database_Widgets_Spec.enso
  test/Visualization_Tests/src/Widgets/Table_Widgets_Spec.enso
  test/Visualization_Tests/src/Widgets/Text_Widgets_Spec.enso
  test/Visualization_Tests/src/Widgets_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#8861 Allow Filter_Condition to be inverted.
  CHANGELOG.md
  distribution/lib/Standard/AWS/0.0.0-dev/src/AWS_Credential.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Base_64.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Enso_Cloud/Enso_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Enso_Cloud/Enso_Secret.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Enso_Cloud/Utils.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Filter_Condition.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Java_Json.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Locale.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/File_Error.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Header.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Response.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Response_Body.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Random.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File_By_Line.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Widget_Helpers.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column_Ref.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Conversions/Convertible_To_Columns.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Conversions/Convertible_To_Rows.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Delimited/Delimited_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Workbook.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Extensions/Table_Ref.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Expand_Objects_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Filter_Condition_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Split_Tokenize.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  distribution/lib/Standard/Test_New/0.0.0-dev/src/Helpers.enso
  distribution/lib/Standard/Test_New/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Test_New/0.0.0-dev/src/Suite.enso
  distribution/lib/Standard/Test_New/0.0.0-dev/src/Test.enso
  distribution/lib/Standard/Test_New/0.0.0-dev/src/Test_Reporter.enso
  distribution/lib/Standard/Test_New/0.0.0-dev/src/Test_Result.enso
  std-bits/table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java
  test/Base_Tests/src/Data/Json_Spec.enso
  test/Base_Tests/src/Data/List_Spec.enso
  test/Base_Tests/src/Data/Range_Spec.enso
  test/Base_Tests/src/Data/Vector_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Derived_Columns_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Filter_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Missing_Values_Spec.enso
  test/Table_Tests/src/Database/Codegen_Spec.enso
  test/Visualization_Tests/src/Lazy_Table_Spec.enso
  test/Visualization_Tests/src/Lazy_Text_Spec.enso
  tools/performance/benchmark-analysis/src/Main.enso
Labels: CI: Ready to merge

#8950 Add a small arrow for dropdowns
  app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui2/src/composables/events.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#8869 Disable tests that fail because of locale-specific Postgres Unicode collation differences
  test/Table_Tests/src/Common_Table_Operations/Order_By_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#8979 Add to_xml component
  CHANGELOG.md
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  std-bits/table/src/main/java/org/enso/table/data/table/TableToXml.java
  test/Table_Tests/src/In_Memory/Table_Xml_Spec.enso
Labels: CI: Ready to merge

#8992 CI: Retry `npm install` in case of failure.
  build/build/src/web.rs
Labels: CI: Ready to merge, CI: No changelog needed

#8996 Add some ICON tags and a few new Icons.
  app/gui2/src/assets/icons.svg
  app/gui2/src/components/visualizations/TableVisualization.vue
  app/gui2/src/util/getIconName.ts
  distribution/lib/Standard/Base/0.0.0-dev/src/Any.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Boolean.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Interval.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/List.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Map.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Pair.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Set.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Statistics.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Duration.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Period.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Of_Day.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Response.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Response_Body.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Nothing.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Database.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Connection.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Data/Image.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Data/Matrix.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column_Vector_Extensions.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Row.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
Labels: CI: Ready to merge, CI: No changelog needed

#8989 New scenarios for e2 e tests: Loading Table Visualization & Fullscreen Vis
  app/gui2/e2e/fullscreenVisualisation.spec.ts
  app/gui2/e2e/tableVisualisation.spec.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#8990 Dispose ydocs provider when closing app
  app/gui2/src/App.vue
  app/gui2/src/stores/project/index.ts
Labels: CI: No changelog needed, --bug, -gui2

#8999 Fix NPE when recomputing the context
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/RecomputeContextCmd.scala
Labels: CI: Ready to merge, CI: No changelog needed

#8924 Store whole IR.Module in .bindings cache
  engine/runtime-compiler/src/main/java/org/enso/compiler/context/CompilerContext.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/PackageRepository.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/phase/ImportResolver.scala
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/job/SerializeModuleJob.java
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/DeserializeLibrarySuggestionsJob.scala
  engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java
  engine/runtime/src/main/java/org/enso/interpreter/caches/CacheUtils.java
  engine/runtime/src/main/java/org/enso/interpreter/caches/ImportExportCache.java
  engine/runtime/src/main/java/org/enso/interpreter/caches/ModuleCache.java
  engine/runtime/src/main/java/org/enso/interpreter/caches/SuggestionsCache.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/SerializationPool.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/ThreadExecutors.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/DefaultPackageRepository.scala
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/SerializationManager.scala
  engine/runtime/src/test/java/org/enso/compiler/SerdeCompilerTest.java
  engine/runtime/src/test/java/org/enso/compiler/SerializationManagerTest.java
  engine/runtime/src/test/java/org/enso/compiler/SerializerTest.java
  engine/runtime/src/test/java/org/enso/interpreter/caches/ModuleCacheTest.java
  lib/java/persistance/src/main/java/org/enso/persist/PerInputImpl.java
  lib/java/persistance/src/main/java/org/enso/persist/Persistance.java
Labels: CI: No changelog needed, CI: Clean build required

#9005 Fix eslints in the project
  app/gui2/eslint.config.js
  app/gui2/mock/engine.ts
  app/gui2/shared/ast/ffi.ts
  app/gui2/shared/ast/parse.ts
  app/gui2/shared/ast/tree.ts
  app/gui2/src/components/GraphEditor/widgets/WidgetNumber.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetText.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetVector.vue
  app/gui2/src/util/ast/abstract.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#9013 Remove obsolete Test_New import
  test/Table_Tests/src/In_Memory/Table_Xml_Spec.enso
Labels: p-highest, CI: Ready to merge, CI: No changelog needed

#9010 Escape default text arguments in suggestions database
  engine/runtime-compiler/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Literal.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/context/SuggestionBuilderTest.scala
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#8958 Fix typo in ContextEventsListener.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextEventsListener.scala
Labels: CI: Keep up to date, CI: No changelog needed

#9004 Cleanup execution contexts when the client disconnects
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistry.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/ContextRegistryTest.scala
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#9000 Merge empty_error
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/List.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Statistics.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Empty_Error.enso
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
  test/Base_Tests/src/Data/List_Spec.enso
  test/Base_Tests/src/Data/Range_Spec.enso
  test/Base_Tests/src/Data/Statistics_Spec.enso
  test/Base_Tests/src/Data/Time/Date_Range_Spec.enso
  test/Base_Tests/src/Data/Vector_Spec.enso
  test/Base_Tests/src/Semantic/Error_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9006 Remove _new and actually run the new tests
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  std-bits/table/src/main/java/org/enso/table/data/table/TableToXml.java
  test/Table_Tests/src/In_Memory/Main.enso
  test/Table_Tests/src/In_Memory/Table_Xml_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9014 Text Editor shows up for Text only parameters.
  app/gui2/e2e/widgets.spec.ts
  app/gui2/src/components/GraphEditor/widgets/WidgetText.vue
Labels: CI: Ready to merge, CI: No changelog needed

#8925 Minor cleanups to docker image
  .github/CODEOWNERS
  engine/language-server/src/main/scala/org/enso/languageserver/boot/LanguageServerComponent.scala
  tools/ci/README.md
  tools/ci/docker/Dockerfile
  tools/ci/docker/docker-entrypoint.sh
Labels: CI: No changelog needed

#8923 Execute and debug `.enso` files with `bin/enso` in VSCode
  .github/workflows/enso4igv.yml
  .vscode/launch.json
  CHANGELOG.md
  tools/enso4igv/README.md
  tools/enso4igv/package.json
  tools/enso4igv/pom.xml
  tools/enso4igv/src/main/java/org/enso/tools/enso4igv/EnsoActionProvider.java
Labels: CI: Ready to merge, CI: Keep up to date, CI: Clean build required

#9019 Change empty_error type to array. Add tests
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso
  test/Base_Tests/src/Data/Array_Spec.enso
  test/Base_Tests/src/Data/Vector_Spec.enso
Labels: CI: No changelog needed

#9025 Propagate location to resolution errors
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/Patterns.scala
  engine/runtime/src/test/java/org/enso/compiler/ExecStrictCompilerTest.java
Labels: CI: No changelog needed

#8985 Local project manager work against any folder
  docs/language-server/protocol-project-manager.md
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/Cli.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/MainModule.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/ProjectManager.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/command/CommandHandler.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/command/ProjectListCommand.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/repository/ProjectFileRepositoryFactory.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/repository/ProjectRepositoryFactory.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/protocol/ClientController.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/protocol/ManagerClientControllerFactory.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/protocol/ProjectManagementApi.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/EngineInstallHandler.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/EngineListAvailableHandler.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/EngineListInstalledHandler.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/EngineUninstallHandler.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/FailureMapper.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/ProjectCreateHandler.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/ProjectDeleteHandler.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/ProjectListHandler.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/ProjectOpenHandler.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/ProjectRenameHandler.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/ProjectServiceFailureMapper.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/ProjectStatusHandler.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectService.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectServiceApi.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectServiceFailure.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/BaseServerSpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/ProjectManagementOps.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectOpenSpecBase.scala
Labels: CI: Ready to merge, CI: No changelog needed

#8994 Small boolean widget tweaks
  app/gui2/src/components/GraphEditor/widgets/WidgetCheckbox.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui2/src/stores/graph/imports.ts
  app/gui2/src/util/equals.ts
  app/gui2/src/util/reactivity.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#8988 Fix chat styling; fix focus issues in chat
  app/ide-desktop/lib/common/src/detect.ts
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/AssetSearchBar.tsx
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/Chat.tsx
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/ChatPlaceholder.tsx
  app/ide-desktop/lib/dashboard/tailwind.config.js
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#9001 CI: Tweaks for backend tests
  build/build/src/engine/context.rs
  build/build/src/enso.rs
  build/build/src/paths.rs
  build/ci_utils/src/actions/workflow.rs
  test/Meta_Test_Suite_Tests/README.md
  test/Meta_Test_Suite_Tests/data/asserts_outside_of_tests/Main.enso
  test/Meta_Test_Suite_Tests/data/asserts_outside_of_tests/stdout.txt
  test/Meta_Test_Suite_Tests/data/asserts_outside_of_tests/test_description.txt
  test/Meta_Test_Suite_Tests/data/fail_report/Main.enso
  test/Meta_Test_Suite_Tests/data/fail_report/stdout.txt
  test/Meta_Test_Suite_Tests/data/fail_report/test_description.txt
  test/Meta_Test_Suite_Tests/data/with_clue_1/Main.enso
  test/Meta_Test_Suite_Tests/data/with_clue_1/stdout.txt
  test/Meta_Test_Suite_Tests/data/with_clue_1/test_description.txt
  test/Meta_Test_Suite_Tests/data/with_clue_2/Main.enso
  test/Meta_Test_Suite_Tests/data/with_clue_2/stdout.txt
  test/Meta_Test_Suite_Tests/data/with_clue_2/test_description.txt
  test/Meta_Test_Suite_Tests/package.yaml
  test/Meta_Test_Suite_Tests/src/Main.enso
Labels: CI: Ready to merge, CI: No changelog needed, -ci, -build-script

#9015 Fix dashboard issues
  app/ide-desktop/lib/dashboard/src/components/DragModal.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/AssetRow.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/FileNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/AssetsTable.tsx
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/Drive.tsx
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/DuplicateAssetsModal.tsx
  app/ide-desktop/lib/dashboard/src/pages/dashboard/Dashboard.tsx
  app/ide-desktop/lib/dashboard/src/services/RemoteBackend.ts
  app/ide-desktop/lib/dashboard/src/tailwind.css
  app/ide-desktop/lib/dashboard/tailwind.config.js
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#9017 Changing Widgets to work better with GUI2
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/List.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Statistics.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Widget_Helpers.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Sort_Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Main.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Order_By_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9030 Rename wrapped_error and make it private
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/DB_Wrapped_Error.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9023 Update ICONs as per Cass's work
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Base_64.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Enso_Cloud/Enso_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Java_Json.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Day_Of_Week.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Duration.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Period.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Of_Day.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Zone.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/URI.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File_By_Line.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Filter_Condition_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9033 CI: Remove Manual Stdlib Compilation
  build/build/src/engine/context.rs
  build/build/src/enso.rs
Labels: CI: Ready to merge, CI: No changelog needed

#8960 Organization settings page
  app/ide-desktop/lib/assets/people_settings.svg
  app/ide-desktop/lib/dashboard/e2e/api.ts
  app/ide-desktop/lib/dashboard/src/components/dashboard/AssetRow.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/ProjectIcon.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/ProjectNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/UserPermissions.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/column/LabelsColumn.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/column/SharedWithColumn.tsx
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/AssetContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/AssetProperties.tsx
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/AssetsTable.tsx
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/AssetsTableContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/ConfirmDeleteUserModal.tsx
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/Drive.tsx
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/GlobalContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/InviteUsersModal.tsx
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/ManageLabelsModal.tsx
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/ManagePermissionsModal.tsx
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/Settings.tsx
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/Settings/AccountSettingsTab.tsx
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/Settings/MembersSettingsTab.tsx
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/Settings/OrganizationSettingsTab.tsx
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/Settings/SettingsTab.ts
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/SettingsSidebar.tsx
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/UserBar.tsx
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/UserMenu.tsx
  app/ide-desktop/lib/dashboard/src/pages/dashboard/Dashboard.tsx
  app/ide-desktop/lib/dashboard/src/providers/AuthProvider.tsx
  app/ide-desktop/lib/dashboard/src/services/Backend.ts
  app/ide-desktop/lib/dashboard/src/services/LocalBackend.ts
  app/ide-desktop/lib/dashboard/src/services/RemoteBackend.ts
  app/ide-desktop/lib/dashboard/src/services/remoteBackendPaths.ts
  app/ide-desktop/lib/dashboard/src/utilities/HttpClient.ts
  app/ide-desktop/lib/dashboard/src/utilities/permissions.ts
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#9027 Update the `aggregate` API to take a separate `group_by`
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Deprecated.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/IR/Context.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Aggregate_Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Aggregate_Column_Helper.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/AI.enso
  test/Benchmarks/src/Table/Add_Row_Number.enso
  test/Benchmarks/src/Table/Aggregate.enso
  test/Benchmarks/src/Table/Cross_Tab.enso
  test/Exploratory_Benchmarks/src/Table/Column_Aggregate.enso
  test/Table_Tests/src/Common_Table_Operations/Add_Row_Number_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Aggregate_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Name_Edge_Cases_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Cross_Tab_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Integration_Tests.enso
  test/Table_Tests/src/Common_Table_Operations/Missing_Values_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Take_Drop_Spec.enso
  test/Table_Tests/src/Database/Codegen_Spec.enso
  test/Table_Tests/src/Database/Common/Common_Spec.enso
  test/Table_Tests/src/Database/Common/Default_Ordering_Spec.enso
  test/Table_Tests/src/Database/Common/Names_Length_Limits_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Database/Types/Postgres_Type_Mapping_Spec.enso
  test/Table_Tests/src/Database/Types/SQLite_Type_Mapping_Spec.enso
  test/Table_Tests/src/Database/Upload_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
  test/Visualization_Tests/src/Table_Spec.enso
  tools/performance/benchmark-analysis/src/Main.enso
  tools/performance/engine-benchmarks/Engine_Benchs/src/Main.enso
Labels: CI: Ready to merge

#9032 Rename Builder to SQL_Builder
  distribution/lib/Standard/AWS/0.0.0-dev/src/Database/Redshift/Internal/Redshift_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/SQL.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
Labels: CI: No changelog needed

#8987 Add "Invite" button on top right
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/InviteUsersModal.tsx
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/UserBar.tsx
  app/ide-desktop/lib/dashboard/tailwind.config.js
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#9043 Synchronize suggestions loading after the reconnect
  engine/language-server/src/main/scala/org/enso/languageserver/search/SearchProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/handler/InvalidateModulesIndexHandler.scala
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/command/InvalidateModulesIndexCommand.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/job/BackgroundJob.java
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/StartBackgroundProcessingCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/DeserializeLibrarySuggestionsJob.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlSuggestionsRepo.scala
Labels: CI: Ready to merge, CI: No changelog needed

#9044 CI: Fix for the runtime docker image build following #8925
  build/build/src/aws/ecr/runtime.rs
  build/ci_utils/src/programs/docker.rs
Labels: CI: Ready to merge, CI: No changelog needed

#9052 Add support for `positionalArgumentsExpressions` of text visualizations
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/VisualizationConfiguration.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/ContextRegistryTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/ExecutionContextJsonMessages.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/VisualizationOperationsTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/UpsertVisualizationJob.scala
  engine/runtime-instrument-common/src/test/java/org/enso/interpreter/instrument/job/JobsTest.java
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#9046 Rename database column to DB_Column
  app/gui/view/graph-editor/src/builtin/visualization/java_script/sql.js
  app/gui2/src/components/visualizations/SQLVisualization.vue
  distribution/lib/Standard/AWS/0.0.0-dev/src/Database/Redshift/Internal/Redshift_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/SQL_Type.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Take_Drop_Helpers.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Helpers.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Type_Mapping.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Nothing_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Database/SQLite_Spec.enso
  test/Table_Tests/src/Util.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9038 Remove vite-plugin-top-level-await plugin
  app/gui2/e2e/main.ts
  app/gui2/package.json
  app/gui2/src/components/ComponentBrowser/__tests__/input.test.ts
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/providers/__tests__/widgetRegistry.test.ts
  app/gui2/src/stores/graph/__tests__/graphDatabase.test.ts
  app/gui2/src/util/ast/__tests__/aliasAnalysis.test.ts
  app/gui2/src/util/ast/aliasAnalysis.ts
  app/gui2/vite.config.ts
  package-lock.json
Labels: CI: Ready to merge, CI: No changelog needed, -ci, --bug, -gui2

#8867 Check type of `self` in static dispatch
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/List.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Pair.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Array_Like_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Warning.enso
  engine/runtime-compiler/src/main/scala/org/enso/compiler/data/BindingsMap.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/MethodDefinitions.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/TypeNames.scala
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/BinaryDispatchTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/SignatureTest.java
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/semantic/DataflowErrorsTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/semantic/MethodsTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/semantic/SuspendedArgumentsTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/immutable/FlattenVectorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/immutable/InsertBuiltinVectorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/immutable/RemoveAtVectorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/immutable/SliceArrayVectorNode.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
  test/Base_Tests/src/Data/Vector_Spec.enso
  test/Base_Tests/src/Semantic/Names_Spec.enso
  test/Base_Tests/src/Semantic/Warnings_Spec.enso
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso
Labels: CI: Ready to merge

#9045 Improving experience with `format` and `parse`.
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time_Formatter.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Time/Format/As_Java_Formatter_Interpreter.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Metadata.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Widget_Helpers.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Data_Formatter.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Type/Value_Type.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  test/Base_Tests/src/Data/Text/Parse_Spec.enso
  test/Table_Tests/src/In_Memory/Column_Format_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9053 Set default timeouts in incremental updates test
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/instrument/IncrementalUpdatesTest.java
Labels: CI: Ready to merge, CI: No changelog needed

#9051 Fix Code Editor click
  app/ide-desktop/lib/dashboard/src/App.tsx
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard, -gui2

#9056 Remove Column Aliases
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Column_Fetcher.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
  test/Table_Tests/src/Common_Table_Operations/Nothing_Spec.enso
  test/Table_Tests/src/Util.enso
Labels: CI: No changelog needed

#9042 WidgetFunction: merge dynamic config for a call with inherited one
  app/gui2/src/components/GraphEditor/widgets/WidgetFunction.vue
  app/gui2/src/providers/widgetRegistry/configuration.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui2

#9066 CI: Fix macOS notarization
  app/ide-desktop/lib/client/tasks/signArchivesMacOs.ts
Labels: CI: No changelog needed

#9072 Revert "Synchronize suggestions loading after the reconnect (#9043)"
  engine/language-server/src/main/scala/org/enso/languageserver/search/SearchProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/handler/InvalidateModulesIndexHandler.scala
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/command/InvalidateModulesIndexCommand.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/job/BackgroundJob.java
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/StartBackgroundProcessingCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/DeserializeLibrarySuggestionsJob.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlSuggestionsRepo.scala
Labels: CI: Ready to merge, CI: No changelog needed

#9029 Implement full wheel component menu
  app/gui2/src/components/CircularMenu.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/VisualizationContainer.vue
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#9057 Serialize UUID for non-library modules
  engine/runtime-compiler/src/main/scala/org/enso/compiler/data/BindingsMap.scala
  engine/runtime-parser/src/main/java/org/enso/compiler/core/IR.java
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Module.scala
  engine/runtime/src/main/java/org/enso/interpreter/caches/CacheUtils.java
  engine/runtime/src/main/java/org/enso/interpreter/caches/ImportExportCache.java
  engine/runtime/src/main/java/org/enso/interpreter/caches/ModuleCache.java
Labels: CI: Ready to merge, CI: No changelog needed

#9076 Starting to refactor Storage and Operations
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Fan_Out.enso
  std-bits/table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/MixedStorageFacade.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/SpecializedStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/Storage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/ComputedLongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/ComputedNullableLongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/DoubleStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/LongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/index/DefaultIndex.java
  std-bits/table/src/main/java/org/enso/table/data/index/Index.java
  std-bits/table/src/main/java/org/enso/table/data/mask/OrderMask.java
  std-bits/table/src/main/java/org/enso/table/data/table/Column.java
  std-bits/table/src/main/java/org/enso/table/data/table/Table.java
  std-bits/table/src/main/java/org/enso/table/data/table/join/lookup/LookupJoin.java
  std-bits/table/src/main/java/org/enso/table/excel/ExcelRange.java
  test/Base_Tests/polyglot-sources/enso-test-java-helpers/src/main/java/org/enso/table_test_helpers/ExplodingStorage.java
Labels: CI: Ready to merge, CI: No changelog needed

#9054 Implement `copy_to` and `move_to` for `S3_File`
  CHANGELOG.md
  distribution/lib/Standard/AWS/0.0.0-dev/src/Internal/Request_Body.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/Internal/S3_File_Write_Strategy.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Enso_Cloud/Enso_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/File_Error.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/Generic/File_Like.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/Generic/File_Write_Strategy.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/Generic/Writable_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/Local_File_Write_Strategy.enso
  test/AWS_Tests/src/Main.enso
  test/AWS_Tests/src/S3_Spec.enso
Labels: CI: Ready to merge

#9082 Introduce hash seed to invaldiate caches
  docs/runtime/ir-caching.md
  engine/runtime-compiler/src/main/scala/org/enso/compiler/data/BindingsMap.scala
  engine/runtime-parser/src/main/java/org/enso/compiler/core/IR.java
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Module.scala
  lib/java/persistance/src/main/java/org/enso/persist/PerMap.java
Labels: CI: Ready to merge, CI: No changelog needed

#9059 CI: force sbt server to start
  build/build/src/engine/sbt.rs
  build/ci_utils/src/programs/sbt.rs
Labels: CI: No changelog needed, -ci, -build-script

#9077 Keep single execute expression job in the queue
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/command/ExecuteExpressionCommand.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/job/ExecuteExpressionJob.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionCallbacks.java
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/CacheInvalidation.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/ExecutionContextManager.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/Visualization.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/VisualizationHolder.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/UpsertVisualizationJob.scala
Labels: CI: Ready to merge, CI: No changelog needed

#9050 Fix dashboard tests
  app/ide-desktop/lib/dashboard/e2e/actions.ts
  app/ide-desktop/lib/dashboard/e2e/copy.spec.ts
  app/ide-desktop/lib/dashboard/playwright.config.ts
  app/ide-desktop/lib/dashboard/src/components/DragModal.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/DirectoryNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/ProjectNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/events/assetEvent.ts
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/AssetsTable.tsx
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/AssetsTableContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/utilities/__tests__/jsonSchema.test.ts
  app/ide-desktop/lib/dashboard/src/utilities/jsonSchema.ts
  app/ide-desktop/lib/dashboard/src/utilities/set.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#9087 Refactor common context handling pattern
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Enso_Cloud/Enso_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Enso_Cloud/Enso_Secret.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Runtime.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/Generic/File_Write_Strategy.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload_Table.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Data/Image.enso
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeExecutionEnvironmentTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/semantic/DesignExecutionEnvironmentTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/semantic/LiveExecutionEnvironmentTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/ForbiddenOperation.java
  test/Base_Tests/src/Semantic/Runtime_Spec.enso
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Runtime.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9070 Equality with conversions
  distribution/lib/Standard/Test/0.0.0-dev/src/Extensions.enso
  docs/syntax/functions.md
  docs/types/dynamic-dispatch.md
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/EqualsBenchmarks.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/EqualsConversionsTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/EqualsTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/HashCodeTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/TestBase.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsAtomNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsComplexNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsSimpleNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/HashCodeNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortArrayNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoMultiValue.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/hash/EnsoHashMap.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/hash/EnsoHashMapBuilder.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/hash/HashMapInsertNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/hash/HashMapRemoveNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/Warning.java
  test/Base_Tests/src/Data/Numbers_Spec.enso
  test/Base_Tests/src/Semantic/Conversion_Spec.enso
Labels: CI: No changelog needed, CI: Clean build required

#9090 Refactoring the Unary operations so uncoupled from Storage.
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/DB_Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  std-bits/table/src/main/java/org/enso/table/data/column/operation/UnaryOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/MapOperationStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/UnaryMapOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/datetime/DatePartExtractors.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/DoubleLongMapOpWithSpecialNumericHandling.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/GenericUnaryIntegerOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/UnaryIntegerOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/UnaryLongToLongOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/AbstractUnaryBooleanOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/AbstractUnaryLongOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/AbstractUnaryOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/DatePartOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/IsEmptyOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/IsInfiniteOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/IsNaNOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/IsNothingOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/NotOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/TextLengthOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/TruncatedTimePartOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/UnaryRoundOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/ColumnBooleanStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/ColumnDoubleStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/ColumnLongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/ColumnStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/ColumnStorageWithInferredStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/ColumnStorageWithNothingMap.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/MixedStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/MixedStorageFacade.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/ObjectStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/SpecializedStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/Storage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/StringStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/ValueIsNothingException.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/datetime/DateStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/datetime/DateTimeStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/datetime/TimeOfDayStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/AbstractLongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/DoubleStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/LongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/type/AnyObjectType.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/type/BigIntegerType.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/type/BooleanType.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/type/DateTimeType.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/type/DateType.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/type/FloatType.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/type/IntegerType.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/type/StorageType.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/type/TextType.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/type/TimeOfDayType.java
  test/Base_Tests/polyglot-sources/enso-test-java-helpers/src/main/java/org/enso/table_test_helpers/ExplodingStorage.java
Labels: CI: Ready to merge, CI: No changelog needed

#9085 Updating Enso Cloud integration - cheaper `Enso_Secret.create`, introducing `Enso_File.creation_time` and `last_modified_time`
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Enso_Cloud/Enso_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Enso_Cloud/Enso_Secret.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Enso_Cloud/Enso_User.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Enso_Cloud/Errors.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Enso_Cloud/Utils.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/HTTP_Error.enso
  test/Base_Tests/src/Network/Enso_Cloud/Cloud_Tests_Setup.enso
  test/Base_Tests/src/Network/Enso_Cloud/Enso_Cloud_Spec.enso
  test/Base_Tests/src/Network/Enso_Cloud/Enso_File_Spec.enso
  test/Base_Tests/src/Network/Enso_Cloud/Secrets_Spec.enso
  test/Base_Tests/src/Network/Http_Spec.enso
  tools/http-test-helper/src/main/java/org/enso/shttp/auth/HandlerWithTokenAuth.java
Labels: CI: Ready to merge, CI: No changelog needed

#9068 Render target attachment bit as part of port.
  app/gui2/src/components/GraphEditor/GraphEdge.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetPort.vue
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#9055 Enable the Code Editor, with new apply-text-edits algo.
  app/gui2/mock/index.ts
  app/gui2/shared/ast/debug.ts
  app/gui2/shared/ast/ffi.ts
  app/gui2/shared/ast/index.ts
  app/gui2/shared/ast/mutableModule.ts
  app/gui2/shared/ast/parse.ts
  app/gui2/shared/ast/sourceDocument.ts
  app/gui2/shared/ast/token.ts
  app/gui2/shared/ast/tree.ts
  app/gui2/shared/util/data/__tests__/iterable.test.ts
  app/gui2/shared/util/data/__tests__/text.test.ts
  app/gui2/shared/util/data/iterable.ts
  app/gui2/shared/util/data/text.ts
  app/gui2/shared/yjsModel.ts
  app/gui2/src/components/CodeEditor.vue
  app/gui2/src/components/CodeEditor/codemirror.ts
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/NodeWidgetTree.vue
  app/gui2/src/stores/graph/graphDatabase.ts
  app/gui2/src/stores/graph/index.ts
  app/gui2/src/stores/project/index.ts
  app/gui2/src/util/ast/__tests__/abstract.test.ts
  app/gui2/src/util/ast/__tests__/match.test.ts
  app/gui2/src/util/ast/__tests__/sourceDocument.test.ts
  app/gui2/src/util/ast/__tests__/testCase.ts
  app/gui2/src/util/ast/abstract.ts
  app/gui2/src/util/ast/extended.ts
  app/gui2/src/util/ast/index.ts
  app/gui2/src/util/ast/match.ts
  app/gui2/src/util/ast/prefixes.ts
  app/gui2/src/util/data/iterable.ts
  app/gui2/ydoc-server/edits.ts
  app/gui2/ydoc-server/languageServerSession.ts
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/Chat.tsx
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#9098 Remove table aliases
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/DB_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Extensions/Upload_Database_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Extensions/Upload_In_Memory_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/JDBC_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Result_Set.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload_Table.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Util.enso
  test/Visualization_Tests/src/Table_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9102 Rename node to component
  lib/scala/pkg/src/main/resources/default/src/Main.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9073 New ... menu in the top bar with zoom controls
  app/gui2/src/components/ExtendedMenu.vue
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/TopBar.vue
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/UserBar.tsx
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#9110 CI: Release links the new IDE
  build/build/release-body.md
Labels: CI: Ready to merge, CI: No changelog needed, -ci

#9111 Fix node edits
  app/gui2/shared/ast/parse.ts
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/stores/project/index.ts
Labels: CI: No changelog needed

#9106 Java and Graal versions are checked before the build starts
  .github/workflows/formatting.yml
  build.sbt
  project/GraalVM.scala
Labels: CI: Ready to merge, CI: No changelog needed

#9108 Display warnings on components
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/GraphNodeError.vue
  app/gui2/src/components/GraphEditor/GraphNodeMessage.vue
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#9119 Fix bug in map visualization
  app/gui2/src/components/visualizations/GeoMapVisualization.vue
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui2

#9126 Including missing Polyglot_Spec in all the tests
  test/Base_Tests/src/Data/Polyglot_Spec.enso
  test/Base_Tests/src/Main.enso
Labels: CI: No changelog needed

#9116 Self-arrows: Distinguish self arguments
  app/gui2/src/components/GraphEditor/GraphEdge.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/NodeWidgetTree.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetHierarchy.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetPort.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetSelfIcon.vue
  app/gui2/src/providers/widgetTree.ts
  app/gui2/src/stores/graph/graphDatabase.ts
  app/gui2/src/stores/graph/index.ts
  app/gui2/src/util/ast/node.ts
Labels: CI: No changelog needed, -gui2

#9131 Add property test for textChangeToEdits and applyTextEdits.
  app/gui2/shared/util/data/__tests__/text.test.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#9128 Refactoring `Table.set` for GUI2 and other GUI fixes
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Widget_Helpers.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/DB_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Calculations/Column_Operation.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column_Ref.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Expression.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Join_Condition.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Simple_Expression.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Extensions/Table_Ref.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Expand_Objects_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Join_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Main.enso
  test/Table_Tests/src/Common_Table_Operations/Aggregate_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Name_Edge_Cases_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Core_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Cross_Tab_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Derived_Columns_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Expression_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Filter_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Join_Spec.enso
  test/Table_Tests/src/Database/Codegen_Spec.enso
  test/Table_Tests/src/Database/Common/Default_Ordering_Spec.enso
  test/Table_Tests/src/Database/Common/Names_Length_Limits_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Database/Upload_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
  test/Visualization_Tests/src/Widgets/Database_Widgets_Spec.enso
  test/Visualization_Tests/src/Widgets/Table_Widgets_Spec.enso
Labels: CI: Ready to merge

#9092 Refactor S3 path handling
  distribution/lib/Standard/AWS/0.0.0-dev/src/Internal/Request_Body.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/Internal/S3_File_Write_Strategy.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/Internal/S3_Path.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3_File.enso
  test/AWS_Tests/src/S3_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9135 Rename `new_name` to `as` on Aggregate_Column.
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/DB_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Aggregate_Helper.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Aggregate_Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Aggregate_Column_Helper.enso
  test/Table_Tests/src/Common_Table_Operations/Aggregate_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Cross_Tab_Spec.enso
  test/Table_Tests/src/Database/Common/Names_Length_Limits_Spec.enso
  test/Table_Tests/src/In_Memory/Aggregate_Column_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#8671 Chained if_then_else application change
  lib/rust/parser/debug/tests/parse.rs
  lib/rust/parser/src/macros/built_in.rs
  lib/rust/parser/src/macros/expand.rs
  lib/rust/parser/src/macros/pattern.rs
  test/Table_Tests/src/Common_Table_Operations/Nothing_Spec.enso
Labels: CI: No changelog needed

#9139 Update link to point to search page
  docs/polyglot/java.md
Labels: CI: Ready to merge, CI: No changelog needed

#9140 Move `Enso_Cloud` from `Data` to top-level in `Standard.Base`
  distribution/lib/Standard/AWS/0.0.0-dev/src/AWS_Credential.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/Internal/S3_Path.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_Secret.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_User.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Errors.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Utils.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Header.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/URI.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/JDBC_Connection.enso
  test/Base_Tests/src/Network/Enso_Cloud/Enso_Cloud_Spec.enso
  test/Base_Tests/src/Network/Enso_Cloud/Secrets_Spec.enso
  test/Base_Tests/src/Network/URI_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9127 Fix interfering click handlers
  app/gui2/e2e/collapsingAndEntering.spec.ts
  app/gui2/src/bindings.ts
  app/gui2/src/components/CircularMenu.vue
  app/gui2/src/components/CodeEditor.vue
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/components/ComponentBrowser/__tests__/filtering.test.ts
  app/gui2/src/components/ComponentBrowser/__tests__/input.test.ts
  app/gui2/src/components/ComponentBrowser/filtering.ts
  app/gui2/src/components/ComponentBrowser/input.ts
  app/gui2/src/components/DocumentationPanel/DocsBreadcrumb.vue
  app/gui2/src/components/DocumentationPanel/DocsBreadcrumbs.vue
  app/gui2/src/components/DocumentationPanel/DocsList.vue
  app/gui2/src/components/ExecutionModeSelector.vue
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/NodeWidgetTree.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetCheckbox.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetNumber.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetSelfIcon.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetText.vue
  app/gui2/src/components/NavBar.vue
  app/gui2/src/components/NavBreadcrumb.vue
  app/gui2/src/components/NavBreadcrumbs.vue
  app/gui2/src/components/ProjectTitle.vue
  app/gui2/src/components/ToggleIcon.vue
  app/gui2/src/components/VisualizationContainer.vue
  app/gui2/src/components/VisualizationSelector.vue
  app/gui2/src/components/visualizations/ScatterplotVisualization.vue
  app/gui2/src/components/widgets/CheckboxWidget.vue
  app/gui2/src/components/widgets/DropdownWidget.vue
  app/gui2/src/components/widgets/EnsoTextInputWidget.vue
  app/gui2/src/components/widgets/ListWidget.vue
  app/gui2/src/util/ast/__tests__/abstract.test.ts
  app/gui2/src/util/ast/abstract.ts
  app/gui2/src/util/ast/text.ts
  app/gui2/src/util/regexp.ts
  app/gui2/src/util/shortcuts.ts
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, --bug, -gui2

#8841 Add Stripe for Billing Support
  app/ide-desktop/lib/client/src/security.ts
  app/ide-desktop/lib/content/src/index.html
  app/ide-desktop/lib/dashboard/index.html
  app/ide-desktop/lib/dashboard/src/App.tsx
  app/ide-desktop/lib/dashboard/src/appUtils.tsx
  app/ide-desktop/lib/dashboard/src/authentication/service.ts
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/ChangePasswordModal.tsx
  app/ide-desktop/lib/dashboard/src/pages/subscribe/Subscribe.tsx
  app/ide-desktop/lib/dashboard/src/services/Backend.ts
  app/ide-desktop/lib/dashboard/src/services/LocalBackend.ts
  app/ide-desktop/lib/dashboard/src/services/RemoteBackend.ts
  app/ide-desktop/lib/dashboard/src/services/remoteBackendPaths.ts
  app/ide-desktop/lib/dashboard/src/utilities/config.ts
  app/ide-desktop/lib/dashboard/tailwind.config.js
  app/ide-desktop/lib/dashboard/vite.config.ts
  app/ide-desktop/package.json
  package-lock.json
Labels: CI: No changelog needed, x-new-feature, g-dashboard

#9137 Remove `countMissing` from Storage and replace with a new `CountNothing` operation.
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  std-bits/table/src/main/java/org/enso/table/data/column/operation/CountNothing.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/MixedStorageFacade.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/SpecializedStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/Storage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/AbstractLongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/ComputedLongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/ComputedNullableLongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/DoubleStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/LongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/index/MultiValueIndex.java
  std-bits/table/src/main/java/org/enso/table/parsing/TypeInferringParser.java
  test/Base_Tests/polyglot-sources/enso-test-java-helpers/src/main/java/org/enso/table_test_helpers/ExplodingStorage.java
  test/Table_Tests/src/Formatting/Parse_Values_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9152 Added unique, deduplicate aliases for distinct
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/DB_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9155 Fix escaping `\`
  app/gui2/src/util/ast/__tests__/abstract.test.ts
  app/gui2/src/util/ast/__tests__/text.ts
  app/gui2/src/util/ast/text.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, --regression, -gui2

#9148 Display alias when searching by alias
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/components/ComponentBrowser/__tests__/component.test.ts
  app/gui2/src/components/ComponentBrowser/component.ts
Labels: CI: No changelog needed, -gui2

#9153 Proper fix for editing node
  app/gui2/e2e/componentBrowser.spec.ts
  app/gui2/e2e/locate.ts
  app/gui2/src/components/CircularMenu.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/util/shortcuts.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, --regression, -gui2

#9146 Checkbox shows argument name if not already shown
  app/gui2/src/components/ComponentBrowser/input.ts
  app/gui2/src/components/GraphEditor/widgets/WidgetArgumentName.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetCheckbox.vue
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#9169 Add comment, warning, error icons.
  app/gui2/src/assets/icons.svg
Labels: CI: Ready to merge, CI: No changelog needed

#9114 Unexpected warning when running a standalone script
  engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java
Labels: CI: Ready to merge, CI: No changelog needed

#9133 Replace execution context controls with record mode controls
  app/gui2/scripts/generateIconMetadata.js
  app/gui2/src/assets/icons.svg
  app/gui2/src/components/ExecutionModeSelector.vue
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/RecordControl.vue
  app/gui2/src/components/TopBar.vue
  app/gui2/src/stores/project/index.ts
  app/gui2/stories/TopBar.story.vue
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#9156 Add ability to choose dimensions and metrics to google analytics report
  distribution/lib/Standard/Google_Api/0.0.0-dev/src/Main.enso
Labels: CI: No changelog needed

#9154 IsNa to IsNothing, missing to Nothing in Table code.
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/DB_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  std-bits/table/src/main/java/org/enso/table/data/column/builder/BigIntegerBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/BoolBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/DoubleBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/InferringDoubleBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/LongBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/LongBuilderChecked.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/LongBuilderUnchecked.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/NumericBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/ToBigIntegerConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/ToFloatStorageConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/ToIntegerStorageConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/ToTextStorageConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/GenericBinaryObjectMapOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/SpecializedIsInOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/bool/BooleanIsInOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/DoubleRoundOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/LongRoundOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/arithmetic/NumericBinaryOpImplementation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/comparisons/NumericComparison.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/helpers/BigIntegerArrayAdapter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/helpers/DoubleArrayAdapter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/text/LikeOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/text/StringBooleanOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/text/StringLongToStringOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/text/StringStringOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/ColumnStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/MixedStorageFacade.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/SpecializedStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/Storage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/StringStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/AbstractLongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/ComputedLongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/ComputedNullableLongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/DoubleStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/LongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/index/MultiValueKeyBase.java
  std-bits/table/src/main/java/org/enso/table/write/ExcelWriter.java
  test/Base_Tests/polyglot-sources/enso-test-java-helpers/src/main/java/org/enso/table_test_helpers/ExplodingStorage.java
  test/Exploratory_Benchmarks/polyglot-sources/exploratory-benchmark-java-helpers/src/main/java/org/enso/exploratory_benchmark_helpers/LongNullHandling.java
  test/Exploratory_Benchmarks/polyglot-sources/exploratory-benchmark-java-helpers/src/main/java/org/enso/exploratory_benchmark_helpers/MapHelpers.java
  test/Exploratory_Benchmarks/polyglot-sources/exploratory-benchmark-java-helpers/src/main/java/org/enso/exploratory_benchmark_helpers/SimpleStorageAggregateHelpers.java
  test/Exploratory_Benchmarks/src/Table/Column_Aggregate.enso
  test/Exploratory_Benchmarks/src/Table/Column_Bi_Map.enso
  test/Exploratory_Benchmarks/src/Table/Column_Map.enso
  test/Exploratory_Benchmarks/src/Table/Enso_Callback.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9078 Use backend errors in toast notifications
  app/ide-desktop/README.md
  app/ide-desktop/eslint.config.js
  app/ide-desktop/lib/dashboard/README.md
  app/ide-desktop/lib/dashboard/src/components/ColorPicker.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/FileNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/AssetProperties.tsx
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/AssetSearchBar.tsx
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/GlobalContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/services/RemoteBackend.ts
Labels: CI: Ready to merge, CI: No changelog needed, x-chore, g-dashboard

#9074 Remove `forceCreate` from backend requests; minor bugfixes
  app/ide-desktop/lib/assets/folder_arrow.svg
  app/ide-desktop/lib/dashboard/e2e/actions.ts
  app/ide-desktop/lib/dashboard/e2e/sort.spec.ts
  app/ide-desktop/lib/dashboard/src/authentication/cognito.ts
  app/ide-desktop/lib/dashboard/src/components/dashboard/AssetIcon.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/AssetRow.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/DataLinkNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/DirectoryNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/FileNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/ProjectIcon.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/ProjectNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/SecretNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/events/AssetEventType.ts
  app/ide-desktop/lib/dashboard/src/events/assetEvent.ts
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/AssetContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/AssetSearchBar.tsx
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/AssetsTable.tsx
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/Drive.tsx
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/DriveBar.tsx
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/TopBar.tsx
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/UserMenu.tsx
  app/ide-desktop/lib/dashboard/src/pages/dashboard/Dashboard.tsx
  app/ide-desktop/lib/dashboard/src/services/Backend.ts
  app/ide-desktop/lib/dashboard/src/services/RemoteBackend.ts
  app/ide-desktop/lib/dashboard/src/utilities/AssetQuery.ts
Labels: CI: Ready to merge, CI: No changelog needed, x-chore, g-dashboard

#9185 Fix E2E tests
  app/gui2/e2e/componentBrowser.spec.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui2

#9079 Move "change password" to settings
  app/ide-desktop/lib/assets/change_password.svg
  app/ide-desktop/lib/dashboard/e2e/actions.ts
  app/ide-desktop/lib/dashboard/e2e/api.ts
  app/ide-desktop/lib/dashboard/e2e/changePassword.spec.ts
  app/ide-desktop/lib/dashboard/e2e/changePasswordModal.spec.ts
  app/ide-desktop/lib/dashboard/src/components/Input.tsx
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/ChangePasswordModal.tsx
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/Settings/AccountSettingsTab.tsx
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/Settings/OrganizationSettingsTab.tsx
  app/ide-desktop/lib/dashboard/src/layouts/dashboard/UserMenu.tsx
  app/ide-desktop/lib/dashboard/src/utilities/ShortcutManager.ts
  app/ide-desktop/lib/dashboard/src/utilities/validation.ts
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#9189 Fix bad merge
  app/ide-desktop/lib/dashboard/src/services/RemoteBackend.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#9192 Fix CB reloading when vis-selector opened
  app/ide-desktop/lib/dashboard/src/App.tsx
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard, -gui2

#9183 Update dry run warning messages to tell user to press Record Once button
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload_Table.enso
Labels: CI: No changelog needed

#9196 Allow setting CB viz type; determine default from suggestion type info.
  app/gui2/e2e/componentBrowser.spec.ts
  app/gui2/mock/engine.ts
  app/gui2/shared/ast/index.ts
  app/gui2/shared/ast/tree.ts
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/components/GraphEditor/GraphVisualization.vue
  app/gui2/src/util/ast/__tests__/abstract.test.ts
  app/gui2/stories/UserDefinedVisualization.story.vue
  app/gui2/stories/mockSuggestions.json
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#9134 Clearer warnings in license review
  build/build/src/engine/context.rs
  distribution/engine/THIRD-PARTY/NOTICE
  distribution/engine/THIRD-PARTY/com.google.guava.listenablefuture-9999.0-empty-to-avoid-conflict-with-guava/NOTICES
  distribution/lib/Standard/Google_Api/0.0.0-dev/THIRD-PARTY/NOTICE
  distribution/lib/Standard/Google_Api/0.0.0-dev/THIRD-PARTY/com.google.guava.listenablefuture-9999.0-empty-to-avoid-conflict-with-guava/NOTICES
  project/GatherLicenses.scala
  project/src/main/scala/licenses/DependencySummary.scala
  project/src/main/scala/licenses/backend/GithubHeuristic.scala
  project/src/main/scala/licenses/frontend/DependencyFilter.scala
  project/src/main/scala/licenses/frontend/SbtLicenses.scala
  project/src/main/scala/licenses/report/Diagnostic.scala
  project/src/main/scala/licenses/report/HTMLWriter.scala
  project/src/main/scala/licenses/report/Report.scala
  project/src/main/scala/licenses/report/Review.scala
  project/src/main/scala/licenses/report/WithDiagnostics.scala
  project/src/main/scala/licenses/report/WithWarnings.scala
  tools/legal-review-helper/static/inject.js
  tools/legal-review/Google_Api/com.google.guava.listenablefuture-9999.0-empty-to-avoid-conflict-with-guava/copyright-add
  tools/legal-review/Google_Api/report-state
  tools/legal-review/engine/com.google.guava.listenablefuture-9999.0-empty-to-avoid-conflict-with-guava/copyright-add
  tools/legal-review/engine/report-state
Labels: CI: Ready to merge, CI: No changelog needed

#9003 Re-enable vibrancy and add support for Linux
  app/gui2/mock/index.ts
  app/gui2/src/config.json
  app/gui2/src/main.ts
  app/ide-desktop/lib/client/src/config.ts
  app/ide-desktop/lib/client/src/detect.ts
  app/ide-desktop/lib/client/src/index.ts
  app/ide-desktop/lib/content-config/src/config.json
  app/ide-desktop/lib/content/src/entrypoint.ts
  app/ide-desktop/lib/dashboard/src/App.tsx
  app/ide-desktop/lib/dashboard/src/entrypoint.ts
  app/ide-desktop/lib/dashboard/src/index.tsx
  app/ide-desktop/lib/dashboard/src/tailwind.css
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#9197 Fix area select regression
  app/gui2/e2e/actions.ts
  app/gui2/e2e/customExpect.ts
  app/gui2/e2e/locate.ts
  app/gui2/e2e/selectingNodes.spec.ts
  app/gui2/src/composables/__tests__/selection.test.ts
  app/gui2/src/composables/selection.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, --regression, -gui2

#9163 Fix Component Browser aliases
  app/gui2/src/components/ComponentBrowser/filtering.ts
  app/gui2/src/stores/suggestionDatabase/documentation.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui2

#9075 Move benchmark download tool and visualization to the CI
  .github/workflows/bench-upload.yml
  tools/performance/engine-benchmarks/README.md
  tools/performance/engine-benchmarks/bench_download.py
  tools/performance/engine-benchmarks/bench_tool/__init__.py
  tools/performance/engine-benchmarks/bench_tool/bench_results.py
  tools/performance/engine-benchmarks/bench_tool/gh.py
  tools/performance/engine-benchmarks/bench_tool/git.py
  tools/performance/engine-benchmarks/bench_tool/remote_cache.py
  tools/performance/engine-benchmarks/bench_tool/requirements.txt
  tools/performance/engine-benchmarks/bench_tool/template_render.py
  tools/performance/engine-benchmarks/bench_tool/test_bench_results.py
  tools/performance/engine-benchmarks/bench_tool/test_gh.py
  tools/performance/engine-benchmarks/bench_tool/test_git.py
  tools/performance/engine-benchmarks/bench_tool/test_remote_cache.py
  tools/performance/engine-benchmarks/bench_tool/test_website_regen.py
  tools/performance/engine-benchmarks/bench_tool/utils.py
  tools/performance/engine-benchmarks/bench_tool/website.py
  tools/performance/engine-benchmarks/templates/template_jinja.html
  tools/performance/engine-benchmarks/website_regen.py
Labels: CI: Ready to merge, CI: No changelog needed

#9205 Represent documentation in AST, load into Node
  app/gui2/shared/ast/index.ts
  app/gui2/shared/ast/mutableModule.ts
  app/gui2/shared/ast/parse.ts
  app/gui2/shared/ast/tree.ts
  app/gui2/src/stores/graph/graphDatabase.ts
  app/gui2/src/util/ast/node.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#9191 Switch to AJV for validating JSON Schema
  app/ide-desktop/.vscode/react.code-snippets
  app/ide-desktop/eslint.config.js
  app/ide-desktop/lib/dashboard/package.json
  app/ide-desktop/lib/dashboard/src/components/JSONSchemaInput.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/DataLinkInput.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetProperties.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetSearchBar.tsx
  app/ide-desktop/lib/dashboard/src/layouts/DataLinkInput.tsx
  app/ide-desktop/lib/dashboard/src/modals/UpsertDataLinkModal.tsx
  app/ide-desktop/lib/dashboard/src/utilities/__tests__/jsonSchema.test.ts
  app/ide-desktop/lib/dashboard/src/utilities/error.ts
  app/ide-desktop/lib/dashboard/src/utilities/jsonSchema.ts
  app/ide-desktop/lib/dashboard/src/utilities/validateDataLink.ts
  app/ide-desktop/lib/types/globals.d.ts
  package-lock.json
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard, x-refactor

#9220 Fix benchmark run build
  build/build/src/engine/context.rs
Labels: CI: Ready to merge, CI: No changelog needed

#9207 Add workaround for huge idmap diffs
  .vscode/launch.json
  app/gui2/src/stores/project/computedValueRegistry.ts
  app/gui2/src/stores/project/index.ts
  app/gui2/ydoc-server/__tests__/edits.bench.ts
  app/gui2/ydoc-server/edits.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, --low-performance, -gui2

#9203 Fix matching JS strings
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/StringLiteralBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/syntax/HostValueToEnsoNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/foreign/CoerceNothing.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/foreign/ForeignMethodCallNode.java
  test/Base_Tests/src/Semantic/Case_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9218 Display comments
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/GraphNodeComment.vue
  app/gui2/src/stores/graph/graphDatabase.ts
  app/gui2/src/stores/graph/index.ts
  app/gui2/src/util/ast/node.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#9217 Ensure objects obtained from Y.Js are not modified
  app/gui2/shared/ast/token.ts
  app/gui2/shared/ast/tree.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#9130 Small visualization fixes
  app/gui2/e2e/selectingNodes.spec.ts
  app/gui2/shared/yjsModel.ts
  app/gui2/src/bindings.ts
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/GraphNodes.vue
  app/gui2/src/components/GraphEditor/GraphVisualization.vue
  app/gui2/src/components/VisualizationContainer.vue
  app/gui2/src/components/visualizations/TableVisualization.vue
  app/gui2/src/composables/events.ts
  app/gui2/src/composables/selection.ts
  app/gui2/src/providers/visualizationConfig.ts
  app/gui2/src/stores/graph/index.ts
  app/gui2/ydoc-server/edits.ts
  app/gui2/ydoc-server/fileFormat.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#9222 PathProgressBodyHandler does not return immediately
  lib/scala/downloader/src/main/java/org/enso/downloader/http/PathProgressBodyHandler.java
  lib/scala/downloader/src/main/java/org/enso/downloader/http/StringProgressBodyHandler.java
  lib/scala/downloader/src/test/java/org/enso/downloader/http/HttpDownloaderTest.java
Labels: CI: Ready to merge, CI: No changelog needed

#8986 Implement Table.replace for the database backend
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Array_Like_Helpers.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/DB_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/IR/From_Spec.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Replace_Helpers.enso
  test/Base_Tests/src/Data/Vector_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Replace_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Main.enso
  test/Table_Tests/src/Common_Table_Operations/Map_To_Table_Spec.enso
Labels: CI: Ready to merge, CI: Clean build required
