Repository enso-org/enso, pull requests merged in 2024-07, with the labels that each got.

#10417 Adjust Colours.
  app/gui2/src/components/CodeEditor.vue
  app/gui2/src/util/colors.ts
  app/ide-desktop/lib/dashboard/src/tailwind.css
  app/ide-desktop/lib/dashboard/tailwind.config.js
  app/ide-desktop/lib/project-manager-shim/src/projectManagerShimMiddleware.ts
  app/ide-desktop/package.json
  distribution/lib/Standard/Base/0.0.0-dev/package.yaml
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10407 Add project/duplicate endpoint
  docs/language-server/protocol-project-manager.md
  lib/scala/json-rpc-server-test/src/main/scala/org/enso/jsonrpc/test/JsonRpcServerTestKit.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/file/BlockingFileSystem.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/file/FileSystem.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/repository/ProjectFileRepository.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/repository/ProjectRepository.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/protocol/ClientController.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/protocol/JsonRpc.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/protocol/ProjectManagementApi.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/ProjectDuplicateHandler.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/MoveProjectDirCmd.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectService.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectServiceApi.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/filesystem/FileSystemService.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/filesystem/FileSystemServiceApi.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/service/filesystem/FileSystemServiceSpec.scala
Labels: CI: Ready to merge, CI: No changelog needed

#10416 Top-level add-node button creates disconnected component.
  app/gui2/e2e/componentBrowser.spec.ts
  app/gui2/src/components/GraphEditor.vue
Labels: CI: Ready to merge, CI: No changelog needed

#10424 Fade the background and darken text.
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Text/Text.tsx
  app/ide-desktop/lib/dashboard/src/tailwind.css
Labels: CI: Ready to merge, CI: No changelog needed

#10408 Disable UpdatingEditionProvider when running Enso CLI
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/runner/src/main/scala/org/enso/runner/DependencyPreinstaller.scala
  lib/scala/edition-updater/src/main/scala/org/enso/editions/updater/EditionManager.scala
  lib/scala/edition-updater/src/main/scala/org/enso/editions/updater/UpdatingEditionProvider.scala
  lib/scala/editions/src/main/scala/org/enso/editions/provider/EditionProvider.scala
  lib/scala/editions/src/main/scala/org/enso/editions/provider/FileSystemEditionProvider.scala
  lib/scala/editions/src/test/scala/org/enso/editions/EditionResolverSpec.scala
Labels: CI: No changelog needed, CI: Clean build required

#10430 Fix issues with Date.new Widgets and Some Viz Fixes.
  app/gui2/src/components/visualizations/JSONVisualization/JsonValueWidget.vue
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Metadata.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Helpers.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10362 Visualise excelwork book sheets, db tables/schemas and add node adding gets to query them
  app/gui2/src/components/visualizations/JSONVisualization/JsonObjectWidget.vue
  app/gui2/src/components/visualizations/TableVisualization.vue
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Connection.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Workbook.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
  test/Visualization_Tests/src/Table_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10436 Fix searchbar visuals
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Button/Button.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Button/CloseButton.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Text/Text.tsx
  app/ide-desktop/lib/dashboard/src/components/SvgMask.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/Label.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetSearchBar.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Labels.tsx
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#10434 Separating `list` from `read` function and other small tweaks.
  CHANGELOG.md
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Metadata.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File_Format.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Dialect.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Display_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Parse_To_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Faker.enso
  test/AWS_Tests/src/S3_Spec.enso
  test/Base_Tests/src/System/File_Spec.enso
  test/Benchmarks/src/Natural_Order_Sort.enso
  test/Benchmarks/src/Number_Parse.enso
  test/Benchmarks/src/Text/Compare.enso
  test/Benchmarks/src/Text/Contains.enso
  test/Benchmarks/src/Text/Pretty.enso
  test/Benchmarks/src/Text/Reverse.enso
  test/Table_Tests/src/IO/Delimited_Read_Spec.enso
Labels: CI: Ready to merge

#10439 Decimal in table viz
  app/gui2/src/components/visualizations/TableVisualization.vue
Labels: CI: Ready to merge, CI: No changelog needed

#10444 Auto create the root folder if not present.
  app/ide-desktop/lib/dashboard/src/services/LocalBackend.ts
  app/ide-desktop/lib/dashboard/src/services/ProjectManager.ts
  app/ide-desktop/lib/project-manager-shim/src/projectManagerShimMiddleware.ts
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/Cli.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/ProjectManager.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/command/filesystem/FileSystemExistsCommand.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/protocol/FileSystemManagementApi.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/protocol/JsonRpc.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/filesystem/FileSystemService.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/filesystem/FileSystemServiceApi.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/service/filesystem/FileSystemServiceSpec.scala
Labels: CI: Ready to merge, CI: No changelog needed

#10396 External documentation
  CHANGELOG.md
  app/gui2/src/bindings.ts
  app/gui2/src/components/CircularMenu.vue
  app/gui2/src/components/ComponentBrowser/DocumentationPanel.vue
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/stores/suggestionDatabase/entry.ts
Labels: CI: Ready to merge

#10413 Doc editor and code editor are toggleable docks
  app/gui2/e2e/actions.ts
  app/gui2/src/App.vue
  app/gui2/src/assets/base.css
  app/gui2/src/components/BottomPanel.vue
  app/gui2/src/components/CodeEditor.vue
  app/gui2/src/components/DockPanel.vue
  app/gui2/src/components/DocumentationEditor.vue
  app/gui2/src/components/ExtendedMenu.vue
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/NodeWidgetTree.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetVector.vue
  app/gui2/src/components/MarkdownEditor.vue
  app/gui2/src/components/MarkdownEditor/FormattingToolbar.vue
  app/gui2/src/components/MarkdownEditor/MarkdownEditorImpl.vue
  app/gui2/src/components/PlusButton.vue
  app/gui2/src/components/ResizeHandles.vue
  app/gui2/src/components/TopBar.vue
  app/gui2/src/composables/events.ts
  app/gui2/src/providers/widgetRegistry/__tests__/editHandler.test.ts
Labels: CI: Ready to merge, CI: No changelog needed

#10445 Tune Text.trim, fix for Text.split
  CHANGELOG.md
  app/gui2/src/stores/graph/index.ts
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Location.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Metadata.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/JDBC_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Connection.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Column_Operation.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Simple_Expression.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Test_Reporter.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Helpers.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Preprocessor.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
  test/Base_Tests/src/Data/Text_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Derived_Columns_Spec.enso
Labels: CI: Ready to merge

#10449 Starting to clean up exporting Problem_Behavior constructor refactor.
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/XML.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Data_Link.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Problem_Behavior.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Array_Like_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/Write_Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File_Format.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/Output_Stream.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10451 Amortize the startup cost of some components
  engine/language-server/src/main/java/org/enso/languageserver/boot/resource/TruffleContextInitialization.java
  engine/language-server/src/main/java/org/enso/languageserver/boot/resource/YdocInitialization.java
  engine/language-server/src/main/scala/org/enso/languageserver/boot/ComponentSupervisor.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/ResourcesInitialization.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/RuntimeKiller.scala
  engine/runner/src/main/java/org/enso/runner/Main.java
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#10437 Refactor database dialect types
  distribution/lib/Standard/AWS/0.0.0-dev/src/Database/Redshift/Internal/Redshift_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Dialect.enso
  test/Table_Tests/src/Database/Types/SQLite_Type_Mapping_Spec.enso
  test/Table_Tests/src/Database/Upload_Spec.enso
Labels: CI: No changelog needed

#10454 Batch Two of Problem_Behavior
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3_File.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/SQLite_Format.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Extensions/Upload_Database_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Extensions/Upload_In_Memory_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Common/Lookup_Query_Helper.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Type_Mapping.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQL_Type_Mapping.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Type_Mapping.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload_Table.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Image_File_Format.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Connection.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Type_Mapping.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data_Formatter.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Delimited/Delimited_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Extensions/Table_Conversions.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Add_Row_Number.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Add_Running.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Column_Ops.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Delimited_Reader.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Delimited_Writer.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Excel_Reader.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Fan_Out.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Filter_Condition_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Java_Problems.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Join_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Lookup_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Parse_To_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Problem_Builder.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Replace_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Split_Tokenize.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Storage.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Ref.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10461 Final step removing the Problem_Behavior publishing.
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Problem_Behavior.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Array_Like_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  engine/runtime-parser/src/test/java/org/enso/compiler/core/EnsoParserTest.java
  test/Base_Tests/src/Data/Ordering_Spec.enso
  test/Base_Tests/src/Data/Text/Encoding_Spec.enso
  test/Base_Tests/src/Data/Vector_Spec.enso
  test/Base_Tests/src/System/File_Spec.enso
  test/Base_Tests/src/System/Reporting_Stream_Decoder_Spec.enso
  test/Base_Tests/src/System/Reporting_Stream_Encoder_Spec.enso
  test/Exploratory_Benchmarks/src/Table/Enso_Callback.enso
  test/Exploratory_Benchmarks/src/Table/Helpers.enso
  test/Table_Tests/src/Common_Table_Operations/Add_Row_Number_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Aggregate_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Conversion_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Core_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Cross_Tab_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Distinct_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Expression_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Filter_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Integration_Tests.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Cross_Join_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Join_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Lookup_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Union_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Zip_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Select_Columns_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Transpose_Spec.enso
  test/Table_Tests/src/Formatting/Parse_Values_Spec.enso
  test/Table_Tests/src/IO/Delimited_Read_Spec.enso
  test/Table_Tests/src/IO/Delimited_Write_Spec.enso
  test/Table_Tests/src/IO/Excel_Spec.enso
  test/Table_Tests/src/In_Memory/Aggregate_Column_Spec.enso
  test/Table_Tests/src/In_Memory/Builders_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Xml_Spec.enso
  test/Table_Tests/src/Util.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10463 Deserialise large integer and decimals from JSON automatically.
  app/gui2/src/components/visualizations/JSONVisualization/JsonPrimitiveWidget.vue
  app/gui2/src/components/visualizations/TableVisualization.vue
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Decimal.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json/Extensions.enso
  test/Base_Tests/src/Data/Json_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10374 Support for --jvm option in Enso runner
  .gitignore
  CHANGELOG.md
  build.sbt
  build/build/paths.yaml
  build/build/src/engine/context.rs
  build/build/src/enso.rs
  distribution/bin/enso
  distribution/bin/enso.bat
  docs/infrastructure/native-image.md
  engine/runner/src/main/java/org/enso/runner/Main.java
  engine/runtime/src/main/java/org/enso/interpreter/OptionsHelper.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/runner/Runner.scala
  project/NativeImage.scala
Labels: CI: Ready to merge, CI: Clean build required

#10466 Stop publishing `Postgres` constructor, update `Postgres_Details.Postgres` to `Postgres.Server`.
  CHANGELOG.md
  distribution/lib/Standard/AWS/0.0.0-dev/src/Database/Redshift/Internal/Redshift_Dialect.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json/Extensions.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection_Details.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Data_Link/Postgres_Data_Link.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Postgres.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Data_Link_Setup.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Connection.enso
  std-bits/database/src/main/java/org/enso/database/postgres/PostgresConnectionDetailsSPI.java
  test/Table_Tests/src/Database/Postgres_Spec.enso
Labels: CI: Ready to merge

#10462 Low-hanging perf improvements
  build.sbt
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/IRPass.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/optimise/LambdaConsolidate.scala
  lib/scala/distribution-manager/src/main/scala/org/enso/distribution/locking/ThreadSafeFileLockManager.scala
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#10315 Replace `Button variant="custom"` with appropriate variant whenever possible
  app/ide-desktop/lib/dashboard/src/components/styled/ButtonRow.tsx
  app/ide-desktop/lib/dashboard/src/components/styled/HorizontalMenuBar.tsx
  app/ide-desktop/lib/dashboard/src/components/styled/SettingsInput.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetVersions/AssetVersion.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Drive.tsx
  app/ide-desktop/lib/dashboard/src/layouts/DriveBar.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/ChangePasswordForm.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/KeyboardShortcutsSettingsSection.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/MembersSettingsSection.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/UserGroupsSettingsSection.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/UserRow.tsx
  app/ide-desktop/lib/dashboard/src/layouts/UserBar.tsx
  app/ide-desktop/lib/dashboard/src/modals/CaptureKeyboardShortcutModal.tsx
  app/ide-desktop/lib/dashboard/src/modals/ConfirmDeleteModal.tsx
  app/ide-desktop/lib/dashboard/src/modals/ConfirmDeleteUserModal.tsx
  app/ide-desktop/lib/dashboard/src/modals/DuplicateAssetsModal.tsx
  app/ide-desktop/lib/dashboard/src/modals/ManageLabelsModal.tsx
  app/ide-desktop/lib/dashboard/src/modals/NewLabelModal.tsx
  app/ide-desktop/lib/dashboard/src/modals/NewUserGroupModal.tsx
  app/ide-desktop/lib/dashboard/src/modals/UpsertDatalinkModal.tsx
  app/ide-desktop/lib/dashboard/src/modals/UpsertSecretModal.tsx
  app/ide-desktop/lib/dashboard/tailwind.config.js
Labels: p-lowest, CI: Ready to merge, CI: No changelog needed, x-chore, g-dashboard

#10347 Persist a subset of IdMap
  app/gui2/shared/languageServer.ts
  app/gui2/shared/languageServerTypes.ts
  app/gui2/ydoc-server/languageServerSession.ts
  app/gui2/ydoc-server/serialization.ts
Labels: CI: Ready to merge, CI: No changelog needed

#10456 Replace presigned S3 URL with lambda request
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Existing_Enso_Asset.enso
  std-bits/base/src/main/java/org/enso/base/enso_cloud/EnsoSecretReader.java
  tools/http-test-helper/src/main/java/org/enso/shttp/cloud_mock/CloudRoot.java
Labels: CI: Ready to merge, CI: No changelog needed

#10423 Dashboard fixes
  app/ide-desktop/lib/assets/computer.svg
  app/ide-desktop/lib/assets/not_cloud.svg
  app/ide-desktop/lib/dashboard/src/components/MenuEntry.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/AssetRow.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetPanel.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetProperties.tsx
  app/ide-desktop/lib/dashboard/src/layouts/CategorySwitcher.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/settingsData.tsx
  app/ide-desktop/lib/dashboard/src/layouts/TabBar.tsx
  app/ide-desktop/lib/dashboard/src/layouts/UserBar.tsx
  app/ide-desktop/lib/dashboard/src/modals/ConfirmDeleteModal.tsx
  app/ide-desktop/lib/dashboard/src/text/english.json
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#10433 Fix opening projects
  app/ide-desktop/lib/dashboard/e2e/createAsset.spec.ts
  app/ide-desktop/lib/dashboard/e2e/driveView.spec.ts
  app/ide-desktop/lib/dashboard/e2e/startModal.spec.ts
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Button/Button.tsx
  app/ide-desktop/lib/dashboard/src/components/Autocomplete.tsx
  app/ide-desktop/lib/dashboard/src/components/ErrorBoundary.tsx
  app/ide-desktop/lib/dashboard/src/components/StatelessSpinner.tsx
  app/ide-desktop/lib/dashboard/src/components/Suspense.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/AssetRow.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/Permission.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/ProjectIcon.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/ProjectNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/column.ts
  app/ide-desktop/lib/dashboard/src/components/dashboard/column/NameColumn.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/column/SharedWithColumn.tsx
  app/ide-desktop/lib/dashboard/src/events/assetEvent.ts
  app/ide-desktop/lib/dashboard/src/hooks/gtagHooks.ts
  app/ide-desktop/lib/dashboard/src/layouts/AssetContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetProperties.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetsTable.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Chat.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Drive.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Editor.tsx
  app/ide-desktop/lib/dashboard/src/layouts/TabBar.tsx
  app/ide-desktop/lib/dashboard/src/layouts/UserBar.tsx
  app/ide-desktop/lib/dashboard/src/modals/ManagePermissionsModal.tsx
  app/ide-desktop/lib/dashboard/src/pages/dashboard/Dashboard.tsx
  app/ide-desktop/lib/dashboard/src/providers/AuthProvider.tsx
  app/ide-desktop/lib/dashboard/src/providers/SessionProvider.tsx
  app/ide-desktop/lib/dashboard/src/services/RemoteBackend.ts
  app/ide-desktop/lib/dashboard/src/text/english.json
  app/ide-desktop/lib/dashboard/src/utilities/error.ts
  app/ide-desktop/lib/dashboard/src/utilities/newtype.ts
  app/ide-desktop/lib/dashboard/src/utilities/tailwindMerge.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#10431 Share tanstack QueryClient between dashboard and IDE
  .github/CODEOWNERS
  app/gui2/package.json
  app/gui2/src/entrypoint.ts
  app/ide-desktop/lib/common/README.md
  app/ide-desktop/lib/common/package.json
  app/ide-desktop/lib/common/src/queryClient.ts
  app/ide-desktop/lib/common/src/vueQuery.ts
  app/ide-desktop/lib/dashboard/package.json
  app/ide-desktop/lib/dashboard/src/App.tsx
  app/ide-desktop/lib/dashboard/src/entrypoint.ts
  app/ide-desktop/lib/dashboard/src/index.tsx
  app/ide-desktop/lib/dashboard/src/reactQueryClient.ts
  pnpm-lock.yaml
Labels: CI: No changelog needed, CI: Clean build required

#10479 Fix return type for Postgres Decimal division
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Util.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10493 Date Time Pickers, Temporarily Disable Encoding.default
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Locale.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Encoding.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Of_Day.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Zone.enso
  std-bits/base/src/main/java/org/enso/base/Time_Utils.java
  test/Base_Tests/src/Data/Json_Spec.enso
  test/Base_Tests/src/Data/Text/Encoding_Spec.enso
  test/Table_Tests/src/IO/Delimited_Read_Spec.enso
  test/Table_Tests/src/IO/Delimited_Write_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10483 Support re-running failed tests with `runEngineDistribution`
  distribution/lib/Standard/Test/0.0.0-dev/src/Suite.enso
Labels: CI: No changelog needed

#10494 More dashboard fixes
  app/ide-desktop/lib/client/package.json
  app/ide-desktop/lib/client/src/index.ts
  app/ide-desktop/lib/client/watch.ts
  app/ide-desktop/lib/dashboard/package.json
  app/ide-desktop/lib/dashboard/src/components/ContextMenus.tsx
  app/ide-desktop/lib/dashboard/src/layouts/CategorySwitcher.tsx
  app/ide-desktop/lib/dashboard/src/tailwind.css
  app/ide-desktop/lib/dashboard/tailwind.config.js
  pnpm-lock.yaml
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#10502 Rename Organization plan to Enterprise
  app/ide-desktop/lib/dashboard/src/text/english.json
Labels: d-easy, CI: No changelog needed, g-dashboard

#10457 Numeric input does not allow non-numeric value
  CHANGELOG.md
  app/gui2/rust-ffi/src/lib.rs
  app/gui2/shared/ast/ffi.ts
  app/gui2/shared/ast/ffiPolyglot.ts
  app/gui2/shared/ast/tree.ts
  app/gui2/src/components/GraphEditor/widgets/WidgetNumber.vue
  app/gui2/src/components/widgets/NumericInputWidget.vue
Labels: CI: Ready to merge, -gui

#10492 hide row count for some table visualizations
  app/gui2/src/components/visualizations/TableVisualization.vue
Labels: CI: Ready to merge, CI: No changelog needed

#10489 Scope CSS code
  app/gui2/src/App.vue
  app/gui2/src/assets/base.css
  app/gui2/src/assets/main.css
  app/gui2/src/asyncApp.ts
  app/gui2/src/components/visualizations/HeatmapVisualization.vue
  app/gui2/src/components/visualizations/SQLVisualization.vue
  app/gui2/src/components/visualizations/TableVisualization.vue
  app/gui2/src/components/widgets/CheckboxWidget.vue
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui

#10501 Make docker instructions clearer for Postgres
  test/Table_Tests/src/Database/README.md
Labels: CI: No changelog needed

#10499 Add ability to choose a plan in enso devtools
  app/ide-desktop/lib/dashboard/e2e/api.ts
  app/ide-desktop/lib/dashboard/src/App.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Button/ButtonGroup.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Form/Form.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Form/components/Reset.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Form/components/types.ts
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Form/components/useForm.ts
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Form/types.ts
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Radio/RadioGroup.tsx
  app/ide-desktop/lib/dashboard/src/components/Devtools/EnsoDevtools.tsx
  app/ide-desktop/lib/dashboard/src/components/Devtools/ReactQueryDevtools.tsx
  app/ide-desktop/lib/dashboard/src/components/Devtools/index.ts
  app/ide-desktop/lib/dashboard/src/components/Paywall/components/index.ts
  app/ide-desktop/lib/dashboard/src/components/Paywall/index.ts
  app/ide-desktop/lib/dashboard/src/hooks/billing/paywallHooks.ts
  app/ide-desktop/lib/dashboard/src/index.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/MembersSettingsSection.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/UserGroupsSettingsSection.tsx
  app/ide-desktop/lib/dashboard/src/pages/subscribe/Subscribe/components/Card.tsx
  app/ide-desktop/lib/dashboard/src/providers/AuthProvider.tsx
  app/ide-desktop/lib/dashboard/src/services/Backend.ts
  app/ide-desktop/lib/dashboard/src/text/english.json
Labels: CI: No changelog needed, x-chore, g-dashboard

#10511 Fix opening local projects
  app/ide-desktop/lib/dashboard/src/layouts/Editor.tsx
  app/ide-desktop/lib/dashboard/src/pages/dashboard/Dashboard.tsx
  app/ide-desktop/lib/dashboard/src/services/LocalBackend.ts
Labels: CI: Ready to merge, CI: No changelog needed, --regression, g-dashboard

#10509 Record control tweaks
  CHANGELOG.md
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/RecordControl.vue
  app/gui2/src/components/TopBar.vue
  app/gui2/src/stores/project/executionContext.ts
  app/gui2/src/stores/project/index.ts
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload_Table.enso
  engine/runtime/src/main/java/org/enso/interpreter/EnsoLanguage.java
Labels: CI: Ready to merge, -gui

#10442 Expose backend API to IDE
  app/ide-desktop/lib/common/package.json
  app/ide-desktop/lib/common/src/services/Backend.ts
  app/ide-desktop/lib/common/src/text/english.json
  app/ide-desktop/lib/common/src/text/index.ts
  app/ide-desktop/lib/common/src/utilities/data/array.ts
  app/ide-desktop/lib/common/src/utilities/data/dateTime.ts
  app/ide-desktop/lib/common/src/utilities/data/newtype.ts
  app/ide-desktop/lib/common/src/utilities/permissions.ts
  app/ide-desktop/lib/common/src/utilities/uniqueString.ts
  app/ide-desktop/lib/common/tsconfig.json
  app/ide-desktop/lib/dashboard/src/components/MenuEntry.tsx
  app/ide-desktop/lib/dashboard/src/components/Paywall/components/PaywallBulletPoints.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/KeyboardShortcut.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/Permission.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/column/columnUtils.ts
  app/ide-desktop/lib/dashboard/src/hooks/billing/FeaturesConfiguration.ts
  app/ide-desktop/lib/dashboard/src/hooks/toastAndLogHooks.ts
  app/ide-desktop/lib/dashboard/src/layouts/CategorySwitcher.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/settingsData.tsx
  app/ide-desktop/lib/dashboard/src/layouts/TabBar.tsx
  app/ide-desktop/lib/dashboard/src/modals/AboutModal.tsx
  app/ide-desktop/lib/dashboard/src/pages/subscribe/Subscribe/components/Card.tsx
  app/ide-desktop/lib/dashboard/src/pages/subscribe/Subscribe/getComponentForPlan.tsx
  app/ide-desktop/lib/dashboard/src/pages/subscribe/constants.ts
  app/ide-desktop/lib/dashboard/src/providers/TextProvider.tsx
  app/ide-desktop/lib/dashboard/src/services/Backend.ts
  app/ide-desktop/lib/dashboard/src/services/RemoteBackend.ts
  app/ide-desktop/lib/dashboard/src/text/index.ts
  app/ide-desktop/lib/dashboard/src/utilities/array.ts
  app/ide-desktop/lib/dashboard/src/utilities/dateTime.ts
  app/ide-desktop/lib/dashboard/src/utilities/newtype.ts
  app/ide-desktop/lib/dashboard/src/utilities/permissions.ts
  app/ide-desktop/lib/dashboard/src/utilities/uniqueString.ts
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#10496 reintroduce column sort
  app/gui2/src/components/visualizations/TableVisualization.vue
Labels: CI: Ready to merge, CI: No changelog needed

#10468 Enforce conversion method return type & redefine Comparable
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Any.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Decimal.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Hashset.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Ordering.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Day_Of_Week.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Array_Like_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Ordering_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Header.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/URI.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/IR/From_Spec.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Image.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Matrix.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Multi_Value_Key.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Value_Type.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Group.enso
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/CallableBenchmarks.java
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/EqualsBenchmarks.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/ExecCompilerTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/EqualsConversionsTest.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsAtomNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/HashCodeNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/Comparable.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/CustomComparatorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/HashCallbackNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/LessThanNode.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
  std-bits/base/src/main/java/org/enso/base/ObjectComparator.java
  test/Base_Tests/src/Data/Decimal_Spec.enso
  test/Base_Tests/src/Data/Dictionary_Spec.enso
  test/Base_Tests/src/Data/Numbers_Spec.enso
  test/Base_Tests/src/Data/Ordering/Comparator_Spec.enso
  test/Base_Tests/src/Data/Ordering_Spec.enso
  test/Base_Tests/src/Data/Statistics_Spec.enso
  test/Base_Tests/src/Data/Time/Date_Time_Spec.enso
  test/Base_Tests/src/Data/Vector_Spec.enso
  test/Base_Tests/src/Semantic/Equals_Spec.enso
  test/Benchmarks/src/Table/Internal/Multi_Value_Key.enso
  test/Benchmarks/src/Table/Sorting.enso
  test/Benchmarks/src/Vector/Sort.enso
  test/Benchmarks/src/Vector/Utils.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Join_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Nothing_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Any.enso
Labels: CI: Clean build required

#10515 Speed up EnsoInputStream again
  distribution/lib/Standard/Examples/0.0.0-dev/src/Main.enso
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoFile.java
  test/Benchmarks/src/Main.enso
  test/Benchmarks/src/Table/Csv.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#10481 Add `projectsDirectory` parameter to project endpoint
  docs/language-server/project-manager-http-endpoints.md
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/http/ProjectsEndpoint.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/repository/ProjectFileRepositoryFactory.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/repository/ProjectRepositoryFactory.scala
Labels: CI: Ready to merge, CI: No changelog needed

#10524 Fix logout error due to ensodevtools
  app/ide-desktop/lib/dashboard/src/App.tsx
Labels: CI: No changelog needed, --regression, g-dashboard

#10521 re-add truncated check to column sort
  app/gui2/src/components/visualizations/TableVisualization.vue
Labels: CI: Ready to merge, CI: No changelog needed

#10534 Fix permissions style
  app/ide-desktop/lib/common/src/utilities/permissions.ts
  app/ide-desktop/lib/dashboard/src/utilities/permissions.ts
Labels: CI: No changelog needed

#10533 rename tooltip message, sort sorting for truncated data and re introduce the row label
  app/gui2/src/components/visualizations/TableVisualization.vue
Labels: CI: Ready to merge, CI: No changelog needed

#10518 Snowflake Dialect pt. 4 - reading a column of small integers as Integer type, other type mapping tests
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Column_Fetcher.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Type_Mapping.enso
  std-bits/snowflake/src/main/java/org/enso/snowflake/SnowflakeIntegerColumnMaterializer.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/BigIntegerBuilder.java
  test/Snowflake_Tests/src/Snowflake_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10512 Use ExternalId for NodeId and preserve it through argument deletions.
  app/gui2/e2e/actions.ts
  app/gui2/e2e/collapsingAndEntering.spec.ts
  app/gui2/e2e/componentBrowser.spec.ts
  app/gui2/e2e/graphNodeVisualization.spec.ts
  app/gui2/e2e/rightDock.spec.ts
  app/gui2/e2e/selectingNodes.spec.ts
  app/gui2/e2e/widgets.spec.ts
  app/gui2/eslint.config.js
  app/gui2/lib0-ext.d.ts
  app/gui2/playwright.config.ts
  app/gui2/shared/__tests__/mutableModule.test.ts
  app/gui2/shared/ast/mutableModule.ts
  app/gui2/src/components/CircularMenu.vue
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/components/ComponentBrowser/__tests__/input.test.ts
  app/gui2/src/components/ExtendedMenu.vue
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/GraphNodeOutputPorts.vue
  app/gui2/src/components/GraphEditor/GraphNodeSelection.vue
  app/gui2/src/components/GraphEditor/NodeWidgetTree.vue
  app/gui2/src/components/GraphEditor/collapsing.ts
  app/gui2/src/components/GraphEditor/widgets/WidgetApplication.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetFunction.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetFunction/__tests__/widgetFunctionCallInfo.test.ts
  app/gui2/src/components/GraphEditor/widgets/WidgetNumber.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetText.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetVector.vue
  app/gui2/src/components/MenuButton.vue
  app/gui2/src/components/RecordControl.vue
  app/gui2/src/components/SelectionMenu.vue
  app/gui2/src/components/SvgIcon.vue
  app/gui2/src/components/ToggleIcon.vue
  app/gui2/src/components/lexical/LinkPlugin/autoMatcher.ts
  app/gui2/src/components/visualizations/TableVisualization.vue
  app/gui2/src/composables/keyboard.ts
  app/gui2/src/composables/nodeCreation.ts
  app/gui2/src/composables/stackNavigator.ts
  app/gui2/src/stores/graph/__tests__/graphDatabase.test.ts
  app/gui2/src/stores/graph/graphDatabase.ts
  app/gui2/src/stores/graph/index.ts
  app/gui2/src/util/__tests__/array.test.ts
  app/gui2/src/util/__tests__/callTree.test.ts
  app/gui2/src/util/callTree.ts
  app/gui2/tsconfig.app.json
  app/gui2/tsconfig.story.json
  app/gui2/vite.config.ts
  app/gui2/vitest.config.ts
Labels: CI: Ready to merge, CI: Keep up to date, CI: No changelog needed, -gui

#10540 Fix devtools show
  app/ide-desktop/lib/dashboard/src/App.tsx
  app/ide-desktop/lib/dashboard/src/layouts/CategorySwitcher.tsx
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#10523 Add shortcuts.md
  app/gui2/shortcuts.md
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#10536 `engine-runner` shall not depend on `language-server`
  build.sbt
  engine/language-server/src/main/java/org/enso/languageserver/boot/LanguageServerRunner.java
  engine/language-server/src/main/scala/org/enso/languageserver/boot/LanguageServerApp.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/LanguageServerConfig.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/data/Config.scala
  engine/language-server/src/main/scala/org/enso/languageserver/libraries/handler/LibraryPublishHandler.scala
  engine/language-server/src/test/java/org/enso/languageserver/LanguageServerDependenciesTest.java
  engine/language-server/src/test/scala/org/enso/languageserver/boot/resource/RepoInitializationSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/filemanager/ContentRootManagerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/runtime/ContextEventsListenerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/SuggestionsHandlerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/binary/BaseBinaryServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/FileManagerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/VcsManagerTest.scala
  engine/runner-common/src/main/java/org/enso/runner/common/LanguageServerApi.java
  engine/runner-common/src/main/java/org/enso/runner/common/WrongOption.java
  engine/runner-common/src/main/scala/org/enso/runner/common/CompilerBasedDependencyExtractor.scala
  engine/runner-common/src/main/scala/org/enso/runner/common/ProfilingConfig.scala
  engine/runner/src/main/java/org/enso/runner/Main.java
  engine/runner/src/main/scala/org/enso/runner/DependencyPreinstaller.scala
  engine/runner/src/main/scala/org/enso/runner/ProjectUploader.scala
  engine/runner/src/test/java/org/enso/runner/EngineRunnerDependenciesTest.java
  project/NativeImage.scala
  tools/legal-review/engine/report-state
Labels: CI: No changelog needed, CI: Clean build required

#10546 Move warning msg below viz
  CHANGELOG.md
  app/gui2/src/components/GraphEditor/GraphNode.vue
Labels: CI: Ready to merge, -gui

#10522 Optimize assets table
  app/ide-desktop/lib/common/src/utilities/data/newtype.ts
  app/ide-desktop/lib/dashboard/package.json
  app/ide-desktop/lib/dashboard/src/components/EditableSpan.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/AssetRow.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/DatalinkNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/DirectoryNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/FileNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/ProjectNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/SecretNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/column/SharedWithColumn.tsx
  app/ide-desktop/lib/dashboard/src/events/assetEvent.ts
  app/ide-desktop/lib/dashboard/src/events/assetListEvent.ts
  app/ide-desktop/lib/dashboard/src/hooks/eventHooks.ts
  app/ide-desktop/lib/dashboard/src/layouts/AssetContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetPanel.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetProperties.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetVersions/AssetVersion.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetVersions/AssetVersions.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetsTable.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetsTable/EventListProvider.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetsTableContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/layouts/CategorySwitcher.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Drive.tsx
  app/ide-desktop/lib/dashboard/src/layouts/DriveBar.tsx
  app/ide-desktop/lib/dashboard/src/layouts/GlobalContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings.tsx
  app/ide-desktop/lib/dashboard/src/modals/DuplicateAssetsModal.tsx
  app/ide-desktop/lib/dashboard/src/pages/dashboard/Dashboard.tsx
  app/ide-desktop/lib/dashboard/src/utilities/AssetTreeNode.ts
  app/ide-desktop/lib/dashboard/src/utilities/newtype.ts
  pnpm-lock.yaml
Labels: p-high, CI: Ready to merge, CI: No changelog needed, g-dashboard, x-refactor

#10548 Add paragraph icon
  app/gui2/src/assets/icons.svg
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#10043 Add ExportImportResolutionBenchmark
  build.sbt
  docs/infrastructure/sbt.md
  engine/runtime-benchmarks/src/main/java/org/enso/compiler/benchmarks/exportimport/ExportImportResolutionBenchmark.java
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#10553 Underline syntax errors in VSCode
  tools/enso4igv/src/main/java/org/enso/tools/enso4igv/enso/EnsoErrorProvider.java
Labels: CI: No changelog needed, CI: Clean build required

#10549 Mitigate Language Server visualizations DOS scenario on startup
  build.sbt
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/text/OpenBufferHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/text/OpenFileHandler.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/JobExecutionEngine.scala
Labels: CI: No changelog needed

#10513 Cloud file browser
  CHANGELOG.md
  app/gui2/src/App.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetCloudBrowser.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui2/src/components/widgets/FileBrowserWidget.vue
  app/gui2/src/composables/backend.ts
  app/gui2/src/composables/vueQuery.ts
  app/gui2/src/entrypoint.ts
  app/gui2/src/providers/backend.ts
  app/gui2/src/util/symbols.ts
  app/ide-desktop/lib/common/package.json
  app/ide-desktop/lib/common/src/backendQuery.ts
  app/ide-desktop/lib/common/src/types.d.ts
  app/ide-desktop/lib/common/src/utilities/data/object.ts
  app/ide-desktop/lib/dashboard/src/App.tsx
  app/ide-desktop/lib/dashboard/src/TestAppRunner.tsx
  app/ide-desktop/lib/dashboard/src/hooks/backendHooks.ts
  app/ide-desktop/lib/dashboard/src/layouts/Editor.tsx
  app/ide-desktop/lib/dashboard/src/pages/dashboard/Dashboard.tsx
  app/ide-desktop/lib/dashboard/src/utilities/object.ts
  pnpm-lock.yaml
Labels: CI: Ready to merge

#10554 Linting, XML to_table and fix JSON viz for XML
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Map.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/XML.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Extensions/Table_Conversions.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
  test/Table_Tests/src/In_Memory/Table_Conversion_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10273 Fix context lock removal
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/command/SetExecutionEnvironmentCommand.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/execution/ContextLock.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/execution/Locking.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/job/ExecuteExpressionJob.java
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/DestroyContextCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/ReentrantLocking.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/DetachVisualizationJob.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ExecuteJob.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/UpsertVisualizationJob.scala
Labels: CI: No changelog needed

#10528 Snowflake Dialect pt. 5
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Dialect.enso
  test/Snowflake_Tests/src/Snowflake_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Expression_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Filter_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Cross_Join_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Join_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Main.enso
  test/Table_Tests/src/Common_Table_Operations/Map_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Missing_Values_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Nothing_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Text_Cleanse_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10565 Fix flaky test
  app/gui2/e2e/widgets.spec.ts
Labels: CI: Ready to merge, CI: No changelog needed, -ci, -gui

#10404 Fix React warnings
  app/ide-desktop/lib/dashboard/e2e/actions/goToPageActions.ts
  app/ide-desktop/lib/dashboard/e2e/copy.spec.ts
  app/ide-desktop/lib/dashboard/src/components/Link.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/AssetRow.tsx
  app/ide-desktop/lib/dashboard/src/layouts/TabBar.tsx
  app/ide-desktop/lib/dashboard/src/modals/TermsOfServiceModal.tsx
  app/ide-desktop/lib/dashboard/src/pages/dashboard/Dashboard.tsx
  app/ide-desktop/lib/dashboard/src/providers/ProjectsProvider.tsx
Labels: CI: Ready to merge, CI: No changelog needed, x-chore, g-dashboard

#10567 Restore Encoding.Default.
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Encoding.enso
  test/Base_Tests/src/Data/Json_Spec.enso
  test/Base_Tests/src/Data/Text/Encoding_Spec.enso
  test/Table_Tests/src/IO/Delimited_Read_Spec.enso
  test/Table_Tests/src/IO/Delimited_Write_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10552 Single instance
  app/ide-desktop/lib/client/src/authentication.ts
  app/ide-desktop/lib/client/src/bin/server.ts
  app/ide-desktop/lib/client/src/config/parser.ts
  app/ide-desktop/lib/client/src/file-associations.ts
  app/ide-desktop/lib/client/src/index.ts
  app/ide-desktop/lib/client/src/ipc.ts
  app/ide-desktop/lib/client/src/preload.ts
  app/ide-desktop/lib/client/src/project-management.ts
  app/ide-desktop/lib/client/src/url-associations.ts
  app/ide-desktop/lib/dashboard/src/events/AssetListEventType.ts
  app/ide-desktop/lib/dashboard/src/events/assetEvent.ts
  app/ide-desktop/lib/dashboard/src/events/assetListEvent.ts
  app/ide-desktop/lib/dashboard/src/layouts/AssetsTable.tsx
  app/ide-desktop/lib/dashboard/src/pages/dashboard/Dashboard.tsx
  app/ide-desktop/lib/types/globals.d.ts
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-electron, g-dashboard

#10517 Various Decimal usability tweaks
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Decimal.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  test/Base_Tests/src/Data/Decimal_Spec.enso
  test/Base_Tests/src/Data/Json_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10570 Update icons
  app/gui2/src/components/MarkdownEditor/BlockTypeMenu.vue
  app/gui2/src/components/MarkdownEditor/FormatPropertiesBar.vue
Labels: CI: No changelog needed

#10558 Fix issue with documentation panel focus
  app/gui2/e2e/docPanel.spec.ts
  app/gui2/e2e/locate.ts
  app/gui2/e2e/rightDock.spec.ts
  app/gui2/src/components/BottomPanel.vue
  app/gui2/src/components/CodeEditor.vue
  app/gui2/src/components/MarkdownEditor/markdown.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#10500 Reduce the number of log INFO events
  engine/language-server/src/main/java/org/enso/languageserver/boot/resource/DirectoriesInitialization.java
  engine/language-server/src/main/java/org/enso/languageserver/boot/resource/JsonRpcInitialization.java
  engine/language-server/src/main/java/org/enso/languageserver/boot/resource/RepoInitialization.java
  engine/language-server/src/main/java/org/enso/languageserver/boot/resource/SequentialResourcesInitialization.java
  engine/language-server/src/main/java/org/enso/languageserver/boot/resource/TruffleContextInitialization.java
  engine/language-server/src/main/java/org/enso/languageserver/boot/resource/YdocInitialization.java
  engine/language-server/src/main/java/org/enso/languageserver/boot/resource/ZioRuntimeInitialization.java
  engine/language-server/src/main/resources/application.conf
  engine/language-server/src/main/scala/org/enso/languageserver/boot/LanguageServerComponent.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/PathWatcher.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/ReceivesTreeUpdatesHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/RuntimeConnector.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/RuntimeKiller.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/CollaborativeBuffer.scala
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/command/SetExecutionEnvironmentCommand.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/execution/ModuleIndexing.java
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/ReentrantLocking.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/StartBackgroundProcessingJob.scala
  engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java
  engine/runtime/src/main/java/org/enso/interpreter/caches/SuggestionsCache.java
  lib/java/test-utils/src/main/java/org/enso/test/utils/ProjectUtils.java
  lib/scala/library-manager/src/main/scala/org/enso/librarymanager/local/DefaultLocalLibraryProvider.scala
  lib/scala/project-manager/src/main/resources/application.conf
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerBootLoader.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerController.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/ShutdownHookActivator.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/EngineManagementApiSpec.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/RuntimeVersionManagementUserInterface.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/RuntimeVersionManager.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/memory/InMemorySuggestionsRepo.scala
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#10575 Widget Improvements
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Filter_Condition.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/List.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Widget_Helpers.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Simple_Expression.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Value_Type.enso
  test/Base_Tests/src/Data/List_Spec.enso
  test/Base_Tests/src/Data/Range_Spec.enso
  test/Base_Tests/src/Data/Vector_Spec.enso
  test/Base_Tests/src/Widget_Helpers_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10578 Ignore ProcessBuilder logs
  engine/language-server/src/main/resources/application.conf
  lib/scala/project-manager/src/main/resources/application.conf
Labels: CI: Ready to merge, CI: No changelog needed

#10573 Still more dashboard fixes
  .gitignore
  app/dashboard/.gitignore
  app/dashboard/src/components/AriaComponents/Button/Button.tsx
  app/dashboard/src/components/EditableSpan.tsx
  app/dashboard/src/components/JSONSchemaInput.tsx
  app/dashboard/src/components/dashboard/DirectoryNameColumn.tsx
  app/dashboard/src/components/dashboard/column/LabelsColumn.tsx
  app/dashboard/src/components/dashboard/column/SharedWithColumn.tsx
  app/dashboard/src/layouts/AssetProperties.tsx
  app/dashboard/src/layouts/DriveBar.tsx
  app/dashboard/src/layouts/Settings/KeyboardShortcutsSettingsSection.tsx
  app/dashboard/src/layouts/TabBar.tsx
  app/dashboard/src/modals/ProjectLogsModal.tsx
  app/dashboard/src/utilities/jsonSchema.ts
  app/ide-desktop/client/esbuild-config.ts
  app/ide-desktop/client/package.json
  app/ide-desktop/client/src/bin/server.ts
  app/ide-desktop/common/src/text/english.json
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#10560 VSCode: Add support for methods in type body
  tools/enso4igv/src/main/java/org/enso/tools/enso4igv/enso/EnsoStructure.java
  tools/enso4igv/src/test/java/org/enso/tools/enso4igv/enso/EnsoStructureTest.java
Labels: CI: Ready to merge, CI: Keep up to date, CI: No changelog needed

#10584 Auto scroll for all types of drags
  app/dashboard/src/hooks/autoScrollHooks.ts
  app/dashboard/src/layouts/AssetsTable.tsx
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#10572 Always write Config's namespace and dashboard accepts a default one
  app/gui2/project-manager-shim-middleware/index.ts
  lib/scala/pkg/src/main/scala/org/enso/pkg/Config.scala
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#10587 Refactor: split `IrToTruffle::processModule` into smaller sub-methods
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
Labels: CI: Ready to merge, CI: No changelog needed, x-refactor

#10589 Linting fixes.
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Decimal.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Filter_Condition.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Ordering.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Ordering_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Main.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10591 Fix doc panel resizing
  app/gui2/src/components/DockPanel.vue
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui

#10569 Refactor precedence for whitespace changes
  app/gui2/shared/ast/tree.ts
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/ErrorCompilerTest.java
  lib/rust/parser/debug/tests/parse.rs
  lib/rust/parser/src/lexer.rs
  lib/rust/parser/src/macros/built_in.rs
  lib/rust/parser/src/syntax.rs
  lib/rust/parser/src/syntax/operator.rs
  lib/rust/parser/src/syntax/operator/application.rs
  lib/rust/parser/src/syntax/operator/arity.rs
  lib/rust/parser/src/syntax/operator/operand.rs
  lib/rust/parser/src/syntax/operator/reducer.rs
  lib/rust/parser/src/syntax/operator/types.rs
  lib/rust/parser/src/syntax/token.rs
  lib/rust/parser/src/syntax/tree.rs
  lib/rust/parser/src/syntax/treebuilding.rs
  lib/rust/parser/src/syntax/treebuilding/block.rs
  lib/rust/parser/src/syntax/treebuilding/compound_token.rs
  lib/rust/parser/src/syntax/treebuilding/consumer.rs
  lib/rust/parser/src/syntax/treebuilding/whitespace.rs
Labels: CI: Ready to merge, CI: No changelog needed

#10574 Detect compilation while benchmarking
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Type.java
  lib/scala/bench-processor/src/main/java/org/enso/benchmarks/processor/BenchProcessor.java
  std-bits/benchmarks/src/main/java/org/enso/benchmarks/libs/LibBenchRunner.java
  test/Benchmarks/src/Vector/Operations.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#10363 System.exit does proper context hard exit.
  engine/runner/src/main/java/org/enso/runner/Main.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/system/ExitException.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/system/System.java
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/System.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10593 Speeding up Ordering_Comparator
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Ordering_Helpers.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/BinaryOperatorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeConversionNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/argument/ReadArgumentCheckNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoMultiValue.java
Labels: CI: No changelog needed

#10590 Fix pasting external images in docs
  app/gui2/src/components/MarkdownEditor/ImagePlugin/LexicalImage.vue
  app/gui2/src/components/MarkdownEditor/ImagePlugin/index.ts
  app/gui2/src/components/lexical/LinkPlugin/index.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui

#10577 Improve output node
  CHANGELOG.md
  app/gui2/e2e/collapsingAndEntering.spec.ts
  app/gui2/e2e/locate.ts
  app/gui2/src/components/CircularMenu.vue
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphEdge.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/collapsing.ts
  app/gui2/src/components/GraphEditor/widgets/WidgetPort.vue
  app/gui2/src/composables/nodeColors.ts
  app/gui2/src/stores/graph/graphDatabase.ts
  app/gui2/src/stores/graph/index.ts
  app/gui2/src/util/ast/node.ts
Labels: CI: Ready to merge, -gui

#10583 Enable and fix mixed-comparison Decimal tests
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Decimal.enso
  test/Base_Tests/src/Data/Decimal_Spec.enso
Labels: CI: No changelog needed

#10576 Snowflake Dialect pt. 6 - Union, Distinct and other improvements
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/IR/Context.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Type_Mapping.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQL_Type_Mapping.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Type_Mapping.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload_Table.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Image.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Dialect.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Type_Mapping.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Extensions.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Problems.enso
  test/AWS_Tests/src/S3_Spec.enso
  test/Base_Tests/src/Data/Dictionary_Spec.enso
  test/Base_Tests/src/Data/Text/Encoding_Spec.enso
  test/Base_Tests/src/Data/Text_Spec.enso
  test/Base_Tests/src/Data/Vector_Spec.enso
  test/Base_Tests/src/Network/Http_Spec.enso
  test/Base_Tests/src/Random_Spec.enso
  test/Base_Tests/src/Semantic/Meta_Spec.enso
  test/Base_Tests/src/Semantic/Warnings_Spec.enso
  test/Base_Tests/src/System/Reporting_Stream_Encoder_Spec.enso
  test/Geo_Tests/src/Geo_Spec.enso
  test/Snowflake_Tests/src/Snowflake_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Conversion_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Distinct_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Integration_Tests.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Cross_Join_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Join_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Lookup_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Union_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Zip_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Main.enso
  test/Table_Tests/src/Common_Table_Operations/Map_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Nothing_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Select_Columns_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Util.enso
  test/Table_Tests/src/Database/Common/Names_Length_Limits_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Database/SQLite_Spec.enso
  test/Table_Tests/src/Database/Upload_Spec.enso
  test/Table_Tests/src/IO/Delimited_Write_Spec.enso
  test/Table_Tests/src/IO/Excel_Spec.enso
  test/Table_Tests/src/In_Memory/Common_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#10596 remove control + click opening enso in browser
  app/gui2/src/components/visualizations/TableVisualization.vue
Labels: CI: Ready to merge, CI: No changelog needed

#10585 Fixes (including downloading Local projects from nested directories)
  app/dashboard/e2e/actions/EditorPageActions.ts
  app/dashboard/e2e/copy.spec.ts
  app/dashboard/src/components/dashboard/column/SharedWithColumn.tsx
  app/dashboard/src/components/dashboard/columnHeading/SharedWithColumnHeading.tsx
  app/dashboard/src/hooks/projectHooks.ts
  app/dashboard/src/layouts/Editor.tsx
  app/dashboard/src/layouts/TabBar.tsx
  app/dashboard/src/pages/dashboard/Dashboard.tsx
  app/dashboard/src/providers/ProjectsProvider.tsx
  app/ide-desktop/client/src/bin/server.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard, local-project-manager

#10621 Update Codeowners - now the Libs team owns the project template
  .github/CODEOWNERS
Labels: CI: Ready to merge, CI: No changelog needed

#10626 Revert "Persist a subset of IdMap (#10347)"
  app/gui2/shared/languageServer.ts
  app/gui2/shared/languageServerTypes.ts
  app/gui2/ydoc-server/languageServerSession.ts
  app/gui2/ydoc-server/serialization.ts
Labels: CI: No changelog needed

#10602 Prevent re-entrant execution of finalizers
  build/build/src/engine/context.rs
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/semantic/RuntimeManagementTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/ResourceManager.java
  test/Base_Tests/src/Runtime/GC_Example.enso
  test/Base_Tests/src/Runtime/Managed_Resource_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#10607 Visuali fixes in multiselect drop-down
  CHANGELOG.md
  app/gui2/src/components/widgets/DropdownWidget.vue
Labels: CI: Ready to merge, CI: Clean build required, -gui

#10542 initProtocol endpoint returns success when already initialized
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/SessionManagementTest.scala
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required, -language-server

#10612 Snowflake Dialect - pt. 7
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Dialect.enso
  lib/scala/pkg/src/main/resources/default/src/Main.enso
  test/Snowflake_Tests/src/Snowflake_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Aggregate_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Derived_Columns_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Replace_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Text_Cleanse_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Util.enso
  test/Table_Tests/src/Database/Upload_Spec.enso
  test/Table_Tests/src/Util.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10566 Use correct URL for YDoc server on Cloud
  app/dashboard/src/layouts/Editor.tsx
  app/dashboard/src/services/LocalBackend.ts
  app/dashboard/src/services/RemoteBackend.ts
  app/ide-desktop/common/src/services/Backend.ts
Labels: p-high, CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#10629 Fix the OAuth redirect on windows
  app/ide-desktop/client/src/index.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, --regression, g-electron

#10563 Wip/mk/whitespace chars monospace font table viz
  CHANGELOG.md
  app/gui2/src/components/TextFormattingSelector.vue
  app/gui2/src/components/VisualizationContainer.vue
  app/gui2/src/components/visualizations/TableVisualization.vue
Labels: CI: Ready to merge

#10627 Disable Graal-based Ydoc temporarily
  engine/language-server/src/main/java/org/enso/languageserver/boot/resource/YdocInitialization.java
Labels: CI: Ready to merge, CI: No changelog needed

#10642 Disable problematic example
  test/Base_Tests/src/Runtime/Managed_Resource_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10497 Billing Page iteration one
  app/dashboard/e2e/assetsTableFeatures.spec.ts
  app/dashboard/src/assets/credit_card.svg
  app/dashboard/src/components/AriaComponents/Button/Button.tsx
  app/dashboard/src/components/AriaComponents/CopyBlock/CopyBlock.tsx
  app/dashboard/src/components/Result.tsx
  app/dashboard/src/components/styled/SidebarTabButton.tsx
  app/dashboard/src/layouts/AssetProjectSession.tsx
  app/dashboard/src/layouts/AssetProjectSessions.tsx
  app/dashboard/src/layouts/Settings.tsx
  app/dashboard/src/layouts/Settings/SettingsTabType.ts
  app/dashboard/src/layouts/Settings/settingsData.tsx
  app/dashboard/src/layouts/SettingsSidebar.tsx
  app/dashboard/src/providers/BackendProvider.tsx
  app/dashboard/src/services/LocalBackend.ts
  app/dashboard/src/services/RemoteBackend.ts
  app/dashboard/src/services/remoteBackendPaths.ts
  app/ide-desktop/common/src/services/Backend.ts
  app/ide-desktop/common/src/text/english.json
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#10646 Check version
  app/dashboard/src/App.tsx
  app/dashboard/src/components/Devtools/EnsoDevtools.tsx
  app/dashboard/src/layouts/VersionChecker.tsx
  app/dashboard/src/providers/EnsoDevtoolsProvider.tsx
  app/dashboard/src/utilities/github.ts
  app/ide-desktop/common/src/text/english.json
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#10586 Only allow creating single project at a time
  app/dashboard/src/App.tsx
  app/dashboard/src/components/dashboard/AssetRow.tsx
  app/dashboard/src/components/dashboard/DatalinkNameColumn.tsx
  app/dashboard/src/components/dashboard/DirectoryNameColumn.tsx
  app/dashboard/src/components/dashboard/FileNameColumn.tsx
  app/dashboard/src/components/dashboard/ProjectIcon.tsx
  app/dashboard/src/components/dashboard/ProjectNameColumn.tsx
  app/dashboard/src/components/dashboard/SecretNameColumn.tsx
  app/dashboard/src/events/AssetEventType.ts
  app/dashboard/src/events/AssetListEventType.ts
  app/dashboard/src/events/assetEvent.ts
  app/dashboard/src/events/assetListEvent.ts
  app/dashboard/src/hooks/projectHooks.ts
  app/dashboard/src/layouts/AssetContextMenu.tsx
  app/dashboard/src/layouts/AssetsTable.tsx
  app/dashboard/src/layouts/Drive.tsx
  app/dashboard/src/layouts/DriveBar.tsx
  app/dashboard/src/layouts/Editor.tsx
  app/dashboard/src/layouts/TabBar.tsx
  app/dashboard/src/pages/dashboard/Dashboard.tsx
  app/dashboard/src/providers/ProjectsProvider.tsx
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#10597 Space-precedence does not apply to value-level operators
  CHANGELOG.md
  app/gui2/src/util/ast/__tests__/__snapshots__/raw.test.ts.snap
  build/build/paths.yaml
  build/build/src/rust.rs
  build/build/src/rust/enso_linter.rs
  build/ci_utils/src/programs/cargo.rs
  build/cli/src/arg.rs
  build/cli/src/arg/libraries.rs
  build/cli/src/lib.rs
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Statistics.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/Local_File_Write_Strategy.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/JDBC_Connection.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Dialect.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Extensions.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Test.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/semantic/SimpleArithmeticTest.scala
  lib/rust/parser/debug/src/bin/bench_parse.rs
  lib/rust/parser/debug/src/bin/check_syntax.rs
  lib/rust/parser/debug/src/lib.rs
  lib/rust/parser/debug/tests/parse.rs
  lib/rust/parser/src/lexer.rs
  lib/rust/parser/src/macros/built_in.rs
  lib/rust/parser/src/source/code.rs
  lib/rust/parser/src/syntax.rs
  lib/rust/parser/src/syntax/operator.rs
  lib/rust/parser/src/syntax/operator/application.rs
  lib/rust/parser/src/syntax/operator/apply.rs
  lib/rust/parser/src/syntax/operator/arity.rs
  lib/rust/parser/src/syntax/operator/precedence_resolver.rs
  lib/rust/parser/src/syntax/operator/reducer.rs
  lib/rust/parser/src/syntax/operator/types.rs
  lib/rust/parser/src/syntax/token.rs
  lib/rust/parser/src/syntax/tree.rs
  lib/rust/parser/src/syntax/tree/block.rs
  lib/rust/prelude/src/vec.rs
  test/AWS_Tests/src/S3_Spec.enso
  test/Base_Tests/src/Data/Numbers_Spec.enso
  test/Base_Tests/src/Network/Enso_Cloud/Enso_File_Spec.enso
  test/Table_Tests/src/IO/Cloud_Spec.enso
  test/Table_Tests/src/IO/Excel_Spec.enso
Labels: CI: Ready to merge, CI: Clean build required

#10654 Fix list widget reordering
  app/gui2/src/components/widgets/ListWidget.vue
Labels: p-highest, CI: Ready to merge, CI: No changelog needed, --bug, --regression, -gui

#10653 Fix Project Manager shim for GUI
  app/gui2/project-manager-shim-middleware/index.ts
  app/gui2/project-manager-shim-middleware/projectManagement.ts
Labels: p-medium, CI: Ready to merge, CI: No changelog needed, --bug, --regression

#10650 Treat WithWarnings via dedicated @Specialization
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Decimal.enso
  engine/runtime/src/main/java/org/enso/interpreter/runtime/library/dispatch/TypeOfNode.java
Labels: CI: No changelog needed

#10658 Fix Simple Expression issue where column arguments weren't resolved.
  distribution/lib/Standard/Table/0.0.0-dev/src/Simple_Expression.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10645 Provide syntax warnings to Java
  Cargo.lock
  engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Warning.scala
  lib/rust/parser/debug/src/bin/bench_parse.rs
  lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java
  lib/rust/parser/jni/Cargo.toml
  lib/rust/parser/jni/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#10659 Reenable "Local" settings tab
  app/dashboard/src/layouts/CategorySwitcher.tsx
  app/dashboard/src/layouts/Settings/settingsData.tsx
  app/ide-desktop/common/src/text/english.json
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#10656 More detailed logs for locking logic
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/JobExecutionEngine.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/ReentrantLocking.scala
Labels: -tooling, CI: Ready to merge, CI: No changelog needed

#10599 Refactor node layout to handle arbitrary widget sizes, add `Table.new` widget stub
  CHANGELOG.md
  app/gui2/e2e/collapsingAndEntering.spec.ts
  app/gui2/e2e/edgeInteractions.spec.ts
  app/gui2/e2e/locate.ts
  app/gui2/e2e/selectingNodes.spec.ts
  app/gui2/package.json
  app/gui2/shared/ast/ffiPolyglot.ts
  app/gui2/shared/ast/tree.ts
  app/gui2/src/assets/base.css
  app/gui2/src/components/CircularMenu.vue
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphEdge.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/GraphNodeOutputPorts.vue
  app/gui2/src/components/GraphEditor/GraphNodeSelection.vue
  app/gui2/src/components/GraphEditor/GraphNodes.vue
  app/gui2/src/components/GraphEditor/GraphVisualization.vue
  app/gui2/src/components/GraphEditor/NodeWidget.vue
  app/gui2/src/components/GraphEditor/NodeWidgetTree.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetApplication.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetArgumentName.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetBlank.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetCheckbox.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetFunction.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetFunctionName.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetGroup.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetHierarchy.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetIcon.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetNumber.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetPort.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetSelfAccessChain.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetSelfIcon.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetTableEditor.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetText.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetToken.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetTopLevelArgument.vue
  app/gui2/src/components/GraphMouse.vue
  app/gui2/src/components/SelectionBrush.vue
  app/gui2/src/components/SizeTransition.vue
  app/gui2/src/components/SmallPlusButton.vue
  app/gui2/src/components/VisualizationContainer.vue
  app/gui2/src/components/widgets/AutoSizedInput.vue
  app/gui2/src/components/widgets/CheckboxWidget.vue
  app/gui2/src/components/widgets/DropdownWidget.vue
  app/gui2/src/components/widgets/ListWidget.vue
  app/gui2/src/components/widgets/NumericInputWidget.vue
  app/gui2/src/composables/events.ts
  app/gui2/src/composables/navigator.ts
  app/gui2/src/composables/selection.ts
  app/gui2/src/composables/stackNavigator.ts
  app/gui2/src/providers/functionInfo.ts
  app/gui2/src/providers/widgetRegistry.ts
  app/gui2/src/providers/widgetTree.ts
  app/gui2/src/stores/suggestionDatabase/entry.ts
  app/gui2/src/util/ast/__tests__/node.test.ts
  app/gui2/src/util/ast/node.ts
  app/gui2/src/util/callTree.ts
  app/gui2/src/util/symbols.ts
  pnpm-lock.yaml
Labels: CI: Ready to merge, -gui

#10673 Fix doc panel images
  app/gui2/src/components/MarkdownEditor/ImagePlugin/LexicalImage.vue
  app/gui2/src/components/MarkdownEditor/markdown.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui

#10655 Text Format Improvements
  app/gui2/src/components/TextFormattingSelector.vue
  app/gui2/src/components/VisualizationContainer.vue
  app/gui2/src/components/visualizations/TableVisualization.vue
Labels: CI: Ready to merge, CI: No changelog needed

#10672 Fix `date_diff` in Snowflake
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Dialect.enso
  test/Snowflake_Tests/src/Snowflake_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Date_Time_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Derived_Columns_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10671 fix: extended menu button
  app/gui2/src/components/DropdownMenu.vue
  app/gui2/src/components/ExtendedMenu.vue
  app/gui2/src/components/TextFormattingSelector.vue
Labels: CI: Ready to merge, CI: No changelog needed, --regression, -gui

#10614 Implement in-memory and database mixed decimal column comparisons
  CHANGELOG.md
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/comparisons/EqualsComparison.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/comparisons/GreaterComparison.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/comparisons/GreaterOrEqualComparison.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/comparisons/LessComparison.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/comparisons/LessOrEqualComparison.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/comparisons/NumericComparison.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/MixedStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/type/StorageType.java
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/In_Memory/Common_Spec.enso
Labels: CI: Ready to merge, CI: Clean build required

#10661 Atom fields are visible in debugger
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/AtomInteropTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/DebuggingEnsoTest.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/Atom.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/GetFieldNode.java
Labels: CI: Ready to merge, CI: No changelog needed

#10677 Fix `aggregate` after `sort` in DB
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  test/Table_Tests/src/Common_Table_Operations/Aggregate_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Integration_Tests.enso
Labels: CI: No changelog needed

#10647 Fix Data Catalog showing spinners when refetching
  app/dashboard/.prettierignore
  app/dashboard/src/layouts/AssetsTable.tsx
Labels: p-highest, CI: Ready to merge, CI: No changelog needed, --bug, --regression, g-dashboard

#10682 Fix `.git-blame-ignore-refs`
  .git-blame-ignore-revs
Labels: CI: Ready to merge, CI: No changelog needed, x-chore

#10688 Avoid calling wasm parser immediately on widget module load.
  app/gui2/src/components/GraphEditor/widgets/WidgetText.vue
Labels: CI: Ready to merge, CI: No changelog needed

#10683 Ag grid boolean inference turned off for mixed type column
  app/gui2/src/components/visualizations/TableVisualization.vue
Labels: CI: Ready to merge, CI: No changelog needed

#10649 Restructure `app/ide-desktop/client/` for consistency with other modules
  app/eslint.config.mjs
  app/ide-desktop/client/buildInfo.ts
  app/ide-desktop/client/bundle.ts
  app/ide-desktop/client/electron-builder-config.ts
  app/ide-desktop/client/esbuildConfig.ts
  app/ide-desktop/client/fileAssociations.ts
  app/ide-desktop/client/src/authentication.ts
  app/ide-desktop/client/src/config.ts
  app/ide-desktop/client/src/configParser.ts
  app/ide-desktop/client/src/contentConfig.ts
  app/ide-desktop/client/src/debug.ts
  app/ide-desktop/client/src/desktopEnvironment.ts
  app/ide-desktop/client/src/fileAssociations.ts
  app/ide-desktop/client/src/index.ts
  app/ide-desktop/client/src/log.ts
  app/ide-desktop/client/src/preload.ts
  app/ide-desktop/client/src/projectManagement.ts
  app/ide-desktop/client/src/projectManager.ts
  app/ide-desktop/client/src/server.ts
  app/ide-desktop/client/src/urlAssociations.ts
  app/ide-desktop/client/tsconfig.json
  app/ide-desktop/client/watch.ts
Labels: CI: Ready to merge, CI: No changelog needed, x-chore, g-dashboard

#10663 Additional info to debug AccessDenied problems
  build.sbt
  engine/launcher/src/main/scala/org/enso/launcher/Launcher.scala
  engine/launcher/src/test/scala/org/enso/launcher/NativeTest.scala
  engine/launcher/src/test/scala/org/enso/launcher/upgrade/UpgradeSpec.scala
  lib/scala/library-manager-test/src/main/scala/org/enso/librarymanager/published/repository/DummyRepository.scala
  lib/scala/process-utils/src/main/scala/org/enso/process/RunResult.scala
  lib/scala/process-utils/src/main/scala/org/enso/process/WrappedProcess.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/file/BlockingFileSystem.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/file/FileSystemFailure.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/repository/ProjectFileRepository.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectCreationService.scala
  lib/scala/runtime-version-manager-test/src/main/scala/org/enso/runtimeversionmanager/test/NativeTestHelper.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/runner/Command.scala
Labels: CI: Ready to merge, CI: No changelog needed

#10680 Fix copying cell value in grid
  app/gui2/src/components/visualizations/TableVisualization.vue
Labels: CI: Ready to merge, CI: No changelog needed

#10685 Tweaks from client Demo
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Filter_Condition.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Locale.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Filter_Condition_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Ref.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Simple_Expression.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  test/Base_Tests/src/Data/List_Spec.enso
  test/Base_Tests/src/Data/Range_Spec.enso
  test/Base_Tests/src/Data/Vector_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Derived_Columns_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Filter_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Union_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Missing_Values_Spec.enso
  test/Table_Tests/src/Database/Codegen_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9625 Implement Runtime.Context.Dataflow_Stack_Trace for dataflow errors thrown from Enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Runtime.enso
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeErrorsTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/ThrowErrorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EnsoProjectNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/decimal/FloatNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/BitShiftNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/DivNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/GreaterNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/GreaterOrEqualNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/LessNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/LessOrEqualNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/ModNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/ParseIntegerNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/runtime/Context.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoFile.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/hash/HashMapRemoveNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/DataflowError.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/library/dispatch/TypeOfNode.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
  test/Base_Tests/src/Runtime/Stack_Traces_Spec.enso
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Runtime.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10674 When reopening a project no dynamic widgets available
  engine/runtime-compiler/src/main/java/org/enso/compiler/data/IdMap.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/phase/IdMapProcessor.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/compiler/context/ChangesetBuilder.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/EditFileCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/PendingEdits.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/PendingFileEdits.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/model/PendingEdit.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/RefactoringRenameJob.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/UpsertVisualizationJob.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java
Labels: CI: Ready to merge, CI: No changelog needed

#10440 Soft delete projects by moving them to trash
  build.sbt
  lib/java/desktop-environment/src/main/java/org/enso/desktopenvironment/DirectoriesFactory.java
  lib/java/desktop-environment/src/main/java/org/enso/desktopenvironment/LinuxTrashBin.java
  lib/java/desktop-environment/src/main/java/org/enso/desktopenvironment/MacTrashBin.java
  lib/java/desktop-environment/src/main/java/org/enso/desktopenvironment/Platform.java
  lib/java/desktop-environment/src/main/java/org/enso/desktopenvironment/RandomUtils.java
  lib/java/desktop-environment/src/main/java/org/enso/desktopenvironment/TrashBin.java
  lib/java/desktop-environment/src/main/java/org/enso/desktopenvironment/WindowsTrashBin.java
  lib/java/desktop-environment/src/test/java/org/enso/desktopenvironment/DirectoriesTest.java
  lib/java/desktop-environment/src/test/java/org/enso/desktopenvironment/PlatformTest.java
  lib/java/desktop-environment/src/test/java/org/enso/desktopenvironment/RandomUtilsTest.java
  lib/java/desktop-environment/src/test/java/org/enso/desktopenvironment/TrashBinTest.java
  lib/scala/project-manager/src/main/java/org/enso/projectmanager/infrastructure/migration/ProjectsMigration.java
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/MainModule.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/command/ProjectListCommand.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/command/filesystem/FileSystemCreateDirectoryCommand.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/command/filesystem/FileSystemDeleteCommand.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/command/filesystem/FileSystemExistsCommand.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/command/filesystem/FileSystemListCommand.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/command/filesystem/FileSystemMoveDirectoryCommand.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/command/filesystem/FileSystemWritePathCommand.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/configuration.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/desktop/DesktopTrash.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/desktop/TrashCan.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/repository/ProjectFileRepository.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/repository/ProjectFileRepositoryFactory.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/repository/ProjectRepository.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectService.scala
  lib/scala/project-manager/src/test/java/org/enso/projectmanager/infrastructure/migration/ProjectsMigrationTest.java
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/BaseServerSpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/service/filesystem/FileSystemServiceSpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/test/Shredder.scala
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#10698 Don't report stacktraces for interruptions
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/ReentrantLocking.scala
Labels: CI: No changelog needed

#10694 Change text under profile picture input
  app/ide-desktop/common/src/text/english.json
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#10665 Avoid race condition in `GC_Example` test
  build/build/src/engine/context.rs
  engine/runtime/src/main/java/org/enso/interpreter/runtime/ResourceManager.java
  test/Base_Tests/src/Runtime/GC_Example.enso
  test/Base_Tests/src/Runtime/Managed_Resource_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10701 Add `.enso-project` extension when downloading project files from cloud
  app/dashboard/src/components/dashboard/AssetRow.tsx
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#10703 Changelog for new release
  CHANGELOG.md
Labels: CI: No changelog needed, x-chore

#10619 Remove unnecessary chrome flags
  app/ide-desktop/client/src/index.ts
Labels: CI: Ready to merge, CI: No changelog needed, x-chore, g-dashboard

#10705 Disable linting passes for IDE and repl
  engine/common/src/main/java/org/enso/common/ContextFactory.java
  engine/common/src/main/java/org/enso/common/RuntimeOptions.java
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/runner/src/main/java/org/enso/runner/Main.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/Passes.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/data/CompilerConfig.scala
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/TypeInferenceTest.java
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/PassesTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/EnsoLanguage.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  tools/ci/README.md
Labels: CI: Ready to merge, CI: No changelog needed

#10660 Relative paths are relative to current project locally and in Cloud
  CHANGELOG.md
  build.sbt
  build/build/src/enso.rs
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  engine/launcher/src/main/scala/org/enso/launcher/components/LauncherRunner.scala
  engine/launcher/src/test/scala/org/enso/launcher/components/LauncherRunnerSpec.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/runner/Command.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/runner/RunSettings.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/runner/Runner.scala
  project/DistributionPackage.scala
  project/LibraryManifestGenerator.scala
  project/Platform.scala
  test/Base_Tests/src/System/File_Spec.enso
Labels: CI: Ready to merge

#10713 Refactor Upload_Table to be more readable: split into separate smaller submodules
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Extensions/Upload_Database_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Extensions/Upload_In_Memory_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Common/Lookup_Query_Helper.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload/Helpers/Argument_Checks.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload/Helpers/Check_Queries.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload/Helpers/Constants.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload/Helpers/Default_Arguments.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload/Helpers/Error_Helpers.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload/Helpers/Prepare_Structure.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload/Helpers/SQL_Helpers.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload/Operations/Create.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload/Operations/Delete.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload/Operations/Internal_Core.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload/Operations/Select_Into.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload/Operations/Update.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/SQL_Query.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/Internal/SQLServer_Connection.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Connection.enso
  test/Table_Tests/src/Database/Upload_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10721 Fix docpanel scrollArea height
  app/gui2/src/components/DockPanel.vue
Labels: p-highest, CI: Ready to merge, CI: No changelog needed, --bug, -gui

#10693 Fix editing number and string literals from code editor
  app/gui2/shared/ast/index.ts
  app/gui2/src/stores/graph/graphDatabase.ts
  app/gui2/src/util/ast/__tests__/abstract.test.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui
