Repository enso-org/enso, pull requests merged in 2024-10, with the labels that each got.

#11207 Updating snakeyaml and removing no longer needed patches
  build.sbt
  distribution/engine/THIRD-PARTY/NOTICE
  distribution/engine/THIRD-PARTY/org.yaml.snakeyaml-2.3/NOTICES
  distribution/launcher/THIRD-PARTY/NOTICE
  distribution/launcher/THIRD-PARTY/org.yaml.snakeyaml-2.3/NOTICES
  distribution/project-manager/THIRD-PARTY/NOTICE
  distribution/project-manager/THIRD-PARTY/org.yaml.snakeyaml-2.3/NOTICES
  lib/java/yaml/src/main/java/org/yaml/snakeyaml/introspector/MethodProperty.java
  lib/java/yaml/src/main/java/org/yaml/snakeyaml/introspector/PropertyUtils.java
  tools/legal-review/AWS/com.fasterxml.jackson.dataformat.jackson-dataformat-cbor-2.12.6/files-ignore
  tools/legal-review/engine/org.yaml.snakeyaml-2.3/copyright-keep
  tools/legal-review/engine/report-state
  tools/legal-review/launcher/org.yaml.snakeyaml-2.3/copyright-keep
  tools/legal-review/launcher/report-state
  tools/legal-review/project-manager/org.yaml.snakeyaml-2.3/copyright-keep
  tools/legal-review/project-manager/report-state
Labels: CI: No changelog needed, CI: Clean build required

#11216 Widget for Database.connect
  distribution/lib/Standard/AWS/0.0.0-dev/src/Database/Redshift/Redshift_Details.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/XML.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Header.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Response.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Response_Body.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/Write_Extensions.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection_Details.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection_Options.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Database.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Postgres.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Postgres_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/SQLite.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/SQLite_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Image.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/Connection/SQLServer_Details.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/SQLServer_Connection.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Connection/Snowflake_Details.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Snowflake_Connection.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Snowflake_Data_Link.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Workbook.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  distribution/lib/Standard/Tableau/0.0.0-dev/src/Hyper_File.enso
  distribution/lib/Standard/Tableau/0.0.0-dev/src/Hyper_Table.enso
  std-bits/aws/src/main/java/org/enso/aws/database/RedshiftConnectionDetailsSPI.java
  std-bits/database/src/main/java/org/enso/database/DatabaseConnectionDetailsSPI.java
  std-bits/microsoft/src/main/java/org/enso/microsoft/SQLServerConnectionDetailsSPI.java
  std-bits/snowflake/src/main/java/org/enso/snowflake/SnowflakeConnectionDetailsSPI.java
  test/Microsoft_Tests/src/SQLServer_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11204 Allow project manager to read files
  docs/language-server/protocol-project-manager.md
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/Cli.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/ProjectManager.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/command/CommandHandler.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/command/filesystem/FileSystemReadPathCommand.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/file/BlockingFileSystem.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/file/FileSystem.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/file/JsonFileStorage.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/protocol/FileSystemManagementApi.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/protocol/JsonRpc.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/filesystem/FileSystemService.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/filesystem/FileSystemServiceApi.scala
Labels: CI: Ready to merge, CI: No changelog needed

#11205 Add format parameter to `Decimal.parse`
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Decimal.enso
  test/Base_Tests/src/Data/Decimal_Spec.enso
Labels: CI: Ready to merge

#11218 Don't send expression updates about interrupts
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/command/ExecuteExpressionCommand.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/command/InvalidateModulesIndexCommand.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/command/SetExecutionEnvironmentCommand.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/execution/JobControlPlane.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/job/VisualizationResult.java
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/DestroyContextCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/EditFileCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/InterruptContextCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/PopContextCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/PushContextCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/RecomputeContextCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/SetExpressionValueCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/JobExecutionEngine.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeAsyncCommandsTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#11223 Fix cloud tests by using correct config from the repo
  .github/workflows/extra-nightly-tests.yml
  build/build/src/ci_gen/job.rs
  test/Base_Tests/src/Network/Enso_Cloud/Enso_File_Spec.enso
  test/Base_Tests/src/System/File_Spec.enso
  test/Table_Tests/src/IO/Cloud_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11224 Avoid NPE on missing @anno name
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/ErrorCompilerTest.java
  engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java
Labels: CI: No changelog needed, CI: Clean build required

#11213 use new icon for adding new nodes
  app/gui2/src/assets/icons.svg
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/components/visualizations/tableVizToolbar.ts
Labels: CI: Ready to merge, CI: No changelog needed

#11162 Scatterplot: Add filter down node functionality
  app/gui2/src/components/visualizations/ScatterplotVisualization.vue
Labels: CI: Ready to merge, CI: No changelog needed

#10821 Reporting Enso test failures as annotations on the PR
  build/build/src/engine/context.rs
  build/build/src/enso.rs
  build/ci_utils/src/program/command.rs
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Test_Reporter.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11235 Resolving `~` in Enso asset paths to user home
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Enso_Path.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Data_Link_Setup.enso
  test/AWS_Tests/src/Inter_Backend_File_Operations_Spec.enso
  test/Base_Tests/src/Network/Enso_Cloud/Enso_File_Spec.enso
  test/Table_Tests/src/Database/Common/Audit_Spec.enso
Labels: CI: Ready to merge

#11236 Small Fixes
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Dictionary.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Request_Body.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection_Options.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Simple_Expression.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11198 Run integration in CI.
  .github/workflows/gui.yml
  app/ide-desktop/client/src/globals.d.ts
  app/ide-desktop/client/tests/createNewProject.spec.ts
  app/ide-desktop/client/tests/electronTest.ts
  build/build/src/ci_gen/job.rs
Labels: CI: Ready to merge, CI: No changelog needed, -ci, x-chore

#11238 Full white space rendering and links fix
  app/gui2/src/components/visualizations/TableVisualization.vue
Labels: CI: Ready to merge, CI: No changelog needed

#11249 Run only relevant tests in the Cloud workflow
  .github/workflows/extra-nightly-tests.yml
  build/build/src/ci_gen/job.rs
  build/build/src/engine.rs
  build/build/src/enso.rs
  build/cli/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#11254 Remove some catch alls
  distribution/lib/Standard/AWS/0.0.0-dev/src/Database/Redshift/Redshift_Details.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Filter_Condition.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File_Format.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Postgres.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/SQLite.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/SQLite_Format.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Image_File_Format.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/Connection/SQLServer_Details.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Connection/Snowflake_Details.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data_Formatter.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Delimited/Delimited_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Format.enso
  distribution/lib/Standard/Tableau/0.0.0-dev/src/Tableau_Format.enso
  std-bits/base/src/main/java/org/enso/base/enso_cloud/EnsoSecretHelper.java
  std-bits/table/src/main/java/org/enso/table/excel/ExcelConnectionPool.java
  std-bits/tableau/src/main/java/org/enso/tableau/HyperReader.java
  test/Table_Tests/src/Database/Common/Audit_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11261 Log failure to refresh the Cloud tokens
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Authentication.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11242 Add Coalesce tests and fix In-Memory version
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/IR/From_Spec.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  test/Table_Tests/src/Common_Table_Operations/Coalesce_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Main.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11250 Do not run visualizations on InterruptedException
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/job/VisualizationResult.java
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/JobExecutionEngine.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/ReentrantLocking.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeAsyncCommandsTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#11163 Add DB_Table feature flags
  distribution/lib/Standard/AWS/0.0.0-dev/src/Database/Redshift/Internal/Redshift_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/.LCKFeature.enso~
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Feature.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/Internal/SQLServer_Dialect.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Dialect.enso
  test/AWS_Tests/src/Redshift_Spec.enso
  test/Microsoft_Tests/src/SQLServer_Spec.enso
  test/Snowflake_Tests/src/Snowflake_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Add_Row_Number_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Aggregate_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Coalesce_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Name_Edge_Cases_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Conversion_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Core_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Date_Time_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Derived_Columns_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Distinct_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Expression_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Filter_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Integration_Tests.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Cross_Join_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Join_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Lookup_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Replace_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Union_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Main.enso
  test/Table_Tests/src/Common_Table_Operations/Map_To_Table_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Missing_Values_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Nothing_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Order_By_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Select_Columns_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Take_Drop_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Text_Cleanse_Spec.enso
  test/Table_Tests/src/Database/Common/Common_Spec.enso
  test/Table_Tests/src/Database/Common/Default_Ordering_Spec.enso
  test/Table_Tests/src/Database/Common/Names_Length_Limits_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Database/SQLite_Spec.enso
  test/Table_Tests/src/In_Memory/Common_Spec.enso
Labels: CI: No changelog needed

#11264 Fix invalid `${rust-jni.out}` in Nix flake on non-Linux systems
  flake.nix
Labels: CI: Ready to merge, CI: No changelog needed

#11258 add method for xml doc drilldown
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/XML.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11270 Enable SQLServer select columns
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Feature.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/Internal/SQLServer_Dialect.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/Internal/SQLServer_Type_Mapping.enso
  test/Microsoft_Tests/src/SQLServer_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Derived_Columns_Spec.enso
Labels: CI: No changelog needed

#11219 Dashboard improvements (from 24 September 2024 + 30 September 2024)
  app/dashboard/e2e/assetsTableFeatures.spec.ts
  app/dashboard/index.html
  app/dashboard/package.json
  app/dashboard/src/components/AriaComponents/Checkbox/Checkbox.tsx
  app/dashboard/src/components/AriaComponents/Form/Form.tsx
  app/dashboard/src/components/AriaComponents/Form/components/Reset.tsx
  app/dashboard/src/components/AriaComponents/Form/components/Submit.tsx
  app/dashboard/src/components/AriaComponents/Form/components/types.ts
  app/dashboard/src/components/AriaComponents/Form/components/useForm.ts
  app/dashboard/src/components/AriaComponents/Inputs/ComboBox/ComboBox.tsx
  app/dashboard/src/components/AriaComponents/Inputs/ComboBox/index.ts
  app/dashboard/src/components/AriaComponents/Inputs/DatePicker/index.ts
  app/dashboard/src/components/AriaComponents/Inputs/Dropdown/Dropdown.tsx
  app/dashboard/src/components/AriaComponents/Inputs/Input/Input.tsx
  app/dashboard/src/components/AriaComponents/Inputs/index.ts
  app/dashboard/src/components/Autocomplete.tsx
  app/dashboard/src/components/ColorPicker.tsx
  app/dashboard/src/components/JSONSchemaInput.tsx
  app/dashboard/src/components/Modal.tsx
  app/dashboard/src/components/aria.tsx
  app/dashboard/src/components/dashboard/AssetIcon.tsx
  app/dashboard/src/components/dashboard/AssetRow.tsx
  app/dashboard/src/components/dashboard/Label.tsx
  app/dashboard/src/components/dashboard/Permission.tsx
  app/dashboard/src/components/dashboard/PermissionSelector.tsx
  app/dashboard/src/components/dashboard/PermissionTypeSelector.tsx
  app/dashboard/src/components/dashboard/ProjectIcon.tsx
  app/dashboard/src/components/dashboard/TheModal.tsx
  app/dashboard/src/components/dashboard/column/LabelsColumn.tsx
  app/dashboard/src/components/dashboard/column/NameColumn.tsx
  app/dashboard/src/components/dashboard/column/columnUtils.ts
  app/dashboard/src/hooks/backendHooks.ts
  app/dashboard/src/hooks/dimensionsHooks.ts
  app/dashboard/src/hooks/spotlightHooks.tsx
  app/dashboard/src/layouts/AssetContextMenu.tsx
  app/dashboard/src/layouts/AssetPanel.tsx
  app/dashboard/src/layouts/AssetProjectSession.tsx
  app/dashboard/src/layouts/AssetProperties.tsx
  app/dashboard/src/layouts/AssetsTable.tsx
  app/dashboard/src/layouts/DriveBar.tsx
  app/dashboard/src/layouts/Settings/SetupTwoFaForm.tsx
  app/dashboard/src/layouts/Settings/data.tsx
  app/dashboard/src/layouts/Settings/index.tsx
  app/dashboard/src/layouts/TabBar.tsx
  app/dashboard/src/modals/ConfirmDeleteModal.tsx
  app/dashboard/src/modals/ConfirmDeleteUserModal.tsx
  app/dashboard/src/modals/EditAssetDescriptionModal.tsx
  app/dashboard/src/modals/ManageLabelsModal.tsx
  app/dashboard/src/modals/NewLabelModal.tsx
  app/dashboard/src/modals/UpsertDatalinkModal.tsx
  app/dashboard/src/modals/UpsertSecretModal.tsx
  app/dashboard/src/pages/dashboard/Dashboard.tsx
  app/dashboard/src/tailwind.css
  app/dashboard/src/utilities/convertCSSUnits.ts
  app/dashboard/tailwind.config.js
  app/ide-desktop/common/src/services/Backend.ts
  app/ide-desktop/common/src/text/english.json
  app/ide-desktop/common/src/text/index.ts
  pnpm-lock.yaml
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#11275 Some Additional Error checks for Enso_File
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_User.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Existing_Enso_Asset.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11173 Run node in a different execution environment
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/executioncontext/RecomputeHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistry.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistryProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ExecutionApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ExpressionConfig.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/InvalidatedExpressions.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/ContextRegistryTest.scala
  engine/polyglot-api/src/main/java/org/enso/polyglot/debugger/IdExecutionService.java
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/ExecutionConfig.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/ExpressionExecutionState.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/command/SetExecutionEnvironmentCommand.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionCallbacks.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/RecomputeContextCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/ExecutionState.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ExecuteJob.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/id/execution/IdExecutionInstrument.java
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeAsyncCommandsTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeExecutionEnvironmentTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeRecomputeTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeSuggestionUpdatesTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/EnsoLanguage.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/Instrumentor.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/state/ExecutionEnvironment.java
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Runtime.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10608 Improve CI feedback when directory is missing
  .github/CODEOWNERS
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/VcsManagerTest.scala
  engine/launcher/src/main/scala/org/enso/launcher/project/ProjectManager.scala
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/DefaultPackageRepository.scala
  lib/scala/pkg/src/main/scala/org/enso/pkg/Package.scala
Labels: CI: No changelog needed

#11285 Clean up credentials file after E2E job.
  .github/workflows/gui.yml
  build/build/src/ci_gen/job.rs
Labels: CI: Ready to merge, CI: No changelog needed

#11269 Add retries to Data.read
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Data_Read_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Runtime/Thread.enso
  test/Base_Tests/src/Network/Http_Spec.enso
  tools/http-test-helper/src/main/java/org/enso/shttp/test_helpers/CrashingTestHandler.java
Labels: CI: No changelog needed

#11255 Accessing and modifying description and labels of Enso Cloud assets
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Color.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Enso_File_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Existing_Enso_Asset.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Utils.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Test.enso
  std-bits/base/src/main/java/org/enso/base/enso_cloud/audit/AuditLogApiAccess.java
  test/Base_Tests/src/Network/Enso_Cloud/Enso_File_Spec.enso
  test/Table_Tests/src/Database/Common/Audit_Spec.enso
  tools/http-test-helper/src/main/java/org/enso/shttp/cloud_mock/AssetStore.java
  tools/http-test-helper/src/main/java/org/enso/shttp/cloud_mock/PostLogHandler.java
Labels: CI: Ready to merge

#11279 Avoid JavaScript and Python in Enso native launcher
  build.sbt
  project/JPMSUtils.scala
  project/NativeImage.scala
  tools/legal-review/engine/report-state
Labels: CI: No changelog needed, CI: Clean build required

#11303 Remove TailCall.TailPosition.NotTail metadata.
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/PassPersistance.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/TailCall.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/analyse/TailCallTest.scala
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#11273 Refactor Dialect_Flag
  distribution/lib/Standard/AWS/0.0.0-dev/src/Database/Redshift/Internal/Redshift_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/.LCKFeature.enso~
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Dialect_Flag.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Dialect_Flags.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/Internal/SQLServer_Dialect.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Dialect.enso
  test/AWS_Tests/src/Redshift_Spec.enso
  test/Microsoft_Tests/src/SQLServer_Spec.enso
  test/Snowflake_Tests/src/Snowflake_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Name_Edge_Cases_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Main.enso
  test/Table_Tests/src/Common_Table_Operations/Select_Columns_Spec.enso
  test/Table_Tests/src/Database/Common/IR_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Database/SQLite_Spec.enso
  test/Table_Tests/src/Database/Upload_Spec.enso
  test/Table_Tests/src/In_Memory/Common_Spec.enso
Labels: CI: No changelog needed

#11306 Enable audit logs for Snowflake backend
  app/gui/src/dashboard/data/__tests__/dataLinkSchema.test.ts
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Authentication.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Data_Link/Postgres_Data_Link.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/DB_Data_Link_Helpers.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Connection/Snowflake_Details.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Dialect.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Snowflake_Data_Link.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Test_Reporter.enso
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoFile.java
  test/Base_Internal_Tests/src/Github_Annotations_Spec.enso
  test/Base_Internal_Tests/src/Main.enso
  test/Snowflake_Tests/data/datalinks/snowflake-db.datalink
  test/Snowflake_Tests/src/Snowflake_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Coalesce_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11317 Remove download font scripts
  .prettierignore
  Cargo.lock
  app/gui/.gitignore
  app/gui/package.json
  app/gui/public/font-dejavu/DejaVuSansMono-Bold.ttf
  app/gui/scripts/downloadFonts.js
  app/gui/src/project-view/assets/font-dejavu.css
  app/gui/src/project-view/assets/font-enso.css
  app/gui/src/project-view/assets/font-mplus1.css
  app/gui/src/project-view/util/iconList.json
  build/build/Cargo.toml
  build/build/src/ide/web.rs
  build/build/src/ide/web/dejavu_font.rs
  build/build/src/ide/web/enso_font.rs
  build/build/src/ide/web/fonts.rs
  build/build/src/ide/web/google_font.rs
  build/build/src/project/gui.rs
  eslint.config.mjs
  lib/rust/enso-font/Cargo.toml
  lib/rust/enso-font/src/lib.rs
  lib/rust/font/Cargo.toml
  lib/rust/font/src/lib.rs
  pnpm-lock.yaml
Labels: CI: Ready to merge, CI: No changelog needed, -build-script, -gui

#11323 Ensure wrapper projects are listed in aggregates
  build.sbt
  engine/runtime-test-instruments/src/main/java/module-info.java
  engine/runtime-test-instruments/src/main/java/org/enso/interpreter/test/instruments/CodeIdsTestInstrument.java
  engine/runtime-test-instruments/src/main/java/org/enso/interpreter/test/instruments/NodeCountingTestInstrument.java
  engine/runtime-test-instruments/src/main/java/org/enso/interpreter/test/instruments/service/FunctionCallInfo.java
  engine/runtime-test-instruments/src/main/java/org/enso/interpreter/test/instruments/service/RuntimeTestService.java
  engine/runtime-test-instruments/src/main/java/org/enso/interpreter/test/instruments/tck/EnsoTckLanguageProvider.java
  lib/java/directory-watcher-wrapper/src/main/java/module-info.java
  lib/java/scala-libs-wrapper/src/main/java/module-info.java
  lib/java/zio-wrapper/src/main/java/module-info.java
Labels: CI: No changelog needed

#11217 Show only fields from current atom constructor in the debugger
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/AtomInteropTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/DebuggingEnsoTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/TypeMembersTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/privateaccess/PrivateConstructorAccessTest.java
  engine/runtime/src/main/java/org/enso/interpreter/node/MethodRootNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/Atom.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/AtomConstructor.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/GetFieldBaseNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/GetFieldNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/GetFieldWithMatchNode.java
  test/Base_Tests/src/Semantic/Private_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#11314 Allow updating local assets
  app/gui/project-manager-shim-middleware/projectManagement.ts
  app/gui/src/dashboard/layouts/AssetsTable.tsx
  app/ide-desktop/client/src/index.ts
  app/ide-desktop/client/src/preload.ts
  app/ide-desktop/client/src/projectManagement.ts
Labels: CI: No changelog needed

#11321 Fix invocation of single benchmarks in `std-benchmarks`
  build.sbt
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#11320 Add `Meta.engine_version`
  distribution/lib/Standard/Base/0.0.0-dev/src/Meta.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/CurrentEngineVersionNode.java
  test/Base_Tests/src/Semantic/Meta_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11191 Migrate some passes to Mini passes
  engine/runtime-compiler/src/main/java/org/enso/compiler/dump/IRDumperPass.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/ChainedMiniPass.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/IRProcessingPass.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/MiniIRPass.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/MiniPassFactory.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/MiniPassTraverser.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/PassPersistance.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/PrivateConstructorAnalysis.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/PrivateModuleAnalysis.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/PrivateSymbolsAnalysis.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/TailCall.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/TypeInference.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/desugar/OperatorToFunctionMini.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/desugar/SectionsToBinOp.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/Passes.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/IRPass.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/PassManager.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/CachePreferenceAnalysis.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/DataflowAnalysis.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/desugar/ComplexType.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/desugar/FunctionBinding.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/desugar/GenerateMethodBodies.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/desugar/LambdaShorthandToLambda.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/desugar/LambdaShorthandToLambdaMini.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/desugar/NestedPatternMatch.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/desugar/OperatorToFunction.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/lint/ShadowedPatternFields.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/lint/UnusedBindings.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/optimise/LambdaConsolidate.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/optimise/UnreachableMatchBranches.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/IgnoredBindings.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/SuspendedArguments.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/TypeFunctions.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/TypeSignatures.scala
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/CompilerTests.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/mini/passes/MiniPassTester.java
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/MiniPassTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/PassesTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/PassManagerTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/analyse/TailCallMegaPass.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/analyse/TailCallTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/desugar/LambdaShorthandToLambdaMegaPass.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/desugar/LambdaShorthandToLambdaTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/desugar/OperatorToFunctionTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/desugar/SectionsToBinOpMegaPass.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/desugar/SectionsToBinOpTest.scala
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#11336 Revert "Add `Meta.engine_version`"
  distribution/lib/Standard/Base/0.0.0-dev/src/Meta.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/CurrentEngineVersionNode.java
  test/Base_Tests/src/Semantic/Meta_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11334 Yield `UnsupportedMessageException` when context isn't accessible
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/DataflowError.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicException.java
Labels: CI: No changelog needed

#11338 Small fixes..
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  std-bits/table/src/main/java/org/enso/table/excel/ExcelHeaders.java
  std-bits/table/src/main/java/org/enso/table/excel/ExcelRow.java
Labels: CI: Ready to merge, CI: No changelog needed

#11340 syncToCode: Test case for rename binding
  app/gui/src/project-view/util/ast/__tests__/abstract.test.ts
Labels: CI: Ready to merge, CI: No changelog needed

#11271 Table widget: reordering rows and columns
  CHANGELOG.md
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor/__tests__/tableNewArgument.test.ts
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor/tableNewArgument.ts
  app/gui/src/project-view/components/shared/AgGridTableView.vue
  app/gui/src/project-view/util/ast/__tests__/abstract.test.ts
  app/gui/src/project-view/util/data/iterable.ts
  app/ydoc-shared/src/ast/tree.ts
Labels: CI: Ready to merge, x-new-feature, -gui

#11343 Save Database connection as data link, SQL Server data link support
  app/gui/src/dashboard/data/__tests__/dataLinkSchema.test.ts
  app/gui/src/dashboard/data/datalinkSchema.json
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Data_Link_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Panic.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Postgres.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Postgres_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Data_Link_Setup.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Data_Link_Setup.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/Connection/SQLServer_Details.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/Internal/SQLServer_Dialect.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/SQLServer_Connection.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/SQLServer_Data_Link.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Connection/Snowflake_Details.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Snowflake_Connection.enso
  std-bits/microsoft/src/main/java/org/enso/microsoft/SQLServerDataLinkSPI.java
  test/Microsoft_Tests/data/datalinks/sqlserver-db.datalink
  test/Microsoft_Tests/src/SQLServer_Spec.enso
  test/Snowflake_Tests/src/Snowflake_Spec.enso
  test/Table_Tests/src/Database/Common/Audit_Spec.enso
  test/Table_Tests/src/Database/Common/Save_Connection_Data_Link.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11288 Make Asset Table selection backend specific
  app/common/src/text/english.json
  app/common/src/text/index.ts
  app/gui/src/dashboard/layouts/AssetContextMenu.tsx
  app/gui/src/dashboard/layouts/AssetsTable.tsx
  app/gui/src/dashboard/layouts/AssetsTableContextMenu.tsx
  app/gui/src/dashboard/layouts/CategorySwitcher.tsx
  app/gui/src/dashboard/layouts/CategorySwitcher/Category.ts
  app/gui/src/dashboard/layouts/DriveBar.tsx
  app/gui/src/dashboard/layouts/GlobalContextMenu.tsx
  app/gui/src/dashboard/pages/dashboard/Dashboard.tsx
  app/gui/src/dashboard/providers/DriveProvider.tsx
Labels: p-high, CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#11345 Switch to newer MacOS GitHub runner
  .github/workflows/engine-nightly.yml
  .github/workflows/enso4igv.yml
  .github/workflows/gui.yml
  .github/workflows/release.yml
  .github/workflows/scala-new.yml
  build/build/src/ci_gen/job.rs
  build/ci_utils/src/actions/workflow/definition.rs
Labels: CI: Ready to merge, CI: No changelog needed

#11349 Handle mixed Date and Date Time column within Excel
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Of_Day.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Zone.enso
  std-bits/table/src/main/java/org/enso/table/data/column/builder/DateBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/DateTimeBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/InferredBuilder.java
  std-bits/table/src/main/java/org/enso/table/read/ExcelReader.java
  test/Table_Tests/data/MixedExcel.xlsx
  test/Table_Tests/src/IO/Excel_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11353 Set live execution environment for REPL
  engine/common/src/main/java/org/enso/common/ContextFactory.java
  engine/runner/src/main/java/org/enso/runner/Main.java
Labels: CI: No changelog needed

#11284 Display error message when Scatterplot Visualization errors out
  app/gui/src/project-view/components/visualizations/ScatterplotVisualization.vue
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Scatter_Plot.enso
  test/Visualization_Tests/src/Scatter_Plot_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11341 Node added inside collapsed node is never executed
  engine/common/src/main/java/org/enso/common/CachePreferences.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/PassPersistance.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/CachePreferenceAnalysis.scala
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/RuntimeCache.java
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/CacheInvalidation.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/RecomputeContextCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime-instrument-common/src/test/java/org/enso/interpreter/instrument/RuntimeCacheTest.java
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#11351 Benchmark lazy infinite sieve of Eratosthenes
  project/GraalVM.scala
  test/Benchmarks/src/Sieve/Lazy_Sieve.enso
  test/Benchmarks/src/Sieve/Main.enso
  test/Benchmarks/src/Sieve/heap_dump_lazy_sieve.js
Labels: CI: No changelog needed

#11324 Distinguish assignment/thunk by statement context
  app/gui/package.json
  app/gui/src/project-view/stores/graph/index.ts
  app/gui/src/project-view/util/ast/__tests__/abstract.test.ts
  app/gui/src/project-view/util/ast/__tests__/raw.test.ts
  app/gui/src/project-view/util/ast/aliasAnalysis.ts
  app/gui/src/project-view/util/ast/extended.ts
  app/gui/src/project-view/util/ast/raw.ts
  app/rust-ffi/src/lib.rs
  app/ydoc-server-polyglot/src/ffiPolyglot.ts
  app/ydoc-server-polyglot/src/polyglot.d.ts
  app/ydoc-server/src/languageServerSession.ts
  app/ydoc-shared/src/ast/ffi.ts
  app/ydoc-shared/src/ast/parse.ts
  app/ydoc-shared/src/ast/tree.ts
  engine/runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/CompilerTests.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/ErrorCompilerTest.java
  engine/runtime-parser/src/main/java/org/enso/compiler/core/EnsoParser.java
  engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java
  lib/java/ydoc-server/src/main/java/org/enso/ydoc/polyfill/ParserPolyfill.java
  lib/java/ydoc-server/src/main/resources/org/enso/ydoc/polyfill/parser.js
  lib/java/ydoc-server/src/test/java/org/enso/ydoc/polyfill/ParserPolyfillTest.java
  lib/rust/parser/debug/fuzz/src/main.rs
  lib/rust/parser/debug/src/bin/bench_parse.rs
  lib/rust/parser/debug/src/bin/binary_ast.rs
  lib/rust/parser/debug/src/bin/check_syntax.rs
  lib/rust/parser/debug/src/bin/json_ast.rs
  lib/rust/parser/debug/src/main.rs
  lib/rust/parser/debug/tests/parse.rs
  lib/rust/parser/doc-parser/src/main.rs
  lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java
  lib/rust/parser/generate-java/src/bin/java-tests.rs
  lib/rust/parser/jni/src/lib.rs
  lib/rust/parser/src/lib.rs
  lib/rust/parser/src/macros/resolver.rs
  lib/rust/parser/src/syntax/statement.rs
  lib/rust/parser/src/syntax/statement/type_def.rs
  lib/rust/parser/src/syntax/tree.rs
  lib/rust/parser/src/syntax/tree/block.rs
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#11354 Handle autoscoped constructor args with no UUID
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeCallableNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/UnresolvedConstructor.java
Labels: CI: No changelog needed

#11359 Unblock the hooks execution
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/execution/RuntimeExecutionHooks.java
Labels: CI: Ready to merge, CI: No changelog needed

#11332 Copying and pasting in Grid fixes.
  CHANGELOG.md
  app/gui/e2e/project-view/actions.ts
  app/gui/e2e/project-view/graphNodeVisualization.spec.ts
  app/gui/e2e/project-view/tableVisualisation.spec.ts
  app/gui/e2e/project-view/widgets.spec.ts
  app/gui/src/project-view/bindings.ts
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor/__tests__/tableNewArgument.test.ts
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor/tableNewArgument.ts
  app/gui/src/project-view/components/shared/AgGridTableView.vue
  app/gui/src/project-view/components/visualizations/TableVisualization.vue
Labels: CI: Ready to merge, CI: Clean build required, x-new-feature, --bug, -gui

#11268 Dashboard improvements (8 Oct 2024)
  app/gui/e2e/dashboard/api.ts
  app/gui/e2e/dashboard/assetPanel.spec.ts
  app/gui/package.json
  app/gui/src/dashboard/components/AriaComponents/Button/Button.tsx
  app/gui/src/dashboard/components/AriaComponents/Form/components/FormProvider.tsx
  app/gui/src/dashboard/components/AriaComponents/Form/components/Reset.tsx
  app/gui/src/dashboard/components/AriaComponents/Inputs/Dropdown/Dropdown.tsx
  app/gui/src/dashboard/components/AriaComponents/Inputs/ResizableInput/ResizableContentEditableInput.tsx
  app/gui/src/dashboard/components/SelectionBrush.tsx
  app/gui/src/dashboard/components/aria.tsx
  app/gui/src/dashboard/components/dashboard/AssetRow.tsx
  app/gui/src/dashboard/components/dashboard/KeyboardShortcut.tsx
  app/gui/src/dashboard/components/dashboard/column.ts
  app/gui/src/dashboard/components/dashboard/column/LabelsColumn.tsx
  app/gui/src/dashboard/components/dashboard/column/SharedWithColumn.tsx
  app/gui/src/dashboard/events/AssetListEventType.ts
  app/gui/src/dashboard/events/assetListEvent.ts
  app/gui/src/dashboard/hooks/backendHooks.ts
  app/gui/src/dashboard/hooks/projectHooks.ts
  app/gui/src/dashboard/layouts/AssetContextMenu.tsx
  app/gui/src/dashboard/layouts/AssetPanel.tsx
  app/gui/src/dashboard/layouts/AssetProperties.tsx
  app/gui/src/dashboard/layouts/AssetVersions/AssetVersions.tsx
  app/gui/src/dashboard/layouts/AssetsTable.tsx
  app/gui/src/dashboard/layouts/AssetsTableContextMenu.tsx
  app/gui/src/dashboard/layouts/CategorySwitcher.tsx
  app/gui/src/dashboard/layouts/CategorySwitcher/Category.ts
  app/gui/src/dashboard/layouts/DriveBar.tsx
  app/gui/src/dashboard/layouts/GlobalContextMenu.tsx
  app/gui/src/dashboard/layouts/Labels.tsx
  app/gui/src/dashboard/layouts/Settings/KeyboardShortcutsSettingsSection.tsx
  app/gui/src/dashboard/layouts/Settings/MembersSettingsSection.tsx
  app/gui/src/dashboard/modals/CaptureKeyboardShortcutModal.tsx
  app/gui/src/dashboard/modals/ManageLabelsModal.tsx
  app/gui/src/dashboard/modals/ManagePermissionsModal.tsx
  app/gui/src/dashboard/modals/NewUserGroupModal.tsx
  app/gui/src/dashboard/modals/UpsertSecretModal.tsx
  app/gui/src/dashboard/pages/dashboard/Dashboard.tsx
  app/gui/src/dashboard/providers/DriveProvider.tsx
  app/gui/src/dashboard/services/RemoteBackend.ts
  app/gui/src/dashboard/services/remoteBackendPaths.ts
  app/gui/src/dashboard/utilities/PasteType.ts
  app/gui/src/dashboard/utilities/drag.ts
  app/gui/src/dashboard/utilities/pasteData.ts
  app/gui/src/dashboard/utilities/reactQuery.ts
  app/gui/src/dashboard/utilities/uniqueString.ts
  app/gui/src/project-view/assets/font-dejavu.css
  app/gui/src/project-view/assets/font-enso.css
  app/gui/src/project-view/assets/font-mplus1.css
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#11358 Limit light selection to "widget-colored" widgets only
  CHANGELOG.md
  app/gui/src/project-view/assets/base.css
  app/gui/src/project-view/components/GraphEditor/GraphNodes.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetText.vue
  app/gui/src/project-view/components/widgets/NumericInputWidget.vue
Labels: CI: Ready to merge, --bug, -gui

#11355 Benchmark time it takes compile `Standard.Base` library
  engine/runtime-compiler/src/main/scala/org/enso/compiler/data/BindingsMap.scala
  test/Benchmarks/src/Compiler/Compile.enso
  test/Benchmarks/src/Main.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#11319 Multipart upload for large files
  app/common/src/services/Backend.ts
  app/common/src/text/english.json
  app/common/src/text/index.ts
  app/gui/e2e/dashboard/api.ts
  app/gui/src/dashboard/components/JSONSchemaInput.tsx
  app/gui/src/dashboard/hooks/backendHooks.ts
  app/gui/src/dashboard/hooks/projectHooks.ts
  app/gui/src/dashboard/hooks/toastAndLogHooks.ts
  app/gui/src/dashboard/layouts/AssetContextMenu.tsx
  app/gui/src/dashboard/layouts/AssetsTable.tsx
  app/gui/src/dashboard/layouts/CategorySwitcher.tsx
  app/gui/src/dashboard/layouts/CategorySwitcher/Category.ts
  app/gui/src/dashboard/layouts/DriveBar.tsx
  app/gui/src/dashboard/layouts/Editor.tsx
  app/gui/src/dashboard/layouts/GlobalContextMenu.tsx
  app/gui/src/dashboard/layouts/OpenAppWatcher.tsx
  app/gui/src/dashboard/layouts/Settings/MembersSettingsSection.tsx
  app/gui/src/dashboard/layouts/Settings/index.tsx
  app/gui/src/dashboard/modals/DuplicateAssetsModal.tsx
  app/gui/src/dashboard/modals/InviteUsersModal/InviteUsersForm.tsx
  app/gui/src/dashboard/modals/InvitedToOrganizationModal.tsx
  app/gui/src/dashboard/modals/ManagePermissionsModal.tsx
  app/gui/src/dashboard/modals/SetupOrganizationAfterSubscribe.tsx
  app/gui/src/dashboard/modules/payments/components/PlanSelector/PlanSelector.tsx
  app/gui/src/dashboard/pages/authentication/Setup/Setup.tsx
  app/gui/src/dashboard/providers/AuthProvider.tsx
  app/gui/src/dashboard/providers/BackendProvider.tsx
  app/gui/src/dashboard/services/LocalBackend.ts
  app/gui/src/dashboard/services/RemoteBackend.ts
  app/gui/src/dashboard/services/remoteBackendPaths.ts
  app/gui/src/dashboard/tailwind.css
  app/gui/src/dashboard/utilities/download.ts
  app/gui/src/dashboard/utilities/input.ts
  app/gui/src/dashboard/utilities/preventNavigation.tsx
  app/gui/tailwind.config.js
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#11346 Replace `private` modifier node with field on supporting types
  app/gui/src/project-view/util/ast/__tests__/abstract.test.ts
  app/ydoc-shared/src/ast/parse.ts
  app/ydoc-shared/src/ast/tree.ts
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/ErrorCompilerTest.java
  engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java
  lib/rust/parser/debug/src/lib.rs
  lib/rust/parser/debug/tests/parse.rs
  lib/rust/parser/src/lexer.rs
  lib/rust/parser/src/macros/built_in.rs
  lib/rust/parser/src/macros/pattern.rs
  lib/rust/parser/src/syntax/item.rs
  lib/rust/parser/src/syntax/statement.rs
  lib/rust/parser/src/syntax/statement/function_def.rs
  lib/rust/parser/src/syntax/statement/type_def.rs
  lib/rust/parser/src/syntax/token.rs
  lib/rust/parser/src/syntax/tree.rs
  lib/rust/parser/src/syntax/tree/block.rs
  lib/rust/prelude/macros/src/tagged_enum.rs
Labels: CI: Ready to merge, CI: No changelog needed

#11364 Move TypeSignature into field of Function
  app/ydoc-shared/src/ast/parse.ts
  app/ydoc-shared/src/ast/tree.ts
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/ErrorCompilerTest.java
  engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java
  lib/rust/parser/debug/src/lib.rs
  lib/rust/parser/debug/tests/parse.rs
  lib/rust/parser/src/macros/resolver.rs
  lib/rust/parser/src/syntax/statement.rs
  lib/rust/parser/src/syntax/statement/function_def.rs
  lib/rust/parser/src/syntax/statement/type_def.rs
  lib/rust/parser/src/syntax/tree.rs
  lib/rust/parser/src/syntax/tree/block.rs
  lib/rust/parser/src/syntax/treebuilding/block.rs
Labels: CI: Ready to merge, CI: No changelog needed

#11361 Fail gracefully when a job is already rejected
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/AttachVisualizationCmd.scala
Labels: CI: No changelog needed

#11377 Fix `AssetSearchBar` E2E tests
  app/gui/e2e/dashboard/assetSearchBar.spec.ts
  app/gui/e2e/dashboard/assetsTableFeatures.spec.ts
  app/gui/playwright.config.ts
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#11381 Simplify IGV graph by trimming nodes for code paths that rarely happen
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/dispatch/InvokeFunctionNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/SuspendedFieldGetterNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#11383 Enable cloud file browser in local projects
  CHANGELOG.md
  app/gui/e2e/project-view/widgets.spec.ts
  app/gui/src/dashboard/layouts/Editor.tsx
  app/gui/src/project-view/App.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetCloudBrowser.vue
  app/gui/src/project-view/components/widgets/FileBrowserWidget.vue
  app/gui/src/project-view/composables/backend.ts
  app/gui/src/project-view/providers/backend.ts
Labels: CI: Ready to merge, CI: Clean build required

#11384 More robust enso4igv when "find in projects" invoked
  tools/enso4igv/src/main/java/org/enso/tools/enso4igv/EnsoRootProject.java
Labels: CI: Ready to merge, CI: Keep up to date, CI: No changelog needed, CI: Clean build required

#11374 Move annotations into fields of Function and ConstructorDefinition
  CHANGELOG.md
  app/ydoc-shared/src/ast/parse.ts
  app/ydoc-shared/src/ast/tree.ts
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Postgres.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data_Formatter.enso
  docs/syntax/types.md
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/ErrorCompilerTest.java
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/resolve/ModuleAnnotationsTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/semantic/ConstructorsTest.scala
  engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java
  lib/rust/parser/debug/tests/parse.rs
  lib/rust/parser/src/syntax/operator/annotations.rs
  lib/rust/parser/src/syntax/statement.rs
  lib/rust/parser/src/syntax/statement/function_def.rs
  lib/rust/parser/src/syntax/statement/type_def.rs
  lib/rust/parser/src/syntax/tree.rs
  lib/rust/parser/src/syntax/tree/block.rs
  lib/rust/prelude/macros/src/tagged_enum.rs
Labels: CI: Ready to merge

#11153 Speedup DataflowError.withDefaultTrace
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/ThrowErrorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/runtime/ContextIsEnabledNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/DataflowError.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/state/ContextPermissions.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/state/ExecutionEnvironment.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/state/HasContextEnabledNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/state/WithContextNode.java
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#11257 Update running tests documentation
  docs/CONTRIBUTING.md
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#11385 Use `enso.dev.insight` property to turn Insight on
  engine/common/src/main/java/org/enso/common/ContextFactory.java
  engine/common/src/main/java/org/enso/common/ContextInsightSetup.java
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/runtime-integration-tests/src/test/java/org/enso/common/test/ContextInsightSetupTest.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/ForeignEvalNode.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/JsForeignNode.java
  engine/runtime-language-epb/src/test/java/org/enso/interpreter/epb/ForeignEvalNodeTest.java
  test/Base_Tests/src/Semantic/Js_Interop_Spec.enso
Labels: CI: No changelog needed, CI: Clean build required

#11371 Saving data links to a DB_Table
  .github/workflows/extra-nightly-tests.yml
  CHANGELOG.md
  app/gui/src/dashboard/data/__tests__/dataLinkSchema.test.ts
  app/gui/src/dashboard/data/datalinkSchema.json
  build/build/src/ci_gen/job.rs
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Data_Link/Postgres_Data_Link.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Postgres_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/DB_Data_Link_Helpers.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Data_Link_Setup.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/IR/Context.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/IR/From_Spec.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/SQL.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/SQL_Statement.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/SQLServer_Connection.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/SQLServer_Data_Link.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Dialect.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Snowflake_Connection.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Snowflake_Data_Link.enso
  test/Base_Tests/src/Data/List_Spec.enso
  test/Base_Tests/src/Data/Vector_Spec.enso
  test/Table_Tests/data/datalinks/postgres-serialized-query.datalink
  test/Table_Tests/data/datalinks/postgres-simple-query.datalink
  test/Table_Tests/src/Database/Codegen_Spec.enso
  test/Table_Tests/src/Database/Common/Save_Connection_Data_Link.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Database/Upload_Spec.enso
  test/Table_Tests/src/Helpers/Main.enso
  test/Table_Tests/src/Helpers/SQL_Statement_Serialization.enso
Labels: CI: Ready to merge

#11395 Testing current behavior of if/then/else
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/IfThenElseTest.java
Labels: CI: Ready to merge, CI: No changelog needed

#11400 Change 3 dots icon
  app/gui/src/project-view/assets/icons.svg
Labels: CI: Ready to merge, CI: No changelog needed

#11394 Execute `test/Geo_Tests` in enso binary launcher
  build.sbt
  build/build/src/engine/context.rs
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Java_Problems.enso
Labels: CI: No changelog needed

#11379 Enable SQLServer Sort Feature and associated tests
  distribution/lib/Standard/AWS/0.0.0-dev/src/Database/Redshift/Internal/Redshift_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/IR/Context.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/Internal/SQLServer_Dialect.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/Internal/SQLServer_Type_Mapping.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Dialect.enso
  test/AWS_Tests/src/Redshift_Spec.enso
  test/Microsoft_Tests/src/SQLServer_Spec.enso
  test/Snowflake_Tests/src/Snowflake_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Add_Row_Number_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Main.enso
  test/Table_Tests/src/Common_Table_Operations/Nothing_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Database/SQLite_Spec.enso
  test/Table_Tests/src/In_Memory/Common_Spec.enso
Labels: CI: No changelog needed

#11388 Table Input Widget: Add column with plus
  CHANGELOG.md
  app/gui/e2e/project-view/rightPanel.spec.ts
  app/gui/e2e/project-view/tableVisualisation.spec.ts
  app/gui/e2e/project-view/widgets.spec.ts
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor/TableHeader.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor/__tests__/tableNewArgument.test.ts
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor/tableNewArgument.ts
  app/gui/src/project-view/components/TooltipTrigger.vue
  app/gui/src/project-view/providers/index.ts
Labels: CI: Ready to merge, CI: Clean build required, -gui

#11403 Execute Base_Internal_Tests with native enso executable
  build/build/src/engine/context.rs
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Delimited_Reader.enso
  test/Base_Internal_Tests/src/Input_Output_Spec.enso
  test/Table_Tests/src/In_Memory/Integer_Overflow_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#11398 New component menu
  CHANGELOG.md
  app/gui/e2e/project-view/componentBrowser.spec.ts
  app/gui/src/project-view/components/CircularMenu.vue
  app/gui/src/project-view/components/ColorRing.vue
  app/gui/src/project-view/components/GraphEditor.vue
  app/gui/src/project-view/components/GraphEditor/GraphNode.vue
  app/gui/src/project-view/components/GraphEditor/GraphNodes.vue
Labels: CI: Ready to merge, x-new-feature, -gui

#11415 Reload insight script on file change
  engine/common/src/main/java/org/enso/common/ContextInsightSetup.java
Labels: CI: Ready to merge, CI: No changelog needed

#11390 Metadata should not depend on absolute text spans
  app/ydoc-server/package.json
  app/ydoc-server/src/fileFormat.ts
  app/ydoc-server/src/languageServerSession.ts
  pnpm-lock.yaml
Labels: CI: Ready to merge, CI: No changelog needed

#11404 Add eslint-react-compiler
  app/gui/package.json
  app/gui/src/dashboard/components/AriaComponents/Alert/Alert.tsx
  app/gui/src/dashboard/components/AriaComponents/Button/Button.tsx
  app/gui/src/dashboard/components/AriaComponents/Checkbox/Checkbox.tsx
  app/gui/src/dashboard/components/AriaComponents/Checkbox/CheckboxGroup.tsx
  app/gui/src/dashboard/components/AriaComponents/Dialog/Popover.tsx
  app/gui/src/dashboard/components/AriaComponents/Form/components/FormProvider.tsx
  app/gui/src/dashboard/components/AriaComponents/Form/components/useForm.ts
  app/gui/src/dashboard/components/AriaComponents/Inputs/Dropdown/Dropdown.tsx
  app/gui/src/dashboard/components/AriaComponents/Inputs/Input/Input.tsx
  app/gui/src/dashboard/components/AriaComponents/Inputs/OTPInput/OTPInput.tsx
  app/gui/src/dashboard/components/AriaComponents/Radio/Radio.tsx
  app/gui/src/dashboard/components/AriaComponents/Radio/RadioGroup.tsx
  app/gui/src/dashboard/components/AriaComponents/Switch/Switch.tsx
  app/gui/src/dashboard/components/AriaComponents/Text/Text.tsx
  app/gui/src/dashboard/components/Portal/Portal.tsx
  app/gui/src/dashboard/components/Portal/usePortal.ts
  app/gui/src/dashboard/hooks/eventCallbackHooks.ts
  app/gui/src/dashboard/hooks/mountHooks.ts
  app/gui/src/dashboard/hooks/syncRefHooks.ts
  app/gui/src/dashboard/hooks/useLazyMemoHooks.ts
  app/gui/src/dashboard/layouts/AssetDiffView/AssetDiffView.tsx
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
Labels: CI: No changelog needed, x-chore, g-dashboard

#11380 Batch refetches for different `listDirectory` queries
  app/gui/src/dashboard/layouts/AssetsTable.tsx
Labels: CI: Ready to merge, CI: No changelog needed, --low-performance, g-dashboard

#11423 Open enso devtools on call of toggleDevtools()
  app/gui/src/dashboard/App.tsx
  app/gui/src/dashboard/components/Devtools/EnsoDevtools.tsx
  app/gui/src/dashboard/components/Devtools/EnsoDevtoolsProvider.tsx
  app/gui/src/dashboard/components/Devtools/ReactQueryDevtools.tsx
  app/gui/src/dashboard/index.tsx
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#11373 Excel before 1900 and AWS signed requests.
  CHANGELOG.md
  distribution/lib/Standard/AWS/0.0.0-dev/src/AWS.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Header.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Extensions/Excel_Extensions.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Main.enso
  std-bits/aws/src/main/java/org/enso/aws/ClientBuilder.java
  std-bits/aws/src/main/java/org/enso/aws/SignedHttpClient.java
  std-bits/base/src/main/java/org/enso/base/net/http/MultipartBodyBuilder.java
  std-bits/base/src/main/java/org/enso/base/net/http/UrlencodedBodyBuilder.java
  std-bits/table/src/main/java/org/enso/table/excel/ExcelRow.java
  std-bits/table/src/main/java/org/enso/table/excel/ExcelUtils.java
  std-bits/table/src/main/java/org/enso/table/write/ExcelWriter.java
  test/Base_Tests/src/Network/Http_Spec.enso
  test/Table_Tests/data/OlderDates.xlsx
  test/Table_Tests/src/IO/Excel_Spec.enso
Labels: CI: Ready to merge

#11419 Removing useless `GraphOccurrence.Global` & some encapsulation
  engine/runtime-benchmarks/src/main/java/org/enso/compiler/benchmarks/inline/InlineCompilerBenchmark.java
  engine/runtime-benchmarks/src/main/java/org/enso/compiler/benchmarks/inline/InlineCompilerErrorBenchmark.java
  engine/runtime-benchmarks/src/main/java/org/enso/compiler/benchmarks/inline/InlineContextResource.java
  engine/runtime-benchmarks/src/main/java/org/enso/compiler/benchmarks/inline/InlineContextResourceFactory.java
  engine/runtime-benchmarks/src/main/java/org/enso/compiler/benchmarks/inline/InlineSource.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/PassPersistance.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/context/InlineContext.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/graph/Graph.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/graph/GraphOccurrence.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/pass/analyse/test/AliasAnalysisTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/pass/analyse/test/FramePointerAnalysisTest.scala
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#11416 Clean up SQLite file after the SQLite file tests have run.
  test/Table_Tests/src/Database/SQLite_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11393 Skeletal PanicExceptionTest and more logging when AssertionError happens
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/node/expression/builtin/error/PanicExceptionTest.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/text/Text.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicException.java
Labels: CI: No changelog needed

#11428 Dependency tracking between nodes is too coarse grained
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/ChangesetBuilder.scala
  engine/runtime-instrument-common/src/test/scala/org/enso/compiler/test/context/ChangesetBuilderTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#11402 Fix `Float.parse` benchmark regression
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso
  test/Base_Tests/src/Data/Numbers_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#11435 Table Input Widget: Size persistence
  CHANGELOG.md
  app/gui/src/project-view/components/GraphEditor/NodeWidgetTree.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetFunction.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor.vue
  app/gui/src/project-view/providers/widgetRegistry.ts
  app/gui/src/project-view/util/ast/reactive.ts
  app/ydoc-server/src/edits.ts
  app/ydoc-server/src/fileFormat.ts
  app/ydoc-server/src/languageServerSession.ts
  app/ydoc-shared/src/ast/mutableModule.ts
  app/ydoc-shared/src/ast/tree.ts
Labels: CI: Ready to merge, -gui

#11430 chore(flake.nix): Add missing macOS-specific dependencies of `enso-formatter`
  flake.nix
Labels: CI: Ready to merge, CI: No changelog needed

#11342 HTTP response caching, with TTL and LRU logic
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Utils.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Data_Read_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Cache_Policy.enso
  std-bits/base/src/main/java/org/enso/base/Stream_Utils.java
  std-bits/base/src/main/java/org/enso/base/cache/LRUCache.java
  std-bits/base/src/main/java/org/enso/base/cache/ResponseTooLargeException.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/EnsoHTTPResponseCache.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/EnsoSecretHelper.java
  test/Base_Tests/src/Network/Http_Spec.enso
  test/Table_Tests/src/IO/Fetch_Spec.enso
  tools/http-test-helper/src/main/java/org/enso/shttp/HTTPTestHelperServer.java
  tools/http-test-helper/src/main/java/org/enso/shttp/test_helpers/DownloadTestHandler.java
Labels: CI: Ready to merge, CI: Clean build required

#11446 Add IDE version to window title.
  CHANGELOG.md
  app/common/src/appConfig.js
  app/gui/index.html
  app/gui/vite.config.ts
Labels: CI: Ready to merge

#11421 Fix help panel
  app/gui/src/project-view/components/ComponentDocumentation.vue
  app/gui/src/project-view/components/DocumentationPanel.vue
  app/gui/src/project-view/components/DocumentationPanel/history.ts
  app/gui/src/project-view/components/GraphEditor.vue
Labels: p-highest, CI: Ready to merge, CI: No changelog needed, --bug, -gui

#11447 Add enter node button to the dropdown menu
  CHANGELOG.md
  app/gui/src/project-view/components/CircularMenu.vue
  app/gui/src/project-view/components/GraphEditor.vue
  app/gui/src/project-view/components/GraphEditor/GraphNode.vue
  app/gui/src/project-view/components/GraphEditor/GraphNodes.vue
  app/gui/src/project-view/composables/stackNavigator.ts
  app/gui/src/project-view/stores/graph/index.ts
Labels: CI: Ready to merge

#11433 Add undo/redo buttons to the top bar
  CHANGELOG.md
  app/gui/src/project-view/components/ControlButtons.vue
  app/gui/src/project-view/components/RecordControl.vue
  app/gui/src/project-view/components/TopBar.vue
  app/gui/src/project-view/components/UndoRedoButtons.vue
  app/gui/src/project-view/stores/graph/index.ts
  app/gui/src/project-view/util/data/observable.ts
Labels: CI: Ready to merge, x-new-feature, -gui

#11452 Display error message when viewed graph doesn't exist.
  .gitattributes
  CHANGELOG.md
  app/gui/src/project-view/components/GraphEditor.vue
  app/gui/src/project-view/components/GraphMissingView.vue
  app/gui/src/project-view/components/StandaloneButton.vue
  app/gui/src/project-view/components/SvgButton.vue
Labels: CI: Ready to merge

#11438 Expand and improve `pretty` for core data types, vector and table.
  distribution/lib/Standard/Base/0.0.0-dev/src/Any.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Period.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Of_Day.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Zone.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_Secret.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Response.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Response_Body.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Widgets.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyPrettyNode.java
  test/Base_Tests/src/Data/Array_Spec.enso
  test/Base_Tests/src/Data/Range_Spec.enso
  test/Base_Tests/src/Data/Time/Date_Range_Spec.enso
  test/Base_Tests/src/Data/Time/Date_Spec.enso
  test/Base_Tests/src/Data/Time/Date_Time_Spec.enso
  test/Base_Tests/src/Data/Time/Day_Of_Week_Spec.enso
  test/Base_Tests/src/Data/Time/Period_Spec.enso
  test/Base_Tests/src/Data/Time/Time_Of_Day_Spec.enso
  test/Base_Tests/src/Data/Vector_Spec.enso
  test/Base_Tests/src/Network/Http_Spec.enso
  test/Table_Tests/src/In_Memory/Column_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11382 Optimize asset table rendering
  app/common/package.json
  app/common/src/services/Backend.ts
  app/common/src/utilities/data/object.ts
  app/gui/src/dashboard/components/dashboard/AssetRow.tsx
  app/gui/src/dashboard/components/dashboard/DatalinkNameColumn.tsx
  app/gui/src/dashboard/components/dashboard/DirectoryNameColumn.tsx
  app/gui/src/dashboard/components/dashboard/FileNameColumn.tsx
  app/gui/src/dashboard/components/dashboard/ProjectNameColumn.tsx
  app/gui/src/dashboard/components/dashboard/SecretNameColumn.tsx
  app/gui/src/dashboard/components/dashboard/column.ts
  app/gui/src/dashboard/components/dashboard/column/DocsColumn.tsx
  app/gui/src/dashboard/components/dashboard/column/LabelsColumn.tsx
  app/gui/src/dashboard/components/dashboard/column/ModifiedColumn.tsx
  app/gui/src/dashboard/components/dashboard/column/SharedWithColumn.tsx
  app/gui/src/dashboard/events/AssetEventType.ts
  app/gui/src/dashboard/events/assetEvent.ts
  app/gui/src/dashboard/hooks/backendHooks.ts
  app/gui/src/dashboard/layouts/AssetContextMenu.tsx
  app/gui/src/dashboard/layouts/AssetPanel.tsx
  app/gui/src/dashboard/layouts/AssetProjectSessions.tsx
  app/gui/src/dashboard/layouts/AssetProperties.tsx
  app/gui/src/dashboard/layouts/AssetVersions/AssetVersion.tsx
  app/gui/src/dashboard/layouts/AssetVersions/AssetVersions.tsx
  app/gui/src/dashboard/layouts/AssetsTable.tsx
  app/gui/src/dashboard/pages/dashboard/Dashboard.tsx
  app/gui/src/dashboard/services/LocalBackend.ts
  app/gui/src/dashboard/utilities/AssetTreeNode.ts
  pnpm-lock.yaml
Labels: CI: Ready to merge, CI: No changelog needed, --regression, g-dashboard

#11405 Add React compiler
  app/gui/package.json
  app/gui/src/dashboard/components/MenuEntry.tsx
  app/gui/src/dashboard/components/dashboard/AssetRow.tsx
  app/gui/src/dashboard/components/dashboard/TheModal.tsx
  app/gui/src/dashboard/components/dashboard/columnHeading/ModifiedColumnHeading.tsx
  app/gui/src/dashboard/components/dashboard/columnHeading/NameColumnHeading.tsx
  app/gui/src/dashboard/layouts/AssetContextMenu.tsx
  app/gui/src/dashboard/layouts/AssetsTable.tsx
  app/gui/src/dashboard/layouts/AssetsTableContextMenu.tsx
  app/gui/src/dashboard/layouts/GlobalContextMenu.tsx
  app/gui/src/dashboard/modals/AgreementsModal.tsx
  app/gui/src/dashboard/providers/ModalProvider.tsx
  app/gui/vite.config.ts
  pnpm-lock.yaml
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#11422 Fixing small bugs uncovered by type checker
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Examples/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Matrix.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Multi_Value_Key.enso
  test/Examples_Tests/src/Examples_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11440 Enso_File integration update: Multi-part upload and presigned URL for download
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Enso_File_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Request_Body.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Extensions.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Test_Reporter.enso
  test/Base_Tests/src/Network/Enso_Cloud/Enso_File_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11401 Fix Meta.get_qualified_type_name when run as single file
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/caches/HelloWorldCacheTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/meta/QualifiedNameTest.java
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/context/SuggestionBuilderTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/refactoring/IRUtilsTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/semantic/ImportExportTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/semantic/TypeSignaturesTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/node/ProgramRootNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/TopLevelScope.java
  lib/scala/pkg/src/main/scala/org/enso/pkg/QualifiedName.scala
  test/Base_Tests/src/Semantic/Meta_Location_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed
