Repository enso-org/enso, pull requests merged in 2024-12, with the labels that each got.

#11720 Refactor runtime-integration-tests - move some tests to more dedicated packages
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/hash/HashCodeTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/instrument/InsightForEnsoTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/interop/AtomInteropTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/interop/JavaInteropTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/interop/JsInteropTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/interop/MetaObjectPolyglotTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/interop/MetaObjectTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/interop/TypeMembersTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/interop/TypesExposeConstructorsTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/meta/MetaIsAPolyglotTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/meta/MetaIsATest.java
Labels: CI: No changelog needed, CI: Clean build required, x-refactor

#11701 Fix copy and paste on local backend
  app/common/src/services/Backend.ts
  app/gui/src/dashboard/components/dashboard/AssetRow.tsx
Labels: CI: No changelog needed, --bug, g-dashboard

#11726 Fix nightly build
  .github/workflows/nightly.yml
  build/build/src/ci/input.rs
  build/build/src/ci_gen.rs
Labels: CI: Ready to merge, CI: No changelog needed, -ci, -build-script

#11712 Simplify shutdown logic on client disconnect in project-manager
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistry.scala
  lib/scala/json-rpc-server/src/main/scala/org/enso/jsonrpc/JsonRpcServer.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerController.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectShutdownSpec.scala
Labels: CI: No changelog needed

#11743 Fix `Data.list` for other file systems
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_File.enso
  test/AWS_Tests/src/S3_Spec.enso
  test/Base_Tests/src/Network/Enso_Cloud/Enso_File_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11715 Extend output port and remove selection halo
  CHANGELOG.md
  app/gui/integration-test/project-view/selectingNodes.spec.ts
  app/gui/src/project-view/assets/base.css
  app/gui/src/project-view/components/GraphEditor/GraphNode.vue
  app/gui/src/project-view/components/GraphEditor/GraphNodeOutputPorts.vue
Labels: CI: Ready to merge, -gui

#11744 Fix drop-down menu
  app/gui/src/project-view/components/DropdownMenu.vue
  app/gui/src/project-view/composables/events.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, --regression, -gui

#11577 Enhance `Managed_Resource` to allow implementation of in-memory caches
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Runtime/Managed_Resource.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/Input_Stream.enso
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/ExecCompilerTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/runtime/ManagedResourceTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/runtime/RefTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/instrument/IncrementalUpdatesTest.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/resource/WithNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/special/NewRefNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/special/ReadRefNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/special/WriteRefNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/ResourceManager.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Special.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/ManagedResource.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/DataflowError.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/MethodProcessor.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/model/MethodDefinition.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/EnsoSecretHelper.java
  test/Base_Tests/src/Runtime/Managed_Resource_Spec.enso
  test/Table_Tests/src/IO/Fetch_Spec.enso
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Runtime/Resource.enso
Labels: CI: Clean build required

#11735 Do not send the generated name to the Backend
  app/gui/integration-test/dashboard/api.ts
  app/gui/integration-test/dashboard/assetPanel.spec.ts
  app/gui/integration-test/dashboard/assetSearchBar.spec.ts
  app/gui/integration-test/dashboard/sort.spec.ts
  app/gui/src/dashboard/hooks/backendHooks.tsx
  app/gui/src/dashboard/services/RemoteBackend.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#11682 Further simplification enabled by chained conversions
  lib/rust/parser/src/syntax/token/operator.rs
Labels: CI: Ready to merge, CI: No changelog needed

#11694 Filter drilldown for mixed column
  app/gui/src/project-view/components/visualizations/TableVisualization.vue
  app/gui/src/project-view/components/visualizations/TableVisualization/TableVisualisationTooltip.ts
  app/gui/src/project-view/components/visualizations/TableVisualization/tableVizToolbar.ts
  app/gui/src/project-view/components/visualizations/TableVisualization/tableVizUtils.ts
  app/gui/src/project-view/components/visualizations/__tests__/tableVizUtilsTests.spec.ts
Labels: CI: Ready to merge, CI: No changelog needed

#11739 Fix reconnecting after hibernation on Windows
  app/gui/src/project-view/components/GraphEditor/toasts.ts
  app/gui/src/project-view/stores/project/executionContext.ts
  app/ydoc-server/src/languageServerSession.ts
  app/ydoc-shared/src/util/data/result.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#11750 check for long negavtive numbers not just positive
  app/gui/src/project-view/components/visualizations/TableVisualization.vue
Labels: CI: Ready to merge, CI: No changelog needed

#11765 Compute correct changeset when swapping nodes
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/ChangesetBuilder.scala
  engine/runtime-instrument-common/src/test/scala/org/enso/compiler/test/context/ChangesetBuilderTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#11768 Fix visualization toolbar dropdown layering
  CHANGELOG.md
  app/gui/src/project-view/components/GraphEditor/GraphVisualization.vue
Labels: CI: Ready to merge

#11769 Fix persistence of output component metadata
  app/ydoc-server/src/languageServerSession.ts
  app/ydoc-shared/src/ast/idMap.ts
  app/ydoc-shared/src/ast/mutableModule.ts
Labels: CI: Ready to merge, CI: No changelog needed

#11771 Fix rounded corners and improve styling on grid visualization
  app/gui/src/project-view/components/GraphEditor/GraphVisualization.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor.vue
  app/gui/src/project-view/components/shared/AgGridTableView.vue
  app/gui/src/project-view/components/visualizations/TableVisualization.vue
Labels: CI: Ready to merge, CI: No changelog needed

#11756 Revert sorting order
  app/common/src/services/Backend.ts
  app/gui/src/dashboard/hooks/backendHooks.tsx
  app/gui/src/dashboard/services/__test__/Backend.test.ts
Labels: CI: No changelog needed, --regression, g-dashboard

#11759 Revert to network (graph) icon for GUI editor tabs
  app/gui/src/dashboard/pages/dashboard/DashboardTabBar.tsx
Labels: CI: Ready to merge, CI: No changelog needed, --regression, g-dashboard

#11764 Row display in Table viz in correct order
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11754 Fix failure to parse an invalid syntax case
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/resolve/ExpressionAnnotationsTest.scala
  lib/rust/parser/debug/tests/parse.rs
  lib/rust/parser/src/syntax/operator/application.rs
  lib/rust/parser/src/syntax/operator/reducer.rs
  lib/rust/parser/src/syntax/operator/types.rs
  lib/rust/parser/src/syntax/statement.rs
  lib/rust/parser/src/syntax/statement/function_def.rs
  lib/rust/parser/src/syntax/token/operator.rs
  lib/rust/parser/src/syntax/tree.rs
  lib/rust/parser/src/syntax/treebuilding/whitespace.rs
Labels: CI: Ready to merge, CI: No changelog needed

#11786 Component menu button opens single-component menu
  app/gui/src/project-view/components/GraphEditor/GraphNode.vue
Labels: CI: Ready to merge, CI: No changelog needed

#11761 Update persisted idmap when metadata changes
  CHANGELOG.md
  app/gui/integration-test/project-view/tableVisualisation.spec.ts
  app/ydoc-server/src/edits.ts
  app/ydoc-server/src/languageServerSession.ts
  app/ydoc-shared/src/ast/tree.ts
Labels: CI: Ready to merge, --bug, -gui

#11797 Add import field to metadata to satisfy older versions
  app/ydoc-server/src/edits.ts
  app/ydoc-server/src/languageServerSession.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui

#11789 Fix performance deterioration after many external or code-editor edits.
  app/gui/src/project-view/util/ast/__tests__/abstract.test.ts
  app/ydoc-shared/src/ast/mutableModule.ts
  app/ydoc-shared/src/ast/parse.ts
  app/ydoc-shared/src/ast/syncToCode.ts
Labels: CI: Ready to merge, CI: No changelog needed

#11800 Visualization selector arrow is now more visible
  CHANGELOG.md
  app/gui/src/project-view/components/DropdownMenu.vue
  app/gui/src/project-view/components/ExtendedMenu.vue
Labels: CI: Ready to merge, -gui

#11773 Paste HTML as Markdown in documentation editor
  app/gui/package.json
  app/gui/src/project-view/components/DocumentationEditor.vue
  app/gui/src/project-view/components/GraphEditor.vue
  app/gui/src/project-view/components/MarkdownEditor/__tests__/__snapshots__/htmlPaste.test.ts.snap
  app/gui/src/project-view/components/MarkdownEditor/__tests__/fixtures/google_docs1.html.bin
  app/gui/src/project-view/components/MarkdownEditor/__tests__/fixtures/preppin_data_2024w1.html.bin
  app/gui/src/project-view/components/MarkdownEditor/__tests__/htmlPaste.test.ts
  app/gui/src/project-view/components/MarkdownEditor/htmlToMarkdown/htmlToMarkdownImpl.ts
  app/gui/src/project-view/components/MarkdownEditor/htmlToMarkdown/imageNode.ts
  app/gui/src/project-view/components/MarkdownEditor/htmlToMarkdown/index.ts
  app/gui/src/project-view/components/MarkdownEditor/htmlToMarkdown/linkNode.ts
  app/ydoc-shared/src/ast/documentation.ts
  pnpm-lock.yaml
Labels: CI: Ready to merge, CI: No changelog needed

#11775 Adding "Warnings note" to suspicious sections in types documentation.
  docs/semantics/errors.md
  docs/types/README.md
  docs/types/access-modifiers.md
  docs/types/contexts.md
  docs/types/dynamic-dispatch.md
  docs/types/errors.md
  docs/types/evaluation.md
  docs/types/function-types.md
  docs/types/goals.md
  docs/types/hierarchy.md
  docs/types/inference-and-checking.md
  docs/types/modules.md
  docs/types/parallelism.md
  docs/types/pattern-matching.md
  docs/types/references.md
  docs/types/type-directed-programming.md
Labels: w-docs, CI: No changelog needed, -compiler

#11796 Bump required launcher version for new engine releases, forcing an upgrade to compatible version
  distribution/manifest.template.yaml
Labels: CI: Ready to merge, CI: No changelog needed

#11804 Project Manager fails to create directory when one exists
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/file/BlockingFileSystem.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/service/filesystem/FileSystemServiceSpec.scala
Labels: CI: Ready to merge, CI: No changelog needed

#11805 Avoid storing 0.0.0-dev into package.yaml
  build.sbt
  lib/scala/pkg/src/main/java/module-info.java
  lib/scala/pkg/src/main/scala/org/enso/pkg/Config.scala
  lib/scala/pkg/src/test/scala/org/enso/pkg/ConfigSpec.scala
Labels: CI: Ready to merge, CI: No changelog needed

#11810 Color edges according to source node.
  .prettierignore
  CHANGELOG.md
  app/gui/src/project-view/components/ComponentBrowser.vue
  app/gui/src/project-view/components/GraphEditor/GraphEdge.vue
  app/gui/src/project-view/components/GraphEditor/GraphEdge/layout.ts
  app/gui/src/project-view/stores/graph/unconnectedEdges.ts
Labels: CI: Ready to merge

#11813 Fix Dates in row visualization
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11799 Correctly format big integers
  app/gui/src/project-view/components/visualizations/TableVisualization.vue
  app/gui/src/project-view/components/visualizations/TableVisualization/tableVizUtils.ts
  app/gui/src/project-view/components/visualizations/__tests__/tableVizUtilsTests.spec.ts
Labels: CI: Ready to merge, CI: No changelog needed

#11809 Refactor drilldown code and add SQL_Server set up
  app/gui/src/project-view/components/visualizations/TableVisualization.vue
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Postgres_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/SQLite_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Common/Connections_Helpers.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/SQLServer_Connection.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Snowflake_Connection.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Workbook.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
  test/Visualization_Tests/src/Table_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11807 Including opencv native libraries as resources in enso runner binary
  build.sbt
  build/build/src/engine/context.rs
  engine/runner/src/main/java/org/enso/runner/EnsoLibraryFeature.java
Labels: CI: No changelog needed

#11802 Allow `Data.list` to cross data links
  distribution/lib/Standard/AWS/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3_Data_Link.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Data_Link_Capabilities.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Data_Link_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Enso_File_Data_Link.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Group.enso
  test/AWS_Tests/src/S3_Spec.enso
  test/Base_Tests/data/transient/.gitignore
  test/Base_Tests/src/Network/Enso_Cloud/Cloud_Data_Link_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11823 Fix required launcher version
  distribution/manifest.template.yaml
Labels: CI: Ready to merge, CI: No changelog needed

#11787 Fix `getFileDetails` and `getProjectDetails`
  app/common/src/services/Backend.ts
  app/gui/src/dashboard/components/dashboard/AssetRow.tsx
  app/gui/src/dashboard/services/RemoteBackend.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#11801 Fix bug causing intermittent GUI unit test failures
  app/gui/src/project-view/util/__tests__/array.test.ts
  app/gui/src/project-view/util/data/array.ts
Labels: CI: Ready to merge, CI: No changelog needed

#11780 Schedule rename symbol job after compilation
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/RenameSymbolCmd.scala
Labels: CI: Ready to merge, CI: No changelog needed

#11824 Some more QA fixes
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Simple_Expression.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Text.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11738 Fix HTTP cache assertion failure for small disks
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso
  std-bits/base/src/main/java/org/enso/base/cache/LRUCache.java
  std-bits/base/src/main/java/org/enso/base/cache/LRUCacheSettings.java
  std-bits/base/src/main/java/org/enso/base/cache/ResponseTooLargeException.java
  test/Table_Tests/src/IO/Fetch_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11673 Clear cache on reload
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/Reload_Detector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Runtime/Managed_Resource.enso
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/RecomputeContextCmd.scala
  std-bits/base/src/main/java/org/enso/base/cache/LRUCache.java
  std-bits/base/src/main/java/org/enso/base/cache/ReloadDetector.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/EnsoSecretHelper.java
  test/Base_Tests/src/Runtime/Managed_Resource_Spec.enso
  test/Table_Tests/src/IO/Fetch_Spec.enso
Labels: CI: Ready to merge

#11834 Fix CB port color
  app/gui/src/project-view/components/ComponentBrowser/ComponentEditor.vue
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui

#11839 Change table viz colors
  app/gui/src/project-view/assets/base.css
  app/gui/src/project-view/components/shared/AgGridTableView.vue
  app/gui/src/project-view/components/visualizations/TableVisualization.vue
  app/gui/src/project-view/components/visualizations/TableVisualization/tableVizToolbar.ts
Labels: CI: Ready to merge, CI: No changelog needed

#11763 Combine context menus into single context menu
  app/gui/integration-test/dashboard/actions/DrivePageActions.ts
  app/gui/integration-test/dashboard/actions/index.ts
  app/gui/integration-test/dashboard/contextMenus.spec.ts
  app/gui/integration-test/dashboard/copy.spec.ts
  app/gui/integration-test/dashboard/editAssetName.spec.ts
  app/gui/integration-test/dashboard/labels.spec.ts
  app/gui/src/dashboard/components/ContextMenu.tsx
  app/gui/src/dashboard/components/ContextMenus.tsx
  app/gui/src/dashboard/components/dashboard/column/LabelsColumn.tsx
  app/gui/src/dashboard/hooks/contextMenuHooks.tsx
  app/gui/src/dashboard/layouts/AssetContextMenu.tsx
  app/gui/src/dashboard/layouts/AssetsTableContextMenu.tsx
  app/gui/src/dashboard/layouts/GlobalContextMenu.tsx
  app/gui/src/dashboard/layouts/Settings/UserGroupRow.tsx
  app/gui/src/dashboard/layouts/Settings/UserGroupUserRow.tsx
  app/gui/src/dashboard/layouts/Settings/UserRow.tsx
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#11841 Color missing value messages blue
  app/gui/src/project-view/assets/base.css
  app/gui/src/project-view/components/GraphEditor/GraphNode.vue
  app/gui/src/project-view/components/GraphEditor/GraphNodeMessage.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetArgumentName.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetText.vue
Labels: CI: Ready to merge, CI: No changelog needed

#11843 Fix visualization on values derived from secrets
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_Secret.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11832 Fix clicking-out Component Browser
  app/gui/src/project-view/components/ComponentBrowser.vue
  app/gui/src/project-view/components/DockPanel.vue
  app/gui/src/project-view/components/GraphEditor.vue
Labels: p-highest, CI: Ready to merge, CI: No changelog needed, --bug, -gui

#11826 Sticky headers for settings tables
  app/gui/src/dashboard/components/dashboard/AssetRow.tsx
  app/gui/src/dashboard/components/dashboard/column/columnUtils.ts
  app/gui/src/dashboard/components/dashboard/columnHeading/NameColumnHeading.tsx
  app/gui/src/dashboard/hooks/scrollHooks.ts
  app/gui/src/dashboard/layouts/AssetsTable.tsx
  app/gui/src/dashboard/layouts/Settings/KeyboardShortcutsSettingsSection.tsx
  app/gui/src/dashboard/layouts/Settings/MembersSettingsSection.tsx
  app/gui/src/dashboard/layouts/Settings/MembersTable.tsx
  app/gui/src/dashboard/layouts/Settings/Section.tsx
  app/gui/src/dashboard/layouts/Settings/Tab.tsx
  app/gui/src/dashboard/layouts/Settings/UserGroupsSettingsSection.tsx
  app/gui/src/dashboard/layouts/Settings/data.tsx
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#11600 Intersection types & type checks
  CHANGELOG.md
  docs/syntax/README.md
  docs/syntax/conversions.md
  docs/types/README.md
  docs/types/hierarchy.md
  docs/types/intersection-types.md
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/node/expression/builtin/meta/TypeOfNodeMultiValueTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/node/typecheck/TypeCheckValueTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/EnsoMultiValueInteropTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/EqualsMultiValueTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/SignatureTest.java
  engine/runtime/src/main/java/org/enso/interpreter/node/BinaryOperatorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeConversionNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsAndInfo.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsSimpleNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/typecheck/AbstractTypeCheckNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/typecheck/AllOfTypesCheckNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/typecheck/MetaTypeCheckNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/typecheck/SingleTypeCheckNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/typecheck/TypeCheckExpressionNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/typecheck/TypeCheckValueNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoMultiValue.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
  lib/java/test-utils/src/main/java/org/enso/test/utils/ContextUtils.java
  test/Base_Tests/src/Data/Complex.enso
  test/Base_Tests/src/Main.enso
  test/Base_Tests/src/Semantic/Multi_Value_Convert_Spec.enso
  test/Base_Tests/src/Semantic/Multi_Value_Spec.enso
Labels: CI: Ready to merge

#11842 Fix benchmarks upload GH Action
  .github/workflows/bench-upload.yml
  .gitignore
  tools/performance/engine-benchmarks/README.md
  tools/performance/engine-benchmarks/bench_tool/__init__.py
  tools/performance/engine-benchmarks/bench_tool/remote_cache.py
  tools/performance/engine-benchmarks/bench_tool/test_bench_results.py
  tools/performance/engine-benchmarks/bench_tool/test_remote_cache.py
  tools/performance/engine-benchmarks/bench_tool/test_website_regen.py
Labels: CI: Ready to merge, CI: No changelog needed

#11833 Fix `ensoup` launcher upgrade mechanism
  engine/launcher/src/main/scala/org/enso/launcher/InfoLogger.scala
  engine/launcher/src/main/scala/org/enso/launcher/releases/LauncherRepository.scala
  engine/launcher/src/main/scala/org/enso/launcher/releases/launcher/LauncherReleaseProvider.scala
  engine/launcher/src/main/scala/org/enso/launcher/upgrade/LauncherUpgrader.scala
  engine/launcher/src/test/resources/org/enso/launcher/components/fake-releases/launcher/enso-1.0.1/launcher-manifest.yaml
  engine/launcher/src/test/resources/org/enso/launcher/components/fake-releases/launcher/enso-1.0.2/enso-launcher-1.0.2-linux-amd64.tar.gz/enso/README.md
  engine/launcher/src/test/resources/org/enso/launcher/components/fake-releases/launcher/enso-1.0.2/enso-launcher-1.0.2-linux-amd64.tar.gz/enso/THIRD-PARTY/test-license.txt
  engine/launcher/src/test/resources/org/enso/launcher/components/fake-releases/launcher/enso-1.0.2/enso-launcher-1.0.2-macos-amd64.tar.gz/enso/README.md
  engine/launcher/src/test/resources/org/enso/launcher/components/fake-releases/launcher/enso-1.0.2/enso-launcher-1.0.2-macos-amd64.tar.gz/enso/THIRD-PARTY/test-license.txt
  engine/launcher/src/test/resources/org/enso/launcher/components/fake-releases/launcher/enso-1.0.2/enso-launcher-1.0.2-windows-amd64.zip/enso/README.md
  engine/launcher/src/test/resources/org/enso/launcher/components/fake-releases/launcher/enso-1.0.2/enso-launcher-1.0.2-windows-amd64.zip/enso/THIRD-PARTY/test-license.txt
  engine/launcher/src/test/resources/org/enso/launcher/components/fake-releases/launcher/enso-1.0.2/launcher-manifest.yaml
  engine/launcher/src/test/resources/org/enso/launcher/components/fake-releases/launcher/enso-1.0.3/launcher-manifest.yaml
  engine/launcher/src/test/resources/org/enso/launcher/components/fake-releases/launcher/enso-1.0.4/launcher-manifest.yaml
  engine/launcher/src/test/resources/org/enso/launcher/components/fake-releases/launcher/enso-99.9999.0/broken
  engine/launcher/src/test/resources/org/enso/launcher/components/fake-releases/launcher/enso-99.9999.0/launcher-manifest.yaml
  engine/launcher/src/test/scala/org/enso/launcher/NativeTest.scala
  engine/launcher/src/test/scala/org/enso/launcher/upgrade/UpgradeSpec.scala
  lib/rust/launcher-shims/src/bin/launcher_000dev.rs
  lib/rust/launcher-shims/src/bin/launcher_001.rs
  lib/rust/launcher-shims/src/bin/launcher_002.rs
  lib/rust/launcher-shims/src/bin/launcher_003.rs
  lib/rust/launcher-shims/src/bin/launcher_004.rs
  lib/rust/launcher-shims/src/bin/launcher_101.rs
  lib/rust/launcher-shims/src/bin/launcher_102.rs
  lib/rust/launcher-shims/src/bin/launcher_103.rs
  lib/rust/launcher-shims/src/bin/launcher_104.rs
  lib/rust/launcher-shims/src/bin/launcher_9999990.rs
  lib/rust/launcher-shims/src/lib.rs
  lib/scala/cli/src/main/scala/org/enso/cli/task/MappedTask.scala
  lib/scala/cli/src/main/scala/org/enso/cli/task/TaskProgress.scala
  lib/scala/downloader/src/main/scala/org/enso/downloader/http/HTTPDownload.scala
  lib/scala/downloader/src/main/scala/org/enso/downloader/http/HTTPRequest.scala
  lib/scala/runtime-version-manager/src/main/java/org/enso/runtimeversionmanager/releases/testing/CompressZipArchive.java
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/releases/ReleaseProviderException.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/releases/github/GithubAPI.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/releases/testing/FakeReleaseProvider.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/releases/testing/TestArchivePackager.scala
  project/NativeImage.scala
Labels: CI: Ready to merge, CI: No changelog needed

#11850 case of and intersection types
  distribution/lib/Standard/Test/0.0.0-dev/src/Extensions.enso
  docs/types/intersection-types.md
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionCallbacks.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/node/expression/builtin/meta/TypeOfNodeMultiValueTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/node/expression/builtin/meta/TypeOfNodeValueTest.java
  engine/runtime/src/main/java/org/enso/interpreter/node/BinaryOperatorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/CatchTypeBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/CatchPanicNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/GetStackTraceTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsSimpleNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/IsANode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/IsValueOfTypeNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/typecheck/MetaTypeCheckNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/typecheck/SingleTypeCheckNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoMultiValue.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/library/dispatch/TypeOfNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/library/dispatch/TypesLibrary.java
  test/Base_Tests/src/Semantic/Multi_Value_Spec.enso
Labels: CI: No changelog needed, CI: Clean build required

#11862 Fix sending same refreshToken as accessToken in open project request
  .prettierignore
  app/gui/src/dashboard/hooks/projectHooks.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#11860 `aggregate ..Sum` of integer column remains integer and handles overflow
  std-bits/table/src/main/java/org/enso/table/aggregations/Aggregator.java
  std-bits/table/src/main/java/org/enso/table/aggregations/Concatenate.java
  std-bits/table/src/main/java/org/enso/table/aggregations/Count.java
  std-bits/table/src/main/java/org/enso/table/aggregations/CountDistinct.java
  std-bits/table/src/main/java/org/enso/table/aggregations/CountEmpty.java
  std-bits/table/src/main/java/org/enso/table/aggregations/CountNothing.java
  std-bits/table/src/main/java/org/enso/table/aggregations/First.java
  std-bits/table/src/main/java/org/enso/table/aggregations/GroupBy.java
  std-bits/table/src/main/java/org/enso/table/aggregations/KnownTypeAggregator.java
  std-bits/table/src/main/java/org/enso/table/aggregations/Last.java
  std-bits/table/src/main/java/org/enso/table/aggregations/Mean.java
  std-bits/table/src/main/java/org/enso/table/aggregations/MinOrMax.java
  std-bits/table/src/main/java/org/enso/table/aggregations/Mode.java
  std-bits/table/src/main/java/org/enso/table/aggregations/Percentile.java
  std-bits/table/src/main/java/org/enso/table/aggregations/ShortestOrLongest.java
  std-bits/table/src/main/java/org/enso/table/aggregations/StandardDeviation.java
  std-bits/table/src/main/java/org/enso/table/aggregations/Sum.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/InferredIntegerBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/index/CrossTabIndex.java
  std-bits/table/src/main/java/org/enso/table/data/index/MultiValueIndex.java
  test/Base_Tests/src/Data/Statistics_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Aggregate_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10877 Excel Reading (XLSX) using SAX Default Handler
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Workbook.enso
  std-bits/table/src/main/java/org/enso/table/excel/ExcelConnectionPool.java
  std-bits/table/src/main/java/org/enso/table/excel/ExcelFileFormat.java
  std-bits/table/src/main/java/org/enso/table/excel/ExcelHeaders.java
  std-bits/table/src/main/java/org/enso/table/excel/ExcelRange.java
  std-bits/table/src/main/java/org/enso/table/excel/ExcelRow.java
  std-bits/table/src/main/java/org/enso/table/excel/ExcelSheet.java
  std-bits/table/src/main/java/org/enso/table/excel/ExcelUtils.java
  std-bits/table/src/main/java/org/enso/table/excel/ExcelWorkbook.java
  std-bits/table/src/main/java/org/enso/table/excel/ReadOnlyExcelConnection.java
  std-bits/table/src/main/java/org/enso/table/excel/xssfreader/XSSFReaderFormats.java
  std-bits/table/src/main/java/org/enso/table/excel/xssfreader/XSSFReaderRow.java
  std-bits/table/src/main/java/org/enso/table/excel/xssfreader/XSSFReaderSheet.java
  std-bits/table/src/main/java/org/enso/table/excel/xssfreader/XSSFReaderSheetXMLHandler.java
  std-bits/table/src/main/java/org/enso/table/excel/xssfreader/XSSFReaderWorkbook.java
  std-bits/table/src/main/java/org/enso/table/read/ExcelReader.java
  std-bits/table/src/main/java/org/enso/table/write/ExcelWriter.java
  test/Table_Tests/src/IO/Excel_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11852 CodeEditor improvements
  app/gui/package.json
  app/gui/src/project-view/components/CodeEditor/CodeEditorImpl.vue
  app/gui/src/project-view/components/CodeEditor/CodeEditorTooltip.vue
  app/gui/src/project-view/components/CodeEditor/diagnostics.ts
  app/gui/src/project-view/components/CodeEditor/ensoSyntax.ts
  app/gui/src/project-view/components/CodeEditor/sync.ts
  app/gui/src/project-view/components/CodeEditor/tooltips.ts
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetFunction/__tests__/widgetFunctionCallInfo.test.ts
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetHierarchy.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetToken.vue
  app/gui/src/project-view/stores/graph/__tests__/graphDatabase.test.ts
  app/gui/src/project-view/util/ast/__tests__/aliasAnalysis.test.ts
  app/gui/src/project-view/util/ast/abstract.ts
  app/gui/src/project-view/util/ast/aliasAnalysis.ts
  app/gui/src/project-view/util/ast/bindings.ts
  app/gui/src/project-view/util/ast/extended.ts
  app/gui/src/project-view/util/ast/raw.ts
  app/gui/src/project-view/util/codemirror/index.ts
  app/gui/src/project-view/util/codemirror/text.ts
  app/ydoc-server/src/serialization.ts
  app/ydoc-shared/src/__tests__/yjsModel.test.ts
  app/ydoc-shared/src/ast/idMap.ts
  app/ydoc-shared/src/ast/mutableModule.ts
  app/ydoc-shared/src/ast/repair.ts
  app/ydoc-shared/src/ast/sourceDocument.ts
  app/ydoc-shared/src/ast/syncToCode.ts
  app/ydoc-shared/src/ast/token.ts
  app/ydoc-shared/src/ast/tree.ts
  app/ydoc-shared/src/util/data/__tests__/text.test.ts
  app/ydoc-shared/src/util/data/text.ts
  app/ydoc-shared/src/util/lezer.ts
  app/ydoc-shared/src/yjsModel.ts
  pnpm-lock.yaml
Labels: CI: Ready to merge, CI: No changelog needed

#11851 Fix unused variable warning
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/Reload_Detector.enso
  std-bits/base/src/main/java/org/enso/base/cache/LRUCache.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/EnsoSecretHelper.java
Labels: CI: Ready to merge, CI: No changelog needed

#11856 Disallow a confusing constructor syntax
  CHANGELOG.md
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/AnnotationsCompilerTest.java
  lib/rust/parser/debug/src/lib.rs
  lib/rust/parser/debug/tests/parse.rs
  lib/rust/parser/src/macros/built_in.rs
  lib/rust/parser/src/syntax/statement/function_def.rs
  lib/rust/parser/src/syntax/statement/type_def.rs
Labels: CI: Ready to merge

#11876 Update licenses codeowners
  .github/CODEOWNERS
Labels: CI: Ready to merge, CI: No changelog needed

#11888 Add Missing_Argument error to join right
  app/gui/src/project-view/util/callTree.ts
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
Labels: CI: No changelog needed

#11875 Enable prettier on docs markdown
  .github/workflows/gui-checks.yml
  .github/workflows/gui-pull-request.yml
  .prettierignore
  docs/semantics/errors.md
  docs/syntax/README.md
  docs/syntax/conversions.md
  docs/types/README.md
  docs/types/access-modifiers.md
  docs/types/contexts.md
  docs/types/dynamic-dispatch.md
  docs/types/errors.md
  docs/types/evaluation.md
  docs/types/function-types.md
  docs/types/goals.md
  docs/types/hierarchy.md
  docs/types/inference-and-checking.md
  docs/types/intersection-types.md
  docs/types/modules.md
  docs/types/parallelism.md
  docs/types/pattern-matching.md
  docs/types/type-directed-programming.md
Labels: CI: No changelog needed

#11871 Stricter URL recognition for autolinking
  app/gui/src/project-view/components/DocumentationEditor/__tests__/textPaste.test.ts
  app/gui/src/project-view/components/DocumentationEditor/textPaste.ts
  app/gui/src/project-view/components/PlainTextEditor/___tests__/urlLinks.test.ts
  app/gui/src/project-view/util/__tests__/link.test.ts
  app/gui/src/project-view/util/link.ts
Labels: CI: Ready to merge, CI: No changelog needed

#11892 RenameSymbol request allows collisions
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/refactoring/RefactoringApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/refactoring/RenameFailureMapper.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/refactoring/IRUtils.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/RefactoringRenameJob.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeRefactoringTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#11705 Wip/mk/display message on warning
  app/gui/src/project-view/components/visualizations/JSONVisualization/JsonErrorWidget.vue
  app/gui/src/project-view/components/visualizations/JSONVisualization/JsonValueWidget.vue
  app/gui/src/project-view/components/visualizations/WarningsVisualization.vue
Labels: CI: Ready to merge, CI: No changelog needed

#11885 Consume fetch stream output in tests
  test/Table_Tests/src/IO/Fetch_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11890 Last Bits for Release
  distribution/lib/Standard/AWS/0.0.0-dev/src/Database/Redshift/Internal/Redshift_Dialect.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Data_Link_Capabilities.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/Reload_Detector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Runtime/Managed_Resource.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/Input_Stream.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Postgres_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Columns_To_Keep.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Workbook.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Extensions/Table_Conversions.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Expand_Objects_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
  lib/scala/pkg/src/main/resources/default/src/Main.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11891 Fix ag grid header style
  app/gui/src/project-view/components/visualizations/TableVisualization.vue
Labels: CI: No changelog needed, --bug, -gui

#11886 Share Name.Literal strings
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/passes/MethodCallsTest.java
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Name.scala
  lib/java/persistance-dsl/src/main/java/org/enso/persist/impl/PersistableProcessor.java
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#11836 Create node from port button
  CHANGELOG.md
  app/gui/integration-test/project-view/actions.ts
  app/gui/integration-test/project-view/componentBrowser.spec.ts
  app/gui/integration-test/project-view/graphNodeVisualization.spec.ts
  app/gui/integration-test/project-view/locate.ts
  app/gui/integration-test/project-view/nodeComments.spec.ts
  app/gui/integration-test/project-view/typesOnNodeHover.spec.ts
  app/gui/src/project-view/components/ComponentBrowser.vue
  app/gui/src/project-view/components/ComponentMenu.vue
  app/gui/src/project-view/components/GraphEditor.vue
  app/gui/src/project-view/components/GraphEditor/CreateNodeFromPortButton.vue
  app/gui/src/project-view/components/GraphEditor/GraphNode.vue
  app/gui/src/project-view/components/GraphEditor/GraphNodeOutputPorts.vue
  app/gui/src/project-view/components/GraphEditor/GraphVisualization.vue
  app/gui/src/project-view/components/SmallPlusButton.vue
  app/gui/src/project-view/providers/graphEditorState.ts
Labels: CI: Ready to merge, x-new-feature, -gui

#11869 Improve code editor performance
  app/gui/src/project-view/components/CodeEditor/sync.ts
  app/gui/src/project-view/stores/graph/index.ts
  app/ydoc-server/src/ydoc.ts
Labels: CI: No changelog needed

#11870 Allow a block to contain mixed indentation levels
  app/gui/src/project-view/util/ast/__tests__/abstract.test.ts
  app/ydoc-shared/src/ast/tree.ts
Labels: CI: No changelog needed

#11907 Fix issue with inline stings.
  std-bits/table/src/main/java/org/enso/table/excel/xssfreader/XSSFReaderSheetXMLHandler.java
  test/Table_Tests/data/Sales_Sample_Data.xlsx
  test/Table_Tests/src/IO/Excel_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11752 Sort output of `File.list`
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  test/Base_Tests/src/System/File_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11889 Read MapBox API token at runtime
  CHANGELOG.md
  app/gui/env.d.ts
  app/gui/package.json
  app/gui/src/project-view/components/visualizations/GeoMapVisualization.vue
  app/gui/src/project-view/stores/visualization/index.ts
  app/ide-desktop/client/src/globals.d.ts
  app/ide-desktop/client/src/preload.ts
  pnpm-lock.yaml
Labels: -gui

#11872 Clear excel cache on reload
  std-bits/base/src/main/java/org/enso/base/cache/ReloadDetector.java
  std-bits/table/src/main/java/org/enso/table/excel/ExcelConnectionPool.java
  test/Table_Tests/src/IO/Excel_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11723 Run workflows depending on changed files
  .github/workflows/engine-changed-files.yml
  .github/workflows/engine-checks-nightly.yml
  .github/workflows/engine-checks-optional.yml
  .github/workflows/engine-checks.yml
  .github/workflows/engine-pull-request.yml
  .github/workflows/gui-changed-files.yml
  .github/workflows/gui-checks.yml
  .github/workflows/gui-packaging-optional.yml
  .github/workflows/gui-packaging-pull-request.yml
  .github/workflows/gui-packaging.yml
  .github/workflows/gui-pull-request.yml
  .github/workflows/shader-tools.yml
  .github/workflows/wasm-changed-files.yml
  .github/workflows/wasm-checks.yml
  .github/workflows/wasm-pull-request.yml
  build/build/paths.yaml
  build/build/src/ci_gen.rs
  build/ci_utils/src/actions/workflow/definition.rs
Labels: CI: No changelog needed, -ci, -build-script

#11914 Add missing entries.
  app/ide-desktop/client/tasks/signArchivesMacOs.ts
Labels: CI: No changelog needed

#11917 Allow checks on develop to complete
  .github/workflows/engine-pull-request.yml
  .github/workflows/gui-checks.yml
  .github/workflows/gui-packaging-pull-request.yml
  .github/workflows/gui-pull-request.yml
  .github/workflows/storybook.yml
  .github/workflows/wasm-pull-request.yml
Labels: CI: Ready to merge, CI: No changelog needed

#11777 Promote broken values instead of ignoring them
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Index_Sub_Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Array_Like_Helpers.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Extensions.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Extensions_Helpers.enso
  docs/types/errors.md
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/semantic/DataflowErrorPropagationTest.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/function/BlockNode.java
  test/Base_Tests/src/Data/Decimal_Spec.enso
  test/Base_Tests/src/Data/Function_Spec.enso
  test/Base_Tests/src/Data/Range_Spec.enso
  test/Base_Tests/src/Data/Time/Date_Range_Spec.enso
  test/Base_Tests/src/Random_Spec.enso
  test/Base_Tests/src/System/File_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Cross_Tab_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Nothing_Spec.enso
  test/Table_Tests/src/Database/SQLite_Spec.enso
  test/Table_Tests/src/Database/Upload_Spec.enso
  test/Table_Tests/src/IO/Fetch_Spec.enso
  test/Table_Tests/src/In_Memory/Split_Tokenize_Spec.enso
  test/Table_Tests/src/Util.enso
  test/Table_Tests/src/Util_Spec.enso
  test/Test_Tests/package.yaml
  test/Test_Tests/src/Extensions_Spec.enso
  test/Test_Tests/src/Helpers.enso
  test/Test_Tests/src/Main.enso
Labels: CI: Ready to merge, CI: Keep up to date, CI: No changelog needed

#11918 Missed one :(
  app/ide-desktop/client/tasks/signArchivesMacOs.ts
Labels: CI: Ready to merge, CI: No changelog needed

#11920 Remove query key
  app/gui/src/dashboard/pages/authentication/Setup/Setup.tsx
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#11921 Small fixes from loading doc site.
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Decimal.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11913 Ensure isAllTypes is compilation constant
  engine/runtime/src/main/java/org/enso/interpreter/node/typecheck/AbstractTypeCheckNode.java
Labels: CI: Ready to merge, CI: Keep up to date, CI: No changelog needed

#11919 Update required checks
  .github/workflows/engine-pull-request.yml
  .github/workflows/gui-pull-request.yml
  .github/workflows/ide-packaging-optional.yml
  .github/workflows/ide-packaging.yml
  .github/workflows/ide-pull-request.yml
  .github/workflows/wasm-pull-request.yml
  build/build/paths.yaml
  build/build/src/ci_gen.rs
Labels: CI: No changelog needed

#11931 Update gui-changed-files workflow
  .github/workflows/gui-changed-files.yml
Labels: CI: Ready to merge, CI: No changelog needed

#11905 Fix snowflake sort tests
  distribution/lib/Standard/AWS/0.0.0-dev/src/Database/Redshift/Internal/Redshift_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Dialect_Flag.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/Internal/SQLServer_Dialect.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Dialect.enso
  test/Table_Tests/src/Common_Table_Operations/Order_By_Spec.enso
  test/Table_Tests/src/Database/Upload_Spec.enso
  test/Table_Tests/src/In_Memory/Common_Spec.enso
Labels: CI: No changelog needed

#11916 Do not report exceptions on long running Excel reads
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextEventsListener.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistryProtocol.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeAsyncCommandsTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/TestMessages.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/control/ThreadInterruptedException.java
  std-bits/table/src/main/java/org/enso/table/excel/ExcelConnectionPool.java
  std-bits/table/src/main/java/org/enso/table/excel/ExcelRange.java
  std-bits/table/src/main/java/org/enso/table/excel/ExcelSheet.java
  std-bits/table/src/main/java/org/enso/table/excel/ReadOnlyExcelConnection.java
  std-bits/table/src/main/java/org/enso/table/excel/xssfreader/XSSFReaderSheet.java
  std-bits/table/src/main/java/org/enso/table/excel/xssfreader/XSSFReaderWorkbook.java
  std-bits/table/src/main/java/org/enso/table/read/ExcelReader.java
  std-bits/table/src/main/java/org/enso/table/util/ConsumerWithException.java
  std-bits/table/src/main/java/org/enso/table/util/FunctionWithException.java
  std-bits/table/src/main/java/org/enso/table/write/ExcelWriter.java
Labels: CI: No changelog needed

#11897 Symetric, transitive and reflexive equality for intersection types
  CHANGELOG.md
  docs/types/intersection-types.md
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/node/expression/builtin/meta/TypeOfNodeMultiValueTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/AnyToTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/EnsoMultiValueInteropTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/EqualsMultiValueTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/ValuesGenerator.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/hash/HashCodeTest.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeConversionNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsSimpleNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/HashCodeNode.java
  test/Base_Tests/src/Semantic/Conversion_Spec.enso
  test/Base_Tests/src/Semantic/Multi_Value_Convert_Spec.enso
Labels: CI: Ready to merge

#11884 Docs panel: add support for loading images from the Cloud
  app/common/src/text/english.json
  app/gui/integration-test/dashboard/actions/api.ts
  app/gui/integration-test/dashboard/assetPanel.spec.ts
  app/gui/integration-test/dashboard/mock/example.png
  app/gui/src/dashboard/components/MarkdownViewer/MarkdownViewer.tsx
  app/gui/src/dashboard/components/MarkdownViewer/defaultRenderer.ts
  app/gui/src/dashboard/services/RemoteBackend.ts
  app/ide-desktop/client/src/projectManager.ts
  tools/performance/engine-benchmarks/README.md
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#11887 Fix Offline Mode
  app/common/package.json
  app/common/src/queryClient.ts
  app/common/src/text/english.json
  app/common/src/utilities/errors.ts
  app/gui/src/dashboard/App.tsx
  app/gui/src/dashboard/assets/offline_filled.svg
  app/gui/src/dashboard/assets/offline_outline.svg
  app/gui/src/dashboard/components/AriaComponents/Form/components/FormError.tsx
  app/gui/src/dashboard/components/ErrorBoundary.tsx
  app/gui/src/dashboard/components/OfflineNotificationManager.tsx
  app/gui/src/dashboard/components/Suspense.tsx
  app/gui/src/dashboard/hooks/backendHooks.tsx
  app/gui/src/dashboard/hooks/offlineHooks.ts
  app/gui/src/dashboard/layouts/Drive.tsx
  app/gui/src/dashboard/layouts/Settings/SetupTwoFaForm.tsx
  app/gui/src/dashboard/layouts/UserBar.tsx
  app/gui/src/dashboard/modules/payments/components/PlanSelector/components/PlanSelectorDialog.tsx
  app/gui/src/dashboard/modules/payments/components/StripeProvider.tsx
  app/gui/src/dashboard/providers/SessionProvider.tsx
  app/gui/src/dashboard/providers/__test__/SessionProvider.test.tsx
  app/gui/src/dashboard/utilities/HttpClient.ts
  app/gui/src/dashboard/utilities/error.ts
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#11904 Use MPLUS 1 font
  app/gui/src/project-view/assets/base.css
Labels: p-highest, CI: Ready to merge, CI: No changelog needed, --bug, -gui

#11820 Sort assets by modified date
  app/common/src/services/Backend.ts
  app/common/src/text/english.json
  app/common/src/text/index.ts
  app/gui/env.d.ts
  app/gui/integration-test/dashboard/actions/DrivePageActions.ts
  app/gui/integration-test/dashboard/actions/api.ts
  app/gui/integration-test/dashboard/actions/index.ts
  app/gui/integration-test/dashboard/assetsTableFeatures.spec.ts
  app/gui/integration-test/dashboard/copy.spec.ts
  app/gui/integration-test/dashboard/editAssetName.spec.ts
  app/gui/integration-test/dashboard/pageSwitcher.spec.ts
  app/gui/integration-test/dashboard/sort.spec.ts
  app/gui/integration-test/dashboard/startModal.spec.ts
  app/gui/src/dashboard/App.tsx
  app/gui/src/dashboard/components/AriaComponents/Form/Form.tsx
  app/gui/src/dashboard/components/AriaComponents/Form/components/Field.tsx
  app/gui/src/dashboard/components/AriaComponents/Form/components/FormError.tsx
  app/gui/src/dashboard/components/AriaComponents/Form/components/FormProvider.tsx
  app/gui/src/dashboard/components/AriaComponents/Form/components/Reset.tsx
  app/gui/src/dashboard/components/AriaComponents/Form/components/index.ts
  app/gui/src/dashboard/components/AriaComponents/Form/components/schema.ts
  app/gui/src/dashboard/components/AriaComponents/Form/components/types.ts
  app/gui/src/dashboard/components/AriaComponents/Form/components/useForm.ts
  app/gui/src/dashboard/components/AriaComponents/Form/components/useFormError.ts
  app/gui/src/dashboard/components/AriaComponents/Inputs/Input/Input.tsx
  app/gui/src/dashboard/components/AriaComponents/Inputs/variants.ts
  app/gui/src/dashboard/components/AriaComponents/Text/Text.tsx
  app/gui/src/dashboard/components/AriaComponents/Underlay.tsx
  app/gui/src/dashboard/components/AriaComponents/index.ts
  app/gui/src/dashboard/components/Devtools/EnsoDevtools.tsx
  app/gui/src/dashboard/components/EditableSpan.tsx
  app/gui/src/dashboard/components/dashboard/AssetRow.tsx
  app/gui/src/dashboard/components/dashboard/DatalinkNameColumn.tsx
  app/gui/src/dashboard/components/dashboard/DirectoryNameColumn.tsx
  app/gui/src/dashboard/components/dashboard/FileNameColumn.tsx
  app/gui/src/dashboard/components/dashboard/ProjectIcon.tsx
  app/gui/src/dashboard/components/dashboard/ProjectNameColumn.tsx
  app/gui/src/dashboard/components/dashboard/SecretNameColumn.tsx
  app/gui/src/dashboard/components/dashboard/column/DocsColumn.tsx
  app/gui/src/dashboard/components/dashboard/column/LabelsColumn.tsx
  app/gui/src/dashboard/components/dashboard/column/ModifiedColumn.tsx
  app/gui/src/dashboard/components/dashboard/column/SharedWithColumn.tsx
  app/gui/src/dashboard/components/dashboard/column/columnUtils.ts
  app/gui/src/dashboard/hooks/backendHooks.tsx
  app/gui/src/dashboard/hooks/projectHooks.ts
  app/gui/src/dashboard/layouts/AssetsTable.tsx
  app/gui/src/dashboard/layouts/Drive/assetsTableItemsHooks.tsx
  app/gui/src/dashboard/pages/authentication/LoadingScreen.tsx
  app/gui/src/dashboard/providers/FeatureFlagsProvider.tsx
  app/gui/src/dashboard/providers/TextProvider.tsx
  app/gui/src/dashboard/services/RemoteBackend.ts
  app/gui/src/dashboard/tailwind.css
  app/gui/src/dashboard/utilities/__tests__/validation.test.ts
  app/gui/src/dashboard/utilities/validation.ts
  eslint.config.mjs
Labels: CI: No changelog needed, g-dashboard

#11909 Add timeout for opening projects
  app/gui/src/dashboard/assets/cross.svg
  app/gui/src/dashboard/assets/cross2.svg
  app/gui/src/dashboard/assets/error_filled.svg
  app/gui/src/dashboard/assets/error_outline.svg
  app/gui/src/dashboard/assets/warning.svg
  app/gui/src/dashboard/hooks/projectHooks.ts
  app/gui/src/dashboard/hooks/timeoutHooks.ts
  app/gui/src/dashboard/layouts/Editor.tsx
  app/gui/src/dashboard/layouts/TabBar.tsx
  app/gui/src/dashboard/pages/dashboard/DashboardTabPanels.tsx
Labels: CI: No changelog needed, g-dashboard

#11861 Every builtin type has a common super class
  engine/runtime-integration-tests/src/test/java/org/enso/example/PolyglotTestClass.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/builtins/BuiltinsJavaInteropTest.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/BuiltinObject.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoDate.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoDateTime.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoDuration.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoFile.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoTimeOfDay.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoTimeZone.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/ManagedResource.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Ref.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/Atom.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/hash/EnsoHashMap.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/text/Text.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/Array.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/ArrayLikeHelpers.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/ArrayProxy.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/Vector.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/number/EnsoBigInteger.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/warning/Warning.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/BuiltinsProcessor.java
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#11936 Await component
  app/common/package.json
  app/common/src/queryClient.ts
  app/gui/package.json
  app/gui/src/dashboard/components/Await.tsx
  app/gui/src/dashboard/components/ErrorBoundary.tsx
  app/gui/src/dashboard/components/Result.tsx
  app/gui/src/dashboard/components/Suspense.tsx
  app/gui/src/dashboard/components/__tests__/Await.test.tsx
  app/gui/src/dashboard/hooks/backendHooks.tsx
  pnpm-lock.yaml
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#11940 Add separate watched files for IDE Packaging CI workflow
  .github/workflows/gui-changed-files.yml
  .github/workflows/ide-changed-files.yml
  .github/workflows/ide-pull-request.yml
Labels: CI: Ready to merge, CI: No changelog needed

#11943 Simplify pattern matching of `CallArgument`
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/AutomaticParallelism.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/DataflowAnalysis.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/FramePointerAnalysis.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/desugar/LambdaShorthandToLambdaMini.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/GlobalNames.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/analyse/GatherDiagnosticsTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/desugar/OperatorToFunctionTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/desugar/SectionsToBinOpMegaPass.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/CallArgument.scala
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
Labels: CI: No changelog needed, CI: Clean build required

#11946 Add ide-changed-files dependency
  .github/workflows/ide-pull-request.yml
Labels: CI: Ready to merge, CI: No changelog needed, -ci

#11942 Fix bugs around mass selection/single selection/drag and drop
  app/common/src/services/Backend.ts
  app/gui/integration-test/dashboard/actions/DrivePageActions.ts
  app/gui/src/dashboard/components/AriaComponents/Dialog/Dialog.tsx
  app/gui/src/dashboard/components/AriaComponents/Dialog/Popover.tsx
  app/gui/src/dashboard/components/AriaComponents/Tooltip/Tooltip.tsx
  app/gui/src/dashboard/components/Badge/Badge.tsx
  app/gui/src/dashboard/components/SelectionBrush.tsx
  app/gui/src/dashboard/components/dashboard/AssetRow.tsx
  app/gui/src/dashboard/hooks/dragAndDropHooks.ts
  app/gui/src/dashboard/hooks/eventCallbackHooks.ts
  app/gui/src/dashboard/hooks/eventListenerHooks.ts
  app/gui/src/dashboard/hooks/measureHooks.ts
  app/gui/src/dashboard/hooks/spotlightHooks.tsx
  app/gui/src/dashboard/hooks/throttleHooks.ts
  app/gui/src/dashboard/hooks/useRaf.ts
  app/gui/src/dashboard/layouts/AssetsTable.tsx
  app/gui/src/dashboard/layouts/Drive.tsx
  app/gui/src/dashboard/layouts/Labels.tsx
  app/gui/src/dashboard/layouts/TabBar.tsx
  app/gui/src/dashboard/modals/DragModal.tsx
  app/gui/src/dashboard/providers/DriveProvider.tsx
  app/gui/src/dashboard/styles.css
  app/gui/src/dashboard/utilities/geometry.ts
  app/gui/src/dashboard/utilities/math.ts
  app/gui/src/dashboard/utilities/scrollContainers.ts
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#11951 Improve Sentry upload
  app/gui/vite.config.ts
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#11950 Fix Snowflake tests - private access error
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Dialect.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11908 Fix redo stack loss when editing text literals
  CHANGELOG.md
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetText.vue
Labels: CI: Ready to merge, --bug, -gui

#11954 Fix type signature for `Integer.parse` to get correct widget for `radix`
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso
Labels: CI: No changelog needed
