Repository enso-org/enso, pull requests merged in 2024-03, with the labels that each got.

#9227 Start using pre-signed URLs for Enso Files
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_File.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9158 Add compiler benchmarks
  build.sbt
  engine/runtime-benchmarks/src/main/java/org/enso/compiler/benchmarks/CodeGenerator.java
  engine/runtime-benchmarks/src/main/java/org/enso/compiler/benchmarks/Utils.java
  engine/runtime-benchmarks/src/main/java/org/enso/compiler/benchmarks/inline/InlineCompilerBenchmark.java
  engine/runtime-benchmarks/src/main/java/org/enso/compiler/benchmarks/inline/InlineCompilerErrorBenchmark.java
  engine/runtime-benchmarks/src/main/java/org/enso/compiler/benchmarks/inline/InlineContextUtils.java
  engine/runtime-benchmarks/src/main/java/org/enso/compiler/benchmarks/inline/InlineSource.java
  engine/runtime-benchmarks/src/main/java/org/enso/compiler/benchmarks/module/ImportStandardLibrariesBenchmark.java
  engine/runtime-benchmarks/src/main/java/org/enso/compiler/benchmarks/module/ManyErrorsBenchmark.java
  engine/runtime-benchmarks/src/main/java/org/enso/compiler/benchmarks/module/ManyLocalVarsBenchmark.java
  engine/runtime-benchmarks/src/main/java/org/enso/compiler/benchmarks/module/ManyNestedBlocksBenchmark.java
  engine/runtime-benchmarks/src/main/java/org/enso/compiler/benchmarks/module/ManySmallMethodsBenchmark.java
Labels: CI: Ready to merge, CI: No changelog needed

#9215 Implementing reading Data Links
  .github/CODEOWNERS
  CHANGELOG.md
  app/ide-desktop/lib/dashboard/src/data/__tests__/dataLinkSchema.test.ts
  app/ide-desktop/lib/dashboard/src/data/dataLinkSchema.json
  distribution/lib/Standard/AWS/0.0.0-dev/src/Internal/Data_Link_Helpers.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3_Data_Link.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Data_Link.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_User.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Public_Utils.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Utils.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/HTTP_Fetch_Data_Link.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Delimited/Delimited_Format.enso
  std-bits/aws/src/main/java/org/enso/aws/file_system/S3DataLinkSPI.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/DataLinkFileFormatSPI.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/DataLinkSPI.java
  std-bits/base/src/main/java/org/enso/base/file_format/FileFormatSPI.java
  std-bits/base/src/main/java/org/enso/base/file_format/JSONFormatSPI.java
  std-bits/base/src/main/java/org/enso/base/net/http/HTTPFetchDataLinkSPI.java
  std-bits/table/src/main/java/org/enso/table/read/DelimitedFormatSPI.java
  test/AWS_Tests/data/credentials-with-secrets.datalink
  test/AWS_Tests/data/format-delimited.datalink
  test/AWS_Tests/data/simple.datalink
  test/AWS_Tests/src/S3_Spec.enso
  test/Base_Tests/data/datalinks/example-http-format-delimited.datalink
  test/Base_Tests/data/datalinks/example-http-format-explicit-default.datalink
  test/Base_Tests/data/datalinks/example-http-format-invalid.datalink
  test/Base_Tests/data/datalinks/example-http-format-json.datalink
  test/Base_Tests/data/datalinks/example-http.datalink
  test/Base_Tests/src/Main.enso
  test/Base_Tests/src/Network/Enso_Cloud/Cloud_Data_Link_Spec.enso
  test/Base_Tests/src/Network/Enso_Cloud/Main.enso
  test/Base_Tests/src/Network/Http/Http_Auto_Parse_Spec.enso
  test/Base_Tests/src/Network/Http/Http_Data_Link_Spec.enso
  test/Base_Tests/src/Network/Http/Http_Test_Setup.enso
  test/Base_Tests/src/Network/Http_Spec.enso
  test/Base_Tests/src/System/File_Spec.enso
  tools/http-test-helper/www-files/js.txt
Labels: CI: Ready to merge, CI: Clean build required

#9240 Fix selection tests
  app/gui2/src/composables/__tests__/selection.test.ts
Labels: CI: Ready to merge, CI: No changelog needed, -ci, -gui2

#9233 Align XML_Document and XML_Element APIs more.
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Any.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/XML.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/DB_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Simple_Expression.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Extensions/Table_Conversions.enso
  std-bits/base/src/main/java/org/enso/base/XML_Utils.java
  test/Base_Tests/src/Data/XML/XML_Spec.enso
Labels: CI: Ready to merge

#9206 Close dropdowns
  app/gui2/src/bindings.ts
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphEdge.vue
  app/gui2/src/components/GraphEditor/GraphEdges.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui2/src/providers/interactionHandler.ts
  app/gui2/src/util/autoBlur.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#9230 Create and edit comments
  app/gui2/shared/ast/parse.ts
  app/gui2/shared/ast/tree.ts
  app/gui2/src/components/CircularMenu.vue
  app/gui2/src/components/CodeEditor.vue
  app/gui2/src/components/CodeEditor/codemirror.ts
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/GraphNodeComment.vue
  app/gui2/src/util/ast/__tests__/abstract.test.ts
Labels: CI: No changelog needed, -gui2

#9234 Fix attaching generic annotations
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/desugar/ComplexType.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/desugar/ComplexTypeTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#9243 Fix termination of http-test-helper on Ctrl-C
  tools/http-test-helper/src/main/java/org/enso/shttp/HTTPTestHelperServer.java
Labels: CI: Ready to merge, CI: No changelog needed

#9225 Allow resolving `enso://` URIs in `Data.read` and other places
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Data_Link.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_Secret.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_User.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Enso_Path.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Utils.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Header.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/URI.enso
  std-bits/base/src/main/java/org/enso/base/enso_cloud/EnsoPathFileSystemSPI.java
  test/AWS_Tests/data/credentials-with-secrets.datalink
  test/AWS_Tests/src/S3_Spec.enso
  test/Base_Tests/src/Network/Enso_Cloud/Enso_File_Spec.enso
  test/Base_Tests/src/Network/Enso_Cloud/Secrets_Spec.enso
Labels: CI: Ready to merge

#9160 Add Warning indicator.
  app/gui2/src/assets/base.css
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/GraphNodeMessage.vue
  app/gui2/src/util/specialCharacters.ts
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, -gui2

#9093 Imports conflict resolution
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/components/ComponentBrowser/__tests__/input.test.ts
  app/gui2/src/components/ComponentBrowser/input.ts
  app/gui2/src/components/GraphEditor/GraphNodeComment.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui2/src/stores/graph/imports.ts
  app/gui2/src/stores/graph/index.ts
  app/gui2/src/stores/suggestionDatabase/index.ts
  app/gui2/src/util/ast/__tests__/abstract.test.ts
  app/gui2/src/util/ast/abstract.ts
  app/gui2/ydoc-server/edits.ts
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, -gui2

#9190 Autoscoped constructors
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso
  docs/runtime-roadmap.md
  docs/syntax/functions.md
  docs/syntax/types.md
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/ArrayProxyBenchmarks.java
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/AtomBenchmarks.java
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/CallableBenchmarks.java
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/EqualsBenchmarks.java
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/IfVsCaseBenchmarks.java
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/ListBenchmarks.java
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/NamedDefaultedArgumentBenchmarks.java
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/NestedPatternCompilationBenchmarks.java
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/RecursionBenchmarks.java
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/SrcUtil.java
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/StringBenchmarks.java
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/TypePatternBenchmarks.java
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/VectorBenchmarks.java
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/WarningBenchmarks.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/AutoscopedConstructorTest.java
  engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeCallableNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/argument/ReadArgumentCheckNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/util/TypeToDisplayTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/constant/DynamicSymbolNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Error.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/UnresolvedConstructor.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
  lib/java/benchmarks-common/src/main/java/org/enso/interpreter/bench/BenchmarksRunner.java
  test/Base_Tests/src/Semantic/Conversion_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Xml_Spec.enso
Labels: CI: Ready to merge

#9253 Add imports on editing nodes
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/stores/graph/index.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#9264 Add delete node icon to circular menu
  app/gui2/src/components/CircularMenu.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/GraphNodes.vue
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#9249 Some minor improvements suggested from Ned's use
  CHANGELOG.md
  distribution/lib/Standard/AWS/0.0.0-dev/src/AWS_Credential.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/Database/Redshift/Redshift_Details.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/Internal/Data_Link_Helpers.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3_Data_Link.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Response.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Response_Body.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Data/DB_Table.enso
  distribution/lib/Standard/Examples/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Searcher/0.0.0-dev/src/Network.enso
  distribution/lib/Standard/Searcher/0.0.0-dev/src/Network/Http.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
Labels: CI: Ready to merge

#9238 E2E test fixing and bring back reports
  .eslintignore
  app/gui2/e2e/collapsingAndEntering.spec.ts
  app/gui2/e2e/componentBrowser.spec.ts
  app/gui2/e2e/fullscreenVisualisation.spec.ts
  app/gui2/eslint.config.js
  app/gui2/playwright.config.ts
  app/ide-desktop/eslint.config.js
  app/ide-desktop/lib/dashboard/playwright.config.ts
  build/build/paths.yaml
  build/build/src/engine/context.rs
  build/ci_utils/src/actions/artifacts.rs
  build/cli/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required, -ci, -gui2

#9267 Add ascription type information to suggestions database
  engine/runtime-compiler/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/context/SuggestionBuilderTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#9268 Enable splitting for EqualsSimpleNode
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsSimpleNode.java
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#9246 Hide placeholders
  app/gui2/e2e/widgets.spec.ts
  app/gui2/mock/providers.ts
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/NodeWidgetTree.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetApplication.vue
  app/gui2/src/composables/selection.ts
  app/gui2/src/providers/widgetTree.ts
  app/gui2/src/util/callTree.ts
Labels: CI: No changelog needed, -gui2

#9270 [CI] Checkbox for requesting a clean build when manually dispatching a workflow
  .github/workflows/changelog.yml
  .github/workflows/engine-benchmark.yml
  .github/workflows/gui.yml
  .github/workflows/promote.yml
  .github/workflows/release.yml
  .github/workflows/scala-new.yml
  .github/workflows/std-libs-benchmark.yml
  build/build/src/ci.rs
  build/build/src/ci_gen.rs
Labels: CI: Ready to merge, CI: No changelog needed

#9091 Hard delete of items in Trash
  app/ide-desktop/lib/dashboard/src/components/dashboard/AssetRow.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/DataLinkNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/DirectoryNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/FileNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/ProjectIcon.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/ProjectNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/SecretNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/events/AssetEventType.ts
  app/ide-desktop/lib/dashboard/src/events/AssetListEventType.ts
  app/ide-desktop/lib/dashboard/src/events/assetEvent.ts
  app/ide-desktop/lib/dashboard/src/events/assetListEvent.ts
  app/ide-desktop/lib/dashboard/src/layouts/AssetContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetsTable.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetsTableContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Drive.tsx
  app/ide-desktop/lib/dashboard/src/layouts/DriveBar.tsx
  app/ide-desktop/lib/dashboard/src/modals/ConfirmDeleteModal.tsx
  app/ide-desktop/lib/dashboard/src/services/Backend.ts
  app/ide-desktop/lib/dashboard/src/services/LocalBackend.ts
  app/ide-desktop/lib/dashboard/src/services/RemoteBackend.ts
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#9280 Add @MrFlashAccount as a codeowner of ide-desktop
  .github/CODEOWNERS
Labels: CI: Ready to merge, CI: No changelog needed

#9279 Fix typechecking
  app/ide-desktop/lib/dashboard/e2e/driveView.spec.ts
  app/ide-desktop/lib/dashboard/tsconfig.json
Labels: CI: Ready to merge, CI: No changelog needed, x-chore, --bug, g-dashboard

#9285 Use .. to identify autoscoped constructors
  docs/syntax/types.md
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/AtomBenchmarks.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/AutoscopedConstructorTest.java
  engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/UnresolvedConstructor.java
  test/Base_Tests/src/Semantic/Conversion_Spec.enso
Labels: CI: No changelog needed

#9229 Extract tests to their own files
  app/gui2/src/components/ComponentBrowser/__tests__/component.test.ts
  app/gui2/src/components/ComponentBrowser/__tests__/filtering.test.ts
  app/gui2/src/components/ComponentBrowser/__tests__/input.test.ts
  app/gui2/src/components/DocumentationPanel/__tests__/history.test.ts
  app/gui2/src/components/DocumentationPanel/history.ts
  app/gui2/src/components/GraphEditor/__tests__/collapsing.test.ts
  app/gui2/src/components/GraphEditor/collapsing.ts
  app/gui2/src/composables/__tests__/selection.test.ts
  app/gui2/src/composables/selection.ts
  app/gui2/src/stores/graph/__tests__/imports.test.ts
  app/gui2/src/stores/graph/imports.ts
  app/gui2/src/stores/suggestionDatabase/__tests__/documentation.test.ts
  app/gui2/src/stores/suggestionDatabase/documentation.ts
  app/gui2/src/stores/suggestionDatabase/entry.ts
  app/gui2/src/util/__tests__/compare.test.ts
  app/gui2/src/util/__tests__/containers.test.ts
  app/gui2/src/util/__tests__/net.test.ts
  app/gui2/src/util/__tests__/qualifiedName.test.ts
  app/gui2/src/util/__tests__/shortcuts.test.ts
  app/gui2/src/util/ast/__tests__/node.test.ts
  app/gui2/src/util/ast/__tests__/opr.test.ts
  app/gui2/src/util/ast/__tests__/testCase.ts
  app/gui2/src/util/ast/node.ts
  app/gui2/src/util/ast/opr.ts
  app/gui2/src/util/compare.ts
  app/gui2/src/util/containers.ts
  app/gui2/src/util/data/__tests__/set.test.ts
  app/gui2/src/util/data/set.ts
  app/gui2/src/util/net.ts
  app/gui2/src/util/qualifiedName.ts
  app/gui2/src/util/shortcuts.ts
  app/gui2/vite.config.ts
  app/gui2/ydoc-server/__tests__/edits.test.ts
  app/gui2/ydoc-server/index.ts
Labels: CI: Ready to merge, CI: No changelog needed, x-chore, -gui2, x-refactor

#9262 Restore whenReady, as I do not see the freeze
  app/ide-desktop/lib/client/src/index.ts
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard, -gui2

#9269 Implement a Data Link for Postgres
  CHANGELOG.md
  app/ide-desktop/lib/dashboard/src/components/JSONSchemaInput.tsx
  app/ide-desktop/lib/dashboard/src/data/__tests__/dataLinkSchema.test.ts
  app/ide-desktop/lib/dashboard/src/data/dataLinkSchema.json
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Data_Link/Postgres_Data_Link.enso
  std-bits/database/src/main/java/org/enso/database/postgres/PostgresConnectionDetailsSPI.java
  std-bits/database/src/main/java/org/enso/database/postgres/PostgresDataLinkSPI.java
  std-bits/database/src/main/java/org/enso/database/sqlite/SQLiteConnectionDetailsSPI.java
  std-bits/database/src/main/java/org/enso/database/sqlite/SQLiteFormatSPI.java
  test/Base_Tests/src/Network/Enso_Cloud/Cloud_Data_Link_Spec.enso
  test/Table_Tests/data/datalinks/postgres-db.datalink
  test/Table_Tests/data/datalinks/postgres-table.datalink
  test/Table_Tests/src/Database/Postgres_Spec.enso
Labels: CI: Ready to merge

#9276 Show progress of buildNativeImage
  project/NativeImage.scala
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#9298 Small change limiting the number of decimal places to 12 digits.
  app/gui2/src/components/visualizations/TableVisualization.vue
Labels: CI: Ready to merge, CI: No changelog needed

#9294 Visualization tests maintenance
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/InstrumentTestContext.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#9295 [CI] Engine CI Rework, Part 1
  .github/workflows/scala-new.yml
  build/build/src/ci_gen.rs
  build/build/src/ci_gen/job.rs
  build/build/src/ci_gen/step.rs
  build/build/src/engine.rs
  build/build/src/engine/context.rs
  build/cli/src/arg/backend.rs
  build/cli/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#9273 Pan to CB
  app/gui2/e2e/componentBrowser.spec.ts
  app/gui2/mock/providers.ts
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/composables/navigator.ts
  app/gui2/src/util/data/__tests__/rect.test.ts
  app/gui2/src/util/data/rect.ts
Labels: CI: Ready to merge, CI: No changelog needed

#9312 Trading shouldNotReachHere() for an abstract method
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/IndirectInvokeCallableNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/IndirectInvokeMethodNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeCallableNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/StringLiteralBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/io/PrintlnNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/hash/HashMapRemoveNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/Vector.java
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required, -compiler

#9321 Move `Standard.Database.Data` to `Standard.Database`.
  app/gui2/src/components/visualizations/HistogramVisualization.vue
  app/gui2/src/components/visualizations/ImageBase64Visualization.vue
  app/gui2/src/components/visualizations/SQLVisualization.vue
  distribution/lib/Standard/AWS/0.0.0-dev/src/Database/Redshift/Internal/Redshift_Dialect.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/XML.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Column_Constraint.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Column_Description.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Data_Link/Postgres_Data_Link.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Extensions/Upload_Database_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Extensions/Upload_In_Memory_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Aggregate_Helper.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Common/Database_Join_Helper.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Common/Lookup_Query_Helper.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Helpers.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/IR/Create_Column_Descriptor.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/IR/Internal_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/IR/SQL_Expression.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/JDBC_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Type_Mapping.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Result_Set.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQL_Type_Mapping.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQL_Type_Reference.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Type_Mapping.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/SQL.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/SQL_Query.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/SQL_Statement.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/SQL_Type.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Take_Drop_Helpers.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Update_Action.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Histogram.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Image.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Image_File_Format.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Matrix.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Matrix_Error.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/SQL/Visualization.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
  test/Image_Tests/src/Data/Image_Spec.enso
  test/Image_Tests/src/Data/Matrix_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Map_To_Table_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Nothing_Spec.enso
  test/Table_Tests/src/Database/Codegen_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Database/Types/SQLite_Type_Mapping_Spec.enso
  test/Table_Tests/src/Database/Upload_Spec.enso
  test/Table_Tests/src/Util.enso
  test/Visualization_Tests/src/Table_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9187 Minor improvements
  app/ide-desktop/lib/dashboard/src/components/Autocomplete.tsx
  app/ide-desktop/lib/dashboard/src/modals/ManagePermissionsModal.tsx
  app/ide-desktop/lib/dashboard/src/modals/UpsertSecretModal.tsx
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#8895 Refactor configuration keys out of repository
  .github/workflows/gui.yml
  .github/workflows/release.yml
  app/gui2/vite.config.ts
  app/ide-desktop/.example.env
  app/ide-desktop/.gitignore
  app/ide-desktop/eslint.config.js
  app/ide-desktop/lib/client/esbuild-config.ts
  app/ide-desktop/lib/client/paths.ts
  app/ide-desktop/lib/client/src/debug.ts
  app/ide-desktop/lib/client/src/index.ts
  app/ide-desktop/lib/client/src/project-management.ts
  app/ide-desktop/lib/client/tsconfig.json
  app/ide-desktop/lib/client/watch.ts
  app/ide-desktop/lib/common/README.md
  app/ide-desktop/lib/common/package.json
  app/ide-desktop/lib/common/src/appConfig.d.ts
  app/ide-desktop/lib/common/src/appConfig.js
  app/ide-desktop/lib/common/src/buildUtils.d.ts
  app/ide-desktop/lib/common/src/buildUtils.js
  app/ide-desktop/lib/content/bundle.ts
  app/ide-desktop/lib/content/esbuild-config.ts
  app/ide-desktop/lib/content/src/remoteLog.ts
  app/ide-desktop/lib/content/start.ts
  app/ide-desktop/lib/content/tsconfig.json
  app/ide-desktop/lib/content/watch.ts
  app/ide-desktop/lib/dashboard/README.md
  app/ide-desktop/lib/dashboard/e2e/api.ts
  app/ide-desktop/lib/dashboard/esbuild-config.ts
  app/ide-desktop/lib/dashboard/package.json
  app/ide-desktop/lib/dashboard/src/App.tsx
  app/ide-desktop/lib/dashboard/src/authentication/cognito.mock.ts
  app/ide-desktop/lib/dashboard/src/authentication/cognito.ts
  app/ide-desktop/lib/dashboard/src/authentication/config.ts
  app/ide-desktop/lib/dashboard/src/authentication/service.ts
  app/ide-desktop/lib/dashboard/src/hooks/navigateHooks.ts
  app/ide-desktop/lib/dashboard/src/index.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetSearchBar.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Chat.tsx
  app/ide-desktop/lib/dashboard/src/layouts/TopBar.tsx
  app/ide-desktop/lib/dashboard/src/pages/dashboard/Dashboard.tsx
  app/ide-desktop/lib/dashboard/src/pages/subscribe/Subscribe.tsx
  app/ide-desktop/lib/dashboard/src/providers/AuthProvider.tsx
  app/ide-desktop/lib/dashboard/src/providers/SessionProvider.tsx
  app/ide-desktop/lib/dashboard/src/services/RemoteBackend.ts
  app/ide-desktop/lib/dashboard/src/utilities/config.ts
  app/ide-desktop/lib/dashboard/vite.config.ts
  app/ide-desktop/lib/dashboard/vite.test.config.ts
  app/ide-desktop/lib/types/globals.d.ts
  build/build/src/ci_gen/job.rs
  build/build/src/ide/web.rs
  build/ci_utils/src/actions/workflow/definition.rs
  package-lock.json
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard, x-refactor

#9188 Change "Override Execution Context" button to "Record" button on nodes
  app/gui2/e2e/main.ts
  app/gui2/src/assets/icons.svg
  app/gui2/src/components/CircularMenu.vue
  app/gui2/src/components/CodeEditor.vue
  app/gui2/src/components/ComponentBrowser/input.ts
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/__tests__/collapsing.test.ts
  app/gui2/src/components/GraphEditor/collapsing.ts
  app/gui2/src/components/RecordControl.vue
  app/gui2/src/components/SvgIcon.vue
  app/gui2/src/composables/__tests__/selection.test.ts
  app/gui2/src/main.ts
  app/gui2/src/stores/graph/__tests__/graphDatabase.test.ts
  app/gui2/src/stores/graph/graphDatabase.ts
  app/gui2/src/stores/graph/index.ts
  app/gui2/src/stores/project/index.ts
  app/gui2/src/util/ast/__tests__/node.test.ts
  app/gui2/src/util/ast/node.ts
  app/gui2/src/util/ast/prefixes.ts
  app/gui2/stories/GraphNode.story.vue
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, -gui2

#9325 Use to_display_text to preview warnings
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/WarningPreview.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeErrorsTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#9308 Split `Excel_Format` into 3 constructors
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/XML/XML_Format.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Data_Link.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File_Format.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/SQLite_Format.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Image_File_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Delimited/Delimited_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Section.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Workbook.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Excel_Reader.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Excel_Section.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Excel_Writer.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Main.enso
  test/AWS_Tests/src/S3_Spec.enso
  test/Table_Tests/src/IO/Excel_Spec.enso
  test/Table_Tests/src/IO/Fetch_Spec.enso
  test/Visualization_Tests/src/Widgets/File_Format_Widgets_Spec.enso
  test/Visualization_Tests/src/Widgets_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9150 Demonstrate usage of foreign arrow function
  build.sbt
  distribution/lib/Standard/Base/0.0.0-dev/src/Polyglot.enso
  engine/runtime-language-arrow/src/main/java/org/enso/interpreter/arrow/ArrowParser.java
  engine/runtime-language-arrow/src/main/java/org/enso/interpreter/arrow/runtime/ArrowCastToFixedSizeArrayFactory.java
  engine/runtime-language-arrow/src/main/java/org/enso/interpreter/arrow/runtime/ArrowFixedArrayDate.java
  engine/runtime-language-arrow/src/main/java/org/enso/interpreter/arrow/runtime/ArrowFixedArrayInt.java
  engine/runtime-language-arrow/src/main/java/org/enso/interpreter/arrow/runtime/ArrowFixedSizeArrayBuilder.java
  engine/runtime-language-arrow/src/main/java/org/enso/interpreter/arrow/runtime/ArrowFixedSizeArrayFactory.java
  engine/runtime-language-arrow/src/main/java/org/enso/interpreter/arrow/runtime/ByteBufferDirect.java
  engine/runtime-language-arrow/src/main/java/org/enso/interpreter/arrow/runtime/RoundingUtil.java
  engine/runtime-language-arrow/src/test/java/org/enso/interpreter/arrow/VerifyArrowTest.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/Builtin.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/BuiltinsProcessor.java
  test/Base_Tests/src/Semantic/Arrow_Interop_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#9245 Project manager API for basic file system operations
  docs/language-server/protocol-project-manager.md
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/Cli.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/ProjectManager.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/command/filesystem/FileSystemCreateDirectoryCommand.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/command/filesystem/FileSystemDeleteDirectoryCommand.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/command/filesystem/FileSystemListCommand.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/command/filesystem/FileSystemMoveDirectoryCommand.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/file/BlockingFileSystem.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/file/FileJson.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/file/FileSystem.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/repository/ProjectFileRepository.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/repository/ProjectRepository.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/repository/ProjectRepositoryFailure.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/protocol/FileSystemManagementApi.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/protocol/JsonRpc.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/filesystem/Attributes.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/filesystem/FileSystemEntry.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/filesystem/FileSystemService.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/filesystem/FileSystemServiceApi.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/filesystem/FileSystemServiceFailure.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/filesystem/FileSystemServiceFailureMapper.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/service/filesystem/FileSystemServiceSpec.scala
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required, -project-manager

#9252 Visualizations fixes follow-up
  app/gui2/src/bindings.ts
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphVisualization.vue
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required, -gui2

#9326 Provide Persistance for Persistance.Reference
  engine/runtime-parser/src/test/java/org/enso/compiler/core/IrPersistanceTest.java
  lib/java/persistance/src/main/java/org/enso/persist/PerMap.java
Labels: CI: No changelog needed, CI: Clean build required, -compiler

#9336 fix text caret not showing for empty input
  app/gui2/src/components/GraphEditor/widgets/WidgetText.vue
  app/gui2/src/components/widgets/AutoSizedInput.vue
  app/gui2/src/util/measurement.ts
  lib/rust/types/build.rs
Labels: CI: Ready to merge, CI: No changelog needed

#9334 Add selecting by type to the table
  CHANGELOG.md
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Type/Value_Type.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Main.enso
  test/Table_Tests/src/Common_Table_Operations/Select_Columns_Spec.enso
Labels: CI: Ready to merge

#9247 Add-node buttons
  app/gui2/e2e/collapsingAndEntering.spec.ts
  app/gui2/e2e/main.ts
  app/gui2/e2e/selectingNodes.spec.ts
  app/gui2/src/assets/icons.svg
  app/gui2/src/components/CircularMenu.vue
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/GraphNodes.vue
  app/gui2/src/components/GraphEditor/GraphVisualization.vue
  app/gui2/src/components/SmallPlusButton.vue
  app/gui2/src/components/VisualizationContainer.vue
  app/gui2/src/providers/visualizationConfig.ts
  app/gui2/stories/setup.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#9341 Correct bug with qualified name of Float.
  app/gui2/src/components/GraphEditor/widgets/WidgetNumber.vue
Labels: CI: Ready to merge, CI: No changelog needed

#9328 Ast.Vector
  app/gui2/shared/ast/parse.ts
  app/gui2/shared/ast/tree.ts
  app/gui2/src/components/GraphEditor/GraphEdges.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetFunction.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetText.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetVector.vue
  app/gui2/src/components/visualizations/ScatterplotVisualization.vue
  app/gui2/src/util/ast/__tests__/abstract.test.ts
  app/gui2/src/util/ast/abstract.ts
Labels: CI: No changelog needed, -gui2

#9330 Remove File from File./
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoFile.java
Labels: CI: Ready to merge

#9290 Use labels from the engine if they are available
  app/gui2/e2e/widgets.spec.ts
  app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue
Labels: CI: Ready to merge, CI: No changelog needed, --regression, -gui2

#9359 Allow deleting files with project manager
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/Cli.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/ProjectManager.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/command/filesystem/FileSystemDeleteCommand.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/file/BlockingFileSystem.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/file/FileSystem.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/repository/ProjectFileRepository.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/filesystem/FileSystemService.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/filesystem/FileSystemServiceApi.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/service/filesystem/FileSystemServiceSpec.scala
Labels: CI: Ready to merge, CI: No changelog needed

#9364 Update Codeowners
  .github/CODEOWNERS
Labels: CI: Ready to merge, CI: No changelog needed

#9352 Fix broken login flow
  app/gui2/vite.config.ts
  app/ide-desktop/lib/dashboard/package.json
  app/ide-desktop/lib/dashboard/src/authentication/service.ts
  package-lock.json
Labels: CI: Ready to merge, CI: No changelog needed

#9344 Move selections to a new layer
  app/gui2/e2e/selectingNodes.spec.ts
  app/gui2/src/assets/base.css
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphEdge.vue
  app/gui2/src/components/GraphEditor/GraphEdges.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/GraphNodeSelection.vue
Labels: CI: Ready to merge, CI: No changelog needed, -gui2

#9346 Excel DataLink
  CHANGELOG.md
  app/ide-desktop/lib/dashboard/src/data/__tests__/dataLinkSchema.test.ts
  app/ide-desktop/lib/dashboard/src/data/dataLinkSchema.json
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Enso_Path.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Delimited/Delimited_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Delimited/Quote_Style.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Format.enso
  std-bits/base/src/main/java/org/enso/base/file_format/FileFormatSPI.java
  std-bits/table/src/main/java/org/enso/table/read/ExcelFormatSPI.java
  test/AWS_Tests/data/format-delimited.datalink
  test/Table_Tests/data/datalinks/example-http-format-delimited-custom-quote.datalink
  test/Table_Tests/data/datalinks/example-http-format-delimited-ignore-quote.datalink
  test/Table_Tests/data/datalinks/example-http-format-excel-range.datalink
  test/Table_Tests/data/datalinks/example-http-format-excel-sheet.datalink
  test/Table_Tests/data/datalinks/example-http-format-excel-workbook.datalink
  test/Table_Tests/src/IO/Data_Link_Formats_Spec.enso
  test/Table_Tests/src/IO/Fetch_Spec.enso
  test/Table_Tests/src/IO/Main.enso
  tools/http-test-helper/www-files/table.tsv
Labels: CI: Ready to merge

#9332 Add xml.write tests and .write to XML_Element
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/XML.enso
  test/Base_Tests/data/xml/sample.xml
  test/Base_Tests/src/Data/XML/XML_Spec.enso
Labels: CI: No changelog needed

#9342 Removed enso-types and a some unused dependencies.
  .github/workflows/changelog.yml
  .github/workflows/engine-benchmark.yml
  .github/workflows/gui.yml
  .github/workflows/promote.yml
  .github/workflows/release.yml
  .github/workflows/scala-new.yml
  .github/workflows/std-libs-benchmark.yml
  Cargo.lock
  Cargo.toml
  build/build/src/ci_gen.rs
  build/deprecated/build-utils/Cargo.toml
  build/deprecated/build-utils/src/lib.rs
  lib/rust/data-structures/Cargo.toml
  lib/rust/logging/Cargo.toml
  lib/rust/parser/Cargo.toml
  lib/rust/parser/jni/Cargo.toml
  lib/rust/parser/src/lib.rs
  lib/rust/parser/src/source/code.rs
  lib/rust/prelude/Cargo.toml
  lib/rust/profiler/Cargo.toml
  lib/rust/reflect/Cargo.toml
  lib/rust/shapely/macros/Cargo.toml
  lib/rust/shapely/macros/src/lib.rs
  lib/rust/shapely/src/clone_ref.rs
  lib/rust/types/Cargo.toml
  lib/rust/types/src/lib.rs
  lib/rust/types/src/unit.rs
  lib/rust/web/Cargo.toml
Labels: CI: Ready to merge, CI: No changelog needed

#9323 [CI] Upload the directory as an artifact, not just its content
  build/ci_utils/src/actions/artifacts.rs
  build/ci_utils/src/actions/artifacts/upload.rs
Labels: CI: Ready to merge, CI: No changelog needed

#9368 Fix issues with labels in qualified entry names.
  app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue
Labels: CI: Ready to merge, CI: No changelog needed

#9370 Add missing icon to Excel DataLink schema
  app/ide-desktop/lib/dashboard/src/data/dataLinkSchema.json
Labels: CI: Ready to merge, CI: No changelog needed

#9366 Fix AST spacing
  app/gui2/shared/ast/ffi.ts
  app/gui2/shared/ast/index.ts
  app/gui2/shared/ast/tree.ts
  app/gui2/src/components/GraphEditor/collapsing.ts
  app/gui2/src/util/ast/__tests__/abstract.test.ts
  app/ide-desktop/lib/dashboard/src/data/__tests__/dataLinkSchema.test.ts
  vitest.workspace.ts
Labels: p-highest, CI: Ready to merge, CI: No changelog needed, --bug, -gui2

#9287 Update ~/.enso/credentials file
  app/ide-desktop/lib/client/src/authentication.ts
  app/ide-desktop/lib/client/src/preload.ts
  app/ide-desktop/lib/dashboard/src/authentication/cognito.ts
  app/ide-desktop/lib/dashboard/src/authentication/service.ts
  app/ide-desktop/lib/dashboard/src/providers/AuthProvider.tsx
  app/ide-desktop/lib/types/globals.d.ts
  app/ide-desktop/lib/types/ipc.d.ts
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Utils.enso
Labels: CI: No changelog needed, g-dashboard

#9339 Declare HTTPDownloaderTest as flaky
  build.sbt
  lib/scala/downloader/src/test/java/org/enso/downloader/http/HttpDownloaderTest.java
  lib/scala/testkit/src/main/java/org/enso/testkit/RetryTestRule.java
Labels: CI: Ready to merge, CI: No changelog needed

#9375 More type-checking for concrete children
  app/gui2/shared/ast/tree.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#9373 Show circular menu on icon-hover
  app/gui2/e2e/componentBrowser.spec.ts
  app/gui2/e2e/locate.ts
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/GraphNodes.vue
  app/gui2/src/components/GraphEditor/NodeWidgetTree.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetSelfIcon.vue
Labels: CI: No changelog needed, -gui

#9310 Scrollbars
  app/gui2/mock/providers.ts
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphEdge.vue
  app/gui2/src/components/SceneScroller.vue
  app/gui2/src/components/ScrollBar.vue
  app/gui2/src/composables/navigator.ts
  app/gui2/src/util/data/__tests__/rect.test.ts
  app/gui2/src/util/data/rect.ts
  app/gui2/src/util/data/vec2.ts
Labels: CI: No changelog needed, -gui

#9384 Fix dropdown clipping
  app/gui2/src/components/GraphEditor/widgets/WidgetApplication.vue
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#9271 Comment UI refinement
  app/gui2/src/components/GraphEditor/GraphNodeComment.vue
  app/gui2/src/components/GraphEditor/__tests__/comments.test.ts
Labels: CI: No changelog needed, -gui

#9322 Add some engine jobs that run with Oracle GraalVM
  .github/workflows/engine-benchmark.yml
  .github/workflows/scala-new.yml
  .github/workflows/std-libs-benchmark.yml
  CHANGELOG.md
  Cargo.lock
  build/build/Cargo.toml
  build/build/src/ci_gen.rs
  build/build/src/ci_gen/job.rs
  build/build/src/ci_gen/step.rs
  build/build/src/engine.rs
  build/build/src/engine/env.rs
  build/ci_utils/src/cache/goodie/graalvm.rs
  project/GraalVM.scala
Labels: CI: Ready to merge, CI: Clean build required

#9376 Build Script Post-Gui1 Cleanup
  .github/workflows/gui.yml
  .github/workflows/release.yml
  app/gui2/scripts/downloadFonts.js
  build/README.md
  build/build/paths.yaml
  build/build/release-body.md
  build/build/src/ci_gen.rs
  build/build/src/ci_gen/job.rs
  build/build/src/config.rs
  build/build/src/ide/web.rs
  build/build/src/project.rs
  build/build/src/project/gui.rs
  build/build/src/project/gui2.rs
  build/build/src/project/ide.rs
  build/build/src/project/ide2.rs
  build/build/src/project/wasm.rs
  build/build/src/project/wasm/test.rs
  build/build/src/release.rs
  build/cli/src/arg.rs
  build/cli/src/arg/gui.rs
  build/cli/src/arg/gui2.rs
  build/cli/src/arg/ide.rs
  build/cli/src/arg/ide2.rs
  build/cli/src/arg/wasm.rs
  build/cli/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#9372 Autoscope syntax
  engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java
  engine/runtime-parser/src/test/java/org/enso/compiler/core/EnsoParserTest.java
  lib/rust/parser/debug/src/lib.rs
  lib/rust/parser/debug/tests/parse.rs
  lib/rust/parser/src/lexer.rs
  lib/rust/parser/src/lib.rs
  lib/rust/parser/src/syntax/token.rs
  lib/rust/parser/src/syntax/tree.rs
Labels: CI: Ready to merge, CI: No changelog needed, -compiler, -syntax, -parser

#9388 [CI] Post-merge fixes for the workflow definitions.
  .github/workflows/engine-benchmark.yml
  .github/workflows/scala-new.yml
  .github/workflows/std-libs-benchmark.yml
Labels: CI: Ready to merge, CI: No changelog needed

#9396 sbt graalVMVersionCheck does not fail during reload
  build.sbt
  project/GraalVM.scala
Labels: CI: Ready to merge, CI: No changelog needed

#9382 Added Table.running
  CHANGELOG.md
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  test/Table_Tests/src/In_Memory/Main.enso
  test/Table_Tests/src/In_Memory/Table_Running_Spec.enso
Labels: CI: Ready to merge

#9398 Cleanup runtime project settings
  build.sbt
Labels: CI: Ready to merge, CI: No changelog needed

#9358 Arrow builder is not an Array
  engine/runtime-language-arrow/src/main/java/org/enso/interpreter/arrow/runtime/ArrowCastToFixedSizeArrayFactory.java
  engine/runtime-language-arrow/src/main/java/org/enso/interpreter/arrow/runtime/ArrowFixedArrayDate.java
  engine/runtime-language-arrow/src/main/java/org/enso/interpreter/arrow/runtime/ArrowFixedArrayInt.java
  engine/runtime-language-arrow/src/main/java/org/enso/interpreter/arrow/runtime/ArrowFixedSizeArrayBuilder.java
  engine/runtime-language-arrow/src/main/java/org/enso/interpreter/arrow/runtime/ByteBufferDirect.java
  engine/runtime-language-arrow/src/main/java/org/enso/interpreter/arrow/runtime/WriteToBuilderNode.java
  engine/runtime-language-arrow/src/test/java/org/enso/interpreter/arrow/VerifyArrowTest.java
  test/Base_Tests/src/Semantic/Arrow_Interop_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9385 Small fixes from building up another demo.
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Simple_Expression.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Workbook.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  test/Benchmarks/src/Map/Hash_Map.enso
  test/Benchmarks/src/Table/Column_From_Vector.enso
  test/Table_Tests/src/Common_Table_Operations/Conversion_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Date_Time_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Derived_Columns_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Union_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Map_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Database/Redshift_Spec.enso
  test/Table_Tests/src/Database/SQLite_Spec.enso
  test/Table_Tests/src/Database/Types/Postgres_Type_Mapping_Spec.enso
  test/Table_Tests/src/Database/Types/SQLite_Type_Mapping_Spec.enso
  test/Table_Tests/src/Database/Upload_Spec.enso
  test/Table_Tests/src/IO/Excel_Spec.enso
  test/Table_Tests/src/In_Memory/Column_Format_Spec.enso
  test/Table_Tests/src/In_Memory/Column_Spec.enso
  test/Table_Tests/src/In_Memory/Integer_Overflow_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9421 Fix the CSV file generation of bench_download script
  tools/performance/engine-benchmarks/Engine_Benchs/package.yaml
  tools/performance/engine-benchmarks/Engine_Benchs/src/Main.enso
  tools/performance/engine-benchmarks/README.md
  tools/performance/engine-benchmarks/bench_download.py
Labels: CI: Ready to merge, CI: No changelog needed

#9302 Implement file browser widget
  app/gui2/e2e/MockApp.vue
  app/gui2/e2e/widgets.spec.ts
  app/gui2/env.d.ts
  app/gui2/src/components/GraphEditor/widgets/WidgetFileBrowser.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue
  app/ide-desktop/lib/client/src/index.ts
  app/ide-desktop/lib/client/src/ipc.ts
  app/ide-desktop/lib/client/src/preload.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#9401 Fix e2e tests on Mac
  app/gui2/e2e/actions.ts
  app/gui2/src/components/GraphEditor/GraphEdge.vue
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#9426 Display custom unicode instead of `ArrowLeft` in keyboard shortcuts
  app/ide-desktop/lib/dashboard/src/components/dashboard/KeyboardShortcut.tsx
  app/ide-desktop/lib/dashboard/src/utilities/inputBindings.ts
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#9397 dry-run benchmarks exits when some benchmark fails
  build.sbt
  build/build/src/engine/context.rs
  engine/runtime-benchmarks/src/main/java/org/enso/compiler/benchmarks/Utils.java
  engine/runtime-benchmarks/src/main/java/org/enso/compiler/benchmarks/module/ImportStandardLibrariesBenchmark.java
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/IfVsCaseBenchmarks.java
  lib/java/benchmarks-common/src/main/java/org/enso/interpreter/bench/BenchmarksRunner.java
Labels: CI: Ready to merge, CI: No changelog needed

#9403 cleanup GUI entrypoints and mocking
  .vscode/extensions.json
  app/gui2/e2e/MockApp.vue
  app/gui2/e2e/actions.ts
  app/gui2/e2e/main.ts
  app/gui2/index.html
  app/gui2/mock/MockFSWrapper.vue
  app/gui2/mock/MockProjectStoreWrapper.vue
  app/gui2/mock/engine.ts
  app/gui2/mock/index.ts
  app/gui2/src/App.vue
  app/gui2/src/appRunner.ts
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/composables/events.ts
  app/gui2/src/createApp.ts
  app/gui2/src/e2e-entrypoint.ts
  app/gui2/src/entrypoint.ts
  app/gui2/src/stores/project/index.ts
  app/gui2/src/util/config.ts
  app/gui2/src/util/crdt.ts
  app/gui2/src/util/toast.ts
  app/gui2/src/util/urlParams.ts
  app/gui2/stories/CodeEditor.story.vue
  app/gui2/stories/GraphEditor.story.vue
  app/gui2/stories/UserDefinedVisualization.story.vue
  app/gui2/tsconfig.app.json
  app/gui2/tsconfig.story.json
  app/gui2/vite.config.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#9365 Code editor open-close improvements
  app/gui2/src/components/CodeEditor.vue
  app/gui2/src/components/ExtendedMenu.vue
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/TopBar.vue
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, -gui

#9297 Allow downloading Data Links and projects
  app/ide-desktop/lib/dashboard/src/components/dashboard/AssetRow.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetsTable.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Drive.tsx
  app/ide-desktop/lib/dashboard/src/layouts/DriveBar.tsx
  app/ide-desktop/lib/dashboard/src/services/Backend.ts
  app/ide-desktop/lib/dashboard/src/utilities/download.ts
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#9201 Reproduce Float-passing problem
  engine/polyglot-api/src/main/java/org/enso/polyglot/HostAccessFactory.java
  test/Base_Tests/polyglot-sources/enso-test-java-helpers/src/main/java/org/enso/base_test_helpers/Number_Utils.java
  test/Base_Tests/src/Data/Numbers_Spec.enso
  test/Base_Tests/src/Semantic/Java_Interop_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#9378 Fix dashboard bugs
  app/ide-desktop/eslint.config.js
  app/ide-desktop/lib/common/src/detect.ts
  app/ide-desktop/lib/dashboard/404.html
  app/ide-desktop/lib/dashboard/e2e/actions.ts
  app/ide-desktop/lib/dashboard/index.html
  app/ide-desktop/lib/dashboard/src/App.tsx
  app/ide-desktop/lib/dashboard/src/components/Modal.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetsTable.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Chat.tsx
  app/ide-desktop/lib/dashboard/src/layouts/ChatPlaceholder.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Editor.tsx
  app/ide-desktop/lib/dashboard/src/layouts/TopBar.tsx
  app/ide-desktop/lib/dashboard/src/pages/dashboard/Dashboard.tsx
  app/ide-desktop/lib/dashboard/src/utilities/object.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#9441 Wrong type dropdown for join_kind.
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9440 Debug JavaScript/Python in Enso Source
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/ForeignEvalNode.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
  tools/enso4igv/nbproject/project.properties
  tools/enso4igv/pom.xml
  tools/enso4igv/src/main/resources/org/enso/tools/enso4igv/enso.tmLanguage.json
  tools/enso4igv/src/test/java/org/enso/tools/enso4igv/EnsoTextMateTest.java
Labels: CI: No changelog needed

#9393 Avoid ArrayIndexOutOfBoundsException with no args
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionService.java
Labels: CI: Ready to merge, CI: No changelog needed

#9214 Fix warning in console about the `dashboard` keybind namespace being rebound
  app/ide-desktop/lib/dashboard/src/App.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/AssetRow.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetsTable.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Drive.tsx
  app/ide-desktop/lib/dashboard/src/modals/CaptureKeyboardShortcutModal.tsx
  app/ide-desktop/lib/dashboard/src/pages/dashboard/Dashboard.tsx
  app/ide-desktop/lib/dashboard/src/providers/InputBindingsProvider.tsx
  app/ide-desktop/lib/dashboard/src/utilities/inputBindings.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#9438 Fix sporadic `Table_Tests` failures caused by reliance on test ordering.
  test/Table_Tests/src/Common_Table_Operations/Select_Columns_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Util.enso
  test/Table_Tests/src/Database/SQLite_Spec.enso
Labels: CI: No changelog needed

#9427 Store additional metainformation for defineKeybinds
  app/gui2/src/components/ExtendedMenu.vue
  app/gui2/src/composables/__tests__/selection.test.ts
  app/gui2/src/util/shortcuts.ts
  app/ide-desktop/lib/dashboard/src/layouts/TopBar.tsx
  app/ide-desktop/lib/dashboard/src/layouts/UserBar.tsx
  app/ide-desktop/lib/dashboard/src/tailwind.css
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#9399 Drop-down filtering
  app/gui2/e2e/widgets.spec.ts
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetText.vue
  app/gui2/src/components/widgets/AutoSizedInput.vue
  app/gui2/src/providers/interactionHandler.ts
  app/gui2/src/providers/widgetRegistry.ts
  app/gui2/src/providers/widgetRegistry/__tests__/editHandler.test.ts
  app/gui2/src/providers/widgetRegistry/editHandler.ts
  app/gui2/src/util/autoBlur.ts
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, -gui

#9447 Make use of new icons from figma
  app/gui2/src/assets/icons.svg
  app/gui2/src/components/CodeEditor.vue
  app/gui2/src/components/ExtendedMenu.vue
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#9343 Added table.from_union and respective tests
  CHANGELOG.md
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Union_Spec.enso
Labels: CI: Ready to merge

#9431 Avoid Interop TypeOfNode specializations for EnsoObject
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/node/expression/builtin/meta/TypeOfNodeTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/TestBase.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/TypeOfNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/UnresolvedConstructor.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/UnresolvedConversion.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/UnresolvedSymbol.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/ArrayOverBuffer.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/ArraySlice.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicException.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicSentinel.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/WithWarnings.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java
Labels: CI: No changelog needed, CI: Clean build required

#9272 `Decimal` type: constuctors, comparisons, and arithmetic
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Decimal.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numeric/Internal/Decimal_Internal.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numeric/Internal/Numbers_Constants.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numeric/Math_Context.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numeric/Rounding_Mode.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
  std-bits/base/src/main/java/org/enso/base/numeric/ConversionResult.java
  std-bits/base/src/main/java/org/enso/base/numeric/Decimal_Utils.java
  test/Base_Tests/src/Data/Decimal_Spec.enso
  test/Base_Tests/src/Data/Numbers_Spec.enso
Labels: CI: Ready to merge, CI: Clean build required

#9434 Inhibit clipping when dropdown is opened
  app/gui2/src/components/GraphEditor/NodeWidgetTree.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetApplication.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui2/src/providers/widgetTree.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#9391 Remove-warnings button
  app/gui2/e2e/graphNodeVisualization.spec.ts
  app/gui2/src/components/CircularMenu.vue
  app/gui2/src/components/CodeEditor.vue
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/GraphNodes.vue
  app/gui2/src/components/GraphEditor/GraphVisualization.vue
  app/gui2/src/components/GraphEditor/nodeCreation.ts
  app/gui2/src/components/SmallPlusButton.vue
  app/gui2/src/components/VisualizationContainer.vue
  app/gui2/src/components/visualizations/WarningsVisualization.vue
  app/gui2/src/providers/visualizationConfig.ts
  app/gui2/src/stores/graph/index.ts
  app/gui2/src/util/ast/match.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#9386 Fix CB interaction with record-mode override and add tests
  app/gui2/e2e/componentBrowser.spec.ts
  app/gui2/src/components/CircularMenu.vue
  app/gui2/src/components/CodeEditor/codemirror.ts
  app/gui2/src/components/ComponentBrowser/input.ts
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/stores/graph/index.ts
  app/gui2/src/util/ast/__tests__/__snapshots__/raw.test.ts.snap
  app/gui2/src/util/ast/__tests__/abstract.test.ts
  app/gui2/src/util/ast/__tests__/opr.test.ts
  app/gui2/src/util/ast/__tests__/raw.test.ts
  app/gui2/src/util/ast/aliasAnalysis.ts
  app/gui2/src/util/ast/extended.ts
  app/gui2/src/util/ast/index.ts
  app/gui2/src/util/ast/opr.ts
  app/gui2/src/util/ast/raw.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#9439 Self-argument access chain ports are conditional
  app/gui2/e2e/componentBrowser.spec.ts
  app/gui2/e2e/edgeInteractions.spec.ts
  app/gui2/e2e/locate.ts
  app/gui2/shared/ast/tree.ts
  app/gui2/src/bindings.ts
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/NodeWidgetTree.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetPort.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetSelfIcon.vue
  app/gui2/src/composables/__tests__/selection.test.ts
  app/gui2/src/composables/events.ts
  app/gui2/src/composables/keyboard.ts
  app/gui2/src/composables/navigator.ts
  app/gui2/src/composables/selection.ts
  app/gui2/src/providers/graphSelection.ts
  app/gui2/src/providers/keyboard.ts
  app/gui2/src/providers/widgetTree.ts
  app/gui2/src/stores/graph/graphDatabase.ts
  app/gui2/src/stores/graph/index.ts
  app/gui2/src/util/__tests__/reactivity.test.ts
  app/gui2/src/util/ast/__tests__/abstract.test.ts
  app/gui2/src/util/ast/__tests__/node.test.ts
  app/gui2/src/util/ast/node.ts
  app/gui2/src/util/data/rect.ts
  app/gui2/src/util/reactivity.ts
  app/gui2/stories/GraphNode.story.vue
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#9446 Fix drag-n-drop onto empty space below asset table
  app/ide-desktop/lib/dashboard/e2e/actions.ts
  app/ide-desktop/lib/dashboard/e2e/assetsTableFeatures.spec.ts
  app/ide-desktop/lib/dashboard/src/layouts/AssetsTable.tsx
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#9407 Remove `ensogl-pack`
  Cargo.lock
  Cargo.toml
  app/ide-desktop/lib/client/package.json
  app/ide-desktop/lib/client/watch.ts
  app/ide-desktop/lib/content/bundle.ts
  app/ide-desktop/lib/content/esbuild-config.ts
  app/ide-desktop/lib/content/globals.d.ts
  app/ide-desktop/lib/content/package.json
  app/ide-desktop/lib/content/src/devServiceWorker.ts
  app/ide-desktop/lib/content/src/entrypoint.ts
  app/ide-desktop/lib/content/src/index.html
  app/ide-desktop/lib/content/src/remoteLog.ts
  app/ide-desktop/lib/content/src/run.js
  app/ide-desktop/lib/content/src/serviceWorker.ts
  app/ide-desktop/lib/content/src/serviceWorkerConstants.js
  app/ide-desktop/lib/content/src/style.css
  app/ide-desktop/lib/content/src/wasm_imports.js
  app/ide-desktop/lib/content/start.ts
  app/ide-desktop/lib/content/tsconfig.json
  app/ide-desktop/lib/content/watch.ts
  app/ide-desktop/lib/dashboard/package.json
  app/ide-desktop/lib/icons/package.json
  build/build/Cargo.toml
  lib/js/runner/.eslintrc.cjs
  lib/js/runner/package.json
  lib/js/runner/src/runner/animation.ts
  lib/js/runner/src/runner/config.json
  lib/js/runner/src/runner/config.ts
  lib/js/runner/src/runner/data/array.ts
  lib/js/runner/src/runner/debug/help-screen.ts
  lib/js/runner/src/runner/debug/index.ts
  lib/js/runner/src/runner/debug/package-info.ts
  lib/js/runner/src/runner/dom/dom.ts
  lib/js/runner/src/runner/dom/logo.ts
  lib/js/runner/src/runner/dom/svg.ts
  lib/js/runner/src/runner/host.ts
  lib/js/runner/src/runner/index.ts
  lib/js/runner/src/runner/log/index.ts
  lib/js/runner/src/runner/log/logger.ts
  lib/js/runner/src/runner/log/router.ts
  lib/js/runner/src/runner/math.ts
  lib/js/runner/src/runner/name.ts
  lib/js/runner/src/runner/wasm/entry-point.ts
  lib/js/runner/src/runner/wasm/index.ts
  lib/js/runner/src/runner/wasm/loader.ts
  lib/js/runner/tsconfig.json
  lib/rust/enso-pack/Cargo.lock
  lib/rust/enso-pack/Cargo.toml
  lib/rust/enso-pack/js/src/asset-extractor/args.ts
  lib/rust/enso-pack/js/src/asset-extractor/asset-extractor.ts
  lib/rust/enso-pack/js/src/asset-extractor/fs.ts
  lib/rust/enso-pack/js/src/runtime-libs/runtime-libs.ts
  lib/rust/enso-pack/js/src/wasm-pack-bundle/index.ts
  lib/rust/enso-pack/src/assets.rs
  lib/rust/enso-pack/src/lib.rs
  package-lock.json
  package.json
Labels: CI: Ready to merge, CI: No changelog needed

#9451 Un-nest AliasAnalysis Info and Graph to allow easier usage from Java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/PassPersistance.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/context/LocalScope.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/AutomaticParallelism.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/DataflowAnalysis.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/DemandAnalysis.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/Graph.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/Info.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/lint/UnusedBindings.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/optimise/LambdaConsolidate.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/FullyQualifiedNames.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/GlobalNames.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/analyse/AliasAnalysisTest.scala
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required, x-refactor

#9467 Dashboard fixes
  app/ide-desktop/lib/client/src/security.ts
  app/ide-desktop/lib/dashboard/src/App.tsx
  app/ide-desktop/lib/dashboard/src/components/JSONSchemaInput.tsx
  app/ide-desktop/lib/dashboard/src/components/SelectionBrush.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetProperties.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetSearchBar.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/AccountSettingsTab.tsx
  app/ide-desktop/lib/dashboard/src/utilities/event.ts
  app/ide-desktop/lib/dashboard/src/utilities/inputBindings.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#9480 Fix getters serialization
  engine/language-server/src/main/scala/org/enso/languageserver/search/SearchProtocol.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/SuggestionsHandlerEventsTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#9461 Hide scrollbars until track hovered
  app/gui2/src/components/SceneScroller.vue
  app/gui2/src/components/ScrollBar.vue
  app/gui2/src/util/data/vec2.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#9406 Allow `Table.replace` to take mutiple target columns
  CHANGELOG.md
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Replace_Helpers.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Replace_Spec.enso
Labels: CI: Ready to merge, CI: Clean build required

#9390 Implement refreshing the Cloud token in Enso libraries
  app/gui/view/graph-editor/src/builtin/visualization/java_script/table.js
  distribution/lib/Standard/AWS/0.0.0-dev/src/Internal/Data_Link_Helpers.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3_Data_Link.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Filter_Condition.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Index_Sub_Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Duration.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Data_Link.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_User.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Errors.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Authentication.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Utils.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Public_Utils.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/HTTP_Fetch_Data_Link.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Data_Link/Postgres_Data_Link.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Filter_Condition_Helpers.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Test.enso
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/semantic/TextTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Error.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/AuthenticationProvider.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/CloudAPI.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/EnsoSecretReader.java
  test/Base_Tests/src/Data/Array_Proxy_Spec.enso
  test/Base_Tests/src/Data/Map_Spec.enso
  test/Base_Tests/src/Data/Text/Regex_Spec.enso
  test/Base_Tests/src/Data/Text_Spec.enso
  test/Base_Tests/src/Data/Vector_Spec.enso
  test/Base_Tests/src/Network/Enso_Cloud/Cloud_Tests_Setup.enso
  test/Base_Tests/src/Network/Enso_Cloud/Enso_Cloud_Spec.enso
  test/Base_Tests/src/Network/Enso_Cloud/Secrets_Spec.enso
  test/Base_Tests/src/Runtime/Ascribed_Parameters_Spec.enso
  test/Base_Tests/src/Semantic/Conversion_Spec.enso
  test/Base_Tests/src/Semantic/Error_Spec.enso
  test/Base_Tests/src/Semantic/Meta_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Take_Drop_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso
  tools/http-test-helper/src/main/java/org/enso/shttp/HTTPTestHelperServer.java
  tools/http-test-helper/src/main/java/org/enso/shttp/SimpleHttpHandler.java
  tools/http-test-helper/src/main/java/org/enso/shttp/auth/HandlerWithTokenAuth.java
  tools/http-test-helper/src/main/java/org/enso/shttp/auth/TokenAuthTestHandler.java
  tools/http-test-helper/src/main/java/org/enso/shttp/cloud_mock/CloudAuthRenew.java
  tools/http-test-helper/src/main/java/org/enso/shttp/cloud_mock/CloudRoot.java
  tools/http-test-helper/src/main/java/org/enso/shttp/cloud_mock/ExpiredTokensCounter.java
  tools/http-test-helper/src/main/java/org/enso/shttp/cloud_mock/SecretsHandler.java
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#9465 Fix project not opening after reopening IDE when on Local backend
  app/ide-desktop/lib/dashboard/src/components/Button.tsx
  app/ide-desktop/lib/dashboard/src/pages/dashboard/Dashboard.tsx
Labels: CI: Ready to merge, CI: No changelog needed, --bug, --regression, g-dashboard

#9495 Fix Conditional ports tests.
  app/gui2/e2e/edgeInteractions.spec.ts
Labels: p-highest, CI: Ready to merge, CI: No changelog needed, -ci, --bug, -gui

#9498 Workaround for failing test
  app/gui2/e2e/componentBrowser.spec.ts
Labels: p-highest, CI: Ready to merge, CI: No changelog needed, -ci, --bug, -gui

#9500 Add new aliases for take
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
Labels: CI: No changelog needed

#9501 Some fixes working towards a sales demo
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/XML.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_Secret.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Request.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Response.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Response_Body.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/URI.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/Write_Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File_Format.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Widget_Helpers.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Image.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9505 Fix replace widget.
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9489 impr(enso/cloud-v2#912): Add `organization_id` and `user_id` fields to `SimpleUser`
  app/ide-desktop/lib/dashboard/e2e/api.ts
  app/ide-desktop/lib/dashboard/e2e/assetPanel.spec.ts
  app/ide-desktop/lib/dashboard/src/components/dashboard/AssetRow.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/UserPermission.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/column/SharedWithColumn.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/MembersSettingsTab.tsx
  app/ide-desktop/lib/dashboard/src/modals/ManagePermissionsModal.tsx
  app/ide-desktop/lib/dashboard/src/services/Backend.ts
  app/ide-desktop/lib/dashboard/src/utilities/permissions.ts
Labels: CI: Ready to merge, CI: No changelog needed

#9490 refr(enso/cloud-v2#912): Rename `SimpleUser.id` to `SimpleUser.userSubject`
  app/ide-desktop/lib/dashboard/src/modals/ManagePermissionsModal.tsx
  app/ide-desktop/lib/dashboard/src/services/Backend.ts
  app/ide-desktop/lib/dashboard/src/utilities/permissions.ts
Labels: CI: Ready to merge, CI: No changelog needed

#9506 [CI] Fix the notarization
  app/ide-desktop/lib/client/tasks/signArchivesMacOs.ts
Labels: CI: Ready to merge, CI: No changelog needed, -ci, -libs

#9496 Loose eslint rules for tailwind
  app/ide-desktop/eslint.config.js
Labels: CI: No changelog needed, x-chore, g-dashboard

#9484 Project manager create method should handle relative paths
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/file/Files.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/ProjectCreateHandler.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/ProjectDeleteHandler.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/ProjectOpenHandler.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/ProjectRenameHandler.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectService.scala
Labels: CI: Ready to merge, CI: No changelog needed

#9371 Speedup visualization and widget responses
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/command/ExecuteExpressionCommand.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/command/SetExecutionEnvironmentCommand.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/execution/JobControlPlane.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/job/ExecuteExpressionJob.java
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/WarningPreview.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/CloseFileCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/EditFileCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/ModifyVisualizationCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/OpenFileCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/SetExpressionValueCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/Executable.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/JobControlPlane.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/JobExecutionEngine.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ExecuteJob.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/Job.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/UpsertVisualizationJob.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeAsyncCommandsTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/HostClassLoader.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/ThreadExecutors.java
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#9513 Fix uninterpolated-text newline-insertion case
  app/gui2/shared/ast/tree.ts
  app/gui2/src/util/ast/__tests__/abstract.test.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#9510 Project manager returns normalized name of the created project
  docs/language-server/protocol-project-manager.md
  lib/scala/json-rpc-server-test/src/main/scala/org/enso/jsonrpc/test/JsonRpcServerTestKit.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/protocol/ProjectManagementApi.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/ProjectCreateHandler.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/ProjectManagementOps.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala
Labels: CI: Ready to merge, CI: No changelog needed

#9514 Data link for Snowflake.
  app/ide-desktop/lib/dashboard/src/data/dataLinkSchema.json
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Credentials.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Connection.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Dialect.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Snowflake_Data_Link.enso
  std-bits/snowflake/src/main/java/org/enso/snowflake/SnowflakeDataLinkSPI.java
Labels: CI: Ready to merge, CI: No changelog needed

#9507 [CI] Split GUI tests into a separate workflow
  .github/workflows/gui-tests.yml
  .github/workflows/gui.yml
  build/build/paths.yaml
  build/build/src/ci_gen.rs
  build/build/src/ci_gen/job.rs
Labels: CI: Ready to merge, CI: No changelog needed, -ci, -gui

#9485 Make data-links behave more like 'symlinks'
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3_Data_Link.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Data_Link.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Errors.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/File_Error.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Data_Read_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/HTTP_Fetch_Data_Link.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Response.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Response_Body.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/Data_Link_Access.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/File_Access.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/Generic/File_Like.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/Generic/File_Write_Strategy.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File_Format_Metadata.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/Input_Stream.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Data_Link/Postgres_Data_Link.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Examples/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Snowflake_Data_Link.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  std-bits/base/src/main/java/org/enso/base/enso_cloud/DataLinkFileFormatSPI.java
  test/AWS_Tests/src/Inter_Backend_File_Operations_Spec.enso
  test/AWS_Tests/src/Main.enso
  test/AWS_Tests/src/S3_Spec.enso
  test/Base_Tests/src/Network/Enso_Cloud/Cloud_Data_Link_Spec.enso
  test/Base_Tests/src/Network/Http/Http_Auto_Parse_Spec.enso
  test/Base_Tests/src/Network/Http/Http_Data_Link_Spec.enso
  test/Base_Tests/src/Network/Http_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/IO/Data_Link_Formats_Spec.enso
  test/Table_Tests/src/IO/Fetch_Spec.enso
  tools/http-test-helper/src/main/java/org/enso/shttp/HTTPTestHelperServer.java
  tools/http-test-helper/src/main/java/org/enso/shttp/SimpleHttpHandler.java
  tools/http-test-helper/src/main/java/org/enso/shttp/test_helpers/CrashingTestHandler.java
  tools/http-test-helper/src/main/java/org/enso/shttp/test_helpers/GenerateDataLinkHandler.java
  tools/http-test-helper/src/main/java/org/enso/shttp/test_helpers/HeaderTestHandler.java
  tools/http-test-helper/src/main/java/org/enso/shttp/test_helpers/RedirectTestHandler.java
  tools/http-test-helper/src/main/java/org/enso/shttp/test_helpers/TestHandler.java
  tools/http-test-helper/www-files/some-postgres.datalink
Labels: CI: Ready to merge, CI: No changelog needed

#9476 Reimplement AI PoC from GUI1
  app/gui2/e2e/componentBrowser.spec.ts
  app/gui2/mock/engine.ts
  app/gui2/mock/index.ts
  app/gui2/shared/languageServer.ts
  app/gui2/shared/languageServerTypes.ts
  app/gui2/shared/util/data/result.ts
  app/gui2/src/bindings.ts
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/components/ComponentBrowser/__tests__/input.test.ts
  app/gui2/src/components/ComponentBrowser/ai.ts
  app/gui2/src/components/ComponentBrowser/input.ts
  app/gui2/src/components/DocumentationPanel.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/collapsing.ts
  app/gui2/src/stores/graph/graphDatabase.ts
  app/gui2/src/stores/graph/index.ts
  app/gui2/src/util/__tests__/shortcuts.test.ts
  app/gui2/src/util/ast/__tests__/node.test.ts
  app/gui2/src/util/ast/node.ts
  app/gui2/src/util/shortcuts.ts
  app/gui2/stories/GraphNode.story.vue
  distribution/lib/Standard/Visualization/0.0.0-dev/src/AI.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Main.enso
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/ai/AICompletionHandler.scala
Labels: CI: Ready to merge, CI: No changelog needed, -ai, -gui

#9409 New JSON visualization
  app/gui2/e2e/css.ts
  app/gui2/e2e/fullscreenVisualisation.spec.ts
  app/gui2/e2e/graphNodeVisualization.spec.ts
  app/gui2/shared/ast/token.ts
  app/gui2/shared/ast/tree.ts
  app/gui2/src/components/CircularMenu.vue
  app/gui2/src/components/ComponentBrowser/__tests__/placement.test.ts
  app/gui2/src/components/ComponentBrowser/placement.ts
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/GraphNodes.vue
  app/gui2/src/components/GraphEditor/GraphVisualization.vue
  app/gui2/src/components/SmallPlusButton.vue
  app/gui2/src/components/VisualizationContainer.vue
  app/gui2/src/components/visualizations/JSONVisualization.vue
  app/gui2/src/components/visualizations/JSONVisualization/JsonArrayWidget.vue
  app/gui2/src/components/visualizations/JSONVisualization/JsonObjectWidget.vue
  app/gui2/src/components/visualizations/JSONVisualization/JsonPrimitiveWidget.vue
  app/gui2/src/components/visualizations/JSONVisualization/JsonValueWidget.vue
  app/gui2/src/components/visualizations/WarningsVisualization.vue
  app/gui2/src/providers/visualizationConfig.ts
  app/gui2/src/stores/graph/index.ts
  app/gui2/src/util/ast/match.ts
  app/gui2/src/util/data/vec2.ts
Labels: CI: No changelog needed, -gui

#9516 Multi-select (part 1)
  app/gui2/e2e/collapsingAndEntering.spec.ts
  app/gui2/e2e/componentBrowser.spec.ts
  app/gui2/e2e/edgeRendering.spec.ts
  app/gui2/e2e/locate.ts
  app/gui2/e2e/widgets.spec.ts
  app/gui2/mock/engine.ts
  app/gui2/shared/ast/tree.ts
  app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetVector.vue
  app/gui2/src/components/widgets/DropdownWidget.vue
  app/gui2/src/components/widgets/ListWidget.vue
  app/gui2/src/providers/widgetRegistry/configuration.ts
  app/gui2/src/providers/widgetRegistry/editHandler.ts
  app/gui2/src/util/ast/__tests__/abstract.test.ts
  app/gui2/src/util/ast/__tests__/callTree.test.ts
  app/gui2/src/util/callTree.ts
  app/gui2/stories/mockSuggestions.json
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
Labels: CI: No changelog needed, -gui

#9537 Ignore repeated key events for bound shortcuts, adjust visualization min width
  app/gui2/src/components/VisualizationContainer.vue
  app/gui2/src/util/shortcuts.ts
Labels: CI: Ready to merge, CI: No changelog needed

#9512 Move imports to first script block to avoid prettier issues
  app/gui2/src/components/visualizations/WarningsVisualization.vue
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#9533 Make expand_to_rows, expand_column support Rows, Tables, Column data types
  CHANGELOG.md
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Conversions/Convertible_To_Columns.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Conversions/Convertible_To_Rows.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso
  test/Table_Tests/src/In_Memory/Table_Conversion_Spec.enso
Labels: CI: Ready to merge

#9536 Select node on any edit
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/NodeWidgetTree.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetNumber.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui2/src/components/widgets/NumericInputWidget.vue
  app/gui2/src/providers/widgetRegistry/__tests__/editHandler.test.ts
  app/gui2/src/providers/widgetRegistry/editHandler.ts
  app/gui2/src/providers/widgetTree.ts
  app/gui2/src/stores/graph/graphDatabase.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#9454 Put all reexports of given entry in Suggestion Database
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/search/SearchProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/SuggestionsHandlerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/SuggestionsHandlerEventsTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/Suggestion.scala
  engine/runtime-compiler/src/main/java/org/enso/compiler/context/ExportsMap.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/context/ExportsBuilder.scala
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/SerializationManagerTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/context/JacksonTest.java
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeSuggestionUpdatesTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeTextEditsTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java
  engine/runtime/src/main/java/org/enso/interpreter/util/ScalaConversions.java
  lib/scala/searcher/src/main/scala/org/enso/searcher/SuggestionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlSuggestionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/Tables.scala
  lib/scala/searcher/src/test/scala/org/enso/searcher/sql/SuggestionsRepoTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#9551 Use `DELETE /assets/<id>` for deleting files and secrets
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_Secret.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Utils.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9544 Inject AG Grid and Mapbox keys through the CI from the GitHub organization variables
  .github/workflows/gui.yml
  .github/workflows/release.yml
  app/gui2/src/components/visualizations/GeoMapVisualization.vue
  app/gui2/src/components/visualizations/TableVisualization.vue
  build/build/src/ci_gen.rs
  build/build/src/ci_gen/job.rs
  build/build/src/env.rs
  build/build/src/ide/web.rs
  build/ci_utils/src/actions/workflow/definition.rs
Labels: CI: Ready to merge, CI: No changelog needed

#9525 Data Link for reading `Enso_File`
  CHANGELOG.md
  app/ide-desktop/lib/dashboard/src/components/dashboard/DataLinkInput.tsx
  app/ide-desktop/lib/dashboard/src/data/__tests__/dataLinkSchema.test.ts
  app/ide-desktop/lib/dashboard/src/data/dataLinkSchema.json
  app/ide-desktop/lib/dashboard/src/data/dataLinkValidator.ts
  app/ide-desktop/lib/dashboard/src/index.html
  app/ide-desktop/lib/dashboard/src/layouts/AssetProperties.tsx
  app/ide-desktop/lib/dashboard/src/modals/UpsertDataLinkModal.tsx
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3_Data_Link.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Enso_File_Data_Link.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Internal/HTTP_Fetch_Data_Link.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Data_Link/Postgres_Data_Link.enso
  std-bits/base/src/main/java/org/enso/base/enso_cloud/EnsoFileDataLinkSPI.java
  std-bits/base/src/main/java/org/enso/base/net/http/HTTPFetchDataLinkSPI.java
  test/Base_Tests/data/datalinks/example-enso-file.datalink
  test/Base_Tests/src/Network/Enso_Cloud/Cloud_Data_Link_Spec.enso
Labels: CI: Ready to merge, CI: Clean build required

#9556 Add --disable-private-check runner option
  engine/runner/src/main/scala/org/enso/runner/Main.scala
Labels: CI: Ready to merge, CI: No changelog needed

#9543 Add IRDumper for Scala IR
  engine/runtime-compiler/src/main/java/org/enso/compiler/dump/GraphVizEdge.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/dump/GraphVizNode.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/dump/IRDumper.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/dump/Utils.java
Labels: CI: Ready to merge, CI: No changelog needed

#9532 Crash when editing secret
  app/ide-desktop/lib/dashboard/src/services/remoteBackendPaths.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#9531 Listing versions on file results in 403 flood
  app/ide-desktop/lib/dashboard/.prettierrc.cjs
  app/ide-desktop/lib/dashboard/src/App.tsx
  app/ide-desktop/lib/dashboard/src/reactQueryClient.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#9546 Fix missing AWS region in S3 operations
  .github/workflows/scala-new.yml
  app/ide-desktop/lib/dashboard/src/index.html
  build/build/src/ci_gen/job.rs
  build/build/src/lib.rs
  build/build/src/libraries_tests.rs
  distribution/lib/Standard/AWS/0.0.0-dev/src/AWS_Credential.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/AWS_Region.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso
  std-bits/aws/src/main/java/org/enso/aws/BucketLocator.java
  std-bits/aws/src/main/java/org/enso/aws/ClientBuilder.java
  std-bits/aws/src/main/java/org/enso/aws/DefaultRegionProvider.java
  std-bits/aws/src/main/java/org/enso/aws/ProfileReader.java
  test/AWS_Tests/src/Credentials_Spec.enso
  test/AWS_Tests/src/Inter_Backend_File_Operations_Spec.enso
  test/AWS_Tests/src/Main.enso
  test/AWS_Tests/src/S3_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9545 Fix collapsing node issues
  app/gui2/src/components/GraphEditor/__tests__/collapsing.test.ts
  app/gui2/src/components/GraphEditor/collapsing.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui

#9508 refr(enso-org/cloud-v2#912): Standardize `User` fields
  app/ide-desktop/lib/dashboard/e2e/api.ts
  app/ide-desktop/lib/dashboard/e2e/assetPanel.spec.ts
  app/ide-desktop/lib/dashboard/e2e/signUpWithOrganizationId.spec.ts
  app/ide-desktop/lib/dashboard/e2e/signUpWithoutOrganizationId.spec.ts
  app/ide-desktop/lib/dashboard/src/components/dashboard/AssetRow.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/ProjectNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/UserPermission.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/column/LabelsColumn.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/column/SharedWithColumn.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetProperties.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetsTable.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetsTableContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings.tsx
  app/ide-desktop/lib/dashboard/src/layouts/UserBar.tsx
  app/ide-desktop/lib/dashboard/src/modals/InviteUsersModal.tsx
  app/ide-desktop/lib/dashboard/src/modals/ManagePermissionsModal.tsx
  app/ide-desktop/lib/dashboard/src/providers/AuthProvider.tsx
  app/ide-desktop/lib/dashboard/src/services/Backend.ts
  app/ide-desktop/lib/dashboard/src/services/RemoteBackend.ts
  app/ide-desktop/lib/dashboard/src/utilities/permissions.ts
Labels: CI: No changelog needed

#9557 [CI] Restore uploading backend image to ECR as part of the release workflow.
  .github/workflows/release.yml
  build/build/src/ci_gen.rs
  build/build/src/ci_gen/job.rs
Labels: CI: Ready to merge, CI: No changelog needed, -ci

#9511 refr(enso-org/cloud-v2#1060): Rename `OrganizationInfo` fields to `camelCase`
  app/ide-desktop/lib/dashboard/src/layouts/Settings.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/OrganizationSettingsTab.tsx
  app/ide-desktop/lib/dashboard/src/services/Backend.ts
Labels: CI: Ready to merge, CI: No changelog needed

#9550 Subprocess does not freeze when it generates a lot of output to stdout
  engine/runtime/src/main/java/org/enso/interpreter/runtime/system/System.java
Labels: CI: No changelog needed

#9548 `Set.to_text` should not assume contents are `Text`
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Set.enso
  test/Base_Tests/src/Data/Set_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed
