Repository enso-org/enso, pull requests merged in 2024-04, with the labels that each got.

#9567 Prevent context menus from going off the left side of the screen
  app/ide-desktop/lib/dashboard/src/components/ContextMenus.tsx
  app/ide-desktop/lib/dashboard/tailwind.config.js
Labels: CI: Ready to merge, CI: No changelog needed, --bug, --regression, g-dashboard

#9587 Fix `dateTime.test.ts`
  app/ide-desktop/lib/dashboard/src/utilities/__tests__/dateTime.test.ts
Labels: p-high, CI: Ready to merge, CI: No changelog needed, --regression, g-dashboard

#9578 Fix numeric widget slider
  app/gui2/src/components/GraphEditor/widgets/WidgetNumber.vue
  app/gui2/src/components/widgets/NumericInputWidget.vue
  app/gui2/src/composables/events.ts
  package-lock.json
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui

#9584 Don't let the non-Enso types float around the Enso interpreter!
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/WarningsTest.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoFile.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/ManagedResource.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Ref.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/ArrayLikeHelpers.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/ArraySlice.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/Warning.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/WithWarnings.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/system/System.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/BuiltinsProcessor.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/builtins/ExecuteMethodImplGenerator.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/builtins/MethodGenerator.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/builtins/MethodParameter.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/builtins/NoSpecializationClassGenerator.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/builtins/SpecializedMethodsGenerator.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/builtins/TypeWithKind.java
Labels: CI: No changelog needed, CI: Clean build required, --bug, -compiler

#9468 Send credentials on `open_project`
  app/ide-desktop/lib/dashboard/src/authentication/cognito.ts
  app/ide-desktop/lib/dashboard/src/components/dashboard/ProjectIcon.tsx
  app/ide-desktop/lib/dashboard/src/services/Backend.ts
  app/ide-desktop/lib/dashboard/src/services/RemoteBackend.ts
  app/ide-desktop/lib/dashboard/src/text/english.json
  app/ide-desktop/lib/dashboard/src/text/index.ts
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#9570 Color picker
  app/gui2/package.json
  app/gui2/shared/ast/tree.ts
  app/gui2/src/bindings.ts
  app/gui2/src/components/CircularMenu.vue
  app/gui2/src/components/ColorPicker.vue
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/GraphNodes.vue
  app/gui2/src/stores/graph/graphDatabase.ts
  app/gui2/src/stores/graph/index.ts
  app/gui2/src/util/colors.ts
  app/gui2/ydoc-server/edits.ts
  app/gui2/ydoc-server/fileFormat.ts
  app/gui2/ydoc-server/languageServerSession.ts
  package-lock.json
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, -gui

#9592 Fix expectations in lock manager test
  lib/scala/connected-lock-manager/src/test/scala/org/enso/lockmanager/ConnectedLockManagerTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#9594 Fix project edits
  app/gui2/ydoc-server/edits.ts
Labels: p-highest, CI: Ready to merge, CI: No changelog needed, --regression, -gui

#9596 Allow vector widget only on vector expressions.
  app/gui2/src/components/GraphEditor/widgets/WidgetVector.vue
  app/gui2/src/providers/widgetRegistry.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#9530 Context menu should have a Edit Description on files
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Button/Button.tsx
  app/ide-desktop/lib/dashboard/src/components/MenuEntry.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/AssetRow.tsx
  app/ide-desktop/lib/dashboard/src/configurations/inputBindings.ts
  app/ide-desktop/lib/dashboard/src/layouts/AssetContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/modals/EditAssetDescriptionModal.tsx
  app/ide-desktop/lib/dashboard/src/text/english.json
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#9602 Fix numeric input widget
  app/gui2/src/components/widgets/NumericInputWidget.vue
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui

#9591 Add missing API for Jackson_Object
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Java_Json.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Zone.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Conversions/Convertible_To_Columns.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Conversions/Convertible_To_Rows.enso
  test/Base_Tests/src/Data/Json_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9590 Removing useless methods
  engine/runtime/src/main/java/org/enso/interpreter/node/ExpressionNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/function/BlockNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/function/CreateFunctionNode.java
Labels: CI: No changelog needed

#9604 Fix reported content-length in project manager shim.
  app/ide-desktop/lib/project-manager-shim/src/projectManagerShimMiddleware.ts
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#9595 Bump clap to v4
  Cargo.lock
  Cargo.toml
  build/build/Cargo.toml
  build/build/src/engine.rs
  build/build/src/project/wasm.rs
  build/build/src/project/wasm/test.rs
  build/build/src/version.rs
  build/build/src/version/promote.rs
  build/ci_utils/Cargo.toml
  build/ci_utils/src/extensions/clap.rs
  build/cli/Cargo.toml
  build/cli/src/arg.rs
  build/cli/src/arg/backend.rs
  build/cli/src/arg/gui.rs
  build/cli/src/arg/ide.rs
  build/cli/src/arg/release.rs
  build/cli/src/arg/runtime.rs
  build/cli/src/arg/wasm.rs
  tools/language-server/logstat/Cargo.toml
  tools/language-server/wstest/Cargo.toml
Labels: CI: Ready to merge, CI: No changelog needed, x-chore, -build-script

#9611 Manage analytics client to avoid leaks
  distribution/lib/Standard/Google_Api/0.0.0-dev/src/Internal/Google_Analytics_Internal.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9616 Fix dropdown item paddings
  app/gui2/src/components/widgets/DropdownWidget.vue
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#9588 Remove pending tests for hash consistency.
  test/Base_Tests/src/Data/Decimal_Spec.enso
  test/Base_Tests/src/Data/Numbers_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9629 Follow up #9611
  distribution/lib/Standard/Google_Api/0.0.0-dev/src/Internal/Google_Analytics_Internal.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9586 Add range info to `Out_Of_Range` error
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Decimal.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso
  test/Base_Tests/src/Data/Decimal_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9579 Improve gui app disposal handling and close all network connections
  app/gui2/shared/dataServer.ts
  app/gui2/shared/languageServer.ts
  app/gui2/shared/util/net.ts
  app/gui2/shared/websocket.ts
  app/gui2/src/appRunner.ts
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/createApp.ts
  app/gui2/src/stores/project/computedValueRegistry.ts
  app/gui2/src/stores/project/index.ts
  app/gui2/src/stores/project/visualizationDataRegistry.ts
  app/gui2/src/util/crdt.ts
  app/gui2/src/util/net.ts
  app/gui2/stories/Widgets.story.vue
  app/gui2/ydoc-server/languageServerSession.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#9564 [CI] Adding `assets.json` file to the releases.
  build/build/release-body.md
  build/build/src/paths.rs
  build/build/src/project/ide.rs
  build/build/src/project_manager.rs
  build/build/src/release.rs
  build/build/src/release/manifest.rs
  build/ci_utils/src/github/release.rs
Labels: CI: Ready to merge, CI: No changelog needed, -ci

#9630 Autoscoped constructors in a vector
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Aggregate_Column_Helper.enso
  engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java
  test/Table_Tests/src/Helpers/Auto_Constructor_Instrumentation_Spec.enso
  test/Table_Tests/src/Helpers/Main.enso
  test/Table_Tests/src/Helpers/Table_Aggregate_Auto_Constructor.enso
Labels: CI: No changelog needed

#9620 Improve perf of Graph.Scope.scopeFor hotspot
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/PassPersistance.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/context/LocalScope.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/Graph.scala
Labels: CI: Ready to merge, CI: No changelog needed

#9589 Make the`%` consistent across both `Integer` sizes.
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Decimal.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/utils/BigIntegerOps.java
  test/Base_Tests/src/Data/Numbers_Spec.enso
Labels: CI: Ready to merge

#9582 `Decimal` arithmetic benchmarks
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numeric/Internal/Numbers_Constants.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Faker.enso
  test/Base_Tests/src/Data/Decimal_Spec.enso
  test/Benchmarks/src/Collections.enso
  test/Benchmarks/src/Column_Numeric.enso
  test/Benchmarks/src/Decimal_Benchmark.enso
  test/Benchmarks/src/Main.enso
  test/Benchmarks/src/Number_Parse.enso
  test/Benchmarks/src/Numeric.enso
  test/Benchmarks/src/Sum.enso
  test/Benchmarks/src/Table/Aggregate.enso
  test/Benchmarks/src/Table/Cross_Tab.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9636 Tests for floating point mod
  test/Base_Tests/src/Data/Numbers_Spec.enso
Labels: CI: No changelog needed

#9466 Remove obsolete GUI arguments
  app/gui2/src/appRunner.ts
  app/ide-desktop/lib/client/esbuild-config.ts
  app/ide-desktop/lib/client/paths.ts
  app/ide-desktop/lib/client/src/config.ts
  app/ide-desktop/lib/content-config/src/config.json
  app/ide-desktop/lib/content-config/src/index.ts
  app/ide-desktop/lib/dashboard/src/layouts/Editor.tsx
  app/ide-desktop/lib/types/globals.d.ts
  lib/js/runner/src/runner/config.ts
Labels: CI: Ready to merge, CI: No changelog needed, x-chore, g-dashboard, -gui

#9633 Hide errors from input nodes
  app/gui2/shared/ast/index.ts
  app/gui2/shared/util/data/graph.ts
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/GraphNodeMessage.vue
  app/gui2/src/stores/graph/__tests__/graphDatabase.test.ts
  app/gui2/src/stores/graph/graphDatabase.ts
  app/gui2/src/stores/graph/index.ts
Labels: CI: Ready to merge, CI: No changelog needed

#9618 Normalize windows paths
  app/ide-desktop/lib/client/package.json
  app/ide-desktop/lib/client/src/index.ts
  app/ide-desktop/lib/client/watch.ts
  app/ide-desktop/lib/dashboard/src/services/ProjectManager.ts
  app/ide-desktop/lib/types/globals.d.ts
  package-lock.json
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#9628 Update organization body param location -> address
  app/ide-desktop/lib/dashboard/src/layouts/Settings/OrganizationSettingsSection.tsx
  app/ide-desktop/lib/dashboard/src/services/Backend.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#9627 Fix reloading when the saved project uses the Local Backend
  app/ide-desktop/lib/dashboard/src/App.tsx
  app/ide-desktop/lib/dashboard/src/index.tsx
  app/ide-desktop/lib/dashboard/src/pages/authentication/ErrorScreen.tsx
  app/ide-desktop/lib/dashboard/src/pages/dashboard/Dashboard.tsx
  app/ide-desktop/lib/dashboard/src/providers/AuthProvider.tsx
  app/ide-desktop/lib/dashboard/src/services/LocalBackend.ts
  app/ide-desktop/lib/dashboard/src/services/ProjectManager.ts
  app/ide-desktop/lib/dashboard/src/services/RemoteBackend.ts
  app/ide-desktop/lib/dashboard/src/text/english.json
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#9634 GUI project does not receive suggestion database
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/handler/InvalidateModulesIndexHandler.scala
Labels: CI: Ready to merge, CI: No changelog needed

#9615 Fix documentation panel layout
  app/gui2/src/components/GraphEditor/widgets/WidgetApplication.vue
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui

#9585 Use predefined zoom levels
  app/gui2/src/composables/navigator.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui

#9293 Use autoscoping when constructing tag values of suggestion arguments
  engine/runtime-compiler/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/context/SuggestionBuilderTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#9646 Do not disable BackgroundCompilation in benchmarks
  engine/runtime-benchmarks/src/main/java/org/enso/compiler/benchmarks/Utils.java
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/ArrayProxyBenchmarks.java
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/AtomBenchmarks.java
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/CallableBenchmarks.java
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/EqualsBenchmarks.java
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/IfVsCaseBenchmarks.java
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/ListBenchmarks.java
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/NamedDefaultedArgumentBenchmarks.java
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/NestedPatternCompilationBenchmarks.java
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/RecursionBenchmarks.java
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/SrcUtil.java
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/StringBenchmarks.java
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/TypePatternBenchmarks.java
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/VectorBenchmarks.java
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/WarningBenchmarks.java
  test/Benchmarks/src/Table/Sorting.enso
Labels: CI: No changelog needed

#9641 `Decimal.abs`, `.negate`, `.signum`
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Decimal.enso
  test/Base_Tests/src/Data/Decimal_Spec.enso
Labels: CI: Ready to merge

#9642 Improve handling of `File.parent` and `File.name`
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoFile.java
  test/Base_Tests/src/System/File_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9649 Add prefixes for cloud url params
  app/gui2/src/appRunner.ts
  app/gui2/src/util/urlParams.ts
  app/ide-desktop/lib/dashboard/src/appUtils.tsx
  app/ide-desktop/lib/dashboard/src/hooks/searchParamsStateHooks.ts
  app/ide-desktop/lib/dashboard/src/layouts/Editor.tsx
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard, -gui

#9652 Make HTTP tests more robust by adding retries to the tests
  distribution/lib/Standard/Test/0.0.0-dev/src/Test.enso
  test/AWS_Tests/src/S3_Spec.enso
  test/Base_Tests/src/Data/XML/XML_Spec.enso
  test/Base_Tests/src/Network/Enso_Cloud/Cloud_Data_Link_Spec.enso
  test/Base_Tests/src/Network/Enso_Cloud/Cloud_Tests_Setup.enso
  test/Base_Tests/src/Network/Enso_Cloud/Enso_File_Spec.enso
  test/Base_Tests/src/Network/Enso_Cloud/Secrets_Spec.enso
  test/Base_Tests/src/Network/Http/Http_Auto_Parse_Spec.enso
  test/Base_Tests/src/Network/Http/Http_Data_Link_Spec.enso
  test/Base_Tests/src/Network/Http_Spec.enso
  test/Base_Tests/src/Network/URI_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Database/Snowflake_Spec.enso
  test/Table_Tests/src/IO/Fetch_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9581 Refactoring `Enso_File` to be path based
  distribution/lib/Standard/AWS/0.0.0-dev/src/Internal/S3_Path.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_Secret.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_User.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Enso_Path.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Existing_Enso_Asset.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Utils.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Public_Utils.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Path_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Spec_Result.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Test.enso
  std-bits/base/src/main/java/org/enso/base/enso_cloud/CloudAPI.java
  test/AWS_Tests/src/S3_Spec.enso
  test/Base_Tests/src/Network/Enso_Cloud/Cloud_Data_Link_Spec.enso
  test/Base_Tests/src/Network/Enso_Cloud/Enso_Cloud_Spec.enso
  test/Base_Tests/src/Network/Enso_Cloud/Enso_File_Spec.enso
  test/Base_Tests/src/Network/Enso_Cloud/Secrets_Spec.enso
  tools/http-test-helper/src/main/java/org/enso/shttp/cloud_mock/SecretsHandler.java
  tools/http-test-helper/src/main/java/org/enso/shttp/cloud_mock/UsersHandler.java
Labels: CI: Ready to merge, CI: No changelog needed

#9651 Store graph viewport in client local storage
  app/gui2/e2e/setup.ts
  app/gui2/e2e/undoRedo.spec.ts
  app/gui2/mock/index.ts
  app/gui2/mock/providers.ts
  app/gui2/shared/ast/ffi.ts
  app/gui2/shared/languageServer.ts
  app/gui2/shared/languageServerTypes.ts
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/clipboard.ts
  app/gui2/src/components/GraphEditor/toasts.ts
  app/gui2/src/components/visualizations/TableVisualization.vue
  app/gui2/src/composables/__tests__/navigator.test.ts
  app/gui2/src/composables/animation.ts
  app/gui2/src/composables/navigator.ts
  app/gui2/src/composables/navigatorStorage.ts
  app/gui2/src/providers/graphSelection.ts
  app/gui2/src/stores/graph/index.ts
  app/gui2/src/stores/project/index.ts
  app/gui2/src/util/data/iterable.ts
  app/gui2/src/util/data/rect.ts
  app/gui2/src/util/data/vec2.ts
  app/gui2/stories/GraphNode.story.vue
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#9655 Accept small BigInteger values
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Decimal.enso
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/ValuesGenerator.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsSimpleNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/HashCodeNode.java
Labels: CI: No changelog needed

#9661 impr(enso-org/cloud-v2#1047): Enable Sentry distributed tracing
  app/ide-desktop/lib/dashboard/src/index.tsx
Labels: CI: Ready to merge, CI: No changelog needed

#9575 Disable everything except restore / hard delete in trash
  app/ide-desktop/lib/dashboard/src/components/dashboard/AssetRow.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/DataLinkNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/DirectoryNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/FileNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/ProjectNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/SecretNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/column.ts
  app/ide-desktop/lib/dashboard/src/components/dashboard/column/SharedWithColumn.tsx
  app/ide-desktop/lib/dashboard/src/hooks/eventHooks.ts
  app/ide-desktop/lib/dashboard/src/layouts/AssetPanel.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetProperties.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetsTable.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Drive.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Labels.tsx
  app/ide-desktop/lib/dashboard/src/pages/dashboard/Dashboard.tsx
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#9601 Undelete user flow
  app/ide-desktop/lib/dashboard/src/App.tsx
  app/ide-desktop/lib/dashboard/src/appUtils.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Button/Button.tsx
  app/ide-desktop/lib/dashboard/src/components/SvgMask.tsx
  app/ide-desktop/lib/dashboard/src/modals/ConfirmDeleteUserModal.tsx
  app/ide-desktop/lib/dashboard/src/pages/authentication/RestoreAccount.tsx
  app/ide-desktop/lib/dashboard/src/providers/AuthProvider.tsx
  app/ide-desktop/lib/dashboard/src/services/Backend.ts
  app/ide-desktop/lib/dashboard/src/services/LocalBackend.ts
  app/ide-desktop/lib/dashboard/src/services/RemoteBackend.ts
  app/ide-desktop/lib/dashboard/src/text/english.json
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#9668 Fix dropdowns no longer opening after first open
  app/ide-desktop/lib/dashboard/src/components/Dropdown.tsx
Labels: CI: Ready to merge, CI: No changelog needed, --bug, --regression, g-dashboard

#9671 Reduce parser dependencies
  Cargo.lock
  Cargo.toml
  lib/rust/logging/Cargo.toml
  lib/rust/logging/macros/Cargo.toml
  lib/rust/logging/macros/build.rs
  lib/rust/logging/macros/src/lib.rs
  lib/rust/logging/src/lib.rs
  lib/rust/parser/Cargo.toml
  lib/rust/parser/debug/Cargo.toml
  lib/rust/parser/debug/src/bin/check_syntax.rs
  lib/rust/parser/debug/tests/parse.rs
  lib/rust/parser/doc-parser/Cargo.toml
  lib/rust/parser/doc-parser/src/lib.rs
  lib/rust/parser/doc-parser/src/main.rs
  lib/rust/parser/jni/src/lib.rs
  lib/rust/parser/src/macros/resolver.rs
  lib/rust/parser/src/syntax/tree.rs
  lib/rust/parser/src/syntax/tree/block.rs
  lib/rust/parser/src/syntax/tree/visitor/src/lib.rs
  lib/rust/prelude/Cargo.toml
  lib/rust/prelude/src/lib.rs
Labels: CI: No changelog needed

#9676 Change window title
  app/gui2/index.html
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#9678 Display parens in groups
  app/gui2/src/components/GraphEditor/widgets/WidgetGroup.vue
  app/gui2/src/components/widgets/ListWidget.vue
  app/gui2/src/stores/graph/index.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui

#9657 working hot reload for widget definitions
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/GraphNodes.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetApplication.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetArgumentName.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetBlank.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetCheckbox.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetFileBrowser.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetFunction.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetGroup.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetHierarchy.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetNumber.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetPort.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetSelfIcon.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetText.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetToken.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetTopLevelArgument.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetVector.vue
  app/gui2/src/providers/widgetRegistry.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#9621 Interaction resumption
  app/gui2/e2e/widgets.spec.ts
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphEdges.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetNumber.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetText.vue
  app/gui2/src/components/widgets/DropdownWidget.vue
  app/gui2/src/providers/interactionHandler.ts
  app/gui2/src/providers/widgetRegistry/__tests__/editHandler.test.ts
  app/gui2/src/providers/widgetRegistry/editHandler.ts
  app/gui2/src/util/callTree.ts
Labels: CI: Ready to merge, CI: No changelog needed

#9660 Attach warning when converting from `Decimal` to `Integer`
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Decimal.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/HashCodeNode.java
  test/Base_Tests/src/Data/Decimal_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9672 Add `Decimal.round`
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Decimal.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso
  std-bits/base/src/main/java/org/enso/base/numeric/Decimal_Utils.java
  test/Base_Tests/src/Data/Decimal_Spec.enso
  test/Base_Tests/src/Data/Numbers_Spec.enso
  test/Base_Tests/src/Data/Round_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
Labels: CI: Ready to merge

#9644 Option to use Data Link in new project
  app/ide-desktop/lib/dashboard/src/components/MenuEntry.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/AssetRow.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/DataLinkNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/DirectoryNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/FileNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/ProjectNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/SecretNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/column.ts
  app/ide-desktop/lib/dashboard/src/configurations/inputBindings.ts
  app/ide-desktop/lib/dashboard/src/events/assetEvent.ts
  app/ide-desktop/lib/dashboard/src/events/assetListEvent.ts
  app/ide-desktop/lib/dashboard/src/hooks/setAssetHooks.ts
  app/ide-desktop/lib/dashboard/src/layouts/AssetContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetPanel.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetProperties.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetsTable.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetsTableContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Drive.tsx
  app/ide-desktop/lib/dashboard/src/layouts/GlobalContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/pages/dashboard/Dashboard.tsx
  app/ide-desktop/lib/dashboard/src/services/Backend.ts
  app/ide-desktop/lib/dashboard/src/text/english.json
  app/ide-desktop/lib/dashboard/src/utilities/AssetTreeNode.ts
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#9653 refr(enso-org/cloud-v2#1088): Make `Project` fields `camelCase`
  app/ide-desktop/lib/dashboard/e2e/api.ts
  app/ide-desktop/lib/dashboard/src/components/dashboard/ProjectIcon.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/ProjectNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetsTable.tsx
  app/ide-desktop/lib/dashboard/src/services/Backend.ts
  app/ide-desktop/lib/dashboard/src/services/LocalBackend.ts
  app/ide-desktop/lib/dashboard/src/utilities/object.ts
Labels: CI: Ready to merge, CI: No changelog needed

#9683 Export works without import
  distribution/lib/Standard/AWS/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Boolean.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Geo/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Google_Api/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Main.enso
  docs/syntax/imports.md
  engine/runtime-compiler/src/main/java/org/enso/compiler/phase/ImportResolverAlgorithm.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/phase/ImportResolver.scala
  engine/runtime-integration-tests/src/test/resources/Cycle_Test/src/Sub/A.enso
  engine/runtime-integration-tests/src/test/resources/Cycle_Test/src/Sub/B.enso
  engine/runtime-integration-tests/src/test/resources/Cycle_Test/src/Sub/C.enso
  engine/runtime-integration-tests/src/test/resources/Test_Fully_Qualified_Name_1/src/Main.enso
  engine/runtime-integration-tests/src/test/resources/Test_Multiple_Conflicting_Exports_1/src/F2.enso
  engine/runtime-integration-tests/src/test/resources/Test_Multiple_Conflicting_Exports_2/src/F2.enso
  engine/runtime-integration-tests/src/test/resources/Test_Multiple_Exports/src/F2.enso
  engine/runtime-integration-tests/src/test/resources/Test_Private_Modules_1/src/Main.enso
  engine/runtime-integration-tests/src/test/resources/Test_Private_Modules_4/src/Main.enso
  engine/runtime-integration-tests/src/test/resources/Test_Private_Modules_7/src/Main.enso
  engine/runtime-integration-tests/src/test/resources/Test_Type_Exports/src/Type_Exp.enso
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/semantic/ImportExportTest.scala
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Data/Boolean.enso
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  test/micro-distribution/lib/Test/Logical_Export/0.0.0-dev/src/Main.enso
Labels: CI: No changelog needed, CI: Clean build required

#9662 Integrate Cloud path resolver
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_Secret.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_User.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Existing_Enso_Asset.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Utils.enso
  std-bits/base/src/main/java/org/enso/base/enso_cloud/CloudAPI.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/CloudRequestCache.java
  test/Base_Tests/src/Network/Enso_Cloud/Secrets_Spec.enso
  tools/http-test-helper/src/main/java/org/enso/shttp/cloud_mock/AssetStore.java
  tools/http-test-helper/src/main/java/org/enso/shttp/cloud_mock/AssetsHandler.java
  tools/http-test-helper/src/main/java/org/enso/shttp/cloud_mock/CloudHandler.java
  tools/http-test-helper/src/main/java/org/enso/shttp/cloud_mock/CloudRoot.java
  tools/http-test-helper/src/main/java/org/enso/shttp/cloud_mock/DirectoriesHandler.java
  tools/http-test-helper/src/main/java/org/enso/shttp/cloud_mock/HiddenSecretsHandler.java
  tools/http-test-helper/src/main/java/org/enso/shttp/cloud_mock/PathResolver.java
  tools/http-test-helper/src/main/java/org/enso/shttp/cloud_mock/SecretsHandler.java
Labels: CI: Ready to merge, CI: No changelog needed

#9685 Fix node arguments hiding animation, clipping and dropdown styles.
  app/gui2/e2e/widgets.spec.ts
  app/gui2/package.json
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/NodeWidgetTree.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetApplication.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetText.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetTopLevelArgument.vue
  app/gui2/src/components/SizeTransition.vue
  app/gui2/src/components/widgets/DropdownWidget.vue
  app/gui2/src/providers/widgetTree.ts
  app/gui2/src/util/patching.ts
  package-lock.json
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#9696 Fix node placement
  app/gui2/src/stores/graph/index.ts
Labels: CI: Ready to merge, CI: No changelog needed

#9697 Fix spurious gui e2e dropdown test failures
  app/gui2/e2e/locate.ts
  app/gui2/e2e/widgets.spec.ts
  app/gui2/src/components/SizeTransition.vue
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#9684 On MacOS, do not assume existence of `Contents/Home` in the JDK binary path
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/components/GraalRuntime.scala
Labels: CI: Ready to merge, CI: No changelog needed

#9659 Disconnect nodes when deleted
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/NodeWidgetTree.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetPort.vue
  app/gui2/src/composables/animation.ts
  app/gui2/src/providers/widgetTree.ts
  app/gui2/src/stores/graph/graphDatabase.ts
  app/gui2/src/stores/graph/index.ts
  app/gui2/src/util/data/rect.ts
  app/gui2/src/util/data/vec2.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#9639 Experiment in lock-free module invalidation
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/command/InvalidateModulesIndexCommand.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/execution/ModuleIndexing.java
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/DeserializeLibrarySuggestionsCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/RenameProjectCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/CommandExecutionEngine.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/ExecutionState.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/JobExecutionEngine.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/AnalyzeModuleInScopeJob.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/AnalyzeModuleJob.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/UpsertVisualizationJob.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/ThreadExecutors.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java
Labels: CI: Ready to merge, CI: No changelog needed

#9677 Implement special handling of subapplications when collecting MethodCallInfo
  app/gui2/src/components/GraphEditor/widgets/WidgetFunction.vue
  app/gui2/src/providers/functionInfo.ts
  app/gui2/src/stores/graph/graphDatabase.ts
  app/gui2/src/util/ast/__tests__/callTree.test.ts
  app/gui2/src/util/callTree.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui

#9632 Refetch user session when it expires
  app/ide-desktop/lib/dashboard/src/App.tsx
  app/ide-desktop/lib/dashboard/src/authentication/cognito.mock.ts
  app/ide-desktop/lib/dashboard/src/authentication/cognito.ts
  app/ide-desktop/lib/dashboard/src/providers/SessionProvider.tsx
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#9686 Writing Cloud files
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Cloud_Caching_Settings.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Authentication.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Enso_File_Write_Strategy.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Existing_Enso_Asset.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Utils.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File_Format.enso
  std-bits/base/src/main/java/org/enso/base/enso_cloud/CacheSettings.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/CloudRequestCache.java
  test/AWS_Tests/src/Inter_Backend_File_Operations_Spec.enso
  test/AWS_Tests/src/S3_Spec.enso
  test/Base_Tests/src/Network/Enso_Cloud/Cloud_Tests_Setup.enso
  test/Base_Tests/src/Network/Enso_Cloud/Enso_Cloud_Spec.enso
  test/Base_Tests/src/Network/Enso_Cloud/Enso_File_Spec.enso
  test/Table_Tests/src/IO/Cloud_Spec.enso
  test/Table_Tests/src/IO/Main.enso
Labels: CI: Ready to merge, CI: Clean build required

#9664 Open Java modules for Snowflake setup
  distribution/bin/enso
  distribution/bin/enso.bat
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Snowflake_Details.enso
  engine/launcher/src/main/scala/org/enso/launcher/Launcher.scala
  engine/launcher/src/test/scala/org/enso/launcher/components/LauncherRunnerSpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/TestDistributionConfiguration.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectCreateHandleMissingRuntimeSpec.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/runner/JVMSettings.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/runner/Runner.scala
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#9722 Fix `Json.parse ""` edge case and add a test for it
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso
  test/Base_Tests/src/Data/Json_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9719 Implement `recursive` argument for `File.delete`
  CHANGELOG.md
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Enso_File_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Enso_File_Write_Strategy.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/File_Error.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoFile.java
  test/AWS_Tests/src/Inter_Backend_File_Operations_Spec.enso
  test/AWS_Tests/src/S3_Spec.enso
  test/Base_Tests/src/Network/Enso_Cloud/Enso_File_Spec.enso
  test/Base_Tests/src/Network/Enso_Cloud/Secrets_Spec.enso
  test/Base_Tests/src/System/File_Spec.enso
Labels: CI: Ready to merge

#9694 Add `Decimal.floor`, `.ceil`, and `.trunc`
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Decimal.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso
  std-bits/base/src/main/java/org/enso/base/numeric/Decimal_Utils.java
  test/Base_Tests/src/Data/Decimal_Spec.enso
Labels: CI: Ready to merge

#9041 Support also COMMAND_RUN and COMMAND_DEBUG actions
  tools/enso4igv/src/main/java/org/enso/tools/enso4igv/EnsoActionProvider.java
  tools/enso4igv/src/main/java/org/enso/tools/enso4igv/EnsoSbtClassPathProvider.java
Labels: CI: Ready to merge, CI: Keep up to date, CI: No changelog needed, --bug, s-downstream

#9735 Fix bundled engine after GraalVM upgrade
  lib/scala/distribution-manager/src/main/scala/org/enso/distribution/DistributionManager.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/runner/Runner.scala
Labels: CI: Ready to merge, CI: No changelog needed

#9717 Add tests for BigDecimal internal representation methods
  test/Base_Tests/src/Data/Decimal_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9739 Working through various issues from OKR / blog use.
  app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue
  distribution/lib/Standard/AWS/0.0.0-dev/src/AWS_Credential.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/AWS_Region.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Decimal.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Cloud_Caching_Settings.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Existing_Enso_Asset.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Google_Api/0.0.0-dev/src/Internal/Google_Analytics_Internal.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Aggregate_Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Aggregate_Column_Helper.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9743 Should not use auto-scoping for atom types
  engine/runtime-compiler/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/context/SuggestionBuilderTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#9691 Automatic reconnect with Language Server.
  app/gui2/e2e/componentBrowser.spec.ts
  app/gui2/e2e/graphNodeVisualization.spec.ts
  app/gui2/e2e/locate.ts
  app/gui2/mock/MockFSWrapper.vue
  app/gui2/mock/dataServer.ts
  app/gui2/mock/engine.ts
  app/gui2/package.json
  app/gui2/shared/languageServer.ts
  app/gui2/shared/languageServer/files.ts
  app/gui2/shared/languageServerTypes/suggestions.ts
  app/gui2/shared/retry.ts
  app/gui2/shared/util/__tests__/net.test.ts
  app/gui2/shared/util/data/result.ts
  app/gui2/shared/util/net.ts
  app/gui2/shared/util/net/ReconnectingWSTransport.ts
  app/gui2/shared/websocket.ts
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/components/ComponentBrowser/ai.ts
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphVisualization.vue
  app/gui2/src/components/GraphEditor/toasts.ts
  app/gui2/src/components/GraphEditor/upload.ts
  app/gui2/src/components/GraphEditor/widgets/WidgetFunction.vue
  app/gui2/src/stores/project/computedValueRegistry.ts
  app/gui2/src/stores/project/executionContext.ts
  app/gui2/src/stores/project/index.ts
  app/gui2/src/stores/project/visualizationDataRegistry.ts
  app/gui2/src/stores/suggestionDatabase/index.ts
  app/gui2/src/stores/visualization/compilerMessaging.ts
  app/gui2/src/stores/visualization/index.ts
  app/gui2/src/util/__tests__/net.test.ts
  app/gui2/src/util/ast/match.ts
  app/gui2/src/util/net.ts
  app/gui2/src/util/net/dataServer.ts
  app/gui2/ydoc-server/languageServerSession.ts
  package-lock.json
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, -gui

#9748 Fix opening templates on Local Backend
  app/ide-desktop/lib/dashboard/src/pages/dashboard/Dashboard.tsx
Labels: CI: Ready to merge, CI: No changelog needed, --bug, --regression, g-dashboard

#9734 Copy/paste improvements
  app/gui2/e2e/collapsingAndEntering.spec.ts
  app/gui2/e2e/componentBrowser.spec.ts
  app/gui2/e2e/keyboard.ts
  app/gui2/e2e/nodeClipboard.spec.ts
  app/gui2/e2e/undoRedo.spec.ts
  app/gui2/shared/ast/text.ts
  app/gui2/shared/ast/tree.ts
  app/gui2/shared/util/types.ts
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/__tests__/clipboard.test.ts
  app/gui2/src/components/GraphEditor/clipboard.ts
  app/gui2/src/stores/graph/index.ts
  app/gui2/src/util/ast/__tests__/abstract.test.ts
  app/gui2/src/util/ast/match.ts
Labels: CI: Ready to merge, CI: No changelog needed

#9752 Make excel writer work for custom types
  std-bits/table/src/main/java/org/enso/table/write/ExcelWriter.java
  test/Table_Tests/src/IO/Excel_Spec.enso
Labels: CI: No changelog needed

#9756 Add new icons
  app/gui2/src/assets/icons.svg
Labels: CI: Ready to merge, CI: No changelog needed

#9746 Allow ..Nothing to resolve to Nothing
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/UnresolvedConstructor.java
  test/Base_Tests/src/Semantic/Conversion_Spec.enso
Labels: CI: No changelog needed

#9751 In-memory suggestions
  build.sbt
  distribution/engine/THIRD-PARTY/NOTICE
  distribution/engine/THIRD-PARTY/com.typesafe.slick.slick_2.13-3.4.1/LICENSE.txt
  distribution/engine/THIRD-PARTY/licenses/CC0
  distribution/engine/THIRD-PARTY/licenses/MIT-0
  distribution/engine/THIRD-PARTY/org.reactivestreams.reactive-streams-1.0.3/NOTICES
  distribution/engine/THIRD-PARTY/org.reactivestreams.reactive-streams-1.0.4/NOTICES
  distribution/engine/THIRD-PARTY/org.xerial.sqlite-jdbc-3.42.0.0/LICENSE
  distribution/engine/THIRD-PARTY/org.xerial.sqlite-jdbc-3.42.0.0/LICENSE.zentus
  distribution/engine/THIRD-PARTY/org.xerial.sqlite-jdbc-3.42.0.0/NOTICES
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/java/org/enso/languageserver/boot/resource/RepoInitialization.java
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/ResourcesInitialization.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/search/CompletionHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SearchProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala
  engine/language-server/src/test/scala/org/enso/languageserver/boot/resource/RepoInitializationSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/search/SuggestionsHandlerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/FileManagerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/SuggestionsHandlerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/VcsManagerTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/Suggestion.scala
  lib/scala/searcher/src/bench/java/org/enso/searcher/sql/SuggestionsRepoBenchmark.java
  lib/scala/searcher/src/main/scala/org/enso/searcher/SuggestionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/memory/InMemorySuggestionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/memory/SuggestinRowUniqueIndex.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/InvalidSchemaVersion.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlDatabase.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/SqlSuggestionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/sql/Tables.scala
  lib/scala/searcher/src/test/scala/org/enso/searcher/sql/SuggestionsRepoTest.scala
  tools/legal-review/engine/com.typesafe.slick.slick_2.13-3.4.1/custom-license
  tools/legal-review/engine/com.typesafe.slick.slick_2.13-3.4.1/files-add/LICENSE.txt
  tools/legal-review/engine/org.reactivestreams.reactive-streams-1.0.3/copyright-keep-context
  tools/legal-review/engine/org.reactivestreams.reactive-streams-1.0.4/copyright-add
  tools/legal-review/engine/org.xerial.sqlite-jdbc-3.42.0.0/copyright-ignore
  tools/legal-review/engine/org.xerial.sqlite-jdbc-3.42.0.0/copyright-keep
  tools/legal-review/engine/org.xerial.sqlite-jdbc-3.42.0.0/custom-license
  tools/legal-review/engine/org.xerial.sqlite-jdbc-3.42.0.0/files-keep
  tools/legal-review/engine/report-state
Labels: CI: Ready to merge, CI: No changelog needed

#9716 `Integer.to_decimal` and `Float.to_decimal`
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso
  test/Base_Tests/src/Data/Decimal_Spec.enso
  test/Base_Tests/src/Semantic/Meta_Spec.enso
Labels: CI: Ready to merge

#9718 Change ‘decimal’ to ‘float’ in Numbers_Spec
  test/Base_Tests/src/Data/Numbers_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#9767 Special treatment for ..True and ..False
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/UnresolvedConstructor.java
  test/Base_Tests/src/Semantic/Conversion_Spec.enso
Labels: CI: No changelog needed

#9742 Make errors propagate out of each
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/List.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Map.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Pair.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Expand_Objects_Helpers.enso
  test/Base_Tests/src/Data/List_Spec.enso
  test/Base_Tests/src/Data/Pair_Spec.enso
  test/Base_Tests/src/Data/Text_Spec.enso
  test/Base_Tests/src/Data/Vector_Spec.enso
  test/Base_Tests/src/Semantic/Error_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Date_Time_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9771 Selection panel
  app/gui2/e2e/collapsingAndEntering.spec.ts
  app/gui2/e2e/selectingNodes.spec.ts
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/__tests__/collapsing.test.ts
  app/gui2/src/components/GraphEditor/collapsing.ts
  app/gui2/src/components/GraphEditor/toasts.ts
  app/gui2/src/components/SelectionMenu.vue
  app/gui2/src/components/TopBar.vue
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, -gui

#9737 Display argument placeholders for autoscoped constructors
  app/gui2/e2e/collapsingAndEntering.spec.ts
  app/gui2/e2e/componentBrowser.spec.ts
  app/gui2/e2e/edgeRendering.spec.ts
  app/gui2/e2e/widgets.spec.ts
  app/gui2/eslint.config.js
  app/gui2/mock/engine.ts
  app/gui2/playwright.config.ts
  app/gui2/shared/ast/parse.ts
  app/gui2/shared/ast/token.ts
  app/gui2/shared/ast/tree.ts
  app/gui2/src/providers/widgetRegistry.ts
  app/gui2/src/stores/graph/index.ts
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, -gui

#9759 `Excel_Workbook.read_many`
  CHANGELOG.md
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Enso_File_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Delimited/Delimited_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Workbook.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Headers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Delimited_Reader.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Delimited_Writer.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Excel_Reader.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Excel_Section.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  std-bits/table/src/main/java/org/enso/table/error/InvalidLocationException.java
  std-bits/table/src/main/java/org/enso/table/read/ExcelReader.java
  std-bits/table/src/main/java/org/enso/table/write/ExcelWriter.java
  test/Table_Tests/src/IO/Excel_Spec.enso
Labels: CI: Ready to merge

#9773 Use InteropLibrary when accepting String values
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/ForeignMethodInvokeTest.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
Labels: CI: Ready to merge, CI: Keep up to date, CI: No changelog needed, CI: Clean build required

#9755 Restore state after reconnecting
  app/gui2/mock/engine.ts
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/composables/stackNavigator.ts
  app/gui2/src/stores/project/executionContext.ts
  app/gui2/src/util/data/array.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#9740 Make conversion of double to BigDecimal exact
  .vscode/settings.json
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Decimal.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Extensions.enso
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/ValuesGenerator.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsSimpleNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/HashCodeNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/utils/BigIntegerOps.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/number/EnsoBigInteger.java
  std-bits/base/src/main/java/org/enso/base/numeric/Decimal_Utils.java
  test/Base_Tests/src/Data/Decimal_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Union_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/In_Memory/Integer_Overflow_Spec.enso
Labels: CI: Ready to merge, CI: Keep up to date, CI: No changelog needed, CI: Clean build required

#9779 Google Analytics events for opening and closing the app, and opening and closing projects
  .envrc
  .gitignore
  app/ide-desktop/lib/common/package.json
  app/ide-desktop/lib/common/src/appConfig.js
  app/ide-desktop/lib/common/src/detect.ts
  app/ide-desktop/lib/common/src/gtag.ts
  app/ide-desktop/lib/common/src/load.ts
  app/ide-desktop/lib/dashboard/404.html
  app/ide-desktop/lib/dashboard/index.html
  app/ide-desktop/lib/dashboard/src/components/dashboard/KeyboardShortcut.tsx
  app/ide-desktop/lib/dashboard/src/hooks/gtagHooks.ts
  app/ide-desktop/lib/dashboard/src/layouts/Chat.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Editor.tsx
  app/ide-desktop/lib/dashboard/src/pages/subscribe/Subscribe.tsx
  app/ide-desktop/lib/dashboard/src/providers/AuthProvider.tsx
  app/ide-desktop/lib/dashboard/src/utilities/load.ts
  app/ide-desktop/lib/types/globals.d.ts
  flake.lock
  flake.nix
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#9781 Node creation improvements
  app/gui2/e2e/componentBrowser.spec.ts
  app/gui2/e2e/locate.ts
  app/gui2/e2e/nodeClipboard.spec.ts
  app/gui2/shared/util/types.ts
  app/gui2/src/components/ComponentBrowser/__tests__/placement.test.ts
  app/gui2/src/components/ComponentBrowser/placement.ts
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/clipboard.ts
  app/gui2/src/components/GraphEditor/nodeCreation.ts
  app/gui2/src/components/SmallPlusButton.vue
  app/gui2/src/composables/nodeCreation.ts
  app/gui2/src/providers/graphNodeCreation.ts
  app/gui2/src/stores/graph/index.ts
  app/gui2/src/util/data/array.ts
  app/gui2/src/util/data/rect.ts
  app/gui2/src/util/data/vec2.ts
Labels: CI: No changelog needed

#9754 Convert `Vector.new_builder` to `Vector.build` in `Standard.Base`
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Filter_Condition.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Index_Sub_Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/List.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Statistics.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Text_Sub_Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Duration.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Period.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/XML.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Array_Like_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Time/Format/Analyzer.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Time/Format/Parser.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/File_Permissions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File_By_Line.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File_Format_Metadata.enso
  test/Base_Tests/src/Data/Vector_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Select_Columns_Spec.enso
Labels: CI: No changelog needed

#9750 Writing to Data Links
  CHANGELOG.md
  distribution/lib/Standard/AWS/0.0.0-dev/src/AWS_Credential.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/Internal/Data_Link_Helpers.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3_Data_Link.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Data_Link.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Data_Link_Capabilities.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Data_Link_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Enso_File_Data_Link.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Data_Read_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Internal/HTTP_Fetch_Data_Link.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Response_Body.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/Generic/File_Write_Strategy.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/Generic/Writable_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/Write_Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/Input_Stream.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Data_Link/Postgres_Data_Link.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Image.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Image_File_Format.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Snowflake_Data_Link.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Delimited_Writer.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Excel_Writer.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Extensions.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Test.enso
  test/AWS_Tests/src/Inter_Backend_File_Operations_Spec.enso
  test/AWS_Tests/src/S3_Spec.enso
  test/Base_Tests/src/Network/Enso_Cloud/Cloud_Data_Link_Spec.enso
  test/Base_Tests/src/Network/Enso_Cloud/Cloud_Tests_Setup.enso
  test/Base_Tests/src/Network/Enso_Cloud/Enso_File_Spec.enso
  test/Base_Tests/src/Network/Enso_Cloud/Secrets_Spec.enso
  test/Base_Tests/src/Network/Http/Http_Data_Link_Spec.enso
  test/Image_Tests/package.yaml
  test/Image_Tests/src/Image_Read_Write_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
Labels: CI: Ready to merge

#9787 Remove special-cased injected Google Analytics tag
  .github/workflows/gui.yml
  .github/workflows/release.yml
  app/ide-desktop/lib/common/src/appConfig.js
  build/build/src/ci_gen/job.rs
  build/build/src/ide/web.rs
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#9793 Improve Table Viz handling of Numbers
  app/gui2/src/components/visualizations/TableVisualization.vue
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9796 Print pending groups in-line and include their reason, also add progress bar to the runner
  distribution/lib/Standard/Test/0.0.0-dev/src/Helpers.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Suite.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Test_Reporter.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9491 Change heuristics for showing missing `.env` error
  app/ide-desktop/lib/common/src/appConfig.d.ts
  app/ide-desktop/lib/common/src/appConfig.js
  app/ide-desktop/lib/dashboard/playwright.config.ts
  app/ide-desktop/lib/dashboard/vite.test.config.ts
  app/ide-desktop/lib/dashboard/vitest.config.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#9805 Compile-time `shapeless` in `runtime-compiler`
  build.sbt
Labels: CI: Ready to merge, CI: No changelog needed

#9775 Set of improvements: selection "committed" state and "add new compnent" button hitbox fix.
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/SmallPlusButton.vue
  app/gui2/src/components/VisualizationContainer.vue
  app/gui2/src/composables/selection.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#9692 Atom constructors can be private
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso
  docs/semantics/encapsulation.md
  engine/polyglot-api/src/main/scala/org/enso/polyglot/Function.scala
  engine/runtime-compiler/src/main/java/org/enso/compiler/dump/GraphVizNode.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/PrivateConstructorAnalysis.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/PrivateSymbolsAnalysis.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/Passes.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/data/BindingsMap.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/BindingAnalysis.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/Patterns.scala
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/ErrorCompilerTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/PrivateAccessTest.java
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/PassesTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/analyse/BindingAnalysisTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/analyse/PrivateModifierTest.scala
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbContext.java
  engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Pattern.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Resolution.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Syntax.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/module/scope/Definition.scala
  engine/runtime-parser/src/test/java/org/enso/compiler/core/EnsoParserTest.java
  engine/runtime-suggestions/src/main/scala/org/enso/compiler/suggestions/SuggestionBuilder.scala
  engine/runtime/src/main/java/org/enso/interpreter/node/EnsoRootNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/argument/ReadArgumentCheckNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/dispatch/InvokeFunctionNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/function/CreateFunctionNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/Builtin.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/PrivateAccess.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/AtomWithAHoleNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/InstrumentorEvalNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/literal/LiteralNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Error.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/argument/CallArgumentInfo.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/Function.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/FunctionSchema.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Type.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/Atom.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/AtomConstructor.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/GetFieldNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/QualifiedAccessorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java
  engine/runtime/src/main/java/org/enso/interpreter/util/ScalaConversions.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/RuntimeStubsGenerator.scala
  lib/rust/parser/debug/tests/parse.rs
  lib/rust/parser/src/macros/built_in.rs
  lib/rust/parser/src/source/code.rs
  test/Base_Tests/package.yaml
  test/Base_Tests/src/Main.enso
  test/Base_Tests/src/Semantic/Private_Spec.enso
  test/Helpers/README.md
  test/Helpers/package.yaml
  test/Helpers/src/Main.enso
  test/Table_Tests/src/Helpers/Auto_Constructor_Instrumentation_Spec.enso
Labels: CI: Clean build required

#9806 Compile parser using musl
  build.sbt
  project/Cargo.scala
Labels: CI: Ready to merge, CI: No changelog needed

#9788 Dragging edges
  app/gui2/e2e/edgeInteractions.spec.ts
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphEdge.vue
  app/gui2/src/components/GraphEditor/GraphEdges.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/GraphNodes.vue
  app/gui2/src/providers/interactionHandler.ts
  app/gui2/src/providers/widgetRegistry/__tests__/editHandler.test.ts
  app/gui2/src/stores/graph/index.ts
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, -gui

#9799 Make Table.should_equal and Column.should_equal consider NaN equal
  std-bits/table/src/main/java/org/enso/table/data/column/builder/InferredBuilder.java
  test/Table_Tests/src/In_Memory/Column_Format_Spec.enso
  test/Table_Tests/src/In_Memory/Split_Tokenize_Spec.enso
  test/Table_Tests/src/Main.enso
  test/Table_Tests/src/Util.enso
  test/Table_Tests/src/Util_Spec.enso
Labels: CI: No changelog needed

#9670 Update docs following GUI1 removal
  .github/PULL_REQUEST_TEMPLATE.md
  docs/profiler/profiling.md
Labels: CI: Ready to merge, CI: No changelog needed

#9784 Move node type to visualization container
  app/gui2/e2e/typesOnNodeHover.spec.ts
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/GraphVisualization.vue
  app/gui2/src/components/VisualizationContainer.vue
  app/gui2/src/providers/visualizationConfig.ts
Labels: CI: No changelog needed

#9821 Prepare for Cloud Environment variable name change
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_File.enso
  test/Base_Tests/src/Network/Enso_Cloud/Enso_File_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9823 Handle URL encoding automatically in query string.
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Of_Day.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/URI.enso
  std-bits/base/src/main/java/org/enso/base/net/URITransformer.java
  test/Base_Tests/src/Network/URI_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required
