Repository enso-org/enso, pull requests merged in 2024-06, with the labels that each got.

#10143 Directly allocate warnings asVectorEnsoObjects
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Warning.enso
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/VectorBenchmarks.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/ArrayBuilder.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/ArrayLikeHelpers.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/Vector.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/Warning.java
Labels: CI: No changelog needed, CI: Clean build required

#10117 Exposing just a single Persistance.Reference abstraction
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Function.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/module/scope/definition/Method.scala
  engine/runtime-parser/src/test/java/org/enso/compiler/core/IrPersistanceTest.java
  lib/java/persistance-dsl/src/main/java/org/enso/persist/impl/PersistableProcessor.java
  lib/java/persistance/src/main/java/org/enso/persist/PerBufferReference.java
  lib/java/persistance/src/main/java/org/enso/persist/PerGenerator.java
  lib/java/persistance/src/main/java/org/enso/persist/PerInputImpl.java
  lib/java/persistance/src/main/java/org/enso/persist/PerMap.java
  lib/java/persistance/src/main/java/org/enso/persist/PerMemoryReference.java
  lib/java/persistance/src/main/java/org/enso/persist/PerReferencePersistance.java
  lib/java/persistance/src/main/java/org/enso/persist/Persistance.java
  lib/java/persistance/src/test/java/org/enso/persist/PersistanceTest.java
  lib/java/persistance/src/test/java/org/enso/persist/ReferenceAsInlineTest.java
  lib/java/persistance/src/test/java/org/enso/persist/ReferenceAsObjectTest.java
Labels: CI: No changelog needed

#10107 Record interaction between GUI and LS
  engine/language-server/src/main/java/org/enso/languageserver/runtime/events/RuntimeEventsMonitor.java
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/ProfilingConfig.scala
  engine/language-server/src/main/scala/org/enso/languageserver/http/server/BinaryWebSocketServer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/profiling/EventsMonitorActor.scala
  engine/language-server/src/main/scala/org/enso/languageserver/profiling/EventsMonitorProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/profiling/ProfilingManager.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/RuntimeConnector.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/ProfilingManagerTest.scala
  lib/scala/json-rpc-server/src/main/scala/org/enso/jsonrpc/JsonRpcServer.scala
  lib/scala/profiling-utils/src/main/java/org/enso/profiling/events/EventsMonitor.java
  lib/scala/profiling-utils/src/main/java/org/enso/profiling/events/NoopEventsMonitor.java
Labels: CI: Ready to merge, CI: No changelog needed

#10153 Fetch EULA in background if a user accepted it before
  app/ide-desktop/lib/dashboard/src/modals/TermsOfServiceModal.tsx
Labels: CI: No changelog needed, --bug, g-dashboard

#10158 Fix visualization z-indexes
  app/gui2/src/components/GraphEditor/GraphVisualization.vue
Labels: CI: Ready to merge, CI: No changelog needed

#10161 Bug fix for read by line.
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File_By_Line.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10079 Add `no_warning_propagation` flag to `Vector.build` and `Builder.new`
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/VectorBenchmarks.java
  test/Base_Tests/src/Data/Vector_Spec.enso
  test/Benchmarks/src/Main.enso
  test/Benchmarks/src/Vector/Build.enso
Labels: CI: No changelog needed

#10152 Add Columns_To_Add type to move away from Integer | Nothing
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Columns_To_Add.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Fan_Out.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Split_Tokenize.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  test/Table_Tests/src/In_Memory/Fan_Out_Spec.enso
  test/Table_Tests/src/In_Memory/Split_Tokenize_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10159 Add select/remove column by type
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Value_Type.enso
  test/Table_Tests/src/Common_Table_Operations/Select_Columns_Spec.enso
  test/Table_Tests/src/Internal/Widget_Helpers_Spec.enso
Labels: CI: No changelog needed

#10160 Implement the ydoc js bundle test
  build.sbt
  lib/java/ydoc-server/src/main/java/org/enso/ydoc/Main.java
  lib/java/ydoc-server/src/test/java/org/enso/ydoc/YdocTest.java
  lib/java/ydoc-server/src/test/java/org/enso/ydoc/jsonrpc/JsonRpcRequest.java
  lib/java/ydoc-server/src/test/java/org/enso/ydoc/jsonrpc/JsonRpcResponse.java
  lib/java/ydoc-server/src/test/java/org/enso/ydoc/jsonrpc/model/ContentRoot.java
  lib/java/ydoc-server/src/test/java/org/enso/ydoc/jsonrpc/model/FilePath.java
  lib/java/ydoc-server/src/test/java/org/enso/ydoc/jsonrpc/model/FileSystemObject.java
  lib/java/ydoc-server/src/test/java/org/enso/ydoc/jsonrpc/model/WriteCapability.java
  lib/java/ydoc-server/src/test/java/org/enso/ydoc/jsonrpc/model/result/FileListResult.java
  lib/java/ydoc-server/src/test/java/org/enso/ydoc/jsonrpc/model/result/InitProtocolConnectionResult.java
  lib/java/ydoc-server/src/test/java/org/enso/ydoc/jsonrpc/model/result/Result.java
  lib/java/ydoc-server/src/test/java/org/enso/ydoc/jsonrpc/model/result/TextOpenFileResult.java
Labels: CI: Ready to merge, CI: No changelog needed

#9950 `BigDecimalBuilder` and arithmetic operations.
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Decimal.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Storage.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Value_Type_Helpers.enso
  std-bits/base/src/main/java/org/enso/base/polyglot/NumericConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/BigDecimalBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/Builder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/DateBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/DateTimeBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/InferredBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/TimeOfDayBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/StorageConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/arithmetic/AddOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/arithmetic/BigDecimalDivideOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/arithmetic/ModOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/arithmetic/MulOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/arithmetic/NumericBinaryOpDefinition.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/arithmetic/NumericBinaryOpImplementation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/arithmetic/NumericBinaryOpReturningBigDecimal.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/arithmetic/NumericBinaryOpReturningDouble.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/arithmetic/SubOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/helpers/BigDecimalArrayAdapter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/helpers/DoubleArrayAdapter.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/BigDecimalStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/type/BigDecimalType.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/type/StorageType.java
  test/Base_Tests/src/Data/Decimal_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/In_Memory/Column_Spec.enso
Labels: CI: Clean build required

#10164 What's the name of my method?
  distribution/bin/enso
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/InsightForEnsoTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/RootNamesTest.java
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
Labels: -tooling, CI: Ready to merge, CI: No changelog needed, -compiler

#10177 Don't hide visual tooltip when mouse goes from target to tooltip
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Text/Text.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Text/useVisualTooltip.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Tooltip/Tooltip.tsx
  app/ide-desktop/lib/dashboard/src/components/aria.tsx
  app/ide-desktop/lib/dashboard/src/tailwind.css
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#10176 Improve Dialog behavior
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/Close.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/Dialog.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/DialogProvider.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/DialogStackProvider.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/DialogTrigger.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/Popover.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/index.ts
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/types.ts
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/utilities.ts
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/variants.ts
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Tooltip/Tooltip.tsx
  app/ide-desktop/lib/dashboard/src/components/Root.tsx
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#10178 Radio and RadioGroup components
  app/ide-desktop/eslint.config.js
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Button/Button.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Button/ButtonGroup.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Button/CloseButton.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Button/CopyButton.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Form/Form.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Form/components/Field.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Form/components/FormError.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Form/components/Reset.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Form/components/Submit.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Form/components/index.ts
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Form/components/types.ts
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Form/components/useField.ts
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Form/components/useFormContext.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Form/components/useFormSchema.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Form/types.ts
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Radio/Radio.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Radio/RadioGroup.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Radio/RadioGroupContext.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Radio/index.ts
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Text/Text.tsx
  app/ide-desktop/lib/dashboard/src/utilities/__tests__/error.test.ts
  app/ide-desktop/lib/dashboard/src/utilities/error.ts
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#10149 Remove workaround for #8937 after it has been fixed
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Response.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Response_Body.enso
Labels: CI: Ready to merge, CI: No changelog needed

#9914 Extract mutable builder from `ModuleScope`
  distribution/lib/Standard/Base/0.0.0-dev/src/Meta.enso
  engine/polyglot-api/src/test/scala/org/enso/polyglot/ModuleManagementTest.scala
  engine/runtime-benchmarks/src/main/java/org/enso/compiler/benchmarks/inline/InlineContextUtils.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/context/CompilerContext.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/UpsertVisualizationJob.scala
  engine/runtime-parser/src/main/java/org/enso/compiler/core/IR.java
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/CallArgument.scala
  engine/runtime/src/main/java/org/enso/interpreter/EnsoLanguage.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodImportResolver.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/dispatch/InvokeFunctionNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/Builtin.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/CreateUnresolvedSymbolNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/FindTypeByFqnNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/GetUnresolvedSymbolScopeNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/debug/EvalNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Type.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/AtomConstructor.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ImportExportScope.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/TruffleCompilerModuleScopeBuilder.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/RuntimeStubsGenerator.scala
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#10188 Small refinements across dashboard components
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Alert/Alert.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/Popover.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/variants.ts
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Form/components/Field.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Form/components/FormError.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Form/components/Submit.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Separator.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Text/Text.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Text/TextProvider.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Tooltip/index.ts
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/index.ts
  app/ide-desktop/lib/dashboard/src/components/SvgMask.tsx
  app/ide-desktop/lib/dashboard/src/components/UnstyledButton.tsx
  app/ide-desktop/lib/dashboard/src/modals/TermsOfServiceModal.tsx
  app/ide-desktop/lib/dashboard/src/text/english.json
Labels: CI: Ready to merge, CI: No changelog needed, x-chore, g-dashboard

#10187 Execute foreign function and check autoscoped constructor result
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/node/EnsoRootNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeCallableNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/UnresolvedConstructor.java
  test/Base_Tests/src/Data/Polyglot_Spec.enso
  test/Base_Tests/src/Semantic/Conversion_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10191 Refactor Stripe integration
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Form/Form.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Form/components/Field.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Form/components/Submit.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Form/types.ts
  app/ide-desktop/lib/dashboard/src/modals/AddPaymentMethodModal.tsx
  app/ide-desktop/lib/dashboard/src/pages/subscribe/Subscribe/Subscribe.tsx
  app/ide-desktop/lib/dashboard/src/pages/subscribe/Subscribe/components/SubscribeForm.tsx
  app/ide-desktop/lib/dashboard/src/pages/subscribe/Subscribe/components/index.ts
  app/ide-desktop/lib/dashboard/src/pages/subscribe/Subscribe/getComponentForPlan.tsx
  app/ide-desktop/lib/dashboard/src/providers/StripeProvider.tsx
  app/ide-desktop/lib/dashboard/src/text/english.json
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#10193 Updating IGV documentation
  tools/enso4igv/IGV.md
  tools/enso4igv/pom.xml
  tools/enso4igv/src/main/java/org/enso/tools/enso4igv/EnsoDataObject.java
  tools/enso4igv/src/main/java/org/enso/tools/enso4igv/Installer.java
  tools/enso4igv/src/main/nbm/manifest.mf
  tools/enso4igv/src/main/resources/org/enso/tools/enso4igv/layer.xml
Labels: -tooling, CI: Ready to merge, CI: No changelog needed, -compiler

#10179 Moving nodes or camera with arrows
  CHANGELOG.md
  app/gui2/e2e/graphNavigator.spec.ts
  app/gui2/e2e/selectingNodes.spec.ts
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphNodes.vue
  app/gui2/src/composables/__tests__/events.test.ts
  app/gui2/src/composables/events.ts
  app/gui2/src/composables/navigator.ts
  app/gui2/stories/SelectionBrushWrapper.vue
Labels: CI: Ready to merge, x-new-feature, -gui

#10172 Implement new design for tooltips in GUI
  app/gui2/e2e/collapsingAndEntering.spec.ts
  app/gui2/e2e/locate.ts
  app/gui2/src/App.vue
  app/gui2/src/components/ColorRing.vue
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/components/ComponentBrowser/ComponentEditor.vue
  app/gui2/src/components/DocumentationPanel/DocsBreadcrumbs.vue
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/GraphNodeSelection.vue
  app/gui2/src/components/GraphEditor/NodeWidgetTree.vue
  app/gui2/src/components/MenuButton.vue
  app/gui2/src/components/ScrollBar.vue
  app/gui2/src/components/SvgButton.vue
  app/gui2/src/components/TooltipDisplayer.vue
  app/gui2/src/components/TooltipTrigger.vue
  app/gui2/src/composables/syncLocalStorage.ts
  app/gui2/src/providers/tooltipState.ts
  app/gui2/src/util/data/iterable.ts
  app/gui2/src/util/patching.ts
  app/gui2/src/util/reactivity.ts
  app/gui2/vite.config.ts
  app/ide-desktop/lib/dashboard/src/services/RemoteBackend.ts
  app/ide-desktop/lib/project-manager-shim/src/projectManagerShimMiddleware.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#10199 Refactors of Dialogs, Popover styles, button sizes and Text
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Button/Button.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Button/ButtonGroup.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/Dialog.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/Popover.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/types.ts
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Inputs/ResizableInput/ResizableContentEditableInput.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Inputs/ResizableInput/variants.ts
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Text/Text.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Tooltip/Tooltip.tsx
  app/ide-desktop/lib/dashboard/src/components/ErrorBoundary.tsx
  app/ide-desktop/lib/dashboard/src/components/Page.tsx
  app/ide-desktop/lib/dashboard/src/components/Result.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Chat.tsx
  app/ide-desktop/lib/dashboard/src/layouts/UserBar.tsx
  app/ide-desktop/lib/dashboard/src/pages/dashboard/Dashboard.tsx
  app/ide-desktop/lib/dashboard/src/utilities/error.ts
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#10200 Add declarative api to invalidate queries in mutations
  app/ide-desktop/eslint.config.js
  app/ide-desktop/lib/dashboard/src/App.tsx
  app/ide-desktop/lib/dashboard/src/index.tsx
  app/ide-desktop/lib/dashboard/src/modals/SetOrganizationNameModal.tsx
  app/ide-desktop/lib/dashboard/src/reactQueryClient.ts
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#10201 Make Settings Sidebar a bit dimmer
  app/ide-desktop/lib/dashboard/src/components/styled/SidebarTabButton.tsx
  app/ide-desktop/lib/dashboard/src/layouts/SettingsSidebar.tsx
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#10156 ydoc-server is a separate module
  build.sbt
  docs/sbt-cheatsheet.md
  engine/interpreter-dsl-test/src/test/java/org/enso/interpreter/dsl/test/ThrowBuiltinNode.java
  engine/interpreter-dsl-test/src/test/java/org/enso/interpreter/dsl/test/ThrowableCatchTest.java
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/Suggestion.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/Graph.scala
  engine/runtime-fat-jar/src/main/java/module-info.java
  engine/runtime-parser/src/main/java/org/enso/compiler/core/IR.java
  engine/runtime-parser/src/main/scala/org/enso/compiler/debug/Debug.scala
  engine/runtime/src/main/java/org/enso/ClassLoaderConstants.java
  engine/runtime/src/main/java/org/enso/EngineRunnerBootLoader.java
  engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java
  engine/runtime/src/main/java/org/enso/interpreter/caches/CacheUtils.java
  engine/runtime/src/main/java/org/enso/interpreter/caches/ImportExportCache.java
  engine/runtime/src/main/java/org/enso/interpreter/caches/ModuleCache.java
  engine/runtime/src/main/java/org/enso/interpreter/caches/PersistUtils.java
  engine/runtime/src/main/java/org/enso/interpreter/caches/SuggestionsCache.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/HostClassLoader.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java
  lib/java/ydoc-server/src/main/java/module-info.java
  lib/scala/profiling-utils/src/main/java/module-info.java
  lib/scala/syntax/README.md
  lib/scala/syntax/definition/src/main/scala/org/enso/data/Compare.scala
  lib/scala/syntax/definition/src/main/scala/org/enso/data/Index.scala
  lib/scala/syntax/definition/src/main/scala/org/enso/data/Size.scala
  lib/scala/syntax/definition/src/main/scala/org/enso/data/Span.scala
  lib/scala/syntax/definition/src/main/scala/org/enso/syntax/text/package.scala
  project/JPMSUtils.scala
Labels: CI: No changelog needed, CI: Clean build required

#10208 Fix button sizes
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Button/Button.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/Popover.tsx
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#10209 Remove Chat Placeholder when chat is hidden
  app/ide-desktop/lib/dashboard/src/components/Page.tsx
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#10204 Fix refactor/renameProject with names containing unsupported characters
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/RenameProjectCmd.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#10210 Expose Ydoc port in Docker container
  tools/ci/docker/Dockerfile
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#10183 Add By_Type option to more components
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Replace_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Conversion_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Replace_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Select_Columns_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Format_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
  test/Table_Tests/src/In_Memory/Text_Cleanse_Spec.enso
Labels: CI: No changelog needed

#10221 Fix enso redirect URL
  app/ide-desktop/.example.env
  app/ide-desktop/lib/common/src/appConfig.js
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#10142 Sort rational numbers and primes first benchmarks
  test/Benchmarks/src/Vector/Distinct.enso
  test/Benchmarks/src/Vector/Sort.enso
  test/Benchmarks/src/Vector/Utils.enso
Labels: CI: Ready to merge, CI: Keep up to date, CI: No changelog needed, CI: Clean build required

#10173 Adding type annotations and enabling auto-scoping
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Filter_Condition.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Index_Sub_Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Case_Sensitivity.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Widget_Helpers.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Aggregate_Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Data_Formatter.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Aggregate_Column_Helper.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Java_Exports.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Join_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Ref.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Join_Condition.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Simple_Expression.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Sort_Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/UnresolvedConstructor.java
  test/Base_Tests/src/Data/Text_Spec.enso
  test/Base_Tests/src/Data/Vector_Spec.enso
  test/Base_Tests/src/Runtime/Missing_Required_Arguments_Spec.enso
  test/Base_Tests/src/Widget_Helpers_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Aggregate_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Derived_Columns_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Filter_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Join_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Order_By_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Take_Drop_Spec.enso
  test/Table_Tests/src/Formatting/Data_Formatter_Spec.enso
  test/Table_Tests/src/Formatting/Parse_Values_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10101 Fixes to Persistance
  build.sbt
  engine/runtime-parser/src/main/java/org/enso/compiler/core/ir/IrPersistance.java
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Function.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/module/scope/definition/Method.scala
  engine/runtime-parser/src/test/java/org/enso/compiler/core/IrPersistanceTest.java
  lib/java/persistance-dsl/src/main/java/org/enso/persist/impl/PersistableProcessor.java
  lib/java/persistance/src/main/java/org/enso/persist/PerBufferReference.java
  lib/java/persistance/src/main/java/org/enso/persist/PerGenerator.java
  lib/java/persistance/src/main/java/org/enso/persist/PerInputImpl.java
  lib/java/persistance/src/main/java/org/enso/persist/PerMap.java
  lib/java/persistance/src/main/java/org/enso/persist/PerMemoryReference.java
  lib/java/persistance/src/main/java/org/enso/persist/PerReferencePersistance.java
  lib/java/persistance/src/main/java/org/enso/persist/Persistance.java
  lib/java/persistance/src/test/java/org/enso/persist/PersistanceTest.java
  lib/java/persistance/src/test/java/org/enso/persist/ReferenceAsInlineTest.java
  lib/java/persistance/src/test/java/org/enso/persist/ReferenceAsObjectTest.java
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#10222 Publish Persistance API+Javadoc to local m2 repository
  .github/workflows/enso4igv.yml
  build.sbt
  lib/java/persistance/src/main/java/org/enso/persist/Persistable.java
  lib/java/persistance/src/main/java/org/enso/persist/package-info.java
Labels: CI: No changelog needed

#10205 Show images in documentation
  CHANGELOG.md
  app/gui2/e2e/locate.ts
  app/gui2/e2e/rightDock.spec.ts
  app/gui2/mock/MockFSWrapper.vue
  app/gui2/package.json
  app/gui2/src/components/DockPanel.vue
  app/gui2/src/components/DocumentationEditor.vue
  app/gui2/src/components/ExtendedMenu.vue
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphNodeComment.vue
  app/gui2/src/components/GraphEditor/upload.ts
  app/gui2/src/components/MarkdownEditor.vue
  app/gui2/src/components/MarkdownEditor/BlockTypeMenu.vue
  app/gui2/src/components/MarkdownEditor/FloatingSelectionMenu.vue
  app/gui2/src/components/MarkdownEditor/FormatPropertiesBar.vue
  app/gui2/src/components/MarkdownEditor/FormattingToolbar.vue
  app/gui2/src/components/MarkdownEditor/ImagePlugin/LexicalImage.vue
  app/gui2/src/components/MarkdownEditor/ImagePlugin/imageNode.ts
  app/gui2/src/components/MarkdownEditor/ImagePlugin/index.ts
  app/gui2/src/components/MarkdownEditor/MarkdownEditorImpl.vue
  app/gui2/src/components/MarkdownEditor/SelectionFormattingToolbar.vue
  app/gui2/src/components/MarkdownEditor/formatting.ts
  app/gui2/src/components/MarkdownEditor/imageUrlTransformer.ts
  app/gui2/src/components/MarkdownEditor/listPlugin.ts
  app/gui2/src/components/MarkdownEditor/markdown.ts
  app/gui2/src/components/MarkdownEditor/theme.css
  app/gui2/src/components/PlainTextEditor.vue
  app/gui2/src/components/SelectionDropdown.vue
  app/gui2/src/components/lexical/LexicalDecorators.vue
  app/gui2/src/components/lexical/MarkdownEditorImpl.vue
  app/gui2/src/components/lexical/SelectionFormattingToolbar.vue
  app/gui2/src/components/lexical/formatting.ts
  app/gui2/src/components/lexical/index.ts
  app/gui2/src/components/lexical/sync.ts
  app/gui2/src/composables/astDocumentation.ts
  app/gui2/src/stores/graph/index.ts
  app/gui2/src/stores/project/index.ts
  app/gui2/src/stores/visualization/index.ts
  app/gui2/src/util/reactivity.ts
  package-lock.json
Labels: CI: Ready to merge

#10218 Fix auth refresh in certain edge cases
  app/ide-desktop/lib/dashboard/src/components/StatelessSpinner.tsx
  app/ide-desktop/lib/dashboard/src/providers/AuthProvider.tsx
  app/ide-desktop/lib/dashboard/src/providers/SessionProvider.tsx
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#10192 Fix Meta.enso_project
  distribution/lib/Standard/Base/0.0.0-dev/src/Meta/Enso_Project.enso
  distribution/lib/Standard/Examples/0.0.0-dev/src/Main.enso
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/meta/EnsoProjectTest.java
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/semantic/EnsoProjectTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EnsoProjectNode.java
  test/Base_Tests/src/Semantic/Meta_Location_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#10194 Copy paste multiple nodes
  CHANGELOG.md
  app/gui2/e2e/nodeClipboard.spec.ts
  app/gui2/src/components/GraphEditor/clipboard.ts
  app/gui2/src/composables/nodeCreation.ts
  app/gui2/src/stores/graph/graphDatabase.ts
  app/gui2/src/stores/graph/index.ts
  app/gui2/src/util/ast/__tests__/abstract.test.ts
  app/gui2/src/util/ast/abstract.ts
Labels: CI: Ready to merge, -gui

#10230 Improve styling system for some components
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Button/Button.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/index.ts
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/variants.ts
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Text/Text.tsx
Labels: CI: No changelog needed, g-dashboard

#10242 Add icons
  app/gui2/src/assets/icons.svg
Labels: CI: Ready to merge, CI: No changelog needed

#10150 Implement and benchmark `ArrowOperationPlus` node
  engine/runtime-language-arrow/src/main/java/org/enso/interpreter/arrow/ArrowParser.java
  engine/runtime-language-arrow/src/main/java/org/enso/interpreter/arrow/node/ArrowCastFixedSizeNode.java
  engine/runtime-language-arrow/src/main/java/org/enso/interpreter/arrow/node/ArrowEvalNode.java
  engine/runtime-language-arrow/src/main/java/org/enso/interpreter/arrow/node/ArrowFixedSizeNode.java
  engine/runtime-language-arrow/src/main/java/org/enso/interpreter/arrow/runtime/ArrowFixedArrayInt.java
  engine/runtime-language-arrow/src/main/java/org/enso/interpreter/arrow/runtime/ArrowFixedSizeArrayBuilder.java
  engine/runtime-language-arrow/src/main/java/org/enso/interpreter/arrow/runtime/ArrowFixedSizeArrayFactory.java
  engine/runtime-language-arrow/src/main/java/org/enso/interpreter/arrow/runtime/ArrowOperationPlus.java
  engine/runtime-language-arrow/src/main/java/org/enso/interpreter/arrow/runtime/ByteBufferDirect.java
  engine/runtime-language-arrow/src/main/java/org/enso/interpreter/arrow/runtime/OperationPlus.java
  engine/runtime-language-arrow/src/main/java/org/enso/interpreter/arrow/runtime/RoundingUtil.java
  engine/runtime-language-arrow/src/main/java/org/enso/interpreter/arrow/runtime/ScalarOperationNode.java
  engine/runtime-language-arrow/src/main/java/org/enso/interpreter/arrow/runtime/ValueToNumberNode.java
  engine/runtime-language-arrow/src/test/java/org/enso/interpreter/arrow/AddArrowTest.java
  engine/runtime-language-arrow/src/test/java/org/enso/interpreter/arrow/VerifyArrowTest.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/ApplicationNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeCallableNode.java
  test/Benchmarks/src/Table/Arithmetic.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required, -compiler

#10035 Replace Jackson serde
  build.sbt
  distribution/engine/THIRD-PARTY/NOTICE
  distribution/engine/THIRD-PARTY/com.fasterxml.jackson.dataformat.jackson-dataformat-cbor-2.15.2/CREDITS-2.x.txt
  distribution/engine/THIRD-PARTY/com.fasterxml.jackson.module.jackson-module-scala_2.13-2.15.2/LICENSE
  distribution/engine/THIRD-PARTY/com.fasterxml.jackson.module.jackson-module-scala_2.13-2.15.2/NOTICES
  distribution/engine/THIRD-PARTY/com.github.plokhotnyuk.jsoniter-scala.jsoniter-scala-core_2.13-2.28.5/LICENSE
  distribution/engine/THIRD-PARTY/com.github.plokhotnyuk.jsoniter-scala.jsoniter-scala-macros_2.13-2.28.5/LICENSE
  distribution/engine/THIRD-PARTY/com.thoughtworks.paranamer.paranamer-2.8/NOTICES
  distribution/project-manager/THIRD-PARTY/NOTICE
  distribution/project-manager/THIRD-PARTY/com.fasterxml.jackson.dataformat.jackson-dataformat-cbor-2.15.2/CREDITS-2.x.txt
  distribution/project-manager/THIRD-PARTY/com.fasterxml.jackson.module.jackson-module-scala_2.13-2.15.2/LICENSE
  distribution/project-manager/THIRD-PARTY/com.fasterxml.jackson.module.jackson-module-scala_2.13-2.15.2/NOTICES
  distribution/project-manager/THIRD-PARTY/com.github.plokhotnyuk.jsoniter-scala.jsoniter-scala-core_2.13-2.28.5/LICENSE
  distribution/project-manager/THIRD-PARTY/com.github.plokhotnyuk.jsoniter-scala.jsoniter-scala-macros_2.13-2.28.5/LICENSE
  distribution/project-manager/THIRD-PARTY/com.thoughtworks.paranamer.paranamer-2.8/NOTICES
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/RuntimeConnector.scala
  engine/polyglot-api-macros/src/main/scala/org/enso/polyglot/macros/SerdeConfig.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/DocSection.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/ExportedSymbol.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/Suggestion.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/data/These.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/data/Tree.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/data/TypeGraph.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/serde/ApiSerde.scala
  engine/polyglot-api/src/test/scala/org/enso/polyglot/runtime/serde/SerdeSpec.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/Endpoint.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/context/JacksonTest.java
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerEmulator.scala
  engine/runtime/src/main/java/org/enso/interpreter/caches/CacheUtils.java
  tools/legal-review/engine/com.fasterxml.jackson.dataformat.jackson-dataformat-cbor-2.15.2/files-add/CREDITS-2.x.txt
  tools/legal-review/engine/com.fasterxml.jackson.dataformat.jackson-dataformat-cbor-2.15.2/files-ignore
  tools/legal-review/engine/com.fasterxml.jackson.module.jackson-module-scala_2.13-2.15.2/copyright-ignore
  tools/legal-review/engine/com.fasterxml.jackson.module.jackson-module-scala_2.13-2.15.2/copyright-keep
  tools/legal-review/engine/com.fasterxml.jackson.module.jackson-module-scala_2.13-2.15.2/files-keep
  tools/legal-review/engine/com.github.plokhotnyuk.jsoniter-scala.jsoniter-scala-core_2.13-2.28.5/custom-license
  tools/legal-review/engine/com.github.plokhotnyuk.jsoniter-scala.jsoniter-scala-core_2.13-2.28.5/files-keep
  tools/legal-review/engine/com.github.plokhotnyuk.jsoniter-scala.jsoniter-scala-macros_2.13-2.28.5/custom-license
  tools/legal-review/engine/com.github.plokhotnyuk.jsoniter-scala.jsoniter-scala-macros_2.13-2.28.5/files-keep
  tools/legal-review/engine/com.thoughtworks.paranamer.paranamer-2.8/copyright-add
  tools/legal-review/engine/com.thoughtworks.paranamer.paranamer-2.8/copyright-ignore
  tools/legal-review/engine/com.thoughtworks.paranamer.paranamer-2.8/copyright-keep-context
  tools/legal-review/engine/com.thoughtworks.paranamer.paranamer-2.8/custom-license
  tools/legal-review/engine/report-state
  tools/legal-review/project-manager/com.fasterxml.jackson.dataformat.jackson-dataformat-cbor-2.15.2/files-add/CREDITS-2.x.txt
  tools/legal-review/project-manager/com.fasterxml.jackson.dataformat.jackson-dataformat-cbor-2.15.2/files-ignore
  tools/legal-review/project-manager/com.fasterxml.jackson.module.jackson-module-scala_2.13-2.15.2/copyright-add
  tools/legal-review/project-manager/com.fasterxml.jackson.module.jackson-module-scala_2.13-2.15.2/copyright-ignore
  tools/legal-review/project-manager/com.fasterxml.jackson.module.jackson-module-scala_2.13-2.15.2/default-and-custom-license
  tools/legal-review/project-manager/com.fasterxml.jackson.module.jackson-module-scala_2.13-2.15.2/files-keep
  tools/legal-review/project-manager/com.github.plokhotnyuk.jsoniter-scala.jsoniter-scala-core_2.13-2.28.5/custom-license
  tools/legal-review/project-manager/com.github.plokhotnyuk.jsoniter-scala.jsoniter-scala-core_2.13-2.28.5/files-keep
  tools/legal-review/project-manager/com.github.plokhotnyuk.jsoniter-scala.jsoniter-scala-macros_2.13-2.28.5/custom-license
  tools/legal-review/project-manager/com.github.plokhotnyuk.jsoniter-scala.jsoniter-scala-macros_2.13-2.28.5/files-keep
  tools/legal-review/project-manager/com.thoughtworks.paranamer.paranamer-2.8/copyright-add
  tools/legal-review/project-manager/com.thoughtworks.paranamer.paranamer-2.8/copyright-ignore
  tools/legal-review/project-manager/com.thoughtworks.paranamer.paranamer-2.8/copyright-keep-context
  tools/legal-review/project-manager/com.thoughtworks.paranamer.paranamer-2.8/custom-license
  tools/legal-review/project-manager/report-state
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#10244 Fix arrow keys in text inputs
  app/gui2/src/components/CodeEditor.vue
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetFunctionName.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetText.vue
  app/gui2/src/components/lexical/LexicalContent.vue
  app/gui2/src/components/widgets/AutoSizedInput.vue
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui

#10229 Ensure type ascriptions are correctly transformed to facilitate checking of more complex return types
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Encoding.enso
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/desugar/OperatorToFunction.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/TypeFunctions.scala
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/SignatureTest.java
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/resolve/TypeSignaturesTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/argument/ReadArgumentCheckNode.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
Labels: CI: Ready to merge, CI: No changelog needed

#10241 Make test framework list out failed tests to use in filter
  distribution/lib/Standard/Test/0.0.0-dev/src/Suite.enso
Labels: CI: No changelog needed

#10225 Add icon to indicate value type in table
  app/gui2/src/components/visualizations/TableVisualization.vue
  distribution/lib/Standard/Table/0.0.0-dev/src/Value_Type.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
  test/Visualization_Tests/src/Table_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10248 Presence of Any disables type checks
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/AutoscopedConstructorTest.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/argument/ReadArgumentCheckNode.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
  test/Base_Tests/src/Semantic/Conversion_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#10252 Format bar: Use new icons
  app/gui2/src/components/MarkdownEditor/BlockTypeMenu.vue
  app/gui2/src/components/MarkdownEditor/FormatPropertiesBar.vue
Labels: CI: No changelog needed

#10198 Implement text ellipsis on dropdowns
  CHANGELOG.md
  app/gui2/src/components/CircularMenu.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/GraphVisualization.vue
  app/gui2/src/components/GraphEditor/NodeWidgetTree.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetPort.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetSelfIcon.vue
  app/gui2/src/components/SvgIcon.vue
  app/gui2/src/components/widgets/DropdownWidget.vue
Labels: CI: Ready to merge

#10262 shouldCreateClosureRootNode when valueHasSomeTypeCheck
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
  test/Base_Tests/src/Semantic/Conversion_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10215 Change grab cursors; fix some bugs
  app/gui2/e2e/edgeRendering.spec.ts
  app/gui2/src/App.vue
  app/gui2/src/assets/base.css
  app/gui2/src/components/DocumentationPanel/DocsBreadcrumb.vue
  app/gui2/src/components/DocumentationPanel/DocsList.vue
  app/gui2/src/components/GraphEditor/GraphEdge.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/GraphNodeOutputPorts.vue
  app/gui2/src/components/GraphEditor/NodeWidgetTree.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetSelfIcon.vue
  app/gui2/src/components/MenuButton.vue
  app/gui2/src/components/NavBreadcrumb.vue
  app/gui2/src/components/NavBreadcrumbs.vue
  app/gui2/src/components/RecordControl.vue
  app/gui2/src/components/TopBar.vue
  app/gui2/src/components/VisualizationSelector.vue
  app/gui2/src/components/visualizations/JSONVisualization/JsonArrayWidget.vue
  app/gui2/src/components/visualizations/JSONVisualization/JsonObjectWidget.vue
  app/gui2/src/components/widgets/CheckboxWidget.vue
  app/gui2/src/components/widgets/DropdownWidget.vue
Labels: CI: Ready to merge, CI: No changelog needed

#10264 Output port interaction hint
  app/gui2/e2e/edgeRendering.spec.ts
  app/gui2/src/components/GraphEditor/GraphEdge.vue
  app/gui2/src/components/GraphEditor/GraphEdges.vue
  app/gui2/src/components/GraphEditor/GraphNodeOutputPorts.vue
  app/gui2/src/stores/graph/index.ts
  app/gui2/src/stores/graph/unconnectedEdges.ts
Labels: CI: Ready to merge, CI: No changelog needed

#10268 Add divider to numeric slider
  app/gui2/e2e/widgets.spec.ts
  app/gui2/src/assets/base.css
  app/gui2/src/components/widgets/NumericInputWidget.vue
Labels: CI: Ready to merge, CI: No changelog needed

#9998 Add an option to profile AppImage
  app/gui2/src/composables/syncLocalStorage.ts
  app/ide-desktop/lib/client/src/config.ts
  app/ide-desktop/lib/client/src/index.ts
Labels: CI: No changelog needed, CI: Clean build required

#10267 Fix numeric slider
  app/gui2/src/components/widgets/NumericInputWidget.vue
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#10266 Initial separation of Snowflake_Dialect from Postgres_Dialect
  distribution/lib/Standard/AWS/0.0.0-dev/src/Database/Redshift/Internal/Redshift_Dialect.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Filter_Condition.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Common/Database_Join_Helper.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Internals_Access.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/JDBC_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Type_Mapping.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/SQL_Statement.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Connection.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Dialect.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Suite.enso
  distribution/manifest.template.yaml
  test/Snowflake_Tests/README.md
  test/Snowflake_Tests/package.yaml
  test/Snowflake_Tests/src/Main.enso
  test/Snowflake_Tests/src/Snowflake_Spec.enso
  test/Table_Tests/src/Database/Common/Common_Spec.enso
  test/Table_Tests/src/Database/Common/Names_Length_Limits_Spec.enso
  test/Table_Tests/src/Util.enso
Labels: CI: Ready to merge, CI: No changelog needed

#8652 Type Inference PoC - iteration 1 - most basic type inference
  engine/polyglot-api/src/main/java/org/enso/polyglot/RuntimeOptions.java
  engine/runner/src/main/java/org/enso/runner/ContextFactory.java
  engine/runner/src/main/java/org/enso/runner/Main.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/MetadataInteropHelpers.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/context/NameResolutionAlgorithm.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/PassPersistance.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/AtomTypeInterface.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/AtomTypeInterfaceFromBindingsMap.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/BuiltinTypes.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/CommonTypeHelpers.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/InferredType.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/LocalBindingsTyping.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/SumTypeSimplifier.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/TypeCompatibility.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/TypeInference.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/TypeInferencePersistance.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/TypePropagation.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/TypeRepresentation.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/TypeResolver.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/util/ProxyList.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/Passes.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/context/InlineContext.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/context/ModuleContext.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/data/BindingsMap.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/data/CompilerConfig.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/IRPass.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/BindingAnalysis.scala
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/CompilerTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/TypeInferenceTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/SymbolResolutionTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/TypeInferenceConsistencyTest.java
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/analyse/BindingAnalysisTest.scala
  engine/runtime-parser/src/main/java/org/enso/compiler/core/ir/IrPersistance.java
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Warning.scala
  engine/runtime/src/main/java/org/enso/interpreter/EnsoLanguage.java
  engine/runtime/src/main/java/org/enso/interpreter/caches/ImportExportCache.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
  engine/runtime/src/test/java/org/enso/runtime/test/TypeMetadataPersistanceTest.java
  lib/java/persistance/src/main/java/org/enso/persist/PerMap.java
  lib/java/persistance/src/main/java/org/enso/persist/Persistance.java
  lib/scala/pkg/src/main/scala/org/enso/pkg/QualifiedName.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/ProjectManagementOps.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#10271 Dashboard hotfixes
  app/gui2/vite.config.ts
  app/ide-desktop/lib/assets/github.svg
  app/ide-desktop/lib/assets/google.svg
  app/ide-desktop/lib/dashboard/e2e/actions.ts
  app/ide-desktop/lib/dashboard/package.json
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Button/Button.tsx
  app/ide-desktop/lib/dashboard/src/components/FontAwesomeIcon.tsx
  app/ide-desktop/lib/dashboard/src/components/Input.tsx
  app/ide-desktop/lib/dashboard/src/components/SubmitButton.tsx
  app/ide-desktop/lib/dashboard/src/components/SvgIcon.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/ProjectIcon.tsx
  app/ide-desktop/lib/dashboard/src/layouts/CategorySwitcher.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Drive.tsx
  app/ide-desktop/lib/dashboard/src/layouts/UserBar.tsx
  app/ide-desktop/lib/dashboard/src/pages/authentication/Login.tsx
  app/ide-desktop/lib/dashboard/src/pages/dashboard/Dashboard.tsx
  app/ide-desktop/lib/dashboard/src/providers/AuthProvider.tsx
  app/ide-desktop/lib/dashboard/src/reactQueryClient.ts
  app/ide-desktop/lib/dashboard/src/text/english.json
  app/ide-desktop/lib/dashboard/tailwind.config.js
  package-lock.json
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required, --bug, g-dashboard

#10251 Support empty and non-numeric default values in number picker
  app/gui2/src/components/GraphEditor/widgets/WidgetNumber.vue
  app/gui2/src/components/widgets/AutoSizedInput.vue
  app/gui2/src/components/widgets/NumericInputWidget.vue
Labels: CI: Ready to merge, CI: No changelog needed

#10272 Soft retries when awaiting runtime responses
  engine/language-server/src/main/scala/org/enso/languageserver/text/CollaborativeBuffer.scala
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#7054 Enso language support with parser in VSCode, IGV, etc.
  .github/workflows/enso4igv.yml
  build.sbt
  engine/runtime-parser/src/main/java/org/enso/compiler/core/ir/MetadataStorage.java
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/Implicits.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/CallArgument.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/DefinitionArgument.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Empty.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Expression.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Function.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Literal.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Module.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Name.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Pattern.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/ProcessingPass.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Type.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/Application.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/Case.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/Comment.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/Error.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/Foreign.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/Operator.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/Section.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/ImportExport.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Redefined.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Syntax.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/module/scope/Definition.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/module/scope/Export.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/module/scope/Import.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/module/scope/definition/Method.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/module/scope/imports/Polyglot.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/type/Set.scala
  lib/java/persistance-dsl/src/main/java/org/enso/persist/impl/PersistableProcessor.java
  lib/java/persistance/src/main/java/org/enso/persist/Persistable.java
  lib/java/persistance/src/main/java/org/enso/persist/Persistance.java
  lib/java/persistance/src/main/java/org/enso/persist/package-info.java
  lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java
  tools/enso4igv/README.md
  tools/enso4igv/package-lock.json
  tools/enso4igv/package.json
  tools/enso4igv/pom.xml
  tools/enso4igv/src/main/java/org/enso/tools/enso4igv/enso/EnsoCompletionCollector.java
  tools/enso4igv/src/main/java/org/enso/tools/enso4igv/enso/EnsoStructure.java
  tools/enso4igv/src/test/java/org/enso/tools/enso4igv/enso/EnsoStructureTest.java
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#10283 TextEdit with custom IdMap
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/text/ApplyEditHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/BufferRegistry.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/CollaborativeBuffer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/TextApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/TextProtocol.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/FileNotificationsTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/TextOperationsTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime-compiler/src/main/java/org/enso/compiler/context/CompilerContext.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/data/IdMap.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/compiler/context/ChangesetBuilder.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/EditFileCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/model/PendingEdit.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/RefactoringRenameJob.scala
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/instrument/IncrementalUpdatesTest.java
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeErrorsTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeRefactoringTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeSuggestionUpdatesTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeTextEditsTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeTypesTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
  engine/runtime-parser/src/main/java/org/enso/compiler/core/EnsoParser.java
  engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java
  lib/scala/text-buffer/src/main/scala/org/enso/text/editing/model.scala
Labels: CI: Ready to merge, CI: No changelog needed

#10257 Fix suspense query
  app/ide-desktop/lib/dashboard/src/providers/SessionProvider.tsx
Labels: CI: No changelog needed, --bug, g-dashboard

#10202 Initial Support for paywalls
  app/ide-desktop/eslint.config.js
  app/ide-desktop/lib/dashboard/src/App.tsx
  app/ide-desktop/lib/dashboard/src/appUtils.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Button/Button.tsx
  app/ide-desktop/lib/dashboard/src/components/Autocomplete.tsx
  app/ide-desktop/lib/dashboard/src/components/MenuEntry.tsx
  app/ide-desktop/lib/dashboard/src/components/Paywall/ContextMenuEntry.tsx
  app/ide-desktop/lib/dashboard/src/components/Paywall/PaywallAlert.tsx
  app/ide-desktop/lib/dashboard/src/components/Paywall/PaywallDialog.tsx
  app/ide-desktop/lib/dashboard/src/components/Paywall/PaywallDialogButton.tsx
  app/ide-desktop/lib/dashboard/src/components/Paywall/PaywallScreen.tsx
  app/ide-desktop/lib/dashboard/src/components/Paywall/UpgradeButton.tsx
  app/ide-desktop/lib/dashboard/src/components/Paywall/components/PaywallBulletPoints.tsx
  app/ide-desktop/lib/dashboard/src/components/Paywall/components/PaywallButton.tsx
  app/ide-desktop/lib/dashboard/src/components/Paywall/components/PaywallDevtools.tsx
  app/ide-desktop/lib/dashboard/src/components/Paywall/components/PaywallLock.tsx
  app/ide-desktop/lib/dashboard/src/components/Paywall/components/index.ts
  app/ide-desktop/lib/dashboard/src/components/Paywall/index.ts
  app/ide-desktop/lib/dashboard/src/hooks/billing/FeaturesConfiguration.ts
  app/ide-desktop/lib/dashboard/src/hooks/billing/index.ts
  app/ide-desktop/lib/dashboard/src/hooks/billing/paywallFeaturesHooks.ts
  app/ide-desktop/lib/dashboard/src/hooks/billing/paywallHooks.ts
  app/ide-desktop/lib/dashboard/src/layouts/Settings/withPaywall.tsx
  app/ide-desktop/lib/dashboard/src/providers/AuthProvider.tsx
  app/ide-desktop/lib/dashboard/src/text/english.json
  app/ide-desktop/lib/dashboard/src/text/index.ts
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#10294 Fix tooltip display and other refinements across dashboard
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Button/Button.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/Dialog.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/types.ts
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/variants.ts
  app/ide-desktop/lib/dashboard/src/components/dashboard/ProjectIcon.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Samples.tsx
  app/ide-desktop/lib/dashboard/src/layouts/StartModal.tsx
  app/ide-desktop/lib/dashboard/src/layouts/WhatsNew.tsx
  app/ide-desktop/lib/dashboard/src/text/english.json
Labels: CI: No changelog needed, g-dashboard

#10290 Async Ydoc initialization
  engine/language-server/src/main/java/org/enso/languageserver/boot/resource/RepoInitialization.java
  engine/language-server/src/main/java/org/enso/languageserver/boot/resource/YdocInitialization.java
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/ResourcesInitialization.scala
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#10260 Remove legacy matrix and legacy objects from table visualization and remove the index column
  app/gui2/src/components/visualizations/TableVisualization.vue
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
  test/Visualization_Tests/src/Table_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10300 Fix User Group page
  app/ide-desktop/lib/dashboard/src/layouts/Settings/MembersTable.tsx
Labels: CI: No changelog needed, --bug, --regression, g-dashboard

#10295 Lower the size of the parser library in VSCode
  .github/workflows/enso4igv.yml
Labels: CI: No changelog needed

#10286 Disable clickThrough for get nodes for anything thats datatype is not JS_Object
  app/gui2/src/components/visualizations/JSONVisualization.vue
Labels: CI: Ready to merge, CI: No changelog needed

#10303 Small fixes to Cloud Integration
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Errors.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Audit_Log.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Utils.enso
  std-bits/base/src/main/java/org/enso/base/enso_cloud/CloudAPI.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/audit/AuditLogMessage.java
  test/Base_Tests/src/Network/Enso_Cloud/Audit_Log_Spec.enso
  test/Base_Tests/src/Network/Enso_Cloud/Secrets_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10310 Visualization Preview
  CHANGELOG.md
  app/gui2/e2e/graphNodeVisualization.spec.ts
  app/gui2/src/components/CircularMenu.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/GraphNodeOutputPorts.vue
  app/gui2/src/components/GraphEditor/GraphNodes.vue
  app/gui2/src/components/GraphEditor/GraphVisualization.vue
  app/gui2/src/components/VisualizationContainer.vue
  app/gui2/src/providers/visualizationConfig.ts
  app/gui2/stories/CircularMenu.story.vue
  package-lock.json
Labels: CI: Ready to merge, x-new-feature, -gui

#10314 Use external IDs for stable selection tracking.
  app/gui2/e2e/edgeInteractions.spec.ts
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/composables/__tests__/selection.test.ts
  app/gui2/src/composables/selection.ts
  app/gui2/src/providers/graphSelection.ts
  app/gui2/src/stores/graph/graphDatabase.ts
Labels: CI: Ready to merge, CI: No changelog needed

#10219 Imrpove BG rendering
  app/ide-desktop/lib/dashboard/src/tailwind.css
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#10298 Some formatting issues and a few tweaks
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/List.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Statistics.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Statistics/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Function.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Response_Body.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/Output_Stream.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Dialect.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Column_Operation.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Delimited/Delimited_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Workbook.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Extensions/Table_Conversions.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Add_Running.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Simple_Expression.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  test/Table_Tests/src/Common_Table_Operations/Core_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Derived_Columns_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10031 Refactor E2E tests for Dashboard; add E2E tests for User and Organization settings pages
  app/ide-desktop/lib/dashboard/e2e/README.md
  app/ide-desktop/lib/dashboard/e2e/actions.ts
  app/ide-desktop/lib/dashboard/e2e/actions/BaseActions.ts
  app/ide-desktop/lib/dashboard/e2e/actions/DrivePageActions.ts
  app/ide-desktop/lib/dashboard/e2e/actions/EditorPageActions.ts
  app/ide-desktop/lib/dashboard/e2e/actions/LoginPageActions.ts
  app/ide-desktop/lib/dashboard/e2e/actions/NewDataLinkModalActions.ts
  app/ide-desktop/lib/dashboard/e2e/actions/SetUsernamePageActions.ts
  app/ide-desktop/lib/dashboard/e2e/actions/SettingsPageActions.ts
  app/ide-desktop/lib/dashboard/e2e/actions/StartModalActions.ts
  app/ide-desktop/lib/dashboard/e2e/actions/contextMenuActions.ts
  app/ide-desktop/lib/dashboard/e2e/actions/goToPageActions.ts
  app/ide-desktop/lib/dashboard/e2e/actions/openUserMenuAction.ts
  app/ide-desktop/lib/dashboard/e2e/actions/userMenuActions.ts
  app/ide-desktop/lib/dashboard/e2e/api.ts
  app/ide-desktop/lib/dashboard/e2e/assetPanel.spec.ts
  app/ide-desktop/lib/dashboard/e2e/changePassword.spec.ts
  app/ide-desktop/lib/dashboard/e2e/copy.spec.ts
  app/ide-desktop/lib/dashboard/e2e/createAsset.spec.ts
  app/ide-desktop/lib/dashboard/e2e/dataLinkEditor.spec.ts
  app/ide-desktop/lib/dashboard/e2e/delete.spec.ts
  app/ide-desktop/lib/dashboard/e2e/driveView.spec.ts
  app/ide-desktop/lib/dashboard/e2e/loginLogout.spec.ts
  app/ide-desktop/lib/dashboard/e2e/membersSettings.spec.ts
  app/ide-desktop/lib/dashboard/e2e/organizationSettings.spec.ts
  app/ide-desktop/lib/dashboard/e2e/pageSwitcher.spec.ts
  app/ide-desktop/lib/dashboard/e2e/signUp.spec.ts
  app/ide-desktop/lib/dashboard/e2e/signUpFlow.spec.ts
  app/ide-desktop/lib/dashboard/e2e/signUpWithOrganizationId.spec.ts
  app/ide-desktop/lib/dashboard/e2e/signUpWithoutOrganizationId.spec.ts
  app/ide-desktop/lib/dashboard/e2e/sort.spec.ts
  app/ide-desktop/lib/dashboard/e2e/startModal.spec.ts
  app/ide-desktop/lib/dashboard/e2e/userMenu.spec.ts
  app/ide-desktop/lib/dashboard/e2e/userSettings.spec.ts
  app/ide-desktop/lib/dashboard/src/authentication/cognito.mock.ts
  app/ide-desktop/lib/dashboard/src/layouts/Settings/OrganizationSettingsSection.tsx
  app/ide-desktop/lib/dashboard/src/modals/AddPaymentMethodModal.tsx
  app/ide-desktop/lib/dashboard/src/providers/AuthProvider.tsx
  app/ide-desktop/lib/dashboard/src/services/Backend.ts
  app/ide-desktop/lib/dashboard/src/services/LocalBackend.ts
  app/ide-desktop/lib/dashboard/src/services/RemoteBackend.ts
  app/ide-desktop/lib/dashboard/src/text/english.json
  app/ide-desktop/lib/dashboard/src/utilities/HttpClient.ts
  app/ide-desktop/lib/types/globals.d.ts
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#10296 Run whole test/Base_Tests with NI
  .vscode/launch.json
  build.sbt
  build/build/src/engine/context.rs
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Base_64.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Regression.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Period.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/XML.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_Secret.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Array_Like_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Extra_Imports.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Meta/Enso_Project.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Response.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/File_Access.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/File_Permissions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/Input_Stream.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/Internal/Reporting_Stream_Decoder_Helper.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/Output_Stream.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Test.enso
  docs/infrastructure/native-image.md
  engine/runner/src/main/java/org/enso/runner/EnsoLibraryFeature.java
  engine/runner/src/main/resources/META-INF/native-image/org/enso/runner/reflect-config.json
  engine/runner/src/main/resources/META-INF/native-image/org/enso/runner/resource-config.json
  engine/runner/src/test/resources/Factorial.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/resolver/HostMethodCallNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EnsoProjectNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/ProjectDescription.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoFile.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicException.java
  lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/Builtin.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/BuiltinsProcessor.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/builtins/MethodGenerator.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/builtins/MethodNodeClassGenerator.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/builtins/NoSpecializationClassGenerator.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/builtins/SpecializedMethodsGenerator.java
  std-bits/base/src/main/java/org/enso/base/Stream_Utils.java
  std-bits/base/src/main/java/org/enso/base/XML_Utils.java
  std-bits/base/src/main/java/org/enso/base/file_system/File_Utils.java
  test/Base_Tests/src/Data/Map_Spec.enso
  test/Base_Tests/src/Main.enso
  test/Base_Tests/src/Semantic/Equals_Spec.enso
  test/Base_Tests/src/System/Input_Stream_Spec.enso
Labels: CI: No changelog needed, CI: Clean build required

#10331 Fix Offline message flickering in offline mode
  app/ide-desktop/lib/dashboard/src/components/Suspense.tsx
  app/ide-desktop/lib/dashboard/src/hooks/debounceCallbackHooks.ts
  app/ide-desktop/lib/dashboard/src/hooks/debounceStateHooks.ts
  app/ide-desktop/lib/dashboard/src/hooks/debounceValueHooks.ts
  app/ide-desktop/lib/dashboard/src/hooks/unmountHooks.ts
  app/ide-desktop/lib/dashboard/src/index.tsx
  app/ide-desktop/lib/dashboard/src/modals/TermsOfServiceModal.tsx
Labels: CI: No changelog needed, --bug, g-dashboard

#10332 Fix "About" modal
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/Dialog.tsx
  app/ide-desktop/lib/dashboard/src/modals/AboutModal.tsx
Labels: CI: No changelog needed, --bug, g-dashboard

#10243 Renaming project in GUI
  CHANGELOG.md
  app/gui2/shared/languageServer.ts
  app/gui2/shared/languageServerTypes.ts
  app/gui2/src/App.vue
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/NavBar.vue
  app/gui2/src/components/NavBreadcrumb.vue
  app/gui2/src/components/NavBreadcrumbs.vue
  app/gui2/src/components/TopBar.vue
  app/gui2/src/providers/graphStackNavigator.ts
  app/gui2/src/stores/project/executionContext.ts
  app/gui2/src/stores/project/index.ts
  app/gui2/src/util/__tests__/qualifiedName.test.ts
  app/gui2/src/util/qualifiedName.ts
  app/gui2/src/views/ProjectView.vue
  app/ide-desktop/lib/dashboard/src/layouts/Editor.tsx
  app/ide-desktop/lib/types/types.d.ts
Labels: CI: Ready to merge, x-new-feature, -gui

#10334 Add column menu to header template
  app/gui2/src/components/visualizations/TableVisualization.vue
Labels: CI: Ready to merge, CI: No changelog needed

#10337 Some drop down fixes
  CHANGELOG.md
  app/gui2/src/components/GraphEditor/widgets/WidgetNumber.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui2/src/providers/selectionArrow.ts
Labels: CI: Ready to merge, --bug, -gui

#10327 Fix pasting tables from Google Sheets; update tests.
  CHANGELOG.md
  app/gui2/src/components/GraphEditor/__tests__/clipboard.test.ts
  app/gui2/src/components/GraphEditor/__tests__/clipboardTestCases.json
  app/gui2/src/components/GraphEditor/clipboard.ts
  app/gui2/tsconfig.app.json
Labels: CI: Ready to merge

#10318 Change the default location for Enso projects
  app/ide-desktop/lib/client/src/bin/server.ts
  app/ide-desktop/lib/project-manager-shim/package.json
  app/ide-desktop/lib/project-manager-shim/src/desktopEnvironment.ts
  app/ide-desktop/lib/project-manager-shim/src/projectManagement.ts
  app/ide-desktop/lib/project-manager-shim/src/projectManagerShimMiddleware.ts
  build.sbt
  lib/java/desktop-environment/src/main/java/org/enso/desktopenvironment/Directories.java
  lib/java/desktop-environment/src/main/java/org/enso/desktopenvironment/DirectoriesFactory.java
  lib/java/desktop-environment/src/main/java/org/enso/desktopenvironment/LinuxDirectories.java
  lib/java/desktop-environment/src/main/java/org/enso/desktopenvironment/MacOsDirectories.java
  lib/java/desktop-environment/src/main/java/org/enso/desktopenvironment/Platform.java
  lib/java/desktop-environment/src/main/java/org/enso/desktopenvironment/WindowsDirectories.java
  lib/java/desktop-environment/src/test/java/org/enso/desktopenvironment/DirectoriesTest.java
  lib/java/desktop-environment/src/test/java/org/enso/desktopenvironment/PlatformTest.java
  lib/scala/project-manager/src/main/java/org/enso/projectmanager/event/package-info.java
  lib/scala/project-manager/src/main/java/org/enso/projectmanager/infrastructure/migration/ProjectsMigration.java
  lib/scala/project-manager/src/main/resources/application.conf
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/MainModule.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/ProjectManager.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/command/ProjectListCommand.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/configuration.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/http/ProjectsEndpoint.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/repository/MetadataFileStorage.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/repository/ProjectFileRepository.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/repository/ProjectFileRepositoryFactory.scala
  lib/scala/project-manager/src/test/java/org/enso/projectmanager/infrastructure/migration/ProjectsMigrationTest.java
  lib/scala/project-manager/src/test/resources/application-test.conf
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/BaseServerSpec.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/service/filesystem/FileSystemServiceSpec.scala
Labels: CI: Ready to merge, CI: No changelog needed

#10348 Autoscoping for File_Format and minor tweaks.
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/XML/XML_Format.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Data_Link_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Response_Body.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File_Format.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Data_Link/Postgres_Data_Link.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/SQLite_Format.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Google_Api/0.0.0-dev/src/Internal/Google_Analytics_Internal.enso
  distribution/lib/Standard/Image/0.0.0-dev/src/Image_File_Format.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Snowflake_Data_Link.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Delimited/Delimited_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Faker.enso
  test/AWS_Tests/src/S3_Spec.enso
  test/Base_Tests/src/Data/Vector_Spec.enso
  test/Base_Tests/src/Network/Enso_Cloud/Enso_File_Spec.enso
  test/Base_Tests/src/Network/Http/Http_Data_Link_Spec.enso
  test/Base_Tests/src/Network/Http_Spec.enso
  test/Base_Tests/src/System/File_Read_Spec.enso
  test/Base_Tests/src/System/Temporary_File_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Database/Upload_Spec.enso
  test/Table_Tests/src/IO/Csv_Spec.enso
  test/Table_Tests/src/IO/Data_Link_Formats_Spec.enso
  test/Table_Tests/src/IO/Delimited_Read_Spec.enso
  test/Table_Tests/src/IO/Delimited_Write_Spec.enso
  test/Table_Tests/src/IO/Excel_Spec.enso
  test/Table_Tests/src/IO/Fetch_Spec.enso
  test/Table_Tests/src/IO/Formats_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Date_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Date_Time_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Time_Of_Day_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10340 Wip/mk/default visualisations for connections
  CHANGELOG.md
  app/gui2/src/components/visualizations/TableVisualization.vue
Labels: CI: Ready to merge

#10333 Improve tab bar
  app/ide-desktop/lib/dashboard/e2e/actions.ts
  app/ide-desktop/lib/dashboard/e2e/actions/BaseActions.ts
  app/ide-desktop/lib/dashboard/e2e/actions/DrivePageActions.ts
  app/ide-desktop/lib/dashboard/e2e/actions/EditorPageActions.ts
  app/ide-desktop/lib/dashboard/e2e/actions/PageActions.ts
  app/ide-desktop/lib/dashboard/e2e/actions/SettingsPageActions.ts
  app/ide-desktop/lib/dashboard/e2e/actions/goToPageActions.ts
  app/ide-desktop/lib/dashboard/e2e/actions/userMenuActions.ts
  app/ide-desktop/lib/dashboard/e2e/membersSettings.spec.ts
  app/ide-desktop/lib/dashboard/playwright.config.ts
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/Dialog.tsx
  app/ide-desktop/lib/dashboard/src/components/DateInput.tsx
  app/ide-desktop/lib/dashboard/src/components/Page.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/ProjectIcon.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/ProjectNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetVersion.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetsTable.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Drive.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Editor.tsx
  app/ide-desktop/lib/dashboard/src/layouts/TabBar.tsx
  app/ide-desktop/lib/dashboard/src/layouts/TopBar.tsx
  app/ide-desktop/lib/dashboard/src/layouts/UserBar.tsx
  app/ide-desktop/lib/dashboard/src/layouts/UserMenu.tsx
  app/ide-desktop/lib/dashboard/src/pages/dashboard/Dashboard.tsx
  app/ide-desktop/lib/dashboard/src/services/Backend.ts
  app/ide-desktop/lib/dashboard/src/services/RemoteBackend.ts
  app/ide-desktop/lib/dashboard/src/text/english.json
  app/ide-desktop/lib/types/globals.d.ts
Labels: p-high, CI: Ready to merge, CI: No changelog needed, g-dashboard

#10350 Fix getDocuments on Windows
  app/ide-desktop/lib/project-manager-shim/src/desktopEnvironment.ts
  build.sbt
  lib/java/desktop-environment/src/main/java/org/enso/desktopenvironment/WindowsDirectories.java
  lib/java/desktop-environment/src/test/java/org/enso/desktopenvironment/DirectoriesTest.java
Labels: CI: Ready to merge, CI: No changelog needed

#10328 More detailed No_Such_Method error message for function like objects
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Meta.enso
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/ExecCompilerTest.java
  test/Base_Tests/src/Data/Function_Spec.enso
Labels: CI: No changelog needed

#10329 Verify ./runner executable on all supported OSes
  build.sbt
  build/build/src/engine.rs
  build/build/src/engine/context.rs
  build/cli/src/lib.rs
  engine/runner/src/main/resources/META-INF/native-image/org/enso/runner/reflect-config.json
Labels: CI: No changelog needed

#10274 Extension methods can be exported by name
  build.sbt
  docs/syntax/functions.md
  engine/runtime-compiler/src/main/java/org/enso/compiler/dump/IRDumper.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/PrivateSymbolsAnalysis.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/data/BindingsMap.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/AmbiguousImportsAnalysis.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/AutomaticParallelism.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/BindingAnalysis.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/FullyQualifiedNames.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/GlobalNames.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/MethodCalls.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/MethodDefinitions.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/Patterns.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/TypeNames.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/refactoring/IRUtils.scala
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/passes/MethodCallsTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/ExtensionMethodResolutionTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/exports/ExportExtensionMethodTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/exports/ExportStaticMethodTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/scope/ModuleScopeTest.java
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/refactoring/IRUtilsTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/analyse/BindingAnalysisTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/resolve/GlobalNamesTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/semantic/ImportExportTest.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/ImportExport.scala
  engine/runtime-suggestions/src/main/scala/org/enso/compiler/suggestions/ExportsBuilder.scala
  engine/runtime/src/main/java/org/enso/interpreter/caches/ImportExportCache.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
  lib/java/test-utils/src/main/java/org/enso/test/utils/ContextUtils.java
  lib/java/test-utils/src/main/java/org/enso/test/utils/ModuleUtils.java
  lib/java/test-utils/src/main/java/org/enso/test/utils/ProjectUtils.java
  lib/java/test-utils/src/main/java/org/enso/test/utils/SourceModule.java
  lib/java/test-utils/src/main/java/org/enso/test/utils/TestRootNode.java
Labels: CI: Ready to merge, CI: No changelog needed

#10365 Fix signatures for distinct and duplicates
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10358 Fix positioning of extended menu
  app/gui2/src/components/ExtendedMenu.vue
Labels: p-high, CI: Ready to merge, CI: No changelog needed, --bug, -gui

#10351 Fix opening cloud projects
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Button/Button.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Text/useVisualTooltip.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/ProjectIcon.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings.tsx
  app/ide-desktop/lib/dashboard/src/layouts/TabBar.tsx
  app/ide-desktop/lib/dashboard/src/pages/dashboard/Dashboard.tsx
  app/ide-desktop/lib/dashboard/src/services/Backend.ts
  app/ide-desktop/lib/dashboard/src/services/RemoteBackend.ts
Labels: p-high, CI: Ready to merge, CI: No changelog needed, --bug, --regression, g-dashboard

#10360 Don't cache errored requests for /user/me endpoint
  app/ide-desktop/lib/dashboard/e2e/actions.ts
  app/ide-desktop/lib/dashboard/e2e/api.ts
  app/ide-desktop/lib/dashboard/e2e/assetSearchBar.spec.ts
  app/ide-desktop/lib/dashboard/e2e/copy.spec.ts
  app/ide-desktop/lib/dashboard/e2e/editAssetName.spec.ts
  app/ide-desktop/lib/dashboard/e2e/labelsPanel.spec.ts
  app/ide-desktop/lib/dashboard/e2e/loginScreen.spec.ts
  app/ide-desktop/lib/dashboard/src/providers/AuthProvider.tsx
  app/ide-desktop/lib/dashboard/src/reactQueryClient.ts
  app/ide-desktop/lib/dashboard/src/services/Backend.ts
  app/ide-desktop/lib/dashboard/src/services/RemoteBackend.ts
  app/ide-desktop/lib/dashboard/src/text/english.json
Labels: CI: Ready to merge, CI: No changelog needed, --bug, --regression, g-dashboard

#10371 Fix creating local projects
  app/ide-desktop/lib/dashboard/src/components/dashboard/ProjectIcon.tsx
  app/ide-desktop/lib/dashboard/src/components/dashboard/ProjectNameColumn.tsx
  app/ide-desktop/lib/dashboard/src/events/assetEvent.ts
  app/ide-desktop/lib/dashboard/src/layouts/AssetContextMenu.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetsTable.tsx
  app/ide-desktop/lib/dashboard/src/services/LocalBackend.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, --regression, g-dashboard

#9745 Show Language Server Logs
  app/ide-desktop/lib/assets/logs.svg
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/Dialog.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/DialogStackProvider.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/types.ts
  app/ide-desktop/lib/dashboard/src/components/ErrorBoundary.tsx
  app/ide-desktop/lib/dashboard/src/components/JSONSchemaInput.tsx
  app/ide-desktop/lib/dashboard/src/components/Loader.tsx
  app/ide-desktop/lib/dashboard/src/components/styled/ButtonRow.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetPanel.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetProjectSession.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetProjectSessions.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetProperties.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetSearchBar.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetVersions/AssetVersion.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetVersions/AssetVersions.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/DeleteUserAccountSettingsSection.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/KeyboardShortcutsTable.tsx
  app/ide-desktop/lib/dashboard/src/modals/EditAssetDescriptionModal.tsx
  app/ide-desktop/lib/dashboard/src/modals/ProjectLogsModal.tsx
  app/ide-desktop/lib/dashboard/src/services/Backend.ts
  app/ide-desktop/lib/dashboard/src/services/LocalBackend.ts
  app/ide-desktop/lib/dashboard/src/services/RemoteBackend.ts
  app/ide-desktop/lib/dashboard/src/services/remoteBackendPaths.ts
  app/ide-desktop/lib/dashboard/src/tailwind.css
  app/ide-desktop/lib/dashboard/src/text/english.json
  app/ide-desktop/lib/dashboard/src/text/index.ts
  app/ide-desktop/lib/dashboard/tailwind.config.js
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#10372 Rename `order_by` to `sort` for `Table` and `DB_Table`.
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Statistics/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Period.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/XML.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_Secret.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Response.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/Internal/Reporting_Stream_Decoder_Helper.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/Output_Stream.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Widget_Helpers.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Searcher/0.0.0-dev/src/Data_Science.enso
  distribution/lib/Standard/Searcher/0.0.0-dev/src/Data_Science/Transform.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Faker.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/AI.enso
  test/Benchmarks/src/Table/Add_Row_Number.enso
  test/Benchmarks/src/Table/Sorting.enso
  test/Table_Tests/src/Common_Table_Operations/Add_Row_Number_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Aggregate_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Name_Edge_Cases_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Distinct_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Integration_Tests.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Cross_Join_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Join_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Lookup_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Replace_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Zip_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Map_To_Table_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Nothing_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Order_By_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Take_Drop_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Util.enso
  test/Table_Tests/src/Database/Codegen_Spec.enso
  test/Table_Tests/src/Database/Common/Common_Spec.enso
  test/Table_Tests/src/Database/Common/Default_Ordering_Spec.enso
  test/Table_Tests/src/Database/Common/Names_Length_Limits_Spec.enso
  test/Table_Tests/src/Database/SQLite_Spec.enso
  test/Table_Tests/src/Database/Upload_Spec.enso
  test/Table_Tests/src/In_Memory/Common_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
Labels: CI: Ready to merge

#10377 Fix linter error
  app/gui2/src/providers/selectionArrow.ts
Labels: CI: Ready to merge, CI: No changelog needed

#10375 Fix close button being shown off the tab
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Button/Button.tsx
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Button/CloseButton.tsx
  app/ide-desktop/lib/dashboard/src/layouts/TabBar.tsx
  app/ide-desktop/lib/dashboard/src/pages/dashboard/Dashboard.tsx
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#9887 Search bar for settings
  app/ide-desktop/lib/dashboard/src/components/MenuEntry.tsx
  app/ide-desktop/lib/dashboard/src/components/styled/SettingsInput.tsx
  app/ide-desktop/lib/dashboard/src/components/styled/settings/SettingsPage.tsx
  app/ide-desktop/lib/dashboard/src/components/styled/settings/SettingsSection.tsx
  app/ide-desktop/lib/dashboard/src/hooks/backendHooks.ts
  app/ide-desktop/lib/dashboard/src/hooks/toastAndLogHooks.ts
  app/ide-desktop/lib/dashboard/src/layouts/AssetPanel.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetProperties.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetSearchBar.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetsTable.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Drive.tsx
  app/ide-desktop/lib/dashboard/src/layouts/DriveBar.tsx
  app/ide-desktop/lib/dashboard/src/layouts/InfoMenu.tsx
  app/ide-desktop/lib/dashboard/src/layouts/SearchBar.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/AccountSettingsTab.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/ActivityLogSettingsSection.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/ActivityLogSettingsTab.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/ChangePasswordForm.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/ChangePasswordSettingsSection.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/DeleteUserAccountSettingsSection.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/KeyboardShortcutsSettingsSection.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/KeyboardShortcutsSettingsTab.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/KeyboardShortcutsSettingsTabBar.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/KeyboardShortcutsTable.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/LocalSettingsTab.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/MembersSettingsSection.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/MembersSettingsTabBar.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/OrganizationProfilePictureInput.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/OrganizationSettingsSection.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/OrganizationSettingsTab.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/ProfilePictureInput.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/SettingsCustomEntry.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/SettingsEntry.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/SettingsInputEntry.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/SettingsPaywall.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/SettingsSection.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/SettingsTab.ts
  app/ide-desktop/lib/dashboard/src/layouts/Settings/SettingsTab.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/SettingsTabType.ts
  app/ide-desktop/lib/dashboard/src/layouts/Settings/UserAccountSettingsSection.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/UserGroupUserRow.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/UserGroupsSettingsSection.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/settingsData.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/withPaywall.tsx
  app/ide-desktop/lib/dashboard/src/layouts/SettingsSidebar.tsx
  app/ide-desktop/lib/dashboard/src/pages/dashboard/Dashboard.tsx
  app/ide-desktop/lib/dashboard/src/providers/ModalProvider.tsx
  app/ide-desktop/lib/dashboard/src/tailwind.css
  app/ide-desktop/lib/dashboard/src/text/english.json
  app/ide-desktop/lib/dashboard/tailwind.config.js
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#10373 Enshure we cleanup ProjectManager before creating a new one
  app/ide-desktop/lib/dashboard/src/App.tsx
  app/ide-desktop/lib/dashboard/src/services/LocalBackend.ts
  app/ide-desktop/lib/dashboard/src/services/ProjectManager.ts
Labels: CI: Keep up to date, CI: No changelog needed, --bug, g-dashboard

#10384 Fix horizontal scrolling in settings
  app/ide-desktop/lib/dashboard/src/layouts/Settings/SettingsSection.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/SettingsTab.tsx
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#10353 Implement markdown link syntax and "follow link" popup.
  CHANGELOG.md
  app/gui2/shared/ast/parse.ts
  app/gui2/src/bindings.ts
  app/gui2/src/components/FloatingSelectionMenu.vue
  app/gui2/src/components/GraphEditor/GraphNodeComment.vue
  app/gui2/src/components/MarkdownEditor/ImagePlugin/index.ts
  app/gui2/src/components/MarkdownEditor/MarkdownEditorImpl.vue
  app/gui2/src/components/MarkdownEditor/theme.css
  app/gui2/src/components/PlainTextEditor.vue
  app/gui2/src/components/lexical/LexicalContent.vue
  app/gui2/src/components/lexical/LinkPlugin/__tests__/LinkPlugin.test.ts
  app/gui2/src/components/lexical/LinkPlugin/autoMatcher.ts
  app/gui2/src/components/lexical/LinkPlugin/index.ts
  app/gui2/src/components/lexical/LinkToolbar.vue
  app/gui2/src/composables/domSelection.ts
  app/gui2/src/stores/graph/index.ts
  app/ide-desktop/lib/client/src/security.ts
Labels: CI: Ready to merge

#10319 Fixing Database tests and Snowflake Dialect - part 2 out of ...
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Type_Mapping.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Connection.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Dialect.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Type_Mapping.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Bench.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Group.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Suite.enso
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/AtomConstructor.java
  test/AWS_Tests/src/Main.enso
  test/AWS_Tests/src/Redshift_Spec.enso
  test/Base_Tests/src/Data/Round_Spec.enso
  test/Snowflake_Tests/src/Snowflake_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Add_Row_Number_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Aggregate_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Name_Edge_Cases_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Main.enso
  test/Table_Tests/src/Common_Table_Operations/Nothing_Spec.enso
  test/Table_Tests/src/Database/Main.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Database/SQLite_Spec.enso
  test/Table_Tests/src/Helpers/Table_Aggregate_Auto_Constructor.enso
  test/Table_Tests/src/In_Memory/Common_Spec.enso
  test/Table_Tests/src/Util.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10382 Fix missing dropdowns in constructor subexpressions
  app/gui2/package.json
  app/gui2/src/components/GraphEditor/widgets/WidgetFunction/__tests__/widgetFunctionCallInfo.test.ts
  app/gui2/src/components/GraphEditor/widgets/WidgetFunction/widgetFunctionCallInfo.ts
  app/gui2/src/components/widgets/DropdownWidget.vue
  app/gui2/src/util/callTree.ts
  app/gui2/vite.config.ts
  app/ide-desktop/lib/client/package.json
  app/ide-desktop/lib/dashboard/package.json
  package-lock.json
Labels: CI: Ready to merge, CI: No changelog needed

#10376 Hide dotfiles on Windows
  app/ide-desktop/lib/project-manager-shim/src/projectManagerShimMiddleware.ts
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/command/filesystem/FileSystemListCommand.scala
Labels: CI: Ready to merge, CI: No changelog needed

#10379 Fix importing `.enso-project` files
  app/ide-desktop/eslint.config.js
  app/ide-desktop/lib/client/src/bin/server.ts
  app/ide-desktop/lib/client/src/desktop-environment.ts
  app/ide-desktop/lib/client/src/project-management.ts
  app/ide-desktop/lib/dashboard/src/pages/dashboard/Dashboard.tsx
  app/ide-desktop/lib/project-manager-shim/src/projectManagement.ts
Labels: p-highest, CI: Ready to merge, CI: No changelog needed, --bug, --regression, g-dashboard

#10391 Fix infinite callstack while opening a popover
  app/ide-desktop/lib/dashboard/src/components/AriaComponents/Dialog/DialogStackProvider.tsx
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#10380 getPublicTruffleFile may yield an exception
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoFile.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/DataflowError.java
  test/Base_Tests/src/System/File_Spec.enso
Labels: CI: No changelog needed, CI: Clean build required

#10398 Add new icons
  app/gui2/src/assets/icons.svg
Labels: CI: No changelog needed

#10336 Rename Postgres environment variables
  build/build/src/postgres.rs
  test/Table_Tests/scripts/postgresssl/CreatePostgresSSL.sh
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Database/README.md
Labels: CI: No changelog needed

#10397 Fix background color
  app/ide-desktop/lib/dashboard/e2e/actions.ts
  app/ide-desktop/lib/dashboard/e2e/assetPanel.spec.ts
  app/ide-desktop/lib/dashboard/src/components/styled/Checkbox.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetPanel.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetProperties.tsx
  app/ide-desktop/lib/dashboard/src/layouts/AssetSearchBar.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Drive.tsx
  app/ide-desktop/lib/dashboard/src/layouts/SearchBar.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings.tsx
  app/ide-desktop/lib/dashboard/src/layouts/Settings/settingsData.tsx
  app/ide-desktop/lib/dashboard/src/tailwind.css
  app/ide-desktop/lib/dashboard/src/text/english.json
  app/ide-desktop/lib/dashboard/tailwind.config.js
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#10395 Resize handle corners are rounded
  app/gui2/src/components/DockPanel.vue
  app/gui2/src/components/ResizeHandles.vue
  app/gui2/src/components/VisualizationContainer.vue
Labels: CI: No changelog needed

#10308 Open multi-select when items are edited
  app/gui2/e2e/widgets.spec.ts
  app/gui2/shared/ast/mutableModule.ts
  app/gui2/shared/ast/tree.ts
  app/gui2/src/components/GraphEditor/NodeWidgetTree.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetText.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetVector.vue
  app/gui2/src/providers/interactionHandler.ts
  app/gui2/src/providers/widgetRegistry.ts
  app/gui2/src/providers/widgetRegistry/__tests__/editHandler.test.ts
  app/gui2/src/providers/widgetRegistry/editHandler.ts
  app/gui2/src/providers/widgetTree.ts
  app/gui2/src/util/ast/abstract.ts
Labels: CI: No changelog needed

#10352 Copied table-viz range pastes as Table component
  CHANGELOG.md
  app/gui2/src/components/GraphEditor/__tests__/clipboard.test.ts
  app/gui2/src/components/GraphEditor/clipboard.ts
  app/gui2/src/components/visualizations/TableVisualization.vue
Labels: CI: Ready to merge

#10405 Add zoom icon
  app/gui2/src/assets/icons.svg
Labels: CI: Ready to merge, CI: No changelog needed

#10403 Clear changelog
  CHANGELOG.md
Labels: CI: Ready to merge
