Repository enso-org/enso, pull requests merged in 2024-08, with the labels that each got.

#10637 Move selected rows state of Data Catalog to zustand store
  app/dashboard/src/App.tsx
  app/dashboard/src/components/dashboard/AssetRow.tsx
  app/dashboard/src/components/dashboard/AssetRow/assetRowUtils.tsx
  app/dashboard/src/components/dashboard/DirectoryNameColumn.tsx
  app/dashboard/src/components/dashboard/ProjectNameColumn.tsx
  app/dashboard/src/layouts/AssetsTable.tsx
  app/dashboard/src/layouts/AssetsTableContextMenu.tsx
  app/dashboard/src/layouts/Drive.tsx
  app/dashboard/src/layouts/DriveBar.tsx
  app/dashboard/src/providers/DriveProvider.tsx
  app/dashboard/src/utilities/AssetTreeNode.ts
  app/dashboard/src/utilities/set.ts
Labels: p-high, CI: Ready to merge, CI: No changelog needed, x-chore, g-dashboard, x-refactor

#10715 Dashboard improvements
  app/dashboard/e2e/actions.ts
  app/dashboard/e2e/actions/DrivePageActions.ts
  app/dashboard/e2e/api.ts
  app/dashboard/src/assets/close_tab.svg
  app/dashboard/src/components/AriaComponents/Text/Text.tsx
  app/dashboard/src/components/AriaComponents/Tooltip/Tooltip.tsx
  app/dashboard/src/components/Autocomplete.tsx
  app/dashboard/src/components/Dropdown.tsx
  app/dashboard/src/components/JSONSchemaInput.tsx
  app/dashboard/src/components/MenuEntry.tsx
  app/dashboard/src/components/SubmitButton.tsx
  app/dashboard/src/components/dashboard/AssetRow.tsx
  app/dashboard/src/components/dashboard/Permission.tsx
  app/dashboard/src/components/styled/Separator.tsx
  app/dashboard/src/components/styled/SettingsInput.tsx
  app/dashboard/src/configurations/inputBindings.ts
  app/dashboard/src/hooks/backendHooks.ts
  app/dashboard/src/hooks/contextMenuHooks.tsx
  app/dashboard/src/hooks/projectHooks.ts
  app/dashboard/src/layouts/AssetContextMenu.tsx
  app/dashboard/src/layouts/AssetProperties.tsx
  app/dashboard/src/layouts/AssetSearchBar.tsx
  app/dashboard/src/layouts/AssetVersions/AssetVersion.tsx
  app/dashboard/src/layouts/Editor.tsx
  app/dashboard/src/layouts/Labels.tsx
  app/dashboard/src/layouts/Settings/KeyboardShortcutsSettingsSection.tsx
  app/dashboard/src/layouts/Settings/MembersSettingsSection.tsx
  app/dashboard/src/layouts/Settings/MembersTable.tsx
  app/dashboard/src/layouts/Settings/SettingsInputEntry.tsx
  app/dashboard/src/layouts/Settings/UserGroupRow.tsx
  app/dashboard/src/layouts/Settings/UserGroupUserRow.tsx
  app/dashboard/src/layouts/Settings/UserGroupsSettingsSection.tsx
  app/dashboard/src/layouts/Settings/UserRow.tsx
  app/dashboard/src/layouts/Settings/settingsData.tsx
  app/dashboard/src/layouts/TabBar.tsx
  app/dashboard/src/layouts/UserBar.tsx
  app/dashboard/src/modals/InviteUsersModal/InviteUsersForm.tsx
  app/dashboard/src/modals/InviteUsersModal/InviteUsersModal.tsx
  app/dashboard/src/modals/ManagePermissionsModal.tsx
  app/dashboard/src/modals/UpsertDatalinkModal.tsx
  app/dashboard/src/pages/authentication/AuthenticationPage.tsx
  app/dashboard/src/pages/authentication/ForgotPassword.tsx
  app/dashboard/src/pages/authentication/Login.tsx
  app/dashboard/src/pages/authentication/Registration.tsx
  app/dashboard/src/pages/authentication/ResetPassword.tsx
  app/dashboard/src/pages/dashboard/Dashboard.tsx
  app/dashboard/src/services/LocalBackend.ts
  app/dashboard/src/services/ProjectManager.ts
  app/dashboard/src/services/RemoteBackend.ts
  app/dashboard/src/services/remoteBackendPaths.ts
  app/dashboard/src/tailwind.css
  app/dashboard/src/utilities/permissions.ts
  app/dashboard/tailwind.config.js
  app/ide-desktop/common/src/services/Backend.ts
  app/ide-desktop/common/src/text/english.json
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#10732 Keep subscription payment form open until plan is successful
  app/dashboard/src/components/ErrorBoundary.tsx
  app/dashboard/src/modules/payments/components/AddPaymentMethodForm.tsx
  app/dashboard/src/modules/payments/components/PlanSelector/PlanSelector.tsx
  app/dashboard/src/pages/authentication/ErrorScreen.tsx
  app/dashboard/src/pages/subscribe/Subscribe/Subscribe.tsx
  app/dashboard/src/pages/subscribe/SubscribeSuccess.tsx
  app/dashboard/src/providers/AuthProvider.tsx
  app/ide-desktop/common/src/text/english.json
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#10708 Propagate FS errors when creating a new project
  engine/language-server/src/main/scala/org/enso/languageserver/libraries/ProjectSettingsManager.scala
  engine/runner/src/main/java/org/enso/runner/Main.java
  lib/scala/library-manager-test/src/main/scala/org/enso/librarymanager/published/repository/DummyRepository.scala
  lib/scala/pkg/src/main/scala/org/enso/filesystem/FileSystem.scala
  lib/scala/pkg/src/main/scala/org/enso/pkg/Package.scala
Labels: CI: Ready to merge, CI: No changelog needed

#10743 Internal tests run with --disable-private-check
  build/build/src/enso.rs
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Extra_Imports.enso
  project/DistributionPackage.scala
  test/Base_Internal_Tests/README.md
  test/Base_Internal_Tests/package.yaml
  test/Base_Internal_Tests/src/Comparator_Spec.enso
  test/Base_Internal_Tests/src/Grapheme_Spec.enso
  test/Base_Internal_Tests/src/Input_Output_Spec.enso
  test/Base_Internal_Tests/src/Main.enso
  test/Base_Tests/src/Data/Dictionary_Spec.enso
  test/Base_Tests/src/Main.enso
  test/Base_Tests/src/Semantic/Equals_Spec.enso
  test/Base_Tests/src/System/Input_Stream_Spec.enso
Labels: CI: No changelog needed, CI: Clean build required

#10744 Fix UX issues with the subscribe dialog form
  app/dashboard/src/components/AriaComponents/Inputs/Selector/Selector.tsx
  app/dashboard/src/components/AriaComponents/Inputs/Selector/SelectorOption.tsx
  app/dashboard/src/components/AriaComponents/Inputs/variants.ts
  app/dashboard/src/components/AriaComponents/Text/Text.tsx
  app/dashboard/src/components/Stepper/Stepper.tsx
  app/dashboard/src/modules/payments/components/PlanSelector/components/PlanSelectorDialog.tsx
  app/ide-desktop/common/src/text/english.json
Labels: CI: No changelog needed, g-dashboard

#10690 Disable console logging for project-manager cli commands
  lib/scala/project-manager/src/main/resources/application.conf
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/command/CommandHandler.scala
Labels: CI: Ready to merge, CI: No changelog needed, -project-manager

#10740 Add org.enso.compiler.dumpIr system prop
  distribution/bin/enso
  distribution/bin/enso.bat
  docs/runtime-guide.md
  docs/runtime/README.md
  docs/runtime/compiler-ir.md
  engine/runner/src/main/java/org/enso/runner/Main.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/dump/IRDumper.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/dump/IRDumperPass.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/Passes.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/data/CompilerConfig.scala
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/TypeInferenceTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/dump/test/IRDumpTest.java
  engine/runtime/src/main/java/org/enso/interpreter/EnsoLanguage.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  tools/enso4igv/IGV.md
  tools/enso4igv/src/main/java/org/enso/tools/enso4igv/EnsoActionProvider.java
Labels: CI: Ready to merge, CI: No changelog needed

#10756 Implement full new-lambda syntax
  docs/syntax/functions.md
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/desugar/FunctionBindingTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/desugar/LambdaShorthandToLambdaTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/semantic/SuspendedArgumentsTest.scala
  engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java
  lib/rust/parser/debug/tests/parse.rs
  lib/rust/parser/src/lexer.rs
  lib/rust/parser/src/macros.rs
  lib/rust/parser/src/macros/built_in.rs
  lib/rust/parser/src/macros/resolver.rs
  lib/rust/parser/src/syntax.rs
  lib/rust/parser/src/syntax/operator/precedence_resolver.rs
  lib/rust/parser/src/syntax/statement.rs
  lib/rust/parser/src/syntax/statement/function_def.rs
  lib/rust/parser/src/syntax/statement/type_def.rs
  lib/rust/parser/src/syntax/tree.rs
  lib/rust/parser/src/syntax/tree/block.rs
  lib/rust/parser/src/syntax/treebuilding.rs
  lib/rust/parser/src/syntax/treebuilding/block.rs
  lib/rust/parser/src/syntax/treebuilding/group.rs
  lib/rust/parser/src/syntax/treebuilding/whitespace.rs
Labels: CI: Ready to merge, CI: No changelog needed

#10687 Debug Ydoc/LS interaction without making code changes
  app/.example.env
  app/dashboard/package.json
  app/gui2/package.json
  app/gui2/shared/languageServer.ts
  app/gui2/src/stores/project/index.ts
  app/gui2/vite.config.ts
  app/gui2/ydoc-server/index.ts
  app/gui2/ydoc-server/indexPolyglot.ts
  app/gui2/ydoc-server/languageServerSession.ts
  app/gui2/ydoc-server/ydoc.ts
  app/ide-desktop/client/package.json
  app/ide-desktop/client/src/server.ts
  lib/java/ydoc-server/src/main/java/org/enso/ydoc/Ydoc.java
  pnpm-lock.yaml
Labels: CI: No changelog needed, CI: Clean build required

#10746 Import all available libraries in --repl mode
  CHANGELOG.md
  engine/common/src/main/java/org/enso/common/MethodNames.java
  engine/polyglot-api/src/main/java/org/enso/polyglot/PolyglotContext.java
  engine/polyglot-api/src/main/scala/org/enso/polyglot/PolyglotContext.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/TopScope.scala
  engine/runner/src/main/java/org/enso/runner/Main.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/PackageRepository.scala
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/runtime/ListLibrariesTest.java
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/ReplTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/TopLevelScope.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/DefaultPackageRepository.scala
  lib/java/test-utils/src/main/java/org/enso/test/utils/ProjectUtils.java
  lib/scala/library-manager/src/main/scala/org/enso/librarymanager/DefaultLibraryProvider.scala
  lib/scala/library-manager/src/main/scala/org/enso/librarymanager/ResolvingLibraryProvider.scala
Labels: CI: Ready to merge, CI: Clean build required

#10733 Initial Tableau Reading Support
  CHANGELOG.md
  build.sbt
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso
  distribution/lib/Standard/Tableau/0.0.0-dev/THIRD-PARTY/COPYRIGHT-HYPERAPI
  distribution/lib/Standard/Tableau/0.0.0-dev/THIRD-PARTY/NOTICE
  distribution/lib/Standard/Tableau/0.0.0-dev/THIRD-PARTY/licenses/APACHE2.0
  distribution/lib/Standard/Tableau/0.0.0-dev/THIRD-PARTY/net.java.dev.jna.jna-5.14.0/NOTICES
  distribution/lib/Standard/Tableau/0.0.0-dev/THIRD-PARTY/net.java.dev.jna.jna-platform-5.14.0/NOTICES
  distribution/lib/Standard/Tableau/0.0.0-dev/package.yaml
  distribution/lib/Standard/Tableau/0.0.0-dev/src/Hyper_Column.enso
  distribution/lib/Standard/Tableau/0.0.0-dev/src/Hyper_Errors.enso
  distribution/lib/Standard/Tableau/0.0.0-dev/src/Hyper_File.enso
  distribution/lib/Standard/Tableau/0.0.0-dev/src/Hyper_Table.enso
  distribution/lib/Standard/Tableau/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Tableau/0.0.0-dev/src/Tableau_Format.enso
  project/Editions.scala
  project/StdBits.scala
  std-bits/base/src/main/java/org/enso/base/arrays/LongArrayList.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/EnsoSecretHelper.java
  std-bits/table/src/main/java/org/enso/table/data/table/join/JoinResult.java
  std-bits/tableau/src/main/java/org/enso/tableau/HyperQueryError.java
  std-bits/tableau/src/main/java/org/enso/tableau/HyperReader.java
  std-bits/tableau/src/main/java/org/enso/tableau/HyperTable.java
  std-bits/tableau/src/main/java/org/enso/tableau/HyperTableColumn.java
  std-bits/tableau/src/main/java/org/enso/tableau/HyperTableNotFound.java
  std-bits/tableau/src/main/java/org/enso/tableau/OSPlatform.java
  std-bits/tableau/src/main/java/org/enso/tableau/TableColumnBuilder.java
  std-bits/tableau/src/main/java/org/enso/tableau/TableauFormatSPI.java
  test/Tableau_Tests/data/empty.hyper
  test/Tableau_Tests/data/names.hyper
  test/Tableau_Tests/package.yaml
  test/Tableau_Tests/src/Main.enso
  test/Tableau_Tests/src/Read_Spec.enso
  test/Tableau_Tests/src/Structure_Spec.enso
  tools/legal-review/Tableau/files-add/COPYRIGHT-HYPERAPI
  tools/legal-review/Tableau/net.java.dev.jna.jna-5.14.0/copyright-keep
  tools/legal-review/Tableau/net.java.dev.jna.jna-platform-5.14.0/copyright-ignore
  tools/legal-review/Tableau/net.java.dev.jna.jna-platform-5.14.0/copyright-keep
  tools/legal-review/Tableau/net.java.dev.jna.jna-platform-5.14.0/copyright-keep-context
  tools/legal-review/Tableau/report-state
  tools/legal-review/Tableau/reviewed-licenses/Apache-2.0
Labels: CI: Ready to merge, CI: Clean build required

#10771 Help tab
  app/dashboard/src/layouts/TabBar.tsx
  app/gui2/e2e/rightPanel.spec.ts
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/components/ComponentDocumentation.vue
  app/gui2/src/components/DockPanel.vue
  app/gui2/src/components/DocumentationEditor.vue
  app/gui2/src/components/DocumentationPanel.vue
  app/gui2/src/components/DocumentationPanel/DocsBreadcrumb.vue
  app/gui2/src/components/DocumentationPanel/DocsBreadcrumbs.vue
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/NodeWidgetTree.vue
  app/gui2/src/composables/selection.ts
  app/gui2/src/stores/graph/graphDatabase.ts
  app/ide-desktop/common/package.json
  app/ide-desktop/common/src/utilities/style/__tests__/tabBar.test.ts
  app/ide-desktop/common/src/utilities/style/tabBar.ts
  pnpm-lock.yaml
Labels: CI: Ready to merge, CI: No changelog needed

#10555 WithWarnings uses EnsoHashMap to speed things up
  build.sbt
  distribution/lib/Standard/Base/0.0.0-dev/src/Warning.enso
  engine/interpreter-dsl-test/src/test/java/org/enso/interpreter/dsl/test/InliningBuiltinsTest.java
  engine/runtime-benchmarks/src/main/java/org/enso/compiler/benchmarks/Utils.java
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/WarningBenchmarks.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/job/VisualizationResult.java
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/WarningsTest.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/IndirectInvokeCallableNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/IndirectInvokeConversionNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/IndirectInvokeMethodNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeCallableNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeConversionNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/dispatch/CallOptimiserNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/dispatch/LoopingCallOptimiserNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/dispatch/SimpleCallOptimiserNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/CaseNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/syntax/HostValueToEnsoNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/io/PrintlnNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsComplexNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsSimpleNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/HashCodeNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/LessThanNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/SortVectorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/util/ExpectStringNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/control/TailCallException.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/ArrayRope.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/Atom.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/InstantiateNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/hash/EnsoHashMap.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/hash/EnsoHashMapBuilder.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/hash/HashMapInsertAllNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/hash/HashMapInsertNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/hash/HashMapSizeNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/Array.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/ArrayBuilder.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/ArrayLikeAtNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/ArrayLikeHelpers.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/ArrayLikeLengthNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/ArraySlice.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/Vector.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/Warning.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/WithWarnings.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/library/dispatch/TypeOfNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/type/Types.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/warning/AppendWarningNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/warning/GetAllWarningsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/warning/LimitReachedNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/warning/SetWarningsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/warning/Warning.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/warning/WarningsLibrary.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/warning/WithWarnings.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/AcceptsWarning.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/BuiltinMethod.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/MethodProcessor.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/builtins/SpecializedMethodParameter.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/builtins/SpecializedMethodsGenerator.java
  test/Base_Tests/src/Semantic/Warnings_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#10766 Fix doc editor sync
  app/gui2/src/components/MarkdownEditor/markdown.ts
  app/gui2/src/components/PlainTextEditor.vue
  app/gui2/src/components/lexical/sync.ts
Labels: CI: Ready to merge, CI: No changelog needed

#10601 Switch from applying optimistic updates to invalidating queries
  app/.vscode/react.code-snippets
  app/dashboard/e2e/api.ts
  app/dashboard/src/App.tsx
  app/dashboard/src/authentication/service.ts
  app/dashboard/src/components/ErrorBoundary.tsx
  app/dashboard/src/components/Root.tsx
  app/dashboard/src/components/UIProviders.tsx
  app/dashboard/src/components/dashboard/AssetRow.tsx
  app/dashboard/src/components/dashboard/DatalinkNameColumn.tsx
  app/dashboard/src/components/dashboard/DirectoryNameColumn.tsx
  app/dashboard/src/components/dashboard/FileNameColumn.tsx
  app/dashboard/src/components/dashboard/Permission.tsx
  app/dashboard/src/components/dashboard/ProjectNameColumn.tsx
  app/dashboard/src/components/dashboard/SecretNameColumn.tsx
  app/dashboard/src/components/dashboard/column/LabelsColumn.tsx
  app/dashboard/src/hooks/backendHooks.ts
  app/dashboard/src/index.tsx
  app/dashboard/src/layouts/AssetPanel.tsx
  app/dashboard/src/layouts/AssetProperties.tsx
  app/dashboard/src/layouts/AssetSearchBar.tsx
  app/dashboard/src/layouts/AssetsTable.tsx
  app/dashboard/src/layouts/Labels.tsx
  app/dashboard/src/layouts/Settings.tsx
  app/dashboard/src/layouts/Settings/ActivityLogSettingsSection.tsx
  app/dashboard/src/layouts/Settings/MembersSettingsSection.tsx
  app/dashboard/src/layouts/Settings/MembersTable.tsx
  app/dashboard/src/layouts/Settings/OrganizationProfilePictureInput.tsx
  app/dashboard/src/layouts/Settings/ProfilePictureInput.tsx
  app/dashboard/src/layouts/Settings/UserGroupsSettingsSection.tsx
  app/dashboard/src/modals/InviteUsersModal/InviteUsersForm.tsx
  app/dashboard/src/modals/ManageLabelsModal.tsx
  app/dashboard/src/modals/ManagePermissionsModal.tsx
  app/dashboard/src/modals/NewLabelModal.tsx
  app/dashboard/src/modals/NewUserGroupModal.tsx
  app/dashboard/src/modals/SetOrganizationNameModal.tsx
  app/dashboard/src/modals/TermsOfServiceModal.tsx
  app/dashboard/src/pages/authentication/Registration.tsx
  app/dashboard/src/utilities/LocalStorage.ts
Labels: CI: Ready to merge, CI: No changelog needed, p-low, g-dashboard, x-refactor

#10765 Attaching a warning to error is no op
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/WarningsTest.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/warning/AppendWarningNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/warning/Warning.java
Labels: CI: No changelog needed, CI: Clean build required

#10781 Make sqlserver temp tables work
  distribution/lib/Standard/AWS/0.0.0-dev/src/Database/Redshift/Internal/Redshift_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/JDBC_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload/Operations/Internal_Core.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/Internal/SQLServer_Connection.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/Internal/SQLServer_Dialect.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Connection.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Dialect.enso
  test/Microsoft_Tests/README.md
  test/Microsoft_Tests/src/SQLServer_Spec.enso
Labels: CI: No changelog needed, CI: Clean build required

#10778 Revert "Import all available libraries in --repl mode (#10746)"
  CHANGELOG.md
  engine/common/src/main/java/org/enso/common/MethodNames.java
  engine/polyglot-api/src/main/java/org/enso/polyglot/PolyglotContext.java
  engine/polyglot-api/src/main/scala/org/enso/polyglot/PolyglotContext.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/TopScope.scala
  engine/runner/src/main/java/org/enso/runner/Main.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/PackageRepository.scala
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/runtime/ListLibrariesTest.java
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/ReplTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/TopLevelScope.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/DefaultPackageRepository.scala
  lib/java/test-utils/src/main/java/org/enso/test/utils/ProjectUtils.java
  lib/scala/library-manager/src/main/scala/org/enso/librarymanager/DefaultLibraryProvider.scala
  lib/scala/library-manager/src/main/scala/org/enso/librarymanager/ResolvingLibraryProvider.scala
Labels: CI: Clean build required

#10787 Fix file open retry in ydocs server
  app/ydoc-server/src/languageServerSession.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui

#10789 Fix test report artifact upload error handling
  app/dashboard/e2e/actions.ts
  app/dashboard/e2e/actions/DrivePageActions.ts
  app/dashboard/e2e/assetsTableFeatures.spec.ts
  app/gui2/README.md
  app/gui2/src/components/DockPanel.vue
  build/ci_utils/src/actions/artifacts.rs
  build/cli/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#10724 Wip/mk/drive drilldown from enso
  app/gui2/src/components/visualizations/TableVisualization.vue
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Connection.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
  test/Visualization_Tests/src/Table_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10773 Fix flaky dashboard E2E tests
  app/dashboard/e2e/api.ts
  app/dashboard/e2e/labels.spec.ts
  app/dashboard/e2e/latestGithubReleases.json
  app/dashboard/e2e/pageSwitcher.spec.ts
  app/dashboard/tsconfig.json
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#10774 Table Editor Widget
  CHANGELOG.md
  app/gui2/e2e/widgets.spec.ts
  app/gui2/package.json
  app/gui2/src/components/GraphEditor/widgets/WidgetTableEditor.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetTableEditor/TableHeader.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetTableEditor/__tests__/tableNewArgument.test.ts
  app/gui2/src/components/GraphEditor/widgets/WidgetTableEditor/tableNewArgument.ts
  app/gui2/src/components/visualizations/TableVisualization.vue
  app/gui2/src/components/widgets/AgGridTableView.vue
  app/gui2/src/util/ast/__tests__/abstract.test.ts
  app/gui2/src/util/ast/abstract.ts
  app/gui2/src/util/autoBlur.ts
  app/ydoc-shared/src/ast/parse.ts
  app/ydoc-shared/src/ast/tree.ts
  app/ydoc-shared/src/util/data/result.ts
  pnpm-lock.yaml
Labels: CI: Ready to merge, x-new-feature, -gui

#10780 Flatten object hierarchy of AliasAnalysis metadata so it is accessible from Java
  engine/runtime-compiler/src/main/java/org/enso/compiler/context/NameResolutionAlgorithm.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/PassPersistance.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/LocalBindingsTyping.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/TypePropagation.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/context/LocalScope.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/AutomaticParallelism.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/DataflowAnalysis.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/DemandAnalysis.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/AliasMetadata.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/Info.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/graph/Graph.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/graph/GraphOccurrence.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/lint/UnusedBindings.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/optimise/LambdaConsolidate.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/FullyQualifiedNames.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/GlobalNames.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/analyse/AliasAnalysisTest.scala
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#10764 Text editing ranges specified in UTF16 code units
  build.sbt
  docs/language-server/protocol-language-server.md
  lib/scala/text-buffer/src/main/scala/org/enso/text/editing/RopeTextEditor.scala
  lib/scala/text-buffer/src/test/scala/org/enso/text/editing/EditorOpsSpec.scala
  lib/scala/text-buffer/src/test/scala/org/enso/text/editing/RopeTextEditorSpec.scala
Labels: CI: Ready to merge, CI: No changelog needed

#10786 Do not default to development ydoc server in prod build.
  app/gui2/package.json
  app/gui2/src/composables/animation.ts
  app/gui2/vite.config.ts
Labels: CI: Ready to merge, CI: No changelog needed

#10795 Adding vectorized implementations to some Column operations
  distribution/lib/Standard/Examples/0.0.0-dev/data/.gitignore
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Bench.enso
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/bool/GenericBinaryOpReturningBoolean.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/datetime/TimeLikeBinaryOpReturningBoolean.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/datetime/TimeLikeCoalescingOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/arithmetic/MaxOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/arithmetic/MinOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/arithmetic/NumericBinaryOpCoalescing.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/arithmetic/NumericBinaryOpImplementation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/helpers/BigDecimalArrayAdapter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/helpers/BigIntegerArrayAdapter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/helpers/DoubleArrayAdapter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/text/CoalescingStringStringOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/text/StringBooleanOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/IsEmptyOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/IsNaNOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/NotOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/SpecializedStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/Storage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/StringStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/datetime/DateStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/datetime/DateTimeStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/datetime/TimeOfDayStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/AbstractLongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/BigDecimalStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/BigIntegerStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/DoubleStorage.java
  std-bits/table/src/main/java/org/enso/table/error/UnexpectedTypeException.java
  test/Benchmarks/src/Main.enso
  test/Benchmarks/src/Table/Column_Comparisons.enso
  test/Benchmarks/src/Table/Csv.enso
  test/Benchmarks/src/Table/Mixed_Operations.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/In_Memory/Bool_Spec.enso
  test/Table_Tests/src/In_Memory/Main.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10790 Clean up Text option from read and query
  distribution/lib/Standard/AWS/0.0.0-dev/src/Database/Redshift/Internal/Redshift_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/SQL_Query.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/Internal/SQLServer_Connection.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/Internal/SQLServer_Dialect.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Connection.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Dialect.enso
  test/Snowflake_Tests/src/Snowflake_Spec.enso
  test/Table_Tests/src/Database/Common/Audit_Spec.enso
  test/Table_Tests/src/Database/Common/Common_Spec.enso
  test/Table_Tests/src/Database/Common/Names_Length_Limits_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Database/SQLite_Spec.enso
  test/Table_Tests/src/Database/Types/Postgres_Type_Mapping_Spec.enso
  test/Visualization_Tests/src/Widgets/Database_Widgets_Spec.enso
Labels: CI: No changelog needed

#10798 Add --vm.D cmdline option
  build.sbt
  engine/runner/src/main/java/org/enso/runner/Main.java
  engine/runner/src/test/java/org/enso/runner/EngineMainTest.java
Labels: CI: No changelog needed

#10745 Various fixes to visualizations
  app/gui2/src/components/visualizations/TableVisualization.vue
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/Internal/SQLServer_Connection.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Snowflake_Connection.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Snowflake_Details.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Helpers.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#10802 Wheel/pan zooming maintains pointer scene pos
  app/gui2/src/composables/navigator.ts
Labels: CI: Ready to merge, CI: No changelog needed

#10800 Select node on menu click
  app/gui2/e2e/actions.ts
  app/gui2/e2e/collapsingAndEntering.spec.ts
  app/gui2/e2e/componentBrowser.spec.ts
  app/gui2/e2e/edgeRendering.spec.ts
  app/gui2/e2e/locate.ts
  app/gui2/e2e/typesOnNodeHover.spec.ts
  app/gui2/src/components/CircularMenu.vue
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/GraphNodes.vue
  app/gui2/src/components/SmallPlusButton.vue
  app/gui2/stories/CircularMenu.story.vue
Labels: CI: No changelog needed

#10785 Cache self argument
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/CachePreferenceAnalysis.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#10815 Add retries to tests depending on HTTP
  test/Base_Tests/src/Network/URI_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/IO/Data_Link_Formats_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10725 Mixed Decimal/Float operations throw error or attach warning
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Decimal.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numeric/Internal/Decimal_Internal.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Storage.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsAtomNode.java
  test/Base_Internal_Tests/src/Comparator_Spec.enso
  test/Base_Internal_Tests/src/Decimal_Constructor_Spec.enso
  test/Base_Internal_Tests/src/Main.enso
  test/Base_Tests/src/Data/Decimal_Spec.enso
Labels: CI: Ready to merge, CI: Clean build required

#10811 Dockerize NodeJS-based Ydoc
  tools/ci/README.md
  tools/ci/docker/ydoc-server/Dockerfile
  tools/ci/docker/ydoc-server/ydoc-server-entrypoint.sh
Labels: CI: Ready to merge, CI: No changelog needed

#10820 Adding support for creating Atoms in expressions
  CHANGELOG.md
  distribution/lib/Standard/AWS/0.0.0-dev/src/Database/Redshift/Internal/Redshift_Dialect.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Decimal.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numeric/Internal/Decimal_Internal.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Period.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Of_Day.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Period.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/DDL_Transaction.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload/Helpers/Prepare_Structure.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload/Operations/Delete.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload/Operations/Internal_Core.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload/Operations/Update.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/SQL_Query.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/Internal/SQLServer_Dialect.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Dialect.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Date_Time_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  distribution/lib/Standard/Tableau/0.0.0-dev/src/Hyper_Column.enso
  distribution/lib/Standard/Tableau/0.0.0-dev/src/Hyper_Errors.enso
  distribution/lib/Standard/Tableau/0.0.0-dev/src/Hyper_File.enso
  distribution/lib/Standard/Tableau/0.0.0-dev/src/Hyper_Table.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Main.enso
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/ValuesGenerator.java
  std-bits/table/src/main/antlr4/Expression.g4
  std-bits/table/src/main/java/org/enso/table/expressions/ExpressionVisitorImpl.java
  test/Base_Tests/src/Data/Time/Date_Spec.enso
  test/Base_Tests/src/Data/Time/Date_Time_Spec.enso
  test/Base_Tests/src/Data/Time/Time_Of_Day_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Date_Time_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Expression_Spec.enso
  test/Tableau_Tests/src/Read_Spec.enso
Labels: CI: Ready to merge

#10825 Add Regex link to all regex functions.
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Decimal.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Named_Pattern.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Extensions/Table_Conversions.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  test/Base_Tests/src/Data/Text/Regex_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10779 Detect outdated launcher
  engine/runner/src/main/java/org/enso/runner/Main.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/InstantiateNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/hash/HashMapInsertAllNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/warning/AppendWarningNode.java
Labels: CI: No changelog needed

#10829 Do not run enterprise engine and stdlib benchmarks
  .github/workflows/engine-benchmark.yml
  .github/workflows/std-libs-benchmark.yml
  build/build/src/ci_gen.rs
Labels: CI: No changelog needed

#10729 Store FramePointer in IR
  engine/runtime-compiler/src/main/java/org/enso/compiler/context/FramePointer.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/context/NameResolutionAlgorithm.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/dump/IRDumper.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/PassPersistance.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/TypePropagation.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/Passes.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/context/LocalScope.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/FramePointerAnalysis.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/analyse/FramePointerAnalysisTest.scala
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
Labels: CI: No changelog needed, CI: Clean build required

#10818 Fix `Count_Distinct` in Snowflake
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Dialect.enso
  test/Snowflake_Tests/src/Snowflake_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Aggregate_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10831 Sort toolbar rendering for narrow nodes
  app/gui2/src/components/TableVizToolbar.vue
  app/gui2/src/components/VisualizationContainer.vue
Labels: CI: Ready to merge, CI: No changelog needed

#10777 Reactive `Ast`s
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphNodeComment.vue
  app/gui2/src/components/GraphEditor/__tests__/clipboard.test.ts
  app/gui2/src/components/GraphEditor/__tests__/collapsing.test.ts
  app/gui2/src/components/GraphEditor/clipboard.ts
  app/gui2/src/components/GraphEditor/collapsing.ts
  app/gui2/src/components/GraphEditor/dragging.ts
  app/gui2/src/components/PlainTextEditor.vue
  app/gui2/src/composables/focus.ts
  app/gui2/src/composables/stackNavigator.ts
  app/gui2/src/stores/graph/__tests__/graphDatabase.test.ts
  app/gui2/src/stores/graph/graphDatabase.ts
  app/gui2/src/stores/graph/index.ts
  app/gui2/src/util/ast/__tests__/node.test.ts
  app/gui2/src/util/ast/__tests__/reactive.test.ts
  app/gui2/src/util/ast/node.ts
  app/gui2/src/util/ast/reactive.ts
  app/gui2/src/util/data/object.ts
  app/gui2/src/util/database/reactiveDb.ts
  app/gui2/src/util/reactivity.ts
  app/gui2/stories/GraphNode.story.vue
  app/ydoc-shared/src/ast/mutableModule.ts
  app/ydoc-shared/src/ast/parse.ts
  app/ydoc-shared/src/ast/tree.ts
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#10832 Tuning S3_File doc comments.
  distribution/lib/Standard/AWS/0.0.0-dev/src/AWS_Credential.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/Internal/S3_Path.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex.enso
  test/AWS_Tests/src/S3_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10837 Delay loading of AliasAnalysis data
  engine/runtime-compiler/src/main/scala/org/enso/compiler/context/LocalScope.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/FramePointerAnalysis.scala
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
Labels: CI: Ready to merge, CI: No changelog needed

#10834 Don't select node when output port is clicked.
  app/gui2/e2e/edgeRendering.spec.ts
  app/gui2/src/components/GraphEditor/GraphNode.vue
Labels: CI: No changelog needed, CI: Clean build required

#10814 New design of CB: two modes
  CHANGELOG.md
  app/gui2/e2e/componentBrowser.spec.ts
  app/gui2/src/bindings.ts
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/components/ComponentBrowser/ComponentEditor.vue
  app/gui2/src/components/ComponentBrowser/ComponentList.vue
  app/gui2/src/components/ComponentBrowser/scrolling.ts
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/NodeWidgetTree.vue
  app/gui2/src/components/SvgButton.vue
  app/gui2/src/stores/graph/graphDatabase.ts
  app/gui2/src/util/autoBlur.ts
  app/gui2/src/util/getIconName.ts
Labels: CI: Ready to merge, x-new-feature, -gui

#10836 Simplify declaration of module path in sbt build
  build.sbt
  project/JPMSPlugin.scala
  project/JPMSUtils.scala
Labels: CI: No changelog needed, CI: Clean build required

#10838 Fix multiselect stability
  app/gui2/src/providers/widgetRegistry/editHandler.ts
Labels: CI: Ready to merge, CI: No changelog needed

#10851 Y-docs: Fix write capability recovery
  app/ydoc-server/src/languageServerSession.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#10842 Print out warnings associated with local variables
  CHANGELOG.md
  engine/common/src/main/java/org/enso/common/ContextFactory.java
  engine/common/src/main/java/org/enso/common/DebugServerInfo.java
  engine/runner/src/main/java/org/enso/runner/Main.java
  engine/runtime-instrument-repl-debugger/src/main/java/org/enso/interpreter/instrument/ReplDebuggerInstrument.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/InsightForEnsoTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/PolyglotErrorTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/RootNamesTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/instrument/DebugServerInspectTest.java
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/InterpreterTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/DebugServerTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/ReplTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/function/BlockNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/UnresolvedConstructor.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/AtomConstructor.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/hash/HashMapToVectorNode.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
  lib/java/test-utils/src/main/java/org/enso/test/utils/ContextUtils.java
Labels: CI: Ready to merge

#10847 Update filtering in new CB
  CHANGELOG.md
  app/gui2/e2e/componentBrowser.spec.ts
  app/gui2/src/bindings.ts
  app/gui2/src/components/ComponentBrowser.vue
  app/gui2/src/components/ComponentBrowser/__tests__/component.test.ts
  app/gui2/src/components/ComponentBrowser/__tests__/filtering.test.ts
  app/gui2/src/components/ComponentBrowser/__tests__/input.test.ts
  app/gui2/src/components/ComponentBrowser/component.ts
  app/gui2/src/components/ComponentBrowser/filtering.ts
  app/gui2/src/components/ComponentBrowser/input.ts
  app/gui2/src/stores/suggestionDatabase/entry.ts
  app/gui2/src/util/data/range.ts
  app/gui2/stories/mockSuggestions.json
Labels: p-highest, CI: Ready to merge, -gui

#10853 Dropdown improvements
  app/gui2/e2e/locate.ts
  app/gui2/src/components/CircularMenu.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetTopLevelArgument.vue
  app/gui2/src/components/widgets/DropdownWidget.vue
Labels: CI: Ready to merge, CI: No changelog needed

#10857 Make tab accept the text input
  CHANGELOG.md
  app/gui2/src/components/GraphEditor/widgets/WidgetText.vue
Labels: CI: Ready to merge, --bug, -gui

#10839 Avoid copying IR nodes when no change is performed in passes
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/PrivateConstructorAnalysis.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/PrivateModuleAnalysis.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/PrivateSymbolsAnalysis.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/phase/exports/ExportSymbolAnalysis.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/MethodDefinitions.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/TypeNames.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/CompilerTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/core/ir/MetadataStorageTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/desugar/GenerateMethodBodiesTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/semantic/TextTest.scala
  engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java
  engine/runtime-parser/src/main/java/org/enso/compiler/core/ir/MetadataStorage.java
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/CallArgument.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/DefinitionArgument.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Empty.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Expression.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Function.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Literal.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Module.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Name.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Pattern.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Type.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/Application.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/Case.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/Comment.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/Error.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/Foreign.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/Operator.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/Section.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Conversion.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/ImportExport.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Pattern.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Redefined.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Resolution.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Syntax.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/errors/Unexpected.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/module/scope/Definition.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/module/scope/Export.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/module/scope/Import.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/module/scope/definition/Method.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/module/scope/imports/Polyglot.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/type/Set.scala
  engine/runtime-parser/src/test/java/org/enso/compiler/core/IrPersistanceTest.java
  engine/runtime-suggestions/src/main/scala/org/enso/compiler/suggestions/SuggestionBuilder.scala
Labels: CI: No changelog needed

#10477 User & Team spaces
  app/dashboard/e2e/actions/DrivePageActions.ts
  app/dashboard/e2e/api.ts
  app/dashboard/e2e/membersSettings.spec.ts
  app/dashboard/src/assets/person.svg
  app/dashboard/src/components/AriaComponents/Button/Button.tsx
  app/dashboard/src/components/AriaComponents/Button/ButtonGroup.tsx
  app/dashboard/src/components/Input.tsx
  app/dashboard/src/components/dashboard/AssetRow.tsx
  app/dashboard/src/components/dashboard/Permission.tsx
  app/dashboard/src/components/dashboard/ProjectIcon.tsx
  app/dashboard/src/components/dashboard/ProjectNameColumn.tsx
  app/dashboard/src/components/dashboard/column/LabelsColumn.tsx
  app/dashboard/src/components/dashboard/column/SharedWithColumn.tsx
  app/dashboard/src/components/dashboard/columnHeading/SharedWithColumnHeading.tsx
  app/dashboard/src/hooks/backendHooks.ts
  app/dashboard/src/layouts/AssetContextMenu.tsx
  app/dashboard/src/layouts/AssetProperties.tsx
  app/dashboard/src/layouts/AssetsTable.tsx
  app/dashboard/src/layouts/AssetsTableContextMenu.tsx
  app/dashboard/src/layouts/CategorySwitcher.tsx
  app/dashboard/src/layouts/CategorySwitcher/Category.ts
  app/dashboard/src/layouts/Chat.tsx
  app/dashboard/src/layouts/Drive.tsx
  app/dashboard/src/layouts/DriveBar.tsx
  app/dashboard/src/layouts/Settings.tsx
  app/dashboard/src/layouts/Settings/ChangePasswordForm.tsx
  app/dashboard/src/layouts/Settings/MembersTable.tsx
  app/dashboard/src/layouts/Settings/UserRow.tsx
  app/dashboard/src/modals/InviteUsersModal/InviteUsersModal.tsx
  app/dashboard/src/modals/ManageLabelsModal.tsx
  app/dashboard/src/modals/ManagePermissionsModal.tsx
  app/dashboard/src/pages/dashboard/Dashboard.tsx
  app/dashboard/src/providers/AuthProvider.tsx
  app/dashboard/src/providers/BackendProvider.tsx
  app/dashboard/src/providers/DriveProvider.tsx
  app/dashboard/src/providers/ProjectsProvider.tsx
  app/dashboard/src/services/LocalBackend.ts
  app/dashboard/src/services/ProjectManager.ts
  app/dashboard/src/services/RemoteBackend.ts
  app/dashboard/src/services/remoteBackendPaths.ts
  app/dashboard/src/utilities/fileInfo.ts
  app/dashboard/src/utilities/path.ts
  app/dashboard/src/utilities/permissions.ts
  app/ide-desktop/common/src/services/Backend.ts
  app/ide-desktop/common/src/text/english.json
  app/ide-desktop/common/src/text/index.ts
  app/ide-desktop/common/src/utilities/permissions.ts
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#10762 Updating Cloud integration to new directory structure
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Enso_Path.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Existing_Enso_Asset.enso
  test/AWS_Tests/data/credentials-with-secrets.datalink
  test/AWS_Tests/src/S3_Spec.enso
  test/Base_Tests/src/Network/Enso_Cloud/Cloud_Tests_Setup.enso
  test/Base_Tests/src/Network/Enso_Cloud/Enso_File_Spec.enso
  test/Base_Tests/src/Network/Enso_Cloud/Secrets_Spec.enso
  tools/http-test-helper/src/main/java/org/enso/shttp/cloud_mock/AssetStore.java
  tools/http-test-helper/src/main/java/org/enso/shttp/cloud_mock/DirectoriesHandler.java
  tools/http-test-helper/src/main/java/org/enso/shttp/cloud_mock/PathResolver.java
  tools/http-test-helper/src/main/java/org/enso/shttp/cloud_mock/SecretsHandler.java
Labels: CI: Ready to merge, CI: No changelog needed

#10867 Fix circular menu z-index and position
  app/gui2/src/components/CircularMenu.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
Labels: CI: Ready to merge, CI: No changelog needed

#10869 Hotfix opening links in browser
  app/dashboard/src/components/Link.tsx
Labels: p-high, CI: Ready to merge, CI: No changelog needed, --regression, g-dashboard

#10872 Ensure clients get write capability
  engine/language-server/src/main/scala/org/enso/languageserver/text/CollaborativeBuffer.scala
Labels: CI: No changelog needed

#10876 Fullscreen improvements
  CHANGELOG.md
  app/gui2/e2e/fullscreenVisualisation.spec.ts
  app/gui2/src/components/BottomPanel.vue
  app/gui2/src/components/CodeEditor.vue
  app/gui2/src/components/DockPanel.vue
  app/gui2/src/components/DocumentationEditor.vue
  app/gui2/src/components/FullscreenButton.vue
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphNode.vue
  app/gui2/src/components/GraphEditor/GraphNodes.vue
  app/gui2/src/components/GraphEditor/GraphVisualization.vue
  app/gui2/src/components/VisualizationContainer.vue
  app/gui2/src/components/VisualizationPanel.vue
  app/gui2/src/components/WithFullscreenMode.vue
  app/gui2/src/providers/fullscreenContext.ts
  app/gui2/src/providers/visualizationConfig.ts
  app/gui2/src/stores/graph/index.ts
  app/gui2/stories/setup.ts
  app/ydoc-server/src/edits.ts
  app/ydoc-shared/src/yjsModel.ts
Labels: CI: Ready to merge

#10883 Ensure execution is scheduled after compilation
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/EditFileCmd.scala
Labels: CI: Ready to merge, CI: No changelog needed

#10879 Provide missing arguments when stepping into a function
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/FunctionCallInstrumentationNode.java
Labels: CI: Ready to merge, CI: No changelog needed

#10880 Enable IR caches in Language Server
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
Labels: CI: Ready to merge, CI: No changelog needed

#10858 IO.print without new line
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/IO.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Extra_Imports.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/IO_Helpers.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Test_Reporter.enso
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/instrument/IncrementalUpdatesTest.java
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeErrorsTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeInstrumentTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/semantic/DataflowErrorsTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/io/PrintlnNode.java
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/IO.enso
Labels: CI: Clean build required

#10891 Speeding up RuntimeVisualizationsTest by one minute
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
Labels: CI: No changelog needed

#10893 Fix S3 spec
  test/AWS_Tests/src/S3_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10894 Fix "Missing queryFn" error when reloading with project openn
  app/dashboard/src/components/dashboard/AssetRow.tsx
  app/dashboard/src/components/dashboard/ProjectIcon.tsx
  app/dashboard/src/hooks/projectHooks.ts
  app/dashboard/src/layouts/DriveBar.tsx
  app/dashboard/src/layouts/TabBar.tsx
Labels: p-high, CI: Ready to merge, CI: No changelog needed, --bug, --regression, g-dashboard

#10890 When there are no pendingItems for a KEEP_ALIVE period, stop RequestQueue observer thread
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/instrument/RuntimeManagementCleanupTest.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/ResourceManager.java
Labels: CI: No changelog needed

#10892 Include `projectName` in audit logs
  std-bits/base/src/main/java/org/enso/base/CurrentEnsoProject.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/audit/AuditLogMessage.java
  std-bits/database/src/main/java/org/enso/database/audit/CloudAuditedConnection.java
  test/Base_Tests/src/Network/Enso_Cloud/Audit_Log_Spec.enso
  test/Table_Tests/src/Database/Common/Audit_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10886 Move Connection classes out of Internal
  distribution/lib/Standard/AWS/0.0.0-dev/src/Database/Redshift/Redshift_Details.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Postgres.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Postgres_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/SQLite.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/SQLite_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Helpers.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/SQLServer_Connection.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/SQLServer_Details.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10841 `First`/`Last` support in Snowflake, and partially in SQLite
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Aggregate_Helper.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Common/Row_Number_Helpers.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/IR/Context.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Type_Mapping.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Dialect.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Aggregate_Column_Helper.enso
  test/Snowflake_Tests/src/Snowflake_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Aggregate_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Util.enso
  test/Table_Tests/src/Database/SQLite_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10902 Fix std benchmarks run
  build.sbt
  lib/scala/bench-processor/src/main/java/org/enso/benchmarks/processor/BenchProcessor.java
Labels: CI: No changelog needed, CI: Clean build required

#10884 Fix collapsed function renaming
  app/gui2/e2e/collapsingAndEntering.spec.ts
  app/gui2/e2e/suggestionUpdates.ts
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetApplication.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetFunction.vue
  app/gui2/src/components/GraphEditor/widgets/WidgetFunctionName.vue
  app/gui2/src/stores/suggestionDatabase/index.ts
  app/gui2/src/util/ast/node.ts
  app/ydoc-shared/src/ast/tree.ts
Labels: CI: Ready to merge, CI: No changelog needed

#10871 Initial enso changes to ScatterPlot
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Scatter_Plot.enso
  test/Visualization_Tests/src/Scatter_Plot_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10889 Fix deletion-failure bug (#10888)
  app/gui2/src/components/ColorPickerMenu.vue
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/components/GraphEditor/GraphEdges.vue
  app/gui2/src/composables/astDocumentation.ts
  app/gui2/src/stores/graph/index.ts
Labels: CI: Ready to merge, CI: No changelog needed

#10664 Support multiple local directories
  app/dashboard/src/App.tsx
  app/dashboard/src/assets/minus2.svg
  app/dashboard/src/assets/plus.svg
  app/dashboard/src/components/AriaComponents/Button/ButtonGroup.tsx
  app/dashboard/src/components/dashboard/AssetRow.tsx
  app/dashboard/src/components/dashboard/DirectoryNameColumn.tsx
  app/dashboard/src/components/dashboard/column/LabelsColumn.tsx
  app/dashboard/src/components/dashboard/column/SharedWithColumn.tsx
  app/dashboard/src/globals.d.ts
  app/dashboard/src/layouts/AssetContextMenu.tsx
  app/dashboard/src/layouts/AssetPanel.tsx
  app/dashboard/src/layouts/AssetProperties.tsx
  app/dashboard/src/layouts/AssetsTable.tsx
  app/dashboard/src/layouts/AssetsTableContextMenu.tsx
  app/dashboard/src/layouts/CategorySwitcher.tsx
  app/dashboard/src/layouts/CategorySwitcher/Category.ts
  app/dashboard/src/layouts/Drive.tsx
  app/dashboard/src/layouts/DriveBar.tsx
  app/dashboard/src/layouts/Labels.tsx
  app/dashboard/src/layouts/Settings.tsx
  app/dashboard/src/layouts/Settings/settingsData.tsx
  app/dashboard/src/modals/TermsOfServiceModal.tsx
  app/dashboard/src/pages/dashboard/Dashboard.tsx
  app/dashboard/src/providers/BackendProvider.tsx
  app/dashboard/src/providers/DriveProvider.tsx
  app/dashboard/src/providers/LocalStorageProvider.tsx
  app/dashboard/src/services/LocalBackend.ts
  app/dashboard/src/services/ProjectManager.ts
  app/dashboard/src/utilities/LocalStorage.ts
  app/dashboard/src/utilities/permissions.ts
  app/ide-desktop/common/src/services/Backend.ts
  app/ide-desktop/common/src/text/english.json
  app/ide-desktop/common/src/text/index.ts
Labels: p-medium, CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#10828 Simplify button variants
  app/dashboard/src/components/AriaComponents/Button/Button.tsx
  app/dashboard/src/components/ControlledInput.tsx
  app/dashboard/src/layouts/AssetPanel.tsx
  app/dashboard/src/layouts/AssetProperties.tsx
  app/dashboard/src/layouts/AssetSearchBar.tsx
  app/dashboard/src/layouts/Drive.tsx
  app/dashboard/src/layouts/DriveBar.tsx
  app/dashboard/src/layouts/Settings/KeyboardShortcutsSettingsSection.tsx
  app/dashboard/src/layouts/Settings/MembersSettingsSection.tsx
  app/dashboard/src/layouts/Settings/UserGroupsSettingsSection.tsx
  app/dashboard/src/layouts/UserBar.tsx
  app/dashboard/src/layouts/VersionChecker.tsx
  app/dashboard/src/modals/CaptureKeyboardShortcutModal.tsx
  app/dashboard/src/modals/ConfirmDeleteModal.tsx
  app/dashboard/src/modals/DuplicateAssetsModal.tsx
  app/dashboard/src/modals/EditAssetDescriptionModal.tsx
  app/dashboard/src/modals/InviteUsersModal/InviteUsersForm.tsx
  app/dashboard/src/modals/InviteUsersModal/InviteUsersSuccess.tsx
  app/dashboard/src/modals/InvitedToOrganizationModal.tsx
  app/dashboard/src/modals/NewLabelModal.tsx
  app/dashboard/src/modals/NewUserGroupModal.tsx
  app/dashboard/src/modals/UpsertDatalinkModal.tsx
  app/dashboard/src/modals/UpsertSecretModal.tsx
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#10772 Require accepting Terms of Service and Privacy Policy when registering
  app/dashboard/e2e/actions.ts
  app/dashboard/e2e/actions/RegisterPageActions.ts
  app/dashboard/e2e/assetPanel.spec.ts
  app/dashboard/e2e/loginLogout.spec.ts
  app/dashboard/e2e/loginScreen.spec.ts
  app/dashboard/src/App.tsx
  app/dashboard/src/components/Devtools/EnsoDevtools.tsx
  app/dashboard/src/modals/AgreementsModal.tsx
  app/dashboard/src/modals/TermsOfServiceModal.tsx
  app/dashboard/src/pages/authentication/Registration.tsx
  app/ide-desktop/common/src/text/english.json
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#10826 Column-level lexically-scoped CTE expressions
  distribution/lib/Standard/AWS/0.0.0-dev/src/Database/Redshift/Internal/Redshift_Dialect.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Runtime/Ref.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/IR/Context.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/IR/From_Spec.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/IR/Order_Descriptor.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/IR/Query.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/IR/SQL_Expression.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/IR/Traversal_Helpers.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Type_Mapping.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/Internal/SQLServer_Dialect.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Dialect.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/IsFiniteOperation.java
  test/AWS_Tests/src/Redshift_Spec.enso
  test/Base_Tests/src/Data/Numbers_Spec.enso
  test/Base_Tests/src/Runtime/Ref_Spec.enso
  test/Snowflake_Tests/src/Snowflake_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Filter_Spec.enso
  test/Table_Tests/src/Database/Common/IR_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Database/SQLite_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10874 Add Text.to_decimal
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Decimal.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  test/Base_Tests/src/Data/Decimal_Spec.enso
Labels: CI: Ready to merge

#10899 Benchmark and speed processing of polyglot java imports up
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/ExecCompilerTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/WarningsTest.java
  engine/runtime/src/main/java/org/enso/interpreter/node/MethodRootNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/argument/ReadArgumentCheckNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/ObjectEqualityBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/constant/ConstantObjectNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/constant/LazyObjectNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Error.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/DataflowError.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicException.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/util/CachingSupplier.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
  test/Benchmarks/src/Startup/Import_World.enso
  test/Benchmarks/src/Startup/Startup.enso
Labels: CI: No changelog needed, CI: Clean build required

#10905 Akka-related startup improvements
  build.sbt
  distribution/engine/THIRD-PARTY/NOTICE
  distribution/engine/THIRD-PARTY/com.typesafe.akka.akka-actor-typed_2.13-2.6.20/NOTICES
  distribution/engine/THIRD-PARTY/com.typesafe.akka.akka-http-spray-json_2.13-10.2.10/NOTICES
  distribution/engine/THIRD-PARTY/com.typesafe.akka.akka-slf4j_2.13-2.6.20/NOTICES
  distribution/engine/THIRD-PARTY/io.spray.spray-json_2.13-1.3.6/NOTICES
  distribution/project-manager/THIRD-PARTY/NOTICE
  distribution/project-manager/THIRD-PARTY/com.typesafe.akka.akka-actor-typed_2.13-2.6.20/NOTICES
  distribution/project-manager/THIRD-PARTY/com.typesafe.akka.akka-http-spray-json_2.13-10.2.10/NOTICES
  distribution/project-manager/THIRD-PARTY/com.typesafe.akka.akka-slf4j_2.13-2.6.20/NOTICES
  distribution/project-manager/THIRD-PARTY/io.spray.spray-json_2.13-1.3.6/NOTICES
  engine/language-server/src/main/resources/application.conf
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  lib/scala/json-rpc-server/src/main/scala/org/enso/jsonrpc/Server.scala
  tools/legal-review/engine/com.typesafe.akka.akka-actor-typed_2.13-2.6.20/copyright-ignore
  tools/legal-review/engine/com.typesafe.akka.akka-actor-typed_2.13-2.6.20/copyright-keep
  tools/legal-review/engine/com.typesafe.akka.akka-http-spray-json_2.13-10.2.10/copyright-ignore
  tools/legal-review/engine/com.typesafe.akka.akka-http-spray-json_2.13-10.2.10/copyright-keep
  tools/legal-review/engine/com.typesafe.akka.akka-slf4j_2.13-2.6.20/copyright-keep
  tools/legal-review/engine/io.spray.spray-json_2.13-1.3.6/copyright-add
  tools/legal-review/engine/io.spray.spray-json_2.13-1.3.6/copyright-ignore
  tools/legal-review/engine/io.spray.spray-json_2.13-1.3.6/copyright-keep-context
  tools/legal-review/engine/report-state
  tools/legal-review/project-manager/com.typesafe.akka.akka-actor-typed_2.13-2.6.20/copyright-ignore
  tools/legal-review/project-manager/com.typesafe.akka.akka-actor-typed_2.13-2.6.20/copyright-keep
  tools/legal-review/project-manager/com.typesafe.akka.akka-http-spray-json_2.13-10.2.10/copyright-keep
  tools/legal-review/project-manager/com.typesafe.akka.akka-slf4j_2.13-2.6.20/copyright-keep
  tools/legal-review/project-manager/io.spray.spray-json_2.13-1.3.6/copyright-add
  tools/legal-review/project-manager/io.spray.spray-json_2.13-1.3.6/copyright-ignore
  tools/legal-review/project-manager/io.spray.spray-json_2.13-1.3.6/copyright-keep-context
  tools/legal-review/project-manager/report-state
Labels: CI: No changelog needed

#10930 Update reflect-config.json to accomodate for akka changes
  lib/scala/project-manager/src/main/resources/META-INF/native-image/org/enso/projectmanager/reflect-config.json
Labels: CI: Ready to merge, CI: No changelog needed

#10918 Pending Audit Logs are sent in batches
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Audit_Log.enso
  lib/scala/downloader/src/test/java/org/enso/downloader/http/HttpDownloaderTest.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/CloudAPI.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/audit/AuditLog.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/audit/AuditLogAPI.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/audit/AuditLogApiAccess.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/audit/AuditLogMessage.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/audit/LogJobsQueue.java
  test/Base_Tests/README.md
  test/Base_Tests/src/Network/Enso_Cloud/Audit_Log_Spec.enso
  test/Base_Tests/src/Network/Enso_Cloud/Cloud_Tests_Setup.enso
  tools/http-test-helper/src/main/java/org/enso/shttp/HTTPTestHelperServer.java
  tools/http-test-helper/src/main/java/org/enso/shttp/cloud_mock/CloudMockSetup.java
  tools/http-test-helper/src/main/java/org/enso/shttp/cloud_mock/CloudRoot.java
  tools/http-test-helper/src/main/java/org/enso/shttp/cloud_mock/PostLogHandler.java
Labels: CI: Ready to merge, CI: No changelog needed

#10931 Temporary workaround for #10921
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
Labels: CI: Ready to merge, CI: No changelog needed

#10920 Fix viewport jumping when adding new nodes
  app/gui2/src/components/GraphEditor.vue
  app/gui2/src/composables/nodeCreation.ts
  app/gui2/src/stores/graph/index.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui

#10941 Small tweaks from QA
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Index_Sub_Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Java_Problems.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Simple_Expression.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  std-bits/table/src/main/java/org/enso/table/parsing/problems/CommonParseProblemAggregator.java
  std-bits/table/src/main/java/org/enso/table/parsing/problems/InvalidFormat.java
  test/Table_Tests/src/Formatting/Data_Formatter_Spec.enso
  test/Table_Tests/src/Formatting/Parse_Values_Spec.enso
Labels: CI: No changelog needed

#10912 Add vectorized rounding operation to Decimal columns
  CHANGELOG.md
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/BigDecimalRoundOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/SpecializedStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/BigDecimalStorage.java
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
Labels: CI: Ready to merge

#10928 Override CWD in `runEngineDistribution` to the parent of the project being run to avoid warning
  project/DistributionPackage.scala
Labels: CI: Ready to merge, CI: No changelog needed
