Repository enso-org/enso, pull requests merged in 2025-09, with the labels that each got.

#13903 Remove `refetchType: 'all'` to avoid unnecessary 'list directory' requests
  app/gui/src/dashboard/hooks/backendBatchedHooks.ts
  app/gui/src/dashboard/hooks/backendHooks.ts
  app/gui/src/project-view/composables/backend.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#13908 Fix regression in startup benchmarks
  test/Benchmarks/src/Compiler/Compile.enso
  test/Benchmarks/src/Startup/Startup.enso
  test/Benchmarks/src/Utils.enso
Labels: CI: Ready to merge, CI: No changelog needed

#13909 Type of cache decides where it should be stored
  CHANGELOG.md
  docs/runtime/compiler-ir.md
  docs/runtime/ir-caching.md
  engine/common/src/main/java/org/enso/common/ContextFactory.java
  engine/common/src/main/java/org/enso/common/RuntimeOptions.java
  engine/runner/src/main/java/org/enso/runner/Main.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/context/CompilerContext.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime-compiler/src/test/java/org/enso/compiler/test/mock/MockCompilerContext.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/job/SerializeModuleJob.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/SerdeCompilerTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/SerializationManagerTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/SerializerTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/caches/HelloWorldCacheTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/caches/IRCacheLocationTest.java
  engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java
  engine/runtime/src/main/java/org/enso/interpreter/caches/ImportExportCache.java
  engine/runtime/src/main/java/org/enso/interpreter/caches/ModuleCache.java
  engine/runtime/src/main/java/org/enso/interpreter/caches/SuggestionsCache.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/TopLevelScope.java
  project/DistributionPackage.scala
  test/Benchmarks/src/Compiler/Compile.enso
Labels: CI: Ready to merge

#13904 Exchanging direct `ByteBuffer`s between the dual JVMs
  build.sbt
  lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/impl/OtherInteropType.java
  lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/impl/OtherJvmMessage.java
  lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/impl/OtherJvmObject.java
  lib/java/jvm-interop/src/test/java/org/enso/jvm/interop/impl/OtherJvmObjectTest.java
Labels: CI: Ready to merge, CI: No changelog needed, -compiler

#13900 No need for `jvm: true` when running `Generic_JDBC_Tests`
  distribution/lib/Standard/Generic_JDBC/0.0.0-dev/docs/api/Generic_JDBC_Connection.md
  distribution/lib/Standard/Generic_JDBC/0.0.0-dev/src/Generic_JDBC_Connection.enso
  test/Generic_JDBC_Tests/package.yaml
  test/Generic_JDBC_Tests/src/H2_Spec.enso
Labels: CI: No changelog needed, -libs-API-change-Generic_JDBC

#13936 Properly compute FQN for a module inside of a project
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/node/ProgramRootNodeTest.java
  engine/runtime/src/main/java/org/enso/interpreter/EnsoLanguage.java
  engine/runtime/src/main/java/org/enso/interpreter/node/ProgramRootNode.java
Labels: CI: No changelog needed

#13940 Revert "Remove `refetchType: 'all'` to avoid unnecessary 'list directory' requests (#13903)"
  app/gui/src/dashboard/hooks/backendBatchedHooks.ts
  app/gui/src/dashboard/hooks/backendHooks.ts
  app/gui/src/project-view/composables/backend.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#13808 Remove `framer-motion`
  app/common/src/text/english.json
  app/gui/env.d.ts
  app/gui/integration-test/dashboard/actions/index.ts
  app/gui/package.json
  app/gui/src/dashboard/components/AnimatedBackground.tsx
  app/gui/src/dashboard/components/Check/Check.tsx
  app/gui/src/dashboard/components/Checkbox/Checkbox.tsx
  app/gui/src/dashboard/components/Devtools/EnsoDevtoolsImpl.tsx
  app/gui/src/dashboard/components/Devtools/EnsoDevtoolsProvider.tsx
  app/gui/src/dashboard/components/Dialog/Dialog.tsx
  app/gui/src/dashboard/components/Dialog/Popover.tsx
  app/gui/src/dashboard/components/Dialog/utilities.ts
  app/gui/src/dashboard/components/EditableSpan.tsx
  app/gui/src/dashboard/components/FilePathInput.tsx
  app/gui/src/dashboard/components/Inputs/Password/Password.tsx
  app/gui/src/dashboard/components/Inputs/Selector/Selector.tsx
  app/gui/src/dashboard/components/Inputs/Selector/SelectorOption.tsx
  app/gui/src/dashboard/components/IsolateLayout.tsx
  app/gui/src/dashboard/components/Menu/Menu.tsx
  app/gui/src/dashboard/components/Menu/MenuItem.tsx
  app/gui/src/dashboard/components/SelectionBrush.tsx
  app/gui/src/dashboard/components/Stepper/Step.tsx
  app/gui/src/dashboard/components/Stepper/Stepper.tsx
  app/gui/src/dashboard/components/Stepper/StepperProvider.tsx
  app/gui/src/dashboard/components/Stepper/useStepperState.ts
  app/gui/src/dashboard/components/UIProviders.tsx
  app/gui/src/dashboard/hooks/measureHooks.ts
  app/gui/src/dashboard/hooks/throttleHooks.ts
  app/gui/src/dashboard/hooks/useRaf.ts
  app/gui/src/dashboard/layouts/AssetSearchBar.tsx
  app/gui/src/dashboard/layouts/AssetsTable.tsx
  app/gui/src/dashboard/layouts/CategorySwitcher.tsx
  app/gui/src/dashboard/layouts/Settings/FormEntry.tsx
  app/gui/src/dashboard/layouts/Settings/UserGroupsSettingsSection.tsx
  app/gui/src/dashboard/modals/ManageLabelsModal.tsx
  app/gui/src/dashboard/pages/dashboard/UserBar/UserBar.tsx
  app/gui/src/dashboard/pages/dashboard/components/TheModal.tsx
  app/gui/src/dashboard/test/setup.ts
  app/gui/src/dashboard/utilities/geometry.ts
  app/gui/src/dashboard/utilities/motion.ts
  app/gui/src/entrypoint.ts
  app/gui/src/providers/featureFlags.ts
  pnpm-lock.yaml
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#13941 Removing assert "The given scope must contain the given Def occurrence"
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/FrameAnalysisMeta.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/DebuggingEnsoTest.java
Labels: CI: No changelog needed

#13658 Command Palette
  CHANGELOG.md
  app/common/src/text/english.json
  app/gui/package.json
  app/gui/src/App.vue
  app/gui/src/components/AppContainer.vue
  app/gui/src/components/CommandPalette.vue
  app/gui/src/dashboard/configurations/inputBindings.ts
  app/gui/src/dashboard/hooks/menuHooks.ts
  app/gui/src/dashboard/layouts/AssetContextMenu.tsx
  app/gui/src/dashboard/layouts/AssetsTable.tsx
  app/gui/src/dashboard/layouts/AssetsTableContextMenu.tsx
  app/gui/src/dashboard/layouts/CategorySwitcher.tsx
  app/gui/src/dashboard/layouts/Settings/Sidebar.tsx
  app/gui/src/dashboard/layouts/Settings/data.tsx
  app/gui/src/dashboard/layouts/useGlobalContextMenuEntries.tsx
  app/gui/src/dashboard/pages/dashboard/Dashboard.tsx
  app/gui/src/dashboard/pages/dashboard/Drive/DriveBar/DriveBarToolbar.tsx
  app/gui/src/dashboard/pages/dashboard/UserBar/UserMenu.tsx
  app/gui/src/dashboard/pages/dashboard/components/Label.tsx
  app/gui/src/dashboard/pages/dashboard/components/column/components.tsx
  app/gui/src/dashboard/providers/InputBindingsProvider.tsx
  app/gui/src/dashboard/utilities/inputBindings.ts
  app/gui/src/project-view/bindings.ts
  app/gui/src/project-view/providers/action.ts
  app/gui/src/project-view/util/shortcuts.ts
  app/gui/src/providers/actions.ts
  app/gui/src/providers/react/globalProvider.tsx
  app/gui/src/providers/react/index.ts
  app/ide-desktop/client/src/index.ts
  pnpm-lock.yaml
Labels: CI: Ready to merge, x-new-feature, g-dashboard

#13848 Table expression: Autocomplete column names and static methods
  CHANGELOG.md
  app/gui/src/components/WithCurrentProject.vue
  app/gui/src/project-view/components/GraphEditor.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetFunction.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetFunction/widgetFunctionCallInfo.ts
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableMethod.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetText.vue
  app/gui/src/project-view/composables/tableColumns.ts
  app/gui/src/project-view/providers/functionInfo.ts
  app/gui/src/project-view/providers/languageSupportExtensions.ts
  app/gui/src/project-view/providers/tableContext.ts
  app/gui/src/project-view/stores/projectNames.ts
  app/gui/src/project-view/stores/suggestionDatabase/index.ts
  app/gui/src/project-view/util/codemirror/language.ts
  app/gui/src/project-view/util/codemirror/language/index.ts
  app/gui/src/project-view/util/codemirror/language/tableExpression.ts
  app/table-expression/src/__tests__/syntax.test.ts
  app/table-expression/src/autocomplete/__tests__/completionType.test.ts
  app/table-expression/src/autocomplete/__tests__/completions.test.ts
  app/table-expression/src/autocomplete/completionType.ts
  app/table-expression/src/autocomplete/index.ts
  app/table-expression/src/expression.grammar
  app/table-expression/src/highlight.ts
  app/table-expression/src/index.ts
  app/ydoc-shared/src/util/data/result.ts
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Internal/Expression_Statics.md
  distribution/lib/Standard/Table/0.0.0-dev/src/Expression.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Expression_Statics.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/docs/api/Widgets.md
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Widgets.enso
Labels: CI: Ready to merge, -libs-API-change-Table, -libs-API-change-Visualization

#13967 Disabeling test Project Duplicate.
  app/ide-desktop/client/tests/cloudWorkflow.spec.ts
Labels: CI: Ready to merge, CI: No changelog needed

#13971 Fix JSON Visualization issues
  CHANGELOG.md
  app/gui/src/dashboard/App.tsx
  app/gui/src/project-view/ProjectView.vue
  app/gui/src/project-view/components/GraphEditor/GraphVisualization.vue
  app/gui/src/project-view/components/visualizations/JSONVisualization/JSONVisualization.vue
  app/gui/src/project-view/components/visualizations/JSONVisualization/JsonArrayWidget.vue
  app/gui/src/project-view/components/visualizations/JSONVisualization/JsonObjectWidget.vue
  app/gui/src/project-view/components/visualizations/JSONVisualization/JsonValueWidget.vue
  app/gui/src/project-view/components/visualizations/JSONVisualization/index.ts
  app/gui/src/project-view/components/visualizations/JSONVisualization/types.ts
  app/gui/src/project-view/components/visualizations/TableVisualization.vue
  app/gui/src/project-view/components/visualizations/VisualizationHost.vue
  app/gui/src/project-view/providers/visualizationConfig.ts
  app/gui/src/project-view/stores/visualization/index.ts
Labels: CI: Ready to merge

#13838 Implement `sbt_build_engine_distribution` Bazel rule
  .github/workflows/bazel-build.yml
  BUILD.bazel
  MODULE.bazel
  MODULE.bazel.lock
  bazel_scripts/python_extract.bzl
  bazel_scripts/run_engine_distribution.bzl
  bazel_scripts/stdlibs.bzl
  build.sbt
  engine/common/src/main/java/org/enso/common/PythonHomeFinder.java
  engine/runtime/src/main/java/org/enso/interpreter/OptionsHelper.java
  lib/java/python-extract/BUILD.bazel
  lib/java/python-extract/src/main/java/org/enso/pyextract/PythonExtract.java
  maven_install.json
  patches/rules_graalvm_java24.patch
  patches/rules_graalvm_tool_toolchain.patch
  project/BazelSupport.scala
  project/DistributionPackage.scala
  project/LibraryManifestGenerator.scala
  test/Base_Tests/BUILD.bazel
Labels: CI: No changelog needed, CI: Clean build required

#13844 Implement functionality to create projects in dashboard
  .github/workflows/gui-checks.yml
  app/gui/project-manager-shim-middleware/index.ts
  app/gui/src/dashboard/services/ProjectManager/ProjectManager.ts
  app/gui/src/providers/featureFlags.ts
  app/gui/vite.config.ts
  app/project-manager-shim/package.json
  app/project-manager-shim/src/filesystem.ts
  app/project-manager-shim/src/index.ts
  app/project-manager-shim/src/projectService/__tests__/nameValidation.test.ts
  app/project-manager-shim/src/projectService/ensoRunner.ts
  app/project-manager-shim/src/projectService/index.ts
  app/project-manager-shim/src/projectService/nameValidation.ts
  app/project-manager-shim/src/projectService/projectRepository.ts
  pnpm-lock.yaml
Labels: CI: Ready to merge, CI: No changelog needed, -project-manager, -gui

#13969 Fix project/archive endpoint in project-manager
  lib/scala/pkg/src/main/java/module-info.java
Labels: CI: Ready to merge, CI: No changelog needed

#13952 Rewriting RuntimeStubsGenerator to Java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/RuntimeStubsGenerator.scala
Labels: CI: Ready to merge, CI: Keep up to date, CI: No changelog needed

#14007 Relax max IR cache sizes to 130 MB.
  project/IRCaches.scala
Labels: p-highest, CI: Ready to merge, CI: No changelog needed

#14004 Moving `|>` operator to Function
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Any.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Function.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Any.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time_Formatter.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Function.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/Generic/Writable_File.enso
Labels: CI: No changelog needed, -libs-API-change-Base

#14008 Fix undo/redo in doc panel, component comments
  app/gui/src/project-view/components/DocumentationEditor.vue
  app/gui/src/project-view/components/GraphEditor/GraphNodeComment.vue
  app/gui/src/project-view/util/codemirror/index.ts
  app/gui/src/project-view/util/codemirror/yCollab/index.ts
  app/gui/src/project-view/util/codemirror/yCollab/y-sync.ts
  app/ydoc-shared/src/yjsModel.ts
Labels: CI: Ready to merge, CI: No changelog needed

#13990 Sandbox&Sentry fixes
  .github/workflows/ide-packaging.yml
  CHANGELOG.md
  app/gui/src/entrypoint.ts
  app/ide-desktop/client/electron-builder-config.ts
  app/ide-desktop/client/src/config.ts
  app/ide-desktop/client/src/index.ts
  build_tools/build/src/ci_gen/job.rs
Labels: CI: Ready to merge

#13920 Forbid function expressions in statement context: Implementation
  app/gui/src/project-view/composables/__tests__/nodeCreation.test.ts
  app/gui/src/project-view/util/ast/__tests__/abstract.test.ts
  app/gui/src/project-view/util/ast/__tests__/codeEdit.test.ts
  app/gui/src/project-view/util/ast/__tests__/node.test.ts
  app/ydoc-shared/src/ast/parse.ts
  app/ydoc-shared/src/ast/tree.ts
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/ErrorCompilerTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/LazyAtomFieldTest.java
  lib/rust/parser/debug/src/test.rs
  lib/rust/parser/debug/tests/parse.rs
  lib/rust/parser/debug/tools/parse_all_enso_files.sh
  lib/rust/parser/src/lib.rs
  lib/rust/parser/src/macros/built_in.rs
  lib/rust/parser/src/macros/resolver.rs
  lib/rust/parser/src/syntax.rs
  lib/rust/parser/src/syntax/expression/apply.rs
  lib/rust/parser/src/syntax/expression/compound_token.rs
  lib/rust/parser/src/syntax/statement.rs
  lib/rust/parser/src/syntax/statement/function_def.rs
  lib/rust/parser/src/syntax/statement/type_def.rs
  lib/rust/parser/src/syntax/tree.rs
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#13976 Remove content reflow when resizing right panel
  CHANGELOG.md
  app/gui/integration-test/project-view/editorPanels.spec.ts
  app/gui/src/components/AppContainer/RightPanel.vue
Labels: CI: Ready to merge, -gui

#13974 Show confirmation dialog when dragging from Team category to User category
  app/gui/src/dashboard/hooks/cutAndPasteHooks.tsx
  app/gui/src/dashboard/layouts/AssetContextMenu.tsx
  app/gui/src/dashboard/layouts/CategorySwitcher.tsx
  app/gui/src/dashboard/layouts/Drive/Categories/Category.ts
  app/gui/src/dashboard/layouts/Drive/Categories/transferBetweenCategoriesHooks.tsx
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#14022 Turn `EnsoDateTimeFormatter` into an API facade
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time_Formatter.enso
  std-bits/base/src/main/java/org/enso/base/time/EnsoDateTimeFormatter.java
  std-bits/base/src/main/java/org/enso/base/time/EnsoDateTimeFormatterImpl.java
  std-bits/table/src/main/java/org/enso/table/formatting/DateFormatter.java
  std-bits/table/src/main/java/org/enso/table/formatting/DateTimeFormatter.java
  std-bits/table/src/main/java/org/enso/table/formatting/TimeFormatter.java
Labels: CI: No changelog needed

#14027 Add missing imports
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Dictionary.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Locale.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Read/Return_As.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Internal/Replacer.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Match.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time_Formatter.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/XML/XML_Format.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Data_Link.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Data_Link_Capabilities.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Data_Link_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_File_System_Impl.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_Secret.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_User.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Authentication.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Enso_File_Data_Link.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Enso_File_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Existing_Enso_Asset.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Utils.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Public_Utils.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Data_Read_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Ordering_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Time/Format/Parser.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Logging.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Meta.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Meta/Enso_Project.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Response_Body.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/URI.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Panic.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Runtime/Managed_Resource.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/Advanced/Restartable_Input_Stream.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/Encoding/Encoding_Resolver.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/Generic/File_Write_Strategy.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/Generic/Writable_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/Local_File_Write_Strategy.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/Write_Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File_Format.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File_Format_Metadata.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/Input_Stream.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/Internal/File_Builtins.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Warning.enso
Labels: CI: Ready to merge, CI: No changelog needed

#13998 Address Assets Table issues
  app/gui/src/dashboard/components/ContextMenu.tsx
  app/gui/src/dashboard/hooks/backendHooks.ts
  app/gui/src/dashboard/hooks/backendUploadFilesHooks.tsx
  app/gui/src/dashboard/hooks/projectHooks.ts
  app/gui/src/dashboard/layouts/AssetContextMenu.tsx
  app/gui/src/dashboard/layouts/AssetsTable.tsx
  app/gui/src/dashboard/layouts/AssetsTableCombinedContextMenu.tsx
  app/gui/src/dashboard/layouts/AssetsTableContextMenu.tsx
  app/gui/src/dashboard/layouts/Drive/Categories/transferBetweenCategoriesHooks.tsx
  app/gui/src/dashboard/pages/dashboard/components/AssetRow.tsx
  app/gui/src/dashboard/pages/dashboard/components/AssetRow/assetRowUtils.tsx
  app/gui/src/dashboard/pages/dashboard/components/column/DatalinkNameColumn.tsx
  app/gui/src/dashboard/pages/dashboard/components/column/DirectoryNameColumn.tsx
  app/gui/src/dashboard/pages/dashboard/components/column/FileNameColumn.tsx
  app/gui/src/dashboard/pages/dashboard/components/column/ProjectNameColumn.tsx
  app/gui/src/dashboard/pages/dashboard/components/column/SecretNameColumn.tsx
  app/gui/src/dashboard/pages/dashboard/components/column/column.ts
  app/gui/src/dashboard/providers/DriveProvider.tsx
  app/gui/src/dashboard/services/RemoteBackend.ts
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#14009 Allow multiple files upload from context menu
  app/gui/src/dashboard/layouts/useGlobalContextMenuEntries.tsx
Labels: CI: Ready to merge, CI: No changelog needed

#13984 Documenting unexpected cmdline opts handling of NI
  docs/infrastructure/README.md
  docs/infrastructure/dual_jvm.md
  docs/infrastructure/logging.md
  docs/infrastructure/native-image.md
  docs/infrastructure/rust.md
  docs/infrastructure/upgrading-graalvm.md
Labels: CI: No changelog needed

#14049 Hide implementations of HideableValue
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_Secret.enso
  std-bits/base/src/main/java/org/enso/base/enso_cloud/EnsoSecretHelper.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/HideableImpl.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/HideableValue.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/InterpretAsPrivateKey.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/SecretValueResolver.java
  std-bits/base/src/main/resources/META-INF/native-image/org/enso/base/reflect-config.json
  std-bits/microsoft/src/main/java/org/enso/microsoft/azure/AzureCredential.java
  std-bits/snowflake/src/main/java/org/enso/snowflake/SnowflakeCloudCredentials.java
Labels: CI: Ready to merge, CI: No changelog needed

#14054 Override test user auth file
  .github/workflows/ide-packaging-optional.yml
  .github/workflows/ide-packaging.yml
  build_tools/build/src/ci_gen/job.rs
Labels: p-highest, -ci

#14056 Prevent entering folder on double click
  app/gui/src/dashboard/components/EditableSpan.tsx
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#14060 Fix tab default width
  app/gui/src/components/AppContainer/RightPanel.vue
Labels: CI: Ready to merge, CI: No changelog needed

#14043 Document strava integration testing
  docs/README.md
  docs/integrations/README.md
  docs/integrations/strava.md
Labels: CI: Ready to merge, CI: No changelog needed

#14078 Fix blank arguments in signature
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Data/XML/XML_Format.md
  engine/runtime-compiler/src/main/java/org/enso/compiler/docs/DocsUtils.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/dump/test/DocsGenerateTest.java
Labels: p-highest, CI: Ready to merge, CI: No changelog needed, -libs-API-change-Base
