Repository enso-org/enso, pull requests merged in 2025-06, with the labels that each got.

#13180 More responsive dashboard
  app/gui/src/dashboard/layouts/CategorySwitcher.tsx
  app/gui/src/dashboard/layouts/Drive.tsx
  app/gui/src/dashboard/layouts/Settings/Settings.tsx
  app/gui/src/dashboard/pages/dashboard/Drive/DriveBar/DriveBar.tsx
  app/gui/src/dashboard/pages/dashboard/Drive/DriveBar/DriveBarNavigation.tsx
  app/gui/src/dashboard/pages/dashboard/UserBar/NotificationTray/NotificationTray.tsx
  app/gui/src/dashboard/pages/dashboard/UserBar/UserBar.tsx
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#13213 Continuing Operations Work
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/In_Memory_Column_Implementation.enso
  std-bits/table/src/main/java/org/enso/table/data/column/builder/BigDecimalBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/BigIntegerBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/BoolBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/DoubleBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/LongBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/StringBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/BinaryCoalescingOperationBool.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/BinaryCoalescingOperationNumeric.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/BinaryOperationBoolean.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/BinaryOperationNumeric.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/NumericColumnAdapter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/UnaryOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/UnaryOperationNumeric.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/binary/LogicalOperations.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/comparators/GenericComparators.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/comparators/NullComparators.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/comparators/NumericComparators.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/MapOperationStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/SpecializedIsInOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/TernaryMapOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/BigDecimalRoundOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/DoubleRoundOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/LongRoundOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/arithmetic/NumericBinaryOpImplementation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/arithmetic/NumericBinaryOpReturningBigDecimal.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/arithmetic/NumericBinaryOpReturningDouble.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/comparisons/EqualsComparison.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/comparisons/GreaterComparison.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/comparisons/GreaterOrEqualComparison.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/comparisons/LessComparison.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/comparisons/LessOrEqualComparison.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/comparisons/NumericComparison.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/text/CoalescingStringStringOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/text/StringStringOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/text/TextPartOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/NotOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/RoundOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/MixedStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/NullStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/SpecializedStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/Storage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/StringStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/AbstractLongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/BigDecimalStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/BigIntegerStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/DoubleStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/LongStorage.java
Labels: CI: Ready to merge, CI: No changelog needed

#13206 `Channel` connecting two `JVM` instances
  build.sbt
  distribution/engine/THIRD-PARTY/NOTICE
  distribution/engine/THIRD-PARTY/org.netbeans.api.org-openide-util-lookup-RELEASE180/NOTICES
  engine/runtime-compiler/src/main/java/module-info.java
  engine/runtime-instrument-runtime-server/src/main/java/module-info.java
  engine/runtime-instrument-runtime-server/src/main/java/org/enso/interpreter/instrument/runtime/server/RuntimeServerInstrument.java
  lib/java/os-environment/src/main/java/module-info.java
  lib/java/os-environment/src/main/java/org/enso/os/environment/jni/Channel.java
  lib/java/os-environment/src/main/java/org/enso/os/environment/jni/JVM.java
  lib/java/os-environment/src/main/java/org/enso/os/environment/jni/JVMPeer.java
  lib/java/os-environment/src/main/java/org/enso/os/environment/jni/TestMain.java
  lib/java/os-environment/src/test/java/org/enso/os/environment/TestCollectorFeature.java
  lib/java/os-environment/src/test/java/org/enso/os/environment/jni/LoadClassTest.java
  lib/java/persistance-dsl/src/main/java/org/enso/persist/impl/PersistableProcessor.java
  lib/scala/bench-processor/src/main/java/module-info.java
  lib/scala/bench-processor/src/main/java/org/enso/benchmarks/processor/BenchProcessor.java
  lib/scala/logging-service-logback/src/test/java/module-info.java
  project/JPMSUtils.scala
  tools/legal-review/engine/org.netbeans.api.org-openide-util-lookup-RELEASE180/copyright-keep
  tools/legal-review/engine/org.netbeans.api.org-openide-util-lookup-RELEASE180/files-ignore
  tools/legal-review/engine/report-state
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#13220 Prototype of YouTube embed
  app/gui/index.html
  app/gui/src/project-view/components/MarkdownEditor/DocumentationImage.vue
Labels: CI: Ready to merge, CI: No changelog needed

#13226 Do not extract projects exported from Local backend
  app/gui/src/dashboard/hooks/backendBatchedHooks.ts
  app/gui/src/dashboard/services/LocalBackend.ts
Labels: p-high, CI: Ready to merge, CI: No changelog needed, --bug, --regression, g-dashboard

#13230 Avoid the need for `-H:+ForeignAPISupport`
  build.sbt
  lib/java/os-environment/src/main/java/org/enso/os/environment/jni/Channel.java
Labels: CI: No changelog needed

#13228 Improve sbt clean
  build.sbt
  project/DistributionPackage.scala
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#13229 Move Is_In to new operation framework and tidy up
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/In_Memory_Column_Implementation.enso
  std-bits/table/src/main/java/org/enso/table/data/column/operation/IfOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/IsInOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/MapOperationStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/SpecializedIsInOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/bool/BooleanIsInOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/datetime/DateTimeIsInOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/isin/BigIntegerIsInOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/isin/DoubleIsInOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/isin/LongIsInOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/text/StringIsInOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/RoundOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/MixedStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/MixedStorageFacade.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/NullStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/ObjectStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/SpecializedStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/Storage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/StringStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/datetime/DateStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/datetime/DateTimeStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/datetime/TimeOfDayStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/AbstractLongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/BigDecimalStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/BigIntegerStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/DoubleStorage.java
  test/Base_Tests/polyglot-sources/enso-test-java-helpers/src/main/java/org/enso/table_test_helpers/ExplodingStorage.java
  test/Table_Tests/src/In_Memory/Table_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#13138 Support encodings in `Fixed_Width_Format`
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/System/Encoding/Encoding_Resolver.md
  distribution/lib/Standard/Base/0.0.0-dev/src/System/Encoding/Encoding_Resolver.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/Internal/Reporting_Stream_Decoder_Helper.enso
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Internal/Fixed_Width_Reader.md
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Fixed_Width_Reader.enso
  std-bits/base/src/main/java/org/enso/base/encoding/DecodingProblem.java
  std-bits/base/src/main/java/org/enso/base/encoding/DecodingProblemAggregator.java
  std-bits/base/src/main/java/org/enso/base/encoding/Encoding_Utils.java
  std-bits/base/src/main/java/org/enso/base/encoding/SimpleDecodingProblemAggregator.java
  std-bits/base/src/main/resources/META-INF/native-image/org/enso/base/reflect-config.json
  std-bits/table/src/main/java/org/enso/table/read/FixedWidthDecodingProblemAggregator.java
  std-bits/table/src/main/java/org/enso/table/read/FixedWidthReader.java
  test/Base_Tests/src/Data/Text/Encoding_Spec.enso
  test/Table_Tests/data/fixed-width/bad_chars.txt
  test/Table_Tests/data/fixed-width/fixed.txt
  test/Table_Tests/data/fixed-width/fixed2.txt
  test/Table_Tests/data/fixed-width/fixed4.txt
  test/Table_Tests/data/fixed-width/formatted.txt
  test/Table_Tests/data/fixed-width/inconsistent_lengths.txt
  test/Table_Tests/data/fixed-width/inconsistent_lengths2.txt
  test/Table_Tests/src/IO/Fixed_Width_Read_Spec.enso
Labels: CI: Ready to merge, CI: Clean build required, -libs-API-change-Base, -libs-API-change-Table

#13233 Remove debug logging
  distribution/lib/Standard/Base/0.0.0-dev/src/System/Internal/Reporting_Stream_Decoder_Helper.enso
Labels: CI: Ready to merge, CI: No changelog needed

#13231 Preparatory refactoring for #13002
  app/gui/integration-test/project-view/collapsingAndEntering.spec.ts
  app/gui/integration-test/project-view/componentBrowser.spec.ts
  app/gui/integration-test/project-view/rightPanel.spec.ts
  app/gui/integration-test/project-view/widgets.spec.ts
  app/gui/src/App.vue
  app/gui/src/project-view/bindings.ts
  app/gui/src/project-view/components/ActionButton.vue
  app/gui/src/project-view/components/ActionMenu.vue
  app/gui/src/project-view/components/BottomPanel.vue
  app/gui/src/project-view/components/ComponentBrowser.vue
  app/gui/src/project-view/components/ComponentMenu.vue
  app/gui/src/project-view/components/ContextMenu.vue
  app/gui/src/project-view/components/ContextMenuTrigger.vue
  app/gui/src/project-view/components/DockPanel.vue
  app/gui/src/project-view/components/DocumentationEditor.vue
  app/gui/src/project-view/components/ExtendedMenu.vue
  app/gui/src/project-view/components/GraphEditor.vue
  app/gui/src/project-view/components/GraphEditor/GraphEdges.vue
  app/gui/src/project-view/components/GraphEditor/GraphNode.vue
  app/gui/src/project-view/components/GraphEditor/GraphNode/nodeMessage.ts
  app/gui/src/project-view/components/GraphEditor/GraphNode/nodeVisualization.ts
  app/gui/src/project-view/components/GraphEditor/GraphNodeMessage.vue
  app/gui/src/project-view/components/GraphEditor/GraphVisualization.vue
  app/gui/src/project-view/components/GraphEditor/GraphVisualization/VisualizationToolbar.vue
  app/gui/src/project-view/components/GraphEditor/selectionActions.ts
  app/gui/src/project-view/components/MarkdownEditor.vue
  app/gui/src/project-view/components/MarkdownEditor/BlockTypeDropdown.vue
  app/gui/src/project-view/components/MarkdownEditor/MarkdownEditorImpl.vue
  app/gui/src/project-view/components/MarkdownEditor/blockTypeActions.ts
  app/gui/src/project-view/components/MarkdownEditor/formatActions.ts
  app/gui/src/project-view/components/MenuButton.vue
  app/gui/src/project-view/components/MenuEntry.vue
  app/gui/src/project-view/components/SelectionMenu.vue
  app/gui/src/project-view/components/SvgButton.vue
  app/gui/src/project-view/components/ToggleIcon.vue
  app/gui/src/project-view/components/TopBar.vue
  app/gui/src/project-view/components/widgets/FileBrowserWidget.vue
  app/gui/src/project-view/components/widgets/FileBrowserWidget/FileBrowserBreadcrumbs.vue
  app/gui/src/project-view/components/widgets/FileBrowserWidget/FileBrowserContent.vue
  app/gui/src/project-view/components/widgets/FileBrowserWidget/FileBrowserTopBar.vue
  app/gui/src/project-view/composables/events.ts
  app/gui/src/project-view/providers/__tests__/interactionHandler.test.ts
  app/gui/src/project-view/providers/action.ts
  app/gui/src/project-view/providers/interactionHandler.ts
  app/gui/src/project-view/providers/widgetRegistry/__tests__/editHandler.test.ts
  app/gui/src/project-view/stores/graph/index.ts
  app/ide-desktop/client/tests/localWorkflow.spec.ts
  app/ydoc-shared/src/util/types.ts
Labels: CI: Ready to merge, CI: No changelog needed

#13248 Fix visualization resizing
  app/gui/src/project-view/components/GraphEditor/GraphNode/nodeVisualization.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, --regression, -gui

#13116 Refactor `DB_Column` as 'subtype' of `Column`
  distribution/lib/Standard/Database/0.0.0-dev/docs/api/DB_Column.md
  distribution/lib/Standard/Database/0.0.0-dev/docs/api/DB_Table.md
  distribution/lib/Standard/Database/0.0.0-dev/docs/api/Internal/Helpers.md
  distribution/lib/Standard/Database/0.0.0-dev/docs/api/Internal/IR/Internal_Column.md
  distribution/lib/Standard/Database/0.0.0-dev/docs/api/Internal/Postgres/Postgres_Dialect.md
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Aggregate_Helper.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/DB_Column_Implementation.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Helpers.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/IR/Internal_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Type_Mapping.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Type_Refinements/DB_Column_Refinements.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Type_Refinements/DB_Table_Refinements.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Type_Refinements/Single_Column_DB_Table_Conversions.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Type_Refinements/Single_Column_Typed_DB_Table_Conversions.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Type_Refinements/Typed_DB_Column_Conversions.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Type_Refinements/Typed_DB_Column_Implementations.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/Internal/SQLServer_Dialect.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Dialect.enso
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Column.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/In_Memory_Column.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Internal/Column_Type_Helpers.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Internal/Filter_Condition_Helpers.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Internal/Table_Helpers.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Refined_Types/Numeric_Column.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Table.md
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Generate_Rows_Range.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/In_Memory_Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Column_Naming_Helper.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Column_Type_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Filter_Condition_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/In_Memory_Column_Implementation.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Type_Refinements/Column_Refinements.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Type_Refinements/Single_Column_Typed_Table_Conversions.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Type_Refinements/Typed_Column_Implementations.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Value_Type_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Refined_Types/Numeric_Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Test.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/EnsoMultiValueTest.java
  engine/runtime/src/main/java/org/enso/interpreter/node/typecheck/AllOfTypesCheckNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoMultiType.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoMultiValue.java
  test/Microsoft_Tests/src/SQLServer_Spec.enso
  test/Snowflake_Tests/src/Snowflake_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Numeric_Column_Spec.enso
  test/Table_Tests/src/Database/Codegen_Spec.enso
  test/Table_Tests/src/Database/Common/IR_Spec.enso
  test/Table_Tests/src/Database/Common/Single_Column_Table_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Util.enso
Labels: CI: Ready to merge, CI: No changelog needed, -libs-API-change-Database, -libs-API-change-Table

#13254 Component group argument default value editor
  .bazelrc
  CHANGELOG.md
  app/gui/src/project-view/components/DocumentationPanel.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetEnsoExpression.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetFunctionDef.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetFunctionDef/ArgumentRow.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetFunctionDef/argumentAst.ts
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection/SelectionSubmenu.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection/submenuEntry.ts
  app/gui/src/project-view/components/widgets/FileBrowserWidget/FileBrowserNameBar.vue
  app/gui/src/project-view/components/widgets/NumericInputWidget.vue
  app/gui/src/project-view/providers/widgetRegistry.ts
  app/gui/src/project-view/providers/widgetRegistry/editHandler.ts
  app/gui/src/project-view/stores/suggestionDatabase/index.ts
  app/gui/src/project-view/util/ast/__tests__/raw.test.ts
  app/gui/src/project-view/util/ast/aliasAnalysis.ts
  app/gui/src/project-view/util/ast/raw.ts
  app/gui/src/project-view/util/callTree.ts
  app/ydoc-shared/parser-codegen/codegen.ts
  app/ydoc-shared/parser-codegen/serialization.ts
  app/ydoc-shared/src/ast/parse.ts
  app/ydoc-shared/src/ast/parserSupport.ts
  app/ydoc-shared/src/ast/tree.ts
  app/ydoc-shared/src/util/data/opt.ts
Labels: CI: Ready to merge, -gui

#13240 Additional Fixed-Width changes
  CHANGELOG.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Errors.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Fixed_Width/Fixed_Width_Format.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Fixed_Width/Invalid_Fixed_Width_Rows.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Fixed_Width/On_Empty_Field.md
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Fixed_Width/Fixed_Width_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Fixed_Width/Invalid_Fixed_Width_Rows.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Fixed_Width/On_Empty_Field.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Fixed_Width_Reader.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Main.enso
  std-bits/table/src/main/java/org/enso/table/read/FixedWidthLineTooLongException.java
  std-bits/table/src/main/java/org/enso/table/read/FixedWidthReader.java
  std-bits/table/src/main/java/org/enso/table/read/FixedWidthReaderProblemAggregator.java
  std-bits/table/src/main/java/org/enso/table/read/InvalidFixedWidthRowsBehavior.java
  std-bits/table/src/main/java/org/enso/table/read/NoColumnNamesFoundException.java
  test/Table_Tests/data/fixed-width/empty_fields.txt
  test/Table_Tests/data/fixed-width/infer_headers_left.txt
  test/Table_Tests/data/fixed-width/infer_headers_no_headers.txt
  test/Table_Tests/data/fixed-width/infer_headers_one_left.txt
  test/Table_Tests/data/fixed-width/infer_headers_one_right.txt
  test/Table_Tests/data/fixed-width/infer_headers_right.txt
  test/Table_Tests/data/fixed-width/infer_headers_skip.txt
  test/Table_Tests/src/IO/Fixed_Width_Read_Spec.enso
Labels: CI: Ready to merge, CI: Clean build required, -libs-API-change-Table

#13257 Make 'Comment on PR' steps only run on PRs
  .github/workflows/gui-changed-files.yml
  .github/workflows/gui-checks.yml
  .github/workflows/gui-pull-request.yml
  .github/workflows/storybook.yml
Labels: CI: Ready to merge, CI: No changelog needed, -ci

#13247 Fixes on vue-react boundaries
  app/gui/src/dashboard/hooks/searchParamsStateHooks.ts
  app/gui/src/dashboard/layouts/AssetPanel/components/AssetProperties.tsx
  app/gui/src/dashboard/layouts/AssetPanel/components/AssetVersions.tsx
  app/gui/src/dashboard/layouts/AssetPanel/components/ProjectExecutionsCalendar.tsx
  app/gui/src/dashboard/layouts/AssetPanel/components/ProjectSessions.tsx
  app/gui/src/dashboard/layouts/AssetsTable.tsx
  app/gui/src/dashboard/layouts/Editor.tsx
  app/gui/src/dashboard/pages/authentication/ConfirmRegistration.tsx
  app/gui/src/dashboard/pages/authentication/ForgotPassword.tsx
  app/gui/src/dashboard/pages/authentication/Login.tsx
  app/gui/src/dashboard/pages/authentication/Registration.tsx
  app/gui/src/dashboard/pages/authentication/ResetPassword.tsx
  app/gui/src/dashboard/pages/dashboard/Dashboard.tsx
  app/gui/src/dashboard/pages/subscribe/Subscribe/Subscribe.tsx
  app/gui/src/dashboard/pages/subscribe/SubscribeSuccess.tsx
  app/gui/src/providers/__tests__/queryParams.test.ts
  app/gui/src/providers/queryParams.ts
  app/gui/src/providers/react/auth.ts
  app/gui/src/providers/react/backends.ts
  app/gui/src/providers/react/common.ts
  app/gui/src/providers/react/globalProvider.tsx
  app/gui/src/providers/react/index.ts
  app/gui/src/providers/react/queryParams.ts
  app/gui/src/providers/react/rightPanel.ts
  app/gui/src/providers/react/rightPanel.tsx
  app/gui/src/providers/react/router.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#13288 Fix black profile picture
  app/gui/src/providers/auth.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, --regression, g-dashboard

#13292 Fix `saveAccessToken`
  app/gui/src/providers/session.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, --regression, g-dashboard

#13289 Can test multiple projects in runtime-compiler/test
  engine/runtime-compiler/src/test/java/org/enso/compiler/test/MultipleProjectsTest.java
  engine/runtime-compiler/src/test/java/org/enso/compiler/test/SyntheticModulesTest.java
  engine/runtime-compiler/src/test/java/org/enso/compiler/test/mock/MockModule.java
  engine/runtime-compiler/src/test/java/org/enso/compiler/test/mock/MockPackageRepository.java
  engine/runtime-compiler/src/test/java/org/enso/compiler/test/mock/TestMockPackageRepository.java
Labels: CI: No changelog needed

#13238 Using `Channel` to load Java classes
  .github/workflows/enso4igv.yml
  build.sbt
  engine/common/src/main/java/module-info.java
  engine/common/src/main/java/org/enso/common/PolyglotSymbolResolver.java
  engine/common/src/main/java/org/enso/common/RuntimeOptions.java
  engine/launcher/src/main/scala/org/enso/launcher/distribution/DefaultManagers.scala
  engine/runner/src/main/java/module-info.java
  engine/runner/src/main/java/org/enso/runner/JavaFinder.java
  engine/runner/src/main/java/org/enso/runner/Main.java
  engine/runtime-compiler/src/test/java/org/enso/compiler/test/pass/PassPersistanceTest.java
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/semantic/ImportExportTest.scala
  engine/runtime-parser/src/test/java/org/enso/compiler/core/IrPersistanceTest.java
  engine/runtime/src/main/java/org/enso/interpreter/caches/CacheUtils.java
  engine/runtime/src/main/java/org/enso/interpreter/caches/ImportExportCache.java
  engine/runtime/src/main/java/org/enso/interpreter/caches/ModuleCache.java
  engine/runtime/src/main/java/org/enso/interpreter/caches/SuggestionsCache.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/test/java/org/enso/runtime/test/TypeMetadataPersistanceTest.java
  lib/java/jvm-channel/src/main/java/module-info.java
  lib/java/jvm-channel/src/main/java/org/enso/jvm/channel/Channel.java
  lib/java/jvm-channel/src/main/java/org/enso/jvm/channel/JNI.java
  lib/java/jvm-channel/src/main/java/org/enso/jvm/channel/JNIBoot.java
  lib/java/jvm-channel/src/main/java/org/enso/jvm/channel/JNIDirectives.java
  lib/java/jvm-channel/src/main/java/org/enso/jvm/channel/JNINativeInterface.java
  lib/java/jvm-channel/src/main/java/org/enso/jvm/channel/JVM.java
  lib/java/jvm-channel/src/main/java/org/enso/jvm/channel/PosixJVM.java
  lib/java/jvm-channel/src/main/java/org/enso/jvm/channel/WindowsJVM.java
  lib/java/jvm-channel/src/test/java/org/enso/jvm/channel/ChannelInSingleJvmTest.java
  lib/java/jvm-interop/src/main/java/module-info.java
  lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/OtherJvmException.java
  lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/OtherJvmMessage.java
  lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/OtherJvmObject.java
  lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/OtherJvmPool.java
  lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/OtherJvmResult.java
  lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/OtherJvmSymbolResolver.java
  lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/TruffleClassLoader.java
  lib/java/jvm-interop/src/main/resources/META-INF/native-image/org/enso/jvm/interop/reflect-config.json
  lib/java/jvm-interop/src/test/java/org/enso/jvm/interop/OtherJvmObjectTest.java
  lib/java/os-environment/src/main/java/module-info.java
  lib/java/os-environment/src/main/java/org/enso/os/environment/jni/JVMPeer.java
  lib/java/os-environment/src/main/java/org/enso/os/environment/jni/TestMain.java
  lib/java/os-environment/src/test/java/org/enso/os/environment/jni/LoadClassTest.java
  lib/java/persistance-dsl/src/main/java/org/enso/persist/impl/PersistableProcessor.java
  lib/java/persistance/src/main/java/org/enso/persist/Persistance.java
  lib/java/persistance/src/test/java/org/enso/persist/PersistanceTest.java
  lib/java/test-utils/src/main/java/org/enso/test/utils/ContextUtils.java
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/versionmanagement/DefaultDistributionConfiguration.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/TestDistributionConfiguration.scala
  lib/scala/runtime-version-manager/src/main/java/org/enso/runtimeversionmanager/components/GraalVersionManager.java
  lib/scala/runtime-version-manager/src/test/scala/org/enso/distribution/locking/ConcurrencyTest.scala
  lib/scala/runtime-version-manager/src/test/scala/org/enso/runtimeversionmanager/test/RuntimeVersionManagerTest.scala
Labels: CI: No changelog needed, CI: Clean build required

#13307 Adding new Google Sheets API
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso
  distribution/lib/Standard/Google_Api/0.0.0-dev/docs/api/Google_Sheets.md
  distribution/lib/Standard/Google_Api/0.0.0-dev/docs/api/Google_Sheets_Workbook.md
  distribution/lib/Standard/Google_Api/0.0.0-dev/src/Google_Sheets.enso
  distribution/lib/Standard/Google_Api/0.0.0-dev/src/Google_Sheets_Workbook.enso
  test/Google_Api_Test/package.yaml
  test/Google_Api_Test/src/Main.enso
Labels: -libs-API-change-Google_Api

#13287 Make Microsoft_Tests less flaky
  .github/workflows/engine-checks-nightly.yml
  .github/workflows/engine-checks-optional.yml
  .github/workflows/engine-checks.yml
  .github/workflows/extra-nightly-tests.yml
  build_tools/build/src/ci_gen.rs
  build_tools/build/src/ci_gen/job.rs
  build_tools/build/src/engine.rs
  build_tools/ci_utils/src/programs/docker.rs
  build_tools/cli/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#13322 Fix excel reading last sheet
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Workbook.enso
  std-bits/table/src/main/java/org/enso/table/read/ExcelReader.java
  test/Table_Tests/src/IO/Excel_Spec.enso
Labels: CI: No changelog needed

#13323 [GUI] Tidy up console, add widget devtools
  MODULE.bazel.lock
  app/gui/package.json
  app/gui/src/beforeMain.ts
  app/gui/src/components/AppContainer.vue
  app/gui/src/dashboard/hooks/gtagHooks.ts
  app/gui/src/dashboard/pages/dashboard/Drive/DriveBar/DriveBarNavigation.tsx
  app/gui/src/entrypoint.ts
  app/gui/src/project-view/components/ConditionalTeleport.vue
  app/gui/src/project-view/composables/navigator.ts
  app/gui/src/project-view/providers/widgetRegistry.ts
  app/gui/src/project-view/providers/widgetRegistry/devtools.ts
  app/gui/src/project-view/stores/graph/index.ts
  app/gui/src/providers/container.ts
  app/gui/src/providers/react/globalProvider.tsx
  app/gui/src/providers/react/rightPanel.tsx
  app/gui/vite.config.ts
  app/ydoc-shared/src/languageServer.ts
  pnpm-lock.yaml
Labels: CI: Ready to merge, CI: No changelog needed

#13319 Restore scrollbar in documentation editor
  app/gui/integration-test/project-view/editorPanels.spec.ts
  app/gui/src/project-view/components/CodeMirrorRoot.vue
  app/gui/src/project-view/components/DocumentationEditor.vue
  app/gui/src/project-view/components/MarkdownEditor.vue
  app/gui/src/project-view/components/MarkdownEditor/MarkdownEditorImpl.vue
  app/gui/src/project-view/util/codemirror/index.ts
Labels: CI: No changelog needed

#13326 Fix paste on Windows
  app/gui/src/project-view/util/codemirror/keymap.ts
Labels: CI: No changelog needed

#13334 Add google sheet telemetry, sheet_count, header, read by index
  distribution/lib/Standard/Google_Api/0.0.0-dev/docs/api/Google_Sheets_Workbook.md
  distribution/lib/Standard/Google_Api/0.0.0-dev/src/Google_Sheets.enso
  distribution/lib/Standard/Google_Api/0.0.0-dev/src/Google_Sheets_Workbook.enso
  distribution/lib/Standard/Google_Api/0.0.0-dev/src/Internal/Telemetry.enso
  std-bits/google-api/src/main/java/org/enso/google/GoogleSheetsForEnso.java
  std-bits/google-api/src/main/java/org/enso/google/GoogleSheetsHeaders.java
  test/Google_Api_Test/src/Main.enso
Labels: CI: No changelog needed, -libs-API-change-Google_Api

#13315 Towards immutable BindingsMap in Java
  engine/runtime-compiler/src/main/java/org/enso/compiler/data/BindingsMapBase.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/data/BindingsMap.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/BindingAnalysis.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/phase/ImportResolver.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/phase/exports/ExportsResolution.scala
  engine/runtime-instrument-common/src/test/scala/org/enso/compiler/test/CompilerTestSetup.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/CompilerTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/semantic/ImportExportTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/caches/ImportExportCache.java
Labels: CI: Ready to merge, CI: No changelog needed

#13346 Extract all dependencies from sbt to a separate file
  build.sbt
  build_tools/build/paths.yaml
  build_tools/build/src/engine.rs
  build_tools/build/src/engine/context.rs
  build_tools/build/src/ide/web.rs
  build_tools/build/src/lib.rs
  project/BenchTasks.scala
  project/Dependencies.scala
  project/GraalVM.scala
  project/JPMSUtils.scala
  project/RecompileParser.scala
Labels: CI: No changelog needed, CI: Clean build required

#13306 Make `Table` a base type of `In_Memory_Table`
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Meta.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Meta_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Meta.enso
  distribution/lib/Standard/Google_Api/0.0.0-dev/src/Google_Analytics.enso
  distribution/lib/Standard/Google_Api/0.0.0-dev/src/Google_Sheets_Workbook.enso
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/In_Memory_Table.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Internal/Delimited_Writer.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Internal/Table_Helpers.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Internal/Table_Type_Helpers.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Table.md
  distribution/lib/Standard/Table/0.0.0-dev/src/Data_Formatter.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Delimited/Delimited_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Workbook.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Extensions/Table_Conversions.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/In_Memory_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Cast_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Column_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Delimited_Reader.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Delimited_Writer.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Excel_Reader.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Excel_Writer.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Expand_Objects_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Fixed_Width_Reader.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/In_Memory_Column_Implementation.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/In_Memory_Table_Implementation.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Match_Columns_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Replace_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Type_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Type_Refinements/Single_Column_Table_Conversions.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Type_Refinements/Single_Column_Typed_Table_Conversions.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Type_Refinements/Table_Refinements.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  distribution/lib/Standard/Tableau/0.0.0-dev/src/Tableau_Format.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/GetMultiTypesBuiltin.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoMultiType.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoMultiValue.java
  test/Base_Tests/src/Semantic/Multi_Value_Spec.enso
  test/Table_Tests/src/IO/Csv_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, -libs-API-change-Base, -libs-API-change-Table

#13345 Extract native libs from jline
  build.sbt
  project/Dependencies.scala
  project/EngineNativeLibraryExtractor.scala
  project/JARUtils.scala
  test/Base_Tests/data/native_libs.json
Labels: CI: No changelog needed, CI: Clean build required

#13349 Add project_id to the initial telemetry message from LS's boot
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
Labels: CI: No changelog needed

#13311 Remove package snapshot testing and PR comments.
  .github/workflows/gui-changed-files.yml
  .github/workflows/gui-checks.yml
  .github/workflows/gui-pull-request.yml
  .github/workflows/ide-packaging-optional.yml
  .github/workflows/ide-packaging.yml
  .github/workflows/storybook.yml
  app/gui/scripts/ci/dedent.js
  app/gui/scripts/ci/parse-playwright-json-report.mjs
  app/gui/scripts/ci/set-message.js
  app/ide-desktop/client/package.json
  app/ide-desktop/client/playwright.config.ts
  app/ide-desktop/client/tests/electronTest.ts
  app/ide-desktop/client/tests/localWorkflow.spec.ts
  build_tools/build/src/ci_gen/job.rs
  pnpm-lock.yaml
Labels: CI: Ready to merge, CI: No changelog needed, -ci, -gui

#13352 Dump visualization text in addition to its UUID
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
Labels: CI: No changelog needed

#13359 Revert "Extract native libs from jline (#13345)"
  build.sbt
  project/Dependencies.scala
  project/EngineNativeLibraryExtractor.scala
  project/JARUtils.scala
  test/Base_Tests/data/native_libs.json
Labels: p-highest, CI: Ready to merge, CI: No changelog needed

#13356 Less heavyweight `persistance` module by bridging `System.Logger` to slf4j
  build.sbt
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/runtime/progress/ObservedMessageTest.java
  lib/java/persistance/src/main/java/module-info.java
  lib/java/persistance/src/main/java/org/enso/persist/PerGenerator.java
  lib/java/persistance/src/main/java/org/enso/persist/PerInputImpl.java
  lib/java/persistance/src/main/java/org/enso/persist/PerUtils.java
  lib/java/persistance/src/test/java/org/enso/persist/PersistanceDependenciesTest.java
  lib/scala/logging-config/src/main/java/module-info.java
  lib/scala/logging-config/src/main/java/org/enso/logging/config/systemlogger/SystemLoggerViaSlf4j.java
Labels: CI: Ready to merge, CI: No changelog needed

#13361 Extract native libs from jline (Second attempt)
  build.sbt
  project/Dependencies.scala
  project/EngineNativeLibraryExtractor.scala
  project/JARUtils.scala
  test/Base_Tests/data/native_libs.json
Labels: CI: No changelog needed

#13365 Update Generic JDBC to be closer to Connection, other clean up tasks
  CHANGELOG.md
  distribution/lib/Standard/Database/0.0.0-dev/docs/api/Connection/Connection.md
  distribution/lib/Standard/Database/0.0.0-dev/docs/api/Internal/Result_Set.md
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Result_Set.enso
  distribution/lib/Standard/Generic_JDBC/0.0.0-dev/src/Generic_JDBC_Connection.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/Azure_Storage.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Add_Row_Number.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Add_Running.enso
  std-bits/base/src/main/java/org/enso/base/arrays/LongArrayList.java
  std-bits/snowflake/src/main/java/org/enso/snowflake/SnowflakeIntegerColumnMaterializer.java
  std-bits/table/src/main/java/org/enso/table/data/column/DataQualityMetrics.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/BigDecimalBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/BigIntegerBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/BoolBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/BoundCheckedIntegerBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/Builder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/DateBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/DateTimeBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/DoubleBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/InferredDoubleBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/LongBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/MixedBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/NullBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/NumericBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/ObjectBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/StringBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/TimeOfDayBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/TypedBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/IsInOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/UnaryOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/ToIntegerStorageConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/masks/MaskedStorageInferred.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/AbstractLongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/ColumnStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/ComputedLongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/DoubleStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/LongRangeStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/LongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/MixedStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/MixedStorageFacade.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/NullStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/ObjectStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/Storage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/StringStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/TypedStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/datetime/DateStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/datetime/DateTimeStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/datetime/TimeOfDayStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/BigDecimalStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/BigIntegerStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/LongConstantStorage.java
  std-bits/table/src/main/java/org/enso/table/format/util/FileSplitter.java
  std-bits/table/src/main/java/org/enso/table/operations/AddGroupNumber.java
  std-bits/table/src/main/java/org/enso/table/operations/AddRowNumber.java
  std-bits/table/src/main/java/org/enso/table/operations/AddRunning.java
  test/Generic_JDBC_Tests/src/Generic_JDBC_Connection_Spec.enso
  test/Generic_JDBC_Tests/src/H2_Spec.enso
Labels: CI: Ready to merge, -libs-API-change-Database

#13342 Evaluate visualization arguments in the `Main` module
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetFunction/widgetFunctionCallInfo.ts
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Widgets.enso
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionService.java
  test/Visualization_Tests/src/Widgets/Table_Widgets_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#13377 Move the position of the variable name
  app/gui/src/project-view/components/GraphEditor/GraphNode.vue
Labels: CI: Ready to merge, CI: No changelog needed

#13375 Update Table Java Problems to be Long based
  std-bits/snowflake/src/main/java/org/enso/snowflake/SnowflakeIntegerColumnMaterializer.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/BoolBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/Builder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/InferredBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/InferredIntegerBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/MixedBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/NullBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/NumericBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/TypedBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/IsInOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/binary/BinaryOperator.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/comparators/NumericComparators.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/NumericUnaryOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/RoundOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/SignumOperation.java
  std-bits/table/src/main/java/org/enso/table/data/index/MultiValueKeyBase.java
  std-bits/table/src/main/java/org/enso/table/data/table/problems/ArithmeticError.java
  std-bits/table/src/main/java/org/enso/table/data/table/problems/ColumnAggregatedProblem.java
  std-bits/table/src/main/java/org/enso/table/data/table/problems/FloatingPointGrouping.java
  std-bits/table/src/main/java/org/enso/table/data/table/problems/IgnoredNaN.java
  std-bits/table/src/main/java/org/enso/table/data/table/problems/IgnoredNothing.java
  std-bits/table/src/main/java/org/enso/table/data/table/problems/IllegalArgumentError.java
  std-bits/table/src/main/java/org/enso/table/data/table/problems/InvalidAggregation.java
  std-bits/table/src/main/java/org/enso/table/data/table/problems/MapOperationProblemAggregator.java
  std-bits/table/src/main/java/org/enso/table/data/table/problems/UnquotedCharactersInOutput.java
  std-bits/table/src/main/java/org/enso/table/data/table/problems/UnquotedDelimiter.java
  std-bits/table/src/main/java/org/enso/table/operations/AddRunning.java
  std-bits/table/src/main/java/org/enso/table/parsing/problems/InvalidFormat.java
  test/Visualization_Tests/src/Table_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#13385 More robust formatting during logging
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/runtime/progress/ObservedMessageTest.java
  lib/scala/logging-config/src/main/java/org/enso/logging/config/systemlogger/SystemLoggerViaSlf4j.java
Labels: CI: No changelog needed

#13363 Less heavyweight jvm-channel by removing dependency on engine-common
  build.sbt
  engine/common/src/main/java/module-info.java
  engine/common/src/main/java/org/enso/common/ContextFactory.java
  engine/common/src/main/java/org/enso/common/ContextLoggingConfigurator.java
  engine/common/src/test/java/org/enso/common/EnsoCommonDependenciesTest.java
  engine/common/src/test/java/org/enso/common/EnsoSourcesTest.java
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/runner-common/src/main/java/module-info.java
  engine/runner-common/src/main/scala/org/enso/runner/common/CompilerBasedDependencyExtractor.scala
  engine/runner/src/main/java/org/enso/runner/Main.java
  lib/java/jvm-channel/src/main/java/module-info.java
  lib/java/jvm-channel/src/main/java/org/enso/jvm/channel/JVM.java
  lib/java/jvm-channel/src/main/java/org/enso/jvm/channel/PosixJVM.java
  lib/java/jvm-channel/src/test/java/org/enso/jvm/channel/ChannelDependenciesTest.java
  lib/java/jvm-interop/src/main/java/module-info.java
  lib/scala/logging-config/src/main/java/module-info.java
  lib/scala/logging-config/src/main/java/org/enso/logging/config/systemlogger/ContextLoggingViaSlf4j.java
  tools/legal-review/engine/report-state
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#13389 Rename "Group Components" to "User Defined Components"
  CHANGELOG.md
  app/gui/integration-test/project-view/actions.ts
  app/gui/integration-test/project-view/collapsingAndEntering.spec.ts
  app/gui/integration-test/project-view/editorPanels.spec.ts
  app/gui/integration-test/project-view/expressionUpdates.ts
  app/gui/src/App.vue
  app/gui/src/dashboard/App.tsx
  app/gui/src/project-view/components/GraphEditor.vue
  app/gui/src/project-view/components/GraphEditor/__tests__/collapsing.test.ts
  app/gui/src/project-view/components/GraphEditor/collapsing.ts
  app/gui/src/project-view/mock/engine.ts
  app/gui/src/project-view/providers/action.ts
  app/ide-desktop/client/tests/localWorkflow.spec.ts
  app/ydoc-shared/src/ast/mutableModule.ts
Labels: CI: Ready to merge

#13401 Add Microsoft Icon
  app/gui/src/project-view/assets/icons.svg
Labels: CI: Ready to merge, CI: No changelog needed

#13405 Intersection type work on Columns
  app/gui/src/project-view/components/ComponentBrowser/ComponentEditorLabel.vue
  app/gui/src/project-view/components/ComponentBrowser/input.ts
  distribution/lib/Standard/Database/0.0.0-dev/docs/api/DB_Column.md
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/DB_Column_Implementation.enso
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Column.md
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/In_Memory_Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/In_Memory_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/In_Memory_Column_Implementation.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/In_Memory_Table_Implementation.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Type_Refinements/In_Memory_Column_Refinements.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Refined_Types/Numeric_Column.enso
  std-bits/table/src/main/java/org/enso/table/data/column/DataQualityMetrics.java
  std-bits/table/src/main/java/org/enso/table/data/table/Column.java
Labels: CI: Ready to merge, CI: No changelog needed, -libs-API-change-Database, -libs-API-change-Table

#13354 Refactorings in preparation for parallel visualization execution
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Main.enso
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/executioncontext/PushHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistry.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistryProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ExecutionApi.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/ContextRegistryTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/RuntimeCache.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/UpdatesSynchronizationState.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/command/SetExecutionEnvironmentCommand.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/execution/JobProcessor.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/execution/Locking.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/job/ExecuteExpressionJob.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionCallbacks.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/ExecutionContextManager.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/ExecutionContextState.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/Handler.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/VisualizationHolder.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/WarningPreview.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/CreateContextCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/DestroyContextCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/PushContextCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/RecomputeContextCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/ErrorResolver.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/JobProcessor.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/LocationResolver.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/ReentrantLocking.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/DetachVisualizationJob.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ExecuteJob.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/UpsertVisualizationJob.scala
  engine/runtime-instrument-runtime-server/src/main/java/org/enso/interpreter/instrument/runtime/server/RuntimeServerInstrument.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/instrument/IncrementalUpdatesTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/instrument/RuntimeProgressTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/instrument/RuntimeServerTesting.java
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/EnsoLanguage.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/HostClassLoader.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  project/GraalVM.scala
Labels: CI: No changelog needed
