Repository enso-org/enso, pull requests merged in 2025-08, with the labels that each got.

#13686 Avoid creation of too many ModuleScope instances
  engine/common/src/main/java/org/enso/common/MethodNames.java
  engine/runtime/src/main/java/org/enso/interpreter/caches/ModuleCache.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodImportResolver.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/Builtin.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/IrTruffleUtils.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/BuiltinsRegistry.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Type.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/AtomConstructor.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScopeBuilder.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScopeUtils.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/TruffleCompilerModuleScopeBuilder.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/DefaultPackageRepository.scala
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/RuntimeStubsGenerator.scala
Labels: CI: No changelog needed, CI: Clean build required

#13709 Making `Builtins.get(...)` the primary accessor for `Builtins`
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/io/PrintErrNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/io/PrintlnNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Error.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Number.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/state/State.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
Labels: CI: No changelog needed

#13713 After registration wait for solo activation
  app/gui/src/providers/auth.ts
Labels: CI: Ready to merge, CI: No changelog needed

#13729 Ignore Azure_Storage tests
  test/Microsoft_Tests/src/Azure_Storage_Spec.enso
Labels: p-highest, CI: Ready to merge, CI: No changelog needed

#13717 Don't call remote backend for free accounts.
  app/gui/src/router/initialProject.ts
  app/ide-desktop/client/tests/localWorkflow.spec.ts
Labels: CI: Ready to merge, CI: No changelog needed

#13703 IR caches are disabled when running with disabled private check
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/caches/HelloWorldCacheTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/caches/IRCacheLocationTest.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
Labels: CI: No changelog needed, CI: Clean build required

#13737 Stop dumping modules on visualization failure
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
Labels: CI: Ready to merge, CI: No changelog needed

#13625 Better jar extraction
  build.sbt
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/HostClassLoader.java
  lib/java/constrypt-wrapper/README.md
  lib/java/epoll-native-wrapper/README.md
  lib/java/grpc-wrapper-older/README.md
  lib/java/grpc-wrapper/README.md
  lib/java/jline-wrapper/README.md
  lib/java/jna-wrapper-extracted/README.md
  lib/java/opencv-wrapper/README.md
  lib/java/sqlite-wrapper/README.md
  lib/java/tableau-wrapper/README.md
  lib/java/tc-native-wrapper/README.md
  project/AnalysisOfExtractedNativeLibs.scala
  project/EngineNativeLibraryExtractor.scala
  project/ExtractedNativeLibSummary.scala
  project/JARUtils.scala
  project/JarExtractPlugin.scala
  project/JarExtractor.scala
  project/Platform.scala
  project/StdBits.scala
  test/Base_Tests/src/System/Runner_Spec.enso
Labels: CI: No changelog needed, CI: Clean build required, -compiler

#13751 Revert "cleanup svg icon usage, types and href generation"
  app/gui/integration-test/dashboard/actions/index.ts
  app/gui/integration-test/dashboard/mock/react-stripe.tsx
  app/gui/integration-test/dashboard/mock/stripe.ts
  app/gui/package.json
  app/gui/playwright.config.ts
  app/gui/src/dashboard/components/Icon/Icon.tsx
  app/gui/src/project-view/assets/icon-missing.svg
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetIcon.vue
  app/gui/src/project-view/components/StandaloneButton.vue
  app/gui/src/project-view/components/SvgButton.vue
  app/gui/src/project-view/components/SvgIcon.vue
  app/gui/src/project-view/components/visualizations/TableVisualization.vue
  app/gui/src/project-view/components/visualizations/toolbar.ts
  app/gui/src/project-view/util/getIconName.ts
  app/gui/src/project-view/util/icons.ts
  app/gui/vite.test.config.ts
  pnpm-lock.yaml
Labels: CI: Ready to merge, CI: No changelog needed

#13749 Exponential backoff in executeExpression request
  app/gui/src/project-view/stores/project/index.ts
Labels: CI: No changelog needed

#13759 Revert "Remove cache invalidation for visualizations (#13608)"
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/UpsertVisualizationJob.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
Labels: CI: No changelog needed

#13733 Fixing file browser
  app/gui/src/project-view/components/widgets/FileBrowserWidget.vue
  app/gui/src/project-view/components/widgets/FileBrowserWidget/__tests__/ensoPath.test.ts
  app/gui/src/project-view/components/widgets/FileBrowserWidget/__tests__/mockData.ts
  app/gui/src/project-view/components/widgets/FileBrowserWidget/__tests__/pathBrowsing.test.ts
  app/gui/src/project-view/components/widgets/FileBrowserWidget/__tests__/useAcceptCurrentFile.test.ts
  app/gui/src/project-view/components/widgets/FileBrowserWidget/__tests__/useFileBrowserSync.test.ts
  app/gui/src/project-view/components/widgets/FileBrowserWidget/fileBrowser.ts
  app/gui/src/project-view/components/widgets/FileBrowserWidget/nameBar.ts
  app/gui/src/project-view/components/widgets/FileBrowserWidget/pathBrowsing.ts
  app/gui/src/project-view/components/widgets/FileBrowserWidget/useAcceptCurrentFile.ts
  app/gui/src/project-view/components/widgets/FileBrowserWidget/useFileBrowserSync.ts
  app/gui/src/project-view/components/widgets/FileBrowserWidget/userFiles.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui

#13755 Table expression autocomplete: stub completion
  app/gui/package.json
  app/gui/src/project-view/components/CodeEditor/CodeEditorImpl.vue
  app/gui/src/project-view/components/ComponentBrowser/ComponentEditor.vue
  app/gui/src/project-view/components/DescriptionEditor.vue
  app/gui/src/project-view/components/GraphEditor/CodeMirrorWidgetBase.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetText.vue
  app/gui/src/project-view/components/NavBreadcrumb.vue
  app/gui/src/project-view/util/codemirror/index.ts
  app/gui/src/project-view/util/codemirror/reactivity.ts
  app/lang-markdown/package.json
  app/lezer-markdown/package.json
  app/table-expression/package.json
  app/table-expression/src/__tests__/syntax.test.ts
  app/table-expression/src/autocomplete.ts
  app/table-expression/src/highlight.ts
  app/table-expression/src/index.ts
  app/table-expression/src/language.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: CI: No changelog needed

#13761 Mini compiler passes are not combined when IR is dumped
  docs/runtime/compiler-ir.md
  engine/runtime-compiler-dump-igv/src/main/java/org/enso/compiler/dump/igv/EnsoModuleAST.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/data/CompilerConfig.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/data/IRDumperConfig.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/data/IRDumperWithConfig.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/PassManager.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
Labels: CI: No changelog needed

#13777 Fix synchronization state for visualizations
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
Labels: CI: No changelog needed

#13771 "cleanup svg icon usage, types and href generation" once more
  app/common/package.json
  app/gui/integration-test/dashboard/actions/index.ts
  app/gui/integration-test/dashboard/mock/react-stripe.tsx
  app/gui/integration-test/dashboard/mock/stripe.ts
  app/gui/package.json
  app/gui/playwright.config.ts
  app/gui/src/dashboard/components/Icon/Icon.tsx
  app/gui/src/project-view/assets/icon-missing.svg
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetIcon.vue
  app/gui/src/project-view/components/StandaloneButton.vue
  app/gui/src/project-view/components/SvgButton.vue
  app/gui/src/project-view/components/SvgIcon.vue
  app/gui/src/project-view/components/visualizations/TableVisualization.vue
  app/gui/src/project-view/components/visualizations/toolbar.ts
  app/gui/src/project-view/util/getIconName.ts
  app/gui/src/project-view/util/icons.ts
  app/gui/vite.test.config.ts
  app/ide-desktop/client/package.json
  app/ide-desktop/client/src/preload.ts
  app/ydoc-server-nodejs/package.json
  app/ydoc-server/package.json
  app/ydoc-shared/package.json
  app/ydoc-shared/src/ast/tree.ts
  lib/js/runner/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: CI: Ready to merge, CI: No changelog needed

#13762 Deduplicate `listDirectory` and `getAssetDetails` requests
  app/gui/src/components/AppContainer.vue
  app/gui/src/dashboard/hooks/backendHooks.ts
  app/gui/src/dashboard/layouts/Drive.tsx
  app/gui/src/dashboard/pages/dashboard/Drive/DriveBar/DriveBarNavigation.tsx
  app/gui/src/dashboard/services/ProjectManager/ProjectManager.ts
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#13786 Fix conditions to show settings tabs
  app/common/src/services/Backend.ts
  app/gui/src/dashboard/layouts/Settings/data.tsx
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#13815 Fix delay reopening project
  app/gui/src/components/AppContainer.vue
  app/gui/src/dashboard/hooks/backendHooks.ts
  app/gui/src/dashboard/layouts/Drive.tsx
  app/gui/src/dashboard/pages/dashboard/Drive/DriveBar/DriveBarNavigation.tsx
  app/gui/src/dashboard/services/ProjectManager/ProjectManager.ts
Labels: CI: Ready to merge, CI: No changelog needed

#13817 Some Fixes For Table Viz
  app/gui/package.json
  app/gui/project-manager-shim-middleware/index.ts
  app/gui/src/project-view/components/shared/AgGridTableView/AgGridVue.ts
  app/gui/src/project-view/components/visualizations/TableVisualization.vue
  app/gui/src/project-view/components/visualizations/TableVisualization/tableVizFilterSetUpUtils.ts
  pnpm-lock.yaml
Labels: CI: Ready to merge, CI: No changelog needed

#13810 Fix shortcuts handled by AG grid also being handled by graph
  app/gui/src/project-view/components/shared/AgGridTableView.vue
Labels: CI: No changelog needed

#13788 Refactor usage of Java IR types
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/MiniIRPass.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/TailCall.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/desugar/OperatorToFunctionMini.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/desugar/SectionsToBinOp.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/resolve/MethodDefinitions.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/AutomaticParallelism.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/DataflowAnalysis.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/DemandAnalysis.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/desugar/GenerateMethodBodies.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/desugar/LambdaShorthandToLambdaMini.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/lint/UnusedBindings.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/ExpressionAnnotations.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/FullyAppliedFunctionUses.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/FullyQualifiedNames.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/GlobalNames.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/IgnoredBindings.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/MethodCalls.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/TypeFunctions.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/CompilerTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/analyse/GatherDiagnosticsTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/analyse/TailCallMegaPass.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/desugar/LambdaShorthandToLambdaMegaPass.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/desugar/OperatorToFunctionTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/desugar/SectionsToBinOpMegaPass.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/optimise/LambdaConsolidateTest.scala
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/IRNodeClassGenerator.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/methodgen/MapExpressionsMethodGenerator.java
  engine/runtime-parser/src/main/java/org/enso/compiler/core/IR.java
  engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java
  engine/runtime-parser/src/main/java/org/enso/compiler/core/ir/CallArgument.java
  engine/runtime-parser/src/main/java/org/enso/compiler/core/ir/DefinitionArgument.java
  engine/runtime-parser/src/main/java/org/enso/compiler/core/ir/expression/Application.java
  engine/runtime-suggestions/src/main/scala/org/enso/compiler/suggestions/SuggestionBuilder.scala
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
Labels: CI: No changelog needed, CI: Clean build required

#13797 Table expressions: autocomplete Column methods
  CHANGELOG.md
  app/gui/package.json
  app/gui/src/project-view/components/CodeMirrorRoot.vue
  app/gui/src/project-view/components/GraphEditor/CodeMirrorWidgetBase.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetText.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetTopLevelArgument.vue
  app/gui/src/project-view/stores/suggestionDatabase/index.ts
  app/gui/src/project-view/util/callTree.ts
  app/gui/src/project-view/util/codemirror/language.ts
  app/gui/src/project-view/util/projectPath.ts
  app/table-expression/package.json
  app/table-expression/src/__tests__/syntax.test.ts
  app/table-expression/src/autocomplete.ts
  app/table-expression/src/autocomplete/__tests__/completionType.test.ts
  app/table-expression/src/autocomplete/completionType.ts
  app/table-expression/src/autocomplete/index.ts
  app/table-expression/src/expression.grammar
  app/table-expression/src/index.ts
  pnpm-lock.yaml
Labels: CI: Ready to merge, CI: Clean build required

#13820 Fix responsive cutoffs for trial counter
  app/gui/src/dashboard/pages/dashboard/UserBar/UserBar.tsx
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#13785 Allow editing secret path in Datalinks
  app/gui/src/dashboard/components/Autocomplete.tsx
  app/gui/src/dashboard/components/Inputs/ComboBox/ComboBox.tsx
  app/gui/src/dashboard/components/JSONSchemaInput.tsx
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#13824 Fix Local folder resetting after renaming an asset
  app/gui/src/components/AppContainer.vue
  app/gui/src/dashboard/hooks/backendHooks.ts
  app/gui/src/dashboard/layouts/AssetsTable.tsx
  app/gui/src/dashboard/layouts/Drive/Categories/CategoriesProvider.tsx
  app/gui/src/dashboard/pages/dashboard/Drive/DriveBar/DriveBarNavigation.tsx
  app/gui/src/dashboard/services/LocalBackend.ts
Labels: CI: No changelog needed, --bug, g-dashboard

#13831 Respect node positions when determining the order of collapsed function arguments
  app/gui/integration-test/project-view/collapsingAndEntering.spec.ts
  app/gui/integration-test/project-view/edgeInteractions.spec.ts
  app/gui/integration-test/project-view/edgeRendering.spec.ts
  app/gui/integration-test/project-view/graphRenderNodes.spec.ts
  app/gui/integration-test/project-view/widgets.spec.ts
  app/gui/src/project-view/components/GraphEditor/collapsing.ts
  app/gui/src/project-view/mock/engine.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#13622 Update bazel version & prepare for running sbt
  .bazelrc
  .bazelversion
  .github/workflows/bazel-build.yml
  BUILD.bazel
  MODULE.bazel
  MODULE.bazel.lock
  WORKSPACE.bazel
  app/common/BUILD.bazel
  app/gui/BUILD.bazel
  app/rust-ffi/BUILD.bazel
  app/table-expression/BUILD.bazel
  app/ydoc-server-nodejs/BUILD.bazel
  app/ydoc-shared/BUILD.bazel
  lib/rust/macro-utils/BUILD.bazel
  lib/rust/metamodel/BUILD.bazel
  lib/rust/parser/BUILD.bazel
  lib/rust/parser/generate-java/BUILD.bazel
  lib/rust/parser/generate-java/src/main.rs
  lib/rust/parser/jni/BUILD.bazel
  lib/rust/parser/macros/BUILD.bazel
  lib/rust/parser/schema/BUILD.bazel
  lib/rust/parser/src/syntax/tree/visitor/BUILD.bazel
  lib/rust/prelude/BUILD.bazel
  lib/rust/prelude/macros/BUILD.bazel
  lib/rust/reflect/BUILD.bazel
  lib/rust/reflect/macros/BUILD.bazel
  lib/rust/zst/BUILD.bazel
  lib/scala/cli/BUILD.bazel.backup
  lib/scala/downloader/BUILD.bazel.backup
  lib/scala/testkit/BUILD.bazel
  patches/rules_graalvm.patch
  toolchains/flatc/BUILD.bazel
  toolchains/flatc/BUILD.bazel.tpl
  toolchains/flatc/extensions.bzl
  toolchains/flatc/toolchain.bzl
  toolchains/sbt/BUILD.bazel
  toolchains/sbt/BUILD.bazel.tpl
  toolchains/sbt/extensions.bzl
  toolchains/sbt/run_sbt.bzl
  toolchains/sbt/toolchain.bzl
  tools/http-test-helper/BUILD.bazel
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#13835 Add new macros
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Statistics/Extensions.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
Labels: CI: No changelog needed

#13825 Minimize calls to local `listDirectory`
  app/gui/src/dashboard/hooks/projectHooks.ts
  app/gui/src/dashboard/services/ProjectManager/ProjectManager.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, --regression, g-dashboard

#13839 Two types aren't the same just because they have the same name
  engine/runtime-integration-tests/src/test/java/org/enso/example/TestClass.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/interop/JavaInteropTest.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/IsSameObjectNode.java
  lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/impl/OtherJvmObject.java
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#13846 Cleanup project directory before unpacking hybrid project
  app/gui/project-manager-shim-middleware/index.ts
  app/ide-desktop/client/src/server.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#13812 Avoid loading Python classes during context initialization
  build.sbt
  engine/common/src/main/java/org/enso/common/ContextFactory.java
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/python-resource-provider/src/main/java/module-info.java
  engine/python-resource-provider/src/main/java/org/enso/python/resource/provider/PythonResourceProvider.java
  engine/runner/src/main/java/org/enso/runner/Main.java
  test/Base_Tests/src/Main.enso
  test/Base_Tests/src/Native_Image_Imports.enso
  test/Base_Tests/src/System/Python_Resource_Spec.enso
  test/Base_Tests/src/System/Runner_Spec.enso
  test/Base_Tests/src/Utils.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#13850 Find file in editor in the Enso project view
  .github/CODEOWNERS
  tools/enso4igv/src/main/java/org/enso/tools/enso4igv/EnsoLogicalView.java
  tools/enso4igv/src/main/java/org/enso/tools/enso4igv/enso/EnsoYamlProject.java
  tools/enso4igv/src/test/java/org/enso/tools/enso4igv/enso/EnsoYamlProjectTest.java
Labels: CI: No changelog needed

#13841 Fix versions panel
  app/gui/src/dashboard/layouts/AssetPanel/components/AssetVersions.tsx
  app/gui/src/dashboard/layouts/AssetPanel/components/queries.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#13869 Remove Python resources test
  test/Base_Tests/src/Main.enso
  test/Base_Tests/src/System/Python_Resource_Spec.enso
Labels: p-highest, CI: Ready to merge, CI: No changelog needed

#13868 Allow other names for lat/lng columns
  distribution/lib/Standard/Visualization/0.0.0-dev/docs/api/Helpers.md
  distribution/lib/Standard/Visualization/0.0.0-dev/docs/api/Histogram.md
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Geo_Map.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Helpers.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Histogram.enso
  test/Visualization_Tests/src/Geo_Map_Spec.enso
  test/Visualization_Tests/src/Helpers_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, -libs-API-change-Visualization

#13875 Fix sqaured => squared in macro
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Statistics/Extensions.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
Labels: CI: Ready to merge, CI: No changelog needed

#13819 `Equal_Sum` for in-memory `add_group_number`
  CHANGELOG.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Errors.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Grouping_Method.md
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Grouping_Method.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Add_Group_Number.enso
  std-bits/table/src/main/java/org/enso/table/operations/AddGroupNumber.java
  std-bits/table/src/main/resources/META-INF/native-image/org/enso/table/reflect-config.json
  test/Table_Tests/src/Common_Table_Operations/Add_Group_Number_Spec.enso
Labels: CI: Ready to merge, -libs-API-change-Table

#13864 New user defined component editor layout
  app/gui/integration-test/project-view/editorPanels.spec.ts
  app/gui/src/dashboard/components/FilePathInput.tsx
  app/gui/src/project-view/ProjectView.vue
  app/gui/src/project-view/assets/base.css
  app/gui/src/project-view/components/DocumentationEditor.vue
  app/gui/src/project-view/components/FormContainer.vue
  app/gui/src/project-view/components/FormRow.vue
  app/gui/src/project-view/components/FunctionSignatureEditor.vue
  app/gui/src/project-view/components/GraphEditor/NodeWidget.vue
  app/gui/src/project-view/components/GraphEditor/WidgetTreeRoot.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetFunctionDef.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetFunctionDef/ArgumentRow.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetPort.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection/SelectionSubmenu.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor/__tests__/editHandler.test.ts
  app/gui/src/project-view/components/widgets/AutoSizedInput.vue
  app/gui/src/project-view/components/widgets/DraggableList.vue
  app/gui/src/project-view/components/widgets/DropdownWidget.vue
  app/gui/src/project-view/components/widgets/FileBrowserWidget.vue
  app/gui/src/project-view/components/widgets/FileBrowserWidget/fileExtensions.ts
  app/gui/src/project-view/providers/widgetRegistry/__tests__/editHandler.test.ts
  app/gui/src/project-view/providers/widgetRegistry/editHandler.ts
  app/gui/src/project-view/providers/widgetTree.ts
  app/gui/src/project-view/util/getIconName.ts
Labels: CI: Ready to merge, CI: No changelog needed

#13881 Add new Secret_Not_Found error
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Enso_Cloud/Enso_Secret.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Errors/Common.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_Secret.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso
  test/Cloud_Tests/src/Network/Enso_Cloud/Secrets_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, -libs-API-change-Base
