Repository enso-org/enso, pull requests merged in 2025-01, with the labels that each got.

#11938 Register type definitions lazily
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Type.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/AtomConstructor.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/util/CachingSupplier.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
Labels: CI: Ready to merge, CI: No changelog needed

#11949 Disable visualizations for subexpressions
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/JobExecutionEngine.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/UpsertVisualizationJob.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#11902 Fix node being selected after deleting node or connection
  CHANGELOG.md
  app/gui/src/project-view/components/GraphEditor/ComponentWidgetTree.vue
  app/gui/src/project-view/components/GraphEditor/GraphEdges.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetCheckbox.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetCloudBrowser.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetFileBrowser.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetFunction.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetNumber.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor/tableInputArgument.ts
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetText.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetVector.vue
  app/gui/src/project-view/providers/widgetRegistry.ts
  app/gui/src/project-view/stores/graph/index.ts
Labels: CI: Ready to merge, --bug, -gui

#11959 Fix wrong version in Changelog
  CHANGELOG.md
Labels: x-chore

#11894 Fix missing placeholders
  app/gui/integration-test/project-view/collapsingAndEntering.spec.ts
  app/gui/integration-test/project-view/expressionUpdates.ts
  app/gui/src/project-view/util/callTree.ts
Labels: CI: Ready to merge, CI: No changelog needed

#11948 Allow renaming secrets
  app/common/src/services/Backend.ts
  app/gui/src/dashboard/components/dashboard/SecretNameColumn.tsx
  app/gui/src/dashboard/layouts/AssetProperties.tsx
  app/gui/src/dashboard/layouts/AssetsTable.tsx
  app/gui/src/dashboard/modals/UpsertSecretModal.tsx
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#11958 Include jline in non-linux setup
  engine/runner/src/main/resources/META-INF/native-image/org/enso/runner/proxy-config.json
  engine/runner/src/main/resources/META-INF/native-image/org/enso/runner/reflect-config.json
Labels: CI: No changelog needed

#11927 Refactoring in preparation for normalized qualified names
  app/gui/src/project-view/components/CodeEditor/tooltips.ts
  app/gui/src/project-view/components/ComponentBrowser/__tests__/component.test.ts
  app/gui/src/project-view/components/ComponentBrowser/__tests__/filtering.test.ts
  app/gui/src/project-view/components/ComponentBrowser/component.ts
  app/gui/src/project-view/components/GraphEditor.vue
  app/gui/src/project-view/components/GraphEditor/GraphNodes.vue
  app/gui/src/project-view/components/GraphEditor/upload.ts
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetFunction/__tests__/widgetFunctionCallInfo.test.ts
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor/__tests__/tableInputArgument.test.ts
  app/gui/src/project-view/stores/awareness.ts
  app/gui/src/project-view/stores/graph/__tests__/imports.test.ts
  app/gui/src/project-view/stores/graph/graphDatabase.ts
  app/gui/src/project-view/stores/graph/imports.ts
  app/gui/src/project-view/stores/suggestionDatabase/__tests__/lsUpdate.test.ts
  app/gui/src/project-view/stores/suggestionDatabase/documentation.ts
  app/gui/src/project-view/stores/suggestionDatabase/entry.ts
  app/gui/src/project-view/stores/suggestionDatabase/index.ts
  app/gui/src/project-view/stores/suggestionDatabase/lsUpdate.ts
  app/gui/src/project-view/stores/suggestionDatabase/mockSuggestion.ts
  app/gui/src/project-view/util/__tests__/callTree.test.ts
  app/gui/src/project-view/util/ast/abstract.ts
  app/gui/src/project-view/util/callTree.ts
  app/gui/src/project-view/util/data/array.ts
  app/gui/src/project-view/util/ensoTypes.ts
  app/ydoc-shared/src/languageServerTypes/suggestions.ts
Labels: CI: No changelog needed

#11857 Edit text for "delete asset" modal
  app/common/src/text/english.json
  app/common/src/text/index.ts
  app/gui/integration-test/dashboard/actions/BaseActions.ts
  app/gui/integration-test/dashboard/actions/DrivePageActions.ts
  app/gui/integration-test/dashboard/actions/api.ts
  app/gui/integration-test/dashboard/actions/contextMenuActions.ts
  app/gui/integration-test/dashboard/delete.spec.ts
  app/gui/src/dashboard/layouts/AssetContextMenu.tsx
  app/gui/src/dashboard/layouts/AssetsTableContextMenu.tsx
  app/gui/src/dashboard/layouts/DriveBar.tsx
  app/gui/src/dashboard/modals/ConfirmDeleteModal.tsx
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#11898 Scatterplot fixes and improvements
  app/gui/src/project-view/components/visualizations/ScatterplotVisualization.vue
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Scatter_Plot.enso
  test/Visualization_Tests/src/Scatter_Plot_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11962 fix special characters in hyperlink in ag grid
  app/gui/src/project-view/components/visualizations/TableVisualization.vue
Labels: CI: Ready to merge, CI: No changelog needed

#11945 Multiple Vector.slice over each other slow things down
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/VectorBenchmarks.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/ArraySlice.java
Labels: CI: Ready to merge, CI: Keep up to date, CI: No changelog needed

#11874 Native libraries are searched in lib/polyglot project dir
  .gitignore
  CHANGELOG.md
  build.sbt
  docs/polyglot/java.md
  engine/runner/src/main/java/org/enso/runner/EnsoLibraryFeature.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/SerializationManagerTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/NativeLibraryFinderTest.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/HostClassLoader.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/util/TruffleFileSystem.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/DefaultPackageRepository.scala
  lib/scala/pkg/src/main/java/org/enso/pkg/NativeLibraryFinder.java
  lib/scala/pkg/src/main/scala/org/enso/filesystem/FileSystem.scala
  lib/scala/pkg/src/main/scala/org/enso/pkg/Package.scala
  project/JARUtils.scala
  project/StdBits.scala
  std-bits/image/src/main/java/org/enso/image/Codecs.java
  std-bits/image/src/main/java/org/enso/image/data/Image.java
  std-bits/image/src/main/java/org/enso/image/data/Matrix.java
Labels: CI: Clean build required

#11974 Avoiding problems of missing `==` by using `Meta.is_same_object`
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso
Labels: CI: Keep up to date, CI: No changelog needed, CI: Clean build required

#11924 Initial benchmarks for intersection types + a bit of speedup
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/MultiValueBenchmarks.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/node/expression/builtin/meta/TypeOfNodeMultiValueTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/node/expression/builtin/meta/TypeOfNodeValueTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/node/typecheck/TypeCheckValueTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/AnyToTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/EnsoMultiValueInteropTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/EqualsMultiValueTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/ValuesGenerator.java
  engine/runtime/src/main/java/org/enso/interpreter/node/BinaryOperatorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/typecheck/AbstractTypeCheckNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/typecheck/AllOfTypesCheckNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/typecheck/SingleTypeCheckNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/UnresolvedSymbol.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoMultiType.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoMultiValue.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicException.java
Labels: CI: No changelog needed, CI: Clean build required

#11880 Native Language Server integration with PM
  build.sbt
  engine/common/src/main/java/org/enso/common/ContextFactory.java
  engine/language-server/src/main/java/module-info.java
  engine/language-server/src/main/java/org/enso/languageserver/boot/LanguageServerRunner.java
  engine/language-server/src/main/java/org/enso/languageserver/boot/resource/RepoInitialization.java
  engine/language-server/src/main/resources/META-INF/native-image/org/enso/languageserver/reflect-config.json
  engine/language-server/src/main/resources/META-INF/native-image/org/enso/languageserver/serialization-config.json
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/RuntimeConnector.scala
  engine/launcher/src/test/scala/org/enso/launcher/components/LauncherRunnerSpec.scala
  engine/runner/src/main/java/org/enso/runner/Main.java
  engine/runner/src/main/java/org/enso/runner/RunnerLogging.java
  engine/runtime-instrument-runtime-server/src/main/java/org/enso/interpreter/instrument/runtime/server/RuntimeServerInstrument.java
  engine/runtime/src/main/java/org/enso/interpreter/EnsoLanguage.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
  lib/scala/distribution-manager/src/main/scala/org/enso/distribution/DistributionManager.scala
  lib/scala/logging-service-logback/src/main/java/org/enso/logging/service/logback/LoggingServer.java
  lib/scala/logging-service-logback/src/main/java/org/enso/logging/service/logback/SocketLoggingNode.java
  lib/scala/logging-service-logback/src/main/java/org/enso/logging/service/logback/SocketServer.java
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/TestDistributionConfiguration.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectCreateHandleMissingRuntimeSpec.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/runner/ExecCommand.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/runner/JVMSettings.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/runner/JavaCommand.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/runner/JavaExecCommand.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/runner/NativeExecCommand.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/runner/RawCommand.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/runner/Runner.scala
Labels: CI: No changelog needed, CI: Clean build required

#11955 Simplify `BindingsMap` by instead relying on `StaticModuleScope` for atom type resolution
  engine/runtime-compiler/src/main/java/org/enso/compiler/common/NameResolutionAlgorithm.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/AtomTypeInterface.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/AtomTypeInterfaceFromBindingsMap.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/BuiltinTypes.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/TypeInferencePersistance.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/TypeInferencePropagation.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/TypeInferenceSignatures.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/TypePropagation.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/TypeRepresentation.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/TypeResolver.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/scope/AtomTypeDefinition.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/scope/StaticImportExportScope.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/scope/StaticModuleScope.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/scope/StaticModuleScopeAnalysis.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/data/BindingsMap.scala
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/TypeInferenceTest.java
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/analyse/BindingAnalysisTest.scala
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
  engine/runtime/src/test/java/org/enso/runtime/test/TypeMetadataPersistanceTest.java
Labels: CI: No changelog needed

#11967 Upload file chunks in parallel
  app/gui/src/dashboard/hooks/backendHooks.tsx
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#12005 Increase package tests' timeout on expectations after loading a new page.
  app/ide-desktop/client/playwright.config.ts
Labels: CI: Ready to merge, CI: No changelog needed

#12016 Allow parse to pass through already matched type.
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Filter_Condition.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Columns_To_Keep.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Workbook.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Return_As_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  test/Table_Tests/src/Common_Table_Operations/Conversion_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#11960 Vue entrypoint
  app/gui/.storybook/preview.tsx
  app/gui/index.html
  app/gui/integration-test/dashboard/createAsset.spec.ts
  app/gui/integration-test/dashboard/driveView.spec.ts
  app/gui/integration-test/dashboard/pageSwitcher.spec.ts
  app/gui/integration-test/dashboard/startModal.spec.ts
  app/gui/integration-test/project-view/graphNodeVisualization.spec.ts
  app/gui/src/App.vue
  app/gui/src/ReactRoot.tsx
  app/gui/src/dashboard/App.tsx
  app/gui/src/dashboard/components/AriaComponents/Dialog/utilities.ts
  app/gui/src/dashboard/index.tsx
  app/gui/src/dashboard/layouts/Editor.tsx
  app/gui/src/dashboard/pages/dashboard/Dashboard.tsx
  app/gui/src/dashboard/pages/dashboard/DashboardTabPanels.tsx
  app/gui/src/dashboard/styles.css
  app/gui/src/dashboard/tailwind.css
  app/gui/src/entrypoint.ts
  app/gui/src/project-view/App.vue
  app/gui/src/project-view/ProjectView.vue
  app/gui/src/project-view/ProjectViewTab.vue
  app/gui/src/project-view/asyncApp.ts
  app/gui/src/project-view/components/GraphEditor.vue
  app/gui/src/project-view/config.json
  app/gui/src/project-view/providers/eventLogging.ts
  app/gui/src/project-view/stores/project/index.ts
  app/gui/src/project-view/test-entrypoint.ts
  app/gui/src/project-view/views/AboutView.vue
  app/gui/src/project-view/views/ProjectView.vue
  app/gui/vite.config.ts
  package.json
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard, -gui, x-refactor

#11926 Treat data links even more like symlinks, allow crossing using `/`
  CHANGELOG.md
  distribution/lib/Standard/AWS/0.0.0-dev/src/Internal/Decomposed_S3_Path.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/Internal/S3_Path.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Data_Link.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Data_Link_Capabilities.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Data_Link_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Enso_File_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Existing_Enso_Asset.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Utils.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Data_Read_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Path_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/Internal/File_Builtins.enso
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoFile.java
  std-bits/aws/src/main/java/org/enso/aws/file_system/S3DataLinkCache.java
  std-bits/base/src/main/java/org/enso/base/cache/APIRequestCache.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/CloudAPI.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/CloudRequestCache.java
  test/AWS_Tests/src/Inter_Backend_File_Operations_Spec.enso
  test/AWS_Tests/src/S3_Spec.enso
  test/Base_Tests/src/Network/Enso_Cloud/Cloud_Data_Link_Spec.enso
  test/Base_Tests/src/System/File_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
Labels: CI: Ready to merge

#11972 Document main IR classes
  docs/libraries/README.md
  docs/libraries/database-ir.md
Labels: CI: Ready to merge, CI: No changelog needed

#12022 Fix a bad merge between #11926 and #11399
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
Labels: CI: Ready to merge, CI: Keep up to date, CI: No changelog needed, CI: Clean build required

#12026 [Quickfix] import std lib benchmark does not fail on IR cache version mismatch
  engine/runtime-benchmarks/src/main/java/org/enso/compiler/benchmarks/module/ImportStandardLibrariesBenchmark.java
Labels: p-highest, CI: Ready to merge, CI: No changelog needed, -compiler

#12029 Fix asset rows not being memoized
  app/gui/src/dashboard/layouts/AssetsTable.tsx
  app/gui/src/dashboard/layouts/Drive/assetTreeHooks.tsx
  app/gui/src/dashboard/layouts/Drive/assetsTableItemsHooks.tsx
  app/gui/src/dashboard/layouts/Drive/suggestionsConstants.ts
Labels: CI: Ready to merge, CI: No changelog needed, --regression, g-dashboard

#11770 Generate IR definitions by annotation processor - 1st step
  CHANGELOG.md
  build.sbt
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/optimise/LambdaConsolidate.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/SuspendedArguments.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/core/ir/DiagnosticStorageTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/desugar/OperatorToFunctionTest.scala
  engine/runtime-parser-dsl/src/main/java/module-info.java
  engine/runtime-parser-dsl/src/main/java/org/enso/runtime/parser/dsl/GenerateFields.java
  engine/runtime-parser-dsl/src/main/java/org/enso/runtime/parser/dsl/GenerateIR.java
  engine/runtime-parser-dsl/src/main/java/org/enso/runtime/parser/dsl/IRChild.java
  engine/runtime-parser-dsl/src/main/java/org/enso/runtime/parser/dsl/IRField.java
  engine/runtime-parser-processor-tests/src/main/java/org/enso/runtime/parser/processor/test/gen/ir/core/JCallArgument.java
  engine/runtime-parser-processor-tests/src/main/java/org/enso/runtime/parser/processor/test/gen/ir/core/JExpression.java
  engine/runtime-parser-processor-tests/src/main/java/org/enso/runtime/parser/processor/test/gen/ir/core/package-info.java
  engine/runtime-parser-processor-tests/src/main/java/org/enso/runtime/parser/processor/test/gen/ir/package-info.java
  engine/runtime-parser-processor-tests/src/test/java/org/enso/runtime/parser/processor/test/TestIRProcessorInline.java
  engine/runtime-parser-processor-tests/src/test/scala/org/enso/runtime/parser/processor/test/GeneratedIRTest.scala
  engine/runtime-parser-processor/src/main/java/module-info.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/ClassField.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/GenerateIRAnnotationVisitor.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/GeneratedClassContext.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/IRNodeClassGenerator.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/IRProcessingException.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/IRProcessor.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/ProcessedClass.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/field/Field.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/field/FieldCollector.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/field/ListField.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/field/OptionField.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/field/PrimitiveField.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/field/ReferenceField.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/methodgen/BuilderMethodGenerator.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/methodgen/CopyMethodGenerator.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/methodgen/DuplicateMethodGenerator.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/methodgen/EqualsMethodGenerator.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/methodgen/HashCodeMethodGenerator.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/methodgen/MapExpressionsMethodGenerator.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/methodgen/SetLocationMethodGenerator.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/methodgen/ToStringMethodGenerator.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/utils/InterfaceHierarchyVisitor.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/utils/Utils.java
  engine/runtime-parser/src/main/java/module-info.java
  engine/runtime-parser/src/main/java/org/enso/compiler/core/ir/CallArgument.java
  engine/runtime-parser/src/main/java/org/enso/compiler/core/ir/Empty.java
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/CallArgument.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/DiagnosticStorage.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Empty.scala
  engine/runtime-parser/src/test/java/org/enso/compiler/core/ParserDependenciesTest.java
Labels: CI: Ready to merge, CI: Clean build required

#12030 Respect number order when sorting assets by title
  app/gui/integration-test/dashboard/sort.spec.ts
  app/gui/src/dashboard/layouts/Drive/__test__/compareAssets.test.ts
  app/gui/src/dashboard/layouts/Drive/assetTreeHooks.ts
  app/gui/src/dashboard/layouts/Drive/assetsTableItemsHooks.ts
  app/gui/src/dashboard/layouts/Drive/compareAssets.ts
  app/gui/src/dashboard/layouts/Drive/directoryIdsHooks.ts
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#11975 `EnsoMultiValue.firstDispatch` to speed benchmarks up
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/node/expression/builtin/meta/TypeOfNodeMultiValueTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/node/expression/builtin/meta/TypeOfNodeValueTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/node/typecheck/TypeCheckValueTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/AnyToTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/EnsoMultiValueInteropTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/EqualsMultiValueTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/ValuesGenerator.java
  engine/runtime/src/main/java/org/enso/interpreter/node/typecheck/AllOfTypesCheckNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoMultiType.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoMultiValue.java
Labels: CI: No changelog needed, CI: Clean build required

#12024 Eliminate handler frames from `Caught_Panic.stack_trace`
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/CatchPanicNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoSource.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/text/Text.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicException.java
  test/Base_Tests/src/Runtime/Stack_Traces_Spec.enso
Labels: CI: No changelog needed, CI: Clean build required

#12025 `HelloWorldCacheTest` CI failures fix + more logging
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/caches/HelloWorldCacheTest.java
  engine/runtime/src/main/java/org/enso/interpreter/caches/Cache.java
  engine/runtime/src/main/java/org/enso/interpreter/caches/ImportExportCache.java
  engine/runtime/src/main/java/org/enso/interpreter/caches/ModuleCache.java
  engine/runtime/src/main/java/org/enso/interpreter/caches/SuggestionsCache.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java
Labels: CI: No changelog needed, CI: Clean build required

#11929 Sort output of `S3_File.list` and `Enso_File.list`
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_File.enso
  test/AWS_Tests/src/S3_Spec.enso
  test/Base_Tests/src/Network/Enso_Cloud/Enso_File_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#12039 Revert veaury back to 2.4
  app/gui/package.json
  pnpm-lock.yaml
Labels: p-highest, CI: Ready to merge, CI: No changelog needed, --bug, -gui

#12041 Always re-package signed jars with existing MANIFEST
  app/ide-desktop/client/tasks/signArchivesMacOs.ts
Labels: CI: No changelog needed

#12034 Better detection for Enso's NI when launching Language Server
  build.sbt
  distribution/launcher/THIRD-PARTY/NOTICE
  distribution/launcher/THIRD-PARTY/org.apache.tika.tika-core-2.4.1/NOTICE
  distribution/launcher/THIRD-PARTY/org.apache.tika.tika-core-2.4.1/NOTICES
  distribution/project-manager/THIRD-PARTY/NOTICE
  distribution/project-manager/THIRD-PARTY/org.apache.tika.tika-core-2.4.1/NOTICE
  distribution/project-manager/THIRD-PARTY/org.apache.tika.tika-core-2.4.1/NOTICES
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/runner/NativeExecCommand.scala
  tools/legal-review/engine/report-state
  tools/legal-review/launcher/org.apache.tika.tika-core-2.4.1/copyright-ignore
  tools/legal-review/launcher/org.apache.tika.tika-core-2.4.1/copyright-keep-context
  tools/legal-review/launcher/org.apache.tika.tika-core-2.4.1/files-ignore
  tools/legal-review/launcher/org.apache.tika.tika-core-2.4.1/files-keep
  tools/legal-review/launcher/report-state
  tools/legal-review/project-manager/org.apache.tika.tika-core-2.4.1/copyright-ignore
  tools/legal-review/project-manager/org.apache.tika.tika-core-2.4.1/copyright-keep-context
  tools/legal-review/project-manager/org.apache.tika.tika-core-2.4.1/files-ignore
  tools/legal-review/project-manager/org.apache.tika.tika-core-2.4.1/files-keep
  tools/legal-review/project-manager/report-state
Labels: CI: Ready to merge, CI: No changelog needed

#11687 Builtins expose Enso methods
  distribution/lib/Standard/Base/0.0.0-dev/src/Meta/Enso_Project.enso
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/runtime/RefTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/DebuggingEnsoTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/VectorSortTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/builtins/BuiltinTypesExposeMethodsTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/builtins/InvokeBuiltinMethodViaInteropTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/privateaccess/PrivateConstructorAccessTest.java
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/semantic/PolyglotTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsComplexNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Type.java
  std-bits/base/src/main/java/org/enso/base/CurrentEnsoProject.java
Labels: CI: No changelog needed, CI: Clean build required

#12044 Add missing teardown to a few cloud tests
  build/cli/src/lib.rs
  test/Base_Tests/src/Network/Enso_Cloud/Cloud_Tests_Setup.enso
  test/Image_Tests/src/Image_Read_Write_Spec.enso
  test/Table_Tests/src/Database/Common/Audit_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#12050 Revert "Disable visualizations for subexpressions (#11949)"
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/JobExecutionEngine.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/UpsertVisualizationJob.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
Labels: CI: No changelog needed

#11944 Invalidate queries when the user goes online + Fix offline mode
  app/common/src/queryClient.ts
  app/gui/src/dashboard/App.tsx
  app/gui/src/dashboard/authentication/cognito.mock.ts
  app/gui/src/dashboard/authentication/cognito.ts
  app/gui/src/dashboard/components/dashboard/ProjectIcon.tsx
  app/gui/src/dashboard/layouts/InfoMenu.tsx
  app/gui/src/dashboard/layouts/Settings/DeleteUserAccountSettingsSection.tsx
  app/gui/src/dashboard/layouts/Settings/SetupTwoFaForm.tsx
  app/gui/src/dashboard/layouts/Settings/index.tsx
  app/gui/src/dashboard/layouts/UserMenu.tsx
  app/gui/src/dashboard/pages/authentication/ConfirmRegistration.tsx
  app/gui/src/dashboard/pages/authentication/ForgotPassword.tsx
  app/gui/src/dashboard/pages/authentication/Login.tsx
  app/gui/src/dashboard/pages/authentication/Registration.tsx
  app/gui/src/dashboard/pages/authentication/ResetPassword.tsx
  app/gui/src/dashboard/pages/authentication/RestoreAccount.tsx
  app/gui/src/dashboard/providers/AuthProvider.tsx
  app/gui/src/dashboard/providers/SessionProvider.tsx
  app/gui/src/dashboard/providers/__test__/SessionProvider.test.tsx
  app/gui/src/dashboard/services/LocalBackend.ts
  app/gui/src/dashboard/services/RemoteBackend.ts
  app/ide-desktop/client/tasks/signArchivesMacOs.ts
Labels: CI: Ready to merge, CI: No changelog needed

#12033 Fix ClassCastException when builtin is invoked with wrong args
  distribution/lib/Standard/Base/0.0.0-dev/src/Error.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Error_Builtins.enso
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/builtins/BuiltinsInvocationTest.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/CatchErrorNode.java
Labels: CI: No changelog needed, CI: Clean build required

#12060 Address common issues after bazel merge
  .gitignore
  app/gui/project-manager-shim-middleware/index.ts
  app/gui/vite.config.ts
  build_tools/build/src/project/gui.rs
  build_tools/build/src/web.rs
  build_tools/cli/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#11988 Remove listGroups while building categories
  .github/workflows/gui-changed-files.yml
  app/common/src/services/Backend.ts
  app/gui/playwright.config.ts
  app/gui/src/dashboard/authentication/cognito.mock.ts
  app/gui/src/dashboard/components/Activity.tsx
  app/gui/src/dashboard/components/AriaComponents/Form/components/FormError.tsx
  app/gui/src/dashboard/components/Await.tsx
  app/gui/src/dashboard/components/__tests__/Activity.test.tsx
  app/gui/src/dashboard/components/dashboard/column/SharedWithColumn.tsx
  app/gui/src/dashboard/hooks/backendHooks.ts
  app/gui/src/dashboard/hooks/backendUploadFilesHooks.tsx
  app/gui/src/dashboard/layouts/AssetContextMenu.tsx
  app/gui/src/dashboard/layouts/AssetsTable.tsx
  app/gui/src/dashboard/layouts/CategorySwitcher.tsx
  app/gui/src/dashboard/layouts/Drive/Categories/Category.ts
  app/gui/src/dashboard/layouts/Drive/Categories/categoriesHooks.tsx
  app/gui/src/dashboard/layouts/UserBar.tsx
  app/gui/src/dashboard/layouts/UserMenu.tsx
  app/gui/src/dashboard/modals/ManagePermissionsModal.tsx
  app/gui/src/dashboard/modals/SetupOrganizationAfterSubscribe.tsx
  app/gui/src/dashboard/pages/authentication/AuthenticationPage.tsx
  app/gui/src/dashboard/pages/authentication/Login.tsx
  app/gui/src/dashboard/pages/dashboard/Dashboard.tsx
  app/gui/src/dashboard/providers/SessionProvider.tsx
  app/gui/src/dashboard/utilities/permissions.ts
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#12049 Marking docs/types/types.md as (mostly) outdated
  docs/types/types.md
Labels: CI: Ready to merge, CI: No changelog needed

#12035 Introduce ENSO_LAUNCHER env var to configure behavior of buildEngineDistribution
  build.sbt
  build_tools/build/src/engine.rs
  build_tools/build/src/engine/context.rs
  build_tools/build/src/engine/env.rs
  docs/infrastructure/native-image.md
  project/NativeImage.scala
Labels: CI: Ready to merge, CI: No changelog needed

#12065 Refactor Suggestion DB
  app/gui/src/project-view/components/ComponentBrowser/__tests__/component.test.ts
  app/gui/src/project-view/components/ComponentBrowser/__tests__/filtering.test.ts
  app/gui/src/project-view/components/ComponentBrowser/component.ts
  app/gui/src/project-view/components/ComponentBrowser/filtering.ts
  app/gui/src/project-view/components/ComponentBrowser/input.ts
  app/gui/src/project-view/components/DocumentationPanel/ir.ts
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetFunction/__tests__/widgetFunctionCallInfo.test.ts
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetFunction/widgetFunctionCallInfo.ts
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui/src/project-view/stores/graph/graphDatabase.ts
  app/gui/src/project-view/stores/graph/imports.ts
  app/gui/src/project-view/stores/suggestionDatabase/__tests__/documentation.test.ts
  app/gui/src/project-view/stores/suggestionDatabase/__tests__/lsUpdate.test.ts
  app/gui/src/project-view/stores/suggestionDatabase/documentation.ts
  app/gui/src/project-view/stores/suggestionDatabase/entry.ts
  app/gui/src/project-view/stores/suggestionDatabase/index.ts
  app/gui/src/project-view/stores/suggestionDatabase/lsUpdate.ts
  app/gui/src/project-view/stores/suggestionDatabase/mockSuggestion.ts
  app/gui/src/project-view/util/callTree.ts
  app/ydoc-shared/src/languageServerTypes/suggestions.ts
Labels: CI: Ready to merge, CI: No changelog needed

#12066 Provide fallback local ENSO_IDE_PROJECT_MANAGER_URL for all builds.
  app/gui/.env
  app/gui/vite.config.ts
Labels: CI: Ready to merge, CI: No changelog needed

#12070 Mention that WSL bash is not suitable on Windows
  docs/CONTRIBUTING.md
Labels: CI: Ready to merge, CI: No changelog needed

#12058 refactor RunningLooper
  std-bits/table/src/main/java/org/enso/table/operations/AddGroupNumber.java
  std-bits/table/src/main/java/org/enso/table/operations/AddRowNumber.java
  std-bits/table/src/main/java/org/enso/table/operations/AddRunning.java
  std-bits/table/src/main/java/org/enso/table/operations/GroupRowVisitor.java
  std-bits/table/src/main/java/org/enso/table/operations/GroupingOrderingVisitor.java
  std-bits/table/src/main/java/org/enso/table/operations/RowVisitorFactory.java
  std-bits/table/src/main/java/org/enso/table/operations/RunningStatistic.java
Labels: CI: No changelog needed

#12055 Add horizontal lines to table viz
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor.vue
  app/gui/src/project-view/components/visualizations/TableVisualization.vue
Labels: CI: Ready to merge, CI: No changelog needed

#12032 Dynamic widget improvements to `Table.filter`.
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
Labels: CI: Ready to merge, CI: No changelog needed

#10291 Infrastructure for `enso --docs` option & signature generator
  engine/polyglot-api/src/main/scala/org/enso/polyglot/Module.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/TopScope.scala
  engine/runner/src/main/java/org/enso/runner/Main.java
  engine/runner/src/test/java/org/enso/runner/EngineMainTest.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/dump/DocsDispatch.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/dump/DocsEmitMarkdown.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/dump/DocsEmitSignatures.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/dump/DocsGenerate.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/dump/DocsUtils.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/dump/DocsVisit.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/phase/ImportResolverForIR.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/phase/ImportResolver.scala
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/dump/test/DocsGenerateTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/SerdeCompilerTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/SerializationManagerTest.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/TopLevelScope.java
  lib/java/test-utils/src/main/java/org/enso/test/utils/ProjectUtils.java
Labels: w-docs, CI: No changelog needed, -compiler, -parser

#12064 Fix header rename
  CHANGELOG.md
  app/common/src/utilities/data/object.ts
  app/gui/src/project-view/components/CodeEditor/CodeEditorImpl.vue
  app/gui/src/project-view/components/CodeEditor/tooltips.ts
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor/TableHeader.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor/__tests__/tableInputArgument.test.ts
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor/tableInputArgument.ts
  app/gui/src/project-view/components/MarkdownEditor/MarkdownEditorImpl.vue
  app/gui/src/project-view/components/MarkdownEditor/markdown/decoration/linksAndImages.ts
  app/gui/src/project-view/components/MarkdownEditor/markdown/decoration/table.ts
  app/gui/src/project-view/components/MarkdownEditor/markdown/decoration/treeStateDecorator.ts
  app/gui/src/project-view/components/MarkdownEditor/markdown/decoration/treeViewDecorator.ts
  app/gui/src/project-view/components/PlainTextEditor/PlainTextEditorImpl.vue
  app/gui/src/project-view/components/VueComponentHost.vue
  app/gui/src/project-view/components/VueHostRender.vue
  app/gui/src/project-view/components/shared/AgGridTableView.vue
  app/gui/src/project-view/components/shared/AgGridTableView/AgGridVue.ts
  app/gui/src/project-view/components/shared/AgGridTableView/Utils.ts
  app/gui/src/project-view/util/codemirror/index.ts
  app/gui/src/project-view/util/codemirror/linkEditPopup.ts
  app/gui/src/project-view/util/codemirror/vueHostExt.ts
Labels: CI: Ready to merge, -gui

#12085 Adapt `parse` test for Snowflake edge case
  test/Table_Tests/src/Common_Table_Operations/Conversion_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#12079 Joined buttons
  app/gui/package.json
  app/gui/src/dashboard/assets/expand_arrow_down.svg
  app/gui/src/dashboard/assets/expand_arrow_right.svg
  app/gui/src/dashboard/assets/expand_arrow_up.svg
  app/gui/src/dashboard/assets/sort_ascending.svg
  app/gui/src/dashboard/components/AriaComponents/Button/Button.stories.tsx
  app/gui/src/dashboard/components/AriaComponents/Button/Button.tsx
  app/gui/src/dashboard/components/AriaComponents/Button/ButtonGroup.tsx
  app/gui/src/dashboard/components/AriaComponents/Button/CloseButton.tsx
  app/gui/src/dashboard/components/AriaComponents/Button/CopyButton.tsx
  app/gui/src/dashboard/components/AriaComponents/Button/index.ts
  app/gui/src/dashboard/components/AriaComponents/Button/shared.tsx
  app/gui/src/dashboard/components/AriaComponents/Button/types.ts
  app/gui/src/dashboard/components/AriaComponents/Button/variants.ts
  app/gui/src/dashboard/components/AriaComponents/Dialog/DialogDismiss.tsx
  app/gui/src/dashboard/components/AriaComponents/Dialog/Popover.tsx
  app/gui/src/dashboard/components/AriaComponents/Form/components/Reset.tsx
  app/gui/src/dashboard/components/AriaComponents/Tooltip/Tooltip.tsx
  app/gui/src/dashboard/components/dashboard/column/PathColumn.tsx
  eslint.config.mjs
  pnpm-lock.yaml
Labels: CI: No changelog needed, g-dashboard

#12080 Menu component
  app/gui/.storybook/preview.tsx
  app/gui/.storybook/storybook.css
  app/gui/integration-test/dashboard/userSettings.spec.ts
  app/gui/package.json
  app/gui/src/dashboard/App.tsx
  app/gui/src/dashboard/components/AnimatedBackground.tsx
  app/gui/src/dashboard/components/AriaComponents/Button/Button.stories.tsx
  app/gui/src/dashboard/components/AriaComponents/Button/Button.tsx
  app/gui/src/dashboard/components/AriaComponents/Check/Check.stories.tsx
  app/gui/src/dashboard/components/AriaComponents/Check/Check.tsx
  app/gui/src/dashboard/components/AriaComponents/Check/index.ts
  app/gui/src/dashboard/components/AriaComponents/Checkbox/Checkbox.stories.tsx
  app/gui/src/dashboard/components/AriaComponents/Checkbox/Checkbox.tsx
  app/gui/src/dashboard/components/AriaComponents/Checkbox/CheckboxContext.tsx
  app/gui/src/dashboard/components/AriaComponents/Checkbox/CheckboxGroup.tsx
  app/gui/src/dashboard/components/AriaComponents/Dialog/Dialog.stories.tsx
  app/gui/src/dashboard/components/AriaComponents/Dialog/Dialog.tsx
  app/gui/src/dashboard/components/AriaComponents/Dialog/Popover.stories.tsx
  app/gui/src/dashboard/components/AriaComponents/Dialog/Popover.tsx
  app/gui/src/dashboard/components/AriaComponents/Dialog/variants.ts
  app/gui/src/dashboard/components/AriaComponents/Form/components/Field.tsx
  app/gui/src/dashboard/components/AriaComponents/Inputs/ComboBox/ComboBox.tsx
  app/gui/src/dashboard/components/AriaComponents/Inputs/DatePicker/DatePicker.tsx
  app/gui/src/dashboard/components/AriaComponents/Inputs/Input/Input.tsx
  app/gui/src/dashboard/components/AriaComponents/Inputs/MultiSelector/MultiSelector.stories.tsx
  app/gui/src/dashboard/components/AriaComponents/Inputs/MultiSelector/MultiSelector.tsx
  app/gui/src/dashboard/components/AriaComponents/Inputs/OTPInput/OTPInput.tsx
  app/gui/src/dashboard/components/AriaComponents/Inputs/Selector/Selector.stories.tsx
  app/gui/src/dashboard/components/AriaComponents/Inputs/Selector/Selector.tsx
  app/gui/src/dashboard/components/AriaComponents/Menu/Menu.stories.tsx
  app/gui/src/dashboard/components/AriaComponents/Menu/Menu.tsx
  app/gui/src/dashboard/components/AriaComponents/Menu/MenuItem.tsx
  app/gui/src/dashboard/components/AriaComponents/Menu/MenuTrigger.tsx
  app/gui/src/dashboard/components/AriaComponents/Menu/index.ts
  app/gui/src/dashboard/components/AriaComponents/Radio/Radio.tsx
  app/gui/src/dashboard/components/AriaComponents/Radio/RadioGroup.tsx
  app/gui/src/dashboard/components/AriaComponents/Separator.tsx
  app/gui/src/dashboard/components/AriaComponents/Switch/Switch.tsx
  app/gui/src/dashboard/components/AriaComponents/Text/Text.stories.tsx
  app/gui/src/dashboard/components/AriaComponents/Text/Text.tsx
  app/gui/src/dashboard/components/AriaComponents/index.ts
  app/gui/src/dashboard/components/AriaComponents/types.ts
  app/gui/src/dashboard/components/Autocomplete.tsx
  app/gui/src/dashboard/components/UIProviders.tsx
  app/gui/src/dashboard/components/dashboard/column/PathColumn.tsx
  app/gui/src/dashboard/components/styled/RadioGroup.tsx
  app/gui/tailwind.config.ts
  pnpm-lock.yaml
Labels: CI: Ready to merge, CI: No changelog needed

#12087 Next step in In-Memory tidy up work.
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Fan_Out.enso
  std-bits/snowflake/src/main/java/org/enso/snowflake/SnowflakeIntegerColumnMaterializer.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/BigDecimalBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/BigIntegerBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/BoolBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/BoundCheckedIntegerBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/Builder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/DateBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/DateTimeBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/DoubleBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/InferredBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/InferredDoubleBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/InferredIntegerBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/LongBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/MixedBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/NumericBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/ObjectBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/StringBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/TimeOfDayBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/TypedBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/UnaryOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/StorageConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/ToBigDecimalConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/ToBigIntegerConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/ToBooleanStorageConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/ToDateStorageConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/ToDateTimeStorageConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/ToFloatStorageConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/ToIntegerStorageConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/ToTextStorageConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/ToTimeOfDayStorageConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/GenericBinaryObjectMapOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/datetime/TimeLikeCoalescingOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/BigDecimalRoundOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/AbstractUnaryBooleanOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/AbstractUnaryLongOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/AbstractUnaryOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/DateTruncateOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/UnaryRoundOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/MixedStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/Storage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/DoubleStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/LongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/index/CrossTabIndex.java
  std-bits/table/src/main/java/org/enso/table/data/index/MultiValueIndex.java
  std-bits/table/src/main/java/org/enso/table/data/table/Column.java
  std-bits/table/src/main/java/org/enso/table/data/table/join/lookup/LookupJoin.java
  std-bits/table/src/main/java/org/enso/table/parsing/IncrementalDatatypeParser.java
  std-bits/table/src/main/java/org/enso/table/parsing/TypeInferringParser.java
  std-bits/table/src/main/java/org/enso/table/read/DelimitedReader.java
  std-bits/table/src/main/java/org/enso/table/read/ExcelReader.java
  test/Exploratory_Benchmarks/src/Table/Column_Bi_Map.enso
  test/Exploratory_Benchmarks/src/Table/Column_Map.enso
  test/Exploratory_Benchmarks/src/Table/Column_Map_2.enso
  test/Exploratory_Benchmarks/src/Table/Enso_Callback.enso
Labels: CI: Ready to merge, CI: No changelog needed

#12094 Remove sentry from .env file
  app/gui/.env
  app/gui/.env.testing
  app/gui/src/entrypoint.ts
Labels: CI: Ready to merge, CI: No changelog needed, x-chore, g-dashboard, -gui

#12096 In-Memory Refactor Part 3
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/Internal/SQLServer_Dialect.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Dialect.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Column_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Display_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Java_Exports.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  distribution/lib/Standard/Tableau/0.0.0-dev/src/Hyper_Table.enso
  test/Exploratory_Benchmarks/src/Table/Enso_Callback.enso
  test/Exploratory_Benchmarks/src/Table/Helpers.enso
Labels: CI: Ready to merge, CI: No changelog needed

#12105 Fix DB maintenance actions broken by #7117
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/JDBC_Connection.enso
Labels: CI: Ready to merge, CI: No changelog needed

#12107 Add cloud icons. Remove some unused icons.
  app/gui/src/project-view/assets/icons.svg
  app/gui/src/project-view/components/GraphEditor/GraphNode.vue
Labels: CI: No changelog needed

#12097 BenchmarksRunner does not override jvm args of forked processes.
  lib/java/benchmarks-common/src/main/java/org/enso/interpreter/bench/BenchmarksRunner.java
Labels: CI: Ready to merge, CI: No changelog needed

#12013 Improve scatterplot legend entance/exits
  app/gui/src/project-view/components/visualizations/ScatterplotVisualization.vue
Labels: CI: Ready to merge, CI: No changelog needed

#12072 Use AG Grid filter types
  app/gui/src/project-view/components/visualizations/TableVisualization.vue
  app/gui/src/project-view/components/visualizations/TableVisualization/tableVizToolbar.ts
Labels: CI: Ready to merge, CI: No changelog needed

#12076 Fix spurious imports, clean up tests
  app/gui/src/project-view/stores/graph/__tests__/imports.test.ts
  app/gui/src/project-view/stores/graph/imports.ts
  app/gui/src/project-view/stores/suggestionDatabase/lsUpdate.ts
  app/gui/src/project-view/stores/suggestionDatabase/mockSuggestion.ts
Labels: CI: No changelog needed

#12121 Unhandled Java Exceptions not handled in same way as Enso panics
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/id/execution/IdExecutionInstrument.java
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeErrorsTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/TestMessages.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicSentinel.java
Labels: CI: Ready to merge, CI: No changelog needed

#12017 `Download_Mode` for `File`, `S3_File` and `Enso_File`
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Download/Download_Mode.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  std-bits/table/src/main/java/org/enso/table/excel/ExcelConnectionPool.java
  test/AWS_Tests/src/S3_Spec.enso
  test/Base_Tests/src/Data/Data_Spec.enso
  test/Base_Tests/src/Network/Enso_Cloud/Enso_File_Spec.enso
  test/Base_Tests/src/System/File_Spec.enso
Labels: CI: Ready to merge, CI: Clean build required

#12104 Better error when unknown language is used with `foreign` in binary mode
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/ForeignMethodInvokeTest.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/ForeignEvalNode.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/ForeignParsingException.java
Labels: CI: Ready to merge, CI: No changelog needed

#12117 `ENSO_LAUNCHER` can be `native,test,debug,fast,-ls`
  build.sbt
  build_tools/build/src/engine.rs
  build_tools/build/src/engine/context.rs
  docs/infrastructure/native-image.md
  engine/runner/src/main/java/org/enso/runner/EnsoLibraryFeature.java
  project/DistributionPackage.scala
  project/GraalVM.scala
Labels: CI: Ready to merge, CI: Keep up to date, CI: No changelog needed, CI: Clean build required

#12125 Second batch of dashboard/cloud icons
  app/gui/src/project-view/assets/icons.svg
Labels: CI: No changelog needed

#12127 Fix mouse interactions in node visualizations
  app/gui/src/project-view/components/GraphEditor/GraphNode.vue
  app/gui/src/project-view/components/visualizations/JSONVisualization/JsonObjectWidget.vue
  app/gui/src/project-view/components/visualizations/ScatterplotVisualization.vue
Labels: CI: Ready to merge, CI: No changelog needed

#12059 Move Help section to the Topbar
  app/common/src/text/english.json
  app/gui/.storybook/preview.tsx
  app/gui/integration-test/dashboard/assetsTableFeatures.spec.ts
  app/gui/src/ReactRoot.tsx
  app/gui/src/dashboard/components/AnimatedBackground.tsx
  app/gui/src/dashboard/components/AriaComponents/Dialog/Dialog.tsx
  app/gui/src/dashboard/components/UIProviders.tsx
  app/gui/src/dashboard/configurations/topbarLinks.json
  app/gui/src/dashboard/layouts/UserBar.tsx
  app/gui/src/dashboard/layouts/stories/UserBar.stories.tsx
  app/gui/src/dashboard/styles.css
  app/gui/src/dashboard/test/testUtils.tsx
  app/gui/src/dashboard/utilities/url.ts
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required, g-dashboard

#12130 Remove storage from offset
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Offset_Helper.enso
  std-bits/table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/SpecializedStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/Storage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/ComputedLongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/ComputedNullableLongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/DoubleStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/LongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/mask/OrderMask.java
  std-bits/table/src/main/java/org/enso/table/data/table/join/lookup/LookupJoin.java
  std-bits/table/src/main/java/org/enso/table/operations/Offset.java
Labels: CI: No changelog needed

#12124 Component status colors
  app/gui/integration-test/project-view/edgeRendering.spec.ts
  app/gui/src/project-view/assets/base.css
  app/gui/src/project-view/components/GraphEditor/GraphEdge.vue
  app/gui/src/project-view/components/GraphEditor/GraphNode.vue
  app/gui/src/project-view/composables/componentColors.ts
  app/gui/src/project-view/stores/graph/unconnectedEdges.ts
Labels: CI: Ready to merge, CI: No changelog needed

#12135 Bump vite 6.0.9
  app/gui/package.json
  app/ide-desktop/client/package.json
  pnpm-lock.yaml
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#12145 Disable bazel remote cache on self-hosted runners
  .github/workflows/changelog.yml
  .github/workflows/engine-benchmark.yml
  .github/workflows/engine-checks-nightly.yml
  .github/workflows/engine-checks-optional.yml
  .github/workflows/engine-checks.yml
  .github/workflows/extra-nightly-tests.yml
  .github/workflows/gui-checks.yml
  .github/workflows/ide-packaging-optional.yml
  .github/workflows/ide-packaging.yml
  .github/workflows/promote.yml
  .github/workflows/release.yml
  .github/workflows/std-libs-benchmark.yml
  .github/workflows/wasm-checks.yml
  build_tools/build/src/ci_gen.rs
  build_tools/build/src/ci_gen/job.rs
  build_tools/ci_utils/src/actions/workflow/definition.rs
Labels: CI: No changelog needed

#12067 Tooltips fixes
  CHANGELOG.md
  app/gui/src/project-view/components/MenuButton.vue
  app/gui/src/project-view/components/TooltipDisplayer.vue
  app/gui/src/project-view/components/TooltipTrigger.vue
  app/gui/src/project-view/providers/tooltipRegistry.ts
  app/gui/src/project-view/util/equals.ts
Labels: CI: Ready to merge, --bug, -gui

#12115 Breadcrumbs component
  .github/workflows/gui-checks.yml
  app/common/package.json
  app/common/src/text/english.json
  app/gui/package.json
  app/gui/src/dashboard/assets/expand_arrow.svg
  app/gui/src/dashboard/assets/three_horizontal_dots_outline.svg
  app/gui/src/dashboard/components/AriaComponents/Button/ButtonGroup.tsx
  app/gui/src/dashboard/components/AriaComponents/Button/types.ts
  app/gui/src/dashboard/components/AriaComponents/Button/variants.ts
  app/gui/src/dashboard/components/AriaComponents/Dialog/Popover.tsx
  app/gui/src/dashboard/components/AriaComponents/Menu/Menu.stories.tsx
  app/gui/src/dashboard/components/AriaComponents/Menu/Menu.tsx
  app/gui/src/dashboard/components/AriaComponents/Menu/MenuItem.tsx
  app/gui/src/dashboard/components/AriaComponents/Text/Text.tsx
  app/gui/src/dashboard/components/AriaComponents/types.ts
  app/gui/src/dashboard/components/Breadcrumbs/BreadcrumbItem.tsx
  app/gui/src/dashboard/components/Breadcrumbs/Breadcrumbs.stories.tsx
  app/gui/src/dashboard/components/Breadcrumbs/Breadcrumbs.test.tsx
  app/gui/src/dashboard/components/Breadcrumbs/Breadcrumbs.tsx
  app/gui/src/dashboard/components/Breadcrumbs/index.ts
  app/gui/src/dashboard/components/Breadcrumbs/utilities.ts
  app/gui/src/dashboard/components/Icon/Icon.stories.tsx
  app/gui/src/dashboard/components/Icon/Icon.tsx
  app/gui/src/dashboard/components/Icon/index.ts
  app/gui/src/dashboard/components/SvgMask.tsx
  app/gui/src/dashboard/components/dashboard/column.ts
  app/gui/src/dashboard/hooks/scrollHooks.ts
  app/gui/src/dashboard/layouts/UserBar.tsx
  app/ydoc-server/package.json
  app/ydoc-shared/package.json
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#12148 Workaround UnresolvedSymbol issues on CI
  distribution/lib/Standard/Base/0.0.0-dev/src/Meta.enso
Labels: CI: No changelog needed

#12116 Hide `main` signature in doc editor
  app/gui/src/project-view/components/ComponentBrowser.vue
  app/gui/src/project-view/components/GraphEditor.vue
  app/gui/src/project-view/components/GraphEditor/GraphNodes.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetFunctionDef.vue
  app/gui/src/project-view/composables/nodeCreation.ts
  app/gui/src/project-view/stores/graph/index.ts
  app/gui/src/project-view/stores/persisted.ts
  app/gui/src/project-view/stores/rightDock.ts
Labels: CI: No changelog needed

#12126 Display component evaluating status
  app/gui/integration-test/project-view/graphRenderNodes.spec.ts
  app/gui/src/project-view/components/GraphEditor/ComponentWidgetTree.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetIcon.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelfAccessChain.vue
  app/gui/src/project-view/util/getIconName.ts
Labels: CI: No changelog needed

#12147 Enable bazel caches for lint and deploy storybook jobs
  .github/workflows/gui-checks.yml
  .github/workflows/storybook.yml
Labels: CI: Ready to merge, CI: No changelog needed, -ci

#12139 Remove logging
  std-bits/table/src/main/java/org/enso/table/excel/ExcelConnectionPool.java
Labels: CI: Ready to merge, CI: No changelog needed

#12141 Remove magic numbers from SQL generation
  distribution/lib/Standard/AWS/0.0.0-dev/src/Database/Redshift/Internal/Redshift_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/IR/Context.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQL_Part.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/Internal/SQLServer_Dialect.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Dialect.enso
Labels: CI: Ready to merge, CI: No changelog needed

#12140 Hide Enso devtools in Prod for users outside of enso team
  app/gui/src/dashboard/components/Devtools/EnsoDevtools.tsx
  app/gui/src/dashboard/components/Devtools/EnsoDevtoolsProvider.tsx
  app/gui/src/dashboard/layouts/UserMenu.tsx
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#12144 Adding some practical tests for intersection types in context of using them for 'refining' types
  test/Base_Tests/src/Main.enso
  test/Base_Tests/src/Semantic/Multi_Value_As_Type_Refinement_Spec.enso
  test/Base_Tests/src/Semantic/Multi_Value_Spec.enso
  test/Base_Tests/src/Semantic/Type_Refinement/Hidden_Conversions.enso
  test/Base_Tests/src/Semantic/Type_Refinement/Types.enso
Labels: CI: Ready to merge, CI: No changelog needed

#12167 Disable flaky test
  test/Table_Tests/src/IO/Excel_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#12061 Dump compiler IR to IGV
  .jvmopts
  build.sbt
  docs/runtime/compiler-ir.md
  engine/common/src/main/java/org/enso/common/RuntimeOptions.java
  engine/runtime-compiler-dump-igv/src/main/java/module-info.java
  engine/runtime-compiler-dump-igv/src/main/java/org/enso/compiler/dump/igv/ASTBlock.java
  engine/runtime-compiler-dump-igv/src/main/java/org/enso/compiler/dump/igv/ASTDumpStructure.java
  engine/runtime-compiler-dump-igv/src/main/java/org/enso/compiler/dump/igv/ASTEdge.java
  engine/runtime-compiler-dump-igv/src/main/java/org/enso/compiler/dump/igv/ASTLocation.java
  engine/runtime-compiler-dump-igv/src/main/java/org/enso/compiler/dump/igv/ASTMethod.java
  engine/runtime-compiler-dump-igv/src/main/java/org/enso/compiler/dump/igv/ASTNode.java
  engine/runtime-compiler-dump-igv/src/main/java/org/enso/compiler/dump/igv/ASTNodeClass.java
  engine/runtime-compiler-dump-igv/src/main/java/org/enso/compiler/dump/igv/EnsoModuleAST.java
  engine/runtime-compiler-dump-igv/src/main/java/org/enso/compiler/dump/igv/IGVDumper.java
  engine/runtime-compiler-dump-igv/src/main/java/org/enso/compiler/dump/igv/IGVDumperFactory.java
  engine/runtime-compiler-dump-igv/src/main/java/org/enso/compiler/dump/igv/Utils.java
  engine/runtime-compiler-dump-igv/src/main/java/org/enso/compiler/dump/igv/package-info.java
  engine/runtime-compiler-dump/src/main/java/module-info.java
  engine/runtime-compiler-dump/src/main/java/org/enso/compiler/dump/service/IRDumpFactoryService.java
  engine/runtime-compiler-dump/src/main/java/org/enso/compiler/dump/service/IRDumpSingleton.java
  engine/runtime-compiler-dump/src/main/java/org/enso/compiler/dump/service/IRDumper.java
  engine/runtime-compiler/src/main/java/module-info.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/docs/DocsDispatch.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/docs/DocsEmitMarkdown.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/docs/DocsEmitSignatures.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/docs/DocsGenerate.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/docs/DocsUtils.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/docs/DocsVisit.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/dump/GraphVizEdge.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/dump/GraphVizNode.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/dump/IRDumper.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/dump/IRDumperPass.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/dump/Utils.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/Passes.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/data/CompilerConfig.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/PassManager.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/phase/BuiltinsIrBuilder.scala
  engine/runtime-instrument-common/src/test/scala/org/enso/compiler/test/CompilerTestSetup.scala
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/dump/test/DocsGenerateTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/dump/test/IRDumpTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/WithIRDumper.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/mini/passes/MiniPassTester.java
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/CompilerTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/EnsoLanguage.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  lib/java/test-utils/src/main/java/org/enso/test/utils/IRDumperTestWrapper.java
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#12157 Always attempt to resolve to a default edition
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/DefaultPackageRepository.scala
  lib/scala/editions/src/test/scala/org/enso/editions/EditionResolverSpec.scala
Labels: CI: No changelog needed

#12169 Avoiding duplicated code inside of the with index and `-NoIndex` tasks
  build.sbt
  project/DistributionPackage.scala
Labels: CI: Ready to merge, CI: No changelog needed

#12156 Enable Standard.AWS and Standard.Microsoft in native image
  build.sbt
  build_tools/build/src/engine/context.rs
  std-bits/microsoft/src/main/resources/META-INF/native-image/org/enso/microsoft/resource-config.json
  test/Microsoft_Tests/README.md
Labels: CI: No changelog needed, CI: Clean build required

#12172 Expect failure when parsing external Qualified Names
  app/gui/src/project-view/components/ComponentBrowser/__tests__/filtering.test.ts
  app/gui/src/project-view/components/DocumentationPanel.vue
  app/gui/src/project-view/components/GraphEditor/GraphNodeMessage.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetFunction/__tests__/widgetFunctionCallInfo.test.ts
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor/__tests__/tableInputArgument.test.ts
  app/gui/src/project-view/stores/graph/__tests__/imports.test.ts
  app/gui/src/project-view/stores/graph/graphDatabase.ts
  app/gui/src/project-view/stores/graph/imports.ts
  app/gui/src/project-view/stores/graph/index.ts
  app/gui/src/project-view/stores/project/computedValueRegistry.ts
  app/gui/src/project-view/stores/projectNames.ts
  app/gui/src/project-view/stores/suggestionDatabase/__tests__/documentation.test.ts
  app/gui/src/project-view/stores/suggestionDatabase/__tests__/lsUpdate.test.ts
  app/gui/src/project-view/stores/suggestionDatabase/lsUpdate.ts
  app/gui/src/project-view/util/__tests__/callTree.test.ts
  app/gui/src/project-view/util/__tests__/projectPath.test.ts
  app/gui/src/project-view/util/__tests__/qualifiedName.test.ts
  app/gui/src/project-view/util/methodPointer.ts
  app/gui/src/project-view/util/projectPath.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#12173 Make test dir unique in S3_Spec
  test/AWS_Tests/data/credentials-with-secrets.datalink
  test/AWS_Tests/src/S3_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#12129 Quick Editing in Table Editor Widget
  CHANGELOG.md
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor/TableHeader.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor/__tests__/editHandler.test.ts
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor/editHandler.ts
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor/tableInputArgument.ts
  app/gui/src/project-view/components/shared/AgGridTableView.vue
  app/gui/src/project-view/providers/index.ts
  app/ydoc-shared/src/ast/tree.ts
Labels: CI: Ready to merge, -gui

#12175 Prepare API generator for automatic check
  engine/runtime-compiler/src/main/java/org/enso/compiler/docs/BindingSorter.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/docs/DocsEmitSignatures.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/docs/DocsGenerate.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/dump/test/ApiModificationTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/dump/test/BindingSorterTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/dump/test/DocsGenerateOrderTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/dump/test/DocsGenerateTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/dump/test/DumpTestUtils.java
  lib/java/scala-libs-wrapper/src/main/java/org/enso/scala/wrapper/ScalaConversions.java
  lib/java/test-utils/src/main/java/org/enso/test/utils/ProjectUtils.java
  test/Examples_Tests/data/signatures/Meta.md
  test/Examples_Tests/src/Signatures_Spec.enso
Labels: CI: No changelog needed, CI: Clean build required
