Repository enso-org/enso, pull requests merged in 2025-07, with the labels that each got.

#13312 Update Project Session Logs view
  app/common/src/services/Backend.ts
  app/common/src/text/english.json
  app/gui/src/dashboard/components/Scroller/Scroller.tsx
  app/gui/src/dashboard/layouts/AssetPanel/components/AssetDiffView.tsx
  app/gui/src/dashboard/layouts/AssetPanel/components/ProjectSessions.tsx
  app/gui/src/dashboard/layouts/SearchBar.tsx
  app/gui/src/dashboard/modals/ProjectLogsModal.tsx
  app/gui/src/dashboard/services/RemoteBackend.ts
  app/gui/src/providers/httpClient.ts
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#13406 No shutdown timeout in std-benchmarks
  build.sbt
Labels: CI: No changelog needed

#13404 Bump compilation timeout for NI on CI
  project/NativeImage.scala
Labels: CI: No changelog needed

#13335 Pooled file chunk uploads
  app/common/src/queryClient.ts
  app/common/src/text.ts
  app/common/src/text/english.json
  app/common/src/utilities/ConditionVariable.ts
  app/common/src/utilities/file.ts
  app/gui/package.json
  app/gui/src/dashboard/components/Devtools/EnsoDevtoolsImpl.tsx
  app/gui/src/dashboard/hooks/backendHooks.ts
  app/gui/src/dashboard/hooks/backendUploadFilesHooks.tsx
  app/gui/src/dashboard/pages/dashboard/Drive/DriveBar/DriveBarToolbar.tsx
  app/gui/src/dashboard/pages/dashboard/UserBar/NotificationTray/computedNotificationHooks.tsx
  app/gui/src/providers/featureFlags.ts
  pnpm-lock.yaml
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#13416 Fix bugs in the way we talked with language server
  app/gui/src/project-view/stores/project/nodeExecution.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#13415 Add execute_query to the Connection types.
  CHANGELOG.md
  distribution/lib/Standard/Database/0.0.0-dev/docs/api/Connection/Connection.md
  distribution/lib/Standard/Database/0.0.0-dev/docs/api/Connection/Postgres_Connection.md
  distribution/lib/Standard/Database/0.0.0-dev/docs/api/Connection/SQLite_Connection.md
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Postgres_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/SQLite_Connection.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/docs/api/SQLServer_Connection.md
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/SQLServer_Connection.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/docs/api/Snowflake_Connection.md
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Snowflake_Connection.enso
  test/Table_Tests/src/Database/Common/Common_Spec.enso
Labels: CI: Ready to merge, -libs-API-change-Database, -libs-API-change-Microsoft, -libs-API-change-Snowflake

#13355 Add google sheets skip and limit
  distribution/lib/Standard/Google_Api/0.0.0-dev/docs/api/Google_Sheets_Workbook.md
  distribution/lib/Standard/Google_Api/0.0.0-dev/src/Google_Sheets_Workbook.enso
  std-bits/google-api/src/main/java/org/enso/google/GoogleSheetsForEnso.java
  std-bits/google-api/src/main/java/org/enso/google/GoogleSheetsHeaders.java
  test/Google_Api_Test/src/Main.enso
  test/Visualization_Tests/src/Table_Visualisation_Integration_Spec.enso
Labels: CI: No changelog needed, -libs-API-change-Google_Api

#13417 Run projects in Hybrid mode by default; allow Cloud execution only on Team plan and above
  app/common/src/text/english.json
  app/common/src/utilities/data/object.ts
  app/gui/env.d.ts
  app/gui/integration-test/dashboard/actions/api.ts
  app/gui/integration-test/dashboard/actions/contextMenuActions.ts
  app/gui/integration-test/dashboard/actions/localApi.ts
  app/gui/src/App.vue
  app/gui/src/ReactRoot.tsx
  app/gui/src/components/AppContainer.vue
  app/gui/src/components/AppContainer/RightPanel.vue
  app/gui/src/dashboard/components/Devtools/EnsoDevtoolsImpl.tsx
  app/gui/src/dashboard/hooks/backendHooks.ts
  app/gui/src/dashboard/hooks/projectHooks.ts
  app/gui/src/dashboard/layouts/AssetContextMenu.tsx
  app/gui/src/dashboard/pages/dashboard/Dashboard.tsx
  app/gui/src/dashboard/pages/dashboard/components/ProjectIcon.tsx
  app/gui/src/providers/auth.ts
  app/gui/src/providers/featureFlags.ts
  app/gui/src/providers/rightPanel.ts
  app/gui/vite.test.config.ts
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#13373 Fix async/reactive issues
  app/common/package.json
  app/common/src/backendQuery.ts
  app/common/src/queryClient.ts
  app/common/src/utilities/data/__tests__/reactive.test.ts
  app/common/src/utilities/data/object.ts
  app/common/src/utilities/data/reactive.ts
  app/gui/integration-test/dashboard/actions/LoginPageActions.ts
  app/gui/package.json
  app/gui/src/dashboard/services/RemoteBackend.ts
  app/gui/src/project-view/providers/widgetRegistry.ts
  app/gui/src/project-view/util/shortcuts.ts
  app/gui/src/providers/session.ts
  app/ydoc-server/package.json
  pnpm-lock.yaml
Labels: CI: No changelog needed

#13422 Add Vector suggestions
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Extensions/Column_Vector_Extensions.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Extensions/Table_Conversions.enso
Labels: CI: Ready to merge, CI: No changelog needed

#13428 Fix `proxyRefs` bug
  app/gui/src/composables/userAgreements.ts
  app/gui/src/project-view/components/ComponentBrowser/input.ts
  app/gui/src/project-view/components/GraphEditor.vue
  app/gui/src/project-view/components/GraphEditor/GraphVisualization.vue
  app/gui/src/project-view/components/GraphEditor/NodeWidget.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetFunction.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetFunctionDef/ArgumentRow.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetPort.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor/__tests__/editHandler.test.ts
  app/gui/src/project-view/components/MarkdownEditor/codemirror/formatting/index.ts
  app/gui/src/project-view/composables/animation.ts
  app/gui/src/project-view/composables/events.ts
  app/gui/src/project-view/composables/keyboard.ts
  app/gui/src/project-view/composables/navigator.ts
  app/gui/src/project-view/providers/actionContext.ts
  app/gui/src/project-view/providers/animationCounter.ts
  app/gui/src/project-view/providers/graphSelection.ts
  app/gui/src/project-view/providers/guiConfig.ts
  app/gui/src/project-view/providers/projectBackend.ts
  app/gui/src/project-view/providers/selectionArrow.ts
  app/gui/src/project-view/providers/widgetRegistry/__tests__/editHandler.test.ts
  app/gui/src/project-view/providers/widgetTree.ts
  app/gui/src/project-view/stores/graph/index.ts
  app/gui/src/project-view/stores/persisted.ts
  app/gui/src/project-view/stores/project/index.ts
  app/gui/src/project-view/stores/suggestionDatabase/index.ts
  app/gui/src/project-view/stores/visualization/compilerMessaging.ts
  app/gui/src/project-view/util/reactivity.ts
  app/gui/src/providers/auth.ts
  app/gui/src/providers/backends.ts
  app/gui/src/providers/container.ts
  app/gui/src/providers/react/globalProvider.tsx
  app/gui/src/providers/rightPanel.ts
  app/gui/src/providers/session.ts
  app/gui/src/providers/text.ts
  app/gui/src/router/__tests__/dataLoader.test.ts
  eslint.config.mjs
Labels: CI: No changelog needed

#13376 IGV that works with GraalVM 24.0.1 is out
  tools/enso4igv/IGV.md
  tools/enso4igv/pom.xml
  tools/enso4igv/src/main/nbm/manifest.mf
Labels: CI: No changelog needed

#13387 Only reordering in Type.from for eligible EnsoMultiValue
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/ConversionMethodTests.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeConversionNode.java
Labels: CI: No changelog needed

#13435 Update Snowflake_Connection Viz
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/SQLServer_Connection.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Connection/Snowflake_Details.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Snowflake_Connection.enso
Labels: CI: No changelog needed

#13453 Add Contact Us link to the top bar
  app/common/src/text/english.json
  app/gui/src/dashboard/configurations/topbarLinks.json
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#13448 Snowflake Bulk Load tests
  std-bits/snowflake/src/main/resources/META-INF/native-image/org/enso/snowflake/proxy-config.json
  std-bits/snowflake/src/main/resources/META-INF/native-image/org/enso/snowflake/reflect-config.json
  std-bits/snowflake/src/main/resources/META-INF/native-image/org/enso/snowflake/resource-config.json
  test/Snowflake_Tests/README.md
  test/Snowflake_Tests/src/Main.enso
  test/Snowflake_Tests/src/Snowflake_Bulk_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#13393 Add signing with apple
  app/common/src/text/english.json
  app/gui/src/authentication/cognito.mock.ts
  app/gui/src/authentication/cognito.ts
  app/gui/src/dashboard/pages/authentication/Login.tsx
  app/gui/src/providers/__tests__/session.test.ts
  app/gui/src/providers/session.ts
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#13456 Show 'Not for commercial use' notice in the title bar
  app/common/src/text.ts
  app/common/src/text/english.json
  app/gui/src/App.vue
  app/gui/src/composables/appTitle.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#13461 Google defect fix
  distribution/lib/Standard/Google/0.0.0-dev/src/Google_Sheets.enso
  lib/scala/pkg/src/main/resources/default/src/Main.enso
Labels: CI: No changelog needed

#13443 `Meta.meta` recognizes functions as `Meta.Function`
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Data/List.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Errors/Common.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Meta.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Filter_Condition.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/List.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Function.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Instrumentor.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Meta_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Meta.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Widgets.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/CreateUnresolvedSymbolNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/GetArgumentNamesNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/GetConstructorFieldNamesNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/GetUnresolvedSymbolNameNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/MetaKindNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/UnresolvedConstructor.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/Function.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/type/Constants.java
  test/Base_Tests/src/Data/List_Spec.enso
  test/Base_Tests/src/Semantic/Conversion_Spec.enso
  test/Base_Tests/src/Semantic/Meta_Spec.enso
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Meta.enso
Labels: CI: Clean build required, -libs-API-change-Base

#13454 Show output port of selected component
  app/common/src/queryClient.ts
  app/common/src/utilities/data/__tests__/reactive.test.ts
  app/common/src/utilities/data/callbacks.ts
  app/common/src/utilities/data/set.ts
  app/gui/src/components/WithCurrentProject.vue
  app/gui/src/project-view/components/GraphEditor.vue
  app/gui/src/project-view/components/GraphEditor/GraphEdges.vue
  app/gui/src/project-view/components/GraphEditor/GraphNode.vue
  app/gui/src/project-view/components/GraphEditor/GraphNodeOutputPorts.vue
  app/gui/src/project-view/composables/componentColors.ts
  app/gui/src/project-view/composables/selection.ts
  app/gui/src/project-view/stores/graph/index.ts
Labels: CI: Ready to merge, CI: No changelog needed

#13451 Add google sheet named range support
  distribution/lib/Standard/Google/0.0.0-dev/docs/api/Google_Sheets_Workbook.md
  distribution/lib/Standard/Google/0.0.0-dev/src/Google_Sheets_Workbook.enso
  std-bits/google/src/main/java/org/enso/google/GoogleSheetsForEnso.java
  test/Google_Test/src/Main.enso
Labels: CI: No changelog needed, -libs-API-change-Google

#13474 Scatterplot Improvement, C/B fix and Dropdown arrow fix
  app/gui/src/project-view/components/ComponentBrowser/ComponentEditor.vue
  app/gui/src/project-view/components/ComponentBrowser/ComponentEditorLabel.vue
  app/gui/src/project-view/components/DropdownMenu.vue
  app/gui/src/project-view/components/GraphEditor/GraphVisualization.vue
  app/gui/src/project-view/components/GraphEditor/GraphVisualization/VisualizationToolbar.vue
  app/gui/src/project-view/components/GraphEditor/GraphVisualization/visualizationSelector.ts
  app/gui/src/project-view/components/visualizations/ScatterplotVisualization.vue
Labels: CI: Ready to merge, CI: No changelog needed

#13465 Snowflake in --jvm mode cannot find `java.rmi.UnexpectedException`
  .github/workflows/extra-nightly-tests.yml
  build_tools/build/src/ci_gen.rs
  build_tools/build/src/ci_gen/job.rs
  build_tools/build/src/engine.rs
  build_tools/cli/src/lib.rs
  engine/runner/src/main/java/module-info.java
  project/SmallJDK.scala
Labels: CI: No changelog needed

#13468 Fix button type in Submit component
  app/gui/src/dashboard/components/Form/components/Submit.tsx
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui

#13473 Fix app title
  app/gui/src/composables/appTitle.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#13460 Avoid meta-programming when converting to Filter_Condition
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Data/Filter_Condition.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Filter_Condition.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/List.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Regex.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Array_Like_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Predicate_Helpers.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/DB_Table_Implementation.enso
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/In_Memory_Table.md
  distribution/lib/Standard/Table/0.0.0-dev/src/In_Memory_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Filter_Condition_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/In_Memory_Table_Implementation.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Simple_Expression.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicException.java
Labels: CI: Ready to merge, -libs-API-change-Base, -libs-API-change-Table

#13481 Don't specify -ea when invoking `runProjectManagerDistribution`
  project/DistributionPackage.scala
Labels: CI: No changelog needed

#13489 Docs: Fix SVG drop
  app/gui/src/project-view/components/MarkdownEditor/MarkdownEditorImpl.vue
  app/gui/src/project-view/components/MarkdownEditor/codemirror/clipboard.ts
  app/gui/src/project-view/components/MarkdownEditor/codemirror/index.ts
  app/gui/src/project-view/components/MarkdownEditor/imageFiles/backendFiles.ts
  app/gui/src/project-view/components/MarkdownEditor/imageFiles/common.ts
  app/gui/src/project-view/components/MarkdownEditor/imageFiles/projectFiles.ts
Labels: CI: Ready to merge, CI: No changelog needed

#13475 Make read_many return path as Char
  CHANGELOG.md
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Read_Many_Helpers.enso
  test/Table_Tests/src/IO/Excel_Spec.enso
  test/Table_Tests/src/IO/Read_Many_Spec.enso
  test/Visualization_Tests/src/Table_Visualisation_Integration_Spec.enso
Labels: CI: Ready to merge

#13495 Support repeated keys
  app/gui/src/project-view/bindings.ts
  app/gui/src/project-view/util/shortcuts.ts
Labels: CI: No changelog needed

#13477 Fix Settings tab
  app/gui/src/components/AppContainer.vue
  app/gui/src/components/AppContainer/SelectableTab.vue
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#13482 Directly search meta parents rather than using `isMetaInstance`
  engine/runtime-integration-tests/src/test/java/org/enso/example/TestClass.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/interop/JavaInteropTest.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/PolyglotSymbolTypeBranchNode.java
Labels: CI: No changelog needed

#13496 Suppress placeholders of partially-applied-function node references
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetFunction/widgetFunctionCallInfo.ts
  app/gui/src/project-view/stores/graph/graphDatabase.ts
  app/gui/src/project-view/stores/project/computedValueRegistry.ts
  app/gui/src/project-view/util/callTree.ts
Labels: CI: No changelog needed

#13487 Add `find_group_number`
  CHANGELOG.md
  app/gui/src/project-view/components/visualizations/ScatterplotVisualization.vue
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Filter_Condition.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Widget_Helpers.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/DB_Table_Implementation.enso
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Grouping_Method.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Internal/Widget_Helpers.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Table.md
  distribution/lib/Standard/Table/0.0.0-dev/src/Grouping_Method.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Add_Group_Number.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Add_Row_Number.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/In_Memory_Table_Implementation.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  std-bits/snowflake/src/main/java/org/enso/snowflake/SnowflakeIntegerColumnMaterializer.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/masks/MaskedStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/Storage.java
  std-bits/table/src/main/java/org/enso/table/operations/AddGroupNumber.java
  std-bits/table/src/main/java/org/enso/table/operations/AddRowNumber.java
  std-bits/table/src/main/java/org/enso/table/operations/AddRunning.java
  std-bits/table/src/main/java/org/enso/table/operations/GroupingOrderingVisitor.java
  std-bits/table/src/main/java/org/enso/table/operations/Offset.java
  std-bits/table/src/main/java/org/enso/table/operations/RowVisitorFactory.java
  test/Table_Tests/src/Common_Table_Operations/Add_Group_Number_Spec.enso
Labels: CI: Ready to merge, -libs-API-change-Table

#13471 Add modal after solo trial end
  app/common/src/backendQuery.ts
  app/common/src/services/Backend.ts
  app/common/src/text.ts
  app/common/src/text/english.json
  app/gui/src/appUtils.ts
  app/gui/src/components/AppContainerLayout.vue
  app/gui/src/dashboard/modals/TrialEndedModal.tsx
  app/gui/src/dashboard/modules/payments/components/PlanSelector/PlanSelector.tsx
  app/gui/src/dashboard/modules/payments/components/PlanSelector/components/Card.tsx
  app/gui/src/dashboard/modules/payments/components/PlanSelector/components/PlanFeatures.tsx
  app/gui/src/dashboard/modules/payments/components/PlanSelector/components/PlanSelectorDialog.tsx
  app/gui/src/dashboard/modules/payments/components/PlanSelector/components/SubscribeButton.tsx
  app/gui/src/dashboard/pages/PaymentsSuccess.tsx
  app/gui/src/dashboard/services/LocalBackend.ts
  app/gui/src/dashboard/services/RemoteBackend.ts
  app/gui/src/dashboard/services/remoteBackendPaths.ts
Labels: CI: Ready to merge, CI: No changelog needed

#13513 Fix spacebar bug in text widgets
  app/gui/integration-test/project-view/widgets.spec.ts
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection.vue
Labels: CI: Ready to merge, CI: No changelog needed

#13537 Don't show selection widget without entries
  app/gui/integration-test/project-view/widgets.spec.ts
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection.vue
Labels: CI: Ready to merge, CI: No changelog needed

#13479 Open "Welcome project" on fresh installs
  CHANGELOG.md
  app/common/src/services/Backend.ts
  app/gui/env.d.ts
  app/gui/integration-test/dashboard/actions/DrivePageActions.ts
  app/gui/integration-test/dashboard/actions/api.ts
  app/gui/integration-test/dashboard/welcomeProject.spec.ts
  app/gui/src/App.vue
  app/gui/src/components/AppContainer.vue
  app/gui/src/components/AppContainer/AppContainerInner.vue
  app/gui/src/components/AppContainer/SelectableTab.vue
  app/gui/src/components/ProtectedLayout.vue
  app/gui/src/dashboard/hooks/backendHooks.ts
  app/gui/src/dashboard/hooks/localStoreState.ts
  app/gui/src/dashboard/hooks/projectHooks.ts
  app/gui/src/dashboard/layouts/AssetPanel/components/AssetProperties.tsx
  app/gui/src/dashboard/layouts/AssetPanel/components/AssetVersions.tsx
  app/gui/src/dashboard/layouts/AssetPanel/components/ProjectExecutionsCalendar.tsx
  app/gui/src/dashboard/layouts/AssetPanel/components/ProjectSessions.tsx
  app/gui/src/dashboard/layouts/AssetsTable.tsx
  app/gui/src/dashboard/layouts/Drive.tsx
  app/gui/src/dashboard/layouts/Editor.tsx
  app/gui/src/dashboard/pages/dashboard/Dashboard/Dashboard.tsx
  app/gui/src/dashboard/pages/dashboard/Dashboard/index.ts
  app/gui/src/dashboard/pages/dashboard/Dashboard/types.ts
  app/gui/src/dashboard/pages/dashboard/Drive/DriveBar/DriveBarNavigation.tsx
  app/gui/src/dashboard/pages/dashboard/components/AssetRow.tsx
  app/gui/src/dashboard/pages/dashboard/components/ProjectIcon.tsx
  app/gui/src/dashboard/pages/dashboard/components/column/column.ts
  app/gui/src/dashboard/providers/ProjectsProvider.tsx
  app/gui/src/dashboard/services/LocalBackend.ts
  app/gui/src/dashboard/services/RemoteBackend.ts
  app/gui/src/dashboard/utilities/LocalStorage.ts
  app/gui/src/project-view/ProjectView.vue
  app/gui/src/project-view/components/ComponentHelpPanel.vue
  app/gui/src/project-view/components/GraphEditor.vue
  app/gui/src/project-view/test-entrypoint.ts
  app/gui/src/project-view/util/router.ts
  app/gui/src/providers/container.ts
  app/gui/src/providers/react/container.tsx
  app/gui/src/providers/react/index.ts
  app/gui/src/providers/react/rightPanel.tsx
  app/gui/src/router/__tests__/initialProject.test.ts
  app/gui/src/router/initialProject.ts
  app/gui/src/router/router.ts
  app/ide-desktop/client/src/globals.d.ts
  app/ide-desktop/client/src/projectManagement.ts
Labels: CI: Ready to merge

#13551 Column to_json_data for Table Viz
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Visualization/Table_Viz_Data.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Visualization/Table_Viz_Data.enso
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/In_Memory_Column.md
  distribution/lib/Standard/Table/0.0.0-dev/src/In_Memory_Column.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
  std-bits/table/src/main/java/org/enso/table/data/column/operation/JsonOperation.java
  test/Table_Tests/src/IO/Json_Spec.enso
  test/Visualization_Tests/src/Table_Spec.enso
  test/Visualization_Tests/src/Table_Visualisation_Integration_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, -libs-API-change-Base, -libs-API-change-Table

#13552 Fix deeplink parsing and login error message display
  app/gui/src/authentication/service.ts
  app/gui/src/project-view/util/__tests__/url.test.ts
  app/gui/src/project-view/util/url.ts
  app/gui/src/providers/session.ts
Labels: CI: Ready to merge, CI: No changelog needed

#13547 Fix scrollbars and file browser
  app/gui/src/components/AppContainer/RightPanel.vue
  app/gui/src/project-view/components/CodeMirrorRoot.vue
  app/gui/src/project-view/components/MarkdownEditor/MarkdownEditorImpl.vue
  app/gui/src/project-view/components/widgets/FileBrowserWidget/__tests__/ensoPath.test.ts
  app/gui/src/project-view/components/widgets/FileBrowserWidget/ensoPath.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui

#13542 Adjust bullet positioning to avoid clipping (fixes #13536)
  app/gui/src/project-view/components/MarkdownEditor/MarkdownEditorImpl.vue
Labels: CI: Ready to merge, CI: No changelog needed

#13459 Add trial progress indicator
  app/common/src/text.ts
  app/common/src/text/english.json
  app/gui/src/dashboard/components/ProgressBar/ProgressBar.tsx
  app/gui/src/dashboard/components/Text/index.ts
  app/gui/src/dashboard/pages/dashboard/UserBar/UserBar.tsx
  app/gui/src/dashboard/utilities/__tests__/time.test.ts
  app/gui/src/dashboard/utilities/time.ts
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#13546 Fix restoring user
  app/gui/src/providers/auth.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, --regression, g-dashboard

#13544 Fix z-indexing problems in selection submenu and file browser
  app/gui/src/dashboard/components/FilePathInput.tsx
  app/gui/src/project-view/components/GraphEditor/GraphNode.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui/src/project-view/components/widgets/FileBrowserWidget.vue
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui

#13559 Change Snowflake action from read -> query
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Snowflake_Connection.enso
Labels: CI: No changelog needed

#13564 Add `_display_text_` for Date, Time_Of_Day and Date_Time
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/In_Memory_Column.md
  distribution/lib/Standard/Table/0.0.0-dev/src/In_Memory_Column.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
  std-bits/table/src/main/java/org/enso/table/data/column/operation/JsonOperation.java
  test/Table_Tests/src/IO/Json_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, -libs-API-change-Table

#13483 Moving `polyglot java import` handling into `EpbLanguage`
  build.sbt
  docs/polyglot/README.md
  docs/polyglot/polyglot-bindings.md
  docs/polyglot/typing-polyglot-bindings.md
  engine/common/src/main/java/module-info.java
  engine/common/src/main/java/org/enso/common/PolyglotSymbolResolver.java
  engine/runtime-integration-tests/src/test/java/org/enso/example/TestException.java
  engine/runtime-integration-tests/src/test/java/org/enso/example/ToString.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/interop/GuestJavaInteropTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/interop/HostJavaInteropTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/interop/JavaInteropTest.java
  engine/runtime-language-epb/src/main/java/module-info.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbLanguage.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/ForeignEvalNode.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/HostClassLoader.java
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/JavaPolyglotNode.java
  engine/runtime-language-epb/src/test/java/org/enso/interpreter/epb/EpbJvmObjectTest.java
  engine/runtime-language-epb/src/test/java/org/enso/interpreter/epb/EpbParseInstrument.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoPolyglotJava.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/HostClassLoader.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicException.java
  lib/java/jvm-interop/src/main/java/module-info.java
  lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/OtherJvmException.java
  lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/OtherJvmSymbolResolver.java
  lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/TruffleClassLoader.java
  lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/api/OtherJvmClassLoader.java
  lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/impl/OtherJvmException.java
  lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/impl/OtherJvmLoader.java
  lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/impl/OtherJvmMessage.java
  lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/impl/OtherJvmObject.java
  lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/impl/OtherJvmPool.java
  lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/impl/OtherJvmResult.java
  lib/java/jvm-interop/src/main/java/org/enso/jvm/interop/impl/OtherJvmTruffleException.java
  lib/java/jvm-interop/src/main/resources/META-INF/native-image/org/enso/jvm/interop/reflect-config.json
  lib/java/jvm-interop/src/test/java/org/enso/jvm/interop/impl/OtherJvmObjectTest.java
  lib/java/persistance-dsl/src/main/java/org/enso/persist/impl/PersistableProcessor.java
  lib/java/persistance/src/test/java/org/enso/persist/PersistanceTest.java
  lib/java/test-utils/src/main/java/org/enso/test/utils/ContextUtils.java
  project/WithDebugCommand.scala
Labels: CI: No changelog needed, CI: Clean build required

#13572 Revert "Close project shortcut (#13498)"
  CHANGELOG.md
  app/gui/src/App.vue
  app/gui/src/components/AppContainer/AppContainerInner.vue
  app/gui/src/dashboard/components/MenuEntry.tsx
  app/gui/src/dashboard/configurations/inputBindings.ts
  app/gui/src/dashboard/layouts/Settings/KeyboardShortcutsSettingsSection.tsx
  app/gui/src/dashboard/layouts/Settings/data.tsx
  app/gui/src/project-view/bindings.ts
  app/gui/src/project-view/providers/action.ts
  app/ide-desktop/client/src/index.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#13576 Fix reopening local projects
  app/gui/src/dashboard/layouts/Editor.tsx
Labels: CI: Ready to merge, CI: No changelog needed, --bug, --regression, g-dashboard

#13573 Support multiple execute expression requests
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/command/ExecuteExpressionCommand.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/job/ExecuteExpressionJob.java
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/VisualizationHolder.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ExecuteJob.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeAsyncCommandsTest.scala
  lib/scala/project-manager/src/main/resources/application.conf
Labels: CI: Ready to merge, CI: No changelog needed

#13583 Improve the Table viz enso code
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/In_Memory_Column.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Internal/Visualization_Helpers.md
  distribution/lib/Standard/Table/0.0.0-dev/src/In_Memory_Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Visualization_Helpers.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
  std-bits/table/src/main/java/org/enso/table/data/column/DataQualityMetrics.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/JsonOperation.java
Labels: CI: Ready to merge, CI: No changelog needed, -libs-API-change-Table

#13587 Check all types of the argument to determine available vizzes.
  app/gui/src/project-view/components/GraphEditor/GraphVisualization.vue
  app/gui/src/project-view/components/GraphEditor/GraphVisualization/visualizationData.ts
  app/gui/src/project-view/stores/visualization/index.ts
Labels: CI: Ready to merge, CI: No changelog needed

#13585 Fix setting preferred time zone in Account settings
  app/common/src/text/english.json
  app/common/src/utilities/data/dateTime.ts
  app/gui/src/dashboard/components/Inputs/ComboBox/ComboBox.tsx
  app/gui/src/dashboard/layouts/NewProjectExecutionModal.tsx
  app/gui/src/dashboard/layouts/Settings/Input.tsx
  app/gui/src/dashboard/layouts/Settings/data.tsx
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#13591 Special handling for Date/Time values in expressions.
  std-bits/table/src/main/java/org/enso/table/expressions/ExpressionVisitorImpl.java
Labels: CI: Ready to merge, CI: No changelog needed

#13589 Allow scrolling in context menu
  app/gui/src/dashboard/components/ContextMenu.tsx
  app/gui/src/dashboard/components/Dialog/Popover.tsx
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#13584 Fixing `jvm: true` in `package.yaml` behavior
  engine/runner/src/main/java/org/enso/runner/JavaFinder.java
  engine/runner/src/main/java/org/enso/runner/Main.java
  test/Base_Tests/src/System/Runner_Spec.enso
Labels: CI: No changelog needed

#13592 Address code review for settings time zone PR
  app/common/src/utilities/data/dateTime.ts
  app/gui/src/dashboard/components/Inputs/ComboBox/ComboBox.tsx
  app/gui/src/dashboard/layouts/Settings/Input.tsx
  app/gui/src/dashboard/layouts/Settings/data.tsx
Labels: CI: Ready to merge, CI: No changelog needed, x-chore, g-dashboard

#13195 Engine and GUI changes for Strava OAuth
  .github/workflows/ide-packaging-optional.yml
  .github/workflows/ide-packaging.yml
  .github/workflows/release.yml
  .github/workflows/std-libs-labels.yml
  app/common/src/services/Backend.ts
  app/common/src/text/english.json
  app/gui/.env.bazel
  app/gui/src/config.ts
  app/gui/src/dashboard/data/serviceCredentials/StravaCredentialsForm.tsx
  app/gui/src/dashboard/data/serviceCredentials/constants.ts
  app/gui/src/dashboard/data/serviceCredentials/strava.ts
  app/ide-desktop/client/src/security.ts
  build.sbt
  build_tools/build/src/ci_gen.rs
  build_tools/build/src/ci_gen/job.rs
  build_tools/build/src/ide/web.rs
  distribution/lib/Standard/Saas/0.0.0-dev/THIRD-PARTY/NOTICE
  distribution/lib/Standard/Saas/0.0.0-dev/docs/api/Main.md
  distribution/lib/Standard/Saas/0.0.0-dev/docs/api/Strava.md
  distribution/lib/Standard/Saas/0.0.0-dev/manifest.yaml
  distribution/lib/Standard/Saas/0.0.0-dev/package.yaml
  distribution/lib/Standard/Saas/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Saas/0.0.0-dev/src/Strava.enso
  project/Editions.scala
  std-bits/base/src/main/java/org/enso/base/enso_cloud/ExternalLibraryCredentialHelper.java
  std-bits/saas/src/main/java/org/enso/saas/strava/StravaService.java
  tools/legal-review/Saas/report-state
Labels: CI: No changelog needed, CI: Clean build required, -libs-API-change-Saas

#13595 Add type support for google sheets
  distribution/lib/Standard/Google/0.0.0-dev/src/Google_Sheets_Workbook.enso
  std-bits/google/src/main/java/org/enso/google/GoogleSheetsForEnso.java
  std-bits/google/src/main/java/org/enso/google/GoogleSheetsHeaders.java
  test/Google_Test/src/Main.enso
Labels: CI: No changelog needed

#13596 Show info bar on crash
  app/gui/src/dashboard/components/Page.tsx
  app/gui/src/dashboard/layouts/Drive.tsx
  app/gui/src/dashboard/layouts/Editor.tsx
  app/gui/src/dashboard/layouts/Settings/Settings.tsx
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#13600 First step to try and improve the async calls inside Table viz
  app/gui/src/project-view/components/GraphEditor/GraphVisualization/visualizationData.ts
  app/gui/src/project-view/components/visualizations/TableVisualization.vue
  app/gui/src/project-view/components/visualizations/VisualizationHost.vue
  app/gui/src/project-view/providers/visualizationConfig.ts
  app/gui/src/project-view/stores/project/index.ts
Labels: CI: Ready to merge, CI: No changelog needed

#13597 Avoid changing directory when moving via drag
  app/gui/src/dashboard/hooks/cutAndPasteHooks.tsx
  app/gui/src/dashboard/hooks/dragDelayHooks.ts
  app/gui/src/dashboard/layouts/CategorySwitcher.tsx
  app/gui/src/dashboard/layouts/Drive/Categories/transferBetweenCategoriesHooks.tsx
  app/gui/src/dashboard/pages/dashboard/components/AssetRow.tsx
  app/gui/src/dashboard/services/ProjectManager/ProjectManager.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#13619 Fix preview visualization show/hide
  app/gui/src/project-view/components/ComponentBrowser.vue
  app/gui/src/project-view/components/GraphEditor/GraphNode.vue
  app/gui/src/project-view/components/GraphEditor/GraphNode/nodeVisualization.ts
  app/gui/src/project-view/components/GraphEditor/GraphVisualization.vue
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui

#13620 Fix Zod error
  app/gui/src/dashboard/pages/dashboard/UserBar/UserBar.tsx
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#13617 Right panel: Fix padding in fullscreen mode
  app/gui/src/components/AppContainer/RightPanel.vue
Labels: CI: No changelog needed

#13578 Fixing project rename
  app/gui/src/dashboard/hooks/projectHooks.ts
  app/gui/src/dashboard/layouts/Editor.tsx
  app/gui/src/project-view/ProjectView.vue
  app/gui/src/project-view/stores/project/index.ts
  app/gui/src/project-view/stores/projectNames.ts
  app/gui/src/project-view/util/__tests__/nameValidation.test.ts
  app/gui/src/project-view/util/nameValidation.ts
  app/gui/src/providers/openedProjects.ts
  app/ydoc-shared/src/util/data/result.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui

#13623 Move markdown link popup to floating layer
  app/gui/integration-test/project-view/editorPanels.spec.ts
  app/gui/integration-test/project-view/nodeComments.spec.ts
  app/gui/src/project-view/components/LinkEditPopup.vue
  app/gui/src/project-view/components/MarkdownEditor/MarkdownEditorImpl.vue
Labels: CI: Ready to merge, CI: No changelog needed

#13636 Fix scrolling in file browser widget
  app/gui/src/project-view/components/widgets/FileBrowserWidget/FileBrowserContent.vue
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui

#13563 Remove React Compiler
  app/gui/package.json
  app/gui/src/dashboard/components/Form/components/FormProvider.tsx
  app/gui/src/dashboard/components/Form/components/useForm.ts
  app/gui/src/dashboard/hooks/debugHooks.ts
  app/gui/src/dashboard/hooks/eventCallbackHooks.ts
  app/gui/src/dashboard/hooks/mountHooks.ts
  app/gui/src/dashboard/hooks/offlineHooks.ts
  app/gui/src/dashboard/hooks/storeHooks.ts
  app/gui/src/dashboard/hooks/syncRefHooks.ts
  app/gui/src/dashboard/hooks/timeoutHooks.ts
  app/gui/src/dashboard/hooks/useLazyMemoHooks.ts
  app/gui/src/dashboard/layouts/AssetsTableContextMenu.tsx
  app/gui/src/dashboard/layouts/useGlobalContextMenuEntries.tsx
  app/gui/vite.config.ts
  app/ide-desktop/client/package.json
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#13644 Delay optional checks until all required ones are known to be OK
  .github/workflows/engine-pull-request.yml
Labels: CI: No changelog needed, CI: Clean build required

#13650 Add read many support for google sheets
  distribution/lib/Standard/Google/0.0.0-dev/docs/api/Google_Sheets.md
  distribution/lib/Standard/Google/0.0.0-dev/docs/api/Google_Sheets_Workbook.md
  distribution/lib/Standard/Google/0.0.0-dev/src/Google_Sheets.enso
  distribution/lib/Standard/Google/0.0.0-dev/src/Google_Sheets_Workbook.enso
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Errors.md
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Workbook.enso
  test/Google_Test/src/Main.enso
Labels: CI: No changelog needed, -libs-API-change-Table, -libs-API-change-Google

#13651 Arguments not appearing on the outside component
  engine/language-server/src/test/scala/org/enso/languageserver/search/SuggestionsHandlerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/SuggestionsHandlerEventsTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeSuggestionUpdatesTest.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/SuggestionsRepo.scala
  lib/scala/searcher/src/main/scala/org/enso/searcher/memory/InMemorySuggestionsRepo.scala
  lib/scala/searcher/src/test/scala/org/enso/searcher/sql/SuggestionsRepoTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#13666 Catch table viz errors
  app/gui/src/project-view/components/visualizations/TableVisualization.vue
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui

#13672 Add new aliases and macros
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Postgres_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/SQLite_Connection.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/SQLServer_Connection.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Snowflake_Connection.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
Labels: CI: Ready to merge, CI: No changelog needed

#13661 Fix text cleanse defect mr
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Text_Cleanse_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#13653 Fix Subscribe view when offline
  app/gui/src/components/AppContainer.vue
  app/gui/src/dashboard/pages/subscribe/Subscribe.tsx
  app/gui/src/project-view/util/tanstack.ts
  app/gui/src/providers/auth.ts
  app/gui/src/providers/session.ts
  app/gui/src/router/initialProject.ts
Labels: CI: Ready to merge, CI: No changelog needed

#13656 Use custom to_json for Widgets
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Metadata.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Metadata.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Widgets.enso
  test/Visualization_Tests/src/Widgets/Database_Widgets_Spec.enso
  test/Visualization_Tests/src/Widgets/Table_Widgets_Spec.enso
  test/Visualization_Tests/src/Widgets/Text_Widgets_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required, -libs-API-change-Base

#13652 Fix removing argument default
  app/gui/integration-test/project-view/editorPanels.spec.ts
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetEnsoExpression.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetFunctionDef/ArgumentRow.vue
  app/gui/src/project-view/util/autoBlur.ts
Labels: CI: Ready to merge, CI: No changelog needed

#13676 Always send execution updates
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/instrument/RuntimeServerTesting.java
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/InstrumentTestContext.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeAsyncCommandsTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeInstrumentTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeRecomputeTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeRefactoringTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeSuggestionUpdatesTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#13680 Fix Table Visualisation Header Icons
  app/gui/src/project-view/components/SvgIcon.vue
  app/gui/src/project-view/components/visualizations/TableVisualization.vue
  app/ide-desktop/client/tests/localWorkflow.spec.ts
Labels: CI: No changelog needed

#13593 Open type check `Type&Any` lets all (visible) types thru
  CHANGELOG.md
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Upload/Operations/Delete.enso
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Table.md
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  docs/runtime/runtime-features.md
  docs/types/goals.md
  docs/types/hierarchy.md
  docs/types/inference-and-checking.md
  docs/types/intersection-types.md
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/TypeCheckAlgorithm.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/TypeFunctions.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/TypeNames.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/TypeSignatures.scala
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/node/typecheck/TypeCheckValueTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/SignatureTest.java
  engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java
  engine/runtime-parser/src/main/java/org/enso/compiler/core/ir/AscriptionReason.java
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Type.scala
  engine/runtime-parser/src/test/java/org/enso/compiler/core/IrPersistanceTest.java
  engine/runtime/src/main/java/org/enso/interpreter/node/typecheck/AllOfTypesCheckNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/typecheck/TypeCheckValueNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/IrTruffleUtils.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoMultiValue.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
  lib/java/persistance-dsl/src/main/java/org/enso/persist/impl/PersistableProcessor.java
  test/Base_Internal_Tests/src/Main.enso
  test/Base_Internal_Tests/src/Meta_Helpers_Spec.enso
  test/Base_Internal_Tests/src/Types/Any_Intersection.enso
  test/Base_Internal_Tests/src/Types/Any_Intersection_Conv.enso
  test/Base_Internal_Tests/src/Types/Any_Intersection_Spec.enso
  test/Table_Internal_Tests/src/Main.enso
  test/Table_Internal_Tests/src/Types/Table_Column_Any_Spec.enso
Labels: CI: Clean build required, -libs-API-change-Table

#13429 Extract python resource during build
  build.sbt
  engine/common/src/main/java/org/enso/common/ContextFactory.java
  engine/common/src/main/java/org/enso/common/PythonHomeFinder.java
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/runner/src/main/java/org/enso/runner/Main.java
  lib/java/python-extract/src/main/java/org/enso/pyextract/PythonExtract.java
  project/DistributionPackage.scala
  test/Base_Tests/data/native_libs.json
Labels: CI: No changelog needed, CI: Clean build required

#13677 Cleaning up std-benchmarks build
  build.sbt
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeAsyncCommandsTest.scala
  lib/java/jna-wrapper/src/main/java/com/sun/jna/Native.java
  project/Dependencies.scala
Labels: CI: Ready to merge, CI: No changelog needed

#13702 Revert Icon.tsx
  app/gui/src/dashboard/components/Icon/Icon.tsx
Labels: CI: Ready to merge, CI: No changelog needed

#13694 Set proper names of Welcome Project
  app/gui/integration-test/dashboard/welcomeProject.spec.ts
  app/gui/src/router/initialProject.ts
Labels: CI: Ready to merge, CI: No changelog needed

#13701 Keep right panel state per tab
  app/gui/integration-test/project-view/editorPanels.spec.ts
  app/gui/integration-test/project-view/graphNodeVisualization.spec.ts
  app/gui/integration-test/project-view/widgets.spec.ts
  app/gui/src/providers/container.ts
  app/gui/src/providers/rightPanel.ts
  app/ide-desktop/client/tests/localWorkflow.spec.ts
Labels: CI: Ready to merge, CI: No changelog needed

#13698 Fix errors when changing tabs
  app/gui/src/components/AppContainer/AppContainerInner.vue
  app/gui/src/components/ReactLayoutWrapper.vue
  app/gui/src/project-view/util/react.tsx
  app/gui/src/providers/react/container.tsx
  app/gui/src/providers/react/globalProvider.tsx
  eslint.config.mjs
Labels: CI: Ready to merge, CI: No changelog needed

#13697 Clean up the short suggestions for Input and Table Components
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_Secret.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Database.enso
  distribution/lib/Standard/Google/0.0.0-dev/src/Google_Analytics.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
Labels: CI: Ready to merge, CI: No changelog needed

#13708 Overhaul the Scatterplot Serialisation Code
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Row.md
  distribution/lib/Standard/Table/0.0.0-dev/src/Row.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/docs/api/Scatter_Plot.md
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Scatter_Plot.enso
  std-bits/table/src/main/java/org/enso/table/data/table/Row.java
  test/Visualization_Tests/src/Scatter_Plot_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, -libs-API-change-Table, -libs-API-change-Visualization
