Repository enso-org/enso, pull requests merged in 2025-04, with the labels that each got.

#12687 `newDef` and `newUse` directly register occurences into scope
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/alias/graph/GraphBuilder.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/context/LocalScope.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/graph/Graph.scala
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/pass/analyse/test/GraphBuilderTest.java
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/pass/analyse/test/AliasAnalysisTest.scala
Labels: CI: No changelog needed

#12666 Report correct type information for inlined types
  engine/runtime-compiler/src/main/scala/org/enso/compiler/data/BindingsMap.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/TypeSignatures.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/context/SuggestionBuilderTest.scala
  engine/runtime-suggestions/src/main/scala/org/enso/compiler/suggestions/SuggestionBuilder.scala
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#12472 Move Generic JDBC driver support to its own non-NI library
  .github/workflows/std-libs-labels.yml
  build.sbt
  build_tools/build/src/ci_gen.rs
  distribution/lib/Standard/Database/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Generic_JDBC/0.0.0-dev/THIRD-PARTY/NOTICE
  distribution/lib/Standard/Generic_JDBC/0.0.0-dev/package.yaml
  distribution/lib/Standard/Generic_JDBC/0.0.0-dev/src/Generic_JDBC_Connection.enso
  distribution/lib/Standard/Generic_JDBC/0.0.0-dev/src/Main.enso
  project/Editions.scala
  project/src/main/scala/licenses/frontend/SbtLicenses.scala
  std-bits/generic-jdbc/src/main/java/org/enso/database/jdbc/GenericJDBCConnectionDetailsImpl.java
  test/Generic_JDBC_Tests/src/Generic_JDBC_Connection_Spec.enso
  test/Generic_JDBC_Tests/src/H2_Spec.enso
  test/Table_Tests/src/Database/JDBC/Generic_JDBC_Postgres_Spec.enso
  test/Table_Tests/src/Database/JDBC/Generic_JDBC_SQLite_Spec.enso
  tools/legal-review/Generic_JDBC/report-state
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#12668 Support unsigned bytes in `Vector.write_bytes`, `Output_Stream.write_bytes`, and `Text.from_bytes`
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Data/Number_Utils.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Errors/Common.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Number_Utils.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File/Write_Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File_By_Line.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/Output_Stream.enso
  std-bits/base/src/main/java/org/enso/base/Array_Utils.java
  std-bits/base/src/main/resources/META-INF/native-image/org/enso/base/reflect-config.json
  test/Base_Tests/src/Data/Text/Encoding_Spec.enso
  test/Base_Tests/src/System/File_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, -libs-API-change-Base

#12698 Limit max memory on MacOS Arm NI builds
  build.sbt
Labels: CI: No changelog needed

#12696 Splitting Graph API and GraphImpl
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/PassPersistance.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/alias/graph/GraphBuilder.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/alias/graph/GraphPersistance.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/context/LocalScope.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/graph/Graph.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/graph/GraphImpl.scala
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/pass/analyse/test/GraphBuilderTest.java
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/pass/analyse/alias/graph/test/AliasAnalysisTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/pass/analyse/alias/graph/test/FramePointerAnalysisTest.scala
Labels: CI: No changelog needed, CI: Clean build required

#12700 Update title when starting hybrid project
  app/gui/src/dashboard/hooks/projectHooks.ts
Labels: CI: Ready to merge, CI: No changelog needed

#12705 Bump enso4igv runner
  .github/workflows/enso4igv.yml
Labels: CI: No changelog needed

#12672 Fix grid not updating
  app/gui/src/project-view/components/shared/AgGridTableView.vue
  app/gui/src/project-view/components/visualizations/TableVisualization.vue
Labels: CI: Ready to merge, CI: No changelog needed

#12724 Further bump max memory on mac build
  build.sbt
Labels: CI: Ready to merge, CI: No changelog needed

#12645 Add Is_Nothing, Not_Nothing and Between filters to table viz
  app/gui/src/project-view/components/visualizations/TableVisualization.vue
  app/gui/src/project-view/components/visualizations/TableVisualization/TableVizDataSourceUtils.ts
  distribution/lib/Standard/Visualization/0.0.0-dev/docs/api/Table/Visualization.md
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
Labels: CI: Ready to merge, CI: No changelog needed, -libs-API-change-Visualization

#12727 Bump max memory once again
  build.sbt
Labels: CI: No changelog needed, CI: Clean build required

#12706 Fix telemetry arg mismatch
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Workbook.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#12702 Clone builder to prevent `EnsoSecretHelper` from leaking secrets
  std-bits/base/src/main/java/org/enso/base/enso_cloud/EnsoSecretHelper.java
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#12703 Bump vite from 6.2.3 to 6.2.4
  app/gui/package.json
  app/ide-desktop/client/package.json
  pnpm-lock.yaml
Labels: CI: Ready to merge, CI: No changelog needed, dependencies, -gui

#12722 Fix doc editor newlines
  app/ydoc-shared/src/ast/__tests__/documentation.test.ts
  app/ydoc-shared/src/ast/__tests__/ensoMarkdown.test.ts
  app/ydoc-shared/src/ast/documentation.ts
Labels: CI: No changelog needed

#12720 60% speedup of `AliasAnalysis` with many local variables
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/FrameAnalysisMeta.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/FrameVariableNames.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/alias/AliasMetadata.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/alias/graph/GraphBuilder.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/alias/graph/GraphOccurrence.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/alias/graph/GraphPersistance.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/context/LocalScope.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/AutomaticParallelism.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/FramePointerAnalysis.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/AliasMetadata.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/graph/Graph.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/graph/GraphImpl.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/pass/analyse/alias/graph/test/AliasAnalysisTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/pass/analyse/alias/graph/test/FramePointerAnalysisTest.scala
Labels: CI: No changelog needed

#12691 Set enso cloud directory
  app/common/src/services/Backend.ts
  app/gui/src/dashboard/hooks/projectHooks.ts
  app/gui/src/dashboard/providers/ProjectsProvider.tsx
  app/gui/src/dashboard/services/LocalBackend.ts
  app/gui/src/dashboard/services/ProjectManager.ts
  docs/language-server/protocol-project-manager.md
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/ProjectManager.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/configuration.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/ExecutorWithUnlimitedPool.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerController.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerDescriptor.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerGateway.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerGatewayImpl.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerProtocol.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerRegistry.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/protocol/ProjectManagementApi.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/ProjectOpenHandler.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectService.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectServiceApi.scala
  lib/scala/project-manager/src/test/scala/org/enso/projectmanager/BaseServerSpec.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/runner/Runner.scala
Labels: CI: Ready to merge, CI: No changelog needed

#12732 Sync hybrid projects using multipart upload
  app/gui/project-manager-shim-middleware/index.ts
  app/gui/src/dashboard/hooks/projectHooks.ts
  app/gui/src/dashboard/providers/ProjectsProvider.tsx
  app/gui/src/dashboard/services/RemoteBackend.ts
  app/gui/src/dashboard/services/remoteBackendPaths.ts
  app/ide-desktop/client/src/server.ts
Labels: CI: Ready to merge, CI: No changelog needed, g-electron, -gui, l-cloud-integration

#12731 Add signature editor to docs panel for local functions.
  app/gui/src/project-view/components/DocumentationPanel.vue
  app/gui/src/project-view/stores/suggestionDatabase/entry.ts
Labels: CI: Ready to merge, CI: No changelog needed

#12735 Hide temporary directories of projects running in Hybrid mode
  app/gui/project-manager-shim-middleware/index.ts
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/command/filesystem/FileSystemListCommand.scala
Labels: CI: Ready to merge, CI: No changelog needed, -language-server, -gui, l-cloud-integration

#12746 Add credential icons
  app/gui/src/project-view/assets/icons.svg
Labels: CI: No changelog needed

#12626 Update / unify signatures for `{Table,Column,Vector.}.zip`
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Constants.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Data/Array.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Data/Vector.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Errors/Common.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Array_Like_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Database/0.0.0-dev/docs/api/DB_Column.md
  distribution/lib/Standard/Database/0.0.0-dev/docs/api/DB_Table.md
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Column.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Constants.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Internal/Widget_Helpers.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Row.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Table.md
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Constants.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Generate_Rows_Range.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Match_Columns_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Row.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  test/Base_Tests/src/Data/Vector_Spec.enso
  test/Benchmarks/src/Main.enso
  test/Benchmarks/src/Vector/Zip_Benchmark.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Zip_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Map_Spec.enso
  test/Table_Tests/src/In_Memory/Single_Column_Table_Spec.enso
  test/Table_Tests/src/In_Memory/Single_Value_Column_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
  test/Table_Tests/src/Util.enso
Labels: --breaking, CI: Ready to merge, -libs-API-change-Base, -libs-API-change-Database, -libs-API-change-Table

#12701 Document generic JDBC drivers
  distribution/lib/Standard/Generic_JDBC/0.0.0-dev/src/Generic_JDBC_Connection.enso
  docs/libraries/README.md
  docs/libraries/generic-jdbc-driver.md
  docs/libraries/images/connect_node.png
Labels: CI: Ready to merge, CI: No changelog needed

#12089 Improve perf of tabs switching. Improve rendering performance of the Assets table by 7 times
  app/gui/integration-test/dashboard/actions/api.ts
  app/gui/integration-test/dashboard/editAssetName.spec.ts
  app/gui/src/dashboard/components/Activity.tsx
  app/gui/src/dashboard/components/EditableSpan.tsx
  app/gui/src/dashboard/components/SvgMask.tsx
  app/gui/src/dashboard/components/aria.tsx
  app/gui/src/dashboard/components/dashboard/AssetRow.tsx
  app/gui/src/dashboard/components/dashboard/DatalinkNameColumn.tsx
  app/gui/src/dashboard/components/dashboard/DirectoryNameColumn.tsx
  app/gui/src/dashboard/components/dashboard/FileNameColumn.tsx
  app/gui/src/dashboard/components/dashboard/ProjectIcon.tsx
  app/gui/src/dashboard/components/dashboard/ProjectNameColumn.tsx
  app/gui/src/dashboard/components/dashboard/SecretNameColumn.tsx
  app/gui/src/dashboard/components/dashboard/column.ts
  app/gui/src/dashboard/components/dashboard/column/columnUtils.ts
  app/gui/src/dashboard/components/styled/FocusArea.tsx
  app/gui/src/dashboard/hooks/backendHooks.ts
  app/gui/src/dashboard/hooks/cutAndPasteHooks.ts
  app/gui/src/dashboard/hooks/measureHooks.ts
  app/gui/src/dashboard/hooks/projectHooks.ts
  app/gui/src/dashboard/layouts/AssetContextMenu.tsx
  app/gui/src/dashboard/layouts/AssetPanel/components/AssetPanelTabs.tsx
  app/gui/src/dashboard/layouts/AssetsTable.tsx
  app/gui/src/dashboard/layouts/Drive.tsx
  app/gui/src/dashboard/layouts/Drive/Categories/Category.ts
  app/gui/src/dashboard/layouts/Drive/assetsTableItemsHooks.ts
  app/gui/src/dashboard/layouts/TabBar.tsx
  app/gui/src/dashboard/modals/AgreementsModal.tsx
  app/gui/src/dashboard/pages/dashboard/Dashboard.tsx
  app/gui/src/dashboard/pages/dashboard/DashboardTabPanels.tsx
  app/gui/src/dashboard/pages/dashboard/Drive/DriveBar/DriveBarNavigation.tsx
  app/gui/src/dashboard/pages/dashboard/Drive/DriveBar/DriveBarToolbar.tsx
  app/gui/src/dashboard/utilities/functions.ts
  app/gui/src/dashboard/utilities/tanstackQuery.ts
  pnpm-lock.yaml
Labels: CI: Ready to merge, CI: No changelog needed, --low-performance, g-dashboard

#12744 Fix doc editor toolbar layering
  app/gui/src/project-view/components/MarkdownEditor/MarkdownEditorImpl.vue
Labels: CI: Ready to merge, CI: No changelog needed

#12676 Persist drive location across restarts
  MODULE.bazel.lock
  app/gui/src/dashboard/components/Devtools/EnsoDevtoolsProvider.tsx
  app/gui/src/dashboard/hooks/backendHooks.ts
  app/gui/src/dashboard/layouts/AssetsTable.tsx
  app/gui/src/dashboard/layouts/Drive/Categories/Category.ts
  app/gui/src/dashboard/layouts/Drive/Categories/categoriesHooks.tsx
  app/gui/src/dashboard/layouts/Drive/directoryIdsHooks.ts
  app/gui/src/dashboard/providers/DriveProvider.tsx
  app/gui/src/dashboard/providers/FeatureFlagsProvider.tsx
  app/gui/src/dashboard/utilities/permissions.ts
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#12754 Hide temporary directories of projects running in Hybrid mode
  app/gui/src/dashboard/layouts/Drive/assetsTableItemsHooks.ts
Labels: CI: Ready to merge, CI: No changelog needed

#12752 Revert hiding temporary directories of projects running in Hybrid mode
  app/gui/project-manager-shim-middleware/index.ts
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/command/filesystem/FileSystemListCommand.scala
Labels: CI: Ready to merge, CI: No changelog needed

#12747 Drag and drop to nested directory
  app/gui/src/dashboard/components/Breadcrumbs/BreadcrumbItem.tsx
  app/gui/src/dashboard/components/aria/TabPanel.tsx
  app/gui/src/dashboard/components/aria/aria.ts
  app/gui/src/dashboard/components/aria/index.ts
  app/gui/src/dashboard/components/dashboard/AssetRow.tsx
  app/gui/src/dashboard/hooks/dragDelayHooks.ts
  app/gui/src/dashboard/layouts/AssetsTable.tsx
  app/gui/src/dashboard/layouts/CategorySwitcher.tsx
  app/gui/src/dashboard/pages/dashboard/Drive/DriveBar/DriveBarNavigation.tsx
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#12756 Use project title from the backend in the TabBar
  app/gui/src/dashboard/layouts/TabBar.tsx
  app/gui/src/dashboard/pages/dashboard/DashboardTabBar.tsx
Labels: CI: No changelog needed, g-dashboard

#12757 Rename `run` -> `open` where appropriate
  app/common/src/text/english.json
Labels: CI: No changelog needed, g-dashboard

#12755 Pass full asset to openHybridProject
  app/gui/src/dashboard/layouts/AssetsTable.tsx
Labels: CI: No changelog needed

#12759 Quick fix for component code edits
  app/gui/src/project-view/components/ComponentBrowser/ComponentEditor.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetFunctionName.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetText.vue
  app/gui/src/project-view/components/NavBreadcrumb.vue
  app/gui/src/project-view/util/codemirror/index.ts
  app/ydoc-shared/src/util/data/range.ts
Labels: CI: Ready to merge, CI: No changelog needed

#12765 Fix Columns in Table Viz
  app/gui/src/project-view/components/visualizations/TableVisualization.vue
  distribution/lib/Standard/Visualization/0.0.0-dev/docs/api/Table/Visualization.md
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
Labels: CI: Ready to merge, CI: No changelog needed, -libs-API-change-Visualization

#12779 Fix suspense appearing on project opening
  app/gui/src/dashboard/layouts/TabBar.tsx
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#12699 Follow up on varargs logging arguments
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/RuntimeConnector.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
Labels: CI: Ready to merge, CI: No changelog needed

#12772 Another update to openxmlformats schemas
  std-bits/table/src/main/resources/META-INF/native-image/org/enso/table/reflect-config.json
Labels: CI: Ready to merge, CI: No changelog needed

#12780 Resources in truffle-api jar need to be signed
  app/ide-desktop/client/tasks/signArchivesMacOs.ts
Labels: CI: Ready to merge, CI: No changelog needed

#12769 Fix root ids for Cloud categories
  app/gui/src/dashboard/hooks/backendHooks.ts
  app/gui/src/dashboard/layouts/Drive/Categories/Category.ts
  app/gui/src/dashboard/layouts/Drive/Categories/categoriesHooks.tsx
  app/gui/src/dashboard/layouts/Drive/directoryIdsHooks.ts
  app/gui/src/dashboard/pages/dashboard/Drive/DriveBar/DriveBarToolbar.tsx
Labels: CI: Ready to merge, CI: No changelog needed, --bug, --regression, g-dashboard

#12723 Remove `ami` and `ide_version` from "update project" endpoint
  app/common/src/services/Backend.ts
  app/gui/src/dashboard/hooks/projectHooks.ts
  app/gui/src/dashboard/services/LocalBackend.ts
  app/gui/src/dashboard/services/RemoteBackend.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#12733 Relax deadlock watchdog rules for Native Image
  project/NativeImage.scala
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#12753 Refactor org.enso.projectmanager.boot.configuration
  lib/scala/project-manager/src/main/java/org/enso/projectmanager/infrastructure/migration/ProjectsMigration.java
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/configuration.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/configuration/BootloaderConfig.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/configuration/MainProcessConfig.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/configuration/MetadataStorageConfig.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/configuration/NetworkConfig.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/configuration/ProjectManagerConfig.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/configuration/ServerConfig.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/configuration/StorageConfig.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/configuration/SupervisionConfig.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/boot/configuration/TimeoutConfig.scala
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#12771 Generate per package Persistables class
  build.sbt
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/PassPersistance.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/alias/graph/GraphPersistance.java
  engine/runtime-compiler/src/test/java/org/enso/compiler/test/pass/PassPersistanceTest.java
  engine/runtime-parser/src/main/java/org/enso/compiler/core/ir/IrPersistance.java
  engine/runtime-parser/src/test/java/org/enso/compiler/core/IrPersistanceTest.java
  engine/runtime/src/main/java/org/enso/interpreter/caches/ImportExportCache.java
  engine/runtime/src/main/java/org/enso/interpreter/caches/SuggestionsCache.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/SerializationPool.java
  engine/runtime/src/test/java/org/enso/runtime/test/TypeMetadataPersistanceTest.java
  lib/java/persistance-dsl/src/main/java/org/enso/persist/impl/PersistableProcessor.java
  lib/java/persistance/src/main/java/module-info.java
  lib/java/persistance/src/main/java/org/enso/persist/PerMap.java
  lib/java/persistance/src/main/java/org/enso/persist/Persistance.java
  lib/java/persistance/src/test/java/org/enso/persist/PersistanceTest.java
  lib/java/persistance/src/test/java/org/enso/persist/ReferenceAsInlineTest.java
  lib/java/persistance/src/test/java/org/enso/persist/ReferenceAsObjectTest.java
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#12773 fix grid reloading issue
  app/gui/src/project-view/components/shared/AgGridTableView.vue
  app/gui/src/project-view/components/visualizations/TableVisualization.vue
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Table.md
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
  std-bits/table/src/main/java/org/enso/table/data/table/Table.java
  test/Visualization_Tests/src/Table_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, -libs-API-change-Table

#12740 Make one test less flaky
  app/gui/integration-test/project-view/fullscreenVisualisation.spec.ts
Labels: CI: Ready to merge, CI: No changelog needed, x-chore, -gui

#12748 Connect `Use` with `Def` via `GraphBuilder`
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/alias/graph/GraphBuilder.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/alias/graph/GraphOccurrence.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/alias/graph/GraphPersistance.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/graph/Graph.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/graph/GraphImpl.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/graph/ScopeImpl.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/lint/UnusedBindings.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/optimise/LambdaConsolidate.scala
  engine/runtime-instrument-repl-debugger/src/main/java/org/enso/interpreter/instrument/repl/debugger/ReplDebuggerInstrument.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/pass/analyse/test/GraphBuilderTest.java
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/pass/analyse/alias/graph/test/AliasAnalysisTest.scala
Labels: CI: No changelog needed

#12791 snwoflake-jdbc-thin forced update of signed archives
  app/ide-desktop/client/tasks/signArchivesMacOs.ts
Labels: CI: Ready to merge, CI: No changelog needed

#12362 Static analysis: resolve conversions and check argument types
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Aggregate_Column_Helper.enso
  docs/CONTRIBUTING.md
  engine/runner/src/main/java/org/enso/runner/Main.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/common/BuildScopeFromModuleAlgorithm.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/common/MethodResolutionAlgorithm.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/BuiltinTypes.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/MethodTypeResolver.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/TypeCompatibility.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/TypeInferencePropagation.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/TypePropagation.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/scope/StaticImportExportScope.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/scope/StaticMethodResolution.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/scope/StaticModuleScope.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/scope/StaticModuleScopeAnalysis.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/TypeInferenceTest.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
  test/Benchmarks/src/Compiler/Compile.enso
Labels: CI: Ready to merge, CI: No changelog needed

#12802 Add back root directory for Trash category
  app/gui/src/dashboard/hooks/backendBatchedHooks.ts
  app/gui/src/dashboard/layouts/AssetsTable.tsx
  app/gui/src/dashboard/layouts/Drive/Categories/Category.ts
  app/gui/src/dashboard/layouts/Drive/Categories/categoriesHooks.tsx
  app/gui/src/dashboard/layouts/Drive/directoryIdsHooks.ts
  app/gui/src/dashboard/pages/dashboard/Drive/DriveBar/DriveBarToolbar.tsx
Labels: p-high, CI: Ready to merge, CI: No changelog needed, --bug, --regression, g-dashboard

#12770 Fix dowloading projects from cloud
  app/gui/src/dashboard/layouts/AssetContextMenu.tsx
  app/ide-desktop/client/src/security.ts
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#12798 12% faster `ManyLocalVars` bench by using map in `resolveUsage`
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/FrameAnalysisMeta.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/alias/graph/GraphBuilder.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/alias/graph/GraphPersistance.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/context/LocalScope.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/graph/Graph.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/graph/GraphImpl.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/graph/ScopeImpl.scala
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/pass/analyse/test/GraphBuilderTest.java
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/pass/analyse/alias/graph/test/AliasAnalysisTest.scala
  lib/java/scala-libs-wrapper/src/main/java/org/enso/scala/wrapper/ScalaConversions.java
Labels: CI: No changelog needed, CI: Clean build required

#12811 Fix closing Full Screen visualization with `Esc` key.
  app/gui/integration-test/project-view/fullscreenVisualisation.spec.ts
  app/gui/src/project-view/components/GraphEditor/GraphVisualization.vue
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#12786 Handle empty text in URI.parse
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/URI.enso
  test/Base_Tests/src/Network/Http_Spec.enso
  test/Base_Tests/src/Network/URI_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#12814 Fix layout when editing existing node
  app/gui/src/project-view/components/ComponentBrowser.vue
  app/gui/src/project-view/components/GraphEditor/GraphNode.vue
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#12812 Fix opening new project
  app/common/src/services/Backend.ts
  app/gui/src/dashboard/hooks/backendHooks.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#12821 Enables Rename for all types in cloud
  app/gui/src/dashboard/components/dashboard/DatalinkNameColumn.tsx
  app/gui/src/dashboard/layouts/AssetContextMenu.tsx
Labels: CI: Ready to merge, CI: No changelog needed

#12804 Run enso exec directly rather than via shell
  .github/workflows/std-libs-labels.yml
  build.sbt
  build_tools/build/src/engine/context.rs
  build_tools/build/src/enso.rs
  docs/infrastructure/native-image.md
Labels: CI: Ready to merge, CI: No changelog needed

#12817 Fix Google API issues with Native Image
  distribution/lib/Standard/Google_Api/0.0.0-dev/docs/api/Google_Sheets.md
  distribution/lib/Standard/Google_Api/0.0.0-dev/src/Google_Sheets.enso
  std-bits/google-api/src/main/java/org/enso/google/GoogleSheetsForEnso.java
  std-bits/google-api/src/main/java/org/enso/google/GoogleSheetsHelpers.java
  std-bits/google-api/src/main/java/org/enso/google/WrappedGoogleCredentials.java
Labels: CI: Ready to merge, CI: No changelog needed, -libs-API-change-Google_Api

#12641 Use `Rounding_Mode` instead of `use_bankers` flag
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Data/Decimal.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Data/Numbers.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Data/Numeric/Rounding_Mode.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Decimal.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numeric/Math_Context.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numeric/Rounding_Mode.enso
  distribution/lib/Standard/Database/0.0.0-dev/docs/api/DB_Column.md
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Column.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Column_Operation.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Simple_Expression.md
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Column_Operation.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Simple_Expression.enso
  lib/scala/common-polyglot-core-utils/src/main/java/org/enso/polyglot/common_utils/Core_Math_Utils.java
  test/Base_Tests/src/Data/Decimal_Spec.enso
  test/Base_Tests/src/Data/Numbers_Spec.enso
  test/Base_Tests/src/Data/Round_Spec.enso
  test/Benchmarks/src/Column_Numeric.enso
  test/Benchmarks/src/Numeric.enso
  test/Snowflake_Tests/src/Snowflake_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Database/Common/IR_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Database/SQLite_Spec.enso
  test/Table_Tests/src/In_Memory/Column_Spec.enso
Labels: --breaking, CI: Ready to merge, CI: Clean build required, -libs-API-change-Base, -libs-API-change-Database, -libs-API-change-Table

#12831 Fix Cloud Browser scrollbars
  CHANGELOG.md
  app/gui/src/project-view/components/widgets/FileBrowserWidget.vue
Labels: CI: No changelog needed, -gui

#12528 Share `getThreadManager` pool among `RuntimeServerInstrument` and Websocket emulation
  MODULE.bazel.lock
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/InterpreterContext.java
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/Handler.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/InterpreterContext.scala
  engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbContext.java
  engine/runtime/src/main/java/org/enso/interpreter/EnsoLanguage.java
  engine/runtime/src/main/java/org/enso/interpreter/node/EnsoRootNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/GuestCodeExecutor.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/ThreadExecutors.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/ThreadManager.java
  lib/java/ydoc-polyfill/src/main/java/org/enso/ydoc/polyfill/web/WebSocket.java
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/runner/Runner.scala
  project/DistributionPackage.scala
Labels: CI: No changelog needed

#12835 Project-manager-shim creates directory when recovering project metadata
  app/gui/project-manager-shim-middleware/index.ts
Labels: CI: Ready to merge, CI: No changelog needed

#12822 Ensure correct BouncyCastle initialization for NI
  build.sbt
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/ReentrantLocking.scala
  project/NativeImage.scala
  std-bits/snowflake/src/main/java/org/enso/snowflake/BouncyCastleInitializer.java
  std-bits/snowflake/src/main/resources/META-INF/native-image/org/enso/snowflake/reflect-config.json
  std-bits/table/src/main/resources/META-INF/native-image/org/enso/table/reflect-config.json
  test/Snowflake_Tests/polyglot-sources/snowflake-test-java-helpers/src/main/java/org/enso/snowflake_helpers/TestKeyGenerator.java
Labels: CI: Ready to merge, CI: No changelog needed

#12836 Do not use `import all` in `Rounding_Mode`
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numeric/Rounding_Mode.enso
Labels: CI: Ready to merge, CI: No changelog needed

#12828 Properly hide temporary directories
  app/common/src/services/Backend.ts
  app/gui/src/dashboard/components/AriaComponents/Button/variants.ts
  app/gui/src/dashboard/components/dashboard/DatalinkNameColumn.tsx
  app/gui/src/dashboard/components/dashboard/DirectoryNameColumn.tsx
  app/gui/src/dashboard/components/dashboard/FileNameColumn.tsx
  app/gui/src/dashboard/components/dashboard/ProjectNameColumn.tsx
  app/gui/src/dashboard/components/dashboard/SecretNameColumn.tsx
  app/gui/src/dashboard/layouts/CategorySwitcher.tsx
  app/gui/src/dashboard/layouts/Drive/Categories/categoriesHooks.tsx
  app/gui/src/dashboard/layouts/Drive/assetsTableItemsHooks.ts
  app/gui/src/dashboard/services/ProjectManager.ts
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#12823 Update form on datalink save
  app/gui/src/dashboard/components/AriaComponents/Form/Form.tsx
  app/gui/src/dashboard/components/AriaComponents/Form/components/index.ts
  app/gui/src/dashboard/components/AriaComponents/Form/components/useForm.ts
  app/gui/src/dashboard/components/AriaComponents/Form/components/useFormState.tsx
  app/gui/src/dashboard/layouts/AssetPanel/components/AssetProperties.tsx
  app/gui/src/dashboard/layouts/Settings/FormEntry.tsx
  app/gui/src/dashboard/layouts/Settings/data.tsx
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#12840 Make login tests more stable
  app/gui/integration-test/dashboard/actions/ForgotPasswordPageActions.ts
  app/gui/integration-test/dashboard/actions/RegisterPageActions.ts
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#12848 Fix importing bundles containing single project_root directory
  app/ide-desktop/client/src/projectManagement.ts
Labels: CI: Ready to merge, CI: No changelog needed, g-electron, -gui

#12833 TelemetryAppender is not stopped on first encountered failure
  lib/java/logging-service-telemetry/src/main/java/org/enso/logging/service/telemetry/LogJobsProcessor.java
  lib/java/logging-service-telemetry/src/main/java/org/enso/logging/service/telemetry/TokenRefresher.java
  lib/java/logging-service-telemetry/src/test/java/org/enso/logging/service/telemetry/test/ConsumeLogs.java
  lib/java/logging-service-telemetry/src/test/java/org/enso/logging/service/telemetry/test/TestTelemetry.java
  lib/java/logging-service-telemetry/src/test/java/org/enso/logging/service/telemetry/test/TestTelemetryBrokenServer.java
  lib/java/logging-service-telemetry/src/test/java/org/enso/logging/service/telemetry/test/TestTokenRefresh.java
  lib/java/logging-service-telemetry/src/test/java/org/enso/logging/service/telemetry/test/Utils.java
Labels: CI: No changelog needed

#12854 Do not abort Base tests in offline mode
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Authentication.enso
  test/Base_Tests/src/Network/Enso_Cloud/Enso_Cloud_Spec.enso
  test/Base_Tests/src/Network/Enso_Cloud/Enso_File_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#12858 Check changed files when calculating outcome of CI job
  .github/workflows/engine-pull-request.yml
  .github/workflows/gui-pull-request.yml
  .github/workflows/ide-pull-request.yml
  .github/workflows/wasm-pull-request.yml
Labels: CI: Ready to merge, CI: No changelog needed, -ci

#12867 Fix slice defect in NullStorage
  std-bits/table/src/main/java/org/enso/table/data/column/storage/NullStorage.java
  test/Table_Tests/src/Common_Table_Operations/Take_Drop_Spec.enso
Labels: CI: No changelog needed

#12856 Another classic round of linting...
  distribution/lib/Standard/AWS/0.0.0-dev/src/AWS_Region.enso
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3.enso
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Data/Numbers.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Number_Utils.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_Secret.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Array_Like_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/Output_Stream.enso
  distribution/lib/Standard/Generic_JDBC/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Google_Api/0.0.0-dev/src/Google_Sheets.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Snowflake_Connection.enso
  test/Base_Tests/src/Data/Numbers_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, -libs-API-change-Base

#12873 Add repeat icon
  app/gui/src/project-view/assets/icons.svg
Labels: CI: Ready to merge, CI: No changelog needed

#12875 add schedule icon
  app/gui/src/project-view/assets/icons.svg
Labels: CI: Ready to merge, CI: No changelog needed

#12820 Text widget: Newline binding is Alt+Enter
  app/gui/integration-test/project-view/keyboard.ts
  app/gui/integration-test/project-view/widgets.spec.ts
  app/gui/src/project-view/bindings.ts
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetText.vue
  app/gui/src/project-view/util/codemirror/index.ts
  app/gui/src/project-view/util/codemirror/keymap.ts
Labels: CI: No changelog needed

#12879 Properly implement `ScopeImpl` serde
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/alias/graph/GraphBuilder.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/alias/graph/GraphOccurrence.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/alias/graph/GraphPersistance.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/graph/Graph.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/alias/graph/ScopeImpl.scala
  engine/runtime-compiler/src/test/java/org/enso/compiler/test/pass/PassPersistanceTest.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/DebugLocalScope.java
  lib/java/persistance-dsl/src/main/java/org/enso/persist/impl/PersistableProcessor.java
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#12898 Fix z-index of drop-down panels
  app/gui/src/project-view/components/DropdownMenu.vue
Labels: p-highest, CI: Ready to merge, CI: No changelog needed, --regression, -gui

#12881 VSCode verifies `rootFolder` exists before using it
  .github/workflows/enso4igv.yml
  tools/enso4igv/src/main/java/org/enso/tools/enso4igv/EnsoRootProject.java
  tools/enso4igv/src/main/java/org/enso/tools/enso4igv/EnsoSbtClassPathProvider.java
  tools/enso4igv/src/test/java/org/enso/tools/enso4igv/EnsoSbtProjectTest.java
Labels: CI: Ready to merge, CI: No changelog needed

#12338 Wip/farmaazon/chromatic in package tests
  .github/workflows/ide-packaging-optional.yml
  .github/workflows/ide-packaging.yml
  .gitignore
  app/gui/package.json
  app/ide-desktop/client/package.json
  app/ide-desktop/client/playwright.config.ts
  app/ide-desktop/client/tests/electronTest.ts
  app/ide-desktop/client/tests/localWorkflow.spec.ts
  app/ide-desktop/client/tests/setup.ts
  build_tools/build/src/ci_gen.rs
  build_tools/build/src/ci_gen/job.rs
  package.json
  patches/@chromatic-com__playwright.patch
  pnpm-lock.yaml
Labels: CI: Ready to merge, CI: No changelog needed

#12903 Make sure Source_Location can be converted to JSON
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Data/Json/Extensions.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Data/Range/Extensions.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Data/Statistics/Extensions.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Data/Text/Extensions.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Network/Extensions.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Runtime.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/System/File/Write_Extensions.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Runtime.enso
  distribution/lib/Standard/Database/0.0.0-dev/docs/api/Extensions/Upload_Database_Table.md
  distribution/lib/Standard/Database/0.0.0-dev/docs/api/Extensions/Upload_In_Memory_Table.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Extensions/Column_Vector_Extensions.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Extensions/Table_Conversions.md
  distribution/lib/Standard/Test/0.0.0-dev/docs/api/Extensions.md
  distribution/lib/Standard/Visualization/0.0.0-dev/docs/api/AI.md
  distribution/lib/Standard/Visualization/0.0.0-dev/docs/api/Helpers.md
  engine/runtime-compiler/src/main/java/org/enso/compiler/docs/DocsGenerate.java
  test/Base_Tests/src/Data/Json_Spec.enso
  test/Base_Tests/src/Runtime/Stack_Traces_Spec.enso
Labels: CI: No changelog needed, -libs-API-change-Base, -libs-API-change-Database, -libs-API-change-Table, -libs-API-change-Test, -libs-API-change-Visualization

#12910 Update lockfile, fixes merge conflict on develop
  pnpm-lock.yaml
Labels: CI: Ready to merge, CI: No changelog needed

#12907 Do not inherit types when resetting scopes
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeSuggestionUpdatesTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
Labels: CI: No changelog needed

#12878 Avoid re-packaging/re-compilation for stdlibs
  build.sbt
  project/AnalysisOfExtractedNativeLibs.scala
  project/ExtractedNativeLibSummary.scala
  project/JARUtils.scala
  project/StdBits.scala
Labels: CI: No changelog needed, CI: Clean build required

#12924 Add color-node-text-placeholder and selected
  app/gui/src/project-view/assets/base.css
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetText.vue
  app/gui/src/project-view/components/widgets/AutoSizedInput.vue
Labels: CI: No changelog needed

#12918 Module index invalidation triggers analysis
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/command/InvalidateModulesIndexCommand.java
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/EnsureCompiledJob.scala
Labels: CI: No changelog needed

#12855 Upgrade to GraalVM for JDK 24
  .github/workflows/enso4igv.yml
  .github/workflows/formatting.yml
  .jvmopts
  CHANGELOG.md
  build.sbt
  distribution/bin/enso
  distribution/bin/enso.bat
  distribution/lib/Standard/Test/0.0.0-dev/src/Test_Reporter.enso
  docs/infrastructure/native-image.md
  docs/runtime/compiler-ir.md
  engine/language-server/src/main/resources/META-INF/native-image/org/enso/languageserver/reachability-metadata.json
  engine/runner/src/main/java/org/enso/runner/Main.java
  engine/runtime-compiler-dump-igv/src/main/java/module-info.java
  engine/runtime-compiler-dump-igv/src/main/java/org/enso/compiler/dump/igv/ASTDumpStructure.java
  engine/runtime-compiler-dump-igv/src/main/java/org/enso/compiler/dump/igv/IGVDumper.java
  engine/runtime-compiler-dump-igv/src/main/java/org/enso/compiler/dump/igv/IGVDumperFactory.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/DiagnosticFormatterTest.java
  engine/runtime-language-arrow/src/main/java/org/enso/interpreter/arrow/runtime/ArrowFixedArrayInt.java
  engine/runtime-language-arrow/src/main/java/org/enso/interpreter/arrow/runtime/ArrowOperationPlus.java
  engine/runtime-language-arrow/src/main/java/org/enso/interpreter/arrow/runtime/ByteBufferDirect.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeCallableNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/BuiltinObject.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/UnresolvedConstructor.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/UnresolvedConversion.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/UnresolvedSymbol.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/Function.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoMultiValue.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/ManagedResource.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/AtomConstructor.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/ArrayOverBuffer.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/ArraySlice.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/DataflowError.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicException.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/TopLevelScope.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/warning/WithWarnings.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/util/DiagnosticFormatter.scala
  project/FrgaalJavaCompiler.scala
  test/Base_Tests/src/Network/Http_Spec.enso
  tools/enso4igv/pom.xml
  tools/enso4igv/src/main/java/org/enso/tools/enso4igv/GraalVMSourceForBinaryQuery.java
  tools/enso4igv/src/main/java/org/enso/tools/enso4igv/scala/ToggleScalaBreakpointActionProvider.java
  tools/http-test-helper/src/main/java/org/enso/shttp/HybridHTTPServer.java
Labels: CI: Clean build required

#12916 Compiler (without any Truffle) test
  engine/runtime-compiler/src/main/java/org/enso/compiler/context/CompilerContext.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/phase/ImportResolver.scala
  engine/runtime-compiler/src/test/java/org/enso/compiler/test/CompilerErrorTest.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java
Labels: CI: No changelog needed

#12913 Display component evaluation progress
  CHANGELOG.md
  app/common/src/utilities/data/math.ts
  app/gui/src/project-view/assets/base.css
  app/gui/src/project-view/components/BottomPanel.vue
  app/gui/src/project-view/components/GraphEditor.vue
  app/gui/src/project-view/components/GraphEditor/GraphEdge/layout.ts
  app/gui/src/project-view/components/GraphEditor/GraphNode.vue
  app/gui/src/project-view/components/GraphEditor/GraphNodeOutputPorts.vue
  app/gui/src/project-view/components/GraphEditor/GraphNodes.vue
  app/gui/src/project-view/components/GraphEditor/UploadingFile.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetFunctionName.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetPort.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection/tags.ts
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor/editHandler.ts
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetText.vue
  app/gui/src/project-view/components/widgets/CheckboxWidget.vue
  app/gui/src/project-view/components/widgets/FileBrowserWidget/paths.ts
  app/gui/src/project-view/components/widgets/NumericInputWidget.vue
  app/gui/src/project-view/composables/__tests__/progressBar.test.ts
  app/gui/src/project-view/composables/animation.ts
  app/gui/src/project-view/composables/navigator.ts
  app/gui/src/project-view/composables/progressBar.ts
  app/gui/src/project-view/providers/action.ts
  app/gui/src/project-view/providers/eventLogging.ts
  app/gui/src/project-view/providers/resizableWidgetRegistry.ts
  app/gui/src/project-view/stores/persisted.ts
  app/gui/src/project-view/stores/project/computedValueRegistry.ts
  app/gui/src/project-view/util/codemirror/index.ts
  app/gui/src/project-view/util/getIconName.ts
  app/ydoc-shared/src/util/data/range.ts
Labels: CI: Ready to merge

#12930 Make sure java.io.Console is included in NI for tests
  test/Base_Tests/src/Native_Image_Imports.enso
Labels: CI: No changelog needed

#12923 Upload/download files by drag and drop
  app/common/src/load.ts
  app/common/src/services/Backend.ts
  app/gui/env.d.ts
  app/gui/src/dashboard/App.tsx
  app/gui/src/dashboard/components/AriaComponents/AlertDialog/AlertDialog.tsx
  app/gui/src/dashboard/components/AriaComponents/AlertDialog/index.ts
  app/gui/src/dashboard/components/AriaComponents/IconDisplay/IconDisplay.tsx
  app/gui/src/dashboard/components/dashboard/AssetRow.tsx
  app/gui/src/dashboard/components/styled/Separator.tsx
  app/gui/src/dashboard/hooks/backendBatchedHooks.ts
  app/gui/src/dashboard/hooks/backendUploadFilesHooks.tsx
  app/gui/src/dashboard/hooks/gtagHooks.ts
  app/gui/src/dashboard/hooks/storeHooks.ts
  app/gui/src/dashboard/layouts/AssetContextMenu.tsx
  app/gui/src/dashboard/layouts/AssetsTable.tsx
  app/gui/src/dashboard/layouts/CategorySwitcher.tsx
  app/gui/src/dashboard/layouts/Drive.tsx
  app/gui/src/dashboard/layouts/Drive/Categories/Category.ts
  app/gui/src/dashboard/layouts/Drive/Categories/categoriesHooks.tsx
  app/gui/src/dashboard/layouts/Drive/Categories/transferBetweenCategoriesHooks.tsx
  app/gui/src/dashboard/layouts/GlobalContextMenu.tsx
  app/gui/src/dashboard/layouts/UserMenu.tsx
  app/gui/src/dashboard/layouts/VersionChecker.tsx
  app/gui/src/dashboard/pages/dashboard/Drive/DriveBar/DriveBarToolbar.tsx
  app/gui/src/dashboard/providers/AuthProvider.tsx
  app/gui/src/dashboard/providers/BackendProvider.tsx
  app/gui/src/dashboard/providers/HttpClientProvider.tsx
  app/gui/src/dashboard/services/LocalBackend.ts
  app/gui/src/dashboard/services/ProjectManager.ts
  app/gui/src/dashboard/services/RemoteBackend.ts
  app/gui/src/dashboard/utilities/appBaseUrl.ts
  app/gui/src/dashboard/utilities/download.ts
  app/gui/tsconfig.node.json
  app/ide-desktop/client/package.json
  app/ide-desktop/client/src/globals.d.ts
  app/ide-desktop/client/src/index.ts
  app/ide-desktop/client/src/preload.ts
  app/ide-desktop/client/src/projectManagement.ts
  pnpm-lock.yaml
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#12932 Rename trash2 icon to trash
  app/gui/src/dashboard/components/Devtools/EnsoDevtoolsImpl.tsx
  app/gui/src/project-view/assets/icons.svg
  app/gui/src/project-view/providers/action.ts
Labels: CI: No changelog needed

#12931 Add suggested components for URI
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/URI.enso
Labels: CI: No changelog needed

#12925 Add grid reset button and apply button to date filters
  app/gui/src/project-view/components/visualizations/TableVisualization.vue
  app/gui/src/project-view/components/visualizations/TableVisualization/tableVizToolbar.ts
Labels: CI: Ready to merge, CI: No changelog needed

#12938 Need to pass the parent ID in for subfolders.
  app/gui/src/dashboard/layouts/AssetPanel/components/AssetProperties.tsx
Labels: CI: Ready to merge, CI: No changelog needed

#12726 Support Reading Fixed Width Text Files
  CHANGELOG.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Delimited/Invalid_Fixed_Width_Rows.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Errors.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Fixed_Width/Fixed_Width_Format.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Internal/Fixed_Width_Reader.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Table.md
  distribution/lib/Standard/Table/0.0.0-dev/src/Delimited/Invalid_Fixed_Width_Rows.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Errors.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Fixed_Width/Fixed_Width_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Fixed_Width_Reader.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Java_Problems.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  std-bits/table/src/main/java/org/enso/table/parsing/problems/InconsistentFixedWidthLengths.java
  std-bits/table/src/main/java/org/enso/table/parsing/problems/InvalidFixedWidthRow.java
  std-bits/table/src/main/java/org/enso/table/read/FixedWidthFileFormatImpl.java
  std-bits/table/src/main/java/org/enso/table/read/FixedWidthReadFailedException.java
  std-bits/table/src/main/java/org/enso/table/read/FixedWidthReader.java
  std-bits/table/src/main/java/org/enso/table/read/FixedWidthReaderProblemAggregator.java
  std-bits/table/src/main/java/org/enso/table/read/InvalidFixedWidthRowsBehavior.java
  test/Table_Tests/data/fixed-width/fixed0.txt
  test/Table_Tests/data/fixed-width/fixed1.txt
  test/Table_Tests/data/fixed-width/fixed2.txt
  test/Table_Tests/data/fixed-width/fixed3.txt
  test/Table_Tests/src/IO/Fixed_Width_Read_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
Labels: CI: Ready to merge, -libs-API-change-Table

#12917 Improve error for missing table ordering
  distribution/lib/Standard/Database/0.0.0-dev/docs/api/Internal/Common/Ordering_Helpers.md
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Common/Ordering_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Fixed_Width/Internal/Column_Namer.md
  test/Table_Tests/src/Common_Table_Operations/Add_Row_Number_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Take_Drop_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, -libs-API-change-Database, -libs-API-change-Table

#12920 Wip/mk/show filtered row count
  app/gui/src/project-view/components/visualizations/TableVisualization.vue
  app/gui/src/project-view/components/visualizations/TableVisualization/TableVizStatusBar.ts
Labels: CI: Ready to merge, CI: No changelog needed

#12943 Update changelog after release
  CHANGELOG.md
Labels: CI: Ready to merge, CI: No changelog needed, x-chore

#12944 Prototype of MACRO support.
  app/gui/src/project-view/components/ComponentBrowser.vue
  app/gui/src/project-view/components/ComponentBrowser/component.ts
  app/gui/src/project-view/components/ComponentBrowser/filtering.ts
  app/gui/src/project-view/components/ComponentBrowser/input.ts
  app/gui/src/project-view/stores/suggestionDatabase/__tests__/lsUpdate.test.ts
  app/gui/src/project-view/stores/suggestionDatabase/documentation.ts
  app/gui/src/project-view/stores/suggestionDatabase/lsUpdate.ts
  app/gui/src/project-view/util/docParser.ts
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Database.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  lib/rust/parser/doc-parser/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#12934 Wip/mk/column state new node
  app/gui/src/project-view/components/shared/AgGridTableView.vue
  app/gui/src/project-view/components/visualizations/TableVisualization.vue
  app/gui/src/project-view/components/visualizations/TableVisualization/tableVizToolbar.ts
Labels: CI: Ready to merge, CI: No changelog needed

#12926 List correct logs when getting logs for a specific scheduler run
  app/common/src/text/english.json
  app/gui/src/dashboard/layouts/AssetPanel/components/ProjectExecution.tsx
  app/gui/src/dashboard/layouts/AssetPanel/components/ProjectExecutionsCalendar.tsx
  app/ide-desktop/client/src/server.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#12953 Cloud secrets browser
  CHANGELOG.md
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetSecretBrowser.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection/tags.ts
  app/gui/src/project-view/components/widgets/FileBrowserWidget.vue
  app/gui/src/project-view/providers/widgetRegistry/configuration.ts
  app/gui/src/project-view/util/ast/abstract.ts
  app/gui/src/project-view/util/methodPointer.ts
  distribution/lib/Standard/AWS/0.0.0-dev/src/AWS_Credential.enso
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Metadata.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_Secret.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Metadata.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Header.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/URI.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Credentials.enso
Labels: CI: Ready to merge, -libs-API-change-Base

#12956 Refactoring gone wrong
  distribution/lib/Standard/Google_Api/0.0.0-dev/src/Google_Credential.enso
Labels: CI: No changelog needed

#12950 Fixed-width `row_limit`
  CHANGELOG.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Fixed_Width/Fixed_Width_Format.md
  distribution/lib/Standard/Table/0.0.0-dev/src/Fixed_Width/Fixed_Width_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Fixed_Width_Reader.enso
  std-bits/table/src/main/java/org/enso/table/read/FixedWidthReader.java
  test/Table_Tests/data/fixed-width/fixed4.txt
  test/Table_Tests/src/IO/Fixed_Width_Read_Spec.enso
Labels: CI: Ready to merge, -libs-API-change-Table

#12936 Instrument function parameters
  distribution/manifest.template.yaml
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/instrument/IncrementalUpdatesTest.java
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
  engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/argument/ReadArgumentNode.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
Labels: CI: Ready to merge, CI: No changelog needed

#12751 Display type casting expressions on nodes
  CHANGELOG.md
  app/gui/src/project-view/components/ComponentBrowser/ComponentEditor.vue
  app/gui/src/project-view/components/ComponentBrowser/ComponentEditorLabel.vue
  app/gui/src/project-view/components/ComponentBrowser/__tests__/component.test.ts
  app/gui/src/project-view/components/ComponentBrowser/__tests__/filtering.test.ts
  app/gui/src/project-view/components/ComponentBrowser/__tests__/input.test.ts
  app/gui/src/project-view/components/ComponentBrowser/component.ts
  app/gui/src/project-view/components/ComponentBrowser/filtering.ts
  app/gui/src/project-view/components/ComponentBrowser/input.ts
  app/gui/src/project-view/components/FunctionSignatureEditor.vue
  app/gui/src/project-view/components/GraphEditor/ComponentWidgetTree.vue
  app/gui/src/project-view/components/GraphEditor/GraphNode.vue
  app/gui/src/project-view/components/GraphEditor/WidgetTreeRoot.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetArgumentName.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetIcon.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetPort.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelfAccessChain.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetTypeCast.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetTypeCastPort.vue
  app/gui/src/project-view/providers/widgetRegistry.ts
  app/gui/src/project-view/providers/widgetTree.ts
  app/gui/src/project-view/stores/graph/__tests__/graphDatabase.test.ts
  app/gui/src/project-view/stores/graph/graphDatabase.ts
  app/gui/src/project-view/stores/graph/index.ts
  app/gui/src/project-view/stores/project/computedValueRegistry.ts
  app/gui/src/project-view/stores/suggestionDatabase/entry.ts
  app/gui/src/project-view/util/ast/__tests__/aliasAnalysis.test.ts
  app/gui/src/project-view/util/ast/__tests__/node.test.ts
  app/gui/src/project-view/util/ast/node.ts
  app/rust-ffi/src/lib.rs
  app/ydoc-shared/src/ast/parse.ts
  app/ydoc-shared/src/ast/tree.ts
  app/ydoc-shared/src/languageServerTypes.ts
Labels: CI: Ready to merge, -gui

#12964 Show yielded errors in API signatures
  distribution/lib/Standard/AWS/0.0.0-dev/docs/api/Internal/S3_Path.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Data/Base_64.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Data/Decimal.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Data/Numbers.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Data/Ordering.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Data/Text/Encoding.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Data/Text/Extensions.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Data/Vector.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Enso_Cloud/Data_Link.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Enso_Cloud/Data_Link_Helpers.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Enso_Cloud/Enso_File.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Enso_Cloud/Enso_Secret.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Internal/Path_Helpers.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Meta.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/System/File.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Meta.enso
  distribution/lib/Standard/Database/0.0.0-dev/docs/api/DB_Column.md
  distribution/lib/Standard/Database/0.0.0-dev/docs/api/DB_Table.md
  distribution/lib/Standard/Database/0.0.0-dev/docs/api/Internal/Data_Link_Setup.md
  distribution/lib/Standard/Database/0.0.0-dev/docs/api/SQL_Statement.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Column.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Table.md
  engine/runtime-compiler/src/main/java/org/enso/compiler/docs/DocsUtils.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/dump/test/DocsGenerateTest.java
  test/Examples_Tests/data/signatures/Meta.md
  test/Examples_Tests/src/Main.enso
  test/Examples_Tests/src/Signatures_Spec.enso
Labels: CI: No changelog needed, -libs-API-change-Base

#12900 Add hyper write support
  CHANGELOG.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Internal/Java_Table_Access.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Table.md
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  distribution/lib/Standard/Tableau/0.0.0-dev/docs/api/Hyper_Errors.md
  distribution/lib/Standard/Tableau/0.0.0-dev/docs/api/Tableau_Format.md
  distribution/lib/Standard/Tableau/0.0.0-dev/src/Hyper_Errors.enso
  distribution/lib/Standard/Tableau/0.0.0-dev/src/Hyper_File.enso
  distribution/lib/Standard/Tableau/0.0.0-dev/src/Hyper_Table.enso
  distribution/lib/Standard/Tableau/0.0.0-dev/src/Tableau_Format.enso
  std-bits/tableau/src/main/java/org/enso/tableau/HyperFormat.java
  std-bits/tableau/src/main/java/org/enso/tableau/HyperUnsupportedTypeError.java
  test/Tableau_Tests/data/all_data_types.csv
  test/Tableau_Tests/data/transient/.gitkeep
  test/Tableau_Tests/src/Main.enso
  test/Tableau_Tests/src/Write_Spec.enso
Labels: -libs-API-change-Table, -libs-API-change-Tableau

#12947 Grid resize on load bug
  app/gui/src/project-view/components/shared/AgGridTableView.vue
  app/gui/src/project-view/components/visualizations/TableVisualization.vue
Labels: CI: Ready to merge, CI: No changelog needed

#12402 Introduce `Numeric_Column` type refinement
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Type_Mapping.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Statement_Setter.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Type_Refinements/DB_Column_Refinements.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Type_Refinements/DB_Table_Refinements.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Type_Refinements/Single_Column_DB_Table_Conversions.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Type_Refinements/Single_Column_Typed_DB_Table_Conversions.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Type_Refinements/Typed_DB_Column_Conversions.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/Internal/SQLServer_Dialect.enso
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Internal/Type_Refinements/Typed_Column_Helpers.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Refined_Types/Numeric_Column.md
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Type_Refinements/Column_Refinements.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Type_Refinements/Single_Column_Table_Conversions.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Type_Refinements/Single_Column_Typed_Table_Conversions.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Type_Refinements/Single_Value_Column_Conversions.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Type_Refinements/Table_Refinements.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Type_Refinements/Typed_Column_Conversions.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Type_Refinements/Typed_Column_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Value_Type_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Refined_Types/Numeric_Column.enso
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/decimal/CeilNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/decimal/FloorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/decimal/RoundNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/decimal/TruncateNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/utils/BigIntegerOps.java
  lib/scala/common-polyglot-core-utils/src/main/java/org/enso/polyglot/common_utils/Core_Math_Utils.java
  lib/scala/common-polyglot-core-utils/src/main/java/org/enso/polyglot/common_utils/Core_Text_Utils.java
  std-bits/table/src/main/java/org/enso/table/aggregations/Mean.java
  std-bits/table/src/main/java/org/enso/table/aggregations/Sum.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/AbsOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/NumericUnaryOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/SignumOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/UnaryRoundOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/ColumnDoubleStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/ColumnLongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/ColumnStorageWithInferredStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/MixedStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/MixedStorageFacade.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/PreciseTypeOptions.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/Storage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/StringStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/AbstractLongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/BigIntegerStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/DoubleStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/DoubleStorageFacade.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/LongStorageFacade.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/type/IntegerType.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/type/StorageType.java
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Conversion_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Filter_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Main.enso
  test/Table_Tests/src/Common_Table_Operations/Numeric_Column_Spec.enso
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso
Labels: CI: Ready to merge, CI: No changelog needed, -libs-API-change-Table

#12973 Making `ENSO_LAUNCHER=native,fast` fast
  build.sbt
  docs/infrastructure/native-image.md
Labels: CI: No changelog needed

#12795 Visual adjustments
  app/common/src/text/english.json
  app/gui/integration-test/dashboard/actions/DrivePageActions.ts
  app/gui/integration-test/dashboard/assetsTableFeatures.spec.ts
  app/gui/integration-test/dashboard/contextMenu.spec.ts
  app/gui/integration-test/dashboard/contextMenus.spec.ts
  app/gui/integration-test/dashboard/labels.spec.ts
  app/gui/integration-test/dashboard/labelsPanel.spec.ts
  app/gui/src/dashboard/components/AriaComponents/AlertDialog/AlertDialog.tsx
  app/gui/src/dashboard/components/AriaComponents/Button/ButtonGroup.tsx
  app/gui/src/dashboard/components/AriaComponents/Button/variants.ts
  app/gui/src/dashboard/components/AriaComponents/Dialog/Popover.tsx
  app/gui/src/dashboard/components/AriaComponents/IconDisplay/IconDisplay.tsx
  app/gui/src/dashboard/components/ContextMenu.tsx
  app/gui/src/dashboard/components/Devtools/EnsoDevtoolsImpl.tsx
  app/gui/src/dashboard/components/dashboard/AssetRow.tsx
  app/gui/src/dashboard/components/dashboard/AssetRow/assetRowUtils.tsx
  app/gui/src/dashboard/components/dashboard/column/LabelsColumn.tsx
  app/gui/src/dashboard/components/dashboard/column/columnUtils.ts
  app/gui/src/dashboard/hooks/backendBatchedHooks.ts
  app/gui/src/dashboard/hooks/contextMenuHooks.tsx
  app/gui/src/dashboard/layouts/AssetContextMenu.tsx
  app/gui/src/dashboard/layouts/AssetPanel/AssetPanel.tsx
  app/gui/src/dashboard/layouts/AssetsTable.tsx
  app/gui/src/dashboard/layouts/CategorySwitcher.tsx
  app/gui/src/dashboard/layouts/Drive.tsx
  app/gui/src/dashboard/layouts/Labels.tsx
  app/gui/src/dashboard/layouts/Settings/KeyboardShortcutsSettingsSection.tsx
  app/gui/src/dashboard/layouts/Settings/MembersSettingsSection.tsx
  app/gui/src/dashboard/layouts/Settings/data.tsx
  app/gui/src/dashboard/modals/ManageLabelsModal.tsx
  app/gui/src/dashboard/modals/NewLabelModal.tsx
  app/gui/src/dashboard/pages/dashboard/Drive/DriveBar/DriveBarToolbar.tsx
  app/gui/src/dashboard/providers/DriveProvider.tsx
  app/gui/src/dashboard/tailwind.css
  app/gui/tailwind.config.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#12958 Revert a small change that was in the Fixed Width PR.
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Fixed_Width/Fixed_Width_Format.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Table.md
  distribution/lib/Standard/Table/0.0.0-dev/src/Fixed_Width/Fixed_Width_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required, -libs-API-change-Table

#12899 Conflict resolution for uploading projects to cloud
  MODULE.bazel.lock
  app/common/src/text/english.json
  app/gui/src/dashboard/hooks/backendHooks.ts
  app/gui/src/dashboard/hooks/backendUploadFilesHooks.tsx
  app/gui/src/dashboard/hooks/projectHooks.ts
  app/gui/src/dashboard/layouts/AssetContextMenu.tsx
  app/gui/src/dashboard/layouts/AssetsTableContextMenu.tsx
  app/gui/src/dashboard/layouts/Drive/Categories/transferBetweenCategoriesHooks.tsx
  app/gui/src/dashboard/modals/DuplicateAssetsModal.tsx
  app/gui/src/dashboard/pages/dashboard/Drive/DriveBar/DriveBarToolbar.tsx
  app/gui/src/dashboard/services/LocalBackend.ts
  app/gui/src/dashboard/utilities/tanstackQuery.ts
Labels: CI: Ready to merge, CI: No changelog needed, x-new-feature, g-dashboard

#12969 Fix download/upload
  app/common/src/services/Backend.ts
  app/gui/env.d.ts
  app/gui/src/dashboard/hooks/backendBatchedHooks.ts
  app/gui/src/dashboard/hooks/backendUploadFilesHooks.tsx
  app/gui/src/dashboard/layouts/AssetContextMenu.tsx
  app/gui/src/dashboard/layouts/Drive.tsx
  app/gui/src/dashboard/layouts/Drive/Categories/transferBetweenCategoriesHooks.tsx
  app/gui/src/dashboard/layouts/UserMenu.tsx
  app/gui/src/dashboard/layouts/VersionChecker.tsx
  app/gui/src/dashboard/providers/AuthProvider.tsx
  app/gui/src/dashboard/services/LocalBackend.ts
  app/gui/src/dashboard/services/RemoteBackend.ts
  app/gui/src/dashboard/utilities/download.ts
  app/ide-desktop/client/src/globals.d.ts
  app/ide-desktop/client/src/index.ts
  app/ide-desktop/client/src/preload.ts
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#12989 Fix for Widgets on values with Warnings
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Widgets.enso
Labels: CI: Ready to merge, CI: No changelog needed

#12901 CI Lint check for Enso code
  .github/workflows/engine-checks.yml
  .gitignore
  build.sbt
  build_tools/build/src/ci_gen.rs
  build_tools/build/src/ci_gen/job.rs
  build_tools/build/src/engine.rs
  build_tools/build/src/engine/context.rs
  build_tools/build/src/libraries_tests.rs
  build_tools/ci_utils/src/program/command.rs
  build_tools/cli/src/arg/libraries.rs
  build_tools/cli/src/lib.rs
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Test_Reporter.enso
  engine/common/src/main/java/org/enso/common/ContextFactory.java
  engine/common/src/main/java/org/enso/common/RuntimeOptions.java
  engine/runner/src/main/java/org/enso/runner/Main.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/TypePropagation.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/data/CompilerConfig.scala
  engine/runtime-compiler/src/test/java/org/enso/compiler/test/CompilerErrorTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/ExecStrictCompilerTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/TypeInferenceTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/WarningsAsErrorsTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/mini/passes/MiniPassTester.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/DiagnosticFormatterTest.java
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/semantic/ImportsTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/semantic/OverloadsResolutionErrorTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/semantic/StrictCompileDiagnosticsTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/EnsoLanguage.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/util/DiagnosticKind.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/util/DiagnosticFormatter.scala
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/util/GitHubDiagnosticFormatter.scala
  project/DistributionPackage.scala
  project/EnsoLint.scala
  project/EnsoProjects.scala
  std-bits/benchmarks/src/main/java/org/enso/benchmarks/libs/LibBenchRunner.java
  test/Base_Tests/src/Runtime/Stack_Size_Spec.enso
  test/Base_Tests/src/Semantic/Import_Loop/B.enso
  test/Benchmarks/package.yaml
  test/Exploratory_Benchmarks/README.md
  test/Exploratory_Benchmarks/package.yaml
  test/Exploratory_Benchmarks/polyglot-sources/exploratory-benchmark-java-helpers/src/main/java/org/enso/exploratory_benchmark_helpers/LongNullHandling.java
  test/Exploratory_Benchmarks/polyglot-sources/exploratory-benchmark-java-helpers/src/main/java/org/enso/exploratory_benchmark_helpers/MapHelpers.java
  test/Exploratory_Benchmarks/polyglot-sources/exploratory-benchmark-java-helpers/src/main/java/org/enso/exploratory_benchmark_helpers/SimpleStorageAggregateHelpers.java
  test/Exploratory_Benchmarks/src/Main.enso
  test/Exploratory_Benchmarks/src/Table/Column_Aggregate.enso
  test/Exploratory_Benchmarks/src/Table/Column_Bi_Map.enso
  test/Exploratory_Benchmarks/src/Table/Column_Map.enso
  test/Exploratory_Benchmarks/src/Table/Column_Map_2.enso
  test/Exploratory_Benchmarks/src/Table/Common_Setup.enso
  test/Exploratory_Benchmarks/src/Table/Enso_Callback.enso
  test/Exploratory_Benchmarks/src/Table/Handling_Null_Return.enso
  test/Exploratory_Benchmarks/src/Table/Helpers.enso
  test/Exploratory_Benchmarks/src/Table/Main.enso
  test/Geo_Tests/package.yaml
  test/Table_Tests/src/Database/Common/Common_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#12963 Update access log to use new API
  app/common/src/services/Backend.ts
  app/common/src/text/english.json
  app/gui/src/dashboard/components/AriaComponents/Inputs/Dropdown/Dropdown.tsx
  app/gui/src/dashboard/components/JSONSchemaInput.tsx
  app/gui/src/dashboard/components/Scroller/Scroller.tsx
  app/gui/src/dashboard/components/UserWithPopover/UserWithPopover.tsx
  app/gui/src/dashboard/components/UserWithPopover/index.ts
  app/gui/src/dashboard/hooks/backendHooks.ts
  app/gui/src/dashboard/layouts/AssetPanel/components/AssetProperties.tsx
  app/gui/src/dashboard/layouts/AssetPanel/components/AssetVersion.tsx
  app/gui/src/dashboard/layouts/AssetSearchBar.tsx
  app/gui/src/dashboard/layouts/AssetsTable.tsx
  app/gui/src/dashboard/layouts/Settings/ActivityLogSettingsSection.tsx
  app/gui/src/dashboard/layouts/Settings/KeyboardShortcutsSettingsSection.tsx
  app/gui/src/dashboard/layouts/Settings/MembersTable.tsx
  app/gui/src/dashboard/layouts/Settings/OrganizationProfilePictureInput.tsx
  app/gui/src/dashboard/layouts/Settings/ProfilePictureInput.tsx
  app/gui/src/dashboard/layouts/Settings/UserGroupsSettingsSection.tsx
  app/gui/src/dashboard/layouts/Settings/data.tsx
  app/gui/src/dashboard/layouts/Settings/index.tsx
  app/gui/src/dashboard/layouts/Settings/lambdaKinds.ts
  app/gui/src/dashboard/modals/ManageLabelsModal.tsx
  app/gui/src/dashboard/modals/NewUserGroupModal.tsx
  app/gui/src/dashboard/providers/SessionProvider.tsx
  app/gui/src/dashboard/services/RemoteBackend.ts
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#12998 Need to resolve Enso file paths accounting for URL encoding.
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_Secret.enso
Labels: CI: Ready to merge, CI: No changelog needed, --bug

#12990 Support Numeric Column operations `Absolute` and `Signum` in Simple Expressions
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Refined_Types/Numeric_Column.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Simple_Expression.md
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Type_Refinements/Typed_Column_Conversions.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Refined_Types/Numeric_Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Simple_Expression.enso
  test/Table_Tests/src/Common_Table_Operations/Derived_Columns_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Numeric_Column_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, -libs-API-change-Table

#13003 Fix test failures on nightly Snowflake tests
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Dialect.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Derived_Columns_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#12993 Debugging native image launcher in VSCode
  .vscode/launch.json
  build.sbt
  distribution/engine/THIRD-PARTY/NOTICE
  distribution/engine/THIRD-PARTY/org.graalvm.tools.dap-tool-24.2.0/NOTICES
  distribution/engine/THIRD-PARTY/org.graalvm.tools.insight-heap-tool-24.2.0/NOTICES
  distribution/engine/THIRD-PARTY/org.graalvm.tools.insight-tool-24.2.0/NOTICES
  docs/debugger/README.md
  docs/debugger/native-debugging.md
  docs/debugger/runtime-debugging.md
  project/NativeImage.scala
  tools/legal-review/AWS/com.fasterxml.jackson.dataformat.jackson-dataformat-cbor-2.12.6/files-ignore
  tools/legal-review/engine/org.graalvm.tools.dap-tool-24.2.0/copyright-keep
  tools/legal-review/engine/org.graalvm.tools.insight-heap-tool-24.2.0/copyright-keep
  tools/legal-review/engine/org.graalvm.tools.insight-tool-24.2.0/copyright-keep
  tools/legal-review/engine/org.graalvm.tools.insight-tool-24.2.0/copyright-keep-context
  tools/legal-review/engine/report-state
Labels: CI: Ready to merge, CI: No changelog needed

#13001 Macro bugs from Libs Demo
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Array.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/List.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Range.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Vector.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Database.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
Labels: CI: Ready to merge, CI: No changelog needed
