Repository enso-org/enso, pull requests merged in 2025-02, with the labels that each got.

#12210 GitHub Artifacts API update
  .github/workflows/ide-packaging-optional.yml
  .github/workflows/ide-packaging.yml
  .github/workflows/wasm-changed-files.yml
  build_tools/build/examples/artifact.rs
  build_tools/build/src/ci_gen/job.rs
  build_tools/build/src/ci_gen/step.rs
  build_tools/build/src/engine/context.rs
  build_tools/build/src/engine/env.rs
  build_tools/build/src/paths.rs
  build_tools/build/src/project.rs
  build_tools/build/src/project/gui.rs
  build_tools/build/src/project/ide.rs
  build_tools/build/src/project/wasm/test.rs
  build_tools/build/src/source.rs
  build_tools/ci_utils/src/actions/artifacts.rs
  build_tools/ci_utils/src/actions/workflow/definition.rs
  build_tools/ci_utils/src/os/target.rs
  build_tools/cli/src/lib.rs
Labels: CI: No changelog needed

#12091 New icon component
  .github/workflows/gui-checks.yml
  .github/workflows/storybook.yml
  app/gui/env.d.ts
  app/gui/scripts/generateIconMetadata.mjs
  app/gui/src/dashboard/components/AriaComponents/Button/Button.stories.tsx
  app/gui/src/dashboard/components/AriaComponents/Button/Button.tsx
  app/gui/src/dashboard/components/AriaComponents/Button/CloseButton.tsx
  app/gui/src/dashboard/components/AriaComponents/Button/CopyButton.tsx
  app/gui/src/dashboard/components/AriaComponents/Button/types.ts
  app/gui/src/dashboard/components/AriaComponents/Dialog/Close.tsx
  app/gui/src/dashboard/components/AriaComponents/Dialog/Dialog.tsx
  app/gui/src/dashboard/components/AriaComponents/Dialog/DialogDismiss.tsx
  app/gui/src/dashboard/components/AriaComponents/Form/components/Reset.tsx
  app/gui/src/dashboard/components/AriaComponents/Form/components/Submit.tsx
  app/gui/src/dashboard/components/AriaComponents/Menu/MenuItem.tsx
  app/gui/src/dashboard/components/AriaComponents/types.ts
  app/gui/src/dashboard/components/Breadcrumbs/BreadcrumbItem.tsx
  app/gui/src/dashboard/components/Breadcrumbs/Breadcrumbs.stories.tsx
  app/gui/src/dashboard/components/Breadcrumbs/Breadcrumbs.tsx
  app/gui/src/dashboard/components/Icon/Icon.stories.tsx
  app/gui/src/dashboard/components/Icon/Icon.tsx
  app/gui/src/dashboard/components/Icon/index.ts
  app/gui/src/dashboard/components/Paywall/PaywallAlert.tsx
  app/gui/src/dashboard/components/Paywall/PaywallDialogButton.tsx
  app/gui/src/dashboard/components/Paywall/UpgradeButton.tsx
  app/gui/src/dashboard/components/Paywall/components/PaywallButton.tsx
  app/gui/src/dashboard/components/SvgIcon.tsx
  app/gui/src/dashboard/components/SvgMask.tsx
  app/gui/src/dashboard/components/styled/SidebarTabButton.tsx
  eslint.config.mjs
  package.json
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#12193 Add Snowflake to native-image
  build.sbt
  build_tools/build/src/engine/context.rs
  std-bits/snowflake/src/main/resources/META-INF/native-image/org/enso/snowflake/reflect-config.json
  std-bits/snowflake/src/main/resources/META-INF/native-image/org/enso/snowflake/resource-config.json
Labels: CI: Ready to merge, CI: No changelog needed

#12214 `Pair.to Meta.Type . qualified_name` fix
  distribution/lib/Standard/Base/0.0.0-dev/src/Meta.enso
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/interop/MetaObjectTest.java
  test/Base_Tests/src/Semantic/Meta_Spec.enso
Labels: CI: No changelog needed

#12133 Move output ports to edges level
  CHANGELOG.md
  app/gui/integration-test/project-view/actions.ts
  app/gui/integration-test/project-view/componentBrowser.spec.ts
  app/gui/integration-test/project-view/edgeInteractions.spec.ts
  app/gui/integration-test/project-view/graphNodeVisualization.spec.ts
  app/gui/integration-test/project-view/locate.ts
  app/gui/src/App.vue
  app/gui/src/project-view/components/GraphEditor.vue
  app/gui/src/project-view/components/GraphEditor/CreateNodeFromPortButton.vue
  app/gui/src/project-view/components/GraphEditor/GraphEdge.vue
  app/gui/src/project-view/components/GraphEditor/GraphEdges.vue
  app/gui/src/project-view/components/GraphEditor/GraphNode.vue
  app/gui/src/project-view/components/GraphEditor/GraphNodeMessage.vue
  app/gui/src/project-view/components/GraphEditor/GraphNodeOutputPorts.vue
  app/gui/src/project-view/components/GraphEditor/GraphNodes.vue
  app/gui/src/project-view/composables/keyboard.ts
  app/gui/src/project-view/composables/selection.ts
  app/gui/src/project-view/stores/graph/index.ts
  app/gui/src/project-view/util/autoBlur.ts
Labels: CI: Ready to merge, -gui

#12202 Add-image button in docs panel
  app/common/src/utilities/data/object.ts
  app/common/src/utilities/file.ts
  app/gui/src/dashboard/layouts/DriveBar.tsx
  app/gui/src/dashboard/layouts/GlobalContextMenu.tsx
  app/gui/src/project-view/components/DocumentationEditor.vue
  app/gui/src/project-view/components/DocumentationEditor/images.ts
  app/gui/src/project-view/util/ast/prefixes.ts
  app/gui/src/project-view/util/record.ts
Labels: CI: Ready to merge, CI: No changelog needed

#12179 Proper port position updates during animations
  app/gui/src/project-view/components/GraphEditor/GraphNode.vue
  app/gui/src/project-view/components/GraphEditor/UploadingFile.vue
  app/gui/src/project-view/components/GraphEditor/WidgetTreeRoot.vue
  app/gui/src/project-view/components/SizeTransition.vue
  app/gui/src/project-view/composables/animation.ts
  app/gui/src/project-view/providers/animationCounter.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#12190 Numbered and nested lists
  CHANGELOG.md
  app/gui/integration-test/project-view/rightPanel.spec.ts
  app/gui/src/project-view/components/CodeEditor/CodeEditorImpl.vue
  app/gui/src/project-view/components/CodeEditor/sync.ts
  app/gui/src/project-view/components/MarkdownEditor/MarkdownEditorImpl.vue
  app/gui/src/project-view/components/MarkdownEditor/__tests__/decorations.test.ts
  app/gui/src/project-view/components/MarkdownEditor/markdown/decoration/index.ts
  app/gui/src/project-view/components/MarkdownEditor/markdown/decoration/lists.ts
  app/gui/src/project-view/components/PlainTextEditor/PlainTextEditorImpl.vue
  app/gui/src/project-view/components/VueHostRender.vue
  app/gui/src/project-view/components/shared/AgGridTableView.vue
  app/gui/src/project-view/mock/engine.ts
  app/ydoc-shared/src/ast/__tests__/documentation.test.ts
  app/ydoc-shared/src/ast/__tests__/ensoMarkdown.test.ts
  app/ydoc-shared/src/ast/documentation.ts
Labels: CI: Ready to merge

#12221 Add IDE artifacts to the release workfow page
  .github/workflows/release.yml
  build_tools/build/src/ci_gen.rs
  build_tools/build/src/ci_gen/job.rs
Labels: CI: No changelog needed

#12222 Remove hash from default column name
  CHANGELOG.md
  app/gui/integration-test/project-view/tableVisualisation.spec.ts
  app/gui/integration-test/project-view/widgets.spec.ts
  app/gui/src/project-view/components/GraphEditor/__tests__/clipboardTestCases.json
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor/__tests__/tableInputArgument.test.ts
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor/__tests__/tableParsing.test.ts
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetTableEditor/tableInputArgument.ts
Labels: CI: Ready to merge, -gui

#12227 Data for bench website generation are gathered from 2024-10-01.
  tools/performance/engine-benchmarks/website_regen.py
Labels: CI: Ready to merge, CI: No changelog needed

#12197 Include Mac OS X aarch64 version of native lib of opencv
  project/StdBits.scala
Labels: CI: No changelog needed

#12226 Fix artifact upload in benchmark jobs
  .github/workflows/engine-benchmark.yml
  .github/workflows/std-libs-benchmark.yml
  build_tools/build/src/ci_gen.rs
  build_tools/build/src/engine/context.rs
  build_tools/ci_utils/src/actions/artifacts.rs
Labels: CI: No changelog needed, CI: Clean build required

#12165 Refine single-column Table to act as a Column
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Common/Lookup_Query_Helper.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Type_Refinements/DB_Table_Refinements.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Type_Refinements/Single_Column_DB_Table_Conversions.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Workbook.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Delimited_Reader.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Delimited_Writer.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Excel_Reader.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Read_Many_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Storage.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Type_Refinements/Column_Refinements.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Type_Refinements/Single_Column_Table_Conversions.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Type_Refinements/Single_Value_Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Type_Refinements/Single_Value_Column_Conversions.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Type_Refinements/Table_Refinements.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Value_Type_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
  test/Base_Tests/src/Semantic/Multi_Value_As_Type_Refinement_Spec.enso
  test/Table_Tests/src/Database/Common/Common_Spec.enso
  test/Table_Tests/src/Database/Common/Single_Column_Table_Spec.enso
  test/Table_Tests/src/IO/Csv_Spec.enso
  test/Table_Tests/src/In_Memory/Main.enso
  test/Table_Tests/src/In_Memory/Single_Column_Table_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Date_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Date_Time_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Time_Of_Day_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#12208 Cloud File Browser displays full tree in teams plan.
  CHANGELOG.md
  app/gui/src/project-view/assets/base.css
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetIcon.vue
  app/gui/src/project-view/components/widgets/FileBrowserWidget.vue
  app/gui/src/project-view/composables/backend.ts
Labels: CI: Ready to merge, -gui

#12234 Fix benchmark comparison in `bench_download.py` tool
  tools/performance/engine-benchmarks/README.md
  tools/performance/engine-benchmarks/bench_tool/__init__.py
  tools/performance/engine-benchmarks/bench_tool/test_bench_results.py
  tools/performance/engine-benchmarks/bench_tool/test_website_regen.py
Labels: CI: Ready to merge, CI: No changelog needed

#12205 Fix Table and Column test for nothing values
  test/Table_Tests/src/In_Memory/Table_Running_Spec.enso
  test/Table_Tests/src/Util.enso
  test/Table_Tests/src/Util_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#12191 Refactor offset tests
  test/Table_Tests/src/Common_Table_Operations/Offset_Spec.enso
  test/Table_Tests/src/Util.enso
  test/Table_Tests/src/Util_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#12231 Add extra columns when reading Delimited file
  CHANGELOG.md
  distribution/lib/Standard/Table/0.0.0-dev/src/Delimited/Delimited_Format.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Delimited/Invalid_Rows.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Delimited_Reader.enso
  std-bits/table/src/main/java/org/enso/table/data/table/Table.java
  std-bits/table/src/main/java/org/enso/table/read/DelimitedFileMetadata.java
  std-bits/table/src/main/java/org/enso/table/read/DelimitedReader.java
  test/Table_Tests/src/IO/Delimited_Read_Spec.enso
Labels: CI: Ready to merge

#12201 Use `BuiltinRootNode.ArgNode` to extract argument for a builtin method
  build.sbt
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/AtomBenchmarks.java
  engine/runtime-benchmarks/src/main/java/org/enso/interpreter/bench/benchmarks/semantic/StringBenchmarks.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/IfThenElseTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/instrument/DebugServerInspectTest.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/Any.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/Boolean.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/Builtin.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/BuiltinRootNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/Error.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/Nothing.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/Polyglot.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/UniquelyConstructibleBuiltin.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/debug/Debug.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/NumberParseError.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/Panic.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/ProblemBehavior.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/function/Function.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/immutable/SliceArrayVectorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/io/PrintlnNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsSimpleNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/Float.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/Integer.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/Number.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/Comparable.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/DefaultComparator.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/ordering/Ordering.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/runtime/Context.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/PrimTextHelper.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/Text.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/hash/EnsoHashMap.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/hash/HashMapInsertAllNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/vector/VectorFromFunctionNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/warning/AppendWarningNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/warning/Warning.java
  engine/runtime/src/test/java/org/enso/interpreter/runtime/data/hash/EnsoHashMapTest.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/BuiltinsProcessor.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/MethodProcessor.java
  test/Base_Tests/src/Semantic/Warnings_Spec.enso
Labels: CI: Ready to merge, CI: Keep up to date, CI: No changelog needed, CI: Clean build required

#12218 Fill in line numbers for IR.bgv files
  engine/runtime-compiler-dump-igv/src/main/java/org/enso/compiler/dump/igv/ASTLocation.java
  engine/runtime-compiler-dump-igv/src/main/java/org/enso/compiler/dump/igv/ASTNode.java
  engine/runtime-compiler-dump-igv/src/main/java/org/enso/compiler/dump/igv/EnsoModuleAST.java
  engine/runtime-compiler-dump-igv/src/main/java/org/enso/compiler/dump/igv/IGVDumper.java
  engine/runtime-compiler-dump/src/main/java/org/enso/compiler/dump/service/IRDumpSingleton.java
  engine/runtime-compiler-dump/src/main/java/org/enso/compiler/dump/service/IRDumper.java
  engine/runtime-compiler-dump/src/main/java/org/enso/compiler/dump/service/IRSource.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/context/CompilerContext.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/PassManager.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/TruffleCompilerContext.java
  lib/java/test-utils/src/main/java/org/enso/test/utils/IRDumperTestWrapper.java
Labels: CI: Ready to merge, CI: Keep up to date, CI: No changelog needed

#11717 Convert some global typing passes to mini passes
  engine/runtime-compiler-dump-igv/src/main/java/org/enso/compiler/dump/igv/EnsoModuleAST.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/lint/ShadowedPatternFields.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/optimise/UnreachableMatchBranches.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/Passes.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/lint/ShadowedPatternFields.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/optimise/UnreachableMatchBranches.scala
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/CompilerTests.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/WithIRDumper.java
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/MiniPassTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/PassesTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/desugar/NestedPatternMatchTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/lint/ShadowedPatternFieldsTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/optimise/UnreachableMatchBranchesTest.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Pattern.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/Case.scala
Labels: CI: No changelog needed, CI: Clean build required

#12248 Fix tests that falsely assumed table ordering in DB
  test/Table_Tests/src/Database/Common/Single_Column_Table_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#12245 Small fix to DB_Column visualization
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
Labels: CI: Ready to merge, CI: No changelog needed

#12204 Add Standard.Tableau to native-image
  build.sbt
  build_tools/build/src/engine/context.rs
  engine/common/src/main/java/org/enso/common/MethodNames.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/NativeLibraryFinderTest.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/TopLevelScope.java
  project/JARUtils.scala
  project/StdBits.scala
  std-bits/tableau/src/main/java/org/enso/tableau/HyperReader.java
  std-bits/tableau/src/main/resources/META-INF/native-image/org/enso/tableau/reflect-config.json
  std-bits/tableau/src/main/resources/META-INF/native-image/org/enso/tableau/resource-config.json
Labels: CI: No changelog needed, CI: Clean build required

#12223 New gate for stdlib API check
  .github/workflows/engine-changed-files.yml
  .github/workflows/engine-checks.yml
  .github/workflows/engine-pull-request.yml
  build_tools/build/src/ci_gen.rs
  build_tools/build/src/ci_gen/job.rs
  build_tools/build/src/engine.rs
  build_tools/build/src/engine/context.rs
  build_tools/ci_utils/src/fs.rs
  build_tools/ci_utils/src/programs/git.rs
  build_tools/cli/src/arg/backend.rs
  build_tools/cli/src/lib.rs
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Errors/Common.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Network/HTTP/HTTP_Method.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Widget_Helpers.md
Labels: CI: No changelog needed, CI: Clean build required, -libs-API-change

#12195 Expression update contains full multi-value info
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextEventsListener.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistryProtocol.scala
  engine/language-server/src/test/scala/org/enso/languageserver/runtime/ContextEventsListenerSpec.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/RuntimeCache.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/TypeInfo.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionCallbacks.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime-instrument-common/src/test/java/org/enso/interpreter/instrument/RuntimeCacheTest.java
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/TestMessages.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoMultiType.java
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#12246 Move Cast out of Storage, new common utils for cast and unary operation.
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Cast_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Extra_Imports.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Parse_Values_Helper.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  std-bits/table/src/main/java/org/enso/table/data/column/operation/StorageIterators.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/UnaryOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/CastOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/StorageConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/ToBigDecimalConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/ToBigIntegerConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/ToBooleanStorageConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/ToDateStorageConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/ToDateTimeStorageConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/ToFloatStorageConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/ToIntegerStorageConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/ToMixedStorageConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/ToTextStorageConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/ToTimeOfDayStorageConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/AbstractUnaryBooleanOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/AbstractUnaryLongOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/AbstractUnaryOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/DatePartOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/DateTruncateOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/DoubleIsOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/IsEmptyOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/IsFiniteOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/IsInfiniteOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/IsNaNOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/IsNothingOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/NotOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/TextLengthOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/TruncatedTimePartOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/unary/UnaryRoundOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/Storage.java
  test/Table_Tests/src/Common_Table_Operations/Conversion_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#12224 Bump openssl from 0.10.66 to 0.10.70
  Cargo.lock
Labels: CI: Ready to merge, CI: No changelog needed, dependencies

#12211 Replace more IR Scala case classes with Java interfaces
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/resolve/MethodDefinitions.java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/AutomaticParallelism.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/CachePreferenceAnalysis.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/DataflowAnalysis.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/DemandAnalysis.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/FramePointerAnalysis.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/desugar/ComplexType.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/desugar/GenerateMethodBodies.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/desugar/LambdaShorthandToLambdaMini.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/lint/NoSelfInStatic.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/lint/UnusedBindings.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/optimise/LambdaConsolidate.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/ExpressionAnnotations.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/FullyAppliedFunctionUses.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/FullyQualifiedNames.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/GlobalNames.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/IgnoredBindings.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/SuspendedArguments.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/TypeFunctions.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/TypeSignatures.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/refactoring/IRUtils.scala
  engine/runtime-instrument-common/src/test/scala/org/enso/compiler/test/context/ChangesetBuilderTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/pass/analyse/test/AliasAnalysisTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/CompilerTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/analyse/DataflowAnalysisTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/analyse/DemandAnalysisTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/analyse/GatherDiagnosticsTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/analyse/TailCallMegaPass.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/analyse/TailCallTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/desugar/LambdaShorthandToLambdaMegaPass.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/desugar/LambdaShorthandToLambdaTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/desugar/OperatorToFunctionTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/desugar/SectionsToBinOpMegaPass.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/desugar/SectionsToBinOpTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/optimise/LambdaConsolidateTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/resolve/ExpressionAnnotationsTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/resolve/GlobalNamesTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/pass/resolve/TypeSignaturesTest.scala
  engine/runtime-parser-processor-tests/src/main/java/org/enso/runtime/parser/processor/test/gen/ir/core/JCallArgument.java
  engine/runtime-parser-processor-tests/src/main/java/org/enso/runtime/parser/processor/test/gen/ir/core/JExpression.java
  engine/runtime-parser-processor-tests/src/test/java/org/enso/runtime/parser/processor/test/TestIRProcessorInline.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/GeneratedClassContext.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/IRNodeClassGenerator.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/methodgen/BuilderMethodGenerator.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/methodgen/SetLocationMethodGenerator.java
  engine/runtime-parser/src/main/java/org/enso/compiler/core/ir/DefinitionArgument.java
  engine/runtime-parser/src/main/java/org/enso/compiler/core/ir/Empty.java
  engine/runtime-parser/src/main/java/org/enso/compiler/core/ir/expression/Application.java
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/DefinitionArgument.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Literal.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/expression/Application.scala
  engine/runtime-suggestions/src/main/scala/org/enso/compiler/suggestions/SuggestionBuilder.scala
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
Labels: CI: No changelog needed, CI: Clean build required

#12158 Improvements in DX/Compiler/CI
  app/gui/src/dashboard/layouts/Editor.tsx
  app/gui/src/dashboard/pages/dashboard/DashboardTabPanels.tsx
  app/gui/vite.config.ts
  package.json
Labels: CI: Ready to merge, CI: No changelog needed

#12256 Include Standard.Google_Api in NI
  build.sbt
  project/StdBits.scala
  std-bits/google-api/src/main/resources/META-INF/native-image/org/enso/google/jni-config.json
  std-bits/google-api/src/main/resources/META-INF/native-image/org/enso/google/reflect-config.json
  std-bits/google-api/src/main/resources/META-INF/native-image/org/enso/google/resource-config.json
  std-bits/microsoft/src/main/resources/META-INF/native-image/org/enso/microsoft/resource-config.json
  test/Google_Api_Test/src/Main.enso
Labels: CI: No changelog needed

#12252 Enable ydoc-server tests
  build.sbt
  project/Ydoc.scala
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#12192 Dispatch of `to_text`, `is_a` & co. on intersection types
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/node/expression/builtin/number/decimal/FloatTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/node/expression/builtin/number/integer/IntegerTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/CaseOfTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/EnsoMultiValueTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/WrappedPrimitive.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeMethodNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/caseexpr/BooleanBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/decimal/AbsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/AbsNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/AddNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/BitAndNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/BitNotNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/BitOrNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/BitShiftNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/BitShiftRightNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/BitXorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/CeilNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/DivNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/DivideNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/FloorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/GreaterNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/GreaterOrEqualNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/IntegerNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/LessNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/LessOrEqualNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/ModNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/MultiplyNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/NegateNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/ParseIntegerNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/PowNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/RoundNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/SubtractNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/integer/ToFloatNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoMultiType.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoMultiValue.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/GetFieldNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/GetFieldWithMatchNode.java
  lib/scala/interpreter-dsl/src/main/java/module-info.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/impl/BuiltinsMetadataProcessor.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/impl/BuiltinsProcessor.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/impl/LayoutSpecProcessor.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/impl/MethodProcessor.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/impl/TypeProcessor.java
  test/Base_Tests/src/Semantic/Multi_Value_As_Type_Refinement_Spec.enso
Labels: CI: No changelog needed, CI: Clean build required

#12228 Filename input in Cloud File Browser for write component.
  CHANGELOG.md
  app/common/package.json
  app/gui/package.json
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetCloudBrowser.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui/src/project-view/components/widgets/FileBrowserWidget.vue
  app/gui/src/project-view/providers/interactionHandler.ts
  app/ydoc-server/package.json
  app/ydoc-shared/package.json
  package.json
  pnpm-lock.yaml
Labels: CI: Ready to merge, -gui

#12269 Add a few more Table benchmarks
  lib/java/benchmarks-common/src/main/java/org/enso/interpreter/bench/BenchmarkResultProcessor.java
  lib/java/benchmarks-common/src/main/java/org/enso/interpreter/bench/ReportItem.java
  test/Benchmarks/src/Main.enso
  test/Benchmarks/src/Table/Arithmetic.enso
  test/Benchmarks/src/Table/Cast.enso
  test/Benchmarks/src/Table/Unary_Column_Operations.enso
Labels: CI: Ready to merge, CI: No changelog needed

#12262 Add unit tests for expressions
  build.sbt
  std-bits/table/src/main/java/org/enso/table/expressions/ExpressionVisitorImpl.java
  std-bits/table/src/test/java/org/enso/table/expressions/ExpressionVisitorImplTest.java
Labels: CI: No changelog needed

#12270 Always run clean builds on `develop`
  .github/workflows/changelog.yml
  .github/workflows/engine-checks-nightly.yml
  .github/workflows/engine-checks-optional.yml
  .github/workflows/engine-checks.yml
  .github/workflows/extra-nightly-tests.yml
  .github/workflows/ide-packaging-optional.yml
  .github/workflows/ide-packaging.yml
  .github/workflows/promote.yml
  .github/workflows/release.yml
  .github/workflows/wasm-checks.yml
  build_tools/build/src/ci_gen.rs
Labels: CI: No changelog needed

#12073 Basic generic JDBC connection
  CHANGELOG.md
  build.sbt
  distribution/lib/Standard/Base/0.0.0-dev/src/Errors/Common.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/JDBC/Generic_JDBC_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Main.enso
  test/Generic_JDBC_Tests/README.md
  test/Generic_JDBC_Tests/package.yaml
  test/Generic_JDBC_Tests/src/Generic_JDBC_Connection_Spec.enso
  test/Generic_JDBC_Tests/src/Main.enso
Labels: CI: Ready to merge, CI: Clean build required

#12284 Move static expression methods to enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Expression_Statics.enso
  std-bits/table/src/main/java/org/enso/table/expressions/ExpressionVisitorImpl.java
  std-bits/table/src/test/java/org/enso/table/expressions/ExpressionVisitorImplTest.java
  test/Table_Tests/src/Common_Table_Operations/Expression_Spec.enso
Labels: CI: No changelog needed

#12287 Enable NI with IDE
  lib/scala/runtime-version-manager/src/main/resources/META-INF/native-image/org/enso/runtimeversionmanager/resource-config.json
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/runner/NativeExecCommand.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/runner/Runner.scala
Labels: CI: No changelog needed

#12275 Creating directory in File Browser
  CHANGELOG.md
  app/common/src/backendQuery.ts
  app/common/src/services/Backend.ts
  app/gui/src/dashboard/hooks/backendHooks.ts
  app/gui/src/dashboard/services/RemoteBackend.ts
  app/gui/src/dashboard/utilities/AssetTreeNode.ts
  app/gui/src/project-view/components/GraphEditor/GraphNodeMessage.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui/src/project-view/components/widgets/FileBrowserWidget.vue
  app/gui/src/project-view/components/widgets/FileBrowserWidget/FileBrowserEntry.vue
  app/gui/src/project-view/composables/backend.ts
Labels: CI: Ready to merge, -gui

#12253 Fix infinite recursion when calling `to_text` on an Atom with lazy field
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/DebuggingEnsoTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/LazyAtomFieldTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/interop/AtomInteropTest.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoMultiValue.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/BoxingAtom.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/StructsLibrary.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/SuspendedFieldGetterNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/UnboxingAtom.java
  test/Base_Tests/src/Runtime/Lazy_Spec.enso
Labels: CI: No changelog needed, CI: Clean build required

#12174 Fix excel cache test failure
  test/Table_Tests/src/IO/Excel_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#12274 Implement Iterators on Storage, arithmetic and comparisons use the StorageIterators
  std-bits/table/src/main/java/org/enso/table/data/column/builder/DoubleBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/builder/LongBuilder.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/StorageIterators.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/arithmetic/NumericBinaryOpCoalescing.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/arithmetic/NumericBinaryOpDefinition.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/arithmetic/NumericBinaryOpImplementation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/arithmetic/NumericBinaryOpReturningBigDecimal.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/arithmetic/NumericBinaryOpReturningDouble.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/comparisons/EqualsComparison.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/comparisons/NumericComparison.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/helpers/BigDecimalArrayAdapter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/helpers/BigIntegerArrayAdapter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/numeric/helpers/DoubleArrayAdapter.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/BoolStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/ColumnBooleanStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/ColumnBooleanStorageIterator.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/ColumnDoubleStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/ColumnDoubleStorageIterator.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/ColumnLongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/ColumnLongStorageIterator.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/ColumnStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/ColumnStorageFacade.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/ColumnStorageIterator.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/SpecializedStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/Storage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/AbstractLongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/BigIntegerStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/ComputedLongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/ComputedNullableLongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/DoubleStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/DoubleStorageFacade.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/LongConstantStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/LongRangeStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/LongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/LongStorageFacade.java
Labels: CI: Ready to merge, CI: No changelog needed

#12296 Enabling native launchers for the release
  build_tools/build/src/engine/context.rs
  project/GraalVM.scala
Labels: CI: No changelog needed

#12297 Expression support for arithmetic functions as numbers
  CHANGELOG.md
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Expression.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Expression_Statics.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  std-bits/table/src/main/java/org/enso/table/expressions/ExpressionVisitorImpl.java
  std-bits/table/src/test/java/org/enso/table/expressions/ExpressionVisitorImplTest.java
  test/Table_Tests/src/Common_Table_Operations/Expression_Spec.enso
Labels: CI: Ready to merge

#12321 Make submodule URL relative
  .gitmodules
Labels: CI: Ready to merge, CI: No changelog needed, -build-script

#12319 Log arguments passed to the 'main' function
  engine/runner/src/main/java/org/enso/runner/Main.java
Labels: CI: Ready to merge, CI: No changelog needed

#12229 Fix delete dialog appearing
  app/gui/src/dashboard/components/Devtools/EnsoDevtools.tsx
  app/gui/src/dashboard/components/Devtools/EnsoDevtoolsProvider.tsx
  app/gui/src/dashboard/components/Icon/Icon.tsx
  app/gui/src/dashboard/modals/UpsertSecretModal.tsx
  app/gui/src/dashboard/pages/dashboard/DashboardTabPanels.tsx
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#12283 Use checked signatures for Table and Column
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Decimal.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Numbers.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Date_Time_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#12324 Ability to run just a single benchmark on the CI
  .github/workflows/engine-benchmark.yml
  .github/workflows/std-libs-benchmark.yml
  build_tools/build/src/ci_gen.rs
  build_tools/build/src/engine.rs
  build_tools/build/src/engine/context.rs
  build_tools/cli/src/arg/backend.rs
  build_tools/cli/src/lib.rs
Labels: CI: No changelog needed

#12320 Regex support in Expressions
  CHANGELOG.md
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Expression_Statics.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Column_Naming_Helper.enso
  std-bits/table/src/main/antlr4/Expression.g4
  std-bits/table/src/main/java/org/enso/table/expressions/ExpressionVisitorImpl.java
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Expression_Spec.enso
Labels: CI: Ready to merge

#12325 Add flag for setting GUI mode
  build_tools/build/src/project/gui.rs
  build_tools/cli/src/arg/gui.rs
  build_tools/cli/src/lib.rs
Labels: CI: Ready to merge, CI: No changelog needed

#12318 Fix detection of bundled runtime with --jvm option
  engine/runner/src/main/java/org/enso/runner/JavaFinder.java
  lib/scala/distribution-manager/src/main/scala/org/enso/distribution/DistributionManager.scala
Labels: CI: No changelog needed

#12333 Enable escaping forwardslash in regex expressions
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Column_Naming_Helper.enso
  std-bits/table/src/main/antlr4/Expression.g4
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Expression_Spec.enso
Labels: CI: No changelog needed

#12323 Rename directories in Cloud File Browser.
  CHANGELOG.md
  app/gui/integration-test/project-view/locate.ts
  app/gui/src/App.vue
  app/gui/src/project-view/components/ActionButton.vue
  app/gui/src/project-view/components/ActionMenu.vue
  app/gui/src/project-view/components/ComponentButton.vue
  app/gui/src/project-view/components/ComponentContextMenu.vue
  app/gui/src/project-view/components/ComponentMenu.vue
  app/gui/src/project-view/components/ContextMenu.vue
  app/gui/src/project-view/components/ContextMenuTrigger.vue
  app/gui/src/project-view/components/GraphEditor.vue
  app/gui/src/project-view/components/GraphEditor/GraphNode.vue
  app/gui/src/project-view/components/GraphEditor/selectionActions.ts
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui/src/project-view/components/MenuButton.vue
  app/gui/src/project-view/components/MenuEntry.vue
  app/gui/src/project-view/components/PointFloatingMenu.vue
  app/gui/src/project-view/components/SelectionButton.vue
  app/gui/src/project-view/components/SelectionMenu.vue
  app/gui/src/project-view/components/WithFullscreenMode.vue
  app/gui/src/project-view/components/widgets/FileBrowserWidget.vue
  app/gui/src/project-view/components/widgets/FileBrowserWidget/FileBrowserEntry.vue
  app/gui/src/project-view/providers/action.ts
  app/gui/src/project-view/providers/componentButtons.ts
  app/gui/src/project-view/providers/graphEditorLayers.ts
  app/gui/src/project-view/providers/interactionHandler.ts
  app/gui/src/project-view/providers/selectionButtons.ts
  app/gui/src/project-view/util/button.ts
  app/ydoc-shared/src/util/types.ts
Labels: CI: Ready to merge, -gui

#12326 Different labels for stdlib API checks
  .github/workflows/engine-changed-files.yml
  .github/workflows/engine-pull-request.yml
  .github/workflows/std-libs-labels.yml
  build_tools/build/paths.yaml
  build_tools/build/src/ci_gen.rs
  build_tools/build/src/ci_gen/job.rs
  build_tools/ci_utils/src/actions/workflow/definition.rs
Labels: CI: No changelog needed

#12339 Text Predicates into new Operations
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  std-bits/table/src/main/java/org/enso/table/data/column/operation/BinaryOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/comparators/Comparators.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/comparators/DateComparators.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/comparators/DateTimeComparators.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/comparators/GenericComparators.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/comparators/NullComparators.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/comparators/StringComparators.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/comparators/TimeOfDayComparators.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/text/LikeOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/text/StringBooleanOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/text/TextPredicates.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/NullStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/Storage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/StringStorage.java
  test/Table_Tests/src/Common_Table_Operations/Column_Operations_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#12314 Encapsulating State access by moving nodes to runtime.state package
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Runtime.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Context_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Runtime_Helpers.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Runtime.enso
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/RuntimeCache.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/instrument/RuntimeServerTesting.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/interop/MetaObjectTest.java
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/IndirectInvokeConversionNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/dispatch/IndirectInvokeFunctionNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/InstrumentorBuiltin.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/runtime/ContextIsEnabledNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Builtins.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/UnresolvedConversion.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/UnresolvedSymbol.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/Function.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/state/GetStateNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/state/PutStateNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/state/RunStateNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/state/State.java
  lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/builtins/MethodNodeClassGenerator.java
  test/micro-distribution/lib/Standard/Base/0.0.0-dev/src/Runtime.enso
Labels: CI: Ready to merge, CI: No changelog needed, -libs-API-change-Base

#12343 Honor ENSO_LAUNCHER in runProjectManagerDistribution
  build.sbt
  docs/CONTRIBUTING.md
  project/DistributionPackage.scala
Labels: CI: Ready to merge, CI: No changelog needed

#12295 Removing volatile and synchronization in Text
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/text/ConcatRope.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/text/Text.java
Labels: CI: No changelog needed

#12353 Guard against values with no type info
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
Labels: CI: No changelog needed

#12348 use ag grid text filter for text columns
  app/gui/src/project-view/components/visualizations/TableVisualization.vue
  app/gui/src/project-view/components/visualizations/TableVisualization/tableVizToolbar.ts
Labels: CI: Ready to merge, CI: No changelog needed

#12354 Move Text Left and Text Right
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  std-bits/table/src/main/java/org/enso/table/data/column/operation/BinaryOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/CountNonTrivialWhitespace.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/cast/ToTextStorageConverter.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/comparators/Comparators.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/map/text/StringLongToStringOp.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/text/TextPartOperation.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/text/TextPredicates.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/NullStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/Storage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/StringStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/type/IntegerType.java
Labels: CI: Ready to merge, CI: No changelog needed

#12356 Fix Native Image search path on Windows
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  lib/scala/project-manager/src/main/resources/application.conf
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/runner/NativeExecCommand.scala
Labels: CI: Ready to merge, CI: No changelog needed

#12053 Add a test that verifies method resolution precedence between runtime and static analysis
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/TypePropagation.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/scope/ModuleResolver.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/TypeInferenceTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/TypeInferenceConsistencyTest.java
Labels: CI: Ready to merge, CI: No changelog needed

#12352 Discarded values static pass
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Multi_Value_Key.enso
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/TypeInferencePropagation.java
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/types/TypePropagation.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/TypeInferenceTest.java
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/Warning.scala
Labels: CI: Ready to merge, CI: No changelog needed

#12361 Ensure project-manager's logs are centrally collected
  lib/scala/logging-service-logback/src/main/java/org/enso/logging/service/logback/SocketLoggingNode.java
  lib/scala/logging-service/src/main/java/org/enso/logging/service/LoggingSetupHelper.java
  lib/scala/project-manager/src/main/resources/application.conf
Labels: CI: No changelog needed

#12369 Add rolling policy to cli logs' appender
  engine/runner/src/main/resources/application.conf
  lib/scala/logging-config/src/main/java/org/enso/logging/config/FileAppender.java
Labels: CI: No changelog needed

#12373 Add isolated = False,
  MODULE.bazel
Labels: CI: No changelog needed

#12367 Add pi and e to the expression language
  CHANGELOG.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Expression_Statics.md
  distribution/lib/Standard/Table/0.0.0-dev/src/Expression_Statics.enso
  test/Table_Tests/src/Common_Table_Operations/Expression_Spec.enso
Labels: CI: Ready to merge, -libs-API-change-Table

#12375 Use @TruffleBoundary instead of transferToInterpreter()
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/text/Text.java
Labels: CI: Ready to merge, CI: No changelog needed

#12363 Make the logging in std-benchmarks less verbose
  build.sbt
  engine/common/src/main/java/org/enso/common/ContextFactory.java
  lib/scala/bench-processor/src/main/java/org/enso/benchmarks/processor/SpecCollector.java
  std-bits/benchmarks/src/main/resources/application-test.conf
Labels: CI: Ready to merge, CI: No changelog needed

#12351 Initialize location in Cloud File Browser
  CHANGELOG.md
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetCloudBrowser.vue
  app/gui/src/project-view/components/widgets/FileBrowserWidget.vue
  app/gui/src/project-view/components/widgets/FileBrowserWidget/FileBrowserEntry.vue
  app/gui/src/project-view/components/widgets/FileBrowserWidget/__tests__/paths.test.ts
  app/gui/src/project-view/components/widgets/FileBrowserWidget/paths.ts
  app/gui/src/project-view/util/data/array.ts
  app/gui/src/project-view/util/equals.ts
Labels: CI: Ready to merge, -gui

#12365 Insert-link button
  CHANGELOG.md
  app/gui/src/project-view/components/MarkdownEditor/MarkdownEditorImpl.vue
  app/gui/src/project-view/components/MarkdownEditor/__tests__/decorations.test.ts
  app/gui/src/project-view/components/MarkdownEditor/__tests__/inlineFormatting.test.ts
  app/gui/src/project-view/components/MarkdownEditor/codemirror/decoration/linksAndImages.ts
  app/gui/src/project-view/components/MarkdownEditor/codemirror/decoration/table.ts
  app/gui/src/project-view/components/MarkdownEditor/codemirror/decoration/treeStateDecorator.ts
  app/gui/src/project-view/components/MarkdownEditor/codemirror/decoration/treeViewDecorator.ts
  app/gui/src/project-view/components/MarkdownEditor/codemirror/formatting/index.ts
  app/gui/src/project-view/components/MarkdownEditor/codemirror/formatting/inline.ts
  app/gui/src/project-view/components/MarkdownEditor/markdown/markdownDocument.ts
  app/gui/src/project-view/components/MarkdownEditor/markdown/trees.ts
Labels: CI: Ready to merge

#12380 Fix single stdlib bench run on CI
  build.sbt
Labels: CI: No changelog needed

#12300 Add tests for Generic JDBC support for Postgres, SQLite
  CHANGELOG.md
  distribution/lib/Standard/Database/0.0.0-dev/docs/api/JDBC/Generic_JDBC_Connection.md
  distribution/lib/Standard/Database/0.0.0-dev/src/JDBC/Generic_JDBC_Connection.enso
  test/Generic_JDBC_Tests/src/Generic_JDBC_Connection_Spec.enso
  test/Generic_JDBC_Tests/src/H2_Spec.enso
  test/Generic_JDBC_Tests/src/Main.enso
  test/Table_Tests/src/Database/JDBC/Generic_JDBC_Postgres_Spec.enso
  test/Table_Tests/src/Database/JDBC/Generic_JDBC_SQLite_Spec.enso
  test/Table_Tests/src/Database/Postgres_Spec.enso
  test/Table_Tests/src/Database/SQLite_Spec.enso
Labels: CI: Ready to merge, CI: Clean build required

#12364 Speculate on no interrupt in `WithInterruptHandlerNode`
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/thread/WithInterruptHandlerNode.java
Labels: CI: Ready to merge, CI: No changelog needed

#12163 Progress API
  CHANGELOG.md
  app/gui/src/project-view/stores/project/computedValueRegistry.ts
  build.sbt
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Logging.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Logging.enso
  engine/common/src/main/java/org/enso/common/RuntimeOptions.java
  engine/launcher/src/test/scala/org/enso/launcher/components/LauncherRunnerSpec.scala
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionCallbacks.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionProgressObserver.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ProgressAggregator.java
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
  engine/runtime-instrument-common/src/test/java/org/enso/interpreter/service/ProgressAggregatorTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/runtime/progress/ProgressTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/instrument/RuntimeProgressTest.java
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/BuiltinTypesTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/InstrumentTestContext.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeAsyncCommandsTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeComponentsTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeErrorsTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeExecutionEnvironmentTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeInstrumentTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeRecomputeTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeRefactoringTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeStdlibTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeSuggestionUpdatesTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeTextEditsTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeTypesTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java
  lib/scala/library-manager-test/src/test/scala/org/enso/librarymanager/published/repository/LibraryDownloadTest.scala
  lib/scala/logging-config/src/main/java/org/enso/logging/config/LoggerSetup.java
  lib/scala/logging-service-logback/src/main/java/module-info.java
  lib/scala/logging-service-logback/src/main/java/org/enso/logging/service/logback/LogbackObservingImpl.java
  lib/scala/logging-utils/src/main/java/module-info.java
  lib/scala/logging-utils/src/main/java/org/enso/logger/Converter.java
  lib/scala/logging-utils/src/main/java/org/enso/logger/LoggerUtils.java
  lib/scala/logging-utils/src/main/java/org/enso/logger/ObservedMessage.java
  lib/scala/logging-utils/src/test/scala/org/enso/logger/TestAppender.scala
  lib/scala/logging-utils/src/test/scala/org/enso/logger/TestLogMessage.scala
  lib/scala/logging-utils/src/test/scala/org/enso/logger/TestLogger.scala
Labels: CI: Ready to merge, CI: Clean build required, -libs-API-change-Base

#12379 Fix minor issues discovered in native-image
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/JobExecutionEngine.scala
  std-bits/base/src/main/resources/META-INF/native-image/org/enso/base/proxy-config.json
  std-bits/base/src/main/resources/META-INF/native-image/org/enso/base/reflect-config.json
Labels: CI: No changelog needed

#12198 Run cloud project locally
  app/common/src/text/english.json
  app/gui/project-manager-shim-middleware/index.ts
  app/gui/project-manager-shim-middleware/projectManagement.ts
  app/gui/src/dashboard/components/Devtools/EnsoDevtoolsImpl.tsx
  app/gui/src/dashboard/hooks/projectHooks.ts
  app/gui/src/dashboard/layouts/AssetContextMenu.tsx
  app/gui/src/dashboard/providers/FeatureFlagsProvider.tsx
  app/gui/src/dashboard/providers/ProjectsProvider.tsx
  app/gui/src/dashboard/services/RemoteBackend.ts
  app/gui/src/dashboard/services/remoteBackendPaths.ts
Labels: CI: No changelog needed, CI: Clean build required
