Repository enso-org/enso, pull requests merged in 2025-03, with the labels that each got.

#12389 Mapbox token from current env takes precedence
  app/gui/src/config.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, --regression, -gui

#12387 Add @codemirror/lang-markdown as git subtree
  .prettierignore
  app/lang-markdown/.github/workflows/dispatch.yml
  app/lang-markdown/.gitignore
  app/lang-markdown/.npmignore
  app/lang-markdown/CHANGELOG.md
  app/lang-markdown/LICENSE
  app/lang-markdown/README.md
  app/lang-markdown/package.json
  app/lang-markdown/src/README.md
  app/lang-markdown/src/commands.ts
  app/lang-markdown/src/index.ts
  app/lang-markdown/src/markdown.ts
  app/lang-markdown/test/test-commands.ts
Labels: CI: No changelog needed

#12391 Add @lezer/markdown as git subtree
  .prettierignore
  app/lezer-markdown/.gitignore
  app/lezer-markdown/CHANGELOG.md
  app/lezer-markdown/LICENSE
  app/lezer-markdown/README.md
  app/lezer-markdown/bin/build-readme.cjs
  app/lezer-markdown/build.js
  app/lezer-markdown/package.json
  app/lezer-markdown/src/README.md
  app/lezer-markdown/src/extension.ts
  app/lezer-markdown/src/index.ts
  app/lezer-markdown/src/markdown.ts
  app/lezer-markdown/src/nest.ts
  app/lezer-markdown/test/compare-tree.ts
  app/lezer-markdown/test/spec.ts
  app/lezer-markdown/test/test-extension.ts
  app/lezer-markdown/test/test-incremental.ts
  app/lezer-markdown/test/test-markdown.ts
  app/lezer-markdown/test/test-nesting.ts
  app/lezer-markdown/test/tsconfig.json
  app/lezer-markdown/tsconfig.json
Labels: CI: Ready to merge, CI: No changelog needed

#12366 Fix atom types in generated expression names
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Column_Naming_Helper.enso
  test/Table_Tests/src/Common_Table_Operations/Derived_Columns_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Offset_Spec.enso
Labels: CI: No changelog needed

#12390 Add locks in ExcelConnectionPool
  lib/scala/logging-service-logback/src/main/java/org/enso/logging/service/logback/SocketServer.java
  std-bits/table/src/main/java/org/enso/table/excel/ExcelConnectionPool.java
Labels: CI: No changelog needed

#12394 Reflection configuration for AWS
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3.enso
  std-bits/aws/src/main/java/org/enso/aws/file_system/S3Utils.java
  std-bits/aws/src/main/resources/META-INF/native-image/org/enso/aws/proxy-config.json
  std-bits/aws/src/main/resources/META-INF/native-image/org/enso/aws/reflect-config.json
  std-bits/aws/src/main/resources/META-INF/native-image/org/enso/aws/resource-config.json
  std-bits/base/src/main/resources/META-INF/native-image/org/enso/base/reflect-config.json
  std-bits/table/src/main/resources/META-INF/native-image/org/enso/table/reflect-config.json
Labels: CI: No changelog needed

#12393 Add Table.distance
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Geo/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Geo/0.0.0-dev/src/Table_Extensions.enso
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Excel/Excel_Range.md
  distribution/lib/Standard/Table/0.0.0-dev/src/Excel/Excel_Range.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Widgets.enso
  lib/scala/pkg/src/main/resources/default/src/Main.enso
  test/Table_Tests/src/IO/Excel_Spec.enso
Labels: CI: Ready to merge

#12398 Fix passing variants into BasicInput
  app/gui/src/dashboard/components/AriaComponents/Inputs/ComboBox/ComboBox.tsx
  app/gui/src/dashboard/components/AriaComponents/Inputs/Input/Input.tsx
Labels: CI: No changelog needed, g-dashboard

#12299 Create Samples directory on application start
  app/ide-desktop/client/src/index.ts
  app/ide-desktop/client/src/projectManagement.ts
Labels: CI: Ready to merge, CI: No changelog needed

#12081 Remove Discovery button
  app/gui/integration-test/dashboard/actions/DrivePageActions.ts
  app/gui/integration-test/dashboard/actions/StartModalActions.ts
  app/gui/integration-test/dashboard/actions/index.ts
  app/gui/integration-test/dashboard/assetPanel.spec.ts
  app/gui/integration-test/dashboard/createAsset.spec.ts
  app/gui/integration-test/dashboard/delete.spec.ts
  app/gui/integration-test/dashboard/loginLogout.spec.ts
  app/gui/integration-test/dashboard/startModal.spec.ts
  app/gui/src/dashboard/components/ErrorBoundary.tsx
  app/gui/src/dashboard/layouts/Drive.tsx
  app/gui/src/dashboard/layouts/StartModal.tsx
  app/gui/src/dashboard/pages/dashboard/Drive/DriveBar/DriveBar.tsx
  app/gui/src/dashboard/pages/dashboard/Drive/DriveBar/DriveBarToolbar.tsx
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#12408 Enable Hybrid execution in Electron
  app/gui/src/dashboard/providers/FeatureFlagsProvider.tsx
  app/ide-desktop/client/src/projectManagement.ts
  app/ide-desktop/client/src/server.ts
Labels: CI: Ready to merge, CI: No changelog needed, g-electron, -gui

#12405 Only create a single `Managed_Resource` for the response stream in `HTTP.request`
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Network/HTTP/Response.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Network/HTTP/Response_Body.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Response.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Response_Body.enso
Labels: CI: Ready to merge, CI: No changelog needed

#12388 Speed Vector.at and Vector.length up by avoiding wrapping of warnings
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/immutable/AtVectorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/immutable/LengthVectorNode.java
Labels: CI: No changelog needed

#12410 Make side bar icons match between dashboard and graph editor
  app/gui/src/project-view/assets/icons.svg
  app/gui/src/project-view/components/DockPanel.vue
  app/gui/src/project-view/stores/rightDock.ts
Labels: CI: No changelog needed

#12401 Add join and navigate icons
  app/gui/src/project-view/assets/icons.svg
Labels: CI: Ready to merge, CI: No changelog needed

#12386 New Component Browser with Groups panel
  CHANGELOG.md
  app/gui/integration-test/project-view/componentBrowser.spec.ts
  app/gui/integration-test/project-view/locate.ts
  app/gui/src/project-view/bindings.ts
  app/gui/src/project-view/components/ComponentBrowser.vue
  app/gui/src/project-view/components/ComponentBrowser/ComponentEditor.vue
  app/gui/src/project-view/components/ComponentBrowser/ComponentEntry.vue
  app/gui/src/project-view/components/ComponentBrowser/ComponentList.vue
  app/gui/src/project-view/components/ComponentBrowser/component.ts
  app/gui/src/project-view/components/ComponentBrowser/filtering.ts
  app/gui/src/project-view/components/ComponentBrowser/input.ts
  app/gui/src/project-view/components/ComponentBrowser/scrolling.ts
  app/gui/src/project-view/components/ContextMenuTrigger.vue
  app/gui/src/project-view/components/DropdownMenu.vue
  app/gui/src/project-view/components/VirtualizedList.vue
  app/gui/src/project-view/composables/nodeColors.ts
  app/gui/src/project-view/providers/action.ts
  app/gui/src/project-view/stores/graph/graphDatabase.ts
  app/gui/src/project-view/stores/suggestionDatabase/documentation.ts
  app/gui/src/project-view/stores/suggestionDatabase/index.ts
  app/gui/src/project-view/stores/suggestionDatabase/lsUpdate.ts
  app/ide-desktop/client/tests/localWorkflow.spec.ts
Labels: CI: Ready to merge, -gui

#12414 Eliminate a number of memory leaks in tests
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/dump/test/DocsGenerateTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/ExecCompilerTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/runtime/ManagedResourceTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/runtime/RefTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/runtime/progress/ProgressTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/AnyOrStaticTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/AnyToTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/AutoscopedConstructorTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/BinaryOpFloatTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/BinaryOpIntegerTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/CaseOfTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/ConversionMethodTests.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/DebuggingEnsoTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/EnsoMultiValueInteropTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/EqualsMultiValueTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/EqualsTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/LazyAtomFieldTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/MethodResolutionTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/MockLogHandler.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/NativeLibraryFinderTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/NonStrictModeTests.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/PolyglotFindExceptionMessageTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/PrintTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/RootNamesTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/SharedEngineTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/SignaturePolyglotTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/TypeInferenceConsistencyTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/ValuesGenerator.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/VectorSortTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/WarningsTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/asserts/AssertionsTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/asserts/SuccessfulAssertionExpressionTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/builtins/BuiltinTypesExposeMethodsTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/builtins/BuiltinsJavaInteropTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/hash/HashCodeTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/instrument/AvoidIdInstrumentationTagTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/instrument/DebugServerInspectTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/instrument/InsightForEnsoTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/instrument/RuntimeProgressTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/interop/JavaInteropTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/interop/JsInteropTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/interop/MetaObjectTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/interop/MethodInvocationOnTypeConsistencyTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/interop/TypesExposeConstructorsTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/meta/MetaIsATest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/meta/MetaTypeMethodsTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/semantic/DataflowErrorPropagationTest.java
  engine/runtime-integration-tests/src/test/scala/org/enso/compiler/test/semantic/ImportExportTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/InstrumentTestContext.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeVisualizationsTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/polyglot/test/ApiTest.scala
  engine/runtime-integration-tests/src/test/scala/org/enso/polyglot/test/ModuleManagementTest.scala
  engine/runtime-test-instruments/src/main/java/org/enso/interpreter/test/instruments/NodeCountingTestInstrument.java
Labels: CI: Ready to merge, CI: No changelog needed

#12384 Run ENSO_CLOUD tests with native-image
  build_tools/build/src/enso.rs
Labels: CI: No changelog needed

#12419 Fix dependencies on `library-manager`
  build.sbt
  lib/scala/library-manager/src/test/resources/application-test.conf
  lib/scala/library-manager/src/test/scala/org/enso/librarymanager/published/repository/LibraryDownloadTest.scala
  lib/scala/library-manager/src/test/scala/org/enso/librarymanager/test/published/repository/DownloaderTest.scala
  lib/scala/library-manager/src/test/scala/org/enso/librarymanager/test/published/repository/DummyRepository.scala
  lib/scala/library-manager/src/test/scala/org/enso/librarymanager/test/published/repository/EmptyRepository.scala
  lib/scala/library-manager/src/test/scala/org/enso/librarymanager/test/published/repository/ExampleRepository.scala
  lib/scala/library-manager/src/test/scala/org/enso/libraryupload/LibraryUploadTest.scala
Labels: CI: No changelog needed

#12399 Fix logout
  app/gui/src/dashboard/providers/SessionProvider.tsx
Labels: CI: No changelog needed, --bug, g-dashboard

#12427 Re-enable running unit tests in shared packages
  app/common/package.json
  app/common/src/services/Backend/__test__/projectExecution.test.ts
  app/gui/src/project-view/components/DocumentationEditor.vue
  app/lang-markdown/package.json
  app/lezer-markdown/package.json
  app/ydoc-server/package.json
  app/ydoc-shared/package.json
  app/ydoc-shared/src/ast/__tests__/documentation.test.ts
  app/ydoc-shared/src/ast/documentation.ts
  app/ydoc-shared/src/ast/ensoMarkdown.ts
  app/ydoc-shared/src/ast/parse.ts
  app/ydoc-shared/src/ast/tree.ts
  package.json
  pnpm-lock.yaml
Labels: CI: Ready to merge, CI: No changelog needed

#12331 Allow generic JDBC connection through `Database.connect`
  CHANGELOG.md
  distribution/lib/Standard/Database/0.0.0-dev/docs/api/JDBC/Generic_JDBC_Connection.md
  distribution/lib/Standard/Database/0.0.0-dev/src/JDBC/Generic_JDBC_Connection.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Main.enso
  std-bits/database/src/main/java/org/enso/database/jdbc/GenericJDBCConnectionDetailsImpl.java
  test/Generic_JDBC_Tests/src/H2_Spec.enso
Labels: CI: Ready to merge, CI: Clean build required

#12404 Remove semi colons from html links
  app/gui/src/project-view/components/visualizations/TableVisualization.vue
  app/gui/src/project-view/components/visualizations/TableVisualization/tableVizUtils.ts
  app/gui/src/project-view/components/visualizations/__tests__/tableVizUtilsTests.spec.ts
Labels: CI: Ready to merge, CI: No changelog needed

#12382 Fix update info
  app/gui/integration-test/project-view/graphNodeVisualization.spec.ts
  app/gui/integration-test/project-view/locate.ts
  app/gui/src/project-view/components/GraphEditor/GraphVisualization/VisualizationToolbar.vue
  app/gui/src/project-view/stores/project/computedValueRegistry.ts
Labels: CI: Ready to merge, CI: No changelog needed

#12441 Fix link to TEAMID.
  app/ide-desktop/client/electron-builder-config.ts
Labels: CI: No changelog needed

#12435 Fix small component menu
  app/gui/src/project-view/components/ActionButton.vue
Labels: CI: No changelog needed

#12420 Literals and operators in Component Browser
  CHANGELOG.md
  app/gui/src/project-view/components/ComponentBrowser.vue
  app/gui/src/project-view/components/ComponentBrowser/ComponentList.vue
  app/gui/src/project-view/components/ComponentBrowser/__tests__/input.test.ts
  app/gui/src/project-view/components/ComponentBrowser/component.ts
  app/gui/src/project-view/components/ComponentBrowser/input.ts
  app/gui/src/project-view/util/ast/__tests__/abstract.test.ts
  app/rust-ffi/src/lib.rs
  app/ydoc-server-polyglot/src/ffiPolyglot.ts
  app/ydoc-server-polyglot/src/polyglot.d.ts
  app/ydoc-shared/src/ast/ffi.ts
  app/ydoc-shared/src/ast/token.ts
  app/ydoc-shared/src/ast/tree.ts
Labels: CI: Ready to merge, -gui

#12260 Make test failure source locations lazy
  distribution/lib/Standard/Test/0.0.0-dev/docs/api/Extensions.md
  distribution/lib/Standard/Test/0.0.0-dev/docs/api/Frame_Hider.md
  distribution/lib/Standard/Test/0.0.0-dev/docs/api/Problems.md
  distribution/lib/Standard/Test/0.0.0-dev/docs/api/Should_Reach.md
  distribution/lib/Standard/Test/0.0.0-dev/docs/api/Test.md
  distribution/lib/Standard/Test/0.0.0-dev/src/Extensions.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Frame_Hider.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Problems.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Should_Reach.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Test.enso
  test/Base_Tests/src/Semantic/Meta_Location_Spec.enso
  test/Base_Tests/src/System/File_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Aggregate_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Join/Join_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Main.enso
  test/Table_Tests/src/Common_Table_Operations/Select_Columns_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Util.enso
  test/Table_Tests/src/IO/Fetch_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Spec.enso
  test/Table_Tests/src/Util.enso
  test/Table_Tests/src/Util_Spec.enso
  test/Test_Tests/src/Extensions_Spec.enso
  test/Test_Tests/src/Helpers.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required, -libs-API-change-Test

#12440 EnsoMultiValue.toDisplayString calls AnyToTextNode
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/node/typecheck/TypeCheckValueTest.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoMultiValue.java
  test/Base_Tests/src/Semantic/Multi_Value_As_Type_Refinement_Spec.enso
  test/Base_Tests/src/Semantic/Multi_Value_Spec.enso
Labels: CI: No changelog needed

#12439 Add runtime suggestions test for local functions
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeSuggestionUpdatesTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#12447 Minor improvements to robustness
  engine/runtime-compiler-dump-igv/src/main/java/module-info.java
  engine/runtime-instrument-repl-debugger/src/main/java/module-info.java
  engine/runtime-language-epb/src/main/java/module-info.java
  engine/runtime/src/main/java/module-info.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/Instrumentor.java
Labels: CI: No changelog needed

#12437 Scala Syntax in VSCode Extension without Metals
  .github/workflows/enso4igv.yml
  lib/scala/library-manager/src/test/java/org/enso/librarymanager/test/package.java
  tools/enso4igv/package.json
  tools/enso4igv/pom.xml
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#12438 Ability to generate cloud credentials in the CLI build tool
  build_tools/build/src/cloud_tests/mod.rs
  build_tools/cli/src/arg/backend.rs
  build_tools/cli/src/lib.rs
Labels: -tooling, CI: Ready to merge, CI: No changelog needed, l-cloud-integration

#12392 Update project state in Cloud when opening project in hybrid mode
  app/gui/src/dashboard/hooks/projectHooks.ts
  app/gui/src/dashboard/layouts/AssetContextMenu.tsx
  app/gui/src/dashboard/providers/ProjectsProvider.tsx
  app/gui/src/dashboard/services/RemoteBackend.ts
  app/gui/src/dashboard/services/remoteBackendPaths.ts
Labels: CI: Ready to merge, CI: No changelog needed, l-cloud-integration

#12430 Some small changes to the dashboard from QA session
  app/common/src/text/english.json
  app/gui/integration-test/dashboard/editAssetName.spec.ts
  app/gui/playwright.config.ts
  app/gui/src/dashboard/components/MenuEntry.tsx
  app/gui/src/dashboard/components/dashboard/DirectoryNameColumn.tsx
  app/gui/src/dashboard/components/dashboard/FileNameColumn.tsx
  app/gui/src/dashboard/components/dashboard/ProjectIcon.tsx
  app/gui/src/dashboard/components/dashboard/ProjectNameColumn.tsx
  app/gui/src/dashboard/components/dashboard/SecretNameColumn.tsx
  app/gui/src/dashboard/configurations/inputBindings.ts
  app/gui/src/dashboard/layouts/AssetContextMenu.tsx
  app/gui/src/dashboard/layouts/AssetPanel/AssetPanel.tsx
  app/gui/src/dashboard/layouts/AssetPanel/components/AssetProperties.tsx
  app/gui/src/dashboard/pages/dashboard/Drive/DriveBar/DriveBarToolbar.tsx
  app/ydoc-server/package.json
  pnpm-lock.yaml
Labels: CI: Ready to merge, CI: No changelog needed

#12460 Fix edition upload step during the CI release
  .github/workflows/release.yml
  build_tools/build/src/ci_gen.rs
  build_tools/build/src/ci_gen/job.rs
  build_tools/build/src/paths.rs
  build_tools/build/src/release.rs
Labels: CI: Ready to merge, CI: No changelog needed

#12286 Table Numeric Formatting
  app/gui/src/project-view/components/visualizations/TableVisualization.vue
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Column.md
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
  std-bits/table/src/main/java/org/enso/table/data/column/operation/CachedPropertyCheck.java
  std-bits/table/src/main/java/org/enso/table/data/column/operation/RequiresNumberFormatting.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/StringStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/BigDecimalStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/BigIntegerStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/DoubleStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/LongStorage.java
  std-bits/table/src/main/java/org/enso/table/data/column/storage/numeric/NumericFormattingStorage.java
  test/Visualization_Tests/src/Table_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, -libs-API-change-Table

#12458 Enable https on native-image
  build.sbt
  engine/runner/src/main/resources/META-INF/native-image/org/enso/runner/native-image.properties
  lib/scala/pkg/src/main/resources/META-INF/native-image/org/enso/pkg/resource-config.json
  project/NativeImage.scala
  std-bits/database/src/main/resources/META-INF/native-image/org/enso/database/native-image.properties
Labels: CI: Ready to merge, CI: No changelog needed

#12445 Avoid usage of isaot property in favor of ImageInfo
  build.sbt
  engine/common/src/main/java/module-info.java
  engine/common/src/main/java/org/enso/common/ContextFactory.java
  engine/common/src/main/java/org/enso/common/HostEnsoUtils.java
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  lib/java/desktop-environment/src/main/java/org/enso/desktopenvironment/MacTrashBin.java
  lib/java/desktop-environment/src/main/java/org/enso/desktopenvironment/WindowsTrashBin.java
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/runner/NativeExecCommand.scala
  test/Generic_JDBC_Tests/src/H2_Spec.enso
Labels: CI: No changelog needed, CI: Clean build required

#12442 Call Any.xyz on first dispatch of a multi value
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/EnsoMultiValue.java
  test/Base_Tests/src/Main.enso
  test/Base_Tests/src/Semantic/Conversion_Spec.enso
  test/Base_Tests/src/Semantic/Multi_On_Any_Spec.enso
Labels: CI: No changelog needed, CI: Clean build required

#12385 Telemetry for `Data.read`
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Telemetry.enso
  std-bits/base/src/main/java/org/enso/base/CurrentEnsoProject.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/audit/AuditLog.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/audit/AuditLogMessage.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/logging/LogApiAccess.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/logging/LogJob.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/logging/LogJobsQueue.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/logging/LogMessage.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/logging/RequestConfig.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/logging/RequestFailureException.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/telemetry/TelemetryLog.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/telemetry/TelemetryLogMessage.java
  test/Base_Internal_Tests/src/Main.enso
  test/Base_Internal_Tests/src/Telemetry_Log_Spec.enso
  tools/http-test-helper/src/main/java/org/enso/shttp/cloud_mock/EventsService.java
  tools/http-test-helper/src/main/java/org/enso/shttp/cloud_mock/PostLogHandler.java
Labels: CI: No changelog needed

#12468 Emit a warning on non-AOT ready libraries
  build.sbt
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/libraries/LocalLibraryManager.scala
  engine/language-server/src/main/scala/org/enso/languageserver/libraries/handler/LibraryPreinstallHandler.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/runner/src/main/java/org/enso/runner/DependencyPreinstaller.java
  engine/runner/src/main/java/org/enso/runner/EnsoLibraryFeature.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/DefaultPackageRepository.scala
  lib/scala/library-manager/src/main/scala/org/enso/librarymanager/DefaultLibraryProvider.scala
  lib/scala/library-manager/src/main/scala/org/enso/librarymanager/ResolvedLibrary.scala
  lib/scala/library-manager/src/main/scala/org/enso/librarymanager/local/DefaultLocalLibraryProvider.scala
  lib/scala/library-manager/src/test/resources/org/enso/librarymanager/local/test-library-path/Lib_With_Poly/package.yaml
  lib/scala/library-manager/src/test/resources/org/enso/librarymanager/local/test-library-path/Lib_With_Poly/polyglot/java/README.md
  lib/scala/library-manager/src/test/scala/org/enso/librarymanager/local/LocalLibraryProviderSpec.scala
  lib/scala/pkg/src/main/java/org/enso/pkg/PackageUtils.java
  lib/scala/pkg/src/main/scala/org/enso/pkg/Package.scala
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#12459 Component Browser Help Panel
  CHANGELOG.md
  app/gui/integration-test/project-view/componentBrowser.spec.ts
  app/gui/src/project-view/components/ComponentBrowser/ComponentList.vue
  app/gui/src/project-view/components/GraphEditor.vue
  app/gui/src/project-view/components/GraphEditor/selectionActions.ts
  app/gui/src/project-view/components/RightDockPanel.vue
  app/gui/src/project-view/components/VirtualizedList.vue
  app/gui/src/project-view/composables/nodeCreation.ts
  app/gui/src/project-view/providers/action.ts
  app/gui/src/project-view/stores/graph/index.ts
  app/gui/src/project-view/stores/rightDock.ts
  app/gui/src/project-view/stores/suggestionDatabase/__tests__/documentation.test.ts
  app/gui/src/project-view/stores/suggestionDatabase/documentation.ts
  app/gui/src/project-view/stores/suggestionDatabase/lsUpdate.ts
  app/gui/src/project-view/util/ast/__tests__/abstract.test.ts
  app/gui/src/project-view/util/ast/abstract.ts
Labels: CI: Ready to merge, -gui

#12413 Add Table.generate_rows
  CHANGELOG.md
  distribution/lib/Standard/AWS/0.0.0-dev/src/Database/Redshift/Internal/Redshift_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/docs/api/DB_Table.md
  distribution/lib/Standard/Database/0.0.0-dev/docs/api/Feature.md
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Feature.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Dialect.enso
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Generate_Rows_Range.md
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Table.md
  distribution/lib/Standard/Table/0.0.0-dev/src/Generate_Rows_Range.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  test/Table_Tests/src/Common_Table_Operations/Generate_Rows_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Main.enso
Labels: CI: Ready to merge, -libs-API-change-Database, -libs-API-change-Table

#12463 Additional test for https and reflection config updates
  build.sbt
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Extra_Imports.enso
  std-bits/base/src/main/resources/META-INF/native-image/org/enso/base/reflect-config.json
  std-bits/database/src/main/resources/META-INF/native-image/org/enso/database/reflect-config.json
  std-bits/table/src/main/resources/META-INF/native-image/org/enso/table/reflect-config.json
  test/Base_Tests/src/Network/Http_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#12481 Manual persistance for CachePreferences
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/PassPersistance.java
  engine/runtime-compiler/src/test/java/org/enso/compiler/test/pass/PassPersistanceTest.java
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#12469 Fix crash in documentation editor.
  app/gui/integration-test/project-view/rightPanel.spec.ts
  app/gui/src/project-view/components/MarkdownEditor/MarkdownEditorImpl.vue
  app/gui/src/project-view/components/MarkdownEditor/codemirror/formatting/index.ts
Labels: CI: Ready to merge, CI: No changelog needed

#12395 Detect duplicate `ManagedResource`s for the same resource
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Runtime/Managed_Resource.enso
  docs/semantics/managed-resources.md
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/ValuesGenerator.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/ResourceManager.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/builtin/Error.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/ManagedResource.java
  test/Base_Tests/src/Runtime/Managed_Resource_Spec.enso
  test/Benchmarks/src/Main.enso
  test/Benchmarks/src/Runtime/Managed_Resources.enso
Labels: --breaking, CI: Ready to merge, CI: Clean build required

#12479 Prevent code editor from sizing to content
  app/gui/integration-test/project-view/rightPanel.spec.ts
  app/gui/src/project-view/ProjectView.vue
  app/gui/src/project-view/components/GraphEditor.vue
  app/gui/src/project-view/mock/engine.ts
Labels: CI: Ready to merge, CI: No changelog needed

#12487 Improve type name on visualisation
  app/gui/src/project-view/components/GraphEditor/GraphVisualization/VisualizationToolbar.vue
Labels: CI: No changelog needed

#12475 disable histogram and heatmap visualizations
  CHANGELOG.md
  app/gui/src/project-view/stores/visualization/index.ts
Labels: CI: Ready to merge

#12495 Remove templates download from build script
  build_tools/build/src/engine.rs
  build_tools/build/src/engine/context.rs
Labels: p-highest, CI: No changelog needed, -ci, --bug, --regression, -build-script

#12494 Update edit icon
  app/gui/src/project-view/assets/icons.svg
Labels: CI: Ready to merge, CI: No changelog needed

#12486 Workaround ANTLR warnings in Native Image
  build.sbt
  distribution/lib/Standard/Table/0.0.0-dev/THIRD-PARTY/NOTICE
  distribution/lib/Standard/Table/0.0.0-dev/THIRD-PARTY/org.antlr.antlr4-runtime-4.12.0/NOTICES
  distribution/lib/Standard/Table/0.0.0-dev/THIRD-PARTY/org.antlr.antlr4-runtime-4.13.0/NOTICES
  docs/infrastructure/upgrading-graalvm.md
  tools/legal-review/Table/org.antlr.antlr4-runtime-4.12.0/copyright-ignore
  tools/legal-review/Table/org.antlr.antlr4-runtime-4.12.0/copyright-keep
  tools/legal-review/Table/org.antlr.antlr4-runtime-4.13.0/copyright-keep
  tools/legal-review/Table/report-state
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#12493 Fix rename function and add route in package testing for it
  .github/CODEOWNERS
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetFunctionName.vue
  app/ide-desktop/client/tests/localWorkflow.spec.ts
Labels: CI: No changelog needed, --bug, -gui

#12490 More reflection updates
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/System/Process.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/System/Process/Process_Builder.md
  distribution/lib/Standard/Base/0.0.0-dev/src/System/Process.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/Process/Process_Builder.enso
  std-bits/base/src/main/resources/META-INF/native-image/org/enso/base/reflect-config.json
  std-bits/snowflake/src/main/resources/META-INF/native-image/org/enso/snowflake/reflect-config.json
  test/Examples_Tests/src/Python_Examples_Spec.enso
Labels: CI: No changelog needed

#12503 Disable index column filtering
  app/gui/src/project-view/components/visualizations/TableVisualization.vue
Labels: CI: Ready to merge, CI: No changelog needed

#12499 Calling `Data.read` on a `Vector` tells the user to use read_many
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  test/Base_Tests/src/Network/Http_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#12477 Component Browser Suggestions
  CHANGELOG.md
  app/gui/integration-test/project-view/componentBrowser.spec.ts
  app/gui/integration-test/project-view/customExpect.ts
  app/gui/src/project-view/components/ComponentBrowser/ComponentEditor.vue
  app/gui/src/project-view/components/ComponentBrowser/__tests__/input.test.ts
  app/gui/src/project-view/components/ComponentBrowser/component.ts
  app/gui/src/project-view/mock/mockSuggestions.json
  app/gui/src/project-view/stores/suggestionDatabase/__tests__/documentation.test.ts
  app/gui/src/project-view/stores/suggestionDatabase/documentation.ts
  app/gui/src/project-view/stores/suggestionDatabase/lsUpdate.ts
  app/gui/src/project-view/util/docParser.ts
  app/ide-desktop/client/tests/localWorkflow.spec.ts
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  lib/rust/parser/doc-parser/src/lib.rs
Labels: CI: Ready to merge, -gui

#12492 Add Regex_Match to filter. Column.regex_match.
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Data/Filter_Condition.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Filter_Condition.enso
  distribution/lib/Standard/Database/0.0.0-dev/docs/api/DB_Column.md
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Column.md
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Filter_Condition_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Table_Ref.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  std-bits/table/src/main/java/org/enso/table/data/column/operation/text/TextPredicates.java
  test/Base_Tests/src/Data/List_Spec.enso
  test/Base_Tests/src/Data/Vector_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Expression_Spec.enso
  test/Table_Tests/src/Common_Table_Operations/Filter_Spec.enso
Labels: CI: Ready to merge, -libs-API-change-Database, -libs-API-change-Table

#12504 Reduce logging noise for heartbeats
  lib/scala/logging-service-logback/src/main/java/org/enso/logging/service/logback/SocketLoggingNode.java
  lib/scala/logging-service-logback/src/main/java/org/enso/logging/service/logback/SocketServer.java
Labels: CI: No changelog needed

#12510 Fix md file pattern match in API change stdlib label jobs
  .github/workflows/std-libs-labels.yml
  build_tools/build/src/ci_gen/job.rs
Labels: CI: No changelog needed

#12507 Unbreak NI integration for Snowflake on Linux
  build.sbt
Labels: CI: No changelog needed

#12272 Set up server side row model for table visualization
  CHANGELOG.md
  app/gui/src/project-view/components/GraphEditor/GraphVisualization.vue
  app/gui/src/project-view/components/GraphEditor/GraphVisualization/visualizationData.ts
  app/gui/src/project-view/components/shared/AgGridTableView.vue
  app/gui/src/project-view/components/visualizations/TableVisualization.vue
  app/gui/src/project-view/components/visualizations/TableVisualization/TableVizDataSourceUtils.ts
  app/gui/src/project-view/components/visualizations/TableVisualization/TableVizStatusBar.ts
  app/gui/src/project-view/components/visualizations/TableVisualization/tableVizFilterUtils.ts
  app/gui/src/project-view/components/visualizations/TableVisualization/tableVizToolbar.ts
  app/gui/src/project-view/components/visualizations/VisualizationHost.vue
  app/gui/src/project-view/providers/visualizationConfig.ts
  distribution/lib/Standard/Visualization/0.0.0-dev/docs/api/Table/Visualization.md
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
  test/Visualization_Tests/src/Table_Spec.enso
Labels: CI: Ready to merge, CI: Clean build required

#12514 Workaround tj-actions CVE
  .github/workflows/engine-changed-files.yml
  .github/workflows/gui-changed-files.yml
  .github/workflows/ide-changed-files.yml
  .github/workflows/std-libs-labels.yml
  .github/workflows/wasm-changed-files.yml
  build_tools/build/src/ci_gen/job.rs
Labels: CI: Ready to merge, CI: No changelog needed

#12509 Disable linting passes in Language Server
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
Labels: CI: Ready to merge, CI: No changelog needed

#12516 Try to workaround flaky "Previewing visualization" test
  app/gui/integration-test/project-view/graphNodeVisualization.spec.ts
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#12482 Accessible output port under warning/error message
  CHANGELOG.md
  app/gui/integration-test/project-view/edgeInteractions.spec.ts
  app/gui/src/project-view/components/GraphEditor/GraphEdge.vue
  app/gui/src/project-view/components/GraphEditor/GraphEdges.vue
  app/gui/src/project-view/components/GraphEditor/GraphNode.vue
  app/gui/src/project-view/components/GraphEditor/GraphNodeMessage.vue
  app/gui/src/project-view/components/GraphEditor/GraphNodeOutputPorts.vue
  app/gui/src/project-view/stores/graph/index.ts
Labels: CI: Ready to merge, -gui

#12491 Fix uploading from local subfolders
  app/gui/src/dashboard/layouts/AssetContextMenu.tsx
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#12496 Refactor top bar to actions and add more menu items.
  CHANGELOG.md
  app/gui/integration-test/project-view/locate.ts
  app/gui/integration-test/project-view/nodeClipboard.spec.ts
  app/gui/integration-test/project-view/removingNodes.spec.ts
  app/gui/src/project-view/ProjectView.vue
  app/gui/src/project-view/components/ActionButton.vue
  app/gui/src/project-view/components/ActionMenu.vue
  app/gui/src/project-view/components/ControlButtons.vue
  app/gui/src/project-view/components/ControlGroup.vue
  app/gui/src/project-view/components/DropdownMenu.vue
  app/gui/src/project-view/components/ExtendedMenu.vue
  app/gui/src/project-view/components/GraphEditor.vue
  app/gui/src/project-view/components/GraphEditor/CreateNodeFromPortButton.vue
  app/gui/src/project-view/components/MenuButton.vue
  app/gui/src/project-view/components/MenuEntry.vue
  app/gui/src/project-view/components/NavBreadcrumbs.vue
  app/gui/src/project-view/components/PlusButton.vue
  app/gui/src/project-view/components/RecordControl.vue
  app/gui/src/project-view/components/SelectionMenu.vue
  app/gui/src/project-view/components/TopBar.vue
  app/gui/src/project-view/components/UndoRedoButtons.vue
  app/gui/src/project-view/components/VNodes.vue
  app/gui/src/project-view/components/ZoomControl.vue
  app/gui/src/project-view/components/shared/AgGridTableView.vue
  app/gui/src/project-view/providers/action.ts
  app/ide-desktop/client/tests/localWorkflow.spec.ts
Labels: CI: Ready to merge

#12505 Change precedence of operator blocks
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  MODULE.bazel
  distribution/lib/Standard/AWS/0.0.0-dev/src/S3/S3_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Internal/Authentication.enso
  lib/rust/parser/BUILD.bazel
  lib/rust/parser/Cargo.toml
  lib/rust/parser/debug/tests/parse.rs
  lib/rust/parser/macros/BUILD.bazel
  lib/rust/parser/macros/Cargo.toml
  lib/rust/parser/macros/src/lib.rs
  lib/rust/parser/src/lexer.rs
  lib/rust/parser/src/lib.rs
  lib/rust/parser/src/macros.rs
  lib/rust/parser/src/macros/built_in.rs
  lib/rust/parser/src/macros/resolver.rs
  lib/rust/parser/src/syntax.rs
  lib/rust/parser/src/syntax/expression.rs
  lib/rust/parser/src/syntax/expression/annotations.rs
  lib/rust/parser/src/syntax/expression/application.rs
  lib/rust/parser/src/syntax/expression/apply.rs
  lib/rust/parser/src/syntax/expression/arity.rs
  lib/rust/parser/src/syntax/expression/blocks.rs
  lib/rust/parser/src/syntax/expression/compound_token.rs
  lib/rust/parser/src/syntax/expression/consumer.rs
  lib/rust/parser/src/syntax/expression/group.rs
  lib/rust/parser/src/syntax/expression/named_app.rs
  lib/rust/parser/src/syntax/expression/numbers.rs
  lib/rust/parser/src/syntax/expression/parser.rs
  lib/rust/parser/src/syntax/expression/reducer.rs
  lib/rust/parser/src/syntax/expression/section.rs
  lib/rust/parser/src/syntax/expression/types.rs
  lib/rust/parser/src/syntax/expression/whitespace.rs
  lib/rust/parser/src/syntax/item.rs
  lib/rust/parser/src/syntax/operator/application.rs
  lib/rust/parser/src/syntax/operator/group.rs
  lib/rust/parser/src/syntax/operator/precedence_resolver.rs
  lib/rust/parser/src/syntax/statement.rs
  lib/rust/parser/src/syntax/statement/function_def.rs
  lib/rust/parser/src/syntax/statement/type_def.rs
  lib/rust/parser/src/syntax/token/collect.rs
  lib/rust/parser/src/syntax/token/operator.rs
  lib/rust/parser/src/syntax/tree.rs
  lib/rust/parser/src/syntax/tree/block.rs
  lib/rust/parser/src/syntax/treebuilding.rs
  lib/rust/parser/src/syntax/treebuilding/block.rs
  lib/rust/parser/src/syntax/treebuilding/group.rs
  test/Base_Tests/src/Runtime/Stack_Size_Spec.enso
Labels: CI: Clean build required

#12527 Re-enable H2 tests for non-Windows
  test/Generic_JDBC_Tests/src/H2_Spec.enso
Labels: CI: No changelog needed

#12534 Fix foreign-function code edits
  app/gui/src/project-view/util/ast/__tests__/abstract.test.ts
  app/gui/src/project-view/util/ast/__tests__/bindings.test.ts
  app/gui/src/project-view/util/ast/__tests__/codeEdit.test.ts
  app/gui/src/project-view/util/ast/__tests__/printParse.test.ts
  app/gui/src/project-view/util/ast/bindings.ts
  app/ydoc-shared/src/ast/__tests__/syncToCode.test.ts
  app/ydoc-shared/src/ast/token.ts
  app/ydoc-shared/src/ast/tree.ts
Labels: CI: Ready to merge, CI: No changelog needed

#12525 fix boolean rendering in table viz
  app/gui/src/project-view/components/visualizations/TableVisualization.vue
Labels: CI: Ready to merge, CI: No changelog needed

#12545 Support flat .enso-project archives when running project in Hybrid mode
  app/gui/project-manager-shim-middleware/index.ts
  app/gui/src/dashboard/hooks/projectHooks.ts
  app/gui/src/dashboard/layouts/AssetContextMenu.tsx
  app/gui/src/dashboard/providers/ProjectsProvider.tsx
  app/gui/src/dashboard/services/RemoteBackend.ts
  app/ide-desktop/client/src/server.ts
Labels: CI: Ready to merge, CI: No changelog needed

#12508 Fix color ring in "global" color picker
  CHANGELOG.md
  app/gui/src/project-view/components/ColorRing.vue
  app/gui/src/project-view/components/ComponentMenu.vue
Labels: CI: Ready to merge, --bug, -gui

#12544 Temporarily disable refined types in Table/Column
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Type_Refinements/DB_Table_Refinements.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Type_Refinements/Column_Refinements.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Type_Refinements/Table_Refinements.enso
  test/Table_Tests/src/Database/Common/Single_Column_Table_Spec.enso
  test/Table_Tests/src/In_Memory/Single_Column_Table_Spec.enso
  test/Table_Tests/src/In_Memory/Single_Value_Column_Spec.enso
Labels: CI: No changelog needed

#12542 Do not dispose LS when ModulePersistence is still using it.
  app/ydoc-server/src/languageServerSession.ts
  app/ydoc-shared/src/util/net/ReconnectingWSTransport.ts
Labels: CI: Ready to merge, CI: No changelog needed

#12547 Set ENSO_CLOUD_PROJECT_DIRECTORY_PATH when running project
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/runner/RunSettings.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/runner/Runner.scala
Labels: CI: Ready to merge, CI: No changelog needed, l-cloud-integration

#12553 Fix recognizing missing currently-entered function
  app/gui/integration-test/project-view/collapsingAndEntering.spec.ts
  app/gui/src/project-view/stores/graph/index.ts
Labels: CI: No changelog needed

#12263 Allow fully qualified names in type signatures
  engine/runtime-compiler/src/main/scala/org/enso/compiler/data/BindingsMap.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/FullyQualifiedNames.scala
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/BindingsMapResolutionTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/ExecStrictCompilerTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/passes/resolve/NameResolutionTest.java
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/InterpreterSymbolResolutionTest.java
Labels: CI: No changelog needed, CI: Clean build required

#12546 Only use the server model for tables with more than 1000 rows
  app/gui/integration-test/project-view/tableVisualisation.spec.ts
  app/gui/src/project-view/components/shared/AgGridTableView.vue
  app/gui/src/project-view/components/visualizations/TableVisualization.vue
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
  test/Visualization_Tests/src/Table_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#12566 Fix broken link to blank issue in issue templates.
  .github/ISSUE_TEMPLATE/config.yml
Labels: CI: Ready to merge, CI: No changelog needed

#12473 Remove Frame_Hider type
  distribution/lib/Standard/Test/0.0.0-dev/docs/api/Frame_Hider.md
  distribution/lib/Standard/Test/0.0.0-dev/src/Extensions.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Frame_Hider.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Main.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Problems.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Should_Reach.enso
  distribution/lib/Standard/Test/0.0.0-dev/src/Test.enso
  test/Table_Tests/src/Common_Table_Operations/Main.enso
  test/Test_Tests/src/Helpers.enso
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required, -libs-API-change-Test

#12563 Fix refetching in versions history
  app/common/src/queryClient.ts
  app/gui/integration-test/dashboard/actions/LoginPageActions.ts
  app/gui/src/dashboard/App.tsx
  app/gui/src/dashboard/components/dashboard/AssetIcon.tsx
  app/gui/src/dashboard/layouts/AssetPanel/components/useAssetVersions.ts
  app/gui/src/dashboard/modals/UpsertSecretModal.tsx
  app/gui/src/dashboard/providers/__test__/SessionProvider.test.tsx
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#12558 Swap the order of redo action bindings on Mac
  app/gui/src/project-view/bindings.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui

#12455 Invalidate asset versions when a file is uploaded
  app/common/src/backendQuery.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#12556 Show error when newly-entered function cannot be found
  app/gui/integration-test/project-view/collapsingAndEntering.spec.ts
  app/gui/src/project-view/components/GraphMissingView.vue
  app/gui/src/project-view/stores/graph/index.ts
Labels: CI: Ready to merge, CI: No changelog needed

#12572 Fix table preserving manually-resized columns when data is updated
  app/gui/integration-test/project-view/tableVisualisation.spec.ts
  app/gui/integration-test/project-view/visualizationUpdates.ts
  app/gui/src/project-view/components/ResizeHandles.vue
  app/gui/src/project-view/components/shared/AgGridTableView.vue
  app/gui/src/project-view/mock/engine.ts
Labels: CI: Ready to merge, CI: No changelog needed

#12577 Ignore tests that rely on external service
  test/Table_Tests/src/IO/Fetch_Spec.enso
Labels: p-highest, CI: Ready to merge, CI: No changelog needed

#12488 Add Telemetry Appender
  build.sbt
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Delimited_Reader.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Telemetry.enso
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/runtime-integration-tests/src/test/java/org/enso/logging/service/logback/telemetry/test/TestLogFormatter.java
  lib/scala/logging-config/src/main/java/org/enso/logging/config/Appender.java
  lib/scala/logging-config/src/main/java/org/enso/logging/config/LoggerSetup.java
  lib/scala/logging-config/src/main/java/org/enso/logging/config/LoggingServiceConfig.java
  lib/scala/logging-config/src/main/java/org/enso/logging/config/TelemetryAppender.java
  lib/scala/logging-service-logback/src/main/java/module-info.java
  lib/scala/logging-service-logback/src/main/java/org/enso/logging/service/logback/LogbackSetup.java
  lib/scala/logging-service-logback/src/main/java/org/enso/logging/service/logback/LoggingServer.java
  lib/scala/logging-service-logback/src/main/java/org/enso/logging/service/logback/SocketServer.java
  lib/scala/logging-service-logback/src/main/java/org/enso/logging/service/logback/telemetry/LogFormatter.java
  lib/scala/logging-service-logback/src/main/java/org/enso/logging/service/logback/telemetry/LogJobsQueue.java
  lib/scala/logging-service-logback/src/main/java/org/enso/logging/service/logback/telemetry/LogMessage.java
  lib/scala/logging-service-logback/src/main/java/org/enso/logging/service/logback/telemetry/TelemetryAppender.java
  lib/scala/project-manager/src/main/resources/META-INF/native-image/org/enso/projectmanager/reflect-config.json
  lib/scala/project-manager/src/main/resources/application.conf
Labels: CI: No changelog needed, CI: Clean build required

#12548 Nested submenus
  CHANGELOG.md
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetCloudBrowser.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetFileBrowser.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection/SelectionSubmenu.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection/__tests__/dropdownTags.test.ts
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection/styles.ts
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection/tags.ts
  app/gui/src/project-view/components/widgets/DropdownWidget.vue
  app/gui/src/project-view/providers/widgetRegistry/__tests__/configuration.test.ts
  app/gui/src/project-view/providers/widgetRegistry/configuration.ts
  app/gui/src/project-view/stores/suggestionDatabase/index.ts
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Metadata.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Metadata.enso
Labels: CI: Ready to merge, -gui, -libs-API-change-Base

#12586 Input nodes have output ports
  app/gui/integration-test/project-view/collapsingAndEntering.spec.ts
  app/gui/src/project-view/components/GraphEditor/clipboard.ts
  app/gui/src/project-view/stores/graph/graphDatabase.ts
  app/gui/src/project-view/util/ast/node.ts
Labels: CI: Ready to merge, CI: No changelog needed

#12581 Ensure project dir exist when using --docs cmdline
  engine/runner/src/main/java/org/enso/runner/Main.java
  engine/runner/src/test/java/org/enso/runner/EngineMainTest.java
Labels: CI: No changelog needed

#12578 Fix spurious import warning
  engine/runtime-compiler/src/main/java/org/enso/compiler/pass/analyse/AmbiguousImportsAnalysis.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/ExecStrictCompilerTest.java
Labels: CI: No changelog needed

#12574 `add_group_number` for Postgres and SQLite
  CHANGELOG.md
  distribution/lib/Standard/Database/0.0.0-dev/docs/api/DB_Table.md
  distribution/lib/Standard/Database/0.0.0-dev/docs/api/Internal/Base_Generator.md
  distribution/lib/Standard/Database/0.0.0-dev/docs/api/Internal/Common/Group_Number_Helpers.md
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Common/Group_Number_Helpers.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Type_Mapping.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Dialect.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Grouping_Method.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  test/Table_Tests/src/Common_Table_Operations/Add_Group_Number_Spec.enso
Labels: CI: Ready to merge, -libs-API-change-Database

#12591 Avoid StringBuilder.setLength
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Pgpass.enso
  test/Base_Tests/src/Data/Text_Spec.enso
Labels: CI: No changelog needed

#12589 `invokeMember` should behave the same as `readMember.execute`
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/interop/AtomInteropTest.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/dispatch/CurryNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/Atom.java
Labels: CI: No changelog needed

#12587 Show menu when any part of component is hovered
  app/gui/integration-test/project-view/graphRenderNodes.spec.ts
  app/gui/src/project-view/components/GraphEditor/GraphNode.vue
Labels: CI: No changelog needed

#12462 Use MarkdownEditor in dashboard
  app/gui/integration-test/dashboard/assetPanel.spec.ts
  app/gui/package.json
  app/gui/src/App.vue
  app/gui/src/dashboard/components/MarkdownViewer/MarkdownViewer.tsx
  app/gui/src/dashboard/components/MarkdownViewer/defaultRenderer.ts
  app/gui/src/dashboard/layouts/AssetDocs/AssetDocs.tsx
  app/gui/src/dashboard/layouts/Editor.tsx
  app/gui/src/dashboard/utilities/vue.ts
  app/gui/src/project-view/components/DocumentationEditor.vue
  app/gui/src/project-view/components/GraphEditor.vue
  app/gui/src/project-view/components/MarkdownEditor.vue
  app/gui/src/project-view/components/MarkdownEditor/MarkdownEditorImpl.vue
  app/gui/src/project-view/util/codemirror/index.ts
  app/gui/src/project-view/util/codemirror/links.ts
  pnpm-lock.yaml
Labels: CI: Ready to merge, CI: No changelog needed

#12595 Avoid `null` & explicitly spell dependecy out
  engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/hash/HashCodeTest.java
  engine/runtime-language-arrow/src/main/java/module-info.java
Labels: CI: Ready to merge, CI: No changelog needed

#12598 Remove deprecated telemetry log from std base
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Telemetry.enso
  std-bits/base/src/main/java/org/enso/base/enso_cloud/audit/AuditLog.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/audit/AuditLogApiAccess.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/audit/AuditLogMessage.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/audit/LogJobsQueue.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/logging/LogJob.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/logging/LogMessage.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/logging/RequestConfig.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/logging/RequestFailureException.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/telemetry/TelemetryLog.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/telemetry/TelemetryLogMessage.java
  test/Base_Internal_Tests/src/Main.enso
  test/Base_Internal_Tests/src/Telemetry_Log_Spec.enso
  tools/http-test-helper/src/main/java/org/enso/shttp/cloud_mock/EventsService.java
  tools/http-test-helper/src/main/java/org/enso/shttp/cloud_mock/PostLogHandler.java
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#12535 Remove "X Components" label when editing existing component
  app/gui/integration-test/project-view/componentBrowser.spec.ts
  app/gui/src/project-view/components/ComponentBrowser/ComponentEditor.vue
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui

#12597 Fix error display on reload
  app/gui/src/dashboard/hooks/projectHooks.ts
  app/gui/src/dashboard/layouts/Editor.tsx
  app/gui/src/dashboard/layouts/TabBar.tsx
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#12590 add_group_number for Snowflake and SQLServer
  CHANGELOG.md
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Base_Generator.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/Internal/SQLServer_Dialect.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Dialect.enso
Labels: CI: Ready to merge, -libs-API-change-Database

#12584 Fix a code-edit whitespace case
  app/gui/src/project-view/components/MarkdownEditor/markdown/trees.ts
  app/gui/src/project-view/util/ast/__tests__/printParse.test.ts
  app/ydoc-shared/src/ast/__tests__/parsePrint.test.ts
  app/ydoc-shared/src/ast/documentation.ts
Labels: CI: Ready to merge, CI: No changelog needed

#12603 Add Navigate Up Button. Standardise breadcrumb icons.
  CHANGELOG.md
  app/gui/src/project-view/components/ActionButton.vue
  app/gui/src/project-view/components/DocumentationPanel/DocsBreadcrumbs.vue
  app/gui/src/project-view/components/ExtendedMenu.vue
  app/gui/src/project-view/components/GraphEditor.vue
  app/gui/src/project-view/components/MenuEntry.vue
  app/gui/src/project-view/components/NavBreadcrumbs.vue
  app/gui/src/project-view/components/widgets/FileBrowserWidget.vue
  app/gui/src/project-view/composables/stackNavigator.ts
  app/gui/src/project-view/providers/action.ts
Labels: CI: Ready to merge

#12576 Adjust output port button size and behavior
  CHANGELOG.md
  app/gui/integration-test/project-view/componentBrowser.spec.ts
  app/gui/src/project-view/components/GraphEditor/CreateNodeFromPortButton.vue
  app/gui/src/project-view/components/GraphEditor/GraphNodeOutputPorts.vue
  app/gui/src/project-view/stores/graph/index.ts
Labels: CI: Ready to merge, -gui

#12554 Fix displayed frontend version in Electron package.
  app/ide-desktop/client/buildInfo.ts
  app/ide-desktop/client/esbuildConfig.ts
  app/ide-desktop/client/src/fileAssociations.ts
  app/ide-desktop/client/src/urlAssociations.ts
  lib/js/runner/src/runner/log.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui

#12579 Display no dropdown for boolean values
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection.vue
Labels: CI: Ready to merge, CI: No changelog needed, --bug, -gui

#12502 Add icons for join_kind
  CHANGELOG.md
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection.vue
  app/gui/src/project-view/components/GraphEditor/widgets/WidgetSelection/tags.ts
  app/gui/src/project-view/components/widgets/DropdownWidget.vue
  app/gui/src/project-view/providers/widgetRegistry/configuration.ts
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Table.enso
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Join_Kind.md
  distribution/lib/Standard/Table/0.0.0-dev/src/Join_Kind.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
Labels: CI: Ready to merge, -libs-API-change-Table

#12609 Fix Data Link telemetry issue in Data.read.
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
Labels: CI: Ready to merge, CI: No changelog needed

#12610 Fix copy.spec, improve tests speed in dev mode
  app/gui/integration-test/dashboard/copy.spec.ts
  app/gui/vite.test.config.ts
Labels: CI: No changelog needed

#12607 Remove updateModal API
  app/gui/src/dashboard/pages/dashboard/Dashboard.tsx
  app/gui/src/dashboard/providers/ModalProvider.tsx
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#12606 Connection test should close the connection and clean up
  test/Generic_JDBC_Tests/src/H2_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#12526 Implement reload cache clearing for `CloudRequestCache`
  CHANGELOG.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Network/Reload_Sentinel.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Extra_Imports.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/Reload_Sentinel.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Excel_Writer.enso
  std-bits/base/src/main/java/org/enso/base/cache/APIRequestCache.java
  std-bits/base/src/main/java/org/enso/base/cache/HasClearableCacheNotRegisteredException.java
  std-bits/base/src/main/java/org/enso/base/cache/LRUCache.java
  std-bits/base/src/main/java/org/enso/base/cache/ReloadDetector.java
  std-bits/base/src/main/java/org/enso/base/enso_cloud/CloudRequestCache.java
  std-bits/table/src/main/java/org/enso/table/excel/ExcelConnectionPool.java
  std-bits/table/src/main/resources/META-INF/native-image/org/enso/table/reflect-config.json
  test/Base_Tests/src/Network/Enso_Cloud/Enso_Cloud_Spec.enso
  test/Table_Tests/src/IO/Excel_Spec.enso
  test/Table_Tests/src/IO/Fetch_Spec.enso
Labels: CI: Ready to merge, CI: Clean build required, -libs-API-change-Base

#12600 Remove jackson from telemetry appender
  build.sbt
  engine/runtime-integration-tests/src/test/java/org/enso/logging/service/logback/telemetry/test/TestLogFormatter.java
  lib/java/logging-service-telemetry/src/main/java/module-info.java
  lib/java/logging-service-telemetry/src/main/java/org/enso/logging/service/telemetry/LogFormatter.java
  lib/java/logging-service-telemetry/src/main/java/org/enso/logging/service/telemetry/LogJobsQueue.java
  lib/java/logging-service-telemetry/src/main/java/org/enso/logging/service/telemetry/LogMessage.java
  lib/java/logging-service-telemetry/src/main/java/org/enso/logging/service/telemetry/TelemetryAppenderImpl.java
  lib/java/logging-service-telemetry/src/main/scala/org/enso/logging/service/telemetry/ApiMessage.scala
  lib/java/logging-service-telemetry/src/main/scala/org/enso/logging/service/telemetry/Credentials.scala
  lib/scala/logging-service-logback/src/main/java/module-info.java
  lib/scala/logging-service-logback/src/main/java/org/enso/logging/service/logback/LogbackSetup.java
  lib/scala/logging-service-logback/src/main/java/org/enso/logging/service/logback/TelemetryAppender.java
  lib/scala/project-manager/src/main/resources/META-INF/native-image/org/enso/projectmanager/reflect-config.json
Labels: CI: No changelog needed, CI: Clean build required

#12612 Add YdocTest timeout
  lib/java/ydoc-server/src/test/java/org/enso/ydoc/server/YdocTest.java
Labels: CI: Ready to merge, CI: No changelog needed

#12616 Fix tab open for local projects/cloud
  app/gui/src/dashboard/hooks/projectHooks.ts
  app/gui/src/dashboard/layouts/AssetContextMenu.tsx
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#12531 Enable NI for engine nightly checks
  .github/workflows/engine-checks-nightly.yml
  build_tools/build/src/ci_gen.rs
  build_tools/build/src/ci_gen/job.rs
  build_tools/build/src/engine.rs
  build_tools/cli/src/lib.rs
Labels: CI: No changelog needed, CI: Clean build required

#12619 Fix grids stuck in loading state
  app/gui/src/project-view/components/shared/AgGridTableView.vue
Labels: CI: Ready to merge, CI: No changelog needed

#12622 Disable flaky excel test (again)
  test/Table_Tests/src/IO/Excel_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed

#12608 Dashboard fixes 2025-03-20
  app/common/src/text/english.json
  app/gui/src/dashboard/assets/docs.svg
  app/gui/src/dashboard/components/dashboard/ProjectIcon.tsx
  app/gui/src/dashboard/components/dashboard/ProjectNameColumn.tsx
  app/gui/src/dashboard/components/dashboard/column.ts
  app/gui/src/dashboard/components/dashboard/column/DocsColumn.tsx
  app/gui/src/dashboard/components/dashboard/column/columnUtils.ts
  app/gui/src/dashboard/components/dashboard/columnHeading.ts
  app/gui/src/dashboard/components/dashboard/columnHeading/DocsColumnHeading.tsx
  app/gui/src/dashboard/configurations/inputBindings.ts
  app/gui/src/dashboard/hooks/backendHooks.ts
  app/gui/src/dashboard/hooks/projectHooks.ts
  app/gui/src/dashboard/layouts/AssetContextMenu.tsx
  app/gui/src/dashboard/layouts/AssetPanel/components/AssetVersion.tsx
  app/gui/src/dashboard/layouts/AssetsTable.tsx
  app/gui/src/dashboard/pages/dashboard/Dashboard.tsx
  app/gui/src/dashboard/pages/dashboard/Drive/DriveBar/DriveBarNavigation.tsx
  app/gui/src/dashboard/providers/FeatureFlagsProvider.tsx
  app/gui/src/dashboard/tailwind.css
  app/gui/src/dashboard/utilities/inputBindings.ts
  app/gui/tailwind.config.ts
  app/ide-desktop/client/src/server.ts
Labels: CI: Ready to merge, CI: No changelog needed, --bug, g-dashboard

#12620 Add more telemetry info during LS start
  engine/language-server/src/main/java/module-info.java
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
Labels: CI: Ready to merge, CI: No changelog needed

#12478 Use `ensoPath` to read the full path of the asset instead of computing it manually
  app/common/src/backendQuery.ts
  app/common/src/services/Backend.ts
  app/gui/integration-test/dashboard/actions/api.ts
  app/gui/src/dashboard/components/dashboard/AssetIcon.tsx
  app/gui/src/dashboard/hooks/backendBatchedHooks.ts
  app/gui/src/dashboard/layouts/AssetContextMenu.tsx
  app/gui/src/dashboard/layouts/AssetPanel/components/AssetProperties.tsx
  app/gui/src/dashboard/services/LocalBackend.ts
  app/gui/src/dashboard/services/RemoteBackend.ts
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#12588 Fix sorting in Table viz
  app/gui/src/project-view/components/visualizations/TableVisualization.vue
  distribution/lib/Standard/Visualization/0.0.0-dev/src/Table/Visualization.enso
Labels: CI: Ready to merge, CI: No changelog needed

#12615 Make Decimal constructors private
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Data/Decimal.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Decimal.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Statement_Setter.enso
Labels: CI: No changelog needed, CI: Clean build required, -libs-API-change-Base

#12632 Minor fixes for release
  distribution/lib/Standard/Table/0.0.0-dev/src/Expression_Statics.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
Labels: CI: Ready to merge, CI: No changelog needed

#12550 Enabled per-project JVM mode configuration
  build_tools/build/src/engine/context.rs
  engine/language-server/src/main/scala/org/enso/languageserver/data/Config.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/workspace/ProjectInfoHandler.scala
  engine/language-server/src/test/scala/org/enso/languageserver/libraries/ComponentGroupsResolverSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/libraries/ComponentGroupsValidatorSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/WorkspaceOperationsTest.scala
  engine/launcher/src/main/scala/org/enso/launcher/cli/LauncherApplication.scala
  engine/launcher/src/test/scala/org/enso/launcher/components/LauncherRunnerSpec.scala
  engine/runner/src/main/java/org/enso/runner/JavaFinder.java
  engine/runner/src/main/java/org/enso/runner/Main.java
  engine/runtime-integration-tests/src/test/java/org/enso/compiler/test/StaticAnalysisTest.java
  lib/scala/pkg/src/main/scala/org/enso/pkg/Config.scala
  lib/scala/pkg/src/main/scala/org/enso/pkg/Package.scala
  lib/scala/pkg/src/test/scala/org/enso/pkg/ConfigSpec.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/ExecutorWithUnlimitedPool.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerController.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerDescriptor.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/repository/ProjectFileRepository.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/model/Project.scala
  lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectService.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/runner/LanguageServerOptions.scala
  lib/scala/runtime-version-manager/src/main/scala/org/enso/runtimeversionmanager/runner/Runner.scala
  test/Generic_JDBC_Tests/package.yaml
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#12633 Component Browser Tuning
  distribution/lib/Standard/Base/0.0.0-dev/package.yaml
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Dictionary.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Map.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/XML.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_Secret.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Internal/Extra_Imports.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Meta.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Network/HTTP/Request.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/System/Process.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Database.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Extensions/Upload_In_Memory_Table.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/JDBC/Generic_JDBC_Connection.enso
  distribution/lib/Standard/Google_Api/0.0.0-dev/src/Google_Analytics.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Connection/Key_Pair_Credentials.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Join_Kind.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Table.enso
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeComponentsTest.scala
Labels: CI: Ready to merge, CI: No changelog needed

#12639 Fix booting of native language server
  engine/language-server/src/main/resources/META-INF/native-image/org/enso/languageserver/reflect-config.json
Labels: p-highest, CI: Ready to merge, CI: No changelog needed

#12602 Make RuntimeAsyncCommandsTest more reliable
  engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/instrument/RuntimeAsyncCommandsTest.scala
Labels: CI: Ready to merge, CI: No changelog needed, CI: Clean build required

#12640 Append x-ide-version to all requests to the backend
  app/gui/src/ReactRoot.tsx
Labels: CI: No changelog needed, g-dashboard

#12474 Refactor more IR Scala case classes to Java
  engine/runtime-compiler/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/desugar/ComplexType.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/desugar/FunctionBinding.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/desugar/Imports.scala
  engine/runtime-compiler/src/main/scala/org/enso/compiler/phase/ImportResolver.scala
  engine/runtime-parser-dsl/src/main/java/org/enso/runtime/parser/dsl/GenerateFields.java
  engine/runtime-parser-dsl/src/main/java/org/enso/runtime/parser/dsl/IRChild.java
  engine/runtime-parser-processor-tests/src/test/java/org/enso/runtime/parser/processor/test/TestIRProcessorInline.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/IRNodeClassGenerator.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/field/Field.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/field/FieldCollector.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/field/ListField.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/field/OptionListField.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/field/PersistanceReferenceField.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/field/ReferenceField.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/methodgen/BuilderMethodGenerator.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/methodgen/ChildrenMethodGenerator.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/methodgen/DuplicateMethodGenerator.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/methodgen/MapExpressionsMethodGenerator.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/methodgen/ToStringMethodGenerator.java
  engine/runtime-parser-processor/src/main/java/org/enso/runtime/parser/processor/utils/Utils.java
  engine/runtime-parser/src/main/java/org/enso/compiler/core/TreeToIr.java
  engine/runtime-parser/src/main/java/org/enso/compiler/core/ir/module/Scope.java
  engine/runtime-parser/src/main/java/org/enso/compiler/core/ir/module/scope/Import.java
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/module/Scope.scala
  engine/runtime-parser/src/main/scala/org/enso/compiler/core/ir/module/scope/Import.scala
Labels: CI: No changelog needed, CI: Clean build required, -compiler

#12646 Minor Dashboard Edits
  app/common/src/text/english.json
  app/gui/src/dashboard/configurations/topbarLinks.json
  app/gui/src/dashboard/layouts/AssetPanel/components/AssetProperties.tsx
  app/gui/src/dashboard/modals/UpsertSecretModal.tsx
Labels: CI: Ready to merge, CI: No changelog needed, g-dashboard

#12657 Add email icon
  app/gui/src/project-view/assets/icons.svg
Labels: CI: Ready to merge, CI: No changelog needed

#12660 Fix NI crash by updating reflection config
  std-bits/table/src/main/resources/META-INF/native-image/org/enso/table/reflect-config.json
Labels: CI: Ready to merge, CI: No changelog needed

#12651 Remove `StringBuilder` from .pgpass parsing
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Pgpass.enso
Labels: CI: Ready to merge, CI: No changelog needed

#12662 Hide Suggestion tag from doc panel
  app/gui/src/project-view/components/DocumentationPanel/DocsTags.vue
Labels: CI: Ready to merge, CI: No changelog needed, -gui

#12642 Add nested dropdowns to Filter Condition
  distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso
Labels: CI: No changelog needed

#12659 Update README.md
  README.md
Labels: CI: No changelog needed

#12664 Fix "No such module" warning in runtime tests
  build.sbt
Labels: CI: No changelog needed

#12661 Use varargs when logging arguments to slf4j
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/instrument/job/SerializeModuleJob.java
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/AttachVisualizationCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/EditFileCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/ModifyVisualizationCmd.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/JobExecutionEngine.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/ReentrantLocking.scala
  engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/UpsertVisualizationJob.scala
Labels: CI: Ready to merge, CI: No changelog needed

#12669 Small change to email icon
  app/gui/src/project-view/assets/icons.svg
Labels: CI: Ready to merge, CI: No changelog needed

#12644 Confirm overwritting files in file browser widget
  CHANGELOG.md
  app/gui/src/project-view/components/widgets/FileBrowserWidget.vue
  app/gui/src/project-view/components/widgets/FileBrowserWidget/__tests__/paths.test.ts
  app/gui/src/project-view/components/widgets/FileBrowserWidget/paths.ts
Labels: CI: Ready to merge, x-new-feature, -gui

#12647 Make CB input as high as node; fix canceling with `Escape`
  app/gui/src/App.vue
  app/gui/src/dashboard/modals/ConfirmDeleteModal.tsx
  app/gui/src/dashboard/pages/dashboard/Dashboard.tsx
  app/gui/src/dashboard/providers/ModalProvider.tsx
  app/gui/src/project-view/components/ComponentBrowser.vue
  app/gui/src/project-view/components/ComponentBrowser/ComponentEditor.vue
  app/gui/src/project-view/components/GraphEditor.vue
  app/gui/src/project-view/components/GraphEditor/GraphNode.vue
Labels: CI: Ready to merge, CI: No changelog needed, --bug

#12663 Add regex_match to postgres
  CHANGELOG.md
  distribution/lib/Standard/AWS/0.0.0-dev/src/Database/Redshift/Internal/Redshift_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/docs/api/DB_Column.md
  distribution/lib/Standard/Database/0.0.0-dev/docs/api/Dialect_Flag.md
  distribution/lib/Standard/Database/0.0.0-dev/docs/api/Internal/Postgres/Postgres_Dialect.md
  distribution/lib/Standard/Database/0.0.0-dev/src/DB_Column.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Dialect_Flag.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/Postgres/Postgres_Dialect.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Internal/SQLite/SQLite_Dialect.enso
  distribution/lib/Standard/Microsoft/0.0.0-dev/src/Internal/SQLServer_Dialect.enso
  distribution/lib/Standard/Snowflake/0.0.0-dev/src/Internal/Snowflake_Dialect.enso
  distribution/lib/Standard/Table/0.0.0-dev/docs/api/Column.md
  distribution/lib/Standard/Table/0.0.0-dev/src/Column.enso
  test/Table_Tests/src/Common_Table_Operations/Filter_Spec.enso
Labels: -libs-API-change-Database, -libs-API-change-Table

#12675 Move `from_text` to `parse`.
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Data/Decimal.md
  distribution/lib/Standard/Base/0.0.0-dev/docs/api/Data/XML.md
  distribution/lib/Standard/Base/0.0.0-dev/src/Data.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Decimal.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Interval.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Json/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Duration.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Period.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Time_Of_Day.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Data/XML.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Enso_Cloud/Enso_File.enso
  distribution/lib/Standard/Base/0.0.0-dev/src/Warning.enso
  distribution/lib/Standard/Database/0.0.0-dev/src/Connection/Database.enso
  distribution/lib/Standard/Google_Api/0.0.0-dev/src/Google_Analytics.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Extensions/Excel_Extensions.enso
  distribution/lib/Standard/Table/0.0.0-dev/src/Extensions/Table_Conversions.enso
  std-bits/base/src/main/java/org/enso/base/numeric/Decimal_Utils.java
  test/Base_Tests/src/Data/Decimal_Spec.enso
  test/Base_Tests/src/Data/Json_Spec.enso
  test/Base_Tests/src/Data/XML/XML_Spec.enso
  test/Table_Tests/src/In_Memory/Table_Conversion_Spec.enso
Labels: CI: Ready to merge, CI: No changelog needed, -libs-API-change-Base

#12679 getSourceSection and hasSourceSection must be consistent
  engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/Function.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicException.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/DebugLocalScope.java
Labels: CI: Ready to merge, CI: No changelog needed

#12654 Add Blame, redesign the Asset versions panel
  MODULE.bazel.lock
  app/common/src/services/Backend.ts
  app/common/src/text.ts
  app/common/src/text/english.json
  app/gui/src/dashboard/components/AriaComponents/Checkbox/Checkbox.stories.tsx
  app/gui/src/dashboard/components/AriaComponents/Text/Text.tsx
  app/gui/src/dashboard/components/Badge/Badge.tsx
  app/gui/src/dashboard/components/Icon/Icon.tsx
  app/gui/src/dashboard/components/ProfilePicture/ProfilePicture.stories.tsx
  app/gui/src/dashboard/components/ProfilePicture/ProfilePicture.tsx
  app/gui/src/dashboard/components/ProfilePicture/index.ts
  app/gui/src/dashboard/components/ProfilePicture/variants.ts
  app/gui/src/dashboard/components/Result.tsx
  app/gui/src/dashboard/components/Spinner.tsx
  app/gui/src/dashboard/components/patterns.ts
  app/gui/src/dashboard/hooks/backendHooks.ts
  app/gui/src/dashboard/layouts/AssetDiffView/AssetDiffView.tsx
  app/gui/src/dashboard/layouts/AssetDiffView/useFetchVersionContent.ts
  app/gui/src/dashboard/layouts/AssetPanel/components/AssetVersion.tsx
  app/gui/src/dashboard/layouts/AssetPanel/components/AssetVersions.tsx
  app/gui/src/dashboard/layouts/AssetPanel/components/useAssetVersions.ts
  app/gui/src/dashboard/layouts/Settings/OrganizationProfilePictureInput.tsx
  app/gui/src/dashboard/layouts/Settings/ProfilePictureInput.tsx
  app/gui/src/dashboard/layouts/Settings/Section.tsx
  app/gui/src/dashboard/layouts/Settings/Tab.tsx
  app/gui/src/dashboard/layouts/UserBar.tsx
  app/gui/src/dashboard/layouts/UserMenu.tsx
  app/gui/src/dashboard/services/LocalBackend.ts
  app/gui/src/dashboard/services/RemoteBackend.ts
  app/gui/src/dashboard/services/remoteBackendPaths.ts
Labels: CI: No changelog needed, g-dashboard
